// catchup 2026-09-14 第5组：天寿后3 + 指背5
module.exports=[
{cat:'fuzhu',slug:'ziwei-tianshou-zai-tianzhaigong',focus:'天寿在田宅宫',focusEn:'Tian Shou in the Property Palace',
 cnT:'天寿在田宅宫：家宅安稳家运长，安居守成',enT:'Tian Shou in the Property Palace: A Stable, Long-Blessed Home',
 cnD:'天寿在田宅宫多主家宅安稳、家运绵长，适合安居守成；重在用心经营、家人安康，置产走正规途径，稳的家最养人。',
 enD:'Tian Shou in the Property Palace suggests a stable home with long family fortune, suiting settled living. Care for it, keep family healthy and use formal channels for property.',
 cnL:'安稳的家是一切的底；家人安康、家运绵长，就是最大的福。',
 enL:'A stable home is the foundation; healthy family and long fortune are blessing.',
 cnA:'有人折腾家宅、不安于稳；星曜是倾向，置产以正规合同和专业意见为准。',
 enA:'Some unsettle the home; stars are tendency, while property relies on formal contracts and advice.',
 cnLog:['天寿在田宅宫，家宅安稳。','家运绵长、安居。','经营、安康、正规。','置产以正规合同和专业意见为准。'],
 enLog:['Tian Shou in Property means a stable home.','Long family fortune, settled.','Care, health, formal.','Rely on formal contracts and professional advice.'],
 cnStep:['安居守成','经营家宅、保安康','置产走正规途径','家人常聚','稳着打理','以家安为要'],
 enStep:['Settle and guard','Care for home and health','Formal property channels','Gather family','Manage steadily','Rest on a stable home'],
 cnMis:['折腾家宅','置产不正规','忽视安康'],
 enMis:['Unsettling the home','Property not formal','Neglecting health'],
 cnClose:'天寿在田宅宫，家宅安稳、家运长。安居守成、走正规路，家才是真港湾。',
 enClose:'Tian Shou in the Property Palace blesses a stable, long-fortuned home. Settle and use formal channels.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-fudegong',focus:'天寿在福德宫',focusEn:'Tian Shou in the Blessings Palace',
 cnT:'天寿在福德宫：心宽则寿长，知足从容养天年',enT:'Tian Shou in the Blessings Palace: A Broad Mind, Long Years',
 cnD:'天寿在福德宫多主心性宽厚、知足从容，精神安稳有助于长寿；重在养心、少计较，心宽一寸、寿延一分。',
 enD:'Tian Shou in the Blessings Palace suggests a broad, content mind whose steady spirit aids longevity. Nurture the mind and reckon less, for a wider heart adds years.',
 cnL:'长寿的人多半心宽、看得开；你少计较、多从容，日子又长又轻。',
 enL:'Long-lived people tend to be broad-minded; reckon less and stay poised.',
 cnA:'有人爱计较、放不下，精神紧绷；星曜是倾向，心宽是修来的。',
 enA:'Some reckon and cannot let go, holding tension; stars are tendency, while broad-mindedness is cultivated.',
 cnLog:['天寿在福德宫，心宽知足。','精神安稳助长寿。','养心、少计较。','倾向描述，非绝对定论。'],
 enLog:['Tian Shou in Blessings means a broad, content mind.','Steady spirit aids longevity.','Nurture mind, reckon less.','This is tendency, not an absolute verdict.'],
 cnStep:['遇事看开','知足少计较','养心安神','多从容、少焦虑','必要时寻求专业帮助','以心安为要'],
 enStep:['Let matters go','Stay content, reckon less','Nurture calm','Stay poised, less anxiety','Seek professional help when needed','Rest on calm'],
 cnMis:['爱计较','放不下、焦虑','心不宽'],
 enMis:['Reckoning','Cannot let go, anxious','Not broad-minded'],
 cnClose:'天寿在福德宫，心宽则寿长。知足、看开、少计较，养出从容天年。',
 enClose:'Tian Shou in the Blessings Palace connects a broad mind to long years. Stay content, let go and reckon less.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-fumugong',focus:'天寿在父母宫',focusEn:'Tian Shou in the Parents Palace',
 cnT:'天寿在父母宫：长辈安康长寿，孝敬陪伴惜福',enT:'Tian Shou in the Parents Palace: Healthy, Long-Lived Elders',
 cnD:'天寿在父母宫多主父母、长辈身体安康、有长寿福；重在多陪伴、关心健康、按时体检，长辈的长寿是全家的福。',
 enD:'Tian Shou in the Parents Palace suggests healthy elders with longevity blessing. Accompany, care for health and arrange check-ups, for elders long life is a family blessing.',
 cnL:'长辈安康长寿，是晚辈最大的福；你多陪伴、早上心，福才长久。',
 enL:'Healthy, long-lived elders are the youngs greatest blessing; accompany and care.',
 cnA:'有人疏于陪伴、忽视长辈健康；星曜是倾向，安康靠照护。',
 enA:'Some neglect presence and elders health; stars are tendency, while health rests on care.',
 cnLog:['天寿在父母宫，长辈安康长寿。','陪伴、关心、体检。','长寿是全家福。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Shou in Parents means healthy, long elders.','Accompany, care, check-ups.','Long life is family blessing.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['多陪伴长辈','关心健康、按时体检','不适及时就诊','规范用药','保持联系','以长辈安康为要'],
 enStep:['Accompany elders','Care for health, arrange check-ups','Seek timely care','Use medicine properly','Keep in touch','Rest on elder wellbeing'],
 cnMis:['疏于陪伴','忽视健康','体检不规律'],
 enMis:['Neglecting presence','Ignoring health','Irregular check-ups'],
 cnClose:'天寿在父母宫，长辈安康长寿是福。陪伴、照护、懂珍惜，全家才安心。',
 enClose:'Tian Shou in the Parents Palace blesses healthy, long elders. Accompany and care for peace of mind.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-minggong',focus:'指背在命宫',focusEn:'Zhi Bei in the Life Palace',
 cnT:'指背在命宫：易遭背后议论，光明磊落不传话',enT:'Zhi Bei in the Life Palace: Above Backbiting',
 cnD:'指背主背后是非，在命宫多主容易被人在背后议论、说闲话；重在行得正、坐得端，不传话、不内耗，清者自清，时间会说话。',
 enD:'Zhi Bei governs backbiting; in the Life Palace it suggests being talked about behind your back. Act upright, do not pass gossip or drain yourself, for clarity shows in time.',
 cnL:'背后的话你管不住，但自己正、不传、不理，它就伤不到你。',
 enL:'You cannot control behind-back words, but stay upright, do not pass or heed them.',
 cnA:'有人为闲话生气、到处辩白，反而越描越黑；星曜是倾向，立身靠端正。',
 enA:'Some anger at gossip and over-defend, making it worse; stars are tendency, while standing rests on uprightness.',
 cnLog:['指背主是非，命宫易被议论。','行得正、不传话。','不内耗、清自清。','倾向描述，非绝对定论。'],
 enLog:['Zhi Bei governs backbiting; in Life you are talked about.','Stay upright, do not pass gossip.','Do not drain yourself.','This is tendency, not an absolute verdict.'],
 cnStep:['行正坐端','不传话、不议论人','不为闲话内耗','专注做好自己','时间证明','以坦荡为要'],
 enStep:['Act upright','Do not pass gossip','Do not drain yourself on hearsay','Focus on yourself','Let time show','Rest on openness'],
 cnMis:['为闲话到处辩','传话、议论人','被是非内耗'],
 enMis:['Over-defending at gossip','Passing hearsay','Drained by backbiting'],
 cnClose:'指背在命宫，背后议论难免。光明磊落、不传话、不内耗，端正的人走得最稳。',
 enClose:'Zhi Bei in the Life Palace makes backbiting normal. Stay upright, do not pass gossip or drain yourself.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-xiongdigong',focus:'指背在兄弟宫',focusEn:'Zhi Bei in the Siblings Palace',
 cnT:'指背在兄弟宫：同辈间防闲话，坦诚不传话',enT:'Zhi Bei in the Siblings Palace: Openness Over Peer Gossip',
 cnD:'指背在兄弟宫多主兄弟姐妹、同辈之间易有背后闲话、小误会；重在当面说开、不传话挑拨，同辈相处坦荡最要紧。',
 enD:'Zhi Bei in the Siblings Palace suggests behind-back gossip and misunderstandings among peers. Talk face to face, do not pass or stir things, for openness matters.',
 cnL:'同辈的是非多是传话传出来的；有话当面讲、不背后说，关系才清爽。',
 enL:'Peer disputes often come through passed words; talk face to face.',
 cnA:'有人爱传话、在同辈间挑拨；星曜是倾向，相处靠坦荡。',
 enA:'Some pass words and stir peers; stars are tendency, while relating rests on openness.',
 cnLog:['指背在兄弟宫，同辈易闲话。','当面说开、不传话。','不挑拨、坦荡。','倾向描述，非绝对定论。'],
 enLog:['Zhi Bei in Siblings means peer gossip.','Talk face to face, do not pass.','Do not stir, stay open.','This is tendency, not an absolute verdict.'],
 cnStep:['有话当面沟通','不传话、不挑拨','误会及时解','珍惜同辈','不在背后议论','以和睦为要'],
 enStep:['Communicate face to face','Do not pass or stir','Resolve misunderstandings in time','Value peers','Do not talk behind backs','Rest on harmony'],
 cnMis:['传话挑拨','背后议论','不当面说'],
 enMis:['Passing, stirring','Talking behind backs','Not facing matters'],
 cnClose:'指背在兄弟宫，同辈闲话要防。当面说、不传话、不挑拨，关系才长久清爽。',
 enClose:'Zhi Bei in the Siblings Palace guards peer gossip. Talk face to face and do not pass or stir.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-fuqigong',focus:'指背在夫妻宫',focusEn:'Zhi Bei in the Spouse Palace',
 cnT:'指背在夫妻宫：感情防流言，彼此信任不传话',enT:'Zhi Bei in the Spouse Palace: Trust Over Outside Rumors',
 cnD:'指背在夫妻宫多主两人感情易受外部流言、旁人闲话干扰；重在彼此信任、有事内部说，不把外面的话带进家，信任是感情的底。',
 enD:'Zhi Bei in the Spouse Palace suggests love disturbed by outside rumors and hearsay. Trust one another, settle matters inside and do not bring outside words home.',
 cnL:'外面的闲话最会钻感情的缝；你俩一条心、不传不信，流言就没处落。',
 enL:'Outside hearsay seeks cracks in love; stay of one mind and do not pass or believe it.',
 cnA:'有人一听闲话就回家质问、伤信任；星曜是倾向，长久靠信任。',
 enA:'Some question a partner at hearsay, hurting trust; stars are tendency, while lasting love needs trust.',
 cnLog:['指背在夫妻宫，感情防流言。','彼此信任、内部说。','不带闲话回家。','倾向描述，非绝对定论。'],
 enLog:['Zhi Bei in Spouse means guarding rumors.','Trust, settle inside.','Do not bring hearsay home.','This is tendency, not an absolute verdict.'],
 cnStep:['彼此信任','有事内部沟通','不轻信外面闲话','不传话','共同对外','以信任为要'],
 enStep:['Trust one another','Settle matters inside','Do not believe outside hearsay','Do not pass words','Face outside together','Rest on trust'],
 cnMis:['听闲话质问','把流言带回家','缺信任'],
 enMis:['Questioning at hearsay','Bringing rumors home','Lacking trust'],
 cnClose:'指背在夫妻宫，感情要防流言。一条心、信任、不传话，家才不被闲话搅乱。',
 enClose:'Zhi Bei in the Spouse Palace guards love against rumors. Stay of one mind, trust and do not pass hearsay.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-zinvgong',focus:'指背在子女宫',focusEn:'Zhi Bei in the Children Palace',
 cnT:'指背在子女宫：孩子被议论，引导坦荡不传话',enT:'Zhi Bei in the Children Palace: Guiding a Child Above Gossip',
 cnD:'指背在子女宫多主孩子在学校、同伴中容易被议论或卷入小是非；重在引导孩子坦荡、不传话、被说时正确应对，也培养内心的稳。',
 enD:'Zhi Bei in the Children Palace suggests a child being talked about or caught in small disputes among peers. Guide openness, not passing words and proper responses, building inner steadiness.',
 cnL:'孩子被议论时，你教他坦荡、教他不传话，比替他出头更有用。',
 enL:'When a child is talked about, guide openness and not passing words, more than intervening.',
 cnA:'有人一听孩子被说就冲动找对方；星曜是倾向，教养靠引导。',
 enA:'Some impulsively confront when the child is discussed; stars are tendency, while parenting rests on guidance.',
 cnLog:['指背在子女宫，孩子被议论。','引导坦荡、不传话。','培养内心稳。','倾向描述，非绝对定论。'],
 enLog:['Zhi Bei in Children means a child talked about.','Guide openness, not passing words.','Build inner steadiness.','This is tendency, not an absolute verdict.'],
 cnStep:['引导孩子不传话','教他正确应对议论','培养坦荡和自信','与老师沟通','不冲动出头','以健康成长为要'],
 enStep:['Guide the child not to pass words','Teach responses to gossip','Build openness and confidence','Talk with teachers','Do not impulsively confront','Rest on healthy growth'],
 cnMis:['冲动找对方','不教方法','替孩子包办'],
 enMis:['Impulsively confronting','Not teaching methods','Taking over for the child'],
 cnClose:'指背在子女宫，孩子被议论难免。引导坦荡、不传话、立自信，比替他出头更养人。',
 enClose:'Zhi Bei in the Children Palace makes a child being discussed normal. Guide openness, not passing words and build confidence.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-caibogong',focus:'指背在财帛宫',focusEn:'Zhi Bei in the Wealth Palace',
 cnT:'指背在财帛宫：钱财防暗算骗局，守正不贪',enT:'Zhi Bei in the Wealth Palace: Guarding Against Fraud and Schemes',
 cnD:'指背在财帛宫多主钱财上要防暗算、骗局、背后做局；重在守正、不贪小便宜、不碰来路不明的“好事”，手续清楚。',
 enD:'Zhi Bei in the Wealth Palace suggests guarding money against schemes and fraud. Stay upright, do not chase small gains or shady good deals and keep paperwork clear.',
 cnL:'天上不掉馅饼，背后的“好事”多是局；你不贪、守正，骗子就没机会。',
 enL:'Free pies do not fall; behind-back good deals are schemes; do not be greedy.',
 cnA:'有人贪小便宜、信来路不明的机会；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some chase small gains and believe shady chances; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['指背在财帛宫，钱财防暗算。','守正、不贪小利。','手续清楚、远骗局。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Zhi Bei in Wealth means guarding schemes.','Upright, do not chase small gains.','Clear paperwork, avoid fraud.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['不贪小便宜','远离来路不明的机会','钱财手续清楚','重大决策咨询持牌专业人士','守正','以稳为要'],
 enStep:['Do not chase small gains','Avoid shady chances','Keep money paperwork clear','Consult licensed professionals for big decisions','Stay upright','Rest on steadiness'],
 cnMis:['贪小便宜','信骗局','手续不清'],
 enMis:['Chasing small gains','Believing fraud','Unclear paperwork'],
 cnClose:'指背在财帛宫，功课是「防暗算、守正、不贪」。远骗局、听专业人士，钱才守得住。',
 enClose:'Zhi Bei in the Wealth Palace calls for guarding schemes, staying upright and not being greedy. Avoid fraud and consult professionals.'}
];
