// catchup 2026-09-11 第1组：主星在疾厄宫 8（紫微/天机/太阳/武曲/天同/廉贞/天府/太阴）
module.exports=[
{cat:'zhuxing',slug:'ziwei-ziwei-zai-jiegong',focus:'紫微在疾厄宫',focusEn:'Zi Wei in the Health Palace',
 cnT:'紫微在疾厄宫：脾胃是重点，操劳应酬别过度',enT:'Zi Wei in the Health Palace: Digestion Takes Care',
 cnD:'紫微属土，在疾厄宫多指向脾胃、消化系统的负担；体质底子通常不弱，但容易因操劳、应酬、饮食不规律把肠胃拖出问题，重在有节律、别硬撑。',
 enD:'Zi Wei belongs to earth, and in the Health Palace it often points to strain on the spleen, stomach and digestion. The constitution is usually not weak, but overwork, social dining and irregular meals can wear the stomach and gut down; rhythm and not forcing through matter most.',
 cnL:'底子好不等于能一直造，肠胃像老实干活的伙计，平时不吭声，垮起来才提醒你。',
 enL:'A good base does not mean endless abuse; the stomach is like a quiet worker that only speaks up once it breaks down.',
 cnA:'有人见紫微在疾厄宫就当身体一定好，胡吃海熬；星曜是倾向，不是免死金牌，节律得自己守。',
 enA:'Some see Zi Wei in the Health Palace and assume perfect health, eating and staying up freely; stars show tendency, not a free pass, and rhythm is on you.',
 cnLog:['紫微属土，重点在脾胃与消化。','体质底子不弱，问题多来自过度。','操劳、应酬、饮食不规律是主因。','倾向非诊断，以正规就医为准。'],
 enLog:['Zi Wei is earth, focus on spleen, stomach and digestion.','The base is not weak; trouble mostly comes from excess.','Overwork, social dining and irregular meals are main causes.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['饮食定时定量，减少油腻应酬','别把操劳当常态，留出恢复','出现胃胀反酸早就医、不拖','规律作息养脾胃','体检关注胃肠指标','一切以医生面诊为准'],
 enStep:['Eat on schedule, cut greasy social meals','Do not make overwork normal; leave room to recover','See a doctor early for bloating or reflux, do not delay','Keep regular hours to nourish digestion','Check stomach and bowel markers in physicals','Always follow the doctor in person'],
 cnMis:['把紫微在疾厄宫当身体铁打','饮食作息无节制','有症状硬扛不就医'],
 enMis:['Taking Zi Wei in Health as an iron body','No restraint in diet and sleep','Toughing out symptoms without care'],
 cnClose:'紫微在疾厄宫，重点是「底子好也要守节律」。脾胃靠养、应酬有节，身体给的信号要当回事，正规就医别耽误。',
 enClose:'Zi Wei in the Health Palace means a good base still needs rhythm. Nourish digestion, keep social dining moderate, take body signals seriously and seek formal care without delay.'},

{cat:'zhuxing',slug:'ziwei-tianji-zai-jiegong',focus:'天机在疾厄宫',focusEn:'Tian Ji in the Health Palace',
 cnT:'天机在疾厄宫：肝胆神经偏敏感，想太多最伤身',enT:'Tian Ji in the Health Palace: Nerves and Liver Need Calm',
 cnD:'天机属木，在疾厄宫多指向肝胆气机与神经系统；人偏敏感、思虑重，容易失眠、紧张、肩颈紧，养身先养心、少内耗，比补什么都管用。',
 enD:'Tian Ji belongs to wood, and in the Health Palace it often points to liver-gallbladder qi and the nervous system. Sensitive and prone to overthinking, one may face insomnia, tension and tight shoulders and neck; calming the mind and cutting inner friction help more than any tonic.',
 cnL:'脑子像停不下来的齿轮，夜里还在转；齿轮也得上油、也得停，人也一样。',
 enL:'The mind is like gears that keep turning at night; gears need oil and rest, and so do people.',
 cnA:'有人靠补品安神却越补越烦，根上是思虑没放下；星曜提示的是调节方向，具体病症还得查。',
 enA:'Some rely on tonics to calm down yet grow more restless, the root being unresolved worry; stars point the way to adjust, while real symptoms need checking.',
 cnLog:['天机属木，重点在肝胆与神经。','思虑过度易失眠、紧张、肩颈紧。','养身先养心，减少内耗。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Ji is wood, focus on liver-gallbladder and nerves.','Overthinking easily brings insomnia, tension and tight neck.','Calm the mind first to nourish the body.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['固定作息，给大脑下班时间','用散步、呼吸放松神经','减少睡前刷手机和思虑','长期失眠焦虑及时就医','关注肝胆相关检查','以医生评估为准'],
 enStep:['Keep fixed hours, give the brain time off','Use walks and breathing to relax nerves','Cut phone use and worry before sleep','Seek timely care for long insomnia or anxiety','Pay attention to liver checks','Follow the doctor assessment'],
 cnMis:['只补身不调心','把失眠紧张当小事长期拖','靠安神补品替代就医'],
 enMis:['Tonifying the body without calming the mind','Letting insomnia and tension drag on','Using calming tonics instead of seeing a doctor'],
 cnClose:'天机在疾厄宫，关键在「少思少虑、神经松下来」。作息规律、心有出口，反复不适应尽早查，别自己扛。',
 enClose:'Tian Ji in the Health Palace hinges on less worry and looser nerves. Keep regular hours, give the mind an outlet, and check recurring discomfort early instead of carrying it alone.'},

{cat:'zhuxing',slug:'ziwei-taiyang-zai-jiegong',focus:'太阳在疾厄宫',focusEn:'Tai Yang in the Health Palace',
 cnT:'太阳在疾厄宫：心火上炎要留意，血压眼睛多关照',enT:'Tai Yang in the Health Palace: Heart Fire, Pressure and Eyes',
 cnD:'太阳属火，在疾厄宫多指向心火、血压、心脑血管与眼睛；容易头痛、眼干、上火，重在别熬夜动怒、清淡饮食、定期量血压，信号别忽视。',
 enD:'Tai Yang belongs to fire, and in the Health Palace it often points to heart fire, blood pressure, cardiovascular-cerebral vessels and the eyes. Headaches, dry eyes and internal heat are common; avoid staying up and anger, eat lightly, check pressure regularly and do not ignore signals.',
 cnL:'太阳像正午的火，火太旺没处散，就往头上、眼睛上走；给火留个出口，人就清爽。',
 enL:'Tai Yang is like midday fire; with nowhere to go, excess heat rises to the head and eyes; give the fire an outlet and the body clears.',
 cnA:'有人把反复头痛眼胀当疲劳，拖到血压高才重视；星曜是提醒，心脑血管的事更要讲证据、看医生。',
 enA:'Some treat recurring headaches and eye pressure as fatigue until blood pressure rises; stars are reminders, and cardiovascular matters demand evidence and a doctor.',
 cnLog:['太阳属火，重点在心火、血压、眼睛。','易头痛、眼干、上火。','少熬夜动怒，清淡饮食。','倾向非诊断，以正规就医为准。'],
 enLog:['Tai Yang is fire, focus on heart fire, pressure and eyes.','Headaches, dry eyes and heat are common.','Avoid late nights and anger, eat lightly.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['不熬夜，给心火降温','定期监测血压','用眼有度，眼干眼早就医','饮食清淡、少酒','胸闷头痛及时就诊','以医生检查为准'],
 enStep:['Do not stay up; bring heart fire down','Monitor blood pressure regularly','Use eyes moderately, seek early care for dryness','Eat lightly, limit alcohol','Seek prompt care for chest tightness or headache','Follow medical checks'],
 cnMis:['熬夜动怒不节制','忽视血压和眼部信号','把心脑血管不适当累了'],
 enMis:['No restraint in late nights and anger','Ignoring pressure and eye signals','Taking cardiovascular discomfort as mere fatigue'],
 cnClose:'太阳在疾厄宫，要在「防火上炎」上下功夫。血压常测、眼睛爱护、作息不熬，异常早就医，心脑血管的事拖不得。',
 enClose:'Tai Yang in the Health Palace calls for preventing rising fire. Check pressure often, care for the eyes, avoid late nights and seek early care; cardiovascular matters cannot wait.'},

{cat:'zhuxing',slug:'ziwei-wuqu-zai-jiegong',focus:'武曲在疾厄宫',focusEn:'Wu Qu in the Health Palace',
 cnT:'武曲在疾厄宫：呼吸道与牙齿偏弱，金属外伤要当心',enT:'Wu Qu in the Health Palace: Respiratory Tract, Teeth and Injury',
 cnD:'武曲属金，在疾厄宫多指向肺、呼吸道、牙齿与鼻腔，也提示留意金属、利器之伤；换季注意防护、口腔卫生勤做，运动劳作防磕碰，有外伤及时处理。',
 enD:'Wu Qu belongs to metal, and in the Health Palace it often points to the lungs, respiratory tract, teeth and nose, and also advises care with metal and sharp-object injury. Protect yourself at season changes, keep up oral care, prevent bumps during work or exercise and treat wounds promptly.',
 cnL:'金对应着呼吸这扇门，门没护好，外邪先从这里进；天冷添衣、入口的卫生，都是给门加栓。',
 enL:'Metal corresponds to the gateway of breathing; unguarded, external ills enter first. Warm clothing in cold and good oral hygiene bolt that door.',
 cnA:'有人把久咳、牙痛当上火自己吃药，结果耽误；星曜给倾向，呼吸和外伤的问题要让专业的人看。',
 enA:'Some treat a long cough or toothache as heat and self-medicate, causing delay; stars give tendency, while respiratory and injury issues need professionals.',
 cnLog:['武曲属金，重点在肺、呼吸道、牙齿。','留意金属利器与磕碰外伤。','换季防护，口腔卫生。','倾向非诊断，以正规就医为准。'],
 enLog:['Wu Qu is metal, focus on lungs, respiratory tract and teeth.','Mind metal, sharp objects and bump injuries.','Protect at season changes, keep oral hygiene.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['换季注意保暖、防呼吸道感染','做好口腔卫生、定期看牙','劳作运动注意防金属利器伤','咳嗽不愈及时就诊','外伤及时清创处理','以医生判断为准'],
 enStep:['Keep warm at season changes, prevent respiratory infection','Maintain oral hygiene, see the dentist regularly','Guard against metal and sharp injury in work and sport','Seek care for a cough that will not clear','Clean and treat wounds promptly','Follow the doctor judgment'],
 cnMis:['忽视呼吸道和牙齿的反复问题','劳作不防外伤','久咳牙痛自行乱吃药'],
 enMis:['Ignoring recurring respiratory and dental issues','Not guarding against injury in work','Self-medicating a long cough or toothache'],
 cnClose:'武曲在疾厄宫，护好「呼吸道这扇门」是首位。换季有防、牙齿勤查、外伤当心，不适应早就医、勿乱用药。',
 enClose:'Wu Qu in the Health Palace puts guarding the respiratory gateway first. Prevent at season changes, check teeth, mind injury and seek early care rather than self-medicating.'},

{cat:'zhuxing',slug:'ziwei-tiantong-zai-jiegong',focus:'天同在疾厄宫',focusEn:'Tian Tong in the Health Palace',
 cnT:'天同在疾厄宫：水湿代谢偏慢，泌尿与糖分多留意',enT:'Tian Tong in the Health Palace: Water Metabolism, Urinary and Sugar',
 cnD:'天同属水，在疾厄宫多指向泌尿、肾与膀胱、水湿和糖分代谢；体质偏虚、易水肿乏力，重在适度运动、少甜少凉、别久坐，代谢相关指标定期查。',
 enD:'Tian Tong belongs to water, and in the Health Palace it often points to the urinary system, kidneys and bladder, water-dampness and sugar metabolism. The constitution tends to be deficient, prone to swelling and fatigue; exercise moderately, cut sweets and cold, avoid long sitting and check metabolic markers regularly.',
 cnL:'水要流动才清，老堵着不动就生湿、就肿；人也得动起来，水才走得顺。',
 enL:'Water stays clear only when moving; blocked, it breeds dampness and swelling; people too must move for water to flow.',
 cnA:'有人把水肿、易累当体虚猛补，反而加重湿气；星曜提示方向，泌尿代谢的毛病要靠检查说话。',
 enA:'Some treat swelling and fatigue as deficiency and tonify hard, worsening dampness; stars point direction, while urinary and metabolic ills rely on tests.',
 cnLog:['天同属水，重点在泌尿、肾、水湿代谢。','体质偏虚，易水肿乏力。','适度运动，少甜少凉、不久坐。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Tong is water, focus on urinary, kidneys and water metabolism.','The constitution tends deficient, prone to swelling and fatigue.','Exercise moderately, cut sweets and cold, avoid long sitting.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['适度运动、促进水液代谢','少甜食冷饮，饮食清淡','避免久坐，作息规律','水肿尿异常及时就医','关注血糖、肾功能检查','以医生评估为准'],
 enStep:['Exercise moderately to promote fluid metabolism','Cut sweets and cold drinks, eat lightly','Avoid long sitting, keep regular hours','Seek care for swelling or abnormal urine','Watch blood sugar and kidney function','Follow the doctor assessment'],
 cnMis:['把水肿乏力一律当虚来补','久坐不动、甜凉不忌','泌尿异常不检查'],
 enMis:['Treating all swelling and fatigue as deficiency to tonify','Long sitting with no restraint in sweets and cold','Not checking urinary abnormalities'],
 cnClose:'天同在疾厄宫，重在「让水动起来」。运动有常、少甜少凉，水肿尿异早就医，代谢指标定期查、别盲目补。',
 enClose:'Tian Tong in the Health Palace focuses on getting water moving. Exercise regularly, cut sweets and cold, seek early care for swelling or abnormal urine and check metabolism instead of tonifying blindly.'},

{cat:'zhuxing',slug:'ziwei-lianzhen-zai-jiegong',focus:'廉贞在疾厄宫',focusEn:'Lian Zhen in the Health Palace',
 cnT:'廉贞在疾厄宫：血液炎症要当心，起病急时别犹豫',enT:'Lian Zhen in the Health Palace: Blood, Inflammation and Acute Onset',
 cnD:'廉贞属火，在疾厄宫多指向血液、心火与急性炎症，也提示皮肤、血压方面；平时清淡作息、少燥，遇到突发高热、剧痛等急症要立即就医，别观望。',
 enD:'Lian Zhen belongs to fire, and in the Health Palace it often points to blood, heart fire and acute inflammation, also the skin and blood pressure. Keep a light diet and calm routine; for emergencies such as sudden high fever or severe pain, seek care at once without waiting.',
 cnL:'火性子起病像一阵急风，来得快；急风来了别想着扛，赶紧找对人处理最要紧。',
 enL:'A fire nature falls ill like a sudden gust, arriving fast; when it comes, do not think of enduring it, get the right help fast.',
 cnA:'有人遇到急性炎症还想偏方拖一晚，风险很大；星曜是倾向，急症和血液问题绝不能凭感觉。',
 enA:'Some facing acute inflammation try folk remedies overnight, which is risky; stars are tendency, and emergencies and blood issues must never rest on feeling.',
 cnLog:['廉贞属火，重点在血液、心火、急性炎症。','留意皮肤与血压。','清淡少燥，作息平稳。','急症立即就医，以正规医疗为准。'],
 enLog:['Lian Zhen is fire, focus on blood, heart fire and acute inflammation.','Mind the skin and blood pressure.','Eat light and calm, keep steady hours.','For emergencies seek care at once; rely on formal medicine.'],
 cnStep:['饮食清淡、少辛辣燥热','规律作息、稳定情绪血压','注意皮肤异常','突发高热剧痛立即急诊','关注血液相关检查','一切以医生为准'],
 enStep:['Eat light, cut spicy and drying food','Keep regular hours, steady mood and pressure','Watch skin abnormalities','Go to emergency for sudden fever or severe pain','Pay attention to blood tests','Always follow the doctor'],
 cnMis:['急性起病还观望拖延','重口味、情绪火躁不调','把血液皮肤信号当小事'],
 enMis:['Waiting and delaying at acute onset','Heavy diet and unchecked fiery mood','Taking blood and skin signals lightly'],
 cnClose:'廉贞在疾厄宫，平日「少燥多清淡」，急症来时「当机立断就医」。血液炎症不凭感觉，突发情况一刻都别拖。',
 enClose:'Lian Zhen in the Health Palace means less heat and lighter meals daily, and decisive care when emergencies strike. Blood and inflammation do not rest on feeling; never delay sudden cases.'},

{cat:'zhuxing',slug:'ziwei-tianfu-zai-jiegong',focus:'天府在疾厄宫',focusEn:'Tian Fu in the Health Palace',
 cnT:'天府在疾厄宫：胃口好是把双刃剑，吃多了脾胃受累',enT:'Tian Fu in the Health Palace: A Good Appetite Can Overload',
 cnD:'天府属土，在疾厄宫同样主脾胃，且多胃口好、吸收强；体质较稳，但管不住嘴就容易过食、积食、体重与血糖走高，重在七分饱、均衡、规律，别恃稳而纵。',
 enD:'Tian Fu belongs to earth, and in the Health Palace it also governs the spleen and stomach, often with a strong appetite and absorption; the constitution is steady, but an unchecked mouth leads to overeating, stagnation, weight and blood-sugar rises. Eat to seventy percent, keep balanced and regular, and do not indulge because you feel stable.',
 cnL:'仓库装得下不代表该装满，老堆到顶，库门都要被撑坏；肚子这个仓库也一样。',
 enL:'Being able to fill the storehouse does not mean it should be full; stacked to the top, even its doors strain; the body storehouse is the same.',
 cnA:'有人觉得体质稳就放开吃，等指标异常才收；星曜给倾向，脾胃代谢仍要以检查为准。',
 enA:'Some feel steady and eat freely, only reining in when markers turn abnormal; stars give tendency, while digestion and metabolism still rely on tests.',
 cnLog:['天府属土，重点在脾胃，胃口好。','体质稳，风险在过食与积食。','七分饱、均衡规律。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Fu is earth, focus on spleen and stomach, good appetite.','Steady constitution, risk in overeating and stagnation.','Seventy percent full, balanced and regular.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['每餐七分饱、不暴饮暴食','饮食均衡、控制体重','规律进餐、少吃夜宵','积食腹胀早就医','关注血糖血脂体重','以医生评估为准'],
 enStep:['Eat to seventy percent, avoid binges','Keep a balanced diet, control weight','Eat regularly, limit late-night food','Seek early care for stagnation and bloating','Watch blood sugar, lipids and weight','Follow the doctor assessment'],
 cnMis:['恃体质稳而放开吃','经常吃撑、夜宵不断','体重血糖走高也不查'],
 enMis:['Indulging because the constitution feels steady','Often overeating with constant late-night food','Not checking rising weight and sugar'],
 cnClose:'天府在疾厄宫，稳是稳，但要防「病从口入、积于脾胃」。七分饱、勤称重、指标定期查，异常早就医。',
 enClose:'Tian Fu in the Health Palace is steady, yet guard against ills entering by the mouth and settling in digestion. Eat moderately, weigh yourself, check markers and seek early care for abnormalities.'},

{cat:'zhuxing',slug:'ziwei-taiyin-zai-jiegong',focus:'太阴在疾厄宫',focusEn:'Tai Yin in the Health Palace',
 cnT:'太阴在疾厄宫：阴虚内分泌偏敏感，睡眠妇科多关照',enT:'Tai Yin in the Health Palace: Yin Deficiency, Hormones, Sleep',
 cnD:'太阴属水，在疾厄宫多指向肾阴、内分泌、妇科与睡眠、眼睛；易阴虚燥热、月经或睡眠失调，重在别熬夜耗阴、情绪平稳，妇科与内分泌异常要专科就诊。',
 enD:'Tai Yin belongs to water, and in the Health Palace it often points to kidney yin, hormones, gynecology, sleep and the eyes. Yin deficiency with heat, menstrual or sleep disturbance are common; avoid staying up which consumes yin, keep emotions steady and seek specialist care for gynecological or hormonal abnormalities.',
 cnL:'月亮有盈亏，熬夜像整夜亮着灯不让月落；灯老不灭，阴分就一点点被耗干。',
 enL:'The moon waxes and wanes; staying up is like keeping lights on all night; with the lights never off, yin is drained bit by bit.',
 cnA:'有人把月经紊乱、长期失眠当压力大硬扛；星曜是倾向，妇科内分泌的事要专科、要看检查。',
 enA:'Some treat menstrual disorder and long insomnia as stress and endure; stars are tendency, while gynecology and hormones need specialists and tests.',
 cnLog:['太阴属水，重点在肾阴、内分泌、妇科睡眠。','易阴虚燥热、月经或睡眠失调。','不熬夜耗阴，情绪平稳。','倾向非诊断，以正规就医为准。'],
 enLog:['Tai Yin is water, focus on kidney yin, hormones, gynecology and sleep.','Prone to yin-deficiency heat, menstrual or sleep disturbance.','Do not stay up consuming yin, keep emotions steady.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['不熬夜、养阴护睡眠','情绪平稳、减少焦虑','妇科内分泌异常专科就诊','眼干燥热适当调理','关注激素与妇科检查','以医生判断为准'],
 enStep:['Do not stay up, nourish yin and protect sleep','Keep emotions steady, reduce anxiety','See specialists for gynecological or hormonal ills','Manage dry eyes and heat appropriately','Watch hormonal and gynecological checks','Follow the doctor judgment'],
 cnMis:['长期熬夜耗阴','妇科内分泌异常硬扛不就诊','把失眠月经问题一律当压力'],
 enMis:['Long-term staying up consumes yin','Enduring gynecological or hormonal ills without care','Treating all insomnia and menstrual issues as stress'],
 cnClose:'太阴在疾厄宫，重在「养阴、不熬夜」。睡眠护好、情绪平稳，妇科内分泌有异常早看专科，别自己扛、别乱调。',
 enClose:'Tai Yin in the Health Palace focuses on nourishing yin and avoiding late nights. Protect sleep, steady emotions and see specialists early for gynecological or hormonal ills rather than enduring or self-adjusting.'}
];
