// catchup 2026-09-16 第4组：吊客8宫（夫妻/子女/财帛/疾厄/迁移/仆役/官禄/田宅）
module.exports=[
{cat:'fuzhu',slug:'ziwei-tiaoke-zai-fuqigong',focus:'吊客在夫妻宫',focusEn:'Diao Ke in the Spouse Palace',
 cnT:'吊客在夫妻宫：患难见真情，一起面对忧愁',enT:'Diao Ke in the Spouse Palace: Facing Sorrow Together',
 cnD:'吊客在夫妻宫多主两人会一起面对家中丧亡、忧愁等难关；重在不各自扛、彼此陪伴，患难与共反而让感情更深。',
 enD:'Diao Ke in the Spouse Palace suggests couples facing family loss and sorrow together. Do not bear apart, accompany one another, for shared adversity deepens love.',
 cnL:'难过的日子有人一起扛，就没那么黑；夫妻本是同林，患难更要一起飞。',
 enL:'Sorrow shared is less dark; partners stand together in adversity.',
 cnA:'有人遇事各自飞、或互相埋怨；星曜是倾向，患难靠经营。',
 enA:'Some scatter or blame in trouble; stars are tendency, while adversity needs care.',
 cnLog:['吊客在夫妻宫，共面对丧忧。','陪伴、不各自扛。','患难深情。','倾向描述，非绝对定论。'],
 enLog:['Diao Ke in Spouse means facing sorrow together.','Accompany, not apart.','Adversity deepens love.','This is tendency, not an absolute verdict.'],
 cnStep:['难关一起面对','陪伴安慰对方','不埋怨、不各自','好好告别','珍惜当下','以相守为要'],
 enStep:['Face passes together','Comfort one another','No blame, not apart','Say proper farewells','Cherish the present','Rest on staying together'],
 cnMis:['各自飞','互相埋怨','缺陪伴'],
 enMis:['Scattering','Blaming','Lacking presence'],
 cnClose:'吊客在夫妻宫，患难要一起面对。陪伴、珍惜、不埋怨，患难更见真情。',
 enClose:'Diao Ke in the Spouse Palace calls for facing sorrow together. Accompany and cherish.'},

{cat:'fuzhu',slug:'ziwei-tiaoke-zai-zinvgong',focus:'吊客在子女宫',focusEn:'Diao Ke in the Children Palace',
 cnT:'吊客在子女宫：教孩子面对离别，温柔陪伴',enT:'Diao Ke in the Children Palace: Gently Teaching Loss',
 cnD:'吊客在子女宫多主需引导孩子面对离别、失去（如宠物、亲人）；重在温柔解释、允许哀伤，培养孩子健康的生死观。',
 enD:'Diao Ke in the Children Palace suggests guiding a child through loss, such as a pet or relative. Explain gently and allow grief, building a healthy view of life and loss.',
 cnL:'孩子第一次面对失去，最需要你在身边；不回避、不吓唬，温柔讲清楚。',
 enL:'A child first loss needs you present; do not avoid or frighten, explain gently.',
 cnA:'有人对孩子隐瞒、或敷衍；星曜是倾向，教育靠陪伴。',
 enA:'Some hide it from the child or brush it off; stars are tendency, while teaching needs presence.',
 cnLog:['吊客在子女宫，教孩子面对失去。','温柔解释、允许哀伤。','健康生死观。','倾向描述，非绝对定论。'],
 enLog:['Diao Ke in Children means teaching loss.','Explain gently, allow grief.','Healthy view of life.','This is tendency, not an absolute verdict.'],
 cnStep:['用孩子能懂的话解释','允许他表达难过','陪伴、不催促','一起做告别','给安全感','以安心为要'],
 enStep:['Explain in words the child understands','Allow sadness','Accompany, do not rush','Say farewell together','Give security','Rest on calm'],
 cnMis:['隐瞒敷衍','孩子难过不陪伴','吓唬'],
 enMis:['Hiding, brushing off','Not present in grief','Frightening'],
 cnClose:'吊客在子女宫，教孩子面对离别。温柔、陪伴、允许哀伤，是给孩子一生的功课。',
 enClose:'Diao Ke in the Children Palace calls for gently teaching loss. Explain and accompany.'},

{cat:'fuzhu',slug:'ziwei-tiaoke-zai-caibogong',focus:'吊客在财帛宫',focusEn:'Diao Ke in the Wealth Palace',
 cnT:'吊客在财帛宫：丧吊有礼金支出，量力规划不攀比',enT:'Diao Ke in the Wealth Palace: Planning for Rites Within Means',
 cnD:'吊客在财帛宫多主因红白事、丧吊有礼金往来、意外支出；重在量力而行、不攀比礼金，人情往来记账清楚。',
 enD:'Diao Ke in the Wealth Palace suggests gifts and expenses around rites and mourning. Spend within means, do not compete on gifts and keep these courtesy accounts clear.',
 cnL:'人情礼金是往来，不是攀比；量力、记账，情分到了就好。',
 enL:'Rite gifts are reciprocity, not competition; measure and record.',
 cnA:'有人为面子打肿脸、攀比礼金；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some overspend for face and compete; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['吊客在财帛宫，丧吊礼金支出。','量力、不攀比。','记账清楚。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Diao Ke in Wealth means rite expenses.','Within means, no competition.','Keep accounts clear.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['人情往来量力','不攀比礼金','记账、留预算','不打肿脸','重大决策咨询持牌专业人士','以稳为要'],
 enStep:['Spend within means','No competing on gifts','Record, budget','No overspending for face','Consult licensed professionals','Rest on steadiness'],
 cnMis:['攀比礼金','为面子超支','不记账'],
 enMis:['Competing on gifts','Overspending for face','Not recording'],
 cnClose:'吊客在财帛宫，丧吊有礼金支出。量力、不攀比、记账，人情才不变成负担。',
 enClose:'Diao Ke in the Wealth Palace calls for rite spending within means. No competition and keep accounts clear.'},

{cat:'fuzhu',slug:'ziwei-tiaoke-zai-jiegong',focus:'吊客在疾厄宫',focusEn:'Diao Ke in the Health Palace',
 cnT:'吊客在疾厄宫：忧愁易伤身，调节情绪早就医',enT:'Diao Ke in the Health Palace: Easing Sorrow for Health',
 cnD:'吊客在疾厄宫多主忧愁、悲伤容易影响身体（睡眠、食欲等）；重在及时疏导情绪、规律生活，身体不适正规就医。',
 enD:'Diao Ke in the Health Palace suggests sorrow affecting sleep and appetite. Channel emotion, live regularly and seek formal care for discomfort.',
 cnL:'悲伤久了身体会替你扛；情绪疏导好，身体才不被拖垮。',
 enL:'Long sorrow is borne by the body; channel emotion for health.',
 cnA:'有人压着悲伤、不疏导；星曜是倾向，健康以正规就医为准。',
 enA:'Some suppress sorrow; stars are tendency, while health relies on formal care.',
 cnLog:['吊客在疾厄宫，忧愁伤身。','疏导情绪、规律生活。','早就医。','倾向非诊断，以正规就医为准。'],
 enLog:['Diao Ke in Health means sorrow harming body.','Channel emotion, live regularly.','Early care.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['悲伤及时疏导','规律作息饮食','不适及时就诊','找人倾诉','必要时寻求专业帮助','以健康为要'],
 enStep:['Channel grief','Regular hours and diet','Seek timely care','Talk to someone','Seek professional help when needed','Rest on health'],
 cnMis:['压悲伤','不疏导','忽视身体信号'],
 enMis:['Suppressing sorrow','Not channeling','Ignoring body signals'],
 cnClose:'吊客在疾厄宫，忧愁易伤身。疏导情绪、早就医，别让悲伤拖垮身体。',
 enClose:'Diao Ke in the Health Palace calls for easing sorrow. Channel emotion and seek early care.'},

{cat:'fuzhu',slug:'ziwei-tiaoke-zai-qianyi',focus:'吊客在迁移宫',focusEn:'Diao Ke in the Travel Palace',
 cnT:'吊客在迁移宫：外出或遇丧吊，冷静面对重安全',enT:'Diao Ke in the Travel Palace: Calm Away, Mind Safety',
 cnD:'吊客在迁移宫多主外出、远行可能遇到丧吊场合或心情低落；重在冷静应对、行程别太赶、注意安全。',
 enD:'Diao Ke in the Travel Palace suggests mourning occasions or low mood away. Stay calm, do not overpack and mind safety.',
 cnL:'出门遇到事别慌，稳住、安全第一。',
 enL:'Do not panic away; stay calm, safety first.',
 cnA:'有人遇状况慌乱；星曜是倾向，平安靠稳。',
 enA:'Some panic at matters; stars are tendency, while safety rests on steadiness.',
 cnLog:['吊客在迁移宫，外出遇丧忧。','冷静、重安全。','行程留余。','倾向描述，非绝对定论。'],
 enLog:['Diao Ke in Travel means mourning away.','Calm, mind safety.','Leave margin.','This is tendency, not an absolute verdict.'],
 cnStep:['遇状况冷静','行程别太赶','注意安全','备常用药','保持联系','以平安为要'],
 enStep:['Stay calm in trouble','Do not overpack','Mind safety','Carry basic medicines','Keep in touch','Rest on safe travel'],
 cnMis:['慌乱','行程太赶','不重安全'],
 enMis:['Panic','Schedules too packed','Ignoring safety'],
 cnClose:'吊客在迁移宫，外出冷静、重安全。稳住、留余，路才平安。',
 enClose:'Diao Ke in the Travel Palace calls for calm and safety away. Stay steady with margin.'},

{cat:'fuzhu',slug:'ziwei-tiaoke-zai-puyigong',focus:'吊客在仆役宫',focusEn:'Diao Ke in the Friends Palace',
 cnT:'吊客在仆役宫：朋友有丧多陪伴，患难见交情',enT:'Diao Ke in the Friends Palace: Presence for Friends Loss',
 cnD:'吊客在仆役宫多主朋友、部属遇到丧亡，需要你陪伴；重在及时到场、帮实际事务，不围观不传播。',
 enD:'Diao Ke in the Friends Palace suggests friends facing loss and needing presence. Show up, help practically and do not gossip.',
 cnL:'朋友难时你在，比平时千句热络都强。',
 enL:'Presence in friends hardship beats a thousand casual words.',
 cnA:'有人躲开、或围观；星曜是倾向，交情靠患难。',
 enA:'Some avoid or crowd; stars are tendency, while bonds show in adversity.',
 cnLog:['吊客在仆役宫，朋友有丧。','陪伴、帮实事。','不围观传播。','倾向描述，非绝对定论。'],
 enLog:['Diao Ke in Friends means friends loss.','Presence, practical help.','No gossip.','This is tendency, not an absolute verdict.'],
 cnStep:['及时到场','帮实际事务','安静陪伴','尊重对方','不传播','以长久为要'],
 enStep:['Show up in time','Help practically','Accompany quietly','Respect them','No gossip','Rest on lasting bonds'],
 cnMis:['躲开','围观传播','说空话'],
 enMis:['Avoiding','Gossip, crowding','Empty words'],
 cnClose:'吊客在仆役宫，朋友有丧要陪伴。到场、帮实事，患难见真情。',
 enClose:'Diao Ke in the Friends Palace calls for presence in friends loss. Show up and help practically.'},

{cat:'fuzhu',slug:'ziwei-tiaoke-zai-guanlugong',focus:'吊客在官禄宫',focusEn:'Diao Ke in the Career Palace',
 cnT:'吊客在官禄宫：工作遇丧忧，稳住专业、会调节',enT:'Diao Ke in the Career Palace: Steady Through Work Sorrow',
 cnD:'吊客在官禄宫多主工作中遇到丧吊、忧愁或相关事务，情绪易影响工作；重在专业稳住、公私分明、及时调节。',
 enD:'Diao Ke in the Career Palace suggests mourning or sorrow affecting work. Stay professional, separate public and private and adjust in time.',
 cnL:'难过的事不带到工作、工作的专业不被情绪拖垮，是成熟。',
 enL:'Not bringing sorrow to work and keeping professional is maturity.',
 cnA:'有人情绪用事、耽误工作；星曜是倾向，事业靠稳。',
 enA:'Some act emotionally and delay work; stars are tendency, while career rests on steadiness.',
 cnLog:['吊客在官禄宫，工作遇丧忧。','专业稳住、公私分。','及时调节。','倾向描述，非绝对定论。'],
 enLog:['Diao Ke in Career means work sorrow.','Professional, separate matters.','Adjust in time.','This is tendency, not an absolute verdict.'],
 cnStep:['工作专业稳住','情绪及时疏导','公私分明','必要时请假处理','照顾好自己','以稳为要'],
 enStep:['Stay professional','Channel emotion','Separate matters','Take leave if needed','Care for yourself','Rest on steadiness'],
 cnMis:['情绪用事','公私不分','不调节'],
 enMis:['Emotional reactions','No boundaries','Not adjusting'],
 cnClose:'吊客在官禄宫，工作遇丧忧要稳。专业、疏导、公私分明，事业才不被拖。',
 enClose:'Diao Ke in the Career Palace calls for steady professionalism. Channel emotion and keep boundaries.'},

{cat:'fuzhu',slug:'ziwei-tiaoke-zai-tianzhaigong',focus:'吊客在田宅宫',focusEn:'Diao Ke in the Property Palace',
 cnT:'吊客在田宅宫：家宅或有丧亡，节哀治家惜团聚',enT:'Diao Ke in the Property Palace: Grieving, Then Gathering',
 cnD:'吊客在田宅宫多主家中会面对老人离世等大事；重在好好尽孝送终、节哀顺变，之后更珍惜家人团聚。',
 enD:'Diao Ke in the Property Palace suggests the family facing an elder passing. Be filial through the end, grieve and recover, then cherish gatherings more.',
 cnL:'尽孝要趁早，离别要好好告别；经历过失去，更懂一家人在一起的好。',
 enL:'Be filial early and farewell well; loss teaches the value of gathering.',
 cnA:'有人子欲养而亲不待、或陷悲伤；星曜是倾向，家和靠珍惜。',
 enA:'Some miss the time to be filial or stay in grief; stars are tendency, while harmony rests on cherishing.',
 cnLog:['吊客在田宅宫，家宅有丧。','尽孝送终、节哀。','珍惜团聚。','倾向描述，非绝对定论。'],
 enLog:['Diao Ke in Property means family loss.','Filial through the end, grieve.','Cherish gatherings.','This is tendency, not an absolute verdict.'],
 cnStep:['长辈在世多尽孝','好好告别','节哀、疏导','家人互相扶持','珍惜每次团聚','以家安为要'],
 enStep:['Be filial while elders live','Farewell well','Grieve, channel','Support one another','Cherish gatherings','Rest on a stable home'],
 cnMis:['尽孝不趁早','陷悲伤不疏导','忽视团聚'],
 enMis:['Not filial in time','Stuck in grief','Neglecting gatherings'],
 cnClose:'吊客在田宅宫，家有丧亡要尽孝、节哀。好好告别、珍惜团聚，家才长久。',
 enClose:'Diao Ke in the Property Palace calls for filial care and grief. Farewell well and cherish gatherings.'}
];
