// catchup 2026-09-12 第4组：天巫8宫（兄弟/夫妻/子女/财帛/疾厄/迁移/仆役/福德）
module.exports=[
{cat:'fuzhu',slug:'ziwei-tianwu-zai-xiongdigong',focus:'天巫在兄弟宫',focusEn:'Tian Wu in the Siblings Palace',
 cnT:'天巫在兄弟宫：手足同辈多提携，得同辈之助',enT:'Tian Wu in the Siblings Palace: Peers Who Lift You Up',
 cnD:'天巫主提携、机缘，在兄弟宫多主兄弟姐妹、同辈朋友中有人能提携你、给机会；重在珍惜同辈缘分、互相成就，机会来了也要自己接得住。',
 enD:'Tian Wu governs support and chance; in the Siblings Palace it suggests siblings or peers able to lift you and offer opportunity. Value peer bonds and help one another, and be ready to grasp chances.',
 cnL:'同辈里肯给你机会的人是贵人；可机会递过来，你得有本事接、也记得回报。',
 enL:'Peers who give chances are mentors; as a chance comes, be able to take it and remember to repay.',
 cnA:'有人只等同辈提携、自己不准备，机会也溜走；星曜是倾向，机缘要配实力。',
 enA:'Some wait for peers to lift them unprepared and chances pass; stars are tendency, while chance pairs with ability.',
 cnLog:['天巫主提携机缘，兄弟宫得同辈助。','有人给机会、能提携。','珍惜缘分、互相成就。','倾向描述，非绝对定论。'],
 enLog:['Tian Wu governs support; in Siblings peers help.','Someone offers chances and lifts you.','Value bonds, help one another.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜同辈贵人','自己练好本事、接得住机会','受人提携知回报','主动经营同辈关系','不坐等机会','以互相成就为要'],
 enStep:['Value peer mentors','Build skill, be ready to take chances','Repay support','Cultivate peer relations','Do not wait idly','Rest on mutual success'],
 cnMis:['只等提携、不准备','受助不回报','把同辈机会当必然'],
 enMis:['Waiting for support unprepared','Ungrateful for help','Taking peer chances as due'],
 cnClose:'天巫在兄弟宫，好在「同辈提携、机缘多」。珍惜、努力、懂回报，贵人缘才长久。',
 enClose:'Tian Wu in the Siblings Palace blesses supportive peers and chances. Value, strive and repay so mentor luck lasts.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-fuqigong',focus:'天巫在夫妻宫',focusEn:'Tian Wu in the Spouse Palace',
 cnT:'天巫在夫妻宫：伴侣多贵气有助，关系互相成全',enT:'Tian Wu in the Spouse Palace: A Supportive Partner',
 cnD:'天巫在夫妻宫多主伴侣有贵气、能在事业生活上给你助力，关系有共同成长的机缘；重在彼此感恩、互相成就，不把对方助力当理所当然。',
 enD:'Tian Wu in the Spouse Palace suggests a dignified partner able to support your work and life, with chances to grow together. Be grateful and help one another, not taking support for granted.',
 cnL:'好伴侣是彼此的贵人，你托我一把、我托你一把，两个人一起往上走。',
 enL:'Good partners are each others mentors; you lift me, I lift you and both rise together.',
 cnA:'有人把伴侣助力当本分、不感恩，缘分渐淡；星曜是倾向，长久靠双向成全。',
 enA:'Some take partner support as due without gratitude, thinning the bond; stars are tendency, while lasting love needs two-way care.',
 cnLog:['天巫在夫妻宫，伴侣有贵气、能助力。','有共同成长机缘。','彼此感恩、互相成就。','倾向描述，非绝对定论。'],
 enLog:['Tian Wu in Spouse means a dignified, supportive partner.','Chances to grow together.','Be grateful, help one another.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜伴侣的助力','共同成长、彼此成全','感恩对方付出','遇事商量、齐努力','不把助力当理所当然','以长久为要'],
 enStep:['Value partner support','Grow and succeed together','Be grateful for effort','Discuss matters, work together','Do not take support as due','Rest on lasting bonds'],
 cnMis:['把助力当本分','只受助、不付出','忽视共同成长'],
 enMis:['Taking support as due','Only receiving, not giving','Neglecting mutual growth'],
 cnClose:'天巫在夫妻宫，难得「伴侣有助、共同成长」。感恩、成全、齐努力，关系才长久。',
 enClose:'Tian Wu in the Spouse Palace offers a supportive partner and shared growth. Be grateful and help one another for a lasting bond.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-zinvgong',focus:'天巫在子女宫',focusEn:'Tian Wu in the Children Palace',
 cnT:'天巫在子女宫：子女多有出息，得长辈提携',enT:'Tian Wu in the Children Palace: Promising Children',
 cnD:'天巫在子女宫多主子女有出息、得师长贵人提携，发展有机缘；重在引导孩子感恩努力，机会面前有真本事，不靠侥幸。',
 enD:'Tian Wu in the Children Palace suggests promising children lifted by teachers and mentors, with chances to develop. Guide them to be grateful and hardworking, with real skill when chances come rather than relying on luck.',
 cnL:'孩子有贵人是好事，但贵人扶的是肯努力的人；你教他踏实，机缘才用得上。',
 enL:'Mentors for a child are good, but they lift the hardworking; teach groundedness so chances serve.',
 cnA:'有人见孩子有机缘就放松要求、坐等提携；星曜是倾向，出息靠努力。',
 enA:'Some relax demands at the child chances and wait to be lifted; stars are tendency, while promise comes from effort.',
 cnLog:['天巫在子女宫，子女有出息、得提携。','发展有机缘。','引导感恩努力、练真本事。','倾向描述，非绝对定论。'],
 enLog:['Tian Wu in Children means promising, supported children.','Chances to develop.','Guide gratitude and effort, build real skill.','This is tendency, not an absolute verdict.'],
 cnStep:['引导孩子努力','珍惜师长提携、教感恩','练好真本事','不坐等侥幸','以身作则','以成才为要'],
 enStep:['Guide the child to work hard','Value teachers, teach gratitude','Build real skill','Do not rely on luck','Lead by example','Rest on growth'],
 cnMis:['放松要求、坐等提携','孩子不努力、靠侥幸','忽视身教'],
 enMis:['Relaxing demands, waiting to be lifted','Not working hard, relying on luck','Neglecting example'],
 cnClose:'天巫在子女宫，孩子有贵人机缘，更要「努力配得上」。引导感恩、踏实，出息才守得住。',
 enClose:'Tian Wu in the Children Palace gives mentors and chances, but effort must match. Guide gratitude and groundedness so promise holds.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-caibogong',focus:'天巫在财帛宫',focusEn:'Tian Wu in the Wealth Palace',
 cnT:'天巫在财帛宫：易得馈赠遗产，守正理财不挥霍',enT:'Tian Wu in the Wealth Palace: Gifts and Inheritance, Wise Handling',
 cnD:'天巫在财帛宫多主有得长辈馈赠、遗产或意外机缘之财的机会；但这种钱更要守规矩、明手续，妥善打理、不挥霍。',
 enD:'Tian Wu in the Wealth Palace suggests chances of gifts, inheritance or unexpected money from elders. Such money calls even more for proper procedures and clear paperwork, handled well and not squandered.',
 cnL:'得来容易的钱最考验人，手续清楚、用得明白，才守得住这分机缘。',
 enL:'Easy money tests character; clear paperwork and wise use keep the chance secure.',
 cnA:'有人对馈赠遗产不走正规手续、或挥霍一空，反生纠纷；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some skip formal procedures for gifts or squander them, breeding disputes; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['天巫在财帛宫，有馈赠遗产机缘。','更要守规矩、明手续。','妥善打理、不挥霍。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Wu in Wealth means gift and inheritance chances.','Follow rules, keep clear paperwork.','Handle well, do not squander.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['馈赠遗产走正规法律手续','保留书面凭据','妥善打理、不挥霍','重大决策咨询专业人士','量力、守正','以稳妥为要'],
 enStep:['Use formal legal procedures for gifts and inheritance','Keep written records','Handle well, do not squander','Consult professionals for big decisions','Measure capacity, stay upright','Rest on steadiness'],
 cnMis:['不走正规手续','挥霍机缘之财','手续不清、生纠纷'],
 enMis:['Skipping formal procedures','Squandering chance money','Unclear paperwork, disputes'],
 cnClose:'天巫在财帛宫，有「馈赠遗产」机缘，但手续要正、钱要会守。走正规途径、听专业意见，才不辜负。',
 enClose:'Tian Wu in the Wealth Palace offers gift and inheritance chances, but keep procedures proper and money wise. Use formal channels and professional advice to do it justice.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-jiegong',focus:'天巫在疾厄宫',focusEn:'Tian Wu in the Health Palace',
 cnT:'天巫在疾厄宫：病中有救应延寿，信医配合治疗',enT:'Tian Wu in the Health Palace: Rescue and Longevity Through Care',
 cnD:'天巫在疾厄宫多主生病时有救应、易遇良医、有延寿之机；但救应要靠规范治疗。重在早就医、信专业，配合治疗与复查。',
 enD:'Tian Wu in the Health Palace suggests rescue during illness, meeting good doctors and chances of longevity. Rescue relies on proper treatment. Seek early care, trust professionals and cooperate with treatment and rechecks.',
 cnL:'病里的延寿之机，常藏在你肯不肯好好治里；遇到良医就配合，别辜负。',
 enL:'The chance of longevity in illness often lies in willingness to treat; meet good doctors and cooperate.',
 cnA:'有人仗有救应拖延、不规范治，结果反复；星曜是倾向，健康以正规就医为准。',
 enA:'Some delay on rescue without proper treatment and relapse; stars are tendency, while health relies on formal care.',
 cnLog:['天巫在疾厄宫，病有救应、延寿。','救应靠规范治疗。','早就医、信专业。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Wu in Health means rescue and longevity.','Rescue relies on proper treatment.','Seek early care, trust professionals.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['生病及时就诊','珍惜良医、配合治疗','规范用药、按时复查','不拖延、不自作主张','作息养身','以医生方案为准'],
 enStep:['Seek timely care','Value good doctors, cooperate','Treat properly, recheck on time','Do not delay or decide alone','Nourish with routines','Follow the doctor plan'],
 cnMis:['仗救应拖延','不配合治疗','把延寿当必然'],
 enMis:['Delaying on rescue','Not cooperating with treatment','Taking longevity as certain'],
 cnClose:'天巫在疾厄宫，是「病有救、可延寿」的好兆头。早就医、信专业、配合治，救应才守得住。',
 enClose:'Tian Wu in the Health Palace is a good sign of rescue and longevity. Seek early care, trust professionals and cooperate so rescue holds.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-qianyi',focus:'天巫在迁移宫',focusEn:'Tian Wu in the Travel Palace',
 cnT:'天巫在迁移宫：外出多遇贵人提携，远行有机缘',enT:'Tian Wu in the Travel Palace: Mentors and Chances Away',
 cnD:'天巫在迁移宫多主外出、远行时遇贵人、得提携机会，利外出发展；重在礼貌待人、自己有备，机缘来了接得住。',
 enD:'Tian Wu in the Travel Palace suggests mentors and chances away from home, favoring outside development. Be polite and prepared so you can grasp chances.',
 cnL:'远行的机缘常给有准备、有礼数的人；你把本事和礼貌带上，路就宽。',
 enL:'Travel chances often go to the prepared and polite; bring skill and courtesy and the road widens.',
 cnA:'有人外出不准备、坐等机缘，结果错过；星曜是倾向，机缘配实力。',
 enA:'Some travel unprepared, waiting for chances and miss them; stars are tendency, while chance pairs with ability.',
 cnLog:['天巫在迁移宫，外出遇贵人、得提携。','利远行发展。','礼貌有备、接得住。','倾向描述，非绝对定论。'],
 enLog:['Tian Wu in Travel means mentors and chances away.','Favors outside growth.','Be polite and prepared.','This is tendency, not an absolute verdict.'],
 cnStep:['外出礼貌待人','提前准备、练本事','珍惜贵人机缘','机会来主动把握','不坐等','以远行有成为要'],
 enStep:['Be polite away','Prepare, build skill','Value mentors and chances','Grasp opportunities','Do not wait idly','Rest on successful travel'],
 cnMis:['不准备、坐等机缘','外出失礼','机缘来却接不住'],
 enMis:['Unprepared, waiting for chances','Rude away','Unable to grasp chances'],
 cnClose:'天巫在迁移宫，外出「有贵人、有机缘」。礼貌、有备、肯努力，路才走得宽。',
 enClose:'Tian Wu in the Travel Palace blesses mentors and chances away. Be polite, prepared and hardworking so the road widens.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-puyigong',focus:'天巫在仆役宫',focusEn:'Tian Wu in the Friends Palace',
 cnT:'天巫在仆役宫：朋友中多贵人，得人提携机会',enT:'Tian Wu in the Friends Palace: Mentors Among Friends',
 cnD:'天巫在仆役宫多主朋友、部属中有贵人，能给你提携和机会；重在真诚交友、知恩图报，自己也要配得上机缘。',
 enD:'Tian Wu in the Friends Palace suggests mentors among friends and staff who offer support and chances. Make friends sincerely, repay kindness and be worthy of chances.',
 cnL:'朋友里的贵人，多是被你的真诚和上进吸引来的；你是什么样的人，就遇到什么样的缘。',
 enL:'Mentors among friends are drawn by sincerity and drive; who you are sets the chances you meet.',
 cnA:'有人只攀贵人、不真诚，缘也留不住；星曜是倾向，贵人靠人品。',
 enA:'Some court mentors without sincerity and bonds do not hold; stars are tendency, while mentors come through character.',
 cnLog:['天巫在仆役宫，朋友中有贵人。','得提携机会。','真诚交友、知恩图报。','倾向描述，非绝对定论。'],
 enLog:['Tian Wu in Friends means mentors among friends.','You receive support and chances.','Be sincere, repay kindness.','This is tendency, not an absolute verdict.'],
 cnStep:['真诚交朋友','珍惜贵人、知回报','提升自己、配得上','守边界','不攀附','以长久信任为要'],
 enStep:['Make friends sincerely','Value mentors, repay kindness','Improve yourself, be worthy','Keep boundaries','Do not fawn','Rest on long trust'],
 cnMis:['只攀附、不真诚','受助不回报','自己不努力'],
 enMis:['Fawning without sincerity','Ungrateful for help','Not striving'],
 cnClose:'天巫在仆役宫，朋友中有贵人是好事。真诚、上进、懂回报，贵人缘才长久。',
 enClose:'Tian Wu in the Friends Palace blesses mentors among friends. Be sincere, driven and grateful so mentor luck lasts.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-fudegong',focus:'天巫在福德宫',focusEn:'Tian Wu in the Blessings Palace',
 cnT:'天巫在福德宫：好玄学哲思，精神有寄托',enT:'Tian Wu in the Blessings Palace: Spiritual Seeking and Inner Anchor',
 cnD:'天巫在福德宫多主对玄学、哲思、信仰有缘分，精神世界有寄托、容易心安；但别脱离现实。重在把精神追求落到日常，有所信也有所为。',
 enD:'Tian Wu in the Blessings Palace suggests an affinity for spirituality, philosophy and faith, with inner anchoring and easy peace. Do not leave reality. Land spiritual seeking in daily life, believing and also doing.',
 cnL:'精神有寄托是福，但鸟飞再远也得有棵树落回；日常和行动，就是那棵树。',
 enL:'Inner anchoring is a blessing, but a far-flying bird needs a tree to return to; daily life and action are that tree.',
 cnA:'有人沉迷玄思、脱离现实生活；星曜是倾向，寄托要与现实平衡。',
 enA:'Some sink into spiritual thought apart from life; stars are tendency, while anchoring must balance reality.',
 cnLog:['天巫在福德宫，好玄学信仰。','精神有寄托、易心安。','落到日常、有所为。','倾向描述，非绝对定论。'],
 enLog:['Tian Wu in Blessings means affinity for spirituality and faith.','Inner anchor, easy peace.','Land in daily life, also do.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜精神上的缘分','把追求落到日常行动','经营现实关系生活','有所信、也有所为','多接触自然','以踏实心安为要'],
 enStep:['Value spiritual affinity','Land seeking in daily action','Cultivate real relations and life','Believe and also do','Engage with nature','Rest on grounded peace'],
 cnMis:['沉迷玄思、脱离现实','只追求、不行动','忽视现实生活'],
 enMis:['Sinking into spirituality apart from life','Only seeking, not acting','Neglecting real life'],
 cnClose:'天巫在福德宫，与玄学有缘是福，但要「寄托落回现实」。有所信、有所为，心安才踏实。',
 enClose:'Tian Wu in the Blessings Palace gives spiritual affinity, but anchor it in reality. Believe and do, for grounded peace.'}
];
