// catchup 2026-09-16 第2组：天厨后3 + 天德前5
module.exports=[
{cat:'fuzhu',slug:'ziwei-tianchu-zai-tianzhaigong',focus:'天厨在田宅宫',focusEn:'Tian Chu in the Property Palace',
 cnT:'天厨在田宅宫：厨房兴旺家有烟火，居家有口福',enT:'Tian Chu in the Property Palace: A Warm, Well-Fed Home',
 cnD:'天厨在田宅宫多主家里厨房兴旺、烟火气足、家人有口福；重在用心经营餐桌、吃得健康，置产走正规途径，热饭热菜家才暖。',
 enD:'Tian Chu in the Property Palace suggests a warm kitchen and well-fed family. Tend the table and eat healthy, using formal channels for property.',
 cnL:'家里有烟火、灶上有热饭，这是最实在的福气。',
 enL:'A warm kitchen with hot food is the most solid blessing.',
 cnA:'有人家不开火、少了烟火；星曜是倾向，置产以正规合同和专业意见为准。',
 enA:'Some never cook and lose warmth; stars are tendency, while property relies on formal contracts and advice.',
 cnLog:['天厨在田宅宫，厨房兴旺。','家人有口福、烟火足。','吃得健康、置产正规。','置产以正规合同和专业意见为准。'],
 enLog:['Tian Chu in Property means a warm kitchen.','Well-fed family.','Eat healthy, formal property.','Rely on formal contracts and professional advice.'],
 cnStep:['经营家里餐桌','厨房保持烟火','饮食健康','置产走正规途径','家人共餐','以家暖为要'],
 enStep:['Tend the family table','Keep the kitchen warm','Eat healthy','Formal property channels','Share meals','Rest on warmth'],
 cnMis:['不开火','置产不正规','忽视饮食健康'],
 enMis:['Not cooking','Property not formal','Ignoring healthy food'],
 cnClose:'天厨在田宅宫，厨房兴旺、家有口福。用心餐桌、走正规路，烟火气里见家暖。',
 enClose:'Tian Chu in the Property Palace blesses a warm, well-fed home. Tend the table and use formal channels.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-fudegong',focus:'天厨在福德宫',focusEn:'Tian Chu in the Blessings Palace',
 cnT:'天厨在福德宫：懂得享受生活，知足常乐会品味',enT:'Tian Chu in the Blessings Palace: Savoring Life with Contentment',
 cnD:'天厨在福德宫多主会享受生活、有品味、知足常乐，一顿好饭就能开心；重在把享受建立在力所能及上，不贪多、不铺张。',
 enD:'Tian Chu in the Blessings Palace suggests enjoying life with taste and contentment, happy with a good meal. Base enjoyment on what you can afford, not greedy or wasteful.',
 cnL:'会生活的人，不是吃得多贵，而是尝得出滋味、懂得知足。',
 enL:'Those who live well eat not the costliest but taste and know contentment.',
 cnA:'有人追求享受超了能力、反成负担；星曜是倾向，知足才真乐。',
 enA:'Some seek pleasure beyond means and grow burdened; stars are tendency, while contentment is true joy.',
 cnLog:['天厨在福德宫，会享受、有品味。','知足常乐。','享受力所能、不铺张。','倾向描述，非绝对定论。'],
 enLog:['Tian Chu in Blessings means enjoying with taste.','Contentment.','Pleasure within means, not wasteful.','This is tendency, not an absolute verdict.'],
 cnStep:['培养生活品味','知足常乐','享受力所能及','不铺张攀比','用心一日三餐','以心安为要'],
 enStep:['Cultivate taste','Stay content','Enjoy within means','No waste or comparing','Mind daily meals','Rest on calm'],
 cnMis:['享受超能力','铺张攀比','不知足'],
 enMis:['Pleasure beyond means','Wasteful, comparing','Not content'],
 cnClose:'天厨在福德宫，会品味生活是好事。知足、力所能及、不铺张，享受才长久安心。',
 enClose:'Tian Chu in the Blessings Palace blesses savoring life. Stay content and within means for lasting joy.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-fumugong',focus:'天厨在父母宫',focusEn:'Tian Chu in the Parents Palace',
 cnT:'天厨在父母宫：长辈有口福，孝敬餐桌暖亲情',enT:'Tian Chu in the Parents Palace: Caring for Elders Through Food',
 cnD:'天厨在父母宫多主父母、长辈有口福、爱吃也能吃；重在多陪长辈吃饭、照顾饮食健康，一顿亲手做的饭最尽孝。',
 enD:'Tian Chu in the Parents Palace suggests elders who enjoy food. Share meals and care for their diet, for a home-cooked meal is filial care.',
 cnL:'长辈盼的不是多贵的东西，是一顿有你在的热饭。',
 enL:'Elders wish not costly things but a hot meal with you present.',
 cnA:'有人疏于陪长辈吃饭、只顾忙；星曜是倾向，亲情靠陪伴。',
 enA:'Some neglect meals with elders; stars are tendency, while kinship needs presence.',
 cnLog:['天厨在父母宫，长辈有口福。','陪饭、照顾饮食。','亲手做饭尽孝。','倾向描述，非绝对定论。'],
 enLog:['Tian Chu in Parents means elders who enjoy food.','Share meals, care for diet.','Cook for them.','This is tendency, not an absolute verdict.'],
 cnStep:['多陪长辈吃饭','照顾饮食健康','亲手做顿饭','记得口味喜好','不冷落','以家和为要'],
 enStep:['Share meals with elders','Care for diet','Cook for them','Remember their tastes','Do not neglect','Rest on harmony'],
 cnMis:['疏于陪饭','只顾忙','不照顾饮食'],
 enMis:['Neglecting meals','Only busy','Not caring for diet'],
 cnClose:'天厨在父母宫，长辈有口福。多陪饭、照顾健康，烟火气里尽孝心。',
 enClose:'Tian Chu in the Parents Palace blesses elders who enjoy food. Share meals and care for their diet.'},

{cat:'fuzhu',slug:'ziwei-tiande-zai-minggong',focus:'天德在命宫',focusEn:'Tian De in the Life Palace',
 cnT:'天德在命宫：为人有德，逢凶多化吉贵人助',enT:'Tian De in the Life Palace: A Virtuous Nature, Misfortune Eased',
 cnD:'天德主德行、贵人，在命宫多主为人厚道、有德行，遇难关常有人帮、能转圜；重在修德、知恩图报，德不孤、必有邻。',
 enD:'Tian De governs virtue and mentors; in the Life Palace it suggests a kind, virtuous nature with help at hard passes. Cultivate virtue and be grateful, for the virtuous are not alone.',
 cnL:'做人厚道，路自然宽；你修的德，都会在难处回来帮你。',
 enL:'Be kind and the road widens; the virtue you cultivate returns to help.',
 cnA:'有人只算计、不修德；星曜是倾向，化吉靠德行配努力。',
 enA:'Some only scheme and neglect virtue; stars are tendency, while ease rests on virtue and effort.',
 cnLog:['天德主德行，命宫为人厚道。','逢凶化吉、贵人助。','修德、感恩。','倾向描述，非绝对定论。'],
 enLog:['Tian De governs virtue; in Life a kind nature.','Misfortune eased, mentors help.','Cultivate virtue, be grateful.','This is tendency, not an absolute verdict.'],
 cnStep:['做人厚道','珍惜贵人、知回报','遇事肯求助','修德于日常','自己努力','以坦荡为要'],
 enStep:['Be kind','Value mentors, repay kindness','Ask help when needed','Cultivate virtue daily','Strive','Rest on openness'],
 cnMis:['只算计、不修德','受助不感恩','把化吉当必然'],
 enMis:['Scheming, no virtue','Ungrateful','Taking ease as certain'],
 cnClose:'天德在命宫，为人有德、逢凶化吉。修德、感恩、肯努力，路才宽。',
 enClose:'Tian De in the Life Palace blesses a virtuous nature and eased misfortune. Cultivate, be grateful and strive.'},

{cat:'fuzhu',slug:'ziwei-tiande-zai-xiongdigong',focus:'天德在兄弟宫',focusEn:'Tian De in the Siblings Palace',
 cnT:'天德在兄弟宫：同辈多贵人，以德相交互助',enT:'Tian De in the Siblings Palace: Virtuous Peers Who Help',
 cnD:'天德在兄弟宫多主兄弟姐妹、同辈中有厚道贵人，难处能帮你；重在以德相交、互相帮衬、知感恩。',
 enD:'Tian De in the Siblings Palace suggests kind mentors among peers who help at hard passes. Relate through virtue, help one another and be grateful.',
 cnL:'以德相交的同辈，处得久、靠得住。',
 enL:'Peers joined through virtue are long and reliable.',
 cnA:'有人只利益相交、不长久；星曜是倾向，情分靠德行。',
 enA:'Some relate only through interest, not lasting; stars are tendency, while affection needs virtue.',
 cnLog:['天德在兄弟宫，同辈贵人。','以德相交、互助。','知感恩。','倾向描述，非绝对定论。'],
 enLog:['Tian De in Siblings means virtuous peers.','Relate through virtue, help.','Be grateful.','This is tendency, not an absolute verdict.'],
 cnStep:['以德交同辈','互相帮衬','珍惜贵人','知回报','常走动','以长久为要'],
 enStep:['Relate through virtue','Help one another','Value mentors','Repay kindness','Stay in touch','Rest on lasting bonds'],
 cnMis:['利益相交','不互助','不感恩'],
 enMis:['Interest-based relating','Not helping','Not grateful'],
 cnClose:'天德在兄弟宫，同辈多贵人。以德相交、懂感恩，情分才长久。',
 enClose:'Tian De in the Siblings Palace blesses virtuous peers. Relate through virtue and be grateful.'},

{cat:'fuzhu',slug:'ziwei-tiande-zai-fuqigong',focus:'天德在夫妻宫',focusEn:'Tian De in the Spouse Palace',
 cnT:'天德在夫妻宫：伴侣有德，逢难化吉共经营',enT:'Tian De in the Spouse Palace: A Virtuous Partner, Hard Passes Eased',
 cnD:'天德在夫妻宫多主伴侣厚道有德，两人遇难关常能转圜；重在以德相待、共同经营、彼此感恩。',
 enD:'Tian De in the Spouse Palace suggests a kind, virtuous partner with hard passes turning around. Treat through virtue, build together and be grateful.',
 cnL:'有德的伴侣，是来一起渡日子的；互相厚道，坎就好迈。',
 enL:'A virtuous partner shares life; mutual kindness eases passes.',
 cnA:'有人有转机也不珍惜、计较；星曜是倾向，长久靠德行经营。',
 enA:'Some do not value chances and reckon; stars are tendency, while lasting love needs virtue.',
 cnLog:['天德在夫妻宫，伴侣有德。','逢难化吉。','以德相待、感恩。','倾向描述，非绝对定论。'],
 enLog:['Tian De in Spouse means a virtuous partner.','Hard passes ease.','Treat through virtue, be grateful.','This is tendency, not an absolute verdict.'],
 cnStep:['以德相待','共同经营','遇难关一起迈','彼此感恩','及时修复','以长久为要'],
 enStep:['Treat through virtue','Build together','Cross passes together','Be grateful','Repair in time','Rest on lasting bonds'],
 cnMis:['不珍惜转机','计较','缺德行'],
 enMis:['Not valuing chances','Reckoning','Lacking virtue'],
 cnClose:'天德在夫妻宫，伴侣有德、逢难化吉。厚道相待、共同经营，感情才长久。',
 enClose:'Tian De in the Spouse Palace blesses a virtuous partner and eased passes. Treat kindly and build together.'},

{cat:'fuzhu',slug:'ziwei-tiande-zai-zinvgong',focus:'天德在子女宫',focusEn:'Tian De in the Children Palace',
 cnT:'天德在子女宫：孩子养德，逢凶化吉善引导',enT:'Tian De in the Children Palace: Raising a Virtuous Child',
 cnD:'天德在子女宫多主孩子本性厚道、有德行，遇小难常化险；重在引导品德、教感恩，德行为一生打底。',
 enD:'Tian De in the Children Palace suggests a kind, virtuous child whose small passes ease. Guide character and teach gratitude, for virtue grounds a life.',
 cnL:'教孩子成才先教做人；德行厚，路自然稳。',
 enL:'Teach character before achievement; virtue steadies the road.',
 cnA:'有人只重成绩、不养德；星曜是倾向，教养靠引导。',
 enA:'Some only value grades and neglect virtue; stars are tendency, while parenting needs guidance.',
 cnLog:['天德在子女宫，孩子本性厚道。','小难化险。','养德、教感恩。','倾向描述，非绝对定论。'],
 enLog:['Tian De in Children means a kind nature.','Small passes ease.','Build virtue, teach gratitude.','This is tendency, not an absolute verdict.'],
 cnStep:['引导孩子品德','教感恩分享','以身作则','不唯成绩','陪伴成长','以成才为要'],
 enStep:['Guide character','Teach gratitude and sharing','Lead by example','Not grades only','Accompany growth','Rest on growth'],
 cnMis:['只重成绩','不养德','忽视身教'],
 enMis:['Grades only','No virtue','Neglecting example'],
 cnClose:'天德在子女宫，孩子本性厚道。养德、教感恩，好品德是一生的底气。',
 enClose:'Tian De in the Children Palace blesses a kind child. Build virtue and teach gratitude as lifelong grounding.'},

{cat:'fuzhu',slug:'ziwei-tiande-zai-caibogong',focus:'天德在财帛宫',focusEn:'Tian De in the Wealth Palace',
 cnT:'天德在财帛宫：以德求财，贵人助财守正道',enT:'Tian De in the Wealth Palace: Earning Through Virtue',
 cnD:'天德在财帛宫多主求财路上有厚道贵人、逢难有解；重在以德求财、不赚亏心钱，守正才长久。',
 enD:'Tian De in the Wealth Palace suggests kind mentors in earning and troubles easing. Seek money through virtue, not dishonest gains, for the upright last.',
 cnL:'财从正道来，才守得稳；你不亏心，贵人也愿帮。',
 enL:'Money from the upright path holds; do not be dishonest and mentors help.',
 cnA:'有人见利忘义、赚快钱；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some forget virtue for profit and chase quick money; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['天德在财帛宫，求财有贵人。','以德求财、不亏心。','守正长久。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian De in Wealth means mentors in earning.','Seek through virtue, honest.','Upright, lasting.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['守正求财','珍惜贵人','不赚亏心钱','留应急钱','咨询持牌专业人士','以稳为要'],
 enStep:['Earn upright','Value mentors','No dishonest gains','Keep emergency money','Consult licensed professionals','Rest on steadiness'],
 cnMis:['见利忘义','赚快钱','不守正'],
 enMis:['Forgetting virtue for profit','Quick money','Not upright'],
 cnClose:'天德在财帛宫，以德求财、贵人助。守正、不亏心，财源才长久。',
 enClose:'Tian De in the Wealth Palace blesses earning through virtue and mentors. Stay upright and honest.'}
];
