// catchup 2026-09-14 第1组：天煞前8宫
module.exports=[
{cat:'fuzhu',slug:'ziwei-tiansha-zai-minggong',focus:'天煞在命宫',focusEn:'Tian Sha in the Life Palace',
 cnT:'天煞在命宫：性子刚烈易招损，收敛锋芒少硬碰',enT:'Tian Sha in the Life Palace: Softening a Sharp Temper',
 cnD:'天煞主刚烈、刑伤，在命宫多主性格直、脾气硬、爱硬碰硬，容易得罪人或招外伤；重在收敛锋芒、遇事缓一缓，刚强用在难处而不是争一时。',
 enD:'Tian Sha governs severity; in the Life Palace it suggests a direct, hard temper that easily offends or invites injury. Soften the edge, pause in trouble and use strength at hard passes rather than for the moment.',
 cnL:'牙尖嘴利赢一时、输掉人心；你把刚用在扛事上、把柔留给待人，路才宽。',
 enL:'A sharp tongue wins the moment but loses hearts; use strength to carry matters and softness with people.',
 cnA:'有人以刚烈为荣、处处不让人；星曜是倾向，收敛是修养也是自保。',
 enA:'Some take pride in harshness and never yield; stars are tendency, while restraint is cultivation and self-care.',
 cnLog:['天煞主刚烈刑伤，命宫性子硬。','易得罪人、招外伤。','收敛锋芒、缓一缓。','倾向描述，非绝对定论。'],
 enLog:['Tian Sha governs severity; in Life a hard temper.','Easy to offend or invite injury.','Soften edge, pause.','This is tendency, not an absolute verdict.'],
 cnStep:['遇事先缓三秒','收敛争胜的脾气','刚强用在扛难上','待人留余地','注意安全防外伤','以稳为要'],
 enStep:['Pause three seconds in trouble','Restrain the competitive temper','Use strength to carry hardship','Leave room with people','Mind safety, prevent injury','Rest on steadiness'],
 cnMis:['以刚烈为荣','处处硬碰','脾气上来不顾后果'],
 enMis:['Proud of harshness','Confronting everywhere','Temper ignoring consequences'],
 cnClose:'天煞在命宫，功课是「收敛刚烈、少硬碰」。把刚用对地方，待人留柔，路才宽、伤才少。',
 enClose:'Tian Sha in the Life Palace calls for softening harshness and fewer confrontations. Use strength well and keep softness so the road widens.'},

{cat:'fuzhu',slug:'ziwei-tiansha-zai-xiongdigong',focus:'天煞在兄弟宫',focusEn:'Tian Sha in the Siblings Palace',
 cnT:'天煞在兄弟宫：手足性子刚，多包容少硬碰',enT:'Tian Sha in the Siblings Palace: Patient with Strong-Willed Kin',
 cnD:'天煞在兄弟宫多主兄弟姐妹、同辈性子刚烈，相处易有硬碰硬的摩擦；重在多包容、不较真，手足之间争赢了也伤感情。',
 enD:'Tian Sha in the Siblings Palace suggests strong-willed siblings and peers with easy confrontations. Be tolerant, do not be stubborn, for winning against kin hurts affection.',
 cnL:'手足是讲情不是讲理的地方；你让一步、不硬碰，那份血缘才暖。',
 enL:'Kinship is for affection not argument; yield and do not confront.',
 cnA:'有人和刚烈手足较真到底；星曜是倾向，情分靠包容。',
 enA:'Some are stubborn with strong-willed kin; stars are tendency, while affection needs tolerance.',
 cnLog:['天煞在兄弟宫，手足性子刚。','易硬碰摩擦。','多包容、不较真。','倾向描述，非绝对定论。'],
 enLog:['Tian Sha in Siblings means strong-willed kin.','Easy confrontations.','Be tolerant, not stubborn.','This is tendency, not an absolute verdict.'],
 cnStep:['手足相处多包容','不硬碰、不较真','有摩擦主动缓和','珍惜血缘','换位体谅','以家和为要'],
 enStep:['Be tolerant with kin','Do not confront or be stubborn','Smooth friction actively','Value blood ties','Understand one another','Rest on family harmony'],
 cnMis:['和手足较真','硬碰到底','缺包容'],
 enMis:['Stubborn with kin','Confronting to the end','Lacking tolerance'],
 cnClose:'天煞在兄弟宫，与刚烈手足相处贵在「包容、不硬碰」。让一步，手足情才不受伤。',
 enClose:'Tian Sha in the Siblings Palace calls for tolerance and no confrontation with strong-willed kin. Yield so affection is not hurt.'},

{cat:'fuzhu',slug:'ziwei-tiansha-zai-fuqigong',focus:'天煞在夫妻宫',focusEn:'Tian Sha in the Spouse Palace',
 cnT:'天煞在夫妻宫：两个硬脾气，学会低头柔和',enT:'Tian Sha in the Spouse Palace: Two Strong Wills, Learning to Yield',
 cnD:'天煞在夫妻宫多主两人性子都偏硬、容易硬碰硬、吵起来互不相让；重在总有一方先软下来，不争输赢，柔和是长久的智慧。',
 enD:'Tian Sha in the Spouse Palace suggests two hard tempers that confront and refuse to yield in fights. One side softening first, not fighting to win, for softness is lasting wisdom.',
 cnL:'夫妻争赢了道理、家就冷了；肯先低头的那个，不是输，是更懂珍惜。',
 enL:'Winning reason cools the home; the one yielding first is not losing but cherishing.',
 cnA:'有人冷战到底、谁也不低头；星曜是倾向，长久靠柔和。',
 enA:'Some hold cold wars and neither yields; stars are tendency, while lasting love needs softness.',
 cnLog:['天煞在夫妻宫，性子硬、易硬碰。','需一方先软。','不争输赢、柔和。','倾向描述，非绝对定论。'],
 enLog:['Tian Sha in Spouse means hard tempers, confrontation.','One side softens first.','Do not fight to win, be soft.','This is tendency, not an absolute verdict.'],
 cnStep:['吵架不冷战到底','肯先低头示好','不争口舌输赢','语气温和','共同经营','以长久为要'],
 enStep:['Do not hold cold wars','Yield and show goodwill first','Do not fight to win','Keep tone gentle','Build together','Rest on lasting bonds'],
 cnMis:['冷战到底','互不相让','硬碰硬'],
 enMis:['Cold wars to the end','Neither yielding','Confronting hard'],
 cnClose:'天煞在夫妻宫，两个硬脾气更要「会低头、肯柔和」。不争输赢，感情才长久。',
 enClose:'Tian Sha in the Spouse Palace calls for yielding and softness with two hard tempers. Do not fight to win for lasting love.'},

{cat:'fuzhu',slug:'ziwei-tiansha-zai-zinvgong',focus:'天煞在子女宫',focusEn:'Tian Sha in the Children Palace',
 cnT:'天煞在子女宫：孩子性子刚烈，因势利导少压制',enT:'Tian Sha in the Children Palace: Guiding a Strong-Willed Child',
 cnD:'天煞在子女宫多主孩子性子刚烈、有主见、吃软不吃硬；重在因势利导、少硬碰压制，把那股刚引向正处，硬碰只会激起逆反。',
 enD:'Tian Sha in the Children Palace suggests a strong-willed, opinioned child who responds to softness not force. Guide the edge to good use rather than suppressing, for confrontation stirs rebellion.',
 cnL:'刚烈的孩子像没驯服的小马，越打越拧；你顺着劲引、立好规矩，那股刚能成大器。',
 enL:'A strong-willed child is like an unbroken colt, firmer under force; guide with the grain and set rules.',
 cnA:'有人对刚烈孩子非打即骂、硬碰硬；星曜是倾向，教养要讲方法。',
 enA:'Some punish and confront a strong-willed child; stars are tendency, while parenting needs method.',
 cnLog:['天煞在子女宫，孩子性子刚。','吃软不吃硬。','因势利导、少压制。','倾向描述，非绝对定论。'],
 enLog:['Tian Sha in Children means a strong-willed child.','Responds to softness not force.','Guide the edge, suppress less.','This is tendency, not an absolute verdict.'],
 cnStep:['遇事多商量、少命令','立规矩、讲原因','把刚烈引向运动/担当','不硬碰、不打骂','以身作则','以成才为要'],
 enStep:['Discuss, order less','Set rules, explain why','Direct the edge to sport and responsibility','Do not confront or punish harshly','Lead by example','Rest on growth'],
 cnMis:['非打即骂','硬碰压制','不立规矩'],
 enMis:['Punishing harshly','Suppressing by force','No rules'],
 cnClose:'天煞在子女宫，刚烈孩子要「顺引、立规、不硬碰」。把那股劲用对，反成大器。',
 enClose:'Tian Sha in the Children Palace calls for guiding with the grain, rules and no confrontation. Direct the edge well and it becomes strength.'},

{cat:'fuzhu',slug:'ziwei-tiansha-zai-caibogong',focus:'天煞在财帛宫',focusEn:'Tian Sha in the Wealth Palace',
 cnT:'天煞在财帛宫：冲动刚烈易破财，缓决策、不斗气',enT:'Tian Sha in the Wealth Palace: Calm Decisions, No Reckless Spending',
 cnD:'天煞在财帛宫多主花钱、投资容易因一时刚烈冲动而破财，斗气消费更亏；重在重大决策缓一缓、不赌气，远离冒险。',
 enD:'Tian Sha in the Wealth Palace suggests money lost to hard, impulsive spending and investment, especially spiteful buys. Slow big decisions, do not act from anger and avoid reckless risk.',
 cnL:'斗气花的钱、冲动投的资，最后都自己买单；缓一缓、心平了再决定。',
 enL:'Spiteful spending and impulsive investment are paid by you; slow down and decide calmly.',
 cnA:'有人脾气上来就乱花钱、冒险；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some spend and risk when angry; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['天煞在财帛宫，冲动刚烈破财。','决策缓一缓、不斗气。','远离冒险。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Sha in Wealth means impulsive loss.','Slow decisions, no spite.','Avoid reckless risk.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['重大决策隔夜再定','不赌气消费','远离冒险投资','记账、留应急','咨询持牌专业人士','以稳为要'],
 enStep:['Sleep on big decisions','No spiteful spending','Avoid risky investment','Track accounts, keep reserves','Consult licensed professionals','Rest on steadiness'],
 cnMis:['冲动花钱','斗气消费','冒险投资'],
 enMis:['Impulsive spending','Spiteful buys','Risky investment'],
 cnClose:'天煞在财帛宫，要防「刚烈冲动破财」。缓决策、不斗气、远风险，守好钱。',
 enClose:'Tian Sha in the Wealth Palace guards against impulsive loss. Slow decisions, avoid spite and risk to guard money.'},

{cat:'fuzhu',slug:'ziwei-tiansha-zai-jiegong',focus:'天煞在疾厄宫',focusEn:'Tian Sha in the Health Palace',
 cnT:'天煞在疾厄宫：脾气急易伤身，平肝降火重安全',enT:'Tian Sha in the Health Palace: Easing a Fiery Temper for Health',
 cnD:'天煞在疾厄宫多主性子急、火气大，容易因情绪影响血压、睡眠等，也要防外伤；重在调心降火、规律生活，不适正规就医。',
 enD:'Tian Sha in the Health Palace suggests a quick, fiery temper affecting blood pressure and sleep, with injury risk too. Calm the mind, live regularly and seek formal care for discomfort.',
 cnL:'急脾气最伤身，火往上走、病跟着来；你把心放宽、节奏放慢，身体才稳。',
 enL:'A quick temper harms the body; widen the heart and slow the pace.',
 cnA:'有人由着性子发火、不调情绪；星曜是倾向，健康以正规就医为准。',
 enA:'Some give in to anger without calming; stars are tendency, while health relies on formal care.',
 cnLog:['天煞在疾厄宫，急火伤身。','防外伤、调情绪。','规律生活、早就医。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Sha in Health means a fiery temper harming body.','Prevent injury, calm mind.','Live regularly, seek early care.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['练习平心静气','规律作息、少熬夜','注意安全防外伤','不适及时就诊','按医生评估处理','以规范为要'],
 enStep:['Practice calming the mind','Regular hours, less late nights','Mind safety, prevent injury','Seek timely care','Follow doctor assessment','Rest on proper care'],
 cnMis:['由着性子发火','不调情绪','忽视外伤风险'],
 enMis:['Giving in to anger','Not calming emotions','Ignoring injury risk'],
 cnClose:'天煞在疾厄宫，功课是「降火调心、重安全」。性子稳了，身体才少受累。',
 enClose:'Tian Sha in the Health Palace calls for calming temper and minding safety. Steady the temper for steadier health.'},

{cat:'fuzhu',slug:'ziwei-tiansha-zai-qianyi',focus:'天煞在迁移宫',focusEn:'Tian Sha in the Travel Palace',
 cnT:'天煞在迁移宫：外出防冲突，忍让冷静保平安',enT:'Tian Sha in the Travel Palace: Avoid Conflict, Stay Calm',
 cnD:'天煞在迁移宫多主在外容易与人起冲突、斗气，也防意外；重在遇事忍让、不逞强，出门在外和为贵、安全第一。',
 enD:'Tian Sha in the Travel Palace suggests easy conflict with others away and mishap risk too. Yield in trouble, do not show off, value harmony and safety first.',
 cnL:'在外争一时之气、最不值当；你肯忍一句、退一步，平安到家最重要。',
 enL:'A moment anger away is not worth it; yield a word and step back, safe return matters.',
 cnA:'有人在外逞强、不肯吃亏；星曜是倾向，平安靠忍让。',
 enA:'Some show off away and refuse to lose out; stars are tendency, while safety rests on yielding.',
 cnLog:['天煞在迁移宫，在外防冲突。','忍让、不逞强。','和为贵、安全第一。','倾向描述，非绝对定论。'],
 enLog:['Tian Sha in Travel means guarding conflict away.','Yield, do not show off.','Harmony and safety first.','This is tendency, not an absolute verdict.'],
 cnStep:['遇事不斗气','忍让一步','守交规、重安全','控制情绪','行程留余','以平安为要'],
 enStep:['Do not act from anger away','Yield a step','Follow rules, mind safety','Control emotions','Leave schedule margin','Rest on safe travel'],
 cnMis:['在外逞强','斗气冲突','不肯忍让'],
 enMis:['Showing off away','Angry conflict','Refusing to yield'],
 cnClose:'天煞在迁移宫，外出「忍让、冷静、不逞强」。和为贵，平安才是真。',
 enClose:'Tian Sha in the Travel Palace calls for yielding, calm and no showing off. Value harmony and safe return.'},

{cat:'fuzhu',slug:'ziwei-tiansha-zai-puyigong',focus:'天煞在仆役宫',focusEn:'Tian Sha in the Friends Palace',
 cnT:'天煞在仆役宫：朋友性子刚，慎择交、少斗气',enT:'Tian Sha in the Friends Palace: Choose Calm Friends, Avoid Clashes',
 cnD:'天煞在仆役宫多主朋友、部属中刚烈者多，相处易起冲突；重在慎重择交、遇事不斗气，与太冲的人保持分寸。',
 enD:'Tian Sha in the Friends Palace suggests many harsh friends and staff with easy conflict. Choose friends carefully, do not act from anger and keep measure with very confrontational people.',
 cnL:'朋友太冲、相处像踩火药；你择善而交、不斗气，耳根清净、事也顺。',
 enL:'Very confrontational friends are like gunpowder; choose well and do not clash.',
 cnA:'有人专和刚烈朋友凑、斗气不断；星曜是倾向，相处靠选择。',
 enA:'Some gather harsh friends and clash often; stars are tendency, while relating rests on choice.',
 cnLog:['天煞在仆役宫，朋友刚烈。','易起冲突。','慎择交、不斗气。','倾向描述，非绝对定论。'],
 enLog:['Tian Sha in Friends means harsh friends.','Easy conflict.','Choose carefully, no anger.','This is tendency, not an absolute verdict.'],
 cnStep:['慎重选择朋友','遇事冷静不斗气','与冲的人守分寸','守边界','真诚待人','以长久为要'],
 enStep:['Choose friends carefully','Stay calm, no anger','Keep measure with confrontational people','Keep boundaries','Be sincere','Rest on lasting relations'],
 cnMis:['专和冲的人凑','斗气冲突','不择交'],
 enMis:['Gathering confrontational people','Angry clashes','Not choosing friends'],
 cnClose:'天煞在仆役宫，要防「朋友冲突斗气」。慎交、冷静、守分寸，相处才顺。',
 enClose:'Tian Sha in the Friends Palace guards against friends conflict. Choose carefully, stay calm and keep measure for smooth relations.'}
];
