// catchup 2026-09-11 第3组：文昌/文曲疾厄宫 + 天官前6宫（命/兄弟/夫妻/子女/财帛/疾厄）
module.exports=[
{cat:'fuzhu',slug:'ziwei-wenchang-zai-jiegong',focus:'文昌在疾厄宫',focusEn:'Wen Chang in the Health Palace',
 cnT:'文昌在疾厄宫：用脑过度最伤身，神经与呼吸道多放松',enT:'Wen Chang in the Health Palace: Overthinking, Nerves and Respiratory',
 cnD:'文昌属金、主理性文书，在疾厄宫多指向神经紧张、用脑过度，也连带支气管；人越较真、越熬夜动脑，越容易失眠、干咳。重在给大脑留白、用呼吸和运动松神经。',
 enD:'Wen Chang belongs to metal and governs reason and documents; in the Health Palace it points to nervous tension and overthinking, also the bronchial tract. The more meticulous and late-night the mental work, the easier insomnia and dry cough. Leave the mind blank space and relax nerves with breathing and exercise.',
 cnL:'脑子是好东西，可也得下班；老让它连轴转，神经和呼吸先替你喊累。',
 enL:'The mind is precious but must clock out; kept running nonstop, nerves and breathing complain first.',
 cnA:'有人靠咖啡硬撑动脑、把失眠干咳当累，拖成慢性；星曜是倾向，神经呼吸的问题仍要就医查清楚。',
 enA:'Some power mental work with coffee and treat insomnia and dry cough as fatigue, dragging into chronic; stars are tendency, while nerve and respiratory ills still need checking.',
 cnLog:['文昌属金主理性，重点在神经、用脑、支气管。','较真、熬夜动脑易失眠干咳。','给大脑留白、松神经。','倾向非诊断，以正规就医为准。'],
 enLog:['Wen Chang is metal governing reason, focus on nerves, mental strain and bronchial.','Meticulous late-night work brings insomnia and cough.','Leave the mind blank, relax nerves.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['用脑有度、规律作息','减少咖啡熬夜硬撑','用呼吸、运动放松神经','失眠久咳及时就诊','关注呼吸道检查','以医生评估为准'],
 enStep:['Use the mind moderately, keep regular hours','Cut coffee-fueled late nights','Relax nerves with breathing and exercise','Seek care for insomnia and long cough','Watch respiratory checks','Follow the doctor assessment'],
 cnMis:['熬夜动脑、咖啡硬撑','把神经呼吸不适当累','用脑无度不放松'],
 enMis:['Late-night mental work powered by coffee','Taking nerve and respiratory ills as fatigue','No moderation or relaxation for the mind'],
 cnClose:'文昌在疾厄宫，要防「脑子过劳、神经先垮」。作息有常、神经常松，失眠久咳早就医，别硬撑。',
 enClose:'Wen Chang in the Health Palace guards against an overworked mind and fraying nerves. Keep regular hours, relax often and seek early care for insomnia and cough rather than forcing through.'},

{cat:'fuzhu',slug:'ziwei-wenqu-zai-jiegong',focus:'文曲在疾厄宫',focusEn:'Wen Qu in the Health Palace',
 cnT:'文曲在疾厄宫：情志起伏牵动身体，养心即是养身',enT:'Wen Qu in the Health Palace: Emotions and the Body',
 cnD:'文曲属水、主感性才情，在疾厄宫多指向情志失调带来的身体反应，如胸闷、睡眠差、肠胃不适；情绪一波动身体就跟着应。重在疏解心情、给感受找出口。',
 enD:'Wen Qu belongs to water and governs feeling and talent; in the Health Palace it points to bodily reactions from emotional imbalance, such as chest tightness, poor sleep and gut upset; the body responds as emotions move. Ease the mood and give feelings an outlet.',
 cnL:'心思细的人，身体像情绪的回声壁；心情一紧，身体各处都跟着响。',
 enL:'In a sensitive person the body is an echo chamber for emotion; as the mood tightens, the body resonates everywhere.',
 cnA:'有人只治身体不调情绪，反复不见好；星曜是倾向，情志相关的身体反应要身心同看、必要时寻求专业帮助。',
 enA:'Some treat only the body without the mood and do not improve; stars are tendency, while emotion-linked bodily reactions need body-mind care and professional help when needed.',
 cnLog:['文曲属水主感性，重点在情志牵动的身体反应。','情绪波动易胸闷、睡差、肠胃不适。','疏解心情、给感受出口。','倾向非诊断，以正规就医为准。'],
 enLog:['Wen Qu is water governing feeling, focus on emotion-linked bodily reactions.','Mood swings bring chest tightness, poor sleep and gut upset.','Ease the mood, give feelings an outlet.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['觉察情绪与身体的关联','用倾诉、兴趣疏解心情','规律作息、稳住睡眠','胸闷肠胃不适及时就诊','必要时寻求心理专业帮助','以医生判断为准'],
 enStep:['Notice how emotions and body connect','Ease mood through talk and interests','Keep regular hours, steady sleep','Seek care for chest and gut discomfort','Seek mental-health help when needed','Follow the doctor judgment'],
 cnMis:['只治身不调心','情绪压抑、没有出口','把情志反应当器质性病乱治'],
 enMis:['Treating only body without mood','Suppressing emotion with no outlet','Treating emotional reactions as random organic disease'],
 cnClose:'文曲在疾厄宫，重在「心情顺、身体才顺」。给情绪出口、身心同看，反复不适应就医、也别忽视心里的结。',
 enClose:'Wen Qu in the Health Palace focuses on a smooth mood for a smooth body. Give emotions an outlet, care for body and mind, seek care for recurring ills and do not ignore inner knots.'},

{cat:'fuzhu',slug:'ziwei-tianguan-zai-minggong',focus:'天官在命宫',focusEn:'Tian Guan in the Life Palace',
 cnT:'天官在命宫：稳重自持带贵气，端着别让自己太累',enT:'Tian Guan in the Life Palace: Steady Dignity Without Strain',
 cnD:'天官主贵气、稳重，在命宫多为人端正、自持、讲体面，给人可靠感；但也容易端着、爱面子、给自己加压。重在守住稳重的同时，学会放松、不必时刻完美。',
 enD:'Tian Guan governs dignity and steadiness; in the Life Palace one is upright, self-possessed and presentable, giving a sense of reliability. Yet one may stand on ceremony, care about face and add pressure. Keep steadiness while learning to relax, without needing constant perfection.',
 cnL:'体面是给别人看的，轻松是给自己的；老端着架子，肩膀和心都酸。',
 enL:'Dignity is for others and ease is for oneself; always holding posture tires both shoulders and heart.',
 cnA:'有人为了体面硬扛压力、不肯示弱，结果内耗；星曜是倾向，放松和示弱不丢人，反而是成熟。',
 enA:'Some carry pressure for face and refuse to show weakness, ending drained; stars are tendency, while relaxing and showing vulnerability are not shame but maturity.',
 cnLog:['天官主贵气稳重，命宫为人端正自持。','易端着、爱面子、自我加压。','守稳重也学会放松。','倾向描述，非绝对定论。'],
 enLog:['Tian Guan governs dignity and steadiness; in Life one is upright and composed.','Prone to ceremony, face and self-pressure.','Keep steadiness and learn to relax.','This is tendency, not an absolute verdict.'],
 cnStep:['发挥稳重可靠的长处','允许自己不完美、会示弱','用运动、社交卸下架子','减少为面子硬扛','作息规律、张弛有度','以自我接纳为要'],
 enStep:['Use the strength of steadiness and reliability','Allow imperfection and showing vulnerability','Drop ceremony through sport and social time','Reduce carrying pressure for face','Keep regular hours with balance','Rest on self-acceptance'],
 cnMis:['为体面硬扛、不肯示弱','时刻要求自己完美','把面子看得过重'],
 enMis:['Carrying on for face, refusing vulnerability','Demanding constant perfection','Overvaluing face'],
 cnClose:'天官在命宫是「端正可靠」的好底色，但别让体面绑架自己。会放松、敢示弱，稳重才不变成负担。',
 enClose:'Tian Guan in the Life Palace gives an upright, reliable tone, but do not let dignity trap you. Able to relax and show vulnerability, steadiness stops becoming a burden.'},

{cat:'fuzhu',slug:'ziwei-tianguan-zai-xiongdigong',focus:'天官在兄弟宫',focusEn:'Tian Guan in the Siblings Palace',
 cnT:'天官在兄弟宫：手足同辈多端正，相处贵乎真诚尊重',enT:'Tian Guan in the Siblings Palace: Upright Peers and Mutual Respect',
 cnD:'天官在兄弟宫多主兄弟姐妹、同辈朋友品行端正、较为可靠，能得同辈之助；但关系也偏讲分寸、略显客气。重在真诚往来、彼此尊重，遇事好商量。',
 enD:'Tian Guan in the Siblings Palace suggests siblings and peers are upright and fairly reliable, able to offer help. Yet relations lean on propriety and can feel formal. Interact sincerely, respect one another and discuss matters openly.',
 cnL:'好的同辈像稳当的同行者，不必天天热络，但有事时靠得住、说得开。',
 enL:'Good peers are steady fellow travelers; not daily-close, but reliable and open when matters arise.',
 cnA:'有人把客气当疏远、疏于经营同辈关系；星曜是倾向，关系靠走动和真诚，不能只等对方主动。',
 enA:'Some take politeness as distance and neglect peer relations; stars are tendency, while bonds rely on contact and sincerity, not waiting for others to move.',
 cnLog:['天官在兄弟宫，手足同辈端正可靠。','关系偏讲分寸、略客气。','真诚往来、彼此尊重。','倾向描述，非绝对定论。'],
 enLog:['Tian Guan in Siblings means upright, reliable peers.','Relations lean on propriety and feel formal.','Interact sincerely, respect one another.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜端正可靠的手足同辈','主动走动、真诚联系','相处尊重、遇事商量','不必拘于客气','互助但守边界','以长期经营为要'],
 enStep:['Value upright, reliable siblings and peers','Initiate contact and connect sincerely','Respect one another, discuss matters','Do not be bound by formality','Help within boundaries','Rest on long-term care'],
 cnMis:['把客气当疏远','只等对方主动、不经营','求助无度、不守边界'],
 enMis:['Taking politeness as distance','Waiting for others, not cultivating','Asking help without boundaries'],
 cnClose:'天官在兄弟宫，好在「同辈端正可靠」。多走动、讲真诚、守边界，手足朋友才是长久的助力。',
 enClose:'Tian Guan in the Siblings Palace blesses upright, reliable peers. More contact, sincerity and boundaries make siblings and friends lasting support.'},

{cat:'fuzhu',slug:'ziwei-tianguan-zai-fuqigong',focus:'天官在夫妻宫',focusEn:'Tian Guan in the Spouse Palace',
 cnT:'天官在夫妻宫：伴侣端正稳重，相处重尊重与责任感',enT:'Tian Guan in the Spouse Palace: A Steady Partner and Respect',
 cnD:'天官在夫妻宫多主伴侣品行端正、稳重可靠、有责任感，关系偏平稳踏实；但也可能少些浪漫、略显严肃。重在彼此尊重、共同担责，平淡中经营温度。',
 enD:'Tian Guan in the Spouse Palace suggests an upright, steady and responsible partner, with a calm and grounded relationship. It may feel less romantic and a bit serious. Respect one another, share responsibility and build warmth within the ordinary.',
 cnL:'安稳的伴侣像合身的家常衣，不抢眼，却挡风遮雨、穿着最踏实。',
 enL:'A steady partner is like well-fitting everyday clothes, not eye-catching but sheltering and the most grounded.',
 cnA:'有人嫌伴侣不够浪漫而忽视其可靠；星曜是倾向，感情靠经营，尊重与陪伴比一时激情更长久。',
 enA:'Some fault a partner for lacking romance and overlook reliability; stars are tendency, while bonds need care, and respect and companionship outlast passion.',
 cnLog:['天官在夫妻宫，伴侣端正稳重、有责任感。','关系平稳、可能少浪漫。','彼此尊重、共担责任。','倾向描述，非绝对定论。'],
 enLog:['Tian Guan in Spouse means an upright, steady, responsible partner.','The bond is calm, perhaps less romantic.','Respect one another, share responsibility.','This is tendency, not an absolute verdict.'],
 cnStep:['欣赏伴侣的稳重可靠','用日常陪伴经营温度','共同担责、遇事商量','主动制造一点仪式感','彼此尊重、少指责','以长期相处为要'],
 enStep:['Appreciate a steady, reliable partner','Build warmth through daily companionship','Share responsibility, discuss matters','Create a little ceremony on purpose','Respect one another, blame less','Rest on long-term relating'],
 cnMis:['只嫌不浪漫、忽视可靠','把平淡当不爱','不主动经营温度'],
 enMis:['Faulting lack of romance, overlooking reliability','Taking calm as lack of love','Not building warmth on purpose'],
 cnClose:'天官在夫妻宫，难得「伴侣稳重有担当」。尊重相伴、平淡中添温度，踏实的关系才走得远。',
 enClose:'Tian Guan in the Spouse Palace offers a steady, responsible partner. Respect and companionship with warmth in the ordinary let a grounded bond go far.'},

{cat:'fuzhu',slug:'ziwei-tianguan-zai-zinvgong',focus:'天官在子女宫',focusEn:'Tian Guan in the Children Palace',
 cnT:'天官在子女宫：子女多乖顺端正，教养重身教与尊重',enT:'Tian Guan in the Children Palace: Well-Behaved Children and Example',
 cnD:'天官在子女宫多主子女乖顺、有教养、较为端正，亲子关系偏规矩；但管束过严易显拘谨。重在以身作则、尊重孩子天性，规矩与温度并施。',
 enD:'Tian Guan in the Children Palace suggests well-behaved, mannerly and upright children, with a fairly disciplined bond. Over-strict control can make them reserved. Lead by example, respect their nature and combine rules with warmth.',
 cnL:'孩子是看着父母背影长大的；你想让他端正，自己先活成那个样子。',
 enL:'Children grow watching their parents backs; to make them upright, first live that way yourself.',
 cnA:'有人只立规矩、不给温度，孩子反而拘谨疏远；星曜是倾向，教养靠身教与尊重，不能只靠管。',
 enA:'Some set rules without warmth and children grow reserved and distant; stars are tendency, while parenting rests on example and respect, not only control.',
 cnLog:['天官在子女宫，子女乖顺有教养。','管束过严易拘谨。','以身作则、规矩与温度并施。','倾向描述，非绝对定论。'],
 enLog:['Tian Guan in Children means mannerly, upright children.','Over-strict control brings reserve.','Lead by example, combine rules and warmth.','This is tendency, not an absolute verdict.'],
 cnStep:['以身作则、言传身教','规矩清晰但有温度','尊重孩子天性与想法','少用压制、多引导','留出亲子温情时光','以长期陪伴为要'],
 enStep:['Lead by example in word and deed','Keep clear rules with warmth','Respect the child nature and ideas','Guide more than suppress','Set aside warm parent-child time','Rest on long companionship'],
 cnMis:['只立规矩不给温度','压制过度、孩子拘谨','自己做不到却要求孩子'],
 enMis:['Rules without warmth','Over-suppressing, reserved children','Demanding what you do not do yourself'],
 cnClose:'天官在子女宫，孩子乖顺是好事，但教养要「身教为先、规矩带温度」。尊重天性，亲子才亲。',
 enClose:'Tian Guan in the Children Palace makes mannerly children a blessing, but parenting needs example first and warm rules. Respect their nature and the bond stays close.'},

{cat:'fuzhu',slug:'ziwei-tianguan-zai-caibogong',focus:'天官在财帛宫',focusEn:'Tian Guan in the Wealth Palace',
 cnT:'天官在财帛宫：财源偏稳、取之有道，守正比冒进更长久',enT:'Tian Guan in the Wealth Palace: Steady, Principled Income',
 cnD:'天官在财帛宫多主财源较稳、取之正道，靠本分与信誉积累；不适合投机取巧、贪快冒进。重在守正、量力，稳稳积累比一时暴利踏实。',
 enD:'Tian Guan in the Wealth Palace suggests steady, principled income built through duty and reputation; speculation and greedy haste do not suit. Stay upright and measure capacity, for steady accumulation is more grounded than sudden profit.',
 cnL:'正道来的钱像慢火熬汤，不惊艳，却养人、长久；快钱烫手，来得快去得也快。',
 enL:'Principled money is like slow-simmered soup, not flashy but nourishing and lasting; quick money burns and leaves as fast as it comes.',
 cnA:'有人为快钱去投机、走偏门，结果因小失大；星曜是倾向，理财决策不构成投资建议，应以持牌机构和正规产品说明为准。',
 enA:'Some chase quick money through speculation or side doors and lose more than they gain; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal product terms.',
 cnLog:['天官在财帛宫，财源稳、取之正道。','靠本分信誉积累，不宜投机。','守正量力、稳积累。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Guan in Wealth means steady, principled income.','Build through duty and reputation, not speculation.','Stay upright, measure capacity, accumulate steadily.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['走正道、靠本事赚钱','珍惜信誉、本分经营','量力而行、不贪快冒进','远离偏门与高息陷阱','重大决策咨询持牌专业人士','以正规产品说明为准'],
 enStep:['Earn principled money through ability','Value reputation, operate with duty','Measure capacity, avoid greedy haste','Avoid side doors and high-interest traps','Consult licensed professionals for big decisions','Rely on formal product terms'],
 cnMis:['贪快钱、走偏门','投机冒进、忽视风险','把稳当当无能、盲目追暴利'],
 enMis:['Chasing quick money through side doors','Speculating, ignoring risk','Taking steadiness as weakness, chasing windfalls'],
 cnClose:'天官在财帛宫，贵在「取财有道、稳中有进」。守本分、远偏门，重大钱财决策听持牌专业人士，踏实才长久。',
 enClose:'Tian Guan in the Wealth Palace values principled, steady gains. Keep duty, avoid side doors and consult licensed professionals for big decisions, for grounded wealth lasts.'},

{cat:'fuzhu',slug:'ziwei-tianguan-zai-jiegong',focus:'天官在疾厄宫',focusEn:'Tian Guan in the Health Palace',
 cnT:'天官在疾厄宫：调养偏稳、重视体面，慢病也要规范随访',enT:'Tian Guan in the Health Palace: Steady Care and Follow-Up',
 cnD:'天官在疾厄宫多主体质偏稳、病势较缓，但人爱体面、有时讳疾忌医或硬撑。重在放下顾虑、规范调养，慢病按时随访，别因面子耽误。',
 enD:'Tian Guan in the Health Palace suggests a fairly steady constitution and slower illness, yet one cares about face and may avoid doctors or tough it out. Set hesitation aside, care properly and keep chronic follow-up on time, not delaying for face.',
 cnL:'病不挑人，也不讲体面；在医生面前端着，最后吃亏的是自己的身子。',
 enL:'Illness spares no one and ignores dignity; standing on ceremony before the doctor only harms your own body.',
 cnA:'有人因怕麻烦、爱体面而拖着不查，结果加重；星曜是倾向，健康问题要规范就医、定期随访。',
 enA:'Some delay checks out of trouble-aversion and face and worsen; stars are tendency, while health ills need proper care and regular follow-up.',
 cnLog:['天官在疾厄宫，体质偏稳、病势缓。','易爱体面、讳疾硬撑。','规范调养、慢病随访。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Guan in Health means a steady constitution, slower illness.','Prone to face, avoiding care or toughing it out.','Care properly, follow up chronic ills.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['放下体面、及时就诊','规范调养、遵医嘱','慢病定期随访、不拖延','作息饮食有规律','不讳疾忌医','以医生方案为准'],
 enStep:['Set face aside, seek timely care','Care properly, follow orders','Follow up chronic ills, do not delay','Keep regular routines and diet','Do not avoid doctors','Follow the doctor plan'],
 cnMis:['爱体面、讳疾忌医','硬撑不查、拖成加重','慢病不随访'],
 enMis:['Caring about face, avoiding doctors','Toughing out checks, worsening','Skipping chronic follow-up'],
 cnClose:'天官在疾厄宫，虽偏稳，更要「放下体面、规范就医」。调养按时、随访不缺，别让面子误了身子。',
 enClose:'Tian Guan in the Health Palace is steady but calls for setting face aside and seeking proper care. Keep care and follow-up on time, and do not let dignity harm the body.'}
];
