// catchup 2026-09-14 第4组：天寿前8宫
module.exports=[
{cat:'fuzhu',slug:'ziwei-tianshou-zai-xiongdigong',focus:'天寿在兄弟宫',focusEn:'Tian Shou in the Siblings Palace',
 cnT:'天寿在兄弟宫：手足同辈多稳重，长久相处情分深',enT:'Tian Shou in the Siblings Palace: Steady, Long-Lasting Peers',
 cnD:'天寿主长寿稳重，在兄弟宫多主兄弟姐妹、同辈性情敦厚、身体安康，关系能处得长久；重在珍惜、常走动，平淡中的长久最难得。',
 enD:'Tian Shou governs longevity and steadiness; in the Siblings Palace it suggests grounded, healthy peers with long bonds. Value them and stay in touch, for steady longevity is rare.',
 cnL:'同辈能处一辈子，靠的是敦厚和常来常往；细水长流，比一时热闹强。',
 enL:'Lifelong peers rest on groundedness and contact; steady flow beats brief noise.',
 cnA:'有人只在热闹时凑、疏于长久经营；星曜是倾向，情分靠走动。',
 enA:'Some gather only in excitement and neglect bonds; stars are tendency, while affection needs contact.',
 cnLog:['天寿主长寿稳重，兄弟宫同辈敦厚。','身体安康、处得久。','珍惜、常走动。','倾向描述，非绝对定论。'],
 enLog:['Tian Shou governs steadiness; in Siblings grounded peers.','Healthy, long bonds.','Value, stay in touch.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜敦厚同辈','常联系走动','平淡中经营','遇事互相帮衬','不势利','以长久为要'],
 enStep:['Value grounded peers','Stay in touch','Care through steady times','Help one another','Do not be snobbish','Rest on lasting bonds'],
 cnMis:['疏于走动','只凑热闹','不珍惜长久'],
 enMis:['Neglecting contact','Only excitement','Not valuing longevity'],
 cnClose:'天寿在兄弟宫，手足同辈稳重能久处。珍惜、常走动，细水长流的情分最难得。',
 enClose:'Tian Shou in the Siblings Palace blesses steady, long-lasting peers. Value and stay in touch.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-fuqigong',focus:'天寿在夫妻宫',focusEn:'Tian Shou in the Spouse Palace',
 cnT:'天寿在夫妻宫：伴侣稳重踏实，细水长流共白头',enT:'Tian Shou in the Spouse Palace: A Steady, Lasting Partnership',
 cnD:'天寿在夫妻宫多主伴侣性情稳重、身体安康，关系经得起平淡岁月；重在共同经营、彼此照顾，长久的婚姻靠的是踏实和陪伴。',
 enD:'Tian Shou in the Spouse Palace suggests a steady, healthy partner with a bond bearing quiet years. Build together and care for one another, for lasting marriage rests on steadiness and presence.',
 cnL:'白头偕老不靠轰轰烈烈，靠的是踏实陪伴、把对方放心上。',
 enL:'Growing old together rests not on drama but steady presence.',
 cnA:'有人只追求激情、守不住平淡；星曜是倾向，长久靠经营。',
 enA:'Some chase passion and cannot bear quiet; stars are tendency, while lasting love needs care.',
 cnLog:['天寿在夫妻宫，伴侣稳重安康。','经得起平淡。','踏实陪伴、经营。','倾向描述，非绝对定论。'],
 enLog:['Tian Shou in Spouse means a steady, healthy partner.','Bears quiet years.','Steady presence, care.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜踏实的伴侣','共同经营、多陪伴','照顾对方健康','安于平淡','遇事商量','以白头为要'],
 enStep:['Value a steady partner','Build, be present','Care for their health','Embrace quiet times','Discuss matters','Rest on lasting bonds'],
 cnMis:['只追激情','守不住平淡','忽视陪伴'],
 enMis:['Chasing passion','Cannot bear quiet','Ignoring presence'],
 cnClose:'天寿在夫妻宫，伴侣稳重、关系长久。踏实陪伴、共同经营，细水长流共白头。',
 enClose:'Tian Shou in the Spouse Palace blesses a steady, lasting partner. Be present and build for growing old together.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-zinvgong',focus:'天寿在子女宫',focusEn:'Tian Shou in the Children Palace',
 cnT:'天寿在子女宫：孩子稳重安康，养身养性平安长',enT:'Tian Shou in the Children Palace: A Steady, Healthy Child',
 cnD:'天寿在子女宫多主孩子性情稳重、身体安康、发育踏实；重在养身也养性，规律作息、培养好性格，平安是一切的基础。',
 enD:'Tian Shou in the Children Palace suggests a grounded, healthy child developing steadily. Nurture body and character with regular habits, for safety is the foundation of all.',
 cnL:'孩子平安稳重，比什么都强；身体和性格，都靠你从小养。',
 enL:'A safe, steady child is worth most; body and character are built early.',
 cnA:'有人只盼孩子出人头地、忽视安康；星曜是倾向，平安是福。',
 enA:'Some only seek achievement and neglect health; stars are tendency, while safety is blessing.',
 cnLog:['天寿在子女宫，孩子稳重安康。','发育踏实。','养身养性、规律。','倾向描述，非绝对定论。'],
 enLog:['Tian Shou in Children means a grounded, healthy child.','Steady development.','Nurture body and character.','This is tendency, not an absolute verdict.'],
 cnStep:['规律作息饮食','培养稳重性格','重视发育健康','不过度催','陪伴成长','以平安为要'],
 enStep:['Regular hours and diet','Build grounded character','Mind development and health','Do not over-push','Accompany growth','Rest on safety'],
 cnMis:['只盼出人头地','忽视安康','作息无规律'],
 enMis:['Only seeking achievement','Neglecting health','Irregular habits'],
 cnClose:'天寿在子女宫，孩子稳重安康是福。养身养性、规律生活，平安长大最重要。',
 enClose:'Tian Shou in the Children Palace blesses a steady, healthy child. Nurture body and character for safe growth.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-caibogong',focus:'天寿在财帛宫',focusEn:'Tian Shou in the Wealth Palace',
 cnT:'天寿在财帛宫：财源稳、善守成，慢慢积累不冒进',enT:'Tian Shou in the Wealth Palace: Steady, Patient Accumulation',
 cnD:'天寿在财帛宫多主钱财来得稳、善守成，靠慢慢积累致富；重在不冒进、不投机，时间和复利是你的朋友。',
 enD:'Tian Shou in the Wealth Palace suggests steady money and good guarding, growing through patient accumulation. Do not rush or speculate, for time and compounding are your friends.',
 cnL:'稳稳的钱最长久；你不贪快、不投机，时间会替你攒。',
 enL:'Steady money lasts longest; do not chase quick gains or speculate.',
 cnA:'有人嫌慢、冒险逐利，反而亏；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some find it slow and chase risky gains, losing instead; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['天寿在财帛宫，财源稳、守成。','慢慢积累、不冒进。','时间复利为友。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Shou in Wealth means steady money, guarding.','Patient accumulation, no rush.','Time and compounding help.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['坚持慢慢积累','不投机、不冒进','留应急钱','选正规产品','咨询持牌专业人士','以稳为要'],
 enStep:['Keep accumulating patiently','No speculation or rushing','Keep emergency money','Choose formal products','Consult licensed professionals','Rest on steadiness'],
 cnMis:['嫌慢冒险','投机逐利','不守成'],
 enMis:['Finding it slow, risking','Speculating for gains','Not guarding'],
 cnClose:'天寿在财帛宫，善「稳守慢积」。不贪快、不投机，时间会给你答案。',
 enClose:'Tian Shou in the Wealth Palace blesses steady guarding and patient accumulation. Do not chase quick gains or speculate.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-jiegong',focus:'天寿在疾厄宫',focusEn:'Tian Shou in the Health Palace',
 cnT:'天寿在疾厄宫：底子好偏长寿，规律养身防慢病',enT:'Tian Shou in the Health Palace: A Strong Base, Guarding Chronic ills',
 cnD:'天寿在疾厄宫多主体质根基好、有长寿倾向，但长寿不是躺来的；重在规律生活、防慢病、按时体检，不挥霍好底子。',
 enD:'Tian Shou in the Health Palace suggests a strong base with longevity tendency, but longevity is not automatic. Live regularly, guard chronic ills and have check-ups, not wasting a good base.',
 cnL:'好底子是本钱，可长寿靠的是一辈子的规律和自律。',
 enL:'A good base is capital, but longevity rests on lifelong regularity.',
 cnA:'有人仗底子好、熬夜挥霍；星曜是倾向，健康以正规就医为准。',
 enA:'Some rely on a good base and squander it; stars are tendency, while health relies on formal care.',
 cnLog:['天寿在疾厄宫，根基好、偏长寿。','长寿非躺来。','规律、防慢病、体检。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Shou in Health means a strong base, longevity tendency.','Not automatic.','Regular, guard chronic ills, check-ups.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['规律作息饮食','按时体检','防慢病、控指标','不挥霍底子','不适及时就诊','以健康为要'],
 enStep:['Regular hours and diet','Check-ups on schedule','Guard chronic ills, control markers','Do not waste the base','Seek timely care','Rest on health'],
 cnMis:['仗底子挥霍','不体检','作息无律'],
 enMis:['Squandering the base','No check-ups','Irregular habits'],
 cnClose:'天寿在疾厄宫，有长寿倾向，但「规律、防慢病、不挥霍」。好底子要养，长寿才守得住。',
 enClose:'Tian Shou in the Health Palace gives longevity tendency, but live regularly, guard chronic ills and do not squander the base.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-qianyi',focus:'天寿在迁移宫',focusEn:'Tian Shou in the Travel Palace',
 cnT:'天寿在迁移宫：外出稳、节奏慢，平安往返少奔波',enT:'Tian Shou in the Travel Palace: Steady, Safe Trips',
 cnD:'天寿在迁移宫多主外出节奏稳、不易出大状况，适合不疾不徐的远行；重在行程别太赶、注意休息，平安往返。',
 enD:'Tian Shou in the Travel Palace suggests steady travel without big mishaps, suiting unhurried trips. Do not overpack schedules, mind rest and return safely.',
 cnL:'出门不赶、稳着来，反而平安顺心；节奏慢一点，路好走。',
 enL:'Travel unhurried and steady for safe, smooth trips; slow the pace.',
 cnA:'有人行程排满、奔波伤神；星曜是倾向，平安靠稳。',
 enA:'Some pack schedules and tire themselves; stars are tendency, while safety rests on steadiness.',
 cnLog:['天寿在迁移宫，外出稳。','少大状况、利远行。','不赶、重休息。','倾向描述，非绝对定论。'],
 enLog:['Tian Shou in Travel means steady trips.','Few big mishaps, good for far travel.','Unhurried, mind rest.','This is tendency, not an absolute verdict.'],
 cnStep:['行程别排太满','注意中途休息','稳着赶路','备常用药','重安全','以平安往返为要'],
 enStep:['Do not overpack schedules','Rest along the way','Travel steadily','Carry basic medicines','Mind safety','Rest on safe return'],
 cnMis:['行程太赶','奔波不休息','节奏乱'],
 enMis:['Schedules too packed','Travel without rest','Unsteady pace'],
 cnClose:'天寿在迁移宫，外出稳、利平安。不赶、重休息，路才走得顺。',
 enClose:'Tian Shou in the Travel Palace blesses steady, safe travel. Do not rush and mind rest.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-puyigong',focus:'天寿在仆役宫',focusEn:'Tian Shou in the Friends Palace',
 cnT:'天寿在仆役宫：朋友稳重长久，慢交深交少而精',enT:'Tian Shou in the Friends Palace: Steady, Long-Tested Friends',
 cnD:'天寿在仆役宫多主朋友、部属稳重可靠，关系经得住时间；重在慢交、深交，少而精的长久朋友最珍贵。',
 enD:'Tian Shou in the Friends Palace suggests steady, reliable friends with bonds bearing time. Make friends slowly and deeply, for few but fine long friends are precious.',
 cnL:'朋友不在多，在稳、在久；时间筛下来的，才是真朋友。',
 enL:'Friends matter not in number but steadiness and time; time sifts true friends.',
 cnA:'有人交游广阔却没深交；星曜是倾向，长久靠真诚。',
 enA:'Some have wide circles but no deep bonds; stars are tendency, while longevity rests on sincerity.',
 cnLog:['天寿在仆役宫，朋友稳重可靠。','经得住时间。','慢交深交、少而精。','倾向描述，非绝对定论。'],
 enLog:['Tian Shou in Friends means steady, reliable people.','Bonds bear time.','Slow, deep, few but fine.','This is tendency, not an absolute verdict.'],
 cnStep:['慢慢交朋友','深交可靠的人','珍惜经时间的情','真诚守边界','不滥交','以长久信任为要'],
 enStep:['Make friends slowly','Deepen with reliable people','Value time-tested bonds','Sincere, keep boundaries','Do not over-socialize','Rest on long trust'],
 cnMis:['交游无深交','只图热闹','不珍惜老友'],
 enMis:['Wide circles, no depth','Only excitement','Not valuing old friends'],
 cnClose:'天寿在仆役宫，朋友稳重能久。慢交深交、少而精，时间留下的最珍贵。',
 enClose:'Tian Shou in the Friends Palace blesses steady, long friends. Make them slowly and deeply, for few but fine are precious.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-guanlugong',focus:'天寿在官禄宫',focusEn:'Tian Shou in the Career Palace',
 cnT:'天寿在官禄宫：事业稳、大器晚成，深耕耐得岁月',enT:'Tian Shou in the Career Palace: Steady, Late-Blooming Success',
 cnD:'天寿在官禄宫多主事业走得稳、大器晚成，靠长期深耕出成果；重在耐得住、不频繁换方向，时间会成就踏实的人。',
 enD:'Tian Shou in the Career Palace suggests steady, late-blooming work through long deepening. Endure and do not change direction often, for time rewards the grounded.',
 cnL:'大器晚成靠的是耐得住、扎得深；你不慌不躁，岁月会给位置。',
 enL:'Late blooming rests on endurance and deep roots; stay calm and time gives place.',
 cnA:'有人急于求成、老换方向；星曜是倾向，事业靠深耕。',
 enA:'Some seek quick success and change direction; stars are tendency, while career rests on deepening.',
 cnLog:['天寿在官禄宫，事业稳、晚成。','长期深耕出成果。','耐得住、不频换。','倾向描述，非绝对定论。'],
 enLog:['Tian Shou in Career means steady, late blooming.','Long deepening yields results.','Endure, change less.','This is tendency, not an absolute verdict.'],
 cnStep:['选定方向深耕','耐住早期平淡','不频繁跳槽','持续积累','踏实做事','以长远为要'],
 enStep:['Choose and deepen a direction','Endure early quiet','Do not change jobs often','Keep accumulating','Work grounded','Rest on long results'],
 cnMis:['急于求成','频繁换方向','耐不住'],
 enMis:['Seeking quick success','Changing direction often','Unable to endure'],
 cnClose:'天寿在官禄宫，事业稳、大器晚成。深耕、耐住、不慌，时间会成就你。',
 enClose:'Tian Shou in the Career Palace blesses steady, late-blooming work. Deepen, endure and stay calm.'}
];
