// catchup 2026-09-13 第1组：灾煞前8宫
module.exports=[
{cat:'fuzhu',slug:'ziwei-zaisha-zai-minggong',focus:'灾煞在命宫',focusEn:'Zai Sha in the Life Palace',
 cnT:'灾煞在命宫：易遇突发小波折，谨慎稳行少冒险',enT:'Zai Sha in the Life Palace: Cautious, Steady Steps',
 cnD:'灾煞主突发意外，在命宫多主人生路上容易遇到一些没预料的小波折、小意外；重在凡事谨慎、不逞强冒险，把安全和余量放在前面，很多小灾本可避开。',
 enD:'Zai Sha governs sudden mishaps; in the Life Palace it suggests unexpected small setbacks in life. Be cautious, do not force risks and put safety and margin first, for many small mishaps can be avoided.',
 cnL:'意外总挑没准备的人；你把小心和余量带在身上，很多坎儿根本不会找上门。',
 enL:'Mishaps choose the unprepared; carry caution and margin and many passes never come.',
 cnA:'有人逞强好胜、爱冒险，小灾也容易变大；星曜是倾向，谨慎是可以养成的习惯。',
 enA:'Some show off and court risks, letting small mishaps grow; stars are tendency, while caution is a habit to build.',
 cnLog:['灾煞主突发意外，命宫易遇小波折。','谨慎、不逞强冒险。','安全余量放前面。','倾向描述，非绝对定论。'],
 enLog:['Zai Sha governs sudden mishaps; in Life small setbacks.','Be cautious, do not force risks.','Put safety and margin first.','This is tendency, not an absolute verdict.'],
 cnStep:['凡事谨慎、不逞强','高风险活动量力','留好安全余量','出行做事守规矩','遇事冷静','以稳为要'],
 enStep:['Be cautious, do not show off','Measure capacity in risky activities','Keep safety margin','Follow rules in travel and work','Stay calm in trouble','Rest on steadiness'],
 cnMis:['逞强冒险','不留余量','把意外当偶然、不预防'],
 enMis:['Showing off, courting risks','No margin','Treating mishaps as mere chance'],
 cnClose:'灾煞在命宫，功课是「谨慎、稳行、不冒险」。把安全放前面，突发小灾就难绊住你。',
 enClose:'Zai Sha in the Life Palace calls for caution, steadiness and no risks. Put safety first and sudden mishaps rarely trip you.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-xiongdigong',focus:'灾煞在兄弟宫',focusEn:'Zai Sha in the Siblings Palace',
 cnT:'灾煞在兄弟宫：同辈之事易牵连，帮忙有度防拖累',enT:'Zai Sha in the Siblings Palace: Help Without Getting Dragged In',
 cnD:'灾煞在兄弟宫多主兄弟姐妹、同辈朋友的突发麻烦容易牵连到你，帮衬时易被拖累；重在有情有义也守边界，担保、借钱尤其谨慎。',
 enD:'Zai Sha in the Siblings Palace suggests sudden troubles of siblings and peers easily involving you, with help dragging you down. Be loyal yet keep boundaries, especially cautious with guarantees and loans.',
 cnL:'同辈有难肯帮，但担保借钱这类事最易把人拖下水；边界守住，情分才不变成债。',
 enL:'Help peers in need, but guarantees and loans drag people under; keep boundaries so affection does not become debt.',
 cnA:'有人为朋友两肋插刀、乱担保，结果背锅；星曜是倾向，帮人要量力、守规矩。',
 enA:'Some go all out and guarantee recklessly, ending liable; stars are tendency, so help within capacity and rules.',
 cnLog:['灾煞在兄弟宫，同辈突发事易牵连。','帮忙易被拖累。','守边界、慎担保借钱。','倾向描述，非绝对定论。'],
 enLog:['Zai Sha in Siblings means peers sudden troubles involve you.','Help can drag you down.','Keep boundaries, wary of guarantees and loans.','This is tendency, not an absolute verdict.'],
 cnStep:['同辈事量力帮忙','不轻易担保、借钱','守好钱财边界','亲兄弟明算账','救急不救穷','以长久为要'],
 enStep:['Help peers within capacity','Do not guarantee or lend lightly','Keep money boundaries','Keep accounts clear even with kin','Aid emergencies not dependence','Rest on lasting bonds'],
 cnMis:['乱担保、背锅','帮衬无度','边界不清'],
 enMis:['Guaranteeing recklessly, held liable','Help without limit','Unclear boundaries'],
 cnClose:'灾煞在兄弟宫，手足情要顾，但「帮忙有度、慎担保」。守边界、明算账，才不被拖累。',
 enClose:'Zai Sha in the Siblings Palace calls for kin care with bounded help and wary guarantees. Keep boundaries and accounts clear to avoid being dragged down.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-fuqigong',focus:'灾煞在夫妻宫',focusEn:'Zai Sha in the Spouse Palace',
 cnT:'灾煞在夫妻宫：感情易有突发波折，遇事稳住共担',enT:'Zai Sha in the Spouse Palace: Weathering Sudden Storms Together',
 cnD:'灾煞在夫妻宫多主感情或共同生活里易有突发波折、意外状况；重在遇事不慌、两人一起扛，外部突发事反而考验并稳固关系。',
 enD:'Zai Sha in the Spouse Palace suggests sudden setbacks in love or shared life. Stay calm and bear matters together, for outside surprises test and steady the bond.',
 cnL:'突发的难最怕两个人分心；你肯一起扛、不互相埋怨，风浪反而把感情绑得更紧。',
 enL:'Sudden hardship fears a divided couple; bear together without blame and the storm binds love tighter.',
 cnA:'有人一遇突发事就互相指责、各自飞；星曜是倾向，患难见真心也靠经营。',
 enA:'Some blame and scatter at sudden trouble; stars are tendency, while adversity reveals and needs care.',
 cnLog:['灾煞在夫妻宫，易有突发波折。','遇事不慌、共同承担。','患难稳固关系。','倾向描述，非绝对定论。'],
 enLog:['Zai Sha in Spouse means sudden setbacks.','Stay calm, bear together.','Adversity steadies the bond.','This is tendency, not an absolute verdict.'],
 cnStep:['突发事两人商量','不互相埋怨指责','共同面对、分担','稳住情绪','平时积累信任','以患难与共为要'],
 enStep:['Discuss sudden matters together','Do not blame one another','Face and share together','Steady emotions','Build trust in normal times','Rest on standing together'],
 cnMis:['遇事互相指责','各自打算、分心','情绪用事'],
 enMis:['Blaming at trouble','Self-serving, divided','Emotional reactions'],
 cnClose:'灾煞在夫妻宫，突发波折难免，贵在「稳住、共担、不埋怨」。一起扛，患难反而见真情。',
 enClose:'Zai Sha in the Spouse Palace makes sudden setbacks normal; stay calm, share and do not blame. Bear together so adversity reveals true love.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-zinvgong',focus:'灾煞在子女宫',focusEn:'Zai Sha in the Children Palace',
 cnT:'灾煞在子女宫：为子女安全多留心，看护到位防意外',enT:'Zai Sha in the Children Palace: Mindful Safety for Children',
 cnD:'灾煞在子女宫多主孩子活泼好动、容易磕碰出小意外，需在安全上多留心；重在看护到位、安全教育，不吓唬也不大意，培养孩子的安全意识。',
 enD:'Zai Sha in the Children Palace suggests active children prone to bumps and small mishaps, needing more attention to safety. Supervise well and teach safety, neither frightening nor careless, building their awareness.',
 cnL:'孩子是摔着长大的，但能防的意外得防；你把安全教到、看护到，比事后心疼强。',
 enL:'Children grow through falls, but preventable mishaps should be prevented; teach and supervise safety, better than later regret.',
 cnA:'有人看护粗心、或因怕出事过度限制；星曜是倾向，安全靠教育和到位看护。',
 enA:'Some supervise carelessly or over-restrict from fear; stars are tendency, while safety rests on teaching and good care.',
 cnLog:['灾煞在子女宫，孩子易磕碰意外。','看护到位、安全教育。','不吓唬不大意。','倾向描述，非绝对定论。'],
 enLog:['Zai Sha in Children means bumps and mishaps.','Supervise well, teach safety.','Neither frighten nor careless.','This is tendency, not an absolute verdict.'],
 cnStep:['居家外出看护到位','教孩子基本安全','排查隐患','不过度限制、也不大意','活动适龄','以平安成长为要'],
 enStep:['Supervise at home and away','Teach basic safety','Remove hazards','Neither over-restrict nor careless','Age-appropriate activity','Rest on safe growth'],
 cnMis:['看护粗心','因怕出事过度限制','不做安全教育'],
 enMis:['Careless supervision','Over-restricting from fear','No safety teaching'],
 cnClose:'灾煞在子女宫，孩子磕碰难免，重在「看护、教育、不大意」。安全意识从小养，意外就少。',
 enClose:'Zai Sha in the Children Palace makes bumps normal; supervise, teach and do not be careless. Build safety awareness early to reduce mishaps.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-caibogong',focus:'灾煞在财帛宫',focusEn:'Zai Sha in the Wealth Palace',
 cnT:'灾煞在财帛宫：钱财易有突发破耗，留应急、不冒险',enT:'Zai Sha in the Wealth Palace: Emergency Reserves, No Reckless Risk',
 cnD:'灾煞在财帛宫多主钱财上易有突发破耗、意外支出；重在留足应急钱、不冒险投资、不碰高息陷阱，遇到突发也不慌。',
 enD:'Zai Sha in the Wealth Palace suggests sudden depletion and unexpected expenses. Keep enough emergency money, avoid risky investment and high-interest traps so surprises do not panic you.',
 cnL:'意外花钱最考验家底；应急钱留足、风险远一点，突发事来了你才站得稳。',
 enL:'Sudden expenses test reserves; keep emergency money and distance risk so surprises find you steady.',
 cnA:'有人不留应急钱、还冒险逐高息，一遇突发就乱；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some keep no reserves and chase high interest, panicking at surprises; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['灾煞在财帛宫，钱财突发破耗。','留应急、不冒险。','远离高息陷阱。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Zai Sha in Wealth means sudden depletion.','Keep reserves, no reckless risk.','Avoid high-interest traps.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['留足应急资金','不冒险投资','远离高息骗局','买合适的保障','重大决策咨询持牌专业人士','以稳守为要'],
 enStep:['Keep enough emergency money','Avoid risky investment','Avoid high-interest scams','Buy suitable protection','Consult licensed professionals for big decisions','Rest on steady guarding'],
 cnMis:['不留应急钱','冒险逐高息','突发花钱就借贷'],
 enMis:['No emergency reserves','Chasing high interest with risk','Borrowing at sudden expenses'],
 cnClose:'灾煞在财帛宫，功课是「留应急、远风险」。守好家底、听持牌专业人士，突发破耗就乱不了你。',
 enClose:'Zai Sha in the Wealth Palace calls for reserves and distance from risk. Guard well and consult licensed professionals so sudden depletion does not disrupt you.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-jiegong',focus:'灾煞在疾厄宫',focusEn:'Zai Sha in the Health Palace',
 cnT:'灾煞在疾厄宫：防外伤急症，注意安全、早就医',enT:'Zai Sha in the Health Palace: Prevent Injury, Seek Early Care',
 cnD:'灾煞在疾厄宫多主需提防外伤、急症、突发身体状况；重在注意安全防护、规律生活，遇急性不适及时正规就医，不硬扛。',
 enD:'Zai Sha in the Health Palace suggests guarding against injury, acute conditions and sudden health matters. Mind safety, live regularly and seek timely formal care for acute discomfort, not toughing it out.',
 cnL:'外伤急症讲究快和稳；安全防护做在前、真出事不耽误，这是对自己负责。',
 enL:'Injury and acute conditions call for speed and steadiness; protect ahead and do not delay if something happens.',
 cnA:'有人对安全防护不在意、急症还硬扛；星曜是倾向，健康以正规就医为准。',
 enA:'Some ignore protection and tough out acute conditions; stars are tendency, while health relies on formal care.',
 cnLog:['灾煞在疾厄宫，防外伤急症。','注意安全、早就医。','不硬扛。','倾向非诊断，以正规就医为准。'],
 enLog:['Zai Sha in Health means guarding against injury.','Mind safety, seek early care.','Do not tough it out.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['注意人身安全防护','高危活动守规范','急症及时就诊','规律作息','按医生评估处理','以规范为要'],
 enStep:['Mind personal safety','Follow rules in high-risk activity','Seek timely care for acute conditions','Keep regular hours','Follow doctor assessment','Rest on proper care'],
 cnMis:['不在意防护','急症硬扛','拖延就诊'],
 enMis:['Ignoring protection','Toughing out acute conditions','Delaying care'],
 cnClose:'灾煞在疾厄宫，重在「防外伤、早就医」。安全做在前、急症不耽误，身体才稳妥。',
 enClose:'Zai Sha in the Health Palace calls for injury prevention and early care. Protect ahead and do not delay acute matters for steady health.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-qianyi',focus:'灾煞在迁移宫',focusEn:'Zai Sha in the Travel Palace',
 cnT:'灾煞在迁移宫：外出防意外，守交规、行程留余',enT:'Zai Sha in the Travel Palace: Prevent Mishaps, Leave Margin',
 cnD:'灾煞在迁移宫多主外出、通勤、旅行时要格外防意外；重在遵守交规、行程留余量、不疲劳赶路，注意人身财物安全。',
 enD:'Zai Sha in the Travel Palace suggests extra care against mishaps while commuting and traveling. Follow traffic rules, leave schedule margin, do not travel exhausted and mind personal and property safety.',
 cnL:'出门在外，意外多在赶和慌里发生；你把行程留宽、交规守好，平安就有底。',
 enL:'Away, mishaps arise in rushing and panic; widen the schedule and keep rules for safe travel.',
 cnA:'有人赶路抢时间、不守交规，易出状况；星曜是倾向，平安靠守规矩和余量。',
 enA:'Some rush and break traffic rules, prone to mishaps; stars are tendency, while safety rests on rules and margin.',
 cnLog:['灾煞在迁移宫，外出防意外。','守交规、行程留余。','不疲劳赶路、重安全。','倾向描述，非绝对定论。'],
 enLog:['Zai Sha in Travel means guarding against mishaps.','Follow rules, leave margin.','Do not travel exhausted, mind safety.','This is tendency, not an absolute verdict.'],
 cnStep:['遵守交通规则','行程留余量','不疲劳赶路','看管好财物','备应急预案','以平安为要'],
 enStep:['Follow traffic rules','Leave schedule margin','Do not travel exhausted','Mind belongings','Prepare contingencies','Rest on safe travel'],
 cnMis:['赶路抢时间','不守交规','行程排满无余'],
 enMis:['Rushing against time','Breaking traffic rules','Schedules packed, no margin'],
 cnClose:'灾煞在迁移宫，外出要「守规、留余、防意外」。不赶不慌，路才走得平安。',
 enClose:'Zai Sha in the Travel Palace calls for rules, margin and mishap prevention. Do not rush or panic for safe travel.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-puyigong',focus:'灾煞在仆役宫',focusEn:'Zai Sha in the Friends Palace',
 cnT:'灾煞在仆役宫：朋友之事易牵连，慎交友、守边界',enT:'Zai Sha in the Friends Palace: Choose Friends, Keep Boundaries',
 cnD:'灾煞在仆役宫多主朋友、部属的突发麻烦容易牵连你，遇人不淑更易受连累；重在慎重交友、守好边界，不替人担责、不盲从。',
 enD:'Zai Sha in the Friends Palace suggests friends and staff sudden troubles involving you, especially with poor company. Choose friends carefully, keep boundaries, do not take others liability or follow blindly.',
 cnL:'朋友的麻烦会不会烧到你，常看你交什么人、边界清不清；慎交、不盲从，就少受连累。',
 enL:'Whether friends troubles reach you depends on company and boundaries; choose well and do not follow blindly.',
 cnA:'有人讲义气不讲边界、替人背锅；星曜是倾向，朋友靠选择和分寸。',
 enA:'Some value loyalty over boundaries and take others blame; stars are tendency, while friends need choice and measure.',
 cnLog:['灾煞在仆役宫，朋友突发事易牵连。','慎交友、守边界。','不替人担责盲从。','倾向描述，非绝对定论。'],
 enLog:['Zai Sha in Friends means sudden troubles involve you.','Choose friends, keep boundaries.','Do not take liability or follow blindly.','This is tendency, not an absolute verdict.'],
 cnStep:['慎重选择朋友','守好钱财责任边界','不替人担保背锅','遇事独立判断','远离损友','以长久信任为要'],
 enStep:['Choose friends carefully','Keep money and liability boundaries','Do not guarantee or take blame','Judge matters independently','Avoid harmful company','Rest on long trust'],
 cnMis:['讲义气不讲边界','替人背锅','盲从朋友'],
 enMis:['Loyalty over boundaries','Taking others blame','Following friends blindly'],
 cnClose:'灾煞在仆役宫，要防「朋友牵连」。慎交友、守边界、不盲从，才不被拖累。',
 enClose:'Zai Sha in the Friends Palace guards against friends involving you. Choose well, keep boundaries and do not follow blindly to avoid being dragged down.'}
];
