// catchup 2026-09-12 第1组：月德前8宫（命/兄弟/夫妻/子女/财帛/疾厄/迁移/仆役）
module.exports=[
{cat:'fuzhu',slug:'ziwei-yuede-zai-minggong',focus:'月德在命宫',focusEn:'Yue De in the Life Palace',
 cnT:'月德在命宫：心性宽厚多逢凶化吉，贵人常在',enT:'Yue De in the Life Palace: A Forgiving Nature and Helpers',
 cnD:'月德是贵人星，在命宫多主为人宽厚、有包容，遇事常能逢凶化吉、得人搭把手；但贵人是助力不是替代，自己仍要走正道、肯努力。',
 enD:'Yue De is a mentor star; in the Life Palace it suggests a forgiving, tolerant nature, often turning misfortune around with help from others. Helpers aid but do not replace you, so keep walking the proper road and working.',
 cnL:'心宽的人像给别人留了门，路也就越走越宽；但门开着，自己也得往前走。',
 enL:'A broad-minded person keeps a door open for others and the road widens; yet with the door open, you still move forward.',
 cnA:'有人以为有贵人就可坐等，结果机会擦肩；星曜是倾向，贵人缘要配自己的本分与努力。',
 enA:'Some wait idly for mentors and chances pass; stars are tendency, and mentor luck pairs with your own duty and effort.',
 cnLog:['月德为贵人星，命宫心性宽厚。','遇事逢凶化吉、得人助。','贵人是助力不是替代。','倾向描述，非绝对定论。'],
 enLog:['Yue De is a mentor star; in Life one is forgiving.','Misfortune turns, help arrives.','Helpers aid not replace.','This is tendency, not an absolute verdict.'],
 cnStep:['保持宽厚包容的长处','珍惜贵人、感恩回报','自己仍走正道努力','遇事多往好处想、肯求助','不把贵人当依赖','以踏实为要'],
 enStep:['Keep the forgiving strength','Value mentors, repay kindness','Still walk the proper road and work','Stay positive, willing to ask help','Do not depend on mentors','Rest on grounded effort'],
 cnMis:['坐等贵人、自己不努力','把贵人缘当免努力金牌','有贵人却不感恩'],
 enMis:['Waiting for mentors without effort','Taking mentor luck as a free pass','Ungrateful for help'],
 cnClose:'月德在命宫是「宽厚逢凶、贵人常在」的好配置。心宽、感恩、肯努力，贵人才能长久为用。',
 enClose:'Yue De in the Life Palace is a fine sign of forgiveness and steady helpers. Stay broad, grateful and hardworking so mentors help for long.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-xiongdigong',focus:'月德在兄弟宫',focusEn:'Yue De in the Siblings Palace',
 cnT:'月德在兄弟宫：手足同辈多宽厚，遇事有人帮衬',enT:'Yue De in the Siblings Palace: Kind Peers and Support',
 cnD:'月德在兄弟宫多主兄弟姐妹、同辈朋友仁厚包容，关系和睦，遇事有人帮衬、能转圜；重在主动珍惜、彼此照应，别把宽厚当理所当然。',
 enD:'Yue De in the Siblings Palace suggests kind, tolerant siblings and peers with harmonious relations, offering help and room to turn matters around. Value them actively and look after one another, not taking kindness for granted.',
 cnL:'好手足像雨天里递来的伞；伞肯借你，你也得记得还、记得惜。',
 enL:'Good kin are like an umbrella handed in rain; lent to you, remember to return and cherish it.',
 cnA:'有人把同辈帮衬当本分、疏于回应，情分渐淡；星曜是倾向，关系靠双向珍惜。',
 enA:'Some take peer help as due and respond little, thinning affection; stars are tendency, while bonds need two-way care.',
 cnLog:['月德在兄弟宫，手足同辈仁厚。','关系和睦、遇事帮衬。','主动珍惜、彼此照应。','倾向描述，非绝对定论。'],
 enLog:['Yue De in Siblings means kind peers.','Harmonious relations, help in need.','Value actively, look after one another.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜仁厚的手足同辈','主动联系、彼此照应','受人帮衬知感恩','遇事好商量、多包容','不把宽厚当理所当然','以和睦为要'],
 enStep:['Value kind siblings and peers','Initiate contact, look after one another','Be grateful for help','Discuss matters, tolerate more','Do not take kindness for granted','Rest on harmony'],
 cnMis:['把帮衬当本分、不回应','疏于珍惜同辈关系','只受助、不助人'],
 enMis:['Taking help as due, no response','Neglecting peer relations','Only receiving, not giving'],
 cnClose:'月德在兄弟宫，好在「手足宽厚、遇事有帮」。双向珍惜、彼此照应，同辈才是长久的温暖。',
 enClose:'Yue De in the Siblings Palace blesses kind peers and help in need. Care two ways and look after one another so peers stay warm for long.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-fuqigong',focus:'月德在夫妻宫',focusEn:'Yue De in the Spouse Palace',
 cnT:'月德在夫妻宫：伴侣宽厚能包容，关系靠互相体谅',enT:'Yue De in the Spouse Palace: A Tolerant Partner and Mutual Grace',
 cnD:'月德在夫妻宫多主伴侣仁厚包容，关系有转圜余地、吵架能和好；但包容不是单方忍让。重在互相体谅、及时给台阶，把宽厚养在日常。',
 enD:'Yue De in the Spouse Palace suggests a kind, tolerant partner with room to repair and reconcile after quarrels. Tolerance is not one-sided yielding. Understand one another, offer a way off the hook in time and nurture kindness daily.',
 cnL:'好伴侣不是不吵架，而是吵完还肯给彼此台阶；台阶你递一次、我接一次，情分就续上了。',
 enL:'Good partners are not quarrel-free but still offer each other a way down; you offer, I accept, and the bond continues.',
 cnA:'有人把对方包容当软弱、得寸进尺，结果寒心；星曜是倾向，宽厚要双向才长久。',
 enA:'Some take a partners tolerance as weakness and push, chilling the heart; stars are tendency, while kindness must be two-way to last.',
 cnLog:['月德在夫妻宫，伴侣仁厚包容。','关系能转圜、吵后和好。','互相体谅、及时给台阶。','倾向描述，非绝对定论。'],
 enLog:['Yue De in Spouse means a kind, tolerant partner.','Room to repair, reconcile after quarrels.','Understand one another, offer a way down.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜伴侣的宽厚','吵架及时给台阶、不冷战','互相体谅、少计较','把包容养在日常','遇事好好沟通','以双向包容为要'],
 enStep:['Value the partners kindness','Offer a way down in time, avoid cold war','Understand one another, score-keep less','Nurture tolerance daily','Communicate well','Rest on two-way tolerance'],
 cnMis:['把包容当软弱、得寸进尺','只让对方单方忍让','吵后不给台阶、冷战'],
 enMis:['Taking tolerance as weakness, pushing','Letting only one side yield','No way down after quarrels, cold war'],
 cnClose:'月德在夫妻宫，难得「伴侣宽厚、关系能容」。互相体谅、台阶勤递，包容双向，感情才长久。',
 enClose:'Yue De in the Spouse Palace offers a tolerant partner and a forgiving bond. Understand one another, offer ways down and keep kindness two-way for lasting love.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-zinvgong',focus:'月德在子女宫',focusEn:'Yue De in the Children Palace',
 cnT:'月德在子女宫：子女仁厚多乖顺，教养以宽容引导',enT:'Yue De in the Children Palace: Kind Children and Gentle Guidance',
 cnD:'月德在子女宫多主子女仁厚包容、较为乖顺，亲子关系宽和；但宽容不是溺爱。重在以身作则、温柔引导，给孩子犯错和成长的空间。',
 enD:'Yue De in the Children Palace suggests kind, tolerant and fairly well-behaved children with a gentle bond. Forgiveness is not spoiling. Lead by example, guide softly and give room to err and grow.',
 cnL:'孩子是在被原谅里学会原谅的；你肯容他小错，他才长成宽厚的人。',
 enL:'Children learn forgiveness by being forgiven; tolerating small mistakes lets them grow kind.',
 cnA:'有人把宽和当纵容、没有规矩，或一味严厉；星曜是倾向，教养要宽容而有原则。',
 enA:'Some take gentleness as spoiling without rules, or stay harsh; stars are tendency, while parenting needs kindness with principles.',
 cnLog:['月德在子女宫，子女仁厚乖顺。','亲子宽和、宽容非溺爱。','以身作则、温柔引导。','倾向描述，非绝对定论。'],
 enLog:['Yue De in Children means kind, well-behaved children.','Gentle bond, forgiveness not spoiling.','Lead by example, guide softly.','This is tendency, not an absolute verdict.'],
 cnStep:['欣赏子女的仁厚','温柔引导、少苛责','宽容而有原则','给孩子犯错成长的空间','以身作则','以宽和亲子为要'],
 enStep:['Appreciate the child kindness','Guide softly, blame less','Be kind yet principled','Give room to err and grow','Lead by example','Rest on a gentle bond'],
 cnMis:['把宽容当溺爱、无规矩','一味严厉、不包容','忽视身教'],
 enMis:['Taking kindness as spoiling, no rules','Harsh without tolerance','Neglecting example'],
 cnClose:'月德在子女宫，孩子仁厚是福气。宽容有原则、温柔引导，亲子才在宽和里越长越亲。',
 enClose:'Yue De in the Children Palace makes kind children a blessing. Be kind yet principled and guide softly so the bond grows close.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-caibogong',focus:'月德在财帛宫',focusEn:'Yue De in the Wealth Palace',
 cnT:'月德在财帛宫：财源多贵人帮衬，取财宽厚有道',enT:'Yue De in the Wealth Palace: Helpers and Principled Income',
 cnD:'月德在财帛宫多主财源上有人帮衬、机会较顺，靠宽厚信誉聚财；但不是坐等之财。重在取之有道、惜福感恩，不贪不占。',
 enD:'Yue De in the Wealth Palace suggests help with income and smooth chances, gathering money through kindness and reputation. It is not money for the waiting. Earn with principle, be grateful and neither greedy nor grasping.',
 cnL:'宽厚的人路广，财也愿意往他那走；可财来了还得守道、还得惜。',
 enL:'Kind people have wide roads and money comes their way; yet with money, keep principle and cherish it.',
 cnA:'有人见财源顺就贪多、忘乎所以，结果反失；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some grow greedy when income is smooth and lose instead; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['月德在财帛宫，财源有贵人帮衬。','靠宽厚信誉聚财。','取之有道、惜福感恩。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Yue De in Wealth means help with income.','Gather money through kindness and reputation.','Earn with principle, be grateful.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['珍惜财源上的贵人','靠信誉宽厚经营','取财有道、不贪不占','重大决策咨询持牌专业人士','惜福、肯助人','以正道聚财为要'],
 enStep:['Value helpers with income','Operate through reputation and kindness','Earn with principle, not greedy','Consult licensed professionals for big decisions','Be grateful, willing to help','Rest on principled wealth'],
 cnMis:['财源顺就贪多忘形','把帮衬当坐等之财','忽视合规与风险'],
 enMis:['Growing greedy when income is smooth','Taking help as money for waiting','Ignoring compliance and risk'],
 cnClose:'月德在财帛宫，贵在「宽厚聚财、贵人相帮」。取之有道、惜福感恩，钱财决策听持牌专业人士。',
 enClose:'Yue De in the Wealth Palace values kind, helped income. Earn with principle, stay grateful and consult licensed professionals for money decisions.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-jiegong',focus:'月德在疾厄宫',focusEn:'Yue De in the Health Palace',
 cnT:'月德在疾厄宫：病中易逢良医，遇病有救应',enT:'Yue De in the Health Palace: Good Doctors and Recovery',
 cnD:'月德在疾厄宫多主生病时易遇好医生、逢凶化吉，恢复较顺；但有救应不等于不用治。重在早就医、信专业，按时治疗复查。',
 enD:'Yue De in the Health Palace suggests meeting good doctors during illness and turning misfortune around, with smooth recovery. Rescue does not mean no treatment. Seek early care, trust professionals and keep treatment and rechecks.',
 cnL:'病里最大的贵人是肯说实话的医生；遇到了就好好配合，别辜负这分救应。',
 enL:'The greatest mentor in illness is a truthful doctor; meeting one, cooperate well and do not waste the rescue.',
 cnA:'有人仗着有救应拖延、不规范治疗，结果反复；星曜是倾向，健康仍以正规就医为准。',
 enA:'Some delay on rescue and treat improperly, relapsing; stars are tendency, while health relies on formal care.',
 cnLog:['月德在疾厄宫，病逢良医、有救应。','恢复较顺、但仍需治疗。','早就医、信专业。','倾向非诊断，以正规就医为准。'],
 enLog:['Yue De in Health means good doctors and rescue.','Recovery smooth but treatment needed.','Seek early care, trust professionals.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['生病及时就诊','珍惜良医、好好配合','规范治疗、按时复查','不拖延、不自作主张','作息饮食养身','以医生方案为准'],
 enStep:['Seek timely care when ill','Value good doctors, cooperate well','Treat properly, recheck on time','Do not delay or decide alone','Nourish with routines and diet','Follow the doctor plan'],
 cnMis:['仗救应拖延治疗','不配合医嘱','把有救当不用就医'],
 enMis:['Delaying treatment on rescue','Not following orders','Taking rescue as no need for care'],
 cnClose:'月德在疾厄宫，是「病逢良医、遇凶有救」的好兆头。早就医、信专业、配合治疗，救应才守得住。',
 enClose:'Yue De in the Health Palace is a good sign of good doctors and rescue. Seek early care, trust professionals and cooperate so the rescue holds.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-qianyi',focus:'月德在迁移宫',focusEn:'Yue De in the Travel Palace',
 cnT:'月德在迁移宫：外出多遇好人，远行平安有照应',enT:'Yue De in the Travel Palace: Kind People and Safe Trips',
 cnD:'月德在迁移宫多主外出、远行时遇好人、有照应，路途较顺、逢麻烦能解；重在礼貌待人、出行有备，不把顺利当大意的理由。',
 enD:'Yue De in the Travel Palace suggests meeting kind people and receiving help away from home, with smooth trips and troubles resolved. Be polite, travel prepared and do not let smoothness breed carelessness.',
 cnL:'出门嘴巴甜一点、礼数足一点，肯帮你的人就多；但顺利时更要把准备做足。',
 enL:'Away, be warm and polite and more people help; yet in smooth times prepare even more.',
 cnA:'有人觉得一路顺就马虎、不做预案，结果遇状况；星曜是倾向，顺利靠礼貌也靠准备。',
 enA:'Some grow careless on smooth trips without plans and face trouble; stars are tendency, while smoothness rests on politeness and preparation.',
 cnLog:['月德在迁移宫，外出遇好人、有照应。','路途顺、麻烦能解。','礼貌待人、出行有备。','倾向描述，非绝对定论。'],
 enLog:['Yue De in Travel means kind people and help away.','Smooth trips, troubles resolve.','Be polite, travel prepared.','This is tendency, not an absolute verdict.'],
 cnStep:['外出礼貌待人','行程提前准备、留余量','珍惜路上的好人','遇麻烦冷静求助','不因顺利而大意','以平安出行为要'],
 enStep:['Be polite away from home','Plan trips ahead with margin','Value kind people on the road','Seek help calmly in trouble','Do not grow careless when smooth','Rest on safe travel'],
 cnMis:['顺利就马虎、无预案','把好人照应当必然','外出失礼数'],
 enMis:['Careless on smooth trips, no plans','Taking kind help as inevitable','Rude away from home'],
 cnClose:'月德在迁移宫，外出「遇好人、有照应」。礼貌、有备、不马虎，路才走得顺、走得安。',
 enClose:'Yue De in the Travel Palace blesses trips with kind people and help. Be polite, prepared and careful so the road stays smooth and safe.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-puyigong',focus:'月德在仆役宫',focusEn:'Yue De in the Friends Palace',
 cnT:'月德在仆役宫：朋友部属多仁厚，待人宽厚得人心',enT:'Yue De in the Friends Palace: Kind Friends and Goodwill',
 cnD:'月德在仆役宫多主朋友、部属仁厚包容，待人宽厚则得人心、众人愿助；重在真诚带人、知人感恩，不把别人的好心当软弱。',
 enD:'Yue De in the Friends Palace suggests kind, tolerant friends and staff, and treating people well wins hearts and willing help. Lead sincerely, know people and be grateful, not mistaking kindness for weakness.',
 cnL:'你怎么待人，人就怎么待你；宽厚是会回声的，你给出去，它绕一圈又回来。',
 enL:'How you treat others is how they treat you; kindness echoes, given out and returning around.',
 cnA:'有人对下属朋友刻薄、还怪无人帮；星曜是倾向，人心是用宽厚换来的。',
 enA:'Some are harsh to staff and friends yet wonder at no help; stars are tendency, while hearts are won by kindness.',
 cnLog:['月德在仆役宫，朋友部属仁厚。','宽厚待人、得人心。','真诚带人、知感恩。','倾向描述，非绝对定论。'],
 enLog:['Yue De in Friends means kind friends and staff.','Kind treatment wins hearts.','Lead sincerely, be grateful.','This is tendency, not an absolute verdict.'],
 cnStep:['对朋友部属宽厚','真诚带人、言而有信','感恩他人的好','知人善任、守边界','不刻薄、不占人便宜','以得人心为要'],
 enStep:['Be kind to friends and staff','Lead sincerely, keep word','Be grateful for kindness','Know people, keep boundaries','Do not be harsh or take advantage','Rest on goodwill'],
 cnMis:['待人刻薄、怪无人助','把好心当软弱','只索取、不真诚'],
 enMis:['Harsh to others, wondering at no help','Mistaking kindness for weakness','Only taking, not sincere'],
 cnClose:'月德在仆役宫，好在「朋友仁厚、宽厚得人」。真诚、感恩、守边界，人脉才暖、才长久。',
 enClose:'Yue De in the Friends Palace blesses kind friends and goodwill. Be sincere, grateful and keep boundaries so connections stay warm and lasting.'}
];
