// catchup 2026-09-11 第5组：大耗后3（官禄/迁移/福德）+ 天空3（官禄/田宅/福德）+ 解神2（疾厄/财帛）
module.exports=[
{cat:'fuzhu',slug:'ziwei-dahao-zai-guanlugong',focus:'大耗在官禄宫',focusEn:'Da Hao in the Career Palace',
 cnT:'大耗在官禄宫：事业易空耗精力，找对方法比蛮干强',enT:'Da Hao in the Career Palace: Avoiding Empty Effort',
 cnD:'大耗在官禄宫多主事业上精力投入多、却易劳而少功，忙在琐事、消耗在无效努力；重在定期复盘、抓重点、会借力，把劲使在产出上。',
 enD:'Da Hao in the Career Palace suggests much effort poured into work with little result, busy on trifles and drained by ineffective striving. Review regularly, focus on priorities and learn to leverage help, directing energy toward output.',
 cnL:'蛮干像踩空转的轮子，使了大力却不往前走；先抬起轮子看看卡在哪，再使劲不迟。',
 enL:'Brute force is like spinning wheels, great force with no movement; lift up and see the block before pushing.',
 cnA:'有人只拼时长、不看方法，结果身心俱疲、成绩平平；星曜是倾向，方法和复盘能省掉大量消耗。',
 enA:'Some only grind hours without method, ending exhausted with average results; stars are tendency, while method and review save much depletion.',
 cnLog:['大耗在官禄宫，事业易劳而少功。','忙琐事、无效努力是主因。','定期复盘、抓重点、会借力。','倾向描述，非绝对定论。'],
 enLog:['Da Hao in Career means much work with little result.','Trifles and ineffective striving are causes.','Review regularly, focus, leverage help.','This is tendency, not an absolute verdict.'],
 cnStep:['定期复盘、分清轻重','把精力投向高产出的事','减少无效忙碌','学会借力与分工','张弛有度、避免倦怠','以结果导向为要'],
 enStep:['Review regularly, set priorities','Direct energy to high-output work','Cut ineffective busyness','Leverage help and divide labor','Balance effort, avoid burnout','Rest on being result-oriented'],
 cnMis:['只拼时长、不讲方法','忙而不果也不复盘','把蛮干当努力'],
 enMis:['Only grinding hours without method','Busy without result or review','Taking brute force for effort'],
 cnClose:'大耗在官禄宫，要破「忙而少功」的耗。会复盘、抓重点、善借力，事业才不被空耗拖垮。',
 enClose:'Da Hao in the Career Palace breaks the drain of busy work with little gain. Review, focus and leverage help so work is not dragged down by empty effort.'},

{cat:'fuzhu',slug:'ziwei-dahao-zai-qianyi',focus:'大耗在迁移宫',focusEn:'Da Hao in the Travel Palace',
 cnT:'大耗在迁移宫：在外奔波易损耗，出行规划要做足',enT:'Da Hao in the Travel Palace: Plan Trips to Cut Loss',
 cnD:'大耗在迁移宫多主外出、奔波中易有时间、金钱或精力的损耗，如临时改程、超支、白跑；重在出行前规划、留余量、备预案，把意外损耗降到低。',
 enD:'Da Hao in the Travel Palace suggests loss of time, money or energy during trips and rushing about, such as changed plans, overspending or fruitless travel. Plan ahead, leave margin and prepare contingencies to keep unexpected loss low.',
 cnL:'出门像过河，提前看好水、备好船，才不至于半路手忙脚乱、白白折损。',
 enL:'Travel is like crossing a river; check the water and ready the boat ahead, avoiding mid-way scramble and needless loss.',
 cnA:'有人说走就走、毫无预案，常为临时状况多花冤枉钱；星曜是倾向，规划和余量能省掉奔波之耗。',
 enA:'Some leave on a whim without plans, often paying for emergencies; stars are tendency, while planning and margin save the loss of rushing.',
 cnLog:['大耗在迁移宫，外出奔波易有损耗。','临时改程、超支、白跑常见。','出行规划、留余量、备预案。','倾向描述，非绝对定论。'],
 enLog:['Da Hao in Travel means loss during trips and rushing.','Changed plans, overspending and fruitless travel are common.','Plan ahead, leave margin, prepare contingencies.','This is tendency, not an absolute verdict.'],
 cnStep:['出行前做好行程规划','预算留余量','备好应急方案与证件','减少无谓奔波','临时状况冷静处理','以稳妥出行为要'],
 enStep:['Plan the itinerary ahead','Leave margin in budget','Prepare contingencies and documents','Reduce needless rushing','Handle emergencies calmly','Rest on steady travel'],
 cnMis:['说走就走、毫无预案','行程排满、不留余量','把奔波之耗当难免'],
 enMis:['Leaving on a whim without plans','Packed schedules with no margin','Taking travel loss as inevitable'],
 cnClose:'大耗在迁移宫，功课在「规划、余量、预案」。出行有备，奔波之耗才少，路上也从容。',
 enClose:'Da Hao in the Travel Palace calls for planning, margin and contingencies. Travel prepared so rushing loss shrinks and the road stays calm.'},

{cat:'fuzhu',slug:'ziwei-dahao-zai-fudegong',focus:'大耗在福德宫',focusEn:'Da Hao in the Blessings Palace',
 cnT:'大耗在福德宫：精神易被琐事耗尽，养心要会断舍离',enT:'Da Hao in the Blessings Palace: Guarding Mental Energy',
 cnD:'大耗在福德宫多主精神能量易被琐事、杂念和过度思虑消耗，明明没做什么却心累；重在做减法、断舍离、给心神留白，把有限的心力留给要紧的人和事。',
 enD:'Da Hao in the Blessings Palace suggests mental energy drained by trifles, stray thoughts and over-worry, feeling heart-tired despite doing little. Subtract, let go and leave the mind blank, reserving limited heart for what and who matter.',
 cnL:'心神的容量有限，什么都往里装，最后哪件都装不深；定期清空，才装得下真正重要的。',
 enL:'Mental capacity is limited; filling it with everything leaves nothing deep; clear it regularly to hold what truly matters.',
 cnA:'有人什么都操心、什么都不舍，结果长期内耗；星曜是倾向，做减法和留白是养精神的实在功夫。',
 enA:'Some worry over everything and let nothing go, long drained; stars are tendency, while subtracting and leaving blank are practical ways to nourish the spirit.',
 cnLog:['大耗在福德宫，精神易被琐事杂念消耗。','过度思虑、心累是主因。','做减法、断舍离、心神留白。','倾向描述，非绝对定论。'],
 enLog:['Da Hao in Blessings means spirit drained by trifles and stray thoughts.','Over-worry and heart-tiredness are causes.','Subtract, let go, leave the mind blank.','This is tendency, not an absolute verdict.'],
 cnStep:['识别消耗心神的琐事','学会拒绝与放下','减少过度思虑','给独处留白的时间','把心力留给重要的人','以心安为要'],
 enStep:['Identify what drains the mind','Learn to refuse and let go','Reduce over-worry','Set aside quiet time alone','Reserve heart for important people','Rest on a calm heart'],
 cnMis:['什么都操心、不做减法','杂念缠身、长期内耗','把心累当矫情、不理会'],
 enMis:['Worrying over everything, not subtracting','Stray thoughts, long inner friction','Dismissing heart-tiredness'],
 cnClose:'大耗在福德宫，要防「精神被琐事耗空」。勤做减法、会放下、留空白，心不累，人才有福。',
 enClose:'Da Hao in the Blessings Palace guards against a spirit emptied by trifles. Subtract, let go and leave blank, keeping the heart untired and the person blessed.'},

{cat:'fuzhu',slug:'ziwei-tiankong-zai-guanlugong',focus:'天空在官禄宫',focusEn:'Tian Kong in the Career Palace',
 cnT:'天空在官禄宫：想法多易落空，事业要落地务实',enT:'Tian Kong in the Career Palace: Grounding Ideas in Reality',
 cnD:'天空在官禄宫多主想法多、点子新，却易停在构想、落地不足，事业也偏精神性或多变动；重在把空想拆成可执行的步骤、小步验证，让创意真正变现。',
 enD:'Tian Kong in the Career Palace suggests many fresh ideas that may stay conceptual with weak execution, and work leaning spiritual or changeable. Break visions into executable steps and validate in small moves so creativity truly delivers.',
 cnL:'点子像风筝，线得攥在手里、一步步收，才不会只在天上飘、落不了地。',
 enL:'Ideas are like kites; hold the string and reel it step by step, lest they only drift and never land.',
 cnA:'有人沉迷构想、迟迟不动，结果一事无成；星曜是倾向，落地与执行才是把想法变成事业的关键。',
 enA:'Some dwell in visions and never act, achieving little; stars are tendency, while grounding and execution turn ideas into a career.',
 cnLog:['天空在官禄宫，想法多、易停留构想。','事业偏精神性、多变动。','拆步骤、小步验证、重落地。','倾向描述，非绝对定论。'],
 enLog:['Tian Kong in Career means many ideas that may stay conceptual.','Work leans spiritual or changeable.','Break into steps, validate small, ground it.','This is tendency, not an absolute verdict.'],
 cnStep:['把大构想拆成小目标','先做最小可行的尝试','用结果验证、及时调整','避免只规划不行动','发挥创意又补执行','以落地为要'],
 enStep:['Break big visions into small goals','Make the smallest viable attempt first','Validate with results, adjust in time','Avoid planning without action','Use creativity and add execution','Rest on grounding'],
 cnMis:['想法多、行动少','追求完美构想、迟迟不落地','把变动当借口不坚持'],
 enMis:['Many ideas, little action','Chasing perfect visions, never landing','Using change as an excuse not to persist'],
 cnClose:'天空在官禄宫，创意是天赋，但要「落地务实、小步快跑」。把空想变成行动，事业才有结果。',
 enClose:'Tian Kong in the Career Palace makes creativity a gift, but ground it and run small and fast. Turn visions into action for real career results.'},

{cat:'fuzhu',slug:'ziwei-tiankong-zai-tianzhaigong',focus:'天空在田宅宫',focusEn:'Tian Kong in the Property Palace',
 cnT:'天空在田宅宫：居家置产易有变数，决策宜稳看合同',enT:'Tian Kong in the Property Palace: Cautious, Contract-Safe Decisions',
 cnD:'天空在田宅宫多主居家、搬迁或置产易有变数、计划赶不上变化，也可能对家居有理想化期待；重在决策务实、留余地，走正规途径、看清合同，不冲动置业。',
 enD:'Tian Kong in the Property Palace suggests variables in home, moving or purchase, plans overtaken by change, and perhaps idealized expectations. Decide practically with margin, use formal channels, read contracts and avoid impulsive buying.',
 cnL:'置产是大事，别让想象中的房子替你做决定；落到合同和数字上看清，才稳。',
 enL:'Property is a major matter; do not let an imagined home decide for you; ground it in contracts and figures for steadiness.',
 cnA:'有人冲动下定、事后发现不合适或合同有坑；星曜是倾向，房产决策要正规、以书面合同和专业意见为准。',
 enA:'Some commit on impulse and later find mismatch or contract pitfalls; stars are tendency, while property decisions need formality and rely on written contracts and professional advice.',
 cnLog:['天空在田宅宫，居家置产易有变数。','易理想化、冲动置业。','务实留余、正规途径、看清合同。','以书面合同和专业意见为准。'],
 enLog:['Tian Kong in Property means variables in home and purchase.','Prone to idealizing and impulsive buying.','Be practical with margin, use formal channels, read contracts.','Rely on written contracts and professional advice.'],
 cnStep:['置业前想清真实需求','预算留余地、不冲动','走正规途径、核实产权','逐条看清书面合同','必要时咨询专业人士','以家庭实际为要'],
 enStep:['Clarify real needs before buying','Leave budget margin, avoid impulse','Use formal channels, verify title','Read the written contract line by line','Consult professionals when needed','Rest on family reality'],
 cnMis:['冲动下定、不留余地','忽视产权核实与合同','对家居过度理想化'],
 enMis:['Committing on impulse without margin','Ignoring title checks and contracts','Over-idealizing the home'],
 cnClose:'天空在田宅宫，决策要「稳、实、看合同」。置产走正规途径、留有余地，才不被变数打乱。',
 enClose:'Tian Kong in the Property Palace calls for steady, practical, contract-safe decisions. Buy through formal channels with margin so variables do not disrupt you.'},

{cat:'fuzhu',slug:'ziwei-tiankong-zai-fudegong',focus:'天空在福德宫',focusEn:'Tian Kong in the Blessings Palace',
 cnT:'天空在福德宫：精神世界丰富，心安也要落到日常',enT:'Tian Kong in the Blessings Palace: Rich Inner Life, Grounded Peace',
 cnD:'天空在福德宫多主精神世界丰富、好哲思与想象，直觉强；但也容易飘、易莫名空虚、不接地气。重在把精神追求落到日常小事、关系和行动里，内心才安稳。',
 enD:'Tian Kong in the Blessings Palace suggests a rich inner life, loving philosophy and imagination with strong intuition. One may drift, feel inexplicably empty or ungrounded. Land spiritual seeking in daily small things, relationships and action for stable peace.',
 cnL:'心灵像会飞的鸟，天空任它翱翔，但也得有棵能落回的树；日常就是那棵树。',
 enL:'The soul is a flying bird free in the sky, yet it needs a tree to return to; the everyday is that tree.',
 cnA:'有人一味追求精神境界、脱离现实，反而更孤独空虚；星曜是倾向，把心安落在具体的人和事上才踏实。',
 enA:'Some pursue only spiritual heights apart from reality, growing lonely and empty; stars are tendency, while grounding peace in concrete people and matters brings steadiness.',
 cnLog:['天空在福德宫，精神世界丰富、直觉强。','易飘、易空虚、不接地气。','把追求落到日常、关系与行动。','倾向描述，非绝对定论。'],
 enLog:['Tian Kong in Blessings means a rich inner life and strong intuition.','Prone to drift, emptiness, ungrounded.','Land seeking in daily life, relationships and action.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜丰富的内心与直觉','用日常规律给自己落地','经营具体的关系','把想法变成小行动','多接触自然与生活','以踏实心安为要'],
 enStep:['Value the rich inner life and intuition','Ground yourself with daily routines','Cultivate concrete relationships','Turn thoughts into small actions','Engage with nature and life','Rest on grounded peace'],
 cnMis:['脱离现实、一味追求精神','想法多却不落地','把飘和空虚当高深'],
 enMis:['Apart from reality, pursuing only spirit','Many thoughts, never grounded','Taking drift and emptiness as depth'],
 cnClose:'天空在福德宫，内在丰富是礼物，但心安要「落回日常」。把精神追求种进关系和行动里，才不空。',
 enClose:'Tian Kong in the Blessings Palace makes inner richness a gift, but peace must return to daily life. Plant spiritual seeking in relationships and action so it is not empty.'},

{cat:'fuzhu',slug:'ziwei-jieshen-zai-jiegong',focus:'解神在疾厄宫',focusEn:'Jie Shen in the Health Palace',
 cnT:'解神在疾厄宫：逢病有解是好事，规范治疗仍不能省',enT:'Jie Shen in the Health Palace: Good Recovery, Proper Treatment',
 cnD:'解神主化解、消灾，在疾厄宫多提示病势易缓解、逢凶有救、恢复较顺；但「能解」不等于不用治。重在早就医、规范治疗、按时复查，把好运和科学结合。',
 enD:'Jie Shen governs resolving and dispelling misfortune; in the Health Palace it suggests illness eases, rescue comes and recovery is smooth. Being resolvable does not mean no treatment. Seek early care, treat properly and recheck on time, combining good fortune with science.',
 cnL:'有解是福气，可药还得按时吃、医生还得按时看；把好运当偷懒的理由，福气也会溜走。',
 enL:'Resolution is a blessing, yet take medicine and see the doctor on time; treating good fortune as a reason to slack lets the blessing slip.',
 cnA:'有人见恢复顺就擅自停药、不复查，结果反复；星曜是倾向，健康的根本仍是规范就医。',
 enA:'Some stop medicine and skip rechecks when recovery is smooth and relapse; stars are tendency, while the root of health remains proper care.',
 cnLog:['解神在疾厄宫，病易缓解、逢凶有救。','恢复较顺、但不能不治疗。','早就医、规范治、按时复查。','倾向非诊断，以正规就医为准。'],
 enLog:['Jie Shen in Health means illness eases, rescue comes.','Recovery is smooth but treatment is still needed.','Seek early care, treat properly, recheck on time.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['善用恢复顺的好时机','规范治疗、遵医嘱','按时复查、不擅自停药','作息饮食配合','有新症状及时就诊','以医生方案为准'],
 enStep:['Use the smooth recovery window well','Treat properly, follow orders','Recheck on time, do not stop medicine','Support with routines and diet','Seek timely care for new symptoms','Follow the doctor plan'],
 cnMis:['恢复顺就擅自停药','把能解当不用治','忽视复查随访'],
 enMis:['Stopping medicine when recovery is smooth','Taking resolvable as no treatment','Ignoring rechecks and follow-up'],
 cnClose:'解神在疾厄宫是「逢病有解」的好兆头，但更要规范就医、不偷懒。治疗复查做到位，好运气才守得住。',
 enClose:'Jie Shen in the Health Palace is a good sign of resolvable illness, yet seek proper care without slacking. Do treatment and rechecks fully so good fortune holds.'},

{cat:'fuzhu',slug:'ziwei-jieshen-zai-caibogong',focus:'解神在财帛宫',focusEn:'Jie Shen in the Wealth Palace',
 cnT:'解神在财帛宫：破财纠纷多能化解，处理走正规途径',enT:'Jie Shen in the Wealth Palace: Resolving Loss Through Proper Channels',
 cnD:'解神在财帛宫多提示破财、财务纠纷多有化解转圜的余地，逢凶能缓；但化解要靠正规途径、留好凭据，而非私下硬来。重在冷静处理、依法依约、及时沟通。',
 enD:'Jie Shen in the Wealth Palace suggests room to resolve financial loss and disputes, misfortune able to ease. Resolution relies on proper channels and kept records, not private force. Handle calmly, by law and contract, and communicate in time.',
 cnL:'钱上的纠纷像死结，越急越扯越紧；退一步、找对正规门路，结反而解得开。',
 enL:'Money disputes are like tight knots; haste pulls them tighter; step back and find proper channels and the knot loosens.',
 cnA:'有人为破财冲动行事、不留凭据，反而被动；星曜是倾向，财务处理要正规，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some act on impulse over loss without records and end on the back foot; stars are tendency, while financial handling must be proper, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['解神在财帛宫，破财纠纷多有转圜。','化解靠正规途径、留凭据。','冷静处理、依法依约。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Jie Shen in Wealth means room to resolve loss and disputes.','Resolution relies on proper channels and records.','Handle calmly, by law and contract.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['遇财务纠纷先冷静','保留合同与往来凭据','走正规途径沟通解决','必要时寻求专业法律帮助','不冲动、不私下硬来','以依法依约为要'],
 enStep:['Stay calm in financial disputes','Keep contracts and transaction records','Resolve through proper channels','Seek professional legal help when needed','Avoid impulse and private force','Rest on law and contract'],
 cnMis:['破财就冲动行事','不留凭据、私下硬来','把能化解当不用处理'],
 enMis:['Acting on impulse over loss','No records, private force','Taking resolvable as needing no action'],
 cnClose:'解神在财帛宫，纠纷破财「多有化解之机」。冷静、留据、走正规途径，必要时找专业人士，才转得圜、不吃亏。',
 enClose:'Jie Shen in the Wealth Palace means loss and disputes often have room to resolve. Stay calm, keep records, use proper channels and seek professionals when needed to turn things around.'}
];
