// catchup 2026-09-13 第4组：天才前8宫
module.exports=[
{cat:'fuzhu',slug:'ziwei-tiancai-zai-xiongdigong',focus:'天才在兄弟宫',focusEn:'Tian Cai in the Siblings Palace',
 cnT:'天才在兄弟宫：手足同辈多聪明，近智者受益',enT:'Tian Cai in the Siblings Palace: Clever Peers Around You',
 cnD:'天才在兄弟宫多主兄弟姐妹、同辈朋友聪明有想法，能在交流中互相启发；重在珍惜聪明的同辈、彼此学习，也提醒自己多听不同意见，别只比高低。',
 enD:'Tian Cai in the Siblings Palace suggests clever, thoughtful siblings and peers who inspire one another. Value them and learn together, and listen to different views rather than only comparing.',
 cnL:'和聪明人在一起，你也会被推着长进；可三人行的本事，是肯向人学。',
 enL:'With clever people you are pushed to grow; the skill is willingness to learn.',
 cnA:'有人见同辈聪明就嫉妒或攀比；星曜是倾向，聪明圈靠互相成就。',
 enA:'Some envy or compete with clever peers; stars are tendency, while clever circles thrive on mutual growth.',
 cnLog:['天才在兄弟宫，同辈聪明有想法。','交流中互相启发。','彼此学习、听意见。','倾向描述，非绝对定论。'],
 enLog:['Tian Cai in Siblings means clever peers.','You inspire one another.','Learn together, listen to views.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜聪明的同辈','多交流、互相启发','肯向人学习','不嫉妒攀比','听不同意见','以共同长进为要'],
 enStep:['Value clever peers','Exchange and inspire','Be willing to learn','Do not envy or compete','Listen to different views','Rest on shared growth'],
 cnMis:['嫉妒聪明同辈','只攀比、不学习','听不进意见'],
 enMis:['Envying clever peers','Competing, not learning','Not hearing views'],
 cnClose:'天才在兄弟宫，好在「身边多聪明人」。肯学、不嫉妒，同辈就是你的助力。',
 enClose:'Tian Cai in the Siblings Palace blesses clever peers. Be willing to learn and not envy so peers help you.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-fuqigong',focus:'天才在夫妻宫',focusEn:'Tian Cai in the Spouse Palace',
 cnT:'天才在夫妻宫：伴侣聪明有想法，智性相处重尊重',enT:'Tian Cai in the Spouse Palace: A Clever, Respected Partner',
 cnD:'天才在夫妻宫多主伴侣聪明、有主见，关系里有智性吸引；重在彼此尊重、遇事讲道理，欣赏对方的聪明也包容差异，不争口舌输赢。',
 enD:'Tian Cai in the Spouse Palace suggests a clever, opinioned partner with intellectual attraction. Respect one another, reason through matters, appreciate the mind and accept differences without arguing to win.',
 cnL:'两个聪明人相处，赢在肯讲理、肯认输；尊重比说服更养感情。',
 enL:'Two clever people thrive on reason and willingness to yield; respect beats persuasion.',
 cnA:'有人和聪明伴侣处处争高低、不服软；星曜是倾向，长久靠尊重。',
 enA:'Some compete with a clever partner and never yield; stars are tendency, while lasting love needs respect.',
 cnLog:['天才在夫妻宫，伴侣聪明有主见。','智性吸引、讲道理。','尊重差异、不争输赢。','倾向描述，非绝对定论。'],
 enLog:['Tian Cai in Spouse means a clever, opinioned partner.','Intellectual attraction, reason.','Respect differences, do not fight to win.','This is tendency, not an absolute verdict.'],
 cnStep:['欣赏伴侣的聪明','遇事商量讲道理','不争口舌高低','包容不同看法','共同成长','以尊重为要'],
 enStep:['Appreciate the partners mind','Reason through matters','Do not argue to win','Accept differing views','Grow together','Rest on respect'],
 cnMis:['处处争高低','不服软、只讲理到伤感情','不尊重主见'],
 enMis:['Competing everywhere','Yielding not, reason hurting love','Not respecting views'],
 cnClose:'天才在夫妻宫，伴侣聪明是好事。尊重、讲理、包容，智性的感情才长久。',
 enClose:'Tian Cai in the Spouse Palace blesses a clever partner. Respect, reason and accept for lasting intellectual love.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-zinvgong',focus:'天才在子女宫',focusEn:'Tian Cai in the Children Palace',
 cnT:'天才在子女宫：孩子聪明早慧，因材施教戒拔苗',enT:'Tian Cai in the Children Palace: A Bright Child, Well Guided',
 cnD:'天才在子女宫多主孩子聪明、领悟快、早慧；重在因材施教、保护好奇心，引导踏实和品德，不拔苗助长，小聪明更要养大格局。',
 enD:'Tian Cai in the Children Palace suggests a bright, quick child. Teach to aptitude, protect curiosity and guide groundedness and character without pushing too hard, for cleverness needs a large frame.',
 cnL:'聪明孩子最怕被催着跑、或聪明没用在正处；你顺着天性、教踏实，路才宽。',
 enL:'Bright children fear being rushed or cleverness misused; follow nature and teach groundedness.',
 cnA:'有人因孩子聪明就炫耀、拔苗，或忽视品德；星曜是倾向，成才靠引导。',
 enA:'Some show off and push bright children, neglecting character; stars are tendency, while growth needs guidance.',
 cnLog:['天才在子女宫，孩子聪明早慧。','因材施教、护好奇。','养品德踏实、不拔苗。','倾向描述，非绝对定论。'],
 enLog:['Tian Cai in Children means a bright child.','Teach to aptitude, protect curiosity.','Build character, do not push too hard.','This is tendency, not an absolute verdict.'],
 cnStep:['保护孩子好奇心','因材施教、不攀比','培养踏实和品德','不拔苗助长','多陪伴引导','以成才为要'],
 enStep:['Protect curiosity','Teach to aptitude, no comparing','Build groundedness and character','Do not push too hard','Accompany and guide','Rest on growth'],
 cnMis:['拔苗助长','只重聪明、不重品德','炫耀攀比'],
 enMis:['Pushing too hard','Cleverness over character','Showing off, comparing'],
 cnClose:'天才在子女宫，孩子聪明是礼物。因材施教、养品德、不拔苗，早慧才走得远。',
 enClose:'Tian Cai in the Children Palace makes brightness a gift. Teach to aptitude, build character and do not push so it goes far.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-caibogong',focus:'天才在财帛宫',focusEn:'Tian Cai in the Wealth Palace',
 cnT:'天才在财帛宫：靠才智点子生财，脑力变现守正道',enT:'Tian Cai in the Wealth Palace: Earning Through Talent and Ideas',
 cnD:'天才在财帛宫多主靠聪明才智、点子技能生财，脑力是你的财源；重在把聪明打磨成真本事、走正道，不投机取巧，守正才能长久。',
 enD:'Tian Cai in the Wealth Palace suggests earning through cleverness, ideas and skill, the mind being your source. Polish cleverness into real ability and walk upright, not seeking shortcuts, for the upright last.',
 cnL:'点子能换钱，但靠的是把聪明练成本事、用在正处；投机取巧走不远。',
 enL:'Ideas pay when cleverness becomes real skill used well; shortcuts do not last.',
 cnA:'有人仗聪明投机、想一夜暴富，反被聪明误；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some rely on cleverness to speculate and get-rich-quick, outwitted by their own cleverness; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['天才在财帛宫，才智点子生财。','聪明练成真本事。','走正道、不投机。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Cai in Wealth means earning through talent.','Polish cleverness into ability.','Walk upright, no speculation.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['打磨专业才智技能','把点子落地成真本事','走正道、不投机取巧','持续学习增值','重大决策咨询持牌专业人士','以长久为要'],
 enStep:['Polish professional talent','Turn ideas into real skill','Walk upright, no shortcuts','Keep learning to add value','Consult licensed professionals for big decisions','Rest on lasting success'],
 cnMis:['仗聪明投机','只耍小聪明','想一夜暴富'],
 enMis:['Speculating on cleverness','Only petty cleverness','Get-rich-quick thinking'],
 cnClose:'天才在财帛宫，靠才智生财是好事。把聪明练成本事、走正道，财源才长久。',
 enClose:'Tian Cai in the Wealth Palace blesses earning through talent. Polish cleverness into skill and walk upright for lasting income.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-jiegong',focus:'天才在疾厄宫',focusEn:'Tian Cai in the Health Palace',
 cnT:'天才在疾厄宫：聪明易多虑，放松神经少内耗',enT:'Tian Cai in the Health Palace: An Active Mind in Need of Rest',
 cnD:'天才在疾厄宫多主聪明但脑子闲不住、容易多虑、神经紧张，影响睡眠和身体；重在学会放松、规律作息，给大脑留白，必要时寻求专业帮助。',
 enD:'Tian Cai in the Health Palace suggests a clever mind that cannot rest, prone to overthinking and nervous tension affecting sleep and body. Learn to relax, keep regular hours and give the mind blank, seeking professional help when needed.',
 cnL:'聪明人最大的累是想太多；你肯让脑子歇、把事放下，身体才不跟着紧。',
 enL:'The clever tire most from overthinking; let the mind rest and body eases.',
 cnA:'有人遇事反复琢磨、停不下来；星曜是倾向，身心的放松要主动练。',
 enA:'Some ruminate and cannot stop; stars are tendency, while relaxation is actively practiced.',
 cnLog:['天才在疾厄宫，聪明易多虑。','神经紧张、影响睡眠。','学会放松、给脑留白。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Cai in Health means an overthinking mind.','Nervous tension affects sleep.','Relax, give the mind blank.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['规律作息、保睡眠','练习放松冥想','减少睡前思虑','适度运动','必要时寻求专业帮助','以身心放松为要'],
 enStep:['Regular hours, protect sleep','Relax and meditate','Less worry before bed','Exercise moderately','Seek professional help when needed','Rest on relaxed mind and body'],
 cnMis:['脑子闲不住、多虑','神经紧张不放松','硬扛失眠'],
 enMis:['Mind cannot rest, overthinking','Nervous tension, not relaxing','Toughing out insomnia'],
 cnClose:'天才在疾厄宫，聪明也需「会放松、不多虑」。给大脑留白、规律生活，身心才轻安。',
 enClose:'Tian Cai in the Health Palace reminds clever minds to relax and not overthink. Give the mind blank and live regularly for ease.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-qianyi',focus:'天才在迁移宫',focusEn:'Tian Cai in the Travel Palace',
 cnT:'天才在迁移宫：外出靠机智应变，利学习见世面',enT:'Tian Cai in the Travel Palace: Quick-Witted Away, Learning the World',
 cnD:'天才在迁移宫多主外出时头脑灵活、善于应变，也利在外学习、见世面；重在把聪明用在观察学习上，礼貌谦逊，越走越开阔。',
 enD:'Tian Cai in the Travel Palace suggests a quick, adaptive mind away from home, favoring learning and broadening horizons. Use cleverness to observe and learn, be polite and humble, and widen with travel.',
 cnL:'行万里路靠的是眼到、脑到；你肯观察学习、放下身段，世面就成了本事。',
 enL:'Travel far with open eyes and mind; observe, learn and stay humble.',
 cnA:'有人外出爱耍小聪明、不谦逊；星曜是倾向，见识靠虚心。',
 enA:'Some show petty cleverness away without humility; stars are tendency, while insight needs openness.',
 cnLog:['天才在迁移宫，外出机智应变。','利学习、见世面。','观察学习、谦逊。','倾向描述，非绝对定论。'],
 enLog:['Tian Cai in Travel means quick wits away.','Favors learning and horizons.','Observe, learn, stay humble.','This is tendency, not an absolute verdict.'],
 cnStep:['外出多观察思考','善应变、讲礼貌','虚心向人学习','记录见闻','保护好安全','以开阔为要'],
 enStep:['Observe and think away','Adapt, be polite','Learn humbly','Record what you see','Mind safety','Rest on broadening'],
 cnMis:['耍小聪明','不谦逊、不学习','外出浮躁'],
 enMis:['Petty cleverness','Not humble, not learning','Restless away'],
 cnClose:'天才在迁移宫，外出「机智、好学、谦逊」。把见闻变本事，路越走越宽。',
 enClose:'Tian Cai in the Travel Palace calls for quick wits, learning and humility. Turn experience into ability as the road widens.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-puyigong',focus:'天才在仆役宫',focusEn:'Tian Cai in the Friends Palace',
 cnT:'天才在仆役宫：善交聪明朋友，用人所长重协作',enT:'Tian Cai in the Friends Palace: Clever Friends and Good Collaboration',
 cnD:'天才在仆役宫多主朋友、部属中多聪明有能的人，善于用人所长；重在欣赏他人才能、分工协作，自己也保持学习，不嫉才、不独揽。',
 enD:'Tian Cai in the Friends Palace suggests clever, able friends and staff, using their strengths. Appreciate talent, divide work and collaborate, keep learning and do not envy ability or take all credit.',
 cnL:'能聚聪明人的人，靠的是胸襟；你欣赏人、会协作，事就成得大。',
 enL:'Those who gather clever people rely on openness; appreciate and collaborate.',
 cnA:'有人见部属朋友有才就忌惮、压制；星曜是倾向，团队靠容人。',
 enA:'Some fear and suppress able associates; stars are tendency, while teams need openness.',
 cnLog:['天才在仆役宫，身边多聪明有能。','用人所长、重协作。','不嫉才、不独揽。','倾向描述，非绝对定论。'],
 enLog:['Tian Cai in Friends means clever, able associates.','Use strengths, collaborate.','Do not envy or take all credit.','This is tendency, not an absolute verdict.'],
 cnStep:['欣赏他人才能','合理分工协作','不嫉才、肯放权','保持学习','真诚待人','以团队成就为要'],
 enStep:['Appreciate others talent','Divide work and collaborate','Do not envy, delegate','Keep learning','Be sincere','Rest on team success'],
 cnMis:['忌惮压制人才','独揽功劳','不会协作'],
 enMis:['Fearing and suppressing talent','Taking all credit','Not collaborating'],
 cnClose:'天才在仆役宫，善聚聪明人。欣赏、协作、不嫉才，团队才走得远。',
 enClose:'Tian Cai in the Friends Palace gathers clever people. Appreciate, collaborate and do not envy so the team goes far.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-guanlugong',focus:'天才在官禄宫',focusEn:'Tian Cai in the Career Palace',
 cnT:'天才在官禄宫：靠才智立足，利动脑创意的工作',enT:'Tian Cai in the Career Palace: Thriving on Intellect and Creativity',
 cnD:'天才在官禄宫多主靠聪明才智立足，适合动脑、创意、技术、策划类工作；重在把聪明转化为专业深度，踏实积累，不恃才傲物。',
 enD:'Tian Cai in the Career Palace suggests thriving on intellect, suited to thinking, creative, technical or planning work. Turn cleverness into professional depth, build steadily and do not be arrogant about talent.',
 cnL:'聪明是入场券，专业深度和踏实才是护城河；你肯沉下心，才智才撑得起事业。',
 enL:'Cleverness is the ticket, depth and steadiness the moat; settle down for talent to support work.',
 cnA:'有人自恃聪明、眼高手低、不踏实；星曜是倾向，事业靠真功夫。',
 enA:'Some rely on cleverness with high eyes and low hands; stars are tendency, while career rests on real skill.',
 cnLog:['天才在官禄宫，才智立足。','利动脑创意工作。','聪明转专业、不傲物。','倾向描述，非绝对定论。'],
 enLog:['Tian Cai in Career means thriving on intellect.','Suited to thinking and creative work.','Turn cleverness into depth, not arrogant.','This is tendency, not an absolute verdict.'],
 cnStep:['选动脑创意的方向','把聪明练成专业深度','踏实积累、不浮躁','持续学习','与同事协作','以专业为要'],
 enStep:['Choose an intellectual, creative path','Turn cleverness into depth','Build steadily, not restless','Keep learning','Collaborate with colleagues','Rest on professionalism'],
 cnMis:['恃才傲物','眼高手低、不踏实','只耍小聪明'],
 enMis:['Arrogant about talent','High eyes, low hands','Only petty cleverness'],
 cnClose:'天才在官禄宫，靠才智做事业。聪明加专业深度、踏实不傲，才立得稳、走得远。',
 enClose:'Tian Cai in the Career Palace builds work on intellect. Add depth and steadiness without arrogance to stand firm and go far.'}
];
