// catchup 2026-09-12 第5组：天巫父母 + 天使7宫（命/兄弟/夫妻/子女/财帛/迁移/官禄）
module.exports=[
{cat:'fuzhu',slug:'ziwei-tianwu-zai-fumugong',focus:'天巫在父母宫',focusEn:'Tian Wu in the Parents Palace',
 cnT:'天巫在父母宫：长辈多贵气提携，得庇荫机缘',enT:'Tian Wu in the Parents Palace: Supportive Elders and Chances',
 cnD:'天巫在父母宫多主父母、长辈有贵气、愿提携你，也可能有馈赠遗产之缘；重在孝敬感恩、走正规手续，不把长辈庇荫当理所当然。',
 enD:'Tian Wu in the Parents Palace suggests dignified elders willing to lift you, perhaps with gift or inheritance chances. Be filial and grateful, use formal procedures and do not take shelter for granted.',
 cnL:'长辈的提携是福，你肯感恩、肯走正道，这分机缘才长久。',
 enL:'Elder support is a blessing; be grateful and walk upright so the chance lasts.',
 cnA:'有人把长辈提携当本分、或遗产不走手续；星曜是倾向，亲情与钱财都要守规矩。',
 enA:'Some take elder support as due or skip inheritance procedures; stars are tendency, while kinship and money need rules.',
 cnLog:['天巫在父母宫，长辈提携、有庇荫。','可能有馈赠遗产缘。','孝敬感恩、正规手续。','倾向描述，非绝对定论。'],
 enLog:['Tian Wu in Parents means supportive elders and shelter.','Perhaps gift or inheritance chances.','Be filial, use formal procedures.','This is tendency, not an absolute verdict.'],
 cnStep:['孝敬感恩长辈','珍惜提携、知回报','馈赠遗产走正规手续','主动关心陪伴','不把庇荫当本分','以家和为要'],
 enStep:['Be filial and grateful','Value support, repay kindness','Use formal procedures for gifts','Care and accompany actively','Do not take shelter as due','Rest on family harmony'],
 cnMis:['把提携当本分','遗产不走手续','疏于孝敬'],
 enMis:['Taking support as due','Skipping inheritance procedures','Neglecting filial piety'],
 cnClose:'天巫在父母宫，难得「长辈提携、有庇荫」。感恩、孝敬、手续正，机缘才守得住。',
 enClose:'Tian Wu in the Parents Palace offers supportive elders and shelter. Be grateful, filial and proper so chances hold.'},

{cat:'fuzhu',slug:'ziwei-tianshi-zai-minggong',focus:'天使在命宫',focusEn:'Tian Shi in the Life Palace',
 cnT:'天使在命宫：一生多奔波破耗，守稳务实少折腾',enT:'Tian Shi in the Life Palace: A Life of Motion, Guarded Steadiness',
 cnD:'天使主破耗、奔波，在命宫多主人生起伏多、爱折腾，精力和资源易在变动中耗散；重在务实守稳、重大决定三思，把劲用在长远。',
 enD:'Tian Shi governs depletion and travel; in the Life Palace it suggests a life of ups and downs with a love of change, where energy and resources scatter in motion. Be grounded, think thrice on big decisions and aim effort long-term.',
 cnL:'爱折腾的人像老换方向的船，划得久却走不远；定个方向、稳住，才不白费力气。',
 enL:'A restless person is like a boat changing course, rowing long yet going far; set a direction and steady it.',
 cnA:'有人把奔波当努力、不断推倒重来，结果一事无成；星曜是倾向，守稳比折腾更难也更值。',
 enA:'Some take motion as effort and keep starting over, achieving little; stars are tendency, while steadiness is harder and worth more.',
 cnLog:['天使主破耗奔波，命宫多起伏。','精力易在变动中耗散。','务实守稳、三思而行。','倾向描述，非绝对定论。'],
 enLog:['Tian Shi governs depletion and motion; in Life many ups and downs.','Energy scatters in change.','Be grounded, think thrice.','This is tendency, not an absolute verdict.'],
 cnStep:['定个长远方向','重大决定三思','减少无谓折腾','守住已有积累','张弛有度','以稳为要'],
 enStep:['Set a long-term direction','Think thrice on big decisions','Cut needless restlessness','Guard what you have','Balance effort','Rest on steadiness'],
 cnMis:['不断推倒重来','把奔波当努力','没有长性'],
 enMis:['Constant starting over','Taking motion as effort','No persistence'],
 cnClose:'天使在命宫，要防「折腾耗散」。定方向、守稳、三思，人生才不白忙。',
 enClose:'Tian Shi in the Life Palace guards against restless depletion. Set direction, steady and think thrice so life is not toiled in vain.'},

{cat:'fuzhu',slug:'ziwei-tianshi-zai-xiongdigong',focus:'天使在兄弟宫',focusEn:'Tian Shi in the Siblings Palace',
 cnT:'天使在兄弟宫：手足之事易耗神，帮衬量力守边界',enT:'Tian Shi in the Siblings Palace: Help Within Boundaries',
 cnD:'天使在兄弟宫多主为兄弟姐妹、同辈朋友的事奔波耗神，帮衬容易没个度；重在重情义也守边界，救急不救穷、量力而行。',
 enD:'Tian Shi in the Siblings Palace suggests rushing and fretting over siblings and peers, with help easily overdone. Value bonds yet keep boundaries, aid emergencies not dependence and measure capacity.',
 cnL:'手足有难肯帮忙，但不能把别人的事全扛成自己的；边界守住，情分才长久。',
 enL:'Help kin in need, but do not make others matters fully yours; keep boundaries so affection lasts.',
 cnA:'有人为同辈两肋插刀、把自己拖垮；星曜是倾向，帮人要量力。',
 enA:'Some go all out for peers and drag themselves down; stars are tendency, so help within capacity.',
 cnLog:['天使在兄弟宫，手足事耗神。','帮衬易过度。','重情义、守边界。','倾向描述，非绝对定论。'],
 enLog:['Tian Shi in Siblings means fretting over kin matters.','Help easily overdone.','Value bonds, keep boundaries.','This is tendency, not an absolute verdict.'],
 cnStep:['手足事先量力','救急不救穷','守好精力金钱边界','不替人挑担','亲兄弟明算账','以长久情分为要'],
 enStep:['Measure capacity before helping kin','Aid emergencies not dependence','Keep energy and money boundaries','Do not carry others loads','Keep money clear among kin','Rest on lasting affection'],
 cnMis:['帮衬无度','替同辈挑担、拖垮自己','边界不清'],
 enMis:['Help without limit','Carrying peers loads, dragging self down','Unclear boundaries'],
 cnClose:'天使在兄弟宫，手足情要顾，但「帮衬有度、守边界」。量力、明算账，才不被拖垮。',
 enClose:'Tian Shi in the Siblings Palace calls for kin care with bounded help. Measure and keep money clear so you are not dragged down.'},

{cat:'fuzhu',slug:'ziwei-tianshi-zai-fuqigong',focus:'天使在夫妻宫',focusEn:'Tian Shi in the Spouse Palace',
 cnT:'天使在夫妻宫：感情易有消耗波折，用心经营不折腾',enT:'Tian Shi in the Spouse Palace: Weathering Emotional Depletion',
 cnD:'天使在夫妻宫多主感情里易有奔波、消耗与小波折，久处需更用心；重在认定了就好好经营、少折腾，彼此体谅、及时修复。',
 enD:'Tian Shi in the Spouse Palace suggests motion, depletion and small hardships in love, needing more care over time. Once committed, manage well with less restlessness, understand one another and repair in time.',
 cnL:'感情经不起反复折腾，你肯定心、肯经营，波折就成了磨合而不是消耗。',
 enL:'Love cannot bear constant restlessness; settle and care, and hardships become mutual adjustment rather than depletion.',
 cnA:'有人感情里反复动摇、推倒重来，把情分耗尽；星曜是倾向，长久靠定心经营。',
 enA:'Some waver and start over in love, exhausting affection; stars are tendency, while lasting bonds need settled care.',
 cnLog:['天使在夫妻宫，感情易消耗波折。','需定心、少折腾。','彼此体谅、及时修复。','倾向描述，非绝对定论。'],
 enLog:['Tian Shi in Spouse means emotional depletion and hardships.','Settle, restlessness less.','Understand one another, repair in time.','This is tendency, not an absolute verdict.'],
 cnStep:['认定后定心经营','减少折腾动摇','小波折及时沟通修复','彼此体谅','共同面对困难','以长久为要'],
 enStep:['Settle and manage once committed','Reduce restlessness and wavering','Repair small hardships through talk','Understand one another','Face difficulty together','Rest on lasting bonds'],
 cnMis:['感情反复折腾','动摇不定、不修复','把对方消耗当无所谓'],
 enMis:['Constant restlessness in love','Wavering, not repairing','Taking partners depletion lightly'],
 cnClose:'天使在夫妻宫，要防「情分被折腾耗尽」。定心、体谅、勤修复，感情才长久。',
 enClose:'Tian Shi in the Spouse Palace guards against affection exhausted by restlessness. Settle, understand and repair for lasting love.'},

{cat:'fuzhu',slug:'ziwei-tianshi-zai-zinvgong',focus:'天使在子女宫',focusEn:'Tian Shi in the Children Palace',
 cnT:'天使在子女宫：为子女易奔波操心，放手不包办',enT:'Tian Shi in the Children Palace: Care Without Taking Over',
 cnD:'天使在子女宫多主为孩子的事奔波、操心耗神，容易包办；重在尽心引导而不越界，培养孩子独立，先照顾好自己。',
 enD:'Tian Shi in the Children Palace suggests rushing and fretting over children, easy to take over. Guide without overstepping, foster independence and care for yourself first.',
 cnL:'为子女操心得有个度，你越包办、孩子越难独立，自己也耗竭。',
 enL:'Worry over children needs limit; the more you take over, the less independent they grow and the more you drain.',
 cnA:'有人为孩子操碎心、全包办，亲子都累；星曜是倾向，教养要会放手。',
 enA:'Some fret fully and take over, tiring both; stars are tendency, while parenting needs letting go.',
 cnLog:['天使在子女宫，为子女奔波操心。','易包办、耗神。','引导不越界、培养独立。','倾向描述，非绝对定论。'],
 enLog:['Tian Shi in Children means rushing and fretting.','Easy to take over, draining.','Guide without overstepping, foster independence.','This is tendency, not an absolute verdict.'],
 cnStep:['为子女尽心、不越界','培养孩子独立','减少包办代劳','照顾好自己的状态','引导为主','以健康亲子为要'],
 enStep:['Do your best without overstepping','Foster independence','Reduce taking over','Care for your own state','Guide primarily','Rest on healthy kinship'],
 cnMis:['包办一切','为子女失去自我','不培养独立'],
 enMis:['Taking over everything','Losing self for children','Not fostering independence'],
 cnClose:'天使在子女宫，为子女操心难免，但「尽心不包办、会放手」。孩子独立、父母不耗竭。',
 enClose:'Tian Shi in the Children Palace makes worry normal, but guide without taking over and let go. Children grow independent and parents avoid burnout.'},

{cat:'fuzhu',slug:'ziwei-tianshi-zai-caibogong',focus:'天使在财帛宫',focusEn:'Tian Shi in the Wealth Palace',
 cnT:'天使在财帛宫：钱财易破耗，守财规划防跑漏',enT:'Tian Shi in the Wealth Palace: Guarding Against Depletion',
 cnD:'天使在财帛宫多主钱财易有意外破耗、跑漏，存得辛苦；重在记账守财、留应急钱，不冲动、不冒险投资。',
 enD:'Tian Shi in the Wealth Palace suggests unexpected depletion and leaks, money saved with effort. Track accounts, keep emergency money and avoid impulse or risky investment.',
 cnL:'钱来得辛苦、去得容易时，先把漏洞堵住、把应急钱留好，再谈别的。',
 enL:'When money comes hard and goes easy, first plug leaks and keep emergency money.',
 cnA:'有人不规划、冲动花钱或冒险，结果总空；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some do not plan, spend impulsively or risk and end empty; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['天使在财帛宫，钱财易破耗。','记账守财、留应急钱。','不冲动、不冒险。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Shi in Wealth means unexpected depletion.','Track accounts, keep emergency money.','No impulse, no risky investment.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['记账、查跑漏','留应急资金','避免冲动消费','远离冒险投资高息陷阱','重大决策咨询持牌专业人士','以守财为要'],
 enStep:['Track accounts, find leaks','Keep emergency money','Avoid impulse spending','Avoid risky investment and high-interest traps','Consult licensed professionals for big decisions','Rest on guarding wealth'],
 cnMis:['不规划、冲动花钱','冒险投资','钱财跑漏不查'],
 enMis:['No plan, impulse spending','Risky investment','Not checking leaks'],
 cnClose:'天使在财帛宫，功课在「守财、堵漏」。规划、留余、远陷阱，财务决策听持牌专业人士。',
 enClose:'Tian Shi in the Wealth Palace calls for guarding money and plugging leaks. Plan, keep reserves, avoid traps and consult licensed professionals.'},

{cat:'fuzhu',slug:'ziwei-tianshi-zai-qianyi',focus:'天使在迁移宫',focusEn:'Tian Shi in the Travel Palace',
 cnT:'天使在迁移宫：在外奔波易损耗，出行规划稳着来',enT:'Tian Shi in the Travel Palace: Guarded, Planned Trips',
 cnD:'天使在迁移宫多主外出、奔波多、易有损耗和小意外；重在出行前规划、留余量、注意安全，不疲劳赶路。',
 enD:'Tian Shi in the Travel Palace suggests much motion away with depletion and small mishaps. Plan ahead, leave margin, mind safety and do not travel exhausted.',
 cnL:'出门在外，安全和余量最要紧；你把行程留宽一点，奔波就少折损。',
 enL:'Away, safety and margin matter most; widen the schedule and rushing causes less loss.',
 cnA:'有人行程排满、疲劳赶路，易出状况；星曜是倾向，稳妥靠规划。',
 enA:'Some pack schedules and travel exhausted, prone to mishaps; stars are tendency, while steadiness comes from planning.',
 cnLog:['天使在迁移宫，在外奔波损耗。','规划、留余、重安全。','不疲劳赶路。','倾向描述，非绝对定论。'],
 enLog:['Tian Shi in Travel means motion and depletion away.','Plan, leave margin, mind safety.','Do not travel exhausted.','This is tendency, not an absolute verdict.'],
 cnStep:['出行提前规划','行程留余量','注意人身财物安全','不疲劳赶路','备应急预案','以平安为要'],
 enStep:['Plan trips ahead','Leave schedule margin','Mind personal and property safety','Do not travel exhausted','Prepare contingencies','Rest on safe travel'],
 cnMis:['行程排满','疲劳赶路','无预案、不重安全'],
 enMis:['Schedules packed','Travel exhausted','No plan, safety ignored'],
 cnClose:'天使在迁移宫，在外奔波要「稳、宽、安全」。规划留余、不硬赶，路才平安。',
 enClose:'Tian Shi in the Travel Palace calls for steady, roomy and safe travel. Plan with margin, do not force through and stay safe.'},

{cat:'fuzhu',slug:'ziwei-tianshi-zai-guanlugong',focus:'天使在官禄宫',focusEn:'Tian Shi in the Career Palace',
 cnT:'天使在官禄宫：事业多波折耗力，稳扎稳打少变动',enT:'Tian Shi in the Career Palace: Steady Work Through Hardships',
 cnD:'天使在官禄宫多主事业上波折、变动多、精力易耗，频繁跳槽折腾更不利；重在稳扎稳打、深耕一行，把困难当磨砺。',
 enD:'Tian Shi in the Career Palace suggests work hardships and changes with energy easily depleted, frequent job shifts being worse. Work steadily, deepen in one field and treat difficulty as tempering.',
 cnL:'事业最怕老换山头，刚扎下根又拔起；选定一行深耕，波折反而养本事。',
 enL:'Careers most fear changing hills, rooted then pulled up; choose a field and deepen, hardships build skill.',
 cnA:'有人一遇不顺就跳槽、推倒重来，结果总在原地；星曜是倾向，深耕比折腾更出成果。',
 enA:'Some change jobs at every hardship and stay in place; stars are tendency, while deepening yields more than restlessness.',
 cnLog:['天使在官禄宫，事业波折耗力。','变动多、频繁跳槽不利。','稳扎稳打、深耕一行。','倾向描述，非绝对定论。'],
 enLog:['Tian Shi in Career means work hardships and depletion.','Many changes, frequent shifts hurt.','Work steadily, deepen in one field.','This is tendency, not an absolute verdict.'],
 cnStep:['选定方向、深耕一行','遇困难稳住、不冲动跳槽','减少无效折腾','持续积累专业','张弛有度防倦怠','以长远成果为要'],
 enStep:['Choose a direction, deepen in one field','Steady through difficulty, no impulsive shifts','Cut ineffective restlessness','Keep building expertise','Balance to prevent burnout','Rest on long-term results'],
 cnMis:['频繁跳槽折腾','遇挫就推倒重来','不深耕、无长性'],
 enMis:['Frequent job shifts','Starting over at every setback','No deepening or persistence'],
 cnClose:'天使在官禄宫，要防「事业被波折折腾耗光」。稳扎稳打、深耕一行，成果才出得来。',
 enClose:'Tian Shi in the Career Palace guards against work exhausted by restless hardships. Steady and deepen so results come.'}
];
