// catchup 2026-09-13 第5组：天才后3 + 天伤3 + 劫煞2
module.exports=[
{cat:'fuzhu',slug:'ziwei-tiancai-zai-tianzhaigong',focus:'天才在田宅宫',focusEn:'Tian Cai in the Property Palace',
 cnT:'天才在田宅宫：治家有巧思，聪明布置会规划',enT:'Tian Cai in the Property Palace: Clever, Well-Planned Home',
 cnD:'天才在田宅宫多主持家有巧思、善于规划布置，把家里安排得井井有条；重在把聪明用在改善生活上，也和家人商量，置产走正规途径。',
 enD:'Tian Cai in the Property Palace suggests clever home management and planning, arranging things well. Use cleverness to improve life, consult family and use formal channels for property.',
 cnL:'家也可以靠脑子经营；巧思加商量，日子过得又顺又暖。',
 enL:'A home can be run with the mind; cleverness and consultation make life smooth.',
 cnA:'有人只按自己想法折腾家、不商量；星曜是倾向，置产以正规合同和专业意见为准。',
 enA:'Some arrange the home alone without consulting; stars are tendency, while property relies on formal contracts and advice.',
 cnLog:['天才在田宅宫，治家有巧思。','善规划布置。','和家人商量、置产正规。','置产以正规合同和专业意见为准。'],
 enLog:['Tian Cai in Property means clever home care.','Good planning and arrangement.','Consult family, formal property channels.','Rely on formal contracts and professional advice.'],
 cnStep:['用心规划居家','巧思改善生活','和家人商量','置产走正规途径','保持整洁实用','以舒心为要'],
 enStep:['Plan the home with care','Use cleverness to improve life','Consult family','Use formal channels for property','Keep it tidy and practical','Rest on comfort'],
 cnMis:['只按己意折腾','不商量','置产不走正规途径'],
 enMis:['Arranging alone','Not consulting','Property without formal channels'],
 cnClose:'天才在田宅宫，治家有巧思是好事。会规划、肯商量、走正规路，家才舒心。',
 enClose:'Tian Cai in the Property Palace blesses clever home care. Plan, consult and use formal channels for a comfortable home.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-fudegong',focus:'天才在福德宫',focusEn:'Tian Cai in the Blessings Palace',
 cnT:'天才在福德宫：心思聪慧好哲思，会想也会放下',enT:'Tian Cai in the Blessings Palace: A Clever Mind That Also Lets Go',
 cnD:'天才在福德宫多主聪明、爱思考、有哲思趣味，但也容易想太多；重在享受思考的乐趣、不过度反刍，学会放下，给心留闲。',
 enD:'Tian Cai in the Blessings Palace suggests a clever, thoughtful mind with a taste for philosophy, yet prone to overthinking. Enjoy thinking without excessive rumination, learn to let go and leave the mind leisure.',
 cnL:'会想是本事，会放下是智慧；脑子聪明，更要懂得给它放假。',
 enL:'Thinking is ability, letting go wisdom; a clever mind needs holidays.',
 cnA:'有人聪明反被聪明累、反复琢磨；星曜是倾向，心安靠平衡。',
 enA:'Some are wearied by their own cleverness and ruminate; stars are tendency, while peace needs balance.',
 cnLog:['天才在福德宫，聪慧好哲思。','防想太多。','会思考、也会放下。','倾向描述，非绝对定论。'],
 enLog:['Tian Cai in Blessings means a clever, thoughtful mind.','Guard against overthinking.','Think and also let go.','This is tendency, not an absolute verdict.'],
 cnStep:['享受思考乐趣','不过度反刍','练习放下','培养闲情爱好','必要时寻求专业帮助','以心安为要'],
 enStep:['Enjoy thinking','Do not ruminate excessively','Practice letting go','Cultivate leisure interests','Seek professional help when needed','Rest on a calm heart'],
 cnMis:['想太多、反刍','聪明自累','心不得闲'],
 enMis:['Overthinking, ruminating','Wearied by own cleverness','No mental leisure'],
 cnClose:'天才在福德宫，聪明更要「会放下、不反刍」。给心留闲，智慧才养出安宁。',
 enClose:'Tian Cai in the Blessings Palace reminds clever minds to let go and not ruminate. Leave leisure so wisdom yields peace.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-fumugong',focus:'天才在父母宫',focusEn:'Tian Cai in the Parents Palace',
 cnT:'天才在父母宫：长辈聪明有见识，智性传承知感恩',enT:'Tian Cai in the Parents Palace: Wise Elders and Gratitude',
 cnD:'天才在父母宫多主父母、长辈聪明有见识，能在思想学问上影响你；重在珍惜长辈的智慧、多请教、知感恩，把好的东西传下去。',
 enD:'Tian Cai in the Parents Palace suggests clever, knowledgeable elders who influence your thinking. Value their wisdom, seek advice, be grateful and pass on what is good.',
 cnL:'有见识的长辈是一本活书；你肯读、肯传，智慧就不会断。',
 enL:'Knowledgeable elders are living books; read and pass on so wisdom continues.',
 cnA:'有人忽视长辈的见识、不耐烦；星曜是倾向，传承靠感恩。',
 enA:'Some ignore elders wisdom impatiently; stars are tendency, while passing on needs gratitude.',
 cnLog:['天才在父母宫，长辈聪明有见识。','思想学问上影响你。','多请教、知感恩。','倾向描述，非绝对定论。'],
 enLog:['Tian Cai in Parents means wise elders.','They influence your thinking.','Seek advice, be grateful.','This is tendency, not an absolute verdict.'],
 cnStep:['多向长辈请教','珍惜他们的见识','感恩、孝敬','把好的传承下去','耐心陪伴','以家和为要'],
 enStep:['Seek elders advice','Value their knowledge','Be grateful and filial','Pass on what is good','Accompany patiently','Rest on family harmony'],
 cnMis:['忽视长辈见识','不耐烦、不请教','不感恩'],
 enMis:['Ignoring elders wisdom','Impatient, not asking','Not grateful'],
 cnClose:'天才在父母宫，长辈有见识是福。多请教、懂感恩、肯传承，智慧才不断。',
 enClose:'Tian Cai in the Parents Palace blesses wise elders. Seek advice, be grateful and pass on so wisdom continues.'},

{cat:'fuzhu',slug:'ziwei-tianshang-zai-minggong',focus:'天伤在命宫',focusEn:'Tian Shang in the Life Palace',
 cnT:'天伤在命宫：一生防外伤，安全意识放第一',enT:'Tian Shang in the Life Palace: Guarding Against Injury',
 cnD:'天伤主外伤、损耗，在命宫多主人生路上要格外防磕碰、外伤等意外；重在安全第一、不逞强，高危活动守规范，受伤及时处理。',
 enD:'Tian Shang governs external injury; in the Life Palace it calls for extra care against bumps and wounds. Put safety first, do not show off, follow rules in risky activity and treat injuries promptly.',
 cnL:'外伤多在逞强和大意时来；安全守在前、不硬来，能少受很多罪。',
 enL:'Injuries come in showing off and carelessness; put safety first.',
 cnA:'有人逞强好胜、不把安全当回事；星曜是倾向，安全靠习惯。',
 enA:'Some show off and ignore safety; stars are tendency, while safety rests on habits.',
 cnLog:['天伤主外伤，命宫防磕碰。','安全第一、不逞强。','受伤及时处理。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Shang governs injury; in Life guard wounds.','Safety first, do not show off.','Treat injuries promptly.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['安全意识放第一','高危活动守规范','不逞强、不蛮干','受伤及时正规处理','做好防护','以平安为要'],
 enStep:['Put safety first','Follow rules in risky activity','Do not show off','Treat injuries through formal care','Use protection','Rest on safety'],
 cnMis:['逞强、不重安全','高危蛮干','外伤不处理'],
 enMis:['Showing off, ignoring safety','Reckless in risky activity','Not treating injuries'],
 cnClose:'天伤在命宫，功课是「防外伤、重安全」。不逞强、守规范，人生少受皮肉之苦。',
 enClose:'Tian Shang in the Life Palace calls for injury prevention and safety. Do not show off and follow rules to avoid harm.'},

{cat:'fuzhu',slug:'ziwei-tianshang-zai-xiongdigong',focus:'天伤在兄弟宫',focusEn:'Tian Shang in the Siblings Palace',
 cnT:'天伤在兄弟宫：同辈外伤事关心，帮忙有度防拖累',enT:'Tian Shang in the Siblings Palace: Care, Within Bounds',
 cnD:'天伤在兄弟宫多主兄弟姐妹、同辈朋友的外伤意外需要关心，帮忙时也容易耗神；重在有情有义、量力而行，守好边界。',
 enD:'Tian Shang in the Siblings Palace suggests caring for peers injuries, with help easily draining you. Be loyal, measure capacity and keep boundaries.',
 cnL:'同辈受伤肯关心，但别把别人的事全扛成自己的；边界守住，情分才久。',
 enL:'Care for injured peers but do not make matters fully yours; keep boundaries.',
 cnA:'有人帮衬无度、把自己拖垮；星曜是倾向，帮忙要量力。',
 enA:'Some help without limit and drain themselves; stars are tendency, so help within capacity.',
 cnLog:['天伤在兄弟宫，同辈外伤关心。','帮忙易耗神。','量力、守边界。','倾向描述，非绝对定论。'],
 enLog:['Tian Shang in Siblings means caring for peers injuries.','Help can drain you.','Measure capacity, keep boundaries.','This is tendency, not an absolute verdict.'],
 cnStep:['关心受伤同辈','量力帮忙','守好精力边界','不替人挑担','鼓励正规处理','以长久为要'],
 enStep:['Care for injured peers','Help within capacity','Keep energy boundaries','Do not carry others loads','Encourage formal care','Rest on lasting bonds'],
 cnMis:['帮衬无度','替人挑担','边界不清'],
 enMis:['Help without limit','Carrying others loads','Unclear boundaries'],
 cnClose:'天伤在兄弟宫，同辈外伤要关心，但「帮忙有度、守边界」。量力而行，才不被拖垮。',
 enClose:'Tian Shang in the Siblings Palace calls for caring with bounded help. Measure capacity to avoid being drained.'},

{cat:'fuzhu',slug:'ziwei-tianshang-zai-caibogong',focus:'天伤在财帛宫',focusEn:'Tian Shang in the Wealth Palace',
 cnT:'天伤在财帛宫：防外伤式破耗，守财留余不冒险',enT:'Tian Shang in the Wealth Palace: Guarding Against Sudden Loss',
 cnD:'天伤在财帛宫多主钱财易因意外、外伤等突发事破耗；重在留应急钱、配合适保障，不冒险投资，意外来了不慌。',
 enD:'Tian Shang in the Wealth Palace suggests money lost to accidents and injury. Keep emergency money, arrange suitable protection, avoid risky investment and stay calm at surprises.',
 cnL:'意外花钱最伤家底；应急钱和保障留在前，风险远一点。',
 enL:'Accident expenses hurt reserves; keep emergency money and protection, distance risk.',
 cnA:'有人不留应急、还冒险，一遇意外就乱；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some keep no reserves and risk, panicking at accidents; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['天伤在财帛宫，意外破财。','留应急、配保障。','不冒险投资。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Shang in Wealth means accident loss.','Keep reserves, arrange protection.','Avoid risky investment.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['留足应急钱','配置合适保障','远离冒险投资','意外支出正规处理','咨询持牌专业人士','以稳守为要'],
 enStep:['Keep emergency money','Arrange suitable protection','Avoid risky investment','Handle accident costs properly','Consult licensed professionals','Rest on steady guarding'],
 cnMis:['不留应急','冒险投资','意外就借贷'],
 enMis:['No reserves','Risky investment','Borrowing at accidents'],
 cnClose:'天伤在财帛宫，功课是「防意外破财、留应急」。守好家底、听专业人士，突发就乱不了你。',
 enClose:'Tian Shang in the Wealth Palace calls for guarding accident loss with reserves. Guard well and consult professionals.'},

{cat:'fuzhu',slug:'ziwei-jiesha-zai-fudegong',focus:'劫煞在福德宫',focusEn:'Jie Sha in the Blessings Palace',
 cnT:'劫煞在福德宫：心神防惊扰患失，稳住安全感',enT:'Jie Sha in the Blessings Palace: Steadying a Fear of Loss',
 cnD:'劫煞主被夺、损耗，在福德宫多主精神上容易有怕失去、被夺走的不安；重在认清哪些忧惧是想象、稳住安全感，必要时寻求专业帮助。',
 enD:'Jie Sha governs deprivation; in the Blessings Palace it suggests mental unease about loss and being robbed. See which fears are imagined, steady your security and seek professional help when needed.',
 cnL:'很多怕失去的焦虑，是心里先被“夺走”了；稳住、看实，安全感才回得来。',
 enL:'Much fear of loss is the mind being robbed first; steady and see clearly.',
 cnA:'有人总担心失去、患得患失；星曜是倾向，心安靠自我安顿。',
 enA:'Some constantly fear loss; stars are tendency, while peace needs self-care.',
 cnLog:['劫煞在福德宫，怕失去不安。','认清想象的忧惧。','稳住安全感。','倾向描述，非绝对定论。'],
 enLog:['Jie Sha in Blessings means fear of loss.','See imagined fears.','Steady security.','This is tendency, not an absolute verdict.'],
 cnStep:['分辨真实与想象的忧惧','练习安顿情绪','减少患得患失','规律作息','必要时寻求专业帮助','以心安为要'],
 enStep:['Tell real from imagined fears','Settle emotions','Reduce fear of loss','Keep regular hours','Seek professional help when needed','Rest on a calm heart'],
 cnMis:['患得患失','被想象的失去吓到','心不安'],
 enMis:['Fear of loss','Frightened by imagined loss','No peace'],
 cnClose:'劫煞在福德宫，要防「怕失去的内耗」。认清忧惧、稳住自己，安全感才回得来。',
 enClose:'Jie Sha in the Blessings Palace guards against fear of loss. See fears clearly and steady yourself for security.'},

{cat:'fuzhu',slug:'ziwei-jiesha-zai-fumugong',focus:'劫煞在父母宫',focusEn:'Jie Sha in the Parents Palace',
 cnT:'劫煞在父母宫：长辈防被骗被夺，多提醒照护',enT:'Jie Sha in the Parents Palace: Protect Elders From Fraud',
 cnD:'劫煞在父母宫多主父母、长辈要防被骗、被借不还或财物被夺；重在多陪伴提醒、帮长辈识别骗局，重要财物事宜走正规途径。',
 enD:'Jie Sha in the Parents Palace suggests guarding elders against fraud, unpaid loans or deprivation. Accompany and remind them, help spot scams and use formal channels for important money matters.',
 cnL:'长辈最容易成为骗子的目标；你多提醒、帮把关，他们的养老钱才守得住。',
 enL:'Elders are common fraud targets; remind and help guard their savings.',
 cnA:'有人疏于提醒、长辈被骗才后悔；星曜是倾向，照护靠用心。',
 enA:'Some neglect reminders and regret after fraud; stars are tendency, while care rests on attention.',
 cnLog:['劫煞在父母宫，长辈防被骗。','多提醒、识骗局。','财物走正规途径。','倾向描述，非绝对定论。'],
 enLog:['Jie Sha in Parents means guarding elders fraud.','Remind, help spot scams.','Use formal money channels.','This is tendency, not an absolute verdict.'],
 cnStep:['常提醒长辈防骗','帮识别可疑信息','重要财物走正规途径','多陪伴、保持联系','遇骗及时处理','以长辈平安为要'],
 enStep:['Remind elders about fraud','Help spot suspicious messages','Use formal channels for money','Accompany, keep in touch','Act promptly if scammed','Rest on elder safety'],
 cnMis:['疏于提醒','长辈被骗不重视','财物不走正规途径'],
 enMis:['Neglecting reminders','Ignoring elder fraud','Money without formal channels'],
 cnClose:'劫煞在父母宫，重在「帮长辈防骗、守养老钱」。多提醒、走正规路，长辈才平安。',
 enClose:'Jie Sha in the Parents Palace calls for protecting elders from fraud. Remind and use formal channels for their safety.'}
];
