// catchup 2026-09-13 第2组：灾煞后4宫 + 病符前4宫
module.exports=[
{cat:'fuzhu',slug:'ziwei-zaisha-zai-guanlugong',focus:'灾煞在官禄宫',focusEn:'Zai Sha in the Career Palace',
 cnT:'灾煞在官禄宫：工作防突发状况，规范操作少侥幸',enT:'Zai Sha in the Career Palace: Preventing Sudden Work Incidents',
 cnD:'灾煞在官禄宫多主工作中要防突发事故、项目意外或临时变故；重在按规范操作、不存侥幸，提前排查风险、留预案，越稳越出活。',
 enD:'Zai Sha in the Career Palace suggests guarding against sudden incidents, project surprises or last-minute changes at work. Follow procedures without cutting corners, check risks ahead and keep contingency plans, for steadiness yields results.',
 cnL:'事故多藏在“就这一次没事”里；规范守到位、预案想在前，意外就难钻空子。',
 enL:'Incidents hide in just this once is fine; follow procedures and plan ahead so surprises find no gap.',
 cnA:'有人图省事、违规操作，小意外找上门；星曜是倾向，安全和规范是底线。',
 enA:'Some save effort and break procedure, inviting incidents; stars are tendency, while safety and rules are the baseline.',
 cnLog:['灾煞在官禄宫，工作防突发。','规范操作、不侥幸。','排查风险、留预案。','倾向描述，非绝对定论。'],
 enLog:['Zai Sha in Career means guarding work surprises.','Follow procedures, no wishful thinking.','Check risks, keep contingency.','This is tendency, not an absolute verdict.'],
 cnStep:['按规范操作','提前排查风险','准备应急预案','不图省事违规','项目留余量','以稳为要'],
 enStep:['Follow procedures','Check risks ahead','Prepare contingency plans','Do not break rules to save effort','Keep project margin','Rest on steadiness'],
 cnMis:['图省事、违规','不做预案','心存侥幸'],
 enMis:['Breaking rules to save effort','No contingency','Wishful thinking'],
 cnClose:'灾煞在官禄宫，功课是「规范、防患、留预案」。少侥幸、守底线，工作才稳当。',
 enClose:'Zai Sha in the Career Palace calls for procedures, prevention and contingency. Avoid wishful thinking and keep the baseline for steady work.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-tianzhaigong',focus:'灾煞在田宅宫',focusEn:'Zai Sha in the Property Palace',
 cnT:'灾煞在田宅宫：家宅防火水意外，排查隐患保平安',enT:'Zai Sha in the Property Palace: Guarding the Home Against Fire and Water',
 cnD:'灾煞在田宅宫多主居家要防火、水、电、燃气等意外；重在定期排查隐患、安全用电用气，家人都懂基本应急，家才安心。',
 enD:'Zai Sha in the Property Palace suggests guarding the home against fire, water, electrical and gas mishaps. Check hazards regularly, use electricity and gas safely and ensure the family knows basic emergency steps.',
 cnL:'家里的意外多是小隐患攒出来的；定期查一查、教家人应急，比什么都踏实。',
 enL:'Home mishaps come from accumulated small hazards; check regularly and teach emergency steps.',
 cnA:'有人对隐患视而不见、图方便；星曜是倾向，家宅平安靠排查和习惯。',
 enA:'Some ignore hazards for convenience; stars are tendency, while home safety rests on checks and habits.',
 cnLog:['灾煞在田宅宫，居家防火水意外。','定期排查隐患。','安全用电用气、会应急。','倾向描述，非绝对定论。'],
 enLog:['Zai Sha in Property means guarding fire and water.','Check hazards regularly.','Use utilities safely, know emergency steps.','This is tendency, not an absolute verdict.'],
 cnStep:['定期排查水电燃气','安全用电用气','配灭火器等应急','教家人基本应急','不堆杂物堵通道','以家宅平安为要'],
 enStep:['Check utilities regularly','Use electricity and gas safely','Keep fire extinguishers','Teach family emergency steps','Keep exits clear','Rest on a safe home'],
 cnMis:['对隐患视而不见','不教应急','图方便违规用电'],
 enMis:['Ignoring hazards','No emergency teaching','Unsafe electricity for convenience'],
 cnClose:'灾煞在田宅宫，重在「排查隐患、安全居家」。防火水、会应急，家才是真正的避风港。',
 enClose:'Zai Sha in the Property Palace calls for hazard checks and safe living. Guard fire and water and know emergency steps so home is a true shelter.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-fudegong',focus:'灾煞在福德宫',focusEn:'Zai Sha in the Blessings Palace',
 cnT:'灾煞在福德宫：心神防突发惊扰，稳住情绪少自扰',enT:'Zai Sha in the Blessings Palace: Steadying a Startled Mind',
 cnD:'灾煞在福德宫多主精神上容易受突发事惊扰、一惊一乍；重在养心安神、遇事稳住，不自己吓自己，必要时寻求专业帮助。',
 enD:'Zai Sha in the Blessings Palace suggests a mind easily startled by sudden events. Nurture calm, steady in trouble and do not frighten yourself, seeking professional help when needed.',
 cnL:'很多惊吓是自己在脑子里放大的；心稳住、事看实，惊就落不了地。',
 enL:'Much fright is enlarged in the mind; steady the heart and see matters as they are.',
 cnA:'有人遇事容易慌、越想越怕；星曜是倾向，心神的稳是练出来的。',
 enA:'Some panic easily and grow afraid; stars are tendency, while steadiness is practiced.',
 cnLog:['灾煞在福德宫，心神防惊扰。','养心安神、遇事稳。','不自吓、必要时求助。','倾向描述，非绝对定论。'],
 enLog:['Zai Sha in Blessings means a startled mind.','Nurture calm, steady in trouble.','Do not frighten yourself; seek help if needed.','This is tendency, not an absolute verdict.'],
 cnStep:['练习放松稳住情绪','遇事看事实、不放大','规律作息养神','少接触惊吓信息','必要时寻求专业帮助','以心安为要'],
 enStep:['Relax and steady emotions','See facts, do not enlarge','Keep regular hours','Limit startling content','Seek professional help when needed','Rest on a calm heart'],
 cnMis:['一惊一乍','自己吓自己','遇事就慌'],
 enMis:['Easily startled','Frightening yourself','Panicking at trouble'],
 cnClose:'灾煞在福德宫，功课是「稳心神、不自扰」。遇事不慌、看实，精神才安定。',
 enClose:'Zai Sha in the Blessings Palace calls for a steady, self-undisturbed mind. Do not panic and see matters clearly for calm.'},

{cat:'fuzhu',slug:'ziwei-zaisha-zai-fumugong',focus:'灾煞在父母宫',focusEn:'Zai Sha in the Parents Palace',
 cnT:'灾煞在父母宫：长辈安全多留心，陪伴提醒防意外',enT:'Zai Sha in the Parents Palace: Mind Elders Safety',
 cnD:'灾煞在父母宫多主父母、长辈要防跌倒、突发身体状况等意外；重在多陪伴、常提醒，居家适老改造，不适及时就医。',
 enD:'Zai Sha in the Parents Palace suggests guarding elders against falls and sudden health matters. Accompany and remind often, make the home age-friendly and seek timely care for discomfort.',
 cnL:'长辈的意外多在一滑一摔里；你把家改适老、多陪伴，平安就有底。',
 enL:'Elder mishaps often come in a slip or fall; make the home age-friendly and accompany.',
 cnA:'有人疏于关心长辈安全、隐患不除；星曜是倾向，长辈平安靠用心。',
 enA:'Some neglect elder safety and leave hazards; stars are tendency, while elder safety rests on care.',
 cnLog:['灾煞在父母宫，长辈防意外。','陪伴提醒、适老改造。','不适及时就医。','倾向非诊断，以正规就医为准。'],
 enLog:['Zai Sha in Parents means guarding elders.','Accompany, make home age-friendly.','Seek timely care.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['居家适老、防滑倒','常陪伴、多提醒','长辈不适及时就诊','用药规律、有人照看','保持联系','以长辈平安为要'],
 enStep:['Make home age-friendly, prevent falls','Accompany and remind','Seek timely care for discomfort','Regular medicine, someone watching','Keep in touch','Rest on elder safety'],
 cnMis:['疏于关心长辈','隐患不除','长辈不适硬拖'],
 enMis:['Neglecting elders','Leaving hazards','Toughing out elder discomfort'],
 cnClose:'灾煞在父母宫，重在「长辈防意外、适老、陪伴」。用心照看，长辈才平安。',
 enClose:'Zai Sha in the Parents Palace calls for elder safety, age-friendly homes and presence. Care well so elders stay safe.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-minggong',focus:'病符在命宫',focusEn:'Bing Fu in the Life Palace',
 cnT:'病符在命宫：体质偏易感，规律作息重预防',enT:'Bing Fu in the Life Palace: A Sensitive Constitution, Prevention First',
 cnD:'病符主疾病、易感性，在命宫多主体质偏敏感、容易被传染或小毛病不断；重在规律作息、均衡饮食、讲卫生重预防，不焦虑，真不适正规就医。',
 enD:'Bing Fu governs illness and susceptibility; in the Life Palace it suggests a sensitive constitution, prone to infection or recurring small ills. Keep regular hours, eat balanced, value hygiene and prevention without anxiety, seeking formal care for real discomfort.',
 cnL:'易生病的人更要把预防当日常；身体养结实、卫生做到，小毛病自然少。',
 enL:'Those prone to illness make prevention daily; strengthen the body and keep hygiene.',
 cnA:'有人不重预防、或稍有不适就焦虑；星曜是倾向，健康以正规就医为准。',
 enA:'Some neglect prevention or fret at every ill; stars are tendency, while health relies on formal care.',
 cnLog:['病符主易感，命宫体质偏敏感。','规律作息、重预防。','不焦虑、真不适就医。','倾向非诊断，以正规就医为准。'],
 enLog:['Bing Fu governs susceptibility; in Life a sensitive constitution.','Regular hours, prevention first.','Do not fret; seek care for real discomfort.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['规律作息、均衡饮食','讲卫生、重预防','适度锻炼增体质','按时体检','不适正规就诊','以预防为要'],
 enStep:['Regular hours, balanced diet','Hygiene, prevention','Exercise to build constitution','Check-ups on schedule','Seek formal care for discomfort','Rest on prevention'],
 cnMis:['不重预防','稍不适就焦虑','作息无规律'],
 enMis:['Neglecting prevention','Fretting at every ill','Irregular hours'],
 cnClose:'病符在命宫，功课是「养体质、重预防」。作息规律、卫生到位，真不适应正规就医。',
 enClose:'Bing Fu in the Life Palace calls for a strong constitution and prevention. Keep regular hours and hygiene, and seek formal care for real discomfort.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-xiongdigong',focus:'病符在兄弟宫',focusEn:'Bing Fu in the Siblings Palace',
 cnT:'病符在兄弟宫：同辈健康多关心，互相提醒保重',enT:'Bing Fu in the Siblings Palace: Caring for Peers Health',
 cnD:'病符在兄弟宫多主兄弟姐妹、同辈朋友的健康需多关心，有人易病；重在常问候、互相提醒保重，遇到同辈生病给予力所能及的关心。',
 enD:'Bing Fu in the Siblings Palace suggests caring for siblings and peers health, some being illness-prone. Check in often, remind one another to stay well and offer what care you can when peers fall ill.',
 cnL:'同辈的健康，常靠一句问候、一次提醒；你心里有他们，缘分就暖。',
 enL:'Peers health often rests on a greeting or reminder; keep them in mind.',
 cnA:'有人对同辈健康漠不关心；星曜是倾向，情分体现在日常关心。',
 enA:'Some are indifferent to peers health; stars are tendency, while affection shows in daily care.',
 cnLog:['病符在兄弟宫，同辈健康关心。','常问候、互提醒。','力所能及时关心。','倾向描述，非绝对定论。'],
 enLog:['Bing Fu in Siblings means caring for peers health.','Check in, remind one another.','Offer care when you can.','This is tendency, not an absolute verdict.'],
 cnStep:['常问候同辈','提醒保重身体','生病给予关心','不越界、不替代就医','珍惜缘分','以长久情分为要'],
 enStep:['Check in with peers','Remind them to stay well','Offer care when ill','Do not overstep or replace care','Value the bond','Rest on lasting affection'],
 cnMis:['漠不关心','只口头、不行动','对同辈生病无感'],
 enMis:['Indifferent','Words without action','Unmoved by peers illness'],
 cnClose:'病符在兄弟宫，同辈健康多留心。常问候、懂提醒，情分才暖、才长久。',
 enClose:'Bing Fu in the Siblings Palace calls for caring about peers health. Check in and remind so affection stays warm.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-fuqigong',focus:'病符在夫妻宫',focusEn:'Bing Fu in the Spouse Palace',
 cnT:'病符在夫妻宫：伴侣健康共照护，互相体贴养生',enT:'Bing Fu in the Spouse Palace: Caring for Each Others Health',
 cnD:'病符在夫妻宫多主伴侣体质偏敏感、需多照护；重在一起规律生活、互相体贴，生病时陪伴就医，健康是两个人一起经营的事。',
 enD:'Bing Fu in the Spouse Palace suggests a sensitive partner needing more care. Live regularly together, be considerate and accompany them to care when ill, for health is managed by both.',
 cnL:'伴侣的身体，你上心一分、关系暖一分；一起养生、病时陪伴，最见真情。',
 enL:'Care for a partners health warms the bond; stay well together and accompany in illness.',
 cnA:'有人对伴侣健康不上心、各顾各；星曜是倾向，长久靠互相照护。',
 enA:'Some neglect partners health and look after themselves; stars are tendency, while lasting bonds need mutual care.',
 cnLog:['病符在夫妻宫，伴侣偏敏感。','共同规律生活、体贴。','病时陪伴就医。','倾向非诊断，以正规就医为准。'],
 enLog:['Bing Fu in Spouse means a sensitive partner.','Live regularly together, be considerate.','Accompany to care when ill.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['陪伴侣规律生活','体贴照护日常','生病陪伴正规就诊','一起锻炼养生','记住对方健康状况','以相守为要'],
 enStep:['Live regularly with your partner','Be considerate daily','Accompany to formal care when ill','Exercise and stay well together','Remember their health needs','Rest on staying together'],
 cnMis:['对伴侣健康不上心','各顾各','生病不陪伴'],
 enMis:['Neglecting partners health','Looking after self only','Not present in illness'],
 cnClose:'病符在夫妻宫，伴侣健康一起顾。规律生活、病时陪伴，感情才长久。',
 enClose:'Bing Fu in the Spouse Palace calls for caring for health together. Live regularly and be present in illness for lasting love.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-zinvgong',focus:'病符在子女宫',focusEn:'Bing Fu in the Children Palace',
 cnT:'病符在子女宫：孩子偏易感，科学照护重预防',enT:'Bing Fu in the Children Palace: Sensitive Children, Scientific Care',
 cnD:'病符在子女宫多主孩子体质偏敏感、容易感冒小毛病；重在科学照护、按时接种、讲卫生重预防，不焦虑、不乱用药，生病正规就医。',
 enD:'Bing Fu in the Children Palace suggests sensitive children prone to colds and small ills. Care scientifically, vaccinate on schedule, value hygiene and prevention without anxiety or random medicine, seeking formal care when ill.',
 cnL:'孩子易生病，预防和科学照护最要紧；你稳住、不乱用药，孩子少遭罪。',
 enL:'For illness-prone children, prevention and scientific care matter most; stay steady and avoid random medicine.',
 cnA:'有人一病就乱用药、或过度焦虑；星曜是倾向，健康以正规就医为准。',
 enA:'Some use random medicine or over-fret; stars are tendency, while health relies on formal care.',
 cnLog:['病符在子女宫，孩子偏易感。','科学照护、按时接种。','不焦虑、不乱用药。','倾向非诊断，以正规就医为准。'],
 enLog:['Bing Fu in Children means sensitive children.','Scientific care, vaccination on schedule.','Do not fret or use random medicine.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['按时接种、讲卫生','科学照护小毛病','不焦虑、不乱用药','生病正规就诊','均衡饮食、规律作息','以预防为要'],
 enStep:['Vaccinate, keep hygiene','Care for small ills scientifically','Do not fret or use random medicine','Seek formal care when ill','Balanced diet, regular hours','Rest on prevention'],
 cnMis:['乱用药','过度焦虑','忽视接种预防'],
 enMis:['Random medicine','Over-fretting','Neglecting vaccination'],
 cnClose:'病符在子女宫，孩子偏易感，重在「预防、科学、不焦虑」。该就医就医，孩子少遭罪。',
 enClose:'Bing Fu in the Children Palace calls for prevention, scientific care and no anxiety. Seek care when needed so children suffer less.'}
];
