// catchup 2026-09-16 第1组：天厨前8宫
module.exports=[
{cat:'fuzhu',slug:'ziwei-tianchu-zai-xiongdigong',focus:'天厨在兄弟宫',focusEn:'Tian Chu in the Siblings Palace',
 cnT:'天厨在兄弟宫：手足同辈多有口福，饭桌聚情',enT:'Tian Chu in the Siblings Palace: Bonding Over Meals',
 cnD:'天厨主食禄口福，在兄弟宫多主兄弟姐妹、同辈朋友有口福、待人体面，感情常在饭桌上加深；重在珍惜、常聚也别铺张，一顿热饭暖人心。',
 enD:'Tian Chu governs food and sustenance; in the Siblings Palace it suggests peers who enjoy food and host warmly, bonds deepening over meals. Gather often without extravagance.',
 cnL:'同辈的情分，很多是一顿顿饭吃出来的；热饭在桌、人在身边，就是好日子。',
 enL:'Peer affection is built over meals; warm food and people present make good days.',
 cnA:'有人聚餐只讲排场、铺张浪费；星曜是倾向，口福也要懂惜福。',
 enA:'Some feast only for show and waste; stars are tendency, while food luck calls for gratitude.',
 cnLog:['天厨主食禄，兄弟宫同辈有口福。','饭桌聚情、待人体面。','常聚不铺张。','倾向描述，非绝对定论。'],
 enLog:['Tian Chu governs food; in Siblings peers enjoy it.','Bonds over meals, warm hosting.','Gather, no extravagance.','This is tendency, not an absolute verdict.'],
 cnStep:['珍惜同辈、常聚','饭桌待客真诚','不铺张浪费','分享美食','记得人情','以惜福为要'],
 enStep:['Value peers, gather often','Host sincerely','No waste','Share good food','Remember kindness','Rest on gratitude'],
 cnMis:['聚餐讲排场','铺张浪费','只受款待、不回请'],
 enMis:['Feasting for show','Wasting','Only receiving, not returning'],
 cnClose:'天厨在兄弟宫，同辈有口福、饭桌聚情。真诚、惜福、不铺张，烟火气里见真情。',
 enClose:'Tian Chu in the Siblings Palace blesses peers who bond over food. Be sincere and grateful, not wasteful.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-fuqigong',focus:'天厨在夫妻宫',focusEn:'Tian Chu in the Spouse Palace',
 cnT:'天厨在夫妻宫：伴侣会生活，一屋两人三餐暖',enT:'Tian Chu in the Spouse Palace: A Warm, Shared Table',
 cnD:'天厨在夫妻宫多主伴侣懂生活、爱美食或会做饭，家里烟火气足；重在一起做饭、彼此照顾，三餐四季的陪伴最养感情。',
 enD:'Tian Chu in the Spouse Palace suggests a partner who enjoys life and food, perhaps cooking, with a warm kitchen. Cook together and care for one another, for daily meals nurture love.',
 cnL:'最好的浪漫，是有人陪你吃很多顿饭；烟火气在，家就暖。',
 enL:'The best romance is sharing many meals; warm kitchen, warm home.',
 cnA:'有人只下馆子、家里不开火，少了烟火气；星曜是倾向，日子靠一起经营。',
 enA:'Some only eat out and never cook, losing warmth; stars are tendency, while life is built together.',
 cnLog:['天厨在夫妻宫，伴侣会生活。','烟火气足、一起做饭。','三餐陪伴养情。','倾向描述，非绝对定论。'],
 enLog:['Tian Chu in Spouse means a partner who enjoys life.','Warm kitchen, cook together.','Daily meals nurture love.','This is tendency, not an absolute verdict.'],
 cnStep:['一起做饭分担','照顾彼此口味','多在家吃饭','不浪费食物','共同采买','以温暖为要'],
 enStep:['Cook together','Care for each others tastes','Eat at home more','Do not waste','Shop together','Rest on warmth'],
 cnMis:['只下馆子','不一起做饭','忽视烟火气'],
 enMis:['Only eating out','Not cooking together','Ignoring the kitchen'],
 cnClose:'天厨在夫妻宫，一屋两人三餐暖。一起做饭、彼此照顾，烟火气里见长久。',
 enClose:'Tian Chu in the Spouse Palace blesses a warm shared table. Cook and care together for lasting warmth.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-zinvgong',focus:'天厨在子女宫',focusEn:'Tian Chu in the Children Palace',
 cnT:'天厨在子女宫：孩子有口福不挑食，亲子共厨',enT:'Tian Chu in the Children Palace: A Child Who Eats Well',
 cnD:'天厨在子女宫多主孩子有口福、吃饭香，也适合带孩子一起做饭；重在培养不挑食、不浪费，亲子共厨既养身体又养感情。',
 enD:'Tian Chu in the Children Palace suggests a child who enjoys food and eats well, suiting cooking together. Teach broad tastes and no waste, for cooking together nurtures body and bond.',
 cnL:'孩子吃饭香是福气；带他下厨房、教他惜食物，比追着喂强。',
 enL:'A child eating well is blessing; cook together and teach gratitude for food.',
 cnA:'有人追着喂、纵容挑食浪费；星曜是倾向，饮食习惯靠从小养。',
 enA:'Some chase-feed and allow picky waste; stars are tendency, while habits are built early.',
 cnLog:['天厨在子女宫，孩子有口福。','亲子共厨、不挑食。','养不浪费的习惯。','倾向描述，非绝对定论。'],
 enLog:['Tian Chu in Children means a child who eats well.','Cook together, broad tastes.','No waste.','This is tendency, not an absolute verdict.'],
 cnStep:['带孩子一起做饭','培养不挑食','教他珍惜食物','规律三餐','不追喂、不纵容','以健康为要'],
 enStep:['Cook with the child','Build broad tastes','Teach gratitude for food','Regular meals','No chase-feeding','Rest on health'],
 cnMis:['纵容挑食','追着喂','浪费食物'],
 enMis:['Allowing pickiness','Chase-feeding','Wasting food'],
 cnClose:'天厨在子女宫，孩子吃饭香是福。亲子共厨、不挑不浪费，养出好身体好习惯。',
 enClose:'Tian Chu in the Children Palace blesses a child who eats well. Cook together and teach broad tastes without waste.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-caibogong',focus:'天厨在财帛宫',focusEn:'Tian Chu in the Wealth Palace',
 cnT:'天厨在财帛宫：衣食丰足有食禄，量入为出不浪费',enT:'Tian Chu in the Wealth Palace: Ample Sustenance, Wise Spending',
 cnD:'天厨在财帛宫多主衣食丰足、有口福食禄，不愁吃穿；但口福也花钱。重在量入为出、不浪费、不铺张，把福气用得长久。',
 enD:'Tian Chu in the Wealth Palace suggests ample food and clothing, no lack of sustenance. Good food costs too. Spend within means, avoid waste and make blessing last.',
 cnL:'衣食丰足是福，可你不浪费、会规划，这福才长久。',
 enL:'Ample food is blessing, but avoid waste and plan to make it last.',
 cnA:'有人有口福就铺张、月光；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some feast and spend the month away; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['天厨在财帛宫，衣食丰足。','量入为出、不浪费。','福气长久。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Chu in Wealth means ample sustenance.','Spend within means, no waste.','Make blessing last.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['量入为出','不铺张浪费','留应急钱','记账','咨询持牌专业人士','以稳为要'],
 enStep:['Spend within means','No waste','Keep emergency money','Track accounts','Consult licensed professionals','Rest on steadiness'],
 cnMis:['铺张月光','不浪费、不规划','只图口福'],
 enMis:['Wasting the month away','No plan','Only food pleasure'],
 cnClose:'天厨在财帛宫，衣食丰足是福。量入为出、不浪费，口福才长久。',
 enClose:'Tian Chu in the Wealth Palace blesses ample sustenance. Spend within means and avoid waste for lasting blessing.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-jiegong',focus:'天厨在疾厄宫',focusEn:'Tian Chu in the Health Palace',
 cnT:'天厨在疾厄宫：病多从口入，清淡均衡重饮食',enT:'Tian Chu in the Health Palace: Mind What You Eat',
 cnD:'天厨在疾厄宫多主健康与饮食关系大，爱吃也容易吃出肠胃、代谢问题；重在均衡清淡、规律三餐，不暴饮暴食，不适正规就医。',
 enD:'Tian Chu in the Health Palace links health closely to diet, with love of food bringing digestion or metabolism issues. Eat balanced and light, keep regular meals and seek formal care for discomfort.',
 cnL:'爱吃不是错，会吃才是本事；清淡均衡，身体才不替嘴买单。',
 enL:'Loving food is fine, eating wisely the skill; balanced and light.',
 cnA:'有人暴饮暴食、重口味；星曜是倾向，健康以正规就医为准。',
 enA:'Some overeat and favor heavy flavors; stars are tendency, while health relies on formal care.',
 cnLog:['天厨在疾厄宫，健康关饮食。','均衡清淡、不暴食。','规律三餐。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Chu in Health links health to diet.','Balanced, light, no overeating.','Regular meals.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['均衡清淡饮食','三餐规律','不暴饮暴食','少重口高糖油','不适及时就诊','以健康为要'],
 enStep:['Balanced, light diet','Regular meals','No overeating','Less heavy, sugary, oily food','Seek timely care','Rest on health'],
 cnMis:['暴饮暴食','重口味、无节制','忽视饮食健康'],
 enMis:['Overeating','Heavy flavors, no restraint','Ignoring diet health'],
 cnClose:'天厨在疾厄宫，要懂「病从口入、会吃养身」。均衡清淡、规律，不适正规就医。',
 enClose:'Tian Chu in the Health Palace reminds us to mind what we eat. Balance and regularity, and seek formal care for discomfort.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-qianyi',focus:'天厨在迁移宫',focusEn:'Tian Chu in the Travel Palace',
 cnT:'天厨在迁移宫：外出有口福，尝鲜也注意卫生',enT:'Tian Chu in the Travel Palace: Tasting the World, Mind Hygiene',
 cnD:'天厨在迁移宫多主外出、旅行有口福、能尝到各地美食；重在尝鲜也注意饮食卫生、不贪生冷，水土不服及时处理。',
 enD:'Tian Chu in the Travel Palace suggests enjoying local foods while traveling. Mind hygiene, avoid excess raw and cold food and handle upset digestion promptly.',
 cnL:'行万里路、尝百味鲜，是人生乐事；但卫生注意、不贪嘴，玩得才踏实。',
 enL:'Travel far and taste widely is a joy; mind hygiene and do not overindulge.',
 cnA:'有人外出贪嘴、不注意卫生闹肚子；星曜是倾向，健康靠自己留心。',
 enA:'Some overindulge away and fall ill; stars are tendency, while health needs care.',
 cnLog:['天厨在迁移宫，外出有口福。','尝鲜重卫生。','不贪生冷。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Chu in Travel means tasting away.','Mind hygiene.','Avoid excess raw and cold.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['尝当地美食','注意饮食卫生','不贪生冷','备肠胃药','不适当地就医','以平安为要'],
 enStep:['Taste local food','Mind hygiene','Avoid excess raw and cold','Carry digestion medicine','Seek local care','Rest on safe travel'],
 cnMis:['贪嘴闹肚子','不注意卫生','生冷不忌'],
 enMis:['Overindulging, falling ill','Ignoring hygiene','Excess raw and cold'],
 cnClose:'天厨在迁移宫，外出尝鲜是乐事。卫生注意、不贪嘴，旅途才顺心。',
 enClose:'Tian Chu in the Travel Palace blesses tasting the world. Mind hygiene and do not overindulge for smooth travel.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-puyigong',focus:'天厨在仆役宫',focusEn:'Tian Chu in the Friends Palace',
 cnT:'天厨在仆役宫：朋友饭局多，款待有度惜缘分',enT:'Tian Chu in the Friends Palace: Many Feasts, Warm Measure',
 cnD:'天厨在仆役宫多主朋友多、饭局多、人缘好，常互相款待；重在真诚相待、款待有度，不铺张也别让人情变负担。',
 enD:'Tian Chu in the Friends Palace suggests many friends and feasts with good relations, hosting one another. Be sincere and measured, not wasteful, keeping friendship light.',
 cnL:'朋友饭局多是热闹，可真诚比酒菜贵、分寸让缘分久。',
 enL:'Many feasts are lively, but sincerity beats food and measure keeps bonds.',
 cnA:'有人天天应酬、铺张伤身；星曜是倾向，朋友靠真诚维系。',
 enA:'Some socialize daily, wasting and tiring; stars are tendency, while friends need sincerity.',
 cnLog:['天厨在仆役宫，朋友饭局多。','款待有度、真诚。','不铺张。','倾向描述，非绝对定论。'],
 enLog:['Tian Chu in Friends means many feasts.','Measured hosting, sincere.','Not wasteful.','This is tendency, not an absolute verdict.'],
 cnStep:['真诚待朋友','款待有度','不铺张拼酒','珍惜饭局缘分','守分寸','以长久为要'],
 enStep:['Be sincere','Host with measure','No waste or heavy drinking','Value feasts and bonds','Keep measure','Rest on lasting relations'],
 cnMis:['天天应酬','铺张拼酒','把饭局当朋友全部'],
 enMis:['Daily socializing','Wasting, heavy drinking','Feasts as all of friendship'],
 cnClose:'天厨在仆役宫，朋友饭局多、人缘好。真诚、有度、不铺张，缘分才长久。',
 enClose:'Tian Chu in the Friends Palace blesses many feasts and friends. Be sincere and measured, not wasteful.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-guanlugong',focus:'天厨在官禄宫',focusEn:'Tian Chu in the Career Palace',
 cnT:'天厨在官禄宫：事业有食禄，利餐饮、踏实有回报',enT:'Tian Chu in the Career Palace: Steady Sustenance Through Work',
 cnD:'天厨在官禄宫多主工作有俸禄、衣食安稳，也适合餐饮、食品、相关行业；重在踏实做事、专业经营，不贪小利，回报自然来。',
 enD:'Tian Chu in the Career Palace suggests steady sustenance through work, also suiting food and related industries. Work grounded and professional, not chasing petty gains.',
 cnL:'踏实的工作养人一辈子；你专业、不贪快，食禄自然稳。',
 enL:'Grounded work sustains for life; be professional and not greedy.',
 cnA:'有人贪小利、不踏实；星曜是倾向，事业靠真功夫。',
 enA:'Some chase petty gains and are not grounded; stars are tendency, while career rests on real skill.',
 cnLog:['天厨在官禄宫，事业有食禄。','利餐饮食品。','踏实专业、不贪。','倾向描述，非绝对定论。'],
 enLog:['Tian Chu in Career means steady sustenance.','Suiting food industries.','Grounded, professional, not greedy.','This is tendency, not an absolute verdict.'],
 cnStep:['踏实做好工作','专业经营','不贪小利','选稳定方向','持续积累','以长远为要'],
 enStep:['Do grounded work','Be professional','No petty gains','Choose a steady path','Keep accumulating','Rest on long results'],
 cnMis:['贪小利','不踏实','频繁换方向'],
 enMis:['Chasing petty gains','Not grounded','Changing direction often'],
 cnClose:'天厨在官禄宫，事业有食禄、利餐饮。踏实专业、不贪小利，回报才长久。',
 enClose:'Tian Chu in the Career Palace blesses steady sustenance and food-related work. Be grounded and professional, not greedy.'}
];
