// catchup 2026-09-11 第2组：主星疾厄宫后6（贪狼/巨门/天相/天梁/七杀/破军）+ 左辅/右弼疾厄宫
module.exports=[
{cat:'zhuxing',slug:'ziwei-tanlang-zai-jiegong',focus:'贪狼在疾厄宫',focusEn:'Tan Lang in the Health Palace',
 cnT:'贪狼在疾厄宫：应酬欲望要有度，肝胆与内分泌多关照',enT:'Tan Lang in the Health Palace: Moderation for Liver and Hormones',
 cnD:'贪狼属木、带桃花，在疾厄宫多指向肝胆、泌尿生殖与内分泌；多欲、多应酬、作息放纵时最易出问题，重在节制、规律，别仗着恢复快就挥霍身体。',
 enD:'Tan Lang belongs to wood and carries romance; in the Health Palace it often points to the liver-gallbladder, urinary-reproductive system and hormones. Strong desires, social indulgence and loose routines bring trouble most easily; restraint and regularity matter, so do not squander the body on quick recovery.',
 cnL:'欲望像油门，踩到底是痛快，可发动机也最伤；身体这台车，得留着开长远。',
 enL:'Desire is the gas pedal; flooring it is thrilling but wears the engine; keep the body car for the long road.',
 cnA:'有人见贪狼在疾厄宫仍烟酒声色无度，等指标亮红灯才收；星曜是倾向，肝胆内分泌的问题要靠检查、看医生。',
 enA:'Some keep tobacco, drink and nightlife unchecked with Tan Lang in Health, only reining in at red-flag markers; stars are tendency, while liver and hormonal ills need tests and a doctor.',
 cnLog:['贪狼属木带桃花，重点在肝胆、生殖、内分泌。','应酬纵欲、作息放纵是主因。','节制规律，别挥霍恢复力。','倾向非诊断，以正规就医为准。'],
 enLog:['Tan Lang is wood with romance, focus on liver, reproduction and hormones.','Social indulgence and loose routines are main causes.','Stay restrained and regular, do not squander recovery.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['应酬有节、少烟酒熬夜','作息规律、避免纵欲过度','关注肝胆与内分泌信号','定期检查肝肾功能与激素','不适及时就诊','以医生评估为准'],
 enStep:['Keep social indulgence moderate, cut tobacco, drink and late nights','Stay regular, avoid excess','Watch liver and hormonal signals','Check liver-kidney function and hormones regularly','Seek timely care for discomfort','Follow the doctor assessment'],
 cnMis:['仗恢复快而纵欲无度','把生殖内分泌不适当小事','烟酒熬夜不节制'],
 enMis:['Indulging on quick recovery','Taking reproductive and hormonal ills lightly','No restraint in tobacco, drink and late nights'],
 cnClose:'贪狼在疾厄宫，关键是「欲望有节、肝胆得养」。应酬少一分、作息稳一分，异常早就医，别把本钱提前透支。',
 enClose:'Tan Lang in the Health Palace hinges on measured desires and a nourished liver. Less indulgence and steadier routines, early care for abnormalities, and do not spend the body capital ahead of time.'},

{cat:'zhuxing',slug:'ziwei-jumen-zai-jiegong',focus:'巨门在疾厄宫',focusEn:'Ju Men in the Health Palace',
 cnT:'巨门在疾厄宫：口腔咽喉是门户，疑病多虑更伤身',enT:'Ju Men in the Health Palace: Mouth, Throat and Worry',
 cnD:'巨门属水、为暗星，在疾厄宫多指向口腔、咽喉、牙齿与肠胃，也容易多疑、焦虑、把小毛病想成大病；重在管好入口、疏解情绪，有疑虑靠检查而非瞎猜。',
 enD:'Ju Men belongs to water and is the dark star; in the Health Palace it often points to the mouth, throat, teeth and gut, and one may grow suspicious or anxious, turning small ills into feared diseases. Guard what enters the mouth, ease emotions, and settle doubts through tests rather than guessing.',
 cnL:'病疑在心里反复煮，越煮越像真的；与其瞎想，不如查个明白，心里那团暗才散。',
 enL:'Health fears simmered in the mind grow more real; instead of guessing, get checked and the inner dark clears.',
 cnA:'有人反复跑医院却查不出问题，根在焦虑；但也不能因此把真信号当多虑，该查还得查，由医生判断。',
 enA:'Some visit hospitals repeatedly without findings, the root being anxiety; yet real signals must not be dismissed as worry, so check when needed and let the doctor judge.',
 cnLog:['巨门属水为暗，重点在口腔咽喉齿与肠胃。','易多疑焦虑、疑病。','管入口、疏情绪，靠检查释疑。','倾向非诊断，以正规就医为准。'],
 enLog:['Ju Men is water and dark, focus on mouth, throat, teeth and gut.','Prone to suspicion, anxiety and health fears.','Guard intake, ease emotions, use tests to settle doubt.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['注意口腔卫生与咽喉养护','饮食温和、护肠胃','情绪有出口、减少疑病焦虑','有疑虑做针对性检查','反复不适就诊、由医生判断','不自行对号入座'],
 enStep:['Mind oral hygiene and throat care','Eat warm and gentle, protect the gut','Give emotions an outlet, reduce health fears','Get targeted tests when doubtful','Seek care for recurring ills, let the doctor judge','Do not self-diagnose'],
 cnMis:['小毛病瞎想成大病','只焦虑不检查、或只检查不调心','忽视口腔咽喉门户'],
 enMis:['Imagining small ills into serious disease','Only anxious without tests, or only testing without calming the mind','Neglecting the mouth and throat gateway'],
 cnClose:'巨门在疾厄宫，一要护「口腔咽喉的门户」，二要破「心里的疑」。该查查、该松松，结论交给医生，别自己吓自己。',
 enClose:'Ju Men in the Health Palace needs both guarding the mouth-throat gateway and breaking inner doubt. Check when needed, relax when possible, leave conclusions to the doctor and do not frighten yourself.'},

{cat:'zhuxing',slug:'ziwei-tianxiang-zai-jiegong',focus:'天相在疾厄宫',focusEn:'Tian Xiang in the Health Palace',
 cnT:'天相在疾厄宫：饮食有节养皮肤，淋巴泌尿多留意',enT:'Tian Xiang in the Health Palace: Diet, Skin and Lymph',
 cnD:'天相属水、为印星，在疾厄宫多指向泌尿肾、皮肤与淋巴，多与饮食、衣着、生活节律相关；体质总体平稳，重在饮食有节、清洁到位、不跟风乱吃补品。',
 enD:'Tian Xiang belongs to water and is the seal star; in the Health Palace it often points to the urinary kidneys, skin and lymph, often tied to diet, clothing and daily rhythm. The constitution is generally steady; eat with restraint, keep clean and do not follow fads with tonics.',
 cnL:'印星讲究体面，皮肤是身体的门面；门面的问题，常常是里头的水和吃进去的东西在说话。',
 enL:'The seal star cares about appearance and skin is the body storefront; its issues often speak of inner water and what is eaten.',
 cnA:'有人皮肤一有状况就乱抹乱吃，反而反复；星曜给方向，皮肤泌尿淋巴的问题要专科看、查清楚。',
 enA:'Some apply or take things randomly at the first skin issue and it recurs; stars give direction, while skin, urinary and lymph ills need specialists and clear checks.',
 cnLog:['天相属水为印，重点在泌尿肾、皮肤、淋巴。','与饮食衣着节律相关。','饮食有节、清洁到位。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Xiang is water and seal, focus on urinary kidneys, skin and lymph.','Tied to diet, clothing and rhythm.','Eat with restraint, keep clean.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['饮食有节、少刺激发物','保持皮肤清洁、衣着透气','关注泌尿与淋巴信号','皮肤反复专科就诊','不乱吃补品偏方','以医生判断为准'],
 enStep:['Eat with restraint, cut irritants','Keep skin clean, wear breathable clothing','Watch urinary and lymph signals','See specialists for recurring skin ills','Avoid fad tonics and folk remedies','Follow the doctor judgment'],
 cnMis:['皮肤问题乱抹乱补','饮食不节、跟风吃发物','泌尿淋巴信号被忽视'],
 enMis:['Random applications and tonics for skin ills','Imbalanced diet, following fads','Urinary and lymph signals ignored'],
 cnClose:'天相在疾厄宫，养在「饮食有节、皮肤清洁」。泌尿淋巴多留意，反复问题看专科，不靠偏方、不乱补。',
 enClose:'Tian Xiang in the Health Palace is nourished by a measured diet and clean skin. Mind urinary and lymph signals, see specialists for recurring ills and avoid folk remedies and random tonics.'},

{cat:'zhuxing',slug:'ziwei-tianliang-zai-jiegong',focus:'天梁在疾厄宫',focusEn:'Tian Liang in the Health Palace',
 cnT:'天梁在疾厄宫：逢凶有救别侥幸，慢病调养贵坚持',enT:'Tian Liang in the Health Palace: Chronic Care and Consistency',
 cnD:'天梁属土、为荫星，在疾厄宫多主脾胃，且有逢凶化吉之意；但正因「总能扛过去」，容易把急性拖成慢性。重在早就医、不侥幸，慢病靠规律调养与随访。',
 enD:'Tian Liang belongs to earth and is the shelter star; in the Health Palace it often governs the spleen and stomach and suggests turning misfortune around. Yet because one always pulls through, acute ills are easily dragged into chronic ones. Seek early care without relying on luck; chronic ills need steady care and follow-up.',
 cnL:'有靠山的人容易不着急，可病这东西，老让它自己好，它就赖着不走了。',
 enL:'Those with backing tend not to rush, but illness left to resolve itself often settles in and stays.',
 cnA:'有人凭「以前扛扛就好」反复拖延，结果小病变慢病；星曜是倾向，脾胃与慢病要规律随访、听医生的。',
 enA:'Some rely on having toughed it out before and delay repeatedly, turning acute into chronic; stars are tendency, while digestion and chronic ills need regular follow-up and the doctor.',
 cnLog:['天梁属土为荫，重点在脾胃。','有逢凶化吉之意，易侥幸拖延。','早就医、慢病规律随访。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Liang is earth and shelter, focus on spleen and stomach.','Misfortune can turn, tempting lucky delay.','Seek early care, follow up chronic ills regularly.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['小毛病早就医、不拖延','脾胃靠规律饮食养护','慢病遵医嘱、定期随访','不靠侥幸、不擅自停药','作息规律、情绪平和','以医生方案为准'],
 enStep:['Seek early care, do not delay','Nourish digestion with regular meals','Follow doctor orders for chronic ills, check regularly','Do not rely on luck or stop medicine on your own','Keep regular hours and calm mood','Follow the doctor plan'],
 cnMis:['凭能扛而拖延就医','急性拖成慢性','慢病擅自停药、不随访'],
 enMis:['Delaying care because one can tough it out','Dragging acute into chronic','Stopping medicine and skipping follow-up'],
 cnClose:'天梁在疾厄宫，虽有救应，更要「不侥幸、早就医」。脾胃规律养、慢病坚持随访，听医生的才是真靠山。',
 enClose:'Tian Liang in the Health Palace offers rescue but calls for early care without relying on luck. Nourish digestion, keep up chronic follow-up and follow the doctor, which is the true backing.'},

{cat:'zhuxing',slug:'ziwei-qisha-zai-jiegong',focus:'七杀在疾厄宫',focusEn:'Qi Sha in the Health Palace',
 cnT:'七杀在疾厄宫：起病急猛别硬扛，外伤防护要到位',enT:'Qi Sha in the Health Palace: Acute Onset and Injury Care',
 cnD:'七杀属金、主肃杀，在疾厄宫多指向肺、呼吸道与外伤，起病常急、来势猛；重在日常防护、运动劳作防外伤，急症当机立断就医，一刻都别观望。',
 enD:'Qi Sha belongs to metal and governs sternness; in the Health Palace it often points to the lungs, respiratory tract and injury, with sudden and forceful onset. Protect daily, prevent injury in sport and work, and seek decisive emergency care without waiting.',
 cnL:'急病像急雨，来得又快又猛；别想着等雨自己停，先找地方躲、找对人，才不被淋透。',
 enL:'Acute illness is like a sudden rain, fast and fierce; do not wait for it to stop, find shelter and the right help before being soaked.',
 cnA:'有人受了外伤、突发剧痛还想忍一忍，风险很大；星曜是倾向，外伤急症绝不能凭硬气，得立即处理。',
 enA:'Some endure injury or sudden severe pain, which is risky; stars are tendency, while injury and emergencies must never rely on toughness and need immediate care.',
 cnLog:['七杀属金主肃杀，重点在肺、呼吸道、外伤。','起病急、来势猛。','日常防护、急症立即就医。','倾向非诊断，以正规就医为准。'],
 enLog:['Qi Sha is metal and stern, focus on lungs, respiratory tract and injury.','Onset is sudden and fierce.','Protect daily, seek emergency care at once.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['劳作运动做好外伤防护','换季注意呼吸道、护肺','突发剧痛高热立即急诊','外伤及时清创处理','不硬扛、不观望','以医生处理为准'],
 enStep:['Guard against injury in work and sport','Mind respiratory health at season changes, protect lungs','Go to emergency for sudden pain or fever','Clean and treat injury promptly','Do not tough it out or wait','Follow medical handling'],
 cnMis:['外伤急症硬扛观望','劳作运动不防护','把起病猛的不适当小事'],
 enMis:['Toughing out injury and emergencies','No protection in work and sport','Taking fierce-onset ills lightly'],
 cnClose:'七杀在疾厄宫，最怕「急病还硬扛」。防护到位、外伤及时处理，急症当机立断送医，别拿身体赌胆量。',
 enClose:'Qi Sha in the Health Palace most fears toughing out acute ills. Protect well, treat injury promptly and seek emergency care decisively rather than betting the body on nerve.'},

{cat:'zhuxing',slug:'ziwei-pojun-zai-jiegong',focus:'破军在疾厄宫',focusEn:'Po Jun in the Health Palace',
 cnT:'破军在疾厄宫：旧疾反复别大意，变动期重牙骨与复查',enT:'Po Jun in the Health Palace: Recurring ills, Teeth and Bones',
 cnD:'破军属水、主耗与变动，在疾厄宫多指向牙齿、骨骼与旧疾反复，生活大变动时尤为明显；重在变动期稳住作息、旧患勤复查，需要正规治疗（含手术）时听专业意见。',
 enD:'Po Jun belongs to water and governs depletion and change; in the Health Palace it often points to teeth, bones and recurring ills, especially during big life changes. Keep routines steady in transitions, recheck old ills diligently, and follow professional advice when formal treatment including surgery is needed.',
 cnL:'旧疾像没关严的窗，一逢变天、变动就漏风；平时多检查，才不至于手忙脚乱。',
 enL:'Old ills are like a loose window that leaks at every change of weather; check often to avoid scrambling.',
 cnA:'有人觉得旧疾老样子、不复查，结果加重；星曜是倾向，牙骨与反复病要规范复查，治疗方案由医生定。',
 enA:'Some assume old ills stay the same and skip rechecks, then worsen; stars are tendency, while teeth, bones and recurring ills need regular rechecks and a doctor plan.',
 cnLog:['破军属水主耗变，重点在牙骨、旧疾反复。','生活变动期更明显。','稳作息、旧患勤复查。','倾向非诊断，以正规就医为准。'],
 enLog:['Po Jun is water governing depletion and change, focus on teeth, bones and recurring ills.','More evident during life changes.','Keep routines steady, recheck old ills.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['变动期稳住作息饮食','注意牙齿骨骼养护','旧疾定期复查、不凭老经验','需要治疗时听专科意见','规范处理、不拖延','以医生方案为准'],
 enStep:['Keep routines and diet steady in transitions','Care for teeth and bones','Recheck old ills regularly, not on old assumptions','Follow specialist advice when treatment is needed','Handle properly, do not delay','Follow the doctor plan'],
 cnMis:['旧疾不复查、凭老经验','变动期作息紊乱','把牙骨反复信号当小事'],
 enMis:['Skipping rechecks, relying on old experience','Loose routines during transitions','Taking recurring teeth and bone signals lightly'],
 cnClose:'破军在疾厄宫，重在「变动中守稳、旧疾勤复查」。牙骨多关照，治疗听专科，别让老问题在变动里加重。',
 enClose:'Po Jun in the Health Palace focuses on staying steady through change and rechecking old ills. Care for teeth and bones, follow specialists and do not let old problems worsen in transitions.'},

{cat:'fuzhu',slug:'ziwei-zuofu-zai-jiegong',focus:'左辅在疾厄宫',focusEn:'Zuo Fu in the Health Palace',
 cnT:'左辅在疾厄宫：恢复有助力，却别因有人照顾而大意',enT:'Zuo Fu in the Health Palace: Good Recovery, No Complacency',
 cnD:'左辅属土、为助力星，在疾厄宫多提示病中有人照护、恢复力较好；但助力容易让人放松警惕、忽视复查。重在感恩照护之余，仍按医嘱、不擅自停药。',
 enD:'Zuo Fu belongs to earth and is a support star; in the Health Palace it suggests care from others during illness and fairly good recovery. But support can ease vigilance and skip rechecks; while grateful for care, still follow doctor orders and do not stop medicine on your own.',
 cnL:'有人搭把手是福气，可路还得自己走；药按时吃、复查按时去，不能全指望别人盯着。',
 enL:'Help from others is a blessing, yet you walk the road yourself; take medicine on time and keep rechecks rather than relying on being watched.',
 cnA:'有人觉得恢复快、有人照顾就提前停药，结果反复；星曜是倾向，康复节奏仍要以医生判断为准。',
 enA:'Some recover fast with care and stop medicine early, then relapse; stars are tendency, while recovery pace still follows the doctor.',
 cnLog:['左辅属土为助力，病中有人照护、恢复较好。','易因助力放松警惕。','遵医嘱、不擅自停药。','倾向非诊断，以正规就医为准。'],
 enLog:['Zuo Fu is earth and support, suggesting care and good recovery.','Support can ease vigilance.','Follow doctor orders, do not stop medicine.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['感谢并接受他人照护','仍按医嘱按时用药','定期复查、不提前结束治疗','作息饮食配合恢复','有反复及时就诊','以医生判断为准'],
 enStep:['Accept care from others with gratitude','Still take medicine on time per orders','Recheck regularly, do not end treatment early','Support recovery with routines and diet','Seek care for relapse','Follow the doctor judgment'],
 cnMis:['因有人照顾而大意','恢复快就擅自停药','忽视复查随访'],
 enMis:['Growing complacent due to care','Stopping medicine on quick recovery','Skipping rechecks and follow-up'],
 cnClose:'左辅在疾厄宫是「恢复有贵人」的好信号，但康复靠自己守。医嘱照做、复查照去，别让助力变成松懈的理由。',
 enClose:'Zuo Fu in the Health Palace is a good sign of supportive recovery, yet recovery rests on your own discipline. Follow orders and rechecks, and do not let support become a reason to slacken.'},

{cat:'fuzhu',slug:'ziwei-youbi-zai-jiegong',focus:'右弼在疾厄宫',focusEn:'You Bi in the Health Palace',
 cnT:'右弼在疾厄宫：情志有陪伴，养病别忘心情也需照料',enT:'You Bi in the Health Palace: Companionship and Emotional Care',
 cnD:'右弼属水、为助力星，在疾厄宫多提示病中得陪伴、情志有慰藉，利于康复；但也易因情绪依赖而忽视规范治疗。重在身心同治，陪伴之外仍听医生的。',
 enD:'You Bi belongs to water and is a support star; in the Health Palace it suggests companionship and emotional comfort during illness, aiding recovery. Yet emotional reliance can overshadow proper treatment. Treat body and mind together, and beyond companionship still follow the doctor.',
 cnL:'养病也养心情，有人陪着说说话，苦就轻一半；但心情好了，药和检查一样不能落。',
 enL:'Healing also tends the mood; a companion to talk with halves the burden, yet with a lighter mood, medicine and checks must not be dropped.',
 cnA:'有人情绪好就觉得病也好了、疏于治疗，结果反复；星曜是倾向，情志有助、规范治疗仍是根本。',
 enA:'Some feel better in mood and assume the illness is gone, neglecting treatment and relapsing; stars are tendency, while emotional help aids but proper treatment remains the root.',
 cnLog:['右弼属水为助力，病中得陪伴、情志慰藉。','易因情绪依赖忽视治疗。','身心同治、仍遵医嘱。','倾向非诊断，以正规就医为准。'],
 enLog:['You Bi is water and support, suggesting companionship and comfort.','Emotional reliance can overshadow treatment.','Treat body and mind, still follow orders.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['善用陪伴、保持好心情','不把情绪好转当病愈','规范治疗、按时用药复查','配合作息饮食','情志问题也可寻求专业帮助','以医生判断为准'],
 enStep:['Use companionship, keep good spirits','Do not take better mood as recovery','Treat properly, take medicine and recheck on time','Support with routines and diet','Seek professional help for emotional ills too','Follow the doctor judgment'],
 cnMis:['心情好就疏于治疗','过度情绪依赖','只养心情不治病'],
 enMis:['Neglecting treatment when spirits rise','Over-relying emotionally','Tending only mood without treating illness'],
 cnClose:'右弼在疾厄宫，好在「养病有陪伴、心情有人托」。但身心要同治，陪伴暖心、医嘱照行，康复才扎实。',
 enClose:'You Bi in the Health Palace blesses recovery with companionship and emotional support. Yet treat body and mind together; let companionship warm the heart and follow doctor orders for solid recovery.'}
];
