// catchup 2026-09-12 第3组：天月后8宫（财帛/疾厄/迁移/仆役/官禄/田宅/福德/父母）
module.exports=[
{cat:'fuzhu',slug:'ziwei-tianyue2-zai-caibogong',focus:'天月在财帛宫',focusEn:'Tian Yue in the Wealth Palace',
 cnT:'天月在财帛宫：钱财易有小漏，记账耐心堵漏',enT:'Tian Yue in the Wealth Palace: Small Leaks, Patient Plugging',
 cnD:'天月在财帛宫多主钱财有零星小漏、莫名小花，单笔不多、累计心疼；重在记账找漏、耐心规划，不焦虑也不大意。',
 enD:'Tian Yue in the Wealth Palace suggests scattered small leaks and unexplained little spends, small each yet adding up. Track accounts to find leaks and plan patiently, neither anxious nor careless.',
 cnL:'钱漏得最凶的常是那些没感觉的小钱；拿本子记一记，小洞就现形。',
 enL:'Money leaks most through unfelt small spends; note them down and the little holes show.',
 cnA:'有人总喊存不住钱、却从不记账；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some say they cannot save yet never track; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['天月在财帛宫，钱财零星小漏。','单笔不多、累计心疼。','记账找漏、耐心规划。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Yue in Wealth means scattered small leaks.','Small each, adding up.','Track accounts, plan patiently.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['养成记账习惯','找出零星小漏','做预算、留应急钱','不冲动消费','重大决策咨询持牌专业人士','以稳守为要'],
 enStep:['Track accounts by habit','Find scattered small leaks','Budget, keep emergency money','No impulse spending','Consult licensed professionals for big decisions','Rest on steady guarding'],
 cnMis:['不记账、找不到漏','只焦虑、不行动','忽视小钱累计'],
 enMis:['Not tracking, cannot find leaks','Only anxious, no action','Ignoring small-money buildup'],
 cnClose:'天月在财帛宫，功课是「记账堵漏、耐心规划」。小钱管好了才存得住，财务决策听持牌专业人士。',
 enClose:'Tian Yue in the Wealth Palace calls for tracking, plugging and patient planning. Mind small money to save, and consult licensed professionals.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-jiegong',focus:'天月在疾厄宫',focusEn:'Tian Yue in the Health Palace',
 cnT:'天月在疾厄宫：小毛病缠绵非重症，调养有恒别拖',enT:'Tian Yue in the Health Palace: Lingering Minor ills, Steady Care',
 cnD:'天月在疾厄宫多主体质上小毛病缠绵、时好时坏，多非重症但拖人；重在规律调养、有恒心，症状加重或持续正规就医。',
 enD:'Tian Yue in the Health Palace suggests lingering minor ills that come and go, mostly not serious yet dragging. Care steadily with consistency and seek formal care if symptoms worsen or persist.',
 cnL:'缠绵小病最考验耐心，你越把作息规律当回事，它越没处赖。',
 enL:'Lingering minor ills test patience; the more you keep regular hours, the less room they have.',
 cnA:'有人对小毛病不在意、拖成麻烦，或焦虑乱治；星曜是倾向，健康以正规就医为准。',
 enA:'Some ignore minor ills until trouble, or fret and treat randomly; stars are tendency, while health relies on formal care.',
 cnLog:['天月在疾厄宫，小毛病缠绵。','多非重症、但拖人。','规律调养、有恒心。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Yue in Health means lingering minor ills.','Mostly not serious but dragging.','Care steadily, with consistency.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['规律作息饮食','小毛病有恒调养','不硬拖、不乱治','症状持续或加重就诊','按医嘱随访','以规范为要'],
 enStep:['Keep regular hours and diet','Care for minor ills consistently','Do not delay or treat randomly','Seek care if ills persist or worsen','Follow doctor orders','Rest on proper care'],
 cnMis:['小毛病硬拖','焦虑乱吃药','作息无规律'],
 enMis:['Toughing out minor ills','Fretting, random medicine','Irregular hours'],
 cnClose:'天月在疾厄宫，是「小病缠绵、非重症」的提示。调养有恒、不拖不乱，真不适应正规就医。',
 enClose:'Tian Yue in the Health Palace suggests lingering minor ills, not serious. Care steadily, neither delay nor random treat, and seek formal care for real discomfort.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-qianyi',focus:'天月在迁移宫',focusEn:'Tian Yue in the Travel Palace',
 cnT:'天月在迁移宫：外出易有小延误，提前规划不急躁',enT:'Tian Yue in the Travel Palace: Small Delays, Calm Planning',
 cnD:'天月在迁移宫多主外出、通勤、旅行易遇小延误、小插曲，事不大却磨人；重在提前出门、留余量，遇状况不急躁、冷静处理。',
 enD:'Tian Yue in the Travel Palace suggests small delays and hiccups in commuting and travel, minor yet trying. Leave early with margin and handle matters calmly, not irritably.',
 cnL:'出门留个十分钟余量，小延误就绊不住你；越是赶时间，越容易出岔子。',
 enL:'Leave ten minutes margin and small delays cannot trip you; the more you rush, the more goes wrong.',
 cnA:'有人把行程排到分秒、一延误就上火；星曜是倾向，从容靠余量。',
 enA:'Some schedule to the minute and flare at delays; stars are tendency, while calm comes from margin.',
 cnLog:['天月在迁移宫，外出易小延误。','事不大、却磨人。','提前规划、留余量。','倾向描述，非绝对定论。'],
 enLog:['Tian Yue in Travel means small delays away.','Minor but trying.','Plan ahead, leave margin.','This is tendency, not an absolute verdict.'],
 cnStep:['出门提前、留余量','行程别排太满','遇延误冷静应对','备好替代路线','心态放从容','以平安为要'],
 enStep:['Leave early with margin','Do not overpack schedules','Handle delays calmly','Ready alternative routes','Stay poised','Rest on safe travel'],
 cnMis:['行程排满、不留余','一延误就急躁','常卡点出门'],
 enMis:['Schedules packed, no margin','Irritable at delays','Always leaving on the dot'],
 cnClose:'天月在迁移宫，小延误难免，贵在「提前、留余、不急躁」。从容出行，小插曲就乱不了你。',
 enClose:'Tian Yue in the Travel Palace makes small delays normal; leave early with margin and stay calm so hiccups do not disrupt you.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-puyigong',focus:'天月在仆役宫',focusEn:'Tian Yue in the Friends Palace',
 cnT:'天月在仆役宫：朋友间易有小误会，坦诚说开不积累',enT:'Tian Yue in the Friends Palace: Small Misunderstandings, Open Talk',
 cnD:'天月在仆役宫多主与朋友、部属易有小误会、小别扭，拖一拖也散，但易反复；重在坦诚沟通、就事论事，别让小误会积成隔阂。',
 enD:'Tian Yue in the Friends Palace suggests small misunderstandings with friends and staff that linger and disperse yet recur. Talk openly, stick to the matter and do not let them pile into distance.',
 cnL:'朋友间最怕话憋着，小误会坦诚一句就化开；老不挑明，反而生分成真。',
 enL:'With friends, held words hurt most; an open sentence dissolves small misunderstandings; left unsaid, distance turns real.',
 cnA:'有人对小误会装没事、心里记账，关系渐淡；星曜是倾向，朋友靠坦诚维护。',
 enA:'Some pretend all is well while keeping score, thinning bonds; stars are tendency, while friends need openness.',
 cnLog:['天月在仆役宫，朋友易小误会。','拖散但易反复。','坦诚沟通、不积累。','倾向描述，非绝对定论。'],
 enLog:['Tian Yue in Friends means small misunderstandings.','They disperse but recur.','Talk openly, do not pile up.','This is tendency, not an absolute verdict.'],
 cnStep:['小误会坦诚说开','就事论事、不记账','主动沟通','珍惜朋友、换位想','不翻旧账','以长久为要'],
 enStep:['Talk small misunderstandings through openly','Stick to the matter, no score-keeping','Communicate actively','Value friends, change places','No old scores','Rest on lasting bonds'],
 cnMis:['装没事、心里记账','小误会不挑明','对朋友缺坦诚'],
 enMis:['Pretending fine while keeping score','Not clarifying small misunderstandings','Lacking openness with friends'],
 cnClose:'天月在仆役宫，小误会难免，重在「坦诚、不积累」。话挑明了，朋友才不生分。',
 enClose:'Tian Yue in the Friends Palace makes small misunderstandings normal; be open and do not pile up. Clarify so friends do not grow distant.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-guanlugong',focus:'天月在官禄宫',focusEn:'Tian Yue in the Career Palace',
 cnT:'天月在官禄宫：事业易被琐事拖，分清轻重提效率',enT:'Tian Yue in the Career Palace: Trifles That Drag, Clear Priorities',
 cnD:'天月在官禄宫多主工作上琐事多、小卡壳，忙却推进慢；重在列优先级、抓重点，减少无效忙碌，别让小事占了大头精力。',
 enD:'Tian Yue in the Career Palace suggests many trifles and small stalls, busy yet slow to advance. Set priorities, focus on what matters and cut ineffective busyness so small things do not take most energy.',
 cnL:'工作常被琐事拖住，像船缠了水草；先把草清一清，船才走得动。',
 enL:'Work is often caught in trifles like a boat in weeds; clear the weeds first so it moves.',
 cnA:'有人忙一天却说不出成果，被琐事牵着走；星曜是倾向，效率靠分清轻重。',
 enA:'Some are busy all day without result, led by trifles; stars are tendency, while efficiency comes from priorities.',
 cnLog:['天月在官禄宫，琐事多、推进慢。','忙却被小事牵。','列优先级、抓重点。','倾向描述，非绝对定论。'],
 enLog:['Tian Yue in Career means many trifles, slow advance.','Busy but led by small things.','Set priorities, focus.','This is tendency, not an absolute verdict.'],
 cnStep:['列出每日优先级','先做重要的事','减少无效琐事','定时复盘进度','学会说不','以结果为要'],
 enStep:['List daily priorities','Do important things first','Cut ineffective trifles','Review progress regularly','Learn to say no','Rest on results'],
 cnMis:['被琐事牵、忙而不果','不分轻重','不复盘、不拒绝'],
 enMis:['Led by trifles, busy without result','No priorities','No review, no saying no'],
 cnClose:'天月在官禄宫，要破「琐事拖效率」。分清轻重、抓重点，工作才忙得有成果。',
 enClose:'Tian Yue in the Career Palace breaks trifles that drag efficiency. Set priorities and focus so busy work yields results.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-tianzhaigong',focus:'天月在田宅宫',focusEn:'Tian Yue in the Property Palace',
 cnT:'天月在田宅宫：居家易有小修小补，规划打理不心烦',enT:'Tian Yue in the Property Palace: Small Fixes, Calm Upkeep',
 cnD:'天月在田宅宫多主居家易有小修小补、小杂事，零零碎碎却占心；重在提前打理、列清单，遇事不烦、一件件来。',
 enD:'Tian Yue in the Property Palace suggests small repairs and household odds and ends, scattered yet on the mind. Upkeep ahead, make lists and handle matters calmly one by one.',
 cnL:'家里的杂事像看不见底的小清单，你越有计划地清，它越压不住你。',
 enL:'Household odds are like an endless small list; the more planned you clear them, the less they weigh.',
 cnA:'有人为居家小事心烦、拖着不管，小事攒成大麻烦；星曜是倾向，打理靠计划。',
 enA:'Some fret over small home matters and delay, letting them grow; stars are tendency, while upkeep rests on plans.',
 cnLog:['天月在田宅宫，居家小修小补。','零碎却占心。','提前打理、列清单。','倾向描述，非绝对定论。'],
 enLog:['Tian Yue in Property means small home fixes.','Scattered yet on the mind.','Upkeep ahead, make lists.','This is tendency, not an absolute verdict.'],
 cnStep:['居家杂事列清单','小修小补及时处理','提前打理、不堆积','遇事一件件来','保持家宅整洁','以省心为要'],
 enStep:['List household odds','Handle small fixes in time','Upkeep ahead, do not pile','Do things one by one','Keep the home tidy','Rest on peace of mind'],
 cnMis:['小修小补拖着','为杂事心烦、堆积','居家无计划'],
 enMis:['Delaying small fixes','Fretting, piling odds','No household plan'],
 cnClose:'天月在田宅宫，居家小杂事难免，重在「计划、及时、不堆积」。家打理顺了，心才不烦。',
 enClose:'Tian Yue in the Property Palace makes small home matters normal; plan, handle in time and do not pile. A smooth home keeps the mind calm.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-fudegong',focus:'天月在福德宫',focusEn:'Tian Yue in the Blessings Palace',
 cnT:'天月在福德宫：小情绪易反复，学会自我疏解',enT:'Tian Yue in the Blessings Palace: Recurring Small Moods, Self-Care',
 cnD:'天月在福德宫多主小情绪、小纠结容易反复，说大不大、却影响心情；重在觉察情绪、自我疏解，给心情留白，必要时寻求专业帮助。',
 enD:'Tian Yue in the Blessings Palace suggests recurring small moods and little knots, not grave yet affecting the mind. Notice emotions, ease yourself and leave the mood blank, seeking professional help when needed.',
 cnL:'小情绪像天气，来了会走；你肯照顾它、不硬压，它散得更快。',
 enL:'Small moods are like weather, coming and going; tend them without forcing down and they clear faster.',
 cnA:'有人对小情绪硬压或钻进去，越陷越深；星曜是倾向，情绪需疏导。',
 enA:'Some force down small moods or sink into them, going deeper; stars are tendency, while emotions need channeling.',
 cnLog:['天月在福德宫，小情绪易反复。','不大、却影响心情。','觉察、疏解、留白。','倾向描述，非绝对定论。'],
 enLog:['Tian Yue in Blessings means recurring small moods.','Not grave, yet affecting the mind.','Notice, ease, leave blank.','This is tendency, not an absolute verdict.'],
 cnStep:['觉察自己的情绪','用倾诉运动疏解','给心情留白时间','不硬压、不钻角','必要时寻求专业帮助','以心安为要'],
 enStep:['Notice your emotions','Ease through talk and exercise','Leave the mind blank','Do not force down or fixate','Seek professional help when needed','Rest on a calm heart'],
 cnMis:['硬压情绪','钻进小纠结','不疏解、不求助'],
 enMis:['Forcing emotions down','Sinking into small knots','Neither easing nor asking help'],
 cnClose:'天月在福德宫，小情绪难免，贵在「觉察、疏解、留白」。照顾好心情，精神才轻安。',
 enClose:'Tian Yue in the Blessings Palace makes small moods normal; notice, ease and leave blank. Tend the mood for steady ease.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-fumugong',focus:'天月在父母宫',focusEn:'Tian Yue in the Parents Palace',
 cnT:'天月在父母宫：与长辈易有小代沟，耐心沟通不较真',enT:'Tian Yue in the Parents Palace: Small Generation Gaps, Patient Talk',
 cnD:'天月在父母宫多主与父母、长辈易有小代沟、小拌嘴，事不大却易僵；重在耐心倾听、换位思考，不争输赢，多陪伴体谅。',
 enD:'Tian Yue in the Parents Palace suggests small generation gaps and little spats with elders, minor yet easy to stiffen. Listen patiently, change places, do not fight to win and accompany more.',
 cnL:'和长辈争赢了道理、往往输了感情；退一步、好好说，代沟就没那么宽。',
 enL:'Winning reason against elders often loses affection; step back, speak well and the gap narrows.',
 cnA:'有人对长辈较真、硬碰硬，小事闹僵；星曜是倾向，亲情靠耐心。',
 enA:'Some are stubborn with elders and stiffen small matters; stars are tendency, while kinship needs patience.',
 cnLog:['天月在父母宫，长辈间小代沟。','事不大、却易僵。','耐心倾听、换位体谅。','倾向描述，非绝对定论。'],
 enLog:['Tian Yue in Parents means small generation gaps.','Minor yet easy to stiffen.','Listen patiently, understand.','This is tendency, not an absolute verdict.'],
 cnStep:['耐心听长辈说','换位思考、不较真','小拌嘴主动缓和','多陪伴、少争辩','表达关心','以家和为要'],
 enStep:['Listen to elders patiently','Change places, do not be stubborn','Smooth small spats actively','Accompany more, argue less','Show care','Rest on family harmony'],
 cnMis:['和长辈硬碰硬','较真争输赢','缺耐心、不陪伴'],
 enMis:['Being stubborn with elders','Fighting to win','Impatient, not present'],
 cnClose:'天月在父母宫，小代沟难免，重在「耐心、换位、不较真」。好好说话、多陪伴，亲情才不被小事僵住。',
 enClose:'Tian Yue in the Parents Palace makes small gaps normal; be patient, understanding and not stubborn. Speak well and accompany so kinship is not stiffened.'}
];
