// catchup 2026-09-13 第3组：病符后8宫
module.exports=[
{cat:'fuzhu',slug:'ziwei-bingfu-zai-caibogong',focus:'病符在财帛宫',focusEn:'Bing Fu in the Wealth Palace',
 cnT:'病符在财帛宫：易有医疗健康支出，提前规划留预算',enT:'Bing Fu in the Wealth Palace: Planning for Health Expenses',
 cnD:'病符在财帛宫多主钱财上容易有医疗、健康类支出；重在提前规划、留好这部分预算和保障，不临时抓瞎，把钱花在预防和规范治疗上。',
 enD:'Bing Fu in the Wealth Palace suggests money often going to medical and health expenses. Plan ahead, keep budget and protection for this so you are not caught short, spending on prevention and proper care.',
 cnL:'健康的钱省不得也慌不得；预算和保障留在前，真要用时才不犯难。',
 enL:'Health money can be neither saved away nor panicked about; keep budget and protection ahead.',
 cnA:'有人不做健康预算、一遇支出就乱；星曜是倾向，本内容不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:'Some make no health budget and panic at expenses; stars are tendency, and this is not investment advice, so rely on licensed institutions and formal terms.',
 cnLog:['病符在财帛宫，易有医疗支出。','提前规划、留预算保障。','花在预防和规范治疗。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Bing Fu in Wealth means medical expenses.','Plan ahead, keep budget and protection.','Spend on prevention and proper care.','Not investment advice; rely on licensed institutions and formal terms.'],
 cnStep:['预留健康医疗预算','配置合适的保障','重视预防、减少大病支出','选择正规机构','重大决策咨询持牌专业人士','以稳为要'],
 enStep:['Reserve a health budget','Arrange suitable protection','Value prevention to cut big costs','Choose formal institutions','Consult licensed professionals for big decisions','Rest on steadiness'],
 cnMis:['不留医疗预算','不做保障','生病才临时抓瞎'],
 enMis:['No health budget','No protection','Caught short when ill'],
 cnClose:'病符在财帛宫，功课是「为健康提前规划」。预算保障留好，钱用在预防和正规治疗上。',
 enClose:'Bing Fu in the Wealth Palace calls for planning ahead for health. Keep budget and protection and spend on prevention and proper care.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-jiegong',focus:'病符在疾厄宫',focusEn:'Bing Fu in the Health Palace',
 cnT:'病符在疾厄宫：体质偏易病，预防为先、早就医',enT:'Bing Fu in the Health Palace: Prevention and Early Care',
 cnD:'病符在疾厄宫是较直接的健康提示，主体质偏敏感、容易生病；重在预防为先、规律生活，有症状早就医、不拖延硬扛，按医嘱规范处理。',
 enD:'Bing Fu in the Health Palace is a fairly direct health sign, suggesting a sensitive, illness-prone constitution. Put prevention first, live regularly, seek early care for symptoms without delay and follow doctor orders.',
 cnL:'容易生病的人，赢在预防和早治；小病不拖、规范处理，就不容易拖成麻烦。',
 enL:'The illness-prone win at prevention and early care; do not delay small ills.',
 cnA:'有人爱硬扛、拖延就诊，小病变大；星曜是倾向，健康以正规就医为准。',
 enA:'Some tough it out and delay, letting ills grow; stars are tendency, while health relies on formal care.',
 cnLog:['病符在疾厄宫，体质偏易病。','预防为先、早就医。','不硬扛、按医嘱。','倾向非诊断，以正规就医为准。'],
 enLog:['Bing Fu in Health means an illness-prone constitution.','Prevention first, early care.','Do not tough it out, follow orders.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['规律作息、增强体质','重视预防、按时体检','有症状及时就诊','不硬扛、不乱治','按医嘱随访','以规范为要'],
 enStep:['Regular hours, build constitution','Prevention, check-ups on schedule','Seek timely care for symptoms','Do not tough out or treat randomly','Follow doctor orders','Rest on proper care'],
 cnMis:['硬扛拖延','小病不重视','作息无规律'],
 enMis:['Toughing out, delaying','Ignoring small ills','Irregular hours'],
 cnClose:'病符在疾厄宫，是直接的健康提示。预防为先、早就医、不硬扛，身体才稳妥。',
 enClose:'Bing Fu in the Health Palace is a direct health sign. Put prevention first, seek early care and do not tough it out.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-qianyi',focus:'病符在迁移宫',focusEn:'Bing Fu in the Travel Palace',
 cnT:'病符在迁移宫：外出易水土不服，备好药品重健康',enT:'Bing Fu in the Travel Palace: Ready for Travel Ailments',
 cnD:'病符在迁移宫多主外出、旅行时容易水土不服、肠胃不适或小毛病；重在出行备好常用药、注意饮食卫生，身体不适及时当地就医。',
 enD:'Bing Fu in the Travel Palace suggests travel-related ailments such as upset digestion or small ills. Carry basic medicines, mind food hygiene and seek local care if unwell.',
 cnL:'出远门，身体最容易在换水土时闹脾气；常用药带上、卫生注意，玩得才踏实。',
 enL:'Far from home, the body often reacts to new surroundings; carry basic medicines and mind hygiene.',
 cnA:'有人外出不注意饮食、不带药，小毛病扫了兴；星曜是倾向，健康靠自己留心。',
 enA:'Some ignore food hygiene and carry no medicines, letting ills spoil trips; stars are tendency, while health needs care.',
 cnLog:['病符在迁移宫，外出易小毛病。','备常用药、重卫生。','不适当地就医。','倾向非诊断，以正规就医为准。'],
 enLog:['Bing Fu in Travel means travel ills.','Carry medicines, mind hygiene.','Seek local care if unwell.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['出行备常用药','注意饮食饮水卫生','作息别太乱','了解当地就医信息','不适及时处理','以平安为要'],
 enStep:['Carry basic medicines','Mind food and water hygiene','Keep reasonable hours','Know local care options','Handle discomfort in time','Rest on safe travel'],
 cnMis:['不注意饮食卫生','出门不带药','小毛病硬撑'],
 enMis:['Ignoring food hygiene','No medicines when traveling','Toughing out ills'],
 cnClose:'病符在迁移宫，外出「备药、重卫生、早就医」。身体照顾好，旅途才顺心。',
 enClose:'Bing Fu in the Travel Palace calls for medicines, hygiene and early care. Look after your health for a smooth trip.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-puyigong',focus:'病符在仆役宫',focusEn:'Bing Fu in the Friends Palace',
 cnT:'病符在仆役宫：朋友部属健康多关心，体谅不苛责',enT:'Bing Fu in the Friends Palace: Caring for Associates Health',
 cnD:'病符在仆役宫多主朋友、部属中有人健康偏弱，管理相处时多体谅；重在关心他人健康、生病不苛责，人情味也是凝聚力。',
 enD:'Bing Fu in the Friends Palace suggests friends or staff with weaker health, calling for understanding. Care about their health and do not be harsh when they are ill, for human warmth binds people.',
 cnL:'身边人身体弱时，一句体谅比十句催促管用；你关心人，人才愿意留下。',
 enL:'When associates are unwell, understanding beats urging; care for people and they stay.',
 cnA:'有人对生病的部属朋友苛责、缺人情味；星曜是倾向，相处靠将心比心。',
 enA:'Some are harsh with unwell associates; stars are tendency, while relating needs empathy.',
 cnLog:['病符在仆役宫，身边人健康弱。','多体谅、不苛责。','人情味聚人。','倾向描述，非绝对定论。'],
 enLog:['Bing Fu in Friends means associates with weak health.','Be understanding, not harsh.','Human warmth binds people.','This is tendency, not an absolute verdict.'],
 cnStep:['关心身边人健康','生病时体谅不苛责','合理安排事务','给予必要照顾','将心比心','以长久相处为要'],
 enStep:['Care about associates health','Be understanding when they are ill','Arrange matters reasonably','Offer needed care','Empathize','Rest on lasting relations'],
 cnMis:['苛责生病的人','缺人情味','只讲事、不讲情'],
 enMis:['Harsh with unwell associates','Lacking warmth','Only tasks, no care'],
 cnClose:'病符在仆役宫，身边人健康多体谅。关心不苛责，人情味才聚得住人。',
 enClose:'Bing Fu in the Friends Palace calls for understanding of associates health. Care and do not be harsh so warmth binds people.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-guanlugong',focus:'病符在官禄宫',focusEn:'Bing Fu in the Career Palace',
 cnT:'病符在官禄宫：劳逸结合，别让身体拖了事业',enT:'Bing Fu in the Career Palace: Balance Work and Rest',
 cnD:'病符在官禄宫多主工作辛苦、容易因劳累影响健康，反过来拖事业；重在劳逸结合、规律作息，身体是事业的本钱，别透支。',
 enD:'Bing Fu in the Career Palace suggests hard work where strain affects health and in turn career. Balance work and rest, keep regular hours and do not overdraw the body, the foundation of work.',
 cnL:'拼事业最怕拿健康换；你把休息和身体顾好，路才走得长。',
 enL:'Careers most suffer trading health; mind rest and the body to go far.',
 cnA:'有人拼命加班、透支身体，结果两头空；星曜是倾向，可持续比一时猛更值。',
 enA:'Some overwork and overdraw, losing both; stars are tendency, while sustainability beats short bursts.',
 cnLog:['病符在官禄宫，劳累影响健康。','劳逸结合、不透支。','身体是事业本钱。','倾向描述，非绝对定论。'],
 enLog:['Bing Fu in Career means strain affecting health.','Balance work and rest, do not overdraw.','Health is the foundation of work.','This is tendency, not an absolute verdict.'],
 cnStep:['合理安排工作休息','规律作息、不透支','坚持锻炼','累了及时调整','效率优先于硬熬','以可持续为要'],
 enStep:['Balance work and rest','Regular hours, do not overdraw','Keep exercising','Adjust when tired','Efficiency over grinding','Rest on sustainability'],
 cnMis:['拼命加班透支','劳逸失衡','拿健康换业绩'],
 enMis:['Overworking, overdrawing','No work-rest balance','Trading health for results'],
 cnClose:'病符在官禄宫，要破「劳累拖垮身体和事业」。劳逸结合、顾好本钱，路才长。',
 enClose:'Bing Fu in the Career Palace breaks strain that harms health and work. Balance and guard your foundation for the long road.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-tianzhaigong',focus:'病符在田宅宫',focusEn:'Bing Fu in the Property Palace',
 cnT:'病符在田宅宫：讲究家宅卫生，环境整洁少生病',enT:'Bing Fu in the Property Palace: A Clean, Healthy Home',
 cnD:'病符在田宅宫多主家宅卫生、通风采光与家人健康相关；重在保持环境整洁、勤通风、防霉防积尘，家里干净，病自然少。',
 enD:'Bing Fu in the Property Palace links home hygiene, ventilation and light to family health. Keep the home clean and aired, prevent mold and dust, and a tidy home means less illness.',
 cnL:'家里的整洁通风，是最便宜的健康投资；环境干净，身体少受罪。',
 enL:'A clean, aired home is the cheapest health investment; tidy surroundings spare the body.',
 cnA:'有人居家杂乱、不重卫生，家人易病；星曜是倾向，健康环境靠日常打理。',
 enA:'Some keep a messy, unhygienic home and family fall ill; stars are tendency, while a healthy environment needs upkeep.',
 cnLog:['病符在田宅宫，家宅卫生关健康。','整洁通风、防霉尘。','环境干净、病少。','倾向描述，非绝对定论。'],
 enLog:['Bing Fu in Property links home hygiene to health.','Clean and aired, prevent mold and dust.','Tidy home, less illness.','This is tendency, not an absolute verdict.'],
 cnStep:['保持居家整洁','勤通风、采光好','防霉防积尘','定期清洁厨卫','垃圾及时处理','以健康居家为要'],
 enStep:['Keep the home tidy','Air rooms, let light in','Prevent mold and dust','Clean kitchen and bath','Dispose of rubbish promptly','Rest on a healthy home'],
 cnMis:['居家杂乱不通风','不重卫生','积尘积水不清理'],
 enMis:['Messy, unaired home','Ignoring hygiene','Dust and standing water left'],
 cnClose:'病符在田宅宫，功课是「家宅整洁通风」。环境打理好，家人少生病。',
 enClose:'Bing Fu in the Property Palace calls for a clean, aired home. Tend the environment so family fall ill less.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-fudegong',focus:'病符在福德宫',focusEn:'Bing Fu in the Blessings Palace',
 cnT:'病符在福德宫：心情影响身体，养心也是养生',enT:'Bing Fu in the Blessings Palace: Mind and Body Together',
 cnD:'病符在福德宫多主情绪、心境容易影响身体，心不畅则身不舒；重在调节心情、减压放松，身心同养，必要时寻求专业帮助。',
 enD:'Bing Fu in the Blessings Palace suggests mood affecting the body, a blocked mind bringing discomfort. Regulate mood, reduce stress and relax, nurturing mind and body together, seeking professional help when needed.',
 cnL:'很多身体的不舒服，根子在心里的结；心情理顺了，身体也松快。',
 enL:'Much bodily discomfort roots in mental knots; smooth the mood and the body eases.',
 cnA:'有人只养身不养心、压着情绪；星曜是倾向，身心都要顾。',
 enA:'Some nurture body not mind, suppressing emotion; stars are tendency, while both need care.',
 cnLog:['病符在福德宫，心情影响身体。','调节情绪、减压放松。','身心同养。','倾向描述，非绝对定论。'],
 enLog:['Bing Fu in Blessings means mood affecting body.','Regulate mood, reduce stress.','Nurture mind and body together.','This is tendency, not an absolute verdict.'],
 cnStep:['调节心情、减压','用倾诉运动放松','规律作息','不硬压情绪','必要时寻求专业帮助','以身心同养为要'],
 enStep:['Regulate mood, reduce stress','Relax through talk and exercise','Keep regular hours','Do not suppress emotion','Seek professional help when needed','Rest on mind-body care'],
 cnMis:['压情绪、不养心','长期焦虑','忽视心情影响'],
 enMis:['Suppressing emotion, not nurturing mind','Long-term anxiety','Ignoring mood effects'],
 cnClose:'病符在福德宫，要懂「养心即养生」。调情绪、勤放松，身心才都舒坦。',
 enClose:'Bing Fu in the Blessings Palace reminds us nurturing mind is nurturing body. Regulate mood and relax for both to ease.'},

{cat:'fuzhu',slug:'ziwei-bingfu-zai-fumugong',focus:'病符在父母宫',focusEn:'Bing Fu in the Parents Palace',
 cnT:'病符在父母宫：长辈健康多上心，陪伴照护早就医',enT:'Bing Fu in the Parents Palace: Caring for Elders Health',
 cnD:'病符在父母宫多主父母、长辈健康需多上心，年纪大更要防慢病；重在常陪伴、定期体检、规范用药，不适及时正规就医。',
 enD:'Bing Fu in the Parents Palace suggests elders health needing attention, with chronic conditions more likely with age. Accompany often, arrange regular check-ups, use medicine properly and seek timely formal care.',
 cnL:'长辈的健康，靠平时的陪伴和定期检查；你上心，病就早发现、好处理。',
 enL:'Elders health rests on presence and regular check-ups; stay attentive for early care.',
 cnA:'有人疏于照护长辈、小病硬拖；星曜是倾向，健康以正规就医为准。',
 enA:'Some neglect elders and delay small ills; stars are tendency, while health relies on formal care.',
 cnLog:['病符在父母宫，长辈健康上心。','定期体检、规范用药。','不适及时就医。','倾向非诊断，以正规就医为准。'],
 enLog:['Bing Fu in Parents means elders health matters.','Regular check-ups, proper medicine.','Seek timely care.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['长辈定期体检','规范用药、有人照看','常陪伴、问身体','不适及时就诊','慢病按医嘱管理','以长辈安康为要'],
 enStep:['Regular elders check-ups','Proper medicine, someone watching','Accompany, ask about health','Seek timely care','Manage chronic conditions by orders','Rest on elder wellbeing'],
 cnMis:['疏于照护长辈','小病硬拖','用药不规范'],
 enMis:['Neglecting elders','Delaying small ills','Improper medicine'],
 cnClose:'病符在父母宫，长辈健康要上心。定期检查、陪伴照护、早就医，长辈才安康。',
 enClose:'Bing Fu in the Parents Palace calls for attention to elders health. Regular checks, presence and early care keep elders well.'}
];
