// catchup 2026-09-12 第2组：月德后4（官禄/田宅/福德/父母）+ 天月前4（命/兄弟/夫妻/子女）
module.exports=[
{cat:'fuzhu',slug:'ziwei-yuede-zai-guanlugong',focus:'月德在官禄宫',focusEn:'Yue De in the Career Palace',
 cnT:'月德在官禄宫：事业多贵人解围，逢难处有人搭手',enT:'Yue De in the Career Palace: Mentors Who Clear the Way',
 cnD:'月德在官禄宫多主事业上遇宽厚贵人，逢难关有人搭手、能转圜；但贵人是加分。重在自己专业过硬、知恩图报，机会才留得住。',
 enD:'Yue De in the Career Palace suggests kind mentors at work who help through hard passes and offer room to turn matters around. Mentors add to you. Stay excellent and grateful so chances hold.',
 cnL:'职场上肯在难处帮你的人是真贵人；你把本事练硬、把恩情记下，路才越走越宽。',
 enL:'Those who help at hard passes at work are true mentors; sharpen skill and remember kindness so the road widens.',
 cnA:'有人只等贵人提携、自己不精进，扶也扶不起；星曜是倾向，贵人要配实力。',
 enA:'Some wait only for mentors without growing and cannot be lifted; stars are tendency, while mentors pair with ability.',
 cnLog:['月德在官禄宫，事业遇宽厚贵人。','逢难关有人搭手、能转圜。','专业过硬、知恩图报。','倾向描述，非绝对定论。'],
 enLog:['Yue De in Career means kind mentors at work.','Help through hard passes, room to recover.','Stay excellent, be grateful.','This is tendency, not an absolute verdict.'],
 cnStep:['把专业本事练硬','珍惜事业贵人、知回报','逢难肯求助、不硬扛','把转圜机会把握好','不坐等提携','以实力+感恩为要'],
 enStep:['Sharpen professional skill','Value career mentors, repay kindness','Ask help at hard passes, do not force alone','Grasp room to recover','Do not wait to be lifted','Rest on ability plus gratitude'],
 cnMis:['只等贵人、不精进','受助不知回报','把贵人当替代'],
 enMis:['Waiting for mentors without growing','Ungrateful for help','Taking mentors as replacement'],
 cnClose:'月德在官禄宫，事业「有贵人、能转圜」是好事。实力过硬、感恩图报，贵人才长久为用。',
 enClose:'Yue De in the Career Palace blesses work with mentors and room to recover. Stay excellent and grateful so mentors help for long.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-tianzhaigong',focus:'月德在田宅宫',focusEn:'Yue De in the Property Palace',
 cnT:'月德在田宅宫：家宅和睦多包容，居家逢难有解',enT:'Yue De in the Property Palace: A Harmonious, Forgiving Home',
 cnD:'月德在田宅宫多主家庭氛围宽厚包容、家人和睦，居家遇到麻烦能化解；重在主动经营、彼此体谅，置产走正规途径。',
 enD:'Yue De in the Property Palace suggests a kind, tolerant family atmosphere with harmonious relations, where household troubles resolve. Care actively, understand one another and use formal channels for property.',
 cnL:'家是讲包容的地方，不是争输赢的地方；你让一寸、我让一寸，家里就宽了。',
 enL:'Home is for tolerance, not winning; you yield an inch, I yield an inch and the home widens.',
 cnA:'有人在家锱铢必较、把和睦耗光；星曜是倾向，家宅的宽厚靠每个人经营。',
 enA:'Some haggle at home and exhaust harmony; stars are tendency, while household kindness needs everyone caring.',
 cnLog:['月德在田宅宫，家庭宽厚和睦。','居家麻烦能化解。','主动经营、彼此体谅。','置产以正规合同和专业意见为准。'],
 enLog:['Yue De in Property means a kind, harmonious family.','Household troubles resolve.','Care actively, understand one another.','Rely on formal contracts and professional advice for property.'],
 cnStep:['经营宽厚的家庭氛围','家人彼此体谅','居家矛盾及时化解','置产走正规途径、看清合同','多陪伴家人','以家和为要'],
 enStep:['Nurture a kind family atmosphere','Understand one another','Resolve household friction in time','Use formal channels, read contracts','Companion family more','Rest on harmony at home'],
 cnMis:['在家计较、耗光和睦','忽视家庭经营','置产不走正规途径'],
 enMis:['Haggling at home, exhausting harmony','Neglecting the family','Property without formal channels'],
 cnClose:'月德在田宅宫，难得「家宅宽厚、逢难能解」。彼此体谅、家和为贵，置产走正规路。',
 enClose:'Yue De in the Property Palace offers a kind home where troubles resolve. Understand one another, value harmony and use formal channels for property.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-fudegong',focus:'月德在福德宫',focusEn:'Yue De in the Blessings Palace',
 cnT:'月德在福德宫：心宽能容事，精神上逢凶自解',enT:'Yue De in the Blessings Palace: A Broad, Self-Healing Mind',
 cnD:'月德在福德宫多主心性宽厚、能容事，精神遇到坎儿能自己想开、慢慢化解；重在知足感恩、给情绪出口，心宽即是福。',
 enD:'Yue De in the Blessings Palace suggests a broad mind able to bear matters, working through mental passes and easing them slowly. Stay content and grateful, give emotion an outlet, for a broad heart is blessing.',
 cnL:'心宽的人不是没烦恼，而是烦恼来了容得下、放得走；心里那杆秤，宽一点就轻一点。',
 enL:'Broad-minded people are not free of trouble but can hold and release it; a wider inner scale feels lighter.',
 cnA:'有人遇事钻牛角尖、和自己过不去；星曜是倾向，宽厚与放下都是可以练的。',
 enA:'Some fixate on matters and turn on themselves; stars are tendency, while tolerance and letting go are practiced.',
 cnLog:['月德在福德宫，心性宽厚能容事。','精神逢坎能自解。','知足感恩、给情绪出口。','倾向描述，非绝对定论。'],
 enLog:['Yue De in Blessings means a broad, bearing mind.','Mental passes can self-resolve.','Stay content, give emotion an outlet.','This is tendency, not an absolute verdict.'],
 cnStep:['遇事往宽处想','培养知足感恩的心','给情绪找出口','少钻牛角尖','用兴趣运动养心','以心安为要'],
 enStep:['Think broadly in trouble','Cultivate contentment and gratitude','Give emotion an outlet','Fixate less','Nourish the mind with interests and exercise','Rest on a calm heart'],
 cnMis:['钻牛角尖、和自己过不去','遇事放不下','忽视情绪出口'],
 enMis:['Fixating, turning on self','Unable to let matters go','Ignoring emotional outlets'],
 cnClose:'月德在福德宫，是「心宽能容、逢凶自解」的好配置。知足、放下、有出口，精神才轻安。',
 enClose:'Yue De in the Blessings Palace is a fine sign of a broad, self-healing mind. Stay content, let go and keep an outlet for steady ease.'},

{cat:'fuzhu',slug:'ziwei-yuede-zai-fumugong',focus:'月德在父母宫',focusEn:'Yue De in the Parents Palace',
 cnT:'月德在父母宫：长辈宽厚多包容，得庇荫知感恩',enT:'Yue De in the Parents Palace: Kind Elders and Gratitude',
 cnD:'月德在父母宫多主父母、长辈仁厚包容，能得长辈庇荫与谅解；重在孝敬感恩、主动沟通，别把长辈的宽厚当理所当然。',
 enD:'Yue De in the Parents Palace suggests kind, tolerant parents and elders, offering shelter and understanding. Be filial and grateful, communicate actively, not taking elder kindness for granted.',
 cnL:'宽厚的长辈是家里的福；你肯走近、肯感恩，那分庇荫才暖得长久。',
 enL:'Kind elders are a family blessing; draw close and be grateful so the shelter stays warm.',
 cnA:'有人把长辈包容当本分、疏于孝敬；星曜是倾向，亲情靠感恩经营。',
 enA:'Some take elder tolerance as due and neglect filial piety; stars are tendency, while kinship needs gratitude.',
 cnLog:['月德在父母宫，长辈仁厚包容。','得庇荫与谅解。','孝敬感恩、主动沟通。','倾向描述，非绝对定论。'],
 enLog:['Yue De in Parents means kind, tolerant elders.','Shelter and understanding.','Be filial, communicate actively.','This is tendency, not an absolute verdict.'],
 cnStep:['孝敬宽厚的长辈','主动沟通、多陪伴','感恩庇荫、不视为当然','遇事多体谅','珍惜亲情','以家和为要'],
 enStep:['Be filial to kind elders','Communicate actively, accompany more','Be grateful, not taking as due','Understand in matters','Value kinship','Rest on family harmony'],
 cnMis:['把长辈宽厚当本分','疏于孝敬陪伴','只受庇荫、不感恩'],
 enMis:['Taking elder kindness as due','Neglecting filial piety and presence','Only sheltered, not grateful'],
 cnClose:'月德在父母宫，难得「长辈宽厚、得庇荫」。感恩、孝敬、多陪伴，亲情才暖、才长久。',
 enClose:'Yue De in the Parents Palace offers kind, sheltering elders. Be grateful, filial and present so kinship stays warm and lasting.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-minggong',focus:'天月在命宫',focusEn:'Tian Yue in the Life Palace',
 cnT:'天月在命宫：小毛病易缠绵，耐心调养别小题大做',enT:'Tian Yue in the Life Palace: Minor Lingering Ailments, Patient Care',
 cnD:'天月主小毛病、缠绵但非重症，在命宫多主体质上小病小痛不断、拖得久，却无大碍；重在规律作息、耐心调养，既不忽视也不焦虑，真不适正规就医。',
 enD:'Tian Yue governs minor, lingering rather than serious ailments; in the Life Palace it suggests recurring small ills that drag on without great harm. Keep regular hours and care patiently, neither ignoring nor anxious, and seek formal care for real discomfort.',
 cnL:'小毛病像黏人的毛毛雨，下不大却老不停；带把伞、稳住心，别它没淋透你、你先慌了神。',
 enL:'Minor ills are like clinging drizzle, never heavy yet constant; take an umbrella and stay calm, lest you panic before getting wet.',
 cnA:'有人把小痛想成大病、整日焦虑，或不当回事硬拖；星曜是倾向，健康以正规就医为准。',
 enA:'Some imagine small ills as grave and fret, or tough them out; stars are tendency, while health relies on formal care.',
 cnLog:['天月主小毛病、缠绵非重症。','命宫小病不断、却无大碍。','规律调养、不忽视不焦虑。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Yue governs minor lingering ills, not serious.','In Life, recurring small ills without great harm.','Care regularly, neither ignore nor fret.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['作息规律、增强体质','小毛病耐心调养','不小题大做、也不硬拖','症状持续或加重就就医','按医生评估处理','以安心+规范为要'],
 enStep:['Keep regular hours, build constitution','Care for minor ills patiently','Do not over-fret or tough out','Seek care if symptoms persist or worsen','Follow doctor assessment','Rest on calm and proper care'],
 cnMis:['把小毛病想成大病、焦虑','不当回事、硬拖','自己乱吃药'],
 enMis:['Imagining minor ills as grave, fretting','Toughing out, ignoring','Self-medicating randomly'],
 cnClose:'天月在命宫，是「小毛病缠绵、但无大碍」的提示。耐心调养、心态放平，真不适应正规就医。',
 enClose:'Tian Yue in the Life Palace suggests minor lingering ills without great harm. Care patiently, stay calm and seek formal care for real discomfort.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-xiongdigong',focus:'天月在兄弟宫',focusEn:'Tian Yue in the Siblings Palace',
 cnT:'天月在兄弟宫：手足同辈易有小摩擦，慢慢磨合不伤本',enT:'Tian Yue in the Siblings Palace: Small Frictions That Heal',
 cnD:'天月在兄弟宫多主与兄弟姐妹、同辈朋友易有小摩擦、小误会，拖一拖、磨一磨，却不伤根本；重在及时说开、多点耐心，别让小事积成疙瘩。',
 enD:'Tian Yue in the Siblings Palace suggests small frictions and misunderstandings with siblings and peers that linger and smooth out without harming the root. Talk it through in time, be patient and do not let small matters pile into grudges.',
 cnL:'同辈相处哪有不磕绊的，小摩擦像鞋里的沙，早点倒出来就好；老留着，路就越走越别扭。',
 enL:'Peers inevitably bump; small friction is sand in a shoe, tipped out early; kept in, the road grows awkward.',
 cnA:'有人对小误会不解释、任其发酵，结果疏远；星曜是倾向，关系靠及时沟通。',
 enA:'Some do not explain small misunderstandings and let them grow, ending distant; stars are tendency, while bonds need timely talk.',
 cnLog:['天月在兄弟宫，同辈易小摩擦。','拖磨但不伤根本。','及时说开、多耐心。','倾向描述，非绝对定论。'],
 enLog:['Tian Yue in Siblings means small peer frictions.','Lingering but not harming the root.','Talk through in time, be patient.','This is tendency, not an absolute verdict.'],
 cnStep:['小摩擦及时沟通','不积攒误会','多点耐心、换位思考','就事论事、不翻旧账','主动示好','以和睦为要'],
 enStep:['Talk through small frictions in time','Do not pile up misunderstandings','Be patient, change places','Stick to the matter, no old scores','Offer goodwill actively','Rest on harmony'],
 cnMis:['小误会不解释、任发酵','翻旧账、记疙瘩','对同辈缺耐心'],
 enMis:['Not explaining, letting misunderstandings grow','Old scores and grudges','Impatient with peers'],
 cnClose:'天月在兄弟宫，小摩擦难免，关键「早说开、不积攒」。耐心磨合，同辈情分才不被小事磨淡。',
 enClose:'Tian Yue in the Siblings Palace makes small frictions normal; talk early and do not pile up. Smooth patiently so peer affection is not worn thin.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-fuqigong',focus:'天月在夫妻宫',focusEn:'Tian Yue in the Spouse Palace',
 cnT:'天月在夫妻宫：感情易有小别扭，拖而不裂靠沟通',enT:'Tian Yue in the Spouse Palace: Small Spats Healed by Talk',
 cnD:'天月在夫妻宫多主两人易有小别扭、小冷战，拖一拖、磨一磨却不致破裂；重在不隔夜、及时哄一哄，别让小情绪反复消耗感情。',
 enD:'Tian Yue in the Spouse Palace suggests small spats and little cold wars that linger without breaking the bond. Do not let them overnight, soothe in time and do not let small moods repeatedly deplete love.',
 cnL:'夫妻没有不拌嘴的，小别扭怕的是憋着；当天的结当天解，床尾和才是真本事。',
 enL:'Couples do bicker, and small spats fear being held; untie the day knot by day, reconciling is the true skill.',
 cnA:'有人小别扭也冷战到底、不肯低头，情分被磨淡；星曜是倾向，关系靠及时修复。',
 enA:'Some fight small spats to a cold war and refuse to yield, wearing love thin; stars are tendency, while bonds need timely repair.',
 cnLog:['天月在夫妻宫，感情易小别扭。','拖磨但不致破裂。','不隔夜、及时修复。','倾向描述，非绝对定论。'],
 enLog:['Tian Yue in Spouse means small spats.','Lingering without breaking.','Do not overnight, repair in time.','This is tendency, not an absolute verdict.'],
 cnStep:['小别扭当天化解','不冷战、肯低头','及时表达关心','少翻旧账','共同经营陪伴','以和好为要'],
 enStep:['Resolve small spats by day','No cold war, willing to yield','Show care in time','Less old scores','Build companionship together','Rest on reconciliation'],
 cnMis:['小别扭也冷战到底','不肯低头、憋着','让小情绪反复消耗'],
 enMis:['Fighting small spats to a cold war','Refusing to yield, holding on','Letting small moods repeatedly deplete'],
 cnClose:'天月在夫妻宫，小别扭难免，贵在「不隔夜、勤修复」。及时哄、肯低头，感情才不被磨淡。',
 enClose:'Tian Yue in the Spouse Palace makes small spats normal; do not overnight and repair often. Soothe in time and yield so love is not worn thin.'},

{cat:'fuzhu',slug:'ziwei-tianyue2-zai-zinvgong',focus:'天月在子女宫',focusEn:'Tian Yue in the Children Palace',
 cnT:'天月在子女宫：子女小毛病小操心，耐心陪伴别焦虑',enT:'Tian Yue in the Children Palace: Small Worries, Patient Presence',
 cnD:'天月在子女宫多主为孩子的小毛小病、小状况操心，事情不大却反复；重在耐心陪伴、科学照护，既不焦虑包办也不大意，健康问题正规就医。',
 enD:'Tian Yue in the Children Palace suggests worry over children small ills and matters, minor but recurring. Be patient and present, care scientifically, neither anxiously controlling nor careless, and seek formal care for health matters.',
 cnL:'孩子是磕磕绊绊长大的，小毛病最磨家长的心；稳住自己、科学应对，比瞎操心有用。',
 enL:'Children grow through bumps and small ills that try parents; steady yourself and respond scientifically, more useful than fretting.',
 cnA:'有人为孩子小事焦虑过度、跑断腿，或粗心大意；星曜是倾向，健康以正规就医为准。',
 enA:'Some over-fret over small matters or are careless; stars are tendency, while health relies on formal care.',
 cnLog:['天月在子女宫，子女小毛病反复。','事不大、却操心。','耐心陪伴、科学照护。','倾向非诊断，以正规就医为准。'],
 enLog:['Tian Yue in Children means recurring small ills.','Minor but worrying.','Be patient, care scientifically.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['孩子小毛病科学照护','不焦虑包办','耐心陪伴、讲方法','该就医时正规就诊','稳住自己的情绪','以安心照护为要'],
 enStep:['Care for small ills scientifically','Do not anxiously control','Be patient, use method','Seek formal care when needed','Steady your own mood','Rest on calm care'],
 cnMis:['为小事焦虑过度','粗心大意、不照护','一有小毛病就乱用药'],
 enMis:['Over-fretting over small matters','Careless, not caring','Random medicine at every small ill'],
 cnClose:'天月在子女宫，孩子小毛病难免，重在「耐心、科学、不焦虑」。该就医就医，陪伴到位，亲子都安心。',
 enClose:'Tian Yue in the Children Palace makes small ills normal; be patient, scientific and not anxious. Seek care when needed and be present so both stay calm.'}
];
