// catchup 2026-09-16 第5组：吊客后2（福德/父母）+ 指背6（疾厄/迁移/仆役/官禄/田宅/福德）
module.exports=[
{cat:'fuzhu',slug:'ziwei-tiaoke-zai-fudegong',focus:'吊客在福德宫',focusEn:'Diao Ke in the Blessings Palace',
 cnT:'吊客在福德宫：心易感忧愁，疏导情绪养精神',enT:'Diao Ke in the Blessings Palace: Easing a Sorrow-Prone Mind',
 cnD:'吊客在福德宫多主心性易感、容易忧愁伤怀；重在及时疏导、不陷进去，培养开朗的精神寄托，必要时寻求专业帮助。',
 enD:'Diao Ke in the Blessings Palace suggests a sensitive, sorrow-prone mind. Channel emotion in time, cultivate uplifting anchors and seek professional help when needed.',
 cnL:'心易感的人更要学会哄自己开心；情绪有出口，精神才不被愁压住。',
 enL:'Sensitive minds learn to lift themselves; give emotion an outlet.',
 cnA:'有人遇事往悲处想、不疏导；星曜是倾向，心安靠调节。',
 enA:'Some think to the sad side without channeling; stars are tendency, while peace needs care.',
 cnLog:['吊客在福德宫，心易感忧愁。','疏导、不陷进去。','养开朗寄托。','倾向描述，非绝对定论。'],
 enLog:['Diao Ke in Blessings means sorrow-prone mind.','Channel, not trapped.','Uplifting anchors.','This is tendency, not an absolute verdict.'],
 cnStep:['情绪及时疏导','培养开朗爱好','少陷悲思','多接触阳光自然','必要时寻求专业帮助','以心安为要'],
 enStep:['Channel emotion','Cultivate uplifting interests','Less sad rumination','Sunlight and nature','Seek professional help when needed','Rest on calm'],
 cnMis:['陷忧愁','不疏导','精神无寄托'],
 enMis:['Trapped in sorrow','Not channeling','No anchor'],
 cnClose:'吊客在福德宫，心易感忧愁。疏导、开朗、有寄托，精神才轻安。',
 enClose:'Diao Ke in the Blessings Palace calls for easing sorrow. Channel and cultivate uplifting anchors.'},

{cat:'fuzhu',slug:'ziwei-tiaoke-zai-fumugong',focus:'吊客在父母宫',focusEn:'Diao Ke in the Parents Palace',
 cnT:'吊客在父母宫：长辈面对丧亡，陪伴尽孝懂告别',enT:'Diao Ke in the Parents Palace: Presence Through Elders Loss',
 cnD:'吊客在父母宫多主父母、长辈会面对丧亡或同辈离去，需你陪伴尽孝；重在生前多尽孝、走时好好送别。',
 enD:'Diao Ke in the Parents Palace suggests elders facing loss and needing your presence. Be filial in life and farewell well.',
 cnL:'尽孝最怕来不及；长辈在时多陪，走时才不留遗憾。',
 enL:'Filial care fears being too late; accompany in life.',
 cnA:'有人生前疏忽、走时才悔恨；星曜是倾向，亲情靠珍惜。',
 enA:'Some neglect in life and regret after; stars are tendency, while kinship needs cherishing.',
 cnLog:['吊客在父母宫，长辈面对丧亡。','生前尽孝、好好送别。','陪伴。','倾向描述，非绝对定论。'],
 enLog:['Diao Ke in Parents means elders facing loss.','Filial in life, farewell well.','Presence.','This is tendency, not an absolute verdict.'],
 cnStep:['长辈在时多尽孝','常陪伴','好好送别','节哀疏导','珍惜亲情','以家和为要'],
 enStep:['Be filial while elders live','Accompany often','Farewell well','Grieve, channel','Value kinship','Rest on harmony'],
 cnMis:['生前疏忽','走时悔恨','不陪伴'],
 enMis:['Neglect in life','Regret after','Not present'],
 cnClose:'吊客在父母宫，长辈面对丧亡。生前尽孝、好好告别，才不留遗憾。',
 enClose:'Diao Ke in the Parents Palace calls for filial care in life and a proper farewell.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-jiegong',focus:'指背在疾厄宫',focusEn:'Zhi Bei in the Health Palace',
 cnT:'指背在疾厄宫：健康上防是非忧心，坦荡少虑',enT:'Zhi Bei in the Health Palace: Calm Over Health Gossip',
 cnD:'指背在疾厄宫多主容易因健康被议论、或为是非忧心伤身；重在行得正、少思虑，身体不适正规就医，不被闲话左右。',
 enD:'Zhi Bei in the Health Palace suggests being talked about over health or fretting into illness. Stay upright and calm, seek formal care and do not let gossip rule.',
 cnL:'为别人的嘴伤自己的身，最不值；坦荡、早就医，是非伤不到你。',
 enL:'Hurting health for others mouths is not worth it; be upright and seek care.',
 cnA:'有人因闲话焦虑伤身；星曜是倾向，健康以正规就医为准。',
 enA:'Some fret into illness over gossip; stars are tendency, while health relies on formal care.',
 cnLog:['指背在疾厄宫，健康防是非忧心。','坦荡少虑。','不适正规就医。','倾向非诊断，以正规就医为准。'],
 enLog:['Zhi Bei in Health means health gossip.','Upright, calm.','Formal care.','This is tendency not diagnosis; rely on formal medical care.'],
 cnStep:['不被是非左右','坦荡少思虑','不适及时就诊','规律生活','情绪疏导','以健康为要'],
 enStep:['Do not let gossip rule','Upright, calm','Seek timely care','Live regularly','Channel emotion','Rest on health'],
 cnMis:['为是非伤身','焦虑不就医','被闲话左右'],
 enMis:['Fretting into illness','Anxious, not seeking care','Ruled by gossip'],
 cnClose:'指背在疾厄宫，别为是非伤身体。坦荡、早就医、少思虑，健康才稳。',
 enClose:'Zhi Bei in the Health Palace calls for calm over health gossip. Be upright and seek care.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-qianyi',focus:'指背在迁移宫',focusEn:'Zhi Bei in the Travel Palace',
 cnT:'指背在迁移宫：外出防口舌是非，少传话、多忍让',enT:'Zhi Bei in the Travel Palace: Avoid Disputes Away',
 cnD:'指背在迁移宫多主在外容易卷入口舌、误会；重在不传话、不议论、遇事忍让，礼貌在外是非少。',
 enD:'Zhi Bei in the Travel Palace suggests being drawn into disputes away. Do not pass gossip, avoid arguing and yield politely.',
 cnL:'出门少一句争、多一句礼，是非就绕着走。',
 enL:'A word less of argument and more of courtesy away.',
 cnA:'有人在外传话、争胜；星曜是倾向，平安靠忍让。',
 enA:'Some pass gossip and compete away; stars are tendency, while safety rests on yielding.',
 cnLog:['指背在迁移宫，外出防口舌。','不传话、忍让。','礼貌。','倾向描述，非绝对定论。'],
 enLog:['Zhi Bei in Travel means disputes away.','No gossip, yield.','Courtesy.','This is tendency, not an absolute verdict.'],
 cnStep:['不传话议论','遇事忍让','礼貌待人','守交规','行程留余','以平安为要'],
 enStep:['No gossip','Yield in trouble','Be polite','Follow rules','Leave margin','Rest on safe travel'],
 cnMis:['传话争胜','不忍让','失礼'],
 enMis:['Passing gossip, competing','Not yielding','Rude'],
 cnClose:'指背在迁移宫，外出防口舌。不传话、肯忍让、有礼貌，路才顺。',
 enClose:'Zhi Bei in the Travel Palace calls for avoiding disputes away. No gossip and yield politely.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-puyigong',focus:'指背在仆役宫',focusEn:'Zhi Bei in the Friends Palace',
 cnT:'指背在仆役宫：朋友间防背后话，坦荡不传话',enT:'Zhi Bei in the Friends Palace: Openness Over Behind-Back Words',
 cnD:'指背在仆役宫多主朋友、部属间易有背后闲话；重在自己不传话、当面沟通，坦荡的朋友圈才清爽。',
 enD:'Zhi Bei in the Friends Palace suggests behind-back words among friends. Do not pass gossip, talk face to face and keep circles open.',
 cnL:'朋友的是非多是传话传的；你不传、当面说，关系就不被搅。',
 enL:'Friend disputes come through passed words; do not pass, talk face to face.',
 cnA:'有人传话、在朋友间挑拨；星曜是倾向，相处靠坦荡。',
 enA:'Some pass gossip and stir; stars are tendency, while relating needs openness.',
 cnLog:['指背在仆役宫，朋友有背后话。','不传话、当面沟通。','坦荡。','倾向描述，非绝对定论。'],
 enLog:['Zhi Bei in Friends means behind-back words.','No gossip, face to face.','Openness.','This is tendency, not an absolute verdict.'],
 cnStep:['不传话','有话当面说','不挑拨','珍惜朋友','守分寸','以长久为要'],
 enStep:['No gossip','Talk face to face','Do not stir','Value friends','Keep measure','Rest on lasting relations'],
 cnMis:['传话挑拨','背后议论','不当面沟通'],
 enMis:['Passing, stirring','Talking behind backs','Not facing matters'],
 cnClose:'指背在仆役宫，朋友间防背后话。不传话、当面说、肯坦荡，相处才久。',
 enClose:'Zhi Bei in the Friends Palace calls for openness over behind-back words. No gossip and talk face to face.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-guanlugong',focus:'指背在官禄宫',focusEn:'Zhi Bei in the Career Palace',
 cnT:'指背在官禄宫：职场防背后议论，光明做事不内耗',enT:'Zhi Bei in the Career Palace: Above Office Gossip',
 cnD:'指背在官禄宫多主职场上容易有背后议论、小报告；重在光明磊落、专业说话，不传话、不内耗，时间证明实力。',
 enD:'Zhi Bei in the Career Palace suggests behind-back talk at work. Stay upright and professional, do not pass gossip or drain yourself, letting time show skill.',
 cnL:'职场的闲话管不住，但行得正、活干好，它伤不到你。',
 enL:'Office gossip cannot be controlled, but upright and excellent work.',
 cnA:'有人为小报告内耗、到处辩；星曜是倾向，立身靠端正。',
 enA:'Some drain and over-defend at hearsay; stars are tendency, while standing rests on uprightness.',
 cnLog:['指背在官禄宫，职场防议论。','光明专业、不传话。','不内耗。','倾向描述，非绝对定论。'],
 enLog:['Zhi Bei in Career means office gossip.','Upright, professional, no hearsay.','Not draining.','This is tendency, not an absolute verdict.'],
 cnStep:['光明做事','专业过硬','不传话、不议论人','不为闲话内耗','专注成果','以坦荡为要'],
 enStep:['Act upright','Be excellent','No gossip','Do not drain on hearsay','Focus on results','Rest on openness'],
 cnMis:['传话、打小报告','为闲话内耗','不专业'],
 enMis:['Passing gossip','Draining on hearsay','Not professional'],
 cnClose:'指背在官禄宫，职场背后话难免。光明、专业、不传话，实力会替你说话。',
 enClose:'Zhi Bei in the Career Palace makes office gossip normal. Stay upright and professional.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-tianzhaigong',focus:'指背在田宅宫',focusEn:'Zhi Bei in the Property Palace',
 cnT:'指背在田宅宫：家宅防邻里是非，少传话、明相处',enT:'Zhi Bei in the Property Palace: Avoid Neighborhood Gossip',
 cnD:'指背在田宅宫多主家里、邻里间易有是非闲话；重在不传话、和睦相处，居家守好边界，邻里和、家才安。',
 enD:'Zhi Bei in the Property Palace suggests disputes among household and neighbors. Do not pass gossip, keep harmony and boundaries.',
 cnL:'邻里相处和为贵，不传话、不掺和，耳根清净家才安。',
 enL:'Harmony with neighbors, no gossip or meddling.',
 cnA:'有人爱传话、掺和邻里事；星曜是倾向，家安靠分寸。',
 enA:'Some pass gossip and meddle; stars are tendency, while peace rests on measure.',
 cnLog:['指背在田宅宫，家宅防邻里是非。','不传话、和睦。','守边界。','倾向描述，非绝对定论。'],
 enLog:['Zhi Bei in Property means neighborhood gossip.','No hearsay, harmony.','Boundaries.','This is tendency, not an absolute verdict.'],
 cnStep:['邻里和睦','不传话、不掺和','守好边界','居家安静','礼貌相处','以家安为要'],
 enStep:['Harmony with neighbors','No gossip or meddling','Keep boundaries','Keep home quiet','Be polite','Rest on a stable home'],
 cnMis:['传话掺和','邻里计较','边界不清'],
 enMis:['Passing, meddling','Reckoning with neighbors','Unclear boundaries'],
 cnClose:'指背在田宅宫，家宅防邻里是非。不传话、和睦、守边界，家才安。',
 enClose:'Zhi Bei in the Property Palace calls for avoiding neighborhood gossip. No hearsay and keep boundaries.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-fudegong',focus:'指背在福德宫',focusEn:'Zhi Bei in the Blessings Palace',
 cnT:'指背在福德宫：心不被是非扰，坦荡自安少内耗',enT:'Zhi Bei in the Blessings Palace: A Mind Above Gossip',
 cnD:'指背在福德宫多主精神上容易被是非、闲话烦扰；重在心里有定力、不内耗，坦荡的人睡得最安。',
 enD:'Zhi Bei in the Blessings Palace suggests a mind easily bothered by gossip. Build steadiness and do not drain yourself, for the upright sleep best.',
 cnL:'别人的嘴你管不住，自己的心要守得住；不内耗，是非就落不了地。',
 enL:'You cannot control mouths but guard your mind; do not drain yourself.',
 cnA:'有人为闲话反复琢磨、内耗；星曜是倾向，心安靠定力。',
 enA:'Some ruminate and drain on gossip; stars are tendency, while peace rests on steadiness.',
 cnLog:['指背在福德宫，心防是非扰。','有定力、不内耗。','坦荡自安。','倾向描述，非绝对定论。'],
 enLog:['Zhi Bei in Blessings means gossip bothering mind.','Steady, not draining.','Upright, calm.','This is tendency, not an absolute verdict.'],
 cnStep:['心里守定力','不为是非内耗','专注做好自己','练习放下','必要时寻求专业帮助','以心安为要'],
 enStep:['Guard steadiness','Do not drain on gossip','Focus on yourself','Let go','Seek professional help when needed','Rest on calm'],
 cnMis:['为是非内耗','反复琢磨','心无定力'],
 enMis:['Draining on gossip','Ruminating','No steadiness'],
 cnClose:'指背在福德宫，心不被是非扰。有定力、不内耗、肯坦荡，精神才安。',
 enClose:'Zhi Bei in the Blessings Palace calls for a mind above gossip. Stay steady and do not drain yourself.'}
];
