const {PORDER,generate}=require('./_engine');
const STARS={
  tiangui:{cn:'天贵',en:'Tian Gui',elem:'阳火',elemEn:'yang fire',nature:'贵气星、名望星、守信星',natureEn:'the nobility, prestige, and trustworthiness star',
    cnT:['天生带贵气、受人尊重','守信用、重承诺','有名望和影响力','容易端着、放不下面子','天贵的诚信和威望是正面'],
    enT:['natural nobility, earns respect','trustworthy, honors commitments','has prestige and influence','prone to standing on dignity','Tian Gui integrity and prestige are positive'],
    th:{qianyi:['在外受人尊重，离乡靠信誉立足','Respected Outside; Establish Through Credibility'],puyigong:['朋友中多有威望之人，社交讲信用','Prestigious Friends; Trust-Based Circle'],guanlugong:['事业靠信誉立身，适合管理和公职','Career Through Credibility; Suited to Management'],tianzhaigong:['家产带贵气，居住环境有档次','Prestigious Assets; Upscale Living Environment'],fudegong:['精神自重自爱，福气来自德行声望','Self-Respecting Mind; Blessings from Virtue'],fumugong:['父母有威望受人尊重，长辈家风正','Prestigious Respected Parents; Upright Family Tradition']}},
  yinsha:{cn:'阴煞',en:'Yin Sha',elem:'阴火',elemEn:'yin fire',nature:'暗损星、小人星、多疑星',natureEn:'the hidden-harm, petty-person, and suspicion star',
    cnT:['容易遭暗中小人是非','性格敏感多疑、直觉强','背后阻力多、事情易生暗变','容易疑神疑鬼影响心情','阴煞的敏锐直觉和风险意识是正面'],
    enT:['prone to hidden petty-person trouble','sensitive and suspicious, strong intuition','behind-the-scenes resistance, hidden changes','prone to suspicion that affects mood','Yin Sha sharp intuition and risk awareness are positive'],
    th:{minggong:['直觉敏锐但多疑，天生防人之心重','Sharp Intuition but Suspicious; Naturally Guarded'],xiongdigong:['兄弟姐妹中有人小心眼，同辈防暗中计较','A Petty Sibling; Beware Hidden Peer Calculation'],fuqigong:['感情里容易猜忌，伴侣关系要建立信任','Prone to Jealousy; Build Trust in the Bond'],zinvgong:['子女偏敏感多疑，教育要给安全感','Sensitive Suspicious Children; Give Security'],caibogong:['钱财防暗中损耗和小人劫财，账目要清','Beware Hidden Loss; Keep Clear Accounts'],jiegong:['注意隐性疾病和心理焦虑，定期排查','Watch Hidden Illness and Anxiety; Get Checkups'],qianyi:['在外防小人和暗算，离乡行事要低调','Beware Hidden Foes Outside; Keep a Low Profile Away'],puyigong:['朋友中防损友小人，合伙要防背地动作','Beware Toxic Friends; Guard Against Hidden Moves'],guanlugong:['职场防暗中使绊，成绩要留证据','Beware Workplace Sabotage; Document Achievements'],tianzhaigong:['家里防暗漏隐患，房产交易防猫腻','Beware Hidden Defects; Guard Property Deals'],fudegong:['精神容易焦虑多疑，福气来自放宽心','Anxious Suspicious Mind; Blessings from Letting Go'],fumugong:['长辈中有人多心，家庭关系防暗中误会','A Suspicious Elder; Prevent Hidden Misunderstanding']}},
  posui:{cn:'破碎',en:'Po Sui',elem:'阴火',elemEn:'yin fire',nature:'耗碎星、变动星、破坏星',natureEn:'the fragmentation, change, and disruption star',
    cnT:['事情容易零散破碎、难一气呵成','性格不拘小节、不喜被束缚','钱财和计划易有小破耗','变动多、坐不住','破碎的灵活和破旧立新是正面'],
    enT:['matters fragment easily, hard to finish in one go','unconventional, dislikes being constrained','money and plans prone to small losses','many changes, restless','Po Sui flexibility and renewal are positive'],
    th:{minggong:['思维跳脱不拘小节，做事要防虎头蛇尾','Unconventional Mind; Avoid Starting Strong Finishing Weak'],xiongdigong:['兄弟姐妹聚少离多，同辈关系易散','Siblings Often Apart; Peer Bonds Easily Scatter'],fuqigong:['感情防聚少离多和小摩擦，需要经营','Beware Separation and Friction; Nurture the Bond'],zinvgong:['子女缘分有波动，教育要重陪伴','Fluctuating Children Luck; Prioritize Companionship'],caibogong:['钱财防零碎破耗，记账和预算很重要','Beware Fragmented Spending; Budget Carefully'],jiegong:['注意磕碰外伤和牙齿骨骼，运动要防护','Watch Bumps, Teeth, and Bones; Protect During Exercise'],qianyi:['在外多奔波变动，离乡防计划被打乱','Restless Travels; Prevent Plans Being Disrupted Away'],puyigong:['朋友聚散无常，合伙关系不稳定','Friends Come and Go; Unstable Partnerships'],guanlugong:['事业多变动调整，适合灵活创新的岗位','Many Career Changes; Suited to Flexible Roles'],tianzhaigong:['家里东西易耗损，搬家装修变动多','Household Items Wear; Frequent Moves and Renovation'],fudegong:['心思难安定，福气来自专注和坚持','Restless Mind; Blessings from Focus and Persistence'],fumugong:['父母缘分有聚散，长辈关系多走动','Parent Bond Has Partings; Stay in Touch with Elders']}},
  jiesha:{cn:'劫煞',en:'Jie Sha',elem:'阳火',elemEn:'yang fire',nature:'劫夺星、竞争星、突发星',natureEn:'the seizure, competition, and sudden-event star',
    cnT:['竞争激烈、容易被争夺抢夺','性格果断、反应快、有冲劲','钱财和机会防被人劫走','突发状况多、来得猛','劫煞的决断力和竞争力是正面'],
    enT:['fierce competition, prone to things being taken','decisive, quick-reacting, driven','money and opportunities risk being seized','many sudden, forceful events','Jie Sha decisiveness and competitiveness are positive'],
    th:{minggong:['果断有冲劲竞争力强，天生适合拼搏','Decisive and Driven; Born to Compete'],xiongdigong:['兄弟姐妹间有竞争，同辈资源要防争抢','Sibling Competition; Guard Peer Resource Disputes'],fuqigong:['感情防第三者争夺，伴侣关系要稳固','Beware Rivals in Love; Keep the Bond Strong'],zinvgong:['子女好胜心强，教育引导良性竞争','Competitive Children; Guide Healthy Rivalry'],caibogong:['钱财防被劫被骗，投资防冲动和争夺','Beware Loss and Fraud; Avoid Impulsive Investment'],jiegong:['注意急性外伤和手术，防突发急症','Watch Acute Injuries; Guard Sudden Emergencies'],qianyi:['在外竞争激烈，离乡防被抢机会','Fierce Competition Outside; Guard Stolen Chances Away'],puyigong:['朋友间有利益争夺，合伙先讲清分配','Interest Rivalry Among Friends; Clarify Profit Sharing'],guanlugong:['职场竞争激烈，靠实力抢下位置','Intense Workplace Competition; Win Through Strength'],tianzhaigong:['房产防产权纠纷和争夺，合同要严谨','Beware Property Disputes; Use Rigorous Contracts']}}
};
const BATCHES=[{date:'2026-09-03T10:00:00+08:00',label:'2026-09-03 10:00',rfc:'Thu, 03 Sep 2026 10:00:00 +0800',
  combos:[['tiangui',['qianyi','puyigong','guanlugong','tianzhaigong','fudegong','fumugong']],
          ['yinsha',PORDER.slice()],['posui',PORDER.slice()],['jiesha',PORDER.slice(0,10)]]}];
generate(STARS,BATCHES,'_manifest_0903.json');
