const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'liuqin',slug:'ziwei-jie-gong-kan-jiankang-tizhi-boruo-buwei',focus:'疾厄宫健康',focusEn:'the Health Palace and constitution',
 cnT:'紫微斗数疾厄宫看健康：体质倾向和薄弱部位怎么读',enT:'The Health Palace in Zi Wei Dou Shu: Reading Constitution and Vulnerable Systems',
 cnD:'疾厄宫主先天体质、易薄弱的身体系统与生病模式，主星五行对应不同系统、煞忌聚则提示风险偏高；它给的是需要长期留意的倾向，不是诊断，更不能替代体检和就医。',
 enD:'The Health Palace governs innate constitution, vulnerable body systems and illness patterns; star elements map to systems, and clustered malefics/Ji flag higher risk. It gives tendencies to watch long-term, not a diagnosis, and never replaces checkups or medical care.',
 cnL:'疾厄宫回答「你的身体哪里更容易先报警」，读懂它是为了提前养护、规律体检，而不是对着盘给自己下诊断书。',
 enL:'Health answers where your body is first likely to send an alarm; read it for prevention and regular checkups, not to write yourself a diagnosis.',
 cnA:'有人看疾厄宫见煞就吓自己、到处对号入座，也有人完全不看、把身体的长期信号忽略，两种极端都误读了疾厄宫的本意。',
 enA:'Some panic at a malefic and self-diagnose everywhere; others ignore the palace and miss long-term signals—both extremes misread its purpose.',
 cnLog:['疾厄宫主一生体质与健康倾向，兼看情绪压力在身体上的落点，须与命宫同看。','主星五行提示相对薄弱的系统：如属火土注意消化代谢、属水注意泌尿肾与循环、属金注意呼吸筋骨（仅为传统倾向，非医学结论）。','煞忌（尤其擎羊、化忌）聚于疾厄，提示该系统更需主动养护、定期筛查，而不是注定生病。','大限流年疾厄宫被引动，是提醒该阶段加强作息、体检与压力管理，出现症状应及时就医，不以盘断病。'],
 enLog:['Health governs lifelong constitution and tendency, plus where emotional stress lands in the body, read with Life.','Star elements hint at relatively vulnerable systems (a traditional tendency, not a medical conclusion).','Clustered malefics/Ji (especially Yang, Hua Ji) mean that system needs proactive care and screening, not destined illness.','An activated decade/year Health Palace is a reminder to improve routine, checkups and stress management then; with symptoms, seek care rather than diagnosing from the chart.'],
 cnStep:['先看疾厄宫主星与五行，了解体质的整体倾向','对照命宫，看性格压力如何反映到身体','找煞忌聚集，标出需要长期留意、定期筛查的系统','看大限流年疾厄何时被引动，提前安排体检和作息调整','把命盘提示转成健康行动：运动、饮食、筛查、减压','任何具体不适都以专业医生诊断为准，命盘只做养护提醒'],
 enStep:['Read the Health major star and element for overall constitutional tendency','Compare Life to see how personality stress reflects in the body','Find clustered malefics/Ji to mark systems needing long-term watch and screening','See when decade/year Health activates and schedule checkups and routine changes early','Turn chart hints into health actions: exercise, diet, screening, stress relief','Let professional doctors diagnose any concrete discomfort; the chart only reminds you to care for yourself'],
 cnMis:['拿疾厄宫给自己下诊断、制造恐慌','见煞就认定要生大病，忽略后天养护和筛查','完全不看疾厄，错过提前调理的提醒'],
 enMis:['Self-diagnosing from the Health Palace and creating panic','Taking a malefic as destined serious illness, ignoring care and screening','Ignoring Health entirely and missing early prevention reminders'],
 cnClose:'疾厄宫是一份「身体使用说明」，不是判决书。它提醒你哪里要多照顾，真正的健康仍靠规律作息、定期体检和及时就医来守住。',
 enClose:'The Health Palace is a body user manual, not a verdict. It reminds you where to take extra care; real health is kept by routine, screening and timely medical care.'},

{cat:'liuqin',slug:'ziwei-fumu-gong-buzhi-fumu-haiyou-zhangbei-wenshu-biyin',focus:'父母宫',focusEn:'the Parents Palace beyond parents',
 cnT:'紫微斗数父母宫：不只是父母，还藏着长辈、文书和你的庇荫',enT:'The Parents Palace in Zi Wei Dou Shu: Beyond Parents—Seniors, Documents and Protection',
 cnD:'父母宫（相貌宫）主与父母长辈的缘分、得长辈庇荫的程度，也兼看学历文书、遗传相貌与和上级的关系；主星吉化则易得长辈与制度助力，逢煞忌则亲缘或文书上多磨合。',
 enD:'The Parents Palace (also appearance palace) governs bonds with parents and elders, the degree of elder protection, and also academic credentials, documents, inherited looks and relations with superiors. Auspicious transformations bring elder and institutional support; malefics/Ji mean more friction in kinship or paperwork.',
 cnL:'父母宫回答「你从上方（父母、长辈、师长、上级、制度）得到多少托举」，它是一个人早年资源和向上通道的重要参考。',
 enL:'Parents answers how much lift you receive from above—parents, elders, mentors, bosses, institutions—a key reference for early resources and upward channels.',
 cnA:'有人把父母宫窄化成「和父母关系好不好」，结果没看到它同时管学历文书、上级关系和长辈贵人，漏掉了一半信息。',
 enA:'Narrowing it to getting-along-with-parents misses that it also governs credentials, documents and boss relations—half the information.',
 cnLog:['父母宫主父母缘分、教养方式与早年庇荫，也看长辈、师长这一类「在上位者」对你的态度。','它兼看文书宫：学历、证书、契约、审批、官方文件，化科利功名考试，化忌易在文书审批上卡壳。','它又称相貌宫，兼看遗传相貌与外在给人的第一观感。','职场中父母宫也对应直属上级，与官禄宫合看，可知你更易被上司提携还是需要磨合。'],
 enLog:['Parents governs parental bonds, upbringing and early protection, plus how elders and mentors—those above you—treat you.','It doubles as the documents palace: degrees, certificates, contracts, approvals and official papers; Hua Ke aids exams, Hua Ji stalls paperwork.','Also called the appearance palace, it covers inherited looks and first impressions.','At work it corresponds to the direct supervisor; read with Career to see whether bosses lift you or require磨合.'],
 cnStep:['先看父母宫主星与四化，判断与父母长辈的缘分基调','找化科化禄，定位长辈庇荫、学历文书的助力','逢煞忌：预判与父母或上级的磨合点，主动沟通化解','把父母宫当文书宫，重要签约审批前多看流程、留备份','合参官禄宫，判断职场上与直属上级的相处模式','大限父母宫引动时，常见搬家、置业、长辈事或文书审批变化'],
 enStep:['Read the Parents major star and transformations for the bond tone with parents and elders','Find Hua Ke/Lu to locate elder protection and credentials/paperwork support','With malefics/Ji, anticipate friction with parents or bosses and communicate proactively','Use it as the documents palace: double-check process and keep backups before signings and approvals','Combine Career to read the relationship with your direct supervisor at work','When the decade Parents activates, expect moves, property, elder matters or paperwork changes'],
 cnMis:['把父母宫只看成亲子关系，漏掉文书和上级','父母宫逢煞就断言父母不好，忽略后天相处','重要审批签约不看文书线，反复卡流程'],
 enMis:['Seeing only parent relations, missing documents and bosses','Declaring bad parents from malefics, ignoring后天 relating','Ignoring the document line in approvals and signings, stuck in process'],
 cnClose:'父母宫是你和「上方资源」的接口：父母、长辈、师长、上级、制度文书都在这。读懂它，你会更清楚自己的托举从哪来、短板又该怎么补。',
 enClose:'Parents is your interface with resources above: parents, elders, mentors, bosses and institutional documents. Read it and you see where your lift comes from and how to fill the gaps.'},

{cat:'liuqin',slug:'ziwei-zinv-gong-zinv-yuanfen-chuangzaoli-xiashu',focus:'子女宫',focusEn:'the Children Palace',
 cnT:'紫微斗数子女宫：子女缘分之外，还管创造力、学生和下属',enT:'The Children Palace in Zi Wei Dou Shu: Beyond Offspring—Creativity, Students and Subordinates',
 cnD:'子女宫主与子女的缘分和相处，也延伸看一个人的创造力、作品产出、学生晚辈与下属关系，以及部分桃花与合伙；主星吉化则晚辈得力、创作丰沛，逢煞忌则在这些「我所生、我所带」的事上多操心。',
 enD:'The Children Palace governs bonds with children and by extension creativity, output and works, students/juniors and subordinates, plus some romance and partnership. Auspicious transformations mean capable juniors and rich creativity; malefics/Ji mean more worry over what you create or lead.',
 cnL:'子女宫的广义内核是「我生出来的东西」：孩子、作品、创意、带的人，读懂它就知道你在创造和带人上是顺还是耗。',
 enL:'Its broad core is what you give birth to: children, works, ideas and people you lead; read it to know whether creating and leading flow or drain you.',
 cnA:'没孩子或不打算要孩子的人常以为子女宫与己无关，其实它同时管创作产出和下属晚辈，是事业与自我表达的重要一宫。',
 enA:'People without children assume this palace is irrelevant, yet it governs creative output and juniors—a key palace for career and self-expression.',
 cnLog:['本义看子女缘分、数量倾向、子女性格与亲子关系，现代更重相处质量而非数量。','广义看创造力与作品：写作、设计、研发、内容等「从无到有产出」的能力。','人际上看学生、徒弟、下属等「我带的晚辈」，与奴仆宫（朋友平辈同事）分工不同。','它也是桃花、合作与外出消费的参考宫之一，须与夫妻、福德、财帛合参。'],
 enLog:['Its core meaning is offspring bonds, number tendency, children\'s character and parent-child relations; modern reading favors quality over number.','Broadly it covers creativity and works—writing, design, R&D, content—the ability to produce something from nothing.','In relations it covers students, apprentices and subordinates you lead, distinct from the Friends palace of peers and colleagues.','It also informs romance, partnership and outward spending, read with Spouse, Happiness and Wealth.'],
 cnStep:['先看子女宫主星与四化，定「产出与带人」的整体基调','有子女：读亲子相处模式与需要注意的缘分课题','无子女：把它当创造力宫，看作品产出和创意表达顺不顺','职场上用它看下属、学生、晚辈是否得力、好不好带','逢煞忌：预判创作瓶颈或带人操心，提前调整方式','大限子女宫引动时，常见添丁、作品发布、团队扩充或合作变化'],
 enStep:['Read the Children major star and transformations for the overall produce-and-lead tone','With children: read the relating mode and bond lessons','Without: treat it as creativity, checking whether output and expression flow','At work use it for whether subordinates, students and juniors are capable and easy to lead','With malefics/Ji, anticipate creative blocks or leadership worry and adjust early','When the decade Children activates, expect a child, a launch, team growth or partnership change'],
 cnMis:['以为没孩子子女宫就没用','把下属朋友混看，忽略子女宫专管晚辈','只看子女性别数量，忽略创造力这层现代含义'],
 enMis:['Assuming the palace is useless without children','Blending subordinates and friends, missing that it covers juniors','Only reading children\'s gender/number, ignoring the modern creativity layer'],
 cnClose:'子女宫看的是「你能创造并带大什么」——无论是孩子、作品还是团队。跳出字面，你会发现它讲的正是一个人把想法变成成果的能力。',
 enClose:'Children is about what you can create and raise—children, works or teams. Beyond the literal, it describes your ability to turn ideas into results.'},

{cat:'faq',slug:'ziwei-tong-shengxiao-tong-bazi-weishime-mingyun-butong',focus:'同生肖同八字差异',focusEn:'why same-sign people differ',
 cnT:'紫微斗数为什么同生肖甚至同八字的人命运也不同',enT:'Why People With the Same Zodiac Sign—or Even Similar Birth Data—Differ in Zi Wei Dou Shu',
 cnD:'生肖只看生年一个维度，紫微盘却要年月日时、性别与地点共同排定；即便四柱相近，紫微命盘的宫位星曜组合、大限节奏和个人选择也不同，命盘给的是倾向区间，不是唯一剧本。',
 enD:'The zodiac uses only birth year, while a Zi Wei chart needs year, month, day, hour, gender and location. Even with similar pillars, palace-star combinations, decade timing and personal choices differ; a chart gives a range of tendencies, not a single script.',
 cnL:'命理描述的是概率分布和倾向，不是定数：同一张盘落在不同环境、做了不同选择，活出来的结果可以差很远。',
 enL:'Astrology describes probability and tendency, not fixed fate: the same chart in different environments with different choices is lived very differently.',
 cnA:'有人用「我们同生肖为什么命差这么多」质疑命理，其实是把粗粒度的生肖标签，错当成了精细的个体命盘，也忽略了选择和环境的作用。',
 enA:'People challenge astrology with same-zodiac-different-lives, mistaking a coarse label for a fine individual chart and ignoring choice and environment.',
 cnLog:['生肖只取生年地支一个信息，全国十二分之一的人同生肖，颗粒度极粗，只能看大类倾向。','紫微盘由农历年月日时加性别排定，时柱一差十二宫全变，同卵双胞胎也会因出生时刻和大限顺逆不同而有别。','命盘给的是星曜组合的倾向区间（性格、擅长、风险、运限节奏），不是确定事件。','最终结果由倾向 × 环境 × 选择共同决定：盘指出顺风逆风，怎么走仍在人，这也是「造命」的空间。'],
 enLog:['The zodiac takes only the birth-year branch; a twelfth of the population shares it—very coarse, only broad tendencies.','A Zi Wei chart needs lunar year/month/day/hour plus gender; a one-hour difference shifts all twelve palaces, and even twins differ by birth moment and decade direction.','The chart gives tendency ranges (personality, strengths, risks, cycle rhythm), not fixed events.','The outcome is tendency × environment × choice: the chart shows tailwind or headwind, but the walking remains yours—the space for making your own fate.'],
 cnStep:['先区分生肖、八字、紫微是三种不同颗粒度的工具','看紫微要凑齐年月日时和性别，时辰不准先定盘','理解命盘给的是倾向区间而非确定结果','在倾向之上叠加家庭、地域、时代等环境变量','把大限流年当「天气」，顺势选择行动节奏','同盘不同命恰恰说明：读懂倾向是为了更好地做选择'],
 enStep:['Distinguish zodiac, BaZi and Zi Wei as three tools at different granularity','Zi Wei needs full year/month/day/hour and gender; fix the chart if the hour is uncertain','Understand the chart gives tendency ranges, not fixed outcomes','Layer environment variables—family, region, era—over the tendencies','Treat decade/year as weather and choose your pace accordingly','Same chart, different life shows precisely why reading tendencies serves better choices'],
 cnMis:['拿生肖标签当精细命盘','以为命盘定死一切，忽略环境与选择','时辰没定准就强行排盘，结论自然漂移'],
 enMis:['Taking zodiac labels as fine-grained charts','Believing the chart fixes everything, ignoring environment and choice','Forcing a chart with an uncertain birth hour, drifting in conclusions'],
 cnClose:'同生肖不同命不是命理失效，而是尺度问题：越精细的盘越能看清倾向，而倾向之上，环境和你每一次的选择，才真正写出了人生。',
 enClose:'Same sign, different life is not astrology failing but a matter of scale: the finer the chart, the clearer the tendencies—and above them, environment and your own choices write the actual life.'},
];
