const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'zhuxing',slug:'ziwei-taiyang-zuoming-faguang-fare-ye-yao-fang-haojin',focus:'太阳坐命',focusEn:'Tai Yang in the Life Palace',
 cnT:'紫微斗数太阳坐命：发光发热的人，也要防被耗尽',enT:'Tai Yang in the Life Palace: The One Who Shines Must Also Avoid Burning Out',
 cnD:'太阳主博爱、付出、名声与公开舞台，庙旺时热心有担当、利公职与对外事业，落陷（如日落西山）则辛劳多、付出不被看见，关键是学会让光照回自己、设好边界。',
 enD:'Tai Yang governs generosity, giving, reputation and the public stage. Bright, it is warm and responsible, favoring public service and outward careers; dimmed (a setting sun), it toils unseen. The key is letting light return to yourself and setting boundaries.',
 cnL:'太阳坐命的人生课题是「付出与回收的平衡」：天生想照亮别人，但只有先照顾好自己，光才持久。',
 enL:'The life lesson of Tai Yang is balancing giving and return: born to illuminate others, your light lasts only if you tend to yourself first.',
 cnA:'很多太阳坐命的人成了团队里最累的老好人，功劳给别人、辛苦自己扛，就是没意识到太阳也分昼夜庙陷、也需要被补。',
 enA:'Many Tai Yang people become the team\'s exhausted giver, credit to others and burden to themselves, not realizing the sun has dawn/dusk brightness and needs replenishing too.',
 cnLog:['太阳为中天主星、属火，主光明、博爱、名声与父亲丈夫等男性缘分，能量向外。','庙旺（如午宫日照中天）主热心、有领导力、利公职教育传播等能见度高的领域。','落陷（如戌亥日落）主劳心劳力、付出与回报不成比例，更要靠吉星与大限补。','太阳最怕只付出不回收，化禄化权化科各补一种资源，逢煞则易急躁、好面子、硬撑。'],
 enLog:['Tai Yang is a central major star of fire, governing light, generosity, reputation and male bonds (father, husband), energy directed outward.','Bright (as at noon) it is warm and leadership-oriented, favoring public service, education and high-visibility fields.','Dimmed (a setting sun) it toils with return out of proportion to effort, relying more on auspicious stars and decades.','It most fears giving without return; Lu/Quan/Ke each replenish a resource, while malefics bring impatience, face-saving and over-endurance.'],
 cnStep:['先看太阳所在宫位庙旺落陷，判断光够不够亮','庙旺：大胆走公开、领导、服务型路线，发挥号召力','落陷：降低「必须被所有人看见」的执念，重质不重量','命宫三方找禄权科与吉星，补资源、补舞台、补名声回报','逢煞设边界，学会拒绝，避免无限付出被耗尽','大限走到日照方向（引动禄权）时争取上位和曝光'],
 enStep:['First read the palace and brightness to judge how strong the light is','Bright: boldly take public, leadership and service routes, using your号召力','Dimmed: lower the need to be seen by everyone; favor quality over quantity','Find Lu/Quan/Ke and auspicious stars in the trine to replenish resources, stage and recognition','With malefics, set boundaries and learn to refuse, avoiding endless giving and burnout','In decades that activate Lu/Quan, pursue promotion and exposure'],
 cnMis:['以为太阳坐命一定风光，不看庙陷','只会付出不会设边界，把自己耗尽','落陷还硬追高曝光，越追越累'],
 enMis:['Assuming Tai Yang always shines, ignoring brightness','Giving without boundaries until burned out','Dimmed yet chasing high visibility, growing more exhausted'],
 cnClose:'太阳坐命的你，天生是来照亮什么的。但请记得，点灯的人也要留灯给自己——边界和回报，是让你的光长明的前提。',
 enClose:'Born a Tai Yang, you are here to illuminate something. Remember the lamplighter must keep a lamp for themselves: boundaries and return are what keep your light burning.'},

{cat:'zhuxing',slug:'ziwei-taiyin-zuoming-wenrou-xixi-yu-qingxu-neihao',focus:'太阴坐命',focusEn:'Tai Yin in the Life Palace',
 cnT:'紫微斗数太阴坐命：温柔细腻是天赋，情绪内耗是功课',enT:'Tai Yin in the Life Palace: Gentleness Is a Gift, Emotional Overthinking Is the Lesson',
 cnD:'太阴主月亮、阴柔、细腻、财库与内在感受，庙旺时温柔有韧性、善理财顾家，落陷则多思敏感、易情绪内耗，关键是给细腻找出口、把感受转化成作品和安全感。',
 enD:'Tai Yin is the moon—soft, meticulous, the treasury and inner feeling. Bright, it is gentle yet resilient, good with money and home; dimmed, it overthinks and drains emotionally. The key is giving sensitivity an outlet and turning feeling into craft and security.',
 cnL:'太阴坐命的人感受力极强，用得好是审美、体贴和聚财能力，用不好就变成反复琢磨、自我怀疑的内耗。',
 enL:'Tai Yin people feel deeply; well used that is aesthetics, care and wealth-gathering, misused it becomes brooding and self-doubt.',
 cnA:'很多太阴坐命的人被一句「你就是想太多」否定，其实问题不是敏感，而是没给这份敏感一个稳定、能产出价值的出口。',
 enA:'Many Tai Yin people are dismissed as overthinking; the problem is not sensitivity but the lack of a stable, value-producing outlet for it.',
 cnLog:['太阴为中天主星、属水，主月亮、母性、田宅财库、审美与内在情绪，能量向内。','庙旺（如酉戌亥月夜）主温柔坚韧、顾家聚财、审美与直觉强，利财务、设计、照护类工作。','落陷（如月失辉）主敏感多虑、安全感不足，逢煞忌更易情绪起伏、失眠内耗。','太阴与太阳相对，一内一外；太阴最需要稳定的环境和可积累的资产来安放内心。'],
 enLog:['Tai Yin is a central major star of water—the moon, mothering, the home treasury, aesthetics and inner emotion, energy directed inward.','Bright (a moonlit night) it is gentle yet resilient, home-oriented and good at gathering wealth, with strong taste and intuition, suiting finance, design and care work.','Dimmed it is sensitive and insecure; with malefics/Ji it swings emotionally, loses sleep and drains.','Opposite Tai Yang, one inner one outer; Tai Yin most needs a stable environment and accumulable assets to settle the heart.'],
 cnStep:['先看太阴道庙旺落陷，判断内在安全感的底子','庙旺：发挥细腻与理财天赋，走专业、审美、照护路线','落陷：先稳环境和作息，减少让自己不安的刺激','给敏感找固定出口：写作、艺术、记账、整理，把感受变作品','用田宅财帛的规划建立安全感，避免情绪性消费','大限引动禄科时，把积累的细腻产出成可见成果'],
 enStep:['Read Tai Yin brightness for the inner-security baseline','Bright: use meticulousness and money sense on professional, aesthetic or care routes','Dimmed: first stabilize environment and routine, cutting anxiety triggers','Give sensitivity a fixed outlet—writing, art, bookkeeping, organizing—turning feeling into work','Build security through Property/Wealth planning, avoiding emotional spending','When the decade activates Lu/Ke, turn accumulated sensitivity into visible results'],
 cnMis:['把细腻当缺点硬改，越改越拧巴','只在情绪里打转，不给感受找产出出口','忽略环境稳定对太阴的决定性作用'],
 enMis:['Forcing sensitivity away as a flaw, growing more twisted','Circling in emotion with no productive outlet','Ignoring how decisive a stable environment is for Tai Yin'],
 cnClose:'太阴坐命的你，拥有别人没有的感受力。别再为敏感抱歉，把它安放进稳定的生活和具体的作品里，温柔也可以很有力量。',
 enClose:'As Tai Yin you hold a rare depth of feeling. Stop apologizing for sensitivity; settle it into a stable life and concrete craft, and gentleness becomes real strength.'},

{cat:'zhuxing',slug:'ziwei-wuqu-zuoming-caixing-shigan-yu-gangying',focus:'武曲坐命',focusEn:'Wu Qu in the Life Palace',
 cnT:'紫微斗数武曲坐命：财星的实干能力和刚硬短板',enT:'Wu Qu in the Life Palace: The Wealth Star\'s Grit and Its Hard Edge',
 cnD:'武曲为正财星、属阴金，主实干、执行力、理财与决断，庙旺化禄权时是能把事做成、把钱管住的将才，短板是刚硬寡言、逢煞易孤克，关键是把硬度用在事上、把柔软留给关系。',
 enD:'Wu Qu is the true wealth star of yin metal—execution, money sense and decisiveness. Bright with Lu/Quan it is a general who gets things done and manages money; its weak edge is hardness and isolation under malefics. Use toughness on tasks, softness on relationships.',
 cnL:'武曲坐命的人靠专业和结果立身，最忌把对事的刚直原样搬到人际里，那样事做成了、人却走远了。',
 enL:'Wu Qu people stand on craft and results; the trap is carrying task-hardness into relationships—work done, people gone.',
 cnA:'很多武曲坐命的人能力极强却总被说难相处、说话伤人，问题不在能力，而在没把「对事硬」和「对人软」分开。',
 enA:'Highly capable Wu Qu people are called difficult or harsh; the issue is not ability but failing to separate hard-on-tasks from soft-on-people.',
 cnLog:['武曲为北斗财星、属阴金，主财帛、行动力、纪律与专业技术，是把目标落地的星。','庙旺或化禄化权：执行力强、善理财、能扛事，利金融、技术、工程、管理等结果导向领域。','武曲性刚直寡言，逢擎羊陀罗火铃会强化硬、急、孤，关系上易有摩擦或晚婚倾向。','会文昌文曲可调和刚烈、增加表达，但也可能因此犹豫，需在果断与沟通间找平衡。'],
 enLog:['Wu Qu is the northern wealth star of yin metal, governing money, action, discipline and technical craft—the star that lands goals.','Bright or with Lu/Quan: strong execution, good money sense and dependable under load, suiting finance, tech, engineering and management.','It is blunt and reserved; Yang/Tuo/Huo/Ling amplify hardness, haste and isolation, bringing relationship friction or late marriage.','Meeting Wenchang/Wenqu softens the edge and adds expression, though it may bring hesitation—balance decisiveness with communication.'],
 cnStep:['先看武曲庙旺与四化，判断执行力和财运底子','走专业、技术、金融、管理等结果导向路线，发挥实干','化禄权时大胆扛责任、带项目，把财星能量变现','刻意练习表达和共情，把「对事硬」与「对人软」分开','逢羊陀火铃时放慢语速、先听后断，避免硬碰硬','用大限看财运和事业冲刺期，关系经营则贯穿始终'],
 enStep:['Read Wu Qu brightness and transformations for execution and wealth baseline','Take result-oriented routes—professional, technical, finance, management—to use the grit','With Lu/Quan, take responsibility and lead projects, monetizing the wealth star','Deliberately practice expression and empathy, separating hard-on-tasks from soft-on-people','Under Yang/Tuo/Huo/Ling, slow speech and listen before judging, avoiding head-on clash','Use decades for wealth and career sprints while tending relationships throughout'],
 cnMis:['把对事的刚硬搬到人际里','只信结果不信沟通，觉得解释是多余','逢煞更硬扛，不懂得以柔化刚'],
 enMis:['Carrying task-hardness into relationships','Trusting only results and seeing communication as redundant','Hardening further under malefics instead of softening'],
 cnClose:'武曲坐命的你，是天生把事做成的人。把硬度留给目标、把柔软练进关系，你会发现：能成事又能容人的武曲，走得最远。',
 enClose:'As Wu Qu you are born to get things done. Reserve hardness for goals and train softness into relationships; the Wu Qu who both delivers and keeps people goes furthest.'},

{cat:'zhuxing',slug:'ziwei-tianxiang-zuoming-yinxing-xietiao-yu-xuanze-kunnan',focus:'天相坐命',focusEn:'Tian Xiang in the Life Palace',
 cnT:'紫微斗数天相坐命：印星的协调天赋，和老好人的选择困难',enT:'Tian Xiang in the Life Palace: The Seal Star\'s Coordination Gift and the People-Pleaser\'s Indecision',
 cnD:'天相为印星、属阳水，主协调、辅佐、体面与规则感，善平衡各方、适合管理与服务支持类角色，短板是过度在意他人评价、选择困难、遇压回避，关键是建立自己的判断主轴。',
 enD:'Tian Xiang is the seal star of yang water—coordination, support, propriety and a sense of rules, skilled at balancing parties and suited to management and service-support roles. Its weak edge is over-caring about opinion, indecision and avoidance under pressure; the key is building your own judgment axis.',
 cnL:'天相坐命的人天生会让场面好看、让各方舒服，但「谁都不想得罪」到极致，就变成没有主意、也没有边界的老好人。',
 enL:'Tian Xiang naturally makes scenes graceful and people comfortable, but trying to offend no one at the extreme becomes an indecisive, boundary-less people-pleaser.',
 cnA:'很多天相坐命的人能力不差却总升不上去，卡在「什么都想顾全、迟迟不敢拍板」，问题正是缺一根属于自己的主轴。',
 enA:'Capable Tian Xiang people stall at promotion, stuck trying to cover everything and never deciding; they lack an axis of their own.',
 cnLog:['天相为南斗印星、属阳水，主印信、辅佐、协调、衣食与体面，是把人和资源组织得体的星。','优点是稳重、周到、善平衡，利行政管理、人力资源、秘书幕僚、服务与中介类工作。','天相为「印」，受相邻星曜（夹宫）影响大：逢财荫夹则贵，逢刑忌夹则压，要看两侧环境。','短板是怕冲突、好面子、选择困难，压力下倾向回避；需靠主见和明确原则补足决断。'],
 enLog:['Tian Xiang is the southern seal star of yang water, governing credentials, support, coordination, comfort and propriety—organizing people and resources gracefully.','Strengths: steady, thorough, balancing, suiting administration, HR, chief-of-staff, service and brokerage work.','As a seal it is strongly shaped by flanking palaces: wealth-and-shelter flanking elevates, punishment-and-Ji flanking pressures—read both sides.','Weak edge: conflict-averse, face-conscious, indecisive, avoidant under pressure; it needs clear principles to supply decisiveness.'],
 cnStep:['先看天相所夹星曜，判断你被好环境托住还是被压力夹住','发挥协调与组织天赋，走管理、支持、统筹型路线','刻意建立个人原则清单，拍板前先问「我的主轴是什么」','用限时决策治选择困难：信息够了就定，不追求人人满意','练习温和而坚定地说不，把边界当成体面的一部分','大限逢财荫夹或化禄权科时，大胆从幕后走到台前'],
 enStep:['Read the flanking stars to see whether a good environment supports you or pressure squeezes you','Use coordination and organization on management, support and planning routes','Build a personal-principles list; before deciding ask what your axis is','Cure indecision with time-boxed calls: decide once information is enough, not when everyone is happy','Practice saying no gently but firmly, treating boundaries as part of propriety','When a decade brings wealth-shelter flanking or Lu/Quan/Ke, step from backstage to front'],
 cnMis:['把不得罪人当成最高目标，失去主轴','选择困难还硬要等完美方案，错过时机','只做幕后补位，不敢承担拍板责任'],
 enMis:['Making offend-no-one the top goal and losing the axis','Waiting for a perfect option amid indecision and missing timing','Only filling backstage roles, never taking decision responsibility'],
 cnClose:'天相坐命的你，天生是让团队运转顺滑的人。当你在「让所有人满意」之外，立起自己的原则和主张，协调才会升级成真正的领导力。',
 enClose:'As Tian Xiang you naturally keep a team running smoothly. When you build principles and a stance beyond pleasing everyone, coordination upgrades into real leadership.'},

{cat:'zhuxing',slug:'ziwei-tiantong-zuoming-fuxing-suihe-yu-anyi-xianjing',focus:'天同坐命',focusEn:'Tian Tong in the Life Palace',
 cnT:'紫微斗数天同坐命：福星的随和，和躲在舒适区的陷阱',enT:'Tian Tong in the Life Palace: The Blessing Star\'s Easiness and the Comfort-Zone Trap',
 cnD:'天同为福星、属阳水，主温和、享受、童心与情绪价值，人缘好、抗压强时是有福且能自愈的人，短板是贪图安逸、逃避压力、韧性不足，关键是在不丢掉松弛感的前提下补执行力。',
 enD:'Tian Tong is the blessing star of yang water—gentleness, enjoyment, childlike heart and emotional value. Well supported it is lucky and self-healing with good rapport; its weak edge is comfort-seeking, avoidance and low resilience. The key is adding execution without losing ease.',
 cnL:'天同坐命的人天生会让自己和别人舒服，这是福气；但「舒服」一旦变成「不肯吃苦、遇事就躲」，福气就变成困住你的安逸。',
 enL:'Tian Tong naturally keeps itself and others comfortable—a blessing; but when comfort becomes refusing hardship and dodging difficulty, the blessing becomes a trapping ease.',
 cnA:'很多天同坐命的人聪明讨喜却总差临门一脚，不是能力不够，而是太早回到舒适区，把「没关系、慢慢来」当成了不行动的借口。',
 enA:'Bright, likable Tian Tong people often miss the final push—not lacking ability but retreating to comfort too early, using it\'s-fine-take-it-easy as an excuse not to act.',
 cnLog:['天同为南斗福星、属阳水，主福分、享受、情绪、孩童般的纯真，是天生的情绪价值提供者。','优点是温和亲和、人缘好、能自我疗愈，逢吉星一生平顺、贵人多、懂生活。','短板是怕苦怕压、易满足、责任感和持久力偏弱，逢煞忌则容易情绪化、逃避现实。','天同常需「先苦后甜」：被煞星或责任适度激发，反而能把福气变成真正的成就。'],
 enLog:['Tian Tong is the southern blessing star of yang water—good fortune, enjoyment, emotion and childlike innocence, a natural provider of emotional value.','Strengths: gentle, likable, self-healing; with auspicious stars life is smooth, patrons plentiful and lifestyle rich.','Weak edge: fears hardship and pressure, easily satisfied, weak on responsibility and stamina; with malefics/Ji it turns emotional and avoidant.','It often needs bitterness-before-sweetness:适度激发 by malefics or responsibility turns the blessing into real achievement.'],
 cnStep:['先看天同逢吉还是逢煞，判断福气能否转化为成就','保留松弛感和好人缘，这是你的独特优势','给享受型天性加装执行力：拆小目标、设外部监督','主动承担一点「不舒服但该做」的事，练韧性和责任','逢煞忌时不逃避情绪，用规律作息和具体行动破内耗','大限引动权忌（被责任推一把）时，当成成长窗口接住'],
 enStep:['Read whether Tian Tong meets auspicious or malefic stars to see if blessing converts to achievement','Keep ease and likeliness—your unique edge','Add execution to an enjoyment nature: small goals, external accountability','Voluntarily take on uncomfortable-but-right tasks to build resilience','Under malefics/Ji, do not flee emotion; break the loop with routine and concrete action','When a decade activates Quan/Ji (a push of responsibility), receive it as a growth window'],
 cnMis:['把随和当偷懒借口，长期停在舒适区','怕吃苦而绕开所有有挑战的机会','一遇压力就躲，韧性始终练不出来'],
 enMis:['Using easiness as an excuse to linger in the comfort zone','Avoiding every challenging opportunity for fear of hardship','Dodging at every pressure, never building resilience'],
 cnClose:'天同坐命的你，自带别人求不来的松弛和福气。别让它变成逃避的温床——在舒服之外多扛一点事，福星才会既有好心态，又有真成绩。',
 enClose:'As Tian Tong you carry ease and blessing others cannot buy. Do not let it become a hiding place; carry a little more beyond comfort, and the blessing star gains both a good mindset and real results.'},

{cat:'zhuxing',slug:'ziwei-jumen-zuoming-koushe-xing-koucai-yu-shifei',focus:'巨门坐命',focusEn:'Ju Men in the Life Palace',
 cnT:'紫微斗数巨门坐命：口舌星的口才天赋，和是非暗耗的短板',enT:'Ju Men in the Life Palace: The Mouth Star\'s Eloquence and Its Friction-and-Doubt Weak Edge',
 cnD:'巨门为暗星、属阴水（又带金），主口舌、思辨、研究与表达，庙旺化权禄时是靠口才、专业分析吃饭的人，短板是多疑、挑剔、言多必失，关键是把「嘴」用在专业表达而非争辩是非。',
 enD:'Ju Men is the dark star of yin water (with metal), governing speech, critical thought, research and expression. Bright with Quan/Lu it lives on eloquence and expert analysis; its weak edge is suspicion, nitpicking and loose-tongued trouble. Use the mouth for expert expression, not argument.',
 cnL:'巨门坐命的人靠「把复杂的事说清楚」立身，同一张嘴，用来做专业输出是影响力，用来争对错、翻旧账就是是非源。',
 enL:'Ju Men people stand on making complexity clear; the same mouth is influence as expert output but a source of friction when used to win arguments and rehash grievances.',
 cnA:'很多巨门坐命的人逻辑强、看得透，却总因说话太直、爱质疑而得罪人、招误解，问题不在看得透，而在表达没选对场合和方式。',
 enA:'Logical, perceptive Ju Men people offend and get misunderstood through bluntness and questioning; the issue is not insight but choosing the wrong setting and manner to express it.',
 cnLog:['巨门为北斗暗星、属阴水，主口舌、声音、猜疑与深度研究，是最需要「被说清楚」的星。','庙旺或化禄化权：口才好、分析深、能以言立身，利律师、教师、主播、销售、研究与评论。','落陷逢煞忌：多疑虑、爱翻旧账、言辞尖锐，易招口舌是非、人际暗耗和沟通误会。','巨门喜太阳照（解暗）、喜化禄权科（给口才正途），表达有了光和专业，暗耗就转成影响力。'],
 enLog:['Ju Men is the northern dark star of yin water, governing speech, voice, doubt and deep research—the star that most needs things spoken clearly.','Bright or with Lu/Quan: eloquent and analytical, building on words, suiting law, teaching, broadcasting, sales, research and commentary.','Dimmed with malefics/Ji: suspicious, grudge-rehashing, sharp-tongued, prone to verbal friction, hidden relational drain and misunderstanding.','It likes Tai Yang\'s illumination (dispelling darkness) and Lu/Quan/Ke (a proper channel for speech); with light and expertise, drain becomes influence.'],
 cnStep:['先看巨门庙旺与四化，判断口才走正途还是招是非','走靠表达和分析立身的路线：教学、法律、内容、研究','化禄权科时大胆输出专业，把口才变成个人品牌','刻意练习「先肯定再表达不同」，减少直话刺人','戒翻旧账和无意义争辩，把质疑用在研究而非人际','找「太阳」型舞台（公开、正向、能见光）化解巨门的暗'],
 enStep:['Read Ju Men brightness and transformations to see whether speech builds or causes friction','Take expression-and-analysis routes: teaching, law, content, research','With Lu/Quan/Ke, output expertise boldly and turn speech into a personal brand','Practice affirm-before-disagree to blunt sharp words','Quit rehashing and pointless arguments; use doubt in research, not relationships','Find a Tai-Yang stage (public, positive, in the light) to dissolve Ju Men\'s darkness'],
 cnMis:['把口无遮拦当直率真性情','爱争对错、翻旧账，把关系吵薄','只质疑不建设，专业输出没跟上'],
 enMis:['Mistaking unfiltered speech for honesty','Winning arguments and rehashing until relationships thin','Only doubting without building, lacking expert output'],
 cnClose:'巨门坐命的你，有一张能穿透迷雾的嘴。把它用在说清真相、输出专业上，再给表达加一层温度，是非会退场，影响力会留下。',
 enClose:'As Ju Men you own a mouth that cuts through fog. Use it to clarify truth and deliver expertise, add warmth to expression, and friction retreats while influence remains.'},

{cat:'zhuxing',slug:'ziwei-pojun-zuoming-haoxing-pojiu-lixin',focus:'破军坐命',focusEn:'Po Jun in the Life Palace',
 cnT:'紫微斗数破军坐命：先锋星的破旧立新，和先破后立的代价',enT:'Po Jun in the Life Palace: The Vanguard Star\'s Destroy-and-Rebuild and Its Cost',
 cnD:'破军为耗星、属阴水（化气为耗），主开创、变革、推倒重来与消费，敢闯敢变、适合开拓新局，短板是波动大、易推倒过头、难守成，关键是学会「破中有立」、为变动留好后手。',
 enD:'Po Jun is the consuming star of yin water (transforming to depletion), governing pioneering, change, tearing down and rebuilding and spending. Bold and suited to opening new ground, its weak edge is high volatility, over-demolishing and poor consolidation; the key is rebuilding within the break and keeping a fallback.',
 cnL:'破军坐命的人生是波浪式的：靠一次又一次破旧立新打开局面，最怕只破不立、把推倒当习惯，却没建起新的东西。',
 enL:'A Po Jun life moves in waves, opening ground through repeated destroy-and-rebuild; the danger is breaking without building, making demolition a habit with nothing new raised.',
 cnA:'很多破军坐命的人敢闯敢变、机会抓得快，却总在「推倒重来」里耗掉积累，问题不是不敢变，而是变之前没想清楚立什么、留什么后手。',
 enA:'Bold, quick-to-grab Po Jun people burn accumulation in endless rebuilds; the issue is not fearing change but changing without knowing what to build and what fallback to keep.',
 cnLog:['破军为北斗耗星、属阴水，主破坏与开创、消费与变动，是杀破狼开创集团里冲在最前的星。','庙旺或化禄化权：敢闯、能开新局，利创业、改革、开拓性岗位，常有先破后立的大成就。','落陷逢煞：波动反复、财来财去、人际关系与事业易大起大落，守成和情绪稳定是功课。','破军最需「禄」来承接（化禄或禄存），破了之后有资源重建，才不会一破到底、白白耗散。'],
 enLog:['Po Jun is the northern consuming star of yin water, governing destruction and pioneering, spending and change—the vanguard of the Sha-Po-Lang pioneering group.','Bright or with Lu/Quan: bold, able to open new ground, suiting entrepreneurship, reform and pioneering roles, often achieving greatly after breaking first.','Dimmed with malefics: repeated swings, money coming and going, big ups and downs in work and relations; consolidation and emotional steadiness are the lessons.','It most needs Lu (Hua Lu or Lu Cun) to receive it—resources to rebuild after the break, so it does not break all the way down and dissipate.'],
 cnStep:['先看破军庙旺与有无禄来承接，判断变动能不能立得住','发挥开创优势，主动进入需要破局、拓荒的领域','每次「破」之前先写清「立什么」：目标、新结构、时间表','留后手：应急金、核心人脉、可回退方案，不一破到底','练守成：新局打开后给它稳定运营的时间，别急着再推翻','大限化禄承接时大胆变革，逢煞无禄的阶段以稳为主'],
 enStep:['Read Po Jun brightness and whether Lu receives it, judging whether change can stand','Use pioneering strength, entering fields that need breakthrough and ground-breaking','Before each break, write what you will build: goal, new structure, timeline','Keep fallbacks: emergency funds, core contacts, a retreat plan—not breaking to the bottom','Practice consolidation: after opening ground, give it stable operating time before another overturn','Change boldly in decades with Lu; in malefic, Lu-less phases prioritize stability'],
 cnMis:['把推倒重来当常态，只破不立','变动前不留后手，一破到底难翻身','新局刚起又推翻，积累始终留不住'],
 enMis:['Making rebuild the norm, breaking without building','Changing with no fallback, breaking to the bottom with no recovery','Overturning a newly opened field, never keeping accumulation'],
 cnClose:'破军坐命的你，是天生的破局者。真正的高手不是敢推翻一切，而是每次破完都能立起更好的新局，并为自己留好退路——破中有立，才是破军的大成。',
 enClose:'As Po Jun you are a born breakthrough-maker. The master is not one who dares tear down everything, but one who raises a better structure after every break with a retreat kept: rebuilding within the break is Po Jun\'s great achievement.'},
];
