const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'gongwei',slug:'ziwei-minggong-daodi-kan-shenme-zonggang-taiji',focus:'命宫',focusEn:'the Life Palace as the chart\'s anchor',
 cnT:'紫微斗数命宫到底看什么：它是整张盘的太极点不是全部',enT:'What the Life Palace Really Shows in Zi Wei Dou Shu: It Is the Anchor, Not the Whole Chart',
 cnD:'命宫是整张盘的太极点，主一个人的核心性格、天赋主轴和行事基调，但任何一件具体的事都要落到对应宫位，命宫定方向、他宫定细节。',
 enD:'The Life Palace is the chart\'s anchor—core personality, innate main line and default style. Any concrete matter still belongs to its own palace: Life sets direction, other palaces set detail.',
 cnL:'命宫回答「你是谁、你用什么姿态面对世界」，不直接回答「你会不会发财、和谁结婚」，那些要去财帛、夫妻宫找答案。',
 enL:'Life answers who you are and how you face the world; it does not directly answer wealth or marriage—those live in Wealth and Spouse palaces.',
 cnA:'新手最容易只盯着命宫主星就给人下一生定论，结果性格说准了，事业感情却全错，因为把太极点当成了整张盘。',
 enA:'Beginners fix on the Life major star and pronounce a whole fate; personality is right but career and love are wrong, because the anchor was mistaken for the chart.',
 cnLog:['命宫由生月与生时定，是十二宫排列的起点，其余十一宫都以它为坐标展开。','命宫主星定核心性格与天赋主轴，辅煞与四化修饰这个主轴的强弱与走向。','命宫强、主轴清的人，面对各领域问题时更有稳定的自己；命宫弱则容易被环境牵着走。','具体事项必须「立太极」到对应宫：看钱立财帛、看感情立夫妻，命宫只提供这个人一贯的应对方式。'],
 enLog:['The Life Palace is set by birth month and hour, the origin from which the other eleven palaces are arranged.','Its major star sets core personality and talent main line; assistants, malefics and transformations tune its strength and direction.','A strong, clear Life Palace gives a stable self across domains; a weak one lets circumstances lead.','Concrete matters move their anchor to the matching palace—money to Wealth, love to Spouse—while Life only supplies the person\'s habitual response.'],
 cnStep:['先定命宫主星与庙旺，说出核心性格和天赋主轴','看命宫三方四正（财帛官禄迁移），补全这个人怎么做事','再看命宫四化与辅煞，判断主轴被加强还是被消耗','看具体问题时，把太极点切到对应宫位，不拿命宫硬套','用命宫的行事风格去解释「他为什么这样处理那件事」','大限命宫叠加本命命宫，看不同阶段这个人的状态变化'],
 enStep:['Set the Life major star and brightness for core personality and talent','Read its trine (Wealth, Career, Travel) to complete how the person acts','Check its transformations and assistants/malefics for strengthening or drain','For a concrete question, move the anchor to the matching palace instead of forcing Life','Use Life style to explain why the person handles that matter this way','Layer the decade Life Palace over the natal one to see how the self shifts by stage'],
 cnMis:['只凭命宫主星断一生吉凶','把命宫当财帛夫妻用，越位回答具体事项','忽略三方四正，把一个人看扁成单星标签'],
 enMis:['Pronouncing lifelong fortune from the Life star alone','Using Life as Wealth or Spouse, answering concrete matters out of place','Ignoring the trine and flattening a person into one-star label'],
 cnClose:'命宫是你读盘的第一站，不是终点站。先在命宫立住「这个人是谁」，再到各宫看「他会经历什么」，盘才读得立体。',
 enClose:'Life is the first stop, not the last. Establish who the person is there, then visit the other palaces for what they experience—that makes the chart three-dimensional.'},

{cat:'gongwei',slug:'ziwei-caibogong-kan-zhuanqian-fangshi-bushi-cunkuan',focus:'财帛宫',focusEn:'the Wealth Palace as earning style',
 cnT:'紫微斗数财帛宫看的是赚钱方式，不是你有多少存款',enT:'The Wealth Palace Shows How You Earn, Not How Much You Have Saved',
 cnD:'财帛宫主现金流量、赚钱方式和对钱的手感，主星决定你适合稳定薪资、专业技能、经营生意还是投资理财，存款总额还要合参田宅与福德。',
 enD:'Wealth governs cash flow, earning style and feel for money. Its major star shows whether you fit a steady salary, professional skill, business or investment; total savings also need Property and Happiness palaces.',
 cnL:'财帛宫回答「钱怎么进来、你怎么用钱」，不回答「你最终多有钱」，后者是财帛、田宅、福德、官禄一起算的总账。',
 enL:'Wealth answers how money comes in and how you use it, not final net worth—that is a joint ledger of Wealth, Property, Happiness and Career.',
 cnA:'有人财帛宫看着普通就认定赚不到钱，其实他可能靠田宅的资产沉淀或官禄的事业平台致富，只看现金流量当然看漏。',
 enA:'An ordinary Wealth Palace is read as cannot-earn, yet wealth may come through Property assets or the Career platform; cash flow alone misses it.',
 cnLog:['财帛宫主收入方式与理财行为：主星是武曲天府偏经营守财，机月同梁偏稳定专业，杀破狼偏开创高波动。','化禄在财帛主来钱顺、机会多，化权主掌控资源，化忌主现金流紧、为钱操心，要看是不是阶段性。','财帛与官禄是对宫，事业模式决定收入模式，不能脱离职业谈财运。','财帛与福德互为表里：福德决定你花钱和守钱的心态，赚得到未必留得住。'],
 enLog:['Wealth governs income style and money behavior: Wu Qu/Tian Fu lean business and stewardship; Ji/Tong/Tong/Liang steady and professional; Sha-Po-Lang pioneering and volatile.','Hua Lu means smooth inflow and chances, Hua Quan resource control, Hua Ji tight cash flow and money worry—check whether it is a phase.','Wealth faces Career across the axis; the work model sets the income model, so money luck cannot be read apart from vocation.','Wealth and Happiness are two sides: Happiness sets the mindset of spending and keeping—earning does not guarantee keeping.'],
 cnStep:['先看财帛宫主星，定赚钱方式：薪资、技能、生意还是投资','看四化：禄权科忌分别对应来钱顺、掌控、名声、阻滞','对宫看官禄，确认收入背后的事业模式是否成立','参田宅看资产沉淀能力，参福德看花钱守钱心态','看煞星：羊铃火陀决定现金流的波动节奏','大限财帛引动禄权时扩张，引动化忌空劫时收缩守成'],
 enStep:['Read the Wealth major star to set earning style: salary, skill, business or investment','Read transformations: Lu/Quan/Ke/Ji for inflow, control, reputation, blockage','Check opposite Career to confirm the work model behind income','Use Property for asset accumulation and Happiness for spending/keeping mindset','Read malefics for the cash-flow volatility rhythm','Expand when the decade Wealth activates Lu/Quan; contract when it activates Ji or empty stars'],
 cnMis:['把财帛宫当存款数字，不看赚钱方式','脱离官禄事业单谈财运','忽略福德，赚得到却留不住也没察觉'],
 enMis:['Treating Wealth as a savings number instead of earning style','Discussing money luck apart from the Career vocation','Ignoring Happiness, so earned money is never kept'],
 cnClose:'财帛宫是你的「赚钱说明书」。先搞懂自己最顺的来钱方式，再谈努力和理财，才不会用别人的赚钱路子硬套自己。',
 enClose:'Wealth is your earning manual. Understand the way money comes to you most smoothly before effort and investing, rather than forcing someone else\'s path.'},

{cat:'gongwei',slug:'ziwei-guanlugong-kan-shiye-geju-shihang-hangye',focus:'官禄宫',focusEn:'the Career Palace and vocation',
 cnT:'紫微斗数官禄宫看事业格局：怎么找到真正适合的行业',enT:'The Career Palace in Zi Wei Dou Shu: Reading Your Vocation and the Right Industry',
 cnD:'官禄宫（事业宫）主事业方向、工作模式、与上司的关系和学业成就，主星组合决定你适合管理、专业技术、业务开创还是稳定体制，选行业先读它。',
 enD:'The Career Palace governs direction, work mode, the relationship with bosses and academic achievement. Its stars show whether you fit management, technical expertise, pioneering sales or a stable institution—read it before choosing an industry.',
 cnL:'官禄宫回答「你靠什么立身、在什么样的组织里最能发挥」，它和命宫、财帛、迁移一起，才拼得完整个职业选择。',
 enL:'Career answers what you stand on and where you perform best; together with Life, Wealth and Travel it completes the vocational choice.',
 cnA:'很多人职业迷茫时只问「我五行属什么」，却不看官禄宫给出的工作模式，结果在不匹配的组织形态里反复内耗。',
 enA:'When lost, people ask their element but ignore the work mode in Career, repeatedly draining inside an organizational form that does not fit.',
 cnLog:['官禄宫主星定工作气质：紫微天府善统筹管理，机梁善研究策划，杀破狼善开创攻坚，同相善协调服务。','官禄与命宫、财帛成三合，事业模式要同时合性格（命）和现金流（财帛）才走得长。','官禄也看上司与学业：化科利考试功名，化权利掌权带队，化忌则易遇瓶颈或与上级磨合。','对宫是夫妻之外的迁移轴：事业能否向外扩张、异地发展，要合参迁移宫。'],
 enLog:['The major star sets work temperament: Zi Wei/Tian Fu coordinate and manage; Ji/Liang research and plan; Sha-Po-Lang pioneer and assault; Tong/Xiang coordinate and serve.','Career trines Life and Wealth; a work model lasts only when it fits both personality (Life) and cash flow (Wealth).','It also covers bosses and study: Hua Ke aids exams and credentials, Hua Quan authority and teams, Hua Ji bottlenecks or friction with superiors.','Its opposite axis is Travel: whether work expands outward or across regions needs the Travel Palace.'],
 cnStep:['先看官禄宫主星与组合，定工作模式和组织类型','三合命宫财帛，确认事业合性格又能带来现金流','看四化：化科走专业名声、化权走管理、化忌先解瓶颈','对宫迁移，判断适合本地深耕还是向外扩张','看辅煞：左右有助力团队，羊陀火铃主高压与波动','大限官禄引动时换岗跳槽创业，对照本命判断是不是长期方向'],
 enStep:['Read the Career major star and combination for work mode and organization type','Trine Life and Wealth to confirm it fits personality and brings cash flow','Read transformations: Ke for professional reputation, Quan for management, Ji to clear bottlenecks','Check opposite Travel for local depth versus outward expansion','Read assistants/malefics: team support versus high-pressure volatility','Change jobs or start up when the decade Career activates, checked against the natal direction'],
 cnMis:['只看命宫选行业，不读官禄的工作模式','把官禄化忌当事业完蛋，其实多是阶段性瓶颈','忽略迁移，错判该不该向外、异地发展'],
 enMis:['Choosing industry from Life alone, ignoring Career work mode','Reading Career Hua Ji as career ruin when it is often a phase bottleneck','Ignoring Travel and misjudging outward or regional expansion'],
 cnClose:'官禄宫是职业选择的罗盘。它不保证你一定成功，但能帮你避开「怎么努力都别扭」的错赛道，把力气用在天生顺手的模式里。',
 enClose:'Career is the vocational compass. It does not guarantee success, but it helps you avoid the wrong track where effort always feels wrong, putting energy into your natural mode.'},

{cat:'gongwei',slug:'ziwei-qianyigong-zaiwai-fazhan-guiren-jiyu-laoyun',focus:'迁移宫',focusEn:'the Travel Palace and outward opportunity',
 cnT:'紫微斗数迁移宫：在外发展、贵人机遇和晚年运势都藏在这',enT:'The Travel Palace in Zi Wei Dou Shu: Outward Growth, Opportunity and Later Years',
 cnD:'迁移宫主外出、异地、人际第一印象与在外际遇，也兼看晚年状态，主星好的人越动越旺、在外得贵人，主星弱或逢煞则出外多波折。',
 enD:'Travel governs going out, relocation, first impressions and fortunes away from home, and later-life state. With good stars one thrives on movement and meets helpers outside; weak or afflicted, travel brings friction.',
 cnL:'迁移宫回答「你离开舒适圈之后会怎样」：是如鱼得水还是处处碰壁，决定你适不适合外出、异地、对外型工作。',
 enL:'Travel answers what happens once you leave the comfort zone—thriving or hitting walls—deciding whether outward, relocated or public-facing work suits you.',
 cnA:'有人命宫很强却窝在原地发展不顺，往往是迁移宫被忽略；这类人恰恰是越往外走、舞台越大。',
 enA:'A strong Life person stuck in place and struggling often has an ignored Travel Palace; for them, the further out they go, the bigger the stage.',
 cnLog:['迁移宫是命宫的对宫，命主内在、迁移主外在表现，两宫合看才是一个人完整的内外状态。','迁移见禄权魁钺，主在外得机会、贵人与舞台，适合对外业务、异地或海外发展。','迁移逢煞忌，主外出奔波、人际摩擦或交通意外式提醒，宜提前规划、避免冲动出行。','迁移也看老运与社会评价：一个人晚年是否被外界善待，迁移宫是重要参考。'],
 enLog:['Travel faces Life: Life is the inner self, Travel the outward expression; read both for the full picture.','Lu/Quan/Kui/Yue in Travel bring outside chances, patrons and stages—suited to public-facing, relocated or overseas work.','Malefics or Ji there mean travel friction, interpersonal clash or accident-type warnings; plan ahead and avoid impulsive trips.','It also reflects later years and social reputation: how the outside world treats you in old age leans on Travel.'],
 cnStep:['先看迁移宫主星，判断在外状态是加分还是消耗','对照命宫，看内外是否一致、有没有「出门更顺」的反差','找禄权魁钺，定位在外贵人与机会的领域','逢煞忌则看波折类型，提前做风险与行程管理','合参官禄，判断事业该不该异地或对外扩张','大限迁移被引动的年份，主动外出、搬迁、拓展人脉'],
 enStep:['Read the Travel major star to see whether going out adds or drains','Compare with Life for inner-outer consistency or a better-outside contrast','Find Lu/Quan/Kui/Yue to locate outside patrons and opportunity fields','With malefics/Ji, identify friction type and manage risk and itineraries','Combine Career to judge relocation or outward expansion','In years the decade Travel activates, travel, relocate and expand networks proactively'],
 cnMis:['只看命宫不看迁移，错判该不该外出','把迁移窄化成旅游出差，忽略异地发展和老运','迁移逢煞就不敢动，其实做好规划仍可借力'],
 enMis:['Judging whether to go out from Life alone, ignoring Travel','Narrowing Travel to tourism while missing relocation and later years','Freezing at Travel malefics when planning still lets you leverage movement'],
 cnClose:'迁移宫是你和世界打交道的界面。读懂它，你会知道自己该守在熟悉处，还是该走出去，让更大的舞台接住你。',
 enClose:'Travel is your interface with the world. Read it and you will know whether to hold familiar ground or step out and let a bigger stage receive you.'},

{cat:'gongwei',slug:'ziwei-fudegong-jingshen-xiangshou-huaqian-xintai',focus:'福德宫',focusEn:'the Happiness Palace and inner capacity',
 cnT:'紫微斗数福德宫：你有没有享受生活的能力，钱都未必说了算',enT:'The Happiness Palace in Zi Wei Dou Shu: Your Capacity to Enjoy Life, Beyond Money',
 cnD:'福德宫主精神世界、内心满足、享受能力与潜意识偏好，也影响花钱守钱的心态，它决定你拥有之后能不能安心享受，而不是一直焦虑。',
 enD:'Happiness governs inner world, mental satisfaction, the capacity to enjoy and subconscious preference, and shapes spending/keeping mindset. It decides whether, after gaining things, you can actually enjoy them instead of constant anxiety.',
 cnL:'福德宫回答「你心里踏实吗、能不能对自己好」，物质由财帛田宅给，幸福感却由福德定。',
 enL:'Happiness asks whether you feel grounded and can treat yourself well; Wealth and Property give things, but Happiness sets the felt sense of well-being.',
 cnA:'有人赚得不少却永远焦虑、不敢停，有人收入平常却自得其乐，差别常常就在福德宫，而不在存款。',
 enA:'High earners stay anxious and unable to rest while modest earners feel content; the difference often sits in Happiness, not savings.',
 cnLog:['福德宫主精神享受与情绪底盘，主星安定（如天府天梁）则内心稳，主星动荡或逢煞忌则容易内耗多虑。','福德与财帛互为表里：福德决定赚钱的动力来源和花钱后的感受，是财运的「心理账户」。','福德也看兴趣、品味与潜意识追求，能解释一个人为什么放着安稳不做、偏要追某种生活。','大限福德被引动，会直接影响那十年的心境：同样的处境，心境不同，过法天差地别。'],
 enLog:['Happiness governs mental enjoyment and emotional baseline; steady stars (Tian Fu, Tian Liang) give calm, restless or afflicted stars bring overthinking.','It pairs with Wealth as inner and outer: Happiness sets the drive to earn and the feeling after spending—the psychological ledger of money.','It also shows interests, taste and subconscious pursuit, explaining why someone leaves stability for a certain life.','An activated decade Happiness directly colors ten years of mood; the same situation is lived very differently with different inner states.'],
 cnStep:['先看福德宫主星，判断情绪底盘是安定还是易感内耗','合参财帛，理解自己赚钱动力和花钱心态','看四化与煞星：化忌羊陀尤其容易焦虑、放不下','对照命宫，看外在表现和内在需求是否一致','用福德的偏好反推适合的生活方式和减压渠道','大限福德逢煞忌的阶段，主动降预期、加心理调节'],
 enStep:['Read the Happiness major star for a calm versus overthinking emotional baseline','Combine Wealth to understand earning drive and spending mindset','Read transformations and malefics: Ji/Yang/Tuo especially breed anxiety and inability to let go','Compare Life for outer performance versus inner need','Use Happiness preferences to infer a fitting lifestyle and stress relief','In decade Happiness afflicted phases, lower expectations and add mental regulation'],
 cnMis:['只看财帛谈幸福，忽略内心享受能力','把福德当虚的、不重要，结果物质够了仍焦虑','不看大限福德，错把阶段性心境问题当性格缺陷'],
 enMis:['Discussing happiness from Wealth alone, ignoring the capacity to enjoy','Dismissing Happiness as soft, then staying anxious despite enough','Ignoring decade Happiness and mistaking a phase mood for a character flaw'],
 cnClose:'福德宫提醒我们：拥有不等于享受。把内心的享受能力修好，外在的努力和财富，才真正变成你能尝到的好日子。',
 enClose:'Happiness reminds us that having is not enjoying. Repair the inner capacity to enjoy, and outer effort and wealth finally become good days you can taste.'},

{cat:'gongwei',slug:'ziwei-tianzhaigong-buzhi-fangchan-huan-you-jiayun-zichan',focus:'田宅宫',focusEn:'the Property Palace and household assets',
 cnT:'紫微斗数田宅宫：不只是买房，它管的是你的家运和资产沉淀',enT:'The Property Palace in Zi Wei Dou Shu: Beyond Housing, It Holds Household Fortune and Accumulated Assets',
 cnD:'田宅宫主房产、居住环境、家庭氛围与固定资产沉淀，也看一家的库藏和归属感，主星稳则容易置业守财，逢煞忌化空则居家多变、资产难聚。',
 enD:'Property governs real estate, living environment, family atmosphere and fixed-asset accumulation, plus household stores and belonging. Steady stars ease home-buying and wealth retention; afflicted or emptied, housing is unstable and assets struggle to gather.',
 cnL:'田宅宫回答「你能不能把流动的钱变成留得住的资产、有没有稳定的后方」，它是财帛的「仓库」。',
 enL:'Property answers whether you can turn flowing money into retained assets and have a stable base—it is Wealth\'s warehouse.',
 cnA:'有人收入很高却始终聚不住资产、频繁搬家或家中不宁，问题往往不在赚钱能力，而在田宅宫这个「库」漏了。',
 enA:'High earners who never accumulate, move often or have a restless home often leak not earning power but the Property warehouse.',
 cnLog:['田宅宫主不动产与居住品质：天府、武曲、太阴庙旺多利置业和资产积累。','田宅是财帛的田宅三方（财帛-官禄-田宅）之一，看长期财富必须把现金流和仓库合起来。','田宅也看家庭氛围与归属感，煞忌聚则家宅不宁、易因房产或家人起摩擦。','田宅与子女、疾厄联动看整体家运；大限田宅引动，常对应买房、搬家、装修或家庭结构变化。'],
 enLog:['Property governs real estate and living quality; Tian Fu, Wu Qu or a bright Tai Yin favor home purchase and accumulation.','It belongs to the Wealth-Career-Property triangle; long-term wealth needs cash flow and warehouse together.','It also shows family atmosphere and belonging; clustered malefics/Ji bring household unrest and friction over property or family.','Linked with Children and Health for overall household fortune; an activated decade Property often means buying, moving, renovating or family-structure change.'],
 cnStep:['先看田宅宫主星庙旺，判断置业与守财的底子','合参财帛官禄，看现金流能不能沉淀成固定资产','找禄权科，定位买房、置产、得家产的机会窗口','煞忌空劫在田宅：避免高杠杆房产，注意家宅与合同','看大限田宅何时引动，安排买房、换房或装修的节奏','居家环境也反作用运势，保持稳定后方是田宅的现实功课'],
 enStep:['Read the Property major star and brightness for home-buying and retention baseline','Combine Wealth and Career to see if cash flow settles into fixed assets','Find Lu/Quan/Ke for windows to buy, acquire or inherit property','Malefics/Ji/empty stars there: avoid leveraged property and watch household and contracts','See when the decade Property activates to time buying, changing or renovating','A stable home feeds back into fortune; keeping a steady base is Property\'s real-life lesson'],
 cnMis:['把田宅窄化成「买不买得起房」','只看财帛不看仓库，赚得多却留不下','田宅逢煞就断定无房产，忽略大限引动和后天规划'],
 enMis:['Narrowing Property to whether you can afford a flat','Reading Wealth without the warehouse, earning much but keeping little','Declaring no property from malefics while ignoring decade timing and planning'],
 cnClose:'田宅宫是你人生的「压舱石」。读懂它，你会知道怎么把一时的收入，变成长期托住你的资产和一个安稳的家。',
 enClose:'Property is life\'s ballast. Read it and you learn to turn momentary income into long-term assets and a stable home that holds you up.'},
];
