const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'sihua',slug:'ziwei-gonggan-feihua-rumen-gong-yu-gong-zenme-chuanlian',focus:'宫干飞化',focusEn:'palace-stem flying transformations',
 cnT:'紫微斗数宫干飞化入门：宫和宫之间是怎么被串联起来的',enT:'Palace-Stem Flying Transformations for Beginners: How Palaces Connect in Zi Wei Dou Shu',
 cnD:'每个宫都有自己的天干，宫干能飞出禄权科忌到别的宫，这叫宫干飞化；它用来追踪一件事从一个领域流向另一个领域的路径，是飞星派看因果串联的核心工具。',
 enD:'Every palace carries its own stem and can fly Lu/Quan/Ke/Ji to other palaces—palace-stem flying. It traces how a matter flows from one life domain to another, the core tool of the Flying-Star school for reading causal chains.',
 cnL:'生年四化是一生的底色（体），宫干飞化是事件的流动（用）：它回答「这件事会牵动、流向哪个领域」，让静态的十二宫动起来。',
 enL:'Birth-year Si Hua is lifelong ground (the body); palace-stem flying is event flow (the function). It answers which domain a matter pulls toward, making the static twelve palaces move.',
 cnA:'新手只看生年四化就停了，遇到「为什么工作一动钱和家也跟着变」这类跨宫问题就读不下去，正是缺了宫干飞化这条动态线。',
 enA:'Beginners stop at birth-year Si Hua and cannot read cross-palace questions like why a work move shifts money and home too—the dynamic flying line is missing.',
 cnLog:['十二宫每一宫都配一个天干（宫干），宫干按十干四化表能化出禄权科忌。','宫干飞化的读法是「A宫干化某曜入B宫」：A宫这件事，以禄/权/科/忌的方式作用到B宫。','化禄是顺缘与资源流向，化权是掌控与推动，化科是名声与平稳，化忌是阻滞、牵挂与必须处理的结。','飞化要成对、成串看：禄忌的流向尤其关键，单飞一颗容易过度解读，连成链才看得出事情的来龙去脉。'],
 enLog:['Each of the twelve palaces carries a stem, which produces Lu/Quan/Ke/Ji per the ten-stem Si Hua table.','It reads as palace A\'s stem transforms a star into palace B: the matter of A acts on B in the mode of Lu, Quan, Ke or Ji.','Lu is smooth resource flow, Quan control and drive, Ke reputation and steadiness, Ji blockage, preoccupation and the knot to handle.','Read flyings in pairs and chains, especially Lu-Ji flow; a single fly is over-read, while a chain reveals the full cause and course.'],
 cnStep:['先确认十二宫每一宫的宫干（排盘软件一般已标）','选定你要问的事，以对应宫为起点（如问钱从财帛起）','按宫干查四化表，找出禄权科忌分别飞到哪宫','逐颗解读：禄给资源、权给掌控、科给名声、忌给课题','把落点连成链，看这件事牵动哪些领域、结在哪','用大限宫干再飞一遍，看这十年的动态是否呼应本命'],
 enStep:['Confirm each palace\'s stem (chart software usually labels it)','Choose the question and start at its palace (e.g. Wealth for money)','Per the stem\'s Si Hua table, find where Lu/Quan/Ke/Ji fly','Read each: Lu resources, Quan control, Ke reputation, Ji the lesson','Link the landings into a chain to see affected domains and the knot','Fly the decade palace stems too, checking whether ten-year dynamics echo the natal'],
 cnMis:['把宫干飞化和生年四化混为一谈','只飞单颗就下结论，不连成链','不看起点宫的事，乱套四化含义'],
 enMis:['Confusing palace-stem flying with birth-year Si Hua','Concluding from one fly without a chain','Ignoring the source palace\'s matter and misapplying the meanings'],
 cnClose:'宫干飞化是命盘的「连线题」。学会看一件事怎么从一个宫流向另一个宫，你就能从静态标签，进到真正的动态推演。',
 enClose:'Palace-stem flying is the chart\'s connect-the-dots. Learning how a matter flows between palaces moves you from static labels to genuine dynamic reasoning.'},

{cat:'sihua',slug:'ziwei-zihua-shi-shenme-nengliang-cong-ziji-huidao-ziji',focus:'自化',focusEn:'self-transformation',
 cnT:'紫微斗数自化是什么：能量从自己出发又回到自己',enT:'What Is Self-Transformation in Zi Wei Dou Shu: Energy That Leaves and Returns to Itself',
 cnD:'当某宫天干化出的四化恰好落回本宫内的星，就叫自化；它代表该领域的能量在内部循环、不往外流，反映命主在这件事上的内在反应模式，而不是外部环境给的。',
 enD:'When a palace\'s stem transforms a star that sits back inside that same palace, it is self-transformation. Energy cycles internally rather than flowing out, reflecting the person\'s inner response pattern in that domain rather than anything the environment imposes.',
 cnL:'飞化是宫与宫之间的往来，自化是一个宫自己跟自己的关系；它常解释「为什么这件事总在自己内部打转」。',
 enL:'Flying is exchange between palaces; self-transformation is a palace relating to itself. It often explains why a matter keeps circling internally.',
 cnA:'有人把自化当普通四化看，结果一直去外部找原因，其实问题出在这个领域「自己消化、自己消耗」的内在模式。',
 enA:'Reading self-transformation as ordinary Si Hua sends you searching outside, when the issue is the domain\'s own internal digest-or-drain pattern.',
 cnLog:['自化分自化禄、自化权、自化科、自化忌四种，都是本宫干化回本宫。','自化禄：自己给自己找舒服、善于消化，但也容易满足现状、好事留不久。','自化权：自己给自己加压、争强，但也容易在这件事上过度掌控、内耗。','自化忌：最需留意，主在该领域自我牵绊、反复纠结、得而复失，是内在功课最重的一种。'],
 enLog:['Self-transformation splits into self-Lu, self-Quan, self-Ke and self-Ji, each the palace\'s own stem returning to it.','Self-Lu comforts and digests things itself, but also settles too easily and does not keep gains long.','Self-Quan pressures and pushes itself, but over-controls and drains in that domain.','Self-Ji needs the most care: self-binding, repeated brooding and gaining-then-losing there, the heaviest inner lesson.'],
 cnStep:['逐宫检查宫干四化是否落回本宫内的星，标出所有自化','分辨是自化禄权科还是自化忌，定内在反应基调','自化禄防满足太快、成果留不住，给自己设外部承诺','自化权防过度掌控，学会分权和松弛','自化忌重点修：识别该领域的自我牵绊，刻意向外求反馈','合参大限，看哪十年自化被引动、内在模式最明显'],
 enStep:['Check each palace whether its stem transforms a star back inside itself; mark all self-transformations','Tell self-Lu/Quan/Ke from self-Ji to set the inner-response tone','Self-Lu: guard against quick satisfaction and lost gains by making external commitments','Self-Quan: guard over-control; learn to delegate and relax','Self-Ji is the key repair: spot self-binding there and deliberately seek outside feedback','Use the decade to see which ten years activate the self-transformation and reveal the pattern'],
 cnMis:['把自化当普通飞化，去外部找错原因','只记凶吉，不理解自化是内在反应模式','看到自化忌就恐慌，不知道它指向的是可修的功课'],
 enMis:['Treating self-transformation as ordinary flying and seeking causes in the wrong place','Memorizing luck only, missing that it is an inner response pattern','Panicking at self-Ji instead of seeing a fixable lesson'],
 cnClose:'自化照见的是你和自己的关系。看懂哪个宫在自我循环、自我消耗，你就找到了那件事真正该下功夫的内在入口。',
 enClose:'Self-transformation mirrors your relationship with yourself. Seeing which palace self-cycles and self-drains reveals the true inner entrance for the work.'},

{cat:'sihua',slug:'ziwei-zihua-lu-zihua-ji-weishime-de-er-fu-shi',focus:'自化禄自化忌得而复失',focusEn:'why self-Lu and self-Ji lose what was gained',
 cnT:'紫微斗数自化禄自化忌：为什么会「得而复失、留不住」',enT:'Self-Lu and Self-Ji in Zi Wei Dou Shu: Why Gains Slip Away',
 cnD:'自化的共同特点是能量不往外走、在本宫消化，所以自化禄常表现为得到却甘心放手、来得容易去得快，自化忌则是反复纠结后仍失去，关键在建立外部锚点把成果留住。',
 enD:'Self-transformation keeps energy from flowing out and digests it inside the palace, so self-Lu often means gaining then willingly letting go—easy come, easy go—while self-Ji means losing after repeated brooding. The fix is building external anchors to retain results.',
 cnL:'「化为无」不是从没得到，而是得到后因为内在模式没接住；自化禄输在不珍惜地放手，自化忌输在纠结中消耗。',
 enL:'Transforming-to-nothing is not never getting, but failing to hold a gain due to an inner pattern; self-Lu loses by careless release, self-Ji by draining brooding.',
 cnA:'有人总在同一类事上「到手又飞了」——机会、感情、存款都如此，往往就是相关宫位自化，能量没被外部结构锁住。',
 enA:'People repeatedly watch chances, relationships and savings arrive then fly away in the same domain—often a self-transforming palace whose energy no external structure locks in.',
 cnLog:['自化禄是「自己给自己禄」：在该领域容易自我满足、看得开，副作用是不执着、成果不主动守。','自化忌是「自己给自己忌」：在该领域过度在意、反复拉扯，反而把关系或机会消耗掉。','两者都呈「得而复失」，但机制相反：一个是松手松掉，一个是抓紧抓坏，应对方式也不同。','破解之道是引入外部结构：自化禄靠承诺、契约、共同目标锁住，自化忌靠止损线、外部反馈和行动闭环破内耗。'],
 enLog:['Self-Lu grants its own comfort: easily content and open-minded there, with the side effect of not clinging and not actively defending results.','Self-Ji grants its own knot: over-caring and repeated pulling there, draining the relationship or chance instead.','Both show gain-then-loss by opposite mechanisms—one releases loosely, the other grips too hard—so responses differ.','The fix imports external structure: self-Lu is locked by commitments, contracts and shared goals; self-Ji breaks the loop with stop-loss lines, outside feedback and action closure.'],
 cnStep:['先确认是哪个宫自化禄或自化忌，锁定「留不住」的领域','自化禄：承认自己容易放手，用书面承诺和对外约定锁住成果','自化忌：承认自己容易内耗，设止损线和决策时限','给该领域建立可检查的外部锚点（deadline、合伙人、账户隔离）','大限引动自化的年份格外警惕，不做情绪化的放弃或抓取','事后复盘：这次失去是松手松掉还是抓紧抓坏，对症调整'],
 enStep:['Confirm which palace has self-Lu or self-Ji, locking the cannot-keep domain','Self-Lu: admit you release easily; use written commitments and external agreements to lock gains','Self-Ji: admit you drain internally; set stop-loss lines and decision deadlines','Build checkable external anchors there (deadlines, partners, separated accounts)','Be extra careful in years the decade activates the self-transformation; no emotional quitting or grasping','Review afterward: was the loss from loose release or tight grip? Adjust accordingly'],
 cnMis:['把得而复失全归运气，不查自化机制','对自化禄和自化忌用同一种解法','只在心态上劝自己，不建立外部锚点'],
 enMis:['Blaming gain-then-loss on luck without checking self-transformation','Using one fix for opposite mechanisms of self-Lu and self-Ji','Only talking oneself around without building external anchors'],
 cnClose:'自化的「留不住」不是命定，而是提醒你：这类事光靠内在感觉守不住，必须用外部结构替你把成果锚住。',
 enClose:'The cannot-keep of self-transformation is not fate but a reminder: such matters cannot be held by inner feeling alone—external structure must anchor the result for you.'},

{cat:'sihua',slug:'ziwei-shengnian-feihua-zihua-sanceng-zenme-fen',focus:'三层四化区分',focusEn:'three layers of Si Hua',
 cnT:'紫微斗数生年四化、宫干飞化、自化三层怎么分、先看哪层',enT:'Birth-Year, Flying and Self Si Hua in Zi Wei Dou Shu: Three Layers and Reading Order',
 cnD:'生年四化是先天底色、一生不变，宫干飞化是宫位间的动态往来，自化是某宫内部循环，三层分工不同；读盘顺序是先用生年定体，再用飞化自化看用，最后叠大限流年看时间。',
 enD:'Birth-year Si Hua is fixed lifelong ground; palace flying is dynamic exchange between palaces; self-transformation is internal cycling. They divide labor: use birth-year for the body first, flying/self for function, then layer decade and year for timing.',
 cnL:'三层四化像地图的底色、道路和红绿灯：生年告诉你地形，飞化告诉你车流方向，自化告诉你哪个路口在原地打转，大限流年告诉你何时通行。',
 enL:'The three layers are a map\'s terrain, roads and lights: birth-year gives terrain, flying gives traffic direction, self-transformation the intersection circling itself, and decade/year says when to move.',
 cnA:'很多人学四化越学越乱，就是把三层混在一起看，结果静态底色、动态流向和时间应期搅成一团，什么都断不准。',
 enA:'People find Si Hua increasingly confusing by blending the three layers, tangling fixed ground, dynamic flow and timing until nothing reads clearly.',
 cnLog:['第一层生年四化：由出生年天干定，落宫一生不变，是天赋与课题的「体」，最先看。','第二层宫干飞化：各宫宫干飞出四化到他宫，是事件与资源的流动路径，回答「怎么牵连」。','第二层还含自化：飞回本宮，是内在循环模式，回答「哪里在自己打转」。','第三层大限流年四化：随时间变化，是引动；当运限四化叠上生年、飞化，事情才真正到应期。'],
 enLog:['Layer one, birth-year Si Hua: set by the birth-year stem, fixed for life in its palace—the body of talent and lesson, read first.','Layer two, palace flying: each stem flies transformations to other palaces, the flow path of events and resources, answering how things connect.','Layer two also holds self-transformation: flying back to the same palace, the inner cycle, answering where things circle themselves.','Layer three, decade/year Si Hua: changes with time as activation; when it overlays birth-year and flying, the matter reaches its timing.'],
 cnStep:['第一步只看生年四化，定出一生的资源（禄）、掌控（权）、名声（科）、课题（忌）','第二步看宫干飞化，追各领域之间怎么流动、牵连','第三步标出自化，找内在循环和得而复失的领域','第四步叠大限四化，看这十年哪些静态结构被引动','第五步叠流年四化收窄到具体年份应期','任何一层都不单独下结论，三层一致才是可靠判断'],
 enStep:['Step one: read only birth-year Si Hua for lifelong resources (Lu), control (Quan), reputation (Ke) and lessons (Ji)','Step two: read palace flying to trace how domains flow and connect','Step three: mark self-transformation for inner cycles and gain-then-loss domains','Step four: overlay decade Si Hua to see which fixed structures activate these ten years','Step five: overlay yearly Si Hua to narrow the concrete timing year','Never conclude from one layer; reliable judgment needs three-layer agreement'],
 cnMis:['三层混看，越看越乱','跳过生年直接玩飞化，失去底色','不叠大限流年，把可能性当成马上发生'],
 enMis:['Blending the three layers into confusion','Skipping birth-year to play with flying, losing the ground','Skipping decade/year and treating possibility as imminent'],
 cnClose:'四化不是四颗星，而是一套「定底色—看流动—找内耗—定时间」的推演系统。按体、用、时三层走，再复杂的盘也能一层层读清。',
 enClose:'Si Hua is not four stars but a system: set ground, read flow, find inner drain, fix timing. Follow body, function and timing in order, and even complex charts read clearly layer by layer.'},
];
