const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'liunian',slug:'ziwei-daxian-xiaoxian-liunian-qubie-yiceng-ceng-kan',focus:'大限小限流年区别',focusEn:'decade, minor limit and year differences',
 cnT:'紫微斗数大限、小限、流年到底什么区别：一张表讲清',enT:'Decade, Minor Limit and Yearly Fortune in Zi Wei Dou Shu: A Clear Breakdown',
 cnD:'大限管十年阶段运势、按命宫顺逆排，流年管一个公历年、所有人同年地支相同，小限按虚岁排、是另一套年度参考；现代看流年以大限为背景、流年为触发，小限多作辅助。',
 enD:'The decade governs a ten-year stage, arranged forward or backward from Life; the yearly fortune covers a calendar year with the same branch for everyone; the minor limit follows nominal age as a second yearly reference. Modern reading treats the decade as background and the year as trigger, with the minor limit as backup.',
 cnL:'大限是「你正走在哪段人生季节」，流年是「这一年天气如何」，小限是另一套年度参照，层级不同，不能混为一个东西。',
 enL:'The decade is your life season, the year is that year\'s weather, and the minor limit is another yearly reference—different levels, not one thing.',
 cnA:'新手常把大限、流年、小限当成三选一，结果用年度的流年级数去否定十年大限的趋势，或反过来，判断当然打架。',
 enA:'Beginners treat them as either-or, using yearly signs to deny a ten-year trend (or reverse), so readings contradict themselves.',
 cnLog:['大限（大运）：以命宫起、阳男阴女顺行、阴男阳女逆行，每十年移一宫，管这十年的主基调与舞台。','流年：以当年农历地支定流年命宫，全世界同一年的人流年命宫地支相同，管一年内的具体事件触发。','小限：以本人虚岁排，每年一宫，是传统派另一套年度气数参考，主该岁的内在状态。','正确层级：本命定一生格局（体），大限定十年阶段，流年定当年应期，小限辅助参照；四层叠加才完整。'],
 enLog:['Decade: starts at Life, forward for yang-male/yin-female and backward for yin-male/yang-female, moving one palace per ten years, setting the decade\'s tone and stage.','Yearly: the lunar-year branch fixes the yearly Life Palace, identical in branch for everyone that year, governing concrete event triggers within the year.','Minor limit: follows nominal age, one palace per year, a traditional second yearly reference of inner state at that age.','Correct hierarchy: natal sets lifelong pattern (body), decade the ten-year stage, year the timing, minor limit as backup; four layers complete the read.'],
 cnStep:['先读本命盘，定一生格局，不急着看运限','排大限：确定当前走哪个十年、顺行还是逆行、主基调','在当前大限背景下排流年，找当年的触发宫位与四化','需要时用小限（虚岁）作年度内在状态的辅助参照','判断顺序永远是大限看趋势、流年看应期，不反过来','流年级的好坏要放进大限里解释：好大限里的好年才发力'],
 enStep:['Read the natal chart for lifelong pattern before any cycles','Lay out the decade: which ten years, forward or backward, and its tone','Within that decade, lay out the year to find trigger palaces and transformations','Use the minor limit (nominal age) as backup for inner yearly state when needed','Always read decade for trend and year for timing, never reversed','Interpret yearly signs inside the decade: a good year fires only in a good decade'],
 cnMis:['把大限流年小限当同一种东西混用','用流年好坏否定十年大限趋势','忽略本命直接谈运限，失去基准'],
 enMis:['Mixing decade, year and minor limit as one thing','Using yearly signs to deny the ten-year trend','Discussing cycles without the natal baseline'],
 cnClose:'运限系统像套娃：本命是你，大限是你正在走的十年，流年是这一年，小限是旁证。一层套一层看，运势才不会越看越乱。',
 enClose:'Cycles nest like dolls: natal is you, decade the ten years you walk, the year this year, minor limit a side note. Read them nested and fortune stops being confusing.'},

{cat:'liunian',slug:'ziwei-liuyue-liuri-zenme-pai-shenme-shihou-cai-xuyao-kan',focus:'流月流日',focusEn:'monthly and daily fortune',
 cnT:'紫微斗数流月流日怎么排：什么时候才需要细看到月和日',enT:'Monthly and Daily Fortune in Zi Wei Dou Shu: How to Derive Them and When You Actually Need Them',
 cnD:'流月以流年斗君宫起正月顺排，流日以流月宫起初一顺排，主月度日度的短期起伏；只有在大事择期、签约、面试、出行等精确到月日的决策时才需要细看，平时看大限流年足够。',
 enD:'Monthly fortune starts the first lunar month at the yearly Dou-Jun palace and proceeds in order; daily fortune starts day one at the monthly palace. They govern short-term fluctuations and are needed only for timing precise decisions—signings, interviews, trips; otherwise decade and year suffice.',
 cnL:'流月流日是「放大镜」不是「主剧情」：大限流年决定有没有这件事，流月流日只帮你挑在哪个月、哪一天动手更顺。',
 enL:'Monthly/daily fortune is a magnifier, not the main plot: decade and year decide whether an event exists; month/day only help pick the smoother time to act.',
 cnA:'有人每天看流日、被吉凶牵着情绪走，其实脱离了大限流年，单日的小波动根本不决定结果，纯属给自己加戏。',
 enA:'People read daily fortune and let it steer mood, but detached from decade and year a single day\'s blip never decides the result—self-imposed drama.',
 cnLog:['先定流年斗君：以流年地支和生月起斗君宫，作为该流年正月的起点。','流月：从斗君宫起正月，沿十二宫顺布，一月一宫，看月度重点与四化。','流日：以当月流月宫起初一，顺行十二宫、一日一宫；流时再从流日宫起子时。','层级铁律：流月不能推翻流年，流日不能推翻流月，短期盘只在长期盘允许的范围内挑时机。'],
 enLog:['First set the yearly Dou-Jun: from the year branch and birth month, as the starting palace for that year\'s first month.','Monthly: the first month begins at Dou-Jun and proceeds around the twelve palaces, one per month, for monthly focus and transformations.','Daily: day one begins at that month\'s palace, one palace per day; hourly then begins zi-hour at the daily palace.','Hierarchy rule: a month cannot overturn a year, a day cannot overturn a month; short charts only time moves within what the long chart allows.'],
 cnStep:['先用大限流年判断这件事这一年到底有没有、值不值得做','确定要做后，定流年斗君宫','从斗君顺排出目标月份的流月宫与四化','在有利流月内，再用流日挑状态好的具体日子','签约面试出行等可细看到日，日常决策不必看流日','任何流月流日的凶都只做时机提醒，不推翻年度判断'],
 enStep:['Use decade and year first to decide whether the matter exists this year and is worth doing','Once committed, set the yearly Dou-Jun palace','Proceed from Dou-Jun to the target month\'s palace and transformations','Within a favorable month, use daily fortune to pick a good specific day','Time signings, interviews and trips to the day; everyday decisions need not','Any bad month/day is only a timing note, never overturning the yearly read'],
 cnMis:['天天看流日，被短期波动牵着走','用流月流日推翻大限流年的趋势','排盘顺序错乱，斗君没定就直接排流月'],
 enMis:['Reading daily fortune constantly, led by short blips','Letting month/day overturn decade/year trends','Misordering the derivation, arranging months before fixing Dou-Jun'],
 cnClose:'流月流日是工具，不是焦虑来源。先用大限流年看清主剧情，再用月日给重要动作挑个好时辰——这才是短期盘的正确用法。',
 enClose:'Monthly and daily fortune are tools, not anxiety. Read the main plot with decade and year, then use month/day to time important moves—that is the correct use of short-term charts.'},

{cat:'liunian',slug:'ziwei-daxian-cong-na-qi-shunxing-nixing-zenme-ding',focus:'大限排法顺逆行',focusEn:'decade arrangement and direction',
 cnT:'紫微斗数大限从哪起、顺行逆行怎么定：十年一步不迷路',enT:'Where the Decade Starts and How Its Direction Is Set in Zi Wei Dou Shu',
 cnD:'大限从命宫起第一步、每十年移一宫，方向由生年阴阳与性别共同决定：阳男阴女顺行、阴男阳女逆行，起运岁数由命宫五行局定，搞懂起点方向岁数，才排得对人生阶段。',
 enD:'The decade starts its first step at the Life Palace and moves one palace every ten years; direction is set by birth-year yin/yang plus gender—yang male and yin female go forward, yin male and yang female backward—while the starting age comes from the Life Palace\'s five-element phase. Master start, direction and age to map life stages correctly.',
 cnL:'大限排法三要素：起点永远是命宫、方向看阴阳性别、几岁起运看五行局，三者定了，十二个十年依次展开。',
 enL:'Three things set the decades: start always at Life, direction from yin/yang and gender, starting age from the five-element phase; then the twelve ten-year steps unfold in order.',
 cnA:'有人排大限方向搞反、或起运岁数算错，结果把别人二十岁的阶段安到三十岁，后面的运势全错位，问题就出在三要素没对齐。',
 enA:'Reversing direction or mis-setting the starting age maps a person\'s twenties onto their thirties and shifts every later stage—the three elements were not aligned.',
 cnLog:['起点：第一个大限就是命宫，代表童年少年起步的十年。','方向：阳年生男、阴年生女顺行（命→兄弟→夫妻…），阴年生男、阳年生女逆行（命→父母→福德…）。','生年阴阳看年干：甲丙戊庚壬为阳，乙丁己辛癸为阴。','起运岁数：由命宫五行局（水二、木三、金四、土五、火六）定，每个大限在该岁数基础上逐宫加十年。'],
 enLog:['Start: the first decade is the Life Palace, the ten years of childhood and early start.','Direction: yang-year male and yin-year female go forward (Life→Siblings→Spouse…); yin-year male and yang-year female go backward (Life→Parents→Happiness…).','Birth-year yin/yang follows the year stem: jia/bing/wu/geng/ren are yang, yi/ding/ji/xin/gui yin.','Starting age: set by the Life Palace five-element phase (water 2, wood 3, metal 4, earth 5, fire 6), adding ten years per palace thereafter.'],
 cnStep:['先定命宫位置和命宫五行局，得出起运岁数','看年干阴阳，再结合性别确定顺行还是逆行','从命宫起第一步大限，标上对应年龄区间','按方向每移一宫加十年，依次排出六到八个大限','把当前年龄对到所在大限宫，读该十年主基调','再在大限内排流年，定位到具体年份'],
 enStep:['Fix the Life Palace and its five-element phase for the starting age','Read the year stem yin/yang and combine gender for direction','Start the first decade at Life and label its age range','Move one palace per step, adding ten years, laying out six to eight decades','Match current age to its decade palace and read that ten-year tone','Then lay out years within the decade to reach specific years'],
 cnMis:['方向只看性别不看年干阴阳，排反了','起运岁数没按五行局，年龄整体错位','跳过命宫直接从别的宫起第一步'],
 enMis:['Setting direction by gender alone, reversing it','Ignoring the five-element phase for starting age, shifting all ages','Starting the first step at another palace instead of Life'],
 cnClose:'大限是把一生切成一段段十年的时间轴。起点、方向、起运岁数这三个开关拨对了，你才能准确说出一个人现在正走在哪段人生季节里。',
 enClose:'The decade cuts life into ten-year segments. Set start, direction and starting age correctly, and you can accurately name which life season someone is walking through now.'},

{cat:'liunian',slug:'ziwei-doujun-liunian-zongkaiguan-zenme-zhao',focus:'流年斗君',focusEn:'the yearly Dou-Jun',
 cnT:'紫微斗数斗君：流年的总开关到底怎么找',enT:'Dou-Jun in Zi Wei Dou Shu: Finding the Master Switch of the Yearly Chart',
 cnD:'斗君是流年盘的正月起点与全年总领，由生月和流年地支推算，流年各宫与流月都从它展开；找到斗君，就拿到了读懂这一年节奏、再往下排流月的总钥匙。',
 enD:'Dou-Jun is the first-month origin and overall commander of the yearly chart, derived from birth month and the year branch; yearly palaces and months unfold from it. Finding Dou-Jun gives the master key to the year\'s rhythm and to arranging months.',
 cnL:'如果说流年命宫是这一年的「主角」，斗君就是这一年的「正月大门和总调度」，流月顺不顺、从哪起，都由它定。',
 enL:'If the yearly Life Palace is the year\'s protagonist, Dou-Jun is its first-month gate and dispatcher; how months run and where they begin are set by it.',
 cnA:'有人排流月直接从流年命宫起正月，省掉斗君，结果月份整体错位，择期自然不准——斗君这一步不能跳。',
 enA:'Starting months at the yearly Life Palace and skipping Dou-Jun shifts every month, so timing is off; this step cannot be skipped.',
 cnLog:['斗君分流年斗君（看一年）与流月斗君，是流盘展开的起算点。','流年斗君推法：从流年地支所在宫起生月，逆数到生月所在，再从该宫起子时顺数到生时，落点即斗君宫。','斗君宫的星曜与四化，可看这一年的总体状态与正月起点的好坏。','十二个流月从斗君宫起正月顺布，因此斗君一错，全年流月连锁错位。'],
 enLog:['Dou-Jun splits into yearly (for the year) and monthly commanders, the origin from which the moving chart unfolds.','Yearly Dou-Jun: count the birth month backward from the year-branch palace, then count the birth hour forward from zi; the landing palace is Dou-Jun.','The stars and transformations in the Dou-Jun palace show the year\'s overall state and the first-month starting quality.','Twelve months proceed from Dou-Jun as month one, so an error there cascades through every month of the year.'],
 cnStep:['先排好流年盘、确定流年地支宫位','按生月从流年地支宫逆数，找到中间落点','再从该宫起子时顺数到本人生时，定出斗君宫','读斗君宫主星与四化，把握全年总基调','从斗君宫起正月，顺排十二流月','在流月基础上再排流日，层级依次向下不跳步'],
 enStep:['Lay out the yearly chart and fix the year-branch palace','Count the birth month backward from that palace to the intermediate landing','From there count the birth hour forward from zi to fix the Dou-Jun palace','Read its major star and transformations for the year\'s overall tone','Start month one at Dou-Jun and arrange the twelve months in order','Arrange days below months, descending level by level without skipping'],
 cnMis:['跳过斗君直接从流年命宫起正月','生月生时数反方向，斗君落错宫','把斗君当流年命宫，混淆主角与总调度'],
 enMis:['Skipping Dou-Jun and starting months at the yearly Life Palace','Counting month/hour in the wrong direction, misplacing Dou-Jun','Confusing Dou-Jun with the yearly Life Palace—dispatcher versus protagonist'],
 cnClose:'斗君是流年盘的第一颗扣子。扣子扣对，全年的流月流日才顺次归位；学会找它，你的运限推演就从「大概哪年」精细到了「哪个月」。',
 enClose:'Dou-Jun is the first button of the yearly chart. Buttoned right, every month and day falls into place; learning to find it takes your reading from roughly-which-year down to exactly-which-month.'},
];
