const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'geju',slug:'ziwei-san-da-jiegou-zonglun-jiyue-tongliang-shapolang-fuxiang-chaoyuan',focus:'三大格局框架总论',focusEn:'three core chart frameworks overview',
 cnT:'紫微斗数三大框架总论：机月同梁、杀破狼、府相朝垣，你属于哪一种',enT:'Three Core Zi Wei Dou Shu Frameworks: Ji-Yue-Tong-Liang, Sha-Po-Lang and Fu-Xiang—Which One Are You',
 cnD:'命宫三方四正（命财官迁）的主星组合，必然落入机月同梁、杀破狼、府相朝垣三大框架之一，分别对应稳定守成型、开创变动型、管理统筹型，三者无高下，只有适不适合的赛道，先定框架再看细节，是看盘第一步。',
 enD:'The major stars across your Life trine and Travel necessarily fall into one of three frameworks: Ji-Yue-Tong-Liang (stable builder), Sha-Po-Lang (pioneering changer), or Fu-Xiang (manager-coordinator). None is superior; only fitting tracks differ. Setting the framework before details is the first reading step.',
 cnL:'三大框架像人生的「操作系统」：机月同梁擅长在体系内稳步积累，杀破狼擅长在变动中开疆拓土，府相朝垣擅长统筹资源守成，选错赛道比不努力更累。',
 enL:'The frameworks are life operating systems: Ji-Yue-Tong-Liang accumulates steadily within systems, Sha-Po-Lang opens new ground amid change, Fu-Xiang coordinates resources and conserves. Choosing the wrong track is more tiring than low effort.',
 cnA:'有人拿杀破狼的盘去考公求稳、拿机月同梁的盘去高风险创业，都是逆着框架走；框架不决定成败，却决定你在哪条路上省力。',
 enA:'A Sha-Po-Lang chart chasing a stable civil-service job, or a Ji-Yue-Tong-Liang chart in high-risk startup, fights its framework. The framework does not decide success but where success costs less.',
 cnLog:['看命宫、财帛、官禄、迁移三方四正的主星群，可归入三大基础框架，人人必居其一。','机月同梁：天机太阴天同天梁交会，性稳、善谋划协调，宜公职、大企业、专业技术与参谋路线。','杀破狼：七杀破军贪狼永远在三方互相牵引，性刚、敢开创、波动大，宜创业、业务、竞争性与变革型工作。','府相朝垣：天府天相在三方照会，主稳重、善管理、重安全与资源调度，宜财务、行政、运营与管理要职。'],
 enLog:['The major stars across Life, Wealth, Career and Travel fall into exactly one of three base frameworks.','Ji-Yue-Tong-Liang: Ji/Tai Yin/Tong/Liang meet—steady, good at planning and coordination, suited to public service, large firms, expertise and advisory routes.','Sha-Po-Lang: Qi Sha/Po Jun/Tan Lang always pull in trine—bold, pioneering and volatile, suited to startups, sales, competition and transformation work.','Fu-Xiang: Tian Fu/Tian Xiang trine—steady, managerial, security-and-resource oriented, suited to finance, administration, operations and leadership.'],
 cnStep:['先排出命财官迁四宫主星','看主星群归入哪一种基础框架','按框架选大方向：守成、开创还是统筹','再看庙旺吉煞，判断框架发挥得好不好','顺着框架选职业和节奏，不逆性硬来','大限引动时观察框架能量被放大还是被压制'],
 enStep:['Lay out the major stars of Life/Wealth/Career/Travel','Classify the star group into one base framework','Pick the broad direction by framework: conserve, pioneer or coordinate','Read strength and auspicious/malefic stars to judge how well the framework expresses','Choose career and pace with the framework, not against it','In activated decades, observe whether the framework is amplified or suppressed'],
 cnMis:['以为三大格局有高低贵贱之分','逆着自己的框架选赛道还怪努力没用','只看命宫单星，不看三方四正整体'],
 enMis:['Believing the frameworks rank high versus low','Choosing against the framework then blaming effort','Reading only the Life star, not the whole trine'],
 cnClose:'先认清自己是哪套「操作系统」，比纠结某颗星重要得多。机月同梁求稳、杀破狼求变、府相朝垣求序，顺框架用力，人生会轻松很多。',
 enClose:'Knowing your operating system matters more than fixating on one star. Ji-Yue-Tong-Liang seeks stability, Sha-Po-Lang change, Fu-Xiang order; work with your framework and life gets far easier.'},

{cat:'geju',slug:'ziwei-jiyue-tongliang-ge-wending-tizhi-canmou-luxian',focus:'机月同梁格',focusEn:'Ji-Yue-Tong-Liang pattern',
 cnT:'紫微斗数机月同梁格：「作吏人」的稳定体制格与参谋路线',enT:'Ji-Yue-Tong-Liang Pattern: The Stable Institutional Pattern and Advisory Route',
 cnD:'天机、太阴、天同、天梁在命宫三方四正交会成机月同梁格，古书说「机月同梁作吏人」，主聪慧稳健、善规划协调，最宜公职、大企业、文教与专业幕僚，逢文昌文曲更佳，见煞则破格、稳定中多波折。',
 enD:'When Tian Ji, Tai Yin, Tian Tong and Tian Liang meet across the Life trine it forms Ji-Yue-Tong-Liang; the classics say it serves as an official—bright, steady, good at planning and coordination, best for public service, large firms, education and advisory staff. Chang/Qu improve it; malefics break the pattern and add波折 to stability.',
 cnL:'机月同梁的优势不是冲锋，而是在一个体系里把复杂的事理清楚、稳稳做上去，走专业和资历路线往往比单打独斗创业更出成绩。',
 enL:'Its edge is not charging but untangling complexity within a system and rising steadily; the expertise-and-seniority route usually outperforms solo entrepreneurship.',
 cnA:'有人嫌机月同梁不够「狼性」硬去创业搏杀，反而丢掉最大优势；这张盘的人要的是选对好平台、用专业和信任慢慢积累话语权。',
 enA:'Finding it insufficiently aggressive, some force startup battles and lose their edge; this chart needs the right platform and slowly builds authority through expertise and trust.',
 cnLog:['正格以命在寅申、天机太阴或天同天梁守命、三方会齐四星为标准，泛格为四星在命财官交会。','四星性偏柔善谋：天机主谋划、太阴主细腻理财、天同主随和、天梁主原则与荫护，合力为稳健协调型。','最利公职、事业单位、大型企业、文教、文秘、策划、财务与专业幕僚，逢昌曲魁钺科名更显。','见擎羊火铃空劫等煞则破格，稳定被打破、易频繁变动或怀才不遇，宜以一技之长立身、减少体制外高风险。'],
 enLog:['The orthodox pattern has Life in Yin/Shen with Ji-Tai Yin or Tong-Liang guarding Life and all four meeting in trine; the broad form has them across Life/Wealth/Career.','The four are soft and strategic: Ji plans, Tai Yin handles detail and money, Tong harmonizes, Liang supplies principle and shelter—together a steady coordinator.','Best for public service, institutions, large firms, education, secretarial work, planning, finance and advisory; Chang/Qu/Kui/Yue/Ke heighten reputation.','Malefics (Yang/Fire-Bell/Empty) break the pattern, disrupting stability into frequent change or unrecognized talent; rely on a specialty and avoid high outside risk.'],
 cnStep:['确认四星是否在命财官三方交会、命是否在寅申','评估庙旺与昌曲魁钺，判断稳定格的成色','优先选公职、大企业、专业幕僚等稳定平台','用规划、协调、专业能力建立不可替代性','逢破格煞星时以技术专长立身，不盲目下海','大限走吉时稳步晋升，走煞时守成充电不折腾'],
 enStep:['Confirm whether the four meet across Life/Wealth/Career and whether Life is in Yin/Shen','Assess strength and Chang/Qu/Kui/Yue for the pattern\'s quality','Favor stable platforms: public service, large firms, advisory staff','Build irreplaceability through planning, coordination and expertise','With broken-pattern malefics, stand on a specialty rather than diving into business','In auspicious decades rise steadily; in malefic ones conserve and recharge'],
 cnMis:['把「作吏人」理解成只能当小职员','嫌稳定而逆性高风险创业','见四星就断好命，不看是否逢煞破格'],
 enMis:['Reading serves-as-official as only being a clerk','Rejecting stability for against-type high-risk startups','Judging a good life from four stars without checking malefics'],
 cnClose:'机月同梁是「把事做稳、把局理清」的格局。别羡慕别人的狼性，选一个值得长期投入的平台，你的专业和资历，就是最深的护城河。',
 enClose:'Ji-Yue-Tong-Liang steadies matters and clarifies the picture. Do not envy aggression; pick a platform worth long investment, and your expertise and seniority become your deepest moat.'},

{cat:'geju',slug:'ziwei-shapolang-ge-kaichuang-dongdang-de-huofa',focus:'杀破狼格',focusEn:'Sha-Po-Lang pattern',
 cnT:'紫微斗数杀破狼格：天生开创者，动荡格局该怎么活',enT:'Sha-Po-Lang Pattern: Born Pioneers and How to Live a Volatile Pattern',
 cnD:'七杀、破军、贪狼永远在三方四正互相会照，构成杀破狼格，主刚劲敢闯、求新求变、人生起伏大，成则开创局面、败则大起大落，关键在选对竞争性赛道、用纪律收敛冲动、趁好运时进攻、低谷时蓄力。',
 enD:'Qi Sha, Po Jun and Tan Lang always meet in trine to form Sha-Po-Lang—bold, innovative, with big life swings. At best it opens new ground; at worst it is boom-bust. The keys are a competitive track, discipline to curb impulse, attacking in good cycles and storing strength in low ones.',
 cnL:'杀破狼的人生像波浪而不是斜坡，稳定重复的生活会憋坏它；它需要在变化和竞争里释放能量，但必须学会控制节奏，否则容易反复推倒重来。',
 enL:'Its life is waves, not a ramp; stable repetition suffocates it. It needs change and competition to release energy but must control pace, or it repeatedly tears down and restarts.',
 cnA:'有人把杀破狼的波动当命不好，其实那是开创者的常态；真正的问题不是起伏，而是在好运时孤注一掷、在低谷时还硬冲，不会攻守转换。',
 enA:'People take its volatility as bad fate, but it is the pioneer\'s norm; the real problem is betting all-in in good times and charging in low ones, never switching offense and defense.',
 cnLog:['七杀守命、破军贪狼在三方会，或破军、贪狼守命而会齐，皆属杀破狼框架，三星永远固定在三方四正。','七杀主决断与威权、破军主破旧立新、贪狼主欲望与多才，合力为强开创、强变动、强竞争。','利创业、业务、市场、军警、技术攻坚、变革型岗位，在扩张期和蓝海领域最能爆发。','逢禄权科、辅弼则开创有成、波动转成上升；逢煞忌空劫则大起大落、易冲动决策，须守纪律、留现金流、不赌身家。'],
 enLog:['Qi Sha guarding Life with Po Jun/Tan Lang in trine—or either guarding Life with all three meeting—is Sha-Po-Lang; the three are fixed in trine.','Qi Sha is resolve and authority, Po Jun breaks-old-to-build-new, Tan Lang desire and versatility—together strong pioneering, change and competition.','Favors startups, sales, marketing, enforcement, hard technical problems and transformation roles; it erupts in expansion and blue-ocean fields.','With Lu/Quan/Ke and assistants the pioneering succeeds and volatility becomes ascent; with malefics/Ji/empty it is boom-bust and impulsive—keep discipline, cash flow, and never bet the whole stake.'],
 cnStep:['确认杀破狼三星是否在命财官三方会齐','选竞争性、变革型、能开荒的赛道，避开纯重复稳定岗','用目标和纪律收敛破军贪狼的冲动','好运大限主动进攻、扩张，低谷大限收缩蓄力','永远留现金流和退路，不孤注一掷','把大起伏当周期管理，而不是命运好坏'],
 enStep:['Confirm the three meet across Life/Wealth/Career','Choose competitive, transformative, frontier tracks and avoid pure repetitive roles','Use goals and discipline to curb Po Jun/Tan Lang impulse','Attack and expand in good decades; contract and recharge in low ones','Always keep cash flow and an exit, never all-in','Manage big swings as cycles, not as good or bad fate'],
 cnMis:['把大起大落当命差','在重复稳定岗里硬熬，憋出内耗','低谷时还硬冲、好运时孤注一掷'],
 enMis:['Taking boom-bust as bad fate','Grinding in repetitive roles until drained','Charging in lows and betting all-in in highs'],
 cnClose:'杀破狼是「乱世里开局面」的格局。你的课题从来不是变稳，而是学会驾驭自己的波浪——会进攻也会收手，动荡就成了你最大的资本。',
 enClose:'Sha-Po-Lang opens ground in turbulent times. Your lesson is not becoming stable but mastering your waves: able to attack and to pull back, volatility becomes your greatest capital.'},

{cat:'geju',slug:'ziwei-fuxiang-chaoyuan-ge-caiku-wengu-de-guanli-ge',focus:'府相朝垣格',focusEn:'Fu-Xiang facing the wall pattern',
 cnT:'紫微斗数府相朝垣格：财库稳固、食禄千钟的管理格局',enT:'Fu-Xiang Facing the Wall Pattern: A Stable Treasury and Management Destiny',
 cnD:'天府与天相在命宫三方四正照会、不见煞冲破为府相朝垣格，主稳重可靠、善统筹调度、重安全与体面，利财务、行政、运营、管理要职，财富靠稳健经营和资源整合累积，逢吉化富贵不小，见煞则减色、需防保守误机。',
 enD:'When Tian Fu and Tian Xiang meet across the Life trine without malefic break, it is Fu-Xiang facing the wall—steady, reliable, good at coordination, valuing security and dignity, suited to finance, administration, operations and leadership. Wealth accumulates through steady management and resource integration; auspicious transformations bring plenty, malefics reduce it and warn against over-conservatism.',
 cnL:'府相朝垣是「管家型」格局：紫微是君、天府是库、天相是印，这张盘最擅长把资源、人和流程安排妥当，在成熟组织里做稳盘的人。',
 enL:'It is the steward pattern: Zi Wei the ruler, Tian Fu the treasury, Tian Xiang the seal; this chart best arranges resources, people and process, steadying mature organizations.',
 cnA:'有人觉得府相朝垣不够刺激、扩张慢，其实它的强项是「稳」和「久」，但要警惕过度求安全、不敢抓机会，把管理天赋变成守成原地踏步。',
 enA:'Some find it slow and unexciting, yet its strength is steadiness and endurance; watch over-caution that refuses chances and turns management talent into stagnation.',
 cnLog:['成格：天府、天相在命宫三方四正朝拱命垣，且无煞忌冲破，主星庙旺为佳。','天府为财库主藏、天相为印主辅佐与协调，合力为稳重、诚信、善规划调度、重安全感和体面。','利财务会计、银行、行政、人力、运营、供应链、秘书幕僚与各类管理岗位，靠长期信任和资源整合上位。','逢禄权科、辅弼魁钺则财官稳美、食禄丰厚；见擎羊火铃空劫则破格，易因保守错失或为安全焦虑，需适度放权与试错。'],
 enLog:['Formation: Tian Fu and Tian Xiang arch toward Life across the trine without malefic/Ji break, major stars strong.','Tian Fu is the storing treasury, Tian Xiang the seal of assistance and coordination—together steady, trustworthy, planning, security-and-dignity oriented.','Favors accounting, banking, administration, HR, operations, supply chain, secretarial staff and management, rising through long-term trust and resource integration.','With Lu/Quan/Ke and assistants, wealth and rank are steady and ample; malefics break it toward missed chances or security anxiety—delegate and experiment in moderation.'],
 cnStep:['确认天府天相是否在三方朝命且无煞破','评估庙旺吉化，判断稳盘能力的成色','优先走财务、行政、运营、管理统筹路线','用可靠和整合能力在成熟平台积累信任','刻意补决断与冒险阈值，避免过度保守','大限吉时稳健升迁扩权，煞时守住基本盘'],
 enStep:['Confirm Tian Fu/Tian Xiang face Life in trine without malefic break','Assess strength and auspicious transformations for steadying power','Favor finance, administration, operations and coordination routes','Build trust on a mature platform through reliability and integration','Deliberately raise decisiveness and risk tolerance to avoid over-caution','In good decades rise and expand authority; in malefic ones hold the base'],
 cnMis:['把稳重当没本事、盲目追刺激','过度求安全，眼睁睁错过机会','见府相就断富贵，不查是否逢煞破格'],
 enMis:['Mistaking steadiness for lack of ability and chasing thrills','Over-valuing safety and watching chances pass','Judging wealth from Fu-Xiang without checking malefics'],
 cnClose:'府相朝垣的天赋是「让一切稳妥运转」。在一个能长期沉淀的平台做统筹者，同时别让求稳困住手脚，你的可靠本身就是稀缺的领导力。',
 enClose:'Fu-Xiang\'s gift is making everything run reliably. Be a coordinator on a platform for long-term growth, but do not let caution bind you; your reliability is itself scarce leadership.'},

{cat:'geju',slug:'ziwei-riyue-fanbei-riyue-shihui-jiu-yiding-xinku-ma',focus:'日月反背',focusEn:'Sun-Moon reversed pattern',
 cnT:'紫微斗数日月反背：日月失辉就一定劳碌辛苦吗',enT:'Sun-Moon Reversed: Does Dim Sun and Moon Always Mean Toil and Hardship',
 cnD:'太阳在戌亥、太阴在辰卯等落陷位置守命、日月皆处失辉之地为日月反背，古书主劳碌、白手成家、昼夜操心，但它不是定死的差命，得吉化吉星或靠专业技术立身者照样有成，关键是理解「靠自己、晚成、多劳」的剧本并顺势安排。',
 enD:'When the Sun sits fallen in Xu/Hai and the Moon in Chen/Mao guarding Life, both dimmed, it is Sun-Moon reversed—the classics say toil, self-made success and day-and-night worry. It is not a fixed bad fate: with auspicious transformations or a technical profession people still succeed; the key is accepting a self-reliant, late-blooming, hard-working script.',
 cnL:'日月反背的核心不是「惨」，而是「缺光」：父母荫庇和现成平台帮不上太多，凡事多靠自己亲力亲为，因此显得忙、显得晚成，但也练出实打实的能力。',
 enL:'Its core is not misery but lack of light: little shelter from family or ready platforms, so everything relies on oneself—busy and late-blooming, but it forges real ability.',
 cnA:'有人一见日月反背就给自己贴劳碌命标签消极认命，也有人无视它硬求年少速成，两种都偏；正确做法是接受晚成节奏、用专业立身、把操心转化为掌控。',
 enA:'Some accept a toil-fate label passively, others ignore it chasing early quick success—both wrong. Accept a late-blooming pace, stand on expertise, and convert worry into control.',
 cnLog:['狭义：太阳居戌、太阴居辰守命，对宫互照；广义：太阳落申酉戌亥子、太阴落寅卯辰巳午等失辉位守命。','日月主光明与庇荫，失辉则先天助力、资源、能见度偏弱，多主白手起家、亲力亲为、作息操劳。','它不否定成就：逢禄权科、昌曲魁钺或主星得辅，靠专业、技术、口碑仍可稳定有成，只是路径更靠自力、更晚熟。','见煞忌空劫时操劳与起伏加重，须特别注意作息健康、情绪与财务缓冲，避免硬撑和透支。'],
 enLog:['Narrow: Sun in Xu, Moon in Chen guarding Life in opposition; broad: Sun fallen in Shen-You-Xu-Hai-Zi or Moon in Yin-Mao-Chen-Si-Wu.','Sun and Moon govern light and shelter; dimmed means weaker innate help, resources and visibility—often self-made, hands-on, tiring schedules.','It does not negate success: with Lu/Quan/Ke, Chang/Qu or Kui/Yue, professional skill and reputation still bring steady achievement, just self-reliant and later.','With malefics/Ji/empty, toil and swings worsen; mind sleep, health, emotion and financial buffer, avoiding over-exertion.'],
 cnStep:['确认日月是否都在失辉落陷位守命或照命','接受「自力、晚成、多劳」的基本剧本，不怨天','优先走专业技术路线，用硬本事替代现成资源','主动经营能见度和贵人，补「光」的不足','重作息健康和财务缓冲，不透支硬撑','大限走到日月庙旺或吉化引动时，往往迎来翻身'],
 enStep:['Confirm whether both Sun and Moon sit/illumine Life from fallen positions','Accept the self-reliant, late-blooming, hard-working script without resentment','Favor a technical-professional route, replacing ready resources with hard skill','Actively build visibility and mentors to supplement the missing light','Prioritize health routines and financial buffer, not over-exertion','When a decade reaches strong Sun/Moon or auspicious activation, turnaround often comes'],
 cnMis:['一见日月反背就认命躺平','无视节奏硬求年少暴成','只顾操劳，不补健康和财务缓冲'],
 enMis:['Giving up on seeing the reversed pattern','Ignoring the pace and forcing early quick success','Only toiling without health and financial buffers'],
 cnClose:'日月反背不是判你辛苦一生，而是告诉你：你的光要自己一点点点亮。接受晚成、练硬本事、照顾好身体，白手起家的人往往走得最扎实。',
 enClose:'Sun-Moon reversed does not sentence you to lifelong toil; it says your light must be lit by yourself, bit by bit. Accept late blooming, build hard skill, care for your body—the self-made often walk most solidly.'},

{cat:'geju',slug:'ziwei-riyue-bingming-yuelang-tianmen-rizhao-leimen-guige',focus:'日月庙旺贵格',focusEn:'bright Sun-Moon noble patterns',
 cnT:'紫微斗数日月并明、月朗天门、日照雷门：日月庙旺的贵格',enT:'Bright Sun-Moon Noble Patterns: Sun-Moon Radiant, Moon at Heaven\'s Gate, Sun at Thunder Gate',
 cnD:'太阳在卯（日照雷门）、太阴在亥（月朗天门）、太阳天梁在卯并明（日月并明）等日月庙旺守命的组合，主光明磊落、才名外显、贵人与机遇较多，利公职、学术、公众表达，是与日月反背相对的一组贵格，但仍需吉曜会照、逢煞亦减分。',
 enD:'Sun in Mao (sun at thunder gate), Moon in Hai (moon at heaven\'s gate), and Sun-Tian-Liang bright in Mao—major stars strong guarding Life—bring openness, visible talent, mentors and chances, favoring public service, academia and public expression. Opposite to reversed Sun-Moon, they still need auspicious support; malefics reduce the score.',
 cnL:'日月庙旺的核心是「自带光」：能见度高、容易被看见被信任，适合走到台前，而日月反背是光弱、靠自己；两组对照着读最清楚。',
 enL:'Bright Sun/Moon means carrying your own light: high visibility, easily seen and trusted, suited to the front stage—directly opposite the dimmed self-reliant reversed pair; reading them together is clearest.',
 cnA:'有人见贵格就以为坐等成功，其实庙旺只给「能见度和起点」，能不能兑现还要看四化和努力；逢煞一样要靠专业稳住。',
 enA:'Seeing a noble pattern, some wait for success; strength only gives visibility and a start, and兑现 still needs transformations and effort, with malefics requiring professional steadiness.',
 cnLog:['日照雷门：太阳在卯宫庙旺守命，主光明、热情、外放、利公职与公众事务。','月朗天门：太阴在亥宫庙旺守命，主才情、清贵、财禄与精神生活丰足，利文艺、财务、研究。','日月并明：太阳天梁在卯等组合，主才高德重、名实相符，逢昌曲化科名声更显。','贵格须无煞冲破、有吉曜会照方真；见煞忌则光被遮、名声起伏，仍需靠实力和经营兑现。'],
 enLog:['Sun at thunder gate: strong Sun in Mao guarding Life—open, warm, outward, favoring public service and public affairs.','Moon at heaven\'s gate: strong Moon in Hai guarding Life—talent, noble refinement, wealth and rich inner life, favoring arts, finance and research.','Sun-Moon radiant: Sun-Tian-Liang in Mao, talented and respected with name matching substance; Chang/Qu/Hua Ke heighten reputation.','A noble pattern needs no malefic break and auspicious support to be genuine; malefics/Ji dim the light and bring reputation swings, still兑现 through strength.'],
 cnStep:['确认太阳或太阴是否在卯亥等庙旺位守命','分清偏太阳（外放公众）还是偏太阴（内敛才情）','顺势走到台前，经营能见度、表达和个人品牌','用昌曲化科强化专业名声，别只靠天赋','查是否逢煞，逢煞则以实力稳住、爱惜羽毛','大限引动庙旺日月时，主动争取曝光和晋升'],
 enStep:['Confirm Sun or Moon guards Life from strong positions like Mao/Hai','Tell Sun-leaning (outward/public) from Moon-leaning (inward/talent)','Step to the front and build visibility, expression and personal brand','Use Chang/Qu/Hua Ke to strengthen professional reputation, not talent alone','Check for malefics; if present, steady with strength and protect reputation','In decades activating strong Sun/Moon, actively seek exposure and promotion'],
 cnMis:['见贵格就坐等成功','庙旺逢煞还以为万事无忧','把日月庙旺和反背混为一谈'],
 enMis:['Waiting for success on a noble pattern','Assuming safety even with malefics','Confusing bright Sun/Moon with the reversed pair'],
 cnClose:'日月庙旺给的是「被看见」的优势。走到台前、把才名变成实力，再爱惜名声，这组贵格才能真正兑现成长期的贵气和机遇。',
 enClose:'Bright Sun/Moon gives the advantage of being seen. Step forward, turn reputation into ability and guard your name, and this noble pattern truly converts into lasting stature and chance.'},

{cat:'geju',slug:'ziwei-shizhong-yinyu-jumen-yincang-caihua-geju',focus:'石中隐玉格',focusEn:'jade hidden in stone pattern',
 cnT:'紫微斗数石中隐玉格：巨门的隐藏才华，为什么越沉潜越发光',enT:'Jade Hidden in Stone: Ju Men\'s Concealed Talent and Why Depth Makes It Shine',
 cnD:'巨门在子午宫守命、三方会禄存或化禄且不见煞冲破为石中隐玉格，巨门本主口舌是非、需打磨，此格却如璞玉藏石，早年多磨砺、不被看见，中晚年靠口才、专业、研究或表达一飞冲天，是典型的大器晚成、厚积薄发格局。',
 enD:'When Ju Men guards Life in Zi/Wu, trining Lu Cun or Hua Lu without malefic break, it is jade hidden in stone. Ju Men governs speech and dispute and needs polishing; like uncut jade it endures early obscurity, then in middle/late years soars through eloquence, expertise, research or expression—a classic late-bloomer, accumulate-then-rise pattern.',
 cnL:'石中隐玉的关键词是「磨」：巨门的口才和洞察要经过现实打磨才不伤人、才成器，所以前半程越沉潜积累，后半程的爆发力越强。',
 enL:'Its keyword is polish: Ju Men\'s eloquence and insight must be honed by reality so they help rather than wound; the deeper the early accumulation, the stronger the later breakthrough.',
 cnA:'有人巨门坐命早年处处碰壁就自我否定，其实正符合「隐玉」剧本；真正可惜的是耐不住打磨、早早放弃，或口舌不收敛、把才华耗在争辩上。',
 enA:'Ju Men people facing early setbacks doubt themselves, yet that fits the hidden-jade script; the real loss is quitting before polish or wasting talent in argument with unchecked speech.',
 cnLog:['成格：巨门在子或午宫守命，三方见禄存、化禄（尤喜太阳化禄、巨门化禄），无四煞空劫冲破。','巨门为口舌、洞察、研究之星，得禄则「口」生财、以专业表达立身，化暗为明。','典型轨迹是早年平凡甚至受质疑、中晚年靠专业、教学、法律、传媒、研究、销售口才成名，越老越吃香。','破格在逢煞忌：口舌是非、表达得罪人，须刻意修炼说话分寸、用事实和专业说话，避免争辩与抱怨。'],
 enLog:['Formation: Ju Men guards Life in Zi/Wu, trining Lu Cun/Hua Lu (esp. Sun or Ju Men Hua Lu), without four-malefic/empty break.','Ju Men is speech, insight and research; with Lu the mouth earns and professional expression converts dark to bright.','Typical arc: ordinary or questioned early, then fame in middle/late years through expertise, teaching, law, media, research or sales eloquence—more valued with age.','Break comes with malefics/Ji: disputes and words offending others; deliberately train measured speech, speak with facts and expertise, avoid argument and complaint.'],
 cnStep:['确认巨门是否在子午守命、三方得禄且无煞破','接受大器晚成节奏，早年沉潜打磨专业','把口才和洞察导向教学、法律、传媒、研究、销售','刻意修炼表达分寸，让口才帮人而非伤人','逢煞忌时少争辩多举证，远离是非场','中晚年大限引动时大胆输出，厚积薄发'],
 enStep:['Confirm Ju Men guards Life in Zi/Wu, trines Lu and has no malefic break','Accept late blooming and use early years to deepen expertise','Direct eloquence and insight into teaching, law, media, research or sales','Train measured expression so speech helps rather than wounds','With malefics/Ji, argue less, evidence more, stay out of dispute scenes','When middle/later decades activate it, output boldly and release accumulated depth'],
 cnMis:['早年受挫就否定自己、半途而废','口才不收敛，把才华耗在争辩抱怨','见巨门就当是非星，看不到隐玉的晚成'],
 enMis:['Quitting after early setbacks','Letting unchecked speech waste talent in argument','Treating Ju Men only as dispute, missing the late-blooming jade'],
 cnClose:'石中隐玉告诉你：巨门的光要磨才出来。别急着在年轻时证明自己，把洞察和表达练成真本事，时间会让藏在石头里的玉，被所有人看见。',
 enClose:'Jade hidden in stone says Ju Men\'s light comes only through polish. Do not rush to prove yourself young; forge insight and expression into real skill, and time will reveal the jade in the stone for all to see.'},
];
