const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'fuzhu',slug:'ziwei-lucun-xing-shoucai-jixu-yu-hualu-qubie',focus:'禄存星',focusEn:'Lu Cun the retained-wealth star',
 cnT:'紫微斗数禄存星：守财积蓄的财库星，它和化禄不是一回事',enT:'Lu Cun in Zi Wei Dou Shu: The Savings Star Is Not the Same as Hua Lu',
 cnD:'禄存由生年天干取、属阴土，主稳定积累、守财与现成福气，是「存量」；化禄是流动的机会与机缘，是「增量」，一个守一个来，读法完全不同。',
 enD:'Lu Cun is set by the birth-year stem, yin earth, governing steady accumulation, retained wealth and existing blessing—the stock. Hua Lu is flowing opportunity and gain—the flow. One keeps, one brings; they read differently.',
 cnL:'禄存回答「你守不守得住、有没有底」，化禄回答「机会从哪来」，真正的财务安全要两者配合：会赚还要会留。',
 enL:'Lu Cun answers whether you can hold wealth and have a base; Hua Lu where chances come from. Real security needs both: earn and keep.',
 cnA:'有人一见化禄就说会发财，却没有禄存守库，钱来得快去得也快；也有人有禄存却不化禄，守着存量却没有新增，两者都偏了。',
 enA:'People see Hua Lu and predict wealth without Lu Cun to hold it, so money comes and goes; others have Lu Cun without Hua Lu, guarding stock with no new inflow—both are one-sided.',
 cnLog:['禄存是北斗辅佐星、属阴土，永远与擎羊、陀罗相夹（前后必带羊陀），主财库、俸禄、稳定收入与保守。','禄存主「存量」：存款、资产、固定收益、既得的福；化禄主「增量」：机会、缘分、新进来的资源。','禄存同宫或会照主星，给该宫稳定的底座，但因羊陀相夹，也带谨慎、孤守、放不开的一面。','禄存最喜会天马成「禄马交驰」、会化禄成「叠禄」，守与流配合，财富才既稳又增。'],
 enLog:['Lu Cun is a northern assistant of yin earth, always flanked by Yang and Tuo, governing the treasury, salary, steady income and conservatism.','It is stock: savings, assets, fixed returns and existing blessing; Hua Lu is flow: chances, encounters and newly arriving resources.','Sharing or meeting a major star gives that palace a stable base, but flanked by Yang/Tuo it also brings caution and a guarded, hard-to-release side.','It loves meeting Tian Ma (Lu-Ma galloping) or Hua Lu (double Lu); when keeping and flowing work together, wealth is both steady and growing.'],
 cnStep:['先定位禄存落在哪宫，确定你在哪个领域最能积累','分清禄存（存量）与化禄（增量），不混为一谈','看是否被擎羊陀罗夹，评估保守与孤守的程度','找禄存同会的主星，判断积累靠什么方式','会化禄或天马时主动扩张，只有禄存时以守成和储蓄为主','大限引动禄存之年适合置产、定存、锁定长期收益'],
 enStep:['Locate Lu Cun to fix where you accumulate best','Separate Lu Cun (stock) from Hua Lu (flow), never blending them','Check the Yang/Tuo flank for caution and guardedness','Find the major star it meets to see how you accumulate','Expand when it meets Hua Lu or Tian Ma; with Lu Cun alone, favor conservation and saving','In years the decade activates Lu Cun, buy property, lock deposits and secure long-term returns'],
 cnMis:['把禄存和化禄当成同一种财','以为有禄存就一定有钱，忽略它只守不来','无视羊陀夹，读不懂禄存的谨慎和孤守'],
 enMis:['Treating Lu Cun and Hua Lu as the same wealth','Assuming Lu Cun alone means wealth while it only keeps, not brings','Ignoring the Yang/Tuo flank and missing its guarded caution'],
 cnClose:'禄存是你财务的「压舱石」。看懂它和化禄的分工——一个管留、一个管来，你才既不会赚多少花多少，也不会只守不增。',
 enClose:'Lu Cun is your financial ballast. Grasp its division of labor with Hua Lu—one keeps, one brings—and you neither spend what you earn nor merely hoard without growth.'},

{cat:'fuzhu',slug:'ziwei-tianma-xing-dongzhong-qiuscai-buan-dong',focus:'天马星',focusEn:'Tian Ma the movement star',
 cnT:'紫微斗数天马星：动中求财，闲不住的变动之星',enT:'Tian Ma in Zi Wei Dou Shu: The Movement Star That Seeks Wealth Through Motion',
 cnD:'天马由生年地支取、只落寅申巳亥四马地，主奔波、迁动、行动力与变化，本身中性，吉则动中生财、越跑越旺，凶则奔波劳碌、变动不安，关键看它和谁同宫。',
 enD:'Tian Ma is set by the birth-year branch and lands only in the four horse palaces (Yin/Shen/Si/Hai), governing travel, movement, action and change. Neutral itself, with auspicious stars it earns through motion; with malefics it is restless toil—the company decides.',
 cnL:'天马是「加速器」不是「财」，它让所在宫的事动起来、快起来，动出什么结果，取决于和它同宫会照的是禄还是煞。',
 enL:'Tian Ma is an accelerator, not wealth; it sets its palace\'s matters in motion and speeds them up. The result depends on whether it meets Lu or a malefic.',
 cnA:'有人见天马就说要远行发财，结果天马逢空劫煞星，越动越破财、白忙一场，就是只看动、不看动出来的是什么。',
 enA:'People see Tian Ma and predict travel wealth, yet with empty/malefic stars more motion means more loss and busywork—seeing movement but not what it produces.',
 cnLog:['天马属阳火、为中天浮曜，只在寅申巳亥四马地，主迁动、奔波、出行、行动力与变化。','天马会禄存或化禄成「禄马交驰」，动中生财、发异乡财，是它最好的组合。','天马会紫微天府为「扶舆马」，主升迁、平台带动；逢空劫煞忌则为「折足马」，奔波而少成。','天马落宫决定动在哪：在财帛为钱奔波、在迁移为外出发展、在官禄为工作常变动或出差。'],
 enLog:['Tian Ma is yang fire, a floating central star landing only in the four horse palaces, governing movement, travel, action and change.','Meeting Lu Cun or Hua Lu forms Lu-Ma galloping—wealth through motion and faraway gain, its best combination.','Meeting Zi Wei/Tian Fu is the supported horse (promotion, platform-driven); meeting empty/malefic/Ji is the broken horse (busy with little result).','Its palace sets where motion goes: Wealth for money, Travel for outward development, Career for frequent job change or trips.'],
 cnStep:['先定位天马落在哪宫，判断变动发生在哪个领域','查它同宫会照的是禄、主星还是煞忌空劫','会禄：主动走出去，争取外派、异地、跨区域机会','逢煞空：减少无效奔波，变动前先评估落点','结合迁移官禄，判断适合稳定岗还是高流动岗','大限流年引动天马时，常见搬家、换岗、出差、迁徙'],
 enStep:['Locate Tian Ma to see which domain change occurs in','Check whether it meets Lu, a major star, or malefic/empty stars','With Lu: step out actively for secondment, relocation and cross-region chances','With malefics/emptiness: cut futile motion and assess the landing before changing','Combine Travel/Career to judge a stable versus high-mobility role','When a decade/year activates Tian Ma, expect moves, transfers, trips or migration'],
 cnMis:['见天马就断发财，不看同宫是禄还是煞','把奔波当努力，忽略折足马的白忙','天马逢煞还频繁折腾，越动越耗'],
 enMis:['Predicting wealth from Tian Ma without checking Lu versus malefic','Mistaking busyness for effort, ignoring the broken horse\'s futile motion','Restlessly changing amid malefics, draining with every move'],
 cnClose:'天马给的是「动」的能量，动得对不对要看同行的星。让它驮着禄走，你越走越宽；让它驮着煞走，只会越奔越累。',
 enClose:'Tian Ma gives the energy of motion; whether it is the right motion depends on its companions. Let it carry Lu and your road widens; let it carry a malefic and you only tire.'},

{cat:'fuzhu',slug:'ziwei-luma-jiaochi-dongzhong-shengcai-fa-yixiang-cai',focus:'禄马交驰',focusEn:'Lu-Ma galloping pattern',
 cnT:'紫微斗数禄马交驰：为什么有的人越往外跑越有钱',enT:'Lu-Ma Galloping in Zi Wei Dou Shu: Why Some People Get Richer the More They Move',
 cnD:'禄存（或化禄）与天马同宫、对拱或三方会照叫禄马交驰，主动中生财、发异乡财，财是流动的，越在奔波、外派、跨区域贸易中越能得财，但仍需本人奔走、属自力格局。',
 enD:'When Lu Cun (or Hua Lu) and Tian Ma share, oppose or trine, it is Lu-Ma galloping: wealth through motion and faraway gain. Money is fluid, earned through travel, secondment and cross-region trade, yet it still requires personal effort—a self-power pattern.',
 cnL:'禄是财、马是轮子，禄马交驰等于给财库装上轮子；这类人不能宅，动起来财源才开，但钱是跑出来的不是等来的。',
 enL:'Lu is wealth and Ma the wheel; the pattern puts wheels on the treasury. Such people cannot stay still—motion opens income—but the money is earned by running, not waiting.',
 cnA:'有人以为禄马交驰是躺着发财，其实它恰恰最辛苦：机会都在外地、外勤、外部市场，不走出去，格局就是睡着的。',
 enA:'People think Lu-Ma is effortless wealth; it is actually the hardest-working pattern—chances sit in outside markets, and without going out the pattern sleeps.',
 cnLog:['成格条件：禄存或化禄与天马同宫最强，对拱、三方会照次之，都算禄马交驰（折鞭马）。','核心象义：财随走动而来，主异地财、外贸、出差外派、物流旅游、跨城跨国发展。','它属佐曜自力格局，不是天降之财，必须本人奔走经营、在变动中抓住机会才兑现。','破格条件：逢地空地劫截空等「空马」，或主星落陷，易白忙、财来财去，需先补承接与财务防线。'],
 enLog:['Formation: Lu Cun/Hua Lu sharing a palace with Tian Ma is strongest, opposition and trine weaker, all counting as Lu-Ma galloping.','Core meaning: wealth follows movement—faraway money, trade, business trips, logistics, tourism, cross-city and cross-border growth.','It is a self-power assistant pattern, not windfall; the person must move and seize chances amid change for it to pay out.','Break: meeting Di Kong/Di Jie/Jie Kong (empty horse) or a fallen major star brings busywork and money in-and-out; build reception and financial defense first.'],
 cnStep:['先全盘找禄存、化禄与天马，判断是否成格及强弱','成格则优先选高流动、跨区域、对外型的工作和生意','主动争取外派、出差、异地市场，别困在原地等客','看清属自力，动的同时要把专业和资源准备好','逢空劫时不盲目扩张，先建财务缓冲再动','用大限流年找禄马被引动的年份，集中在那几年开拓'],
 enStep:['Search the chart for Lu Cun/Hua Lu and Tian Ma to judge the pattern and its strength','If formed, favor high-mobility, cross-region and outward-facing work or business','Actively seek secondment, trips and outside markets rather than waiting locally','Remember it is self-power: prepare expertise and resources while moving','With empty stars, do not expand blindly; build a buffer first','Use decades/years to find when Lu-Ma activates and concentrate expansion there'],
 cnMis:['把禄马交驰当不劳而获','成格却选择宅着不动，格局空转','逢空马还高杠杆扩张，白忙加破财'],
 enMis:['Taking Lu-Ma as something for nothing','Having the pattern yet staying still so it idles','Leveraging up with an empty horse, adding loss to busywork'],
 cnClose:'禄马交驰的人，财在远方、在路上。读懂它，你就知道自己的财富密码不是守，而是带着本事有方向地「动」。',
 enClose:'For Lu-Ma galloping, wealth lies far away and on the road. Read it and you know your code is not guarding but moving with skill and direction.'},

{cat:'fuzhu',slug:'ziwei-guchen-guasu-xinggu-xingu-chiwan-jingshen-duli',focus:'孤辰寡宿',focusEn:'Gu Chen and Gua Su',
 cnT:'紫微斗数孤辰寡宿：形孤和心孤，晚婚与精神独立怎么读',enT:'Gu Chen and Gua Su in Zi Wei Dou Shu: Outer Solitude, Inner Solitude, Late Marriage and Independence',
 cnD:'孤辰属阳火主外在环境造成的形孤、独立与漂泊，寡宿属阴火主内在精神上的心孤、寡合与难被走进，两星入夫妻福德多主晚婚或精神疏离，但并非注定孤独，反能转为独立深度。',
 enD:'Gu Chen is yang fire—outer solitude, independence and wandering caused by environment; Gua Su is yin fire—inner solitude, reserve and being hard to reach. In Spouse/Happiness they often mean late marriage or emotional distance, but not destined loneliness; they can convert to independent depth.',
 cnL:'孤辰是「身边没人」的形孤，寡宿是「有人也走不进心里」的心孤，分清是哪一种，才知道该补相处时间还是补情感表达。',
 enL:'Gu Chen is outer solitude (no one around), Gua Su inner solitude (someone near but not let in); tell them apart to know whether to add time together or emotional expression.',
 cnA:'有人一见夫妻宫孤寡就断言婚姻不幸，其实很多人只是需要独处空间、适合晚婚，主动经营后关系照样稳固，不必被标签吓住。',
 enA:'Seeing Gu Chen/Gua Su in Spouse, people predict marriage failure; many simply need solo space and suit late marriage, and with active effort the bond stays stable—do not fear the label.',
 cnLog:['孤辰、寡宿按生年地支取，是一对主「孤」的杂曜，孤为阳火偏外、寡为阴火偏内。','与武曲、天梁、天机、巨门、七杀、破军等清冷刚硬星系同会，孤独色彩最明显，多主晚婚、聚少离多。','入夫妻宫：观念易有落差、需要空间，宜晚婚、找能尊重独处的伴侣；入福德宫：享受独处、精神自给。','叠华盖时悟性、艺术与玄学缘分增强，并非凶煞，而是把能量转向内在与专业，主动表达情感即可化解疏离。'],
 enLog:['Gu Chen and Gua Su, set by the birth-year branch, are a pair of solitude stars; Gu is yang and outward, Gua yin and inward.','With cool or hard galaxies (Wu Qu, Tian Liang, Tian Ji, Ju Men, Qi Sha, Po Jun) the solitude is strongest, often late marriage and time apart.','In Spouse: value gaps and a need for space, suiting late marriage and a partner who respects solitude; in Happiness: enjoying alone time and emotional self-sufficiency.','Stacked with Hua Gai, insight, art and metaphysical affinity grow—not a malefic but energy turned inward and professional; active expression dissolves the distance.'],
 cnStep:['先按生年支找出孤辰寡宿落在哪宫','分清是形孤（环境聚少离多）还是心孤（精神难共鸣）','在夫妻宫：优先考虑晚婚和尊重空间的伴侣','在福德命宫：把独处转化为深度专注和专业积累','主动练习情感表达和共处仪式，对冲疏离倾向','大限引动孤寡之年不急于绑定关系，先确认相处舒适'],
 enStep:['Find Gu Chen/Gua Su by birth-year branch and their palace','Tell outer solitude (time apart) from inner (no mental resonance)','In Spouse: favor late marriage and a space-respecting partner','In Happiness/Life: turn solitude into deep focus and professional depth','Practice emotional expression and togetherness rituals to offset distance','In decades activating the stars, do not rush commitment; confirm comfort first'],
 cnMis:['见孤寡就判婚姻不幸，忽略晚婚和经营','不区分形孤心孤，补错方向','把独处需求当缺陷，硬改反而内耗'],
 enMis:['Judging marriage failure from the stars, ignoring late timing and effort','Not separating outer from inner solitude, fixing the wrong thing','Treating the need for solitude as a flaw and forcing change, causing drain'],
 cnClose:'孤辰寡宿不是「注定一个人」，而是提醒你：你的关系需要更多空间和更主动的表达。晚婚或独处，都可以是清醒的选择，不是缺憾。',
 enClose:'The solitude stars are not destined aloneness but a reminder that your bonds need more space and more active expression. Late marriage or solitude can be clear choices, not deficits.'},

{cat:'fuzhu',slug:'ziwei-huagai-yishu-xuanxue-tianfu-qinggao',focus:'华盖星',focusEn:'Hua Gai the canopy star',
 cnT:'紫微斗数华盖星：艺术玄学天赋，和那份天生的清高',enT:'Hua Gai in Zi Wei Dou Shu: Artistic and Metaphysical Gift, and a Natural Nobility of Spirit',
 cnD:'华盖主孤高、悟性、艺术、宗教哲学与专精之才，入命者聪明有独特审美、喜欢精神性事物，也容易不合群、自命清高，用得好是深耕一门的大师潜质，用偏则是脱离现实。',
 enD:'Hua Gai governs noble detachment, insight, art, religion and philosophy, and mastery of a specialized craft. In Life it gives intelligence, distinctive taste and spiritual interests, but also reserve and aloofness; well used it is master-level depth, misused it is detachment from reality.',
 cnL:'华盖是一把「向内钻」的钥匙：它让你在一门技艺、一种精神世界里扎得比常人深，代价是对世俗热闹天然兴趣不高。',
 enL:'Hua Gai is a key that drills inward: it lets you go deeper than most into a craft or an inner world, at the price of low natural interest in worldly noise.',
 cnA:'有人把华盖当出家星、孤僻星吓自己，其实它更多是专业与才华的标记，真正要防的不是孤独，而是只顾精神世界、丢了现实经营。',
 enA:'People fear Hua Gai as a monk or loner star; it is mostly a mark of craft and talent. Guard not against solitude but against tending the inner world while neglecting reality.',
 cnLog:['华盖本为帝王车驾之伞，引申为孤高、威仪、悟性与精神追求，按年支或日支取。','入命主聪明、见解独特、审美高、对艺术、玄学、哲学、宗教有天然亲近，能长期深耕冷门专业。','负面是不合群、自命清高、想法脱俗但落地弱，逢煞忌易逃避现实、陷入孤芳自赏。','华盖与孤寡同会精神性更强，与昌曲龙池凤阁同会则艺术才华出众，关键是给才华找现实出口。'],
 enLog:['Originally the imperial canopy, it extends to noble detachment, dignity, insight and spiritual pursuit, set by year or day branch.','In Life it gives intelligence, distinctive views, high taste and natural affinity for art, metaphysics and philosophy, sustaining deep work in niche fields.','The downside is reserve, aloofness and unworldly ideas weak in practice; with malefics/Ji it escapes reality into self-admiration.','With solitude stars the spiritual side strengthens; with Chang/Qu and Dragon/Phoenix the artistry shines—the key is a real-world outlet for talent.'],
 cnStep:['定位华盖落宫，看精神与才华集中在哪个领域','顺着悟性深耕一门技艺或学问，把清高变成专业壁垒','刻意补现实经营：社交、表达、变现，别只活在精神里','与昌曲同会时走艺术、内容、设计、研究路线','逢煞忌时警惕逃避现实，用具体成果把自己拉回地面','尊重自己不合群的天性，但保留必要的世俗连接'],
 enStep:['Locate Hua Gai to see where spirit and talent concentrate','Follow the insight into one craft or field, turning detachment into a professional moat','Deliberately build real-world skills: networking, expression, monetization','With Chang/Qu take art, content, design or research routes','With malefics/Ji watch escapism and return to ground through concrete results','Honor your reserved nature while keeping necessary worldly ties'],
 cnMis:['把华盖当出家或孤僻的凶星','只顾精神追求，完全不经营现实','为迎合别人硬改清高，丢了深度优势'],
 enMis:['Taking Hua Gai as an ominous monk/loner star','Pursuing only the inner world while neglecting reality','Forcing away the detachment to fit in, losing the depth edge'],
 cnClose:'华盖给你的是「深」的天赋。不必为不合群自卑，也别让清高变成逃避——把那份悟性扎进一门专业，再给它接上现实的出口，就是最好的活法。',
 enClose:'Hua Gai gives the gift of depth. Do not feel inferior for reserve, nor let aloofness become escape: root that insight in a craft and connect it to the real world—that is its best life.'},

{cat:'fuzhu',slug:'ziwei-tianxing-falu-zilv-daoguang-yiyao-yuan',focus:'天刑星',focusEn:'Tian Xing the punishment star',
 cnT:'紫微斗数天刑星：法律、自律、刀光与医药缘',enT:'Tian Xing in Zi Wei Dou Shu: Law, Self-Discipline, Blade Energy and an Affinity for Medicine',
 cnD:'天刑主法律刑克、纪律、刀光（手术金属伤）与医药玄学缘分，入命者原则性强、能自律、适合法律军警医疗等行业，逢煞忌主官非、手术或硬碰硬的摩擦，宜以专业和规则化解。',
 enD:'Tian Xing governs law and discipline, blade energy (surgery, metal injury) and an affinity for medicine and metaphysics. In Life it gives strong principles and self-discipline, suiting law, enforcement and medicine; with malefics/Ji it means disputes, surgery or hard clashes—best resolved through expertise and rules.',
 cnL:'天刑是一把「规则之刃」：向内是自律和专业底线，向外是法律、竞争和必要的切割，用在专业上是权威，用在情绪上是硬碰硬。',
 enL:'Tian Xing is a blade of rules: inward it is self-discipline and professional bottom line, outward law, competition and necessary cuts. In expertise it is authority; in emotion it is head-on clash.',
 cnA:'有人见天刑就怕官非血光，其实它更是自律和专业之星，很多医生、律师、审计、军警都带天刑，真正要防的是得理不饶人的硬。',
 enA:'People fear Tian Xing as lawsuits and blood, but it is more a discipline and profession star—common in doctors, lawyers, auditors and police; guard against being harshly unforgiving when in the right.',
 cnLog:['天刑为火、主刑克，与法律、纪律、契约、医药、手术、金属刀具相关，也带孤克和突然的切断。','入命主原则性强、自律、能吃苦、讲规矩，利法律、军警、医疗、审计、技术监督等「硬规则」行业。','天刑与天梁、天喜有特殊关系（天刑喜天喜解其孤），会昌曲主以专业文书立身。','逢擎羊、化忌、煞星聚时主官非、合同纠纷、手术或外伤式提醒，宜守规则、留证据、避免硬刚。'],
 enLog:['Tian Xing is fire governing punishment—law, discipline, contracts, medicine, surgery and metal blades, with isolation and sudden cuts.','In Life it gives principles, self-discipline, endurance and rule-following, favoring law, enforcement, medicine, audit and technical supervision.','It has a special tie with Tian Liang and Tian Xi (Tian Xi eases its isolation); with Chang/Qu it builds on professional documents.','Clustered with Yang, Hua Ji or malefics it means disputes, contract trouble, surgery or injury warnings—follow rules, keep evidence, avoid head-on fights.'],
 cnStep:['定位天刑落宫，看规则与切割发生在哪个领域','顺其性走法律、医疗、审计、技术监督等硬规则路线','用自律和专业建立权威，而不是用强硬压人','逢煞忌时重合同、留证据、按流程，不硬碰硬','涉及健康手术以正规医疗为准，命盘只做提醒','大限引动天刑之年，主动处理积弊、做必要的了断'],
 enStep:['Locate Tian Xing to see where rules and cuts apply','Follow it into law, medicine, audit or technical-supervision routes','Build authority through discipline and expertise, not harshness','With malefics/Ji, honor contracts, keep evidence, follow process, avoid clash','For health and surgery defer to formal medicine; the chart only reminds','In years it activates, proactively clear backlogs and make necessary cuts'],
 cnMis:['见天刑只想到血光官非','把原则性变成得理不饶人的硬','逢煞忌还硬刚，把小摩擦弄成大纠纷'],
 enMis:['Seeing only blood and lawsuits in Tian Xing','Turning principles into harsh, unforgiving rigidity','Fighting head-on amid malefics, turning friction into disputes'],
 cnClose:'天刑的本质是「有原则的切割力」。把它用在自律和专业上，你是让人放心的规则守护者；只用在硬碰硬上，它才变成伤己的刃。',
 enClose:'Tian Xing is princed cutting power. Used on self-discipline and expertise you are a trusted guardian of rules; used only for head-on clash it becomes a blade that wounds you too.'},

{cat:'fuzhu',slug:'ziwei-longchi-fengge-caiyi-wenzhong-zhuanye-xingxiang',focus:'龙池凤阁',focusEn:'Long Chi and Feng Ge',
 cnT:'紫微斗数龙池凤阁：才艺、审美与专业形象的一对小吉星',enT:'Long Chi and Feng Ge in Zi Wei Dou Shu: A Pair of Small Stars for Talent, Taste and Professional Image',
 cnD:'龙池凤阁是一对主才艺、审美、精巧手艺与外在形象的辅星，龙池偏内在技艺与聪敏，凤阁偏外在风度与品味，同会主星能给专业和气质加分，力量温和，属锦上添花而非雪中送炭。',
 enD:'Long Chi and Feng Ge are a pair of assistant stars for talent, taste, fine craftsmanship and image. Long Chi leans to inner skill and quickness, Feng Ge to outward bearing and taste; meeting a major star they add polish and presence—gentle, icing-on-the-cake rather than rescue.',
 cnL:'龙池凤阁不决定成败，只决定「做得精不精致、看起来专不专业」，它们让本来就成立的事更有质感和说服力。',
 enL:'They do not decide success but refinement and professional appearance; they give an already-valid matter more texture and persuasiveness.',
 cnA:'有人指望一对小吉星改命，其实它们没有扭转大局的力量，但在靠手艺、审美、形象吃饭的领域，这对星往往是专业感的关键加分项。',
 enA:'People expect small stars to change fate; they cannot turn a whole chart, yet in craft, taste and image fields they are often the key polish that signals professionalism.',
 cnLog:['龙池、凤阁为一对辅星，龙池主聪敏、精巧技艺、口技与内才，凤阁主仪表、审美、装饰、风度与外在品味。','两星同宫或会照主星，增加才艺、气质与专业形象，利设计、工艺、餐饮、美容、艺术、技术专精等领域。','它们力量温和，须依附有力主星和四化才显，属「佐曜」，不能单独撑起一个格局。','逢煞星时审美与表达仍在，但容易在精致处过度纠结，需抓大放小、先完成再完美。'],
 enLog:['Long Chi and Feng Ge are a pair: Long Chi quickness, fine craft, vocal skill and inner talent; Feng Ge bearing, aesthetics, decoration and outward taste.','Sharing or meeting a major star adds talent, presence and professional image, favoring design, craft, food, beauty, art and technical specialization.','Their force is gentle and needs a strong major star and transformations to show—assistants that cannot carry a pattern alone.','With malefics the taste remains but one over-fusses refinement; keep the big picture and finish before perfecting.'],
 cnStep:['定位龙池凤阁落宫，看才艺和审美用在哪个领域','顺着它们走手艺、设计、艺术、技术专精路线','把精致用在能被看见的成果上，而非无谓的细节内耗','依附有力主星，让专业形象为真实能力加分','先保证事情成立，再用这对星提升质感与卖相','大限引动时适合考证、出作品、打造个人专业形象'],
 enStep:['Locate the pair to see where talent and taste apply','Follow them into craft, design, art or technical specialization','Spend refinement on visible results, not pointless detail drain','Attach to a strong major star so professional image backs real ability','Make the matter valid first, then use the pair to lift texture and presentation','When activated, earn credentials, release work and build a professional image'],
 cnMis:['指望小吉星独立改命','只追求精致外表，事情本身没立住','在细节上过度纠结，拖慢交付'],
 enMis:['Expecting small stars to change fate alone','Polishing appearance while the matter itself is not valid','Over-fussing details and slowing delivery'],
 cnClose:'龙池凤阁是「专业感」的微调器。它们不负责让你成功，但当你已有真本事，这对星能让你的成果更精致、形象更可信。',
 enClose:'Long Chi/Feng Ge are fine-tuners of professionalism. They do not make you succeed, but given real ability they make your work more refined and your image more credible.'},

{cat:'fuzhu',slug:'ziwei-tianku-tianxu-qingxu-anhao-kongxugan-zenme-du',focus:'天哭天虚',focusEn:'Tian Ku and Tian Xu',
 cnT:'紫微斗数天哭天虚：情绪暗耗和空虚感从哪来、怎么补',enT:'Tian Ku and Tian Xu in Zi Wei Dou Shu: Where Hidden Emotional Drain and Emptiness Come From and How to Fill Them',
 cnD:'天哭主低落、忧伤与情绪性消耗，天虚主空虚、不实与底气不足，两星本身力量不强，却会放大所在宫的不确定感，逢煞忌或在福德时最明显，解法是建立稳定的内在支撑和现实成果。',
 enD:'Tian Ku governs low mood, sorrow and emotional drain; Tian Xu emptiness, unreality and weak confidence. Neither is strong alone, but each amplifies uncertainty in its palace, most visible with malefics/Ji or in Happiness; the fix is stable inner support and real results.',
 cnL:'天哭天虚不是灾星，而是「情绪漏气点」：它们标出你在哪个领域容易莫名低落、觉得没底，补上真实的积累就好。',
 enL:'They are not disaster stars but emotional leak points, marking where you feel inexplicably low or ungrounded; filling it with real accumulation resolves them.',
 cnA:'有人带着天哭天虚总觉得自己不够好、事情要黄，其实多是情绪放大了不确定性，把注意力从「担心」转到「做出成果」，虚感自然消退。',
 enA:'With these stars people feel not-good-enough and expect failure; emotion amplifies uncertainty, and shifting from worry to producing results dissolves the hollow feeling.',
 cnLog:['天哭属阳金、主哭泣忧伤，天虚属阴土、主空亡虚耗，两星常成对论，是偏情绪层面的小杂曜。','落宫决定「在哪容易没底」：在福德主精神易低落，在命宫主气质偏忧，在财帛官禄主对钱和事业缺乏安全感。','它们多为辅助色彩，须逢煞忌、化忌或与敏感主星同会才明显，单独出现影响有限。','对冲方法不是硬压情绪，而是用可验证的小成果、稳定作息和现实连接，把「虚」变成「实」。'],
 enLog:['Tian Ku is yang metal of sorrow; Tian Xu yin earth of void and drain; often paired, they are small emotion-level stars.','The palace sets where you feel ungrounded: Happiness for low spirits, Life for a melancholic temperament, Wealth/Career for insecurity about money and work.','Mostly auxiliary, they show mainly with malefics/Hua Ji or sensitive major stars; alone their effect is limited.','The counter is not suppressing emotion but turning void into substance with verifiable small wins, stable routine and real-world connection.'],
 cnStep:['定位天哭天虚落宫，找出容易没底的领域','认清这是情绪放大，不是事实判断，先停止灾难化','在该领域用可验证的小成果重建掌控感','在福德时优先稳作息、运动、睡眠和现实社交','逢化忌煞星的阶段降低预期、分步推进，不硬扛情绪','大限走出该星引动后，虚耗感会明显减轻，不必过度解读'],
 enStep:['Locate the stars to find the domain that feels ungrounded','Recognize amplified emotion, not fact; stop catastrophizing','Rebuild control there with verifiable small wins','In Happiness, prioritize routine, exercise, sleep and real connection','In Hua Ji/malefic phases lower expectations and advance stepwise, not white-knuckling','After the decade leaves their activation, the drain eases; do not over-read it'],
 cnMis:['把情绪暗耗当客观事实判断','硬压焦虑不行动，虚感越来越重','忽略落宫，笼统当成性格悲观'],
 enMis:['Taking emotional drain as objective fact','Suppressing anxiety without acting, deepening the void','Ignoring the palace and labeling it generic pessimism'],
 cnClose:'天哭天虚标出的是你心里容易漏气的地方。别和情绪硬拼，去那个领域做出一件件扎实的小事，底气是被真实成果一点点填满的。',
 enClose:'These stars mark where your confidence leaks. Do not fight the emotion; build solid small things in that domain, for grounding is filled one real result at a time.'},
];
