const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'kanpan',slug:'ziwei-diegong-jifa-benming-daxian-liunian-sanceng-diejia',focus:'叠宫技法',focusEn:'palace stacking technique',
 cnT:'紫微斗数叠宫技法：本命、大限、流年三层叠在一起怎么读',enT:'Palace Stacking in Zi Wei Dou Shu: Reading Life, Decade and Year Layers Together',
 cnD:'叠宫是把本命盘、大限盘、流年盘的同名宫位叠加来看：本命是体、大限是十年环境、流年是当年触发，某宫被多层叠到，就代表那段时间该领域成为人生重心，叠宫定「主题」，飞化自化定「怎么演」，是从静态盘走向动态断事的核心技法。',
 enD:'Palace stacking overlays Life, decade and year charts: Life is the base, the decade the ten-year environment, the year the trigger. When a palace is stacked across layers, that domain becomes the life focus then. Stacking sets the theme; flying/self-transformations set how it plays—the core technique from static chart to dynamic reading.',
 cnL:'只看本命盘只学会一半，叠宫告诉你「这十年、这一年，哪件事被推到台前」，本命决定底色，叠宫决定当下重心。',
 enL:'Reading only the natal chart is half the skill; stacking tells you which matter is pushed front-stage in a decade or year. Natal sets the base tone, stacking the current focus.',
 cnA:'有人看流年只盯流年命宫单星，忽略它叠在大限哪个宫、本命哪个宫，结果断事飘；三层一对，当年重心和应事领域才清楚。',
 enA:'Reading a year by its Life star alone, ignoring which decade and natal palace it stacks on, yields vague predictions; aligning three layers clarifies the year\'s focus and the domain it manifests in.',
 cnLog:['本命盘为「体」，是一生不变的结构；大限盘为十年环境，流年盘为当年触发，三层宫位依地支位置重叠即叠宫。','读法：流年命宫落在大限某宫、又叠本命某宫，该宫事象就是当年重心，如叠大限财帛、本命官禄，当年事业与收入是主线。','多层同向叠加（如大限夫妻又叠流年夫妻）主题最强，婚恋事件概率高；叠命宫、迁移则重心回到自己或外出变动。','叠宫只定「大概率主题框架」，具体吉凶还要看该宫星曜、四化飞化与自化，体用结合才完整。'],
 enLog:['The natal chart is the unchanging body; the decade is the ten-year environment; the year the trigger—palaces overlap by branch position, which is stacking.','Method: the year Life palace landing on a decade palace and a natal palace makes that domain the year\'s focus, e.g. stacking decade Wealth and natal Career puts work and income center-stage.','Same-direction multi-stacking (decade Spouse plus year Spouse) is the strongest theme, raising relationship-event odds; stacking Life/Travel returns focus to self or outward change.','Stacking only sets the likely theme frame; concrete fortune still needs that palace\'s stars, flying and self-transformations—body and use together.'],
 cnStep:['先读熟本命十二宫，确定一生结构底色','排出当前大限十二宫，标出十年环境','排出流年十二宫，找到流年命宫地支','逐层对叠：流年命宫叠大限哪宫、本命哪宫','锁定当年主题领域，再看该宫星曜吉凶','用飞化自化判断主题如何展开、应在哪几个月'],
 enStep:['Know the natal twelve palaces and lifelong structure','Lay out the current decade twelve palaces and mark the ten-year environment','Lay out the year twelve and find the year Life palace branch','Stack layer by layer: which decade and natal palace the year Life sits on','Lock the year\'s theme domain, then read that palace\'s stars','Use flying/self-transformations to see how the theme unfolds and in which months'],
 cnMis:['只看流年命宫单星，不做三层对叠','把叠宫主题当注定结果，不看飞化','本命盘没读熟就硬叠，根基全错'],
 enMis:['Reading only the year Life star without three-layer stacking','Taking the stacked theme as fixed result, ignoring transformations','Stacking before knowing the natal chart, on a faulty base'],
 cnClose:'叠宫是让命盘「动起来」的关键。本命定你是谁，大限定你处在哪段环境，流年定今年哪件事浮上台面——三层一对，断事才既有方向又能落到实处。',
 enClose:'Stacking makes the chart move. Natal fixes who you are, decade your environment, year which matter surfaces—align the three and predictions gain both direction and substance.'},

{cat:'kanpan',slug:'ziwei-fuyin-fanyin-daxian-minggong-die-benming',focus:'伏吟反吟',focusEn:'Fu Yin and Fan Yin overlaps',
 cnT:'紫微斗数伏吟反吟：大限命宫叠本命、走到对宫意味着什么',enT:'Fu Yin and Fan Yin: When the Decade Life Overlaps Natal Life or Sits Opposite',
 cnD:'大限命宫走到本命命宫叫伏吟（同宫重叠），主这十年重心回到自己、旧课题重演、成败多由自身性格决定；走到本命命宫对宫叫反吟，主外在冲击与反向牵动、变动来自环境和他人，读懂这两种特殊叠宫能把握十年的内在节奏。',
 enD:'When the decade Life reaches natal Life it is Fu Yin (same-palace overlap): the decade\'s focus returns to self, old lessons replay and success hinges on one\'s own character. Reaching the opposite palace is Fan Yin: external impact and reverse pull, change from environment and others. Reading these two special overlaps grasps the decade\'s inner rhythm.',
 cnL:'伏吟是「向内的十年」，要面对自己重复的模式；反吟是「向外被牵动的十年」，人和环境从对面冲过来，一个修内、一个应外。',
 enL:'Fu Yin is an inward decade facing repeated patterns; Fan Yin an outward-pulled decade where people and environment rush from opposite—one cultivates within, the other responds without.',
 cnA:'有人伏吟十年总觉得老问题反复、原地打转，以为运气差，其实那是专门留给你解决自身课题的时期；硬换赛道不如先改模式。',
 enA:'In a Fu Yin decade people feel old problems repeating and think luck is bad; it is actually the period reserved for solving one\'s own patterns—changing the pattern beats changing tracks.',
 cnLog:['伏吟：大限命宫与本命命宫同宫（地支相同），星曜能量被放大叠加，主回归自我、旧事重演、内省与自我较劲。','伏吟十年成败多源于自身性格与决策，外力贵人有限，吉则深耕突破、煞忌则内耗重复，宜守成或彻底改模式。','反吟：大限命宫走到本命命宫的对宫（冲位），主环境、他人、外部关系反向牵动，变动与冲击多从外来。','反吟十年重在应对外部：迁移、合作、婚姻、对手等「对面的力量」被激活，须以灵活和边界感应对，避免硬碰。'],
 enLog:['Fu Yin: decade Life shares the natal Life palace (same branch), amplifying its stars—return to self, old matters replay, introspection and self-struggle.','In that decade success mostly stems from one\'s own character and choices with limited outside help; auspicious means deep breakthrough, malefics mean repeated drain—conserve or fully change the pattern.','Fan Yin: decade Life sits opposite natal Life (the clash position)—environment, others and external relations pull in reverse, change and impact arriving from outside.','That decade is about responding externally: Travel, partnership, marriage and rivals are activated; meet them with flexibility and boundaries, not head-on clash.'],
 cnStep:['先找本命命宫地支','排大限命宫，判断是否与本命命宫同宫或对宫','伏吟：列出反复出现的老模式，主动修内','伏吟吉时深耕核心能力，煞忌时守成不硬换赛道','反吟：重点管理外部关系、合作与迁移变动','反吟时以柔克刚、守边界，重大决策多缓一拍'],
 enStep:['Find the natal Life branch first','Locate decade Life and judge same-palace versus opposite to natal Life','Fu Yin: list recurring old patterns and cultivate within','In auspicious Fu Yin deepen core ability; in malefic conserve rather than change tracks','Fan Yin: focus on managing external relations, partnership and movement','In Fan Yin overcome softly, hold boundaries and slow major decisions a beat'],
 cnMis:['把伏吟老问题重演当运气差','伏吟时不向内改、只向外逃','反吟时硬碰外部冲击，两败俱伤'],
 enMis:['Taking Fu Yin\'s repeating problems as bad luck','Fleeing outward instead of changing within during Fu Yin','Fighting external impact head-on in Fan Yin, losing both'],
 cnClose:'伏吟反吟是十年节奏的两种特殊开关。伏吟修好自己、把重复的课题终结；反吟接住外部、用灵活代替硬刚，你就握住了这十年的主动权。',
 enClose:'Fu Yin and Fan Yin are two special switches of a decade\'s rhythm. In Fu Yin fix yourself and end repeating lessons; in Fan Yin receive the external and trade clash for flexibility—then you hold the decade\'s initiative.'},

{cat:'kanpan',slug:'ziwei-laiyingong-qintian-sihua-zongyuantou-rumen',focus:'来因宫入门',focusEn:'Lai Yin palace introduction',
 cnT:'紫微斗数来因宫是什么：钦天四化的总源头，一次讲清',enT:'What Is the Lai Yin Palace: The Source of Qin-Tian Four Transformations, Explained',
 cnD:'来因宫是钦天四化（飞星）体系里的关键概念，指出生年天干所在的宫位，是生年四化能量的「来处」，决定这一辈子禄权科忌围绕哪个主题展开，三合派不排来因宫，它属于进阶飞化视角，入门者先理解其定位即可，不必和本命宫位体系混淆。',
 enD:'Lai Yin (cause palace) is key in the Qin-Tian flying-transformations school: the palace holding the birth-year stem, the source from which birth-year Lu/Quan/Ke/Ji energy arises, determining which life theme the four transformations revolve around. The San-He school does not use it; it is an advanced flying view. Beginners need only grasp its role without confusing it with the natal palace system.',
 cnL:'生年四化是「能量」，来因宫是「能量从哪个宫发出来」，同一个化禄，从来因宫是命还是夫妻，主题差很远。',
 enL:'Birth-year transformations are energy; Lai Yin is which palace emits it. The same Hua Lu differs greatly depending on whether it originates from Life or Spouse.',
 cnA:'有人刚入门就硬套来因宫，结果和三合派宫位搅成一团；正确做法是先用熟三方四正和生年四化，再把来因宫当理解「四化为什么落在这条线」的进阶钥匙。',
 enA:'Beginners force Lai Yin in and tangle it with San-He palaces; first master trines and birth-year transformations, then use Lai Yin as the advanced key to why transformations fall along a certain line.',
 cnLog:['来因宫＝出生年天干所在的本命宫位，是生年禄权科忌四化的发轫宫、此生因缘的总源头。','它决定四化的「主题方向」：来因官禄则一生变化多围绕事业，来因夫妻则围绕关系，来因财帛则围绕资源。','来因宫是钦天四化/飞星派概念，强调「气从何来、往哪去」，与三合派重星曜组合是两套语言，不必互相否定。','入门读法：先定来因宫，再追生年四化分别飞入何宫，理解此生「因什么而得禄、因什么而挂碍（忌）」。'],
 enLog:['Lai Yin = the natal palace holding the birth-year stem, the origin of birth-year Lu/Quan/Ke/Ji and the total source of this life\'s causal themes.','It sets the transformations\' thematic direction: from Career, lifelong change revolves around work; from Spouse, relationships; from Wealth, resources.','It belongs to the Qin-Tian/flying school emphasizing where qi comes and goes; the San-He school stresses star combinations—two languages, neither invalidating the other.','Beginner method: fix Lai Yin, then trace where each birth-year transformation flies, understanding what brings gain (Lu) and what binds (Ji) this life.'],
 cnStep:['先排出本命盘并找到生年天干','定位该天干所在宫位，即来因宫','读出来因宫主题（如官禄主事业、夫妻主关系）','追生年禄权科忌分别飞入哪些宫','串起来看：此生从哪个主题出发、在哪些领域得化','把它当进阶视角，基础宫位与三方四正仍要先打牢'],
 enStep:['Cast the natal chart and find the birth-year stem','Locate the palace holding that stem—Lai Yin','Read its theme (Career=work, Spouse=relationship, etc.)','Trace where birth-year Lu/Quan/Ke/Ji each fly','Connect: from which theme this life starts and where transformations land','Treat it as advanced; keep building natal palaces and trines first'],
 cnMis:['入门就把来因宫和三合宫位混为一谈','只记四化落宫，不问能量来处','把钦天和三合两套语言对立起来'],
 enMis:['Confusing Lai Yin with San-He palaces as a beginner','Noting only where transformations land, not their source','Pitting Qin-Tian and San-He languages against each other'],
 cnClose:'来因宫回答的是「这一世的课题从哪起头」。初学不必急着用它断事，先记住：生年四化是从来因宫这个源头流向各宫的，理解了来处，飞化才不是一堆孤立的符号。',
 enClose:'Lai Yin answers where this life\'s themes begin. Beginners need not predict with it at once; remember birth-year transformations flow from this source to each palace—understand the origin and flying transformations stop being isolated symbols.'},

{cat:'kanpan',slug:'ziwei-taisui-rugua-fa-kan-yu-mouren-guanxi',focus:'太岁入卦法',focusEn:'Tai Sui insertion method',
 cnT:'紫微斗数太岁入卦法：看你和某个人关系的另一套方法',enT:'Tai Sui Insertion Method: Another Way to Read Your Relationship With Someone',
 cnD:'太岁入卦是把对方的生年天干（太岁）放进自己命盘，看其天干四化落入自己哪些宫，从而判断两个人在哪些领域有缘、谁付出多、关系卡点在哪，常用于亲密关系、亲子与合伙，是对常规合盘的补充，重在看「对方能量进入你命盘后的走向」。',
 enD:'Tai Sui insertion places the other person\'s birth-year stem (Tai Sui) into your own chart and reads where its four transformations land in your palaces, judging where two people connect, who gives more and where the bond sticks. Used for intimacy, family and partnership, it complements ordinary synastry, focusing on how the other\'s energy moves inside your chart.',
 cnL:'普通合盘是两张盘对照，太岁入卦是把对方「放进你的盘里」看他落在你哪些领域，特别适合看一段关系里谁牵动谁、牵动什么。',
 enL:'Ordinary synastry compares two charts; Tai Sui insertion puts the other inside your chart to see which domains they land in—ideal for who pulls whom and along what.',
 cnA:'有人合盘只比主星合不合，忽略能量互动；太岁入卦能看出「对方化禄入你财帛」还是「化忌入你夫妻」这类具体流向，比笼统的星座式合盘更细。',
 enA:'Synastry that only compares main stars misses energy interaction; insertion shows concrete flows like their Lu into your Wealth versus Ji into your Spouse, finer than vague sign-style matching.',
 cnLog:['取对方生年天干，按其天干起四化（禄权科忌），这组四化即「对方带入你命盘的能量」。','以自己命盘为体，看对方四化落入自己哪些宫：禄入为缘分与给益，权入为推动与掌控，科入为名声与温和，忌入为牵挂与卡点。','关系判断：对方化禄入我命财官迁，多为助益善待；化忌入我六亲或夫妻，主牵挂、纠葛或需磨合之处。','它是合盘的补充视角，仍要结合双方本命、夫妻宫与现实相处，不能单凭一组四化下定论。'],
 enLog:['Take the other\'s birth-year stem and derive its Lu/Quan/Ke/Ji—the energy they bring into your chart.','Using your chart as the body, see where their transformations land: Lu is bond and benefit, Quan drive or control, Ke reputation and gentleness, Ji attachment and sticking point.','Relation reading: their Lu into your Life/Wealth/Career/Travel tends to help and favor; Ji into your family or Spouse means attachment, entanglement or磨合 needed.','It complements synastry and must still combine both natal charts, Spouse palaces and real interaction—never conclude from one set of transformations alone.'],
 cnStep:['先确认对方准确的出生年份天干','以自己命盘为体，起对方天干四化','逐一标注对方禄权科忌落入自己哪些宫','禄权科看缘分与助力领域，忌看牵挂卡点','结合双方夫妻宫与现实互动综合判断','把入卦当补充，不替代本命与常规合盘'],
 enStep:['Confirm the other\'s exact birth-year stem','Using your chart as body, derive their stem\'s four transformations','Mark which of your palaces their Lu/Quan/Ke/Ji enter','Read Lu/Quan/Ke for bond and help, Ji for attachment and sticking points','Combine both Spouse palaces and real interaction','Treat insertion as supplement, not replacement for natal and standard synastry'],
 cnMis:['只比主星合不合，不看能量流向','单凭对方一组四化就给关系判生死','搞错对方生年天干，全盘皆错'],
 enMis:['Comparing only main-star match, ignoring energy flows','Judging a relationship solely from one transformation set','Getting the other\'s birth-year stem wrong, invalidating the whole read'],
 cnClose:'太岁入卦给了你一个独特视角：看对方的能量进入你命盘后流向哪里。它不替代合盘，却能把「这段关系到底在哪个领域成全你、考验你」看得更具体。',
 enClose:'Tai Sui insertion gives a unique view: where the other\'s energy flows inside your chart. It does not replace synastry but makes concrete which domain a relationship fulfills—or tests—you in.'},

{cat:'kanpan',slug:'ziwei-jiagong-liliang-liangling-jiaming-ji-xiong-jia',focus:'夹宫的力量',focusEn:'flanking palaces power',
 cnT:'紫微斗数夹宫：两邻夹命的力量，吉夹和凶夹怎么分辨',enT:'Flanking Palaces in Zi Wei Dou Shu: How the Two Neighbors Shape a Palace, Auspicious vs Hostile Flank',
 cnD:'每个宫都被左右两邻宫「夹」，两邻星曜会对中间宫产生加持或压制：辅弼夹、日月夹、财荫夹为吉夹，增强该宫；羊陀夹、火铃夹、空劫夹、刑忌夹为凶夹，暗中消耗。三方四正之外，夹宫是最容易被新手忽略的第二股力量。',
 enD:'Every palace is flanked by its two neighbors, whose stars support or suppress it: Zuo-You flank, Sun-Moon flank and wealth-shelter flank are auspicious and strengthen it; Yang-Tuo, Fire-Bell, Empty and punishment-Ji flanks are hostile and quietly drain it. Beyond the trine, flanking is the second force beginners most often miss.',
 cnL:'三方四正是「明面上的会照」，夹宫是「贴着身边的影响」，一个宫强不强，不只看本宫和三方，还要看左右两邻是在托它还是拖它。',
 enL:'The trine is visible meeting; flanking is the influence pressed against both sides. A palace\'s strength depends not only on itself and its trine but whether its neighbors lift or drag it.',
 cnA:'有人看本宫星曜不错就断好，结果被两邻羊陀空劫暗夹，好事打折、总觉使不上劲；把夹宫补上，判断才完整。',
 enA:'A good-looking palace is judged well yet quietly flanked by Yang-Tuo or Empty stars, so benefits are discounted and effort feels blocked; adding flanking completes the read.',
 cnLog:['夹宫：某宫左右相邻两宫的星曜对其形成「夹」，力量不如三方会照直接，却长期、贴身、潜移默化。','常见吉夹：左辅右弼夹（助力多）、太阳太阴夹（光明调和）、天府天相「财荫夹印」（稳中有贵）、禄存化禄夹（双禄夹，财气厚）。','常见凶夹：擎羊陀罗夹（禄存必带，主磨）、火星铃星夹（煎熬）、地空地劫夹（破耗落空）、天刑化忌「刑忌夹」（压力是非）。','判断顺序：先看本宫主星、再看三方四正、最后看两邻夹，三者综合，吉夹加分、凶夹减分并给应对。'],
 enLog:['Flanking: a palace\'s two neighbors flank it; less direct than trine meeting but long-term, close and subtle.','Common auspicious flanks: Zuo Fu/You Bi (more help), Sun/Moon (bright harmony), Tian Fu/Tian Xiang wealth-shelter seal (steady nobility), and double-Lu flank (thick wealth qi).','Common hostile flanks: Yang/Tuo (always around Lu Cun, grinding), Fire/Bell (torment), Di Kong/Di Jie (loss and void), Tian Xing/Hua Ji punishment-Ji (pressure and dispute).','Order: read the palace\'s main star, then its trine, finally its two flanks; combine all three, adding for auspicious and subtracting for hostile flanks with responses.'],
 cnStep:['定位要判断的目标宫','先读本宫主星与四化，定基本盘','读三方四正会照，看外部支援','找左右两邻宫星曜，判断是吉夹还是凶夹','吉夹则顺势加码，凶夹则提前防损耗','三层综合下结论，不凭单宫单星断事'],
 enStep:['Locate the target palace','Read its own stars and transformations for the base','Read its trine for external support','Find both neighbors and judge auspicious versus hostile flank','With auspicious flank press the advantage; with hostile, prevent drain early','Conclude from all three layers, never a single palace or star'],
 cnMis:['只看本宫，完全忽略两邻夹','把所有夹都当加分，分不清吉夹凶夹','禄存被羊陀夹却只读好、不读磨'],
 enMis:['Reading only the palace, ignoring both flanks','Treating every flank as helpful, unable to tell them apart','Reading Lu Cun\'s benefit but not its Yang/Tuo grind'],
 cnClose:'夹宫是藏在「身边」的力量。三方四正看大环境，两邻夹看贴身影响——本宫、三方、夹宫三层都过一遍，你对一个宫位强弱的判断才不会漏算那股暗中的推力或阻力。',
 enClose:'Flanking is the power at your side. The trine shows the big environment, neighbors the close influence; check the palace, trine and both flanks and you will not miss the hidden push or drag on its strength.'},

{cat:'kanpan',slug:'ziwei-hui-zhao-chong-he-sanfang-sizheng-liliang-fangxiang',focus:'会照冲合力量方向',focusEn:'meeting shining clashing combining directions',
 cnT:'紫微斗数会、照、冲、合：三方四正里的力量方向一次分清',enT:'Meeting, Shining, Clashing and Combining: Sorting Out Force Directions in the Trine and Opposition',
 cnD:'星曜之间分同宫（合）、三方会（会）、对宫照（照）、对宫冲（冲）几种作用方式：同宫力量最贴身、三方为呼应支援、对宫为迎面牵引，吉凶相同时互相增强、吉凶相反时互相拉扯，分清力量方向，才不会把「会到」和「同宫」混为一谈。',
 enD:'Stars interact by sharing a palace (combine), trine meeting, opposite shining and opposite clashing: sharing is most intimate, trine is echoing support, opposition is head-on pull. Same-nature forces reinforce; opposite-nature forces tug. Sorting directions keeps meeting from being confused with sharing.',
 cnL:'同样一颗吉星，和你同宫、在三方会你、在对宫照你，力度和感觉完全不同；先分清作用方向，再谈吉凶强弱。',
 enL:'The same auspicious star feels entirely different sharing your palace, trining you, or shining from opposite; sort the direction before judging fortune and strength.',
 cnA:'有人把「三方会到禄」直接当成「禄在本宫」，夸大力度；也有人忽略对宫冲的牵引，把冲来的煞当不存在，都是方向没分清。',
 enA:'Trining Lu is mistaken for Lu in the palace, overstating it; others ignore the opposite clash and treat an oncoming malefic as absent—both fail to separate directions.',
 cnLog:['合（同宫）：两星同坐一宫，力量最直接、最贴身，吉凶深度混合，是最强的作用方式。','会（三方会照）：命宫与财帛、官禄、迁移构成三方四正，隔宫呼应，是支援与共振，力度次于同宫。','照与冲：对宫之星永远「照」本宫，吉星来照为荫护，煞忌来照为「冲」，形成迎面的牵引或冲击。','判断要则：同性则叠加增强（吉会吉更吉），异性则牵制（本宫吉、对宫煞则美中不足、需调和），并结合庙旺定强弱。'],
 enLog:['Combine (same palace): two stars share one palace, the most direct and intimate force, deeply blending fortune—the strongest interaction.','Meet (trine): Life with Wealth/Career/Travel forms the trine, echoing across palaces as support and resonance, weaker than sharing.','Shine and clash: the opposite star always shines on the palace; an auspicious star shelters, a malefic/Ji clashes, creating head-on pull or impact.','Rule: same nature stacks (auspicious+auspicious stronger), opposite nature tugs (auspicious palace with opposite malefic is flawed and needs harmonizing); strength also depends on star brilliance.'],
 cnStep:['先锁定要分析的目标宫和星曜','找同宫星，判断最贴身的混合作用','找三方（财官迁等）会照星，看支援力量','找对宫星，分清是吉星来照还是煞忌来冲','判断力量是同向增强还是异向拉扯','结合庙旺落陷给最终强弱与调和建议'],
 enStep:['Fix the target palace and stars','Find same-palace stars for the most intimate blend','Find trine stars (Wealth/Career/Travel) for support','Find the opposite star and tell auspicious shine from malefic clash','Judge whether forces align and strengthen or tug in opposition','Add star brilliance for final strength and harmonizing advice'],
 cnMis:['把三方会到等同于同宫，夸大力度','无视对宫冲，漏掉迎面的牵引冲击','不分同向异向，吉凶一锅端'],
 enMis:['Equating trine meeting with same-palace, overstating force','Ignoring the opposite clash and missing head-on pull','Blending aligned and opposing forces without distinction'],
 cnClose:'「合、会、照、冲」是星曜对话的四种方向。同宫最贴身、三方是呼应、对宫是迎面牵引——把方向和力度分清，你读任何一组星曜组合，才不会夸大或漏算。',
 enClose:'Combine, meet, shine and clash are the four directions of star dialogue: sharing most intimate, trine echoing, opposition head-on. Separate direction and strength and you will neither overstate nor undercount any star combination.'},
];
