const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'gongwei',slug:'ziwei-xiongdigong-shouzu-tongbei-hehuoren',focus:'兄弟宫',focusEn:'Siblings palace',
 cnT:'紫微斗数兄弟宫：不只看手足，还看同辈朋友与事业合伙人',enT:'The Siblings Palace in Zi Wei Dou Shu: Siblings, Peers and Business Partners',
 cnD:'兄弟宫看手足缘分，更看一切「平辈关系」：亲密朋友、同学同事、合伙人与同行。主星吉化主平辈有助、合伙顺遂，煞忌主缘浅、争利或合伙纠纷，是判断能不能合伙、靠不靠同辈的关键宫位。',
 enD:'The Siblings palace reads sibling bonds and, more broadly, all peer relations: close friends, classmates, colleagues, partners and industry peers. Auspicious stars/transformations mean helpful peers and smooth partnership; malefics/Ji mean thin bonds, profit disputes or partnership conflict—key to judging whether to partner and rely on peers.',
 cnL:'兄弟宫是你「平辈生态」的窗口：你和同辈是互相成就还是互相消耗，能不能放心合伙，看的不是感情深浅，而是这宫的星曜组合。',
 enL:'It is the window to your peer ecosystem: whether peers build you up or drain you, and whether partnership is safe, depends on its star combinations, not on affection alone.',
 cnA:'有人只把兄弟宫当兄弟姐妹看，错过它对合伙、团队、人脉的提示；也有人感情好就盲目合伙，兄弟宫煞忌重时往往因利失和。',
 enA:'Some read it only for siblings and miss its guidance on partnership, team and network; others partner blindly from affection, yet heavy malefics here often turn friendship into profit conflict.',
 cnLog:['兄弟宫在六亲轴上看手足，在社会轴上延伸为同辈、密友、同学同事、合伙人和同行圈层。','主星庙旺吉化、见辅弼魁钺，主平辈有情有义、能得兄弟朋友与合伙人之力。','见煞忌空劫，主缘薄、聚少离多、为钱或立场起争执，合伙尤其要白纸黑字、权责清晰。','兄弟宫也是「现金库」田宅的对轴与财帛的田宅（财之库位之一），其状态会间接影响资金调度与周转。'],
 enLog:['On the family axis it reads siblings; on the social axis it extends to peers, close friends, classmates, colleagues, partners and industry circles.','Strong major stars with auspicious transformations and assistants mean loyal, helpful siblings, friends and partners.','With malefics/Ji/empty stars, bonds are thin or distant and disputes arise over money or stance; partnership especially needs written terms and clear roles.','It also sits opposite Property and is one of wealth\'s storage positions, indirectly affecting cash scheduling and turnover.'],
 cnStep:['先看兄弟宫主星庙旺落陷，定平辈关系基调','看吉曜煞忌，判断平辈是助力还是消耗','评估合伙：吉化可合伙但仍立协议，煞忌重宜独立或弱绑定','结合交友宫看整个团队和外部人脉是否齐心','看兄弟宫四化飞星，判断平辈资源流向命主还是外流','大限引动兄弟宫之年，常见合伙、分家、团队变动'],
 enStep:['Read its major star and strength to set the peer-relation tone','Check auspicious versus malefic stars to see whether peers help or drain','For partnership: with auspicious stars partner but still contract; with heavy malefics stay independent or loosely bound','Combine the Friends palace to judge whether the whole team and network align','Read its flying transformations to see whether peer resources flow to you or away','In years it activates, expect partnership, split or team changes'],
 cnMis:['只看亲兄弟姐妹，忽略合伙人和同辈','感情好就盲目合伙，不看煞忌','把兄弟宫当孤立宫位，不连财帛田宅'],
 enMis:['Reading only blood siblings, ignoring partners and peers','Partnering from affection without checking malefics','Treating it in isolation, unlinked to Wealth and Property'],
 cnClose:'兄弟宫真正回答的是：你能不能靠「同辈」这股力量。看懂它，你会知道什么时候该合伙借力、什么时候该保持距离、把规则写在前面。',
 enClose:'The Siblings palace really asks whether you can rely on peers. Read it and you know when to partner for leverage, when to keep distance, and when to set rules first.'},

{cat:'gongwei',slug:'ziwei-fuqigong-shendu-qinmi-guanxi-hudong-moshi',focus:'夫妻宫深度',focusEn:'Spouse palace in depth',
 cnT:'紫微斗数夫妻宫深度：配偶特质之外，更是你在亲密关系里的模式',enT:'The Spouse Palace in Depth: Beyond the Partner\'s Traits, Your Own Pattern in Intimacy',
 cnD:'夫妻宫既看配偶的性格外形与关系状态，也照见你自己在亲密关系中的需求、互动和课题。庙旺吉化主顺遂，煞忌不等于没感情，而是相处多磨、需要经营，对宫官禄还决定感情与事业的能量消长。',
 enD:'The Spouse palace shows the partner\'s character, appearance and the relationship, while mirroring your own needs, interactions and lessons in intimacy. Strong/auspicious means smooth; malefics/Ji do not mean no love but a relationship needing work; the opposite Career palace governs how love and career trade energy.',
 cnL:'夫妻宫是一面双向镜：向外看伴侣，向内看你怎么爱人、怎么被爱，读不懂自己这一半，只按配偶特质找对象容易反复踩坑。',
 enL:'It is a two-way mirror: outward the partner, inward how you love and are loved. Miss your own half and choosing by partner traits alone repeats the same pitfall.',
 cnA:'有人见煞星入夫妻就断言离婚，其实那多表示相处方式需要磨合、历程多波折，而非没有感情；也有人只盯配偶条件，忽略自己在关系里的固定模式。',
 enA:'Malefics in Spouse are read as divorce; they usually mean interaction needs磨合 and a winding path, not absence of love. Others fixate on partner conditions and ignore their own recurring pattern.',
 cnLog:['夫妻宫主配偶特质（星曜）、关系状态（庙陷吉凶）与婚姻早晚，也反映命主本人的亲密关系模式。','星曜定伴侣类型：如太阳主外向担当、天机主聪明多思、贪狼主多才多情，煞曜叠加则相处带摩擦。','煞忌入夫妻主历程多磨、沟通或情绪课题重，不等于无姻缘，晚婚、找对相处方式往往更稳。','夫妻宫对宫是官禄，事业与感情互相牵动；女命田宅、福德也深刻影响婚姻稳定，须整体看。'],
 enLog:['It governs the partner\'s traits (stars), relationship state (strength and auspiciousness), marriage timing, and your own intimacy pattern.','Stars set partner type: Sun outgoing and responsible, Ji clever and thoughtful, Tan Lang versatile and romantic; malefics add friction.','Malefics/Ji mean a winding path with communication or emotional lessons, not no marriage; late marriage and the right interaction style often stabilize it.','Its opposite is Career, so work and love pull on each other; for women, Property and Happiness also deeply shape stability—read as a whole.'],
 cnStep:['先看夫妻宫主星，描述伴侣特质与你被吸引的类型','看庙陷与吉凶，判断关系基调是顺是磨','反推自己：这颗星也对应你在关系里的需求和课题','对宫官禄一起看，评估事业如何牵动感情','煞忌重时优先晚婚、先学沟通，不急于绑定','大限引动夫妻宫之年，常见恋爱、结婚、关系转折'],
 enStep:['Read its major star for the partner\'s traits and your attraction type','Check strength and auspiciousness for a smooth versus grinding tone','Reverse to yourself: the star also maps your needs and lessons','Read opposite Career to assess how work pulls on love','With heavy malefics, favor late marriage and communication skills before binding','In years it activates, expect romance, marriage or a relationship turning point'],
 cnMis:['见煞就断离婚，忽略煞只主多磨','只挑配偶条件，不看自己的关系模式','夫妻宫孤立看，不连官禄福德田宅'],
 enMis:['Reading malefics as divorce when they mean a winding path','Choosing only by partner conditions, ignoring your own pattern','Reading Spouse in isolation from Career/Happiness/Property'],
 cnClose:'夫妻宫写的是「两个人的剧本」，其中一个主角是你。看懂自己在亲密关系里的固定模式，比反复挑对方条件，更能让你走向稳定的关系。',
 enClose:'The Spouse palace writes a two-person script and one lead is you. Understanding your own recurring pattern in intimacy leads to stability more than repeatedly grading a partner\'s conditions.'},

{cat:'gongwei',slug:'ziwei-nupu-jiaoyou-gong-pengyou-xiashu-quanceng-renmai',focus:'奴仆交友宫',focusEn:'Friends and subordinates palace',
 cnT:'紫微斗数奴仆宫（交友宫）：朋友、下属与你的圈层人脉',enT:'The Friends/Subordinates Palace: Friends, Staff and the Network Around You',
 cnD:'奴仆宫（交友宫）看朋友、下属、工友与一切「我对众人」的关系。宫干化禄入命主朋友有情义、下属得力，化忌入命主遇人不淑、被拖累，紫微在此主下属有能但骄，见煞多先助后反，是用人和择友的重要参考。',
 enD:'The Friends/Subordinates palace reads friends, staff, coworkers and all self-to-crowd relations. Its stem flying Lu into Life means loyal friends and capable staff; flying Ji means bad company or being dragged down. Zi Wei here means capable but proud staff; with malefics, help often turns to opposition later—key for hiring and choosing friends.',
 cnL:'兄弟宫看「平级」，奴仆宫看「众人与下属」：你能不能带团队、交什么样的朋友、会不会被人脉拖累，这宫给得最直接。',
 enL:'Siblings reads equals; Friends/Subordinates reads the crowd and those below: whether you can lead a team, what friends you draw, and whether your network drags you—this palace is the most direct.',
 cnA:'有人以为朋友越多越好，奴仆宫化忌或煞重时，广交反成消耗；也有人不懂下属先助后反的信号，用人时栽在「一开始很得力」的人身上。',
 enA:'People think more friends are better, yet with Ji or heavy malefics broad networking drains; others miss the helps-then-turns signal and lose over someone who seemed strong at first.',
 cnLog:['奴仆宫（交友宫）主朋友、下属、员工、合伙外的泛人脉，以及命主的统御力和被拥戴程度。','宫干飞化是关键：化禄化权化科入命财官，主朋友下属有助、能借众人之力；化忌入命主被拖累、背叛或为友破财。','主星定人群质地：紫微天府主交游层次高但需驾驭，机月同梁主温和稳定，杀破狼贪主朋友能干但波动大。','见擎羊陀罗火铃空劫，主关系易翻脸、聚散快或下属先助后反，用人须考核、授权留边界。'],
 enLog:['It governs friends, subordinates, employees and broad network beyond partnership, plus your leadership and popularity.','Its stem transformations are key: Lu/Quan/Ke flying into Life/Wealth/Career mean helpful friends and staff; Ji into Life means being dragged down, betrayed or losing money for friends.','Major stars set the crowd\'s quality: Zi Wei/Tian Fu high-level but needing control; Ji-Yue-Tong-Liang gentle and stable; Sha-Po-Lang/Tan capable but volatile.','With Yang/Tuo/Fire-Bell/Empty stars, bonds turn easily and staff help then oppose; hire with assessment and bounded delegation.'],
 cnStep:['先看奴仆宫主星，判断你周围人群的整体质地','重点看宫干飞化：禄权科入命为助，忌入命为耗','评估统御力：能不能带团队、下属是否稳定长久','煞忌重时精简社交、重质不重量，授权留边界','结合兄弟宫区分平级合伙与下属朋友两类关系','大限引动奴仆宫之年，常见换团队、广结人脉或人际风波'],
 enStep:['Read its major star for the overall quality of people around you','Focus on stem transformations: Lu/Quan/Ke into Life help; Ji into Life drains','Assess leadership: whether you can lead and keep staff stable','With heavy malefics/Ji, prune social life to quality over quantity and delegate with bounds','Combine Siblings to separate equal-partner from subordinate/friend relations','In years it activates, expect team changes, new networks or social friction'],
 cnMis:['以为朋友越多越好，忽略化忌的消耗','只看一开始得力，不防先助后反','把朋友下属混为一谈，不区分两类关系'],
 enMis:['Assuming more friends are better, ignoring Ji\'s drain','Trusting early competence without guarding against later opposition','Blending friends and subordinates without separating the two'],
 cnClose:'奴仆宫教你的是「择人与用人」。看清谁是真助力、谁会拖你下水，圈层贵精不贵多，授权有界，你的人脉才是资产而不是负担。',
 enClose:'This palace teaches choosing and using people. See who truly helps and who drags you down; value a refined network over a big one, delegate with bounds, and your connections become assets, not burdens.'},
];
