const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'faq',slug:'ziwei-konggong-shi-bu-shi-ming-cha-jiedui-xing-fan-cheng-daqi',focus:'空宫是不是命差',focusEn:'is an empty palace a bad fate',
 cnT:'紫微斗数空宫是不是命差？借对宫反成大器的真相',enT:'Is an Empty Palace Bad Fate in Zi Wei Dou Shu? The Truth That Borrowing the Opposite Can Make One Exceptional',
 cnD:'空宫指本宫没有十四主星坐守，只有辅煞杂曜，主本宫力量偏弱、易受环境影响，但绝非命差：空宫要借对宫主星安星、再看两邻夹宫，借得好反而没有固定星性束缚、可塑性极强，很多成就者命宫或关键宫反而是空宫。',
 enD:'An empty palace has none of the fourteen major stars, only assistants and minor stars, so its own force is weaker and more influenced by environment—but it is never bad fate. It borrows the opposite palace\'s major star and reads both neighbors; borrowed well, free of fixed star nature, it is highly malleable, and many high achievers have an empty Life or key palace.',
 cnL:'空宫不是「没有」，而是「留白」：本宫不设主星，就以对宫为主、邻宫为辅，性格和命运反而更灵活、更能因境而变，关键是会借、借对。',
 enL:'Empty is not absent but blank: with no own major star it takes the opposite as primary and neighbors as secondary, making character and fate more flexible and adaptive—the key is borrowing, and borrowing right.',
 cnA:'有人一排盘见命宫空就慌，觉得自己注定平庸，其实空宫借对宫吉星、逢吉化，往往博采众长、在某个领域极有悟性，错在不会借星、只看本宫。',
 enA:'People panic at an empty Life and expect mediocrity; borrowing an auspicious opposite with good transformations often blends strengths and gives rare insight in a field. The error is not borrowing and reading only the empty palace.',
 cnLog:['空宫定义：本宫无十四主星（紫微到七杀）坐守，无论有无辅星煞星，都称空宫，约三分之一的宫位会空，极常见。','空宫特性：本宫主气弱、稳定性低、易受对宫和环境牵引，优点是不被单一星性定型、可塑性与适应力强。','正确三步：一对宫借星安宫（以对宫主星为该宫主星，连同其四化一起借）、二看两邻夹宫是吉夹还是凶夹、三看三方会照补强。','空宫成器：命宫空而对宫庙旺吉化、三方有辅弼魁钺昌曲者，常能兼收并蓄、后发制人；只有空宫又逢对宫落陷煞冲、邻宫凶夹时才偏弱。'],
 enLog:['Definition: no one of the fourteen major stars guards the palace (assistants/malefics notwithstanding)—about a third of palaces are empty, very common.','Traits: weak own qi and low stability, easily pulled by the opposite and environment; the upside is not being fixed to one star nature, with high malleability and adaptability.','Correct three steps: borrow the opposite major star (with its transformations), read both neighbors\' auspicious or hostile flank, then read trine reinforcement.','Exceptional empty: empty Life with a strong, auspicious opposite and assistants in trine often integrates broadly and wins later; it is weak only when the opposite is fallen/clashing and neighbors hostile.'],
 cnStep:['确认空宫是「无主星」而非什么星都没有','第一步永远借对宫主星安十四主星','连对宫四化一起借，不借半套','第二步看左右邻宫是吉夹还是凶夹','第三步看三方四正有无吉星补强','综合判断：借得好是灵活成器，借得差才需补稳'],
 enStep:['Confirm empty means no major star, not no stars at all','Always borrow the opposite major star first','Borrow the opposite transformations too, not half','Second read whether neighbors flank auspiciously or hostilly','Third read trine reinforcement by auspicious stars','Synthesize: borrowed well means flexible strength; borrowed poorly needs stabilizing'],
 cnMis:['见空宫就断定命差','只看本宫不借对宫','借星不借四化、不看夹宫，读不完整'],
 enMis:['Judging bad fate from an empty palace','Reading only the empty palace, not borrowing opposite','Borrowing the star without its transformations or flanking, incomplete'],
 cnClose:'空宫是命盘里的「留白」，不是缺陷。学会借对宫、看夹宫、会三方，你会发现空宫的人少了一层束缚、多了几分弹性，借得好，反而能走出一条别人复制不了的路。',
 enClose:'An empty palace is blank space, not defect. Learn to borrow the opposite, read the flanks and trine, and you find empty-palace people less bound and more adaptive; borrowed well, they walk a path others cannot copy.'},

{cat:'faq',slug:'ziwei-shuang-zhuxing-tonggong-zenme-kan-liang-ke-zhuxing-shui-ting-shui',focus:'双主星同宫谁听谁的',focusEn:'two major stars in one palace',
 cnT:'紫微斗数双主星同宫怎么看：两颗主星到底谁听谁的',enT:'Two Major Stars in One Palace in Zi Wei Dou Shu: Which One Leads',
 cnD:'一个宫同时有两颗主星（如紫微天府、廉贞贪狼、天同天梁）叫双主星同宫，读法不是二选一，而是分主从、看生克：以庙旺有力、化禄权科、更贴合所问领域的那颗为主，另一颗调色，再看两星是相生互补还是互相拉扯，结合煞曜四化定最终性质。',
 enD:'A palace with two major stars (e.g. Zi Wei-Tian Fu, Lian Zhen-Tan Lang, Tian Tong-Tian Liang) is a dual-star palace; reading is not either-or but assigning lead and support: the stronger/brilliant star, the one with Lu/Quan/Ke, or the one most relevant to the question leads while the other tints; then see whether the pair complements or tugs, with malefics and transformations fixing the final nature.',
 cnL:'双主星像两个人搭档：总有一个拍板、一个配合，谁当主角取决于谁更有力（庙旺、得化）、以及你问的是事业还是感情，不能永远固定某颗说了算。',
 enL:'Two stars are partners: one decides, one supports. Who leads depends on who is stronger (brilliant, transformed) and whether you ask about career or relationship—it is never permanently fixed.',
 cnA:'有人背口诀说某组合一定怎样，忽略庙旺和四化会改变主从：同是廉贪，化禄在贪狼和化忌在廉贞，性格走向几乎相反，不看强弱生克就会套错。',
 enA:'Rote formulas fix a combination while brilliance and transformations shift leadership: the same Lian-Tan with Lu on Tan Lang versus Ji on Lian Zhen runs nearly opposite—missing strength and interaction misapplies it.',
 cnLog:['十四主星在十二宫分布，必然出现两星同宫，常见如紫微天府、紫微贪狼、廉贞天府、廉贞贪狼、天同天梁、天机太阴等。','定主从第一看庙旺落陷：庙旺有力者主导，落陷者退为辅助；第二看四化：化禄权科的那颗被放大、话语权上升。','第二看关系：相生互补（如府相、紫府）则一加一大于二，相克拉扯（如廉贪的矛盾、机梁的操心）则呈现内在张力。','第三看所问：问事业以偏事业、偏刚性的星为主，问感情以偏感情、偏柔的星为主，煞星再决定这份组合顺不顺。'],
 enLog:['Distributing fourteen stars across twelve palaces necessarily creates dual-star palaces: Zi Wei-Tian Fu, Zi Wei-Tan Lang, Lian Zhen-Tian Fu, Lian Zhen-Tan Lang, Tong-Liang, Ji-Tai Yin, etc.','Lead first by brilliance: the strong star leads, the fallen supports; second by transformations: the star with Lu/Quan/Ke is amplified and gains sway.','Then relation: complementary pairs (Fu-Xiang, Zi-Fu) exceed the sum, clashing pairs (Lian-Tan contradiction, Ji-Liang worry) show inner tension.','Then the question: for career the career-leaning, firmer star leads; for relationship the softer, affection-leaning star leads; malefics decide whether the combination runs smoothly.'],
 cnStep:['先认出同宫的是哪两颗主星','比较庙旺落陷，先定谁更有力','查四化落在哪颗，被化的那颗升为主导','判断两星相生互补还是相克拉扯','按所问领域（事业/感情/财）选对应主星','叠加煞曜吉曜，给组合的顺畅度下结论'],
 enStep:['Identify the two co-stars','Compare brilliance to find the stronger','Check which star a transformation lands on—the transformed one leads','Judge whether the pair complements or clashes','By the question (career/love/money) pick the relevant lead','Layer malefics/auspicious stars to conclude how smoothly the pair runs'],
 cnMis:['背固定口诀，不看庙旺四化','把双主星当单星，丢掉另一颗的调色','不分所问领域，永远同一颗主导'],
 enMis:['Using fixed formulas without brilliance or transformations','Treating dual stars as one, losing the other\'s tint','Always letting one star lead regardless of the question'],
 cnClose:'双主星不是矛盾，而是更丰富的组合。先比谁有力、再看谁得四化、最后按所问分主从，你就能把「紫微天府」「廉贞贪狼」这类组合，读成有主次、有张力、有层次的真实性格。',
 enClose:'Dual stars are not contradiction but richer combination. Compare strength, see who is transformed, then assign lead by the question—and pairs like Zi Wei-Tian Fu or Lian Zhen-Tan Lang read as real character with hierarchy, tension and nuance.'},

{cat:'faq',slug:'ziwei-ming-hui-yuesuan-yue-bao-ma-suanming-zhengque-shiyong',focus:'命会越算越薄吗',focusEn:'does frequent reading weaken fate',
 cnT:'紫微斗数命会越算越薄吗：算命的正确打开方式',enT:'Does Frequent Zi Wei Dou Shu Reading Weaken Your Fate? The Right Way to Use a Reading',
 cnD:'「命越算越薄」不是玄学事实，而是心理现象：反复算命、只挑坏结果听、把倾向当定数，会让人丧失行动力、越算越焦虑，命盘给出的是「倾向区间×环境×选择」，正确用法是了解倾向、做好规划、把决定权握在自己手里，而不是用算命替代行动。',
 enD:'Fate thinning with frequent reading is not a metaphysical fact but a psychological one: repeatedly reading, hearing only bad results and treating tendency as fixed outcome erodes action and raises anxiety. A chart gives tendency range × environment × choice; the right use is understanding tendency, planning well and keeping decisiveness in your own hands—not replacing action with reading.',
 cnL:'命盘是「天气图」不是「判决书」：它告诉你大概率的风向和要防的坑，怎么走、走不走，永远是你决定，看多了就不动，才是真正的「越算越薄」。',
 enL:'A chart is a weather map, not a verdict: it shows likely winds and pits to avoid; how and whether to move stays yours. Reading so much that you stop acting is the only real thinning.',
 cnA:'有人同一件事找十几个人算、答案稍有不同就慌，反而内耗到错过时机；也有人被一句「化忌」吓得不敢行动，这些都不是命盘的问题，而是使用方式错了。',
 enA:'People ask a dozen readers about one matter and panic at differing answers, draining themselves past the window; others freeze at a single Hua Ji. That is not the chart\'s fault but its misuse.',
 cnLog:['命盘本质是出生时间对应的星曜结构，描述性格倾向、资源分布与概率较高的路径，不写死结果，更不会因「被算」而减少什么。','「越算越薄」的真实机制：选择性接收负面预言、把倾向当定数、反复求证导致决策瘫痪和焦虑，削弱的是行动力而非命运。','正确用法三步：一看结构认识自己的优势与课题，二看大限流年选对节奏和时机，三回到现实做选择、承担结果，命盘只作参考。','避免依赖：同一阶段不为同一件事反复占问，重大决定以现实信息、专业意见和自身目标为主，命盘用于补充视角和风险提示。'],
 enLog:['A chart is the star structure for a birth time, describing temperament, resource distribution and higher-probability paths—not fixed results, and nothing is reduced by being read.','The real thinning mechanism: selectively receiving negative predictions, treating tendency as fixed, and repeated verification causing decision paralysis and anxiety, weakening action, not fate.','Right use in three steps: read structure to know strengths and lessons, read decades/years for rhythm and timing, return to reality to choose and bear results—the chart is reference.','Avoid dependence: don\'t repeatedly ask the same question in one phase; base big decisions on real information, professional advice and your own goals, using the chart to add perspective and risk cues.'],
 cnStep:['明确命盘是倾向和概率，不是定数','同一阶段不为同一件事反复算命','先用命盘认清优势、课题和节奏','重大决定以现实调研和自身目标为主','把命盘当风险提示和规划工具，而非替代行动','看完就回到行动，用结果反馈和调整下一步'],
 enStep:['Be clear the chart is tendency and probability, not fixed outcome','Don\'t repeatedly read the same matter in one phase','Use the chart first to know strengths, lessons and rhythm','Base major decisions on real research and your own goals','Treat the chart as risk cue and planning tool, not action replacement','After reading return to action, using results to feedback and adjust'],
 cnMis:['把倾向当定数，被一句话吓住不行动','同一件事反复找人算，越算越乱','用算命替代现实调研和自己的决定'],
 enMis:['Taking tendency as fixed and freezing on one phrase','Asking many readers about one matter until confused','Replacing real research and your own decision with reading'],
 cnClose:'命不会因为被看懂而变薄，却会因为只看不做而变窄。把紫微斗数当一张帮你认识自己、踩准节奏的地图，看完就上路，决定权和人生，始终在你自己手里。',
 enClose:'Fate does not thin from being understood, but narrows from only looking and never doing. Use Zi Wei Dou Shu as a map to know yourself and time your steps, then hit the road—the decision and the life stay in your hands.'},
];
