const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'liunian',slug:'ziwei-daxian-minggong-zenme-zhao-shinian-zhuzhou',focus:'大限命宫与十年主轴',focusEn:'decade Life palace and ten-year theme',
 cnT:'紫微斗数大限命宫怎么找、十年主轴怎么定',enT:'How to Find the Decade Life Palace and Set a Ten-Year Theme in Zi Wei Dou Shu',
 cnD:'大限（大运）以命宫五行局定起运岁数、按阳男阴女顺行、阴男阳女逆行，每宫十年，走到的那个宫就是这十年的「大限命宫」。定十年主轴的方法是：以大限命宫为新太极重排十二宫，看其主星、四化与三方四正，判断这十年的主题、机会与功课。',
 enD:'The decade starts at an age set by the Life palace\'s five-element phase, advancing clockwise for yang-male/yin-female and counterclockwise otherwise, ten years per palace; the palace reached is the decade Life palace. To set the ten-year theme, treat it as a new taiji, re-lay the twelve palaces, and read its major star, transformations and trine to judge the decade\'s theme, chances and lessons.',
 cnL:'本命是一生剧本，大限是其中一幕：找到大限命宫，就知道这十年人生舞台搭在哪个领域、灯光打在什么主题上。',
 enL:'The natal chart is the whole script, a decade one act: finding the decade Life palace shows which domain the stage is set on and what theme the spotlight hits for ten years.',
 cnA:'有人把大限和流年混为一谈，拿一年的星断十年；也有人不重排大限十二宫，只看走到的那颗星，结果读不出这十年事业、感情、财的整体走向。',
 enA:'People confuse decade with year and read ten years from one-year stars; others read only the arrived star without re-laying the decade twelve, missing the decade\'s overall work, relationship and wealth direction.',
 cnLog:['起运：由命宫五行局（水二、木三、金四、土五、火六）定起运岁数，阳男阴女顺行、阴男阳女逆行，逐宫走十年。','大限命宫＝本十年走到的本命宫位，以它为新命宫，按固定顺序重排大限的兄弟、夫妻、财帛等十二宫。','定主轴：看大限命宫主星庙旺定基调，看大限天干四化（尤其化禄化忌飞入本命何宫）定十年得失方向。','再合本命：大限吉而本命强则乘势而起，大限煞忌冲本命弱宫则这十年以守成、修课题为主，不可只看一层。'],
 enLog:['Start age comes from the Life palace\'s five-element phase (water-2, wood-3, metal-4, earth-5, fire-6); yang-male/yin-female advance clockwise, others counterclockwise, ten years per palace.','The decade Life palace is the natal palace reached; use it as the new Life and re-lay the decade twelve (Siblings, Spouse, Wealth, etc.) in fixed order.','Set the theme: its major star and brilliance set tone; the decade stem\'s transformations (esp. Lu and Ji flying into natal palaces) set ten-year gain/loss direction.','Combine with natal: an auspicious decade over a strong natal rises; a malefic/Ji decade clashing a weak natal palace calls for conservation and lessons—never read one layer alone.'],
 cnStep:['先确定命宫五行局和起运岁数、顺逆行方向','按年龄找到当前十年走到的大限命宫','以它为新太极，重排大限十二宫','读大限命宫主星庙旺，定十年基调','起大限天干四化，看禄忌飞入本命哪些宫','本命×大限合参，写出这十年的主题、机会与功课'],
 enStep:['Determine the Life five-element phase, start age and direction','By age find the natal palace the current decade reaches','Use it as new taiji and re-lay the decade twelve palaces','Read its major star and brilliance for the decade tone','Derive the decade stem transformations, seeing where Lu/Ji fly in the natal chart','Combine natal and decade to state the ten-year theme, chances and lessons'],
 cnMis:['拿流年星去断十年','走到哪宫只看单星，不重排十二宫','只看大限不看本命，失去根基'],
 enMis:['Reading ten years from yearly stars','Reading only the arrived star without re-laying the twelve','Reading the decade alone without the natal base'],
 cnClose:'大限是把一生切成一段段的「十年主题」。先找对大限命宫、以它重排十二宫、再看四化飞星，你就能清楚知道：这十年该主攻什么、守住什么、修哪门功课。',
 enClose:'A decade slices life into ten-year themes. Find the decade Life palace, re-lay the twelve around it, then read flying transformations—and you know clearly what to pursue, protect and learn these ten years.'},

{cat:'liunian',slug:'ziwei-liunian-zenme-kan-jixiong-liunian-shiergong-zhongpai',focus:'流年吉凶与流年十二宫重排',focusEn:'yearly fortune and re-laid year palaces',
 cnT:'紫微斗数流年怎么看吉凶：流年十二宫重排后的完整读法',enT:'How to Read a Year\'s Fortune in Zi Wei Dou Shu: The Full Method After Re-laying the Year Twelve Palaces',
 cnD:'流年以当年地支定流年命宫，再以它为太极重排流年十二宫，叠在本命和大限之上。看一年吉凶要三层合参：大限给十年背景、流年定当年事件，流年命宫主星与流年四化（禄权科忌飞入哪宫）定这一年的得失与应期，再用流月落到具体时段。',
 enD:'The year Life palace is set by that year\'s branch, then its twelve palaces re-laid as a taiji stacked over natal and decade. Reading a year needs three layers: the decade gives ten-year background, the year sets events; the year Life star and year transformations (where Lu/Quan/Ke/Ji fly) set that year\'s gains and timing, with months pinning the period.',
 cnL:'大限回答「这十年大概如何」，流年回答「今年具体发生什么」，流年十二宫一重排，今年的事业、感情、财分别由哪个宫管就清楚了。',
 enL:'The decade answers the rough ten years; the year answers what specifically happens this year. Re-lay the year twelve and it becomes clear which palace governs this year\'s work, love and money.',
 cnA:'有人只看生肖年运势那种泛泛说法，不重排流年盘；也有人只看流年命宫，忽略流年四化和大限背景，断事要么太泛、要么没有层次。',
 enA:'Some rely on vague zodiac-year fortune without re-laying the year chart; others read only the year Life palace, ignoring year transformations and decade background—too vague or lacking layers.',
 cnLog:['流年命宫：以当年太岁地支所在宫位为流年命宫，顺排流年十二宫，形成该年独立的「小命盘」。','三层关系：本命为体、大限为十年环境、流年为当年触发，流年宫位叠到大限、本命同名宫上主题最强。','定吉凶：看流年命宫主星庙旺与吉凶，再起流年天干四化，化禄所入为今年的得、化忌所入为今年的卡点。','定应期：流年定到年，再用流月命宫逐月推，吉化集中的月份主动推进，忌煞集中的月份守成避锋。'],
 enLog:['Year Life palace: the palace on that year\'s Tai Sui branch becomes year Life; lay the year twelve in order to form that year\'s small chart.','Three layers: natal body, decade environment, year trigger; a year palace stacked on same-named decade/natal palaces has the strongest theme.','Fortune: read the year Life star and brilliance, derive year-stem transformations—where Lu enters is this year\'s gain, where Ji enters this year\'s sticking point.','Timing: the year sets the year, month Life palaces refine by month; push in months clustered with auspicious transformations, conserve in Ji/malefic months.'],
 cnStep:['用当年地支定位流年命宫','以它重排流年十二宫','叠到大限与本命盘上，找主题重叠最强的领域','读流年命宫主星与三方吉凶','起流年四化，定今年的得（禄）与卡点（忌）','用流月把关键事件落到具体月份，定进退节奏'],
 enStep:['Locate the year Life palace by that year\'s branch','Re-lay the year twelve palaces around it','Stack on decade and natal to find the strongest overlapping theme','Read the year Life star and trine fortune','Derive year transformations to set this year\'s gain (Lu) and sticking point (Ji)','Use month palaces to pin key events and set push/conserve rhythm'],
 cnMis:['只看生肖年运势，不排流年盘','只看流年命宫，不看流年四化','脱离大限背景单断流年，没有层次'],
 enMis:['Relying on zodiac-year fortune, not casting the year chart','Reading only year Life, ignoring year transformations','Judging the year without decade background, lacking layers'],
 cnClose:'流年是「今年这一局」。定位流年命宫、重排十二宫、看流年四化、再用流月定时点，你就能把一年的机会和卡点，从笼统的运势变成可安排的节奏。',
 enClose:'The year is this round. Locate year Life, re-lay the twelve, read year transformations and time events by month—and you turn vague yearly fortune into a schedulable rhythm of chances and sticking points.'},

{cat:'liunian',slug:'ziwei-huan-daxian-jiaojie-nian-wei-shenme-dongdang',focus:'换大限交接年',focusEn:'decade transition years',
 cnT:'紫微斗数换大限的交接年，为什么最容易动荡',enT:'Why Decade Transition Years Are the Most Turbulent in Zi Wei Dou Shu',
 cnD:'两个大限交界前后一两年，旧十年的能量在收、新十年的能量在起，两套大限四化与重心同时作用，常见换工作、搬家、分手、转型、身份转变等大变动，这不是运气差，而是「换挡期」的正常震荡，提前看懂交接结构就能主动布局、平稳过渡。',
 enD:'A year or two around a decade boundary, the old ten-year energy closes as the new opens, with both sets of decade transformations and focus acting at once—job change, moving, breakup, transformation and identity shifts are common. This is not bad luck but the normal shake of a gear-change; reading the transition structure early lets you plan and cross smoothly.',
 cnL:'大限交接像换轨道：旧车还没完全停、新车已经启动，人在两套主题之间，自然会觉得拉扯、不稳、想改变，这是结构性的而不是偶然。',
 enL:'A decade transition is switching tracks: the old train has not fully stopped as the new starts; between two themes one naturally feels pulled, unstable and ready to change—structural, not accidental.',
 cnA:'有人在交接年把正常的换挡震荡当人生失败，慌乱中做重大决定；也有人完全无感、硬按旧模式走，结果被新旧能量撕扯。看懂交接，反而能把动荡变成升级的窗口。',
 enA:'In transition years people take normal gear-change shake as failure and make panicked big decisions, or feel nothing and force the old pattern, torn by both energies. Understanding transition turns turbulence into an upgrade window.',
 cnLog:['大限每十年一换，交界点由五行局起运岁数逐宫推算，交接前后约一到两年处于「新旧并置」状态。','震荡来源：旧大限四化的主题在收尾、新大限四化的主题在启动，两个大限命宫主星往往性质不同，方向感冲突。','典型应事：换工作或行业、搬迁、关系的合与分、财务结构调整、身份角色转变（结婚、为人父母、退休等）。','应对原则：交接年重大决策多留缓冲、先立后破，借新大限主轴提前布局，不在旧能量最乱时孤注一掷。'],
 enLog:['Decades change every ten years, boundaries computed from the five-element start age palace by palace; about one to two years around it sit in old-and-new overlap.','Shake source: old decade transformations close their theme as new ones open, and the two decade Life stars often differ in nature, conflicting in direction.','Typical events: job/industry change, moving, relationship start/end, financial restructuring, role shifts (marriage, parenthood, retirement).','Response: in transition years buffer big decisions, build the new before breaking the old, lay groundwork by the new decade theme, and never go all-in amid the old energy\'s mess.'],
 cnStep:['用五行局起运岁数算出自己每个大限的交界年份','标出当前所处阶段：旧限收尾、正交接、还是新限已稳','交接前后降低重大决策的冲动，先立后破','提前读新大限命宫与四化，判断下一个十年方向','在旧限收尾期清理包袱、储备资源和能力','新限稳定后再全力切换，把震荡变成升级窗口'],
 enStep:['Use the five-element start age to compute every decade boundary year','Mark your phase: old closing, mid-transition, or new stabilized','Around transition reduce impulsive big decisions; build new before breaking old','Read the new decade Life and transformations early for the next ten-year direction','In the old decade\'s close, clear burdens and stock resources and skills','Switch fully once the new decade stabilizes, turning shake into an upgrade window'],
 cnMis:['把换挡震荡当人生失败而慌乱决策','完全无视交接、硬按旧模式走','新限未稳就孤注一掷全部切换'],
 enMis:['Taking gear-change shake as failure and deciding in panic','Ignoring transition and forcing the old pattern','Going all-in before the new decade stabilizes'],
 cnClose:'换大限的动荡不是意外，而是人生在「换挡」。算清交接年份、提前读懂下一个十年的方向、先立后破，你就能把最不稳的那两年，过成升级和转型最宝贵的窗口。',
 enClose:'Decade-transition turbulence is not accident but life changing gears. Compute boundary years, read the next decade early and build new before breaking old—and you turn the shakiest two years into your most valuable window to upgrade and transform.'},

{cat:'yingyong',slug:'ziwei-kan-shifou-shihe-kaogong-tizhi-nei-fazhan',focus:'考公与体制内发展',focusEn:'civil service and institutional career fit',
 cnT:'紫微斗数怎么看适不适合考公、走体制内路线',enT:'How Zi Wei Dou Shu Shows Whether You Suit Civil Service and an Institutional Career',
 cnD:'看考公与体制内发展，核心看官禄宫、命宫与迁移，机月同梁、天府天相、太阳天梁等稳定星系最适配，逢文昌文曲化科、天魁天钺利考试与贵人，再看父母宫（文书功名）与大限流年科甲运，多宫同吉才是真正「上岸」的信号。',
 enD:'For civil-service fit, focus on Career, Life and Travel: stable galaxies like Ji-Yue-Tong-Liang, Tian Fu/Tian Xiang and Sun/Tian Liang suit best; Chang/Qu/Hua Ke and Kui/Yue favor exams and mentors. Add the Parents palace (documents and scholarly repute) and the decade/year scholarly luck—multiple palaces auspicious together is the real signal of success.',
 cnL:'适不适合体制，不是单看一颗星：命宫定性格稳不稳、官禄定职业形态、父母宫定文书考运、大限定时机，四层都顺，考公才是顺势而为。',
 enL:'Institutional fit is never one star: Life sets temperament, Career the work form, Parents the document/exam luck, the decade the timing—four aligned layers make civil service a natural move.',
 cnA:'有人命带杀破狼却硬考公求稳，上岸后也痛苦；也有人明明是机月同梁的稳定格，却被「外面赚得多」带偏。看清适配度，比盲目跟风考公重要得多。',
 enA:'A Sha-Po-Lang chart forcing civil service is miserable even after passing; a clear Ji-Yue-Tong-Liang stable chart can be led astray by outside money. Fit matters far more than following the crowd.',
 cnLog:['性格层（命宫、迁移）：机月同梁、天府天相、太阳天梁、天同太阴等稳定、守序、善协调的星系最适配体制。','事业层（官禄宫）：官禄主星稳健、逢禄权科、不逢煞忌冲破，主适合层级清晰、按资积累的组织。','考试层（父母宫为文书功名宫＋昌曲化科魁钺）：多科名星、化科引动，考试、面试、政审、评职称更顺。','时机层（大限流年）：大限官禄吉、流年走科甲（化科、昌曲、魁钺引动）时报考，命中率最高，煞忌重的年份宜蓄力。'],
 enLog:['Temperament (Life/Travel): stable, orderly, coordinating galaxies—Ji-Yue-Tong-Liang, Tian Fu/Tian Xiang, Sun/Tian Liang, Tong/Tai Yin—best fit institutions.','Career (Career palace): a steady major star with Lu/Quan/Ke and no malefic/Ji break suits clear-hierarchy, seniority-based organizations.','Exam layer (Parents as documents/repute palace plus Chang/Qu/Hua Ke/Kui/Yue): many scholarly stars and activated Ke smooth exams, interviews, vetting and title evaluation.','Timing (decade/year): apply when decade Career is auspicious and the year carries scholarly activation (Ke, Chang/Qu, Kui/Yue); heavy malefic/Ji years are for preparation.'],
 cnStep:['先看命宫迁移，判断性格是否适配稳定有序环境','看官禄宫主星与四化，判断职业形态是否偏体制','查父母宫与昌曲化科魁钺，评估考试文书运','用大限官禄和流年科甲定报考的最佳窗口','稳定格则系统备考、走长期资历路线','开创格若仍要考，选体制内竞争性、开拓性岗位'],
 enStep:['Read Life/Travel for fit with a stable, orderly environment','Read Career star and transformations for institutional work form','Check Parents and Chang/Qu/Ke/Kui/Yue for exam and document luck','Use decade Career and year scholarly activation to pick the best window','Stable charts prepare systematically and take the long seniority route','Pioneering charts that still enter should choose competitive, pioneering institutional roles'],
 cnMis:['单看一颗星就断定能不能上岸','杀破狼硬求稳、稳定格盲目跟风下海','只看原盘不看大限流年，错过报考窗口'],
 enMis:['Judging exam success from one star','Sha-Po-Lang forcing stability, stable charts blindly diving into business','Reading only the natal chart and missing the exam window'],
 cnClose:'考公适不适合，是「性格＋职业形态＋考试运＋时机」四层合参。稳定星系逢科名、再踩对大限流年的窗口，你的努力才是顺水推舟，而不是逆水行舟。',
 enClose:'Civil-service fit combines temperament, work form, exam luck and timing. Stable galaxies with scholarly stars and the right decade/year window make effort downstream rather than upstream.'},

{cat:'yingyong',slug:'ziwei-kaoshi-yun-xueye-ming-fuguan-changqu-huake',focus:'考试运与学业',focusEn:'exam and study luck',
 cnT:'紫微斗数怎么看考试运和学业：命宫、官禄、父母宫与昌曲化科',enT:'How Zi Wei Dou Shu Reads Exam and Study Luck: Life, Career, Parents Palaces with Chang-Qu and Hua Ke',
 cnD:'看学业考试以命宫定学习素质、官禄宫（学业为事业之体）定用功方向、父母宫为文书功名宫看文凭与考官缘，再看文昌文曲、化科、天魁天钺等科名星，最后用大限流年判断哪次考试最有机会，是一套「素质—用功—功名—时机」的完整链条。',
 enD:'For study and exams, Life sets learning quality, Career (study as the body of career) sets effort direction, Parents as documents/repute palace shows diploma and examiner rapport, then Chang/Qu, Hua Ke and Kui/Yue scholarly stars, and finally decade/year for which exam has the best chance—a full chain of quality, effort, repute and timing.',
 cnL:'考试不是只靠聪明：命宫看底子、官禄看肯不肯持续投入、父母宫看文书和临场功名、科名星看发挥、大限流年定时机，缺一环都可能临场掉链子。',
 enL:'Exams are not raw intelligence: Life is base, Career is sustained effort, Parents is documents and on-site repute, scholarly stars performance, decade/year timing—one missing link can cause an on-site stumble.',
 cnA:'有人命宫聪明却官禄不化科、父母宫逢煞，平时强一考就砸；也有人底子一般但赶上科甲大限、方法对，反而超常发挥，关键在看懂自己的强弱环。',
 enA:'Bright Life without Career Ke or with malefic Parents means strong in practice, poor in exams; an average base in a scholarly decade with right method can over-perform—the key is knowing your strong and weak links.',
 cnLog:['命宫：主学习能力与综合素质，主星庙旺、见昌曲化科主头脑清楚、记忆力理解力佳。','官禄宫：学业为「学生的事业」，官禄化禄学得起劲、化权肯下苦功、化科按部就班有章法，化忌则易卡壳、厌学或方法不对。','父母宫：古为文书宫、功名宫，主文凭、考试、老师与学校缘分，吉则临场顺、得老师赏识，逢煞忌则易粗心、紧张、与标准答法不合。','科名星与时机：文昌文曲主科甲与文书、化科主名声、魁钺主贵人，逢大限流年引动时报考、考证、评职称最有利。'],
 enLog:['Life: learning ability and overall quality; a strong star with Chang/Qu/Ke means a clear mind, good memory and comprehension.','Career: study is a student\'s career; Career Lu makes study engaging, Quan means willing hard work, Ke methodical order, Ji means blocks, aversion or wrong method.','Parents: anciently the documents/repute palace for diploma, exams, teachers and school; auspicious means smooth performance and teacher favor, malefics/Ji mean carelessness, nerves or mismatch with standard answers.','Scholarly stars and timing: Chang/Qu govern exams and documents, Ke reputation, Kui/Yue mentors; applying, certifying or evaluating titles when a decade/year activates them is most favorable.'],
 cnStep:['先看命宫与昌曲，评估学习底子和理解记忆力','看官禄四化，判断用功状态和学习方法对不对','看父母宫，评估文凭缘、考场发挥和老师缘','找化科、魁钺被引动的大限流年，定考试窗口','弱环补强：父母宫弱就练规范答题、控紧张','大限流年逢煞忌的考试提前更充分准备，不裸考'],
 enStep:['Read Life and Chang/Qu for learning base, comprehension and memory','Read Career transformations for effort state and method','Read Parents for diploma luck, exam performance and teacher rapport','Find decades/years activating Ke and Kui/Yue to set exam windows','Strengthen weak links: weak Parents means practicing standard answers and controlling nerves','For exams in malefic/Ji periods, prepare more thoroughly—never sit unprepared'],
 cnMis:['只看聪不聪明，忽略用功和考场发挥','把父母宫只当父母关系，漏掉文书功名','不看大限流年，关键考试选错年份'],
 enMis:['Looking only at intelligence, ignoring effort and performance','Treating Parents only as family relations, missing documents/repute','Ignoring decade/year and choosing the wrong year for a key exam'],
 cnClose:'考试运是一条链子：底子、用功、文书功名、科名星、时机。看清自己哪一环强、哪一环弱，再踩对化科引动的年份，努力才会稳定地变成成绩。',
 enClose:'Exam luck is a chain: base, effort, documents/repute, scholarly stars, timing. Know your strong and weak links and hit a Ke-activated year, and effort reliably becomes results.'},

{cat:'yingyong',slug:'ziwei-shifou-shihe-chuangye-shapolang-guanlu-caibo-daxian',focus:'是否适合创业',focusEn:'entrepreneurship fit',
 cnT:'紫微斗数怎么看适不适合创业：杀破狼、官禄财帛与大限时机',enT:'How Zi Wei Dou Shu Judges Entrepreneurship Fit: Sha-Po-Lang, Career/Wealth Palaces and Decade Timing',
 cnD:'创业适配看命宫有没有开创承受力（杀破狼、紫微武曲贪狼等偏开创）、官禄宫是否适合自立而非受雇、财帛与田宅有没有承接资金的库、迁移是否利向外开拓，更关键的是大限是否走到「可创业」的发动期，原盘适配＋大限引动，才是出手窗口。',
 enD:'Entrepreneurship fit depends on Life\'s pioneering resilience (Sha-Po-Lang, Zi Wei/Wu Qu/Tan Lang lean pioneering), whether Career suits independence over employment, whether Wealth/Property hold a fund-receiving vault, and whether Travel favors outward expansion. Crucially, whether the decade reaches a launch phase: natal fit plus decade activation is the window to act.',
 cnL:'适不适合创业是「性格＋事业形态＋财库＋时机」：原盘决定你是不是那块料，大限决定现在是不是时候，两者缺一，硬创业多半交学费。',
 enL:'Entrepreneurship fit is temperament + work form + treasury + timing: the natal chart decides if you are the material, the decade whether now is the time; missing either means paying tuition.',
 cnA:'有人原盘明明是机月同梁的受雇稳定格，却在煞忌大限跟风创业，屡创屡败；也有人是杀破狼的料，却没等发动大限、在低谷期硬上，同样艰难。',
 enA:'A natal Ji-Yue-Tong-Liang employee chart starting a business in a malefic decade fails repeatedly; a Sha-Po-Lang type launching in a low decade before activation struggles just as much.',
 cnLog:['性格层：杀破狼、紫微、武曲、贪狼等开创型主星坐命，敢冒险、能承压、善破局，较适合创业；机月同梁、府相则更利组织内发展。','官禄宫：逢化权化禄、主星强旺，主能自立掌舵；煞忌重、化忌入官禄则资金链、团队或方向易出问题，不宜贸然下海。','财帛田宅：创业要有「库」承接现金流，田宅财帛稳、见禄存化禄者抗风险力强，空劫夹财则易资金断链。','时机层（最关键）：大限命宫走开创格、大限官禄财帛化禄权引动时为创业窗口；煞忌大限宜先打工积累，不宜逆势开局。'],
 enLog:['Temperament: pioneering Life stars—Sha-Po-Lang, Zi Wei, Wu Qu, Tan Lang—dare risk, bear pressure and break ground, suiting startups; Ji-Yue-Tong-Liang and Fu-Xiang favor organizations.','Career: Quan/Lu with a strong star means steering independently; heavy malefics or Ji in Career means cash-flow, team or direction problems—don\'t dive in rashly.','Wealth/Property: startups need a vault for cash flow; stable Wealth/Property with Lu Cun/Hua Lu resists risk, empty stars flanking wealth mean broken cash chains.','Timing (key): launch when the decade Life takes a pioneering pattern and decade Career/Wealth activate Lu/Quan; malefic/Ji decades are for employment and accumulation, not against-trend launches.'],
 cnStep:['先看命宫主星，判断开创承受力','看官禄是否利自立、有无化权化禄引动','查财帛田宅，评估资金库和抗风险力','看迁移，判断是否利向外开拓市场','用大限找真正的创业发动窗口','适配不足时选副业、内部创业或合伙等中间形态'],
 enStep:['Read the Life star for pioneering resilience','See whether Career favors independence with activated Quan/Lu','Check Wealth/Property for the fund vault and risk resistance','Read Travel for outward market expansion','Use the decade to find the real launch window','When fit is partial, choose side business, intrapreneurship or partnership'],
 cnMis:['以为人人都适合创业','只看原盘不看大限，在低谷期硬上','财库逢空劫还高杠杆开局'],
 enMis:['Assuming entrepreneurship suits everyone','Reading natal only and launching in a low decade','Starting leveraged with an empty-star treasury'],
 cnClose:'创业是「对的人在对的时候做对的事」。原盘有开创格、官禄财帛有库、再踩中大限的发动窗口，你的冒险才是胜算；否则先蓄力，比硬交学费聪明。',
 enClose:'Entrepreneurship is the right person doing the right thing at the right time. A pioneering natal chart, a Career/Wealth vault and a decade launch window turn risk into odds; otherwise storing strength first beats paying tuition.'},

{cat:'yingyong',slug:'ziwei-tiaocao-shiji-zenme-kan-guanlu-qianyi-daxian-liunian',focus:'跳槽时机',focusEn:'job-change timing',
 cnT:'紫微斗数跳槽时机怎么看：官禄、迁移与大限流年的信号',enT:'How to Read Job-Change Timing in Zi Wei Dou Shu: Signals from Career, Travel and Decade/Year',
 cnD:'跳槽看官禄宫（工作本身）、迁移宫（向外的机会与变动）、命宫与福德（内心想不想动），官禄或迁移被化禄化权引动、且大限流年走到变动结构时是好窗口；官禄化忌、迁移逢煞时动反而更差，核心是分清「该跳」和「想逃」，并选在能量向上时动。',
 enD:'Job change reads Career (the work itself), Travel (outward chance and movement), and Life/Happiness (inner urge). When Career or Travel is activated by Lu/Quan and the decade/year enters a movement structure it is a good window; moving amid Career Ji or malefic Travel is worse. The core is separating should-leave from want-to-escape and moving when energy rises.',
 cnL:'跳槽不是一不爽就走：官禄看现有工作和下一份的质地，迁移看外部机会开不开，大限流年定什么时候动，三处都顺才是「跳得更高」。',
 enL:'Don\'t leave at every grievance: Career shows current and next job quality, Travel whether outside chances open, decade/year when to move—all three aligned means jumping higher.',
 cnA:'有人官禄化忌、迁移也逢煞时赌气裸辞，结果越跳越差；也有人明明大限引动迁移化禄、外部机会极好，却因怕变不敢动，错过窗口。',
 enA:'Some quit in anger amid Career Ji and malefic Travel, each move worse; others freeze when a decade activates Travel Lu with excellent outside chances and miss the window.',
 cnLog:['官禄宫：看工作状态与职业形态，化禄化权主有新的职位与主导机会，化忌主现职瓶颈或下一份也易出问题。','迁移宫：主外部机会、外出与变动，迁移化禄化权、逢魁钺主向外有贵人好平台，逢煞忌主外出受阻、变动不顺。','命宫福德：看内心动机，因成长与机会而跳（吉）和因逃避情绪而跳（多凶）要分清，后者换地方常重演旧问题。','时机：大限官禄迁移走吉、流年再引动禄权时谈offer、跳槽最有利；官禄化忌或流年煞重时宜蛰伏积累、骑驴找马。'],
 enLog:['Career: work state and form; Lu/Quan mean new posts and leading chances, Ji means a current bottleneck or problems in the next job too.','Travel: outside chance, going out and change; Travel Lu/Quan with Kui/Yue means mentors and good platforms outside, malefics/Ji mean blocked movement.','Life/Happiness: inner motive—leaving for growth and chance (auspicious) versus escaping emotion (often inauspicious); the latter repeats old problems elsewhere.','Timing: negotiate offers and move when decade Career/Travel is auspicious and the year activates Lu/Quan; amid Career Ji or a heavy-malefic year, lie low and job-hunt while employed.'],
 cnStep:['先看官禄宫，判断现职瓶颈是暂时还是结构性','看迁移宫，评估外部有没有真机会和贵人','向内核对动机：为成长跳还是为逃避跳','用大限官禄迁移判断这十年适不适合动','用流年禄权引动定具体跳槽窗口','煞忌年份不裸辞，骑驴找马、备好下家再动'],
 enStep:['Read Career to tell a temporary from structural bottleneck','Read Travel to assess real outside chances and mentors','Check inner motive: growth versus escape','Use decade Career/Travel to judge whether to move these ten years','Use year Lu/Quan activation to set the concrete window','In malefic/Ji years don\'t quit bare; job-hunt while employed and line up the next role'],
 cnMis:['一不爽就裸辞，不看官禄迁移吉凶','为逃避而跳，换地方重演问题','大限引动好机会却因怕变不敢动'],
 enMis:['Quitting bare at every grievance, ignoring Career/Travel fortune','Leaving to escape, repeating problems elsewhere','Freezing when a decade opens a good chance, fearing change'],
 cnClose:'跳槽是一次需要踩点的变动。分清是「奔向机会」还是「逃离困境」，看官禄迁移、再等大限流年的禄权窗口，你才能每一次都跳得更高，而不是换个地方重复内耗。',
 enClose:'A job change is timed movement. Tell moving-toward-chance from fleeing-trouble, read Career/Travel and await the decade/year Lu/Quan window, and every jump takes you higher rather than repeating drain elsewhere.'},

{cat:'yingyong',slug:'ziwei-pocai-xinhao-shoucai-caibo-huaji-kongjie-zenme-tiqian-fang',focus:'破财信号与守财',focusEn:'loss signals and wealth defense',
 cnT:'紫微斗数破财信号与守财：财帛化忌、空劫怎么提前防',enT:'Loss Signals and Wealth Defense in Zi Wei Dou Shu: How to Prepare for Wealth-Palace Ji and Empty Stars',
 cnD:'破财风险看财帛宫化忌、地空地劫大耗夹财或入财、田宅库位不稳，再叠加大限流年的引动时点。这些信号不等于注定破财，而是提示某阶段现金流脆弱、易冲动投资或被拖累，提前减杠杆、留备用金、避开担保高风险，就能把「破财倾向」化解成「有惊无险」。',
 enD:'Loss risk reads Wealth-Palace Ji, Di Kong/Di Jie/Da Hao flanking or entering wealth, and an unstable Property vault, plus the decade/year activation timing. These signals are not destined loss but flag a phase of fragile cash flow, impulsive investment or being dragged down; lowering leverage early, keeping reserves and avoiding guarantees/high risk converts loss tendency into a close call.',
 cnL:'命盘给的是「破财倾向和时间窗」，不是破财定局：知道哪几年财帛脆弱，提前收杠杆、不担保不投机，倾向就很难变成现实。',
 enL:'The chart gives loss tendency and its window, not fixed loss; knowing which years wealth is fragile and cutting leverage, guarantees and speculation early keeps tendency from becoming reality.',
 cnA:'有人见财帛化忌就吓得什么都不敢做，也有人在空劫引动的大限还加杠杆投资、给人担保，结果正中信号；正确做法是顺势收防，而不是躺平或硬冲。',
 enA:'Some freeze at Wealth Ji; others leverage up and guarantee loans in an empty-star decade, fulfilling the signal. The right move is calibrated defense, neither lying flat nor charging.',
 cnLog:['财帛宫化忌：主现金流紧张、为钱操心、投资易判断失误或被拖欠，逢武曲化忌、太阴化忌更重，重在资金链安全。','空劫大耗：地空地劫属「空、耗」，入财帛田宅或夹财，主突发破耗、投资落空、存不住钱，大限引动时最明显。','田宅为库：田宅稳则财有处藏，田宅逢煞忌则库漏，赚钱能力再强也易左手进右手出。','引动与时点：本命看倾向，大限看哪十年脆弱，流年定哪一年须防守，提前减杠杆、留足6到12个月备用金、不担保不投机。'],
 enLog:['Wealth Ji: tight cash flow, money worry, investment misjudgment or unpaid dues; Wu Qu/Tai Yin Ji is heavier—focus on cash-chain safety.','Empty/Da Hao: Di Kong/Di Jie are void and drain; in Wealth/Property or flanking wealth they mean sudden loss, failed investment and inability to save, clearest when a decade activates.','Property is the vault: stable Property stores wealth, malefic/Ji Property leaks the vault, so even strong earners see money in and out.','Activation and timing: natal shows tendency, decade which ten years are fragile, year which to defend; cut leverage early, keep 6–12 months reserves, no guarantees or speculation.'],
 cnStep:['先查财帛宫有无化忌、空劫大耗','查田宅库位稳不稳，判断能不能存住','用大限找出财务脆弱的十年','用流年锁定须重点防守的年份','防守期减杠杆、留备用金、不担保不投机','信号期过后再恢复正常投资节奏，不长期躺平'],
 enStep:['Check Wealth for Ji and Empty/Da Hao stars','Check the Property vault for whether money can be saved','Use the decade to find financially fragile ten years','Use the year to lock key defense years','In defense phases cut leverage, keep reserves, no guarantees or speculation','Resume normal investment after the signal phase, not permanently idle'],
 cnMis:['见破财信号就躺平什么都不做','空劫引动期还加杠杆、担保、投机','只看本命倾向，不看大限流年时点'],
 enMis:['Lying flat at any loss signal','Leveraging, guaranteeing and speculating during empty-star activation','Reading natal tendency without decade/year timing'],
 cnClose:'破财信号的价值在于「提前知道」。看清财帛化忌和空劫落在哪、哪几年被引动，在那之前收杠杆、留备用金、不碰担保投机，你就能把命盘里的破财倾向，变成有惊无险的财务纪律。',
 enClose:'Loss signals are valuable because they warn early. See where Wealth Ji and empty stars fall and which years activate them, then cut leverage, keep reserves and avoid guarantees and speculation—and loss tendency becomes close-call financial discipline.'},
];
