const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'yingyong',slug:'ziwei-maifang-zhichan-tianzhai-yun-na-yi-nian-shihou',focus:'买房置产田宅运',focusEn:'property timing via Property palace',
 cnT:'紫微斗数买房置产怎么看：田宅运好的年份特征',enT:'Buying Property in Zi Wei Dou Shu: The Signs of a Strong Property Year',
 cnD:'田宅宫主不动产、财库与家运，本命田宅有武曲禄存太阴庙旺化禄，主一生房产缘深；真正适合出手的年份，是大限田宅化禄、流年田宅吉化无煞、且流年命宫财帛配合，几个信号叠加、资金到位时，才是置产窗口，只看一年容易踩高点。',
 enD:'The Property palace governs real estate, the wealth store and family fortune; natal Property with Wu Qu/Lu Cun or strong Tai Yin Lu means lifelong property affinity. The right year to buy is when decade Property gets Lu, year Property is auspicious without malefics, and year Life/Wealth align—several signals plus ready funds make the window; one year alone risks buying the peak.',
 cnL:'本命田宅看你「和房子的缘分深浅」，大限看这十年有没有置产运，流年看具体哪年适合出手，三层叠加、再配合现金，买房决策才稳。',
 enL:'Natal Property shows property affinity, the decade whether these ten years carry it, the year the exact time; three layers plus cash make a steady purchase.',
 cnA:'有人见流年田宅化禄就冲进去，结果大限田宅逢煞、资金链紧，买在高点；置产是大额决策，必须本命、大限、流年和现金流一起看，宁可错过不追高。',
 enA:'Rushing in on a year Property Lu when the decade Property has malefics and cash is tight buys the peak; big decisions need natal, decade, year and cash flow together—better miss than chase.',
 cnLog:['本命田宅：武曲、禄存、太阴庙旺或化禄入田宅，主财库稳、与不动产缘深、易有置产运；见煞忌则房产多波折。','大限层：大限田宅化禄化权、无空劫煞冲破，这十年具备买房换房的大环境与资金积累。','流年层：流年田宅化禄、流年命宫或财帛吉化、叠本命吉点，且无煞忌，为具体出手窗口；左右魁钺入田宅主房源多、遇好房。','现实配合：首付贷款、月供占比、家庭需求必须同步，盘只给倾向窗口，最终以财务安全和自住需求为准，不鼓励投机炒房。'],
 enLog:['Natal Property: Wu Qu, Lu Cun or strong Tai Yin/Lu means a stable wealth store and property affinity; malefics/Ji bring property setbacks.','Decade: decade Property Lu/Quan without emptiness/malefic break gives the environment and savings to buy or upgrade these ten years.','Year: year Property Lu, auspicious year Life/Wealth stacking natal strength without malefics is the concrete window; Zuo-You/Kui-Yue bring more and better listings.','Reality: down payment, loan, monthly-payment ratio and family need must align; the chart gives a tendency window, final calls follow financial safety and self-use, not speculation.'],
 cnStep:['先看本命田宅星曜，判断房产缘深浅','找大限田宅化禄、无煞的置产十年','在该十年内找流年田宅吉化的年份','核对流年命宫财帛是否同步配合','算清首付贷款月供，确保财务安全','信号叠加且资金到位再出手，不追高'],
 enStep:['Read natal Property for property affinity','Find the decade with Property Lu and no malefics','Within it, find years with auspicious year Property','Check year Life/Wealth alignment','Calculate down payment, loan and monthly burden','Act only when signals stack and funds are ready; don\'t chase peaks'],
 cnMis:['单看流年田宅化禄就冲','忽略大限环境和现金流','把命盘倾向当炒房依据'],
 enMis:['Rushing on year Property Lu alone','Ignoring decade context and cash flow','Using chart tendency as a speculation basis'],
 cnClose:'买房是大多数人最大的一笔支出，值得用三层盘慢慢看：本命看缘分、大限看十年、流年看窗口，再让现金流做最终决定。信号凑齐、钱也稳，置产才真正成为你的财库而不是负担。',
 enClose:'Property is most people\'s biggest expense and deserves a three-layer read: natal affinity, decade environment, year window, with cash flow as final judge. When signals and money both align, property becomes a wealth store, not a burden.'},

{cat:'yingyong',slug:'ziwei-piancai-touzi-shibudu-taiyin-tanlang-tianzhai',focus:'偏财投资适合度',focusEn:'windfall and investment aptitude',
 cnT:'紫微斗数偏财、投资运怎么看：太阴贪狼与田宅库的配合',enT:'Windfall and Investment Aptitude in Zi Wei Dou Shu: Tai Yin/Tan Lang and the Property Store',
 cnD:'正财看财帛与武曲，偏财看太阴（隐性、被动收入）与贪狼（机会、风口财），能不能留住偏财看田宅库。太阴庙旺、贪狼化禄且田宅稳固的人，适合稳健投资与被动收入；贪狼逢火铃化忌、田宅破的人，投机易横发横破，核心是先看库、再看机会。',
 enD:'Regular income is Wealth/Wu Qu; windfall is Tai Yin (hidden, passive income) and Tan Lang (opportunity, trend money); whether windfall is kept depends on the Property store. Strong Tai Yin, Tan Lang Lu and a stable Property suit steady investment and passive income; Tan Lang with Fire-Bell/Ji and a broken Property tends boom-bust speculation—check the store before the chance.',
 cnL:'偏财星决定你「能不能遇到机会财」，田宅库决定「钱来了留不留得住」，没有库的偏财像过路财神，先修库再谈赚多少。',
 enL:'Windfall stars decide whether opportunity money arrives, the Property store whether it stays; windfall without a store is money passing through—build the store first.',
 cnA:'有人贪狼化禄就自认投资天才、重仓投机，结果田宅库弱、火铃引动横发横破；真正能靠偏财的人，往往太阴稳、贪狼活、田宅固，赚得到也守得住。',
 enA:'Tan Lang Lu is taken for investment genius with heavy speculation, but a weak store plus Fire-Bell causes boom-bust; those who truly profit from windfall have steady Tai Yin, lively Tan Lang and solid Property.',
 cnLog:['正财：财帛宫与武曲，主工资、经营等稳定收入；偏财：太阴主隐性、被动收入（租金、分红、利息），贪狼主机会、风口、人脉带来的财。','适合投资的配置：太阴庙旺化禄、贪狼化禄不逢煞，且田宅宫稳固（禄存、天府、吉化），主有机会也守得住，宜稳健配置与长期被动收入。','高风险信号：贪狼会火星铃星、化忌或逢空劫，田宅又弱，主投机心重、横发横破、赚快钱后回吐。','原则：先建财库（储蓄、保险、应急金、不动产）再谈风险投资；仓位与止损纪律比「偏财命」更决定结果，不赌身家。'],
 enLog:['Regular income: Wealth palace and Wu Qu (wages, business); windfall: Tai Yin hidden/passive (rent, dividends, interest), Tan Lang opportunity/trend/network money.','Investment-suited: strong Tai Yin Lu, Tan Lang Lu without malefics and a stable Property (Lu Cun/Tian Fu/auspicious)—chances arrive and are kept, favoring steady allocation and passive income.','High-risk: Tan Lang with Fire/Bell, Ji or emptiness plus weak Property means strong speculation, boom-bust and giving back quick gains.','Principle: build the store first (savings, insurance, emergency fund, property), then risk investing; position sizing and stop-loss discipline decide outcomes more than a windfall destiny—never bet the household.'],
 cnStep:['分正财（财帛武曲）与偏财（太阴贪狼）','看太阴是否庙旺、贪狼化禄是否逢煞','重点看田宅库稳不稳，判断留财能力','库稳再配置稳健投资与被动收入','贪狼逢火铃忌者严控仓位、设止损','先储蓄建库，风险投资只用闲钱'],
 enStep:['Separate regular income (Wealth/Wu Qu) from windfall (Tai Yin/Tan Lang)','Check Tai Yin strength and whether Tan Lang Lu meets malefics','Focus on the Property store to judge retention','With a stable store, allocate to steady investment and passive income','With Tan Lang/Fire-Bell/Ji, limit position and set stops','Save and build the store first; risk only spare money'],
 cnMis:['贪狼化禄就重仓投机','只看偏财星不看田宅库','没有应急金就拿身家赌'],
 enMis:['Heavy speculation on Tan Lang Lu','Reading windfall stars without the store','Betting the household without an emergency fund'],
 cnClose:'偏财的真相是「机会×守财」：太阴贪狼给你机会，田宅库决定结局。先把库筑牢、再用闲钱和纪律去接机会财，你才不会成为那个「赚过、又还回去」的人。',
 enClose:'Windfall truth is opportunity times retention: Tai Yin/Tan Lang give chances, the Property store decides the ending. Build the store, then use spare money and discipline for opportunity gains, so you\'re not the one who earned it all and gave it back.'},

{cat:'yingyong',slug:'ziwei-jie-gong-kan-tizhi-ruodian-jiankang-tixing',focus:'疾厄宫看体质',focusEn:'health tendencies from Health palace',
 cnT:'紫微斗数疾厄宫看体质：先天薄弱部位与健康提醒（非诊断）',enT:'Health Tendencies From the Zi Wei Dou Shu Health Palace: Innate Weak Spots as Reminders, Not Diagnosis',
 cnD:'疾厄宫结合命宫、福德、迁移，提示先天体质的薄弱环节与慢病倾向：紫府梁同无煞体质较稳，火铃羊陀主急性、突发与外伤，廉贞偏泌尿生殖与血液、巨门偏消化口腔。这些只是「需要多留意的方向」，不是诊断，任何不适都以正规医院检查为准。',
 enD:'Health palace with Life, Happiness and Travel hints at innate weak spots and chronic tendencies: Zi-Wei/Tian Fu/Tian Liang without malefics are sturdier; Fire-Bell/Yang-Tuo lean acute/sudden/injury; Lian Zhen urinary-reproductive/blood, Ju Men digestion/oral. These are areas to watch, not diagnosis—any symptom follows formal medical examination.',
 cnL:'疾厄宫给的是「保养优先级地图」：哪里天生要多留心、生活方式上该避什么，它帮你提前预防，而不是替你下医学结论。',
 enL:'The Health palace is a maintenance-priority map: where to take innate care and what lifestyle to avoid, helping prevention rather than issuing medical conclusions.',
 cnA:'有人拿疾厄宫自我确诊、吓自己或乱吃药，这是误用；正确用法是把它当体检和生活习惯的提醒，星曜倾向永远不能替代医生和检查。',
 enA:'Self-diagnosing from the Health palace causes fear or self-medication, a misuse; treat it as a checkup/lifestyle reminder—star tendencies never replace doctors and tests.',
 cnLog:['疾厄宫主身体先天底子与薄弱环节，须命宫、疾厄、福德、迁移合参，单宫不下结论。','星曜倾向：紫微天府天同天梁庙旺无煞多体质稳；火星擎羊主急性、炎症、外伤，铃星陀罗主慢性、拖延、反复。','脏腑取象（仅文化取象、非医学对应）：廉贞偏血液泌尿生殖、巨门偏消化口腔、天机偏神经肝胆、太阴偏水液代谢与妇科。','正确用法：据倾向安排作息、饮食、运动与针对性体检，出现症状第一时间正规就医、遵医嘱，不据命盘自我诊断或停药。'],
 enLog:['Health governs innate constitution and weak spots, read with Life/Happiness/Travel; no conclusion from one palace.','Star tendencies: strong Zi-Wei/Tian Fu/Tian Tong/Tian Liang without malefics are sturdy; Fire/Yang lean acute/inflammation/injury, Bell/Tuo chronic/dragging/recurrent.','Organ imagery (cultural only, not medical mapping): Lian Zhen blood/urinary-reproductive, Ju Men digestion/oral, Tian Ji nerves/liver-gallbladder, Tai Yin fluid metabolism/gynecology.','Correct use: schedule rest, diet, exercise and targeted checkups by tendency; at symptoms seek formal care and follow doctors—never self-diagnose or stop medication from a chart.'],
 cnStep:['看疾厄宫主星与煞曜，列薄弱倾向','结合命宫福德迁移，不做单宫判断','把倾向转成作息饮食运动的调整','据倾向安排针对性体检项目','任何不适以正规医院检查为准','不据盘自我诊断、不自行停药进补'],
 enStep:['Read Health stars and malefics for weak tendencies','Combine Life/Happiness/Travel, no single-palace call','Turn tendencies into rest/diet/exercise changes','Schedule targeted checkups accordingly','Let formal medical examination rule on symptoms','No self-diagnosis, stopping medication or supplements from the chart'],
 cnMis:['拿疾厄宫自我确诊','据星曜自行买药停药','把文化取象当医学对应'],
 enMis:['Self-diagnosing from the Health palace','Buying drugs or stopping medication by stars','Treating cultural imagery as medical mapping'],
 cnClose:'疾厄宫的价值在「治未病」：它提醒你哪里要多保养、体检该重点查什么，仅此而已。把命理当健康提醒、把诊断交给医生，两者各归其位，才是对身体真正负责。',
 enClose:'The Health palace\'s value is prevention: where to maintain and what checkups to prioritize, nothing more. Treat the chart as a health reminder and leave diagnosis to doctors—each in its place is true responsibility to your body.'},

{cat:'yingyong',slug:'ziwei-qianyi-yimin-yidi-fazhan-zenme-kan',focus:'迁移宫看异地移民',focusEn:'migration and relocation via Travel palace',
 cnT:'紫微斗数迁移宫看异地、移民与跨城发展',enT:'Relocation, Emigration and Cross-City Development Through the Zi Wei Dou Shu Travel Palace',
 cnD:'迁移宫主外出、异地环境与对外发展，迁移庙旺吉化、命宫与迁移良性互动的人，离乡发展、跨城出国反而更顺；迁移自化忌或逢煞重者，外出多阻、异地劳心。移民定居尤其重迁移，且头三年多为适应期，须结合大限迁移判断哪个阶段最适合走出去。',
 enD:'Travel governs going out, the external environment and outward development; strong, auspiciously transformed Travel with good Life-Travel interplay means leaving home, cross-city or abroad goes smoother; Travel self-Ji or heavy malefics mean obstacles and strain elsewhere. Emigration especially weighs Travel, with the first three years as adaptation; use decade Travel to time when going out is best.',
 cnL:'命宫是你在本地的状态，迁移宫是你「离开舒适圈后」的状态，迁移比命宫强的人，往往是「树挪活、人走旺」，越往外越开阔。',
 enL:'Life is your local state, Travel your state outside the comfort zone; when Travel beats Life, moving away broadens and lifts you.',
 cnA:'有人只看命宫好就死守本地，或迁移自化忌还盲目移民，结果异地劳而少获；走出去之前，先看迁移宫和大限迁移，选对阶段比一时冲动重要。',
 enA:'Staying local on a good Life alone, or emigrating blindly with Travel self-Ji, brings strain and little gain; before leaving, read Travel and decade Travel—timing beats impulse.',
 cnLog:['迁移宫主外出际遇、异地环境、对外人际与发展空间，与命宫成对（「命迁线」），须对照看。','利外出：迁移庙旺、化禄化权化科、会禄存左右魁钺，主异地贵人多、舞台大、离乡更有发展。','不利信号：迁移落陷、自化忌、逢四煞空劫，主外出多阻、异地小人、劳多获少，重大迁移须更谨慎、多做准备。','移民跨城：重点看大限迁移吉化的阶段，通常头三年为适应期（语言、身份、重建人脉），结合财帛田宅判断落地后的经济与安居。'],
 enLog:['Travel governs away-from-home encounters, external environment, outward relations and room to grow, paired with Life (Life-Travel axis).','Favoring going out: strong Travel with Lu/Quan/Ke, Lu Cun/Zuo-You/Kui-Yue means mentors and a bigger stage away from home.','Caution signs: fallen Travel, self-Ji or four malefics/emptiness mean obstacles, petty people and low return elsewhere; major moves need more preparation.','Emigration: focus on decades with auspicious decade Travel; the first three years are usually adaptation (language, status, rebuilding network), with Wealth/Property for post-move finances and housing.'],
 cnStep:['对照命宫与迁移宫，判断本地强还是外出强','看迁移庙旺吉化还是落陷逢煞','利外出者主动争取跨城、外派、出国机会','重大移民选大限迁移吉化的阶段','预留头三年适应期的资金与心理准备','迁移逢忌煞者先短期外派试水，不孤注一掷'],
 enStep:['Compare Life and Travel for local versus outward strength','Check Travel brilliance/auspiciousness versus fallen/malefics','If outward-favored, pursue cross-city, secondment and abroad chances','Time emigration to a decade with auspicious decade Travel','Reserve funds and mindset for the three-year adaptation','With Travel Ji/malefics, pilot with short stints, don\'t bet all'],
 cnMis:['只看命宫、忽略命迁线','迁移自化忌还盲目移民','不看大限阶段，冲动裸辞出国'],
 enMis:['Reading Life only, ignoring the axis','Emigrating blindly with Travel self-Ji','Ignoring decade timing, quitting and leaving on impulse'],
 cnClose:'迁移宫回答的是「你该守还是该走」。迁移强、大限又走到吉化阶段的人，勇敢走出去世界更大；迁移逢忌煞的人，先试水、备足粮草。选对方向和阶段，异地才是跳板而不是消耗。',
 enClose:'Travel answers whether to stay or go. With strong Travel and an auspicious decade, leaving broadens your world; with Ji/malefics, pilot and prepare. Right direction and timing make relocation a springboard, not a drain.'},

{cat:'yingyong',slug:'ziwei-fang-xiaoren-shifei-na-xie-pan-rongyi-bei-yin',focus:'防小人是非',focusEn:'guarding against petty people',
 cnT:'紫微斗数怎么看小人是非，哪些盘容易被暗中使绊',enT:'How Zi Wei Dou Shu Shows Petty People and Gossip—and Which Charts Are Prone to Hidden Sabotage',
 cnD:'小人是非多与巨门（口舌）、擎羊陀罗（明争暗斗）、化忌（卡点怨结）落在哪一宫有关：落奴仆宫易遇损友和下属问题、落官禄易职场是非、落迁移易在外招怨。命盘只给「容易招是非的场景」，真正化解靠沟通留痕、边界和情绪管理，而非戴什么化解物。',
 enD:'Gossip and petty people relate to Ju Men (speech), Yang/Tuo (open/hidden conflict) and Hua Ji (grievance) by palace: in Friends trouble with peers/subordinates, in Career workplace disputes, in Travel external resentment. The chart gives dispute-prone scenarios; real resolution comes from documented communication, boundaries and emotion management—not charms.',
 cnL:'命盘标出你「在哪类人际场景里容易被绊」，是为了让你提前设防：对什么人留痕、在什么场合少表态、利益边界划在哪。',
 enL:'The chart marks where you are prone to be tripped, so you guard ahead: whom to document with, when to speak less, where to draw interest boundaries.',
 cnA:'有人一见巨门化忌就认定身边全是小人、处处提防，反而破坏正常关系；盘给的是概率场景，不是让你预设敌意，关键是制度化自保。',
 enA:'Ju Men/Ji is read as everyone being an enemy, which itself ruins relations; the chart gives probability scenarios, not preset hostility—institutional self-protection is key.',
 cnLog:['口舌星：巨门主语言是非，落官禄主职场口舌、落奴仆主人际摩擦、落迁移主在外招怨，化忌时加重。','争斗星：擎羊主明面冲突、陀罗主暗中纠缠拖延，落交友、官禄时易遇竞争使绊、抢功甩锅。','化忌落点：化忌在哪个宫，就在那个领域易生怨结与卡点，是是非高发区。','化解之道（靠人不靠物）：重要沟通书面留痕、权责边界清晰、不传话不站队、情绪上来不当场发作、实力和成果说话，远离持续消耗的关系。'],
 enLog:['Speech star: Ju Men governs verbal dispute—in Career workplace gossip, in Friends peer friction, in Travel external resentment, worsened by Ji.','Conflict stars: Yang open clash, Tuo hidden entanglement/dragging; in Friends/Career they bring competition, credit-snatching and blame-shifting.','Ji location: whichever palace holds Ji is where grievance and sticking points cluster, a dispute hotspot.','Resolution (by people, not objects): document key communication, clear responsibility boundaries, no rumor-mongering or faction-taking, no outburst in anger, let results speak, leave chronically draining ties.'],
 cnStep:['找巨门、擎羊陀罗、化忌落在哪几宫','定位是非高发领域（职场/朋友/外出）','该领域重要沟通一律书面留痕','划清权责和利益边界，不替人背锅','不传话、不站队、情绪不当场爆发','持续消耗、爱使绊的人主动疏远'],
 enStep:['Locate Ju Men, Yang/Tuo and Ji palaces','Identify dispute hotspots (work/friends/outside)','Document key communication there in writing','Clarify responsibility and interest boundaries, don\'t take blame','No gossip, no factions, no angry outbursts','Distance from chronically draining, sabotaging people'],
 cnMis:['见巨门化忌就认定人人是小人','靠戴化解物而不改沟通方式','情绪当场发作，反落口实'],
 enMis:['Assuming everyone is petty from Ju Men/Ji','Relying on charms instead of changing communication','Outbursts that hand others an excuse'],
 cnClose:'小人是非的盘，给的是「风险地图」不是「敌人名单」。看清自己在哪个领域容易招怨，就把留痕、边界和情绪管理做在前面——真正的护身符不是物件，是清晰的规则和过硬的实力。',
 enClose:'A dispute chart is a risk map, not an enemy list. See where you attract resentment and front-load documentation, boundaries and emotion management—the real talisman is clear rules and solid results, not an object.'},
];
