const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'kanpan',slug:'ziwei-sanhe-pai-yu-feixing-pai-qubie-ruhe-xuanze',focus:'三合派与飞星派区别',focusEn:'San He vs Flying Stars schools',
 cnT:'紫微斗数三合派和飞星派到底差在哪，新手该怎么选',enT:'San He vs Flying Stars in Zi Wei Dou Shu: The Difference and How a Beginner Chooses',
 cnD:'三合派（南派）重星曜组合、庙旺格局与三方四正，擅长看性格、天赋与人生基调；飞星派（北派/钦天四化）重宫干四化的飞化往来，擅长看事件、因果与具体应期。两者不是对错关系，现代多以三合打底、飞星断事，新手应先三合后飞星。',
 enD:'The San He (southern) school stresses star combinations, brilliance/patterns and the trine, strong for character, talent and life tone; the Flying Stars (northern/Qin-Tian) school stresses stem transformations flying between palaces, strong for events, cause-effect and timing. Neither is right-or-wrong; modern practice often grounds with San He and predicts events with Flying Stars. Beginners should do San He first.',
 cnL:'三合回答「你是怎样的人、有什么牌」，飞星回答「这件事怎么发生、什么时候应」，一个偏静态结构，一个偏动态往来，合起来才完整。',
 enL:'San He answers who you are and your cards; Flying Stars how an event happens and when—one static structure, one dynamic exchange, complete only together.',
 cnA:'有人一上来就背飞化口诀、星性都没搞懂，结果断事飘；也有人只学三合、格局背一堆却断不了流年应期，正确路径是先把星曜三方打牢，再学四化飞化。',
 enA:'Beginners memorize flying formulas before star nature and predict vaguely; others learn only San He patterns but cannot time events—the right path is solid stars and trines first, transformations later.',
 cnLog:['三合派（南派）：以108星入十二宫，核心是星情、庙旺落陷、三方四正、夹宫与格局，直观、体系完整，最适合入门打基础。','飞星派（北派/钦天四化）：以宫干四化的「飞入、飞出、自化」论宫与宫的能量往来，重事件、因果、应期，星曜用得相对精简。','两者在部分四化表（尤其庚干、壬干）和大限排法上有差异，同一盘结论侧重不同，属体系不同而非矛盾，不必互相否定。','实务路径：先用三合定性格、资源、格局基调，再用飞星看具体事项的往来与时间，初学先三合、进阶再飞星最稳。'],
 enLog:['San He (southern): 108 stars in twelve palaces, centered on star nature, brilliance, trine, flanking and patterns—intuitive and complete, best for foundations.','Flying Stars (northern/Qin-Tian): stem transformations flying in/out/self between palaces, emphasizing events, cause-effect and timing, using fewer stars.','They differ in some transformation tables (esp. Geng/Ren stems) and decade methods; the same chart gets different emphasis—a system difference, not contradiction.','Practical path: use San He for character, resources and pattern tone, Flying Stars for concrete exchanges and timing; San He first, Flying Stars later.'],
 cnStep:['先学十四主星星性与庙旺，打三合底子','再学三方四正、夹宫与常见格局','能独立描述一张盘的基调后，再接触四化','进阶时学宫干飞化、自化与来因宫','对照同一盘分别用三合、飞星看，体会侧重','不混派别规则，标注自己用的是哪套体系'],
 enStep:['Learn the fourteen major stars and brilliance for a San He base','Then learn trine, flanking and common patterns','Once you can describe a chart\'s tone, approach transformations','At advanced stage learn stem flying, self-transformation and Lai Yin','Compare San He versus Flying readings of the same chart','Keep school rules separate and note which system you use'],
 cnMis:['入门就硬背飞化、星性没懂','只学格局不会断流年应事','把两派差异当对错互相否定'],
 enMis:['Memorizing flying formulas before star nature','Learning only patterns, unable to time events','Treating school differences as right versus wrong'],
 cnClose:'三合和飞星不是两套互相打架的学问，而是一张盘的「体」和「用」：先用三合看清你手里的牌，再用飞星看清牌怎么打出去，顺序对了，紫微斗数既学得稳，也断得准。',
 enClose:'The two schools are not rivals but a chart\'s body and use: San He shows your hand, Flying Stars how it plays. In that order, Zi Wei Dou Shu is both learned solidly and predicted accurately.'},

{cat:'kanpan',slug:'ziwei-wuxingju-xiangjie-da-xian-qibu-nianling',focus:'五行局详解',focusEn:'five-element phases explained',
 cnT:'紫微斗数五行局详解：水二木三金四土五火六，决定大限几岁起运',enT:'Five-Element Phases in Zi Wei Dou Shu: Water-2 to Fire-6 and How They Set the Decade Start Age',
 cnD:'五行局由命宫地支与生年天干（纳音）推得，分水二、木三、金四、土五、火六局，决定紫微星落宫和大限起运年龄（2/3/4/5/6岁起，每宫十年），也带一点性格底色。它是排盘和排大限的关键参数，不懂五行局，大限顺逆行和起算岁数就会全错。',
 enD:'The five-element phase is derived from the Life palace branch and birth-year stem (na-yin), into water-2, wood-3, metal-4, earth-5, fire-6; it sets Zi Wei\'s placement and the decade start age (2/3/4/5/6, ten years per palace), with a slight temperament tint. It is the key parameter for casting and decades; without it, decade direction and start age go wrong.',
 cnL:'五行局最实际的作用是「几岁起第一个大限」：水二局两岁起、火六局六岁起，同样年龄，不同局的人走在完全不同的大限里。',
 enL:'Its most practical role is the first-decade start age: water at two, fire at six—at the same age, people of different phases walk entirely different decades.',
 cnA:'有人排大限直接从某个固定岁数套，忽略五行局，结果十年阶段全错位；起运岁数差几岁，人生阶段的判断就会整体偏移，必须先定局再排限。',
 enA:'People apply a fixed start age for decades ignoring the phase, misaligning every ten-year stage; a few years\' offset shifts the whole reading—fix the phase before decades.',
 cnLog:['五行局依命宫地支与生年天干的纳音关系定，共水二局、木三局、金四局、土五局、火六局五种。','它决定两件事：一是安紫微星的位置（排盘定盘核心），二是大限起运年龄（分别2、3、4、5、6岁起）。','大限从命宫起，按阳男阴女顺行、阴男阳女逆行，每宫走十年，起运岁数由五行局决定。','性格附会（水灵动、火晚发等）只作参考，真正硬作用在排盘与大限起算，务必以排盘软件核定的局为准。'],
 enLog:['The phase comes from the Life branch and birth-year stem na-yin: water-2, wood-3, metal-4, earth-5, fire-6.','It sets two things: Zi Wei\'s position (core of casting) and the decade start age (2/3/4/5/6).','Decades start at Life, clockwise for yang-male/yin-female and counterclockwise otherwise, ten years per palace, start age from the phase.','Temperament associations (water agile, fire late) are reference only; the hard role is casting and decade start—use software-verified phase.'],
 cnStep:['用出生年月日时排盘，先定命宫地支与生年天干','按纳音表查出五行局（水二至火六）','据局确定大限起运年龄（2-6岁）','按性别阴阳定大限顺行或逆行','从命宫起逐宫排每十年大限','以软件核定的五行局校验，避免手工错局'],
 enStep:['Cast from birth date/time, fix Life branch and birth-year stem','Look up the phase (water-2 to fire-6) by na-yin table','Set the decade start age (2–6) from the phase','Set clockwise/counterclockwise by gender yin-yang','Lay each ten-year decade palace by palace from Life','Verify with software-confirmed phase to avoid manual error'],
 cnMis:['用固定岁数起大限，不查五行局','把五行局性格附会当主要用途','顺逆行和起运岁数没对应，阶段全错位'],
 enMis:['Starting decades at a fixed age without the phase','Treating phase temperament as its main use','Mismatching direction and start age, shifting all stages'],
 cnClose:'五行局是排盘里「牵一发动全身」的参数：它既定紫微星落在哪，也定你几岁走进第一个大限。先把局定准，后面的大限流年才有正确的时间坐标。',
 enClose:'The phase is a one-move-affects-all parameter: it sets both Zi Wei\'s position and your first-decade age. Fix it accurately and later decades and years get a correct time coordinate.'},

{cat:'kanpan',slug:'ziwei-mingzhu-shenzhu-shipan-yinyi-zenme-yong',focus:'命主身主',focusEn:'Life master and body master',
 cnT:'紫微斗数命主身主是什么，排盘里到底怎么用',enT:'Life Master and Body Master in Zi Wei Dou Shu: What They Are and How to Use Them',
 cnD:'命主由命宫地支对应的星（如命宫在子命主为贪狼）取，是先天命格的「总代表」；身主由生年地支取，主后天行为与中年后走向。看命主身主所在宫位庙旺吉凶，可辅助判断先天禀赋强弱与后天着力点，它们是提纲式的参考星，不替代十二宫正解。',
 enD:'The Life master is the star mapped from the Life branch (e.g. Life in Zi → Tan Lang), a general representative of innate pattern; the Body master from the birth-year branch governs later behavior and post-midlife direction. Their palace, brilliance and fortune help judge innate endowment and later focus; they are outline reference stars, not replacements for the twelve-palace reading.',
 cnL:'命主像先天的「代言人」，看你天生的牌面强在哪；身主像后天的「操盘手」，看你中年后把力气使向哪，两颗落宫一对照，人生前后半段的重心就清楚些。',
 enL:'Life master is the innate spokesperson showing where your natural hand is strong; Body master the later operator showing where effort goes after midlife—comparing both clarifies life\'s two halves.',
 cnA:'有人把命主身主神秘化、以为是什么隐藏命格，其实它们是辅助提纲；也有人完全忽略，其实看这两颗落宫吉凶，能快速校验命盘前后半段的强弱和着力点。',
 enA:'Some mystify them as hidden destinies; they are outline aids. Others ignore them entirely, yet their palaces quickly verify strength and focus across life\'s halves.',
 cnLog:['命主：依命宫地支按固定口诀取一颗主星（子贪狼、亥巨门等），代表先天命格的总纲，落宫庙旺吉化则先天根基好。','身主：依生年地支取（子火星之类，门派略有差异），代表后天作为、行为模式与中晚年走向。','用法：看命主、身主落在哪一宫、星曜庙旺吉凶与四化，辅助判断先天禀赋与后天着力领域，是「提纲挈领」的第二视角。','定位：它们不替代命宫、身宫和十二宫的正解，只作交叉验证；身宫落宫（六宫之一）仍以后天行迹为主。'],
 enLog:['Life master: a major star from the Life branch by fixed formula (Zi→Tan Lang, Hai→Ju Men), summarizing innate pattern; strong/auspicious placement means good innate base.','Body master: from the birth-year branch (e.g. Zi→Fire, slight school variation), governing later action, behavior and mid/late-life direction.','Use: read which palace each lands in, its brilliance and transformations to aid innate-endowment and later-focus judgment—a second, outline view.','Role: they do not replace Life/Body palaces and the twelve-palace reading, only cross-check; the Body palace (one of six) still governs later tracks.'],
 cnStep:['排盘后先按命宫地支查出命主星','按生年地支查出身主星','分别定位两颗星落在哪个宫','看其庙旺吉凶与四化，判断先后天强弱','命主看先天禀赋、身主看中后天着力点','作为十二宫正解的交叉参考，不喧宾夺主'],
 enStep:['After casting, find the Life master from the Life branch','Find the Body master from the birth-year branch','Locate each star\'s palace','Read brilliance and transformations for innate/later strength','Life master for endowment, Body master for later focus','Use as cross-reference to the twelve-palace reading, not the main event'],
 cnMis:['把命主身主当隐藏神星','只看命主身主、不看十二宫正解','身主命主取法门派不同却混用'],
 enMis:['Mystifying the masters as hidden stars','Reading only them, not the twelve palaces','Mixing schools\' different master-star formulas'],
 cnClose:'命主身主是命盘的「两张提纲」：一个概括你天生的牌面，一个提示你后天往哪使劲。它们不抢十二宫的主角，却能帮你快速抓住先后天的重点，是老手常用的校验视角。',
 enClose:'The two masters are outline cards: one summarizing your natural hand, one hinting where later effort goes. They don\'t replace the twelve palaces but quickly anchor innate and later focus—a seasoned cross-check.'},

{cat:'kanpan',slug:'ziwei-xiaoxian-zenme-yong-yu-liunian-qubie-he-canzhan',focus:'小限用法',focusEn:'minor limit usage',
 cnT:'紫微斗数小限怎么用：它和流年的区别与配合',enT:'The Minor Limit in Zi Wei Dou Shu: How It Differs From the Year and How They Work Together',
 cnD:'小限以生年支定起、逐年顺行，是从本人角度看的「一岁一宫」内在运势，偏内心状态、身体与个人感受；流年以当年地支定，偏外部环境与实际事件。三合派常小限看迹象、流年断实事，两者一内一外配合，比单看流年更立体。',
 enD:'The minor limit starts from the birth-year branch and advances one palace yearly, an inner one-age-one-palace trend focused on mental state, body and personal feeling; the year is set by that year\'s branch and focuses on external environment and actual events. San He often reads signs in the minor limit and facts in the year—inner and outer together are fuller than the year alone.',
 cnL:'小限是「你内心和身体的天气」，流年是「外面世界发生了什么」，一个主内一个主外，同吉同凶才更确定，内外不一致时往往是「事顺心不静」或反之。',
 enL:'The minor limit is inner/body weather, the year what happens outside; aligned fortune is certain, misalignment often means smooth events with restless mind or vice versa.',
 cnA:'有人把小限和流年混为一谈，只看一个；也有人觉得小限没用。其实当流年事件和小限状态对不上时，小限正好解释「为什么好事来了你却焦虑」这种内外落差。',
 enA:'People conflate the two and read one, or dismiss the minor limit; when year events and inner state mismatch, it explains why good news arrives yet you feel anxious—the inner-outer gap.',
 cnLog:['小限起法：以生年地支定一岁小限所在宫（如辰年生男子一歲在辰），之后男女皆逐年顺行，一歲一宫，绕十二宫一周。','性质：小限从「我」的内在出发，主心态、情绪、身体状态与个人层面的迹象，偏内因。','流年：以当年太岁地支定流年命宫，主外部环境、人事、实际发生的事件，偏外因。','合参：小限看迹象与内因、流年断实事与外因，两者吉凶一致则事象明确，互相矛盾时多为内外落差，需分别说明。'],
 enLog:['Start: the birth-year branch sets age-one minor-limit palace, then advances one palace yearly for both genders, cycling the twelve.','Nature: from the inner self, governing mindset, emotion, body and personal signs—internal.','Year: that year\'s Tai Sui branch sets the year Life palace, governing external environment, people and actual events—external.','Together: minor limit for signs/internal, year for facts/external; aligned fortune is clear, contradiction is an inner-outer gap to explain separately.'],
 cnStep:['按生年支定一岁小限宫位，逐年顺行排到当前年龄','另排当年流年命宫与流年十二宫','小限读心态、情绪、身体等内在迹象','流年读外部环境与实际事件','内外同吉同凶则结论更确定','内外矛盾时分述：是事的问题还是心的问题'],
 enStep:['Set age-one minor-limit palace by birth branch, advance to current age','Separately cast the year Life and year twelve','Read inner signs: mindset, emotion, body in the minor limit','Read external environment and events in the year','Aligned fortune gives a firmer conclusion','When contradictory, separate event problem from mind problem'],
 cnMis:['把小限和流年当成同一个东西','只看流年，解释不了内心落差','小限起法男女顺逆行搞错'],
 enMis:['Treating minor limit and year as the same','Reading only the year, unable to explain inner gaps','Getting the minor-limit direction wrong'],
 cnClose:'小限补的是流年看不到的「内在一面」。流年告诉你世界给了你什么，小限告诉你自己接不接得住、心里好不好受，两个一起看，对一年的判断才既见事、也见人。',
 enClose:'The minor limit supplies the inner side the year misses. The year shows what the world gives, the minor whether you can receive it and how you feel; together a yearly reading sees both event and person.'},

{cat:'kanpan',slug:'ziwei-anhe-gong-liuhe-anzhong-guanxi-yinxian',focus:'暗合宫（六合）',focusEn:'hidden-harmony palace',
 cnT:'紫微斗数暗合宫（六合）：藏在明盘背后的隐性关系线',enT:'Hidden-Harmony Palace (Liu-He) in Zi Wei Dou Shu: The Hidden Relationship Line Behind the Visible Chart',
 cnD:'暗合宫依地支六合（子丑、寅亥、卯戌、辰酉、巳申、午未）找某宫暗中对应的另一宫，代表台面上看不到、却在背后默默影响的资源、关系或心理活动。明宫看显性表现，暗合看隐性牵连，常用于看暗中助力、隐性桃花、内心真实想法。',
 enD:'The hidden-harmony palace uses branch six-harmony pairs (Zi-Chou, Yin-Hai, Mao-Xu, Chen-You, Si-Shen, Wu-Wei) to find the palace secretly corresponding to a given one—hidden resources, ties or mental activity influencing behind the scenes. The visible palace shows the surface, hidden-harmony the concealed tie, used for quiet help, hidden romance and true inner thoughts.',
 cnL:'明盘是「说出来、看得见」的部分，暗合是「没说出口、在背后起作用」的部分，读懂这条暗线，很多表面看不懂的行为和关系就有了解释。',
 enL:'The visible chart is spoken and seen; hidden-harmony is unspoken and working behind—reading this dark line explains otherwise puzzling behavior and ties.',
 cnA:'有人只看明宫，遇到「明明这宫不好却暗中有人帮」「嘴上说不要心里很在意」就解释不通；暗合宫正好补上台面之下的那层关系。',
 enA:'Reading only visible palaces cannot explain hidden help or saying-one-thing-feeling-another; hidden-harmony supplies the layer beneath the surface.',
 cnLog:['暗合（六合）关系：子丑合、寅亥合、卯戌合、辰酉合、巳申合、午未合，每宫都有一个地支六合的暗合宫。','含义：明宫主显性、外显的人事物；暗合宫主隐性、暗中、未明说的牵连、助力、桃花或心理动机。','常见用法：看事业有无暗中贵人资源、感情有无隐性情缘或暗恋、命宫暗合什么宫判断内心真正在意的领域。','定位：它是三合体系的补充视角，属「加分的细节」，断事仍以明宫、三方四正、四化为主，暗合作辅证。'],
 enLog:['Six-harmony pairs: Zi-Chou, Yin-Hai, Mao-Xu, Chen-You, Si-Shen, Wu-Wei; every palace has one hidden-harmony palace.','Meaning: visible palace governs the explicit; hidden-harmony the concealed ties, quiet help, secret romance or inner motive.','Common use: hidden career mentors/resources, implicit affection or crushes, and what the Life palace\'s hidden-harmony says one truly cares about.','Role: a San He supplementary detail; predictions still center on visible palaces, trine and transformations, with hidden-harmony as corroboration.'],
 cnStep:['先读熟明宫与三方四正的显性信息','按地支六合表找出目标宫的暗合宫','看暗合宫主星吉凶，判断隐性牵连','事业看暗中资源与贵人，感情看隐性情缘','命宫暗合看内心真正在意的领域','把暗合当辅证，不喧宾夺主'],
 enStep:['First read visible palaces and trine','Find the target\'s hidden-harmony palace by the six-harmony table','Read its stars for the concealed tie','Career: hidden resources/mentors; romance: implicit ties','Life hidden-harmony: what one truly cares about','Treat it as corroboration, not the main reading'],
 cnMis:['只看明宫，解释不了暗中助力','把暗合当主线，反忽略明盘','六合配对记错，暗合宫找错'],
 enMis:['Only visible palaces, unable to explain quiet help','Making hidden-harmony the main line, ignoring the visible chart','Misremembering six-harmony pairs, finding the wrong palace'],
 cnClose:'暗合宫是命盘里的「潜台词」。明盘演的是台面戏，暗合藏的是幕后线，看清那条隐性的资源、情缘和心思，你对人和事的理解，会比只看表面深一层。',
 enClose:'Hidden-harmony is the chart\'s subtext. The visible chart plays the onstage scene while it hides the backstage line; seeing concealed resources, bonds and motives deepens your reading beyond the surface.'},

{cat:'kanpan',slug:'ziwei-jiekong-xunkong-kongwang-zenme-yingxiang-pan',focus:'截空旬空（空亡）',focusEn:'Jie Kong and Xun Kong voids',
 cnT:'紫微斗数截空旬空（空亡）：让吉星打折、让事情落空的星',enT:'Jie Kong and Xun Kong Voids in Zi Wei Dou Shu: Stars That Discount Auspiciousness and Empty Outcomes',
 cnD:'截空（分旬空/天空）主突然的中断、放弃与落空，旬空主缓慢的消耗与「看着有、抓不住」，它们属空亡类杂曜，会让同宫的吉星打折、让计划生变，但也能缓冲煞忌的凶性。读懂空亡，能解释「为什么明明条件好却差一口气」。',
 enD:'Jie Kong (including Xun Kong/Sky-void) governs sudden interruption, giving-up and falling-through; Xun Kong slow drain and looks-present-but-ungrabbable. These void stars discount co-located auspicious stars and derail plans, yet also buffer malefic/Ji harshness. Reading voids explains why good conditions still fall one step short.',
 cnL:'空亡像「漏气阀」：它让实的变虚、让满的留缺口，吉星空了力量打折，煞星空了反而没那么凶，关键看它和谁同宫、落在哪件事上。',
 enL:'A void is a leak valve: solid turns hollow, full gets a gap—auspicious stars lose force while malefics soften; the key is its co-star and domain.',
 cnA:'有人见某宫吉星云集就断定必成，结果落空，往往就是截空旬空在同宫「漏气」；也有人见煞忌就怕，却不知空亡同宫反而卸掉一部分凶性。',
 enA:'Auspicious-stacked palaces predicted to succeed fall through, often because a void leaks; feared malefics/Ji can be partly disarmed by the same void.',
 cnLog:['截空（地空相关、分旬空/天空）：主突然中断、戛然而止、临时放弃与计划生变，来得快。','旬空：主缓慢的空耗、拖延式落空、「看似有却抓不牢」，力量绵长。','作用机制：与吉星同宫则吉力打折、好事多磨或临门一脚落空；与煞忌同宫则缓冲凶性、减轻冲击，具两面性。','应对：重要事项逢空亡要留备选、别把话说满、合同与承诺留书面，大限流年引动时尤其防突变与烂尾。'],
 enLog:['Jie Kong (related to Di Kong, with Xun Kong/Sky-void): sudden interruption, abrupt stop, last-minute giving-up and plan change—fast.','Xun Kong: slow hollow drain, dragging fall-through, looks-present-but-ungrabbable—lingering.','Mechanism: with auspicious stars it discounts force and makes good things stumble at the finish; with malefics/Ji it buffers harshness—two-sided.','Response: for important matters under a void keep alternatives, avoid overpromising, put contracts in writing, and guard against sudden change and unfinished endings when activated.'],
 cnStep:['全盘标出截空、旬空落在哪宫','看它与吉星还是煞忌同宫','逢吉星：降低「必成」预期、留备选','逢煞忌：知道凶性被缓冲，不必过度恐慌','重要计划留书面、留后路，防临门落空','大限流年引动空亡时，重大决定多缓一拍'],
 enStep:['Mark Jie Kong/Xun Kong palaces across the chart','See whether it shares auspicious or malefic stars','With auspicious stars: lower guaranteed-success expectations, keep alternatives','With malefics/Ji: know harshness is buffered, no need to panic','Put plans in writing with exits to guard the final-step letdown','When a decade/year activates a void, slow major decisions a beat'],
 cnMis:['吉星云集就断言必成，忽略空亡漏气','见空亡就全当凶，不知它能化煞','逢空还把话说满、不留备选'],
 enMis:['Guaranteeing success from auspicious stars, ignoring void leakage','Taking every void as bad, unaware it softens malefics','Overpromising under a void with no alternative'],
 cnClose:'截空旬空解释的是「差的那一口气」。它让好事多磨、也让坏事留余地，看清空亡落在哪、和谁同宫，你就懂得为什么有些事看着稳却落空，也知道该怎么提前补上那个缺口。',
 enClose:'Voids explain the missing final breath: they make good things stumble and bad things less absolute. Seeing where a void falls and with whom, you understand why sure things slip and how to close that gap ahead of time.'},
];
