const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'liunian',slug:'ziwei-liunian-taohua-na-yi-nian-lianhua-wang',focus:'流年桃花怎么看',focusEn:'year romance forecast',
 cnT:'紫微斗数流年桃花怎么看：哪一年感情有动静',enT:'How to Read Year Romance in Zi Wei Dou Shu: Which Year Brings Relationship Movement',
 cnD:'看流年桃花要叠三层：本命夫妻宫与桃花星定基调，大限夫妻宫看这十年有没有感情戏，流年红鸾天喜入命、流年夫妻宫化禄、贪狼廉贞被引动的年份，最容易有桃花、恋爱或复合；但桃花分正缘和烂桃花，逢吉化多正缘，逢煞忌要防烂桃花。',
 enD:'Year romance stacks three layers: natal Spouse and romance stars set tone, decade Spouse shows whether the decade has relationship play; years when Hong Luan/Tian Xi enter Life, year Spouse gets Lu, or Tan Lang/Lian Zhen activate most often bring romance, love or reunion. Yet romance splits into right match and bad romance—auspicious transformation favors the former, malefics/Ji warn of the latter.',
 cnL:'本命定你感情的底色，大限定这十年开不开花，流年定具体哪一年发芽；三层叠到一起，再分清是正缘还是劫，一年的感情运才看得准。',
 enL:'Natal sets the emotional base, the decade whether it flowers these ten years, the year when it sprouts; stack all three and separate right match from trouble for an accurate year.',
 cnA:'有人一见流年红鸾就坐等脱单，忽略大限夫妻宫逢煞、流年化忌，结果来的是烂桃花；桃花年份只代表机会多，质量还要看星曜组合。',
 enA:'Sitting single-ready at a Hong Luan year while decade Spouse has malefics and year Ji brings bad romance; a romance year means more chances, quality still depends on star combinations.',
 cnLog:['本命层：夫妻宫星曜与红鸾天喜、咸池天姚位置，定感情基调与桃花强弱。','大限层：大限夫妻宫化禄化科、逢桃花星，这十年感情机会多；逢煞忌则多波折。','流年层：流年命宫逢红鸾天喜、流年夫妻宫化禄、流年引动贪狼廉贞，为桃花/恋爱/复合高概率年。','辨质量：吉化、吉星多为正缘、稳定关系；逢擎羊陀罗火铃化忌、咸池叠煞多为短暂、纠缠的烂桃花，机会年也要慢确认。'],
 enLog:['Natal: Spouse stars and Hong Luan/Tian Xi/Xian Chi/Tian Yao positions set base and romance strength.','Decade: decade Spouse Lu/Ke with romance stars means many chances; malefics/Ji mean setbacks.','Year: year Life with Hong Luan/Tian Xi, year Spouse Lu, or year activating Tan Lang/Lian Zhen makes a high-probability romance/love/reunion year.','Quality: auspicious stars favor stable right matches; Yang/Tuo/Fire-Bell/Ji and Xian-chi-with-malefic favor short entangled bad romance—confirm slowly even in a chance year.'],
 cnStep:['先看本命夫妻宫与桃花星定基调','找大限夫妻宫吉化、有感情戏的十年','逐流年找红鸾天喜入命或夫妻宫化禄','看该年是吉化还是逢煞忌，分正缘烂桃花','正缘年主动社交、认真经营','烂桃花信号年放慢确认、设好边界'],
 enStep:['Read natal Spouse and romance stars for the base','Find the decade with auspicious decade Spouse and relationship play','Scan years for Hong Luan/Tian Xi in Life or Spouse Lu','Tell auspicious from malefic to separate right match and bad romance','In a right-match year socialize and invest seriously','In a bad-romance-signal year slow confirmation and set boundaries'],
 cnMis:['见红鸾就断定脱单','只看流年不看大限夫妻宫','桃花年不辨正缘烂桃花，照单全收'],
 enMis:['Guaranteeing a relationship from Hong Luan','Reading the year without decade Spouse','Accepting all chances without telling right from bad'],
 cnClose:'流年桃花不是「某年必脱单」，而是「某年缘分信号变强」。把本命、大限、流年叠起来，再分清来的是正缘还是烂桃花，机会来的那一年，你才接得稳、也选得对。',
 enClose:'Year romance is not guaranteed-coupling but a stronger signal year. Stack natal, decade and year, separate right match from bad romance, and when the chance year comes you receive it steadily and choose well.'},

{cat:'liunian',slug:'ziwei-liunian-pocai-na-yi-nian-yaofang-zenme-tiqian-kan',focus:'流年破财怎么提前看',focusEn:'year financial loss forecast',
 cnT:'紫微斗数流年破财怎么提前看、怎么防',enT:'How to Foresee and Prevent a Financial-Loss Year in Zi Wei Dou Shu',
 cnD:'破财风险年通常是流年财帛或田宅化忌、逢擎羊火铃空劫，叠大限财帛也走弱的年份，主超支、投资亏损、被骗、大额意外支出或财库破洞。提前看出风险年，不是为了焦虑，而是把高风险动作（加杠杆、担保、重仓投机）主动避开，留足现金安全垫。',
 enD:'Loss-risk years usually have year Wealth or Property Hua Ji with Yang/Fire-Bell/emptiness, stacked on a weakening decade Wealth—overspending, investment loss, fraud, large unexpected costs or a leak in the store. Foreseeing them is not anxiety but actively avoiding high-risk moves (leverage, guarantees, heavy speculation) and keeping a cash cushion.',
 cnL:'破财年的盘往往提前写在财帛和田宅上，看懂它不是让你什么都不敢做，而是把「不该做的动作」在那一年收起来，先守后攻。',
 enL:'Loss years are often written early on Wealth and Property; reading them doesn\'t freeze you but shelves the wrong moves that year—defend first, attack later.',
 cnA:'有人在财帛化忌叠空劫的年份加杠杆、替人担保，结果正中破财信号；风险年不是不能用钱，而是不赌、不借、不冲动，守比赚重要。',
 enA:'Leveraging or guaranteeing in a Wealth-Ji-plus-emptiness year hits the loss signal squarely; a risk year isn\'t no-spending but no gambling, lending or impulse—defense over gain.',
 cnLog:['本命层：财帛、田宅先天强弱与化忌，定你守财的底子，库弱的人更要防风险年。','大限层：大限财帛化忌、逢空劫煞星，这十年财务波动大、不宜高杠杆。','流年层：流年财帛或田宅化忌、逢擎羊火星地空地劫，叠大限走弱，为破财高概率年。','常见破财形式：冲动消费与超支、投机亏损、借贷担保被拖累、诈骗、医疗意外等大额支出，须按信号类型提前设防。'],
 enLog:['Natal: innate Wealth/Property strength and Ji set your savings base; weak stores need more caution in risk years.','Decade: decade Wealth Ji with emptiness/malefics means volatile finances and no high leverage these ten years.','Year: year Wealth/Property Ji with Yang/Fire/Di Kong/Di Jie on a weakening decade makes a high-probability loss year.','Common forms: impulse overspending, speculation loss, dragged by loans/guarantees, fraud, medical/accident costs—guard by signal type ahead.'],
 cnStep:['先看本命财帛田宅，评估守财底子','标出大限财帛走弱、不宜杠杆的十年','逐年找财帛田宅化忌逢煞空的年份','风险年主动避开加杠杆、担保、重仓投机','留足应急现金，大额支出缓一拍','涉及投资借贷多查证、签书面，防诈骗'],
 enStep:['Read natal Wealth/Property for the savings base','Mark decades with weakening Wealth where leverage is unwise','Scan years for Wealth/Property Ji with malefics/emptiness','In risk years avoid leverage, guarantees and heavy speculation','Keep emergency cash; delay large expenditures a beat','Verify investments/loans and put them in writing against fraud'],
 cnMis:['财帛化忌年还加杠杆重仓','替人担保不看自己的风险年','看出风险年却只焦虑、不做防守'],
 enMis:['Leveraging heavily in a Wealth-Ji year','Guaranteeing loans ignoring one\'s risk year','Anxiously seeing the risk but not defending'],
 cnClose:'提前看出破财年，是命理最实用的功能之一。它不预测你一定亏多少，而是提醒你哪一年该把盾牌举起来：不赌、不担、留现金，等风险年过去再进攻，财才守得住。',
 enClose:'Foreseeing a loss year is among the most practical uses of the chart. It doesn\'t fix a loss amount but tells you when to raise the shield: no gambling, no guarantees, keep cash, attack after the risk year passes—that is how wealth is kept.'},

{cat:'faq',slug:'ziwei-butong-paipan-ruanjian-jieguo-butong-weishime',focus:'排盘软件结果为何不同',focusEn:'why chart apps differ',
 cnT:'为什么不同紫微斗数排盘软件结果不一样',enT:'Why Different Zi Wei Dou Shu Apps Produce Different Charts',
 cnD:'同一出生信息，不同软件偶有差异，主要来自四方面：早晚子时的处理、庚干壬干四化表流派不同、是否用真太阳时校正、安星与闰月规则不同。差异多集中在个别星曜或四化，主星和大框架通常一致；选一套你认同的流派规则、固定用一个软件即可，软件只负责起盘，解盘靠人。',
 enD:'For the same birth data, apps occasionally differ from four causes: treatment of early/late Zi hour, school differences in Geng/Ren transformation tables, whether true solar time is corrected, and star-placement/leap-month rules. Differences usually touch a few stars or transformations while major stars and framework agree; pick one school and stick to one app—software only casts, people interpret.',
 cnL:'软件差异不是谁算错了，而是背后用的流派规则不同，搞清楚差在哪、固定一套规则，你的盘才不会今天一个样、明天一个样。',
 enL:'App differences are not errors but different school rules behind them; understand the gap and fix one rule set so your chart stays consistent.',
 cnA:'有人用三个软件排出三张盘就慌了，其实主星宫位大多一致，差的多是四化和小星；与其反复换软件，不如先弄懂差异来源、锁定一套。',
 enA:'Three apps, three charts causes panic, yet major stars mostly agree, differing in transformations and minor stars; rather than switching apps, understand the source and lock one set.',
 cnLog:['子时问题：23:00-24:00算当天晚子时还是次日子时，流派不同会让命宫、日主整体错位一天，是最大差异源。','四化表差异：庚干（太阳化禄还是太阴等）、壬干四化各流派版本不同，会让四化落点不同。','真太阳时：是否按出生地经度把北京时间校正为真太阳时，交界时辰出生者可能因此换宫。','安星规则：闰月如何处理、部分小星安法、大限起法不同，多影响辅星；主星十二宫框架一般稳定，固定一套规则与一个软件即可。'],
 enLog:['Zi-hour issue: whether 23:00–24:00 is that day\'s late Zi or next day\'s Zi shifts Life palace and day master by a day—the biggest source.','Transformation tables: Geng (whether Sun or Tai Yin gets Lu, etc.) and Ren stems differ by school, changing transformation placement.','True solar time: whether Beijing time is corrected by birthplace longitude; borderline-hour births may shift palace.','Star rules: leap-month handling, some minor-star placements and decade starts differ, mostly affecting assistants; the major-star twelve-palace frame is usually stable—fix one rule set and app.'],
 cnStep:['先核对出生时间是否在23点交界，确定子时口径','选定你认同的流派四化表（庚干壬干）','决定是否用真太阳时并固定下来','闰月、大限起法也固定一套规则','之后长期用同一个软件排盘','软件只起盘，解盘结合规则与现实'],
 enStep:['Check whether birth time borders 23:00 and fix the Zi-hour convention','Choose your school\'s Geng/Ren transformation table','Decide whether to use true solar time and keep it','Fix leap-month and decade-start rules too','Thereafter use one app consistently','Apps only cast; interpretation combines rules and reality'],
 cnMis:['三个软件不同就以为全错','忽略早晚子时这个最大差异源','今天用这套规则明天换另一套'],
 enMis:['Thinking differing apps mean all are wrong','Ignoring early/late Zi hour, the biggest source','Switching rule sets day to day'],
 cnClose:'排盘软件的差异，本质是流派规则的差异而不是数学错误。把早晚子时、四化表、真太阳时这几个关键口径定下来、固定一个软件，你就拥有一张稳定、可长期对照的命盘。',
 enClose:'App differences are essentially school-rule differences, not math errors. Fix early/late Zi hour, transformation tables and true solar time, stick to one app, and you hold a stable chart for long-term reference.'},

{cat:'faq',slug:'ziwei-gaiyun-zhuangyun-shi-zhen-shi-jia-ma',focus:'改运转运真假',focusEn:'do fortune remedies work',
 cnT:'紫微斗数改运、补财库、开光物是真是假',enT:'Are Fortune Remedies, Wealth Repletion and Consecrated Objects Real in Zi Wei Dou Shu?',
 cnD:'命盘呈现的是倾向与概率，不是写死的剧本；真正的「改运」是读懂倾向后调整选择、环境和行为，把优势用足、把风险规避。花钱补财库、买开光物、做法事改命缺乏可靠依据，多为利用焦虑的商业套路；命理能帮你找规律，真正改变结果的，是你自己的行动。',
 enD:'A chart shows tendencies and probabilities, not a fixed script; real fortune-changing reads those tendencies and adjusts choices, environment and behavior to maximize strengths and avoid risks. Paid wealth repletion, consecrated objects and rituals that alter fate lack reliable basis and often commercialize anxiety. Metaphysics finds patterns; your own action changes outcomes.',
 cnL:'命盘像天气预报：它说明天大概率下雨，真正「改运」的是你带伞、改行程，而不是花钱买一个号称能让天放晴的物件。',
 enL:'A chart is a weather forecast: it says rain likely tomorrow; real change is carrying an umbrella and adjusting plans, not buying an object claiming to clear the sky.',
 cnA:'有人破财或走低谷时最容易被「补财库、开光转运」收割，越焦虑越要警惕大额收费；能落地的改运从来都是具体行动：补能力、换环境、理财务、修关系。',
 enA:'During loss or low points people are most easily harvested by wealth-repletion and consecrated-object sales; the more anxious, the more to guard large fees. Actionable change is always concrete: skills, environment, finances, relationships.',
 cnLog:['命理定位：紫微斗数描述星曜组合的倾向区间与概率，不决定结果，同一盘在不同选择下走向不同。','什么是真改运：读懂盘上的优势与风险，调整选择、环境、习惯与行动，顺势而为、规避风险，是可验证的「运」。','常见套路：花钱补财库/还阴债、高价开光法器、保证改命消灾、按八字命盘卖物，多利用恐惧与焦虑，无法验证、越贵越要警惕。','自助方向：大限流年走弱时稳扎稳打（储蓄、学习、健康、关系），走强时主动进取；把命理当决策参考，结果由行动负责。'],
 enLog:['Role of metaphysics: Zi Wei Dou Shu describes tendency ranges and probabilities, not fixed results; the same chart diverges by choice.','Real change: reading strengths/risks and adjusting choices, environment, habits and action, going with the grain and avoiding risk—verifiable fortune.','Common schemes: paid wealth repletion/karmic-debt clearing, pricey consecrated objects, guaranteed fate-fixing, selling items by chart—exploiting fear, unverifiable; the costlier, the warier.','Self-help: in weak decades/years play steady (savings, learning, health, bonds), in strong ones advance; use metaphysics as decision reference, let action own the outcome.'],
 cnStep:['先把命盘定位成倾向参考而非定数','走弱大限以守为主：储蓄、学习、健康、关系','走强大限主动进取、把握窗口','警惕补财库、开光物等大额收费套路','把「想改运」转成具体可执行的行动清单','重大决策结合现实信息，不把结果托付给物件'],
 enStep:['Frame the chart as tendency reference, not fixed fate','In weak decades defend: savings, learning, health, bonds','In strong decades advance and seize windows','Guard against paid wealth-repletion and consecrated-object schemes','Convert wanting change into a concrete action list','Base big decisions on real information, not objects'],
 cnMis:['相信花钱补财库能改命','把命盘当写死的剧本、消极认命','越焦虑越买高价开光物'],
 enMis:['Believing paid wealth repletion changes fate','Taking the chart as fixed script, resigning passively','Buying pricier consecrated objects when anxious'],
 cnClose:'紫微斗数能帮你看清规律，但真正改运的钥匙一直在你自己手里。与其花钱买一个无法验证的「转运物」，不如顺着盘上的倾向去调整选择和行动——这才是唯一被反复验证有效的改运方式。',
 enClose:'Zi Wei Dou Shu helps you see patterns, but the key to changing fortune stays in your hands. Rather than buying unverifiable remedies, adjust choices and action along your tendencies—the only repeatedly proven way to change your luck.'},
];
