const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'ganqing',slug:'ziwei-fuqi-gong-zhuxing-kan-peiou-waixing-zhiye',focus:'夫妻宫主星看配偶',focusEn:'spouse traits from Spouse palace star',
 cnT:'紫微斗数夫妻宫主星看配偶：长相、气质与职业倾向',enT:'Reading Your Spouse From the Spouse-Palace Major Star in Zi Wei Dou Shu: Looks, Temperament and Career Lean',
 cnD:'夫妻宫主星大致勾勒你容易被吸引、也容易遇到的配偶类型：紫微偏成熟有主见、太阳偏外向阳光、太阴偏柔美细腻、贪狼偏多才魅力、武曲偏干练务实。它给的是「类型模板」而非固定某人，须结合庙旺、煞曜和对宫官禄一起看，避免对号入座。',
 enD:'The Spouse-palace major star sketches the type you are drawn to and tend to meet: Zi Wei mature and assertive, Sun outgoing and sunny, Tai Yin soft and meticulous, Tan Lang versatile and charming, Wu Qu capable and pragmatic. It gives a type template, not a fixed person—read with brilliance, malefics and opposite Career, avoiding rigid matching.',
 cnL:'夫妻宫是你「择偶雷达」的出厂设置：它不指定某个人，却显示什么气质、外形、职业的人最容易和你互相吸引。',
 enL:'The Spouse palace is your mate-selection radar\'s factory setting: not a specific person, but the temperament, looks and profession you most readily attract.',
 cnA:'有人拿夫妻宫主星当寻人启事、差一点就说不合，其实它只是倾向，真正相处还要看双方命宫、合盘和现实，模板是参考不是枷锁。',
 enA:'Used as a wanted poster, any deviation means incompatibility; it is only tendency, and real bonds need both Life palaces, synastry and reality—template as reference, not cage.',
 cnLog:['夫妻宫主星定配偶「类型基调」：紫微天府偏成熟稳重有主见、太阳偏外向担当、太阴偏温柔细腻顾家。','机月同梁系（天机天同天梁）配偶多聪明、随和或年长稳重；武曲天相系偏干练、理性、专业；杀破狼贪系偏个性强、有冲劲、魅力足。','外形气质随星性：庙旺多正面舒展、落陷减色；昌曲同会主斯文有才、魁钺主气质好、桃花星主外形出众。','职业倾向看星性与官禄对宫：阳梁昌禄利公职文教、武曲天府利金融管理、贪狼廉贞利业务艺术娱乐，须整体合参、不可单星定死。'],
 enLog:['The major star sets the spouse type: Zi Wei/Tian Fu mature and assertive, Sun outgoing responsible, Tai Yin gentle meticulous and home-oriented.','Ji-Yue-Tong-Liang types are clever, easygoing or older-steady; Wu Qu/Tian Xiang capable, rational, professional; Sha-Po-Lang/Tan strong, driven, charming.','Looks follow star nature: strong stars appear open and positive, fallen ones less so; Chang/Qu add refinement, Kui/Yue bearing, peach stars standout looks.','Career lean combines star nature with opposite Career: Sun-Liang-Chang-Lu public/education, Wu Qu/Tian Fu finance-management, Tan/Lian sales-art-entertainment—always synthesize, never fix by one star.'],
 cnStep:['先看夫妻宫主星，定配偶类型基调','看庙旺落陷，判断特质是正面发挥还是减分','看昌曲魁钺桃花，补外形气质细节','对宫官禄一起看，推职业与相处模式','记住这是倾向模板，不是指定某人','结合双方命宫与现实相处做最终判断'],
 enStep:['Read the Spouse major star for the type tone','Check brilliance for positive or reduced expression','Add Chang/Qu, Kui/Yue and peach stars for looks and bearing','Read opposite Career for profession and interaction style','Remember this is a tendency template, not a fixed person','Combine both Life palaces and real interaction for the final call'],
 cnMis:['拿主星当寻人启事，差一点就不合','单星定死职业外形','只看夫妻宫，不看对宫和合盘'],
 enMis:['Using the star as a wanted poster, rejecting near-misses','Fixing looks and career by one star','Reading Spouse alone, ignoring opposite and synastry'],
 cnClose:'夫妻宫主星是一张「择偶倾向地图」：它告诉你什么类型最让你心动、最容易走进你的生活。看懂倾向、又不被模板绑死，你才既不会错过对的人，也不会错把类型当宿命。',
 enClose:'The Spouse star is a mate-tendency map: who stirs you and enters your life most easily. Understand the tendency without being trapped by the template, and you neither miss the right person nor mistake type for fate.'},

{cat:'ganqing',slug:'ziwei-jiehun-yingqi-na-yi-nian-rueding-hunqi',focus:'结婚应期',focusEn:'marriage timing',
 cnT:'紫微斗数结婚应期怎么看：哪一年最容易定下来',enT:'Marriage Timing in Zi Wei Dou Shu: Which Year You Are Most Likely to Settle',
 cnD:'断结婚年份要多层叠加：本命夫妻宫定基调与早晚婚倾向，大限走到夫妻宫三方、且大限夫妻宫吉化，再到流年引动红鸾天喜、流年命宫或夫妻宫化禄、叠本命夫妻宫，几个条件凑齐的年份，才是高概率成婚窗口，只看一颗红鸾不够准。',
 enD:'Marriage timing needs layered overlap: the natal Spouse palace sets tone and early/late tendency; a decade reaching the Spouse trine with an auspiciously transformed decade Spouse; then a year activating Hong Luan/Tian Xi, with year Life or Spouse Hua Lu stacking natal Spouse. Years where several conditions meet are high-probability windows—one Hong Luan alone is inaccurate.',
 cnL:'本命定「会不会、早还是晚」，大限定「这十年有没有婚姻戏」，流年代「具体哪一年」，三层信号同向叠加，才是真正的应期。',
 enL:'Natal sets whether and early/late, the decade whether marriage is in play these ten years, the year which exact one; three aligned signals make real timing.',
 cnA:'有人见红鸾流年就说要结婚，结果没应，就是只看一层；也有人本命偏晚婚却在早年限硬催，反而不稳。应期是多层共振，不是单点信号。',
 enA:'A Hong Luan year predicted to end in marriage doesn\'t, from reading one layer; pushing a late-marriage chart in early years is unstable. Timing is multi-layer resonance, not a single signal.',
 cnLog:['本命层：夫妻宫星曜吉凶、是否逢煞、红鸾天喜位置，定早婚或晚婚倾向（杀破狼廉贞在夫妻多宜晚）。','大限层：大限命宫走到本命夫妻宫或其三方、大限夫妻宫化禄化科、逢红鸾天喜，这十年才有成婚大环境。','流年层：流年遇红鸾天喜、流年命宫或夫妻宫化禄、流年夫妻宫叠本命夫妻宫，几个信号在同一年凑齐为高概率窗口。','辅助：流年福德、田宅吉化（成家、置产）也佐证；信号冲突或逢忌煞的年份不宜强推，应期只给高概率区间，不给定数。'],
 enLog:['Natal layer: Spouse stars, malefics and Hong Luan/Tian Xi position set early/late tendency (Sha-Po-Lang/Lian in Spouse often favor late).','Decade layer: decade Life reaching natal Spouse or its trine, decade Spouse with Lu/Ke and Hong Luan/Tian Xi gives the marriage environment.','Year layer: year Hong Luan/Tian Xi, year Life/Spouse Hua Lu, year Spouse stacking natal Spouse—several signals in one year make a high-probability window.','Support: auspicious year Happiness/Property (forming a home, buying property) corroborates; conflicting or Ji/malefic years shouldn\'t be forced—timing gives a probability range, not fixed fate.'],
 cnStep:['先看本命夫妻宫，定早婚还是晚婚倾向','找大限走到夫妻宫三方且夫妻宫吉化的十年','在该十年内逐流年找红鸾天喜引动','叠加流年命宫/夫妻宫化禄与叠本命夫妻宫','几个信号同年凑齐，标为高概率成婚窗口','逢忌煞冲突年份不强推，尊重现实关系进度'],
 enStep:['Read natal Spouse for early/late tendency','Find the decade reaching Spouse trine with auspicious decade Spouse','Within it, scan years for Hong Luan/Tian Xi activation','Stack year Life/Spouse Lu and stacking on natal Spouse','Mark years with several aligned signals as high-probability windows','Don\'t force Ji/malefic conflict years; respect real relationship progress'],
 cnMis:['见红鸾就断当年结婚','只看流年不看大限环境','晚婚盘在早年限硬催婚'],
 enMis:['Predicting marriage from Hong Luan alone','Reading the year without decade context','Forcing a late-marriage chart in early years'],
 cnClose:'结婚应期是「本命倾向×大限环境×流年触发」的共振。与其盯着某颗婚喜星，不如把三层信号叠起来找那几年——窗口对上了、关系也到了，才是水到渠成的好时候。',
 enClose:'Marriage timing is the resonance of natal tendency, decade environment and year trigger. Rather than fixating on a romance star, stack three layers to find those years; when the window and the relationship both align, settling down comes naturally.'},

{cat:'ganqing',slug:'ziwei-taohuajie-lantaohua-zenme-biren-bu-cai-keng',focus:'桃花劫与烂桃花',focusEn:'peach-blossom trouble and bad romance',
 cnT:'紫微斗数桃花劫和烂桃花怎么分辨、怎么避开',enT:'How to Tell Peach-Blossom Trouble From Bad Romance in Zi Wei Dou Shu—and Avoid the Trap',
 cnD:'正桃花主健康、能走向稳定的缘分，多与红鸾天喜、化禄、吉曜相关；烂桃花和桃花劫主消耗、纠缠、破财或受伤，多见贪狼廉贞逢煞忌、咸池天姚叠煞、夫妻宫化忌。分辨关键看星曜组合与落宫，避开靠设边界、慢确认、不在情绪低谷期做感情决定。',
 enD:'Healthy romance tends toward stability, tied to Hong Luan/Tian Xi, Hua Lu and auspicious stars; bad romance and peach-blossom trouble drain, entangle, cost money or wound, often Tan Lang/Lian Zhen with malefics/Ji, Xian Chi/Tian Yao with malefics, or Spouse Hua Ji. Distinguish by star combinations and palace; avoid through boundaries, slow confirmation and no romantic decisions in emotional lows.',
 cnL:'桃花多不等于桃花好：让你变好、走向稳定的是正缘，让你内耗、破财、失去自我的是劫，命盘能提前标出你容易在哪类关系里栽跟头。',
 enL:'More romance is not better romance: bonds that improve you and stabilize are right; those that drain, cost or erase self are trouble—the chart flags where you tend to stumble.',
 cnA:'有人把强烈心动当正缘、把纠缠当深情，尤其在空窗或低谷期最易遇烂桃花；看懂自己的桃花弱点、把确认节奏放慢，能避开大部分劫。',
 enA:'Intense infatuation is taken as destiny and entanglement as devotion, especially when lonely or low; knowing your romance weak spot and slowing confirmation avoids most trouble.',
 cnLog:['正桃花信号：红鸾天喜引动、夫妻宫或福德化禄、吉星会照，关系顺畅、彼此成就、能走向承诺。','烂桃花信号：贪狼廉贞逢擎羊陀罗火铃化忌、咸池天姚叠煞、夫妻宫化忌冲，主短暂激情、纠缠控制、破财或情伤。','高风险情境：大限流年引动煞忌桃花、又恰逢情绪低谷、空窗、经济压力时，最易把烂桃花当救命稻草。','规避方法：设边界与底线、拉长观察期、重大投入（钱、同居、闪婚）慢半拍、不在低谷期定终身，必要时听亲友客观意见。'],
 enLog:['Healthy signals: Hong Luan/Tian Xi activation, Spouse/Happiness Hua Lu, auspicious trine—smooth, mutually building, moving to commitment.','Bad signals: Tan Lang/Lian Zhen with Yang/Tuo/Fire-Bell/Ji, Xian Chi/Tian Yao with malefics, Spouse Ji clash—short passion, control-entanglement, loss or heartbreak.','High-risk context: a decade/year activating malefic romance during emotional low, a gap or financial pressure most mistakes bad romance for a lifeline.','Avoidance: boundaries and bottom lines, longer observation, delay big commitments (money, cohabitation, flash marriage), no lifelong calls in low points, seek objective advice.'],
 cnStep:['看夫妻宫与桃花星是吉化还是逢煞忌','分清这段关系是成就你还是消耗你','识别自己的桃花弱点（重激情/怕孤单/心软）','拉长确认期，重大投入一律慢半拍','不在空窗或情绪低谷做感情决定','发现控制、纠缠、破财信号及时止损'],
 enStep:['See whether Spouse and romance stars are auspicious or malefic','Tell if the bond builds or drains you','Identify your weak spot (thrill/fear of being alone/soft heart)','Extend confirmation; delay all big commitments','Make no romantic decision in a gap or emotional low','Cut losses at control, entanglement or financial-drain signals'],
 cnMis:['把强烈心动当正缘','把纠缠控制当深情','低谷期抓烂桃花当救命稻草'],
 enMis:['Taking intense infatuation as destiny','Mistaking control-entanglement for devotion','Grabbing bad romance as a lifeline in low points'],
 cnClose:'命盘不阻止你爱谁，但能提醒你容易在哪种关系里受伤。把正桃花和桃花劫分清楚，再用边界和慢确认替自己把关，热烈可以有，止损更要快。',
 enClose:'The chart does not choose whom you love but warns where you get hurt. Distinguish healthy romance from trouble, guard with boundaries and slow confirmation—passion is fine, cutting losses must be faster.'},

{cat:'ganqing',slug:'ziwei-wanhun-mingpan-tezheng-wei-shenme-wanhun-geng-wen',focus:'晚婚命盘特征',focusEn:'late-marriage chart signs',
 cnT:'紫微斗数晚婚的命盘特征：为什么有些人晚婚反而更稳',enT:'Late-Marriage Chart Signs in Zi Wei Dou Shu: Why Some People Are More Stable Marrying Later',
 cnD:'夫妻宫见七杀破军廉贞擎羊陀罗、孤辰寡宿华盖、或夫妻宫化忌的人，多主感情成熟晚、早婚易磨合失败，更适合晚婚；晚婚不是「剩下」，而是等自我稳定、识人能力到位后再进入关系，往往质量更高、更持久。',
 enD:'Spouse palace with Qi Sha/Po Jun/Lian Zhen, Yang/Tuo, Gu Chen/Gua Su/Hua Gai, or Spouse Hua Ji often means emotional maturity arrives late and early marriage struggles to磨合, suiting later marriage; it is not being left over but entering bonds after the self stabilizes and judgment matures—often higher quality and more lasting.',
 cnL:'晚婚倾向写在盘上，本质是「你的自我和节奏需要更长时间定型」，等自己稳了再结婚，不是退而求其次，而是顺势而为。',
 enL:'Late-marriage tendency is on the chart; its essence is needing longer for self and rhythm to settle—marrying stable is not settling, but going with the grain.',
 cnA:'有人被「年纪到了」催着早婚，恰恰是晚婚盘，结果磨合失败；看懂自己的节奏，把用来焦虑的时间换成自我成长，晚婚反成优势。',
 enA:'Pushed by age into early marriage despite a late chart, people face failed磨合; knowing your rhythm and trading anxiety for growth turns late marriage into an edge.',
 cnLog:['晚婚信号一：夫妻宫坐杀破狼、廉贞或逢擎羊陀罗火铃，关系历程多磨、需要阅历才驾驭。','晚婚信号二：夫妻宫、福德见孤辰寡宿华盖，重精神空间、不轻易将就，天然需要更长选择期。','晚婚信号三：夫妻宫化忌或对宫官禄强势，前期重心在事业或自我课题，感情成熟晚。','晚婚之利：自我、经济、识人和情绪管理更成熟，能识别合适的人并经营关系；关键不是拖，而是在等待期持续成长、不关闭可能性。'],
 enLog:['Sign one: Spouse with Sha-Po-Lang/Lian Zhen or Yang/Tuo/Fire-Bell means a winding relational path needing experience.','Sign two: Spouse/Happiness with Gu Chen/Gua Su/Hua Gai values mental space and won\'t settle, naturally needing a longer selection period.','Sign three: Spouse Ji or a strong opposite Career puts early focus on work or self-lessons, with late emotional maturity.','The upside: more mature self, finances, judgment and emotion management to recognize and keep the right person; the key is not delay but growing while staying open.'],
 cnStep:['看夫妻宫主星与煞曜，判断是否多磨型','查孤寡华盖与化忌，评估精神空间需求','若是晚婚倾向，接受节奏、不被催婚打乱','等待期专注事业、情绪成熟和自我稳定','保持社交与可能性，不把晚婚当封闭','关系出现时用成熟度而非年龄做判断'],
 enStep:['Read Spouse stars and malefics for a winding type','Check solitude stars and Ji for mental-space needs','If late-inclined, accept the rhythm despite pressure','Use the wait for career, emotional maturity and stability','Stay social and open; late marriage is not closure','When a bond appears, judge by maturity not age'],
 cnMis:['被年龄催着早婚，逆了自己的盘','把晚婚当失败而焦虑封闭','等待期不成长，只是干等'],
 enMis:['Rushing early marriage against one\'s own chart','Treating late marriage as failure, closing off','Just waiting without growing in the meantime'],
 cnClose:'晚婚盘不是姻缘差，而是「好饭不怕晚」。当你需要更长时间把自己活稳，晚一点进入婚姻反而是对关系负责；把等待期过成成长期，你的婚姻会更稳、更有质量。',
 enClose:'A late-marriage chart is not poor romance but good things worth the wait. Needing longer to settle yourself, marrying later is responsible to the bond; turn the wait into growth and your marriage is steadier and higher quality.'},

{cat:'ganqing',slug:'ziwei-yidi-lian-jushaolidu-mingpan-zenme-weichi',focus:'异地恋聚少离多',focusEn:'long-distance relationship chart',
 cnT:'紫微斗数异地恋、聚少离多的盘怎么看、怎么维持',enT:'Long-Distance and Often-Apart Relationships in Zi Wei Dou Shu: Reading and Sustaining Them',
 cnD:'夫妻宫逢天马、迁移宫与夫妻宫强联动、或夫妻宫见孤寡、煞星的人，感情易带异地、聚少离多、奔波相会的色彩。异地不是必分，关键看有没有稳定的信任结构（化禄化科、吉星）和明确的结束异地计划，逢化忌煞重则更需经营与安全感建设。',
 enD:'Spouse with Tian Ma, strong Travel-Spouse linkage, or solitude/malefic stars tends toward long-distance, time-apart and travel-to-meet romance. Distance is not certain breakup; the keys are a stable trust structure (Lu/Ke, auspicious stars) and a clear plan to end the distance, while heavy Ji/malefics need active trust-building.',
 cnL:'命盘显示的是「你们容易以什么形态相处」，常奔波的盘更考验信任和规划，能不能成，看的是结构和经营，不是距离本身。',
 enL:'The chart shows your likely relationship form; apart-heavy bonds test trust and planning more—success depends on structure and effort, not distance itself.',
 cnA:'有人一见夫妻宫逢天马就说必分，其实很多跨国跨城婚姻很稳，差别在有没有共同目标、结束异地的时间表和高频而稳定的沟通。',
 enA:'Spouse Tian Ma is read as certain breakup, yet cross-border marriages stay stable; the difference is shared goals, a timeline to close distance and steady communication.',
 cnLog:['异地信号：夫妻宫逢天马、迁移宫化禄化忌入夫妻、夫妻宫对宫官禄强（因工作奔波），主缘分带迁动、易异地或聚少离多。','稳的条件：夫妻宫化禄化科、吉星拱照，主信任足、能沟通、感情有黏性；再加共同的结束异地计划则可长久。','风险信号：夫妻宫化忌、逢煞孤寡，主安全感不足、易猜忌、沟通一断就生变，须刻意补信任。','经营方法：固定高频沟通、透明行程与社交、设共同目标和团聚时间表、尽早规划同城，重大节点多见面、不靠猜。'],
 enLog:['Distance signs: Spouse with Tian Ma, Travel Lu/Ji flying into Spouse, strong opposite Career (work travel)—romance carries movement, often apart.','Stable conditions: Spouse Lu/Ke with auspicious support means trust, communication and bond stickiness; a shared plan to end distance makes it lasting.','Risk signs: Spouse Ji with malefics/solitude means weak security, suspicion and change when communication breaks—deliberately build trust.','Maintenance: regular high-frequency contact, transparent schedules, shared goals and reunion timeline, plan same-city early, meet at key moments instead of guessing.'],
 cnStep:['看夫妻宫是否逢天马、与迁移强联动','查化禄化科与吉星，判断信任结构稳不稳','化忌煞重者把安全感建设当首要任务','建立固定高频沟通和透明机制','共同制定结束异地的时间表','关键节点尽量见面，减少纯文字猜忌'],
 enStep:['See whether Spouse has Tian Ma and strong Travel linkage','Check Lu/Ke and auspicious stars for trust structure','With heavy Ji/malefics, make security the priority','Build regular contact and transparency','Set a shared timeline to end the distance','Meet at key moments, reducing text-based suspicion'],
 cnMis:['见天马就断异地必分','只靠感情、不给结束异地的计划','沟通一断就靠猜，激化不安全感'],
 enMis:['Predicting certain breakup from Tian Ma','Relying on feeling with no plan to close distance','Guessing when communication breaks, worsening insecurity'],
 cnClose:'异地恋考验的从来不是爱得够不够，而是信任结构和未来规划清不清。命盘若带聚少离多色彩，就更早把沟通、透明和「什么时候在一起」定下来——距离是过程，同城才是目标。',
 enClose:'Long-distance tests not love\'s amount but trust structure and future planning. If your chart leans apart, fix communication, transparency and a when-together date early—distance is the process, same-city the goal.'},
];
