const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'sihua',slug:'ziwei-shisi-zhuxing-hualu-chayi-na-ke-xing-rongyi-decai',focus:'十四主星化禄差异',focusEn:'major stars Hua Lu differences',
 cnT:'紫微斗数十四主星化禄差别：同样是化禄，得财方式完全不同',enT:'How Each Major Star\'s Hua Lu Differs in Zi Wei Dou Shu: Same Gain, Different Path',
 cnD:'化禄主顺遂、得到与机缘，但落在哪颗主星上，「得什么、怎么得」差别极大：武曲化禄是实财现金、太阴化禄是资产与暗财、天机化禄是点子生财、天梁化禄是荫蔽之财、廉贞化禄靠人际与魅力。只看「有化禄」远远不够，要看星性定得财方式。',
 enD:'Hua Lu governs smoothness, gain and chance, but which major star it transforms decides what and how one gains: Wu Qu Lu is cash, Tai Yin Lu assets and hidden income, Tian Ji Lu ideas, Tian Liang Lu shelter-based gain, Lian Zhen Lu people and charm. Seeing Hua Lu is far from enough—star nature sets the earning path.',
 cnL:'化禄是「得到」这个动作，主星是「得到的东西和途径」，同一颗化禄落在武曲和贪狼身上，一个是实打实的钱，一个是机会与人缘带来的财。',
 enL:'Hua Lu is the action of gaining; the major star is the object and path. The same Lu on Wu Qu versus Tan Lang means hard cash versus opportunity-and-network money.',
 cnA:'有人见化禄就笼统说财运好，结果天机化禄的人去囤房、武曲化禄的人去搞人脉变现，方式全错；读懂星性，才知道自己的禄该怎么接。',
 enA:'People say wealth generically at Hua Lu; a Tian Ji Lu person hoarding property or Wu Qu person monetizing connections gets the path wrong. Read star nature to know how to receive your Lu.',
 cnLog:['化禄是四化之一，主缘、得、顺遂，但「得什么」由被化的主星星性决定，不能一概而论。','财星化禄最实：武曲化禄主正财现金、理财能力；太阴化禄主资产、不动产、储蓄与暗财、被动收入。','机巧星化禄主「以智生财」：天机化禄靠策划点子、贪狼化禄靠机会人脉与多才、廉贞化禄靠交际魅力与事业经营。','荫名星化禄偏非现金：天梁化禄主荫蔽、照顾与名声带来的利，天同化禄主享受与福气，化禄落星不同，得财路径与节奏完全不同。'],
 enLog:['Hua Lu governs encounter, gain and smoothness, but what is gained is set by the transformed star\'s nature, never one-size-fits-all.','Wealth-star Lu is most concrete: Wu Qu Lu for earned cash and finance skill; Tai Yin Lu for assets, real estate, savings and passive income.','Ingenuity-star Lu earns through intellect: Tian Ji Lu planning/ideas, Tan Lang Lu opportunity/network/versatility, Lian Zhen Lu social charm and business.','Shelter/repute-star Lu is non-cash: Tian Liang Lu shelter and reputation benefits, Tian Tong Lu enjoyment and blessing; different stars mean wholly different paths and pacing.'],
 cnStep:['先找全盘化禄落在哪颗主星','按星性判断这份「得」是现金、资产、点子还是人缘','武曲太阴禄：走理财、资产、专业变现路线','天机贪狼廉贞禄：走创意、机会、人脉经营路线','天梁天同禄：善用荫蔽、口碑与福气，不强求快钱','结合落宫，确定这份禄具体在哪个领域兑现'],
 enStep:['Find which major star Hua Lu lands on','By star nature classify the gain: cash, assets, ideas or network','Wu Qu/Tai Yin Lu: finance, assets, professional monetization','Tian Ji/Tan Lang/Lian Zhen Lu: creativity, opportunity, network routes','Tian Liang/Tian Tong Lu: use shelter, reputation and blessing, not quick cash','Combine the palace to fix the domain where this Lu pays out'],
 cnMis:['见化禄就笼统断发财','不看星性，用错得财方式','把荫财、福分当成现金收入'],
 enMis:['Predicting wealth generically from Hua Lu','Ignoring star nature, using the wrong earning path','Mistaking shelter/blessing for cash income'],
 cnClose:'化禄人人会看，看出「怎么得」才是水平。武曲的禄在账上、太阴的禄在资产里、天机的禄在点子里——顺着你那颗化禄主星的本性去接财，那份顺遂才真正落袋。',
 enClose:'Anyone can spot Hua Lu; seeing how one gains is skill. Wu Qu\'s Lu is on the ledger, Tai Yin\'s in assets, Tian Ji\'s in ideas—receive it along your transformed star\'s nature and the smoothness truly lands.'},

{cat:'sihua',slug:'ziwei-shisi-zhuxing-huaji-chayi-na-kekan-zui-kashen',focus:'十四主星化忌差异',focusEn:'major stars Hua Ji differences',
 cnT:'紫微斗数十四主星化忌差别：同样是化忌，卡点完全不同',enT:'How Each Major Star\'s Hua Ji Differs in Zi Wei Dou Shu: Same Hook, Different Sticking Point',
 cnD:'化忌主执着、卡点与内收，但落在哪颗星上，「卡在哪、怎么磨」截然不同：武曲化忌主资金周转与决断之困、太阴化忌主情绪与女性亲属之忧、天机化忌主想太多钻牛角尖、巨门化忌主口舌是非、文昌化忌主文书失误。看化忌必须连同星性，才知道真正的课题。',
 enD:'Hua Ji governs attachment, blockage and inward gathering, but the star decides where and how one is stuck: Wu Qu Ji is cash-flow and decisional trouble, Tai Yin Ji emotion and female-relative worry, Tian Ji Ji overthinking, Ju Men Ji verbal dispute, Wen Chang Ji document error. Hua Ji must be read with star nature to reveal the real lesson.',
 cnL:'化忌是「卡住」这个动作，主星决定卡在什么事上，同样是忌，武曲卡在钱、天机卡在念头、巨门卡在嘴，解法自然完全不同。',
 enL:'Hua Ji is the action of sticking; the star sets the matter—Wu Qu stuck on money, Tian Ji on thoughts, Ju Men on words—so solutions differ entirely.',
 cnA:'有人见任何化忌都用一句「多注意」带过，结果武曲化忌的人去调节情绪、天机化忌的人去补现金流，补错方向；分清星性，化忌的课题才解得准。',
 enA:'Every Ji gets a vague take-care; a Wu Qu Ji person regulating emotion or Tian Ji Ji fixing cash flow addresses the wrong thing. Distinguish star nature to solve the real lesson.',
 cnLog:['化忌主收敛、执着、亏欠感与卡点，具体卡在哪由被化主星的星性决定。','财星化忌：武曲化忌主资金周转、决断与破财之忧；太阴化忌主情绪内耗、家宅或女性亲属相关牵挂。','机巧星化忌：天机化忌主想太多、钻牛角尖、计划反复；贪狼化忌主欲望落空、多而不精；廉贞化忌主情绪、关系或制度性困扰。','口舌文书星化忌：巨门化忌主口舌是非、沟通受阻；文昌文曲化忌主文书、考试、合同失误，须按星性给不同的防范重点。'],
 enLog:['Hua Ji governs gathering, attachment, sense of lack and sticking; the stuck point is set by the transformed star.','Wealth-star Ji: Wu Qu Ji cash-flow, decision and loss worry; Tai Yin Ji emotional drain, home/female-relative attachment.','Ingenuity-star Ji: Tian Ji Ji overthinking and plan loops; Tan Lang Ji frustrated desire and scattered breadth; Lian Zhen Ji emotional, relational or institutional trouble.','Speech/document-star Ji: Ju Men Ji disputes and blocked communication; Chang/Qu Ji document, exam and contract errors—each needs different prevention by star nature.'],
 cnStep:['找全盘化忌落在哪颗主星','按星性判断卡点：钱、情绪、念头还是口舌文书','武曲化忌重现金流和合同，不硬扛周转','天机化忌练「停止反刍」、给决策设时限','巨门昌曲化忌重沟通留痕、文书反复核对','结合落宫确定课题领域，对症而不是笼统担心'],
 enStep:['Find which major star Hua Ji lands on','Classify the sticking point: money, emotion, thought, speech or documents','Wu Qu Ji: secure cash flow and contracts, don\'t white-knuckle turnover','Tian Ji Ji: stop rumination, set decision deadlines','Ju Men/Chang-Qu Ji: document communication, double-check paperwork','Combine the palace to target the lesson, not vague worry'],
 cnMis:['所有化忌都一句「多注意」带过','不看星性，补错方向','把不同星的化忌当成同一种凶'],
 enMis:['Dismissing every Ji with vague caution','Ignoring star nature, fixing the wrong thing','Treating different stars\' Ji as one misfortune'],
 cnClose:'化忌不可怕，看不懂化忌卡在哪才可怕。武曲的忌在钱上、天机的忌在念头上、巨门的忌在嘴上——认清你那颗化忌主星的课题，卡点才会变成可以下手解决的具体问题。',
 enClose:'Hua Ji is not scary; not seeing where it sticks is. Wu Qu\'s Ji is money, Tian Ji\'s thoughts, Ju Men\'s words—recognize your transformed star\'s lesson and the block becomes a concrete, solvable problem.'},

{cat:'sihua',slug:'ziwei-huaquan-xiangjie-zhangkong-lixing-bushi-badan',focus:'化权详解',focusEn:'Hua Quan explained',
 cnT:'紫微斗数化权详解：掌控、行动力与压力的一体两面',enT:'Hua Quan Explained in Zi Wei Dou Shu: Control, Drive and Pressure as Two Sides of One Coin',
 cnD:'化权属火、主掌控、扩张、行动力与话语权，让所落宫的能量变强、变主动，正面是有魄力、能扛事、有领导与决断力，负面是强势、控制欲、压力大、容易孤行。它和化禄的「顺得」不同，化权是「争来、扛起来」，用得好是领导力，用过头是压迫感。',
 enD:'Hua Quan is fire, governing control, expansion, action and say-so, strengthening and activating its palace. Positively boldness, responsibility, leadership and decisiveness; negatively dominance, control, pressure and going it alone. Unlike Hua Lu\'s smooth gain, Quan is contested and shouldered—leadership when well used, oppression when overdone.',
 cnL:'化禄是「东西来找你」，化权是「你去拿、去扛」，它给的是力量和主导权，但力量越大，对自己和身边人的压力也越大。',
 enL:'Lu is things coming to you, Quan your taking and carrying; it gives power and initiative, but greater force means greater pressure on yourself and those nearby.',
 cnA:'有人一见化权就说掌权升官，忽略化权也主劳碌、强势和关系紧张；真正成熟的化权，是有掌控力却不控制别人，能扛事也懂得分权。',
 enA:'Hua Quan is read as promotion while ignoring toil, dominance and strained relations; mature Quan holds control without controlling others, able to carry and to share power.',
 cnLog:['化权五行属火，主权力、掌控、扩张、行动与竞争，让落宫主题变主动、变强、变快。','正面：有魄力、决断快、执行力强、能扛责任、有领导统御力，适合管理、开拓、攻坚和需要拍板的位置。','负面：强势、好掌控、刚愎、给人压迫感、亲力亲为易过劳，落六亲宫则关系里易有主导权之争。','调和：与化禄同会「禄权」则既有资源又有掌控、最佳；与化科同会则刚中带柔、有名望；逢化忌则掌权中带阻、须防硬撑。'],
 enLog:['Hua Quan is fire governing authority, control, expansion, action and competition, making its palace proactive, stronger and faster.','Positive: bold, decisive, strong executor who carries responsibility and leads—suited to management, frontier work and decision seats.','Negative: dominant, controlling, stubborn, pressuring, prone to overwork; in family palaces it brings power struggles in relationships.','Harmony: with Lu it pairs resources and control (best); with Ke it is firm yet gentle with repute; with Ji authority meets obstruction—avoid white-knuckling.'],
 cnStep:['定位化权落在哪宫，判断掌控欲集中在哪','用在事业：主动承担、练决断和带团队','警惕强势：刻意放权、听意见，避免亲力亲为','在六亲宫：关系里少争输赢、多协商','逢禄科配合时大胆主导，逢忌时减压不硬扛','把掌控力用于自我管理，而非控制他人'],
 enStep:['Locate Hua Quan to see where control concentrates','At work: take initiative, practice decision and team leadership','Guard dominance: deliberately delegate and listen, avoid doing all','In family palaces: win less, consult more in relationships','Lead boldly with Lu/Ke; with Ji reduce pressure instead of forcing','Direct control at self-management, not controlling others'],
 cnMis:['见化权只说升官掌权','忽略强势和过劳的一面','把掌控力用在控制身边人'],
 enMis:['Reading Hua Quan only as promotion','Ignoring dominance and overwork','Using control to dominate those nearby'],
 cnClose:'化权是「把事情扛起来」的力量。它让你有主导权和执行力，也容易让你太硬太累；学会掌权而不控人、刚强里留三分柔，化权就从压迫感，变成别人愿意追随的领导力。',
 enClose:'Hua Quan is the power to carry matters. It gives initiative and execution but can make you hard and tired; lead without controlling, keep softness within firmness, and it turns from pressure into leadership others willingly follow.'},

{cat:'sihua',slug:'ziwei-huake-xiangjie-mingsheng-wenhua-guihe-guiren',focus:'化科详解',focusEn:'Hua Ke explained',
 cnT:'紫微斗数化科详解：名声、贵人与逢凶化吉的缓和之力',enT:'Hua Ke Explained in Zi Wei Dou Shu: Reputation, Mentors and the Softening Force That Averts Trouble',
 cnD:'化科属木、主名声、文采、科甲、贵人和缓和，让所落宫的能量变得平顺、有名、被认可，正面是口碑好、有贵人、考试文书顺、能化解冲突，负面是爱面子、重名声、有时偏于表面。它不像化禄给实利、化权给力量，化科给的是「名」和「转圜」。',
 enD:'Hua Ke is wood, governing reputation, literary grace, scholarly success, mentors and smoothing, making its palace even, known and recognized. Positively good name, mentors, smooth exams/documents and conflict resolution; negatively face-consciousness, repute-focus and occasional superficiality. Unlike Lu\'s substance or Quan\'s force, Ke gives name and room to maneuver.',
 cnL:'禄给实得、权给力量、科给名声：化科所在的地方，容易被看见、被认可、有人帮你打圆场，是四化里最「柔」的一颗。',
 enL:'Lu gives gain, Quan force, Ke reputation: where Ke sits is easily seen, recognized and smoothed over for you—the softest transformation.',
 cnA:'有人觉得化科不实在、不如化禄，其实化科主贵人缘和口碑，关键时候能逢凶化吉、让事情有名分地解决；但要防只爱面子、重名不重实。',
 enA:'Ke seems less real than Lu, yet it brings mentors and reputation, averting trouble and giving matters a legitimate resolution; guard against loving face over substance.',
 cnLog:['化科五行属木，主科甲、名声、文采、贵人、缓和与解厄，让落宫主题平顺、外显、被认可。','正面：口碑好、有名望、考试文书合同顺、易得师长贵人提携，冲突时有人调解、逢凶化吉。','利学业考试、职称评审、品牌名声、公关调解、文化教育与一切需要「名分和认可」的事。','负面：好面子、重名声、有时为了好看而不够务实；与禄权相会最佳（名利权兼备），逢忌则名声易受损、须重诚信。'],
 enLog:['Hua Ke is wood governing scholarly success, reputation, literary grace, mentors, smoothing and rescue, making its palace even, visible and recognized.','Positive: good name, smooth exams/documents/contracts, teacher-mentor support, mediation and trouble-averting in conflict.','Favors study/exams, title evaluation, brand repute, PR mediation, culture/education and anything needing legitimacy and recognition.','Negative: face-conscious, repute-focused, sometimes polished over substance; best with Lu/Quan (name, gain, authority), with Ji reputation is at risk—prioritize integrity.'],
 cnStep:['定位化科落在哪宫，判断名声与贵人落在哪','学业考试职称：引动化科时积极应考、申报','事业上经营口碑、个人品牌和专业形象','冲突中善用调解与沟通，给彼此台阶','务实打底，别只追求好看和面子','逢忌时重诚信、守声誉，避免名实不符'],
 enStep:['Locate Hua Ke to see where reputation and mentors fall','For exams/titles: sit and apply when Ke activates','At work build word-of-mouth, personal brand and professional image','In conflict use mediation and communication, giving face both ways','Ground in substance, not mere appearance','With Ji, prioritize integrity and guard reputation against name-substance gaps'],
 cnMis:['觉得化科不实在、忽略贵人运','只爱面子重名声，不重实质','逢化科化忌还透支信誉'],
 enMis:['Dismissing Ke as unreal, ignoring mentor luck','Loving face over substance','Spending credibility when Ke meets Ji'],
 cnClose:'化科给的是「被认可、有人帮」的力量。它不直接发钱、也不直接给权，却让你有名声、有贵人、关键处能转圜——把口碑做实，这颗最柔的化，会在你看不见的地方替你铺路。',
 enClose:'Hua Ke gives recognition and help. It neither pays nor empowers directly, yet brings repute, mentors and room to maneuver at key moments—make your name solid, and this softest transformation quietly paves your way.'},
];
