const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'geju',slug:'ziwei-matou-daijian-qingyang-zai-wu-fansha-chenggui',focus:'马头带剑格',focusEn:'horse head bearing sword pattern',
 cnT:'紫微斗数马头带剑格：擎羊在午，为什么反煞成贵、他乡立业',enT:'Horse-Head-Bearing-Sword in Zi Wei Dou Shu: Why Qing Yang in Wu Turns Malefic to Rank and Builds Away From Home',
 cnD:'马头带剑指擎羊在午宫守命，尤丙戊年生人、无空劫忌冲破者，反把擎羊的刚猛炼成武贵，主威镇边疆、异地扬名、武职或竞争性行业荣显，属「煞星得地、化煞为权」的典型；若落陷逢煞无制则仍是劳碌伤灾，成格条件很严格。',
 enD:'Horse-head-bearing-sword means Qing Yang guards Life in Wu, especially for Bing/Wu birth stems and without empty/Ji break; it refines the malefic\'s ferocity into martial rank—guarding the frontier, fame away from home, distinction in uniform or competitive fields, a classic case of a malefic in its right place converting to authority. Fallen and unrestrained it remains toil and injury; formation conditions are strict.',
 cnL:'同一颗擎羊，落对宫位、得对条件就从「伤」变「权」，马头带剑讲的是煞星不是不能用，而是要得地、有制、配上开创的胆识。',
 enL:'The same Qing Yang, in the right palace and conditions, turns from harm to authority—the pattern shows malefics are not unusable but need the right place, restraint and pioneering nerve.',
 cnA:'有人一见擎羊在午就套马头带剑断富贵，忽略必须无空劫冲破、看年干和庙旺，条件不全时反而是劳碌伤灾，成格与否要逐条核对。',
 enA:'People apply the pattern to any Qing Yang in Wu while ignoring the no-empty-break rule, birth stem and brilliance; incomplete conditions mean toil and injury, so verify formation point by point.',
 cnLog:['成格：擎羊在午宫守命，丙、戊年生人最正，且无地空地劫化忌冲破、有吉星拱照，方为马头带剑（带箭）。','象义：午为火地、擎羊阳金，火炼真金，化煞为权，主刚毅果决、武贵、竞争性强，利军警、外科、工程、竞技、开拓型岗位。','发展方式：多主离乡背井、异地或边疆、跨区域立业而显贵，「马头」本身带驿马奔动之意。','破格：落陷、逢空劫火铃化忌无制，则不成格，反主劳碌、伤灾、刚愎，须以专业和情绪管理收敛。'],
 enLog:['Formation: Qing Yang guards Life in Wu, truest for Bing/Wu stems, with no Di Kong/Di Jie/Hua Ji break and auspicious support—horse-head bearing sword.','Meaning: Wu is fire, Qing Yang yang metal; fire refines true gold, converting malefic to authority—resolute, martial-rank, competitive, favoring police, surgery, engineering, sports and frontier roles.','Path: often leaving home to rise in distant/frontier or cross-region work; horse-head itself carries movement.','Break: fallen with unrestrained empty/Fire-Bell/Ji, no pattern forms—toil, injury and stubbornness instead, needing expertise and emotion management.'],
 cnStep:['先确认擎羊是否在午守命','核对年干（丙戊最正）与有无空劫忌冲破','查吉星拱照与主星强弱，判断是否真成格','成格则走竞争性、武职、技术攻坚、异地开拓路线','主动拥抱跨区域发展，不困守原地','破格则按普通擎羊收敛锋芒、防伤灾硬碰'],
 enStep:['Confirm Qing Yang guards Life in Wu','Check birth stem (Bing/Wu truest) and any empty/Ji break','Check auspicious support and major-star strength for true formation','If formed, take competitive, uniform, hard-technique or frontier routes','Embrace cross-region development rather than staying local','If broken, treat as ordinary Qing Yang: rein in edge, prevent injury and clash'],
 cnMis:['擎羊在午就一律套贵格','忽略无空劫冲破等严格条件','破格还硬走武贵路线，反招伤灾'],
 enMis:['Applying the noble pattern to any Qing Yang in Wu','Ignoring strict no-break conditions','Forcing a martial-rank route on a broken chart, courting injury'],
 cnClose:'马头带剑是「煞星得地」的范本：刚猛不是缺点，关键看有没有被炼化成权。逐条核对成格条件，再把那份刚毅用在异地开拓和硬骨头竞争上，反煞成贵才成立。',
 enClose:'The pattern is a model of a malefic in its place: ferocity is not a flaw if refined into authority. Verify every condition, then aim that resolve at cross-region frontier work and hard competition—and malefic converts to rank.'},

{cat:'geju',slug:'ziwei-junchen-qinghui-ziwei-zuoming-qunchen-fuzuo',focus:'君臣庆会格',focusEn:'ruler-ministers celebration pattern',
 cnT:'紫微斗数君臣庆会格：紫微坐命、百官朝拱的领袖格局',enT:'Ruler-Ministers Celebration in Zi Wei Dou Shu: Zi Wei Guarding Life With a Full Court of Assistants',
 cnD:'君臣庆会指紫微星坐命，天府、天相、左辅、右弼、文昌、文曲、禄存等百官在三方四正朝拱、且无煞冲破，主领袖气质、组织能力强、易得团队拥戴而居管理要职，加禄存吉化更佳；若辅曜稀少或逢煞，则只是孤君，格局大打折扣。',
 enD:'Ruler-ministers celebration means Zi Wei guards Life while Tian Fu, Tian Xiang, Zuo Fu, You Bi, Chang, Qu and Lu Cun court it across the trine without malefic break—leadership, strong organization and team support for management roles, better with Lu Cun; sparse assistants or malefics leave a lone ruler, greatly weakening the pattern.',
 cnL:'紫微是君，辅曜是臣，孤君无道、众臣扶君才成气候，这格讲的是「领导不是一个人强，而是能聚起一整套班底」。',
 enL:'Zi Wei is ruler, assistants the court; a lone ruler has no way, only a supported court forms climate—leadership is not one person\'s strength but assembling a whole team.',
 cnA:'有人紫微坐命就自称帝王命，却不看有没有百官朝拱；没有辅弼昌曲的紫微只是孤高、凡事亲力亲为，成不成都累，差别就在有没有「臣」。',
 enA:'Zi Wei in Life is called an emperor destiny without checking the court; without Zuo-You/Chang-Qu it is merely aloof and hands-on, exhausted either way—the difference is the ministers.',
 cnLog:['成格：紫微守命，三方四正会天府天相、左辅右弼、文昌文曲、天魁天钺、禄存等众吉，无煞忌冲破。','象义：君主得百官辅佐，主气度、统筹、领导力与贵人运，宜管理、行政、政务、企业负责人，能聚人成事。','加分：再会禄存化禄化权，主既贵且富、有实权；会昌曲主有谋略与文名。','破格：辅曜稀少为「君臣不义/孤君」，逢擎羊陀罗火铃空劫则领导力变独断、助力少、高处不胜寒。'],
 enLog:['Formation: Zi Wei guards Life with Tian Fu/Tian Xiang, Zuo-You, Chang-Qu, Kui-Yue and Lu Cun across the trine, no malefic/Ji break.','Meaning: a ruler with a full court—bearing, coordination, leadership and mentor luck, suited to management, administration and leading enterprises by gathering people.','Bonus: Lu Cun/Hua Lu/Hua Quan brings rank and wealth with real authority; Chang-Qu adds strategy and repute.','Break: sparse assistants make a lone ruler; with malefics leadership turns dictatorial with little help, lonely at the top.'],
 cnStep:['确认紫微是否守命及庙旺','逐一数三方四正的百官辅曜是否齐全','查有无煞忌冲破，判断是众臣还是孤君','成格则走管理统筹、带团队路线','刻意经营班底和授权，不做孤君式亲力亲为','辅曜少时主动补团队，逢煞时戒独断'],
 enStep:['Confirm Zi Wei guards Life and its brilliance','Count the court assistants across the trine one by one','Check malefic/Ji break to tell full court from lone ruler','If formed, take management and team-lead routes','Deliberately build a team and delegate, not hands-on lone rule','With few assistants, actively add team; with malefics avoid dictatorship'],
 cnMis:['紫微坐命就当帝王命','不数百官、不查冲破','孤君还凡事独断，越做越累'],
 enMis:['Calling any Zi Wei Life an emperor destiny','Not counting the court or checking breaks','A lone ruler deciding everything alone, growing exhausted'],
 cnClose:'君臣庆会的核心不是紫微星多尊贵，而是「有没有人辅佐」。真正的领袖格局，是你能聚起左辅右弼、文昌文曲这样的班底；会用人、能授权，帝星才坐得稳。',
 enClose:'The pattern\'s core is not Zi Wei\'s nobility but whether it has ministers. True leadership gathers a court of Zuo-You and Chang-Qu; able to use people and delegate, the emperor star sits steady.'},

{cat:'geju',slug:'ziwei-wutan-tongxing-wuqu-tanlang-chouwei-xianpin-houfu',focus:'武贪同行格',focusEn:'Wu Qu-Tan Lang together pattern',
 cnT:'紫微斗数武贪同行格：武曲贪狼在丑未，先贫后富的晚发格局',enT:'Wu-Tan Together in Zi Wei Dou Shu: Wu Qu and Tan Lang in Chou/Wei, a Poor-First-Rich-Later Late-Bloomer',
 cnD:'武曲贪狼同守丑、未宫守命为武贪同行（武贪不发少年人），武曲的实干财星配上贪狼的欲望与多才，主年轻时多摸索、三十岁后渐入佳境、中晚年发越，逢火星铃星成火贪铃贪主横发，关键在把贪狼的欲望关进武曲的纪律里。',
 enD:'Wu Qu and Tan Lang guarding Life in Chou/Wei is Wu-Tan together (it does not bloom in youth): Wu Qu\'s practical finance plus Tan Lang\'s desire and versatility mean early exploration, improvement after thirty and mid/late-life rise; with Fire/Bell it forms Fire/Bell-Tan sudden wealth. The key is caging Tan Lang\'s desire inside Wu Qu\'s discipline.',
 cnL:'武曲是会赚钱的硬星，贪狼是想要更多的活星，两颗一起，年轻时容易什么都想试，一旦把欲望聚焦成目标、用纪律执行，后劲儿很足。',
 enL:'Wu Qu is a hard earning star, Tan Lang a wanting-more versatile star; together youth tries everything, but once desire focuses into goals executed with discipline, staying power is strong.',
 cnA:'有人武贪坐命年轻时频繁换方向、怀疑自己不成器，其实正合晚发剧本；真正的风险是贪狼分心和投机，武曲的务实和长期主义才是这格的开关。',
 enA:'Young Wu-Tan people switch directions and doubt themselves, exactly the late-bloomer script; the real risk is Tan Lang distraction and speculation—Wu Qu\'s pragmatism and long-termism are the switch.',
 cnLog:['成格：武曲与贪狼同守丑宫或未宫守命，三方见吉、无重煞冲破。','星性组合：武曲主财、实干、刚毅，贪狼主欲望、多才、交际与变化，一收一放，主先经历摸索后聚焦成事。','典型轨迹：「武贪不发少年人」，早年多变动试错，约三十岁后随大限引动渐发，中晚年财与事业越走越稳。','爆发条件：同宫或三方会火星铃星成火贪、铃贪，逢禄主突然的机会财，但须防横发横破、落袋为安。'],
 enLog:['Formation: Wu Qu and Tan Lang guard Life in Chou or Wei with trine auspicious stars and no heavy malefic break.','Combination: Wu Qu finance/practical/resolve, Tan Lang desire/versatility/social/change—one gathers, one expands, meaning early exploration then focused achievement.','Typical arc: it does not bloom young; early change and trial, gradual rise after thirty as decades activate, steadier wealth and career later.','Burst: Fire/Bell in palace or trine forms Fire/Bell-Tan with Lu for sudden opportunity money, but guard boom-bust and bank gains.'],
 cnStep:['确认武曲贪狼是否同守丑未','接受晚发节奏，年轻时多试但要记录方向','用武曲的纪律聚焦贪狼的欲望，选一深耕','逢火铃成火贪时抓机会但设止盈、防横破','大限三十岁后引动时加大投入','戒投机赌性和频繁分心，走长期主义'],
 enStep:['Confirm Wu Qu/Tan Lang guard Chou/Wei','Accept late blooming; explore young but record directions','Use Wu Qu discipline to focus Tan Lang desire, pick one depth','With Fire/Bell seize chances but set take-profit against boom-bust','Increase investment when post-thirty decades activate','Avoid speculation and frequent distraction; take the long view'],
 cnMis:['年轻时不成就自我否定','贪狼分心什么都做，无法聚焦','火贪横发后不收，结果横破'],
 enMis:['Self-denial when young success is absent','Tan Lang scattering effort across everything','Not banking Fire-Tan sudden gains, ending in bust'],
 cnClose:'武贪同行是典型的「大器晚成」。年轻时的折腾不是白费，是在找方向；等你用武曲的纪律把贪狼的欲望收成一个点，三十岁后的后劲会远超那些早早定型的人。',
 enClose:'Wu-Tan is classic late blooming. Early striving is not wasted but direction-finding; once Wu Qu discipline focuses Tan Lang desire to one point, post-thirty staying power far exceeds those who定型 early.'},

{cat:'geju',slug:'ziwei-liantan-tonggong-lianzhen-tanlang-sihai-duobian',focus:'廉贪同宫格',focusEn:'Lian Zhen-Tan Lang pattern',
 cnT:'紫微斗数廉贞贪狼同宫：巳亥宫的多才、欲望与自我管理',enT:'Lian Zhen-Tan Lang in Si/Hai: Versatility, Desire and Self-Management',
 cnD:'廉贞贪狼同守巳、亥宫为廉贪同宫，两颗都是带桃花与欲望色彩的星，主多才多艺、善交际、魅力强、对艺术娱乐和人情世故敏感，能量大但也最考验自控，逢吉化把魅力变事业，逢煞忌空劫则易耽于情欲享乐、起伏不定，关键在给旺盛能量找高级出口。',
 enD:'Lian Zhen and Tan Lang guarding Si/Hai is Lian-Tan; both carry peach-blossom and desire, giving versatility, social skill, charm and sensitivity to art, entertainment and human dynamics. High energy but the greatest test of self-control: with auspicious transformations charm becomes career; with malefics/Ji/emptiness one indulges in pleasure with instability. The key is a high-grade outlet for strong energy.',
 cnL:'廉贞是火里的执念和魅力，贪狼是木里的欲望和多才，两颗在巳亥相遇，能量加倍，用对了是社交与创意高手，用偏了就是情困和沉迷。',
 enL:'Lian Zhen is fiery obsession and charm, Tan Lang woody desire and versatility; doubled in Si/Hai, used right they make a social-creative master, used off they mean romantic entrapment and addiction.',
 cnA:'有人把廉贪简单当花心或风流格，其实它更是「能量管理」命题：这格的人欲望和才华都旺，差别只在能不能把社交魅力和审美，导向事业和作品。',
 enA:'Lian-Tan is reduced to flirtation; it is really an energy-management命题: desire and talent both run high, differing only in whether charm and taste are directed to career and work.',
 cnLog:['成格：廉贞与贪狼同守巳宫或亥宫守命，两星皆主桃花、欲望、才艺与人际，能量强而复杂。','正面：多才多艺、审美高、善社交应酬、魅力与表现力强，利艺术、娱乐、传媒、设计、销售、公关、公关型创业。','风险：两桃花相会，逢煞忌空劫易耽于情欲、享乐、赌性与复杂关系，情绪和欲望起伏大、定力受考验。','转化：见禄权科或天府（廉府）理智收敛，把魅力与创意变成专业品牌；靠明确目标、边界和自律给能量定方向。'],
 enLog:['Formation: Lian Zhen and Tan Lang guard Life in Si or Hai, both governing peach-blossom, desire, talent and people skills—strong, complex energy.','Positive: versatile, high taste, socially skilled, charming and expressive, favoring art, entertainment, media, design, sales, PR and people-facing startups.','Risk: two peach stars with malefics/Ji/emptiness lean to indulgence, pleasure, gambling and tangled relations, with big swings testing resolve.','Conversion: Lu/Quan/Ke or Tian Fu rationalizes, turning charm and creativity into a professional brand; clear goals, boundaries and discipline direct the energy.'],
 cnStep:['确认廉贞贪狼是否同守巳亥','把多才和魅力列成可发展的专业方向','用明确目标收敛欲望，避免什么都想尝','主动远离复杂暧昧和赌性诱惑','逢吉化时打造个人品牌和作品','逢煞忌时加强自律、边界和情绪管理'],
 enStep:['Confirm Lian-Tan guard Si/Hai','List versatility and charm as developable professional directions','Focus desire with clear goals, avoid sampling everything','Actively avoid tangled affairs and gambling temptation','With auspicious transformations build personal brand and work','With malefics/Ji strengthen discipline, boundaries and emotion management'],
 cnMis:['把廉贪简单贴风流标签','旺盛能量没有高级出口，滑向沉迷','忽视自控，随欲望和情绪走'],
 enMis:['Labeling Lian-Tan simply as flirtatious','Having strong energy with no high outlet, sliding to indulgence','Ignoring self-control, following desire and mood'],
 cnClose:'廉贪同宫是一张「高能量、高魅力、也高诱惑」的盘。它不缺才华和人缘，缺的是定向——把那份对美和人情的敏感做成专业和品牌，你的魅力就是别人抢不走的竞争力。',
 enClose:'Lian-Tan is a high-energy, high-charm, high-temptation chart. It never lacks talent or connections but direction: turn sensitivity to beauty and people into profession and brand, and charm becomes unstealable competitiveness.'},

{cat:'geju',slug:'ziwei-juji-tonglin-tianji-jumen-maoyou-biancai-xuesi',focus:'巨机同临格',focusEn:'Ju Men-Tian Ji together pattern',
 cnT:'紫微斗数巨机同临格：天机巨门在卯酉，善思辨、靠口才学问立身',enT:'Ju-Ji Together in Zi Wei Dou Shu: Tian Ji and Ju Men in Mao/You, Sharp Thinkers Who Build on Eloquence and Learning',
 cnD:'巨机同临指天机、巨门同守卯宫（卯优于酉）守命，再会禄存、化权化禄、左右昌曲，主思维敏捷、辩才无碍、研究分析与记忆俱佳，宜学术、教育、法律、传媒、专业咨询，靠口才和学问名成利就；若会煞无制，则易变成口舌是非、多学少成。',
 enD:'Ju-Ji together means Tian Ji and Ju Men guard Life in Mao (Mao over You), meeting Lu Cun, Hua Quan/Hua Lu and Zuo-You/Chang-Qu: agile thought, eloquence, strong research-analysis and memory, suited to academia, education, law, media and expert consulting, succeeding through speech and learning. With unrestrained malefics it becomes verbal dispute and much study, little result.',
 cnL:'天机是转动的脑、巨门是表达的口，两颗同宫等于「会想又会说」，成格靠的是把思辨和口才扎进一门专业，否则聪明容易变成抬杠和空谈。',
 enL:'Tian Ji is the turning mind, Ju Men the expressing mouth—together, thinking and speaking; formation requires rooting that thought and speech in a profession, else cleverness becomes argument and empty talk.',
 cnA:'有人巨机坐命聪明善辩却处处得罪人、学得多精得少，问题不在聪明不够，而在没有用禄权和专业把口才「定向」，定向后这格非常能出专家和意见领袖。',
 enA:'Bright and eloquent Ju-Ji people offend others and learn broadly but shallowly; not lacking cleverness but direction via Lu/Quan and a profession—once directed, this pattern produces experts and opinion leaders.',
 cnLog:['成格：天机巨门同守卯（正）、酉（次）守命，同宫或三方会禄存、化禄化权、左辅右弼、文昌文曲。','象义：天机主思维谋略，巨门主口才研究，合力为思辨敏捷、分析记忆强、善表达与辩论。','宜走学术、教育、法律、传媒、写作、专业咨询、研发等「靠脑子和嘴」立身的领域，逢化禄主以口生财、化权主言论有分量。','破格：逢擎羊火铃空劫无制，易口舌是非、好辩树敌、多学少成，须深耕一门、练表达分寸。'],
 enLog:['Formation: Tian Ji/Ju Men guard Life in Mao (primary) or You (secondary), meeting Lu Cun, Lu/Quan, Zuo-You and Chang-Qu in palace or trine.','Meaning: Tian Ji thought/strategy plus Ju Men speech/research—agile, analytical, strong memory, expressive and argumentative.','Suited to academia, education, law, media, writing, expert consulting and R&D—building on mind and mouth; Hua Lu earns through speech, Hua Quan gives words weight.','Break: unrestrained Yang/Fire-Bell/emptiness brings disputes, argumentative enmity and shallow learning; deepen one field and train measured speech.'],
 cnStep:['确认天机巨门是否同守卯酉（卯更佳）','查禄存化禄化权与左右昌曲是否会齐','选一门靠思辨和表达的专业深耕','把口才用于教学、咨询、内容，而非争辩','逢化禄化权时打造专业言论影响力','逢煞时戒好辩抬杠，练表达分寸'],
 enStep:['Confirm Tian Ji/Ju Men guard Mao/You (Mao better)','Check Lu Cun, Lu/Quan and Zuo-You/Chang-Qu','Pick one thought-and-speech profession to deepen','Use eloquence in teaching, consulting and content, not argument','With Lu/Quan build professional influence','With malefics avoid quibbling and train measured expression'],
 cnMis:['聪明善辩却不深耕，多学少成','把口才用在抬杠争辩，四处树敌','不查吉曜会齐与否就套贵格'],
 enMis:['Bright and eloquent but shallow, never deepening','Using speech to quibble and argue, making enemies','Applying the noble pattern without checking auspicious support'],
 cnClose:'巨机同临给的是「最强大脑加一张利嘴」。聪明和辩才只是原料，把它扎进一门专业、用在建设性的表达上，你才能靠学问和口才真正立住身、名成利就。',
 enClose:'Ju-Ji gives a powerful mind and sharp tongue, but those are raw materials. Root them in one profession and constructive expression, and learning with eloquence becomes a solid, rewarded standing.'},

{cat:'geju',slug:'ziwei-yixing-rumiao-pojun-zai-ziwu-kaituo',focus:'英星入庙格',focusEn:'heroic star in temple pattern',
 cnT:'紫微斗数英星入庙格：破军在子午庙旺，破而后立的开创者',enT:'Heroic Star in Temple in Zi Wei Dou Shu: Po Jun Strong in Zi/Wu, a Builder Who Breaks First',
 cnD:'英星入庙指破军在子宫或午宫庙旺守命，破军本主破旧立新、变动开创，得地庙旺则把破坏力化为开创力，主有魄力、敢改革、能在废墟或空白处重建局面，逢禄权辅曜则破中有成、越变革越上位，落陷逢煞则破而难立、动荡折腾。',
 enD:'Heroic star in temple means Po Jun guards Life strong in Zi/Wu; Po Jun governs breaking-old-to-build-new and change, and in its strong place converts destruction to creation—bold, reforming, able to rebuild from ruin or blank ground. With Lu/Quan and assistants it builds within breaking and rises through reform; fallen with malefics it breaks without rebuilding, churning in turmoil.',
 cnL:'破军的本质是「先破后立」，庙旺时这份破不是破坏，而是推倒过时结构、重建新局的魄力，关键在破的同时手里要有「立」的方案。',
 enL:'Po Jun\'s essence is break-first-build-later; strong, the break is not destruction but the boldness to replace outdated structures—the key is holding a build plan while breaking.',
 cnA:'有人破军坐命只顾推倒、不擅重建，人生反复归零；英星入庙的差别就在庙旺得地、又有禄权辅佐，破完真能立得起新东西，而不是为变而变。',
 enA:'Po Jun people only tear down and repeatedly reset to zero; the in-temple difference is strong position plus Lu/Quan support, truly rebuilding after breaking rather than change for change\'s sake.',
 cnLog:['成格：破军在子或午宫庙旺守命，得禄存化禄化权、左辅右弼等吉曜会照，无重煞破格。','象义：破军化气为耗、主破旧立新，庙旺得地则魄力化为开创与改革能力，敢动僵局、能重建秩序。','利创业、改革、重组、开拓新市场、技术换代、危机重建等「需要先打破再建立」的领域。','破格：落陷、逢四煞空劫无制，则破而不立、频繁归零、动荡伤财，须先备好重建方案与资源再动。'],
 enLog:['Formation: Po Jun guards Life strong in Zi/Wu with Lu Cun/Lu/Quan and Zuo-You, no heavy malefic break.','Meaning: Po Jun qi of耗 governs break-old-build-new; strong, boldness becomes creation and reform—daring to move stagnation and rebuild order.','Favors startups, reform, restructuring, new markets, technology transitions and crisis rebuilding where breaking precedes building.','Break: fallen with unrestrained malefics/emptiness breaks without building, repeatedly resetting and losing wealth; prepare a rebuild plan and resources before acting.'],
 cnStep:['确认破军是否在子午庙旺守命','查禄权辅曜是否会照、有无重煞','选需要改革、开拓、重建的领域发挥','动手破之前先写好「立」的方案','逢禄权时大胆推动变革并接住成果','落陷逢煞时减少折腾，先积累再重建'],
 enStep:['Confirm Po Jun guards Life strong in Zi/Wu','Check Lu/Quan assistants and heavy malefics','Choose reform/frontier/rebuild domains','Write the build plan before breaking','With Lu/Quan push reform boldly and catch the results','Fallen with malefics, reduce churn and accumulate before rebuilding'],
 cnMis:['只破不立，人生反复归零','为变而变，没有重建方案','落陷逢煞还硬推大变革'],
 enMis:['Breaking without building, repeatedly resetting','Change for change\'s sake with no rebuild plan','Forcing big reform while fallen with malefics'],
 cnClose:'英星入庙把破军「破」的一面炼成了「立」的能力。真正的开创者不是爱折腾，而是看准过时的东西敢推倒，更有本事在推倒的地方，建起更好的新局。',
 enClose:'In-temple tempers Po Jun\'s breaking into building. A real pioneer doesn\'t love churn but dares to topple the outdated—and has the skill to build something better where it stood.'},

{cat:'geju',slug:'ziwei-xingqiu-jiayin-tianxiang-lianzhen-qingyang-yalimima',focus:'刑囚夹印格',focusEn:'punishment-prisoner clasping seal pattern',
 cnT:'紫微斗数刑囚夹印：天相被廉贞擎羊夹，压力格局怎么读怎么解',enT:'Punishment-Prisoner Clasping the Seal in Zi Wei Dou Shu: Tian Xiang Flanked by Lian Zhen and Qing Yang—Reading and Resolving a Pressure Pattern',
 cnD:'刑囚夹印（刑囚夹印）指天相守命时，被廉贞（囚）与擎羊（刑）在两邻夹拱，主责任压力重、易遇制度性约束、合同纠纷或官非是非、性格易紧绷硬扛，是一个需要主动「松绑」的格局；得禄权科、天魁天钺调和则能把压力转成专业权威，逢煞忌重时尤须守合规、留证据。',
 enD:'Punishment-prisoner clasping the seal means Tian Xiang guarding Life is flanked by Lian Zhen (prisoner) and Qing Yang (punishment), bringing heavy responsibility, institutional constraint, contract disputes or legal friction, and a tense, white-knuckled personality—a pattern needing active unbinding. With Lu/Quan/Ke and Kui/Yue harmonizing, pressure converts to professional authority; with heavy malefics/Ji, compliance and evidence are essential.',
 cnL:'天相是印、主辅佐和盖章，被「刑」与「囚」两邻夹住，等于每做一件事都被规则和压力盯着，读这格不是吓自己，而是学会在制度里把事做稳、把自己松绑。',
 enL:'Tian Xiang is the seal of assistance and approval; flanked by punishment and prisoner, every act is watched by rules and pressure—read it not as fear but as learning to work steadily within institutions and unbind yourself.',
 cnA:'有人天相守命、两邻正好是廉贞擎羊，总觉得责任压身、容易背锅和遇纠纷；解法不是硬刚制度，而是重合同、走流程、留痕，并用专业把压力转成话语权。',
 enA:'Tian Xiang people flanked this way feel burdened, blamed and dispute-prone; the answer is not fighting institutions but honoring contracts, following process, keeping records and converting pressure to authority through expertise.',
 cnLog:['成格：天相守命，相邻两宫分别为廉贞（化气为囚）与擎羊（化气为刑），形成「刑囚夹印」。','象义：印星被刑囚夹，主责任与约束并重，易遇制度压力、合同条款、官非口舌、手续卡关，性格偏谨慎紧绷、习惯硬扛。','轻重看会照：得禄存化禄化权化科、魁钺辅弼调和，主承压能力强、能在规则体系内做到专业权威。','逢煞忌重、无吉化解时，须特别重视合规、合同、证据与流程，避免替人担保、口头约定和灰色操作，并主动减压。'],
 enLog:['Formation: Tian Xiang guards Life, flanked by Lian Zhen (qi of prisoner) and Qing Yang (qi of punishment).','Meaning: the seal clasped by punishment-prisoner—responsibility plus constraint, prone to institutional pressure, contract terms, legal friction and procedural blocks, with a cautious, tense, white-knuckling personality.','Severity by trine: Lu Cun/Lu/Quan/Ke and Kui/Yue/Zuo-You harmonize, giving strong pressure tolerance and professional authority within rules.','With heavy malefics/Ji and no relief, prioritize compliance, contracts, evidence and process; avoid guarantees, verbal deals and gray operations, and actively reduce pressure.'],
 cnStep:['确认天相守命、两邻是否为廉贞与擎羊','查有无禄权科魁钺调和，判断压力能否转权威','凡事重合同、走流程、留书面证据','不替人担保、不做口头约定和灰色操作','用专业能力在规则体系内建立话语权','主动减压：运动、授权、不把责任全揽身上'],
 enStep:['Confirm Tian Xiang Life flanked by Lian Zhen and Qing Yang','Check Lu/Quan/Ke/Kui-Yue for whether pressure converts to authority','Honor contracts, follow process, keep written records','Avoid guarantees, verbal deals and gray operations','Build authority within the rules through expertise','Reduce pressure actively: exercise, delegate, don\'t take all responsibility'],
 cnMis:['见刑囚夹印就断言官非牢狱','硬刚制度不走流程，反惹纠纷','责任全揽、不会松绑，长期紧绷'],
 enMis:['Predicting lawsuits/jail from the pattern alone','Fighting institutions without process, courting disputes','Taking all responsibility, never unbinding, chronically tense'],
 cnClose:'刑囚夹印不是判你一定惹官非，而是提醒你：你天生要在规则和压力里做事。把合同、流程、证据做扎实，再用专业把压力熬成权威，那个最谨慎的印，反而盖得最稳。',
 enClose:'The pattern does not sentence you to lawsuits but reminds you that you work within rules and pressure. Solid contracts, process and evidence, plus expertise that turns pressure to authority, make the cautious seal the steadiest.'},

{cat:'geju',slug:'ziwei-taohua-zhuge-fanshui-taohua-fengliu-caizhang-zenme-du',focus:'桃花诸格',focusEn:'peach-blossom patterns',
 cnT:'紫微斗数桃花诸格：泛水桃花、风流彩杖，桃花过重怎么读',enT:'Peach-Blossom Patterns in Zi Wei Dou Shu: Water-Borne Peach and Romantic-Ribbon—Reading Excess Romance',
 cnD:'贪狼在子为泛水桃花、贪狼加陀罗在寅为风流彩杖等，是桃花星与特定宫位、煞曜组合出的「感情复杂、情缘波动」格局，主魅力强、追求者多、感情经历丰富但也易因情生扰、纠缠或声誉受损，关键不是断人花心，而是看清模式、把人际魅力导向正缘和事业，主动做情感管理。',
 enD:'Tan Lang in Zi is water-borne peach, Tan Lang with Tuo Luo in Yin is romantic-ribbon—peach stars combined with specific palaces/malefics producing complex, fluctuating romance: strong charm and many suitors, rich love history but also emotional entanglement or reputational cost. Rather than labeling one flirtatious, see the pattern, direct social charm toward stable bonds and career, and actively manage relationships.',
 cnL:'桃花格给的是「人际吸引力」，本身中性：用在正缘和人脉上是魅力，用在不断的暧昧和纠缠里就是消耗，差别在选择和边界。',
 enL:'Peach patterns give interpersonal attraction, neutral in itself: charm for stable bonds and networks, or drain in endless affairs—difference lies in choice and boundaries.',
 cnA:'有人一见桃花格就自我标签「花心」或被人贴标签，其实这类盘往往情商高、有亲和力，真正要学的是给魅力设边界、把情缘质量放在数量前面。',
 enA:'People self-label or get labeled flirtatious; such charts often have high EQ and warmth, and the real lesson is boundaries for charm and quality over quantity in bonds.',
 cnLog:['常见桃花格：贪狼在子守命为泛水桃花，贪狼与陀罗同宫（多在寅）为风流彩杖，另有贪狼会咸池天姚等加强桃花色彩。','共同象义：魅力强、异性缘与人脉旺、感情机会多、情绪和审美丰富，利演艺、销售、公关、内容、美业等靠人际吸引的领域。','风险面：情缘多而不稳、易暧昧纠缠、因情破财或影响声誉，逢陀罗主拖泥带水、逢煞忌主情伤与是非。','管理之道：分清桃花（人缘魅力）与红鸾天喜（正缘婚喜），给关系设边界、重质量，把亲和力转化为事业人脉和稳定亲密关系。'],
 enLog:['Common patterns: Tan Lang in Zi is water-borne peach; Tan Lang with Tuo Luo (often Yin) is romantic-ribbon; Tan Lang with Xian Chi/Tian Yao strengthens romance.','Shared meaning: strong charm, broad romantic/social ties, many chances, rich emotion and taste—favoring entertainment, sales, PR, content and beauty industries built on attraction.','Risks: many unstable bonds, affairs and entanglement, money/reputation loss through love; Tuo Luo drags things out, malefics/Ji bring heartbreak and dispute.','Management: distinguish peach (charm/network) from Hong Luan/Tian Xi (stable marriage); set boundaries, value quality, convert warmth to professional network and stable intimacy.'],
 cnStep:['认清桃花格的本质是人际吸引力而非注定花心','把魅力和高情商导向事业、人脉与内容','给亲密关系设清晰边界，拒绝暧昧惯性','重情缘质量而非追求者数量','逢陀罗时快刀斩乱麻，不拖泥带水','逢煞忌年份在感情上放慢、守声誉'],
 enStep:['Recognize the pattern as attraction, not destined flirtation','Direct charm and high EQ to career, network and content','Set clear boundaries, reject the affair habit','Value bond quality over suitor quantity','With Tuo Luo, cut cleanly rather than dragging out','In malefic/Ji years slow romance and guard reputation'],
 cnMis:['把桃花格直接等同花心命烂','只享受追求数量，不管关系质量','魅力没有边界，反被情缘消耗'],
 enMis:['Equating peach patterns with promiscuity or bad fate','Enjoying suitor quantity regardless of quality','Charm without boundaries, drained by affairs'],
 cnClose:'桃花诸格给你的是难得的亲和力和魅力，它不是道德判决，而是一道管理题。给魅力设边界、把人缘变人脉、把情缘走成正缘，你天生的吸引力，会成为感情和事业的双重助力。',
 enClose:'Peach patterns give rare warmth and charm—not a moral verdict but a management test. Bound charm, turn popularity into network and romance into stable bonds, and natural attraction becomes an asset in both love and career.'},
];
