// 2026-10-06 调研驱动 第5组：入门 2（迷信/四化入门）+ FAQ 2（同时辰同命/能看风水）+ 应用 2（手术择期/提前还贷）+ 看盘 2（三合配对/星曜阴阳）
module.exports=[
{cat:'rumen',slug:'ziwei-bushi-mixin-zenme-kan',focus:'紫微斗数是不是迷信',focusEn:'whether Zi Wei Dou Shu is superstition',
 cnT:'紫微斗数是不是迷信：传统符号体系，知命而不宿命',enT:'Is Zi Wei Dou Shu Superstition? A Traditional Symbol System',
 cnD:'紫微斗数是古人用星象建立的天人对应模型，属传统符号与人文观察体系，不是可证伪的科学结论；它的价值在认识自我、辅助决策，应「知命而不宿命」，用它反思而不是用它替你做决定。',
 enD:'Zi Wei Dou Shu is a model of heaven-human correspondence built by the ancients using star imagery, belonging to traditional symbolism and humanistic observation, not a falsifiable scientific conclusion. Its value lies in self-understanding and decision support; one should know fate without being fatalistic, using it for reflection rather than letting it decide for you.',
 cnL:'把紫微斗数当工具，它是一面镜子；把它当定论，它就成了枷锁。镜子照人，枷锁困人，差别在你怎么用。',
 enL:'Treat Zi Wei Dou Shu as a tool and it is a mirror; treat it as a verdict and it becomes a shackle. A mirror reflects, a shackle binds; the difference is how you use it.',
 cnA:'有人问「紫微是不是迷信」，真正的问题是「你用它来做什么」；用来反思自己是启发，用来逃避选择才是迷信。',
 enA:'People ask whether Zi Wei is superstition, but the real question is what you use it for; using it to reflect on yourself is enlightening, using it to avoid choosing is superstition.',
 cnLog:['紫微斗数是一套用星曜、宫位、四化描述人事倾向的符号模型，有千年传承。','它不是可证伪的科学，不能用实验重复验证，也不应替代专业判断。','它的价值在提供自我观察的角度和决策的参考框架。','正确态度是「知命而不宿命」：了解倾向，但最终选择和行动在自己。'],
 enLog:['Zi Wei Dou Shu is a symbolic model using stars, palaces and transformations to describe human tendencies, with a thousand-year tradition.','It is not falsifiable science, cannot be verified by repeated experiments, and should not replace professional judgment.','Its value lies in providing a perspective for self-observation and a reference framework for decisions.','The right attitude is know fate without being fatalistic: understand tendencies, but the final choice and action are yours.'],
 cnStep:['先把紫微斗数定位为「传统符号工具」，不是科学定论','用它观察自己的性格倾向和行为模式','把观察到的倾向当成参考，不当成不可改的判决','遇到重大决策，结合现实信息和专业意见','用命盘反思「我为什么这样选」，而不是「命说我只能这样」','保持批判性，不把任何命理结论当成逃避努力的理由'],
 enStep:['First position Zi Wei Dou Shu as a traditional symbolic tool, not a scientific verdict','Use it to observe your own personality tendencies and behavior patterns','Treat observed tendencies as reference, not unchangeable verdicts','For major decisions, combine real-world information and professional advice','Use the chart to reflect on why I choose this way, not fate says I can only choose this','Stay critical, do not use any astrological conclusion as a reason to avoid effort'],
 cnMis:['把紫微斗数当成科学定论，用它替代专业判断','用「命里注定」逃避选择和努力','完全否定，看不到它作为自我观察工具的价值'],
 enMis:['Treating Zi Wei Dou Shu as a scientific verdict and using it to replace professional judgment','Using destined by fate to avoid choices and effort','Rejecting it entirely and missing its value as a self-observation tool'],
 cnClose:'紫微斗数是不是迷信，答案在使用者手里。把它当镜子照自己、当参考做决策，它就是有价值的传统智慧；把它当定论、当逃避，它才成了迷信。',
 enClose:'Whether Zi Wei Dou Shu is superstition depends on the user. Treat it as a mirror for self-reflection and a reference for decisions, and it is valuable traditional wisdom; treat it as a verdict and an escape, and it becomes superstition.'},

{cat:'rumen',slug:'ziwei-shenme-shi-sihua-luquankeji-rumen',focus:'什么是四化',focusEn:'what are the Four Transformations',
 cnT:'什么是四化：禄权科忌是命盘的能量开关',enT:'What Are the Four Transformations? The Energy Switches of a Chart',
 cnD:'四化是星曜表达方式的变化：化禄主资源机缘、化权主掌控执行、化科主名声缓和、化忌主执着亏欠；它们不是固定吉凶分数，而是命盘的能量开关，先懂象义再谈落宫。',
 enD:'The Four Transformations are changes in how stars express themselves: Hua Lu governs resources and opportunity, Hua Quan control and execution, Hua Ke reputation and smoothing, Hua Ji attachment and debt. They are not fixed good-or-bad scores but the energy switches of a chart; understand the meanings first, then discuss which palace they land in.',
 cnL:'四化像四颗开关按钮，按下去星曜就换一种表达方式；禄是开门迎客，权是握紧方向盘，科是调亮灯光，忌是踩住刹车。',
 enL:'The Four Transformations are like four switch buttons; pressing one changes how a star expresses itself. Lu opens the door to guests, Quan grips the steering wheel, Ke brightens the lights, and Ji hits the brake.',
 cnA:'有人背了四化术语却不会用，因为没把象义落到具体人事；四化不是标签，是描述「这件事以什么方式发生」。',
 enA:'Some memorize transformation terms but cannot use them because they do not ground the meanings in real affairs; transformations are not labels but descriptions of how this matter happens.',
 cnLog:['四化=化禄、化权、化科、化忌，是星曜表达方式的四种变化。','化禄=资源、机缘、人缘、顺利；化权=掌控、执行、竞争、责任。','化科=名声、文书、缓和、理性；化忌=执着、亏欠、卡点、操心。','四化不是吉凶加分器，同一化在不同宫、不同星上含义不同。'],
 enLog:['The Four Transformations are Hua Lu, Hua Quan, Hua Ke and Hua Ji, four changes in how stars express themselves.','Hua Lu is resources, opportunity, relationships and smoothness; Hua Quan is control, execution, competition and responsibility.','Hua Ke is reputation, documents, smoothing and reason; Hua Ji is attachment, debt, sticking points and worry.','Transformations are not good-or-bad score adders; the same transformation means different things in different palaces and on different stars.'],
 cnStep:['先记住禄权科忌各自的基本象义','看四化落在哪一宫，定它影响哪个领域','看它附在哪颗主星上，定具体表现方式','把象义翻译成现实场景（工作、钱、关系、健康）','合三方四正，看四化有没有被引动或打折','最后落到该怎么应对，而不是停在术语'],
 enStep:['First memorize the basic meanings of Lu, Quan, Ke and Ji','See which palace each transformation lands in to set the area it affects','Read which major star it attaches to for the concrete expression','Translate the meaning into real scenarios (work, money, relationships, health)','Combine the triple-direction to see whether the transformation is activated or discounted','Finally settle how to respond rather than stopping at terms'],
 cnMis:['把四化当固定吉凶分数，见到就贴标签','只背术语不翻译成人话，一套生活就空','只看化曜不看落星落宫与三方'],
 enMis:['Treating transformations as fixed good-or-bad scores and labeling on sight','Memorizing terms without plain-language translation, turning hollow in real life','Reading only the transformed star without the host star, palace and trines'],
 cnClose:'四化是命盘的能量开关。先懂禄权科忌各自说什么，再看它落在哪宫、附在哪星，你才能把术语读成生活里具体的事。',
 enClose:'The Four Transformations are the energy switches of a chart. First understand what Lu, Quan, Ke and Ji each say, then see which palace they land in and which star they attach to, and you can read the terms as concrete matters in life.'},

{cat:'faq',slug:'ziwei-tongyi-shichen-chusheng-mingyun-yiyang-ma',focus:'同时辰出生命运一样吗',focusEn:'do people born in the same shichen have the same fate',
 cnT:'同一时辰出生的人命运一样吗：盘给趋势，选择分高下',enT:'Do People Born in the Same Shichen Share the Same Fate?',
 cnD:'同一时辰出生的人排出来的盘结构相似，但命运不会一样；盘给的是共同趋势与概率区间，环境、家庭、努力、关键选择分高下，时间无限可分，时辰论命有先天局限。',
 enD:'People born in the same shichen (two-hour window) produce similar chart structures, but their fates are not the same. The chart gives shared tendencies and probability ranges; environment, family, effort and key choices separate outcomes. Time is infinitely divisible, so shichen-based reading has inherent limitations.',
 cnL:'同一个时辰出生的人，拿到的是同一张地图，但走哪条路、走多快、和谁一起走，全在自己。',
 enL:'People born in the same shichen receive the same map, but which road to take, how fast to walk and who to walk with are entirely their own.',
 cnA:'有人问「同时辰的人命运一样吗」，潜台词是「那我努力还有用吗」；答案是盘只给倾向，努力和选择才是变量。',
 enA:'People ask whether those born in the same shichen share fate, with the underlying question does my effort still matter; the answer is the chart only gives tendencies, effort and choice are the variables.',
 cnLog:['同一时辰（两小时）内出生的人，命盘结构基本相同。','但实际命运差异很大：家庭、地域、教育、选择、努力都不同。','斗数时辰以两小时为单位，时间无限可分，这是论命的先天局限。','盘给的是概率区间和倾向，不是精确到个人的唯一剧本。'],
 enLog:['People born within the same shichen (two hours) produce essentially the same chart structure.','But actual fates differ greatly: family, region, education, choices and effort all vary.','Zi Wei uses two-hour shichen units, and time is infinitely divisible, an inherent limitation of the system.','The chart gives probability ranges and tendencies, not a single precise script for each individual.'],
 cnStep:['理解同一时辰的盘结构相似，但不代表命运相同','把盘读成「倾向和概率区间」，不是定论','对比同时辰的人，看环境和选择造成的差异','在自己的盘里找可优化的方向，而不是找「注定」','用大限流年看时间节奏，用努力和选择改变兑现程度','保持开放，不因为盘相似就放弃个人努力'],
 enStep:['Understand that same-shichen charts are structurally similar but do not mean the same fate','Read the chart as tendencies and probability ranges, not verdicts','Compare people of the same shichen to see differences from environment and choice','Find optimizable directions in your own chart rather than looking for destiny','Use decades and years for timing, and let effort and choice change how much materializes','Stay open, do not give up personal effort because charts are similar'],
 cnMis:['认为同时辰出生的人命运完全一样','因为盘相似就否定个人努力和选择的作用','把概率区间当成精确的个人定论'],
 enMis:['Believing people born in the same shichen have exactly the same fate','Denying the role of personal effort and choice because charts are similar','Treating probability ranges as precise individual verdicts'],
 cnClose:'同时辰出生的人命运不一样。盘给的是共同的趋势和概率区间，而环境、努力和关键选择，才是把同一张地图走出不同人生的真正变量。',
 enClose:'People born in the same shichen do not share the same fate. The chart gives shared tendencies and probability ranges, while environment, effort and key choices are the real variables that turn the same map into different lives.'},

{cat:'faq',slug:'ziwei-neng-kan-fengshui-ma',focus:'紫微斗数能看风水吗',focusEn:'can Zi Wei Dou Shu read feng shui',
 cnT:'紫微斗数能看风水吗：斗数看人事时间，风水看空间，各有体系',enT:'Can Zi Wei Dou Shu Read Feng Shui? Two Separate Systems',
 cnD:'紫微斗数看的是人事与时间节奏，风水（堪舆）看的是空间环境与气场，二者是不同体系；斗数里的田宅宫可以反映居住状态和家庭氛围，但不能替代专业风水勘察，不宜混为一谈。',
 enD:'Zi Wei Dou Shu reads human affairs and timing, while feng shui (Kan Yu) reads spatial environment and energy flow; they are different systems. The Property Palace in Zi Wei can reflect living conditions and family atmosphere, but it cannot replace a professional feng shui survey, and the two should not be conflated.',
 cnL:'斗数是时间轴上的人事地图，风水是空间轴上的环境地图；两张图可以对照看，但不能用一张替代另一张。',
 enL:'Zi Wei is a map of human affairs on the time axis, feng shui is a map of environment on the space axis; the two maps can be read together, but one cannot replace the other.',
 cnA:'有人想用斗数看风水，也有人想用风水改命盘；两者各有边界，混着用容易两头都读不准。',
 enA:'Some want to use Zi Wei to read feng shui, others want to use feng shui to change their chart; each has its boundaries, and mixing them easily leads to inaccurate readings on both sides.',
 cnLog:['紫微斗数核心是星曜、宫位、四化，描述的是人事与时间节奏。','风水核心是空间方位、环境形局、气流光照，描述的是居住与办公环境。','斗数的田宅宫可反映居住状态、家庭氛围和不动产缘分。','但田宅宫不能替代专业风水的实地勘察，二者不宜混为一谈。'],
 enLog:['The core of Zi Wei Dou Shu is stars, palaces and transformations, describing human affairs and timing.','The core of feng shui is spatial orientation, environmental form, airflow and light, describing living and working environments.','The Property Palace in Zi Wei can reflect living conditions, family atmosphere and real-estate bonds.','But the Property Palace cannot replace a professional on-site feng shui survey; the two should not be conflated.'],
 cnStep:['先分清斗数（时间人事）和风水（空间环境）是两套体系','用斗数田宅宫看居住状态和家庭氛围的倾向','如果需要具体风水调整，找专业风水师实地勘察','把斗数读成「这阶段居住上容易有什么主题」','不把斗数结论当成风水布局的直接依据','两者结合时各守边界，互相参考不互相替代'],
 enStep:['First clarify that Zi Wei (time and human affairs) and feng shui (space and environment) are two systems','Use the Property Palace to read tendencies in living conditions and family atmosphere','If specific feng shui adjustment is needed, consult a professional for on-site survey','Read Zi Wei as what theme is likely in living arrangements this stage','Do not take Zi Wei conclusions as direct instructions for feng shui layout','When combining the two, keep each within its bounds, reference each other without replacing'],
 cnMis:['用斗数田宅宫直接替代风水勘察','把风水和斗数混为一谈，两边都读不准','以为改了风水就能改命盘，忽略人事努力'],
 enMis:['Using the Property Palace to directly replace feng shui survey','Conflating feng shui and Zi Wei, reading neither accurately','Assuming changing feng shui can change the chart, ignoring human effort'],
 cnClose:'紫微斗数不能直接看风水。斗数管时间和人事，风水管空间和环境，田宅宫可以给居住倾向的参考，但具体的空间调理要找专业风水，各守边界才读得准。',
 enClose:'Zi Wei Dou Shu cannot directly read feng shui. Zi Wei governs time and human affairs, feng shui governs space and environment. The Property Palace can reference living tendencies, but specific spatial adjustment needs a professional; each within its bounds reads accurately.'},

{cat:'yingyong',slug:'ziwei-shoushu-zeqi-ruhe-kan',focus:'手术择期',focusEn:'scheduling surgery',
 cnT:'手术择期怎么看：命理只是倾向参考，一切以正规医院为准',enT:'How to Approach Scheduling Surgery',
 cnD:'命盘可以提示健康关口的时间节奏和倾向，但手术安排必须以正规医院和专业医生的判断为准；不因命理拖延必要治疗，择期只是在医生允许的范围内选相对平稳的时间。',
 enD:'A chart can hint at the timing and tendency of health thresholds, but surgery scheduling must follow the judgment of proper hospitals and professional doctors. Do not delay necessary treatment for astrology; scheduling only means choosing a relatively stable time within what the doctor allows.',
 cnL:'手术择期里，命理是锦上添花的参考，医生的判断是不可动摇的主心骨；顺序不能反。',
 enL:'In scheduling surgery, astrology is a nice-to-have reference, while the doctor judgment is the unshakable backbone; the order cannot be reversed.',
 cnA:'有人为了等一个「好日子」拖延手术，也有人完全不看时间随意安排；正确的做法是先听医生，再在允许范围内参考命理节奏。',
 enA:'Some delay surgery waiting for a good day, while others schedule arbitrarily with no regard for timing; the correct approach is to listen to the doctor first, then reference astrological rhythm within what is allowed.',
 cnLog:['命盘疾厄宫与大限流年可提示健康关口的倾向和时间节奏。','但命理倾向不是诊断，不能替代医学检查和医生判断。','择期手术可在医生允许的范围内，避开化忌、煞星集中的流年流月。','急症和限期手术必须遵医嘱，不因任何命理理由拖延。'],
 enLog:['The Health Palace and decade/year charts can hint at health threshold tendencies and timing.','But astrological tendency is not a diagnosis and cannot replace medical examination or doctor judgment.','For elective surgery, within what the doctor allows, one may avoid years or months heavy with Hua Ji or malefics.','Emergency and time-sensitive surgery must follow doctor orders, never delayed for any astrological reason.'],
 cnStep:['先确认手术类型：急症立即就医，不考虑择期','择期手术先听医生的建议时间窗','在医生允许的范围内，参考流年流月的健康倾向','避开化忌、煞星集中或与疾厄宫冲克的时间段','选定后与医生确认，以医疗安排为最终决定','术后遵医嘱康复，命理只做辅助参考'],
 enStep:['First confirm the surgery type: emergency means immediate care, no scheduling consideration','For elective surgery, first hear the doctor recommended time window','Within what the doctor allows, reference health tendencies in the year and month','Avoid time periods heavy with Hua Ji, malefics or clashing the Health Palace','After choosing, confirm with the doctor, medical arrangement is the final decision','Follow doctor orders for post-surgery recovery, astrology is only a supporting reference'],
 cnMis:['为等「好日子」拖延必要手术，危及健康','把命理倾向当诊断，不做正规检查','完全不遵医嘱，只按命理时间安排'],
 enMis:['Delaying necessary surgery waiting for a good day, endangering health','Treating astrological tendency as diagnosis and skipping proper examination','Ignoring doctor orders entirely and scheduling only by astrological timing'],
 cnClose:'手术择期看的是「医生为主、命理为辅」。先听专业医生的安排，再在允许范围内参考时间节奏，健康和安全永远排在第一位。以上为命理倾向，非诊断，以正规就医为准。',
 enClose:'Scheduling surgery puts the doctor first and astrology second. Follow the professional doctor arrangement first, then reference timing within what is allowed; health and safety always come first. This is a cultural-tendency reference, not a diagnosis; defer to proper medical care.'},

{cat:'yingyong',slug:'ziwei-tiqian-huandai-ruhe-kan',focus:'提前还贷',focusEn:'paying off a loan early',
 cnT:'提前还贷怎么看：权衡现金流与利率，留足应急钱',enT:'How to Decide Whether to Pay Off a Loan Early',
 cnD:'提前还贷不是「越早还越好」，要权衡贷款利率、投资收益率、现金流安全和应急储备；命盘财帛与田宅可提示财务节奏，但最终决策以正规贷款合同和持牌机构说明为准，不构成投资建议。',
 enD:'Paying off a loan early is not the earlier the better; one must weigh the loan interest rate, investment return, cash-flow safety and emergency reserve. The Wealth and Property Palaces can hint at financial rhythm, but the final decision follows the formal loan contract and licensed institution guidance; this is not investment advice.',
 cnL:'提前还贷像把手里的钱填进一个坑，坑填了心里踏实，但手里没了余粮；要算的是「踏实」和「灵活」哪个更值。',
 enL:'Paying off early is like filling a pit with cash in hand; the pit filled brings peace of mind, but you lose your surplus. The calculation is whether peace of mind or flexibility is worth more.',
 cnA:'有人一有钱就提前还贷，也有人坚决不还拿去投资；真正要算的是利率差、现金流和应急储备，不是情绪决定。',
 enA:'Some pay off early as soon as they have money, others refuse to pay and invest instead; what to calculate is the interest gap, cash flow and emergency reserve, not an emotional decision.',
 cnLog:['提前还贷的核心权衡：贷款利率 vs 资金的其他用途收益率。','必须留足3-6个月应急金，不能把所有现金都填进贷款。','要看贷款合同的提前还款违约金、次数限制和最低金额。','命盘财帛、田宅与大限可提示财务节奏，但不能替代实际算账。'],
 enLog:['The core trade-off of early repayment: loan interest rate versus the return rate of other uses of the funds.','You must keep 3-6 months of emergency funds, cannot pour all cash into the loan.','Check the loan contract for early-repayment penalties, frequency limits and minimum amounts.','The Wealth, Property and decade charts can hint at financial rhythm, but cannot replace actual calculation.'],
 cnStep:['先算清贷款利率、剩余本金和提前还款规则','评估自己的应急储备是否充足（至少3-6个月开支）','比较贷款利率与稳健投资收益率的差','如果贷款利率远高于无风险收益，提前还贷更划算','如果现金流紧张或有更好用途，可暂缓或部分还','决策以贷款合同和持牌机构说明为准，不构成投资建议'],
 enStep:['First calculate the loan interest rate, remaining principal and early-repayment rules','Assess whether your emergency reserve is sufficient (at least 3-6 months of expenses)','Compare the loan rate with the return on conservative investments','If the loan rate is far above risk-free return, early repayment is more worthwhile','If cash flow is tight or there are better uses, delay or partially repay','Decide based on the loan contract and licensed institution guidance; this is not investment advice'],
 cnMis:['把所有现金都提前还贷，不留应急金','只看利率不看现金流，导致手头紧张','完全不算账，凭情绪决定还或不还'],
 enMis:['Pouring all cash into early repayment without keeping emergency funds','Looking only at interest rate without cash flow, leading to tight liquidity','Not calculating at all, deciding to repay or not based on emotion'],
 cnClose:'提前还贷看的是「利率、现金流、应急金」三者的平衡。算清账、留足余粮、以合同为准，你才能决定是提前还更踏实，还是留着现金更灵活。以上为命理倾向，不构成投资建议，以持牌机构和正规产品说明为准。',
 enClose:'Early repayment is about balancing interest rate, cash flow and emergency funds. Calculate clearly, keep enough surplus and follow the contract, then you can decide whether paying early brings more peace or keeping cash brings more flexibility. This is a cultural-tendency reference, not investment advice; defer to licensed institutions and official product terms.'},

{cat:'kanpan',slug:'ziwei-sanhe-gong-peidui-ruhe-kan',focus:'三合宫配对',focusEn:'reading the trine palace pairings',
 cnT:'三合宫配对怎么看：本宫与两个三合宫是核心—资源—执行',enT:'How to Read Trine Palace Pairings: Core, Resource, Execution',
 cnD:'三合不是排队，本宫与两个三合宫构成「核心—资源—执行」的呼应；看三合要配对看主题词，比如财帛的三合是官禄和福德，分别管赚钱的方式和花钱的感受，三者连起来才读得全。',
 enD:'The trine is not a queue; the home palace and its two trine palaces form an echo of core, resource and execution. Reading the trine means pairing by theme: for example, the Wealth Palace trines with Career and Karma, governing how you earn and how spending feels, and only all three together give the full picture.',
 cnL:'三合宫像一个三角形的三条边，缺了任何一条，这个领域就立不稳；看三合不是数吉星，是看三条边能不能咬合。',
 enL:'The trine palaces are like three sides of a triangle; missing any side, the area cannot stand steady. Reading the trine is not counting auspicious stars but seeing whether the three sides interlock.',
 cnA:'有人看三合只数吉星多少，也有人只看本宫不看三合；真正要读的是三个宫之间的主题呼应和力量分配。',
 enA:'Some read the trine only by counting auspicious stars, others only look at the home palace; what to read is the thematic echo and distribution of power among the three palaces.',
 cnLog:['三合宫指本宫及相隔四位的两宫，构成三角形，是一个领域的完整结构。','本宫=核心，一个三合=资源/条件，另一个三合=执行/结果。','例如命宫三合财帛、官禄：我是谁、靠什么赚钱、做什么事。','看三合要配对主题词，三宫连起来读，不是各自孤立看。'],
 enLog:['The trine consists of the home palace and two palaces four positions away, forming a triangle, the complete structure of one area.','Home palace = core, one trine = resource/condition, the other trine = execution/result.','For example, Life Palace trines Wealth and Career: who I am, how I earn, what I do.','Read the trine by pairing themes, connecting all three palaces rather than reading each in isolation.'],
 cnStep:['先定位本宫，确认要看哪个领域','找出本宫的两个三合宫，构成三角形','给三个宫分别贴标签：核心、资源、执行','逐宫看主星和四化，定每条边的力量','把三宫连起来读：核心有没有资源支撑、资源能不能变成执行','看有没有煞忌冲破某一条边，定这个领域的短板在哪'],
 enStep:['First locate the home palace, confirming which area to read','Find its two trine palaces, forming the triangle','Label the three palaces: core, resource, execution','Read the major star and transformations of each to set the power of each side','Connect all three: whether the core has resource support and whether resource becomes execution','See whether a malefic or Ji breaks any side, locating the weakness in this area'],
 cnMis:['看三合只数吉星多少，不看主题呼应','只看本宫不看三合，读不出完整结构','把三合当三个独立宫，不连起来读'],
 enMis:['Reading the trine only by counting auspicious stars, ignoring thematic echo','Looking only at the home palace without the trine, missing the complete structure','Treating the trine as three independent palaces, not connecting them'],
 cnClose:'三合宫配对看的是「一个领域的三条边能不能咬合」。把核心、资源、执行连起来读，你才知道这个领域是完整有力，还是缺了某一条边立不稳。',
 enClose:'Trine palace pairings ask whether the three sides of an area interlock. Connect core, resource and execution, and you know whether the area is complete and strong, or missing a side and unable to stand steady.'},

{cat:'kanpan',slug:'ziwei-xingyao-fen-yinyang-ruhe-kan',focus:'星曜分阴阳',focusEn:'stars divided by yin and yang',
 cnT:'星曜分阴阳怎么理解：冷热、动静、表里的底层钥匙',enT:'How to Understand Stars Divided by Yin and Yang',
 cnD:'星有阴阳，决定冷热、动静、表里的表达方式：阳星偏外放、主动、热，阴星偏内敛、被动、冷；阴阳是理解星性的底层钥匙，同颗星阴阳不同，落宫表现也不同。',
 enD:'Stars have yin and yang, which determines their expression of cold-heat, movement-stillness and inner-outer: yang stars lean outward, active and warm, yin stars lean inward, passive and cool. Yin-yang is the underlying key to understanding star nature; the same star with different yin-yang expresses differently by palace.',
 cnL:'阴阳像星曜的性别和温度，不是好坏之分，是表达方式之别；阳星像白天，阴星像夜晚，各有各的用场。',
 enL:'Yin-yang is like the gender and temperature of a star, not a good-bad distinction but a difference in expression; yang stars are like daytime, yin stars like nighttime, each with its own use.',
 cnA:'有人背了星性却读不出差别，因为没看到阴阳这层底色；同是主星，阴阳不同，处理事情的方式就不同。',
 enA:'Some memorize star natures but cannot read the differences because they miss the yin-yang underlying layer; even among major stars, different yin-yang means different ways of handling matters.',
 cnLog:['十四主星分阴阳：紫微、天机、太阳、武曲、天同、廉贞属阳；太阴、贪狼、巨门、天相、天梁、七杀、破军、天府属阴（不同流派略有差异）。','阳星偏外放、主动、热、刚；阴星偏内敛、被动、冷、柔。','阴阳不是吉凶，是表达方式，落宫后还要看庙旺和四化。','阴阳搭配：阳星遇阴宫、阴星遇阳宫，表达方式会被调和或激发。'],
 enLog:['The fourteen major stars divide into yin and yang: Zi Wei, Tian Ji, Sun, Wu Qu, Tian Tong, Lian Zhen are yang; Tai Yin, Tan Lang, Ju Men, Tian Xiang, Tian Liang, Qi Sha, Po Jun, Tian Fu are yin (schools vary slightly).','Yang stars lean outward, active, warm and firm; yin stars lean inward, passive, cool and gentle.','Yin-yang is not good or bad but expression; after landing in a palace, still read brightness and transformations.','Yin-yang pairing: a yang star in a yin palace or yin star in a yang palace has its expression tempered or activated.'],
 cnStep:['先认每颗主星的阴阳属性','把阴阳翻译成表达方式：阳=外放主动，阴=内敛被动','看星落宫的阴阳，判断是被调和还是被激发','结合庙旺落陷，看这股阴阳之气得不得舒展','看四化引动，阳星化权更刚、阴星化科更柔','最后落到现实：这个人处理事情是主动出击还是被动应对'],
 enStep:['First learn the yin-yang attribute of each major star','Translate yin-yang into expression: yang = outward and active, yin = inward and passive','Read the yin-yang of the palace the star lands in, judging whether tempered or activated','Combine brightness to see whether the yin-yang energy can express itself','Read transformation activation: yang star with Hua Quan is firmer, yin star with Hua Ke is gentler','Finally land in reality: whether this person handles matters by proactive attack or passive response'],
 cnMis:['把阴阳当吉凶，阳就是好、阴就是坏','只看星性不看阴阳，读不出表达方式的差别','忽略落宫阴阳对星性的调和作用'],
 enMis:['Treating yin-yang as good-or-bad, yang is good and yin is bad','Reading only star nature without yin-yang, missing expression differences','Ignoring how the palace yin-yang tempers the star nature'],
 cnClose:'星曜分阴阳是理解星性的底层钥匙。认出每颗星的阴阳、看它落宫的阴阳、再结合庙旺和四化，你才能读懂这颗星到底是「往外冲」还是「往里收」。',
 enClose:'Stars divided by yin and yang is the underlying key to understanding star nature. Recognize each star yin-yang, read the palace yin-yang it lands in, then combine brightness and transformations, and you can read whether the star charges outward or draws inward.'}
];
