// 2026-10-04 调研驱动 第3组：看盘方法进阶6 + 入门2，共8篇
module.exports=[
{cat:'kanpan',slug:'ziwei-konggong-duo-ruhe-du',focus:'空宫多的盘',focusEn:'charts with many empty palaces',
 cnT:'盘上空宫多怎么读：不是处处空，而是分别借、逐个定',enT:'How to Read a Chart With Many Empty Palaces: Not Empty Everywhere, but Borrowing and Confirming One by One',
 cnD:'多个宫位无主星，不代表处处无依；每个空宫分别借对宫、看三方与四化从哪被触发，再做一次定盘，思路反而清楚。',
 enD:'Several palaces without major stars do not mean no support everywhere; each empty palace borrows from its opposite, reads its trine and the transformations that trigger it, and after confirming the chart the reading actually clarifies.',
 cnL:'空宫多的盘看着格子空，其实信息一点不少，只是答案写在对宫和四化里，要一个个去借、去对。',
 enL:'A chart with many empty palaces looks sparse, yet the information is all there; the answers sit in the opposite palaces and transformations and must be borrowed and matched one by one.',
 cnA:'有人一看四五个空宫就慌，觉得这张盘「什么都没有」，问题不在空宫多，而在想用同一套「看本宫主星」的方法硬读所有宫。',
 enA:'Some panic at four or five empty palaces and feel the chart has nothing; the issue is not many empty palaces but trying to read every palace with the same home-major-star method.',
 cnLog:['空宫指本宫无十四主星，不等于无星，辅星、煞星与生年四化仍落在那里。','空宫的基本读法是借对宫安星，再合三方四正，看这件事的资源和阻力从哪来。','多个空宫要分别处理，每个宫看是哪一层（本命/大限/流年）在引动，不能一句「全空」带过。','空宫多的盘尤其要先定盘，确认出生时辰无误后再下结论。'],
 enLog:['An empty palace has no major star but is not starless; assistant, malefic and natal transformation stars still land there.','The basic reading borrows stars from the opposite palace and then combines the trine to see where resources and resistance come from.','Multiple empty palaces are handled separately, each checked for which layer, natal, decade or year, activates it rather than dismissed as all empty.','A chart with many empty palaces especially needs the chart confirmed, verifying the birth time before conclusions.',],
 cnStep:['先标出所有空宫，数清到底有几个、分布在哪些事务上','每个空宫先借对宫主星，写出它的基本倾向','再合该宫三方四正，数吉星煞星与四化，看净效果','查生年四化是否落入空宫，定先天有没有被补一笔','看大限、流年怎么经过这些空宫，定什么时候被引动','定盘核对无误后再下结论，宁可慢在前面'],
 enStep:['Mark all empty palaces and count how many there are and which affairs they sit on','For each, first borrow the opposite major star and write its basic tendency','Then combine that palace trine, count auspicious, malefic and transformation stars for the net effect','Check whether natal transformations land in the empty palace to see if the baseline adds support','Read how the decade and year pass through these palaces to see when they activate','Confirm the chart and verify before concluding, preferring to be slow early'],
 cnMis:['把空宫等同「没有」，自我设限','所有空宫一概而论，不分别借对宫、看引动','不做定盘就凭空宫下结论，时辰错了全盘偏'],
 enMis:['Equating empty palaces with nothing and limiting yourself','Treating all empty palaces alike without borrowing opposites and checking activation','Concluding from empty palaces without confirming the chart, so a wrong time shifts everything'],
 cnClose:'空宫多的功课，是把「借」和「定」做扎实。每个宫分别借来对宫的星、对清四化、定准时辰，这张盘一点不比满盘星的盘单薄。',
 enClose:'Reading many empty palaces teaches solid borrowing and confirming. Borrow each opposite star, match the transformations and verify the time, and the chart is no thinner than one full of stars.'},

{cat:'kanpan',slug:'ziwei-pan-sihua-duo-ruhe-zhua-zhongdian',focus:'四化很多的盘',focusEn:'charts with many transformations in play',
 cnT:'盘上四化太多怎么抓重点：先分层，再分禄忌',enT:'How to Find Focus When Many Transformations Appear: Layer First, Then Lu and Ji',
 cnD:'本命、大限、流年四化叠在一起动辄十几颗，抓重点的方法是先按时间分层、再按禄忌优先，先定主线，权科与细节往后放。',
 enD:'Natal, decade and year transformations can stack into a dozen or more; the way to focus is to layer by time first and then prioritize Lu and Ji, settling the main line before placing Quan, Ke and details.',
 cnL:'四化一多就容易眼花，其实不是每颗都一样重，分层之后真正要盯的往往就两三处。',
 enL:'Many transformations dazzle, but they are not all equal; after layering, the ones that truly need attention are usually just two or three.',
 cnA:'有人看到盘上四化密密麻麻，就觉得处处是重点、处处要操心，问题不在四化多，而在没分层、没分主次地一锅看。',
 enA:'Seeing dense transformations, some feel every point is central and worth worrying over; the issue is not many transformations but viewing them all at once without layers or ranking.',
 cnLog:['四化分属三层：生年四化定先天底色，大限四化定十年主线，流年四化定当年触发。','同一层内，化禄、化忌牵动得失与执着，先看；化权、化科主掌控与名声，作为补充。','多层四化落在同一宫叫叠宫，该宫这一阶段被反复引动，是重点中的重点。','四化是表达方式的变化，不是孤立的吉凶分数，要连同宫主星一起读。'],
 enLog:['Transformations belong to three layers: natal set the innate baseline, decade set the ten-year main line and year set the annual trigger.','Within a layer, Hua Lu and Hua Ji move gain, loss and attachment and are read first; Hua Quan and Hua Ke govern control and reputation as support.','Transformations from several layers landing in one palace is overlap; that palace is repeatedly activated and is the top focus.','Transformations are changes in how stars express, not isolated good-bad scores, and are read with the palace major star.'],
 cnStep:['先把所有四化按生年、大限、流年分成三层，分开标记','每层先圈化禄、化忌落宫，定得失与执着所在','再看化权、化科，补充掌控力与名声的位置','找多层四化共同落入的宫位，定阶段重点','把重点宫连同宫主星和三方一起读，不孤立看化','最后用一两句话概括主线，其余细节不再平均用力'],
 enStep:['First sort all transformations into natal, decade and year layers and mark them separately','In each layer, circle where Hua Lu and Hua Ji land to locate gain, loss and attachment','Then read Hua Quan and Hua Ke to add where control and reputation sit','Find palaces where several layers land together to set the stage focus','Read the focus palaces with their major star and trine rather than viewing transformations alone','Finally summarize the main line in a sentence or two and stop giving every detail equal weight'],
 cnMis:['所有四化平均看，结果没有重点','只看流年一层，不先生年、大限定底色','把化忌全当坏、化禄全当好，不看落星落宫'],
 enMis:['Viewing all transformations equally and ending with no focus','Reading only the year layer without setting the natal and decade baseline','Taking every Hua Ji as bad and Hua Lu as good without the star and palace'],
 cnClose:'四化多的功课是「先分层、再抓禄忌、最后收成一句话」。主线一旦定出来，信息再多也不会把你带乱。',
 enClose:'Many transformations teach layering, then catching Lu and Ji, then reducing to a sentence. Once the main line is set, no amount of information scatters you.'},

{cat:'kanpan',slug:'ziwei-yizhang-pan-ruhe-zhao-zhuzhou',focus:'本命主轴',focusEn:'the natal chart main thread',
 cnT:'一张盘怎么找本命主轴：这一生被什么牵引',enT:'How to Find the Natal Main Thread: What Pulls This Life',
 cnD:'本命主轴看的是这一生反复围绕的主题，方法是把生年四化与命财官三合合起来提炼，先定长期主线，再交给大限看它在哪个阶段展开。',
 enD:'The natal main thread is the theme a life keeps returning to; extract it by combining the natal transformations with the Life-Wealth-Career trine, settling the long line first and then using the decades to see where it unfolds.',
 cnL:'主轴不是某一颗星，而是整张盘反复指向的那件事，找出来之后，很多看似分散的选择都能串成一条线。',
 enL:'The main thread is not one star but the matter the whole chart keeps pointing to; once found, many scattered choices line up into one thread.',
 cnA:'有人读盘逐宫断吉凶，断了很多却答不出「这一生主要在修什么」，问题不在看得不细，而在没有从全盘提炼主轴这一步。',
 enA:'Some read palace by palace and judge much yet cannot answer what this life is mainly working on; the issue is not lack of detail but the missing step of extracting a whole-chart thread.',
 cnLog:['生年四化是主轴的第一条线索：禄在哪得、权在哪掌、科在哪名、忌在哪执着。','命财官三合定主轴落在自我、赚钱还是事业的比重，三者合看才完整。','主轴通常一主一辅，长期反复出现，具体事件由大限流年展开。','主轴是倾向而非定局，选择和行动会改变它展开的方式。'],
 enLog:['Natal transformations are the first clue to the main thread: where Lu gains, Quan controls, Ke names and Ji attaches.','The Life-Wealth-Career trine sets whether the thread weighs on self, earning or work, and all three are read together.','The thread usually has one main and one supporting theme that recur over time, with specific events unfolded by decades and years.','It is a tendency, not a fixed outcome; choices and actions change how it unfolds.'],
 cnStep:['先列生年四化落宫，写出这张盘最在意的几件事','再合命财官三合，看主轴偏自我、财富还是事业','把反复出现的主题收成一主一辅两条线','对照过往经历，验证主轴是否成立、不硬套','再看大限安排，定主轴在哪些年龄段展开','最后只把主轴当方向，具体决定仍结合现实'],
 enStep:['List where the natal transformations land and write what the chart cares about most','Then combine the Life-Wealth-Career trine to see whether the thread leans self, wealth or career','Reduce recurring themes into one main and one supporting line','Verify the thread against past experience rather than forcing it','Then read the decade arrangement to see at which ages the thread unfolds','Finally treat the thread only as direction and make concrete decisions against reality'],
 cnMis:['逐宫断吉凶，却没有全盘主轴','把主轴当定局，忽略选择的修正','只看主星不看四化，提炼不出牵引点'],
 enMis:['Judging palace by palace without a whole-chart thread','Taking the thread as fixed and ignoring correction by choice','Reading only major stars without transformations and failing to find the pull'],
 cnClose:'找主轴的功课，是从「一堆吉凶」升到「一条线」。主轴清楚之后，你会更容易分清哪些事值得投入、哪些只是插曲。',
 enClose:'Finding the main thread moves you from a pile of verdicts to one line. With it clear, you more easily tell what deserves investment and what is only an interlude.'},

{cat:'kanpan',slug:'ziwei-liuyue-liuri-ding-yingqi-dao-yue-dao-ri',focus:'流月流日应期',focusEn:'pinning timing with monthly and daily stars',
 cnT:'大限流年定了年份，流月流日怎么把应期定到月到日',enT:'After Decade and Year Set the Year, How Monthly and Daily Stars Pin Timing to Month and Day',
 cnD:'大限、流年先把事件定到某一年，再用流月四化收窄到月份、流日干支收窄到日子；越细的层级越只做微调，不能反过来主导吉凶。',
 enD:'The decade and year first place an event in a given year, then monthly transformations narrow it to a month and daily stems narrow it to a day; the finer layers only fine-tune and must not reverse the main verdict.',
 cnL:'流月流日像放大镜，年份这一层定了之后，它们帮你找更合适的那几周、那几天去行动。',
 enL:'Monthly and daily stars act like a magnifier; once the year layer is set, they help find the better weeks and days to act.',
 cnA:'有人跳过本命大限，直接用流日断今天吉凶，结果舍本逐末，问题不在流日不准，而在把最细的微调层当成了主导层。',
 enA:'Some skip the natal chart and decade and use daily stars to judge today, missing the essentials; the issue is not an inaccurate day layer but treating the finest adjustment as the governing one.',
 cnLog:['应期分层：大限主十年、流年主一年、流月主一月、流日主一日，层级越细作用越轻。','流月以流月四化看当月引动，常用于在已定的年份里挑月份。','流日以流日干支与所落宫位看短期节奏，多用于择日、安排重要会面。','细层只做微调，若本命大限不支持，再好的流日也托不起大事。'],
 enLog:['Timing is layered: the decade governs ten years, the year one year, the month one month and the day one day, with finer layers carrying less weight.','Monthly transformations show that month activation and are often used to choose a month within a set year.','Daily stems and the palace they land on show short-term rhythm, mostly used to pick a day or schedule key meetings.','Finer layers only fine-tune; if the natal chart and decade do not support it, even the best day cannot carry a major matter.'],
 cnStep:['先用大限、流年把事件定到某一年，不越级','在该年里用流月四化，找出被引动的那一两个月','再用流日干支，在目标月份里挑几天合适的日子','重要行动避开明显相冲的流日，选与事件相生的日子','把细层结论放回本命大限核对，不喧宾夺主','平日只用到流年即可，重大决定才细化到月日'],
 enStep:['First use the decade and year to place an event in a year without skipping layers','Within that year use monthly transformations to find the one or two activated months','Then use daily stems to pick suitable days in the target month','For important actions avoid clearly clashing days and choose ones that support the matter','Check the fine-layer conclusion against the natal chart and decade so it does not dominate','Use only the year layer ordinarily and refine to month and day only for major decisions'],
 cnMis:['跳过本命大限，直接用流日主导吉凶','把流月流日当定论，忽略它们只是微调','不会分层，所有时间信息混在一起看'],
 enMis:['Skipping the natal chart and decade and letting daily stars govern the verdict','Taking monthly and daily stars as final and ignoring that they only fine-tune','Failing to layer and viewing all timing information at once'],
 cnClose:'流月流日的功课，是「先有年、再挑月、最后择日」。守住层级顺序，细层能帮你把行动的节拍踩得更准，而不是把判断带偏。',
 enClose:'Monthly and daily stars teach having the year first, then choosing a month and finally a day. Keep the layer order and the fine levels sharpen your timing rather than skewing the judgment.'},

{cat:'kanpan',slug:'ziwei-ruhe-panduan-yizhang-pan-gaodi',focus:'一张盘的高低层次',focusEn:'the overall level of a chart',
 cnT:'怎么判断一张盘的高低层次：不看单颗星，看净组合',enT:'How to Judge a Chart Overall Level: Not One Star, but the Net Combination',
 cnD:'盘的高低不取决于有没有某颗吉星，而看主星庙旺、三方四正净组合与四化能否成格；先看整体结构，再谈单宫强弱。',
 enD:'A chart level does not depend on owning a certain auspicious star but on major-star brightness, the net triple-direction combination and whether transformations form a pattern; read the overall structure before individual palace strength.',
 cnL:'层次是整张盘的事，单颗星再亮也撑不起全盘，组合干净、四化接得上，层次才上得去。',
 enL:'Level concerns the whole chart; one bright star cannot carry it, and only a clean combination with well-connected transformations raises it.',
 cnA:'有人见命宫有紫微就判高、见一颗煞星就判低，结果时灵时不灵，问题在拿单颗星给整张盘定级。',
 enA:'Some rate a chart high for Zi Wei in Life and low for one malefic, then find it inconsistent; the issue is grading the whole chart by a single star.',
 cnLog:['先看命宫主星庙旺与三方四正，定主体是舒展还是受限。','再数三方的吉星、煞星与四化净效果，吉多煞少有制才算稳。','三看四化能否成格，禄权科接续、不被煞忌冲破，层次更高。','高低是相对的层次而非绝对等级，且大运配合决定层次何时兑现。'],
 enLog:['First read the Life Palace major star brightness and its trine to see whether the core expresses or is constrained.','Then count the net effect of auspicious stars, malefics and transformations in the trine; more good than harm, with control, means steady.','Third see whether transformations form a pattern, with Lu, Quan and Ke connected and not broken by malefics or obstruction, for a higher level.','Level is relative rather than an absolute rank, and decade cooperation decides when it is realized.'],
 cnStep:['先看命宫与三方主星庙旺，定主体强弱','数三方四正的吉星煞星，算净效果而非单点','梳理生年四化，看禄权科能否接续成格','检查煞忌有没有冲破关键结构','再看大限安排，定高的层次在哪个阶段兑现','最后只做相对判断，不贴绝对高低标签'],
 enStep:['First read the Life Palace and trine major-star brightness to set core strength','Count auspicious and malefic stars in the trine for the net effect rather than one point','Trace natal transformations to see whether Lu, Quan and Ke connect into a pattern','Check whether malefics and obstruction break the key structure','Then read the decade arrangement to see at which stage the higher level is realized','Finally make only relative judgments without absolute high-low labels'],
 cnMis:['拿单颗吉星或煞星给全盘定级','只看本命不看大限，判断层次何时兑现','把层次当固定等级，忽略组合的净效果'],
 enMis:['Grading the whole chart by one auspicious or malefic star','Reading only the natal chart without decades to see when level is realized','Taking level as a fixed rank and ignoring the net combination'],
 cnClose:'判断高低的功课，是把视线从「一颗星」拉到「一张网」。净组合和成格条件清楚了，层次判断才稳，也才谈得上什么时候兑现。',
 enClose:'Judging level teaches lifting the eye from one star to one network. Once the net combination and pattern conditions are clear, the level reads steadily and you can say when it is realized.'},

{cat:'kanpan',slug:'ziwei-kanpan-xiankan-daxian-haishi-liunian',focus:'先看大限还是流年',focusEn:'whether to read the decade or the year first',
 cnT:'看盘先看大限还是先看流年：本命为体，大限先于流年',enT:'Read the Decade or the Year First: Natal as the Base, Decade Before Year',
 cnD:'正确顺序是本命为体、先大限定十年底色、再流年定当年触发；跳过十年直接看流年，容易把短期波动误当成长期方向。',
 enD:'The right order is natal as the base, then the decade to set the ten-year tone, then the year to set that year trigger; skipping the decade to read the year makes short-term fluctuation look like long-term direction.',
 cnL:'大限是流年的背景，先知道这十年整体往哪走，再看某一年的好坏才有坐标。',
 enL:'The decade is the background to the year; knowing where the ten years head first gives a coordinate for any single year.',
 cnA:'有人一上来就问今年运势，只看流年就下结论，结果好年坏年都判断得很飘，问题在缺了大限这层背景。',
 enA:'Some ask at once about this year and conclude from the year alone, then find good and bad years read loosely; the issue is the missing decade background.',
 cnLog:['本命为体，描述一生的结构与底色，是所有判断的前提。','大限为用，十年一段，定这一阶段的主线与资源，先于流年。','流年再为用，在大限背景下定当年的具体触发与节奏。','顺序颠倒会以偏概全：流年再好在差的大限里也有限，再差在好的大限里也有托底。'],
 enLog:['The natal chart is the base, describing lifelong structure and tone and the premise of every judgment.','The decade is the first application, a ten-year segment setting that stage main line and resources before the year.','The year is then applied within the decade background to set that year specific trigger and rhythm.','Reversing the order overgeneralizes: a good year in a weak decade is limited, and a bad year in a strong decade still has support.'],
 cnStep:['先排本命盘，定一生结构与三方四正','再找当前大限，读十年主线、四化与资源','在大限背景下定位今年流年，看当年引动','把流年结论放回大限核对，判断力度与边界','需要行动时再参考流月流日微调','养成「本命—大限—流年」固定顺序，不跳级'],
 enStep:['First cast the natal chart to set lifelong structure and trines','Then find the current decade and read its ten-year main line, transformations and resources','Within the decade background locate this year and see its activation','Check the year conclusion against the decade to gauge strength and bounds','When acting, refer to monthly and daily stars for fine adjustment','Build the fixed natal, decade, year order without skipping'],
 cnMis:['跳过大限，只看流年就下结论','把流年波动当长期方向','顺序混乱，各层结论互相打架'],
 enMis:['Skipping the decade and concluding from the year alone','Taking annual fluctuation as long-term direction','Mixing the order so layer conclusions conflict'],
 cnClose:'先看大限还是流年的功课，是守住「体—用」的次序。十年底色清楚了，某一年的好坏才看得准、放得对位置。',
 enClose:'Decade-before-year teaches keeping the base-and-application order. With the ten-year tone clear, any single year reads accurately and sits in its proper place.'},

{cat:'rumen',slug:'ziwei-shisi-zhuxing-zenme-ji-zuikuai',focus:'记十四主星',focusEn:'memorizing the fourteen major stars',
 cnT:'十四主星怎么记最快：分组加对星，比死背顺序牢',enT:'How to Memorize the Fourteen Major Stars Fast: Groups and Pairs Beat Rote Order',
 cnD:'把十四主星按领导、开创、理财、智谋、服务分组，再用太阳太阴、天府天相等对星串起来，记住功能分工比背顺序快得多。',
 enD:'Group the fourteen major stars by leading, pioneering, managing, strategizing and serving, then link them through pairs such as Sun-Moon and Treasury-Minister; remembering functional roles is far faster than reciting order.',
 cnL:'记星不是背名册，而是先分清每颗星「主要管什么」，再用分组和对星把它们串成几类。',
 enL:'Memorizing stars is not reciting a roster but first sorting what each mainly governs and then linking them into groups and pairs.',
 cnA:'有人从紫微开始顺着背，背到后面就混，问题不在记性，而在把十四颗星当成互不相干的名词硬记。',
 enA:'Some recite from Zi Wei and get mixed up later; the issue is not memory but treating the fourteen stars as unrelated terms to force in.',
 cnLog:['可按功能分组：紫微天府主领导守成，杀破贪主开创变动，武曲主理财，天机天梁主智谋原则，太阳太阴主明暗，天同天相主服务协调，巨门主辨析。','对星帮助记忆：太阳与太阴、天府与天相、天同与天梁常成对理解。','先记每颗星一句话功能，再学庙旺和落宫的变化。','用自己盘的命宫主星做锚点，比抽象背诵更牢。'],
 enLog:['Group by function: Zi Wei and Tian Fu lead and preserve, Qi Sha, Po Jun and Tan Lang pioneer and change, Wu Qu manages resources, Tian Ji and Tian Liang handle strategy and principle, Sun and Moon cover light and shade, Tian Tong and Tian Xiang serve and coordinate, and Ju Men analyzes.','Pairs aid memory: Sun and Moon, Tian Fu and Tian Xiang, and Tian Tong and Tian Liang are often understood together.','First remember one-line functions, then learn brightness and palace changes.','Use your own Life Palace major star as an anchor; it sticks better than abstract recitation.'],
 cnStep:['先把十四主星按功能分成五到六组，降低记忆量','每组用一句话概括共同主题','再记三到四组对星，用对照加深印象','每颗星写一句「它主要管什么」','用自己盘和熟人盘的主星逐一对号','最后再学这些星遇到四化、落宫怎么变化'],
 enStep:['First split the fourteen stars into five or six functional groups to shrink the load','Summarize each group shared theme in one line','Then learn three or four pairs and deepen them through contrast','Write one line for each star on what it mainly governs','Match the stars on your chart and familiar charts one by one','Finally learn how they change with transformations and palaces'],
 cnMis:['顺着顺序死背，容易混、忘得快','只记名不记功能，不会用','一上来就背庙旺落宫，基础没立住'],
 enMis:['Reciting in order, which mixes easily and fades fast','Memorizing names without functions and being unable to use them','Learning brightness and palaces at once before the basics hold'],
 cnClose:'记主星的功课，是「先分组、再配对、抓功能」。框架立住之后，再往里面填庙旺、四化和落宫，就不会越学越乱。',
 enClose:'Memorizing major stars teaches grouping, pairing and grasping function. With the frame set, fill in brightness, transformations and palaces and learning no longer tangles.'},

{cat:'rumen',slug:'ziwei-ruhe-lijie-xingyao-zuhe',focus:'星曜组合',focusEn:'how stars work in combination',
 cnT:'怎么理解星曜靠组合而非单星：一颗星会随同伴变意思',enT:'How to Understand Stars Through Combination, Not Alone: One Star Changes Meaning With Its Company',
 cnD:'同颗星落不同宫、遇不同同伴和四化，含义会明显变化；先建立「星+宫+化」的组合读法，比孤立背单星判语准确得多。',
 enD:'The same star changes meaning across palaces, companions and transformations; building a star-plus-palace-plus-transformation reading is far more accurate than memorizing isolated star verdicts.',
 cnL:'星曜不是固定标签，它像演员，落在什么宫位、和谁同台、有没有被四化点到，演出来就不一样。',
 enL:'A star is not a fixed label; like an actor, it performs differently depending on the palace, the company and whether a transformation touches it.',
 cnA:'有人背了一堆单星断语，套到真盘上却不准，问题不在断语错，而在真实盘里没有一颗星是单独存在的。',
 enA:'Some memorize many single-star verdicts and find them off on real charts; the issue is not wrong verdicts but that on a real chart no star exists alone.',
 cnLog:['星曜含义由三层决定：本宫星性是底色，同宫与三方的同伴是加减，四化是表达方式的改变。','吉星遇煞星会打折，煞星遇吉星与化科可被制，净效果才是结论。','同一颗星落不同宫位，事务主题不同，表现也随之改变。','组合读法要先抓主星定方向，再看辅煞与四化做修正。'],
 enLog:['A star meaning is set on three layers: its own nature as the baseline, its companions in the palace and trine as additions, and transformations as changes in expression.','An auspicious star meeting a malefic is discounted, while a malefic meeting auspicious stars and Hua Ke can be controlled; the net effect is the conclusion.','The same star in different palaces changes the affair theme and therefore its expression.','Combination reading first uses the major star to set direction and then assistant, malefic and transformation stars to correct it.'],
 cnStep:['先认本宫主星的基本星性，定方向','再看同宫有没有另一颗主星，判断是相助还是拉扯','合三方四正，数辅星煞星，算净效果','查四化有没有点到这颗星，看表达方式变化','把亮度（庙旺落陷）一并纳入，判断力量大小','最后合起来下结论，不拿任何单星判语直接套用'],
 enStep:['First recognize the home major star basic nature to set direction','Then see whether another major star shares the palace, helping or pulling','Combine the trine and count assistant and malefic stars for the net effect','Check whether a transformation touches the star and how expression changes','Include brightness, exaltation or fall, to gauge power','Finally conclude together without applying any single-star verdict directly'],
 cnMis:['孤立背单星断语，到处硬套','只看本宫不看同伴和三方','见一颗煞星就判坏，忽略净效果'],
 enMis:['Memorizing isolated star verdicts and forcing them everywhere','Reading only the home palace without companions and trine','Judging one malefic as bad and ignoring the net effect'],
 cnClose:'星曜组合的功课，是养成「先主星、再同伴、后四化」的连读习惯。这样读盘，你对一颗星的判断才会随情境立体起来。',
 enClose:'Star combination teaches the connected habit of major star first, companions next and transformations after. Reading this way makes your judgment of a star three-dimensional across situations.'}
];
