// 2026-10-07 调研驱动 第5组：应用 6（考试季/买房选房/出差外派/合作签约/养老规划/离婚财产）+ 格局 2（左右夹命/命身同宫）
module.exports=[
{cat:'yingyong',slug:'ziwei-kaoshi-jixiao-ruhe-kan',focus:'考试季',focusEn:'exam season',
 cnT:'考试季怎么看：文昌化科与流年节奏，努力仍是主体',enT:'How to Read Exam Season: Wen Chang, Hua Ke and Timing',
 cnD:'考试运看官禄宫、文昌文曲与流年有没有化科引动，利考试的年份节奏更顺；但盘只给状态和节奏，复习、方法和临场发挥才是主体，不努力光看流年没用。',
 enD:'Exam fortune reads the Career Palace, Wen Chang Wen Qu and whether the year has Hua Ke activation; favorable timing runs smoother. But the chart only gives state and timing; review, method and performance are the substance, and timing without effort is useless.',
 cnL:'流年文昌化科像考试时灯调亮了、状态更顺，但灯亮不替你答题；节奏对了，努力更出效果。',
 enL:'Annual Wen Chang Hua Ke is like a brighter light and smoother state in exams, but the light does not answer for you; with right timing, effort yields more.',
 cnA:'有人见化科就当一定考中、不复习，也有人流年不利就放弃；正确是节奏顺时抓紧、不顺时更努力。',
 enA:'Some see Hua Ke and assume passing without review, others give up in an unfavorable year; the right way is seize smooth timing and work harder when not.',
 cnLog:['看官禄宫与文昌文曲，定考试底子。','流年化科、魁钺引动，状态名声更顺。','看大限，定这阶段利不利进修考证。','努力、方法、心态是主体，流年只加减。'],
 enLog:['Read Career Palace and Wen Chang Wen Qu for the exam foundation.','Annual Hua Ke and Kui Yue activation smooth state and name.','Read the decade for whether the stage favors study and certification.','Effort, method and mindset are the substance; the year only adjusts.'],
 cnStep:['先看官禄宫与昌星的底子','查流年有没有化科引动','看大限利不利进修','节奏顺：抓紧报考、全力复习','节奏一般：更重方法和努力','临场以状态为主，不被流年干扰'],
 enStep:['First read the Career Palace and literary stars','Check whether the year has Hua Ke activation','Read whether the decade favors study','Smooth timing: seize registration and review fully','Average timing: emphasize method and effort more','At the exam focus on state, not the year'],
 cnMis:['见化科就当必中、不努力','流年不利就放弃','只看流年不看大限和基础'],
 enMis:['Seeing Hua Ke and assuming passing without effort','Giving up in an unfavorable year','Seeing only the year without decade and foundation'],
 cnClose:'考试季看的是「节奏对了、努力怎么更出效果」。昌星化科给状态，复习方法给结果，两者都有才考得好。',
 enClose:'Exam season asks how effort yields more with right timing. Literary stars and Hua Ke give state, review and method give results; with both you perform well.'},

{cat:'yingyong',slug:'ziwei-maifang-xuanfang-ruhe-kan',focus:'买房选房',focusEn:'buying and choosing a home',
 cnT:'买房选房怎么看：田宅宫看缘分，合同渠道是底线',enT:'How to Read Buying and Choosing a Home',
 cnD:'田宅宫看不动产缘分与家庭节奏，结合财帛判断购买力；但买房最终靠现实：预算、地段、贷款、正规合同与开发商资质，命理只给节奏参考，不构成投资建议。',
 enD:'The Property Palace reads real-estate bonds and home timing, combined with Wealth for purchasing power. But buying ultimately relies on reality: budget, location, loans, proper contracts and developer qualifications; astrology only gives timing, not investment advice.',
 cnL:'田宅宫利置业的年份，像买房的窗口开了；但窗口开了，钱、合同、资质一样不能少。',
 enL:'Years when the Property Palace favor buying are like an open window; but with the window open, money, contracts and qualifications are still required.',
 cnA:'有人见田宅吉化就冲动买房、不查资质，也有人完全不信节奏；正确是参考节奏、守住现实底线。',
 enA:'Some see Property auspicious transformations and buy impulsively without checking qualifications, others ignore timing; the right way references timing and guards reality.',
 cnLog:['田宅宫看不动产缘分、家庭与财库。','逢化禄禄存、吉星，利置业。','合财帛官禄，判断购买力和还款力。','合同、贷款、资质以正规渠道和书面为准。'],
 enLog:['The Property Palace reads real-estate bonds, home and treasury.','With Hua Lu, Lu Cun and auspicious stars, buying is favored.','Combine Wealth and Career for purchasing and repayment power.','Contracts, loans and qualifications rely on proper channels and writing.'],
 cnStep:['先看田宅宫与流年置业节奏','合财帛，定预算和贷款能力','现实选地段、看房、核验资质','合同条款逐条看、以书面为准','留足应急钱、不掏空现金流','决策以正规产品说明为准，不构成投资建议'],
 enStep:['First read the Property Palace and annual buying timing','Combine Wealth for budget and loan ability','Choose location, view homes and verify qualifications in reality','Read contract terms one by one, rely on writing','Keep enough emergency funds, do not empty cash flow','Decide by official product terms, not investment advice'],
 cnMis:['见吉化就冲动买房、不查资质','掏空现金流、不留应急钱','把命理当保证，忽略合同风险'],
 enMis:['Seeing auspicious transformations and buying impulsively without qualifications','Emptying cash flow without emergency funds','Taking astrology as guarantee, ignoring contract risk'],
 cnClose:'买房选房看的是「置业窗口和现实底线」。田宅给节奏，预算合同资质给保障，两者都有，买房才稳。命理倾向不构成投资建议，以持牌机构和正规合同为准。',
 enClose:'Buying a home reads the property window and reality baseline. Property gives timing, budget-contract-qualifications give security; with both, buying is steady. This cultural-tendency reference is not investment advice; defer to licensed institutions and proper contracts.'},

{cat:'yingyong',slug:'ziwei-chucha-waipai-ruhe-kan',focus:'出差外派',focusEn:'business trips and out-of-town assignments',
 cnT:'出差外派怎么看：迁移宫看在外际遇，逢禄马利外出',enT:'How to Read Business Trips and Out-of-Town Assignments',
 cnD:'迁移宫看在外的状态与际遇，逢天马、化禄引动利出差外派、动中求财；逢煞忌防在外阻滞、劳损和口舌，外出的顺逆仍要合本命迁移三方看。',
 enD:'The Travel Palace reads your state and encounters away; with Tian Ma and Hua Lu activation, trips and assignments are favored with gain through movement. With malefics, guard obstacles, exhaustion and disputes away; travel outcomes still combine natal Travel trines.',
 cnL:'迁移逢禄马像顺风出门，机会在外；逢煞忌像逆风，要防奔波无所得和身体劳损。',
 enL:'Travel with Lu Ma is like departing with a tailwind, opportunity away; with malefics it is a headwind; guard running for nothing and exhaustion.',
 cnA:'有人见天马就怕奔波推掉机会，也有人见吉就什么外派都接；正确是看方向和身体，选择性地接。',
 enA:'Some see Tian Ma and fear travel, turning down opportunity; others take every assignment when seeing auspicious; the right way chooses by direction and health.',
 cnLog:['迁移宫主外出际遇、外缘、社会舞台。','逢天马化禄，利出差外派、动中求财。','逢魁钺，在外有贵人。','逢煞忌，防阻滞、劳损、口舌。'],
 enLog:['The Travel Palace governs travel encounters, outside ties and public stage.','With Tian Ma and Hua Lu, trips and assignments are favored with gain through movement.','With Kui Yue, there are mentors away.','With malefics, guard obstacles, exhaustion and disputes.'],
 cnStep:['先看迁移宫与流年引动','逢禄马：判断外派机会值不值','看在外贵人与资源','数煞忌，防阻滞劳损','评估身体精力，不硬接','安排好家庭和节奏，防两头拉扯'],
 enStep:['First read the Travel Palace and annual activation','With Lu Ma: judge whether the assignment is worth it','Read mentors and resources away','Count malefics to guard obstacles and exhaustion','Assess health and energy, do not force it','Arrange family and rhythm, guard two-way strain'],
 cnMis:['见天马就推机会、自我限制','什么外派都接、不看身体','不防在外阻滞劳损'],
 enMis:['Seeing Tian Ma and turning down opportunity, self-limiting','Taking every assignment without health checks','Not guarding obstacles and exhaustion away'],
 cnClose:'出差外派看的是「外出机会和身体节奏的平衡」。逢禄马抓机会、逢煞忌知防守，外派才是加分而不是劳损。',
 enClose:'Business trips read the balance between outside opportunity and health rhythm. Seize with Lu Ma, know guards with malefics, and assignments are a plus rather than exhaustion.'},

{cat:'yingyong',slug:'ziwei-hezuo-qianyue-ruhe-kan',focus:'合作签约',focusEn:'cooperation and signing contracts',
 cnT:'合作签约怎么看：交友官禄看合作，书面合同是底线',enT:'How to Read Cooperation and Signing Contracts',
 cnD:'合作看交友宫与官禄宫的配合，看双方分工与缘分；但签约最终靠书面合同、条款审核和专业律师，命理只提示合作节奏，口头承诺不作数。',
 enD:'Cooperation reads the Friends and Career Palaces for division and bonds. But signing ultimately relies on written contracts, term review and professional lawyers; astrology only hints at cooperation timing, and verbal promises do not count.',
 cnL:'交友宫利合作的年份像缘分到位，但缘分再好，权责、分成、退出条款也要白纸黑字。',
 enL:'Years when the Friends Palace favor cooperation are like bonds in place, but however good, authority, shares and exit terms must be in black and white.',
 cnA:'有人凭感情和口头约定就签约，结果纠纷无据；也有人完全不信合作节奏；正确是缘分参考、合同兜底。',
 enA:'Some sign on feelings and verbal promises, ending in disputes without evidence; others ignore cooperation timing; the right way references bonds and backs with contracts.',
 cnLog:['交友宫看合作缘分、伙伴类型。','官禄宫看合作做什么事。','逢吉星化禄，合作有助力。','权责、分成、违约、退出以书面合同和律师为准。'],
 enLog:['The Friends Palace reads cooperation bonds and partner types.','The Career Palace reads what the cooperation does.','With auspicious stars and Lu, cooperation has support.','Authority, shares, breach and exit rely on written contracts and lawyers.'],
 cnStep:['先看交友宫与合作缘分','合官禄，判断合作的事靠不靠谱','现实尽调对方资质和履约力','条款逐条谈、权责分成写清','签约前找专业律师审核','以书面合同为准，不凭口头'],
 enStep:['First read the Friends Palace and cooperation bonds','Combine Career to judge whether the matter is sound','In reality, do due diligence on qualifications and ability to perform','Negotiate terms one by one, write authority and shares clearly','Have a professional lawyer review before signing','Rely on written contracts, not verbal promises'],
 cnMis:['凭感情口头就签约','不做尽调、不审条款','把缘分当保证，忽略退出机制'],
 enMis:['Signing on feelings and verbal promises','No due diligence or term review','Taking bonds as guarantee, ignoring exit mechanisms'],
 cnClose:'合作签约看的是「缘分参考、合同兜底」。交友宫给节奏，书面条款和律师给保障，合作才走得远。以专业律师和正规途径、书面合同为准。',
 enClose:'Cooperation and signing read bonds as reference and contracts as backup. The Friends Palace gives timing, written terms and lawyers give security; cooperation then goes far. Rely on professional lawyers, proper channels and written contracts.'},

{cat:'yingyong',slug:'ziwei-yanglao-guihua-ruhe-kan',focus:'养老规划',focusEn:'retirement planning',
 cnT:'养老规划怎么看：田宅福德财帛看节奏，正规产品为准',enT:'How to Read Retirement Planning',
 cnD:'养老看田宅（居住）、福德（精神）、财帛（养老金）三宫配合与大限节奏；但规划最终靠正规金融产品、社保、合同和持牌机构，命理只给方向，不构成投资建议。',
 enD:'Retirement reads Property (housing), Karma (spirit) and Wealth (pension) together with decade timing. But planning ultimately relies on proper financial products, social security, contracts and licensed institutions; astrology only gives direction, not investment advice.',
 cnL:'养老规划像提前挖一口晚年的井，田宅财帛福德三宫看井在哪、有没有水；但井要靠正规工具挖。',
 enL:'Retirement planning is like digging a well for later years in advance; Property, Wealth and Karma show where and whether there is water; but the well is dug with proper tools.',
 cnA:'有人只靠命理节奏不做实际规划，也有人觉得养老还早不准备；正确是早规划、用正规产品、留合同。',
 enA:'Some rely only on timing without real planning, others feel retirement is far off and do not prepare; the right way plans early, uses proper products and keeps contracts.',
 cnLog:['田宅看养老居住安排。','财帛看养老金积累。','福德看晚年精神状态。','产品、社保、合同以持牌机构和书面为准。'],
 enLog:['Property reads retirement housing.','Wealth reads pension accumulation.','Karma reads later spiritual state.','Products, social security and contracts rely on licensed institutions and writing.'],
 cnStep:['先看田宅财帛福德三宫节奏','估算养老所需资金和居住安排','了解社保和正规养老产品','配置以稳健、合同清晰为准','留足医疗和应急安排','定期复盘，不构成投资建议'],
 enStep:['First read Property, Wealth and Karma timing','Estimate retirement funds and housing needs','Understand social security and proper retirement products','Allocate conservatively with clear contracts','Keep enough medical and emergency arrangements','Review regularly, not investment advice'],
 cnMis:['只看命理不做实际规划','觉得养老还早、不准备','轻信非正规养老产品'],
 enMis:['Relying only on timing without real planning','Feeling retirement is far and not preparing','Trusting non-formal retirement products'],
 cnClose:'养老规划看的是「三宫节奏和正规工具」。早准备、用持牌产品、守合同，晚年才有踏实的依靠。命理倾向不构成投资建议，以持牌机构说明为准。',
 enClose:'Retirement planning reads three-palace timing and proper tools. Prepare early, use licensed products and guard contracts, and later years have steady support. This cultural-tendency reference is not investment advice; defer to licensed institutions.'},

{cat:'yingyong',slug:'ziwei-lixian-caichan-ruhe-kan',focus:'离婚财产',focusEn:'divorce property division',
 cnT:'离婚财产怎么看：夫妻财帛田宅看分割，以律师法院为准',enT:'How to Read Divorce Property Division',
 cnD:'夫妻宫与财帛、田宅宫可看财产分割的倾向与纠葛；但离婚财产分割必须以婚姻法、专业律师、法院判决和书面协议为准，命理只提示关系与财产的节奏，不作法律依据。',
 enD:'The Spouse, Wealth and Property Palaces can show tendencies and entanglement in division. But divorce property must follow marriage law, professional lawyers, court judgments and written agreements; astrology only hints at relationship and property timing, not legal basis.',
 cnL:'离婚财产是关系断了、钱还要分清楚；盘能提示纠葛在哪，但怎么分、分多少，要走法律途径。',
 enL:'Divorce property is a bond ended and money still divided; the chart can hint at entanglement, but how and how much follows legal channels.',
 cnA:'有人凭盘判断对方会分走多少，其实没有法律效力；也有人情绪化处理、不留证据；正确是找律师、留书面、走正规途径。',
 enA:'Some judge from the chart how much the other gets, with no legal force; others handle it emotionally without evidence; the right way finds lawyers, keeps writing and takes proper channels.',
 cnLog:['夫妻宫看婚姻关系状态。','财帛田宅看共同财产与房产。','化忌空劫会照，提示分割纠葛。','分割以律师、法院、书面协议为准。'],
 enLog:['The Spouse Palace reads the marriage state.','Wealth and Property read joint assets and real estate.','Ji or emptiness in aspect hints at division entanglement.','Division relies on lawyers, courts and written agreements.'],
 cnStep:['先冷静，理清夫妻财帛田宅','盘点共同财产、债务、房产','保留财产和出资证据','找专业婚姻律师咨询','协商或诉讼，以书面协议或判决为准','不凭命理做法律判断'],
 enStep:['First stay calm and sort Spouse, Wealth and Property','Inventory joint assets, debts and real estate','Keep evidence of property and contributions','Consult a professional marriage lawyer','Negotiate or litigate, relying on written agreement or judgment','Do not make legal judgments from astrology'],
 cnMis:['凭盘判断分割结果、当法律依据','情绪化处理、不留证据','不走正规途径、口头约定'],
 enMis:['Judging division from the chart as legal basis','Handling emotionally without evidence','Not taking proper channels, verbal agreements'],
 cnClose:'离婚财产看的是「财产纠葛怎么依法分清」。盘只提示节奏，律师、法院和书面协议才是分割的依据，以专业律师和正规途径为准。',
 enClose:'Divorce property reads how asset entanglement is legally resolved. The chart only hints at timing; lawyers, courts and written agreements are the basis; rely on professional lawyers and proper channels.'},

{cat:'geju',slug:'ziwei-zuofu-youbi-jia-ming',focus:'左右夹命',focusEn:'Zuo Fu and You Bi flanking the Life Palace',
 cnT:'左右夹命：左辅右弼在左右，助力贴身',enT:'Zuo Fu and You Bi Flanking the Life Palace',
 cnD:'左辅、右弼分守命宫左右夹宫，主助力贴身、有人辅佐、做事有人帮；成格须无煞冲破，辅星帮的是肯做事的人，自身仍是主心骨。',
 enD:'Zuo Fu and You Bi guard the two flanking palaces around Life, bringing close support and assistance in doing. The pattern needs no malefic break; assistant stars help those willing to act, and the self remains the backbone.',
 cnL:'左右夹命像一左一右有帮手，做事不孤单；但帮手是辅佐，拍板和担当还在自己。',
 enL:'This pattern is like having helpers on either side, not alone in doing; but helpers assist, while decisions and responsibility remain yours.',
 cnA:'有人见左右夹命就当自己不用出力，结果辅佐也落空；辅星是助力，不是替代。',
 enA:'Some see Zuo You flanking and assume no effort needed, and support falls through; assistant stars are support, not replacement.',
 cnLog:['左辅右弼主辅佐、助力、协调。','夹命主贴身帮手、团队支撑。','逢吉化，助力更稳。','须无煞忌冲破，自身努力是根本。'],
 enLog:['Zuo Fu You Bi govern assistance, support and coordination.','Flanking brings close helpers and team support.','With auspicious transformations, support is steadier.','No malefic or Ji break; one own effort is the root.'],
 cnStep:['先确认左辅右弼在命宫左右','看二星亮度','数煞忌，看有没有冲破','看帮手所附星，定助力类型','结合自身担当，判断帮不帮得上','合大限，看助力何时到位'],
 enStep:['First confirm Zuo Fu You Bi flank Life','Read their brightness','Count malefics and Ji for breaks','Read the stars they attach to for support type','Combine your own responsibility to judge whether support lands','Layer the decade for when support arrives'],
 cnMis:['见左右夹命就当不用出力','不查煞忌冲破','把辅佐当替代'],
 enMis:['Seeing Zuo You flanking and assuming no effort','Not checking malefic or Ji breaks','Taking assistance as replacement'],
 cnClose:'左右夹命看的是「贴身助力和自身担当」。无煞破、肯做事，辅佐才真正帮得上，自己仍是主心骨。',
 enClose:'This pattern reads close support and one own responsibility. No malefic break and willingness to act, and assistance truly lands; the self remains the backbone.'},

{cat:'kanpan',slug:'ziwei-ming-shen-he-kan',focus:'命身同宫',focusEn:'Life and Body Palaces in the same position',
 cnT:'命身同宫怎么看：先天后天合一，性格与走向一致',enT:'Life and Body Palaces in the Same Position',
 cnD:'命宫身宫落在同一宫，先天性格与后天方向合一，主顺性发展、言行一致、少内耗；但同宫也意味着这一领域主题集中，成败都落在这，要看星曜组合和三方。',
 enD:'When Life and Body Palaces land in the same position, innate temperament and later direction align, bringing development with nature, consistency and less inner friction. But it also means the theme concentrates there, success and failure both landing in it; read the star combination and trines.',
 cnL:'命身同宫像一个人从小就知道自己要往哪走，先天后天不打架；但路集中在一条，好坏都在这。',
 enL:'This alignment is like knowing from early on where to go, innate and later not conflicting; but the path concentrates in one, good and bad both there.',
 cnA:'有人见命身同宫就当一定顺，其实主题集中也意味着这一宫的煞忌影响更重；仍要看星曜和三方。',
 enA:'Some see alignment and assume smoothness, but concentrated theme means malefics in that palace weigh more; still read stars and trines.',
 cnLog:['命身同宫=先天底色与后天重心一致。','主顺性、专注、少自我拉扯。','该宫主星定一生集中主题。','该宫煞忌影响更重，吉星助力也更集中。'],
 enLog:['Life-Body alignment = innate tone and later focus consistent.','It brings flow, focus and less self-pull.','The palace star sets the concentrated life theme.','Malefics there weigh more, auspicious support also concentrates.'],
 cnStep:['先确认命宫身宫同宫','看同宫主星，定集中主题','看星曜亮度，定顺不顺','数三方吉星，看助力集中','数煞忌，看集中风险','顺性深耕这一领域，成败都认'],
 enStep:['First confirm Life and Body align','Read the shared star for the concentrated theme','Read brightness for flow','Count trine auspicious stars for concentrated support','Count malefics for concentrated risk','Deepen in this area with nature, accept both outcomes'],
 cnMis:['见同宫就当一定顺、不看煞忌','忽略主题集中的风险','只看命宫不看身宫'],
 enMis:['Seeing alignment and assuming smoothness without malefics','Ignoring concentrated-theme risk','Reading only Life without Body'],
 cnClose:'命身同宫看的是「先天后天一致、主题集中」。顺性深耕、看清煞忌，专注是优势，但这一领域的功课也更集中。',
 enClose:'Life-Body alignment reads innate-later consistency and concentrated theme. Deepen with nature and see malefics; focus is an advantage, but the lesson in this area also concentrates.'}
];
