// 2026-10-01 调研驱动 第1组：日月命/日月福/机阴迁/紫府疾/武相兄/同梁父/七政四余/财富三宫 8篇
module.exports=[
{cat:'zhuxing',slug:'ziwei-taiyang-taiyin-zai-minggong',focus:'太阳太阴在命宫',focusEn:'the Sun and Moon together in the Life Palace',
 cnT:'太阳太阴同在命宫：又热又柔的人，怎么把两股劲用顺',
 enT:'Sun and Moon Together in the Life Palace: Balancing Warmth and Softness in One Nature',
 cnD:'太阳主热情外放、太阴主细腻内敛，两颗主星同在命宫的人，对人冷热、对钱松紧会随状态切换，显得丰富也容易纠结。关键不是消灭矛盾，而是让该出手时的太阳和该收束时的太阴各归各位。',
 enD:'The Sun is warm and outward while the Moon is sensitive and inward. People with both in the Life Palace shift between bold and gentle, generous and careful, which makes them rich in nature yet prone to inner conflict. The key is not removing the contrast but letting each side lead at the right moment.',
 cnL:'太阳太阴同坐命宫的人，常常让人摸不透：熟了之后你会发现他有时像小太阳、有时又安静得像换了个人，其实这不是反复无常，而是两种能量都在他身上。',
 enL:'People with the Sun and Moon in the Life Palace can be hard to read: once close, you find them sometimes bright and outgoing and sometimes quiet, almost like another person. This is less inconsistency than two energies both living in them.',
 cnA:'这个问题在问：日月同宫坐命到底是什么性格、怎么活得更顺。要先分清太阳和太阴各自管什么，再看在你这张盘上谁更有力、被什么星引动。',
 enA:'The question is what Sun-Moon in the Life Palace means and how to live it more smoothly. First separate what each star governs, then see which is stronger on your chart and what other stars activate it.',
 cnLog:['太阳主贵、主热情、奉献与外放，遇到事愿意冲在前面，也在意被看见、被认可。','太阴主富、主细腻、感受与内敛，擅长照顾细节、体察情绪，也需要安全感与私人空间。','两星同宫是「阴阳并照」：好处是既能开拓又懂善后，难处是两套反应模式会抢方向盘，表现为冷热、松紧、快慢的切换。','若三方见禄权科与吉曜，两星的切换会变成弹性；若见煞忌，则容易在该断时犹豫、该静时躁动。'],
 enLog:['The Sun governs nobility, warmth, dedication and outward expression, willing to take the lead and caring about being seen and recognized.','The Moon governs wealth, sensitivity, feeling and inward focus, skilled at details and emotions while needing safety and private space.','Together they bring both yin and yang: the strength is being able to open new ground and then tend it; the difficulty is two response modes competing for the wheel, showing as shifts between hot and cool, loose and careful, fast and slow.','With Lu, Quan, Ke and auspicious stars in the triple-direction, the shifts become flexibility; with malefics and Ji, one hesitates when one should decide and stirs when one should be still.'],
 cnStep:['先确认命宫是太阳太阴同宫，并看两星在该宫的亮度','再看三方四正的吉曜与煞忌，判断切换是弹性还是内耗','观察自己一天或一件事里，什么时候是太阳主导、什么时候是太阴主导','给太阳的热情设方向（值得投入的人和事），避免有求必应','给太阴的感受留空间（独处、休息、边界），避免一味硬撑','练一个「切换前停一下」的动作，让反应回到当下需要'],
 enStep:['First confirm the Sun and Moon share the Life Palace and check their brightness there','Then read the auspicious stars and malefics in the triple-direction to judge whether the shifts are flexibility or inner drain','Notice across a day or a task when the Sun leads and when the Moon leads','Give the Sun’s warmth a direction—people and causes worth investing in—rather than saying yes to everything','Leave room for the Moon’s sensitivity through solitude, rest and boundaries instead of forcing through','Build a pause-before-switching habit so the response fits what the moment needs'],
 cnMis:['把日月的切换当成「善变、不可靠」，急着改掉一半本性','只顺着太阳的热情走，长期不给太阴的感受留空间，结果透支','看到两星同宫就以为一定富贵，忽略了三方煞忌与后天经营'],
 enMis:['Taking the Sun-Moon shifts as being fickle or unreliable and rushing to remove half of the nature','Following only the Sun’s warmth and never making room for the Moon, ending in burnout','Assuming the two stars together guarantee wealth and status while ignoring the malefics and one’s own choices'],
 cnClose:'日月坐命的人，天赋是既能照亮别人也能照顾细节，功课是学会什么时候亮、什么时候柔。把两股劲用顺，你会比只有一种能量的人更有弹性。',
 enClose:'People with the Sun and Moon in the Life Palace can both brighten a room and tend the details; the lesson is knowing when to shine and when to soften. Used well, the two energies give more flexibility than a single nature allows.'},

{cat:'zhuxing',slug:'ziwei-taiyang-taiyin-zai-fudegong',focus:'太阳太阴在福德宫',focusEn:'the Sun and Moon together in the Karma Palace',
 cnT:'太阳太阴同在福德宫：精神世界又亮又细，怎么让心安定',
 enT:'Sun and Moon Together in the Karma Palace: A Mind That Is Both Bright and Refined',
 cnD:'福德宫管一个人内在的感受与满足方式，太阳太阴同落在这里，精神世界丰富、兴趣和情绪层次多，既能从奉献里得乐、也能从独处中得安；但两星拉扯时容易一会儿闲不住、一会儿想太多。',
 enD:'The Karma Palace governs inner feeling and how one finds satisfaction. With the Sun and Moon there, the inner world is rich and layered, able to enjoy both contribution and solitude, though the two can pull between restlessness and overthinking.',
 cnL:'福德宫有日月的人，常常心里同时住着一个闲不住的热心人和一个爱琢磨的细腻人，开心来源很多，烦恼来源也不少。',
 enL:'People with the Sun and Moon in the Karma Palace often carry both an earnest part that cannot sit still and a refined part that loves to reflect, giving them many sources of joy and many of worry.',
 cnA:'这个问题在问：日月在福德宫，内心满足感到底从哪来、怎么更安定。要先理解福德宫看的是「精神怎么自处」，再看两星谁主感受。',
 enA:'The question is where inner satisfaction comes from with the Sun and Moon in the Karma Palace and how to feel more settled. First understand that this palace is about how the mind holds itself, then see which star shapes feeling.',
 cnLog:['太阳在福德，主从付出、被需要、明朗的节奏里得到精神满足，闲下来反而容易发空。','太阴在福德，主从安静、审美、亲密的感受里得到滋养，需要留白与安全感。','两星同宫，精神满足有两条路：一条向外给、一条向内收，合得好是张弛有度。','若见煞忌，两星会在「闲不住」与「想不开」之间摆荡，睡眠和情绪最先受影响。'],
 enLog:['The Sun in the Karma Palace finds satisfaction through giving, being needed and a bright rhythm, and can feel empty when idle.','The Moon there is nourished by quiet, beauty and intimate feeling, needing white space and safety.','Together there are two routes to satisfaction—giving outward and gathering inward—and balanced they give real poise.','With malefics and Ji, the two swing between restlessness and taking things too hard, with sleep and mood affected first.'],
 cnStep:['先确认福德宫是太阳太阴同宫，并看两星亮度','把让自己开心的事分「向外奉献」和「向内静养」两类列出来','安排作息时两类都留时间，避免长期只用一种充电方式','太阳那股劲用在有意义的参与上，而不是瞎忙','太阴那股劲用在审美、休息和亲密关系上，而不是反刍念头','情绪起伏时先看是哪颗星被引动，再决定动还是静'],
 enStep:['First confirm the Sun and Moon share the Karma Palace and check their brightness','List the things that lift you, split into outward contribution and inward restoration','Make room in the week for both rather than recharging only one way','Channel the Sun into meaningful involvement rather than busywork','Channel the Moon into beauty, rest and close connection rather than replaying thoughts','When mood shifts, first see which star is activated, then decide whether to move or be still'],
 cnMis:['把福德宫的日月只当成「有福气」，不处理两种满足方式的冲突','长期只向外付出不给自己留白，把太阳的劲耗成疲惫','情绪一低就当成命不好，忽略了煞忌引动是阶段性、可调的'],
 enMis:['Treating the Sun-Moon in the Karma Palace only as good fortune without handling the two routes to satisfaction','Always giving outward and never leaving white space, wearing the Sun’s energy into fatigue','Reading low mood as a doomed fate instead of a stage triggered by malefics that can be adjusted'],
 cnClose:'日月在福德，给的是一个既需要发光、也需要安静的内心。把两种满足都照顾到，心自然会比只追一头时安定。',
 enClose:'The Sun and Moon in the Karma Palace give a mind that needs both to shine and to be still. Tending both kinds of satisfaction settles the heart more than chasing only one.'},

{cat:'zhuxing',slug:'ziwei-tianji-taiyin-zai-qianyigong',focus:'天机太阴在迁移宫',focusEn:'Tian Ji and Tai Yin together in the Migration Palace',
 cnT:'天机太阴同在迁移宫：在外善规划又细腻，怎么把路走宽',
 enT:'Tian Ji and Tai Yin Together in the Migration Palace: A Thoughtful, Refined Way Out in the World',
 cnD:'迁移宫管一个人在外部世界的舞台与机缘，天机善规划应变、太阴细腻懂感受，两星同落在这里，在外靠脑子和细致立足，适合需要策划、审美与沟通的外部发展；但要防想太多而迈不开、或在外过于敏感。',
 enD:'The Migration Palace governs one’s stage and opportunities in the outer world. Tian Ji plans and adapts while Tai Yin is sensitive and refined; together they build a place through thought and care, suiting external work that calls for strategy, taste and communication, while guarding against overthinking and oversensitivity.',
 cnL:'天机太阴在迁移的人，一到外面就会先观察、再盘算，做事细、懂分寸，常能靠周全和审美赢得外部机会，只是心里那台思考机器在外容易转得太快。',
 enL:'People with Tian Ji and Tai Yin in the Migration Palace observe and plan as soon as they step out, working carefully and with tact, often winning chances through thoroughness and taste, though the thinking can run too fast away from home.',
 cnA:'这个问题在问：机阴在迁移，外出发展到底是什么路数。要先理解迁移宫看的是「外部机缘与形象」，再看两星如何配合。',
 enA:'The question is what going out into the world looks like with Tian Ji and Tai Yin in the Migration Palace. First understand it governs outer opportunity and image, then see how the two stars work together.',
 cnLog:['天机主思维、策划与机变，在迁移宫主在外点子多、反应快、善安排路线与节奏。','太阴主细腻、审美与感受，在迁移宫主在外形象温和、懂体察，也容易因环境变化而敏感。','两星同宫是「用脑子、也用心」在外立足：适合策划、设计、咨询、文教、女性向市场等外部场景。','若见禄权科与吉曜，外部规划容易落地成机会；若见煞忌，则易在外反复权衡、迟迟不动，或因敏感而回避。'],
 enLog:['Tian Ji governs thought, planning and adaptiveness, giving many ideas, quick reactions and a good sense of route and timing away from home.','Tai Yin governs refinement, taste and feeling, giving a gentle outer image and empathy while making one sensitive to changes in environment.','Together one succeeds out in the world using both head and heart, suiting strategy, design, consulting, education and markets oriented toward women.','With Lu, Quan, Ke and auspicious stars, outer plans become real opportunities; with malefics and Ji, one weighs things endlessly and delays, or withdraws through sensitivity.'],
 cnStep:['先确认迁移宫是天机太阴同宫，并看两星亮度','再看三方四正吉曜煞忌，判断外部规划能否落地','列出在外发展真正想走的方向，避免被太多点子分散','把天机的策划落到具体时间表和下一步动作','给太阴的敏感设缓冲（提前熟悉环境、留休息时间）','结合大限流年，判断外部机缘被引动的阶段再发力'],
 enStep:['First confirm Tian Ji and Tai Yin share the Migration Palace and check their brightness','Then read the auspicious stars and malefics to judge whether outer plans can land','List the directions you truly want outside rather than scattering across too many ideas','Turn Tian Ji’s planning into a concrete timeline and next step','Build a buffer for Tai Yin’s sensitivity by scouting places early and leaving time to rest','With the decade and year, time your push to when outer opportunity is activated'],
 cnMis:['把机阴在迁移只当成「适合离家」，忽略了要靠规划和细致经营','在外想太多、把方案反复改，结果错过窗口','把敏感当成缺点硬压，反而让适应更吃力'],
 enMis:['Taking Tian Ji-Tai Yin in Migration as simply “meant to leave home” while ignoring the planning and care it needs','Overthinking and reworking plans away from home until the window passes','Forcing sensitivity down as a flaw, which makes adapting harder'],
 cnClose:'机阴在迁移，给的是一条靠脑子和细致走出去的路。把想法落成动作、给敏感留缓冲，外部的舞台会越走越宽。',
 enClose:'Tian Ji and Tai Yin in the Migration Palace give a path out into the world built on thought and care. Turning ideas into action and buffering sensitivity widens the outer stage over time.'},

{cat:'zhuxing',slug:'ziwei-ziwei-tianfu-zai-jiegong',focus:'紫微天府在疾厄宫',focusEn:'Zi Wei and Tian Fu together in the Health Palace',
 cnT:'紫微天府同在疾厄宫：底子厚但要防「硬扛」，身体喜欢有节奏',
 enT:'Zi Wei and Tian Fu in the Health Palace: A Strong Constitution That Must Not Be Run on Pride Alone',
 cnD:'疾厄宫管体质与身体的承压方式，紫微主尊贵、天府主厚实，两星同落在这里，先天底子通常不弱、恢复力尚可；但两星都偏「要强、能扛」，最容易出现的不是大病，而是长期硬撑、作息不规律带来的积压。',
 enD:'The Health Palace governs constitution and how the body bears pressure. Zi Wei carries dignity and Tian Fu solidity, so the baseline is usually strong with decent recovery; yet both tend toward pride and endurance, so the main risk is not sudden illness but the slow backlog of pushing too hard with irregular rest.',
 cnL:'紫府在疾厄的人，常给人「身体很能扛」的印象，小病小痛不爱说，习惯咬牙把事做完，问题往往就藏在这份能扛里。',
 enL:'People with Zi Wei and Tian Fu in the Health Palace often seem able to carry a great deal physically, saying little about minor ailments and gritting through the work; the risk hides in exactly that endurance.',
 cnA:'这个问题在问：紫府在疾厄，体质到底要注意什么。要先把疾厄宫读成「身体怎么承压」，再看两星要强的性格怎么落到作息。',
 enA:'The question is what to watch with Zi Wei and Tian Fu in the Health Palace. Read it as how the body bears pressure, then see how the stars’ pride shows up in daily routines.',
 cnLog:['紫微在疾厄，主身体有「主心骨」、底子不弱，但也主不肯示弱、容易忽略身体的提醒。','天府在疾厄，主体质厚实、脾胃与承载相关，怕长期过饱、过劳与缺乏舒展。','两星同宫是「又强又能扛」：好处是恢复力尚可，风险是把硬撑当本事，积压到一定程度才集中爆发。','若见煞忌，承压的节奏更容易断；若见禄科与吉曜，规律作息、定期体检时身体反而很稳。'],
 enLog:['Zi Wei in the Health Palace gives the body a strong core and decent baseline, but also a refusal to show weakness, making it easy to ignore signals.','Tian Fu there gives a solid constitution tied to digestion and capacity, disliking long-term overeating, overwork and lack of movement.','Together they mean strong and enduring: recovery is decent, but the risk is treating stubborn endurance as skill until pressure builds and releases at once.','With malefics and Ji the rhythm breaks more easily; with Lu, Ke and auspicious stars, regular rest and checkups keep the body steady.'],
 cnStep:['先确认疾厄宫是紫微天府同宫，并看两星亮度','把身体的「硬扛记录」列出来：哪些不适被一再延后','建立固定作息和运动节奏，给天府的厚实一个舒展出口','把定期体检、看牙、复查当成例行安排，不等到扛不住','紫微要强的劲用在长期自律上，而不是当下硬撑','出现持续不适时及时到正规医疗机构检查，不以感觉好代替检查'],
 enStep:['First confirm Zi Wei and Tian Fu share the Health Palace and check their brightness','List the endurance record—which symptoms have repeatedly been postponed','Build steady sleep and movement routines so Tian Fu’s solidity has an outlet','Treat regular checkups, dental visits and follow-ups as routine rather than waiting for a crisis','Use Zi Wei’s pride for long-term discipline rather than pushing through the moment','When symptoms persist, seek a licensed medical provider instead of trusting how you feel'],
 cnMis:['把紫府在疾厄只当成「身体好」，放心长期硬扛','把能扛当成资本，作息饮食长期不规律','身体出信号时先否定、拖延，错过最好处理的窗口'],
 enMis:['Taking Zi Wei-Tian Fu in the Health Palace only as strong health and pushing hard for years','Treating endurance as capital while keeping irregular sleep and eating habits','Denying and delaying when the body signals, missing the easiest window to act'],
 cnClose:'紫府在疾厄给的是一副好底子，也给了一个爱扛的性格。把要强用在规律和预防上，身体会比靠硬撑更稳。这里讲的是倾向而非诊断，具体不适以正规就医为准。',
 enClose:'Zi Wei and Tian Fu in the Health Palace give a strong baseline and a prideful, enduring nature. Directing that pride toward routine and prevention steadies the body more than grit alone. This is a tendency, not a diagnosis; for any symptom, rely on qualified medical care.'},

{cat:'liuqin',slug:'ziwei-wuqu-tianxiang-zai-xiongdigong',focus:'武曲天相在兄弟宫',focusEn:'Wu Qu and Tian Xiang together in the Siblings Palace',
 cnT:'武曲天相同在兄弟宫：平辈务实讲分寸，怎么处好这层关系',
 enT:'Wu Qu and Tian Xiang in the Siblings Palace: Practical, Principled Peers and How to Keep the Bond Steady',
 cnD:'兄弟宫看手足与同辈、也看平辈间的合作与资金往来，武曲务实讲规则、天相正派懂分寸，两星同落在这里，身边多是踏实、讲规矩的同辈，关系偏理性稳定；但两星都不擅甜腻表达，要防有事只讲原则、少了情分。',
 enD:'The Siblings Palace covers siblings and peers, along with peer-level cooperation and money matters. Wu Qu is practical and rule-oriented while Tian Xiang is upright and tactful, so the people around you tend to be steady and principled and the bond rational and stable, though neither is sentimental, so one must guard against principles crowding out warmth.',
 cnL:'武曲天相在兄弟宫的人，遇到事常能看到同辈里有人默默把责任担起来、按规矩办，关系不靠甜言蜜语，靠的是靠谱。',
 enL:'People with Wu Qu and Tian Xiang in the Siblings Palace often find a peer who quietly takes responsibility and does things by the book; the bond rests not on sweet words but on reliability.',
 cnA:'这个问题在问：武相在兄弟宫，手足同辈是什么相处模式。要先理解兄弟宫既看手足、也看平辈合作，再看两星怎么定关系基调。',
 enA:'The question is how siblings and peers relate with Wu Qu and Tian Xiang in the Siblings Palace. Understand it covers both family and peer cooperation, then see how the two stars set the tone.',
 cnLog:['武曲在兄弟宫，主同辈务实、讲规则、重责任，谈钱和分工时比较分明。','天相在兄弟宫，主同辈正派、懂分寸、能当协调者，关系里讲规矩也讲体面。','两星同宫是「务实＋正派」：同辈多是能一起办事的人，合作和资金往来相对清楚。','若见禄存化禄与吉曜，平辈能成为稳定助力；若见煞忌，则容易因分工、钱或原则问题生分。'],
 enLog:['Wu Qu in the Siblings Palace makes peers practical, rule-oriented and responsible, with clear lines around money and tasks.','Tian Xiang there makes peers upright, tactful and able to mediate, valuing both rules and dignity in the relationship.','Together they bring practicality and integrity: peers are people you can get things done with, and cooperation or money matters stay relatively clear.','With Lu Cun, Hua Lu and auspicious stars, peers become steady support; with malefics and Ji, distance grows over tasks, money or principles.'],
 cnStep:['先确认兄弟宫是武曲天相同宫，并看两星亮度','把身边同辈分「手足、朋友、合作伙伴」三类，分别看边界','涉及钱和分工时按武曲的方式讲清楚、留记录','用天相的分寸主动协调，别让小误会攒成隔阂','在讲原则之外主动表达关心，补上两星不擅的情分','结合大限流年，判断同辈关系被引动的阶段再深入合作'],
 enStep:['First confirm Wu Qu and Tian Xiang share the Siblings Palace and check their brightness','Sort the people around you into siblings, friends and partners, with the boundary for each','When money or tasks are involved, be clear and keep records in Wu Qu’s way','Use Tian Xiang’s tact to mediate early so small misunderstandings do not harden','Beyond principles, actively show care to supply the warmth both stars lack','With the decade and year, deepen cooperation when the peer relationship is activated'],
 cnMis:['把武相在兄弟宫只当成「手足靠谱」，忽略平辈合作也要看边界','只讲规则不讲情分，关系越处越冷','涉及资金往来不留凭证，事后各有各的理解'],
 enMis:['Taking Wu Qu-Tian Xiang in the Siblings Palace only as reliable siblings while ignoring boundaries in peer cooperation','Stressing rules without warmth until the bond cools','Leaving money matters undocumented so each side remembers it differently'],
 cnClose:'武相在兄弟宫，给的是一层务实、正派、能办事的平辈关系。把规则讲清、把情分补上，这层关系会很稳、也很能托事。',
 enClose:'Wu Qu and Tian Xiang in the Siblings Palace give a practical, upright and capable set of peers. Keeping rules clear and warmth present makes the bond steady and dependable.'},

{cat:'liuqin',slug:'ziwei-tiantong-tianliang-zai-fumugong',focus:'天同天梁在父母宫',focusEn:'Tian Tong and Tian Liang together in the Parents Palace',
 cnT:'天同天梁同在父母宫：长辈温和有荫庇，怎么承接这份照顾',
 enT:'Tian Tong and Tian Liang in the Parents Palace: Warm, Sheltering Elders and How to Receive the Care',
 cnD:'父母宫看长辈缘、家教与庇荫，天同温和孩子气、天梁稳重能荫庇，两星同落在这里，长辈多是心软、照顾型，家庭氛围偏暖、愿意兜底；但照顾太足时，容易在独立和依赖之间拉扯。',
 enD:'The Parents Palace covers elders, upbringing and shelter. Tian Tong is warm and childlike while Tian Liang is steady and protective, so elders tend to be soft-hearted and nurturing, with a warm home willing to catch you; yet too much shelter can pull between independence and dependence.',
 cnL:'天同天梁在父母宫的人，常被长辈疼着、遇事有人兜底，家里讲情分也讲道理，只是这份照顾越足，越要学自己站稳。',
 enL:'People with Tian Tong and Tian Liang in the Parents Palace are often cherished by elders who catch them when things go wrong, in a home that values both feeling and reason; the fuller the care, the more one must learn to stand alone.',
 cnA:'这个问题在问：同梁在父母宫，和长辈是什么缘分。要先理解父母宫看的是「长辈缘与庇荫」，再看两星的照顾怎么影响独立。',
 enA:'The question is the bond with elders when Tian Tong and Tian Liang are in the Parents Palace. Understand it covers the elder bond and shelter, then see how that care affects independence.',
 cnLog:['天同在父母宫，主长辈温和、心软、有童心，家庭氛围轻松，也容易被疼、被让着。','天梁在父母宫，主长辈稳重、能荫庇、讲原则，是那种遇事能给忠告也能兜底的人。','两星同宫是「温情＋荫庇」：长辈缘通常不错，成长里有安全感，也容易获得资源与提醒。','若见煞忌，照顾可能变成操心或管束，独立的节奏会被拖晚，需要主动建立边界。'],
 enLog:['Tian Tong in the Parents Palace gives warm, soft-hearted, youthful elders and a relaxed home where one is indulged.','Tian Liang there gives steady, protective, principled elders who offer both advice and a safety net.','Together they bring warmth and shelter: the elder bond is usually good, the upbringing secure, and resources and reminders come readily.','With malefics and Ji, care can turn into worry or control and delay independence, calling for active boundaries.'],
 cnStep:['先确认父母宫是天同天梁同宫，并看两星亮度','把长辈给的照顾分「情感支持」和「实际兜底」两类看清','珍惜温情的同时，主动练习自己做决定、承担后果','与长辈沟通时既听忠告，也说明自己的节奏和边界','大的人生选择（工作、婚姻、城市）自己拿主意，避免一味依赖','结合大限流年，看独立与离家的阶段，逐步把庇护转为后盾'],
 enStep:['First confirm Tian Tong and Tian Liang share the Parents Palace and check their brightness','Separate the care you receive into emotional support and practical backup','While treasuring the warmth, actively practice making and owning decisions','Listen to advice while explaining your own pace and boundaries','Take the lead on major choices—work, marriage, city—rather than defaulting to dependence','With the decade and year, move from shelter toward having elders as a backup as independence grows'],
 cnMis:['把同梁在父母宫只当成「命好、有人管」，忽略独立功课','长期接受兜底，遇事不敢自己拿主意','把长辈的操心当成束缚去对抗，而不是用边界去转化'],
 enMis:['Taking Tian Tong-Tian Liang in the Parents Palace only as good fortune with someone in charge while ignoring independence','Relying on the safety net for so long that one fears deciding alone','Treating elder worry as control and fighting it rather than converting it through boundaries'],
 cnClose:'同梁在父母宫，给的是一份温暖、有荫庇的长辈缘。把照顾当后盾而不是拐杖，你既承接了这份情，也能越活越独立。',
 enClose:'Tian Tong and Tian Liang in the Parents Palace give a warm, sheltering bond with elders. Treating the care as backup rather than a crutch lets you receive it while growing steadily independent.'},

{cat:'faq',slug:'ziwei-yu-qizhengsiyu-qubie',focus:'紫微斗数与七政四余的区别',focusEn:'the difference between Zi Wei Dou Shu and Qi Zheng Si Yu',
 cnT:'紫微斗数和七政四余有什么不同：两套中式命理看的不是一回事',
 enT:'Zi Wei Dou Shu vs Qi Zheng Si Yu: Two Chinese Systems Reading Different Things',
 cnD:'七政四余（果老星宗）以日月五星等真实天体按黄道二十八宿推命，偏天人相应与一生格局；紫微斗数以一套星曜落入十二人事宫、配四化推命，偏具体人事与时机。两者都用出生时间，但坐标、星曜和侧重不同。',
 enD:'Qi Zheng Si Yu, also tied to the Guo Lao star tradition, reads the sun, moon and visible planets against the zodiac and lunar lodges, leaning toward cosmic correspondence and the shape of a whole life; Zi Wei Dou Shu places symbolic stars in twelve human-affairs palaces with the four transformations, leaning toward concrete affairs and timing. Both use birth time but differ in coordinates, stars and focus.',
 cnL:'有人问紫微和七政四余是不是一回事、能不能一起看。它们都是中国传统命理、都要排星盘，但一个对着真实天象、一个对着人事宫位，其实是两套独立系统。',
 enL:'People ask whether Zi Wei Dou Shu and Qi Zheng Si Yu are the same and can be read together. Both are traditional Chinese systems that cast star charts, but one faces the visible heavens and the other human-affairs palaces—two independent systems.',
 cnA:'这个问题在问：两套体系到底差在哪、怎么选。关键看三处——星曜是真实天体还是虚拟星曜、坐标怎么分、重点落在一生气象还是具体人事。',
 enA:'The question is where the two differ and how to choose. Look at three points: whether the stars are visible bodies or symbolic stars, how the coordinates divide, and whether the focus is a life’s overall climate or concrete affairs.',
 cnLog:['星曜不同：七政四余用日月、金木水火土五星及四余气等真实天体；紫微用紫微、天府等一套星曜，星名多为象征而非对应某颗行星。','坐标不同：七政四余按黄道十二宫与二十八宿度数定位；紫微按命、财、夫、官等十二人事宫定位，宫名即所问之事。','侧重不同：七政四余偏一生的整体气象、禀赋与天人相应；紫微偏财运、事业、婚姻、六亲等具体领域的形态与应期。','两者可以互参但不能硬套：把七政四余对一生基调的判断，与紫微对具体人事的落宫对照看，结论不必强求一致。'],
 enLog:['The stars differ: Qi Zheng Si Yu uses the sun, moon, the five visible planets and added symbolic nodes, while Zi Wei uses stars such as Zi Wei and Tian Fu whose names are symbolic rather than tied to a planet.','The coordinates differ: Qi Zheng Si Yu locates by the zodiac and the twenty-eight lunar lodges in degrees, while Zi Wei locates by twelve human-affairs palaces such as Life, Wealth, Spouse and Career, where the name is the matter.','The focus differs: Qi Zheng Si Yu leans to the overall climate and endowment of a life and cosmic correspondence, while Zi Wei leans to the shape and timing of wealth, career, marriage and family.','They can inform each other but not be forced: compare the life-tone from Qi Zheng Si Yu with the concrete palaces of Zi Wei without demanding the same answer.'],
 cnStep:['先确认自己更想了解「一生整体气象」还是「具体人事与时机」','一生格局与天人相应的问题，主看七政四余的星曜度数','财运、事业、婚姻、六亲等具体领域，主看紫微十二宫','对照时只比大方向（如禀赋刚柔、动静），不硬套星名','两套结论冲突时回到现实，观察哪一种更贴合自己','把两套当成互补的自我认识工具，而非争谁更准'],
 enStep:['First decide whether you want the overall climate of a life or concrete affairs and timing','Questions of life pattern and cosmic correspondence lead with Qi Zheng Si Yu’s stars and degrees','Concrete domains—wealth, career, marriage, family—lead with the Zi Wei twelve palaces','When comparing, only contrast broad directions such as firmness and softness, movement and stillness, without forcing star names','When the two clash, return to reality and see which fits you better','Treat them as complementary tools for self-knowledge rather than competing for accuracy'],
 cnMis:['把两套盘按星名直接对号，忽略坐标与星曜根本不同','以为都用出生时间结论就该一致','只信一套就否定另一套，看不到各自擅长的问题'],
 enMis:['Matching the two charts by star name while ignoring that the coordinates and stars differ at the root','Expecting identical answers because both use birth time','Trusting one and dismissing the other without seeing the questions each handles well'],
 cnClose:'紫微与七政四余不是一回事：一个重人事落宫与时机、一个重真实天象与一生气象。按问题选工具、互参不硬套，自我认识会更完整。',
 enClose:'Zi Wei Dou Shu and Qi Zheng Si Yu are not the same: one stresses affairs in palaces and timing, the other the visible heavens and a life’s climate. Choose by question and cross-reference without forcing, and self-knowledge becomes more complete.'},

{cat:'yingyong',slug:'ziwei-caifu-san-gong-xianjinliu-zichan-shouru',focus:'财富三宫：财帛现金流、田宅资产、官禄收入来源',focusEn:'reading wealth across three palaces: cash flow, assets and income source',
 cnT:'看财运为什么要三个宫一起看：现金流、资产和收入来源别混',
 enT:'Why Wealth Needs Three Palaces: Cash Flow, Assets and Income Source Are Not the Same',
 cnD:'财帛宫看现金流与花钱习惯，田宅宫看固定资产与资产沉淀，官禄宫看职业带来的收入来源，三者合起来才是完整的财富结构。只看一个宫，常会误判「赚得多却留不住」或「职位高但现金紧」。',
 enD:'The Wealth Palace reads cash flow and spending habits, the Property Palace fixed assets and accumulated wealth, and the Career Palace the income your work provides; together they form the full financial structure. One palace alone misreads cases such as earning well yet saving little or holding a high title with tight cash.',
 cnL:'很多人看财运只盯着财帛宫，结果有人明明收入不错却存不下、有人资产不少却手头紧。财富其实是三件事：钱怎么流、东西怎么存、收入从哪来。',
 enL:'Many read wealth only through the Wealth Palace, then wonder why a good income never accumulates or why sizable assets coexist with tight cash. Wealth is really three things: how money flows, how it is stored, and where income comes from.',
 cnA:'这个问题在问：财运到底要看哪几个宫、怎么合看。要先把现金流、资产存量、收入来源三件事分开，再看它们在自己盘上怎么配合。',
 enA:'The question is which palaces wealth requires and how to read them together. First separate cash flow, stored assets and income source, then see how they combine on your chart.',
 cnLog:['财帛宫是「现金流」：收入怎么进、钱怎么花、周转灵不灵、风险偏好如何，反映的是当下与钱的关系。','田宅宫是「资产存量」：房产、家当、能沉淀下来的东西，反映的是长期承载与守不守得住。','官禄宫是「收入来源」：靠什么职业和角色赚钱、收入稳不稳，反映的是现金流的上游。','三宫要合看：财帛强而田宅弱，容易过手财；官禄强而财帛弱，常见职位高但现金有限；田宅强而现金流紧，则是资产厚但当下要省着用。'],
 enLog:['The Wealth Palace is cash flow: how income arrives, money is spent, turnover works and what risk you prefer, showing your current relationship with money.','The Property Palace is stored assets: real estate and possessions that settle and accumulate, showing long-term capacity and whether wealth is kept.','The Career Palace is the income source: what work and role earn the money and how stable it is, showing the upstream of cash flow.','Read them together: strong Wealth with weak Property means money passes through; strong Career with weak Wealth often means a high title but limited cash; strong Property with tight cash means solid assets but careful present spending.'],
 cnStep:['先分别找到财帛、田宅、官禄三宫，看各自的主星与亮度','看财帛宫，判断现金流松紧与花钱习惯','看田宅宫，判断资产沉淀与承载能力','看官禄宫，判断收入来源是否稳定、有没有增长','把三宫叠起来，定位自己的财富短板在流、存还是源','结合大限这十年财务周期，决定先补哪一块，而不是只盯收入数字'],
 enStep:['First locate the Wealth, Property and Career palaces and read their major stars and brightness','Read the Wealth Palace to judge cash flow and spending habits','Read the Property Palace to judge accumulated assets and capacity','Read the Career Palace to judge whether the income source is stable and growing','Layer the three to locate whether your weak point is flow, storage or source','With the decade’s ten-year financial cycle, decide which to strengthen first rather than fixating on income'],
 cnMis:['把财运只等于财帛宫，忽略资产和收入来源','看到收入高就以为有钱，不看过手和沉淀','把大耗、空劫的信号只当一时，不结合三宫看长期结构'],
 enMis:['Reducing wealth to the Wealth Palace while ignoring assets and income source','Assuming high income means rich without checking flow and storage','Treating signals such as Great Expenditure or void stars as temporary without reading the long-term structure'],
 cnClose:'财富是现金流、资产和收入来源三件事的合力。把三宫一起看，你才知道该补的是周转、沉淀还是来源——这比盯着一个数字更能落到行动。这里不构成投资建议，具体产品以持牌机构和正规说明为准。',
 enClose:'Wealth is the combined result of cash flow, assets and income source. Reading the three palaces together shows whether to fix turnover, storage or source, which is more actionable than one number. This is not investment advice; for any product, rely on licensed institutions and official disclosures.'}
];
