// 2026-10-07 调研驱动 第1组：看盘方法 8（布局/四正/夹宫/庙旺/空宫借星/飞宫三段论/本宫飞出他宫飞入/看盘顺序）
module.exports=[
{cat:'kanpan',slug:'ziwei-pan-buju-ruhe-kan',focus:'盘的整体布局',focusEn:'the overall layout of a chart',
 cnT:'盘的整体布局怎么看：先看骨架再填血肉',enT:'How to Read the Overall Layout of a Zi Wei Chart',
 cnD:'一张盘的整体布局，先看命宫三方四正的骨架结构，再填星曜四化的血肉细节，最后叠大限流年；布局读的是力量往哪个方向走，不是单宫吉凶。',
 enD:'For the overall layout of a chart, first read the skeleton of the Life Palace triple-direction, then fill in the details of stars and transformations, and finally layer the decade and year. The layout reads where the power flows, not the good or bad of one palace.',
 cnL:'布局像看一座房子的户型图，先看承重墙和朝向，再看家具摆在哪；一上来就盯某颗星，等于只看一把椅子。',
 enL:'The layout is like reading a floor plan: first look at load-bearing walls and orientation, then where the furniture goes. Fixating on one star at the start is like looking only at one chair.',
 cnA:'有人一拿盘就逐宫问吉凶，结果只见树木不见森林；真正的读法是先看整张盘的力量结构，再收窄到具体宫位。',
 enA:'Some go palace by palace asking good or bad and miss the forest for the trees; the real way is to first read the power structure of the whole chart, then narrow to specific palaces.',
 cnLog:['布局第一步看命宫及三方四正，定整张盘的骨架与主色调。','再看星曜分布：主星在哪几宫集中，力量就往哪个领域走。','四化是能量开关，看禄权科忌落宫，定资源、掌控、名声、卡点的分布。','最后叠大限流年，看先天布局在当前阶段怎么被引动。'],
 enLog:['The first step of layout reads the Life Palace and triple-direction to set the skeleton and dominant tone.','Then read star distribution: where the major stars gather, power flows toward that area.','Transformations are energy switches; read where Lu Quan Ke Ji land to set the distribution of resources, control, reputation and sticking points.','Finally layer the decade and year to see how the innate layout is activated now.'],
 cnStep:['先定位命宫，看主星定整张盘的主色调','把命宫三方四正摊开，看骨架结构','数吉星煞星在整张盘的分布，定力量强弱','看生年四化落宫，定能量开关在哪','找出主星和四化集中的领域，定人生主轴','叠大限流年，看当前阶段引动布局的哪一部分'],
 enStep:['First locate the Life Palace and read its star for the dominant tone','Open the Life Palace triple-direction to see the skeleton','Count auspicious and malefic stars across the chart to gauge power','Read where natal transformations land to set the energy switches','Find the area where stars and transformations concentrate, the main life axis','Layer the decade and year to see which part of the layout is activated now'],
 cnMis:['一上来逐宫问吉凶，不见整体结构','只看命宫不看三方，读不出力量走向','忽略四化和大限，把静态布局当成全部'],
 enMis:['Going palace by palace at the start without seeing the structure','Reading only the Life Palace without the trines, missing power flow','Ignoring transformations and decades, treating static layout as the whole'],
 cnClose:'盘的整体布局看的是「力量往哪走」。先读骨架、再填血肉、最后叠时间，你才不会在单宫吉凶里打转。',
 enClose:'The overall layout asks where the power flows. Read the skeleton first, fill in the details, then layer time, and you will not spin on the good or bad of one palace.'},

{cat:'kanpan',slug:'ziwei-sicong-zhengzhao-ruhe-kan',focus:'四正宫',focusEn:'the four-direction palaces',
 cnT:'四正宫怎么照：本宫与对宫是一条直线上的呼应',enT:'How the Four-Direction Palaces Work in a Zi Wei Chart',
 cnD:'四正指本宫、对宫及两个三合宫构成的完整视野；本宫写核心，对宫是一条直线上的补充，两个三合宫从侧面供给，四宫合看才读得全。',
 enD:'The four-direction means the home palace, the opposite palace and two trine palaces forming a complete view. The home palace is the core, the opposite supplements along a straight line, and the two trines supply from the side; all four together read fully.',
 cnL:'四正宫像一张桌子的四条腿，本宫是桌面，对宫和三合是腿，缺一条都不稳。',
 enL:'The four-direction palaces are like four legs of a table; the home palace is the tabletop, the opposite and trines are legs, and missing any one makes it unsteady.',
 cnA:'有人只看本宫不看对宫，结果读到的事情总缺另一半；对宫往往写的是这件事的外部条件和隐性补充。',
 enA:'Some read only the home palace without the opposite and things always lack the other half; the opposite often describes external conditions and hidden supplements.',
 cnLog:['四正=本宫+对宫+两个三合宫，是一个宫位的完整视野。','本宫写核心，对宫在一条直线上正面对照，三合从侧面供给。','例如命宫对迁移：内在自我与外部际遇互为表里。','四正宫要一起读，单看本宫只读到四分之一。'],
 enLog:['Four-direction = home palace + opposite + two trines, the complete view of one palace.','The home palace is the core, the opposite faces it along a straight line, the trines supply from the side.','For example, Life Palace opposite Travel: inner self and outside encounters are two sides.','Read all four together; the home palace alone is only a quarter.'],
 cnStep:['先定位本宫，确认要看的核心领域','找对宫，看一条直线上的正面补充','找两个三合宫，看侧面供给','分别数四宫的主星、吉星、煞星','看四化在四宫的分布，定能量怎么流动','四宫合读，判断这个领域的完整状态'],
 enStep:['First locate the home palace, the core area to read','Find the opposite palace for the direct supplement along the line','Find the two trine palaces for side supply','Count major, auspicious and malefic stars in all four','Read how transformations distribute across the four to set energy flow','Read all four together to judge the complete state of the area'],
 cnMis:['只看本宫不看对宫三合，读不到完整视野','把对宫当对立，其实它是补充','四宫分开读，不连起来看'],
 enMis:['Reading only the home palace without opposite and trines, missing the full view','Treating the opposite as opposition when it is a supplement','Reading the four separately without connecting them'],
 cnClose:'四正宫看的是「一个领域的完整视野」。把本宫、对宫和两个三合连起来，你才读得到这件事的全貌。',
 enClose:'The four-direction asks for the complete view of one area. Connect the home palace, opposite and two trines, and you read the whole matter.'},

{cat:'kanpan',slug:'ziwei-jiaogong-ruhe-kan',focus:'夹宫',focusEn:'the flanking palaces',
 cnT:'夹宫怎么看：左右两宫夹住本宫，夹吉助吉夹煞助煞',enT:'How to Read the Flanking Palaces in a Zi Wei Chart',
 cnD:'夹宫指本宫左右相邻两宫，如命宫的父母宫与兄弟宫；夹吉则助力贴身，夹煞则压力贴身，夹宫看的是身边最近的外部力量。',
 enD:'The flanking palaces are the two adjacent palaces, such as Parents and Siblings around the Life Palace. Auspicious flanks bring close support, malefic flanks bring close pressure; flanks read the nearest external forces.',
 cnL:'夹宫像两个人一左一右站在你旁边，是帮你还是绊你，看这两宫放的是什么。',
 enL:'Flanking palaces are like two people standing on either side; whether they help or trip you depends on what those palaces hold.',
 cnA:'有人只看三方不看夹宫，忽略了贴身的力量；夹宫虽不在三方，却是离本宫最近的外部影响。',
 enA:'Some read the trines but ignore the flanks, missing close forces; though not in the trine, flanks are the nearest external influence.',
 cnLog:['夹宫=本宫左右相邻两宫，命宫的夹宫是父母与兄弟。','夹吉（禄权科、左右魁钺）主贴身助力。','夹煞（羊陀火铃、空劫）主贴身压力。','夹宫要与三方四正合看，贴身力量加外部供给才完整。'],
 enLog:['Flanks = the two adjacent palaces; around the Life Palace they are Parents and Siblings.','Auspicious flanks (Lu Quan Ke, Zuo You Kui Yue) bring close support.','Malefic flanks (Yang Tuo Huo Ling, emptiness) bring close pressure.','Read flanks with the triple-direction; close force plus external supply is complete.'],
 cnStep:['先定位本宫，找左右相邻两宫','看两夹宫放的是吉星还是煞星','夹吉：判断贴身助力来自什么领域','夹煞：判断贴身压力来自什么领域','看夹宫四化，定贴身力量的能量性质','与三方四正合读，定这个领域的整体处境'],
 enStep:['First locate the home palace and find the two adjacent palaces','Read whether the flanks hold auspicious or malefic stars','Auspicious flank: judge which area the close support comes from','Malefic flank: judge which area the close pressure comes from','Read flank transformations to set the energy nature of the close force','Read with the triple-direction to set the overall situation of the area'],
 cnMis:['只看三方不看夹宫，忽略贴身力量','把夹宫当三方，几何位置分不清','见夹吉就躺赢，不看夹煞'],
 enMis:['Reading only the trines without flanks, ignoring close force','Confusing flanks with trines, unable to distinguish geometry','Seeing auspicious flanks and relaxing, ignoring malefic flanks'],
 cnClose:'夹宫看的是「身边最近的外部力量」。分清夹吉夹煞、再合三方，你才知道贴身的是助力还是压力。',
 enClose:'Flanking palaces read the nearest external forces. Distinguish auspicious from malefic flanks and combine with the trines, and you know whether what is close is support or pressure.'},

{cat:'kanpan',slug:'ziwei-xingmiao-wangxian-ruhe-kan',focus:'星曜庙旺落陷',focusEn:'star brightness: temple, prosperous, fallen',
 cnT:'星曜庙旺落陷怎么判断：亮度决定这股劲有没有力气',enT:'How to Judge Star Brightness: Temple, Prosperous and Fallen',
 cnD:'庙旺落陷是星曜在不同地支的亮度状态，决定这股星性能不能舒展；庙旺是星得地、力量足，落陷是星失地、难发挥，但亮度不是吉凶本身。',
 enD:'Brightness is the state of a star across branches, deciding whether the star nature can express itself. Temple means well-placed and strong, fallen means displaced and hard to express, but brightness is not good or bad in itself.',
 cnL:'庙旺像一个人在自己擅长的舞台，落陷像被放到不熟悉的场地；同一个人，舞台不同，发挥差很多。',
 enL:'Temple is like a person on a stage they master, fallen is like being put in an unfamiliar venue; the same person performs very differently by stage.',
 cnA:'有人见落陷就判坏、见庙旺就判好，其实还要看星性、四化和组合；落陷的星逢吉化也能成事，庙旺的星逢煞破也会打折。',
 enA:'Some call fallen bad and temple good, but still read star nature, transformations and combinations; a fallen star with auspicious transformations can deliver, a temple star with malefics is discounted.',
 cnLog:['庙旺落陷分庙、旺、得地、平、落陷等亮度等级。','庙旺主星得地、力量足、表达方式舒展。','落陷主星失地、力量弱、表达方式扭曲或压抑。','亮度要与星性、四化、三方四正合看，不能单独判吉凶。'],
 enLog:['Brightness has levels: temple, prosperous, well-placed, neutral and fallen.','Temple means the star is well-placed, strong and expressive.','Fallen means displaced, weak and distorted or repressed in expression.','Read brightness with star nature, transformations and triple-direction; do not judge good or bad alone.'],
 cnStep:['先认所看星曜在本宫的亮度等级','庙旺：判断这股星性怎么舒展','落陷：判断哪方面被压抑或扭曲','看四化引动，落陷逢禄科可补、庙旺逢煞忌可破','看三方四正有没有支撑或冲克','综合亮度、星性、四化，定这个领域的发挥程度'],
 enStep:['First learn the brightness level of the star in that palace','Temple: judge how the star nature expresses','Fallen: judge what is repressed or distorted','Read transformation activation; fallen with Lu Ke can be remedied, temple with malefics can break','Check the triple-direction for support or clash','Combine brightness, star nature and transformations to set how the area performs'],
 cnMis:['见落陷就判坏、自我恐吓','见庙旺就判好、坐等兑现','只看亮度不看四化组合'],
 enMis:['Calling fallen bad and frightening yourself','Calling temple good and waiting for it','Reading only brightness without transformations and combinations'],
 cnClose:'庙旺落陷看的是「星有没有力气舒展」。把亮度放回星性、四化和三方里读，你才知道这股劲能发挥几分。',
 enClose:'Brightness asks whether the star has strength to express. Put brightness back into star nature, transformations and trines, and you know how much of the energy can perform.'},

{cat:'kanpan',slug:'ziwei-konggong-jiexie-ruhe-kan',focus:'空宫借星',focusEn:'empty palaces borrowing a star',
 cnT:'空宫借星详解：本宫无主星，借对宫的星来安',enT:'Empty Palaces Borrowing a Star: A Detailed Guide',
 cnD:'本宫无主星叫空宫，不是「空了没戏」，而是借对宫主星来安，再合三方四正一起读；借星后这宫的表现方式，由对宫星性和本宫环境共同决定。',
 enD:'A palace with no major star is empty, not empty and hopeless; borrow the opposite star and read it with the triple-direction. After borrowing, how this palace expresses is set by both the opposite star nature and the home palace environment.',
 cnL:'空宫像一间没有固定主人的房间，对宫的星像请来的管家；管家怎么做事，还要看房间本身的条件。',
 enL:'An empty palace is like a room with no fixed owner; the opposite star is like a borrowed steward; how the steward works depends on the room itself.',
 cnA:'有人见空宫就慌，也有人见空宫就当无所谓；真正要做的是借对宫星、再看三方，空宫一样读得出内容。',
 enA:'Some panic at an empty palace, others dismiss it; what to do is borrow the opposite star and read the trines, and an empty palace can still be read.',
 cnLog:['空宫=本宫无十四主星坐守，须借对宫主星安。','借星后以对宫星性定这宫的基本表现。','再合本宫三方四正，看环境怎么调和这颗借来的星。','空宫不是缺陷，只是表达方式受外部影响更大。'],
 enLog:['Empty = no major star in the palace; borrow the opposite star.','After borrowing, the opposite star nature sets the basic expression of this palace.','Then combine the home palace triple-direction to see how the environment tempers the borrowed star.','An empty palace is not a flaw, just more influenced externally in expression.'],
 cnStep:['先确认本宫无主星，定位为空宫','找对宫主星，借星安宫','以借来的星性定这宫的基本表现','看本宫三方四正，数吉星煞星','看四化有没有落本宫或引动借星','综合借星与环境，定这宫的实际状态'],
 enStep:['First confirm the palace has no major star, locating it as empty','Find the opposite star and borrow it','Use the borrowed star nature to set the basic expression','Read the home palace triple-direction, counting auspicious and malefic stars','See whether transformations land in this palace or activate the borrowed star','Combine the borrowed star and environment to set the actual state'],
 cnMis:['见空宫就当「没戏了」、自我否定','不借对宫星，把空宫当真空','借星后不看三方环境'],
 enMis:['Taking an empty palace as hopeless and denying yourself','Not borrowing the opposite star and treating it as truly empty','After borrowing, ignoring the trine environment'],
 cnClose:'空宫借星看的是「没有固定主人的宫位怎么读」。借对宫星、合三方，空宫一样有内容、有方向。',
 enClose:'Empty palaces borrowing a star asks how to read a palace with no fixed owner. Borrow the opposite star and combine the trines, and an empty palace still has content and direction.'},

{cat:'kanpan',slug:'ziwei-feixing-san-duan-lun',focus:'飞宫三段论',focusEn:'the three-step flying-palace method',
 cnT:'飞宫三段论：立太极、找四化、看落点因果',enT:'The Three-Step Flying-Palace Method for Beginners',
 cnD:'飞宫三段论把宫干飞化拆成三步：先立太极（站在哪个宫说话）、再找该宫干四化、最后看落点宫位的因果；新手按这三步走，飞星就不会乱。',
 enD:'The three-step method breaks palace-stem flights into three: first set Tai Ji (which palace you speak from), then find that palace stem transformations, finally read the cause and effect of the landing palaces. Following these three steps keeps flying stars orderly.',
 cnL:'飞星像从一个宫往别的宫寄信，先弄清自己站在哪、再看信寄给谁、最后看对方收到后发生什么。',
 enL:'Flying stars are like sending letters from one palace to others; first know where you stand, then to whom the letter goes, finally what happens when received.',
 cnA:'有人学飞星不立太极，方向全乱；也有人只看四化不看落点，读不到因果；三段论就是治这两个毛病。',
 enA:'Some learn flying stars without setting Tai Ji and lose direction; others see transformations without the landing and miss cause and effect; the three-step method treats both problems.',
 cnLog:['第一步立太极：确定起点宫位，弄清自己站在哪说话。','第二步找宫干四化：看该宫天干使哪颗星化禄权科忌。','第三步看落点：四化分别飞向哪个宫，定因果方向。','禄为因、忌为果，落点宫位的星曜和环境定具体表现。'],
 enLog:['Step one set Tai Ji: determine the starting palace, knowing where you speak from.','Step two find stem transformations: see which star that palace stem transforms to Lu Quan Ke Ji.','Step three read landings: which palace each transformation flies to, setting cause-effect direction.','Lu is cause and Ji is effect; the landing palace stars and environment set the concrete form.'],
 cnStep:['先定要追的事，选起点宫位立太极','查起点宫的天干，对照四化表','找该天干使哪颗星化禄、化权、化科、化忌','看四化星所在宫位，定落点','先读禄的落点为因，再读忌的落点为果','合落点宫的星曜三方，定这件事的具体走向'],
 enStep:['First settle the matter to trace, choose the starting palace and set Tai Ji','Look up the starting palace stem against the transformation table','Find which star that stem transforms to Lu, Quan, Ke, Ji','Read which palace the transformed stars sit in, the landings','First read the Lu landing as cause, then the Ji landing as effect','Combine the landing palace stars and trines to set the concrete direction'],
 cnMis:['不立太极就飞，方向全乱','只找四化不看落点，读不到因果','把飞星和生年四化混成一层'],
 enMis:['Flying without setting Tai Ji and losing direction','Finding transformations without landings, missing cause and effect','Merging flying stars and natal transformations into one layer'],
 cnClose:'飞宫三段论看的是「飞星怎么一步步读」。立太极、找四化、看落点，再乱的盘也能理出因果线。',
 enClose:'The three-step method asks how to read flying stars step by step. Set Tai Ji, find transformations and read landings, and even a complex chart yields a cause-effect line.'},

{cat:'kanpan',slug:'ziwei-ben-gong-feichu-ta-gong-feiru',focus:'本宫飞出他宫飞入',focusEn:'flying out of the home palace and flying in from others',
 cnT:'本宫飞出、他宫飞入：主动对外与外部对我的双向读法',enT:'Flying Out vs Flying In: A Two-Way Reading',
 cnD:'本宫飞出（化出）是我主动对外做的事、为因；他宫飞入（化入）是外部宫位对我的影响、为果；双向都看，才知道一件事里我主动几分、外部推几分。',
 enD:'Flying out of the home palace is what you actively do outward, the cause; flying in from other palaces is external influence on you, the effect. Read both directions to know how much is your initiative and how much is external push.',
 cnL:'本宫飞出像我主动给别人打电话，他宫飞入像别人打给我；一段关系里，谁主动、谁回应，看双向飞化。',
 enL:'Flying out is like you actively calling others, flying in is like others calling you; in a relationship, who initiates and who responds is read by two-way flights.',
 cnA:'有人只看本宫飞出，全当自己主动；也有人只看他宫飞入，全当外部造成；真正的读法是双向合看，分清因果。',
 enA:'Some only see flying out and take all as their initiative; others only see flying in and take all as external; the real way reads both directions and separates cause and effect.',
 cnLog:['本宫飞出=化出，本宫为因、落点为果，主主动对外。','飞出禄：主动结缘求财；飞出权：主动争夺主导；飞出忌：主动内耗。','他宫飞入=化入，他宫为因、本宫为果，主外部对我。','飞入禄：外部给我资源；飞入权：外部给我压力；飞入忌：外部给我卡点。'],
 enLog:['Flying out = the home palace is cause and landing is effect, active outward.','Flying out Lu: actively connect and seek gain; Quan: actively compete and lead; Ji: actively turn inward.','Flying in = other palaces are cause and home palace is effect, external toward you.','Flying in Lu: external resources to you; Quan: external pressure to you; Ji: external sticking points to you.'],
 cnStep:['先立太极，定本宫为哪个宫','找本宫宫干四化，看飞出到哪些宫','读飞出：判断我主动对外做了什么','找哪些宫的宫干飞入本宫','读飞入：判断外部对我做了什么','双向合看，分清一件事的因果和主被动'],
 enStep:['First set Tai Ji, determining the home palace','Find the home palace stem transformations, see where they fly out to','Read flying out: judge what you actively do outward','Find which palace stems fly into the home palace','Read flying in: judge what external forces do to you','Read both directions together, separating cause-effect and active-passive'],
 cnMis:['只看飞出不看飞入，全当自己主动','只看飞入不看飞出，全当外部造成','不立太极，双向方向全乱'],
 enMis:['Seeing only flying out and taking all as your initiative','Seeing only flying in and taking all as external','Not setting Tai Ji, losing direction in both ways'],
 cnClose:'本宫飞出他宫飞入看的是「一件事里谁主动、谁回应」。双向都读、分清因果，你才知道自己能掌控几分。',
 enClose:'Flying out and flying in ask who initiates and who responds in a matter. Read both directions and separate cause and effect, and you know how much you can control.'},

{cat:'kanpan',slug:'ziwei-kanpan-shunxu-ruhe-anpai',focus:'看盘顺序',focusEn:'the order of reading a chart',
 cnT:'看盘顺序怎么安排：固定六步，不乱不跳',enT:'How to Arrange the Order of Reading a Chart',
 cnD:'看盘有固定顺序：命宫定底色→三方四正看结构→四化看能量→身宫看后天→大限看阶段→流年看当年；按顺序走，才不会东一榔头西一棒子。',
 enD:'Reading a chart has a fixed order: Life Palace sets the tone, triple-direction shows structure, transformations show energy, Body Palace shows later direction, decade shows the stage, year shows the current year. Following the order keeps you from jumping around.',
 cnL:'看盘像解一道题，有已知条件、有推导步骤；顺序乱了，结论就容易互相打架。',
 enL:'Reading a chart is like solving a problem with given conditions and steps; with the order scrambled, conclusions contradict each other.',
 cnA:'有人看盘想到哪看到哪，结果信息越堆越乱；固定顺序的意义，是让每一步建立在前一步的结论上。',
 enA:'Some read wherever they think and information piles into chaos; the point of a fixed order is letting each step build on the previous conclusion.',
 cnLog:['第一步命宫：定先天性格与主色调。','第二步三方四正：看结构与外部供给。','第三步四化：看能量开关与资源卡点分布。','第四步身宫、第五步大限、第六步流年：从后天方向到阶段到当年。'],
 enLog:['Step one Life Palace: set innate temperament and dominant tone.','Step two triple-direction: see structure and external supply.','Step three transformations: see energy switches and resource-sticking-point distribution.','Step four Body Palace, five decade, six year: from later direction to stage to current year.'],
 cnStep:['先看命宫主星，定底色','再看命宫三方四正，定结构','看生年四化落宫，定能量','看身宫落宫，定后天重心','看当前大限，定阶段主题','看流年，定当年引动，最后综合下结论'],
 enStep:['First read the Life Palace star to set the tone','Then read the triple-direction to set structure','Read natal transformation landings to set energy','Read the Body Palace to set later focus','Read the current decade to set the stage theme','Read the year for current activation, finally synthesize'],
 cnMis:['想到哪看到哪，顺序全乱','跳过基础直接看流年，结论悬空','每一步不建立在前一步上，信息打架'],
 enMis:['Reading wherever you think, order scrambled','Skipping basics to the year, conclusions unsupported','Each step not building on the previous, information contradicting'],
 cnClose:'看盘顺序看的是「怎么一步步推出结论」。固定六步、不跳不乱，你读的盘才前后一致、站得住脚。',
 enClose:'Chart-reading order asks how to derive conclusions step by step. Fix the six steps, do not jump or scramble, and your reading is consistent and sound.'}
];
