// 2026-10-04 调研驱动 第2组：2026丙午 天同化禄(4) + 天机化权(4) 落宫深读 8篇
module.exports=[
{cat:'sihua',slug:'ziwei-2026-tiantonghualu-minggong',focus:'天同化禄在命宫',focusEn:'Tian Tong Hua Lu in the Life Palace',
 cnT:'2026天同化禄在命宫：福气回到自己身上，也别只图舒服',enT:'2026 Tian Tong Hua Lu in the Life Palace: Goodwill Flows Back to You, Just Do Not Settle for Comfort Alone',
 cnD:'天同化禄落命宫，这一年被善待、人缘与机会都比平时顺，心情也松；关键是把福气转成积累，防只顾当下舒服、该推进的事被拖过去。',
 enD:'With Tian Tong Hua Lu in the Life Palace, the year brings goodwill, connections and smoother openings along with an easier mood; turn that goodwill into accumulation and guard against chasing comfort while what should move gets delayed.',
 cnL:'天同是福星，化禄落回命宫，等于这一年「被善待」的资源直接到自己身上，日子比平时好过。',
 enL:'Tian Tong is the ease star, and with Hua Lu back in the Life Palace, the resource of being treated well reaches you directly and life runs easier.',
 cnA:'有人这一年处处遇贵人、心情好，却松过头、把计划全拖了，问题不在福气多，而在把「舒服」当成了目标，没把顺境转成积累。',
 enA:'Some meet helpers everywhere and feel good, yet ease too much and delay every plan; the issue is not abundant goodwill but making comfort the goal instead of turning smooth times into accumulation.',
 cnLog:['天同化禄主缓和、享受、人情与被照顾，落命宫时这一年人缘顺、开口容易被接住。','它给的是「顺风的状态」，不是自动的成果，仍要自己把事情定下来、往前走。','天同喜享受，化禄要防松散拖延，尤其把该做的决定以「再说」搁下。','流年化禄只主一年，长期性格与成就仍以本命命宫与大限为主。'],
 enLog:['Tian Tong Hua Lu governs ease, enjoyment, warmth and being cared for; in the Life Palace the year brings smooth connections and words that are readily received.','It gives a tailwind state, not automatic results; you still have to settle matters and move forward yourself.','Tian Tong enjoys ease, so with Hua Lu guard against slack and delay, especially setting decisions aside with later.','An annual Hua Lu governs only one year; long-term character and achievement still rest on the natal Life Palace and decade.'],
 cnStep:['先确认本命命宫主星，看天同化禄是落在怎样的底色上','把今年被善待、被帮助的机会具体列出来','顺境里主动把拖了很久的一两件事定下来','给享受设边界，先完成正事再放松，不颠倒顺序','把人情和好感沉淀成关系与作品，而非只消费心情','年底复盘福气有没有转成积累，校准下一年'],
 enStep:['First confirm the natal Life Palace major star to see the baseline Tian Tong Hua Lu lands on','List concretely the chances this year to be treated well and helped','During smooth times, deliberately settle one or two long-delayed matters','Set a boundary on enjoyment by finishing real work before relaxing, not the reverse','Turn warmth and goodwill into relationships and work rather than only consuming good mood','At year-end review whether goodwill became accumulation and recalibrate'],
 cnMis:['把被善待当成可以不努力，松过头','只图当下舒服，把该定的决定一直拖','把一年顺境误判成长期，不看本命大限'],
 enMis:['Taking being treated well as permission to stop trying and easing too much','Chasing present comfort and delaying decisions that should be settled','Taking one smooth year as long-term without the natal chart and decade'],
 cnClose:'天同化禄在命宫的功课，是「接得住福气，也不被福气养懒」。把顺境用来定事、攒底，这一年的好才留得下来。',
 enClose:'Tian Tong Hua Lu in the Life Palace teaches receiving goodwill without being made lazy by it. Use smooth times to settle matters and build reserves, and the year good stays with you.'},

{cat:'sihua',slug:'ziwei-2026-tiantonghualu-caibogong',focus:'天同化禄在财帛宫',focusEn:'Tian Tong Hua Lu in the Wealth Palace',
 cnT:'2026天同化禄在财帛宫：轻松得财、人情生财，也要留得住',enT:'2026 Tian Tong Hua Lu in the Wealth Palace: Easier, People-Based Income That You Still Must Keep',
 cnD:'天同化禄落财帛，这一年钱来得相对轻松、人缘能生财，机会多在服务、人情与合作上；关键是把到手的钱留住、转成储蓄，防随手花掉（不构成投资建议）。',
 enD:'With Tian Tong Hua Lu in the Wealth Palace, money arrives more easily and connections can generate income, often through service, warmth and cooperation; keep what arrives and turn it into savings rather than spending it freely. This is not investment advice.',
 cnL:'天同化禄在财帛，是那种「不太费力就有钱进来」的年份，但轻松的钱也最容易轻松地花出去。',
 enL:'Tian Tong Hua Lu in the Wealth Palace marks a year when money comes in without great strain, yet easy money is also the easiest to spend.',
 cnA:'有人这一年进项不错，年底却没存下，问题不在赚得少，而在把轻松得的财当意外之财随手花，没立储蓄和预算。',
 enA:'Some earn well this year yet save nothing by year-end; the issue is not low income but treating easy money as windfall and spending it without savings or a budget.',
 cnLog:['天同化禄在财帛，主财源缓和、人情生财与服务型收入，过程不紧绷。','它给的是「进得顺」，不保证「存得住」，留存要靠预算和自动储蓄。','逢煞忌或天同被冲，轻松财也会伴随随手花、人情支出增多。','财务安排不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Tong Hua Lu in the Wealth Palace governs relaxed income, people-based earnings and service revenue without a strained process.','It gives smooth inflow but does not guarantee retention; keeping money depends on a budget and automatic savings.','When met by malefics, obstruction or a clash, easy money is paired with free spending and rising social expenses.','Financial arrangements are not investment advice; rely on licensed institutions and formal product terms.'],
 cnStep:['先看本命财帛主星与命财官三合，定收入的基本方式','今年收入顺时，先按比例自动转储蓄再安排开销','把人情、服务、合作带来的机会列清楚并主动接','人情往来单列预算，防面子支出吃掉盈余','大额消费和投资缓一缓，以正规产品说明为准','每季度对账，看轻松钱有没有真正留下来'],
 enStep:['First read the natal Wealth Palace major star and the Life-Wealth-Career trine to set the basic income model','When income flows this year, move a share to savings automatically before spending','List clearly the chances from warmth, service and cooperation and take them actively','Budget social spending separately so face expenses do not eat the surplus','Slow down large purchases and investments and rely on formal product terms','Reconcile accounts each quarter to see whether easy money is genuinely kept'],
 cnMis:['把轻松得财当意外之财，随手花光','只看进得顺，不立预算和储蓄','把一年好财运当长期，忽略本命财富格局'],
 enMis:['Treating easy income as windfall and spending it freely','Seeing only smooth inflow without a budget or savings','Taking one good money year as long-term and ignoring the natal wealth pattern'],
 cnClose:'天同化禄在财帛的功课，是「让轻松来的钱不轻松地走」。先存后花、单列人情预算，这一年的顺财才真正变成底气。',
 enClose:'Tian Tong Hua Lu in the Wealth Palace teaches not letting easy money leave easily. Save first, budget social spending separately, and the year smooth income becomes real security.'},

{cat:'sihua',slug:'ziwei-2026-tiantonghualu-guanlugong',focus:'天同化禄在官禄宫',focusEn:'Tian Tong Hua Lu in the Career Palace',
 cnT:'2026天同化禄在官禄宫：工作气氛缓和，利协调服务，防躺平',enT:'2026 Tian Tong Hua Lu in the Career Palace: A Gentler Workplace Favoring Coordination, While Guarding Against Checking Out',
 cnD:'天同化禄落官禄，这一年工作关系缓和、利协调、服务与人情型岗位，冲突少；关键是借顺境把事做成、把位置坐稳，防一味求轻松而不上进。',
 enD:'With Tian Tong Hua Lu in the Career Palace, work relationships ease and coordination, service and people-focused roles benefit with less conflict; use the smooth period to deliver and secure your position, guarding against seeking ease so much that you stop advancing.',
 cnL:'天同化禄在官禄，是职场上「好说话、好配合、少硬碰」的一年，推进事情比平时少阻力。',
 enL:'Tian Tong Hua Lu in the Career Palace makes the workplace easier to talk with and cooperate with and lower on confrontation, so moving things forward meets less resistance.',
 cnA:'有人这一年职场顺、人际松，却顺势躺平、绩效平平，问题不在环境太舒服，而在把「少冲突」误当成「可以不成长」。',
 enA:'Some find work smooth and relations relaxed but check out and deliver mediocre results; the issue is not a comfortable environment but mistaking low conflict for permission to stop growing.',
 cnLog:['天同化禄在官禄，主工作气氛缓和、利协调服务、对上对下都好沟通。','它减的是摩擦，不是责任，事情仍要按时交付、成果仍要做出来。','天同喜安逸，化禄要防「躺平」，表现为只挑轻松活、回避挑战。','流年化禄只主一年工作氛围，长期事业仍以本命官禄与大限为主。'],
 enLog:['Tian Tong Hua Lu in the Career Palace governs an eased work climate, favoring coordination and service and smooth communication up and down.','It reduces friction, not responsibility; work still ships on time and results still must be produced.','Tian Tong likes ease, so with Hua Lu guard against checking out, shown by taking only easy tasks and avoiding challenge.','An annual Hua Lu governs only one year work climate; long-term career still rests on the natal Career Palace and decade.'],
 cnStep:['先看本命官禄主星与三方，定工作的基本姿态','借沟通顺畅的一年，主动协调卡住的项目和关系','把缓和用在推进正事上，而非只用来躲冲突','主动接一件有挑战的任务，防只挑轻松活','和上级谈目标与成长，把顺境转成可见成果','定期复盘绩效，避免松到被边缘化'],
 enStep:['First read the natal Career Palace major star and its trine to set the basic work posture','Use the year smooth communication to actively coordinate stalled projects and relations','Direct the easing toward moving real work rather than only avoiding conflict','Take on one challenging task to guard against choosing only easy work','Discuss goals and growth with leadership and turn smooth times into visible results','Review performance regularly to avoid easing into being sidelined'],
 cnMis:['把职场缓和当躺平理由，回避挑战','只享受少冲突，不交付成果','把一年顺境当长期，不看本命官禄与大限'],
 enMis:['Taking an eased workplace as reason to check out and avoid challenge','Enjoying low conflict without delivering results','Taking one smooth year as long-term without the natal Career Palace and decade'],
 cnClose:'天同化禄在官禄的功课，是「把和气变成推进力」。少冲突的一年里主动成事、接一件难事，位置才会越坐越稳。',
 enClose:'Tian Tong Hua Lu in the Career Palace teaches turning goodwill into drive. In a low-conflict year, deliver and take on one hard thing, and your position grows steadier.'},

{cat:'sihua',slug:'ziwei-2026-tiantonghualu-fudegong',focus:'天同化禄在福德宫',focusEn:'Tian Tong Hua Lu in the Karma Palace',
 cnT:'2026天同化禄在福德宫：精神放松、利睡眠情绪，防沉溺安逸',enT:'2026 Tian Tong Hua Lu in the Karma Palace: Mental Ease for Sleep and Mood, While Guarding Against Indulgence',
 cnD:'天同化禄落福德，这一年精神松、容易知足，利睡眠与情绪恢复；关键是把放松用成续航而非逃避，防沉溺安逸、兴趣消磨斗志。',
 enD:'With Tian Tong Hua Lu in the Karma Palace, the mind relaxes and contentment comes more easily, helping sleep and emotional recovery; use that ease as stamina rather than escape, guarding against indulgence that lets comforts wear down drive.',
 cnL:'天同本就最喜入福德，化禄落在这里，是这一年心里容易松、容易想开，精神上有人照顾自己。',
 enL:'Tian Tong is naturally most at home in the Karma Palace, and with Hua Lu there the mind eases and lets go more readily, as if cared for from within.',
 cnA:'有人这一年睡得好、想得开，却松到提不起劲、正事全靠后，问题不在放松本身，而在把休息过成了逃避。',
 enA:'Some sleep well and let go this year yet ease into low motivation and put real work last; the issue is not relaxation itself but turning rest into avoidance.',
 cnLog:['天同化禄在福德，主精神缓和、知足常乐，利睡眠、情绪与压力恢复。','它给的是「恢复力」，用好了续航更足，用过了则安于现状。','要防沉溺安逸，包括靠娱乐和兴趣回避真正要面对的事。','流年化禄只主一年心境，长期精神状态仍以本命福德与大限为主。'],
 enLog:['Tian Tong Hua Lu in the Karma Palace governs mental ease and contentment, helping sleep, mood and recovery from stress.','It gives resilience; used well it adds stamina, overused it settles for the status quo.','Guard against indulgence, including using entertainment and hobbies to avoid what must be faced.','An annual Hua Lu governs only one year state of mind; long-term mental outlook still rests on the natal Karma Palace and decade.'],
 cnStep:['先看本命福德主星与三方，定精神底色','把放松安排成规律休息，而不是无节制地消遣','睡好、情绪稳时优先处理拖了很久的正事','给兴趣和享受定时长，防占掉主要时间','留一点适度挑战，保持基本的斗志和节奏','观察自己是在恢复还是在逃避，及时调整'],
 enStep:['First read the natal Karma Palace major star and its trine to set the mental baseline','Arrange relaxation as regular rest rather than unlimited distraction','When sleeping well and steady, handle long-delayed real matters first','Set time limits on hobbies and enjoyment so they do not take the main hours','Keep a modest challenge to maintain basic drive and rhythm','Notice whether you are recovering or avoiding and adjust'],
 cnMis:['把放松过成逃避，正事全靠后','无节制消遣，把恢复力变成懒散','把一年心境好当长期，不看本命福德'],
 enMis:['Turning relaxation into avoidance and putting real work last','Indulging without limit and turning resilience into laziness','Taking one good mental year as long-term without the natal Karma Palace'],
 cnClose:'天同化禄在福德的功课，是「会休息也会起身」。把松下来的精神养回干劲，这一年的好心境才用得长久。',
 enClose:'Tian Tong Hua Lu in the Karma Palace teaches resting well and then rising. Restore the eased mind back into drive, and the year good state lasts.'},

{cat:'sihua',slug:'ziwei-2026-tianjihuaquan-minggong',focus:'天机化权在命宫',focusEn:'Tian Ji Hua Quan in the Life Palace',
 cnT:'2026天机化权在命宫：谋略决断增强，防算得太精、刚愎',enT:'2026 Tian Ji Hua Quan in the Life Palace: Sharper Strategy and Decisiveness, While Guarding Against Overcalculation and Stubbornness',
 cnD:'天机化权落命宫，这一年动脑、决断与掌控力都增强，想做的事能推动；关键是把聪明用于落实，防刚愎自用、算过头和变动太频。',
 enD:'With Tian Ji Hua Quan in the Life Palace, thinking, decisiveness and control strengthen this year and what you want can be moved; use the intelligence to execute, guarding against stubbornness, overcalculation and too-frequent change.',
 cnL:'天机是智谋星，化权等于这一年想法「长了牙齿」，不再只是想，而是能定、能推、能落地。',
 enL:'Tian Ji is the strategist, and Hua Quan gives this year ideas teeth; they are no longer only considered but decided, pushed and carried out.',
 cnA:'有人这一年特别有主意、能掌控，却听不进人、反复改主意，问题不在不够聪明，而在把权用成了固执，没给执行和协作留空间。',
 enA:'Some are full of ideas and control this year yet cannot listen and keep changing plans; the issue is not low intelligence but turning authority into stubbornness with no room for execution or collaboration.',
 cnLog:['天机化权主谋略、决断与掌控，落命宫时这一年主见强、推动快。','它承接前一年的化禄，重点从「想得到」转向「做得到」，落实比分析更重要。','化权属刚，要防刚愎自用、算得太精和频繁调整让人跟不上。','流年化权只主一年，长期性格仍以本命命宫与大限为主。'],
 enLog:['Tian Ji Hua Quan governs strategy, decisiveness and control; in the Life Palace the year brings strong views and fast progress.','It follows the prior year Hua Lu and shifts the focus from conceiving to achieving, where execution matters more than analysis.','Hua Quan is firm; guard against stubbornness, overcalculation and frequent adjustments others cannot follow.','An annual Hua Quan governs only one year; long-term character still rests on the natal Life Palace and decade.'],
 cnStep:['先看本命命宫主星，定天机化权落在怎样的底色上','把今年想推动的事列成少数重点，避免主意太多','每个决定定了就给执行期，不边做边反复改','主动听一次不同意见，防刚愎、补盲区','把复杂方案收成可执行的几步，防算过头','推进时照顾协作节奏，不让人总跟不上'],
 enStep:['First read the natal Life Palace major star to set the baseline Tian Ji Hua Quan lands on','Turn what you want to push this year into a few priorities to avoid having too many ideas','Once a decision is made, give it an execution window instead of revising while doing','Actively listen once to opposing views to guard against stubbornness and blind spots','Reduce complex plans into a few executable steps to avoid overcalculation','When pushing, mind the collaboration rhythm so others are not always behind'],
 cnMis:['主意太多、变动太频，让人无法跟随','听不进意见，把掌控用成固执','只在脑内盘算，不给落实和执行留时间'],
 enMis:['Too many ideas and too-frequent changes that others cannot follow','Refusing to listen and turning control into stubbornness','Only calculating in the mind with no time for implementation'],
 cnClose:'天机化权在命宫的功课，是「让聪明变成行动」。少改主意、肯听意见、重在落实，这一年的决断才真正成事。',
 enClose:'Tian Ji Hua Quan in the Life Palace teaches turning intelligence into action. Change plans less, listen and focus on execution, and the year decisiveness genuinely delivers.'},

{cat:'sihua',slug:'ziwei-2026-tianjihuaquan-caibogong',focus:'天机化权在财帛宫',focusEn:'Tian Ji Hua Quan in the Wealth Palace',
 cnT:'2026天机化权在财帛宫：靠策划动脑进财，防算过头、钱不安稳',enT:'2026 Tian Ji Hua Quan in the Wealth Palace: Income Through Planning, While Guarding Against Overcalculation and Unsteady Money',
 cnD:'天机化权落财帛，这一年靠策划、技术与动脑进财，现金流可因安排得当而改善；关键是方案落地、账目清楚，防只算不动或算过头（不构成投资建议）。',
 enD:'With Tian Ji Hua Quan in the Wealth Palace, income comes through planning, skill and thinking, and cash flow can improve when arranged well; land the plans and keep clear accounts, guarding against only calculating or overcalculating. This is not investment advice.',
 cnL:'天机化权在财帛，是「靠脑子和方案赚钱」的年份，钱不是等来的，是策划和执行安排出来的。',
 enL:'Tian Ji Hua Quan in the Wealth Palace marks a year of earning through the mind and plans; money is not waited for but arranged through planning and execution.',
 cnA:'有人这一年方案很多、算得很细，却迟迟不动手或频繁换方向，结果没进多少财，问题在重盘算、轻落地。',
 enA:'Some have many plans and detailed calculations this year yet never act or keep changing direction and earn little; the issue is heavy figuring and light follow-through.',
 cnLog:['天机化权在财帛，主靠策划、技术、信息与统筹进财，利专业与顾问型收入。','它要的是「方案落地」，光盘算不执行，再好的安排也变不成钱。','化权要防算过头、频繁调整，让收入来源不稳。','财务安排不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['Tian Ji Hua Quan in the Wealth Palace governs income through planning, skill, information and coordination, favoring professional and advisory earnings.','It requires plans to land; with only figuring and no execution, even good arrangements never become money.','Hua Quan calls for guarding against overcalculation and frequent adjustment that make income sources unsteady.','Financial arrangements are not investment advice; rely on licensed institutions and formal product terms.'],
 cnStep:['先看本命财帛主星与命财官，定赚钱的基本方式','把能进财的策划和技能列成具体产品或服务','每个方案定执行节点，边算边做、不停在纸面','账目和现金流单独管清楚，定期对账','收入来源一次别铺太多，防频繁换方向','大额投资缓办，以正规产品说明为准'],
 enStep:['First read the natal Wealth Palace major star and the Life-Wealth-Career trine to set the basic earning model','Turn money-making plans and skills into concrete products or services','Set an execution point for each plan and act while figuring rather than staying on paper','Manage accounts and cash flow separately and reconcile regularly','Do not open too many income sources at once to avoid frequent direction changes','Slow large investments and rely on formal product terms'],
 cnMis:['只盘算不执行，方案变不成收入','方向换得太勤，财源不稳','把动脑赚钱当稳赚，忽略风险与正规说明'],
 enMis:['Only figuring without executing so plans never become income','Changing direction too often and making earnings unsteady','Taking mind-based income as guaranteed while ignoring risk and formal terms'],
 cnClose:'天机化权在财帛的功课，是「把方案变成进账」。边想边做、账目清楚、少换方向，动脑的钱才落得稳。',
 enClose:'Tian Ji Hua Quan in the Wealth Palace teaches turning plans into receipts. Act while thinking, keep clear accounts and change direction less, and mind-based income lands steadily.'},

{cat:'sihua',slug:'ziwei-2026-tianjihuaquan-guanlugong',focus:'天机化权在官禄宫',focusEn:'Tian Ji Hua Quan in the Career Palace',
 cnT:'2026天机化权在官禄宫：事业突破与改组，利技术统筹，防变动过频',enT:'2026 Tian Ji Hua Quan in the Career Palace: Breakthrough and Restructuring Favoring Technical Leadership, While Guarding Against Too Much Change',
 cnD:'天机化权落官禄，这一年事业有突破、改组与升迁机会，利技术、统筹与幕后决策；关键是把改革落到成果，防变动过频、团队跟不上。',
 enD:'With Tian Ji Hua Quan in the Career Palace, work brings breakthroughs, restructuring and promotion chances, favoring technical, coordinating and behind-the-scenes decision roles; carry reforms into results and guard against too much change that the team cannot follow.',
 cnL:'天机化权在官禄，是事业上「想改、能改、改得动」的一年，僵局容易被推动。',
 enL:'Tian Ji Hua Quan in the Career Palace marks a year when work wants to change, can change and can be moved, so deadlocks are readily pushed open.',
 cnA:'有人这一年改革不断、点子频出，团队却疲于跟随、成果不扎实，问题不在不改，而在改得太频、没给落地留时间。',
 enA:'Some drive constant reforms and frequent ideas this year while the team tires following and results stay thin; the issue is not changing but changing too often with no time to land.',
 cnLog:['天机化权在官禄，主事业突破、改组、流程优化与技术统筹的机会。','它利「想清楚再改」，改革要有目标、有步骤、有验收，而非凭兴致调整。','化权要防变动过频、刚愎，让团队无所适从、成果反复。','流年化权只主一年事业节奏，长期仍以本命官禄与大限为主。'],
 enLog:['Tian Ji Hua Quan in the Career Palace governs breakthroughs, restructuring, process improvement and technical coordination.','It favors thinking clearly before changing; reform needs goals, steps and acceptance rather than adjustment by mood.','Hua Quan calls for guarding against too-frequent change and stubbornness that leave the team unsure and results unstable.','An annual Hua Quan governs only one year career rhythm; the long term still rests on the natal Career Palace and decade.'],
 cnStep:['先看本命官禄主星与三方，定事业基本方向','把今年要改的事收成一两项重点，不同时开太多','每项改革定目标、步骤和验收标准','给团队留执行和适应时间，不朝令夕改','关键岗位用技术与统筹能力立住权威','阶段性验收成果，再决定要不要继续改'],
 enStep:['First read the natal Career Palace major star and its trine to set the basic career direction','Reduce what should change this year to one or two priorities rather than opening too much','Set goals, steps and acceptance criteria for each reform','Give the team time to execute and adapt rather than changing orders daily','Use technical and coordinating ability to establish authority in key roles','Accept results in stages before deciding whether to keep changing'],
 cnMis:['改革点太多、变动太频，团队跟不上','凭兴致调整，没有目标和验收','把一年突破当长期，不看本命官禄大限'],
 enMis:['Too many reforms and too-frequent changes that the team cannot follow','Adjusting by mood without goals or acceptance','Taking one breakthrough year as long-term without the natal Career Palace and decade'],
 cnClose:'天机化权在官禄的功课，是「会改也会收成」。把改革聚焦、给落地时间、按验收说话，这一年的突破才立得住。',
 enClose:'Tian Ji Hua Quan in the Career Palace teaches knowing how to change and to harvest. Focus reform, give it time to land and speak through acceptance, and the year breakthrough holds.'},

{cat:'sihua',slug:'ziwei-2026-tianjihuaquan-qianyigong',focus:'天机化权在迁移宫',focusEn:'Tian Ji Hua Quan in the Travel Palace',
 cnT:'2026天机化权在迁移宫：外部机会与奔波，利出差迁移，防劳损',enT:'2026 Tian Ji Hua Quan in the Travel Palace: Outside Opportunity and Movement Favoring Travel, While Guarding Against Strain',
 cnD:'天机化权落迁移，这一年外部机会多、利出差、搬迁与对外拓展，能靠应变打开局面；关键是把奔波安排出节奏，防过劳、变动太多和在外少援。',
 enD:'With Tian Ji Hua Quan in the Travel Palace, outside opportunities abound and travel, relocation and outward expansion benefit, with adaptability opening new ground; pace the movement and guard against overwork, too much change and feeling unsupported away from home.',
 cnL:'天机化权在迁移，是「走出去就有机会」的一年，外部的变化和应变反而能把局面打开。',
 enL:'Tian Ji Hua Quan in the Travel Palace marks a year when stepping out creates opportunity, where outside change and adaptability open the situation.',
 cnA:'有人这一年四处奔波、机会不少，却累得够呛、事情也铺得太散，问题不在不该动，而在没给奔波排节奏、没留休整。',
 enA:'Some move about constantly with many chances this year yet end exhausted and overstretched; the issue is not that movement is wrong but scheduling it with no rhythm and no recovery.',
 cnLog:['天机化权在迁移，主外部机会、出差搬迁、对外谈判与应变能力增强。','它利「动中开拓」，但方向要清楚，否则机会越多越散。','化权要防奔波过劳、变动过频，以及在外少援、事事亲为。','流年化权只主一年外部节奏，长期仍以本命迁移与大限为主。'],
 enLog:['Tian Ji Hua Quan in the Travel Palace governs outside opportunity, travel and relocation, external negotiation and stronger adaptability.','It favors opening ground through movement, but the direction must be clear or more opportunities mean more scatter.','Hua Quan calls for guarding against exhausting travel, too-frequent change, little support away from home and doing everything yourself.','An annual Hua Quan governs only one year outside rhythm; the long term still rests on the natal Travel Palace and decade.'],
 cnStep:['先看本命迁移主星与命迁线，定对外的基本姿态','把今年外部机会收成少数重点，按方向取舍','出差搬迁提前排期，给行程留缓冲和休整','在外的接应、联系人提前落实，防少援','重要谈判准备方案，靠应变而非临场硬扛','定期回顾奔波有没有转成成果，及时收束'],
 enStep:['First read the natal Travel Palace major star and the Life-Travel line to set the basic outward posture','Reduce this year outside opportunities to a few priorities chosen by direction','Schedule travel and relocation in advance with buffer and recovery','Arrange support and contacts away from home beforehand to prevent going unsupported','Prepare plans for key negotiations and rely on adaptability rather than forcing it on the spot','Review periodically whether movement became results and rein in as needed'],
 cnMis:['外部机会全接，铺得太散','行程排满、不留休整，奔波劳损','只看流年，不回到本命迁移与大限'],
 enMis:['Taking every outside opportunity and overstretching','Filling the schedule with no recovery and exhausting oneself through travel','Reading only the year without the natal Travel Palace and decade'],
 cnClose:'天机化权在迁移的功课，是「动得出去也收得回来」。按方向取舍、给奔波留休整，外部的机会才真正变成局面。',
 enClose:'Tian Ji Hua Quan in the Travel Palace teaches being able to move out and pull back. Choose by direction and leave recovery in travel, and outside opportunities genuinely become new ground.'}
];
