// 2026-10-08 调研驱动 第2组：四化 4（组成路线/飞禄飞忌/引合/权科路线）+ 入门 4（对批盘/学星曜/看财富/看健康）
module.exports=[
{cat:'sihua',slug:'ziwei-sihua-zucheng-luxian-ruhe-kan',focus:'四化组成路线',focusEn:'the route formed by the Four Transformations',
 cnT:'四化组成路线：资源—掌控—名声—课题连成一条线',enT:'The Route Formed by the Four Transformations',
 cnD:'禄权科忌各管一段，连起来是一条完整路线：化禄给资源起步、化权给掌控执行、化科给名声收尾、化忌给要修的课题；四化不是四颗孤立按钮，是一条能量流动线。',
 enD:'Lu Quan Ke Ji each govern a segment, together forming one complete route: Lu gives resources to start, Quan gives control to execute, Ke gives reputation to finish and Ji gives the lesson to work on. They are not four isolated buttons but one energy-flow line.',
 cnL:'四化像一件事的四个阶段：有资源、能掌控、被看见、留课题，断一段都不完整。',
 enL:'The transformations are like four stages of a matter: having resources, control, being seen and a lesson; missing one stage is incomplete.',
 cnA:'有人把四化当四个独立标签贴，没看到它们串成的路线；顺着路线读，才知道一件事怎么一步步走。',
 enA:'Some take the transformations as four independent labels, missing the route; reading along the route shows how a matter proceeds.',
 cnLog:['化禄：资源、机缘、起点。','化权：掌控、执行、推进。','化科：名声、缓和、收尾。','化忌：课题、卡点、要修处，四段相连。'],
 enLog:['Lu: resources, opportunity, start.','Quan: control, execution, advance.','Ke: reputation, smoothing, finish.','Ji: lesson, sticking point, work area; four segments linked.'],
 cnStep:['先认四化各自的阶段位置','看禄在哪宫、资源从哪起','看权科怎么接、怎么收','看忌落在哪、课题在哪','把四化按路线连起来','判断这条路线顺不顺、卡在哪段'],
 enStep:['First recognize each transformation stage','See which palace Lu is in, where resources start','See how Quan Ke advance and finish','See where Ji lands, the lesson','Link transformations along the route','Judge whether the route is smooth, where it stalls'],
 cnMis:['四化当孤立标签、不连线','只看单化、不看四段衔接','把路线当固定吉凶'],
 enMis:['Taking transformations as isolated labels, not linking','Seeing one transformation without the four segments','Taking the route as fixed good or bad'],
 cnClose:'四化组成路线看的是「能量怎么从资源流到课题」。四段连起来读，你才读得懂一件事的完整走向。',
 enClose:'The transformation route asks how energy flows from resources to lesson. Read four segments linked, and you understand a matter complete direction.'},

{cat:'sihua',slug:'ziwei-feilu-feiji-ruhe-kan',focus:'飞禄飞忌',focusEn:'flying Lu and flying Ji',
 cnT:'飞禄飞忌：一宫干飞禄看投入、飞忌看结果',enT:'Flying Lu and Flying Ji from a Palace Stem',
 cnD:'看某宫，宫干飞化禄看这领域主动投入与机缘，飞化忌看它的牵挂与结果；一宫之飞禄飞忌合起来，才读得到这件事「因什么投入、最后落什么结果」。',
 enD:'For a palace, its stem flying Lu shows active investment and opportunity in the area, flying Ji shows attachment and result. The flying Lu and Ji together read why it invests and what result finally lands.',
 cnL:'飞禄是「我往哪给」，飞忌是「我心挂哪」；一头一尾，合起来是一件事的来去。',
 enL:'Flying Lu is where I give, flying Ji is where my heart hangs; the two ends together are a matter coming and going.',
 cnA:'有人只看飞禄、乐观投入却没看飞忌的结果；也有人只看飞忌、被结果吓住；两头一起读才全。',
 enA:'Some see only flying Lu and invest without the Ji result; others see only Ji and are frightened; read both for the full picture.',
 cnLog:['宫干飞禄：主动投入、结缘、求财的方向。','宫干飞忌：牵挂、亏欠、结果的方向。','禄为因、忌为果。','落宫主星定投入与结果的具体形式。'],
 enLog:['Palace stem flying Lu: active investment, connection and gain direction.','Flying Ji: attachment, debt and result direction.','Lu is cause, Ji result.','Landing palace stars set the concrete form.'],
 cnStep:['先立太极、选要读的宫','找该宫天干','看飞禄落宫、定投入方向','看飞忌落宫、定结果方向','用禄转忌再追一步','合落宫星性定具体走向'],
 enStep:['First set Tai Ji and choose the palace','Find that palace stem','Read flying Lu landing for investment direction','Read flying Ji landing for result direction','Use Lu-turns-to-Ji one more step','Combine landing star nature for concrete direction'],
 cnMis:['只看飞禄不看飞忌','只看飞忌不看飞禄','不立太极、方向乱'],
 enMis:['Seeing only flying Lu without Ji','Seeing only Ji without Lu','Not setting Tai Ji, direction lost'],
 cnClose:'飞禄飞忌看的是「一件事的投入和结果两头」。合起来读、再追禄转忌，你才知道因什么给、最后落什么。',
 enClose:'Flying Lu and Ji read the investment and result ends. Read together and trace Lu-turns-to-Ji, and you know why you give and what finally lands.'},

{cat:'sihua',slug:'ziwei-sihua-yinhe-ruhe-kan',focus:'四化引合',focusEn:'transformations joining and reinforcing',
 cnT:'四化引合：飞化碰生年自化「成组」，力量翻倍',enT:'Transformations Joining: When Flights Meet Natal or Self-Transformations',
 cnD:'引合是飞化碰到生年四化或自化、「成组」时力量加强：禄与忌成一组、权与科成一组；看一件事有没有被引合、成不成组，判断这股力量是翻倍还是落空。',
 enD:'Joining is when flights meet natal or self-transformations and form groups, reinforcing force: Lu with Ji is one group, Quan with Ke another. See whether a matter is joined and forms groups to judge whether force doubles or falls through.',
 cnL:'飞化像一根线，碰到生年或自化像接上电源，成组就通电、力量翻倍。',
 enL:'Flights are like a wire; meeting natal or self-transformation is like connecting power; forming groups energizes and doubles force.',
 cnA:'有人只看单颗飞化、不看有没有引合，力量估得不准；成不成组，差别很大。',
 enA:'Some see a single flight without checking joining, misjudging force; whether it forms a group makes a big difference.',
 cnLog:['引合：飞化与生年或自化相遇。','禄忌成组：投入与结果接上。','权科成组：执行与名声接上。','成组力量翻倍，不接则力量散。'],
 enLog:['Joining: flights meet natal or self-transformation.','Lu-Ji group: investment connects with result.','Quan-Ke group: execution connects with reputation.','Groups double force; no connection scatters it.'],
 cnStep:['先找飞化落点','看落点有没有生年四化','看落点有没有自化','判断禄忌或权科成不成组','成组：力量翻倍、主题加强','不成组：力量一般、再找别的引动'],
 enStep:['First find flight landings','See whether landings have natal transformations','See whether landings have self-transformations','Judge whether Lu-Ji or Quan-Ke form groups','Group: force doubles, theme strengthens','No group: force average, seek other activation'],
 cnMis:['只看单飞化、不看引合','成不成组分不清','把没引合的力量估太高'],
 enMis:['Seeing single flights without joining','Unable to tell whether groups form','Overestimating unjoined force'],
 cnClose:'四化引合看的是「飞化有没有接上电源、成不成组」。成组力量翻倍、主题加重，你才读得准一件事的强弱。',
 enClose:'Transformation joining asks whether flights connect and form groups. Groups double force and strengthen theme, and you read a matter strength accurately.'},

{cat:'sihua',slug:'ziwei-quanke-luxian-ruhe-kan',focus:'权科路线',focusEn:'the Quan-Ke route',
 cnT:'权科路线：实干被看见，专业成名的一条路',enT:'The Quan-Ke Route: Doing the Work and Being Seen',
 cnD:'化权的执行接化科的名声，是「实干—被看见—成名」的路线：先靠权把事做扎实，再靠科让专业被认可，适合技术、专业、学术立身，防好胜和虚名。',
 enD:'Quan execution connects with Ke reputation, the route of doing, being seen and becoming known: first use Quan to do solid work, then Ke to have expertise recognized, suiting technical, professional and scholarly standing; guard competitiveness and empty name.',
 cnL:'权科路线是「做得出、也讲得明、还被看见」，专业靠这条路立名。',
 enL:'The Quan-Ke route is producing, explaining and being seen; expertise builds name this way.',
 cnA:'有人只实干不彰显（有权无科）、专业被埋没；也有人只图名声不做实功（有科无权）、成虚名；权科接上才稳。',
 enA:'Some only do work without showing it (Quan without Ke), expertise buried; others seek name without substance (Ke without Quan), empty fame; Quan connected with Ke is steady.',
 cnLog:['权：执行、掌控、把事做实。','科：名声、理性、让专业被看见。','权科相接：实干成名。','防好争功（权过）与虚名（科过）。'],
 enLog:['Quan: execution, control, doing solid work.','Ke: reputation, reason, having expertise seen.','Quan-Ke connected: doing leads to name.','Guard credit fights (excess Quan) and empty name (excess Ke).'],
 cnStep:['先看权在哪宫、执行落在哪个领域','看科在哪宫、名声落在哪个领域','判断权科接不接得上','接上：做实功、再让专业被认可','防只干不亮或只亮不干','合昌曲、看文名助力'],
 enStep:['First see which palace Quan is in, where execution lands','See which palace Ke is in, where reputation lands','Judge whether Quan and Ke connect','Connected: do solid work, then have expertise recognized','Guard doing without showing or showing without doing','Combine Chang Qu for scholarly support'],
 cnMis:['有权无科、专业埋没','有科无权、虚名无实','权科不接、路线断'],
 enMis:['Quan without Ke, expertise buried','Ke without Quan, empty name','Quan-Ke not connected, route broken'],
 cnClose:'权科路线看的是「实干怎么被看见、成专业之名」。权科接上、做实功再彰显，名声才有根、才立得久。',
 enClose:'The Quan-Ke route asks how doing is seen into professional name. Quan connected with Ke, do solid work then show it, and reputation has roots and lasts.'},

{cat:'rumen',slug:'ziwei-ruhe-dui-bapan',focus:'怎么对批盘',focusEn:'how to practice by comparing charts',
 cnT:'怎么对批盘：拿自己和他人盘对照练，入门快法',enT:'How to Practice by Comparing Charts',
 cnD:'对批盘是入门快法：拿自己的盘和熟悉的家人朋友盘对照，看同一类宫位在不同星性下的差别，再对照现实性格，星性和落宫就理解得快。',
 enD:'Comparing charts is a fast beginner method: take your own chart and those of familiar family or friends, see how the same palace differs across star natures, then compare with real temperament, and star nature and placement are understood quickly.',
 cnL:'一个人读自己的盘容易主观，对照熟悉的盘，才看得出星性的客观差别。',
 enL:'Reading your own chart alone is subjective; comparing familiar charts shows objective star differences.',
 cnA:'有人一上来就读陌生盘、没有现实对照，读得云里雾里；先用熟悉的盘练手最稳。',
 enA:'Some start with unfamiliar charts without real comparison and get confused; practicing with familiar charts is steadiest.',
 cnLog:['先读自己的盘、对照自己性格。','再读熟悉的家人朋友盘。','同宫位、不同星性，对比差别。','用现实相处验证，积累判断。'],
 enLog:['First read your own chart against your temperament.','Then read familiar family and friends charts.','Same palace, different star natures, compare differences.','Verify with real relating to build judgment.'],
 cnStep:['先把自己的盘读一遍','找2-3个熟悉的人的盘','选同一个宫位逐盘对比','记下不同星性的表现差别','用现实性格验证','慢慢扩到不熟悉的盘'],
 enStep:['First read your own chart','Find 2-3 familiar people charts','Choose one palace and compare chart by chart','Note how different star natures behave','Verify with real temperament','Gradually expand to unfamiliar charts'],
 cnMis:['一上来读陌生盘、无现实对照','只读自己盘、主观偏差','不验证、凭想象读'],
 enMis:['Starting with unfamiliar charts without real comparison','Reading only your own chart with subjective bias','Not verifying, reading by imagination'],
 cnClose:'对批盘看的是「用熟悉的盘快速理解星性」。对照差别、现实验证，入门就快、判断就实。',
 enClose:'Comparing charts asks to use familiar charts to understand star nature quickly. Compare differences and verify in reality, and entry is fast and judgment solid.'},

{cat:'rumen',slug:'ziwei-ruhe-xue-xingyao',focus:'怎么学星曜',focusEn:'how to learn the stars',
 cnT:'怎么学星曜：先认星性阴阳五行，再看落宫',enT:'How to Learn the Stars: Nature, Yin-Yang and Elements First',
 cnD:'学星曜别急着背落宫吉凶，先认每颗星的阴阳、五行与核心象义，再看它落在不同宫位、遇到不同同伴怎么变；星性是根，落宫是枝叶。',
 enD:'When learning stars, do not rush to memorize palace fortune; first learn each star yin-yang, elements and core meaning, then see how it changes across palaces and companions. Star nature is the root, placement the branches.',
 cnL:'星曜像人，先了解一个人的本性，再看他在不同场合的样子；顺序反了，越背越乱。',
 enL:'Stars are like people; first know one nature, then see them in different settings; reversing order makes memorization chaotic.',
 cnA:'有人一上来背「某星在某宫吉」，条目太多记不住；先抓星性这根主线，落宫自己能推。',
 enA:'Some start memorizing a star in a palace is good, too many entries to hold; first grasp star nature and placement can be inferred.',
 cnLog:['先认十四主星阴阳五行。','再记每颗星核心象义（一两个关键词）。','看庙旺落陷、判断星有没有力。','最后看落宫与同伴、推表达方式。'],
 enLog:['First learn fourteen stars yin-yang and elements.','Then memorize each star core meaning (one or two keywords).','Read brightness to judge whether the star has force.','Finally read placement and companions to infer expression.'],
 cnStep:['把十四主星按阴阳五行分类','每颗星记一个核心关键词','用自己和熟悉的人盘对照星性','看星曜亮度','练习同颗星在不同宫的变化','再学辅星煞星，方法相同'],
 enStep:['Classify fourteen stars by yin-yang and elements','Memorize one core keyword per star','Use your own and familiar charts to compare nature','Read star brightness','Practice the same star across palaces','Then learn assistant and malefic stars the same way'],
 cnMis:['先背落宫吉凶、不抓星性','条目太多、越背越乱','把星性当固定、不看变化'],
 enMis:['Memorizing palace fortune before star nature','Too many entries, memorization chaotic','Taking star nature as fixed, ignoring change'],
 cnClose:'学星曜看的是「先认本性、再推落宫」。阴阳五行和核心象义是根，根扎稳了，落宫组合自己能读懂。',
 enClose:'Learning stars asks to know nature first and infer placement later. Yin-yang, elements and core meaning are roots; with roots steady, placements can be read.'},

{cat:'rumen',slug:'ziwei-ruhe-kan-caifu',focus:'怎么看财富层次',focusEn:'how to read wealth levels',
 cnT:'怎么看财富层次：财帛官禄田宅三宫合看',enT:'How to Read Wealth Levels: Three Palaces Together',
 cnD:'财富层次不能只看财帛，要三宫合看：财帛写赚钱方式、官禄（三方）写收入来源、田宅写能不能沉淀成库；三宫都稳，财富层次才高，只旺一宫多是过路钱。',
 enD:'Wealth levels cannot rest on Wealth alone; read three palaces: Wealth writes how you earn, Career (trine) writes income sources, Property writes whether it settles into a treasury. All three steady means a high wealth level; only one palace strong is often passing money.',
 cnL:'赚钱（财帛）、来源（官禄）、存钱（田宅）是三件事，合起来才看得到财富的全貌和层次。',
 enL:'Earning (Wealth), sources (Career) and storing (Property) are three matters; together they show the full wealth picture and level.',
 cnA:'有人见财帛吉就当有钱，结果钱留不住；少看了官禄来源和田宅库藏。',
 enA:'Some see Wealth auspicious and assume money, but it does not stay; they missed Career sources and Property treasury.',
 cnLog:['财帛：赚钱方式与现金来源。','官禄：收入靠什么事业来。','田宅：财富能不能沉淀。','三宫四化定资源、掌控、库藏。'],
 enLog:['Wealth: earning method and cash sources.','Career: what work income comes from.','Property: whether wealth settles.','Three-palace transformations set resources, control and storage.'],
 cnStep:['先看财帛、定赚钱方式','再看官禄、定收入来源','后看田宅、定库藏','三宫吉星分别数','看四化飞化、钱怎么流动','判断财富层次与短板'],
 enStep:['First read Wealth for earning method','Then read Career for income sources','Then read Property for storage','Count auspicious stars in all three','Read transformations, how money flows','Judge wealth level and weakness'],
 cnMis:['只看财帛、当存款数字','不看官禄田宅','三宫不合、层次读不出'],
 enMis:['Reading only Wealth as savings balance','Ignoring Career and Property','Not combining three, level unreadable'],
 cnClose:'财富层次看的是「赚钱、来源、库藏三宫咬合」。三宫都稳才是真层次，只旺一处多是过路钱。命理倾向不构成投资建议，以持牌机构说明为准。',
 enClose:'Wealth levels ask whether earning, source and storage interlock. All three steady is a true level; one palace strong is often passing money. This cultural-tendency reference is not investment advice; defer to licensed institutions.'},

{cat:'rumen',slug:'ziwei-ruhe-kan-jiankang',focus:'怎么看健康',focusEn:'how to read health in a chart',
 cnT:'怎么看健康：疾厄宫与三方四化，看倾向不是诊断',enT:'How to Read Health: The Health Palace and Tendencies',
 cnD:'健康看疾厄宫主星与三方、四化，看的是身体容易在哪些方面有倾向、哪些阶段是关口；它不是医学诊断，任何不适都要以正规医院检查为准，不因命理拖延就医。',
 enD:'Health reads the Health Palace star, trines and transformations for where the body tends to be vulnerable and which stages are thresholds. It is not a medical diagnosis; any discomfort must be checked at a proper hospital, not delayed for astrology.',
 cnL:'疾厄宫写身体的倾向，像一张「需要多留意哪里」的提示图，不是一张诊断书。',
 enL:'The Health Palace writes body tendencies, like a map of where to pay attention, not a diagnosis.',
 cnA:'有人拿盘判断自己会得什么病、自己吓自己；也有人完全不看健康节奏；正确是看倾向、定期体检、遵医嘱。',
 enA:'Some judge from the chart what illness they get and frighten themselves; others ignore health timing; the right way reads tendencies, checks regularly and follows doctors.',
 cnLog:['疾厄宫主身体倾向与先天体质。','三方四正看健康有没有冲。','四化：化忌主该阶段健康多操心。','只给倾向，诊断治疗归正规医院。'],
 enLog:['The Health Palace governs body tendencies and innate constitution.','The triple-direction shows whether health has clashes.','Transformations: Ji means more health concern that stage.','It only gives tendencies; diagnosis and treatment belong to hospitals.'],
 cnStep:['先看疾厄宫主星、定体质倾向','看三方有没有煞星冲','看大限流年健康关口','把倾向翻译成需要留意的方向','定期体检、规律作息','不适及时就医、不拖延'],
 enStep:['First read the Health Palace star for constitution tendency','Read trines for malefic clashes','Read decade and year health thresholds','Translate tendencies into areas to watch','Check regularly, keep regular routines','Seek care promptly for discomfort, no delay'],
 cnMis:['拿盘当诊断、自己吓自己','看倾向就拖延正规检查','只看疾厄本宫、不看三方四化'],
 enMis:['Taking the chart as diagnosis and frightening yourself','Delaying proper checks for tendencies','Reading only Health palace without trines'],
 cnClose:'看健康看的是「身体倾向和关口节奏」。它给的是留意方向，不是诊断，定期体检、及时就医才是根本。倾向非诊断，以正规就医为准。',
 enClose:'Reading health asks for body tendencies and threshold timing. It gives areas to watch, not diagnosis; regular checks and prompt care are fundamental. Tendency is not diagnosis; defer to proper medical care.'}
];
