// 2026-10-03 调研驱动 第3组：看盘方法4 + 格局3 + 宫位1 8篇
module.exports=[
{cat:'kanpan',slug:'ziwei-kanpan-wenti-zhixian-ruhe-duzhan',focus:'问题在先再看盘',focusEn:'framing a question before reading the chart',
 cnT:'紫微看盘为什么要「先有问题、再看盘」：泛泛看最容易看花眼',
 enT:'Why to Frame a Question Before Reading a Zi Wei Chart: Vague Reading Blurs Everything',
 cnD:'拿到一张盘就想把十二宫、上百颗星全看一遍，最容易越看越乱、乱贴标签。更稳的是先锁定一个具体问题（比如这两年适不适合换工作、这段关系能不能走下去），再以相关宫位立太极、把三方四正和四化收拢到这条线上。关键是「一事一太极」，一个问题看清再换下一个；盘不会变，问题越具体答案越可验证。',
 enD:'Trying to read all twelve palaces and a hundred stars at once most easily leads to confusion and random labels. A steadier approach is first locking one concrete question, such as whether these two years suit a job change or whether a relationship can last, then setting the taiji on the relevant palaces and gathering the triple-direction and transformations onto that line. The key is one question, one taiji, reading one clearly before moving to the next. The chart does not change, and the more specific the question, the more verifiable the answer.',
 cnL:'很多人排完盘就从头扫到尾，结果信息太多、主次不分；真正会看盘的人，是先问清楚「你到底想解决什么」。',
 enL:'Many people scan a chart from start to finish and end with too much information and no priority; those who read well first ask what exactly you want to resolve.',
 cnA:'这个问题在问：为什么以及怎么带着问题看盘。要先理解「立太极」就是为具体问题定一个中心，再把相关宫位当网络展开。',
 enA:'The question is why and how to read with a question. Understand that setting the taiji means fixing a center for a concrete question, then unfolding the relevant palaces as a network.',
 cnLog:['一张盘信息量很大，没有问题牵引时每个宫都像同等重要，最容易平均用力、抓不住重点。','立太极就是以具体问题所在宫位为中心，先看本宫，再拉对宫与三方，把范围收窄到一条线。','问题不同重心就不同：问事业重官禄与命财官，问感情重夫妻与福德，同一颗星在不同问题里分量不一样。','一次只解一个问题，读完验证、再换下一个，既避免信息过载，也让每个判断都能落到现实核对。'],
 enLog:['A chart carries a great deal of information, and without a question to pull it every palace seems equally important, making it easy to spread effort and miss the point.','Setting the taiji means centering on the palace of the concrete question, reading the home palace first, then pulling the opposite and trine to narrow the scope to one line.','Different questions shift the center: career emphasizes Career and the Life-Wealth-Career trine, relationships emphasize Spouse and Karma, and the same star carries different weight in different questions.','Resolve only one question at a time, verify it, then move to the next, avoiding overload and letting every judgment be checked against reality.'],
 cnStep:['先把想问的事写成一句具体、可验证的问题，避免「我命怎么样」这种大而泛','找到这个问题对应的宫位，以它立太极、作为本宫','拉本宫的对宫和三方四正，把相关星曜列全','看生年、大限、流年四化在这条线上的引动','就这一个问题下判断、给行动建议，不顺手把其他宫也断了','回到现实验证，再决定是否换下一个问题继续看'],
 enStep:['First write what you want to ask as one concrete, verifiable question rather than something broad like how is my fate','Find the palace corresponding to that question and set the taiji on it as the home palace','Pull its opposite and triple-direction and list the relevant stars','Read how the natal, decade and year transformations activate this line','Judge and advise on this one question without casually reading the other palaces','Verify against reality before deciding whether to move to the next question'],
 cnMis:['没具体问题就泛泛看全盘，结果越看越乱','一个问题还没看清就连环断十几件事，件件不扎实','把立太极神秘化，其实就是为具体问题定中心、收范围'],
 enMis:['Reading the whole chart vaguely with no concrete question and growing more confused','Judging a dozen matters before one question is clear, with none solid','Mystifying setting the taiji when it is simply fixing a center and narrowing scope for a question'],
 cnClose:'看盘先立问题，是把一张大网收成一条线的功夫。问题越具体、范围越聚焦，你越能读到可验证的答案，而不是一堆模糊吉凶。',
 enClose:'Framing a question first is the skill of gathering a large net into one line. The more specific the question and focused the scope, the more you reach verifiable answers rather than vague good-or-bad labels.'},

{cat:'kanpan',slug:'ziwei-kanpan-dayun-ruhe-tiqu-zhutici',focus:'给大运流年提取主题词',focusEn:'extracting a theme word for a decade or year',
 cnT:'紫微怎么给一个大运或流年提「主题词」：用主星加四化概括这阶段主线',
 enT:'How to Give a Decade or Year a Theme Word: Summarizing the Stage With the Major Star and Transformations',
 cnD:'看一个十年大运或某一流年，不必罗列所有会发生的事，而是用「大限/流年命宫主星 + 这一层四化 + 叠到本命的宫位」概括一两个主题词，比如「重建秩序」「向外拓展」「向内修复」。主题词不是断吉凶，而是帮你抓住这阶段最值得用力的方向；具体事件仍要结合流年逐月、落到行动，单一年运不主长期结论。',
 enD:'Reading a decade or a year does not require listing everything that happens; instead use the decade or year Life Palace major star, that layer’s transformations and the natal palace it overlaps to summarize one or two theme words, such as rebuilding order, expanding outward or repairing inward. A theme word is not a verdict but helps you grasp where effort is most worthwhile this stage. Specific events still combine the yearly and monthly layers and real action, and one year does not set long-term conclusions.',
 cnL:'很多人看运只想知道「会不会好」，其实更有用的是搞清楚「这阶段主线是什么、该把劲往哪使」。',
 enL:'Many people reading their luck only want to know whether it will be good, but it is more useful to understand the stage’s main line and where to direct effort.',
 cnA:'这个问题在问：怎么从盘上提炼一个阶段的主题词。要先看主事主星，再看四化给它的修饰，最后看它叠到本命哪个领域。',
 enA:'The question is how to distill a stage’s theme word from the chart. First read the leading major star, then the transformations’ modification, and finally the natal field it overlaps.',
 cnLog:['每个大运、流年都由命宫入主的主星定基调，主星星性就是主题词的第一个来源。','这一层四化（禄权科忌）修饰主星：化禄加资源与机会、化权加掌控与推进、化科加名声与修复、化忌加课题与纠缠。','大限/流年命宫叠到本命哪个宫，主题就落在哪个现实领域（事业、家宅、关系、财务等）。','三者合起来概括一两个主题词，用来排这阶段优先级，而不是当成每件具体事的清单。'],
 enLog:['Every decade and year takes its tone from the major star hosting its Life Palace, and that star’s nature is the first source of a theme word.','That layer’s transformations modify the star: Lu adds resources and opportunity, Quan adds control and push, Ke adds reputation and repair, Ji adds lessons and entanglement.','Whichever natal palace the decade or year Life Palace overlaps is the real field where the theme lands: career, home, relationships, finances and so on.','Combine the three to summarize one or two theme words for setting priorities this stage, rather than treating them as a list of every concrete event.'],
 cnStep:['先确定所看大运或流年的命宫主星，写下它的核心星性','找这一层的禄权科忌，记下它们分别给主星加了什么意味','看大限/流年命宫叠到本命哪个宫，确定主题落在哪个领域','把星性、四化修饰、领域合成一两个简短主题词','用主题词排这阶段几件大事的先后与精力分配','进入具体流年流月时再细化，不把主题词当细节预言'],
 enStep:['First identify the Life Palace major star of the decade or year and write down its core nature','Find that layer’s Lu, Quan, Ke and Ji and note what each adds to the star','See which natal palace the decade or year Life Palace overlaps to fix the theme’s field','Combine nature, transformation modification and field into one or two short theme words','Use them to order the stage’s major matters and allocate energy','Refine when entering specific years and months, not treating the theme word as a detailed prophecy'],
 cnMis:['只问运势好坏、不提炼主线，看完仍不知往哪用力','把主题词当成具体事件清单，硬对每件事','只看主星忽略四化与叠宫，主题定得太空泛'],
 enMis:['Only asking whether luck is good or bad without distilling the line, still not knowing where to act','Treating the theme word as a concrete event list and forcing it onto everything','Reading only the star while ignoring transformations and overlap, making the theme too vague'],
 cnClose:'给一个阶段提主题词，是把复杂运限收成一句话方向的功夫。抓住主星、四化和叠宫，你就能知道这几年最该做什么，而不是被琐事带着走。',
 enClose:'Giving a stage a theme word is the skill of condensing complex cycles into one line of direction. Grasping the star, transformations and overlap tells you what matters most these years rather than being led by trivialities.'},

{cat:'kanpan',slug:'ziwei-kanpan-xianshi-dui-bushang-ruhe-chuli',focus:'盘和现实对不上',focusEn:'when the chart and reality do not match',
 cnT:'紫微盘和现实对不上时怎么办：先查排盘、再查读盘，别急着否定',
 enT:'When a Zi Wei Chart Does Not Match Reality: Check the Casting, Then the Reading',
 cnD:'觉得盘和自己对不上，先别急着怀疑命理，多数问题出在两个环节：一是排盘错了（农历换算、闰月、早晚子时、真太阳时、出生地），二是读盘错了（只看一颗星、忽略三方四化、把流年当本命）。关键是按顺序逐项排查、用性格和过往大事定盘，而不是硬把盘往身上套或全盘否定。',
 enD:'When a chart does not seem to fit, do not rush to doubt the system; most issues lie in two places: the casting is wrong, from lunar conversion, leap months, early and late Zi hour, true solar time or birthplace, or the reading is wrong, from one star alone, ignoring the trine and transformations or treating a year as the natal chart. The key is checking item by item in order and rectifying the chart with personality and past events rather than forcing it on or rejecting it wholesale.',
 cnL:'有人拿着盘越看越觉得「这说的不是我」，其实先该回头检查生日时辰和排盘设置，而不是马上否定这张盘。',
 enL:'Some people grow more sure that a chart is not about them, when the first step should be rechecking the birth date, time and casting settings rather than rejecting the chart.',
 cnA:'这个问题在问：盘对不上时按什么顺序排查。要先分清是「盘错」还是「读错」，再分别处理。',
 enA:'The question is what order to follow when a chart does not fit. First distinguish whether the casting is wrong or the reading wrong, then handle each.',
 cnLog:['排盘是第一关：公历没换算农历、闰月处理错、早晚子时没分、真太阳时和出生地没校正，都会让整张盘偏掉。','定盘用客观信息：以命宫星性核对性格、以父母宫核对家庭、以过往升迁婚变搬家等大事核对运限。','若盘没问题就查读法：是否只盯一颗星、忽略三方四正与四化，是否把流年小限误当本命主线。','对不上时最忌讳两件事：硬把解释往身上套，或因一处不符就全盘否定、频繁换盘。'],
 enLog:['Casting is the first gate: failing to convert solar to lunar, mishandling leap months, not splitting early and late Zi hour, or not correcting true solar time and birthplace all shift the chart.','Rectify with objective information: use the Life Star to check temperament, the Parents Palace for family, and past promotions, marriage changes and moves to check the cycles.','If the chart is fine, check the reading: one star alone, ignoring the trine and transformations, or mistaking a year for the natal line.','When it does not fit, two things are worst: forcing the interpretation on yourself, or rejecting the whole chart and switching repeatedly over one mismatch.'],
 cnStep:['先复核出生年月日时、出生地与性别，确认公历/农历换算无误','检查是否涉及闰月、早晚子时、真太阳时校正，必要时排候选盘','用性格、长相倾向与家庭背景先做本命层次的定盘','再用过往大事（升学、工作、婚恋、搬迁、伤病）核对运限','盘确认后，检查自己的读法是否漏了三方、四化与时间层','仍不符就保留疑问、换角度，不硬套也不草率否定'],
 enStep:['First recheck the birth date, time, birthplace and gender, confirming the solar-to-lunar conversion','Check for leap months, early and late Zi hour and true solar time, casting candidate charts if needed','Rectify the natal layer first using temperament, appearance tendencies and family background','Then use past events, schooling, work, relationships, moves and illness, to check the cycles','Once the chart is confirmed, check whether your reading missed the trine, transformations and time layers','If it still does not fit, keep the question and change angle, neither forcing nor rejecting carelessly'],
 cnMis:['不查排盘就怪命理不准，常是历法时辰输入错了','硬把盘往现实套，把不像的地方也强行解释','因一处不符就频繁换盘、全盘否定，永远对不上'],
 enMis:['Blaming the system without checking the casting, often over a wrong calendar or time input','Forcing the chart onto reality and explaining away what does not fit','Switching charts and rejecting everything over one mismatch, so it never aligns'],
 cnClose:'盘和现实对不上，多半是一次系统排查能解决的问题。先查排盘、再查读法、用大事定盘，你会发现多数「不准」其实是没读对。',
 enClose:'A chart not matching reality is usually solvable through systematic checking. Check the casting, then the reading, and rectify with major events, and you will find most inaccuracy is actually a misread.'},

{cat:'kanpan',slug:'ziwei-kanpan-ruhe-lianpan-tigao',focus:'练盘提高',focusEn:'how to practice reading charts to improve',
 cnT:'紫微怎么练盘才会进步：用「先断后验」建立自己的反馈闭环',
 enT:'How to Practice Zi Wei to Improve: Build a Feedback Loop by Judging First, Verifying Later',
 cnD:'看懂理论不等于会读盘，真正提高靠刻意练习：先拿自己或熟人的盘，在不知道结果前按方法写下判断，再用后来发生的事对照打分，看错在哪、漏了什么。关键是大量看、及时验、反复复盘，并把每个判断连回星曜、宫位与四化的依据，而不是凭感觉断。',
 enD:'Understanding theory is not the same as reading a chart, and real improvement comes from deliberate practice: take your own or a familiar chart, write judgments by method before knowing the outcome, then compare with what later happens and score where you were wrong or missed something. The key is reading widely, verifying promptly and reviewing repeatedly, linking every judgment back to stars, palaces and transformations rather than judging by feeling.',
 cnL:'很多人背了一堆星性却不会看盘，缺的不是知识而是「断—验—复盘」的练习量，方法和学骑车一样，得自己上手。',
 enL:'Many people memorize star natures yet cannot read a chart; what is missing is not knowledge but the volume of judging, verifying and reviewing, and like learning to ride, it must be done hands-on.',
 cnA:'这个问题在问：用什么方法练盘提高最快。要先理解能力来自反馈闭环，再定可重复的练习流程。',
 enA:'The question is what practice method improves you fastest. Understand that ability comes from a feedback loop, then set a repeatable routine.',
 cnLog:['只读理论不练，知识是散的；只有在具体盘上判断、再被现实验证，星性组合才会真正变成你的。','「先断后验」很关键：结果已知后再解释容易事后诸葛，练习时务必先写预测、标依据。','复盘看错的地方，区分是排盘错、漏看三方四化，还是权重判断错，并据此调整读法。','用自己和亲近的人盘起步（信息全、易验证），积累后再看陌生盘，长期靠量和反馈堆出判断力。'],
 enLog:['Reading theory without practice leaves knowledge scattered; only judging on a real chart and being verified by reality makes star natures and combinations truly yours.','Judging first and verifying later matters: explaining after the result is hindsight, so in practice always write the prediction and mark your basis first.','Review what you got wrong, distinguishing a casting error, a missed trine or transformation, or a weight misjudgment, and adjust your reading accordingly.','Start with your own and close people’s charts, where information is full and verification easy, then move to unfamiliar charts, building judgment over time through volume and feedback.'],
 cnStep:['先选一个信息完整、方便验证的盘（自己或熟人）','不看结果，按宫位、星曜、四化方法写下几条具体判断和依据','给判断设定可验证的时间点和明确标准，避免模糊两可','到时间用事实逐条对照，记下对、错和拿不准的','针对错的项复盘，找出是漏看、误判权重还是排盘问题','定期重复、逐步增加陌生盘与复杂议题，积累自己的案例库'],
 enStep:['First choose a chart with complete information and easy verification, your own or a familiar person’s','Without seeing the result, write concrete judgments and their basis using palaces, stars and transformations','Set a verifiable time and clear standard for each judgment to avoid ambiguity','At that time, compare with facts item by item and note what was right, wrong or uncertain','Review the wrong items to find whether you missed something, misjudged weight or cast wrongly','Repeat regularly, gradually adding unfamiliar charts and complex topics to build your own case library'],
 cnMis:['只背书不练盘，遇到真盘还是不会断','知道结果后再解释，自我感觉良好却没真正练到预测','凭感觉断、不标依据，错了也无法复盘改进'],
 enMis:['Memorizing without practice, still unable to judge a real chart','Explaining after knowing the result and feeling capable without truly practicing prediction','Judging by feeling without marking the basis, unable to review and improve when wrong'],
 cnClose:'练盘是把理论变能力的唯一捷径，方法就是「先断、后验、再复盘」。坚持一段时间，你会明显感到看盘越来越有底气。',
 enClose:'Practice is the only shortcut from theory to ability, and the method is judge, verify, then review. Keeping at it, you will clearly feel more grounded reading charts.'},

{cat:'geju',slug:'ziwei-riruo-jiaming-geju',focus:'日月夹命',focusEn:'the Sun and Moon framing the Life Palace',
 cnT:'紫微格局：日月夹命，明暗两方面资源都来扶你的人怎么走得稳',
 enT:'The Sun-and-Moon Framing Pattern: When Light and Shadow Both Support You, Walking Steadily',
 cnD:'日月夹命指太阳、太阴分别在命宫两侧（父母宫与兄弟宫）夹拱，主明暗、内外、前后台资源都来相济，通常助力多、眼界宽、遇事有人帮。但夹宫也要看太阳太阴亮度、有无煞忌同夹，若夹的是落陷星或空劫，助力会打折；格局是底色不是保证书，仍要配合三方四正与后天行动。',
 enD:'Sun-and-Moon framing means the Sun and Moon flank the Life Palace from the Parents and Siblings palaces, bringing both visible and hidden, inner and outer, front-stage and back-stage support, usually meaning more help, broad perspective and people to assist. Yet the framing also depends on the stars’ brightness and whether malefics and Ji frame it too; fallen stars or voids discount the help. A pattern is a baseline, not a guarantee, and still combines with the triple-direction and later action.',
 cnL:'命宫被日月一左一右夹着，常是一种「资源人缘都不缺、关键时候总有人搭手」的结构，只是仍要看夹来的星亮不亮、干不干净。',
 enL:'With the Sun and Moon flanking the Life Palace, it is often a structure with no lack of resources and rapport and someone to help at key moments, though one must still see whether the framing stars are bright and clean.',
 cnA:'这个问题在问：日月夹命成不成立、好在哪里。要先确认太阳太阴确实在命宫两侧，再看亮度与夹宫有无煞忌。',
 enA:'The question is whether Sun-and-Moon framing holds and where it helps. First confirm the Sun and Moon truly flank the Life Palace, then check brightness and whether malefics and Ji frame it.',
 cnLog:['夹宫是命宫两侧（兄弟宫、父母宫）共同作用，日月夹命即一明一暗、一外一内两相扶持。','太阳主外、主显、主贵人与公共面，太阴主内、主藏、主家宅与细腻，两者夹命则资源面较全。','成格要日月庙旺、不逢煞忌空劫；若落陷或被羊陀火铃夹住，助力打折、反多牵扯。','格局只给倾向，最终仍以命宫三方四正与四化、大限为主断，不能见夹就夸大好结果。'],
 enLog:['Framing is the combined effect of the two palaces beside Life, Siblings and Parents, and Sun-and-Moon framing means one visible and one hidden, one outer and one inner support.','The Sun governs the outer, visible, benefactor and public side while the Moon governs the inner, stored, home and refined side, and framing Life gives a fuller range of resources.','To hold, the Sun and Moon must be bright without malefics, Ji or voids; if fallen or framed by Qing Yang, Tuo Luo, Mars or the Bell, help is discounted and entanglement rises.','A pattern only gives a tendency, and the final verdict still rests on Life’s triple-direction, transformations and decade, so one should not exaggerate the result from framing alone.'],
 cnStep:['先定位命宫，检查两侧兄弟宫、父母宫分别是哪颗主星','确认一侧太阳、一侧太阴，构成日月夹命','查日月各自亮度，落陷则格局减分','看两个夹宫有无煞星、化忌、空劫同度','再合命宫三方四正与四化，判断整体强弱','据格局倾向安排人脉资源，但不把结果当必然'],
 enStep:['First locate the Life Palace and check which major stars sit in the two flanking palaces, Siblings and Parents','Confirm the Sun on one side and the Moon on the other, forming the framing','Check each star’s brightness, as fallen stars reduce the pattern','Look for malefics, Hua Ji or voids in the two framing palaces','Then open Life’s triple-direction and transformations to judge overall strength','Arrange networks and resources by the tendency but do not treat the result as certain'],
 cnMis:['见命宫两侧有星就当日月夹命，没先确认是太阳太阴','忽略亮度与煞忌，把落陷受夹也说成大吉','拿一个格局当保证书，不看三方与后天努力'],
 enMis:['Taking any flanking stars as Sun-and-Moon framing without first confirming they are the Sun and Moon','Ignoring brightness and malefics and calling fallen framing a great fortune','Treating a pattern as a guarantee without reading the trine and later effort'],
 cnClose:'日月夹命给的是明暗资源相扶的好底色。把成格条件看清、把三方四化接上，这层助力才能真正变成遇事有人帮的稳，而不是虚名。',
 enClose:'Sun-and-Moon framing gives a strong baseline of visible and hidden support. Checking the conditions and connecting the trine and transformations lets that help truly become reliable assistance rather than an empty name.'},

{cat:'geju',slug:'ziwei-zuoyou-tonggong-geju',focus:'左辅右弼同宫',focusEn:'Zuo Fu and You Bi sharing a palace',
 cnT:'紫微格局：左辅右弼同宫，助力班底强的人怎么不变成依赖',
 enT:'The Zuo Fu-You Bi Pattern: Strong Support, Without Turning It Into Dependence',
 cnD:'左辅右弼是一对主协调、助力与接班班底的辅星，同宫或会照命宫时，主一生易得人帮、善协调、适合带团队，遇事有人承接。但辅星要依附主星才有力，若主星弱、又只见辅弼，容易变成依赖他人、自己拿不定主意；关键是把别人的助力接到自己主心骨上，而不是等别人安排。',
 enD:'Zuo Fu and You Bi are a pair of assistant stars governing coordination, help and a supporting team; sharing or meeting the Life Palace means help comes easily, coordination is strong and team leadership suits you, with people to take things on. But assistant stars need a major star to be effective, and if the major star is weak with only the pair, one easily depends on others and cannot decide. The key is connecting others’ help to your own backbone rather than waiting to be arranged for.',
 cnL:'辅弼会聚的盘常给人「好人缘、遇事有人搭手」的感觉，带团队做协调特别顺，只是太习惯被帮，反而容易少了主张。',
 enL:'Charts with the pair meeting give a sense of good rapport and help, making teams and coordination especially smooth, but being too used to help can reduce your own initiative.',
 cnA:'这个问题在问：辅弼同宫好在哪、要防什么。要先理解辅星是「助力而非主力」，再看它们依附的主星强不强。',
 enA:'The question is where the pair helps and what to guard. Understand that assistant stars are support rather than the main force, then see whether the major star they attach to is strong.',
 cnLog:['左辅右弼成对，主协调、包容、助力与班底，会聚命宫则一生多助、善安排人事。','辅星本身不主大局，必须依附主星：主星强则助力用成事业，主星弱则易依赖、随人。','同宫力量比单见、会照更集中，但仍要看有无煞忌同度，以及三方是否接得住。','格局功课是「借力之外有主张」：感谢并善用别人帮衬，同时练自己拍板的能力。'],
 enLog:['Zuo Fu and You Bi as a pair govern coordination, tolerance, help and a team, and meeting Life means much support and skill at arranging people.','Assistant stars do not set the big picture themselves and must attach to a major star: a strong star turns help into career, a weak star brings dependence and drifting.','Sharing a palace concentrates force more than meeting alone, but one still checks for malefics and Ji and whether the trine supports it.','The pattern’s lesson is initiative beyond borrowed help: appreciate and use others’ support while building your own ability to decide.'],
 cnStep:['先在盘上找到左辅右弼，确认是同宫、会照还是单见','看它们依附的主星是哪颗、亮度与强弱如何','合起命宫三方四正，判断助力能不能被用实','检查辅弼所在宫有无煞星、化忌同度','用好协调与班底长处，同时刻意练习自己拿主意','结合大限看哪阶段助力最旺，安排团队与接班'],
 enStep:['First find Zuo Fu and You Bi on the chart and confirm whether they share, meet or appear alone','See which major star they attach to and how bright and strong it is','Open Life’s triple-direction to judge whether the help can be made real','Check whether malefics or Hua Ji share the pair’s palace','Use coordination and team strengths while deliberately practicing your own decisions','Read the decade to see which stage brings the most help and arrange the team and succession'],
 cnMis:['见辅弼就以为万事有人帮、自己不用强','忽略主星强弱，主星弱时把助力变依赖','只享受协调的顺、不练拍板能力，关键时刻没主张'],
 enMis:['Assuming the pair means everything is handled without needing to be strong yourself','Ignoring the major star’s strength and turning help into dependence when it is weak','Only enjoying smooth coordination without practicing decisions, lacking initiative at key moments'],
 cnClose:'左辅右弼同宫给的是难得的班底与助力。把它接到强主星和自己主张上，别人的帮衬才会加成你的事业，而不是让你越靠越软。',
 enClose:'The pair sharing a palace gives a rare supporting team. Connecting it to a strong major star and your own initiative lets others’ help add to your career rather than making you softer with reliance.'},

{cat:'geju',slug:'ziwei-sizheng-tonglin-geju',focus:'四正同临',focusEn:'stars aligned across all four directions',
 cnT:'紫微格局：四正同临，本宫与三方对宫一齐得力的饱满结构',
 enT:'The Four-Direction Alignment: A Full Structure With the Home, Trine and Opposite All Strong',
 cnD:'四正同临指本宫连同对宫、两个三合宫星曜一齐得地、吉多煞少，主体格局饱满、资源执行牵引互相呼应，通常是较稳结构。但成格要看四个位置净组合，不能只数吉星数量，若对宫或三方落陷、见化忌煞星，表面齐美也会破；重点是整体能否形成合力。',
 enD:'Four-direction alignment means the home palace together with its opposite and two trine palaces are all well-placed with many auspicious and few malefic stars, giving a full pattern where resources, execution and pull answer one another, usually a steady structure. But holding depends on the net combination of all four positions, not just counting auspicious stars; if the opposite or trine is fallen with Ji and malefics, the apparent fullness breaks. The point is whether the whole forms joint force.',
 cnL:'四正同临的盘读起来很「整」：本宫有人、对宫有牵引、三方有资源，四头一起得力，事情容易成，只是仍要逐宫看清有没有藏着的破。',
 enL:'A four-direction chart reads as complete: the home has the person, the opposite has pull, the trine has resources, and all four work together so things tend to succeed, though one still reads each palace for hidden breaks.',
 cnA:'这个问题在问：四正同临怎么算成格、怎么判断饱满。要把四个位置星曜与四化一起列出，看净效果，而不是见几颗吉星就套格。',
 enA:'The question is how four-direction alignment holds and how to judge fullness. List the stars and transformations of all four positions and read the net effect rather than applying the pattern from a few auspicious stars.',
 cnLog:['三方四正四个位置共同构成一个宫位的完整班底，四正同临即四头星曜一齐得地、彼此呼应。','本宫主核心、对宫主牵引、两个三合宫主资源与执行，四者皆稳才是真饱满，缺一便有短板。','成格重净组合：吉星虽多，若被一颗化忌或落陷煞星冲破，格局就打折，不能只看表面齐整。','格局给的是「容易形成合力」的倾向，最终成败仍看四化引动与大限流年，并靠行动落实。'],
 enLog:['The four positions of the triple-direction form a palace’s complete cast, and four-direction alignment means all four are well-placed and answer one another.','The home governs the core, the opposite the pull, and the two trine palaces resources and execution, and all four steady is true fullness, with any missing one a weak point.','Holding rests on the net combination: many auspicious stars still get discounted if one Hua Ji or fallen malefic breaks through, so one should not look only at surface fullness.','The pattern gives a tendency to form joint force, while final success still depends on transformation activation, the decade and year, and real action.'],
 cnStep:['先锁定要判断的宫位，列出本宫、对宫、两个三合宫全部主星','逐宫查星曜亮度，标出得地与落陷','数四个位置吉星、煞星与四化，先看净组合','检查有没有化忌或落陷煞星冲破齐美','四头皆稳才算四正同临，据此判断格局高低','结合大限流年看合力何时被引动，再安排行动'],
 enStep:['First lock the palace to judge and list all major stars in the home, opposite and two trine palaces','Check star brightness palace by palace, marking well-placed and fallen','Count auspicious stars, malefics and transformations across the four and read the net combination','Check whether Hua Ji or a fallen malefic breaks the fullness','Only with all four steady is it four-direction alignment, judging the pattern’s level accordingly','Read the decade and year to see when joint force activates, then arrange action'],
 cnMis:['数到几颗吉星就判成格，没看对宫三方是否落陷','忽略一颗化忌冲破的力量，把破局当饱满','把格局当结果，不看四化时间层与实际行动'],
 enMis:['Judging the pattern from a few auspicious stars without seeing whether the opposite and trine are fallen','Ignoring the force of one breaking Hua Ji and taking a broken pattern as full','Taking the pattern as a result without reading the transformation timing and real action'],
 cnClose:'四正同临是一种四头合力的饱满结构。把净组合看清、把破点排除、再接到时间层，这股合力才会真正把事推成。',
 enClose:'Four-direction alignment is a full structure of joint force across four positions. Reading the net combination, excluding breaks and connecting to the timing layers is what lets that force truly push things through.'},

{cat:'gongwei',slug:'ziwei-gongwei-qiangruo-ruhe-panduan',focus:'宫位强弱判断',focusEn:'judging palace strength',
 cnT:'紫微十二宫的强弱怎么判断：不看单颗星，看净组合、四化与夹宫',
 enT:'How to Judge the Strength of the Twelve Palaces: Not One Star, but Net Combination, Transformations and Framing',
 cnD:'判断一个宫位强不强，不能只看有没有吉星或主星亮不亮，要把三方四正星曜净组合、生年四化有没有落进来、两侧夹宫是吉是凶合起来看：吉星会聚、四化引动、夹宫干净才算真有力。强弱不是固定的，大限流年引动时会变化；它描述这一领域的底气，不直接等于吉凶结果。',
 enD:'Judging a palace’s strength is not just whether it has auspicious stars or a bright major star; combine the net stars of its triple-direction, whether the natal transformations land there, and whether the two flanking palaces are auspicious or harsh: auspicious meetings, transformation activation and clean framing make true force. Strength is not fixed and shifts as the decade and year activate it. It describes grounding in that field rather than directly equaling a good or bad result.',
 cnL:'很多人判断宫位强弱只盯本宫一颗星，其实一宫底气藏在它的三方、四化和两侧夹宫里，合起来才看得准。',
 enL:'Many people judge palace strength by one star in the home palace, but the grounding hides in its trine, transformations and flanking palaces, and only combining them reads accurately.',
 cnA:'这个问题在问：按什么标准判断宫位强弱。要先理解本宫只是中心、力量来自周围网络，再逐项看。',
 enA:'The question is the standard for judging palace strength. Understand that the home palace is only the center and force comes from the surrounding network, then read item by item.',
 cnLog:['本宫主星与亮度是第一层，但单星再强，三方四正没人接应也会虚。','三方四正净组合是主体：吉星会聚、煞星少而有制，这一宫才稳。','生年禄权科忌落不落在本宫及其三方，决定它有没有被先天能量加强或套住。','两侧夹宫也参与：吉夹则助、凶夹则损；强弱还随大限流年引动变化，不是终身定值。'],
 enLog:['The home major star and brightness are the first layer, but even a strong single star is hollow if the triple-direction offers no support.','The net combination of the triple-direction is the main body: auspicious meetings and few, controlled malefics make the palace steady.','Whether natal Lu, Quan, Ke and Ji land in the home and its trine decides whether innate energy strengthens or ties it.','The two flanking palaces also take part: auspicious framing helps and harsh framing harms; strength also shifts with decade and year activation and is not fixed for life.'],
 cnStep:['先锁定要判断的宫位，看本宫主星与亮度','拉三方四正，逐宫列星曜，算吉星煞星净效果','看生年四化有没有落在本宫或三方','检查两侧夹宫是吉夹还是凶夹','把本宫、三方、四化、夹宫合起来，定这一宫强弱','再叠大限流年，看这领域在什么阶段被加强或削弱'],
 enStep:['First lock the palace to judge and read its major star and brightness','Pull the triple-direction, list stars palace by palace and compute the net effect of auspicious and malefic stars','See whether the natal transformations land in the home or its trine','Check whether the flanking palaces frame it auspiciously or harshly','Combine home, trine, transformations and framing to set the palace’s strength','Then layer the decade and year to see when this field is strengthened or weakened'],
 cnMis:['只凭本宫一颗星或亮度判强弱','忽略四化与夹宫，把表面有吉星的宫当稳','把强弱当终身固定，不看运限引动的变化'],
 enMis:['Judging strength from one home star or brightness alone','Ignoring transformations and framing and taking a surface-auspicious palace as steady','Treating strength as fixed for life without seeing shifts from cycle activation'],
 cnClose:'判断宫位强弱是一张网络活：本宫、三方四正、四化、夹宫缺一不可。把这几层合起来，你才知道自己在哪个领域真正有底气。',
 enClose:'Judging palace strength is network work: the home, triple-direction, transformations and framing all matter. Combining these layers tells you in which field you truly have grounding.'}
];
