// 2026-10-05 调研驱动 第1组：流年剩余神煞 8篇（大耗/伏兵/六合/贵神/将军/喜神/灾煞/亡神）
module.exports=[
{cat:'liunian',slug:'ziwei-liunian-dahao-ruhe-kan',focus:'流年大耗',focusEn:'the year when Da Hao (Great Expenditure) appears',
 cnT:'流年大耗怎么看：大破财年先守后耗，把被动损变成主动花',enT:'When Da Hao Appears: Guard First in a Major-Spending Year',
 cnD:'大耗主大额支出、投资亏损与意外开销，这一年钱容易大进大出；宜降低杠杆、回避高风险投资和大额借出，用计划内的必要支出主动应耗。',
 enD:'Da Hao governs large expenses, investment losses and unexpected bills in a year of big cash swings. Cut leverage, avoid high-risk bets and large loans, and meet the energy with planned, necessary spending.',
 cnL:'大耗不是世界末日，更像一年里财务的「泄洪口」，看清它在哪、提前留蓄洪区，水再大也冲不垮你。',
 enL:'Da Hao is not the end of the world; it is more like a spillway in your finances. See where it sits and reserve a holding basin, and even a large flow cannot break you.',
 cnA:'有人逢大耗年投资被套、借钱收不回，就怪运气差，其实真正要问的是：在一个本就容易大额流出的年份，自己有没有提前收缩、留足缓冲。',
 enA:'Some people face failed investments and unpaid loans in a Da Hao year and blame luck. The real question is whether, in a year prone to large outflows, they tightened early and kept enough buffer.',
 cnLog:['大耗属岁前神煞，主大笔金钱散失、物资损耗与大额支出，应事多在房子、车子、大单、大病与担保上。','它是「放大器」而非凭空生灾：本命财库稳，大耗多为大进大出；本命财库虚，才容易一泄难收。','大耗永与岁建对冲，逢煞聚、空劫同照时损耗更重，逢禄会、吉星拱照则进多出少、可补回。','流年大耗只主一年节奏，长期财富格局仍看本命财帛、田宅与大限，不据此另断贫富。'],
 enLog:['Da Hao is an annual sign governing large money loss, material wear and big expenses, often showing up in property, cars, large contracts, major illness and guarantees.','It is an amplifier rather than a source of disaster: with a stable natal treasury it means big-in big-out, while a weak treasury lets the outflow run unchecked.','It always sits opposite the year ruler; with malefics or emptiness the loss deepens, while auspicious stars and Hua Lu bring more in than out.','It sets only one year rhythm; long-term wealth still rests on the natal Wealth and Property palaces and the decade limit, not a second verdict.'],
 cnStep:['先定位流年大耗落在本命哪个宫位，定这一年大额支出会出在哪个领域','看该宫三方四正与本命财库，分清被放大的是实力还是漏洞','该年主动降杠杆，高风险投资、投机与大额借出一律缓一缓','用「计划内的必要支出」主动应耗，如早就该买的设备、该做的维修','留足应急资金，大额合同与担保逐条看清条款再签','年底复盘哪些是主动花、哪些是被动损，校准下一年的预算'],
 enStep:['Locate which natal palace Da Hao falls in to see which area faces big spending this year','Read that palace triple-direction and the natal treasury to see whether strength or a weak spot is amplified','Reduce leverage this year and postpone high-risk bets, speculation and large personal loans','Meet the energy with planned necessary spending, such as equipment or repairs already due','Keep an emergency fund and review every large contract and guarantee clause before signing','At year-end separate planned spending from passive loss and recalibrate the budget'],
 cnMis:['把大耗年直接当灾年，什么钱都不敢花、机会也错过','以为大耗人人一样，不看本命财库与三方净组合就自我恐吓','只看流年大耗一层，不回到本命和大限就下长期结论'],
 enMis:['Treating a Da Hao year as pure disaster and daring to spend on anything, missing openings too','Assuming Da Hao affects everyone identically without reading the natal treasury and triple-direction','Reading only the annual Da Hao and drawing long-term conclusions without the natal chart and decade'],
 cnClose:'大耗年的功课是「先守后耗」。把杠杆降下来、把缓冲留出来，再用计划内的花替代计划外的损，这一年反而能把财务练得更稳。',
 enClose:'A Da Hao year teaches guarding before spending. Lower leverage, keep a buffer and replace unplanned loss with planned spending, and the year leaves your finances steadier.'},

{cat:'liunian',slug:'ziwei-liunian-fubing-ruhe-kan',focus:'流年伏兵',focusEn:'the year when Fu Bing (Hidden Troops) appears',
 cnT:'流年伏兵怎么看：事情卡在暗处，把话摊开就少踩坑',enT:'When Fu Bing Appears: Things Stall in the Dark; Bring Them Into the Open',
 cnD:'伏兵主暗中阻碍、拖延、隐性口舌与临门生变，这一年麻烦多藏在看不见处；宜把约定写清楚、流程走明、多核对，别靠口头和侥幸。',
 enD:'Fu Bing governs hidden obstacles, delays, quiet disputes and last-minute changes, with trouble concealed from view. Put agreements in writing, keep processes transparent and double-check rather than relying on words or hope.',
 cnL:'伏兵不是明刀明枪的敌人，更像路上没盖的井，平时看不见，踩上去才知道，靠的是提前探路和照明。',
 enL:'Fu Bing is not an open enemy; it is more like an uncovered pit on the road, invisible until you step in it, so the answer is lighting the way and checking ahead.',
 cnA:'有人这一年总遇到事情临到签字才出岔、合作方临时变卦，就怪小人，其实问题多在前期没把分工、条款和退路讲明白，给暗处留了空间。',
 enA:'Some face last-minute breakdowns and partners changing terms and blame bad actors, when the issue is usually that roles, clauses and exit terms were never made clear, leaving room in the dark.',
 cnLog:['伏兵属博士神煞体系，主埋伏、阻滞、暗耗与口舌，应事多为拖延、卡流程、信息不对称与临门生变。','它的特点是「不透明」，解法在流程：白纸黑字、节点确认、留痕留底，比事后补救省力。','伏兵逢化科、吉星会照，暗处有人提醒、容易化解；逢煞聚、化忌则暗损缠身、反复返工。','重要约定这一年尤其要走明路，以专业律师、正规途径和书面合同为准。'],
 enLog:['Fu Bing belongs to the Bo Shi sign system, governing ambush, blockage, hidden drain and disputes, showing delays, stuck processes, asymmetric information and last-minute change.','Its trait is opacity, so process is the answer: writing, checkpoint confirmation and records cost less than fixing things afterward.','With Hua Ke and auspicious stars someone flags the hidden issue; with malefics and obstruction the drain lingers and work repeats.','Important agreements this year especially need the open route, relying on a qualified lawyer, proper channels and a written contract.'],
 cnStep:['先定位伏兵落在哪个宫位，定哪类事这一年容易卡在暗处','重要约定一律书面化，分工、节点、金额、退路一次写清','每个关键节点主动确认，不默认「对方应该知道」','资料、数据、合同条款做二次核对，防信息差和疏漏','感觉事有蹊跷就停下来问清楚，不带着侥幸往前推','把已踩的坑记下来，补成下一次的检查清单'],
 enStep:['Locate which palace Fu Bing falls in to see which affairs tend to stall in the dark','Put important agreements in writing with roles, deadlines, amounts and exit terms clear','Confirm each key checkpoint actively rather than assuming the other side knows','Double-check data, figures and contract clauses to prevent information gaps','When something feels off, pause and clarify rather than pushing on with hope','Record each pitfall and turn it into a checklist for next time'],
 cnMis:['一出问题就归罪小人，不反省流程和约定是否清楚','只凭口头承诺、不留书面，把暗处全留给运气','把伏兵年的所有拖延都当针对自己，情绪先于事实'],
 enMis:['Blaming bad actors for every problem without examining whether the process and terms were clear','Relying on spoken promises with nothing written, leaving the dark to chance','Taking every delay personally and letting emotion precede facts'],
 cnClose:'伏兵年的功课是「把暗处照亮」。把约定写全、把流程走明、把核对做在前，埋伏再深也很难真正绊住你。',
 enClose:'A Fu Bing year teaches lighting the dark. Write complete agreements, keep processes open and check early, and even a deep ambush struggles to trip you.'},

{cat:'liunian',slug:'ziwei-liunian-liuhe-ruhe-kan',focus:'流年六合',focusEn:'the year when Liu He (Six Harmonies) appears',
 cnT:'流年六合怎么看：和合撮合的一年，利谈判结盟，仍要守边界',enT:'When Liu He Appears: A Year of Harmony and Matchmaking, Favoring Talks and Alliances',
 cnD:'六合主人缘和合、合作撮合、谈判与说媒，这一年关系容易谈拢、阻力偏小；但和合靠的是把条件摆公平，若逢煞忌或一味迁就，合作也会埋雷。',
 enD:'Liu He governs harmony, matchmaking, negotiation and alliances, making relationships easier to agree on and resistance lighter. Yet harmony rests on fair terms; with malefics or one-sided concessions, a deal plants hidden problems.',
 cnL:'六合像一年里的「和事佬」，它当值时人与人之间容易对上话，可和气得建立在规则上，否则只是把分歧往后拖。',
 enL:'Liu He is like the year peacemaker; when it presides people find it easier to talk, but goodwill must rest on rules or it merely postpones disagreement.',
 cnA:'有人逢六合年谈合作、处关系特别顺，就以为万事大吉，结果事后翻账，问题不在合不来，而在当时只图和气、没把权责和利益讲清楚。',
 enA:'Some find deals and relationships unusually smooth in a Liu He year and assume all is well, then dispute the accounts later; the issue was not incompatibility but prizing goodwill over clear rights and shares.',
 cnLog:['六合主和合、撮合与契约的顺利达成，常见于谈判顺、说媒成、旧怨和解的年份。','它利「谈得拢」但不保证「处得久」，公平条款、对等付出才是合作能走下去的基础。','六合逢煞忌同宫或对冲，容易表面和合、内里生隙，表现为当时点头、事后反悔。','涉及合作、婚约与借贷，仍要以专业律师、正规途径和书面合同为准。'],
 enLog:['Liu He governs harmony, matchmaking and the smooth reaching of agreements, often showing easy negotiations, successful introductions and reconciled grudges.','It favors agreement but not durability; fair terms and equal commitment are what let cooperation last.','With malefics or obstruction in the same or opposite palace, harmony stays on the surface while gaps form, showing nods at the time and regret later.','For partnerships, marriage promises and loans, rely on a qualified lawyer, proper channels and a written contract.'],
 cnStep:['先定位六合落在哪个宫位，定哪类关系或合作这一年最易谈拢','借顺风把重要谈判、和解与结盟安排在这一年','谈之前先把各自的权责、利益和退出条件列清楚','和谈中对事不对人，公平比一时的客气更重要','口头达成后立刻落到书面，不让默契替代条款','逢对方过度迁就或条款含糊时多问一句，防埋暗雷'],
 enStep:['Locate which palace Liu He falls in to see which relationships or deals agree most easily this year','Use the tailwind to schedule important negotiations, reconciliations and alliances','Before talking, list each side rights, benefits and exit terms','Keep talks issue-focused; fairness matters more than momentary politeness','Turn spoken agreement into writing at once rather than letting understanding replace clauses','When the other side concedes too much or terms stay vague, ask more to prevent hidden problems'],
 cnMis:['把谈得拢当处得久，只图和气不立条款','逢和合就一味迁就，把公平让给面子','只看六合不看同宫煞忌，高估关系的稳固度'],
 enMis:['Taking agreement for durability and prizing goodwill over terms','Conceding everything in the name of harmony and trading fairness for face','Reading Liu He without its accompanying malefics and overestimating stability'],
 cnClose:'六合年的功课是「和而有则」。借顺风把该谈的谈成，再用公平的书面约定守住，和合才不会变成日后的疙瘩。',
 enClose:'A Liu He year teaches harmony with rules. Settle what should be settled with the tailwind and protect it with fair written terms, and harmony never becomes a later grievance.'},

{cat:'liunian',slug:'ziwei-liunian-guishen-ruhe-kan',focus:'流年贵神',focusEn:'the year when Gui Shen (Noble Spirit) appears',
 cnT:'流年贵神怎么看：贵人提携年，机会给你但不替你成事',enT:'When Gui Shen Appears: A Year of Mentors Who Open Doors, Not Do the Work',
 cnD:'贵神主贵人提携、公开机遇、功名与引荐，这一年关键时刻容易有人拉一把；但贵人给的是台阶，能不能站稳仍看实力与准备，逢煞忌则贵人缘打折。',
 enD:'Gui Shen governs mentors, public opportunities, recognition and referrals, so someone tends to help at a key moment. Yet a mentor offers a stepping stone, not the result; standing on it still depends on preparation, and malefics discount the help.',
 cnL:'贵神像一年里替你开门的人，门开了能走多远是自己的事，越有准备，贵人出现时越接得住。',
 enL:'Gui Shen is like the person who opens a door for you this year; how far you go through it is your own affair, and preparation lets you catch the moment.',
 cnA:'有人逢贵神年确实遇到提携，却因没准备好而错过，就抱怨贵人不灵，其实真正要问的是：机会来时，自己有没有把本事和心态提前备好。',
 enA:'Some do receive help in a Gui Shen year but miss it for lack of preparation and then call the mentor ineffective. The real question is whether the skill and mindset were ready when the opening came.',
 cnLog:['贵神主贵人、功名与公开机遇，应象多为长辈上司引荐、师长点拨、考核评比中有人给机会。','它提供「条件与台阶」而非自动结果，准备足、肯主动，贵人的提携才落得到实处。','贵神逢魁钺、化科会照，贵人缘更稳；逢煞聚、空劫则机缘擦肩、易成虚缘。','贵人运只主一年的外部助力，长期成败仍看本命主轴与大限。'],
 enLog:['Gui Shen governs mentors, recognition and public opportunities, often showing referrals from seniors, guidance from teachers and chances in evaluations.','It offers conditions and stepping stones, not automatic results; with preparation and initiative the help lands in reality.','With Kui Yue and Hua Ke the mentor bond is steadier; with malefics and emptiness the chance passes and becomes an empty connection.','Mentor luck sets only one year of outside help; long-term success still rests on the natal axis and decade.'],
 cnStep:['先定位贵神落在哪个宫位，定这一年哪类事易得提携','把目标和需要的引荐列清楚，机会来时有具体的承接动作','提前把本事、作品和履历备好，不让贵人无的放矢','主动向前辈、师长请教，贵人多在互动中出现','得到机会后及时反馈、把事做好，关系才走得长','逢机缘没落地时先查准备是否不足，不归咎运气'],
 enStep:['Locate which palace Gui Shen falls in to see which affairs draw support this year','List goals and the referrals needed so an opening has a concrete next step','Prepare skills, work and resume in advance so a mentor has something to point to','Ask seniors and teachers for advice; mentors tend to appear through interaction','After receiving help, follow up and deliver so the relationship lasts','When an opening does not land, first check whether preparation was lacking rather than blaming luck'],
 cnMis:['把贵人当结果，等提携自己兑现','只盼贵人却不准备本事，机会来了也接不住','把一年贵人缘误判成长期成败，不看本命大限'],
 enMis:['Treating a mentor as an outcome and waiting for support to deliver itself','Hoping for help without preparing skill, so the opening cannot be caught','Taking one year of mentor luck as long-term success without the natal chart and decade'],
 cnClose:'贵神年的功课是「把自己备好」。贵人给台阶，实力决定高度，越主动、越扎实，这一年的提携越能变成真正的台阶。',
 enClose:'A Gui Shen year teaches being ready. Mentors give the step and ability decides the height; the more proactive and solid you are, the more the support becomes a real stair.'},

{cat:'liunian',slug:'ziwei-liunian-jiangjun-ruhe-kan',focus:'流年将军',focusEn:'the year when Jiang Jun (the General) appears',
 cnT:'流年将军怎么看：威权与竞争增强，把气势用在带队而非争胜',enT:'When Jiang Jun Appears: Authority and Competition Rise; Lead, Do Not Just Win',
 cnD:'将军属博士神煞，主威权、竞争、执行与带队伍的气势，这一年个人魄力强、容易被推到负责位置；关键是把锋芒对准目标，防过刚、争强与听不进意见。',
 enD:'Jiang Jun is a Bo Shi sign governing authority, competition, execution and the bearing to lead, so personal drive is strong and responsibility tends to find you. Aim that edge at the goal and guard against rigidity, one-upmanship and refusing advice.',
 cnL:'将军像一年里授给你的剑，能破局也能伤人，使得好是带队的将才，使不好是处处争锋的孤家寡人。',
 enL:'Jiang Jun is like a sword given to you for the year, able to break a deadlock or wound others; wielded well it makes a leader, wielded poorly it makes a lone contender.',
 cnA:'有人逢将军年特别能拼、敢负责，却因太争强、不肯让步而把关系弄僵，问题不在没魄力，而在把气势都用在了「赢」上而非「成事」上。',
 enA:'Some work hard and take responsibility in a Jiang Jun year but stiffen relationships through one-upmanship and refusal to yield; the issue is not low drive but using the bearing to win rather than to deliver.',
 cnLog:['将军主威权与竞争，应象为魄力足、推进快、敢于拍板，也容易被委以带队、攻坚的任务。','它随博士体系而起，方向要先正：对事是攻坚的底气，对人过刚则易折、易孤立。','将军逢吉星、化权会照，威权有助、名实相符；逢煞聚则争强好斗、口舌增多。','它只主一年的气势与执行，长期格局仍看本命与大限。'],
 enLog:['Jiang Jun governs authority and competition, showing strong drive, fast progress and willingness to decide, often bringing leadership and hard-task roles.','It rises within the Bo Shi system, so direction must be right: toward a task it is confidence, toward people it breaks and isolates when rigid.','With auspicious stars and Hua Quan the authority helps and matches the name; with malefics it turns combative and dispute-prone.','It sets only one year of bearing and execution; long-term patterns still rest on the natal chart and decade.'],
 cnStep:['先定位将军落在哪个宫位，定这一年哪类事最需攻坚与带队','动手前先确认目标，把锋芒对准事而不是对准人','把任务排出主次，魄力优先用在关键的硬骨头','带队伍时多听意见、肯分功，不把功劳揽尽','遇分歧先讲理与目标，不为面子争一时高低','每段复盘气势有没有用过，及时收敛锋芒'],
 enStep:['Locate which palace Jiang Jun falls in to see which affairs need leadership and hard pushes this year','Confirm the goal before acting and aim the edge at the task, not the person','Rank tasks and put drive first into the key hard problems','When leading, listen and share credit rather than taking it all','In disagreement, reason around the goal instead of winning for face','After each stage review whether the bearing was overused and soften the edge'],
 cnMis:['把魄力用在处处争赢，伤了关系还误了事','过刚独断、听不进意见，把自己变成孤家寡人','把一年威权强误判成长期地位，不看本命大限'],
 enMis:['Using drive to win everywhere, hurting relationships and the task too','Staying rigid and refusing advice until isolated','Taking one year of strong authority as long-term status without the natal chart and decade'],
 cnClose:'将军年的功课是「有威而不逞强」。把魄力用在攻坚、把气度用在带队，这一年的气势才真正成就事，而不是压垮人。',
 enClose:'A Jiang Jun year teaches authority without force. Put drive into hard tasks and bearing into leadership, and the year energy accomplishes things rather than wearing people down.'},

{cat:'liunian',slug:'ziwei-liunian-xishen-ruhe-kan',focus:'流年喜神',focusEn:'the year when Xi Shen (the Joy God) appears',
 cnT:'流年喜神怎么看：喜庆舒展的一年，喜事也要主动伸手接',enT:'When Xi Shen Appears: A Year of Joy and Relief, But Happy Events Must Be Met',
 cnD:'喜神主喜庆、婚嫁添丁、心情舒展与好事开端，这一年气氛偏顺、笑容比平时多；但喜事是「条件变好」，仍要主动表态和落实，逢煞忌则喜力打折。',
 enD:'Xi Shen governs joy, weddings and births, an open heart and good beginnings, making the mood smoother and smiles more common. Yet joy means conditions improve and still needs action to become real; malefics discount it.',
 cnL:'喜神像一年里放晴的天，适合把重要的事办在阳光下，可天晴时也得出门，好事才会真正落到自己头上。',
 enL:'Xi Shen is like a stretch of clear sky in the year, suited to handling important matters in the open, but you still have to walk out into it for good things to land.',
 cnA:'有人逢喜神年心情好、机会多，却因为不主动、不表态而让喜事悄悄过去，问题不在星不灵，而在把「喜庆的气氛」当成了「已兑现的好事」。',
 enA:'Some feel good and have many chances in a Xi Shen year but let them pass through inaction; the issue is not an ineffective sign but mistaking a joyful mood for a delivered result.',
 cnLog:['喜神属博士神煞，主喜庆、婚嫁、添丁、升职庆祝与心情的舒展，应事多为好事开端、阻力偏小。','它给的是「顺的条件」而非自动的喜事，主动争取、及时表态才接得住。','喜神逢吉星、红鸾天喜会照，喜庆更稳；逢煞聚、化忌则好事多磨、喜中藏波折。','它只主一年的喜庆面，长期走向仍看本命与大限。'],
 enLog:['Xi Shen is a Bo Shi sign governing joy, weddings, births, promotion celebrations and an open mood, often showing good beginnings and low resistance.','It gives smooth conditions rather than automatic joy; pursuing and speaking up is what catches it.','With auspicious stars and the romance stars the joy is steadier; with malefics and obstruction good things need effort and hide setbacks.','It sets only the year joyful side; the long-term course still rests on the natal chart and decade.'],
 cnStep:['先定位喜神落在哪个宫位，定这一年哪类喜事最易出现','把今年想办的婚事、添丁、庆祝与新开始列成清单','对每件好事定一个主动动作和时间点，不等它自己来','借好心情修复关系、表达感谢、把心结说开','重要的新开始尽量在这一年启动，顺风好起手','逢好事多磨时不泄气，按步骤把它落实'],
 enStep:['Locate which palace Xi Shen falls in to see which joys are most likely this year','List the weddings, births, celebrations and new beginnings you want this year','Set one active step and date for each rather than waiting','Use the good mood to repair relationships, express thanks and clear grudges','Launch important new beginnings this year while the wind favors','When good things need effort, do not be deflated; carry them through step by step'],
 cnMis:['把喜庆气氛当已兑现的好事，只等不做','只看喜神不看同宫煞忌，高估顺利程度','顺了一年就误判长期，忽略本命与大限主线'],
 enMis:['Taking a joyful mood for a delivered result and only waiting','Reading Xi Shen without its accompanying malefics and overestimating smoothness','Taking one smooth year as a long-term verdict while ignoring the natal and decade main line'],
 cnClose:'喜神年的功课是「趁晴办事」。把好心情变成主动的动作，把该办的喜事办在顺风里，这一年的喜气才算真正被接住。',
 enClose:'A Xi Shen year teaches acting while the sky is clear. Turn good mood into action and handle joyful matters with the tailwind, and the year happiness is genuinely caught.'},

{cat:'liunian',slug:'ziwei-liunian-zaisha-ruhe-kan',focus:'流年灾煞',focusEn:'the year when Zai Sha (the Calamity Star) appears',
 cnT:'流年灾煞怎么看：突发意外偏急，提前排查、慢一步就少大半',enT:'When Zai Sha Appears: Sudden Mishaps Favor Caution; Inspect Early and Slow Down',
 cnD:'灾煞主突发意外、血光、自然灾害与急冲的波折，性质来得急、难预料；这一年宜把安全检查做在前、重要节点慢一步、保险留足，多数急险能避开。',
 enD:'Zai Sha governs sudden accidents, minor blood injuries, natural mishaps and abrupt disruptions that arrive fast and hard. Do safety checks early, slow at key moments and keep insurance adequate, and most sudden risks can be avoided.',
 cnL:'灾煞不像大耗那样慢慢泄，它像一阵急风暴雨，来得快去得也快，靠的是雨前修好屋、风里不赶路。',
 enL:'Unlike Da Hao which drains slowly, Zai Sha is a sudden storm that comes and goes quickly; the answer is fixing the roof before the rain and not rushing through the wind.',
 cnA:'有人这一年遇到磕碰、小伤、设备急坏，就怪倒霉，其实问题多在该检查、该慢一点的时候没做，把急险全攒到了那一刻。',
 enA:'Some face knocks, small injuries and sudden breakdowns and blame bad luck, when the issue is usually skipping the checks and the slower pace, letting sudden risk gather at that moment.',
 cnLog:['灾煞与劫煞、亡神同属一类冲星，主突发、急冲、血光与意外，应事偏急、偏短暂，类似小型的白虎。','它提醒「防急」：交通、用火用电、高风险作业与外出旅行，都要排查在前、留余量。','身体不适是倾向而非诊断，急伤急病务必以正规就医为准，不靠侥幸拖延。','灾煞只主一年的急险，不改变本命长期走向，配合吉星、保险可明显减凶。'],
 enLog:['Zai Sha belongs with Jie Sha and Wang Shen as a clash star governing sudden, abrupt events, blood and accidents that are brief, like a smaller White Tiger.','It warns against haste: traffic, fire and electricity, high-risk work and travel all need early checks and margin.','Health discomfort is a tendency, not a diagnosis; for sudden injury or illness rely on formal medical care rather than hope or delay.','It sets only one year of sudden risk and does not change the long-term natal course; auspicious stars and insurance clearly reduce it.'],
 cnStep:['先定位灾煞落在哪个宫位，定哪类事这一年易出急险','该年重要节点前留安全检查时间，不抢那一步','交通、用火用电、设备与高风险作业做一次排查','外出、旅行、运动做好防护与保险，不逞能冒险','身体有急伤急病及时正规就医，不硬扛','遇天气、路况异常就慢下来、改时间，不硬赶'],
 enStep:['Locate which palace Zai Sha falls in to see which affairs draw sudden risk this year','Leave safety-check time before key moments and do not rush that one step','Inspect traffic, fire and electricity, equipment and high-risk work once','Use protection and insurance for travel and sport rather than daring risk','Seek formal medical care promptly for sudden injury or illness instead of enduring','When weather or road conditions turn bad, slow down or reschedule rather than forcing it'],
 cnMis:['把急险当注定，不做排查也不留余量','图快逞强、安全防护嫌麻烦，把偶然攒成必然','把灾煞看成大凶，整年自我恐吓、什么都不敢做'],
 enMis:['Treating sudden risk as fixed and neither checking nor keeping margin','Rushing and skipping protection until chance turns into certainty','Taking Zai Sha as a major threat and living the year in fear, daring nothing'],
 cnClose:'灾煞年的功课是「防急、肯慢」。把排查做在风前、把脚步放慢半拍，急风暴雨的一年反而最不容易出事。',
 enClose:'A Zai Sha year teaches guarding the sudden and being willing to slow. Check before the storm and ease the pace, and the stormy year ends up the least accident-prone.'},

{cat:'liunian',slug:'ziwei-liunian-wangshen-ruhe-kan',focus:'流年亡神',focusEn:'the year when Wang Shen (the Perishing Spirit) appears',
 cnT:'流年亡神怎么看：失神与暗损，守得住心神就破不了局',enT:'When Wang Shen Appears: Losing Focus and Hidden Drain; Guard the Mind and the Plan Holds',
 cnD:'亡神主失神、暗损、精神恍惚与计划被暗中破坏，这一年容易注意力下滑、判断走样、被人钻空子；重点是规律作息、守住流程、多核对，不靠硬撑。',
 enD:'Wang Shen governs loss of focus, hidden drain, mental fog and plans quietly undermined, making attention slip and judgment waver. The focus is regular rest, disciplined process and more checks rather than forcing through.',
 cnL:'亡神不是外鬼，更像心神暂时离开了岗位，人一愣神、一松懈，漏洞和误会就顺着缝隙进来。',
 enL:'Wang Shen is not an outside ghost; it is more like the mind temporarily leaving its post, and in that lapse gaps and misunderstandings slip through.',
 cnA:'有人这一年总犯低级错、丢三落四、谈事被人牵着走，就怪状态邪，其实问题多在太累、太满、流程省了核对，把心神耗在了无关处。',
 enA:'Some make careless errors, lose things and get led in talks, then call it a strange state, when the issue is usually being over-tired and over-full and skipping checks, spending the mind on what does not matter.',
 cnLog:['亡神与劫煞、灾煞同属一类，主暗损、失神、算计与口舌，应事多为精神不集中、计划被暗中改动、合作中吃亏。','它的根在「心神不宁」，规律作息、专注一事、流程核对比事后补救省力。','亡神逢吉星、贵人会照，暗处有人提醒；逢煞聚、化忌则暗损变多、反复返工。','情绪低落、长期失眠是倾向而非诊断，必要时以正规就医和专业心理帮助为准。'],
 enLog:['Wang Shen belongs with Jie Sha and Zai Sha, governing hidden drain, loss of focus, calculation and disputes, often showing inattention, quietly altered plans and losses in cooperation.','Its root is a restless mind; regular rest, single focus and process checks cost less than fixing things afterward.','With auspicious stars and helpful people someone flags the hidden issue; with malefics and obstruction the drain grows and work repeats.','Low mood and lasting insomnia are a tendency, not a diagnosis; when needed rely on formal medical care and professional mental-health support.'],
 cnStep:['先定位亡神落在哪个宫位，定哪类事这一年易失神、出暗损','把节奏降下来、睡眠规律化，先把心神养住','重要事项减到专注的几件，不同时铺太多摊','关键资料、金额、条款做二次核对，防走神出错','合作谈判前理清底线，不被对方节奏牵着走','定期复盘哪些错源于疲劳和省流程，补上检查'],
 enStep:['Locate which palace Wang Shen falls in to see which affairs draw inattention and hidden loss this year','Slow the pace and regularize sleep to restore the mind first','Cut important matters to a focused few rather than opening too many at once','Double-check key data, amounts and clauses to prevent lapse errors','Clarify your bottom line before talks so the other side cannot lead the pace','Review which errors came from fatigue and skipped process, then add checks'],
 cnMis:['把失神当外鬼，往玄乎里解释而不调整作息','排太满、不核对，把暗损全攒到关键时候','情绪低落硬扛、不求助，把倾向拖成问题'],
 enMis:['Treating inattention as an outside force and explaining it mystically instead of resting','Scheduling too full and skipping checks until hidden loss gathers','Enduring low mood without help and letting a tendency become a problem'],
 cnClose:'亡神年的功课是「守神」。把心神养足、把流程守住、把核对做细，人不走神，再暗的损耗也找不到缝隙。',
 enClose:'A Wang Shen year teaches guarding the mind. Rest it, keep the process and check carefully; when attention holds, even hidden drain finds no opening.'}
];
