// 2026-10-05 调研驱动 第2组：2026丙午廉贞化忌逐宫深读 8篇
module.exports=[
{cat:'sihua',slug:'ziwei-2026-lianzhenhuaji-minggong',focus:'廉贞化忌在命宫',focusEn:'Lian Zhen Hua Ji in the Life Palace',
 cnT:'2026廉贞化忌在命宫：情绪打结的一年，学会就事论事',enT:'2026 Lian Zhen Hua Ji in the Life Palace: A Year of Tangled Emotions, Learned One Issue at a Time',
 cnD:'廉贞化气为囚，落命宫这一年容易钻牛角尖、自我设限、情绪一上头就冲动；重点不是压住自己，而是给情绪找出口、把人和事分开，慢慢练就事论事。',
 enD:'Lian Zhen carries the energy of confinement, and in the Life Palace this year you tend to fixate, limit yourself and react when emotion rises. The point is not suppression but finding an outlet, separating people from issues and practicing taking things one at a time.',
 cnL:'廉贞化忌在命，像心里有个解不开的小疙瘩，越较劲越紧；松一松、退一步看，反而能找到那根线头。',
 enL:'Lian Zhen Hua Ji in the Life Palace is like a small knot in the mind that tightens when you force it; easing off and stepping back reveals the loose end.',
 cnA:'有人这一年总跟自己过不去、一点小事想半天，还容易冲动表态后后悔，问题不在性格变差，而在囚星把注意力锁死在了「我对不对、行不行」上。',
 enA:'Some are hard on themselves all year, turning small matters over and over and regretting impulsive statements; the issue is not a worse temperament but the confining star locking attention on whether they are right or good enough.',
 cnLog:['廉贞主规矩、分寸与人际边界，化气为囚；化忌则把这份约束转向自己，表现为内耗、自责与想不开。','这一年情绪来得急，容易把「一件事没做好」放大成「我这个人不行」，需要刻意把事和自我分开。','廉贞也是次桃花星，化忌在命的人对关系更敏感、更怕失控，越抓越紧反而推远。','流年化忌只主一年加减分，长期性格与走向仍看本命主星与大限，不据此另断一条命。'],
 enLog:['Lian Zhen governs rules, measure and interpersonal boundaries with the energy of confinement; Hua Ji turns that constraint inward, showing self-drain, blame and fixation.','Emotions arrive quickly this year and tend to enlarge one failed task into I am a failure, so deliberately separate the issue from the self.','Lian Zhen is also a secondary romance star; with Hua Ji in the Life Palace you are more sensitive to relationships and fear losing control, yet gripping tighter pushes them away.','An annual Hua Ji sets only one year of pluses and minuses; long-term temperament still rests on the natal major stars and decade, not a second fate.'],
 cnStep:['先确认廉贞化忌是流年一层，本命性格底色并未改变','情绪上头时先停一停、不立刻表态，给冲动一个缓冲','把让自己纠结的事写下来，分清「事实」和「我的解读」','练习把话限定在具体事情上，不上升到对人的评判','给情绪固定出口，如运动、书写、与信任的人聊一聊','年底复盘哪些结被自己解开，总结一套自我松绑的方法'],
 enStep:['First confirm that Lian Zhen Hua Ji is the annual layer and the natal temperament has not changed','When emotion rises, pause before speaking and give the impulse a buffer','Write down what troubles you and separate facts from your interpretation','Practice keeping words on the concrete issue rather than judging the person','Give emotion a regular outlet such as exercise, writing or talking with someone trusted','At year-end review which knots you loosened and build a method for self-release'],
 cnMis:['把情绪压抑当成熟，结果内耗越积越重','一冲动就表态、事后又后悔，不给自己缓冲','把流年化忌当本命定局，整年自我否定'],
 enMis:['Taking suppression for maturity until the inner drain grows','Reacting at once and regretting it without any buffer','Taking the annual Hua Ji as a natal verdict and rejecting yourself all year'],
 cnClose:'廉贞化忌在命的功课是「松绑自己」。情绪来的时候肯停、肯分、肯找出口，这颗囚星反而教会你把自己和事情温柔地分开。',
 enClose:'Lian Zhen Hua Ji in the Life Palace teaches unbinding yourself. Be willing to pause, separate and find an outlet when emotion comes, and the confining star teaches you to gently part yourself from the issue.'},

{cat:'sihua',slug:'ziwei-2026-lianzhenhuaji-fuqigong',focus:'廉贞化忌在夫妻宫',focusEn:'Lian Zhen Hua Ji in the Spouse Palace',
 cnT:'2026廉贞化忌在夫妻宫：感情里的掌控与猜忌，靠坦诚和边界化解',enT:'2026 Lian Zhen Hua Ji in the Spouse Palace: Control and Suspicion in Love, Resolved by Honesty and Boundaries',
 cnD:'廉贞为次桃花、化气为囚，落夫妻宫这一年感情易纠结、掌控欲强、遇暧昧或冷战便内耗；重点是把不安说开、守住彼此边界，远离不清不楚的关系。',
 enD:'Lian Zhen is a secondary romance star with the energy of confinement, and in the Spouse Palace this year relationships tend to tangle with strong control and inner drain over ambiguity or cold silence. Speak the unease openly, keep boundaries and avoid unclear involvements.',
 cnL:'廉贞化忌在夫妻宫，像把感情攥在手里的沙，越用力留住越漏；摊开手心、彼此坦诚，反而留得住。',
 enL:'Lian Zhen Hua Ji in the Spouse Palace is like sand held in hand, the more forcefully you grip the more it slips; open the palm and be honest, and it stays.',
 cnA:'有人这一年查行踪、翻记录、一句话琢磨半天，把自己和对方都累坏，问题不在爱不爱，而在囚星把「怕失去」变成了「想控制」。',
 enA:'Some track whereabouts, reread messages and turn one sentence over for hours, exhausting both sides; the issue is not love or its absence but the confining star turning fear of loss into control.',
 cnLog:['夫妻宫写亲密关系的相处模式，廉贞化忌让关系里的规矩与安全感变得紧绷，易生猜忌与冷战。','它考验坦诚：不安、需求和底线说清楚，关系就轻；靠试探、查问和憋着，误会就重。','廉贞为次桃花，化忌逢煞聚更要防烂桃花、桃花劫与复杂多角关系，不与不清不楚的人纠缠。','流年化忌只主一年感情上的加减分，长期婚姻仍看本命夫妻宫与大限。'],
 enLog:['The Spouse Palace describes how intimacy is conducted, and Lian Zhen Hua Ji tightens the rules and sense of safety, breeding suspicion and cold silence.','It tests honesty: naming unease, needs and bottom lines keeps the relationship light, while probing and holding it in makes misunderstanding heavy.','As a secondary romance star, with gathered malefics guard against unhealthy romance and complicated triangles rather than entangling with unclear people.','An annual Hua Ji sets only one year of relationship pluses and minuses; long-term marriage still rests on the natal Spouse Palace and decade.'],
 cnStep:['先定位流年夫妻宫，看清这一年感情被引动的方式','把自己的不安和需求直接告诉对方，不靠试探和查问','约定彼此的边界，如与异性相处、沟通节奏与隐私','遇冷战先主动澄清事实，不猜、不憋、不翻旧账','远离暧昧不清的关系，不在多角纠缠里消耗自己','年底复盘关系里哪些结被坦诚解开'],
 enStep:['Locate the annual Spouse Palace and see how the relationship is activated this year','Tell your unease and needs directly rather than probing','Agree on boundaries regarding opposite-sex friendships, communication and privacy','In a cold spell, clarify facts first rather than guessing, holding it in or reopening old issues','Stay away from unclear involvements and do not drain yourself in triangles','At year-end review which knots honesty loosened'],
 cnMis:['把怕失去变成查问和控制，把对方越推越远','遇暧昧不拒绝、不表态，任由桃花劫上身','只看流年化忌就判婚姻好坏，不回本命与大限'],
 enMis:['Turning fear of loss into probing and control, pushing the partner away','Neither refusing nor naming ambiguity until unhealthy romance takes hold','Judging the marriage from the annual Hua Ji alone without the natal chart and decade'],
 cnClose:'廉贞化忌在夫妻宫的功课是「爱而不囚」。把不安说开、把边界立住、把暧昧挡在门外，感情反而在这一年变得更踏实。',
 enClose:'Lian Zhen Hua Ji in the Spouse Palace teaches loving without confining. Speak the unease, set boundaries and keep ambiguity out, and the relationship grows steadier this year.'},

{cat:'sihua',slug:'ziwei-2026-lianzhenhuaji-guanlugong',focus:'廉贞化忌在官禄宫',focusEn:'Lian Zhen Hua Ji in the Career Palace',
 cnT:'2026廉贞化忌在官禄宫：职场纠纷与职务压力，靠流程合规和留痕过关',enT:'2026 Lian Zhen Hua Ji in the Career Palace: Workplace Disputes and Role Pressure, Cleared by Compliance and Records',
 cnD:'廉贞主规矩、化气为囚，落官禄宫这一年易遇职场纠纷、被投诉举报、职务边界不清与流程卡壳；重点是按规章办事、把资料留全、沟通走正规渠道，不硬碰。',
 enD:'Lian Zhen governs rules with the energy of confinement, and in the Career Palace this year you may meet workplace disputes, complaints, unclear role boundaries and stuck processes. Follow regulations, keep complete records and use proper channels rather than forcing a clash.',
 cnL:'廉贞化忌在官禄，像工作里突然多了一道看不见的栅栏，与其翻栏硬闯，不如顺着流程把门找到、把手续补齐。',
 enL:'Lian Zhen Hua Ji in the Career Palace is like an unseen fence added at work; instead of climbing over, follow the process to find the gate and complete the paperwork.',
 cnA:'有人这一年因一句口头安排、一份没留底的文件惹上麻烦，就怪被人针对，其实问题多在没按流程走、没把证据和分工留清楚。',
 enA:'Some get into trouble over a verbal arrangement or an unfiled document and blame being targeted, when the issue is usually bypassing process and failing to keep evidence and roles clear.',
 cnLog:['官禄宫写工作姿态与职务关系，廉贞化忌让职场的规矩、考核与边界变得紧绷，易生投诉、争执与卡流程。','它考验合规：按制度办事、节点留痕、重要沟通书面化，多数纠纷能提前避开。','廉贞化忌逢煞聚，易遇小人举报、同事推责；逢化科、吉星则靠正规说明与材料化解。','涉及合同、职务与法律边界的事，以专业律师、正规途径和书面文件为准。'],
 enLog:['The Career Palace describes work style and role relationships, and Lian Zhen Hua Ji tightens rules, reviews and boundaries, breeding complaints, disputes and stuck processes.','It tests compliance: following systems, keeping checkpoint records and putting key communication in writing prevents most disputes.','With gathered malefics it brings false reports and shifted blame; with Hua Ke and auspicious stars, proper statements and materials resolve it.','For contracts, roles and legal boundaries, rely on a qualified lawyer, proper channels and written documents.'],
 cnStep:['先定位流年官禄宫，看清这一年职场压力从哪来','重要安排一律走流程、留书面，不靠口头承诺','分清自己的职责边界，不替别人签字、不揽含糊的活','资料、审批、沟通记录留存好，把证据做扎实','遇投诉或误会先按正规渠道说明，不带情绪硬顶','年底复盘哪些麻烦源于省流程，补上检查习惯'],
 enStep:['Locate the annual Career Palace and see where workplace pressure comes from this year','Put important arrangements through the process and in writing rather than verbal promises','Clarify your role boundaries and do not sign for others or take vague tasks','Keep documents, approvals and communication records so evidence is solid','For complaints or misunderstandings, explain through proper channels without emotional pushback','At year-end review which troubles came from skipping process and add the check habit'],
 cnMis:['图省事省流程、不留痕，把麻烦全攒到关键时候','被投诉就情绪化硬顶，把小事闹大','把流年职务压力当长期事业定局，不看本命大限'],
 enMis:['Skipping process and records for convenience until trouble gathers at the key moment','Answering complaints with emotion and inflating a small matter','Taking annual role pressure as a long-term career verdict without the natal chart and decade'],
 cnClose:'廉贞化忌在官禄的功课是「守规矩、走明路」。把流程做扎实、把证据留齐全，这一年的职务压力反而逼着你把职业根基打得更稳。',
 enClose:'Lian Zhen Hua Ji in the Career Palace teaches following rules and the open route. Solidify process and keep complete evidence, and the year pressure pushes you to build a steadier professional foundation.'},

{cat:'sihua',slug:'ziwei-2026-lianzhenhuaji-jiaoyougong',focus:'廉贞化忌在交友宫',focusEn:'Lian Zhen Hua Ji in the Friends Palace',
 cnT:'2026廉贞化忌在交友宫：朋友同事易拖累反目，先小人后君子',enT:'2026 Lian Zhen Hua Ji in the Friends Palace: Friends and Colleagues May Let You Down; Settle Terms First',
 cnD:'廉贞化忌落交友宫，这一年易遇朋友同事拖累、因财因情反目、合作口头说清事后翻脸；重点是把规则和账讲在前面、不碍于面子，关系反而走得长。',
 enD:'With Lian Zhen Hua Ji in the Friends Palace, friends and colleagues may let you down or fall out over money or feelings, and verbal cooperation can turn later. Put rules and accounts first rather than sparing face, and relationships last longer.',
 cnL:'廉贞化忌在交友，像一年里给朋友关系做体检，先把账和边界摆明白的人留得住，只靠义气、含糊相处的容易散。',
 enL:'Lian Zhen Hua Ji in the Friends Palace is like a checkup on friendships for the year; those with clear accounts and boundaries stay, while those relying only on vague loyalty tend to part.',
 cnA:'有人这一年替朋友担保、合伙没立字据、帮人背了锅，最后反目，问题不在交情深浅，而在该把规则讲明的时候碍于面子没讲。',
 enA:'Some guarantee for friends, partner without writing or take the blame for others and then fall out; the issue is not depth of friendship but sparing face when rules should have been named.',
 cnLog:['交友宫写朋友、同事与平辈的相处，廉贞化忌让关系里的分寸、账目与边界变得紧绷，易生误会与反目。','它考验「先明后不争」：钱、分工、退出与责任先讲清、留书面，事后才不伤感情。','廉贞化忌逢煞聚，易遇拖累、推责与因财失义；逢吉星、化科则有人调和、误会易解。','涉及合伙、借贷与担保，以专业律师、正规途径和书面合同为准。'],
 enLog:['The Friends Palace describes friends, colleagues and peers, and Lian Zhen Hua Ji tightens measure, accounts and boundaries, breeding misunderstanding and falling out.','It tests clarity before conflict: naming money, roles, exit and responsibility in writing protects the friendship later.','With gathered malefics it brings dragging feet, shifted blame and loyalty lost over money; with auspicious stars and Hua Ke someone mediates.','For partnerships, loans and guarantees, rely on a qualified lawyer, proper channels and a written contract.'],
 cnStep:['先定位流年交友宫，看清这一年哪类关系易出问题','合作、借贷、担保前先把条款和账讲清、立字据','分清情分与责任，不碍于面子答应含糊的事','帮人之前先评估自己的承受力，不替人背无限责任','遇误会先对账、对事，不带情绪翻旧账','年底梳理哪些关系经住了明算账，值得深交'],
 enStep:['Locate the annual Friends Palace and see which relationships tend to trouble this year','Before partnerships, loans and guarantees, clarify terms and accounts in writing','Separate goodwill from responsibility and do not agree to vague matters to spare face','Before helping, assess what you can bear rather than taking unlimited blame','In misunderstanding, reconcile accounts and issues first without emotional reopening','At year-end identify which relationships survived clear accounting and deserve depth'],
 cnMis:['碍于面子不立规则，事后反目伤得更深','把朋友的事当自己的无限责任，替人背锅','一出问题就归罪对方不义，不反省当初没讲清'],
 enMis:['Sparing face over rules, then falling out harder afterward','Taking a friend affairs as unlimited responsibility and bearing the blame','Blaming the other side without examining whether terms were ever clear'],
 cnClose:'廉贞化忌在交友的功课是「亲弟兄明算账」。把规则和边界讲在前面、落在纸上，这一年真正的朋友反而留得更稳。',
 enClose:'Lian Zhen Hua Ji in the Friends Palace teaches clear accounting even among close peers. Put rules and boundaries first and in writing, and genuine friends stay steadier this year.'},

{cat:'sihua',slug:'ziwei-2026-lianzhenhuaji-qianyigong',focus:'廉贞化忌在迁移宫',focusEn:'Lian Zhen Hua Ji in the Travel Palace',
 cnT:'2026廉贞化忌在迁移宫：外出多是非与磕碰，慢行、留据、防被骗',enT:'2026 Lian Zhen Hua Ji in the Travel Palace: Outside Brings Disputes and Knocks; Go Slow, Keep Records and Guard Against Fraud',
 cnD:'廉贞化忌落迁移宫，这一年外出易遇是非、磕碰、合同条款吃亏或被骗，外部环境偏紧绷；重点是行程留余量、重要约定看条款、证件票据存好，不贪小便宜。',
 enD:'With Lian Zhen Hua Ji in the Travel Palace, going outside this year may bring disputes, knocks, unfavorable contract terms or fraud as the outer environment tightens. Keep margin in plans, read key terms and secure documents rather than chasing small gains.',
 cnL:'廉贞化忌在迁移，像出门遇上逆风，走得急容易摔；放慢半拍、把路看清，反而能顺顺当当到达。',
 enL:'Lian Zhen Hua Ji in the Travel Palace is like a headwind outside, where rushing leads to falls; slow half a step and see the road, and you arrive smoothly.',
 cnA:'有人这 year 出差旅游遇纠纷、签约没细看吃亏、被人以好处诱导上当，就怪外面坏人多，其实问题多在贪快、贪小利和没留凭证。',
 enA:'Some meet disputes on trips, lose out by not reading contracts or get lured by promised benefits and blame bad people outside, when the issue is usually rushing, chasing small gains and lacking proof.',
 cnLog:['迁移宫写人进入陌生环境、面对外部规则时的状态，廉贞化忌让外部的边界、手续与是非变多，易生磕碰与纠纷。','它考验谨慎：行程留缓冲、条款看清楚、证件票据留底，多数麻烦能提前避开。','廉贞化忌逢煞聚，防交通碰撞、在外口舌与被骗；逢吉星、化科则靠正规渠道与凭证化解。','身体磕碰、急伤是倾向，必要时以正规就医为准。'],
 enLog:['The Travel Palace describes how you act in unfamiliar settings and against outside rules, and Lian Zhen Hua Ji multiplies boundaries, paperwork and disputes, bringing knocks and conflict.','It tests caution: buffer in plans, clear reading of terms and secure documents prevent most trouble.','With gathered malefics guard against traffic knocks, outside disputes and fraud; with auspicious stars and Hua Ke, proper channels and proof resolve it.','Knocks and sudden injury are a tendency; when needed rely on formal medical care.'],
 cnStep:['先定位流年迁移宫，看清这一年外出易遇哪类麻烦','行程、出差、搬迁留缓冲，不把时间排到极限','签合同、谈条件前逐条看，重点看责任与退出条款','证件、票据、聊天与转账记录留存好','不轻信来路不明的好处与「内部渠道」，防被骗','遇纠纷走正规渠道、留凭证，不私下斗气'],
 enStep:['Locate the annual Travel Palace and see which troubles going outside tends to bring this year','Keep buffer in trips and moves rather than scheduling to the limit','Before signing, read each clause, especially responsibility and exit terms','Secure documents, receipts, messages and transfer records','Do not trust unclear benefits or inside channels and guard against fraud','Handle disputes through proper channels with proof rather than private feuds'],
 cnMis:['贪快、贪小利，不留凭证、不看条款','在外遇事就硬顶或斗气，把纠纷闹大','把一年外出不顺当长期不能远行，不看本命大限'],
 enMis:['Rushing and chasing small gains without proof or reading terms','Forcing or feuding outside and inflating disputes','Taking one difficult travel year as a permanent no-travel verdict without the natal chart and decade'],
 cnClose:'廉贞化忌在迁移的功课是「外圆内有则」。把脚步放慢、把条款看清、把凭证留全，外面的逆风反而帮你走得更稳。',
 enClose:'Lian Zhen Hua Ji in the Travel Palace teaches outward flexibility with inner rules. Slow the pace, read the terms and keep proof, and the outer headwind helps you move more steadily.'},

{cat:'sihua',slug:'ziwei-2026-lianzhenhuaji-fudegong',focus:'廉贞化忌在福德宫',focusEn:'Lian Zhen Hua Ji in the Karma Palace',
 cnT:'2026廉贞化忌在福德宫：精神内耗偏重，学会给心事松绑、肯求助',enT:'2026 Lian Zhen Hua Ji in the Karma Palace: Heavier Mental Strain; Learn to Unbind Thoughts and Seek Help',
 cnD:'廉贞化忌落福德宫，这一年容易反复想、钻想不开、睡眠与情绪偏低落，心事像被锁住；重点是降低自我施压、规律作息、把困扰说出来，必要时寻求专业帮助。',
 enD:'With Lian Zhen Hua Ji in the Karma Palace, this year you tend to ruminate and fixate with lower sleep and mood, as if thoughts are locked. Reduce self-pressure, keep regular rest, speak the trouble out and seek professional support when needed.',
 cnL:'廉贞化忌在福德，像心里常年阴天，不是硬撑能放晴的；肯歇、肯说、肯求助，太阳才会慢慢出来。',
 enL:'Lian Zhen Hua Ji in the Karma Palace is like lasting overcast in the mind that forcing through cannot clear; be willing to rest, talk and seek help, and the sun gradually returns.',
 cnA:'有人这一年失眠、提不起劲、遇事往坏处想，却咬牙硬扛怕被说矫情，问题不在想太多，而在囚星把精神的出口堵住了。',
 enA:'Some lose sleep, feel low and expect the worst but grit their teeth for fear of seeming difficult; the issue is not thinking too much but the confining star blocking the mind outlet.',
 cnLog:['福德宫写一个人内心的感受、恢复力与精神状态，廉贞化忌让心思变得紧绷、爱反刍，易生低落与睡眠波动。','它考验自我松绑：降低过高的自我要求、规律作息、给情绪出口，比硬扛有效。','廉贞化忌逢煞聚，内耗更重；逢吉星、化科则想通、有人开解。','情绪低落、持续失眠是倾向而非诊断，若明显影响生活，务必以正规就医和专业心理帮助为准。'],
 enLog:['The Karma Palace describes inner feeling, resilience and mental state, and Lian Zhen Hua Ji tightens thought into rumination, bringing low mood and sleep changes.','It tests self-release: lowering excessive self-demand, regular rest and emotional outlets work better than forcing through.','With gathered malefics the inner drain deepens; with auspicious stars and Hua Ke you think it through with someone to help.','Low mood and lasting insomnia are a tendency, not a diagnosis; if they clearly affect daily life, rely on formal medical care and professional mental-health support.'],
 cnStep:['先定位流年福德宫，看清这一年精神压力的来源','把自我要求降一档，允许事情和自己都不完美','固定作息与运动，给身体和情绪稳定的节奏','把困扰向信任的人讲出来，不独自反刍','安排能让自己放松、专注的事，给心事留出口','若低落持续、影响生活，及时寻求正规就医与专业帮助'],
 enStep:['Locate the annual Karma Palace and see the source of mental pressure this year','Lower self-demand one notch and allow imperfection in things and in yourself','Fix regular rest and exercise for a steady body-and-emotion rhythm','Speak trouble out to someone trusted rather than ruminating alone','Schedule things that relax and focus you, giving thoughts an outlet','If low mood persists and affects life, seek formal medical care and professional help promptly'],
 cnMis:['咬牙硬扛、把求助当软弱，任由内耗加重','对自己提过高要求，稍不完美就自责','把流年精神低落当本命性格或定论，不看大限'],
 enMis:['Forcing through and treating help as weakness until the drain deepens','Holding excessive self-demand and blaming any imperfection','Taking annual low mood as a natal verdict without the decade limit'],
 cnClose:'廉贞化忌在福德的功课是「与自己和解」。肯松绑、肯出口、肯求助，这一年的阴天反而教会你如何真正照顾内心。',
 enClose:'Lian Zhen Hua Ji in the Karma Palace teaches making peace with yourself. Be willing to unbind, express and seek help, and the year overcast teaches you how to genuinely care for the mind.'},

{cat:'sihua',slug:'ziwei-2026-lianzhenhuaji-caibogong',focus:'廉贞化忌在财帛宫',focusEn:'Lian Zhen Hua Ji in the Wealth Palace',
 cnT:'2026廉贞化忌在财帛宫：因钱生困的一年，控杠杆、慢决策',enT:'2026 Lian Zhen Hua Ji in the Wealth Palace: A Year of Money Pressure; Control Leverage and Decide Slowly',
 cnD:'廉贞化忌落财帛宫，这一年容易因钱焦虑、投资纠结、大额支出或被套、对得失看得过重；重点是降杠杆、不碰看不懂的投机、决策留缓冲，财务以稳为主。',
 enD:'With Lian Zhen Hua Ji in the Wealth Palace, this year you may feel money anxiety, struggle with investments, face large expenses or lockups and weigh gains too heavily. Cut leverage, avoid speculation you do not understand and keep decisions buffered, prioritizing stability.',
 cnL:'廉贞化忌在财帛，像和钱较上了劲，越想一把翻回来越容易陷；退一步、慢下来、守好本金，反而不被困住。',
 enL:'Lian Zhen Hua Ji in the Wealth Palace is like locking horns with money, where trying to win it back at once sinks you deeper; step back, slow and guard principal, and you stay free.',
 cnA:'有人这一年加杠杆追涨、替人出头垫钱、或因执着不肯止损而越套越深，问题不在没财运，而在囚星把「不甘心」变成了「下重注」。',
 enA:'Some add leverage to chase gains, advance money for others or refuse to cut losses and sink deeper; the issue is not absent wealth luck but the confining star turning unwillingness to accept loss into heavier bets.',
 cnLog:['财帛宫写赚钱与花钱的方式，廉贞化忌让对钱的态度变得紧绷执着，易生焦虑、纠结与大额支出。','它考验风控：降杠杆、分散、留应急金，不碰高风险与看不懂的产品。','廉贞化忌逢煞聚、空劫，破财与被套更重；逢禄会、吉星则进多出少、可补回。','本文不构成投资建议，具体以持牌机构和正规产品说明为准。'],
 enLog:['The Wealth Palace describes how you earn and spend, and Lian Zhen Hua Ji tightens the attitude to money into fixation, bringing anxiety and large expenses.','It tests risk control: cut leverage, diversify and keep emergency funds rather than high-risk products you do not understand.','With gathered malefics and emptiness, losses and lockups deepen; with Hua Lu and auspicious stars more comes in than out.','This is not investment advice; rely on licensed institutions and the official product disclosures.'],
 cnStep:['先定位流年财帛宫，看清这一年钱上的压力从哪来','主动降杠杆，高风险、投机与大额借出缓一缓','大额支出和投资决策放几天、留缓冲，不冲动拍板','看不懂、说不清的产品一律不碰','留足应急资金，账目和合同条款看清楚','年底复盘哪些困局源于不甘心与高杠杆'],
 enStep:['Locate the annual Wealth Palace and see where money pressure comes from this year','Cut leverage and postpone high-risk speculation and large personal loans','Delay large spending and investment decisions for a few days rather than acting on impulse','Avoid any product you cannot understand or explain clearly','Keep adequate emergency funds and read accounts and contract terms','At year-end review which difficulties came from unwillingness to accept loss and high leverage'],
 cnMis:['不甘心就下重注想翻本，越套越深','把钱攥太紧、该花不花，或反过来冲动消费','把流年财务困局当长期贫富定论，不看本命大限'],
 enMis:['Placing heavier bets to win it back and sinking deeper','Gripping money too tightly, or the reverse of impulsive spending','Taking annual money trouble as a long-term wealth verdict without the natal chart and decade'],
 cnClose:'廉贞化忌在财帛的功课是「不与钱较劲」。控好杠杆、慢做决策、守好本金，这一年的财务压力反而帮你把风险管得更牢。',
 enClose:'Lian Zhen Hua Ji in the Wealth Palace teaches not locking horns with money. Control leverage, decide slowly and guard principal, and the year pressure helps you manage risk more firmly.'},

{cat:'sihua',slug:'ziwei-2026-lianzhenhuaji-tianzhaigong',focus:'廉贞化忌在田宅宫',focusEn:'Lian Zhen Hua Ji in the Property Palace',
 cnT:'2026廉贞化忌在田宅宫：家宅易生纠纷与隐患，合同看清、安全查细',enT:'2026 Lian Zhen Hua Ji in the Property Palace: Home and Property Disputes; Read Contracts and Check Safety',
 cnD:'廉贞化忌落田宅宫，这一年易遇房产合同纠纷、家中修缮电路隐患、与家人或邻里摩擦；重点是买卖租赁条款看全、水火用电检查做细、多沟通少硬碰。',
 enD:'With Lian Zhen Hua Ji in the Property Palace, this year may bring real-estate contract disputes, repair and electrical risks at home and friction with family or neighbors. Read sale and rental terms fully, check fire, water and electricity carefully and communicate rather than clash.',
 cnL:'廉贞化忌在田宅，像家里有处看不见的隐患，与其等它发作，不如提前排查、把合同和手续一次理顺。',
 enL:'Lian Zhen Hua Ji in the Property Palace is like a hidden risk at home; instead of waiting for it to surface, inspect early and put contracts and procedures in order once.',
 cnA:'有人这一年买房租房没细看条款吃亏、家中电路漏水出问题、与家人因空间和钱生隙，就怪家宅不宁，其实问题多在前期没查、没讲清。',
 enA:'Some lose out by not reading property terms, face electrical or water problems at home and fall out with family over space and money, then blame an unsettled home, when the issue was not checking and clarifying early.',
 cnLog:['田宅宫写房产、居住环境与家庭空间，廉贞化忌让家宅里的合同、边界与安全变紧，易生纠纷与隐患。','它考验细致：买卖租赁条款、产权与维修责任看清楚，水火用电、燃气设备检查在前。','廉贞化忌逢煞聚，房产纠纷、家中破财与口舌更重；逢吉星、化科则靠正规合同与沟通化解。','涉及房产交易、合同与邻里法律边界，以专业律师、正规途径和书面合同为准。'],
 enLog:['The Property Palace describes real estate, living environment and home space, and Lian Zhen Hua Ji tightens contracts, boundaries and safety, breeding disputes and hidden risk.','It tests care: read sale and rental terms, ownership and repair duties clearly, and check fire, water, electricity and gas equipment early.','With gathered malefics, property disputes, home losses and disputes deepen; with auspicious stars and Hua Ke, proper contracts and communication resolve it.','For property transactions, contracts and neighbor legal boundaries, rely on a qualified lawyer, proper channels and a written contract.'],
 cnStep:['先定位流年田宅宫，看清这一年家宅压力从哪来','买房、租房、装修前把产权、条款与维修责任看全','家中电路、燃气、水管与消防设备做一次排查','与家人、邻里先沟通边界，不硬碰、不积怨','重要交易走正规渠道、留书面，不轻信口头承诺','年底复盘哪些隐患被提前排除'],
 enStep:['Locate the annual Property Palace and see where home pressure comes from this year','Before buying, renting or renovating, read ownership, terms and repair duties fully','Inspect electrical wiring, gas, water pipes and fire equipment once','Communicate boundaries with family and neighbors rather than clashing or holding grudges','Handle key transactions through proper channels in writing rather than verbal promises','At year-end review which hidden risks were removed early'],
 cnMis:['不看条款、不留书面，房产上吃哑巴亏','忽视水火用电与燃气检查，等出问题才补救','把家宅纠纷都硬碰硬，把小摩擦积成大怨'],
 enMis:['Skipping terms and writing until losing out silently on property','Ignoring fire, water, electricity and gas checks until trouble starts','Forcing every home dispute until small friction becomes a grudge'],
 cnClose:'廉贞化忌在田宅的功课是「治家如理事」。把合同看清、把安全查细、把沟通做在前，家宅这一年反而更安稳。',
 enClose:'Lian Zhen Hua Ji in the Property Palace teaches managing home like affairs. Read contracts, check safety and communicate early, and the home steadies itself this year.'}
];
