// 2026-10-08 调研驱动 第3组：格局 7（双禄朝垣/甲第登科/文桂文华/巨机同宫/昌曲夹命/七杀朝斗/将星得地）+ 主星 1（紫微星总论）
module.exports=[
{cat:'geju',slug:'ziwei-shuanglu-chaoyuan-ge-ruhe-kan',focus:'双禄朝垣格',focusEn:'the Two Lu Facing the Origin pattern',
 cnT:'双禄朝垣格：禄存化禄三方会照，财气稳',enT:'The Two Lu Facing the Origin Pattern',
 cnD:'禄存与化禄在三方四正加会命宫，主财气厚、收入稳，不大贵即大富；但仍要左右百官拱照才贵，无吉星扶持多是富而不贵，逢煞冲破也破格。',
 enD:'When Lu Cun and Hua Lu meet the Life Palace in the triple-direction, it brings thick wealth and steady income, either rank or riches. But it still needs Zuo You and officials around for distinction; without auspicious support it is often rich without rank, and malefics break it.',
 cnL:'双禄是两颗财星一起来、财气足；但财要有人守、有名配，才成格局。',
 enL:'Two Lu are two wealth stars coming together with ample wealth; but wealth needs guardians and name to form a pattern.',
 cnA:'有人见双禄会就当大格，其实财星独旺、无百官，只主富；成格条件要看全。',
 enA:'Some see two Lu and call it great, but wealth stars alone without officials only mean riches; read conditions fully.',
 cnLog:['禄存化禄在三方会命，双财星。','主财气厚、收入稳。','左右魁钺百官拱，才贵。','煞冲破则破格。'],
 enLog:['Lu Cun and Hua Lu meet Life in trine, two wealth stars.','It brings thick wealth and steady income.','Zuo You Kui Yue and officials around bring rank.','Malefics breaking it void the pattern.'],
 cnStep:['先确认禄存化禄在三方会命','看二星亮度','数百官吉星、看贵气','数煞星、看冲破','看田宅、财能不能入库','判断富贵层次'],
 enStep:['First confirm Lu Cun and Hua Lu meet Life in trine','Read their brightness','Count official auspicious stars for rank','Count malefics for breaks','Read Property, whether wealth enters storage','Judge wealth-rank level'],
 cnMis:['双禄会就当大格、不看百官','财星独旺、误判为贵','不防煞破'],
 enMis:['Seeing two Lu and calling it great without officials','Wealth stars alone, misjudging rank','Not guarding malefics'],
 cnClose:'双禄朝垣看的是「财气厚、有没有百官配」。双禄给富、百官给贵，无煞破，才是富贵双全的格。命理倾向不构成投资建议，以持牌机构说明为准。',
 enClose:'This pattern asks whether thick wealth has officials to match. Two Lu give riches, officials give rank, no malefic break for wealth and rank together. This cultural-tendency reference is not investment advice; defer to licensed institutions.'},

{cat:'geju',slug:'ziwei-jiadi-dengke-ge-ruhe-kan',focus:'甲第登科格',focusEn:'the Top Graduate pattern',
 cnT:'甲第登科格：昌曲魁钺化科会命，利功名考试',enT:'The Top Graduate Pattern: Chang Qu, Kui Yue and Hua Ke',
 cnD:'文昌文曲、天魁天钺与化科会聚命宫，如科举甲第登科，主聪明、考试运佳、功名顺遂，利学术、公职、文教；逢煞忌破格，考运打折。',
 enD:'When Wen Chang Wen Qu, Tian Kui Tian Yue and Hua Ke gather at the Life Palace, like a top graduate in the imperial exam, it brings intelligence, good exam fortune and smooth distinction, favoring scholarship, public service and education. Malefics break it and discount exam fortune.',
 cnL:'甲第登科是文星贵人一齐来、考试这条路特别顺；但顺的是节奏，功夫还得下。',
 enL:'This pattern has literary stars and mentors coming together, the exam path especially smooth; but timing is smooth, effort still required.',
 cnA:'有人见此格就当必中、不复习，结果节奏再好也白搭；文星给状态，不给现成答案。',
 enA:'Some see this pattern and assume passing without review, and good timing is wasted; literary stars give state, not answers.',
 cnLog:['昌曲主文才，魁钺主贵人，化科主名声。','会聚命宫，利考试功名。','主聪明、学习力强。','煞忌破格，考运打折。'],
 enLog:['Chang Qu govern talent, Kui Yue mentors, Hua Ke reputation.','Gathering at Life favors exams and distinction.','It brings intelligence and strong learning.','Malefics break it, discounting exam fortune.'],
 cnStep:['先认昌曲魁钺化科是否会命','看文星亮度','看流年大限引动、考试应期','数煞忌、看破格','节奏顺抓紧、全力复习','判断功名方向'],
 enStep:['First recognize whether Chang Qu, Kui Yue and Hua Ke meet Life','Read literary star brightness','Read annual-decade activation for exam timing','Count malefics for breaks','Smooth timing, seize and review fully','Judge distinction direction'],
 cnMis:['见格当必中、不努力','不看煞忌破格','只看文星、不看流年应期'],
 enMis:['Seeing the pattern and assuming passing without effort','Ignoring malefic breaks','Seeing only literary stars without timing'],
 cnClose:'甲第登科看的是「考试节奏顺不顺」。文星贵人给状态、化科给名声，配上努力，功名才兑现。',
 enClose:'This pattern asks whether exam timing is smooth. Literary stars and mentors give state, Hua Ke reputation; with effort, distinction materializes.'},

{cat:'geju',slug:'ziwei-wengui-wenhua-ge-ruhe-kan',focus:'文桂文华格',focusEn:'the Literary Laurel and Splendor pattern',
 cnT:'文桂文华格：昌曲遇吉星，文才出众利学术',enT:'The Literary Laurel and Splendor Pattern',
 cnD:'文昌文曲遇吉星、化科会聚，如桂树开花，主文才、学问、艺术感受力，利学术研究、写作、文教；要防有文无实、光说不练，逢煞破格。',
 enD:'When Wen Chang Wen Qu meet auspicious stars and Hua Ke, like a laurel blooming, it brings literary talent, learning and artistic sensitivity, favoring scholarship, writing and education. Guard letters without substance and talk without practice; malefics break it.',
 cnL:'文桂文华是文星开了花，好看也要结果；学问要做实，才不是空文采。',
 enL:'This pattern is literary stars blossoming, beautiful but needing fruit; learning must be made solid, not empty talent.',
 cnA:'有人见昌曲会聚就当学者，其实文采和学问是两回事；要做实功、防虚名。',
 enA:'Some see Chang Qu gather and assume a scholar, but literary grace and learning differ; do solid work, guard empty name.',
 cnLog:['昌曲遇吉星化科，文才盛。','利学术、写作、文教、艺术。','主头脑清、表达好。','防有文无实，煞破格。'],
 enLog:['Chang Qu meet auspicious stars and Ke, talent flourishes.','It favors scholarship, writing, education and art.','It brings a clear mind and good expression.','Guard letters without substance; malefics break it.'],
 cnStep:['先认昌曲吉星会聚','看文星亮度','看化科引动','做实学、不图虚名','数煞星、看破格','定才华施展领域'],
 enStep:['First recognize Chang Qu and auspicious stars gathering','Read literary star brightness','Read Ke activation','Do solid learning, not empty name','Count malefics for breaks','Set the talent area'],
 cnMis:['文采当学问、有文无实','只图虚名、不做实功','不防煞破'],
 enMis:['Taking literary grace as learning, letters without substance','Seeking empty name without solid work','Not guarding malefics'],
 cnClose:'文桂文华看的是「文才怎么结成学问的果」。星曜给文采、实学给分量，配起来才是真才华。',
 enClose:'This pattern asks how literary talent fruits into learning. Stars give grace, solid learning gives weight; together they are true talent.'},

{cat:'geju',slug:'ziwei-juji-tonggong-ge-ruhe-kan',focus:'巨机同宫格',focusEn:'the Ju Men and Tian Ji same-palace pattern',
 cnT:'巨机同宫格：巨门天机同度，善辩善谋利思辨',enT:'The Ju Men and Tian Ji Same-Palace Pattern',
 cnD:'巨门（口舌思辨）与天机（谋略变动）同宫守命，主善辩、善谋、反应快，利策划、辩论、研究、表达；防心劳、多思、口舌招非，逢吉化才把才思用好。',
 enD:'When Ju Men (speech and critical thought) and Tian Ji (strategy and change) share the Life Palace, it brings eloquence, planning and quick response, favoring planning, debate, research and expression. Guard mental toil, overthinking and disputes; auspicious transformations use the talent well.',
 cnL:'巨机是一颗思辨星配一颗谋略星，脑子转得快、嘴巴跟得上；但想得多也容易累、容易惹口舌。',
 enL:'This pattern is a critical star with a strategy star, a quick mind and matching speech; but overthinking tires and invites disputes.',
 cnA:'有人见巨机同宫就当聪明绝顶，忽略心劳口舌；才思要用对地方、防内耗。',
 enA:'Some see Ju Men Tian Ji and assume brilliant intelligence, ignoring mental toil and disputes; talent must be used right, guard inner friction.',
 cnLog:['巨门主思辨表达，天机主谋略变动。','同宫主善辩善谋、反应快。','利策划、辩论、研究、传播。','防心劳、多思、口舌，逢煞破格。'],
 enLog:['Ju Men governs critical expression, Tian Ji strategy and change.','Together they bring eloquence, planning and quick response.','It favors planning, debate, research and communication.','Guard mental toil, overthinking and disputes; malefics break it.'],
 cnStep:['先确认巨门天机同宫','看二星亮度','看吉化、才思怎么用','数煞忌、防口舌心劳','选能发挥思辨谋略的方向','练专注、防想太多'],
 enStep:['First confirm Ju Men and Tian Ji share a palace','Read their brightness','Read auspicious transformations for using talent','Count malefics to guard disputes and toil','Choose directions using critical thought and strategy','Practice focus, guard overthinking'],
 cnMis:['见同宫当聪明、忽略心劳','才思没用对、惹口舌','不防多思内耗'],
 enMis:['Seeing the pattern as intelligence, ignoring toil','Talent misused, inviting disputes','Not guarding overthinking and inner friction'],
 cnClose:'巨机同宫看的是「思辨谋略怎么用成专业表达」。逢吉化、防口舌心劳，才思才是利器而不是负担。',
 enClose:'This pattern asks how critical thought and strategy become professional expression. With auspicious transformations and guarding disputes and toil, talent is an asset rather than a burden.'},

{cat:'geju',slug:'ziwei-changqu-jia-ming-ruhe-kan',focus:'昌曲夹命',focusEn:'Chang Qu flanking the Life Palace',
 cnT:'昌曲夹命：文昌文曲在左右，文气贴身',enT:'Chang Qu Flanking the Life Palace',
 cnD:'文昌文曲分守命宫左右夹宫，主文气贴身、表达力强、利考试文书；同对星夹命，逢吉化文名更显，逢煞冲破则文采打折。',
 enD:'When Wen Chang and Wen Qu guard the two flanking palaces around Life, it brings close literary force, strong expression and favors exams and documents. As a paired-star flank, auspicious transformations brighten literary name; malefics discount talent.',
 cnL:'昌曲夹命像一左一右有文气，说话写文章都带劲；但文气要配实学。',
 enL:'This flank is like literary force on either side, speech and writing with drive; but literary force needs real learning.',
 cnA:'有人见昌曲夹命就当必成名，其实文采要做实、要逢吉化；成格条件看清。',
 enA:'Some see Chang Qu flanking and assume fame, but talent must be made solid and meet auspicious transformations; read conditions.',
 cnLog:['昌曲在命宫左右夹命。','主文气贴身、表达力强。','逢化科、吉星，文名显。','煞冲破则文采打折。'],
 enLog:['Chang Qu flank the Life Palace.','It brings close literary force and strong expression.','With Ke and auspicious stars, literary name shows.','Malefics breaking it discount talent.'],
 cnStep:['先确认昌曲在命宫左右','看二星亮度','看化科引动','数煞星、看冲破','做实学、防有文无实','定文才施展领域'],
 enStep:['First confirm Chang Qu flank Life','Read their brightness','Read Ke activation','Count malefics for breaks','Do solid learning, guard letters without substance','Set the talent area'],
 cnMis:['见夹命当必成名、不做实学','不看煞破','文气当结果、忽略努力'],
 enMis:['Seeing the flank and assuming fame without solid learning','Ignoring malefic breaks','Taking literary force as result, ignoring effort'],
 cnClose:'昌曲夹命看的是「文气贴身、能不能成实学」。逢吉化、做实功，文采才变成文名。',
 enClose:'This flank asks whether close literary force becomes real learning. With auspicious transformations and solid work, talent becomes literary name.'},

{cat:'geju',slug:'ziwei-shazi-chaodou-ge-ruhe-kan',focus:'七杀朝斗格',focusEn:'Qi Sha Facing the Pole pattern',
 cnT:'七杀朝斗格：七杀寅申守命、对宫紫微，威权立功名',enT:'Qi Sha Facing the Pole Pattern',
 cnD:'七杀在寅、申守命、对宫紫微，如七杀朝见北斗，主威权、决断、武职功名，利军警、开拓、管理；防孤克、刑伤，须吉星调和。',
 enD:'When Qi Sha guards life at Yin or Shen with Zi Wei opposite, like Qi Sha facing the North Pole, it brings authority, decisiveness and martial distinction, favoring police-military, pioneering and management. Guard isolation and injury; auspicious stars must temper it.',
 cnL:'七杀朝斗是煞星得帝星正照，刚烈化成威权；但威权要有人辅、防孤。',
 enL:'This pattern is a malefic with the emperor star directly opposite, fierceness becoming authority; but authority needs assistants, guard isolation.',
 cnA:'有人见七杀朝斗就当武职大贵，其实更要看吉星调和，否则刚烈招刑伤。',
 enA:'Some see this pattern and assume high martial rank, but auspicious tempering matters even more, or fierceness brings injury.',
 cnLog:['七杀在寅申守命、对宫紫微。','主威权、决断、武职功名。','吉星调和、左右辅佐。','防孤克刑伤，煞破格。'],
 enLog:['Qi Sha guards life at Yin Shen, Zi Wei opposite.','It brings authority, decisiveness and martial distinction.','Auspicious stars temper, Zuo You assist.','Guard isolation and injury; malefics break it.'],
 cnStep:['先确认七杀寅申守命、紫微对照','看七杀亮度','数吉星、看调和辅佐','数煞星、防刑伤','看三方、定功名方向','判断成格还是孤克'],
 enStep:['First confirm Qi Sha at Yin Shen with Zi Wei opposite','Read Qi Sha brightness','Count auspicious stars for tempering and assistance','Count malefics to guard injury','Read trines for distinction direction','Judge valid or isolation'],
 cnMis:['见格当大贵、不看调和','忽略孤克刑伤','只看七杀、不看紫微三方'],
 enMis:['Seeing the pattern and assuming rank without tempering','Ignoring isolation and injury','Seeing only Qi Sha without Zi Wei and trines'],
 cnClose:'七杀朝斗看的是「刚烈怎么化成威权功名」。帝星正照、吉星辅佐、防住刑伤，威权才立得稳。',
 enClose:'This pattern asks how fierceness becomes authority and distinction. Emperor opposite, auspicious assistance and guarding injury, and authority stands steady.'},

{cat:'geju',slug:'ziwei-xingjiang-dedi-ge-ruhe-kan',focus:'将星得地格',focusEn:'the General Star Well-Placed pattern',
 cnT:'将星得地格：武曲庙旺守命，刚毅财星得用',enT:'The General Star Well-Placed Pattern: Wu Qu at Brightness',
 cnD:'武曲（将星、财星）在庙旺宫位守命，主刚毅、果断、理财与执行，利金融、军警、工程、技术；防过刚、孤直，逢吉星调和才把财星将星用好。',
 enD:'When Wu Qu (general and wealth star) guards life at a bright palace, it brings resolve, decisiveness, finance and execution, favoring finance, police-military, engineering and technology. Guard excess rigidity and bluntness; auspicious stars temper it to use the general-wealth star well.',
 cnL:'将星得地是武曲这颗财星将星站到了有力的位置，能扛事、能理财；但刚要配柔。',
 enL:'This pattern is Wu Qu the general-wealth star in a strong position, able to carry matters and manage wealth; but firmness needs softness.',
 cnA:'有人见武曲庙旺就当一定发财掌权，其实过刚易折、要吉星调和；成格看组合。',
 enA:'Some see Wu Qu bright and assume wealth and authority, but excess firmness breaks and needs tempering; read combinations.',
 cnLog:['武曲主财、主将、主刚毅执行。','庙旺守命，财星将星得用。','利金融、军警、工程、技术。','防过刚孤直，煞破格。'],
 enLog:['Wu Qu governs wealth, generalship and firm execution.','At brightness guarding life, the general-wealth star is well-used.','It favors finance, police-military, engineering and technology.','Guard excess rigidity and bluntness; malefics break it.'],
 cnStep:['先确认武曲庙旺守命','看武曲亮度','数吉星、看调和','数煞星、防过刚','看三方财官、定方向','判断成格还是孤直'],
 enStep:['First confirm Wu Qu bright guarding life','Read Wu Qu brightness','Count auspicious stars for tempering','Count malefics to guard excess firmness','Read trine wealth-career for direction','Judge valid or blunt isolation'],
 cnMis:['见武曲庙旺当必发财、不看调和','过刚孤直、不防折损','只看财星、不看将星执行'],
 enMis:['Seeing Wu Qu bright and assuming wealth without tempering','Excess firmness and bluntness, not guarding loss','Seeing only wealth, not generalship execution'],
 cnClose:'将星得地看的是「财星将星得位、刚柔配不配」。庙旺给力、吉星调和，刚毅才成财、成功名。命理倾向不构成投资建议，以持牌机构说明为准。',
 enClose:'This pattern asks whether the general-wealth star well-placed has firmness matched with softness. Brightness gives force, auspicious stars temper, and resolve becomes wealth and distinction. This cultural-tendency reference is not investment advice; defer to licensed institutions.'},

{cat:'zhuxing',slug:'ziwei-ziwei-xing-zonglun',focus:'紫微星总论',focusEn:'the Zi Wei star overview',
 cnT:'紫微星总论：帝星主尊贵、领导，百官拱才成格',enT:'The Zi Wei Star Overview: The Emperor Star',
 cnD:'紫微星为北斗主、帝星，主尊贵、领导、好面子与高标准；紫微独坐要百官（左右魁钺昌曲府相）拱照才成大格，无辅则孤高，逢煞破则高傲劳碌。',
 enD:'Zi Wei is the North Pole ruler and emperor star, governing distinction, leadership, face and high standards. Zi Wei alone needs the hundred officials (Zuo You Kui Yue Chang Qu Fu Xiang) around to form a great pattern; without assistants it is aloof, and malefics make it proud and toilsome.',
 cnL:'紫微像皇帝，要有百官辅佐才坐得稳；光有帝星没有臣子，高处不胜寒。',
 enL:'Zi Wei is like an emperor needing officials to sit steady; the emperor star alone feels lonely at the top.',
 cnA:'有人见紫微守命就当一定大贵，其实格局高低全看百官到不到位；帝星给的是领导底色。',
 enA:'Some see Zi Wei guard life and assume great rank, but pattern height depends on officials; the emperor star gives leadership tone.',
 cnLog:['紫微属土，主尊贵、领导、好面子。','百官（左右魁钺昌曲府相）拱照，君臣庆会。','无辅佐主孤高，逢煞破主高傲劳碌。','利领导、管理、公职。'],
 enLog:['Zi Wei belongs to earth, governing distinction, leadership and face.','Hundred officials (Zuo You Kui Yue Chang Qu Fu Xiang) around form the ruler-minister meeting.','Without assistants it is aloof; malefics make it proud and toilsome.','It favors leadership, management and public office.'],
 cnStep:['先看紫微所在宫位与亮度','看百官有没有拱照','数左右魁钺昌曲府相','无辅：防孤高','逢煞：防高傲劳碌','判断格局高低'],
 enStep:['First read the Zi Wei palace and brightness','See whether officials surround','Count Zuo You Kui Yue Chang Qu Fu Xiang','No assistants: guard aloofness','With malefics: guard pride and toil','Judge pattern height'],
 cnMis:['见紫微守命当必大贵、不看百官','无辅佐还自傲','逢煞破不查、高处生寒'],
 enMis:['Seeing Zi Wei guard life and assuming rank without officials','Proud without assistants','Not checking malefics, lonely at the top'],
 cnClose:'紫微星总论看的是「帝星有没有百官拱」。百官齐、无煞破，尊贵才成大格；否则领导底色也会变成孤高劳碌。',
 enClose:'The Zi Wei overview asks whether the emperor star has officials around. Officials complete and no malefic break, and distinction becomes a great pattern; or leadership tone turns aloof and toilsome.'}
];
