// 2026-10-05 调研驱动 第3组：文昌化科逐宫 4 + 看盘方法进阶 4
module.exports=[
{cat:'sihua',slug:'ziwei-2026-wenchanghuake-minggong',focus:'文昌化科在命宫',focusEn:'Wen Chang Hua Ke in the Life Palace',
 cnT:'2026文昌化科在命宫：名声与文采被点亮，把表达练成个人招牌',enT:'2026 Wen Chang Hua Ke in the Life Palace: Reputation and Eloquence Light Up; Make Expression Your Signature',
 cnD:'文昌主才学、文书与正统功名，化科落命宫这一年思路清晰、表达得体、容易被人看见与信任；重点是把作品和专业形象立起来，同时留意文书细节、不因顺而草率。',
 enD:'Wen Chang governs learning, documents and formal recognition, and Hua Ke in the Life Palace brings clear thinking, polished expression and visibility and trust this year. Build your work and professional image while minding document details rather than growing careless with ease.',
 cnL:'文昌化科在命，像给才华打上一束光，平时的积累这一年容易被看见，可光打下来还得有拿得出手的东西。',
 enL:'Wen Chang Hua Ke in the Life Palace is like a spotlight on talent, where past effort is seen this year, yet the light still needs something worth showing.',
 cnA:'有人这一年考试、面试、提案比平时顺，个人口碑变好，就以为光靠运气，其实问题在于：机会被照亮时，自己有没有持续把本事和作品做实。',
 enA:'Some find exams, interviews and proposals smoother and their reputation better, then credit luck alone; the issue is whether, when the opening is lit, they keep deepening the skill and the work.',
 cnLog:['文昌主正统文才、学术与文书，化科主名声、显扬与条理，落命宫则个人表达与口碑被加强。','它利「被看见、被信任」，但名声要靠真才与作品承接，否则容易名过其实。','文昌化科逢魁钺、吉星，贵人与口碑更稳；逢煞忌、空劫则易因文书疏漏、说错话而损名。','流年化科只主一年加减分，长期学业事业仍看本命与大限。'],
 enLog:['Wen Chang governs formal literary talent, scholarship and documents, while Hua Ke governs reputation, visibility and order, strengthening expression and standing in the Life Palace.','It favors being seen and trusted, but reputation must be met by real skill and work or it overstates the name.','With Kui Yue and auspicious stars the mentors and standing are steadier; with malefics and emptiness, document slips and careless words harm the name.','An annual Hua Ke sets only one year of pluses and minuses; long-term study and career still rest on the natal chart and decade.'],
 cnStep:['先定位文昌化科是流年一层，本命底色未变','把今年想立的专业形象、作品与目标列清楚','借思路清晰之机把重要表达、考试、提案提前演练','作品、履历、个人介绍一次做规范，不留小瑕疵','重要文书与公开发言复核细节，不因顺而草率','年底复盘名声背后有多少是真实本事撑住的'],
 enStep:['First confirm that Wen Chang Hua Ke is the annual layer and the natal baseline has not changed','List the professional image, work and goals you want to establish this year','Use the clear thinking to rehearse key expression, exams and proposals in advance','Polish work, resume and personal introduction to standard without small flaws','Review key documents and public statements for details rather than growing careless','At year-end assess how much of the reputation real ability supports'],
 cnMis:['把名声当本事，被看见后却拿不出作品','顺了就草率，文书和发言不复核、埋下损名的坑','把一年的口碑当长期成就，不看本命大限'],
 enMis:['Taking reputation for ability and having no work once seen','Growing careless with ease and skipping review until words harm the name','Taking one year of standing as long-term achievement without the natal chart and decade'],
 cnClose:'文昌化科在命的功课是「让名实相符」。把表达练扎实、把作品做出来、把细节守住，这一年被点亮的才华才真正变成个人招牌。',
 enClose:'Wen Chang Hua Ke in the Life Palace teaches matching name to substance. Make expression solid, produce the work and guard details, and the lit talent genuinely becomes your signature.'},

{cat:'sihua',slug:'ziwei-2026-wenchanghuake-guanlugong',focus:'文昌化科在官禄宫',focusEn:'Wen Chang Hua Ke in the Career Palace',
 cnT:'2026文昌化科在官禄宫：专业名声与晋升运，利考证、技术与文书岗',enT:'2026 Wen Chang Hua Ke in the Career Palace: Professional Reputation and Promotion, Favoring Credentials, Technical and Document Roles',
 cnD:'文昌化科落官禄宫，这一年职场上专业表现易被肯定、利考证晋升、文书与方案容易通过；重点是把资格和成果做规范、节点抓准，把名声落到实际职责上。',
 enD:'With Wen Chang Hua Ke in the Career Palace, professional performance is recognized this year, favoring credentials, promotion and the approval of documents and plans. Standardize qualifications and results, hit deadlines and ground reputation in real responsibilities.',
 cnL:'文昌化科在官禄，像给专业能力盖了一枚认可的章，这一年凭本事说话最管用，可章盖了还得把活干漂亮。',
 enL:'Wen Chang Hua Ke in the Career Palace is like a stamp of approval on ability, where skill speaks loudest this year, yet the work must still be done well after the stamp.',
 cnA:'有人这一年考证、评级、申报比平时顺，方案也容易被采纳，就等晋升自己来，其实问题在于：专业被认可后，有没有把成果和职责稳稳接住。',
 enA:'Some find credentials, reviews and filings smoother and plans adopted, then wait for promotion to arrive; the issue is whether, after recognition, they steadily take up the results and responsibilities.',
 cnLog:['官禄宫写工作方式与职务成就，文昌化科加强专业名声、文书方案与资格功名，利考试、评级与晋升。','它给「被认可的条件」而非自动升职，材料规范、成果扎实、节点准时才接得住。','文昌化科逢魁钺、吉星，晋升与贵人更稳；逢煞忌则易因文书格式、疏漏被退回。','它只主一年事业上的加减分，长期职业格局仍看本命官禄与大限。'],
 enLog:['The Career Palace describes work style and role achievement, and Wen Chang Hua Ke strengthens professional reputation, documents and credentials, favoring exams, reviews and promotion.','It gives conditions for recognition rather than automatic promotion; standard materials, solid results and punctual deadlines catch it.','With Kui Yue and auspicious stars promotion and mentors are steadier; with malefics, document format and slips cause rejection.','It sets only one year of career pluses and minuses; long-term professional patterns still rest on the natal Career Palace and decade.'],
 cnStep:['先定位流年官禄宫，看清这一年专业认可从哪来','把今年要考的证、申报的评级和截止节点列清楚','材料、方案按规范一次做到位，逻辑与署名不含糊','重要提交预留复核时间，不压到最后','把被认可的成果落到实际职责和团队贡献上','被退回时按意见补正，不情绪化、不弃节点'],
 enStep:['Locate the annual Career Palace and see where professional recognition comes from this year','List credentials and reviews due this year with their deadlines','Prepare materials and plans to standard with clear logic and attribution done once','Reserve review time for key submissions rather than finishing last','Ground recognized results in real responsibilities and team contribution','If returned, correct per feedback without emotion and keep the deadline'],
 cnMis:['以为认可就会自动升职，材料和成果却草率','不记节点、压到最后，来不及复核','把一年专业名声当长期职位，不看本命大限'],
 enMis:['Assuming recognition means automatic promotion while materials stay careless','Ignoring deadlines and finishing last with no review time','Taking one year of professional reputation as long-term position without the natal chart and decade'],
 cnClose:'文昌化科在官禄的功课是「以实配名」。把资格和成果做规范、把节点守准，这一年的专业认可才真正变成职业台阶。',
 enClose:'Wen Chang Hua Ke in the Career Palace teaches matching substance to name. Standardize credentials and results and keep deadlines, and the year recognition genuinely becomes a career stair.'},

{cat:'sihua',slug:'ziwei-2026-wenchanghuake-fumugong',focus:'文昌化科在父母宫',focusEn:'Wen Chang Hua Ke in the Parents Palace',
 cnT:'2026文昌化科在父母宫：考试、师长与文书契约，走正规渠道最顺',enT:'2026 Wen Chang Hua Ke in the Parents Palace: Exams, Mentors and Documents Go Best Through Proper Channels',
 cnD:'父母宫为文书位、师长位，文昌化科落此这一年利考试、申请、签约与长辈提携，材料规范、渠道正规则事半功倍；重点是按规矩递交、把契约条款看清。',
 enD:'The Parents Palace is the document and mentor position, and Wen Chang Hua Ke there favors exams, applications, contracts and senior support this year when materials are standard and channels proper. Submit by the rules and read contract terms.',
 cnL:'文昌化科在父母，像文书路上有人替你把了关，这一年按正规流程递交的事容易成，可材料还得自己备齐。',
 enL:'Wen Chang Hua Ke in the Parents Palace is like someone checking your documents; matters submitted through proper process tend to pass, yet the materials must still be complete.',
 cnA:'有人这一年考证、申请、签约特别顺，也有人总卡在格式、手续和表达上，差别不在运气，而在有没有把文书和正规渠道当回事。',
 enA:'Some find credentials, applications and contracts smooth while others get stuck on format and procedure; the difference is not luck but whether documents and proper channels were taken seriously.',
 cnLog:['父母宫主文书、学业、师长与正规渠道，文昌化科加强考试、申请、签约与长辈贵人的顺遂面。','它利功名但不自动给结果，材料规范、逻辑清楚、节点准时才接得住。','文昌化科逢魁钺、吉星，师长提携更稳；逢煞忌则易因格式、疏漏被退回。','涉及契约与法律边界，以专业律师、正规途径和书面合同为准。'],
 enLog:['The Parents Palace governs documents, study, mentors and proper channels, and Wen Chang Hua Ke strengthens exams, applications, contracts and senior support.','It favors recognition but grants nothing automatically; standard materials, clear logic and punctual deadlines catch it.','With Kui Yue and auspicious stars mentor support is steadier; with malefics, format and slips cause rejection.','For contracts and legal boundaries, rely on a qualified lawyer, proper channels and a written contract.'],
 cnStep:['先定位流年父母宫，看清这一年文书与考试的引动','把要递交、申报、签约的事项和截止节点列清楚','材料按规范准备，逻辑、格式、署名一次到位','重要提交预留复核时间，不压到最后','签契约前逐条看条款，走正规渠道、不留口头约定','被退回时按意见补正，按节点重新递交'],
 enStep:['Locate the annual Parents Palace and see the activation of documents and exams this year','List submissions, filings and contracts due with their deadlines','Prepare materials to standard with clear logic, format and attribution done once','Reserve review time for key submissions rather than finishing last','Before signing, read each clause and use proper channels rather than verbal promises','If returned, correct per feedback and resubmit by the deadline'],
 cnMis:['以为文书星当值就自动通过，材料草率','不看契约条款、不留书面，事后吃哑巴亏','一次被退回就放弃，不按意见补正'],
 enMis:['Assuming a document star means automatic approval and preparing careless materials','Skipping contract terms and writing until losing out silently','Giving up after one rejection instead of correcting per feedback'],
 cnClose:'文昌化科在父母的功课是「把文书办规范」。材料齐、渠道正、条款清，这一年的考试与契约自然接得住。',
 enClose:'Wen Chang Hua Ke in the Parents Palace teaches handling documents to standard. With complete materials, proper channels and clear terms, the year exams and contracts are naturally caught.'},

{cat:'sihua',slug:'ziwei-2026-wenchanghuake-caibogong',focus:'文昌化科在财帛宫',focusEn:'Wen Chang Hua Ke in the Wealth Palace',
 cnT:'2026文昌化科在财帛宫：以名生财、靠文书合同进财的一年',enT:'2026 Wen Chang Hua Ke in the Wealth Palace: Earning Through Reputation and Documents',
 cnD:'文昌化科落财帛宫，这一年容易靠专业名声、文书合同、版权与资格带来收入，名声能变现；重点是把合作与合同条款做规范，守住口碑，不赚来路不清的钱。',
 enD:'With Wen Chang Hua Ke in the Wealth Palace, income tends to come through professional reputation, documents, contracts, copyright and credentials this year. Standardize cooperation and contract terms, protect standing and avoid money from unclear sources.',
 cnL:'文昌化科在财帛，像把名声变成了进账的渠道，这一年专业背书值钱，可合同和口碑还得守牢。',
 enL:'Wen Chang Hua Ke in the Wealth Palace is like turning reputation into an income channel, where professional endorsement is valuable, yet contracts and standing must be guarded.',
 cnA:'有人这一年靠作品、资质与合同谈下不错的收入，也有人只图快、合同没看清吃亏，差别不在机会，而在有没有把文书和口碑当回事。',
 enA:'Some negotiate good income through work, credentials and contracts, while others rush and lose out by not reading them; the difference is not opportunity but whether documents and standing were taken seriously.',
 cnLog:['财帛宫写收入来源，文昌化科让「以名生财、文书进财」的路径变顺，利版权、资格与专业背书。','它给的是变现条件而非自动收入，合同规范、口碑扎实才接得住。','文昌化科逢魁钺、吉星，贵人介绍与进财更稳；逢煞忌则易因合同疏漏、口舌损财。','本文不构成投资建议，合作以专业律师、正规途径和书面合同为准。'],
 enLog:['The Wealth Palace describes income sources, and Wen Chang Hua Ke smooths earning through reputation and documents, favoring copyright, credentials and endorsement.','It gives conditions to monetize rather than automatic income; standard contracts and solid standing catch it.','With Kui Yue and auspicious stars referrals and income are steadier; with malefics, contract slips and disputes cost money.','This is not investment advice; for cooperation rely on a qualified lawyer, proper channels and a written contract.'],
 cnStep:['先定位流年财帛宫，看清这一年名声变现的路径','把靠专业、版权、资格能带来的收入来源列清楚','重要合作与合同逐条看条款，分成、署名与责任明确','把口碑和作品做扎实，让专业背书经得起核对','不赚来路不清、靠口头承诺的钱','年底复盘哪些收入是名声与合同稳稳带来的'],
 enStep:['Locate the annual Wealth Palace and see the path to monetize reputation this year','List income sources through skill, copyright and credentials','Read key cooperation and contract clauses, clarifying shares, attribution and responsibility','Solidify standing and work so professional endorsement bears checking','Avoid money from unclear sources or verbal promises','At year-end review which income reputation and contracts steadily brought'],
 cnMis:['以为名声会自动变钱，合同与作品却草率','不看合同条款、不留书面，进账后反生纠纷','把一年顺遂当长期财运，不看本命大限'],
 enMis:['Assuming reputation turns to money by itself while contracts and work stay careless','Skipping contract terms until disputes arise after payment','Taking one smooth year as long-term wealth luck without the natal chart and decade'],
 cnClose:'文昌化科在财帛的功课是「以名立信、以约守财」。把专业做硬、把合同看清，这一年的名声才真正变成稳当的收入。',
 enClose:'Wen Chang Hua Ke in the Wealth Palace teaches building trust through reputation and guarding money through agreements. Harden the skill and read contracts, and the year reputation genuinely becomes steady income.'},

{cat:'kanpan',slug:'ziwei-shaxing-miaowang-luoxian-ruhe-kan',focus:'煞星庙旺落陷的不同破法',focusEn:'how malefics break things differently in exaltation versus fall',
 cnT:'煞星庙旺和落陷破法有何不同：一个急而有力，一个别扭内耗',enT:'How Malefics Differ in Exaltation Versus Fall: Sharp Force Versus Awkward Drain',
 cnD:'同样一颗煞星，庙旺时力量急而集中，常表现为冲击也可能是爆发力；落陷时力量别扭、易成内耗与反复。分清这两种状态，化解的方向才不会用反。',
 enD:'The same malefic in exaltation carries sharp, concentrated force that may strike or drive a breakthrough, while in fall it turns awkward and becomes inner drain and repetition. Telling the two apart keeps the remedy pointed the right way.',
 cnL:'煞星不是一律的坏，庙旺的煞像一把快刀，能伤人也能砍柴；落陷的煞像钝刀，砍不动还磨手，处理方法自然不同。',
 enL:'Malefics are not uniformly bad; an exalted one is like a sharp blade that can wound or cut wood, while a fallen one is a dull blade that will not cut yet chafes the hand.',
 cnA:'有人看到煞星就一律紧张、一律压制，结果对庙旺的煞误了爆发力、对落陷的煞又没解决内耗，问题不在煞星，而在没分清它的状态。',
 enA:'Some fear and suppress every malefic alike, missing the drive of an exalted one and failing to fix the drain of a fallen one; the issue is not the star but not distinguishing its state.',
 cnLog:['煞星（擎羊、陀罗、火星、铃星等）的影响随庙旺落陷而变：庙旺力量集中、来得急，落陷力量别扭、爱反复。','庙旺的煞若方向对，常是行动力与爆发力，宜疏导到具体目标，而非硬压。','落陷的煞多表现为拖延、内耗与使不上劲，宜降预期、补流程、慢慢来。','具体仍要看同宫主星、三方四正与四化，不能只凭亮度单断。'],
 enLog:['Malefics such as Qing Yang, Tuo Luo, Huo Xing and Ling Xing change with brightness: exalted force is concentrated and abrupt, fallen force is awkward and repetitive.','When an exalted malefic points the right way it often becomes drive and breakthrough, best channeled to a concrete goal rather than suppressed.','A fallen malefic tends to delay and drain with effort that will not land, so lower expectations, add process and go slowly.','Still read the home major stars, triple-direction and transformations rather than judging by brightness alone.'],
 cnStep:['先认出是哪颗煞星、基本性质偏急还是偏缠','查它在当前宫位的亮度，分清庙旺还是落陷','庙旺的煞：找一个正当目标把力量疏导出去','落陷的煞：降预期、补流程，用小步替代硬闯','再结合同宫主星与三方四化，看净效果','最后定化解方向，不对所有煞星一刀切'],
 enStep:['Identify which malefic it is and whether its nature is abrupt or entangling','Check its brightness in the current palace to separate exaltation from fall','Exalted malefic: find a proper goal and channel the force into it','Fallen malefic: lower expectations, add process and use small steps instead of forcing','Combine the home major stars and triple-direction transformations for the net effect','Only then set the remedy rather than treating all malefics alike'],
 cnMis:['把所有煞星当一类，一律压制或一律害怕','庙旺的煞硬压，白白浪费爆发力','落陷的煞还硬闯，把内耗拖成反复的麻烦'],
 enMis:['Treating all malefics as one and suppressing or fearing them uniformly','Suppressing an exalted malefic and wasting its drive','Forcing a fallen malefic and turning drain into repeated trouble'],
 cnClose:'看懂煞星的庙旺落陷，就明白「急煞宜导、缠煞宜缓」。把力量和状态分清，煞星不再只是吓人的标签，而能被你用对地方。',
 enClose:'Reading malefic brightness shows that sharp force is best channeled and entangling force best slowed. Separate power and state, and malefics stop being mere scary labels and can be put to proper use.'},

{cat:'kanpan',slug:'ziwei-pocai-nianfen-yingqi-ruhe-kan',focus:'破财年份与应期',focusEn:'the year and timing of financial loss',
 cnT:'怎么看破财的年份与应期：先定薄弱环节，再用流月收窄时间窗',enT:'How to Read the Year and Timing of Financial Loss: Find the Weak Link, Then Narrow It by Month',
 cnD:'看破财不是凭一句「今年破财」，而是先找财帛、田宅三方的薄弱组合，再用大限与流年四化定年份、流月四化收窄到具体时段，提前做风控就能把损失降到最低。',
 enD:'Reading loss is not a flat prediction of losing money this year. First find the weak combination around Wealth and Property, use decade and annual transformations to set the year and monthly transformations to narrow the window, then do early risk control to minimize loss.',
 cnL:'破财的应期像天气预报，先看季节（大限），再看哪天有雨（流年、流月），带伞出门就淋不湿。',
 enL:'The timing of loss is like a weather forecast: first see the season (decade), then which day brings rain (year, month), and carry an umbrella to stay dry.',
 cnA:'有人一句「今年破财」就整年紧张，或事后才发现早有信号却没防，问题不在准不准，而在没把薄弱环节和时间窗一层层找出来、提前布置。',
 enA:'Some hear you will lose money this year and worry all year, or only afterward see the signals; the issue is not accuracy but failing to find the weak link and time window layer by layer and preparing early.',
 cnLog:['破财的结构先看财帛宫、田宅宫的三方四正：煞聚、空劫、化忌冲照处就是薄弱环节。','年份由大限四化与流年四化引动，流年禄忌、流煞落宫定这一年的触发点。','再用流月四化与流月落宫，把时间窗收窄到具体月份，便于提前安排。','本文不构成投资建议，具体以持牌机构和正规产品说明为准，重点在风控而非断言。'],
 enLog:['The structure of loss first reads the triple-direction of Wealth and Property: gathered malefics, emptiness and obstruction mark the weak link.','The year is activated by decade and annual transformations, with annual Lu Ji and flowing malefics setting the trigger.','Then monthly transformations and palace narrow the window to a concrete month for early planning.','This is not investment advice; rely on licensed institutions and official product disclosures, with the focus on risk control rather than verdicts.'],
 cnStep:['先看本命财帛、田宅三方，找出最薄弱的组合','再看当前大限四化，定这十年财务偏紧的阶段','用流年四化与流煞落宫，定具体的破财年份','用流月四化把高风险时段收窄到月','在时间窗到来前主动降杠杆、留应急金、缓大额支出','事后复盘哪些损失被提前的风控化解'],
 enStep:['First read the natal Wealth and Property triple-direction to find the weakest combination','Then read the current decade transformations to set the tighter financial stage','Use annual transformations and flowing malefics to set the specific loss year','Use monthly transformations to narrow the high-risk window to a month','Before the window, cut leverage, keep emergency funds and postpone large spending','Afterward review which losses early risk control prevented'],
 cnMis:['把「破财」当笼统断言，不找环节、不定时间','只看流年一层，忽略大限打底与流月收窄','明知有信号却不做风控，事后才怪运气'],
 enMis:['Taking loss as a vague verdict without finding the link or timing','Reading only the year while ignoring the decade baseline and monthly narrowing','Seeing the signal yet skipping risk control and blaming luck afterward'],
 cnClose:'会看破财应期，重点不是吓唬自己，而是把有限的风控力气用在最关键的年份和月份，提前一步，损失自然小得多。',
 enClose:'Reading loss timing is not about fear but aiming finite risk-control effort at the key year and month; one step early, the loss is naturally far smaller.'},

{cat:'kanpan',slug:'ziwei-benming-daxian-liunian-sihua-xiangfan',focus:'三层四化相反时的裁决',focusEn:'how to judge when natal, decade and annual transformations conflict',
 cnT:'本命、大限、流年三层四化相反时怎么裁决：分层看，别平均用力',enT:'When Natal, Decade and Annual Transformations Conflict: Read in Layers, Not Evenly',
 cnD:'本命禄、大限忌、流年又禄，信号相反时最容易乱。裁决的关键是分层：生年四化定一生底色、大限四化定十年阶段、流年四化只定当年触发，权重不同，不能混在一起平均算。',
 enD:'When natal Lu meets a decade Ji and an annual Lu, the conflicting signals confuse. The key is layering: natal transformations set the lifelong tone, decade transformations set the ten-year stage and annual transformations only set the year trigger, with different weight rather than an even average.',
 cnL:'三层四化像公司的三级决策：董事会定方向（本命）、部门定阶段（大限）、当天值班定临时安排（流年），不能拿临时安排推翻大方向。',
 enL:'The three layers are like three levels of decisions: the board sets direction (natal), the department sets the stage (decade) and the duty shift sets temporary arrangements (year), which cannot overturn the main direction.',
 cnA:'有人一看今年流年化禄就以为要翻盘，忽略大限正走忌、本命也不配合，结果落空；问题不在信号矛盾，而在把三层权重当成了一样大。',
 enA:'Some see an annual Hua Lu and expect a turnaround, ignoring a decade Ji and an unsupporting natal, then miss; the issue is not contradiction but treating the three layers as equally weighted.',
 cnLog:['生年四化是本命结构的一部分，定一生的基调与主线，权重最高、最稳定。','大限四化主十年的阶段变化，在本命底色上加减，会引动或压住某些线。','流年四化只主当年的触发与节奏，时间短，不能据此推翻本命与大限的主线。','三层信号相反时，以「本命定方向、大限定阶段、流年定时机」顺序裁决，再决定怎么行动。'],
 enLog:['Natal transformations are part of the natal structure, setting the lifelong tone and main line with the highest, steadiest weight.','Decade transformations govern the ten-year stage, adding and subtracting on the natal baseline to activate or press certain lines.','Annual transformations govern only the year trigger and rhythm for a short time and cannot overturn the natal and decade main line.','When layers conflict, judge in the order of natal direction, decade stage and annual timing, then decide how to act.'],
 cnStep:['先把生年四化落宫列出，定这张盘的一生底色','再看当前大限四化，定这十年是助力还是压力','然后看流年四化，只当当年的触发点','三层相反时按权重裁决，不被流年一层带着走','把结论落到行动的节奏上：什么事这十年做、什么今年做','复盘时回看哪些判断尊重了分层，哪些被短期信号带偏'],
 enStep:['First list the natal transformation palaces to set the lifelong tone','Then read the current decade transformations to set whether the ten years help or press','Then read annual transformations only as the year trigger','When layers conflict, judge by weight rather than being led by the year alone','Turn the conclusion into timing: what to do this decade and what this year','In review, see which judgments respected layering and which short signals skewed'],
 cnMis:['拿流年一层推翻本命和大限的主线','把三层四化当同等权重，信号一多就乱','看到相反信号就断言「命不准」，不理解时间分层'],
 enMis:['Using the annual layer to overturn the natal and decade main line','Treating the three layers as equally weighted and getting lost in many signals','Calling the chart inaccurate at conflicting signals without understanding time layers'],
 cnClose:'掌握三层四化的权重，看盘就不会被一时的吉凶带着跑。本命定方向、大限定阶段、流年定时机，顺序清楚，行动才稳。',
 enClose:'Mastering the three-layer weight keeps a reading from being led by momentary signs. Natal sets direction, decade sets stage and year sets timing, and a clear order steadies action.'},

{cat:'kanpan',slug:'ziwei-daqi-wancheng-ruhe-kan',focus:'大器晚成的判断',focusEn:'whether a person blooms late',
 cnT:'怎么看一个人会不会大器晚成：看主轴星是否晚发、后段大限是否走强',enT:'How to Tell If Someone Blooms Late: Late-Opening Axis Stars and Stronger Later Decades',
 cnD:'大器晚成不是安慰话，盘上有迹可循：主轴星是否偏内敛晚发、中青年大限是否在积累、后半段大限是否三方转强、四化是否在后段引动，合起来才好判断。',
 enD:'Blooming late is not mere comfort; it can be read in the chart: whether the axis stars open late, whether early decades accumulate, whether later decades strengthen in the triple-direction and whether transformations activate later, taken together.',
 cnL:'大器晚成像树木里长得慢的那种，前期在扎根、看不见，根扎深了，后面的长势反而更稳更久。',
 enL:'Blooming late is like a slow-growing tree that puts down roots early out of sight, and once deep, its later growth is steadier and longer.',
 cnA:'有人年轻时处处被比下去就自我否定，也有人拿「大器晚成」当不行动的借口，问题不在快慢，而在有没有分清自己是「晚发」还是「没在积累」。',
 enA:'Some outdone when young reject themselves, while others use blooming late as an excuse for inaction; the issue is not speed but whether one is genuinely opening late or simply not accumulating.',
 cnLog:['先看本命主轴星：偏内敛、厚积型的星（如天府、天梁、太阴等）更有晚发的底子。','再看中青年大限是否在积累资源与能力，晚发不等于空等。','后半段大限三方四正转强、四化引动主轴，才是「晚成」的关键信号。','一时快慢不决定一生，判断要回到本命结构与连续大限，不凭单年下结论。'],
 enLog:['First read the natal axis stars: reserved, accumulating types such as Tian Fu, Tian Liang and Tai Yin carry more late-opening foundation.','Then see whether early decades accumulate resources and ability; opening late is not idle waiting.','Later decades strengthening in the triple-direction with transformations activating the axis are the key signal of late success.','Momentary speed does not decide a life; judge from the natal structure and consecutive decades rather than a single year.'],
 cnStep:['先定本命主轴星，看它的性质偏早发还是晚发','再逐段看中青年大限是在积累还是在消耗','重点看后半段大限三方是否转强、四化有无引动','把「晚发的底子」和「实际的积累」分开核对','若确属晚成型，把力气放在持续积累、不被快慢扰乱','若只是没行动，就别用晚成安慰自己'],
 enStep:['First set the natal axis stars and see whether their nature opens early or late','Then read early decades stage by stage to see accumulation or consumption','Focus on whether later decades strengthen in the triple-direction with transformations','Check late-opening foundation and actual accumulation separately','If genuinely late-blooming, put effort into steady accumulation without being disturbed by speed','If simply inactive, do not comfort yourself with late success'],
 cnMis:['把大器晚成当不行动的借口','只看一时快慢就定一生，不看连续大限','看到内敛星就断言晚成，忽略了有没有真积累'],
 enMis:['Using late blooming as an excuse for inaction','Judging a life from momentary speed without consecutive decades','Assuming reserved stars mean late success while ignoring real accumulation'],
 cnClose:'看懂大器晚成，不是给自己找台阶，而是理解「扎根期」和「收获期」各有节奏。该积累时沉住气，后段的强运才接得住。',
 enClose:'Reading late blooming is not an excuse but understanding that root-laying and harvest have their own rhythms. Stay steady in accumulation, and the later strong luck can be caught.'}
];
