// 2026-10-01 调研驱动 第4组：紫府财/机阴财/武相财/同阴财/同梁财/武破子/蜚廉命/蜚廉官 8篇
module.exports=[
{cat:'zhuxing',slug:'ziwei-ziwei-tianfu-zai-caibogong',focus:'紫微天府在财帛宫',focusEn:'Zi Wei and Tian Fu together in the Wealth Palace',
 cnT:'紫微天府同在财帛宫：赚钱有主位、留钱有库藏，怎么把财管稳',
 enT:'Zi Wei and Tian Fu in the Wealth Palace: Earning from a Leading Place and Keeping It in the Treasury',
 cnD:'财帛宫看现金流与理财方式，紫微主主导统筹、天府主守藏厚实，两星同落在这里，赚钱有格局、管钱有章法，适合管理资金、经营大盘与稳健理财。风险是保守、面子消费与孤高，关键是在守财之外让钱流动、生息并适度分享。',
 enD:'The Wealth Palace reads cash flow and how one manages money. Zi Wei leads and coordinates while Tian Fu stores and steadies, so together one earns with breadth and manages with order, suiting fund management, large operations and steady finance. The risk is conservatism, face-related spending and proud isolation, so the key is letting money move and grow alongside keeping it, and sharing appropriately.',
 cnL:'紫府在财帛的人，跟钱打交道常有主心骨：既能把钱赚得有格局，也能把账管得稳，只是把库看得太紧时，容易让钱只守不转、也为面子花钱。',
 enL:'People with Zi Wei and Tian Fu in the Wealth Palace handle money with a clear center, able both to earn with breadth and keep the books steady; when the treasury is guarded too tightly, money only sits instead of moving and gets spent on face.',
 cnA:'这个问题在问：紫府在财帛是什么理财路数。要先理解财帛看现金流，再看两星的主导和守藏怎么配合。',
 enA:'The question is the financial style with Zi Wei and Tian Fu in the Wealth Palace. Understand it reads cash flow, then see how leading and storing combine.',
 cnLog:['紫微在财帛，主赚钱有主导权、有格局，容易在资金和资源上牵头，也在意体面。','天府在财帛，主善守财、会管理、家底厚，能把钱留住、把库养满。','两星同宫是「能赚也能守」：见禄存化禄与辅佐星，财大气稳，适合管大钱、做大盘。','见煞忌或空劫大耗，则易因面子、独断或守财过紧而生折损，流动与配置要用心。'],
 enLog:['Zi Wei in the Wealth Palace gives leadership and breadth in earning, often initiating with funds and resources while caring about dignity.','Tian Fu there gives skill at keeping money and managing, with solid reserves and the ability to store wealth.','Together they both earn and keep: with Lu Cun, Hua Lu and supporting stars the finances are large and steady, suiting managing big money and operations.','With malefics, void stars or Great Expenditure, loss follows from face, one-sided decisions or over-tight guarding, so movement and allocation need care.'],
 cnStep:['先确认财帛宫是紫微天府同宫，并看两星亮度','看现金流和资产现状，分清赚、留、增值三件事','发挥统筹长处，把收入、储蓄、投资做整体规划','避免为面子和人情花钱，给大额支出设规则','让守财之外的钱合理流动、生息，并适度分享','结合大限流年判断财务引动阶段，再决定进取或稳守'],
 enStep:['First confirm Zi Wei and Tian Fu share the Wealth Palace and check their brightness','Read cash flow and assets, separating earning, keeping and growing','Use coordination to plan income, savings and investment as a whole','Avoid spending on face and obligations, with rules for large expenses','Let money beyond the savings move and grow sensibly, and share appropriately','With the decade and year, decide whether to advance or hold as finance is activated'],
 cnMis:['把紫府在财帛只当成「会有钱、财大」，忽略管理','只守不流动，钱库越捂越死','为面子、人情和体面花钱，把格局花成损耗'],
 enMis:['Taking Zi Wei-Tian Fu in the Wealth Palace only as becoming wealthy while ignoring management','Only storing without movement until the treasury stagnates','Spending on face, obligations and dignity until breadth becomes loss'],
 cnClose:'紫府在财帛给的是一条能赚、能守、也能管的财路。把整体规划做起来、让钱合理流动并去掉面子消费，财才会大而稳。这里不构成投资建议，具体配置以持牌机构和正规说明为准。',
 enClose:'Zi Wei and Tian Fu in the Wealth Palace give a path that earns, keeps and manages. Building a whole plan, letting money move sensibly and removing face spending make wealth large and steady. This is not investment advice; for any allocation, rely on licensed institutions and official disclosures.'},

{cat:'zhuxing',slug:'ziwei-tianji-taiyin-zai-caibogong',focus:'天机太阴在财帛宫',focusEn:'Tian Ji and Tai Yin together in the Wealth Palace',
 cnT:'天机太阴同在财帛宫：赚钱靠策划和细致，怎么把脑力变成稳定收入',
 enT:'Tian Ji and Tai Yin in the Wealth Palace: Earning Through Planning and Care, Turning Thought Into Steady Income',
 cnD:'天机善策划应变、太阴细腻懂守财，两星同在财帛，赚钱靠脑子、专业与细致，适合策划、设计、文职、咨询及间接财、技术财。风险是想法多变、过手财、决断慢，关键是把脑力收成稳定的收入结构和留存习惯。',
 enD:'Tian Ji plans and adapts while Tai Yin is refined and careful with money. Together in the Wealth Palace they earn through thought, expertise and care, suiting strategy, design, office work, consulting and indirect or skill-based income. The risk is shifting ideas, money passing through and slow decisions, so the key is gathering thought into a steady income structure and savings habit.',
 cnL:'机阴在财帛的人，赚钱常有巧劲：靠方案、专业和细致吃饭，路子活；只是想法一多、变动一快，钱容易过手、也容易在反复权衡里错过。',
 enL:'People with Tian Ji and Tai Yin in the Wealth Palace earn with ingenuity, living on plans, expertise and care with lively routes; when ideas multiply and change speeds up, money passes through and gets lost in weighing.',
 cnA:'这个问题在问：机阴在财帛是什么赚钱方式。要先理解财帛看现金流，再看两星的策划和守财怎么落地。',
 enA:'The question is the earning style with Tian Ji and Tai Yin in the Wealth Palace. Understand it reads cash flow, then see how planning and carefulness land.',
 cnLog:['天机在财帛，主靠智慧、策划和应变赚钱，办法多、信息灵，适合技术与脑力收入。','太阴在财帛，主间接财、稳定财与守财力，靠细致、审美和长期积累得财。','两星同宫是「脑力＋细致」：见禄权科与吉曜，专业容易变现、收入稳。','见煞忌则易多变、过手、因想太多而错过，固定留存和决断要练。'],
 enLog:['Tian Ji in the Wealth Palace gives earning through wisdom, planning and adaptiveness, with many approaches and lively information, suiting skill and intellectual income.','Tai Yin there gives indirect and steady income and the ability to keep money, earning through care, taste and long-term accumulation.','Together they mean thought plus refinement: with Lu, Quan, Ke and auspicious stars expertise monetizes and income steadies.','With malefics and Ji, change, money passing through and missed chances from overthinking follow, so fixed savings and deciding must be practiced.'],
 cnStep:['先确认财帛宫是天机太阴同宫，并看两星亮度','把收入来源和技能对到一两个稳定方向','给想法设变现路径，避免只停在方案阶段','建立自动留存和预算习惯，把过手财留住','练到点就定、边做边调，减少反复权衡','结合大限流年判断收入机会阶段，集中投入'],
 enStep:['First confirm Tian Ji and Tai Yin share the Wealth Palace and check their brightness','Match income sources and skills to one or two steady directions','Give ideas a path to monetization rather than leaving them as plans','Build automatic savings and a budget to keep money that passes through','Practice deciding on schedule and adjusting while doing, reducing endless weighing','With the decade and year, concentrate effort when income opportunity is activated'],
 cnMis:['把机阴在财帛只当成「靠脑子赚钱」，忽略留存','想法多变、方案多，钱在变动里过手','只想不定、只算不做，收入稳不下来'],
 enMis:['Taking Tian Ji-Tai Yin in the Wealth Palace only as earning through thought while ignoring savings','Shifting ideas and many plans until money passes through in the change','Only thinking and calculating without acting, so income never steadies'],
 cnClose:'机阴在财帛给的是一条靠脑力和细致赚钱的路。把专业收成稳定方向、把留存自动化并练果断，巧劲才会变成持续而稳的收入。',
 enClose:'Tian Ji and Tai Yin in the Wealth Palace give a path that earns through thought and care. Gathering expertise into a steady direction, automating savings and practicing decisiveness turns ingenuity into lasting, stable income.'},

{cat:'zhuxing',slug:'ziwei-wuqu-tianxiang-zai-caibogong',focus:'武曲天相在财帛宫',focusEn:'Wu Qu and Tian Xiang together in the Wealth Palace',
 cnT:'武曲天相同在财帛宫：赚钱务实讲规矩，怎么把正派经营做成财',
 enT:'Wu Qu and Tian Xiang in the Wealth Palace: Practical, Principled Earning and Turning Upright Business Into Wealth',
 cnD:'武曲务实讲执行、天相正派懂协调，两星同在财帛，赚钱靠规则、专业与信誉，适合金融、管理、代理、财政与制度化经营。风险是规则刚硬、财务压力与因印绶（担保、名分）生累，关键是把规矩立清、把边界守住。',
 enD:'Wu Qu is pragmatic and execution-oriented while Tian Xiang is upright and good at coordination. Together in the Wealth Palace they earn through rules, expertise and reputation, suiting finance, management, agency, fiscal work and institutional business. The risk is rigid rules, financial pressure and burdens through guarantees or titles, so the key is keeping rules clear and boundaries held.',
 cnL:'武相在财帛的人，赚钱讲规矩、重信誉，做事让人放心，适合跟制度和资金打交道；只是规则一硬、担保名分一多，容易把自己绑进财务压力里。',
 enL:'People with Wu Qu and Tian Xiang in the Wealth Palace earn by rules and reputation, dependable in work and suited to institutions and funds; when rules harden and guarantees or titles multiply, they can be tied into financial pressure.',
 cnA:'这个问题在问：武相在财帛是什么赚钱方式。要先理解财帛看现金流，再看两星的务实和正派怎么化成信誉之财。',
 enA:'The question is the earning style with Wu Qu and Tian Xiang in the Wealth Palace. Understand it reads cash flow, then see how pragmatism and integrity become reputational wealth.',
 cnLog:['武曲在财帛，主务实、讲规则、执行强，靠专业和结果赚钱。','天相在财帛，主正派、懂协调、重信誉，适合代理、管理与财政类事。','两星同宫是「务实＋正派」：见禄存化禄与吉曜（如财荫夹印），经营稳、信誉好、财源正。','见煞忌则易规则压人、担保受累、财务纠纷，合同与边界要格外清楚。'],
 enLog:['Wu Qu in the Wealth Palace gives pragmatism, rules and strong execution, earning through expertise and results.','Tian Xiang there gives integrity, coordination and reputation, suiting agency, management and fiscal work.','Together they mean practical plus upright: with Lu Cun, Hua Lu and auspicious stars the business is steady, reputable and clean.','With malefics and Ji, rigid rules, guarantee burdens and financial disputes follow, so contracts and boundaries must be especially clear.'],
 cnStep:['先确认财帛宫是武曲天相同宫，并看两星亮度','把收入、合同、担保和名分逐条看清','赚钱按规则和信誉推进，不碰来路不清的钱','涉及担保、合伙、代理先立书面合同和边界','给财务压力留缓冲（储备、保险、现金流）','结合大限流年判断财运阶段，再决定进取'],
 enStep:['First confirm Wu Qu and Tian Xiang share the Wealth Palace and check their brightness','Go through income, contracts, guarantees and titles one by one','Earn by rules and reputation, avoiding money of unclear origin','For guarantees, partnerships and agency, set written contracts and boundaries first','Keep a buffer for financial pressure through reserves, insurance and cash flow','With the decade and year, decide whether to advance as wealth is activated'],
 cnMis:['把武相在财帛只当成「会理财、有钱」，忽略规则和边界','好面子做担保、讲名分，结果替人受累','只凭规矩硬来，合同不清反而生纠纷'],
 enMis:['Taking Wu Qu-Tian Xiang in the Wealth Palace only as good with money while ignoring rules and boundaries','Giving guarantees and caring about titles, ending up carrying others’ burdens','Acting only on rigid rules with unclear contracts, which breeds disputes'],
 cnClose:'武相在财帛给的是一条务实、正派、重信誉的财路。把合同和边界立清、把担保和名分看住，规矩经营会走得很稳。涉及合同的事以书面约定和专业律师意见为准。',
 enClose:'Wu Qu and Tian Xiang in the Wealth Palace give a practical, upright, reputation-driven path. Keeping contracts and boundaries clear and watching guarantees and titles makes principled business steady. For contractual matters, rely on written agreements and professional legal advice.'},

{cat:'zhuxing',slug:'ziwei-tiantong-taiyin-zai-caibogong',focus:'天同太阴在财帛宫',focusEn:'Tian Tong and Tai Yin together in the Wealth Palace',
 cnT:'天同太阴同在财帛宫：赚钱温和求稳，怎么把日子过成细水长流',
 enT:'Tian Tong and Tai Yin in the Wealth Palace: Gentle, Steady Earning and a Long, Even Flow',
 cnD:'天同温和主福气、太阴细腻主守财，两星同在财帛，赚钱不偏好猛冲，适合服务、文教、女性向市场与稳定薪水、间接财，现金流偏平稳、也愿意储蓄。风险是安于现状、偏被动、进账慢，关键是在稳的基础上设增长目标。',
 enD:'Tian Tong is warm and easygoing while Tai Yin is refined and careful with money. Together in the Wealth Palace they do not favor aggressive earning, suiting services, education, markets oriented toward women, steady salaries and indirect income, with even cash flow and a willingness to save. The risk is complacency, passivity and slow growth, so the key is setting growth goals on top of stability.',
 cnL:'同阴在财帛的人，跟钱的关系偏松弛：不爱冒险、愿意慢慢赚、稳稳存，日子有安全感；只是太安于舒适时，进账和冲劲会偏慢。',
 enL:'People with Tian Tong and Tai Yin in the Wealth Palace have a relaxed relationship with money, disliking risk and willing to earn slowly and save steadily for security; when too comfortable, income and drive run slow.',
 cnA:'这个问题在问：同阴在财帛是什么赚钱方式。要先理解财帛看现金流，再看两星的温和与守财怎么配上增长。',
 enA:'The question is the earning style with Tian Tong and Tai Yin in the Wealth Palace. Understand it reads cash flow, then see how gentleness and carefulness pair with growth.',
 cnLog:['天同在财帛，主和气生财、服务生财，收入来得不猛但持续，人情和口碑有助力。','太阴在财帛，主稳定财、间接财与强守财力，擅长储蓄和长期安排。','两星同宫是「温和＋守财」：见禄存化禄与吉曜，现金流稳、家底渐厚。','见煞忌则易安于现状、依赖、因心软破财，增长目标和边界要立。'],
 enLog:['Tian Tong in the Wealth Palace gives earning through harmony and service, with income that arrives gently but steadily, helped by goodwill and reputation.','Tai Yin there gives steady and indirect income and strong saving ability, skilled at long-term arrangements.','Together they mean gentle plus careful: with Lu Cun, Hua Lu and auspicious stars cash flow steadies and reserves grow.','With malefics and Ji, complacency, dependence and loss through soft-heartedness follow, so growth goals and boundaries are needed.'],
 cnStep:['先确认财帛宫是天同太阴同宫，并看两星亮度','把稳定收入、储蓄和保障先安排好','在稳的基础上设一个可达成的增长目标','发挥服务和口碑长处，拓展稳定客源','给心软借钱、人情支出设边界','结合大限流年判断财运阶段，稳中求进'],
 enStep:['First confirm Tian Tong and Tai Yin share the Wealth Palace and check their brightness','Arrange steady income, savings and protection first','Set an achievable growth goal on top of stability','Use service and reputation to build a steady client base','Set boundaries around lending from sympathy and social spending','With the decade and year, seek progress within steadiness as wealth is activated'],
 cnMis:['把同阴在财帛只当成「财稳、有福」，忽略增长','安于舒适、被动等待，进账越来越慢','心软借钱、为人情花钱，把储蓄漏掉'],
 enMis:['Taking Tian Tong-Tai Yin in the Wealth Palace only as steady, fortunate money while ignoring growth','Staying comfortable and waiting passively until income slows','Lending from sympathy and spending on obligations until savings leak'],
 cnClose:'同阴在财帛给的是一条温和、稳定、会储蓄的财路。先把安稳垫厚、再立增长目标和边界，细水长流的日子会越过越宽裕。',
 enClose:'Tian Tong and Tai Yin in the Wealth Palace give a gentle, steady path that saves. Building the safety base and then setting growth goals and boundaries makes the long, even flow more abundant over time.'},

{cat:'zhuxing',slug:'ziwei-tiantong-tianliang-zai-caibogong',focus:'天同天梁在财帛宫',focusEn:'Tian Tong and Tian Liang together in the Wealth Palace',
 cnT:'天同天梁同在财帛宫：赚钱随缘重服务，怎么把清高变成稳定的财源',
 enT:'Tian Tong and Tian Liang in the Wealth Palace: Earning Through Service Rather Than Strain',
 cnD:'天同和气、天梁荫庇讲原则，两星同在财帛，赚钱偏随缘、重口碑与服务，适合文教、公益、咨询、稳定体制与照顾型行业，财来得不猛但相对干净、有人帮。风险是被动清高、不积极争取，关键是在随缘之外主动经营收入。',
 enD:'Tian Tong is harmonious while Tian Liang is protective and principled. Together in the Wealth Palace earning leans to ease, reputation and service, suiting education, public-good work, consulting, stable institutions and caring fields, with income that arrives gently but stays relatively clean and supported. The risk is passive detachment from money, so the key is actively managing income alongside letting things come.',
 cnL:'同梁在财帛的人，不太愿意为钱折腰，赚钱讲情分也讲原则，口碑好、贵人不少；只是太随缘、太清高时，容易该争取的不争取、收入偏紧。',
 enL:'People with Tian Tong and Tian Liang in the Wealth Palace are reluctant to bend for money, earning with both feeling and principle, with good reputation and helpful people; when too detached, they fail to pursue what is due and income tightens.',
 cnA:'这个问题在问：同梁在财帛是什么赚钱方式。要先理解财帛看现金流，再看两星的服务和荫庇怎么配上主动经营。',
 enA:'The question is the earning style with Tian Tong and Tian Liang in the Wealth Palace. Understand it reads cash flow, then see how service and protection pair with active management.',
 cnLog:['天同在财帛，主和气、服务与随缘的财，收入持续但不猛。','天梁在财帛，主荫庇之财、贵人之财，讲原则也能逢凶化吉。','两星同宫是「服务＋荫庇」：见禄存化禄与吉曜，财源干净、有人托底。','见煞忌则易被动、清高、因原则错过机会，主动报价和争取要练。'],
 enLog:['Tian Tong in the Wealth Palace gives harmonious, service-oriented and easygoing income that is steady but not aggressive.','Tian Liang there gives sheltered and patron-supported wealth, principled and able to turn difficulty around.','Together they mean service plus protection: with Lu Cun, Hua Lu and auspicious stars the income is clean and supported.','With malefics and Ji, passivity and detachment make one miss chances, so quoting prices and pursuing must be practiced.'],
 cnStep:['先确认财帛宫是天同天梁同宫，并看两星亮度','把口碑、服务和贵人资源对到收入上','主动报价、开票、谈条件，克服不好意思','给收入做稳定安排（合同、续约、固定客户）','在原则之内积极争取，而不是坐等缘来','结合大限流年判断财运阶段，主动把握'],
 enStep:['First confirm Tian Tong and Tian Liang share the Wealth Palace and check their brightness','Connect reputation, service and helpful people to income','Quote prices, bill and negotiate terms actively, overcoming awkwardness','Build steady income through contracts, renewals and regular clients','Pursue actively within your principles rather than waiting for things to come','With the decade and year, grasp the wealth stage actively'],
 cnMis:['把同梁在财帛只当成「财干净、有人帮」，忽略主动经营','太清高、不报价不争取，收入偏紧','把随缘当不作为，机会来了也不接'],
 enMis:['Taking Tian Tong-Tian Liang in the Wealth Palace only as clean, supported money while ignoring active management','Staying too detached to quote or pursue, tightening income','Mistaking ease for inaction and not taking chances when they arrive'],
 cnClose:'同梁在财帛给的是一条重服务、讲原则、有荫庇的财路。把口碑接到主动经营上、该争取时争取，干净的财源一样可以稳定而宽裕。',
 enClose:'Tian Tong and Tian Liang in the Wealth Palace give a service-oriented, principled and protected path. Connecting reputation to active management and pursuing what is due makes a clean income steady and abundant.'},

{cat:'liuqin',slug:'ziwei-wuqu-pojun-zai-zinvgong',focus:'武曲破军在子女宫',focusEn:'Wu Qu and Po Jun together in the Children Palace',
 cnT:'武曲破军同在子女宫：孩子务实又有变革劲，怎么给空间又立规矩',
 enT:'Wu Qu and Po Jun in the Children Palace: A Practical, Transformative Child and Balancing Space with Rules',
 cnD:'子女宫看子女缘分与亲子模式，武曲务实讲规则、破军敢变敢重启，两星同落在这里，孩子多是独立、能吃苦、有主见、爱破旧局的类型，行动力强。风险是硬碰、变动多、聚少离多或为孩子花费大，关键是给足空间、也把规矩和陪伴立住。',
 enD:'The Children Palace reads the bond with children and the parenting pattern. Wu Qu is practical and rule-oriented while Po Jun dares to change and restart, so children tend to be independent, able to bear hardship, opinionated and eager to break old patterns, with strong drive. The risk is head-on clashes, frequent change, time apart or large spending on the child, so the key is giving room while holding rules and presence.',
 cnL:'武破在子女的人，孩子常比同龄人早熟、有主意，肯动手也敢改变，不太服管；越是这样，越要把硬碰换成引导，把规矩立在前面、把陪伴留足。',
 enL:'People with Wu Qu and Po Jun in the Children Palace often have a child who is mature and opinionated beyond their years, willing to act and change and not easy to control; the more this is so, the more one should replace clashing with guidance, setting rules early and staying present.',
 cnA:'这个问题在问：武破在子女是什么亲子模式。要先理解子女宫也看作品与后辈，再看两星的务实和变革怎么化成引导。',
 enA:'The question is the parenting pattern with Wu Qu and Po Jun in the Children Palace. Understand it also covers creations and juniors, then see how pragmatism and transformation become guidance.',
 cnLog:['武曲在子女，主孩子务实、能吃苦、讲规则，做事有执行力。','破军在子女，主孩子独立、敢变、爱破旧，成长里变动和主见都多。','两星同宫是「硬中带变」：孩子行动力强，见禄存化禄与吉曜，能把这股劲做成事。','见煞忌则易硬碰、聚少离多、为孩子花费或操心，沟通与空间要用心。'],
 enLog:['Wu Qu in the Children Palace gives a practical, hardy, rule-oriented child with execution.','Po Jun there gives an independent, changing, convention-breaking child with strong opinions and transitions in growth.','Together they mean firm with change: the child has strong drive, and with Lu Cun, Hua Lu and auspicious stars that energy becomes accomplishment.','With malefics and Ji, head-on clashes, time apart and large spending or worry follow, so communication and space need care.'],
 cnStep:['先确认子女宫是武曲破军同宫，并看两星亮度','把孩子的独立和变革劲看成优点而非麻烦','规矩立在前面、讲清原因，避免硬碰压制','给足尝试和自主空间，边做边引导','把陪伴和沟通固定下来，减少聚少离多','结合大限流年判断亲子关系引动阶段，调整投入'],
 enStep:['First confirm Wu Qu and Po Jun share the Children Palace and check their brightness','See the child’s independence and drive as a strength rather than trouble','Set rules early with clear reasons rather than suppressing through clashes','Give ample room to try and decide, guiding while doing','Make presence and communication regular to reduce time apart','With the decade and year, adjust involvement as the parent-child bond is activated'],
 cnMis:['把武破在子女只当成「孩子难管」，忽略其独立和能干','硬碰压制，反而激起更强的叛逆','只顾立规矩或忙事业，陪伴和沟通缺位'],
 enMis:['Taking Wu Qu-Po Jun in the Children Palace only as a difficult child while ignoring independence and capability','Suppressing through clashes, which provokes stronger rebellion','Holding only rules or staying busy with work while presence and communication are missing'],
 cnClose:'武破在子女给的是一个务实、独立、有变革劲的孩子。把硬碰换成引导、规矩和陪伴并立，这股行动力会成为他将来最能成事的底气。',
 enClose:'Wu Qu and Po Jun in the Children Palace give a practical, independent, transformative child. Replacing clashing with guidance and holding both rules and presence turns that drive into the foundation for real accomplishment later.'},

{cat:'fuzhu',slug:'ziwei-feilian-zai-minggong',focus:'蜚廉在命宫',focusEn:'Fei Lian in the Life Palace',
 cnT:'蜚廉在命宫：心思细、感受敏，怎么把「怕流言」活成观察力',
 enT:'Fei Lian in the Life Palace: A Refined, Sensitive Nature That Turns Fear of Rumor Into Insight',
 cnD:'蜚廉主口舌流言、孤僻与细腻，落命宫的人感受敏锐、观察力强、做事认真，也容易把外界的闲言放在心上、显得不太合群。它不主大凶，关键是把敏感转化为细致、研究与调查的能力，并主动建立稳固的自我评价。',
 enD:'Fei Lian governs rumors, solitude and refinement. In the Life Palace one is sensitive, observant and conscientious, yet easily takes outside chatter to heart and can seem reserved. It does not bring major misfortune; the key is turning sensitivity into thoroughness, research and investigative skill, and building steady self-regard.',
 cnL:'蜚廉坐命的人，常是那种心里门儿清、嘴上不多说的人，细节逃不过他，也容易被几句闲话困扰；把这份细劲用在专业上，反而比旁人钻得深。',
 enL:'People with Fei Lian in the Life Palace often understand clearly while saying little, with no detail escaping them, yet they can be troubled by a few words of gossip; directing that refinement into expertise lets them go deeper than others.',
 cnA:'这个问题在问：蜚廉坐命是什么性格、怎么扬长。要先分清蜚廉主的是细腻与流言感受，再看吉星是帮转化、煞忌是增孤僻。',
 enA:'The question is the temperament of Fei Lian in the Life Palace and how to use it. First separate its refinement from its sensitivity to rumor, then see whether auspicious stars aid conversion or malefics add solitude.',
 cnLog:['蜚廉属阴火，主细腻、观察力与认真，也主一丝孤僻和对流言的在意。','落命宫者感受力强、重细节，适合研究、调查、质检、技术等需要耐心和眼力的事。','见吉星与主星有力，敏感化成专业深度与严谨；见煞忌，则易多疑、心神不宁、自我孤立。','蜚廉力量不重，不决定一生吉凶，自我评价稳定、圈子干净时它几乎不碍事。'],
 enLog:['Fei Lian is yin fire, governing refinement, observation and conscientiousness, along with a touch of solitude and concern over rumor.','In the Life Palace one feels deeply and values detail, suiting research, investigation, quality control and technical work that needs patience and a sharp eye.','With auspicious stars and a strong major star, sensitivity becomes professional depth and rigor; with malefics and Ji, suspicion, unease and self-isolation follow.','Fei Lian is light and does not decide a life’s fortune; with stable self-regard and a clean circle it barely interferes.'],
 cnStep:['先确认命宫有蜚廉，并看同宫主星是谁','把在意流言的精力转成观察、记录和研究','主动筛选圈子，远离爱搬弄是非的人和场合','建立不依赖外界评价的自我肯定方式','练习表达和连接，避免把孤僻越养越重','结合大限流年，看敏感被引动的阶段再调整'],
 enStep:['First confirm Fei Lian is in the Life Palace and see which major star shares it','Turn the energy spent on rumor into observation, note-taking and research','Deliberately choose your circle and stay away from people and settings that gossip','Build self-affirmation that does not depend on outside opinion','Practice expression and connection so solitude does not deepen','With the decade and year, adjust when sensitivity is activated'],
 cnMis:['把蜚廉坐命只当成「命犯小人、是非多」，吓自己','为躲流言把自己封闭，孤僻越养越重','把敏感当缺点硬压，观察力也一起被埋没'],
 enMis:['Taking Fei Lian in the Life Palace only as being fated to meet petty people and disputes, frightening oneself','Closing off to avoid rumor until solitude deepens','Forcing sensitivity down and burying the observation along with it'],
 cnClose:'蜚廉坐命给的是一份细、一份敏，不是一道凶符。把观察力用在专业上、把圈子和自我评价立稳，你会比谁都看得清、也钻得深。',
 enClose:'Fei Lian in the Life Palace gives refinement and sensitivity rather than a bad omen. Using observation in expertise and steadying the circle and self-regard lets you see clearly and go deep.'},

{cat:'fuzhu',slug:'ziwei-feilian-zai-guanlugong',focus:'蜚廉在官禄宫',focusEn:'Fei Lian in the Career Palace',
 cnT:'蜚廉在官禄宫：职场上防小是非，怎么把谨慎变成专业严谨',
 enT:'Fei Lian in the Career Palace: Guarding Against Small Workplace Gossip and Turning Care Into Professional Rigor',
 cnD:'蜚廉落官禄宫，职场上容易遇到说不清的小是非、暗中的闲话或流程上的小别扭，也主做事细、讲规矩、能查问题。它不主事业破败，关键是把谨慎用在流程和质量上，沟通留痕、不传话，把专业口碑做起来。',
 enD:'Fei Lian in the Career Palace can bring small workplace disputes, quiet gossip or minor process friction, while also indicating careful, rule-based work and an ability to spot problems. It does not mean career failure; the key is using care for process and quality, keeping communication documented, not passing rumors and building a professional reputation.',
 cnL:'蜚廉在官禄的人，职场上常是那个把细节和漏洞看在眼里的人，认真可靠；只是闲话和小别扭一多，容易分心、也影响心情。',
 enL:'People with Fei Lian in the Career Palace are often the ones who notice details and gaps at work, serious and dependable; when gossip and friction grow, they get distracted and their mood is affected.',
 cnA:'这个问题在问：蜚廉在官禄要注意什么。要先分清它主的是小是非与细致，再看吉星助严谨、煞忌增困扰。',
 enA:'The question is what to watch with Fei Lian in the Career Palace. First separate its small disputes from its refinement, then see whether auspicious stars aid rigor or malefics add trouble.',
 cnLog:['蜚廉在官禄，主职场小是非、暗中小话，也主流程上的细腻与检查力。','落此宫者做事认真、守规矩，适合质检、稽核、研究、合规与技术类岗位。','见吉星与主星有力，谨慎化成专业严谨和口碑；见煞忌，则易卷入闲话、情绪受扰。','蜚廉力量轻，不决定事业成败，沟通留痕、不参与传话时影响很小。'],
 enLog:['Fei Lian in the Career Palace brings small workplace disputes and quiet gossip, along with refinement and an eye for checking process.','There one works conscientiously and by rules, suiting quality control, audit, research, compliance and technical roles.','With auspicious stars and a strong major star, care becomes professional rigor and reputation; with malefics and Ji, one is drawn into gossip and emotional distraction.','Fei Lian is light and does not decide career success; with documented communication and no rumor-passing its effect is small.'],
 cnStep:['先确认官禄宫有蜚廉，并看同宫主星','把认真和检查力对到质量、流程和合规上','工作沟通尽量留痕，不口头传话、不参与八卦','遇到小是非先核对事实，不跟着情绪走','用专业成果说话，把口碑做扎实','结合大限流年判断职场引动阶段，理性应对'],
 enStep:['First confirm Fei Lian is in the Career Palace and see the sharing major star','Direct conscientiousness and checking toward quality, process and compliance','Keep work communication documented, neither relaying verbal messages nor joining gossip','When small disputes arise, check facts first rather than following emotion','Let professional results speak and build a solid reputation','With the decade and year, respond rationally as the workplace is activated'],
 cnMis:['把蜚廉在官禄只当成「职场犯小人」，影响心情','卷入传话和八卦，小事越搅越大','只防是非不用细致，专业长处没发挥'],
 enMis:['Taking Fei Lian in the Career Palace only as meeting petty people at work and letting it affect mood','Joining rumor-passing until small things grow','Only guarding against gossip without using refinement, wasting the strength'],
 cnClose:'蜚廉在官禄给的是一份职场上的细致和谨慎。把它用在质量与合规上、沟通留痕不传话，小是非碍不了事，专业口碑反而立得更稳。',
 enClose:'Fei Lian in the Career Palace gives refinement and care at work. Directing it to quality and compliance, documenting communication and not passing gossip lets small disputes fade while professional reputation grows steadier.'}
];
