// 2026-10-06 调研驱动 第4组：流年走星 2（禄存/天马）+ 太岁 2（害/刑）+ 应用 4（防骗/兼职/站队/债务）
module.exports=[
{cat:'liunian',slug:'ziwei-liunian-zou-lucun',focus:'流年走禄存',focusEn:'the annual chart passing through Lu Cun',
 cnT:'流年走禄存怎么看：财星当值的一年，利稳财守成',enT:'How to Read the Annual Chart Passing Through Lu Cun',
 cnD:'流年命宫走到禄存，财星当值，利稳财、储蓄、守成；但不是人人一样，仍要看本命财帛与三方四正，禄存逢空劫也可能是「看着有、抓不住」。',
 enD:'When the annual Life Palace passes through Lu Cun, the wealth star is on duty, favoring steady income, saving and preservation. But it is not the same for everyone; still read the natal Wealth Palace and triple-direction, as Lu Cun with emptiness or robbery can mean seeing it but not holding it.',
 cnL:'流年走禄存是「财星来敲门」，敲的是门不是金库；开不开得了门，要看本命的底子和三方的配合。',
 enL:'The annual chart passing Lu Cun is the wealth star knocking at the door, not opening the vault; whether the door opens depends on your natal foundation and trine support.',
 cnA:'有人见流年走禄存就以为一定发财，也有人逢空劫就说白搭；真正要看的是本命财帛能不能接得住这股财气。',
 enA:'Some assume passing Lu Cun guarantees a windfall, while others with emptiness or robbery say it is useless; the real test is whether the natal Wealth Palace can receive this wealth energy.',
 cnLog:['禄存主财、主稳、主守，流年走到代表这一年财星当值。','利储蓄、守成、稳健理财，不宜冒进投机。','逢化禄、化权会照，财气更实、机会更多。','逢地空、地劫、大耗会照，防「看着有、留不住」，仍以稳为主。'],
 enLog:['Lu Cun governs wealth, stability and preservation; the annual chart passing it means the wealth star is on duty this year.','It favors saving, preservation and steady finance, not aggressive speculation.','With Hua Lu or Hua Quan in the trine, the wealth is more real and opportunities more plentiful.','With Di Kong, Di Jie or Da Hao, guard seeing it but not holding it; stay steady.'],
 cnStep:['先定位流年命宫是否走到禄存','看本命财帛宫的底子，评估能不能接住财气','看流年三方四正有没有禄权科配合','数空劫、大耗等煞星，防财来财去','定策略：以稳财、储蓄为主，不冒进','叠大限，看这一年的财运在十年周期里的位置'],
 enStep:['First locate whether the annual Life Palace passes through Lu Cun','Read the natal Wealth Palace foundation to assess whether you can receive the wealth','Check the annual triple-direction for Lu Quan Ke support','Count emptiness, robbery and waste stars to guard money coming and going','Set strategy: prioritize steady income and saving, not speculation','Layer the decade to see where this year sits in the ten-year wealth cycle'],
 cnMis:['见流年走禄存就当一定发财、盲目投资','逢空劫就全盘否定，不看本命底子','只看流年不看大限和本命，层次不清'],
 enMis:['Assuming passing Lu Cun guarantees wealth and investing blindly','Negating everything with emptiness or robbery without reading the natal foundation','Reading only the annual chart without the decade and natal layers'],
 cnClose:'流年走禄存看的是「财星当值的一年怎么稳着接」。把本命底子、三方配合和煞星防漏都算上，稳财才不是一句空话。以上为命理倾向，不构成投资建议，以持牌机构和正规产品说明为准。',
 enClose:'Passing Lu Cun asks how to steadily receive a year when the wealth star is on duty. Factor in the natal foundation, trine support and guarding against leaks, and steady income is no longer empty talk. This is a cultural-tendency reference, not investment advice; defer to licensed institutions and official product terms.'},

{cat:'liunian',slug:'ziwei-liunian-zou-tianma',focus:'流年走天马',focusEn:'the annual chart passing through Tian Ma',
 cnT:'流年走天马怎么看：奔忙多动的一年，把奔波变成机会',enT:'How to Read the Annual Chart Passing Through Tian Ma',
 cnD:'流年命宫走到天马，主奔忙、多动、利外出与变化；把奔波变成机会要看本命迁移与三方，逢禄则动中生财，防空忙、劳损与两头跑。',
 enD:'When the annual Life Palace passes through Tian Ma, it brings busyness, movement and favors travel and change. Whether the running becomes opportunity depends on the natal Travel Palace and trine; with Lu it generates wealth through movement, so guard against empty busyness, exhaustion and running back and forth.',
 cnL:'流年走天马是「脚不停」的一年，动本身不是好坏，关键是动的方向对不对、有没有带着禄走。',
 enL:'Passing Tian Ma is a year of constant motion; movement itself is neither good nor bad, the key is whether the direction is right and whether Lu travels with it.',
 cnA:'有人见天马就怕奔波，也有人见天马就以为动就有财；真正要看的是动的方向和有没有禄权科跟着。',
 enA:'Some fear busyness when seeing Tian Ma, while others assume movement always brings wealth; the real test is the direction of movement and whether Lu Quan Ke travel along.',
 cnLog:['天马主动、主奔忙、主外出变化，流年走到代表这一年动象明显。','利出差、搬迁、拓展、换环境，把变化变成机会。','逢化禄、禄存会照，动中生财、越动越有。','逢煞星或空劫，防空忙、劳损、两头跑而无所得。'],
 enLog:['Tian Ma governs movement, busyness and travel change; the annual chart passing it means obvious movement this year.','It favors business trips, relocation, expansion and changing environment, turning change into opportunity.','With Hua Lu or Lu Cun in the trine, it generates wealth through movement, the more you move the more you gain.','With malefics or emptiness, guard empty busyness, exhaustion and running back and forth for nothing.'],
 cnStep:['先定位流年命宫是否走到天马','看本命迁移宫，评估在外的底子和机会','看流年三方有没有禄、权、科配合动象','数煞星与空劫，防空忙和劳损','定策略：主动选方向，不被动被推着跑','把外出、变化安排在精力允许的范围，防透支'],
 enStep:['First locate whether the annual Life Palace passes through Tian Ma','Read the natal Travel Palace to assess your foundation and opportunity away from home','Check the annual trine for Lu, Quan, Ke supporting the movement','Count malefics and emptiness to guard empty busyness and exhaustion','Set strategy: choose direction actively rather than being pushed passively','Keep travel and change within your energy capacity to guard against overdraw'],
 cnMis:['见天马就怕奔波、自我限制','以为动就有财，不看有没有禄跟着','被动被推着跑，不选方向、防空忙'],
 enMis:['Fearing busyness at the sight of Tian Ma and limiting yourself','Assuming movement always brings wealth without checking whether Lu travels along','Being pushed passively, not choosing direction and failing to guard empty busyness'],
 cnClose:'流年走天马看的是「多动的一年怎么跑出机会」。选对方向、带着禄走、防住空忙，奔波才不是白累，而是动中生财的路。',
 enClose:'Passing Tian Ma asks how to run toward opportunity in a busy year. Choose the right direction, travel with Lu and guard against empty busyness, so the running is not wasted but a path to wealth through movement.'},

{cat:'liunian',slug:'ziwei-hai-taishui-ruhe-kan',focus:'害太岁',focusEn:'harming the Tai Sui',
 cnT:'害太岁怎么看：2026丑午相害，主人际暗耗与口舌误会',enT:'How to Read Harming the Tai Sui in 2026',
 cnD:'2026丙午年，丑牛与午马相害，主人际暗耗、口舌误会、合作不顺；害太岁是提醒不是定灾，把话说开、守住书面契约、关键决策避不利月份即可。',
 enD:'In 2026 Bing Wu, the Chou ox and Wu horse harm each other, bringing hidden interpersonal drain, verbal misunderstanding and cooperation friction. Harming Tai Sui is a reminder, not a destined disaster; speak openly, keep written contracts and avoid key decisions in unfavorable months.',
 cnL:'害太岁像「暗中有人扯袖子」，不是正面冲撞，而是说不清的误会和暗耗；把话挑明、把事落纸，大部分能化解。',
 enL:'Harming Tai Sui is like someone quietly tugging your sleeve, not a head-on collision, but vague misunderstanding and hidden drain; speaking plainly and putting things in writing resolves most of it.',
 cnA:'有人见害太岁就慌，也有人完全不当回事；真正要做的是在人际和合作上多留个心眼，不是什么都不做。',
 enA:'Some panic at harming Tai Sui, while others ignore it entirely; what is needed is extra care in relationships and cooperation, not doing nothing.',
 cnLog:['2026丙午，午马值太岁，丑牛害太岁，主暗中的人际摩擦。','常见表现：误会、口舌、合作不顺、被人背后议论、小事扯皮。','化解要点：把话说开、不猜、守住书面契约、关键决策缓一缓。','害太岁只主一年加减，长期仍看本命与大限，不是定灾。'],
 enLog:['In 2026 Bing Wu, the Wu horse is on Tai Sui duty and the Chou ox harms it, bringing hidden interpersonal friction.','Common signs: misunderstanding, disputes, cooperation trouble, behind-the-back talk, petty quarrels.','Remedies: speak openly, do not guess, keep written contracts, and pause key decisions.','Harming Tai Sui only adjusts one year; the long term still depends on the natal chart and decade, not destined disaster.'],
 cnStep:['确认自己生肖是否在2026害太岁（丑牛）','理解害是暗中摩擦，不是正面冲','盘点当前重要合作和人际关系，提前沟通','把口头约定落实为书面合同','关键决策避开农历六月（未月）、十二月（丑月）等冲动月份','遇事对事不对人，不翻旧账、不冷战'],
 enStep:['Confirm whether your zodiac harms Tai Sui in 2026 (Chou ox)','Understand that harm is hidden friction, not a head-on clash','Review current important cooperations and relationships, communicate in advance','Put verbal agreements into written contracts','Avoid key decisions in months that stir conflict, such as the sixth and twelfth lunar months','Address issues not personalities, do not dredge up the past or give the silent treatment'],
 cnMis:['见害太岁就当定灾、什么都不敢做','完全不当回事、不做任何预防','把所有不顺都归罪于害太岁，不反思自己'],
 enMis:['Treating harming Tai Sui as destined disaster and daring to do nothing','Ignoring it entirely and taking no precautions','Blaming every setback on Tai Sui without self-reflection'],
 cnClose:'害太岁看的是「暗中的人际摩擦怎么提前化解」。把话说开、把事落纸、关键决策缓一缓，这一年的暗耗就能降到最低。犯太岁是提醒不是定灾。',
 enClose:'Harming Tai Sui asks how to resolve hidden interpersonal friction in advance. Speak openly, put things in writing and pause key decisions, and the hidden drain of this year can be minimized. Tai Sui is a reminder, not a destined disaster.'},

{cat:'liunian',slug:'ziwei-xing-taishui-ruhe-kan',focus:'刑太岁',focusEn:'punishing the Tai Sui',
 cnT:'刑太岁怎么看：2026午午自刑，主自我折磨与内耗',enT:'How to Read Punishing the Tai Sui in 2026',
 cnD:'2026丙午年，午马自刑（午午相刑），主自我折磨、内耗、钻牛角尖；刑太岁多是自己跟自己过不去，学会对事不对自己、规律作息、肯求助，比外求更有效。',
 enD:'In 2026 Bing Wu, the Wu horse self-punishes (Wu-Wu punishment), bringing self-torment, inner friction and overthinking. Punishing Tai Sui is mostly fighting oneself; learning to address issues not oneself, keeping regular routines and asking for help works better than seeking external solutions.',
 cnL:'刑太岁像「自己跟自己较劲」，外面没那么多敌人，是心里的结把自己困住了；解开的钥匙在自己手里。',
 enL:'Punishing Tai Sui is like competing with yourself; there are not that many enemies outside, it is the knot in your mind that traps you; the key to untying it is in your own hands.',
 cnA:'有人见刑太岁就怕出事，也有人把所有情绪都归罪于太岁；真正要做的是关注自己的心理状态和作息，而不是到处求符。',
 enA:'Some fear misfortune when punishing Tai Sui, while others blame every emotion on it; what is needed is attention to your own mental state and routines, not seeking charms everywhere.',
 cnLog:['2026丙午，午马自刑，主自我纠结、内耗、钻牛角尖。','常见表现：反复想同一件事、失眠、自责、对自己要求过高。','化解要点：对事不对自己、规律作息、运动、肯求助、不独自硬扛。','刑太岁只主一年加减，长期看本命与大限，不是定灾。'],
 enLog:['In 2026 Bing Wu, the Wu horse self-punishes, bringing self-entanglement, inner friction and overthinking.','Common signs: looping on the same issue, insomnia, self-blame, demanding too much of oneself.','Remedies: address issues not oneself, keep regular routines, exercise, ask for help and do not tough it out alone.','Punishing Tai Sui only adjusts one year; the long term depends on the natal chart and decade, not destined disaster.'],
 cnStep:['确认自己生肖是否在2026刑太岁（午马自刑）','理解刑多是自我纠结，不是外部灾难','留意睡眠、情绪和反复思虑的信号','建立规律作息和运动，用身体带动心理','遇到纠结的事，写下来或找人说，不独自钻牛角尖','对事不对自己，把「我不行」换成「这件事可以怎么做」'],
 enStep:['Confirm whether your zodiac punishes Tai Sui in 2026 (Wu horse self-punishment)','Understand that punishment is mostly self-entanglement, not external disaster','Watch for signals in sleep, emotion and looping thoughts','Establish regular routines and exercise, using the body to lift the mind','When stuck, write it down or talk to someone, do not brood alone','Address issues not oneself, replace I cannot with how can this be done'],
 cnMis:['见刑太岁就当定灾、过度焦虑','把所有情绪归罪于太岁，不关注自身状态','独自硬扛、不肯求助，内耗越来越重'],
 enMis:['Treating punishing Tai Sui as destined disaster and becoming overly anxious','Blaming every emotion on Tai Sui without attention to one own state','Toughing it out alone and refusing help, letting inner friction grow heavier'],
 cnClose:'刑太岁看的是「自己跟自己较劲怎么松绑」。把注意力从「我怎么了」转到「这件事怎么做」，规律作息、肯求助，这一年的内耗就能化开。犯太岁是提醒不是定灾。',
 enClose:'Punishing Tai Sui asks how to loosen the knot of competing with yourself. Shift attention from what is wrong with me to how to do this, keep regular routines and ask for help, and the inner friction of this year can dissolve. Tai Sui is a reminder, not a destined disaster.'},

{cat:'yingyong',slug:'ziwei-fangpian-shipian-ruhe-shibie',focus:'识别骗局',focusEn:'recognizing scams and fraud',
 cnT:'怎么用命盘识别破财信号与现实防骗清单',enT:'How to Spot Wealth-Loss Signals in a Chart and Prevent Fraud',
 cnD:'命盘中化忌、空劫、大耗会照财帛或福德，是破财的倾向信号；但防骗最终靠现实动作：不点陌生链接、不转账、核验官方渠道，凡「花钱改运、补财库、开光招财」多为骗局。',
 enD:'In a chart, Hua Ji, emptiness, robbery or waste stars aspecting the Wealth or Karma Palace signal a tendency toward wealth loss. But fraud prevention ultimately relies on real actions: do not click unknown links, do not transfer money, verify official channels, and any paid luck-changing, treasury-replenishing or consecrated wealth-blessing is likely a scam.',
 cnL:'命盘能提示「这阶段容易因什么破财」，但不能替你挡骗子；真正的防火墙是你自己的习惯和核验。',
 enL:'A chart can hint at what may cause wealth loss this stage, but it cannot block scammers for you; the real firewall is your own habits and verification.',
 cnA:'有人见破财信号就慌去买「改运服务」，结果反而被骗；也有人完全不信信号、不设防，两头都吃亏。',
 enA:'Some see wealth-loss signals and panic into buying luck-changing services, only to be scammed; others ignore the signals entirely and set no defenses, and both lose out.',
 cnLog:['命盘破财信号：化忌落财帛、空劫会照、大耗同宫，提示这阶段财来财去。','常见破财场景：高息诱惑、内部消息、刷单返利、冒充公检法、花钱改运。','现实防骗三原则：不点陌生链接、不向陌生账户转账、凡事核验官方渠道。','凡承诺「花钱改运、补财库、开光招财、包赚不赔」，基本可判定为骗局。'],
 enLog:['Chart wealth-loss signals: Hua Ji in the Wealth Palace, emptiness or robbery in aspect, waste stars conjunct, hinting money comes and goes this stage.','Common loss scenarios: high-interest bait, insider tips, rebate scams, impersonating authorities, paid luck-changing.','Three real prevention principles: do not click unknown links, do not transfer to unknown accounts, always verify official channels.','Any promise of paid luck-changing, treasury replenishing, consecrated wealth or guaranteed profit can essentially be judged a scam.'],
 cnStep:['先看命盘财帛与福德有没有破财信号，知道风险方向','把信号翻译成现实场景（是投资冲动、还是轻信他人）','建立防骗习惯：陌生链接不点、转账前先核实','遇到「花钱改运」类承诺，直接判定为骗局','大额决策先缓24小时、找信任的人商量','定期检查账户和订阅，清理不必要的授权'],
 enStep:['First read the Wealth and Karma Palaces for wealth-loss signals to know the risk direction','Translate the signal into real scenarios (investment impulse or gullibility)','Build prevention habits: no unknown links, verify before transferring','When encountering paid luck-changing promises, directly judge as scam','Pause large decisions for 24 hours and discuss with someone trusted','Regularly check accounts and subscriptions, clean up unnecessary authorizations'],
 cnMis:['见破财信号就去买「改运服务」，反而被骗','完全不信信号、不设防，轻信高息承诺','把命盘当挡箭牌，以为有信号就不会被骗'],
 enMis:['Seeing wealth-loss signals and buying luck-changing services, getting scammed instead','Ignoring signals entirely and setting no defense, trusting high-interest promises','Treating the chart as a shield, assuming having a signal means you cannot be scammed'],
 cnClose:'识别骗局看的是「命盘提示 + 现实防火墙」。知道自己容易在哪栽、再把不点不转不迷信的习惯立住，破财的坑才能绕过去。凡涉及钱财以正规机构和官方渠道为准。',
 enClose:'Recognizing scams combines chart hints with a real-life firewall. Know where you tend to stumble, then establish the habits of not clicking, not transferring and not superstition, and you can avoid the wealth-loss traps. For all money matters, rely on licensed institutions and official channels.'},

{cat:'yingyong',slug:'ziwei-jianzhi-dier-shouru-ruhe-kan',focus:'兼职第二收入',focusEn:'side jobs and second income',
 cnT:'兼职第二收入怎么看：用主业稳盘、用兼职试水，防本末倒置',enT:'How to Approach Side Jobs and Second Income',
 cnD:'兼职是用主业稳基本盘、用多余精力试水第二曲线；命盘看官禄与财帛的配合，时间精力够不够、三方有没有支撑，防兼职挤垮主业、贪多嚼不烂。',
 enD:'A side job uses the main career to stabilize the base and spare energy to test a second curve. Read the Career and Wealth Palaces in the chart for whether time and energy suffice and whether the trine supports it, guarding against the side job crowding out the main career and taking on too much.',
 cnL:'兼职的本质是「用多余的精力换额外的收入」，前提是主业不能倒；本末倒置，两头都做不好。',
 enL:'A side job essentially exchanges spare energy for extra income, on the premise that the main career does not collapse; reversing priorities means doing neither well.',
 cnA:'有人见别人兼职赚钱就跟风，也有人怕影响主业完全不敢试；真正要算的是自己的时间精力和命盘里的事业财帛配合。',
 enA:'Some follow the crowd when seeing others earn from side jobs, while others dare not try for fear of affecting the main career; what to calculate is your own time and energy and the career-wealth fit in your chart.',
 cnLog:['先看主业（官禄）稳不稳：主业是基本盘，不能为兼职牺牲。','再看财帛与三方：有没有第二收入的机缘和承接力。','时间精力是硬约束：兼职不能挤占睡眠、健康和主业核心时间。','选兼职要顺着自己的星性和技能，不盲目追风口。'],
 enLog:['First check whether the main career (Career Palace) is stable: it is the base and cannot be sacrificed for the side job.','Then read the Wealth Palace and trine: whether there is opportunity and capacity for second income.','Time and energy are hard constraints: a side job must not crowd out sleep, health and core main-career time.','Choose a side job that fits your star nature and skills, do not blindly chase trends.'],
 cnStep:['先评估主业状态，确认基本盘稳固','盘点每周可投入兼职的真实时间（扣除睡眠和主业）','看命盘官禄、财帛与迁移，评估第二收入方向','选一个低门槛、可验证的方向先试水，不all in','设定兼职的收入和时间上限，到点就收','定期复盘：兼职是否影响主业，决定继续、调整还是停'],
 enStep:['First assess the main career state, confirming the base is stable','Inventory the real weekly time available for the side job (after sleep and main career)','Read the Career, Wealth and Travel Palaces to assess the second-income direction','Choose one low-barrier, testable direction to try first, do not go all in','Set income and time caps for the side job, stop when reached','Regularly review whether the side job affects the main career, then continue, adjust or stop'],
 cnMis:['盲目跟风兼职，不看自己时间精力','兼职挤垮主业，本末倒置','贪多嚼不烂，同时开好几个兼职方向'],
 enMis:['Blindly following the crowd into side jobs without considering time and energy','Letting the side job crowd out the main career, reversing priorities','Taking on too much, opening several side directions at once'],
 cnClose:'兼职第二收入看的是「主业稳不稳、精力够不够、方向对不对」。把基本盘守住、用多余精力试水、设好上限，第二收入才是加分而不是透支。以上为命理倾向，不构成投资建议，以持牌机构和正规产品说明为准。',
 enClose:'Second income asks whether the main career is stable, energy suffices and direction fits. Guard the base, test with spare energy and set caps, so the second income is a plus rather than exhaustion. This is a cultural-tendency reference, not investment advice; defer to licensed institutions and official product terms.'},

{cat:'yingyong',slug:'ziwei-zhichang-zhandui-paixi-ruhe-kan',focus:'职场站队',focusEn:'workplace faction alignment',
 cnT:'职场站队怎么看：守住专业与边界，比依附派系更稳',enT:'How to Handle Workplace Faction Alignment',
 cnD:'职场派系是权力结构的现实，命盘看官禄与交友的配合；但长期来看，守住专业能力和职业边界、不轻易选边、以书面与流程保护自己，比依附某一派更稳。',
 enD:'Workplace factions are a reality of power structures; read the Career and Friends Palaces in the chart. But in the long run, guarding professional competence and boundaries, not easily taking sides and protecting yourself through documentation and process is steadier than attaching to one faction.',
 cnL:'站队的本质是「选谁做靠山」，但靠山会倒，专业和口碑不会；把不可替代的能力握在手里，比选边更安全。',
 enL:'Taking sides essentially means choosing a backer, but backers can fall while competence and reputation do not; holding irreplaceable ability in hand is safer than choosing a side.',
 cnA:'有人见派系斗争就急着选边，也有人完全回避、被边缘化；真正要做的是守住专业、不轻易表态、用流程保护自己。',
 enA:'Some rush to take sides at the sight of factional struggle, while others withdraw entirely and get marginalized; what is needed is guarding professionalism, not readily declaring allegiance and using process to protect yourself.',
 cnLog:['职场派系客观存在，完全无视不现实，但不必急于选边。','命盘看官禄（事业）与交友（人际）的配合，评估派系对你的影响。','核心策略：专业能力是硬通货，流程和书面是保护壳。','不轻易在公开场合表态、不传闲话、不参与人身攻击。'],
 enLog:['Workplace factions exist objectively, ignoring them entirely is unrealistic, but there is no need to rush to choose.','Read the Career (work) and Friends (relationships) Palaces to assess how factions affect you.','Core strategy: professional competence is hard currency, process and documentation are a protective shell.','Do not readily declare allegiance in public, do not spread gossip, do not join personal attacks.'],
 cnStep:['先观察组织里的派系结构和核心人物，不急着表态','评估自己的岗位和专业能力是不是不可替代','把重要沟通和决策落实为邮件或书面记录','遇到派系拉拢，用「对事不对人」的话术缓住','不参与闲话和人身攻击，保持职业中立','持续积累专业能力和外部机会，把选择权握在自己手里'],
 enStep:['First observe the faction structure and key figures in the organization, do not rush to declare','Assess whether your role and professional competence are irreplaceable','Put important communication and decisions into emails or written records','When courted by a faction, use issue-not-person language to deflect','Do not join gossip or personal attacks, maintain professional neutrality','Continuously build professional competence and external options, holding choice in your own hands'],
 cnMis:['急于选边、把前途押在某个人身上','完全回避、被边缘化、失去机会','参与闲话和人身攻击，留下把柄'],
 enMis:['Rushing to take sides and betting the future on one person','Withdrawing entirely, getting marginalized and losing opportunities','Joining gossip and personal attacks, leaving leverage for others'],
 cnClose:'职场站队看的是「专业和边界能不能守住」。不急于选边、用流程保护自己、把能力握在手里，你才不会因为派系变动而被动。涉及职场权益以正规劳动合同和公司制度为准。',
 enClose:'Workplace alignment asks whether professionalism and boundaries can be guarded. Do not rush to take sides, protect yourself through process and hold ability in hand, so you are not left passive when factions shift. For workplace rights, rely on formal labor contracts and company policies.'},

{cat:'yingyong',slug:'ziwei-zhaiwu-shangan-huanqing-ruhe-kan',focus:'债务上岸',focusEn:'getting out of debt',
 cnT:'债务上岸怎么看：定节奏、做减法、先高息后低息',enT:'How to Get Out of Debt: A Practical Path',
 cnD:'债务上岸不靠命盘转运，靠的是现实的财务计划：盘点全部负债、定还款节奏、做支出减法、先还高息后还低息，与债权人沟通走正规书面途径，命盘只提示哪个阶段容易因什么负债。',
 enD:'Getting out of debt does not depend on chart luck-turning but on a real financial plan: inventory all debts, set a repayment rhythm, cut expenses, pay high-interest before low-interest, and communicate with creditors through proper written channels. The chart only hints at which stage tends to incur debt and why.',
 cnL:'债务上岸像爬山，第一步是承认山有多高；盘点清楚、定好节奏，比到处找捷径更有用。',
 enL:'Getting out of debt is like climbing a mountain; the first step is acknowledging how high it is. A clear inventory and set rhythm are more useful than searching for shortcuts everywhere.',
 cnA:'有人负债后不敢面对、以贷养贷，也有人想靠「改运」一夜还清；真正要做的是坐下来算账、定计划、一步步还。',
 enA:'Some avoid facing debt and borrow to repay, while others hope to clear it overnight through luck-changing; what is needed is sitting down to calculate, making a plan and repaying step by step.',
 cnLog:['命盘提示：化忌落财帛或福德、空劫会照，提示容易因冲动或人情负债。','上岸第一步：盘点全部负债（本金、利率、月供、期限），不回避。','还款策略：先高息后低息，同时做支出减法、增加收入。','与债权人沟通走正规书面途径，不逃避、不失联，协商还款方案。'],
 enLog:['Chart hint: Hua Ji in Wealth or Karma, emptiness or robbery in aspect, suggests a tendency to incur debt through impulse or obligations.','First step: inventory all debts (principal, interest, monthly payment, term), do not avoid.','Repayment strategy: high-interest first, then low-interest, while cutting expenses and increasing income.','Communicate with creditors through proper written channels, do not evade or lose contact, negotiate a repayment plan.'],
 cnStep:['先盘点全部负债，列清本金、利率、月供','做支出减法：区分必要和非必要，砍掉非必要','定还款顺序：先还高息（如信用卡分期、网贷），后还低息','增加收入：兼职、变卖闲置、争取加薪','与债权人主动沟通，协商延期或分期，走书面途径','每月复盘还款进度，调整计划，不半途而废'],
 enStep:['First inventory all debts, listing principal, interest and monthly payment','Cut expenses: separate necessary from unnecessary, eliminate the unnecessary','Set repayment order: high-interest first (credit card installments, online loans), then low-interest','Increase income: side jobs, selling unused items, seeking a raise','Proactively communicate with creditors, negotiate extension or installment in writing','Review repayment progress monthly, adjust the plan and do not give up halfway'],
 cnMis:['以贷养贷、拆东墙补西墙，债务越滚越大','不敢面对、不盘点，逃避让利息继续涨','想靠「改运」或一夜暴富还清，不做实际计划'],
 enMis:['Borrowing to repay, robbing Peter to pay Paul, letting debt snowball','Avoiding facing it and not inventorying, letting interest keep growing','Hoping to clear debt through luck-changing or overnight riches without a real plan'],
 cnClose:'债务上岸看的是「盘点清楚、节奏稳住、一步步还」。命盘只提示风险方向，真正的上岸靠现实的财务计划和执行力。涉及借贷以专业律师和正规途径、书面合同为准。',
 enClose:'Getting out of debt is about a clear inventory, steady rhythm and step-by-step repayment. The chart only hints at risk directions; real escape from debt depends on a practical financial plan and execution. For borrowing matters, rely on professional lawyers, proper channels and written contracts.'}
];
