// 2026-10-01 调研驱动 第5组：蜚廉疾/大耗命/大耗财/大耗田/天空命/天空财/天福命/天福官 8篇
module.exports=[
{cat:'fuzhu',slug:'ziwei-feilian-zai-jiegong',focus:'蜚廉在疾厄宫',focusEn:'Fei Lian in the Health Palace',
 cnT:'蜚廉在疾厄宫：体质偏敏感，怎么把卫生和小感染管在前面',
 enT:'Fei Lian in the Health Palace: A Sensitive Constitution and Staying Ahead of Hygiene and Minor Infections',
 cnD:'蜚廉落疾厄宫，象意多与细菌、病毒、小感染、过敏及体质敏感有关，也主身体对环境变化反应细。它不主大病大灾，关键是讲卫生、留意饮食与居住环境，出现持续不适及时到正规机构检查，而不是对着星名瞎担心。',
 enD:'Fei Lian in the Health Palace tends to relate to germs, minor infections, allergies and a sensitive constitution, along with a body that reacts finely to changes in environment. It does not indicate serious illness; the key is good hygiene, attention to food and living conditions and seeking a licensed provider when symptoms persist, rather than worrying over the star name.',
 cnL:'蜚廉在疾厄的人，身体常像一台灵敏的检测器：环境一脏、饮食一不洁就先有反应，把卫生和预防做在前面，反而少受不少小毛病。',
 enL:'People with Fei Lian in the Health Palace often have a body like a sensitive detector, reacting first when surroundings get dirty or food is unsafe; tending hygiene and prevention early spares many minor ailments.',
 cnA:'这个问题在问：蜚廉在疾厄要注意什么。要先把它读成体质敏感与卫生提醒，再看吉星、煞忌对恢复力的影响。',
 enA:'The question is what to watch with Fei Lian in the Health Palace. Read it as sensitivity and a hygiene reminder, then see how auspicious or malefic stars affect recovery.',
 cnLog:['蜚廉在疾厄，主细菌、病毒、小感染、过敏一类的小问题，跟饮食卫生和环境关系较大。','落此宫者体质偏敏感，换季、换环境、不洁饮食时更容易先出现反应。','见吉星与主星有力，恢复较快、小毛病易过；见煞忌，则易反复、拖成慢性小困扰。','蜚廉力量轻，不预示大病，定期检查、作息规律时影响很小。'],
 enLog:['Fei Lian in the Health Palace points to small matters such as germs, minor infections and allergies, closely tied to food hygiene and environment.','There the constitution is sensitive and reacts first around seasonal changes, new settings or unsafe food.','With auspicious stars and a strong major star recovery is quick and minor issues pass; with malefics and Ji they can recur into chronic nuisances.','Fei Lian is light and does not predict serious illness; with regular checkups and steady routines its effect is small.'],
 cnStep:['先确认疾厄宫有蜚廉，并看同宫主星','把饮食卫生、居家清洁和换季防护做在前面','留意过敏史和反复出现的小感染，记录诱因','作息规律、适度运动，稳住敏感体质','出现持续或加重的不适及时就医，不靠自我判断','结合大限流年看身体引动阶段，提前安排检查'],
 enStep:['First confirm Fei Lian is in the Health Palace and see the sharing major star','Tend food hygiene, home cleanliness and seasonal protection early','Note allergies and recurring minor infections and record their triggers','Keep steady routines and moderate exercise to settle a sensitive constitution','Seek medical care when symptoms persist or worsen rather than self-diagnosing','With the decade and year, schedule checkups ahead of when health is activated'],
 cnMis:['把蜚廉在疾厄只当成「要得大病」，自己吓自己','不重视卫生和环境，小毛病反复出现','身体有信号却拖延、不检查，错过最好处理窗口'],
 enMis:['Taking Fei Lian in the Health Palace only as serious illness ahead and frightening oneself','Neglecting hygiene and environment until minor issues recur','Delaying and not checking when the body signals, missing the easiest window'],
 cnClose:'蜚廉在疾厄给的是一份「体质敏感、注意卫生」的提醒。把预防和检查做在前面，小感染、小过敏管好了，它几乎碍不了事。这里讲的是倾向而非诊断，具体不适以正规就医为准。',
 enClose:'Fei Lian in the Health Palace gives a reminder of a sensitive constitution that benefits from hygiene. Tending prevention and checkups and managing minor infections and allergies well lets it barely interfere. This is a tendency, not a diagnosis; for any symptom, rely on qualified medical care.'},

{cat:'fuzhu',slug:'ziwei-dahao-zai-minggong',focus:'大耗在命宫',focusEn:'Da Hao in the Life Palace',
 cnT:'大耗在命宫：为人慷慨看得开，怎么把「爱花」管成有度',
 enT:'Da Hao in the Life Palace: Generous and Open-Handed, and How to Keep Spending in Measure',
 cnD:'大耗落命宫的人，多半性情大方、对钱看得开、愿意请客分享，也容易浪费、做事大起大落、缺恒心。它不等于一生破财，关键是给慷慨配上预算和目标，用「主动、有计划的耗」代替被动、冲动的失。',
 enD:'People with Da Hao in the Life Palace tend to be generous and relaxed about money, willing to treat and share, while being prone to waste, big ups and downs and weak persistence. It does not mean lifelong loss; the key is pairing generosity with a budget and goals, using planned, intentional expenditure instead of passive, impulsive loss.',
 cnL:'大耗坐命的人，花钱常图个痛快、也讲义气，朋友喜欢、场面热闹；只是没有计划时，钱来得快、去得也快，攒家底会比较吃力。',
 enL:'People with Da Hao in the Life Palace spend for the pleasure of it and value loyalty, popular and lively; without a plan money comes and goes quickly and building reserves is harder.',
 cnA:'这个问题在问：大耗坐命是什么性格、怎么管。要先分清它主慷慨与耗散，再看吉星助大进大出、煞忌增破耗。',
 enA:'The question is the temperament of Da Hao in the Life Palace and how to manage it. First separate its generosity from its scatter, then see whether auspicious stars aid large flows or malefics add loss.',
 cnLog:['大耗属火，主大方、慷慨与看得开，落命宫者不抠门、愿分享，人情上有号召力。','也主耗散：容易冲动消费、浪费、做事虎头蛇尾，钱财和精力都可能大进大出。','见禄权与主星庙旺（尤其做生意、当老板），大进大出反而能滚动获利。','见煞忌则易大破、留不住，预算、储蓄目标和「主动耗」（先买计划内必需品）能化解不少。'],
 enLog:['Da Hao is fire, governing generosity and an open hand; in the Life Palace one is not stingy and willing to share, with social pull.','It also governs scatter: impulsive buying, waste and tasks that start strong and end weak, with money and energy moving in large swings.','With Lu, Quan and a bright major star, especially in business, large inflows and outflows can roll into profit.','With malefics and Ji, major loss and weak retention follow, so budgets, savings goals and intentional spending on planned necessities help a great deal.'],
 cnStep:['先确认命宫有大耗，并看同宫主星','把每月收入先做分配（储蓄、必要开支、机动）','给请客、人情和冲动消费设额度','用「主动耗」：需要的大件提前规划采购，化解被动破财','做事拆成小目标、设节点，培养恒心','结合大限流年看破财风险年份，提前谨慎'],
 enStep:['First confirm Da Hao is in the Life Palace and see the sharing major star','Allocate monthly income first to savings, necessities and flexible spending','Set limits for treating others, social obligations and impulse purchases','Use intentional spending by planning needed purchases ahead to offset passive loss','Break tasks into small goals with checkpoints to build persistence','With the decade and year, be cautious in years that signal loss'],
 cnMis:['把大耗坐命只当成「注定破财」，自我设限','只图痛快、不做预算，钱过手就空','把慷慨当挥霍的借口，人情和冲动消费没边'],
 enMis:['Taking Da Hao in the Life Palace only as fated loss and limiting oneself','Spending for pleasure without a budget until money passes through empty','Using generosity as an excuse for waste, with no bounds on social and impulse spending'],
 cnClose:'大耗坐命给的是一份大方、讲义气的性格，也给了一道管钱的功课。把预算和储蓄立在前、用主动耗代替被动失，慷慨会成为人缘，而不是漏洞。',
 enClose:'Da Hao in the Life Palace gives a generous, loyal nature and a lesson in managing money. Putting budgets and savings first and replacing passive loss with intentional spending turns generosity into goodwill rather than a leak.'},

{cat:'fuzhu',slug:'ziwei-dahao-zai-caibogong',focus:'大耗在财帛宫',focusEn:'Da Hao in the Wealth Palace',
 cnT:'大耗在财帛宫：现金流容易大进大出，怎么把口子收住',
 enT:'Da Hao in the Wealth Palace: When Cash Flow Swings Wide and How to Hold the Opening',
 cnD:'大耗落财帛宫，跟钱的关系偏松：容易大手笔进出、对成本不敏感、积蓄偏少，也可能在投资、生意、人情上出现较大支出。它不等于没钱，关键是给现金流立纪律——预算、留存、风控一个不少。',
 enD:'Da Hao in the Wealth Palace makes the relationship with money loose, prone to large inflows and outflows, low sensitivity to cost and thin reserves, with sizable spending possible in investment, business or social obligations. It does not mean no money; the key is disciplining cash flow with a budget, savings and risk control.',
 cnL:'大耗在财帛的人，常出现「账上热闹、余额冷清」：进出金额不小，真正留下的不多。把出口看住，钱才留得下来。',
 enL:'People with Da Hao in the Wealth Palace often see busy accounts and quiet balances, with sizable turnover but little retained; watching the outlets is what lets money stay.',
 cnA:'这个问题在问：大耗在财帛要防什么。要先分清它主现金流的耗散，再看吉星助大进、煞忌增大出。',
 enA:'The question is what to guard with Da Hao in the Wealth Palace. First separate its cash-flow scatter, then see whether auspicious stars aid inflows or malefics add outflows.',
 cnLog:['大耗在财帛，主钱财大进大出、成本意识偏弱，也主意外的大额支出。','做生意、跑业务者见禄权，大进大出可能是周转需要，反而有利可图。','见煞忌、空劫，则易破财、被骗、投资失利，风控和尽调要格外严格。','预算、自动储蓄、信用与债务上限，是把口子收住的关键工具。'],
 enLog:['Da Hao in the Wealth Palace brings large inflows and outflows, weak cost awareness and unexpected major expenses.','In business or sales with Lu and Quan, large turnover may be a working need and can be profitable.','With malefics or void stars, loss, deception and failed investment follow, so risk control and due diligence must be strict.','Budgets, automatic savings and limits on credit and debt are the key tools that hold the opening shut.'],
 cnStep:['先确认财帛宫有大耗，并看同宫主星','把固定比例的收入先自动存下','给大额支出、投资和人情设审批与冷静期','记账一两个月，找出最大的漏财口','控制债务和担保，不替人扛不确定的钱','结合大限流年判断破财年份，提前留余地'],
 enStep:['First confirm Da Hao is in the Wealth Palace and see the sharing major star','Automatically save a fixed share of income first','Set approval and cooling-off rules for large spending, investments and obligations','Track expenses for a month or two to find the biggest leak','Control debt and guarantees and avoid carrying uncertain money for others','With the decade and year, leave room ahead of loss-signaling years'],
 cnMis:['把大耗在财帛只当成「存不住钱、命里漏财」','只图进出痛快，不做预算和风控','凭人情做担保、借钱，结果替人承担损失'],
 enMis:['Taking Da Hao in the Wealth Palace only as being unable to keep money','Enjoying the turnover without budgets or risk control','Giving guarantees and lending from obligation and carrying others’ losses'],
 cnClose:'大耗在财帛给的是一个现金流偏松的信号，不是一张穷命。把储蓄自动化、把大额支出和债务管起来，进出再热闹，钱也能慢慢留住。这里不构成投资建议，具体产品以持牌机构和正规说明为准。',
 enClose:'Da Hao in the Wealth Palace signals loose cash flow rather than a poor fate. Automating savings and managing large expenses and debt let money accumulate despite lively turnover. This is not investment advice; for any product, rely on licensed institutions and official disclosures.'},

{cat:'fuzhu',slug:'ziwei-dahao-zai-tianzhaigong',focus:'大耗在田宅宫',focusEn:'Da Hao in the Property Palace',
 cnT:'大耗在田宅宫：守好家产这道库，怎么防不动产的损耗',
 enT:'Da Hao in the Property Palace: Guarding the Household Treasury Against Loss to Fixed Assets',
 cnD:'田宅宫是家产之库，大耗落在这里，最怕不动产上的大损耗：高价置业后贬值、装修超支、被盗、火灾虚惊或家中大额开销。它不代表一定败宅，关键是重安防、留保险、理性决策，把「库」看牢。',
 enD:'The Property Palace is the household treasury, and Da Hao there most risks major loss to fixed assets: buying high before a drop, overspending on renovation, theft, fire scares or large home expenses. It does not mean the home must fail; the key is security, insurance and rational decisions, guarding the treasury well.',
 cnL:'大耗在田宅的人，在家产和房子上容易出现计划外的大支出，或者东西损耗得快。把安防、保险和冷静期做足，能挡掉不少被动破财。',
 enL:'People with Da Hao in the Property Palace easily face unplanned large spending on the home or find possessions wearing out fast; solid security, insurance and cooling-off periods block a good deal of passive loss.',
 cnA:'这个问题在问：大耗在田宅要防什么。要先理解田宅看家与资产承载，再看煞忌增损耗、吉星助守。',
 enA:'The question is what to guard with Da Hao in the Property Palace. Understand it reads home and asset capacity, then see whether malefics add loss or auspicious stars aid protection.',
 cnLog:['大耗在田宅，主家产、不动产的较大损耗，古称「耗库」，最忌此宫。','象意包括高价买入、装修超支、被盗、火灾、家电频坏及为家人的大额支出。','见禄存化禄与吉曜，且决策理性，损耗可控、家业仍稳；见煞忌空劫，则易大破。','安防措施、家庭财产保险、买房装修的预算与冷静期，是最直接的化解。'],
 enLog:['Da Hao in the Property Palace brings sizable loss to household assets and real estate, traditionally called draining the treasury, and it is least liked here.','Signs include buying high, renovation overruns, theft, fire, appliances failing often and large spending for family.','With Lu Cun, Hua Lu, auspicious stars and rational decisions, loss stays manageable and the home steadies; with malefics and void stars major breaks follow.','Security measures, home and property insurance and budgets with cooling-off periods for purchases and renovation are the most direct remedies.'],
 cnStep:['先确认田宅宫有大耗，并看同宫主星','买房、装修先做预算和比价，留冷静期','检查门锁、消防、水电，消除安防隐患','配置合适的家庭财产保险','大额家用支出全家商量，避免冲动','结合大限流年判断田宅损耗阶段，提前谨慎'],
 enStep:['First confirm Da Hao is in the Property Palace and see the sharing major star','Make budgets and comparisons with a cooling-off period for buying and renovation','Check locks, fire safety and utilities to remove security risks','Carry suitable home and property insurance','Discuss large household spending as a family and avoid impulse','With the decade and year, be cautious ahead of property-loss stages'],
 cnMis:['把大耗在田宅只当成「家产必败」，吓自己','买房装修凭一时冲动，超支也不设防','忽略安防和保险，出事才补救'],
 enMis:['Taking Da Hao in the Property Palace only as the household treasury being doomed and frightening oneself','Buying and renovating on impulse and overspending without safeguards','Neglecting security and insurance until something happens'],
 cnClose:'大耗在田宅给的是一道「守库」的提醒，不是败宅的判决。把预算、安防和保险做扎实，房子和家产能守得很稳，大额损耗也能提前避开。',
 enClose:'Da Hao in the Property Palace gives a reminder to guard the treasury rather than a verdict of loss. Solid budgets, security and insurance keep the home and assets steady and help avoid major loss ahead of time.'},

{cat:'fuzhu',slug:'ziwei-tiankong-zai-minggong',focus:'天空在命宫',focusEn:'Tian Kong in the Life Palace',
 cnT:'天空在命宫：想法超脱、精神自由，怎么不把聪明活成空想',
 enT:'Tian Kong in the Life Palace: An Unconventional, Free Mind and How Not to Let Cleverness Drift Into Fantasy',
 cnD:'天空主思想独特、超脱、不爱拘束，落命宫的人想象力强、精神世界开阔、对名利相对淡，适合创意、设计、研究、哲学与精神领域。风险是空想、不切实际、与现实脱节，关键是给超脱的想法一个落地的抓手。',
 enD:'Tian Kong governs original, detached thought and a dislike of constraint. In the Life Palace one has strong imagination, a wide inner world and relative indifference to fame and gain, suiting creativity, design, research, philosophy and spiritual fields. The risk is fantasy, impracticality and disconnect from reality, so the key is giving detached ideas a handle to land.',
 cnL:'天空坐命的人，脑子常比别人「高半截」：想法新、看得开，也容易飘在半空，事情想了很多、落地的少。给思想接上动作，天赋才出得来。',
 enL:'People with Tian Kong in the Life Palace often think a step above others, with fresh ideas and an open mind, yet they can float halfway up, thinking much and landing little; connecting thought to action lets the gift emerge.',
 cnA:'这个问题在问：天空坐命是什么性格、怎么落地。要先分清天空与地空的差别（天空更偏思想超脱），再看吉星助落地。',
 enA:'The question is the temperament of Tian Kong in the Life Palace and how to land. First distinguish Tian Kong from Di Kong, as Tian Kong leans more to detached thought, then see how auspicious stars aid grounding.',
 cnLog:['天空性质与地空相近但更偏思想，主独特、超脱、不与人抵触，有时沦为空想。','落命宫者想象力强、直觉好、不爱拘束，适合设计、创意、研究、冷门学问与精神类工作。','喜与紫微同宫（从海阔天空里做出事业）、与贪狼同宫（把桃花转为物欲与创作）。','见煞忌则易空想、逃避、不切实际，时间表、具体目标和动手习惯是化解。'],
 enLog:['Tian Kong is close to Di Kong but leans more to thought, governing originality and detachment without clashing, sometimes slipping into fantasy.','In the Life Palace one has strong imagination and intuition and dislikes constraint, suiting design, creativity, research, uncommon learning and spiritual work.','It pairs well with Zi Wei to build a career out of wide-open thinking and with Tan Lang to turn romance into material creativity.','With malefics and Ji, fantasy, avoidance and impracticality follow, so timelines, concrete goals and hands-on habits are the remedy.'],
 cnStep:['先确认命宫有天空，并看同宫主星','把想法和灵感及时记录、整理','给每个想法配一个最小可行动作和期限','保留精神自由的同时，固定动手和落地时间','找能把创意转成成果的伙伴或平台','结合大限流年判断创意被引动的阶段'],
 enStep:['First confirm Tian Kong is in the Life Palace and see the sharing major star','Record and organize ideas and inspirations promptly','Give each idea a smallest doable action and a deadline','While keeping mental freedom, protect fixed hands-on time','Find partners or platforms that turn creativity into results','With the decade and year, see when creativity is activated'],
 cnMis:['把天空坐命只当成「不切实际、爱做白日梦」','只想不做，把超脱变成逃避','为了合群硬压独特性，天赋也被埋没'],
 enMis:['Taking Tian Kong in the Life Palace only as impractical daydreaming','Only thinking without doing and turning detachment into avoidance','Forcing originality down to fit in and burying the gift'],
 cnClose:'天空坐命给的是一个开阔、自由、有想象力的脑子。把想法记下来、接上最小动作和期限，超脱才会变成真正的创造力，而不是空中楼阁。',
 enClose:'Tian Kong in the Life Palace gives an open, free and imaginative mind. Recording ideas and attaching the smallest action and deadline turns detachment into real creativity rather than a castle in the air.'},

{cat:'fuzhu',slug:'ziwei-tiankong-zai-caibogong',focus:'天空在财帛宫',focusEn:'Tian Kong in the Wealth Palace',
 cnT:'天空在财帛宫：钱不宜只攥在手里，靠知识与创意反而更顺',
 enT:'Tian Kong in the Wealth Palace: Money That Does Better Through Knowledge and Creativity Than Being Gripped Tight',
 cnD:'天空落财帛宫，对实物钱财的掌控感偏松，硬做只靠囤货、炒卖的事容易落空；但靠知识、创意、设计、内容、技术与精神服务变现反而顺。关键是认清自己的财路偏「无形」，并给现金流立纪律。',
 enD:'Tian Kong in the Wealth Palace loosens the grip on tangible money, and things that rely only on hoarding or speculation tend to fall through; monetizing knowledge, creativity, design, content, skill and spiritual services works better. The key is recognizing an intangible earning style and disciplining cash flow.',
 cnL:'天空在财帛的人，越想把钱死死攥住越容易空，顺着创意和专业去赚，反而来得自然；只是进账不稳时，预算和缓冲更要备好。',
 enL:'People with Tian Kong in the Wealth Palace find that gripping money tighter leaves it empty, while earning through creativity and expertise feels natural; when income is uneven, budgets and buffers matter more.',
 cnA:'这个问题在问：天空在财帛是什么财路。要先理解它主「无形之财」，再看吉星助变现、煞忌增空耗。',
 enA:'The question is the earning style with Tian Kong in the Wealth Palace. First understand it governs intangible wealth, then see whether auspicious stars aid monetization or malefics add empty expenditure.',
 cnLog:['天空在财帛，主钱财上偏空、不重囤积，硬追实物和投机容易落空。','适合知识付费、设计、创意、内容、技术与精神服务等「无形」收入。','见禄权科与吉曜，创意和专业能稳定变现；见煞忌空劫，则易财来财去、进账飘忽。','现金流纪律、多元收入与应急储备，能把飘忽的财路托稳。'],
 enLog:['Tian Kong in the Wealth Palace brings a loose, non-hoarding relationship with money, and forcing speculation on tangible things tends to fail.','It suits intangible income such as knowledge products, design, creativity, content, skill and spiritual services.','With Lu, Quan, Ke and auspicious stars creativity and expertise monetize steadily; with malefics or void stars money comes and goes and income is uneven.','Cash-flow discipline, diversified income and emergency reserves steady an uneven earning path.'],
 cnStep:['先确认财帛宫有天空，并看同宫主星','把收入重心放到知识、创意和专业服务上','避免高风险投机和盲目囤货','给飘忽进账做预算，保持应急储备','拓展两三条收入线，降低单一来源波动','结合大限流年判断变现机会阶段'],
 enStep:['First confirm Tian Kong is in the Wealth Palace and see the sharing major star','Put the earning focus on knowledge, creativity and expert services','Avoid high-risk speculation and blind hoarding','Budget for uneven income and keep emergency reserves','Develop two or three income lines to reduce single-source swings','With the decade and year, see when monetization is activated'],
 cnMis:['把天空在财帛只当成「存不住钱、漏财」','硬追投机和实物财，反复落空','进账一不稳就不做预算，风险来时没缓冲'],
 enMis:['Taking Tian Kong in the Wealth Palace only as being unable to keep money','Forcing speculation and tangible wealth and failing repeatedly','Skipping budgets when income is uneven, leaving no buffer'],
 cnClose:'天空在财帛给的是一条偏知识、创意与专业的财路。顺着无形之财去赚、给现金流立好纪律和储备，钱会比硬攥、硬投机时来得稳。这里不构成投资建议。',
 enClose:'Tian Kong in the Wealth Palace gives a path oriented to knowledge, creativity and expertise. Earning along intangible lines and disciplining cash flow with reserves steadies money more than gripping or speculating. This is not investment advice.'},

{cat:'fuzhu',slug:'ziwei-tianfuxing-zai-minggong',focus:'天福在命宫',focusEn:'Tian Fu Xing (Tian Fu the blessing star) in the Life Palace',
 cnT:'天福在命宫：温和敦厚带天赐之福，怎么顺势把福分养厚',
 enT:'Tian Fu Xing in the Life Palace: A Warm, Steady Nature With an Innate Blessing',
 cnD:'天福主爵禄、福寿与天赐之福，落命宫的人性情温和敦厚、待人诚恳、做事稳重、任劳任怨，一生多逢凶化吉、贵人相助，中年后更稳。它不是坐等天降，关键是顺着本性把人和、健康与专业慢慢养厚。',
 enD:'Tian Fu Xing governs salary-blessings, longevity and innate good fortune. In the Life Palace one is warm, sincere, steady and hardworking, often finding that difficulties turn around and helpful people appear, growing steadier after midlife. It is not passive waiting; the key is nurturing relationships, health and expertise in line with the nature.',
 cnL:'天福坐命的人，常给人「舒服、可靠、有福相」的感觉，不刻意争，也容易被善待；越是自然、顺势，这份福越养得厚，勉强反而压住它。',
 enL:'People with Tian Fu Xing in the Life Palace seem comfortable, dependable and blessed, not striving conspicuously yet often treated well; the more natural and aligned they are, the more the blessing grows, while forcing things weighs it down.',
 cnA:'这个问题在问：天福坐命是什么福气、怎么把握。要先分清天福与天府（slug 用 tianfuxing 区分），再看吉星助福寿。',
 enA:'The question is the blessing of Tian Fu Xing in the Life Palace and how to use it. First distinguish it from Tian Fu the treasury star, then see how auspicious stars aid longevity and fortune.',
 cnLog:['天福属阳土，为天同辅星，主爵禄、福寿、名利与天赐之福，入十二宫皆偏安稳。','落命宫者温和敦厚、任劳任怨，逢凶化吉、贵人助，中年后更发达。','与天寿同宫最吉（福寿双全），与天同守福德亦吉。','见煞忌则福分打折、易操心，但本性稳重，长期经营仍能安稳。'],
 enLog:['Tian Fu Xing is yang earth and an assistant to Tian Tong, governing salary-blessings, longevity, name and innate fortune, and it tends to steady every palace.','In the Life Palace one is warm and hardworking, turning difficulty around with helpful people, and developing more after midlife.','It is most auspicious with Tian Shou for longevity and fortune, and also fine holding the Karma Palace with Tian Tong.','With malefics and Ji the blessing is discounted and worry grows, yet the steady nature still settles through long-term care.'],
 cnStep:['先确认命宫有天福，并看同宫主星','顺着温和本性经营人际，不刻意强求','把健康、作息和长期保障照顾好','在专业上稳步积累，等中年后自然成熟','珍惜贵人、感恩回馈，把福分传出去','结合大限流年看福气引动阶段'],
 enStep:['First confirm Tian Fu Xing is in the Life Palace and see the sharing major star','Nurture relationships in line with the warm nature without forcing','Tend health, routines and long-term protection','Build expertise steadily and ripen naturally toward midlife','Value helpful people and give back to extend the blessing','With the decade and year, see when fortune is activated'],
 cnMis:['把天福坐命只当成「天生好命、不用努力」','为争利扭曲本性，反而把福气压住','只图安稳不积累，中年后后劲不足'],
 enMis:['Taking Tian Fu Xing in the Life Palace only as innate good fortune requiring no effort','Twisting the nature to compete and weighing the blessing down','Seeking only comfort without building, leaving little momentum after midlife'],
 cnClose:'天福坐命给的是一份温和、敦厚、逢凶化吉的福气。顺势把人、健康和专业养厚，不坐等也不强求，这份天赐之福会越走越稳。',
 enClose:'Tian Fu Xing in the Life Palace gives a warm, steady nature that turns difficulty around. Nurturing relationships, health and expertise in alignment, neither waiting passively nor forcing, lets the innate blessing grow steadier.'},

{cat:'fuzhu',slug:'ziwei-tianfuxing-zai-guanlugong',focus:'天福在官禄宫',focusEn:'Tian Fu Xing in the Career Palace',
 cnT:'天福在官禄宫：事业稳、有福报，怎么把岗位做成长久的安稳',
 enT:'Tian Fu Xing in the Career Palace: A Steady, Blessed Career Built Into Lasting Security',
 cnD:'天福落官禄宫，事业上多一分稳、一分福报：做事稳重可靠、能得善待与提携，适合稳定的专业岗位、文教、福利型与制度化行业，中年后职分和待遇往往更踏实。关键是在安稳里持续精进、把口碑做厚。',
 enD:'Tian Fu Xing in the Career Palace adds steadiness and good fortune to work: one is reliable and treated well with support, suiting stable professional roles, education, welfare-oriented and institutional fields, with firmer position and rewards after midlife. The key is continuing to improve within security and deepening reputation.',
 cnL:'天福在官禄的人，职场上不爱大起大落，做事让人放心、也容易遇到好同事、好领导，长期看岗位稳、待遇也稳；只是太安于现状时，成长会偏慢。',
 enL:'People with Tian Fu Xing in the Career Palace dislike swings at work, are dependable and easily find good colleagues and leaders, with steady roles and rewards over time; when too settled, growth slows.',
 cnA:'这个问题在问：天福在官禄是什么事业运。要先理解官禄看做事方式，再看天福的稳和福寿怎么配上升迁与精进。',
 enA:'The question is the career fortune with Tian Fu Xing in the Career Palace. Understand it reads how one works, then see how its steadiness pairs with advancement and improvement.',
 cnLog:['天福在官禄，主事业安稳、做事稳重、易得善待，职分和待遇偏踏实。','适合文教、民政、福利、医疗护理、稳定企业与专业型岗位。','见天官、天贵、恩光及魁钺，升迁和名誉更顺；与天寿同度亦增稳。','见煞忌则易偏安、节奏慢，持续学习和主动承担能补上成长。'],
 enLog:['Tian Fu Xing in the Career Palace gives steady work and reliable treatment, with firm position and rewards.','It suits education, civil and welfare work, health care, stable firms and professional roles.','With Tian Guan, Tian Gui, En Guang and Kui Yue, advancement and reputation go smoothly; with Tian Shou it also steadies.','With malefics and Ji one settles too comfortably and slows, so continued learning and active responsibility restore growth.'],
 cnStep:['先确认官禄宫有天福，并看同宫主星','把本职工作做稳、把口碑和信任养厚','在安稳岗位上持续学习、更新技能','主动承担项目，争取顺理成章的提升','经营与同事、领导的良好关系','结合大限流年判断事业成熟阶段'],
 enStep:['First confirm Tian Fu Xing is in the Career Palace and see the sharing major star','Steady the core work and deepen reputation and trust','Keep learning and updating skills within a secure role','Take on projects actively and pursue well-earned advancement','Nurture good relationships with colleagues and leaders','With the decade and year, see when the career matures'],
 cnMis:['把天福在官禄只当成「事业稳、铁饭碗」，忽略精进','安于现状、不主动承担，成长偏慢','只靠福报等待提携，专业积累不够'],
 enMis:['Taking Tian Fu Xing in the Career Palace only as a secure job while ignoring improvement','Settling in comfort without taking initiative, slowing growth','Waiting for support through fortune alone with too little expertise'],
 cnClose:'天福在官禄给的是一条稳当、有福报、能长久的事业路。把口碑做厚、在安稳里持续精进，职分和待遇会随时间越走越踏实。',
 enClose:'Tian Fu Xing in the Career Palace gives a steady, blessed and lasting career path. Deepening reputation and improving within security let position and rewards grow firmer with time.'}
];
