// 2026-10-04 调研驱动 第4组：格局1 + 主星配对4 + 婚恋2 + 六亲1，共8篇
module.exports=[
{cat:'geju',slug:'ziwei-yingxing-rumiao-geju-ruhe-kan',focus:'英星入庙格',focusEn:'the Ying Xing Ru Miao pattern',
 cnT:'英星入庙格怎么看：破军在子午入庙，危中建功、先破后立',enT:'The Ying Xing Ru Miao Pattern: Po Jun Exalted at Zi or Wu, Building Through Crisis',
 cnD:'破军在子、午宫入庙守命为英星入庙，主敢于破旧局、在难处建功、先破后立；仍要见禄与吉星，落陷加煞则不成，不能见破军就套格。',
 enD:'Po Jun exalted in the Life Palace at Zi or Wu forms Ying Xing Ru Miao, showing someone who dares to break a stale order and builds through difficulty; it still needs Lu and auspicious stars, and a fallen Po Jun with malefics does not form the pattern.',
 cnL:'英星入庙讲的是破军得地时那股「敢在乱局里动手」的劲，破是为了立，不是为破而破。',
 enL:'Ying Xing Ru Miao describes Po Jun at full strength with the nerve to act in disorder; the breaking exists to build, not for its own sake.',
 cnA:'有人见命宫破军就套英星入庙，忽略了庙旺和禄会，结果时验时不验，问题在把成格条件省掉了。',
 enA:'Some apply the pattern to any Po Jun in Life while ignoring brightness and Lu meetings, then find it inconsistent; the issue is skipping the conditions that form it.',
 cnLog:['成格第一条件是破军在子、午入庙，力量舒展，落在他宫或落陷则不成立。','第二要看禄：破军带耗，最需化禄或禄存收敛耗气，破而有助才层次高。','三方见左辅右弼、魁钺、昌曲为助力，见煞忌齐来则破格。','此格主先破后立，人生常见先难后成，兑现节奏仍看大限。'],
 enLog:['The first condition is Po Jun exalted at Zi or Wu with full strength; in other palaces or fallen it does not hold.','The second is Lu: Po Jun carries drain and most needs Hua Lu or Lu Cun to restrain it, so breaking with support raises the level.','Left/Right Assistants, Kui/Yue and Chang/Qu in the trine support it, while gathered malefics and obstruction break the pattern.','It governs building after breaking, often showing difficulty before achievement, with timing still set by the decades.'],
 cnStep:['先确认命宫是否为破军、是否在子午且入庙','再查有无化禄或禄存同会，收敛耗气','合三方四正数辅星与煞星，看净助力','见煞忌齐来则谨慎，不硬套成格','看大限安排，定先破后立在哪个阶段兑现','把破的方向指向要立的事，避免只破不立'],
 enStep:['First confirm whether the Life Palace holds Po Jun at Zi or Wu and exalted','Then check whether Hua Lu or Lu Cun meets it to restrain the drain','Combine the trine to count assistant and malefic stars for net support','If malefics and obstruction gather, be cautious and do not force the pattern','Read the decade arrangement to see when build-after-break is realized','Point the breaking toward what should be built rather than only breaking'],
 cnMis:['见破军就套格，不看庙旺和禄会','只讲破不讲立，把格局用成一味折腾','忽略大限，判断不了兑现的阶段'],
 enMis:['Applying the pattern to any Po Jun without brightness and Lu','Speaking only of breaking and not building, turning the pattern into constant upheaval','Ignoring decades and unable to judge when it is realized'],
 cnClose:'英星入庙的功课，是「破得有方向、立得有本钱」。成格条件看全、节奏交给大限，这股敢破的劲才能真正建出东西。',
 enClose:'Ying Xing Ru Miao teaches breaking with direction and building with capital. Check all conditions and leave timing to the decades, and the nerve to break genuinely constructs something.'},

{cat:'zhuxing',slug:'ziwei-peiou-ziwei-tianfu-xing',focus:'紫微天府型人的配对',focusEn:'partner matches for Zi Wei and Tian Fu types',
 cnT:'紫微、天府型的人配什么伴侣：懂掌控、也给稳定的人',enT:'What Partners Suit Zi Wei and Tian Fu Types: Someone Who Understands Control and Gives Stability',
 cnD:'紫微重掌控与面子、天府重稳定与积累，这两类人适合能理解其主导感、情绪稳定、有自己底气又不正面争主导的伴侣，相处重在被理解而非被顶撞。',
 enD:'Zi Wei values control and dignity while Tian Fu values stability and accumulation; both suit steady, emotionally grounded partners who understand their lead, have their own confidence and do not fight for control head-on, where being understood matters more than being challenged.',
 cnL:'紫微天府都是「要稳、要主导」的类型，伴侣最要紧的不是更强，而是接得住这份主导、又给得了安定。',
 enL:'Zi Wei and Tian Fu both want stability and the lead; what matters most in a partner is not greater strength but holding that lead while providing steadiness.',
 cnA:'有人用「谁更强」来配紫微天府，结果两个主导硬碰，问题不在谁不好，而在没给这类型留被理解和被尊重的空间。',
 enA:'Some match Zi Wei and Tian Fu by who is stronger and end with two leads clashing; the issue is not either person but no room for the type to be understood and respected.',
 cnLog:['紫微型重面子与掌控，吃软不吃硬，适合先肯定再沟通的相处方式。','天府型重安全感与积累，适合可靠、守信、步调稳的伴侣。','两类都需要伴侣有独立底气，却以不争夺主导为前提。','配对是倾向参考而非合婚定论，关键仍在相处与经营。'],
 enLog:['Zi Wei types value dignity and control and respond better to respect than pressure, suiting affirm-then-discuss communication.','Tian Fu types value security and accumulation and suit reliable, trustworthy, steady partners.','Both need a partner with independent confidence, provided they do not contest the lead.','Matching is a tendency, not a fixed marriage verdict, and rests on how the relationship is run.'],
 cnStep:['先确认自己命宫主星偏紫微还是天府，分清主导与稳定的侧重','看自己最在意的是面子掌控还是安全积累','选伴侣时把情绪稳定、可靠守信放在前面','相处时给对方主导感和尊重，少正面争高下','同时保留各自的独立空间和底气','把配对当参考，长期仍看沟通与经营'],
 enStep:['First confirm whether your Life Palace leans Zi Wei or Tian Fu to distinguish control from stability','See whether you care most about dignity and control or security and accumulation','In choosing a partner, prioritize emotional steadiness, reliability and trust','Give the other person a sense of lead and respect in relating and contest rank less head-on','At the same time keep independent space and confidence on both sides','Treat matching as reference; the long term still rests on communication and care'],
 cnMis:['用谁更强来配对，导致硬碰硬','只看主星就下定论，忽略相处经营','要求伴侣一味顺从，反而失去对等'],
 enMis:['Matching by who is stronger and causing head-on clashes','Concluding from the star alone and ignoring how the relationship is run','Demanding total compliance and losing equality'],
 cnClose:'紫微天府型的配对功课，是找一个「尊重你主导、也陪你求稳」的人。星性只给倾向，真正留住关系的还是被理解和长期的靠谱。',
 enClose:'Matching Zi Wei and Tian Fu types teaches finding someone who respects your lead and builds stability with you; the star gives only a tendency, while being understood and steady reliability keep the relationship.'},

{cat:'zhuxing',slug:'ziwei-peiou-wuqu-tanlang-xing',focus:'武曲贪狼型人的配对',focusEn:'partner matches for Wu Qu and Tan Lang types',
 cnT:'武曲、贪狼型的人配什么伴侣：落地务实、又不被绑死的人',enT:'What Partners Suit Wu Qu and Tan Lang Types: Grounded and Practical, Yet Not Tied Down',
 cnD:'武曲务实重结果、贪狼多才爱新鲜，这两类人适合既能把日子落地、讲原则，又给彼此空间、不把关系绑死的伴侣，相处重在务实与自由的平衡。',
 enD:'Wu Qu is practical and result-focused while Tan Lang is versatile and loves novelty; both suit partners who ground daily life with principles yet give room and do not tie the relationship down, where the balance of practicality and freedom matters.',
 cnL:'武曲要的是靠谱落地，贪狼要的是新鲜和空间，能同时给这两样的伴侣才处得长。',
 enL:'Wu Qu wants reliability and grounding and Tan Lang wants novelty and room; a partner who can offer both is one who lasts.',
 cnA:'有人给武曲配太飘的人、给贪狼配太管控的人，结果一个嫌虚、一个嫌闷，问题在没对上这两类最核心的需求。',
 enA:'Some match Wu Qu with an ungrounded person and Tan Lang with a controlling one, ending with one finding it empty and the other dull; the issue is missing what each type needs most.',
 cnLog:['武曲型重实际与责任，适合守信、能一起承担现实的伴侣。','贪狼型重兴趣与自由，适合包容、不黏控、一起体验生活的伴侣。','两类都怕极端：太飘让武曲没安全感，太管让贪狼想逃。','配对是倾向参考，长期仍看价值观与相处节奏。'],
 enLog:['Wu Qu types value practicality and responsibility and suit trustworthy partners who share real burdens.','Tan Lang types value interests and freedom and suit tolerant, non-clingy partners who experience life with them.','Both fear extremes: too ungrounded leaves Wu Qu insecure and too controlling makes Tan Lang want to leave.','Matching is a tendency; the long term still rests on values and relating rhythm.'],
 cnStep:['先确认自己偏武曲还是贪狼，分清务实与自由的侧重','看自己最需要的是靠谱承担还是空间新鲜','选伴侣时把价值观和生活节奏对齐放在前面','武曲型找能落地的人，贪狼型找不黏控的人','相处时把承诺和空间都讲清楚，不靠猜','把配对当参考，长期靠共同经营'],
 enStep:['First confirm whether you lean Wu Qu or Tan Lang to distinguish practicality from freedom','See whether you most need reliable commitment or room and novelty','In choosing a partner, prioritize aligned values and life rhythm','Wu Qu types seek grounded people and Tan Lang types seek non-controlling ones','In relating, make both commitment and room clear rather than guessing','Treat matching as reference; the long term relies on shared care'],
 cnMis:['给务实型配太飘的人、给自由型配太管控的人','只看主星就下定论，不看价值观','把空间当放任、把务实当无趣'],
 enMis:['Matching grounded types with ungrounded people and free types with controlling ones','Concluding from the star alone without values','Taking room as neglect and practicality as dullness'],
 cnClose:'武曲贪狼型的配对功课，是找一个「陪你落地、也给你新鲜」的人。务实和自由平衡住了，关系才既稳得住、又不闷。',
 enClose:'Matching Wu Qu and Tan Lang types teaches finding someone who grounds you and keeps things fresh; with practicality and freedom balanced, the relationship stays steady without growing dull.'},

{cat:'zhuxing',slug:'ziwei-peiou-taiyang-taiyin-xing',focus:'太阳太阴型人的配对',focusEn:'partner matches for Sun and Moon types',
 cnT:'太阳、太阴型的人配什么伴侣：明暗互补、情绪节奏同频',enT:'What Partners Suit Sun and Moon Types: Complementary Light and Shade with Matching Emotional Rhythm',
 cnD:'太阳外放热情、主付出与照亮，太阴内敛细腻、主感受与照顾；适合明暗互补、情绪节奏同频、能彼此承接的伴侣，相处重在被回应而非单向付出。',
 enD:'The Sun is outward and warm, giving and illuminating, while the Moon is inward and sensitive, feeling and caring; they suit partners who complement light and shade, share emotional rhythm and hold each other, where being responded to matters more than one-way giving.',
 cnL:'太阳要的是付出被看见，太阴要的是感受被接住，情绪和节奏能对上的伴侣才处得暖。',
 enL:'The Sun wants giving to be seen and the Moon wants feelings to be held; a partner whose emotion and rhythm align is one who feels warm.',
 cnA:'有人让两个太阳争着付出、或两个太阴各自憋着，结果都得不到回应，问题在没做到明暗互补、节奏同频。',
 enA:'Some let two Suns compete in giving or two Moons each hold things in, and neither gets a response; the issue is the lack of complementary light and shade and shared rhythm.',
 cnLog:['太阳型热情外放，适合懂得回应、肯定其付出的伴侣。','太阴型细腻敏感，适合体贴、可靠、给安全感的伴侣。','明暗互补最稳：一外一内、一动一静，彼此承接。','配对是倾向参考，长期仍看情绪沟通与互相照顾。'],
 enLog:['Sun types are warm and outward and suit partners who respond to and affirm their giving.','Moon types are sensitive and inward and suit thoughtful, reliable partners who give security.','Complementary light and shade is steadiest: one out and one in, one active and one quiet, holding each other.','Matching is a tendency; the long term still rests on emotional communication and mutual care.'],
 cnStep:['先确认自己偏太阳还是太阴，分清外放与内敛','看自己最需要的是付出被看见还是感受被接住','选伴侣时把情绪稳定、愿意回应放在前面','尽量明暗互补，避免两个都强外放或都憋着','相处时主动表达感受，也练习接住对方','把配对当参考，长期靠互相照顾'],
 enStep:['First confirm whether you lean Sun or Moon to distinguish outward from inward','See whether you most need giving to be seen or feelings to be held','In choosing a partner, prioritize emotional steadiness and willingness to respond','Favor complementary light and shade and avoid two strong outward types or two who hold back','In relating, express feelings actively and practice holding the other','Treat matching as reference; the long term relies on mutual care'],
 cnMis:['只看主星就下定论，不看情绪节奏','两个同类型硬碰，缺互补','把单向付出当爱，忽略被回应'],
 enMis:['Concluding from the star alone without emotional rhythm','Two same types clashing without complement','Taking one-way giving as love and ignoring being responded to'],
 cnClose:'太阳太阴型的配对功课，是找一个「和你明暗互补、节奏同频」的人。付出和感受彼此接得住，关系才长久地暖。',
 enClose:'Matching Sun and Moon types teaches finding someone complementary in light and shade and aligned in rhythm; when giving and feeling are held on both sides, the relationship stays warm for long.'},

{cat:'zhuxing',slug:'ziwei-peiou-shapolang-xing',focus:'杀破狼型人的配对',focusEn:'partner matches for Sha-Po-Lang types',
 cnT:'杀破狼型的人配什么伴侣：接得住变化、各自独立的人',enT:'What Partners Suit Sha-Po-Lang Types: Someone Who Handles Change and Stays Independent',
 cnD:'七杀、破军、贪狼变动性强、节奏快、爱折腾，适合内心独立、接得住变化、有自己生活重心、不依赖对方安定的伴侣，相处重在并肩而行而非互相捆绑。',
 enD:'Qi Sha, Po Jun and Tan Lang carry strong change, fast rhythm and a love of reshaping; they suit independent partners who handle change, keep their own life focus and do not depend on the other for stability, where moving side by side matters more than binding each other.',
 cnL:'杀破狼停不下来，伴侣最要紧的不是管住他们，而是自己也站得稳、接得住这一路的变化。',
 enL:'Sha-Po-Lang cannot sit still; what matters most in a partner is not controlling them but standing steady themselves and handling the changes along the way.',
 cnA:'有人想用安全感和管控留住杀破狼，结果越管越想走，问题在没理解这类型要的是并肩的独立，不是被安排的安稳。',
 enA:'Some try to hold Sha-Po-Lang with security and control and find them wanting to leave the more they are managed; the issue is missing that the type wants side-by-side independence, not arranged stability.',
 cnLog:['杀破狼型主开创变动，生活节奏快、阶段性起伏大。','适合独立、有韧性、有自己重心的伴侣，能接变化而不被带乱。','最怕高管控、高依赖，把对方的变动当成威胁。','配对是倾向参考，长期仍看信任、空间与共同成长。'],
 enLog:['Sha-Po-Lang types pioneer change with fast rhythm and large stage-by-stage ups and downs.','They suit independent, resilient partners with their own focus who handle change without being scattered.','They most fear high control and dependence that treat the other change as a threat.','Matching is a tendency; the long term still rests on trust, room and shared growth.'],
 cnStep:['先确认自己是否偏杀破狼，认清变动是常态','选伴侣时把独立、有韧性、有自己重心放在前面','相处时给足信任和空间，少管控','找能并肩做事、一起成长的人，而非找依赖','把变化和规划讲清楚，减少对方不安','把配对当参考，长期靠信任经营'],
 enStep:['First confirm whether you lean Sha-Po-Lang and recognize change as normal','In choosing a partner, prioritize independence, resilience and their own focus','In relating, give enough trust and room and control less','Seek someone who works and grows side by side rather than someone dependent','Make change and plans clear to reduce the other unease','Treat matching as reference; the long term relies on trust'],
 cnMis:['用管控求安稳，越管对方越想走','要求杀破狼停下变化，等于否定其本性','只看主星下定论，忽略信任与空间'],
 enMis:['Seeking stability through control, where more control makes the other want to leave','Asking Sha-Po-Lang to stop changing, which denies their nature','Concluding from the star alone and ignoring trust and room'],
 cnClose:'杀破狼型的配对功课，是找一个「自己站稳、陪你变动」的人。彼此独立又并肩，变化再大也不会把关系冲散。',
 enClose:'Matching Sha-Po-Lang types teaches finding someone steady on their own who changes with you; independent yet side by side, no amount of change scatters the relationship.'},

{cat:'ganqing',slug:'ziwei-jiuqing-fuhe-nengfou-changjiu',focus:'复合能否长久',focusEn:'whether a reconciled relationship can last',
 cnT:'旧情复合能不能长久：看当初分开的问题解没解决',enT:'Can a Reconciled Relationship Last: Whether the Original Problem Was Actually Solved',
 cnD:'复合会不会长久，不取决于还爱不爱，而看当初导致分开的结构性问题是否被解决、双方是否真的改变，以及大限夫妻线是否仍在引动，先辨问题再谈回头。',
 enD:'Whether reconciliation lasts depends not on love alone but on whether the structural problem that caused the split was solved, whether both genuinely changed, and whether the decade Spouse line is still activated; diagnose the problem before discussing return.',
 cnL:'回头容易、处久难，复合前最该看的不是感情还在不在，而是当初让你们分开的那个问题还在不在。',
 enL:'Returning is easy and staying is hard; before reconciling, what matters most is not whether feelings remain but whether the problem that split you remains.',
 cnA:'有人凭一时不舍复合，几个月后因同样的事再分开，问题不在缘分尽了，而在用复合回避了当初的核心问题。',
 enA:'Some reconcile on a wave of missing each other and split again over the same matter months later; the issue is not exhausted fate but using reunion to avoid the original core problem.',
 cnLog:['先分清当初分开是外部条件、沟通模式，还是价值观与性格的结构性冲突。','外部与沟通类问题若现实改变、方法学会，复合可长久；价值观结构性冲突最难解。','看大限夫妻宫与四化，若这一阶段关系线仍反复引动，才有持续的基础。','复合是双方的事，任何一方只靠妥协忍让都难长久。'],
 enLog:['First separate whether the split came from external conditions, communication patterns, or a structural conflict of values and character.','If external or communication problems genuinely change and new methods are learned, reconciliation can last; structural value conflicts are hardest.','Read the decade Spouse Palace and transformations; only if the relationship line keeps activating in this stage is there a basis to continue.','Reconciliation belongs to both, and one side relying only on compromise rarely lasts.'],
 cnStep:['先写下当初导致分开的具体问题，不回避','归类它是外部条件、沟通模式还是价值观结构','逐项核对这些问题现在是否真的被解决','看双方是否有可见的改变，而非口头承诺','查大限夫妻线四化，判断这一阶段是否仍引动','若核心问题仍在，宁可先解决再谈复合'],
 enStep:['First write down the specific problem that caused the split without avoiding it','Classify it as external conditions, communication patterns or value structure','Check item by item whether these problems are now genuinely solved','Look for visible change on both sides rather than verbal promises','Read the decade Spouse line transformations to see whether this stage still activates it','If the core problem remains, prefer solving it before discussing reunion'],
 cnMis:['凭不舍复合，回避当初的核心问题','只听口头承诺，不看真实改变','把还爱当成能长久，忽略结构性冲突'],
 enMis:['Reconciling on longing and avoiding the original core problem','Trusting verbal promises without seeing real change','Taking remaining love as lasting while ignoring structural conflict'],
 cnClose:'复合能否长久的功课，是「先对问题、再谈感情」。当初分开的根被真正解决、双方都有改变，第二次牵手才走得远。',
 enClose:'Whether reconciliation lasts teaches facing the problem before the feelings; when the root of the split is truly solved and both change, the second joining goes far.'},

{cat:'ganqing',slug:'ziwei-yidi-changju-ganqing-ruhe-kan',focus:'异地长距感情',focusEn:'long-distance relationships',
 cnT:'异地长距感情怎么看：看信任、节奏与团聚的时间窗',enT:'How to Read Long-Distance Relationships: Trust, Rhythm and the Window to Reunite',
 cnD:'异地感情看夫妻宫、迁移宫与天马、四化，重点是信任基础、沟通节奏和有没有明确的团聚时间窗；距离本身不决定成败，看不到头才消耗人。',
 enD:'Long-distance relationships are read through the Spouse Palace, Travel Palace, Tian Ma and transformations, focusing on trust, communication rhythm and a clear window to reunite; distance itself does not decide success, but no visible end is what drains people.',
 cnL:'异地难的不是距离，是有没有一个共同的时间表，让双方都知道这段分开是暂时的、有期限的。',
 enL:'What is hard about distance is not the miles but whether a shared timeline exists so both know the separation is temporary and bounded.',
 cnA:'有人把异地失败全怪给距离，其实多数耗在沟通失序和团聚无期，问题在没把节奏和终点谈清楚。',
 enA:'Some blame distance entirely for failure, when most is spent on disordered communication and no reunion date; the issue is not making rhythm and an endpoint clear.',
 cnLog:['夫妻宫与迁移宫、天马一起看，判断这段关系是否天然带分离与奔波的象。','信任是底座，稳定的沟通节奏和透明度比一时热情更维持关系。','关键看有没有明确的团聚规划与时间窗，看不到头最易动摇。','流年四化与大限可提示什么时候有机会结束异地、走到一起。'],
 enLog:['Read the Spouse Palace together with the Travel Palace and Tian Ma to see whether the relationship naturally carries separation and movement.','Trust is the base, and steady communication rhythm and transparency sustain it more than momentary passion.','The key is whether a clear reunion plan and window exist; no visible end most easily shakes it.','Year transformations and the decade can show when there is a chance to end the distance and come together.'],
 cnStep:['先看夫妻宫主星与三方，定关系的基本相处模式','再看迁移宫、天马，判断异地奔波的成分','把沟通频率和透明度约定清楚，建立稳定节奏','一起定一个明确的团聚时间表和阶段目标','用大限流年找结束异地、团聚的时间窗','定期复盘信任和节奏，不靠猜测维持'],
 enStep:['First read the Spouse Palace major star and trine to set the basic relationship pattern','Then read the Travel Palace and Tian Ma to gauge the part of distance and travel','Agree on communication frequency and transparency to build steady rhythm','Set a clear reunion timeline and stage goals together','Use the decade and year to find the window to end distance and reunite','Review trust and rhythm regularly rather than maintaining it by guessing'],
 cnMis:['把成败全归于距离，忽略信任与节奏','没有团聚时间表，让分开看不到头','用查岗代替信任，反而消耗感情'],
 enMis:['Attributing success entirely to distance while ignoring trust and rhythm','Having no reunion timeline so separation shows no end','Replacing trust with checking up, which instead drains the relationship'],
 cnClose:'异地感情的功课，是「把信任和时间表立起来」。节奏稳、终点清楚，再远的距离也只是阶段性的考验。',
 enClose:'Long-distance teaches setting trust and a timeline; with steady rhythm and a clear endpoint, even great distance is only a stage-by-stage test.'},

{cat:'liuqin',slug:'ziwei-chengnian-hou-yu-fumu-xiangchu-bianjie',focus:'成年后与父母的边界',focusEn:'boundaries with parents in adulthood',
 cnT:'成年后怎么和父母相处：从被照顾转到有边界的互相照顾',enT:'How to Relate to Parents in Adulthood: From Being Cared For to Boundaried Mutual Care',
 cnD:'成年后与父母的关系要看父母宫与大限，重心从「被父母安排」转到「各自独立、有边界地照顾」；把尊重、边界和责任讲清楚，反而更亲。',
 enD:'The adult relationship with parents is read through the Parents Palace and decades, shifting from being arranged by them to separate, boundaried mutual care; making respect, boundaries and responsibility clear actually brings you closer.',
 cnL:'成年后的亲子关系要换一种处法，不再是谁听谁，而是两个独立的成年人之间有尊重、有边界、也有照顾。',
 enL:'The adult parent-child bond needs a new way of relating, no longer who obeys whom but respect, boundaries and care between two independent adults.',
 cnA:'有人成年后还和父母互相管控、为工作婚姻争执，问题不在谁不爱谁，而在关系没从「上下」转到「对等独立」。',
 enA:'Some still control and are controlled by parents over work and marriage as adults; the issue is not lack of love but the relationship not shifting from top-down to equal and independent.',
 cnLog:['父母宫描述与长辈、父母的缘分和相处模式，大限可提示关系在哪个阶段转变。','成年后的核心是边界：经济、居住、重大决定逐步自主，同时保留照顾责任。','边界不是疏远，而是让关心不越位、让彼此都被尊重。','沟通上从「被安排」转到「先听意见、自己决定并负责」。'],
 enLog:['The Parents Palace describes the bond and relating pattern with elders and parents, while decades show at which stage the relationship changes.','The adult core is boundaries: finances, living and major decisions gradually become self-directed while care responsibility remains.','Boundaries are not distance; they keep care from overstepping and keep both respected.','Communication shifts from being arranged to hearing input, deciding oneself and taking responsibility.'],
 cnStep:['先看父母宫主星与三方，理解和父母的固有相处模式','用大限确认关系转变的年龄段和契机','把经济、居住、重大决定的自主权逐步立起来','和父母把边界讲清楚，语气尊重、立场稳定','保留固定的关心和照顾，不让边界变成疏远','遇到分歧先听、再表达自己的决定并承担后果'],
 enStep:['First read the Parents Palace major star and trine to understand the inherent pattern with your parents','Use the decade to confirm the age and opening when the relationship changes','Gradually establish autonomy over finances, living and major decisions','Make boundaries clear to your parents with respectful tone and steady position','Keep regular care and concern so boundaries do not become distance','In disagreement, listen first, then express your decision and bear the result'],
 cnMis:['把边界当决裂，用冷战处理','经济与决定不独立，又抱怨被管控','只讲自主不讲照顾，伤了长辈的心'],
 enMis:['Taking boundaries as a break and handling them with cold war','Staying dependent in money and decisions while complaining about control','Speaking only of autonomy without care and wounding the elders'],
 cnClose:'成年后与父母相处的功课，是「独立而不疏远」。把边界立稳、把照顾留住，两个成年人之间反而能处出真正的亲近。',
 enClose:'Relating to parents as adults teaches independence without distance; with steady boundaries and continued care, two adults can build genuine closeness.'}
];
