// 2026-10-07 调研驱动 第2组：入门 4（排盘步骤/天干地支/真太阳时/身宫）+ 四化 4（禄为因忌为果/自化权/飞化与生年区别/禄忌冲宫）
module.exports=[
{cat:'rumen',slug:'ziwei-paipan-buzhou-ruhe-kan',focus:'排盘步骤',focusEn:'the steps to build a chart',
 cnT:'紫微斗数排盘步骤：从出生时辰到完整命盘',enT:'Steps to Build a Zi Wei Dou Shu Chart',
 cnD:'排盘分五步：定出生时辰与命宫身宫→安十四主星→安辅星煞星→定生年四化→检查空宫借星；现代用软件排盘，但懂步骤才读得懂盘怎么来的。',
 enD:'Building a chart has five steps: set birth time and Life/Body Palaces, place the fourteen major stars, place assistant and malefic stars, set natal transformations, and check empty palaces. Modern software does this, but knowing the steps lets you understand where the chart comes from.',
 cnL:'排盘像按图纸搭房子，命宫是地基、主星是梁柱、辅煞是门窗、四化是电路；顺序不能乱。',
 enL:'Building a chart is like erecting a house from a blueprint: Life Palace is the foundation, major stars the beams, assistants and malefics the doors and windows, transformations the wiring; order matters.',
 cnA:'有人只靠软件一键排盘、不懂步骤，结果盘一出错或时辰交界就抓瞎；懂步骤是为了能核验、能读懂。',
 enA:'Some rely on one-click software without knowing the steps, and when the chart errs or time sits on a boundary they are lost; knowing the steps lets you verify and understand.',
 cnLog:['第一步据出生年月日时定命宫、身宫位置。','第二步安紫微天府等十四主星。','第三步安左辅右弼、文昌文曲、魁钺与羊陀火铃空劫。','第四步据生年天干定四化，第五步检查空宫借星。'],
 enLog:['Step one set Life and Body Palaces from birth date and time.','Step two place the fourteen major stars including Zi Wei and Tian Fu.','Step three place Zuo Fu You Bi, Wen Chang Wen Qu, Kui Yue, and Yang Tuo Huo Ling plus emptiness.','Step four set natal transformations from the birth-year stem, five check empty palaces.'],
 cnStep:['先核对出生信息：公历或农历、性别、出生地点','据出生时辰定命宫，再定身宫','按紫微定位法安十四主星','安辅星与六煞星','据生年天干安四化','整体检查：空宫借星、星曜亮度、有无遗漏'],
 enStep:['First verify birth information: solar or lunar date, gender, birth place','Set the Life Palace from birth time, then the Body Palace','Place the fourteen major stars by the Zi Wei positioning method','Place assistant stars and six malefics','Set transformations from the birth-year stem','Overall check: empty palaces, brightness, omissions'],
 cnMis:['只靠软件不懂步骤，无法核验','时辰交界不注意，命宫可能排错','跳步骤，星曜四化漏安'],
 enMis:['Relying only on software without steps, unable to verify','Ignoring time boundaries, the Life Palace may be wrong','Skipping steps, omitting stars or transformations'],
 cnClose:'排盘步骤看的是「一张盘怎么一步步搭出来」。懂步骤、会核验，软件给你的盘你才真正读得懂、信得过。',
 enClose:'Chart-building steps ask how a chart is erected step by step. Know the steps and verify, and the chart software gives you is truly understood and trustworthy.'},

{cat:'rumen',slug:'ziwei-ganzhi-jichu-ruhe-kan',focus:'天干地支基础',focusEn:'heavenly stems and earthly branches basics',
 cnT:'天干地支基础：排盘与飞化的坐标系统',enT:'Heavenly Stems and Earthly Branches: The Coordinate System',
 cnD:'十天干、十二地支是紫微斗数的坐标：地支定十二宫位置，天干定宫干、引动四化飞星；先懂干支，才读得懂排盘和宫干飞化。',
 enD:'The ten heavenly stems and twelve earthly branches are the coordinates of Zi Wei Dou Shu: branches set the twelve palaces, stems set palace stems and activate transformations. Understand stems and branches first, then chart building and palace-stem flights.',
 cnL:'干支像地图上的经度和纬度，地支是横向的宫位坐标，天干是纵向的能量开关。',
 enL:'Stems and branches are like longitude and latitude on a map; branches are the horizontal palace coordinates, stems the vertical energy switches.',
 cnA:'有人觉得干支枯燥就跳过，结果学到宫干飞化完全接不上；干支是基础中的基础，绕不过去。',
 enA:'Some find stems and branches dry and skip them, then cannot follow palace-stem flights; stems and branches are the most basic foundation, unavoidable.',
 cnLog:['十天干：甲乙丙丁戊己庚辛壬癸，配不同四化。','十二地支：子丑寅卯辰巳午未申酉戌亥，定十二宫。','每个地支宫位配一个天干，叫宫干，宫干引动飞化。','生年天干定生年四化，如丙年天同化禄、廉贞化忌。'],
 enLog:['Ten stems: Jia Yi Bing Ding Wu Ji Geng Xin Ren Gui, each with different transformations.','Twelve branches: Zi Chou Yin Mao Chen Si Wu Wei Shen You Xu Hai, setting the twelve palaces.','Each branch palace pairs with a stem, the palace stem, which activates flights.','The birth-year stem sets natal transformations, e.g. Bing year Tian Tong Lu and Lian Zhen Ji.'],
 cnStep:['先背十天干顺序与阴阳五行','再背十二地支顺序与对应生肖','理解干支组合成六十甲子','看命盘十二宫怎么配地支','看每宫宫干，理解宫干飞化','用生年天干练习定四化'],
 enStep:['First memorize the ten stems order, yin-yang and elements','Then memorize the twelve branches order and zodiac animals','Understand stems and branches combine into sixty Jia Zi','See how the twelve palaces pair with branches','See each palace stem, understand stem flights','Practice setting transformations with the birth-year stem'],
 cnMis:['跳过干支直接学飞化，接不上','干支只死背不理解用途','把地支和宫位固定死，不懂相对关系'],
 enMis:['Skipping stems and branches to flights, unable to follow','Memorizing without understanding use','Fixing branches and palaces rigidly, missing relative relationships'],
 cnClose:'天干地支看的是「排盘和飞化的坐标」。把干支记熟、理解宫干，后面的四化飞星才有地基。',
 enClose:'Stems and branches read the coordinates for chart building and flights. Memorize them and understand palace stems, and later transformations have a foundation.'},

{cat:'rumen',slug:'ziwei-zhenshi-shijian-ruhe-kan',focus:'真太阳时',focusEn:'true solar time',
 cnT:'真太阳时怎么看：出生地经度对时辰的修正',enT:'How to Read True Solar Time in Zi Wei Dou Shu',
 cnD:'钟表时是统一时区时间，真太阳时据出生地经度修正，时辰交界尤其要算；若出生在时辰交界前后，不修正可能排错命宫，这是排盘第一道核验。',
 enD:'Clock time is unified zone time; true solar time corrects by birth-place longitude, especially at shichen boundaries. If born near a boundary, without correction the Life Palace may be wrong; this is the first verification.',
 cnL:'真太阳时像把统一的钟表时间，调回太阳在你出生地实际的位置；东西跨度大，差别能到几十分钟。',
 enL:'True solar time is like adjusting unified clock time back to the sun actual position at your birth place; across a large east-west span the difference can reach dozens of minutes.',
 cnA:'有人完全不管真太阳时，时辰交界的盘可能整个排错；也有人过度纠结几分钟，其实大多数人不在交界，影响不大。',
 enA:'Some ignore true solar time and boundary charts may be wholly wrong; others obsess over minutes, but most are not on boundaries and the effect is small.',
 cnLog:['中国统一用东八区北京时间，但东西经度跨度大。','真太阳时=钟表时+经度修正+均时差，时辰交界必算。','若出生在奇数时辰交界（如子时/丑时交界），命宫可能移位。','不在交界的盘，真太阳时通常不改变宫位。'],
 enLog:['China uses unified UTC+8 Beijing time, but spans large longitude.','True solar time = clock time + longitude correction + equation of time; boundaries require it.','If born on an odd shichen boundary, the Life Palace may shift.','For charts not on a boundary, true solar time usually does not change palaces.'],
 cnStep:['先确认出生钟表时间和出生地（经度）','判断是否在时辰交界前后约半小时','若在交界，按经度修正为真太阳时','用修正后时间重定命宫身宫','不在交界则正常排盘','存疑时结合性格经历核验命宫'],
 enStep:['First confirm birth clock time and birth place (longitude)','Judge whether within about half an hour of a shichen boundary','If on a boundary, correct to true solar time by longitude','Reset Life and Body Palaces with corrected time','If not on a boundary, build normally','When uncertain, verify the Life Palace against temperament and history'],
 cnMis:['时辰交界不算真太阳时，命宫排错','不在交界也过度纠结几分钟','完全不核验，盘错了还照读'],
 enMis:['Ignoring true solar time at boundaries, Life Palace wrong','Obsessing over minutes when not on a boundary','Not verifying, reading a wrong chart as is'],
 cnClose:'真太阳时看的是「时辰交界的盘会不会排错」。交界必算、不在交界不纠结，命宫准了，后面才读得对。',
 enClose:'True solar time asks whether boundary charts are wrong. Calculate at boundaries, do not obsess otherwise; with the Life Palace correct, later reading is right.'},

{cat:'rumen',slug:'ziwei-shenong-ruhe-kan',focus:'身宫',focusEn:'the Body Palace',
 cnT:'身宫怎么看：后天用力的方向，与命宫对读',enT:'How to Read the Body Palace: The Direction of Later Effort',
 cnD:'身宫写一个人后天的用力方向与发展重心，命宫写先天底色；身宫落在哪个宫，后天就往哪个领域使劲，命身对读才看得到一个人的走向。',
 enD:'The Body Palace holds the direction and focus of later effort, the Life Palace holds the innate tone. Whichever palace the Body Palace lands in is where later effort goes; reading both shows a person direction.',
 cnL:'命宫像出厂设置，身宫像你后天把自己活成的样子；两个宫位一致是顺，不一致是后天在调整。',
 enL:'The Life Palace is like factory settings, the Body Palace like who you later make yourself; the two aligned is smooth, misaligned is later adjustment.',
 cnA:'有人只看命宫忽略身宫，读不到后天走向；也有人把身宫当另一个命宫，其实它只写后天重心，不重写先天。',
 enA:'Some read only the Life Palace and miss later direction; others treat the Body Palace as another Life Palace, but it only writes later focus, not innate.',
 cnLog:['身宫无独立宫位，依附在命、夫妻、财帛、迁移、官禄、福德六宫之一。','身宫落命：先天后天一致；落官禄：后天重心在事业。','落财帛：重心在钱；落迁移：重心在外；落夫妻：重心在关系；落福德：重心在精神。','身宫与命宫合看，才看得到一个人完整的走向。'],
 enLog:['The Body Palace has no independent position, attached to one of Life, Spouse, Wealth, Travel, Career or Karma.','Body in Life: innate and later aligned; in Career: later focus on work.','In Wealth: focus on money; in Travel: focus outward; in Spouse: focus on relationships; in Karma: focus on spirit.','Read Body and Life together to see the complete direction.'],
 cnStep:['先找身宫依附在哪一宫','看身宫主星，定后天用力方式','命身同宫：先天后天一致，顺性发展','命身不同宫：看后天往哪个领域调整','合三方四正，读身宫的力量强弱','叠大限流年，看后天重心何时兑现'],
 enStep:['First find which palace the Body Palace attaches to','Read its star for the later effort style','Body in Life: aligned, develop with nature','Body elsewhere: see which area later adjusts toward','Combine the triple-direction to read Body Palace strength','Layer decade and year to see when later focus materializes'],
 cnMis:['只看命宫不看身宫，读不到后天走向','把身宫当另一个命宫，重写先天','身宫落宫不看主星，读不出用力方式'],
 enMis:['Reading only Life without Body, missing later direction','Treating Body as another Life Palace, rewriting innate','Reading Body position without its star, missing effort style'],
 cnClose:'身宫看的是「后天往哪使劲」。把它和命宫对读，你才看得到一个人从先天底色走到后天重心的完整路线。',
 enClose:'The Body Palace reads where later effort goes. Read it with the Life Palace, and you see the complete route from innate tone to later focus.'},

{cat:'sihua',slug:'ziwei-sihua-luwei-yin-guo-ruhe-kan',focus:'禄为因忌为果',focusEn:'Lu as cause and Ji as effect',
 cnT:'禄为因、忌为果：四化里的因果链怎么读',enT:'Lu as Cause and Ji as Effect: Reading the Cause-Effect Chain',
 cnD:'化禄主投入、机缘，是一件事的因；化忌主牵挂、结果，是一件事的果；从禄追到忌，看投入最终回报在哪、卡在哪，这是飞星读因果的核心。',
 enD:'Hua Lu governs investment and opportunity, the cause; Hua Ji governs attachment and result, the effect. Tracing from Lu to Ji shows where investment finally returns or stalls; this is the core of reading cause and effect.',
 cnL:'禄像把种子种下去，忌像最后结出的果子；种了什么、结在哪，要从禄一路追到忌。',
 enL:'Lu is like planting a seed, Ji like the final fruit; what was planted and where it fruits is traced from Lu to Ji.',
 cnA:'有人只看禄不看忌，以为投入就有回报；也有人只看忌不看禄，不知道卡点从哪来；因果要两头追。',
 enA:'Some see only Lu and assume investment returns; others see only Ji and do not know where the sticking point comes from; trace both ends.',
 cnLog:['禄主机缘、投入、结缘，是事情的起因。','忌主牵挂、亏欠、结果，是事情的收尾。','禄转忌：从禄的落点再追其宫干之忌，看最终结果。','投入的领域（禄）和结果的领域（忌）往往不在同一宫。'],
 enLog:['Lu governs opportunity, investment and connection, the cause.','Ji governs attachment, debt and result, the conclusion.','Lu-turns-to-Ji: from the Lu landing trace its stem Ji to see the final result.','The investment area (Lu) and result area (Ji) often differ.'],
 cnStep:['先立太极，定要追的事','找起点宫干化禄落在哪，定投入方向','再找化忌落在哪，定结果方向','用禄转忌再追一步，定最终落点','看落点宫星曜，定回报或卡点的具体形式','合大限背景，判断因果何时兑现'],
 enStep:['First set Tai Ji and the matter to trace','Find where the starting stem Lu lands, the investment direction','Then find where Ji lands, the result direction','Use Lu-turns-to-Ji one more step for the final landing','Read the landing stars for the concrete return or sticking point','Combine decade background to judge when cause-effect materializes'],
 cnMis:['只看禄不看忌，以为投入必回报','只看忌不看禄，不知卡点来源','不追禄转忌，读不到最终结果'],
 enMis:['Seeing only Lu and assuming investment returns','Seeing only Ji without knowing the sticking point source','Not tracing Lu-turns-to-Ji, missing the final result'],
 cnClose:'禄为因忌为果看的是「一件事从投入到结果的链条」。从禄追到忌、再追禄转忌，你才知道付出回报在哪、卡在哪。',
 enClose:'Lu as cause and Ji as effect read the chain from investment to result. Trace Lu to Ji and Lu-turns-to-Ji, and you know where effort returns and where it stalls.'},

{cat:'sihua',slug:'ziwei-zihua-quan-ruhe-kan',focus:'自化权',focusEn:'the self-transforming Hua Quan',
 cnT:'自化权怎么看：主动掌控的劲，防过刚独断',enT:'How to Read the Self-Transforming Hua Quan',
 cnD:'本宫宫干使本宫星自化权，是自己主动要掌控、要拍板的劲，利带队、创业、专业负责；与生年权的「天生掌控」不同，要防过刚、独断、听不进人。',
 enD:'When a palace stem makes its own star transform to Quan, it is the energy of actively wanting control and decisions, favoring leadership, entrepreneurship and responsibility. Unlike a natal Quan that is innate, guard being too rigid, dictatorial and deaf to others.',
 cnL:'自化权像自己给自己加了一副指挥的担子，不是别人给的位置，是自己要扛；扛得动是担当，扛过头是独断。',
 enL:'Self-transforming Quan is like taking up a command burden yourself, not a position given by others; carrying it well is responsibility, overdoing it is dictatorship.',
 cnA:'有人见自化权就当一定掌权，其实那是自己主动要控的劲；若没有实力和团队托住，越控越孤立。',
 enA:'Some take self-Quan as guaranteed authority, but it is the energy of actively wanting control; without ability and team behind it, the more you control the more isolated.',
 cnLog:['自化权=本宫宫干引动本宫星化权，主主动掌控。','与生年权不同：生年权是天生底色，自化权是后天主动要权。','利带队、创业、技术负责、需要拍板的角色。','防过刚独断、争胜、听不进异见而孤立。'],
 enLog:['Self-Quan = the palace stem activates its own star to Quan, active control.','It differs from natal Quan: natal is innate, self-Quan is later actively seeking control.','It favors leadership, entrepreneurship, technical responsibility and decision roles.','Guard rigidity, dictatorship, competitiveness and deafness to dissent leading to isolation.'],
 cnStep:['先找自化权所在宫，定主动掌控的领域','理解这是后天主动要权，不是天生位置','看本宫主星实力，定掌控有没有底气','看三方团队支撑，防只靠个人','数煞星，防过刚、争斗、口舌','刻意分权、听异见，不把掌控变独断'],
 enStep:['First find the self-Quan palace, the area of active control','Understand it as later seeking control, not an innate position','Read the home palace star ability for the backing to control','Check trine team support, not relying on the individual','Count malefics to guard rigidity, fights and disputes','Deliberately share control and hear dissent, not turning control into dictatorship'],
 cnMis:['把自化权当天生掌权、坐等','过刚独断、听不进人，把自己孤立','只看本宫不看团队实力'],
 enMis:['Taking self-Quan as innate authority and waiting','Being rigid and dictatorial, deaf to others and isolated','Reading only the home palace without team ability'],
 cnClose:'自化权看的是「主动要掌控的劲怎么用成担当」。有实力、肯分权、听得进人，这股劲才是领导力而不是独断。',
 enClose:'Self-Quan asks how active control becomes responsibility. With ability, willingness to share and hearing others, this energy is leadership rather than dictatorship.'},

{cat:'sihua',slug:'ziwei-sihua-feixing-qubie-ruhe-kan',focus:'飞化与生年四化区别',focusEn:'the difference between flying and natal transformations',
 cnT:'飞化与生年四化区别：先天静态与后天动态两层',enT:'Flying vs Natal Transformations: Two Layers',
 cnD:'生年四化由出生年天干定，是先天静态的能量底色；宫干飞化由各宫天干引动，是后天动态的因果动作；两层分开读，才不会把「天生的」和「自己做的」混为一谈。',
 enD:'Natal transformations are set by the birth-year stem, the innate static energy tone; palace-stem flights are activated by each palace stem, the later dynamic cause-effect actions. Read the two layers separately, not confusing innate with self-made.',
 cnL:'生年四化像出生就有的地形，飞化像你在地形上走出来的路；地形改不了，路怎么走在自己。',
 enL:'Natal transformations are like terrain at birth, flights like the paths you walk on that terrain; terrain cannot change, how you walk is yours.',
 cnA:'有人把飞化和生年四化混成一层，结果因果和底色分不清；先读生年定底色，再追飞化看动作，层次才清楚。',
 enA:'Some merge flights and natal transformations, and cause-effect blurs with tone; first read natal for tone, then trace flights for actions, and layers are clear.',
 cnLog:['生年四化：出生年天干引动，全盘面只有一组，静态。','飞化（宫干飞星）：十二宫各有天干，可飞出多组，动态。','生年定先天资源与卡点分布，飞化定后天主动因果。','读盘先后：先生年、再飞化，不混用。'],
 enLog:['Natal transformations: activated by birth-year stem, one set per chart, static.','Flights: each of twelve palaces has a stem and can fly multiple sets, dynamic.','Natal sets innate resource and sticking-point distribution, flights set later active cause-effect.','Reading order: natal first, then flights, not mixed.'],
 cnStep:['先找生年天干，定生年四化落宫','以生年四化定整张盘先天底色','再逐宫看宫干，找飞化','飞化看主动动作和因果方向','两层对照：后天飞化是顺先天还是逆先天','合大限流年，看哪层被引动'],
 enStep:['First find the birth-year stem and natal transformation landings','Use natal transformations to set the innate tone','Then read each palace stem for flights','Read flights for active actions and cause-effect direction','Compare layers: later flights follow or oppose innate','Combine decade and year to see which layer is activated'],
 cnMis:['把飞化和生年混成一层','只看生年不看飞化，读不到后天动作','只追飞化不读生年，没有底色'],
 enMis:['Merging flights and natal into one layer','Seeing only natal without flights, missing later actions','Tracing only flights without natal, no tone'],
 cnClose:'飞化与生年四化看的是「先天底色和后天动作两层」。先生年再飞化、分开读，你才知道什么是天生的、什么是自己走出来的。',
 enClose:'Flying vs natal transformations read two layers: innate tone and later actions. Natal first then flights, read separately, and you know what is innate and what you walk yourself.'},

{cat:'sihua',slug:'ziwei-luji-chonggong-ruhe-kan',focus:'禄忌冲宫',focusEn:'Lu and Ji clashing across opposite palaces',
 cnT:'禄忌冲宫怎么看：投入与卡点在一条线上拉扯',enT:'How to Read Lu and Ji Clashing Across Opposite Palaces',
 cnD:'化禄与化忌分守对宫相冲，是投入的方向和卡点的方向在一条直线上拉扯；禄给资源、忌给牵挂，两头都想要又互相牵制，要看哪头力量强。',
 enD:'When Lu and Ji guard opposite palaces and clash, the investment direction and sticking-point direction pull along one straight line. Lu gives resources and Ji gives attachment; both are wanted yet restrain each other, and the stronger side leads.',
 cnL:'禄忌冲宫像一根绳子两头拽，一头是想要的好处，一头是放不下的牵挂；拽得越紧，内耗越大。',
 enL:'Lu-Ji clash is like a rope pulled at both ends, one the desired benefit, one the attachment not let go; the tighter the pull, the greater the inner friction.',
 cnA:'有人见禄忌冲就判坏事，其实它是两种力量共存；关键看哪头主导、能不能把卡点转化。',
 enA:'Some call a Lu-Ji clash bad, but it is two forces coexisting; the key is which side leads and whether the sticking point can transform.',
 cnLog:['禄在本宫、忌在对宫（或反之），一条直线相冲。','禄主这头投入与资源，忌主那头牵挂与卡点。','两头力量相近时拉扯最重，差距大时强端主导。','要看星曜亮度与三方，判断哪头更有力。'],
 enLog:['Lu in the home palace and Ji opposite (or vice versa), clashing along a line.','Lu governs investment and resources at one end, Ji attachment and sticking points at the other.','When the two are close in strength the pull is heaviest; a gap lets the strong end lead.','Read star brightness and trines to judge which end is stronger.'],
 cnStep:['先定位禄和忌是否分守对宫','看禄这头的资源投入方向','看忌那头的牵挂卡点方向','比较两端星曜亮度与三方力量','强端主导：顺资源端做、化解卡点端','行动上避免两头都想要，先抓一头'],
 enStep:['First locate whether Lu and Ji guard opposite palaces','Read the Lu end resource-investment direction','Read the Ji end attachment-sticking-point direction','Compare star brightness and trine strength at both ends','Strong end leads: follow the resource end, resolve the sticking-point end','In action avoid wanting both, take one end first'],
 cnMis:['见禄忌冲就判坏事、自我恐吓','两头都想要、不取舍，内耗到底','不比较力量强弱，笼统下结论'],
 enMis:['Calling a Lu-Ji clash bad and frightening yourself','Wanting both ends without choosing, friction to the end','Not comparing strength, concluding vaguely'],
 cnClose:'禄忌冲宫看的是「投入和卡点怎么在一条线上拉扯」。分清哪头强、先抓资源端、再化卡点，这股劲才不会内耗掉。',
 enClose:'Lu-Ji clash reads how investment and sticking points pull along a line. Know which end is strong, take the resource end first and resolve the sticking point, so the energy is not lost to friction.'}
];
