// 2026-10-05 调研驱动 第4组：主星配对 3 + 婚恋 3 + 格局 2
module.exports=[
{cat:'zhuxing',slug:'ziwei-peiou-tiantong-tianliang-xing',focus:'天同天梁型人的配对',focusEn:'partnerships for Tian Tong and Tian Liang types',
 cnT:'天同、天梁型人配什么伴侣：一个怕被琐事绑住，一个需要被需要',enT:'What Tian Tong and Tian Liang Types Need in a Partner: Freedom From Trivia and the Sense of Being Needed',
 cnD:'天同重享受与情绪、怕操心，天梁重照顾与原则、爱扛事，这两类人找伴侣的关键是有人接住情绪或分担责任，又不把自己的付出与退让当成理所当然。',
 enD:'Tian Tong values comfort and feeling and dislikes worry, while Tian Liang values care and principle and tends to carry matters. The key for both is a partner who meets the emotions or shares responsibility without taking the giving and conceding for granted.',
 cnL:'天同像个需要被哄开心的孩子，天梁像个闲不住的大家长，一个要轻松、一个要被需要，找对了人彼此都松快。',
 enL:'Tian Tong is like a child who needs to be cheered, Tian Liang like a steady elder who cannot sit idle; one wants ease, the other wants to be needed, and the right partner relaxes both.',
 cnA:'有人是天同天梁型，感情里要么一味退让图清净、要么照顾对方到失去自己，问题不在遇人不淑，而在没把「我要轻松/我要被需要」的底层需求讲清楚。',
 enA:'Some Tian Tong or Tian Liang types either concede for quiet or care until they lose themselves; the issue is not a poor match but failing to name the underlying need for ease or for being needed.',
 cnLog:['天同主福、情绪与随和，天梁主荫、原则与照顾，二星都偏「柔」，感情里付出多、也怕冲突。','天同型需要能带来轻松、不制造焦虑的伴侣；天梁型需要懂得感恩、肯分担、不把照顾当义务的人。','这两类人都要防「过度退让」：边界讲清、需求说出，关系才不会一边倒。','配对是星性长短互补，不是绝对合婚，仍要看双方本命与相处。'],
 enLog:['Tian Tong governs comfort, feeling and agreeableness, Tian Liang governs shelter, principle and care; both lean soft, giving much in relationships and avoiding conflict.','Tian Tong needs a partner who brings ease without anxiety; Tian Liang needs a grateful partner who shares and does not treat care as duty.','Both guard against over-conceding: name boundaries and needs so the relationship does not tip one way.','Pairing is the complement of star traits, not an absolute marriage verdict, and still rests on both charts and conduct.'],
 cnStep:['先分清自己偏天同还是天梁，理清底层需求','天同型：找情绪稳定、能一起轻松过日子的人','天梁型：找懂感恩、肯分担责任的人','把自己的边界和需求在相处早期说清','不一味退让图清净，也不照顾到失去自己','长期看双方是否彼此珍惜、对等付出'],
 enStep:['First separate whether you lean Tian Tong or Tian Liang and clarify the underlying need','Tian Tong: seek an emotionally steady partner who enjoys an easy life together','Tian Liang: seek a grateful partner willing to share responsibility','Name your boundaries and needs early in the relationship','Neither concede for quiet nor care until you lose yourself','Over time see whether both sides cherish and give equally'],
 cnMis:['把退让当温柔，长期一边倒还委屈','天梁型逢人就照顾，把伴侣养成不担责的人','只看星性就断合不合，不看实际相处'],
 enMis:['Taking concession for tenderness until the relationship tips one way','Tian Liang types caring for everyone until the partner stops taking responsibility','Judging compatibility from star traits alone without real conduct'],
 cnClose:'天同天梁型的功课是「柔中有界」。把需求说清、把退让收住、找一个肯对等珍惜的人，你的温柔才不会被辜负。',
 enClose:'Tian Tong and Tian Liang types teach softness with boundaries. Name needs, limit concession and find someone who cherishes equally, and your tenderness is not let down.'},

{cat:'zhuxing',slug:'ziwei-peiou-tianji-tianxiang-xing',focus:'天机天相型人的配对',focusEn:'partnerships for Tian Ji and Tian Xiang types',
 cnT:'天机、天相型人配什么伴侣：一个要能商量，一个要讲规则',enT:'What Tian Ji and Tian Xiang Types Need in a Partner: Room to Talk Things Over and Clear Rules',
 cnD:'天机主动脑、善变、爱琢磨，天相主稳重、协调、讲规矩，这两类人找伴侣的关键是有人能一起商量、尊重规则与节奏，又能给多变或多虑的心一份安定。',
 enD:'Tian Ji governs thought, change and deliberation, while Tian Xiang governs steadiness, coordination and rules. The key for both is a partner who talks things through, respects rules and pace and gives the changing or worrying mind some stability.',
 cnL:'天机像停不下来的脑筋，天相像讲究分寸的管家，一个要能聊、一个要靠谱，遇到能商量又守规则的人最安心。',
 enL:'Tian Ji is like a mind that will not stop, Tian Xiang like a steward careful with measure; one wants conversation, the other reliability, and a partner who talks and keeps rules is most reassuring.',
 cnA:'有人是天机天相型，感情里要么想太多反复试探、要么太讲规矩少了温度，问题不在对方，而在没把「我需要商量、需要规则感」的底层需求表达出来。',
 enA:'Some Tian Ji or Tian Xiang types either overthink and probe or keep so much rule that warmth fades; the issue is not the partner but failing to express the need to talk things over and to feel clear rules.',
 cnLog:['天机主智谋、变动与思虑，天相主印绶、协调与规矩，二星都重「理」，感情里需要沟通与确定性。','天机型需要能深度交流、跟得上思路、又能安抚多虑的伴侣。','天相型需要守承诺、讲分寸、关系里有稳定规则的人。','两类都要防「想太多、讲太清」伤温度，理性之外也要留感性的空间。'],
 enLog:['Tian Ji governs strategy, change and thought, Tian Xiang governs the seal, coordination and rules; both value reason and need communication and certainty.','Tian Ji needs a partner who can talk deeply, keep up with the thinking and soothe worry.','Tian Xiang needs a promise-keeping partner with measure and stable rules in the relationship.','Both guard against overthinking and over-specifying that chill warmth, leaving room for feeling beside reason.'],
 cnStep:['先分清偏天机还是天相，理清底层需求','天机型：找能聊得来、情绪稳、肯安抚你的人','天相型：找守承诺、讲分寸、规则一致的人','把需要沟通和确定性的需求直接告诉对方','给关系留感性空间，不把什么都算清楚','长期看彼此是否谈得拢、也处得暖'],
 enStep:['First separate whether you lean Tian Ji or Tian Xiang and clarify the underlying need','Tian Ji: seek a conversational, steady partner willing to soothe you','Tian Xiang: seek a promise-keeping partner with measure and consistent rules','Tell the other side directly about the need for communication and certainty','Leave feeling room in the relationship rather than calculating everything','Over time see whether you talk well and stay warm together'],
 cnMis:['天机型想太多、反复试探，把对方问烦','天相型太讲规矩、少了温度和弹性','只看星性断合婚，不看真实相处'],
 enMis:['Tian Ji types overthink and probe until tiring the partner','Tian Xiang types keep too many rules with little warmth or flexibility','Judging marriage from star traits alone without real conduct'],
 cnClose:'天机天相型的功课是「理中有暖」。把沟通和规则的需求讲清，也给感情留余地，遇到能商量、靠得住的人就别错过。',
 enClose:'Tian Ji and Tian Xiang types teach reason with warmth. Name the needs for talk and rules while leaving room for feeling, and do not miss a partner who converses and is reliable.'},

{cat:'zhuxing',slug:'ziwei-peiou-lianzhen-jumen-xing',focus:'廉贞巨门型人的配对',focusEn:'partnerships for Lian Zhen and Ju Men types',
 cnT:'廉贞、巨门型人配什么伴侣：一个要坦诚，一个要能接住口角与情绪',enT:'What Lian Zhen and Ju Men Types Need in a Partner: Honesty and the Ability to Handle Words and Emotion',
 cnD:'廉贞主复杂、规矩与掌控，巨门主表达、口舌与多疑，这两类人感情里起伏偏大，关键是找一个足够坦诚、能把话讲开、不回避冲突也不记仇的人。',
 enD:'Lian Zhen governs complexity, rules and control, while Ju Men governs expression, words and suspicion, bringing larger ups and downs. The key is a partner honest enough to talk things through, neither avoiding conflict nor holding grudges.',
 cnL:'廉贞像心里有团忽明忽暗的火，巨门像一张停不下的嘴，一个怕被瞒、一个怕被曲解，遇到坦荡、能把话说开的人最踏实。',
 enL:'Lian Zhen is like a fire in the mind that flares and dims, Ju Men like words that will not stop; one fears being hidden from, the other being twisted, and an open partner who talks things through is most grounding.',
 cnA:'有人是廉贞巨门型，感情里要么掌控得紧、要么嘴上不饶人，吵完又后悔，问题不在缘分，而在没学会用坦诚替代猜忌、用沟通替代狠话。',
 enA:'Some Lian Zhen or Ju Men types either grip tightly or cut with words and regret it after; the issue is not fate but failing to replace suspicion with honesty and harsh words with communication.',
 cnLog:['廉贞主分寸、边界与掌控，巨门主口舌、表达与多疑，二星都偏「紧」，感情里考验坦诚与沟通。','廉贞型需要诚实、有边界、不玩暧昧的伴侣。','巨门型需要能讲道理、吵完就翻篇、不被狠话吓退的人。','两类都要防「话赶话、掌控紧」，学会把真实需求平静说出。'],
 enLog:['Lian Zhen governs measure, boundaries and control, Ju Men governs words, expression and suspicion; both lean tight and test honesty and communication.','Lian Zhen needs an honest partner with boundaries who does not play ambiguity.','Ju Men needs a reasonable partner who moves on after a quarrel and is not driven off by sharp words.','Both guard against escalating words and tight control, learning to state real needs calmly.'],
 cnStep:['先分清偏廉贞还是巨门，理清底层的不安','廉贞型：找诚实、有边界、不暧昧的人','巨门型：找讲道理、肯翻篇、接得住话的人','练习把狠话换成真实感受和需求','吵完对事不对人，不翻旧账、不记仇','长期看彼此是否够坦诚、吵不散'],
 enStep:['First separate whether you lean Lian Zhen or Ju Men and clarify the underlying unease','Lian Zhen: seek an honest, bounded partner without ambiguity','Ju Men: seek a reasonable partner who moves on and handles words','Practice replacing sharp words with real feelings and needs','After a quarrel stay issue-focused without reopening grudges','Over time see whether you are honest enough and cannot be split by conflict'],
 cnMis:['掌控太紧或话太狠，把对方逼走','用猜忌替代坦诚，小事吵成大矛盾','只看星性断合婚，不看相处与修为'],
 enMis:['Gripping too tightly or cutting too sharply until driving the partner off','Replacing honesty with suspicion until small issues grow','Judging marriage from star traits alone without conduct and growth'],
 cnClose:'廉贞巨门型的功课是「紧中学会坦」。把掌控放松、把狠话收住、把话讲开，遇到坦荡又吵不散的人就好好珍惜。',
 enClose:'Lian Zhen and Ju Men types teach finding openness within tension. Relax control, hold harsh words and talk things through, and cherish an open partner you cannot split by quarrel.'},

{cat:'ganqing',slug:'ziwei-hunyin-weiji-lihun-fengxian-ruhe-kan',focus:'婚姻危机与离婚风险信号',focusEn:'signs of marriage crisis and divorce risk',
 cnT:'婚姻危机、离婚风险的信号怎么看：重在提前识别、及时修复',enT:'How to Read Signs of Marriage Crisis and Divorce Risk: Early Recognition and Timely Repair',
 cnD:'盘上看婚姻风险，不是断言离不离，而是识别沟通长期失温、价值观渐行渐远、第三方介入或现实压力过载等信号，趁问题还小及时沟通、修复或寻求专业婚姻咨询。',
 enD:'Reading marriage risk is not a verdict on divorce but recognizing prolonged communication breakdown, drifting values, a third party or overload of real-world pressure, then communicating, repairing or seeking professional marriage counseling while the issue is small.',
 cnL:'婚姻的危机很少突然降临，多是一次次没说开的小事攒成的寒心，盘上能看到引动，现实里更要早早修补。',
 enL:'Marriage crisis rarely arrives suddenly; it is usually small matters never talked through that gather into chill, and while the chart shows activation, real repair should start early.',
 cnA:'有人一看到夫妻宫逢煞、逢忌就断言要离，把自己吓住，问题不在星凶，而在把「风险信号」当成了「结局」，忽略了沟通与修复的空间。',
 enA:'Some see malefics in the Spouse Palace and conclude divorce, frightening themselves; the issue is not a fierce star but taking a risk signal as the ending and ignoring room to communicate and repair.',
 cnLog:['先看本命夫妻宫三方：长期沟通模式、价值观契合度与对关系的态度。','大限夫妻线逢煞忌引动，主这一阶段关系压力偏大、易有冷战或外力干扰。','风险信号（长期失温、回避沟通、第三方、现实压力）是提醒修复，不是判决。','判断要回到双方相处与选择，必要时寻求专业婚姻咨询，不凭单星断离散。'],
 enLog:['First read the natal Spouse Palace triple-direction: the lasting communication pattern, value fit and attitude to the relationship.','When the decade relationship line meets malefics, that stage carries more pressure with cold silence or outside interference.','Risk signals such as prolonged chill, avoided talks, a third party or real pressure remind you to repair, not to sentence.','Judge from real conduct and choices, seeking professional marriage counseling when needed rather than predicting separation from one star.'],
 cnStep:['先看本命夫妻宫，定关系的长期相处底色','再看当前大限夫妻线，判断这阶段压力从哪来','把风险信号逐条对照，分清是暂时摩擦还是长期失温','遇到问题先主动沟通、就事论事，不回避、不冷战','自己解决不动时寻求专业婚姻咨询','把信号当提醒，把精力放在修复而非担忧结局'],
 enStep:['First read the natal Spouse Palace to set the lasting relationship tone','Then read the current decade relationship line to see where pressure comes from','Compare risk signals to separate temporary friction from prolonged chill','Face problems with active, issue-focused communication rather than avoidance','Seek professional marriage counseling when you cannot move things alone','Treat signals as reminders and put energy into repair rather than fearing the ending'],
 cnMis:['一见夫妻宫逢煞就断言离婚，自我恐吓','把风险信号当结局，不做任何沟通与修复','只看盘不看现实相处，忽略人的选择'],
 enMis:['Concluding divorce at the sight of malefics and frightening themselves','Taking risk signals as endings without communication or repair','Reading the chart over real conduct and ignoring human choice'],
 cnClose:'婚姻危机信号的价值，是提醒你趁问题还小去修补。把沟通做在前、把外力挡在外、肯求助，多数关系都有转圜的余地。',
 enClose:'The value of crisis signals is reminding you to repair while small. Communicate early, keep outside forces out and be willing to seek help, and most relationships have room to turn.'},

{cat:'ganqing',slug:'ziwei-panduan-zhengyuan-ruhe-kan',focus:'判断对方是不是正缘',focusEn:'judging whether someone is the right partner',
 cnT:'怎么判断对方是不是正缘：看相处的稳定与价值观，而非一时心跳',enT:'How to Judge Whether Someone Is the Right Partner: Stability and Values Over a Racing Heart',
 cnD:'正缘不是心跳最快的那个，而是相处下来情绪稳定、价值观合得来、遇事能一起解决、彼此都愿意长期投入的人；盘上看夫妻宫与三方，现实里更要看长时间的相处。',
 enD:'The right partner is not the one who makes the heart race most but the one with steady feelings, aligned values, the ability to solve problems together and willingness to commit long term. Read the Spouse Palace and triple-direction, but in reality watch the relationship over time.',
 cnL:'判断正缘像选一双走远路的鞋，合脚、稳当比一时的好看更重要，走得久不累才是真的合适。',
 enL:'Judging the right partner is like choosing shoes for a long road, where fit and steadiness matter more than momentary looks, and walking far without tiring shows real suitability.',
 cnA:'有人把心动当正缘、把平淡当无缘，结果热恋期一过就怀疑，问题不在对方，而在用「心跳的强度」替代了「相处的质量」。',
 enA:'Some take excitement as the right match and calm as no connection, then doubt once the honeymoon fades; the issue is replacing the quality of companionship with the intensity of a racing heart.',
 cnLog:['先看本命夫妻宫三方：自己适合什么样的相处模式与伴侣特质。','正缘的现实特征：情绪稳定、价值观契合、遇事能沟通、愿意共同承担。','时间是检验：热恋期后仍能自在相处、一起解决问题，才靠得住。','判断要把盘和长时间的现实相处合起来，不凭一时感觉定终身。'],
 enLog:['First read the natal Spouse Palace triple-direction: what companionship pattern and partner traits suit you.','Real traits of the right partner: steady feelings, aligned values, problem-solving communication and willingness to share responsibility.','Time is the test: staying at ease and solving problems together after the honeymoon proves reliability.','Combine the chart with long real companionship rather than deciding a lifetime on a feeling.'],
 cnStep:['先看夫妻宫，理清自己真正适合的伴侣类型','列下自己最看重的两三个价值观，看对方是否一致','观察遇事时对方是一起解决还是回避、指责','拉长时间看热恋期后相处是否依然自在','看彼此是否都愿意长期投入、共同承担','把心跳和相处质量分开，不冲动定终身'],
 enStep:['First read the Spouse Palace and clarify the partner type that truly suits you','List the few values you care about most and see whether they align','When problems arise, watch whether the other side solves together or avoids and blames','Over time see whether companionship stays at ease after the honeymoon','See whether both are willing to commit and share responsibility long term','Separate racing heart from companionship quality rather than deciding on impulse'],
 cnMis:['把心动当正缘，热度一退就怀疑','只看条件不看相处，或只看感觉不看价值观','凭一时热恋就定终身，不给时间检验'],
 enMis:['Taking excitement as the right match and doubting once the heat fades','Looking only at conditions or only at feeling without values','Deciding a lifetime on honeymoon without giving time to test'],
 cnClose:'正缘的判断，拼的不是一时的热烈，而是长久的安稳。把价值观和相处放进时间里看，对的人会越走越踏实。',
 enClose:'Judging the right partner is not about momentary heat but lasting steadiness. Put values and companionship to the test of time, and the right person feels steadier the farther you go.'},

{cat:'ganqing',slug:'ziwei-zaihun-erhun-ruhe-kan',focus:'再婚与二婚',focusEn:'second marriage and remarrying',
 cnT:'再婚、二婚的盘怎么看：先看清前段的功课，再看当下的现实基础',enT:'How to Read Remarriage: First See the Lessons of the Earlier Relationship, Then the Present Foundation',
 cnD:'看再婚不是比较谁更好，而是看前段关系留下的功课是否完成、当下两人的价值观与现实条件是否扎实、能否处理好子女与旧事，盘上看夫妻宫与大限，现实里更看坦诚与经营。',
 enD:'Reading remarriage is not comparing who is better but whether the lessons of the earlier relationship are complete, whether present values and real conditions are solid and whether children and old matters can be handled. Read the Spouse Palace and decade, but in reality watch honesty and steady effort.',
 cnL:'再婚像带着旧行李走新路，先把该放下的放下、该了结的了结，轻装、坦诚，新的路才走得稳。',
 enL:'Remarriage is like walking a new road with old luggage; set down what should be set down and close what should be closed, and a lighter, honest step steadies the new road.',
 cnA:'有人再婚时要么拿前任比现任、要么怕再受伤而不敢投入，问题不在缘分，而在前段的功课没做完、当下的现实基础没看清。',
 enA:'Some either compare the new partner to the former or hold back from fear of being hurt again; the issue is unfinished lessons and an unclear view of the present foundation.',
 cnLog:['先看本命夫妻宫与前段关系：分开的结构性问题是什么、自己学到了什么。','再看当前大限夫妻线是否引动、这一阶段是否具备重新开始的条件。','再婚的现实基础：价值观、经济、子女与旧事的处理，都要坦诚摆清。','判断要回到当下两人的经营，不被过去的阴影或一时的感动牵着走。'],
 enLog:['First read the natal Spouse Palace and the earlier relationship: what was the structural problem and what did you learn.','Then see whether the current decade relationship line activates and whether this stage offers conditions to start again.','The real foundation of remarriage: values, finances, children and old matters must be laid out honestly.','Judge from the present effort of both rather than being led by past shadows or momentary emotion.'],
 cnStep:['先复盘前段关系，把未完成的功课看明白','把该了结的旧事、债务与心结处理干净','再看当前大限夫妻线，判断重新开始的时机','和现任把价值观、经济、子女安排坦诚谈清','不拿前任比现任，也不因怕受伤而不投入','用长时间的现实经营验证这段关系'],
 enStep:['First review the earlier relationship and see the unfinished lessons','Close old matters, debts and emotional knots that should be handled','Then read the current decade relationship line to judge when to start again','Talk honestly with the present partner about values, finances and children','Neither compare present to former nor hold back from fear of hurt','Verify the relationship through long, real effort'],
 cnMis:['前段功课没做完就匆忙进入新关系','拿前任比现任，或因怕受伤而处处设防','只看感动不看现实基础，旧事未清就重启'],
 enMis:['Rushing into a new relationship before the earlier lessons are complete','Comparing present to former or guarding everywhere from fear','Seeing only emotion without the real foundation while old matters remain'],
 cnClose:'再婚的功课是「了结过去、经营当下」。把功课做完、把现实谈清、肯坦诚投入，这一次的关系反而能走得更成熟稳当。',
 enClose:'Remarriage teaches closing the past and tending the present. Complete the lessons, clarify reality and invest honestly, and this relationship can move more mature and steady.'},

{cat:'geju',slug:'ziwei-fubi-jiadi-geju-ruhe-kan',focus:'辅弼夹帝（夹命）格',focusEn:'the pattern of Zuo Fu and You Bi flanking the chart',
 cnT:'辅弼夹帝、夹命格怎么看：助力环绕的稳，仍需主星自己有力',enT:'The Pattern of Fu Bi Flanking the Emperor or Life: Surrounding Support That Still Needs a Strong Core Star',
 cnD:'左辅右弼一前一后夹命或夹紫微，主一生助力不断、有人从旁成全、做事比别人多些稳当；但夹的是「辅」，主星自己得立得住，逢煞聚空劫则助力打折。',
 enD:'When Zuo Fu and You Bi flank the Life Palace or Zi Wei from either side, support stays present with people helping from beside and steadier progress. Yet they flank as assistants and the core star must stand on its own, while gathered malefics and emptiness discount the help.',
 cnL:'辅弼夹命像走路时前后都有人照应，摔了有人扶、难了有人帮，可路终究得自己走，主星有力才用得上这些帮手。',
 enL:'Fu Bi flanking the Life Palace is like having people watch ahead and behind, steadying you when you fall, yet the road is still yours and a strong core star makes the helpers count.',
 cnA:'有人一听夹命就以为躺赢，结果自己不立、帮手也扶不起，问题不在格局假，而在把「外围的助力」当成了「自己的实力」。',
 enA:'Some hear flanking and assume an easy win, then do not establish themselves and the helpers cannot carry them; the issue is taking surrounding support for personal strength.',
 cnLog:['左辅主踏实、直接的助力，右弼主间接、圆融的协助，二星一前一后夹命，主助力环绕。','成格要主星庙旺、自己立得住，辅弼才是锦上添花；主星落陷无力，夹也扶不起来。','逢煞聚、空劫同照，助力分散或被人分走；逢魁钺、吉星则帮手更多、更稳。','格局是特质的放大，不是人生上限，仍要看四化与大限引动。'],
 enLog:['Zuo Fu gives steady, direct help and You Bi indirect, tactful assistance; flanking the Life Palace they surround it with support.','The pattern needs an exalted, self-standing core star for the assistants to add to, while a weak fallen star cannot be carried.','With gathered malefics and emptiness the support scatters; with Kui Yue and auspicious stars the helpers are more and steadier.','A pattern amplifies traits rather than capping life, and still depends on transformations and decade activation.'],
 cnStep:['先确认左辅右弼是否一前一后夹命或夹紫微','再看命宫主星是否庙旺、自己立不立得住','数三方的吉星、煞星与四化，算净助力','主星有力则借外围帮手稳步推进','主星偏弱则先立自己，不把希望全押在别人帮上','逢大限引动时把助力用在关键事上'],
 enStep:['First confirm whether Zuo Fu and You Bi flank the Life Palace or Zi Wei from either side','Then see whether the Life Palace core star is exalted and self-standing','Count auspicious stars, malefics and transformations for the net support','With a strong core star, use surrounding helpers to advance steadily','With a weak core star, establish yourself first rather than relying on others','When the decade activates, use the support on key matters'],
 cnMis:['把夹命当躺赢，自己不立、帮手也扶不起','只看辅弼不看主星庙旺与三方净组合','把格局当人生上限，忽略后天与大限'],
 enMis:['Taking flanking as an easy win while not standing and being too weak to carry','Reading Fu Bi without the core star brightness and triple-direction','Taking the pattern as a life cap while ignoring effort and the decade'],
 cnClose:'辅弼夹命格的功课是「借力先自立」。把主星立稳、把本事做实，外围的助力才真正成全你，而不是替你走路。',
 enClose:'The Fu Bi flanking pattern teaches self-reliance before borrowing help. Steady the core star and make the skill real, and surrounding support genuinely completes you rather than walking for you.'},

{cat:'geju',slug:'ziwei-zuoyou-shouyuan-weige-ruhe-kan',focus:'左右守垣格辨伪',focusEn:'evaluating whether Zuo You Shou Yuan is a genuine pattern',
 cnT:'左右守垣格是真格还是穿凿：出现条件太宽，需辨明',enT:'Is Zuo You Shou Yuan a Real Pattern or Forced? Its Conditions Are Too Broad, So Examine It',
 cnD:'口诀把左辅右弼守命称「左右守垣格」，但二星随年干排列、出现条件宽，很多盘都能沾边，单凭此称格容易穿凿；本站建议看主星、三方与四化是否配合，再决定算不算。',
 enD:'Rhyme calls it a pattern when Zuo Fu and You Bi guard the Life Palace, but the two arrange by year stem with broad conditions that many charts can meet, so naming it a pattern on that alone is forced. See whether the core star, triple-direction and transformations support it before counting it.',
 cnL:'辨别格局像验货，不能因为有个响亮名头就认，得看成格条件严不严、是不是很多盘都能凑上，凑得上的往往不是真格。',
 enL:'Judging a pattern is like inspecting goods; a famous name is not enough, and you must check whether the conditions are strict or many charts can meet them, which usually means it is not a true pattern.',
 cnA:'有人一看到左辅右弼就给自己安个贵格，名不副实还空欢喜，问题不在星不好，而在没辨「真格 / 附会」，把宽泛条件当成了硬门槛。',
 enA:'Some grant themselves an elite pattern at the sight of the two stars and rejoice without substance; the issue is not a bad star but failing to separate real from forced, taking broad conditions as a hard threshold.',
 cnLog:['左辅右弼随生年干排列，位置组合有限、出现频率高，单看守命并不稀有。','真格要主星庙旺、三方净组合好、四化引动，左右只是助力之一，不能单独撑起名头。','条件宽、人人可沾边的「格」多属穿凿附会，宜谨慎，不必妄自菲薄也不必空欢喜。','流派有别，遇分歧并列说明，本站以「主星+三方+四化」为判断基准。'],
 enLog:['Zuo Fu and You Bi arrange by birth-year stem with limited position pairs and high frequency, so guarding the Life Palace alone is not rare.','A true pattern needs an exalted core star, a good triple-direction net and transformation activation; the two are only one support and cannot carry the name alone.','Patterns with broad conditions anyone can meet are usually forced, so stay cautious without self-doubt or empty delight.','Schools differ and such differences are presented side by side; the baseline here is core star plus triple-direction plus transformations.'],
 cnStep:['先看左辅右弼是否守命，再查它们由年干得出的稀有度','看命宫主星是否庙旺、自己立不立得住','数三方四正净组合与四化引动，判断有没有真底子','若只是二星守命、其余平平，不轻易称格','理解流派分歧，不被口诀名头带着走','把辨格的尺子固定下来，再下结论'],
 enStep:['First see whether the two stars guard life, then check how rare that is given the year stem','See whether the Life Palace core star is exalted and self-standing','Count the triple-direction net and transformation activation for real foundation','If only the two stars guard life and the rest is ordinary, do not name a pattern lightly','Understand school differences rather than being led by rhyme names','Fix the ruler for judging patterns before concluding'],
 cnMis:['名头一响就认贵格，不看成格条件硬不硬','把出现频率高的组合当稀有，空欢喜','只凭左辅右弼断格局高低，不看主星三方四化'],
 enMis:['Granting an elite pattern at a famous name without checking strict conditions','Taking a frequent combination as rare and rejoicing emptily','Judging pattern level from the two stars alone without core, triple-direction and transformations'],
 cnClose:'左右守垣辨伪的功课，是学会「名头越大、越要看条件」。把主星、三方、四化这三把尺子用上，真假格局自然分得清。',
 enClose:'Evaluating Zuo You Shou Yuan teaches that the bigger the name, the more you check conditions. With the three rulers of core star, triple-direction and transformations, real and forced patterns separate clearly.'}
];
