// 2026-10-04 调研驱动 第5组：宫位3(疾厄/兄弟/福德) + 辅煞2 + 应用2 + FAQ1，共8篇
module.exports=[
{cat:'gongwei',slug:'ziwei-jiegong-ruhe-kan',focus:'疾厄宫',focusEn:'the Health Palace',
 cnT:'疾厄宫怎么看：看体质倾向，不是给自己下诊断',enT:'How to Read the Health Palace: Constitutional Tendencies, Not a Self-Diagnosis',
 cnD:'疾厄宫看的是体质偏性与容易承压的系统，结合主星、四化与大限流年，只提示要留意的方向；身体不适是倾向非诊断，务必以正规就医为准。',
 enD:'The Health Palace shows constitutional leanings and the systems most likely to bear strain; combined with major stars, transformations and timing, it only flags areas to watch. Health discomfort is a tendency, not a diagnosis, and formal medical care always takes precedence.',
 cnL:'疾厄宫不是吓人的宫位，它像一份体质说明书，告诉你哪里天生偏弱、平时该多照顾，而不是预言会得什么病。',
 enL:'The Health Palace is not a frightening palace; it is like a constitution guide telling you where you are innately softer and what to care for, not a prediction of illness.',
 cnA:'有人看到疾厄宫有煞星就吓得睡不着，也有人完全不管、硬扛小信号，两种都偏了，问题在把「倾向」要么当判决、要么当不存在。',
 enA:'Some lose sleep over a malefic in the Health Palace while others ignore it and endure small signs; both extremes come from treating a tendency either as a verdict or as nothing.',
 cnLog:['疾厄宫主体质、身体承压方式与情绪在身体上的反应，常与福德宫一起读身心。','本宫主星提示偏性，如阳主动、阴主养，煞星多则提示易有急性损耗与小伤。','生年四化与大限、流年经过疾厄，只提示某阶段要多留意，不决定具体疾病。','任何健康判断都是倾向而非诊断，务必以正规就医、体检为准，不靠命理拖延。'],
 enLog:['The Health Palace governs constitution, how the body bears strain and how emotion shows in the body, often read with the Karma Palace for body and mind.','Its major stars show leanings, active versus nurturing, while many malefics suggest acute wear and small injuries.','Natal transformations and decades or years passing through it only flag a stage to watch, not a specific illness.','Any health reading is a tendency, not a diagnosis; always rely on formal medical care and checkups rather than delaying.'],
 cnStep:['先定位疾厄宫主星，写出体质的基本偏性','合三方四正数辅星煞星，看哪里易承压','看生年四化落在哪，定先天要照顾的方向','再看大限、流年经过疾厄的阶段，提前留意作息','把倾向转成具体的作息、运动和体检安排','身体不适及时正规就医，不拿命理替代检查'],
 enStep:['First locate the Health Palace major star and write the basic constitutional leaning','Combine the trine to count assistant and malefic stars and see where strain gathers','See where natal transformations land to set the innate area to care for','Then read the stages when decades and years pass through the Health Palace and plan rest early','Turn tendencies into concrete sleep, exercise and checkup routines','Seek formal medical care promptly for discomfort rather than replacing checkups with the chart'],
 cnMis:['把煞星当判决书，过度恐慌','完全不管体质偏性，硬扛小信号','拿命理替代就医、拖延检查'],
 enMis:['Taking malefics as a verdict and panicking','Ignoring constitutional leanings and enduring small signs','Replacing medical care with the chart and delaying checkups'],
 cnClose:'疾厄宫的功课，是「把倾向当提醒、把就医当正事」。顺着体质照顾好作息、按时体检、不舒服就看医生，这颗宫位才真正帮到你。',
 enClose:'The Health Palace teaches taking tendencies as reminders and medical care as the real matter; follow your constitution with rest and checkups and see a doctor when unwell, and the palace genuinely helps you.'},

{cat:'gongwei',slug:'ziwei-xiongdigong-ruhe-kan',focus:'兄弟宫',focusEn:'the Siblings Palace',
 cnT:'兄弟宫怎么看：手足、同辈，以及合伙借贷的边界',enT:'How to Read the Siblings Palace: Siblings, Peers, and the Boundaries of Partnership and Lending',
 cnD:'兄弟宫管手足、同辈与现金存量的缘分，也旁及合伙、借贷的资源边界；有情义与讲规则要分开，凡借贷合作以专业律师、正规途径和书面合同为准。',
 enD:'The Siblings Palace governs siblings, peers and the bond over cash reserves, touching the resource boundaries of partnership and lending; warmth and rules must be kept separate, and any lending or cooperation relies on a qualified lawyer, proper channels and a written contract.',
 cnL:'兄弟宫不只看兄弟姐妹，也看你和同辈之间的资源往来，处得好是帮手，边界不清则最容易因钱伤感情。',
 enL:'The Siblings Palace covers more than brothers and sisters; it also covers resource dealings with peers, who are helpers when clear and a source of hurt over money when boundaries are vague.',
 cnA:'有人把兄弟宫只当手足关系，遇到朋友合伙、借钱才发现没规则，问题在没把「情义」和「财务边界」分开。',
 enA:'Some treat the palace as only sibling relationships and find no rules when friends partner or borrow; the issue is not separating warmth from financial boundaries.',
 cnLog:['兄弟宫主手足、同辈缘分，也常作为现金存量与短期周转的参考。','本宫星曜与四化提示同辈是助力还是消耗，化禄主靠得住、化忌主牵扯多。','合伙、借贷要另看财帛与交友，并把分工、还款、退出写进书面。','情义归情义、规则归规则，凡合同借贷以专业律师和正规途径为准。'],
 enLog:['The Siblings Palace governs siblings and peers and is also a reference for cash reserves and short-term turnover.','Its stars and transformations show whether peers support or drain, with Hua Lu reliable and Hua Ji tangled.','Partnership and lending also read the Wealth and Friends palaces, with roles, repayment and exit written down.','Warmth is warmth and rules are rules; contracts and lending rely on a qualified lawyer and proper channels.'],
 cnStep:['先定位兄弟宫主星与三方，写出手足同辈的基本缘分','看生年四化，判断同辈偏助力还是牵扯','把现金往来、周转的情况单独理清','涉及借贷先立书面，写清金额、还款和退出','合伙前把分工和责任讲明白，不靠口头义气','遇到纠纷走正规途径，以书面合同为准'],
 enStep:['First locate the Siblings Palace major star and trine to write the basic bond with siblings and peers','Read natal transformations to judge whether peers lean support or tangle','Sort cash dealings and turnover separately','For lending, set up writing first with amount, repayment and exit clear','Before partnership, make roles and responsibilities clear rather than relying on spoken loyalty','In disputes use proper channels and rely on the written contract'],
 cnMis:['只讲情义不立规则，因钱伤感情','把兄弟宫只当手足，忽略合伙借贷边界','靠口头约定，出事没有凭据'],
 enMis:['Speaking only of warmth without rules and getting hurt over money','Treating the palace as only siblings and ignoring partnership and lending boundaries','Relying on spoken agreements with no evidence when trouble comes'],
 cnClose:'兄弟宫的功课，是「情义在先、规则在手」。把书面合同和边界立起来，同辈之间才既暖、又不会因钱生分。',
 enClose:'The Siblings Palace teaches warmth first and rules in hand; with written contracts and boundaries, peer relationships stay warm without growing apart over money.'},

{cat:'gongwei',slug:'ziwei-fudegong-ruhe-kan-neixin-kuaile',focus:'福德宫与内心快乐',focusEn:'the Karma Palace and inner happiness',
 cnT:'福德宫怎么看：一个人内心快不快乐、会不会内耗',enT:'How to Read the Karma Palace: Inner Happiness and Whether the Mind Drains Itself',
 cnD:'福德宫管精神世界、情绪模式与恢复力，是内心快乐的底色；看主星、四化与三方，能看出一个人是知足常乐还是容易内耗，以及该怎么养心。',
 enD:'The Karma Palace governs the mental world, emotional patterns and resilience as the baseline of inner happiness; reading its major star, transformations and trine shows whether someone is content or prone to inner drain and how to nourish the mind.',
 cnL:'命宫是给别人看的样子，福德宫才是自己独处时的状态，内心松不松、够不够，都写在这里。',
 enL:'The Life Palace is the face others see while the Karma Palace is how you are alone; whether the mind is at ease or not is written there.',
 cnA:'有人外在条件很好却不快乐，也有人忙碌却心里踏实，差别多在福德宫，问题不在拥有多少，而在精神的底色和恢复力。',
 enA:'Some have good outer conditions yet are unhappy while others are busy but grounded; the difference often lies in the Karma Palace, and the issue is not how much is owned but the mental baseline and resilience.',
 cnLog:['福德宫主享受、兴趣、情绪与思想，也看一个人对生活的满足方式。','吉星化禄化科、昌曲辅弼会聚，主情绪稳、想得开、恢复快。','煞星（火铃羊陀）与化忌会聚，主易焦虑、内耗、睡眠与情绪波动。','福德宫也与财帛成对，赚钱的感受和花钱的态度要一起读。'],
 enLog:['The Karma Palace governs enjoyment, interests, emotion and thought, and how a person feels satisfied with life.','Auspicious stars with Hua Lu, Hua Ke, Chang/Qu or assistants bring steady emotion, perspective and quick recovery.','Malefics such as Fire, Bell and the two blades, with obstruction, bring anxiety, inner drain and sleep and mood swings.','It also pairs with the Wealth Palace, so the feeling of earning and the attitude to spending are read together.'],
 cnStep:['先定位福德宫主星，写出精神底色是外放还是内收','合三方数吉星煞星与四化，看情绪稳不稳','看化禄化科或化忌落在哪，定满足感与执着点','若煞忌多，找出最易内耗的触发场景','把结论转成养心的具体安排：作息、兴趣、运动、社交','反复内耗时配合规律作息，必要时寻求专业心理支持'],
 enStep:['First locate the Karma Palace major star and write whether the mental baseline is outward or inward','Combine the trine to count auspicious, malefic and transformation stars for emotional steadiness','See where Hua Lu, Hua Ke or Hua Ji land to set satisfaction and attachment','If malefics and obstruction gather, find the triggers most likely to cause inner drain','Turn the reading into concrete mind-care: sleep, interests, exercise and social connection','With repeated inner drain, keep regular routines and seek professional mental support when needed'],
 cnMis:['只看外在条件判断快乐，忽略精神底色','见煞星就判自己会抑郁，过度标签化','把内耗全归因想太多，不调整作息和环境'],
 enMis:['Judging happiness only by outer conditions and ignoring the mental baseline','Labeling oneself as depressed at the sight of malefics','Blaming inner drain entirely on overthinking without changing routines and environment'],
 cnClose:'福德宫的功课，是「认真照顾自己的内心」。情绪的底色看清了、恢复的方法立起来，外在的起伏就不容易把你困住。',
 enClose:'The Karma Palace teaches caring seriously for your inner world; once the emotional baseline is seen and recovery methods are set, outer ups and downs struggle to trap you.'},

{cat:'fuzhu',slug:'ziwei-zhibei-zai-minggong-ruhe-kan',focus:'指背在命宫',focusEn:'Zhi Bei in the Life Palace',
 cnT:'指背在命宫怎么看：易被背后议论，把敏感活成坦荡',enT:'Zhi Bei in the Life Palace: Easily Talked About, Turning Sensitivity Into Open Strength',
 cnD:'指背主背后非议、被人误会与名声上的小扰动，落命宫的人直觉强、在意评价；关键是把敏感用成自省与实力，行得正、少靠解释，议论自然落空。',
 enD:'Zhi Bei governs behind-the-back criticism, misunderstanding and small disturbances to reputation; in the Life Palace it brings strong intuition and concern with judgment. Use that sensitivity for self-reflection and real ability, and by acting with integrity and explaining less, the talk falls flat.',
 cnL:'指背不是大凶，更像提醒你「总会有人在背后说」，与其追着解释，不如把人做正、把事做实。',
 enL:'Zhi Bei is not a major inauspicious sign; it is more a reminder that someone will talk, and rather than chasing explanations, it is better to act with integrity and deliver solid work.',
 cnA:'有人一发现被议论就急着澄清、对号入座，结果越描越黑，问题不在议论多，而在被名声的小扰动牵着情绪走。',
 enA:'Some rush to clarify and take things personally when talked about and end up making it worse; the issue is not more talk but being led emotionally by small disturbances to reputation.',
 cnLog:['指背属戊级小星，主背后非议、指摘与误会，应事多为名声上的小扰动而非重大灾祸。','落命宫的人感受敏锐、直觉强，也容易把别人的话往心里放。','化解靠「正」与「实」：行为端正、成果扎实，比反复解释更能止息议论。','指背只作辅星层面的加减，主星与四化才主整体，不必放大。'],
 enLog:['Zhi Bei is a minor star governing behind-the-back criticism and misunderstanding, showing small disturbances to reputation rather than major misfortune.','In the Life Palace it brings keen sensitivity and intuition but also a tendency to take others words to heart.','It resolves through integrity and substance: upright conduct and solid results stop talk better than repeated explanations.','It only adds a minor adjustment, while major stars and transformations set the whole and should not be overshadowed.'],
 cnStep:['先确认命宫整体结构，不把指背单独放大','认清自己在意评价、直觉强的特点','遇到议论先分辨是否属实，不急着对号入座','属实的部分踏实改正，不属实的靠时间和行动澄清','把精力放在把事做正、做实上，少追着解释','定期自省但不自困，把敏感转成观察力'],
 enStep:['First confirm the whole Life Palace structure rather than magnifying Zhi Bei alone','Recognize your traits of caring about judgment and having strong intuition','When talked about, first check whether it is true rather than taking it personally','Correct what is true and let time and action clear what is not','Put energy into upright and solid work and chase explanations less','Reflect regularly without trapping yourself and turn sensitivity into observation'],
 cnMis:['一被议论就情绪化澄清，越描越黑','把小星放大成灾，自我恐吓','只在意别人怎么说，不把事做实'],
 enMis:['Clarifying emotionally when talked about and making it worse','Magnifying a minor star into a disaster and frightening yourself','Caring only about what others say without making work solid'],
 cnClose:'指背在命宫的功课，是「行得正、做得实、少自困」。把敏感变成自省和实力，背后的话再多也伤不到你。',
 enClose:'Zhi Bei in the Life Palace teaches acting upright, building substance and not trapping yourself; turn sensitivity into reflection and ability, and no amount of behind-the-back talk can hurt you.'},

{cat:'fuzhu',slug:'ziwei-taohuaxing-huiju-ruhe-kan',focus:'桃花星会聚',focusEn:'multiple romance stars gathering',
 cnT:'桃花星会聚怎么看：人缘魅力强，分清人缘、桃花与正缘',enT:'When Romance Stars Gather: Strong Charm, and the Need to Tell Popularity, Attraction and the Right Person Apart',
 cnD:'红鸾、天喜、咸池、天姚等桃花星同会，主人缘好、魅力强、机会多；关键是分清「好人缘、烂桃花、正缘」三件事，防暧昧损耗，关系要落到明确与负责。',
 enD:'When romance stars such as Hong Luan, Tian Xi, Xian Chi and Tian Yao meet, they bring strong popularity, charm and many chances; the key is separating good connections, draining flirtation and the right partner, guarding against ambiguous attachments and moving relationships toward clarity and responsibility.',
 cnL:'桃花星多不等于感情乱，它首先是「人缘和魅力」，怎么用、会不会挑，决定它是助力还是消耗。',
 enL:'Many romance stars do not mean a chaotic love life; they first mean popularity and charm, and how you use and choose decides whether they support or drain.',
 cnA:'有人桃花一多就陷在暧昧里、关系说不清，问题不在魅力本身，而在没把「被喜欢」和「认真选一个」分开。',
 enA:'Some, with many suitors, sink into ambiguity and unclear relationships; the issue is not charm itself but not separating being liked from seriously choosing one person.',
 cnLog:['桃花星分几类：红鸾天喜主正缘喜庆，咸池天姚主魅力、才艺与暧昧 attraction。','多星会聚主人缘旺、机会多，本身中性，吉凶看选择与自律。','要防暧昧不断、关系不明确带来的情绪与名声损耗。','正缘仍要回到夫妻宫主星、三方与四化，不能只数桃花星。'],
 enLog:['Romance stars fall into types: Hong Luan and Tian Xi govern the right partner and happy unions, while Xian Chi and Tian Yao govern charm, talent and ambiguous attraction.','Gathered stars bring strong popularity and many chances and are neutral in themselves, with the verdict set by choice and self-discipline.','Guard against constant ambiguity and unclear relationships that cost emotion and reputation.','The right partner still returns to the Spouse Palace major star, trine and transformations, not just a count of romance stars.'],
 cnStep:['先列出盘上会聚了哪些桃花星，分清类型','看夫妻宫主星与三方，定自己真正适合的关系','把好人缘和认真交往分开，不处处留暧昧','开始关系就把意图和边界讲清楚','防短期 attraction 主导选择，多看相处与价值观','婚后或确定关系后主动收束，给彼此安全感'],
 enStep:['First list which romance stars gather and separate their types','Read the Spouse Palace major star and trine to define the relationship that truly suits you','Separate good popularity from serious relating and do not leave ambiguity everywhere','Make intentions and boundaries clear when a relationship begins','Guard against short-term attraction driving choice and weigh relating and values more','After marriage or commitment, deliberately settle and give each other security'],
 cnMis:['把桃花多当感情丰富，陷在暧昧里','只数桃花星，不看夫妻宫和四化','把魅力当资本游戏，损耗名声与真心'],
 enMis:['Taking many suitors as a rich love life and sinking into ambiguity','Counting romance stars without the Spouse Palace and transformations','Using charm as a game and costing reputation and sincerity'],
 cnClose:'桃花星会聚的功课，是「接得住喜欢、也守得住专一」。把人缘当资源、把正缘当正事，魅力才不会变成消耗。',
 enClose:'Gathered romance stars teach receiving affection while keeping loyalty; treat popularity as a resource and the right partner as the real matter, and charm never becomes a drain.'},

{cat:'yingyong',slug:'ziwei-2026-bingwu-huan-gongzuo-shiji',focus:'2026换工作时机',focusEn:'the timing for changing jobs in 2026',
 cnT:'2026丙午年换工作时机：天机化权主变动，先看大限再动身',enT:'Changing Jobs in the 2026 Bing Wu Year: Tian Ji Hua Quan Drives Change, Check the Decade Before Moving',
 cnD:'2026 天机化权主事业变动与改组、廉贞化忌防人际背刺，换工作要先看大限与官禄主线、备好现金流，再挑流年流月的窗口，忌裸辞冲动（不构成职业与投资建议）。',
 enD:'In 2026 Tian Ji Hua Quan drives career change and restructuring while Lian Zhen Hua Ji warns of workplace friction; before changing jobs, read the decade and Career main line, prepare cash flow and then choose a year-or-month window, avoiding impulsive resignation. This is not career or investment advice.',
 cnL:'2026 的变动能量确实强，但「能换」不等于「该换」，先确认大限支不支持、手头有没有底，再谈什么时候动。',
 enL:'The change energy in 2026 is genuinely strong, but being able to move does not mean you should; first confirm the decade supports it and that you have reserves, then discuss timing.',
 cnA:'有人一看天机化权、工作一不顺就想裸辞，结果跳完后悔，问题不在不能换，而在把短期情绪和变动能量当成了决策依据。',
 enA:'Some, seeing Tian Ji Hua Quan and a rough patch, want to resign at once and regret it after; the issue is not that change is impossible but basing the decision on short-term emotion and change energy.',
 cnLog:['先看大限官禄主线，判断当前阶段是该积累还是该转换，这是前提。','2026 天机化权利变动与改组，但廉贞化忌提示防人际纠纷与背刺，重要关系先处理。','换工作前备好至少数月现金流，offer 与合同条款确认后再动，不裸辞。','流年、流月四化用于在已定的方向里挑递交、入职的窗口。'],
 enLog:['First read the decade Career main line to judge whether the stage calls for accumulation or change; this is the premise.','In 2026 Tian Ji Hua Quan favors change and restructuring, but Lian Zhen Hua Ji warns of workplace disputes and betrayal, so handle key relationships first.','Before changing jobs, prepare several months of cash flow and confirm the offer and contract terms before moving, rather than resigning first.','Year and month transformations choose the window to apply and start within the settled direction.'],
 cnStep:['先排本命与当前大限，看官禄主线和阶段任务','分辨想换是长期方向问题，还是一时情绪','评估新机会的岗位、成长与合同条款，不靠冲动','备足现金流缓冲，拿到确定 offer 再提离职','用流年流月四化挑递交、入职的合适窗口','入职后继续经营人际，防廉贞化忌的口舌'],
 enStep:['First cast the natal chart and current decade to read the Career main line and stage task','Tell whether the wish to change is a long-term direction issue or passing emotion','Assess the new role, growth and contract terms without impulse','Prepare enough cash buffer and resign only after a confirmed offer','Use year and month transformations to choose a good window to apply and start','After starting, keep working relationships to avoid the Lian Zhen Hua Ji disputes'],
 cnMis:['工作一不顺就裸辞，靠情绪决策','只看流年变动，不看大限主线','不留现金流、不核合同就跳，风险全自己扛'],
 enMis:['Resigning at once over a rough patch and deciding by emotion','Reading only the year change without the decade main line','Jumping without cash flow or checking the contract and carrying all the risk'],
 cnClose:'2026 换工作的功课，是「顺变动、但不被变动带着跑」。大限支持、现金有底、合同看清，再借天机化权的势动，才跳得稳。',
 enClose:'Changing jobs in 2026 teaches following change without being carried away by it; with decade support, cash reserves and a clear contract, move on the Tian Ji Hua Quan momentum and the jump is steady.'},

{cat:'yingyong',slug:'ziwei-caiwu-jiufen-ruhe-chuli',focus:'财务纠纷处理',focusEn:'handling financial disputes',
 cnT:'财务纠纷怎么处理：先看清分歧来源，再走正规途径留证据',enT:'How to Handle Financial Disputes: See the Source of Disagreement, Then Use Proper Channels and Keep Evidence',
 cnD:'财务纠纷可从财帛、兄弟、田宅的四化看分歧多发生在钱、人情还是资产上；现实处理以专业律师、正规途径和书面证据为准，先协商、讲规则，不靠斗气。',
 enD:'Financial disputes can be read through the Wealth, Siblings and Property transformations to see whether disagreement centers on money, relationships or assets; in practice rely on a qualified lawyer, proper channels and written evidence, negotiating with rules first rather than fighting on emotion.',
 cnL:'财务纠纷最怕一个「乱」字，账目和证据先理清，再按正规途径一步步走，情绪用事最吃亏。',
 enL:'What harms most in a financial dispute is disorder; first sort the accounts and evidence and then proceed step by step through proper channels, where emotion costs most.',
 cnA:'有人一遇到钱的纠纷就吵架、翻旧账，结果没凭据、更被动，问题不在谁声大，而在没把证据和正规途径放在前面。',
 enA:'Some argue and dig up old grievances at the first money dispute and end without evidence and in a weaker spot; the issue is not who is louder but failing to put evidence and proper channels first.',
 cnLog:['先分清纠纷类型：借贷、合伙分账，还是买卖、资产与合同条款，不同类型处理路径不同。','回到财帛、兄弟、田宅与四化，看分歧是利益分配、人情牵扯还是权属不清。','所有资金往来留合同、票据、转账与聊天记录，证据是处理的前提。','凡法律事项以专业律师和正规途径、书面合同为准，不私下斗气、不采取过激手段。'],
 enLog:['First separate the dispute type: lending, partnership profit split, or sale, asset and contract terms, each with a different path.','Return to Wealth, Siblings, Property and transformations to see whether disagreement is profit sharing, relationship tangle or unclear ownership.','Keep contracts, receipts, transfers and messages for all money dealings; evidence is the premise of handling it.','Legal matters rely on a qualified lawyer, proper channels and a written contract, not private feuds or extreme measures.'],
 cnStep:['先把纠纷的类型和争议金额理清楚','收集并固定合同、票据、转账和沟通记录','回到相关宫位与四化，看清分歧的真正来源','优先按合同和规则协商，提出明确方案','协商不成及时找专业律师、走正规途径','全程控制情绪，不翻旧账、不采取过激行为'],
 enStep:['First clarify the dispute type and the amount in question','Collect and secure contracts, receipts, transfers and communication records','Return to the relevant palaces and transformations to see the true source of disagreement','First negotiate by the contract and rules with a clear proposal','If negotiation fails, promptly seek a qualified lawyer and use proper channels','Control emotion throughout, avoid old grievances and extreme actions'],
 cnMis:['靠吵架和斗气解决，忽略证据','资金往来不留书面，出事很被动','不找专业律师，自作主张走偏门'],
 enMis:['Resolving through argument and emotion while ignoring evidence','Keeping nothing in writing for money dealings and ending exposed','Avoiding a qualified lawyer and taking unregulated matters into one own hands'],
 cnClose:'财务纠纷的功课，是「证据在先、规则在手、情绪靠后」。把账目理清、交给正规途径，再复杂的纠纷也能处理得有章法。',
 enClose:'Financial disputes teach evidence first, rules in hand and emotion last; sort the accounts and hand matters to proper channels, and even complex disputes are handled with order.'},

{cat:'faq',slug:'ziwei-neng-kan-shouming-zhunma',focus:'能否看寿命',focusEn:'whether longevity can be read',
 cnT:'紫微斗数能看寿命吗：看的是健康倾向，不是具体寿数',enT:'Can Zi Wei Dou Shu Read Longevity: It Shows Health Tendencies, Not a Fixed Lifespan',
 cnD:'紫微盘能从疾厄、福德与大限看体质偏性和恢复力，提示该留意的健康方向，但不能、也不应断言具体寿命；健康问题一律以正规就医为准。',
 enD:'A Zi Wei chart can read constitutional leanings and resilience through the Health Palace, Karma Palace and decades to flag health directions, but it cannot and should not assert a fixed lifespan; all health matters rely on formal medical care.',
 cnL:'寿命不是盘上能被算死的数字，盘里能读的是哪里偏弱、该怎么照顾，以及遇到大限时多留意身体。',
 enL:'Longevity is not a fixed number the chart can determine; what it can read is where you are softer, how to care for yourself and when to pay more attention during certain decades.',
 cnA:'有人拿着盘问「能活多久」，听到煞星就恐慌，问题不在星凶，而在把「健康倾向」误当成了「寿命判决」。',
 enA:'Some ask how long they will live and panic at a malefic; the issue is not a fierce star but mistaking a health tendency for a lifespan verdict.',
 cnLog:['古人文中偶有寿夭说法，那是当时语境下的极端比拟，不能当作对个人的具体断言。','盘上能读的是疾厄宫的体质偏性、福德宫的精神状态与恢复力。','大限、流年经过疾厄只提示某阶段要留意作息与体检，不决定寿数。','身体不适务必以正规就医为准，命理只作生活照顾的提醒。'],
 enLog:['Old texts occasionally mention long and short life, an extreme figure of speech in their context and never a concrete verdict on an individual.','What the chart reads is the Health Palace constitutional leaning and the Karma Palace mental state and resilience.','Decades and years passing through Health only flag a stage to watch rest and checkups, not a lifespan.','For discomfort always rely on formal medical care; the chart serves only as a reminder for daily self-care.'],
 cnStep:['先分清问的是寿命还是健康照顾，前者无法断言','用疾厄宫、福德宫看体质偏性和恢复力','把倾向转成作息、运动和定期体检安排','大限流年经过疾厄时提前留意、不拖延检查','身体不适及时正规就医，不被命理吓住或安抚住','理性看待古籍措辞，不做绝对解读'],
 enStep:['First separate whether you ask about lifespan or health care; the former cannot be asserted','Use the Health and Karma palaces to read constitutional leaning and resilience','Turn tendencies into sleep, exercise and regular checkup routines','When decades and years pass through Health, pay attention early and do not delay checkups','Seek formal medical care promptly for discomfort, neither frightened nor falsely reassured by the chart','Read old-text wording rationally without absolute interpretation'],
 cnMis:['把健康倾向当寿命判决，恐慌焦虑','据煞星断言寿数，制造心理负担','拿命理替代就医，耽误检查治疗'],
 enMis:['Taking health tendencies as a lifespan verdict and panicking','Asserting longevity from malefics and creating mental burden','Replacing medical care with the chart and delaying checkups and treatment'],
 cnClose:'这个问题的功课，是「把盘当照顾提醒、把健康交给医生」。能读的是倾向、不是寿数，规律生活加正规就医，才是对身体真正负责。',
 enClose:'This question teaches taking the chart as a care reminder and leaving health to doctors; what is readable is tendency, not lifespan, and regular living plus formal care are the true responsibility to the body.'}
];
