// 2026-10-08 调研驱动 第4组：辅煞 2（文昌总论/文曲总论）+ 流年 3（流年交接/月运/日运）+ FAQ 3（盘可以改吗/学紫微需要基础吗/命理可以全信吗）
module.exports=[
{cat:'fuzhu',slug:'ziwei-wenchang-xing-ruhe-kan',focus:'文昌星总论',focusEn:'the Wen Chang star overview',
 cnT:'文昌星总论：主文书、考试、理性、契约',enT:'The Wen Chang Star Overview: Documents, Exams and Reason',
 cnD:'文昌星主文书、考试、理性与契约，是科甲主星；逢化科文名显、利考试签约，落陷或逢煞防文书出错、契约纠纷，文昌给的是条理和文墨，不是现成功名。',
 enD:'Wen Chang governs documents, exams, reason and contracts, the star of scholarly distinction. With Hua Ke its literary name shows and favors exams and signing; fallen or with malefics, guard document errors and contract disputes. It gives order and writing, not ready distinction.',
 cnL:'文昌像一位严谨的文书，条理清、落笔准；但文书要写对内容，才不惹麻烦。',
 enL:'Wen Chang is like a rigorous scribe with clear order and precise writing; but documents need correct content to avoid trouble.',
 cnA:'有人见文昌就当考试必过，其实要化科引动、功夫下足；星给状态，不给答案。',
 enA:'Some see Wen Chang and assume exam passage, but it needs Ke activation and effort; the star gives state, not answers.',
 cnLog:['文昌主文书、考试、理性。','化科文名显，利功名。','主条理、契约、制度。','落陷逢煞，防文书出错。'],
 enLog:['Wen Chang governs documents, exams and reason.','With Ke its literary name shows, favoring distinction.','It brings order, contracts and systems.','Fallen with malefics, guard document errors.'],
 cnStep:['先看文昌所在宫与亮度','看化科引动','看流年考试签约节奏','数煞星、防文书错','把契约条款落实清楚','定文才施展领域'],
 enStep:['First read the Wen Chang palace and brightness','Read Ke activation','Read annual exam and signing timing','Count malefics to guard document errors','Put contract terms clearly','Set the literary talent area'],
 cnMis:['见文昌当必过、不努力','不防文书出错','只看文星、不看化科引动'],
 enMis:['Seeing Wen Chang and assuming passage without effort','Not guarding document errors','Seeing only the star without Ke activation'],
 cnClose:'文昌总论看的是「文书考试的条理怎么成名」。化科引动、功夫下足、防住差错，文星才成功名。',
 enClose:'Wen Chang overview asks how document-exam order becomes name. Ke activation, sufficient effort and guarding errors, and the literary star becomes distinction.'},

{cat:'fuzhu',slug:'ziwei-wenqu-xing-ruhe-kan',focus:'文曲星总论',focusEn:'the Wen Qu star overview',
 cnT:'文曲星总论：主口才、艺术、感性、异路功名',enT:'The Wen Qu Star Overview: Speech, Art and Feeling',
 cnD:'文曲星主口才、艺术、感性与异路功名，与文昌（理性）相对；逢吉化利传播、艺术、口才成名，逢煞防口舌、情绪化、感情纠葛，文曲给的是表达和感受力。',
 enD:'Wen Qu governs speech, art, feeling and distinction by an unconventional path, opposite Wen Chang (reason). With auspicious transformations it favors communication, art and verbal fame; with malefics, guard disputes, moodiness and relationship entanglement. It gives expression and sensitivity.',
 cnL:'文曲像一位感性的艺人，会说会演、感受细；但感性要配理性，才不惹情绪麻烦。',
 enL:'Wen Qu is like a feeling artist, eloquent and perceptive; but feeling needs reason to avoid emotional trouble.',
 cnA:'有人把文曲只当桃花、忽略口才艺术；也有人见文曲就当口才好，不防口舌。',
 enA:'Some take Wen Qu only as romance, ignoring speech and art; others see it and assume eloquence, not guarding disputes.',
 cnLog:['文曲主口才、艺术、感性。','异路功名，利传播演艺。','逢吉化，表达成名。','逢煞防口舌、情绪化。'],
 enLog:['Wen Qu governs speech, art and feeling.','Unconventional distinction, favoring communication and performance.','With auspicious transformations, expression becomes name.','With malefics, guard disputes and moodiness.'],
 cnStep:['先看文曲所在宫与亮度','看吉化引动','看表达艺术方向','数煞星、防口舌','配理性、防情绪化','定才华施展领域'],
 enStep:['First read the Wen Qu palace and brightness','Read auspicious transformation activation','Read expression and art direction','Count malefics to guard disputes','Pair with reason, guard moodiness','Set the talent area'],
 cnMis:['文曲只当桃花、忽略才华','不防口舌情绪','感性不配理性'],
 enMis:['Taking Wen Qu only as romance, ignoring talent','Not guarding disputes and moodiness','Feeling without reason'],
 cnClose:'文曲总论看的是「表达感受力怎么成才华之名」。逢吉化、配理性、防住口舌，文曲的艺术口才才立得稳。',
 enClose:'Wen Qu overview asks how expression and sensitivity become talent name. With auspicious transformations, reason and guarding disputes, Wen Qu art and speech stand steady.'},

{cat:'liunian',slug:'ziwei-liunian-jiaojie-ruhe-kan',focus:'流年交接',focusEn:'the transition between years',
 cnT:'流年交接怎么看：旧年与新年气怎么转、主题怎么换',enT:'How to Read the Transition Between Years',
 cnD:'流年交接看旧年与新年的四化和宫位怎么切换：旧年的主题收尾、新年的主题启动，交界前后往往事多、心不定，看清气往哪转，交接才不乱。',
 enD:'The year transition reads how old and new year transformations and palaces switch: the old theme concludes, the new begins; around the boundary matters pile and minds unsettle; see where the energy turns for an orderly transition.',
 cnL:'流年交接像换一班岗，旧岗的事要收、新岗的事要接，两头都在的时候最忙。',
 enL:'The year transition is like a shift change; old duties close and new ones begin; the busiest when both overlap.',
 cnA:'有人只看新年不管旧年收尾，结果旧事未了、新事又起；交接要两头顾。',
 enA:'Some see only the new year without closing the old, and unfinished matters pile; the transition needs both.',
 cnLog:['看旧年四化主题收尾。','看新年四化主题启动。','交界前后事多、心不定。','分清旧事新事，不混。'],
 enLog:['Read the old year transformation theme concluding.','Read the new year transformation theme starting.','Around the boundary matters pile and mind unsettles.','Separate old and new matters, not mixing.'],
 cnStep:['先看旧年主题','盘点旧年未了的事','看新年四化落宫','定新年主题方向','交界前后稳住节奏','收尾旧的、再接新的'],
 enStep:['First read the old year theme','Inventory unfinished old matters','Read new year transformation landings','Set the new year theme direction','Steady rhythm around the boundary','Close the old, then take the new'],
 cnMis:['只看新年、不收旧','新旧事混、越理越乱','交界慌乱、不看气怎么转'],
 enMis:['Seeing only the new year, not closing the old','Mixing old and new, increasingly chaotic','Panicking at the boundary, not seeing energy turn'],
 cnClose:'流年交接看的是「旧主题收尾、新主题启动」。两头顾、分清事，交接才顺、心才定。',
 enClose:'Year transition asks the old theme to close and new to start. Mind both and separate matters, and the transition is smooth and mind settled.'},

{cat:'liunian',slug:'ziwei-yueyun-ruhe-kan',focus:'月运',focusEn:'monthly fortune',
 cnT:'月运怎么看：流年盘按月重布，看一月节奏',enT:'How to Read Monthly Fortune',
 cnD:'月运在流年盘上按月重布十二宫、配月干支，看一个月的节奏与加减；它只主月内小事，大事仍看流年大限，不宜过度解读。',
 enD:'Monthly fortune rebuilds the twelve palaces by month on the annual chart with month stems, reading a month rhythm and adjustments. It governs only small matters within the month; big matters still rely on year and decade, not to be over-read.',
 cnL:'月运像把流年这张大图裁成十二张月历，看每月的小节奏，不替全年定调。',
 enL:'Monthly fortune is like cutting the year chart into twelve month calendars, seeing small rhythms, not setting the year tone.',
 cnA:'有人见一个月差就慌、见一个月好就冲，其实月运只管小事、时间短；别被月运牵着走。',
 enA:'Some panic at a bad month and charge at a good one, but monthly fortune governs small, short matters; do not be led by it.',
 cnLog:['月运按月重布流年盘。','主一月内小节奏。','大事归流年大限。','不宜过度解读。'],
 enLog:['Monthly fortune rebuilds the annual chart by month.','It governs small rhythms within a month.','Big matters belong to year and decade.','Do not over-read.'],
 cnStep:['先看流年基调','按月重布十二宫','看月干支四化','只断月内小事','安排当月节奏','不替大事下结论'],
 enStep:['First read the annual tone','Rebuild twelve palaces by month','Read month stem transformations','Only judge small matters within the month','Arrange the month rhythm','Do not conclude big matters'],
 cnMis:['月运过度解读','一个月好坏就大动作','只看月运、不看流年大限'],
 enMis:['Over-reading monthly fortune','Making big moves on one month','Seeing only months without year and decade'],
 cnClose:'月运看的是「一个月的小节奏」。它帮你安排当月，不替全年和大事定调，别被它牵着走。',
 enClose:'Monthly fortune reads a month small rhythm. It helps arrange the month, not setting year or big-matter tone; do not be led by it.'},

{cat:'liunian',slug:'ziwei-riyun-ruhe-kan',focus:'日运',focusEn:'daily fortune',
 cnT:'日运怎么看：更细一层，参考价值有限不宜执着',enT:'How to Read Daily Fortune: Limited Reference',
 cnD:'日运是比月运更细的一层，按日干支看每日起伏；斗数时辰本以两小时为单位，日运颗粒度过细、参考价值有限，不宜执着、更不该因日运决定大事。',
 enD:'Daily fortune is a layer finer than monthly, reading daily fluctuations by day stems. Zi Wei shichen itself uses two-hour units; daily fortune is too fine-grained with limited reference, not to be fixated on or used to decide big matters.',
 cnL:'日运像放大镜看一天，起伏天天有；天天盯着看，反而被小波动绑住。',
 enL:'Daily fortune is like magnifying one day, fluctuations every day; watching daily binds you to small waves.',
 cnA:'有人每天看日运、好坏都影响心情，其实日运管的太短太细；参考一下就好。',
 enA:'Some read daily fortune and let it shape mood, but it governs too briefly and finely; a glance is enough.',
 cnLog:['日运按日干支，颗粒度最细。','参考价值有限。','大事归流年大限。','不宜执着。'],
 enLog:['Daily fortune by day stems, finest grain.','Limited reference value.','Big matters belong to year and decade.','Do not fixate.'],
 cnStep:['理解日运颗粒度过细','只作当日小参考','不因日运定大事','把精力放回实际行动','看节奏以月年为主','保持平常心'],
 enStep:['Understand daily fortune is too fine-grained','Only use it as a small daily reference','Do not decide big matters by it','Put energy back into real action','Read timing mainly by month and year','Stay even-minded'],
 cnMis:['日运执着、被小波动绑住','因日运决定大事','天天看、影响心情'],
 enMis:['Fixating on daily fortune, bound by small waves','Deciding big matters by daily fortune','Watching daily, letting it shape mood'],
 cnClose:'日运看的是「一天的小起伏」。颗粒太细、价值有限，参考一下就好，别让它绑住心情和大事。',
 enClose:'Daily fortune reads a day small waves. Too fine and limited, a glance is enough; do not let it bind mood or big matters.'},

{cat:'faq',slug:'ziwei-pan-keyi-gai-ma',focus:'盘可以改吗',focusEn:'can a chart be changed',
 cnT:'命盘可以改吗：盘改不了，但选择和行动改兑现',enT:'Can a Chart Be Changed? The Chart Cannot, Choices Can',
 cnD:'命盘排出来的结构改不了，但它写的是倾向不是定局；环境、努力、关键选择能改变兑现的程度和方向，改不了的是底色，握得住的是怎么活。',
 enD:'The chart structure cannot change, but it writes tendencies not verdicts; environment, effort and key choices can change how and how much materializes. What cannot change is the tone, what is held is how to live.',
 cnL:'盘像一张地图，路线改不了，但走哪条、怎么走、走多远，在自己。',
 enL:'The chart is like a map; routes are fixed, but which to take, how and how far are yours.',
 cnA:'有人觉得盘定了就改不了、放弃努力；也有人想「改盘」、找偏门；真正能改的是兑现程度。',
 enA:'Some feel the chart fixed and give up; others seek to change the chart through dubious ways; what truly changes is materialization.',
 cnLog:['盘的结构改不了。','倾向不是定局。','选择努力改兑现。','不找改盘偏门。'],
 enLog:['Chart structure cannot change.','Tendencies are not verdicts.','Choices and effort change materialization.','Do not seek dubious chart-changing.'],
 cnStep:['先接受盘的底色','把盘读成倾向','找出可优化的方向','用选择行动改兑现','不把盘当定局','也不白费力气改盘'],
 enStep:['First accept the chart tone','Read the chart as tendencies','Find optimizable directions','Use choices and effort to change materialization','Do not take the chart as verdict','Do not waste effort changing the chart'],
 cnMis:['盘定了就放弃努力','找改盘偏门','把倾向当定局'],
 enMis:['Giving up once the chart is fixed','Seeking dubious chart-changing','Taking tendencies as verdicts'],
 cnClose:'盘改不了，但「怎么活」改得了。认下底色、把倾向当参考、用选择和努力改兑现，这才是用盘的正路。',
 enClose:'The chart cannot change, but how to live can. Accept the tone, take tendencies as reference and use choices and effort to change materialization; this is the right way.'},

{cat:'faq',slug:'ziwei-xuexi-xuyao-jichu-ma',focus:'学紫微需要基础吗',focusEn:'do you need prior foundation to learn Zi Wei',
 cnT:'学紫微需要基础吗：不必先会八字，干支补一补即可',enT:'Do You Need Prior Foundation to Learn Zi Wei?',
 cnD:'学紫微不必先会八字或别的术数，零基础也能入门；只需先补一点天干地支、阴阳五行常识，再按宫星化限顺序学，门槛没有想象的高。',
 enD:'Learning Zi Wei does not require knowing Ba Zi or other arts first; complete beginners can enter. Just supplement a little stems-branches and yin-yang elements, then learn in palace-star-transformation-limit order; the threshold is lower than imagined.',
 cnL:'紫微自成一套体系，不用先学别的打底；干支常识是唯一需要先补的。',
 enL:'Zi Wei is its own system, no prior study needed; stems-branches common sense is the only prerequisite.',
 cnA:'有人觉得没基础学不会、不敢开始；也有人跳过干支直接学飞化、结果卡住；补一点基础就顺。',
 enA:'Some feel they cannot learn without foundation and dare not start; others skip stems-branches to flights and get stuck; a little foundation smooths it.',
 cnLog:['零基础可入门。','先补干支阴阳五行。','按宫星化限顺序学。','不必先会八字。'],
 enLog:['Complete beginners can enter.','First supplement stems-branches and yin-yang elements.','Learn in palace-star-transformation-limit order.','No prior Ba Zi needed.'],
 cnStep:['先补十天干十二地支','了解阴阳五行常识','学十二宫','再学十四主星','接四化、最后大限流年','多拿盘练习'],
 enStep:['First supplement ten stems and twelve branches','Learn yin-yang elements common sense','Learn twelve palaces','Then fourteen major stars','Then transformations, finally decade and year','Practice with charts'],
 cnMis:['觉得没基础学不会','跳过干支、后面卡住','以为必须先学八字'],
 enMis:['Feeling unable to learn without foundation','Skipping stems-branches, getting stuck later','Thinking Ba Zi must be learned first'],
 cnClose:'学紫微不需要先会别的。补一点干支常识、按顺序学、多练盘，零基础一样读得懂自己的盘。',
 enClose:'Learning Zi Wei needs no prior art. Supplement some stems-branches, learn in order and practice, and beginners can read their own chart.'},

{cat:'faq',slug:'ziwei-mingli-keyi-quxin-ma',focus:'命理可以全信吗',focusEn:'can fortune telling be fully believed',
 cnT:'命理可以全信吗：不可全信，参考倾向、自己做主',enT:'Can Fortune Telling Be Fully Believed? Reference, Not Full Belief',
 cnD:'命理不可全信，也不必全不信；它给的是倾向和参考框架，决定和行动在自己，全信会失去主动权，全不信又少了一面照自己的镜子。',
 enD:'Fortortune telling can be neither fully believed nor wholly disbelieved; it gives tendencies and a reference framework, decisions and actions are yours. Full belief loses initiative, full disbelief removes a mirror for yourself.',
 cnL:'命理是参考不是指令，信它的倾向、不把决定权交出去，分寸刚好。',
 enL:'Fortune telling is reference not command; trust its tendency, do not hand over decisions; the right balance.',
 cnA:'有人全信、被盘牵着走；也有人全不信、错过自我观察；中间的「参考」才是正位。',
 enA:'Some fully believe and are led by the chart; others wholly disbelieve and miss self-observation; the middle reference is right.',
 cnLog:['不可全信、不可全不信。','给倾向参考。','决定在自己。','全信失主动、全不信少镜子。'],
 enLog:['Neither fully believe nor wholly disbelieve.','It gives tendency reference.','Decisions are yours.','Full belief loses initiative, full disbelief removes the mirror.'],
 cnStep:['把命理定位为参考','用它照自己的倾向','决定权行动权留自己','不全信、不迷信','也不全盘否定','保持批判和开放'],
 enStep:['Position fortune telling as reference','Use it to reflect your tendencies','Keep decisions and actions yourself','Do not fully believe or superstition','Do not wholly reject','Stay critical and open'],
 cnMis:['全信命理、被牵着走','全不信、错过镜子','把参考当指令'],
 enMis:['Fully believing and being led','Wholly disbelieving and missing the mirror','Taking reference as command'],
 cnClose:'命理不可全信。它给倾向、你做决定，把它当镜子和参考，主动权握在自己手里，分寸才对。',
 enClose:'Fortune telling cannot be fully believed. It gives tendencies, you decide; take it as mirror and reference, holding initiative, and the balance is right.'}
];
