// 2026-10-01 调研驱动 第3组：紫府官/机阴官/武杀官/同巨官/廉杀官/紫府田/机梁夫/廉相夫 8篇
module.exports=[
{cat:'zhuxing',slug:'ziwei-ziwei-tianfu-zai-guanlugong',focus:'紫微天府在官禄宫',focusEn:'Zi Wei and Tian Fu together in the Career Palace',
 cnT:'紫微天府同在官禄宫：事业上既有主位也有库藏，怎么把局面做大做稳',
 enT:'Zi Wei and Tian Fu in the Career Palace: Leading and Holding Resources in One Career',
 cnD:'官禄宫看做事方式与事业格局，紫微主统筹主导、天府主厚实守成，两星同落在这里，事业上既能牵头、又能稳住资源，适合管理、统筹与大型平台。风险在偏保守、缺独创、孤高，关键是在守成之外留出创新与授权。',
 enD:'The Career Palace reads how one works and the shape of a career. Zi Wei leads and coordinates while Tian Fu steadies and conserves, so together one can both initiate and hold resources, suiting management, coordination and large platforms. The risk is conservatism, weak originality and proud isolation, so the key is making room for innovation and delegation alongside stewardship.',
 cnL:'紫府在官禄的人，事业上常给人「能扛大局、也守得住摊」的印象，做事有章法、资源看得牢，只是摊子越稳，越容易在新变化面前慢半拍。',
 enL:'People with Zi Wei and Tian Fu in the Career Palace seem able to carry the big picture and hold the position, working methodically and guarding resources; the steadier the operation, the easier to lag when change arrives.',
 cnA:'这个问题在问：紫府在官禄是什么事业路数。要先理解官禄看做事方式，再看两星主导与守成如何配合、有没有辅佐。',
 enA:'The question is the career style with Zi Wei and Tian Fu in the Career Palace. Understand it reads how one works, then see how leading and conserving combine and whether support exists.',
 cnLog:['紫微在官禄，主事业上有主导权、统筹力和身份，容易被放到负责大局的位置。','天府在官禄，主做事稳、善管理资源与节奏，能把局面守住、把家底养厚。','两星同宫是「能开也能守」：适合管理、行政、财税、大型组织；见禄存化禄与辅佐星，事业大而稳。','若见煞忌，保守与孤高会放大，容易缺独创、不肯授权，遇到转型时偏被动。'],
 enLog:['Zi Wei in the Career Palace gives leadership, coordination and status, often placing one over the big picture.','Tian Fu there gives steady work and skill at managing resources and rhythm, able to hold the operation and build reserves.','Together they both open and hold, suiting management, administration, finance and large organizations; with Lu Cun, Hua Lu and supporting stars the career is large and steady.','With malefics and Ji, conservatism and proud isolation amplify, weakening originality and delegation and making transitions feel passive.'],
 cnStep:['先确认官禄宫是紫微天府同宫，并看两星亮度','看三方四正辅佐星，判断事业有没有班底与资源','把统筹大局的机会接下来，锻炼管理与担当','主动授权、培养副手，避免事事自己拍板','在守成之外留固定时间做创新和新业务尝试','结合大限流年判断事业被引动的阶段，再决定扩张或稳守'],
 enStep:['First confirm Zi Wei and Tian Fu share the Career Palace and check their brightness','Read the supporting stars in the triple-direction to judge team and resources','Take the chances to coordinate the big picture, building management and accountability','Actively delegate and develop deputies rather than deciding everything alone','Alongside stewardship, protect fixed time for innovation and new ventures','With the decade and year, see when the career is activated before expanding or holding'],
 cnMis:['把紫府在官禄只当成「要当大官、高管」，忽略班底和担当','位子一稳就保守，不肯授权也不肯尝试新东西','把孤高当威严，遇到转型反而最被动'],
 enMis:['Taking Zi Wei-Tian Fu in the Career Palace only as becoming a senior leader while ignoring team and responsibility','Becoming conservative once steady, neither delegating nor trying new things','Mistaking proud isolation for authority and ending most passive in transitions'],
 cnClose:'紫府在官禄给的是一条能主导、也能守成的事业路。把班底用起来、给创新和授权留位置，你既能把局面做大，也能在变化里守得稳。',
 enClose:'Zi Wei and Tian Fu in the Career Palace give a path that both leads and conserves. Using the team and making room for innovation and delegation lets you grow the operation while holding steady through change.'},

{cat:'zhuxing',slug:'ziwei-tianji-taiyin-zai-guanlugong',focus:'天机太阴在官禄宫',focusEn:'Tian Ji and Tai Yin together in the Career Palace',
 cnT:'天机太阴同在官禄宫：事业靠脑子也靠细致，怎么把规划做成成果',
 enT:'Tian Ji and Tai Yin in the Career Palace: A Career Built on Thought and Refinement',
 cnD:'天机善策划应变、太阴细腻懂审美，两星同在官禄，事业上适合规划、设计、文职、咨询与研究类工作，靠专业与细致立身。好处是周全有美感，风险是想太多、变动多、决断慢，关键是把策划落到节奏与成果。',
 enD:'Tian Ji plans and adapts while Tai Yin is refined and tasteful. Together in the Career Palace they suit strategy, design, office work, consulting and research, building a place through expertise and care. The strength is thoroughness and taste; the risk is overthinking, frequent change and slow decisions, so the key is turning plans into rhythm and results.',
 cnL:'机阴在官禄的人，做事常先在脑子里把方案打磨得很细，也懂审美和体察，方案漂亮；只是反复斟酌时，容易错过该拍板的点。',
 enL:'People with Tian Ji and Tai Yin in the Career Palace polish plans carefully in the mind and understand taste and empathy, producing elegant work; prolonged deliberation can miss the moment to decide.',
 cnA:'这个问题在问：机阴在官禄是什么做事方式。要先理解官禄看实践方式，再看两星的策划与细腻怎么落地。',
 enA:'The question is the work style with Tian Ji and Tai Yin in the Career Palace. Understand it reads how one practices, then see how planning and refinement land.',
 cnLog:['天机在官禄，主善策划、学习与应变，办法多、思路活，适合动脑的岗位。','太阴在官禄，主做事细、有审美、懂体察，适合文职、设计与服务型专业。','两星同宫是「又聪明又细致」：适合策划、设计、研究、文教、咨询；见禄权科与吉曜，专业容易被认可。','见煞忌则易多虑、犹豫、频繁调整，决断和推进要刻意练习。'],
 enLog:['Tian Ji in the Career Palace gives planning, learning and adaptiveness, with many approaches and lively thought, suiting intellectual roles.','Tai Yin there gives careful work, taste and empathy, suiting office, design and service professions.','Together they mean bright and refined, suiting strategy, design, research, education and consulting; with Lu, Quan, Ke and auspicious stars the expertise is recognized.','With malefics and Ji, worry, hesitation and frequent adjustment follow, so deciding and advancing must be practiced deliberately.'],
 cnStep:['先确认官禄宫是天机太阴同宫，并看两星亮度','把策划和创意写下来，避免只在脑中反复打磨','给方案设「到点就定」的截止时间，限制修改次数','把大目标拆成有节奏的小步骤，边做边调','发挥审美和细致的长处，同时练习果断与表达','结合大限流年判断事业机会的阶段，集中投入'],
 enStep:['First confirm Tian Ji and Tai Yin share the Career Palace and check their brightness','Write plans and ideas down rather than polishing only in the mind','Set a decide-by deadline for proposals and cap revisions','Break large goals into rhythmic small steps and adjust while doing','Use taste and care while practicing decisiveness and expression','With the decade and year, time concentrated effort to when career opportunity is activated'],
 cnMis:['把机阴在官禄只当成「适合脑力活」，忽略落地','方案反复打磨、迟迟不拍板，错过窗口','把细腻当犹豫的借口，专业好却推进慢'],
 enMis:['Taking Tian Ji-Tai Yin in the Career Palace only as suited to intellectual work while ignoring execution','Polishing plans and delaying decisions until the window passes','Using refinement as an excuse for hesitation, with good expertise but slow progress'],
 cnClose:'机阴在官禄给的是一条靠策划和细致立身的事业路。把想法写下来、到点就定并落到节奏，周全和美感才会变成真正的成果。',
 enClose:'Tian Ji and Tai Yin in the Career Palace give a path built on planning and care. Writing ideas down, deciding on schedule and keeping a rhythm turns thoroughness and taste into real results.'},

{cat:'zhuxing',slug:'ziwei-wuqu-qisha-zai-guanlugong',focus:'武曲七杀在官禄宫',focusEn:'Wu Qu and Qi Sha together in the Career Palace',
 cnT:'武曲七杀同在官禄宫：事业敢打硬仗，怎么把冲劲用成事业',
 enT:'Wu Qu and Qi Sha in the Career Palace: Daring Hard Battles and Turning Drive Into a Career',
 cnD:'武曲务实讲执行、七杀果敢能攻坚，两星同在官禄，事业上冲劲足、敢决断、能啃硬骨头，适合业务攻坚、工程、政法或自主创业。风险是硬碰、冒险、孤克，关键是勇而有谋、选对方向并留后路。',
 enD:'Wu Qu is pragmatic and execution-oriented while Qi Sha is courageous and tackles hard problems. Together in the Career Palace they bring strong drive, resolve and the ability to carry difficult work, suiting high-pressure sales, engineering, law, enforcement or entrepreneurship. The risk is head-on clashes, risk and solitude, so the key is courage with a plan, the right direction and a fallback.',
 cnL:'武杀在官禄的人，遇到难活反而来劲，敢拍板、敢负责，常是团队里冲在最前的人；只是一直硬碰，容易把风险和身体一起扛上。',
 enL:'People with Wu Qu and Qi Sha in the Career Palace rise to difficult work, willing to decide and answer for it, often leading from the front; constant head-on pressure can pile up both risk and physical cost.',
 cnA:'这个问题在问：武杀在官禄是什么事业风格。要先理解官禄看做事方式，再看两星的执行力有没有被风险和煞星拖累。',
 enA:'The question is the career style with Wu Qu and Qi Sha in the Career Palace. Understand it reads how one works, then see whether execution is dragged by risk and malefics.',
 cnLog:['武曲在官禄，主务实、讲结果、执行强，做事有规则也有韧劲。','七杀在官禄，主果敢、独立、能攻坚，适合开拓和高挑战岗位。','两星同宫是「硬上加硬」：事业冲劲足，见禄权科与吉曜，能凭攻坚做出位置。','见煞忌则易冒险、硬碰、少回旋，合作关系与健康要主动经营。'],
 enLog:['Wu Qu in the Career Palace gives pragmatism, results and strong execution, with rules and persistence.','Qi Sha there gives courage, independence and the ability to tackle hard problems, suiting pioneering and high-challenge roles.','Together they are doubly firm: career drive is strong, and with Lu, Quan, Ke and auspicious stars one builds a position through hard work.','With malefics and Ji, risk, head-on clashes and little room to maneuver follow, so cooperation and health need active care.'],
 cnStep:['先确认官禄宫是武曲七杀同宫，并看两星亮度','把事业上的硬仗和机会列出来，分清主次','行动前评估风险和后路，不凭血气冲','把冲劲集中到一两个主方向，避免处处开火','主动经营合作与团队，补上两星的孤克','结合大限流年判断开拓的年份，稳守的年份'],
 enStep:['First confirm Wu Qu and Qi Sha share the Career Palace and check their brightness','List the hard tasks and opportunities, sorting what matters','Weigh risk and fallback before acting rather than charging on impulse','Focus drive on one or two main directions rather than opening fire everywhere','Actively build cooperation and team to offset the stars’ solitude','With the decade and year, find the years to pioneer and the years to hold'],
 cnMis:['把武杀在官禄只当成「敢拼就能成」，忽略风险','逢硬仗就硬碰，把蛮勇当能力','只顾冲事业，忽略合作、后路与健康'],
 enMis:['Taking Wu Qu-Qi Sha in the Career Palace only as daring enough to win while ignoring risk','Meeting every hard fight head-on and mistaking brute force for ability','Pushing career alone while ignoring cooperation, fallback and health'],
 cnClose:'武杀在官禄给的是一条敢打硬仗的事业路。勇而有谋、选准方向并留好后路，这股冲劲才会变成坐得住的事业，而不是一时的冒险。',
 enClose:'Wu Qu and Qi Sha in the Career Palace give a path that dares the hard battles. With courage and a plan, the right direction and a fallback, that drive becomes a lasting career rather than a flash of risk.'},

{cat:'zhuxing',slug:'ziwei-tiantong-jumen-zai-guanlugong',focus:'天同巨门在官禄宫',focusEn:'Tian Tong and Ju Men together in the Career Palace',
 cnT:'天同巨门同在官禄宫：事业靠服务与表达，怎么把话说对、把事做稳',
 enT:'Tian Tong and Ju Men in the Career Palace: A Career Built on Service and Expression',
 cnD:'天同温和主服务、巨门善辨析主表达，两星同在官禄，事业上适合教学、传播、客服、咨询与靠沟通立身的岗位，亲和力与逻辑都不弱。风险是口舌是非、情绪起伏，关键是把表达接到专业上、把分寸立住。',
 enD:'Tian Tong is warm and service-oriented while Ju Men is analytical and expressive. Together in the Career Palace they suit teaching, communication, customer service, consulting and roles built on dialogue, with both approachability and logic. The risk is disputes and emotional ups and downs, so the key is grounding expression in expertise and holding tact.',
 cnL:'同巨在官禄的人，既愿意帮人、也能把道理讲清楚，适合靠沟通吃饭；只是话说得多、追得深时，容易在口舌和情绪上吃亏。',
 enL:'People with Tian Tong and Ju Men in the Career Palace both want to help and can reason clearly, suiting work built on dialogue; when words run long and probing runs deep, they can lose out in disputes and emotion.',
 cnA:'这个问题在问：同巨在官禄是什么做事方式。要先理解官禄看实践，再看两星的服务与表达怎么化成专业。',
 enA:'The question is the work style with Tian Tong and Ju Men in the Career Palace. Understand it reads practice, then see how service and expression become expertise.',
 cnLog:['天同在官禄，主做事温和、愿配合、重服务，给人亲和、好合作的感觉。','巨门在官禄，主善辨析、表达与研究，靠专业内容和口才立身，也主口舌两面。','两星同宫是「服务＋表达」：适合教学、传播、咨询、客服与研究；见魁钺昌曲与吉化，表达易得赏识。','见煞忌则易多言招尤、情绪内耗，开口前的停顿和分寸要练。'],
 enLog:['Tian Tong in the Career Palace gives warm, cooperative, service-oriented work and an approachable, easy-to-collaborate manner.','Ju Men there gives analysis, expression and research, building a place through expertise and eloquence while carrying the two-sided nature of words.','Together they mean service plus expression, suiting teaching, communication, consulting, customer care and research; with Kui Yue, Chang Qu and auspicious transformations the expression is recognized.','With malefics and Ji, loose words and emotional drain follow, so pausing and tact before speaking must be practiced.'],
 cnStep:['先确认官禄宫是天同巨门同宫，并看两星亮度','把沟通和服务的专长对到具体专业领域','练「开口前停一下」，区分讲理与争胜','把表达做成内容、方案和文档，而不只是口头应对','给情绪留出口（休息、倾诉、运动），避免内耗','结合大限流年判断事业机会阶段，重点发力'],
 enStep:['First confirm Tian Tong and Ju Men share the Career Palace and check their brightness','Match the communication and service strength to a concrete professional field','Practice pausing before speaking, distinguishing clarifying from winning','Turn expression into content, plans and documents rather than only verbal responses','Give emotion an outlet through rest, conversation and exercise to avoid inner drain','With the decade and year, push hardest when career opportunity is activated'],
 cnMis:['把同巨在官禄只当成「会说、适合沟通」，忽略专业支撑','好辩争胜、图嘴上痛快，结果多言招尤','把情绪带进工作，亲和力反而被内耗抵消'],
 enMis:['Taking Tian Tong-Ju Men in the Career Palace only as eloquent and suited to communication while ignoring substance','Arguing to win and inviting friction through words','Bringing emotion into work until approachability is offset by inner drain'],
 cnClose:'同巨在官禄给的是一条靠服务和表达立身的事业路。把沟通接到专业上、把分寸和情绪管好，亲和力与口才会成为你最稳的职业资本。',
 enClose:'Tian Tong and Ju Men in the Career Palace give a path built on service and expression. Grounding dialogue in expertise and managing tact and emotion makes approachability and eloquence steady career capital.'},

{cat:'zhuxing',slug:'ziwei-lianzhen-qisha-zai-guanlugong',focus:'廉贞七杀在官禄宫',focusEn:'Lian Zhen and Qi Sha together in the Career Palace',
 cnT:'廉贞七杀同在官禄宫：事业刚猛能开创，怎么把魄力用得稳',
 enT:'Lian Zhen and Qi Sha in the Career Palace: Fierce Pioneering Energy and How to Use It Steadily',
 cnD:'廉贞主原则与魄力、七杀主果敢与攻坚，两星同在官禄，事业上行动力和开创力都强，适合改革、攻坚、政法与高挑战岗位。风险是刚猛易折、冒险与刑克，关键是给魄力配上规则、风险判断和团队。',
 enD:'Lian Zhen governs principles and daring while Qi Sha governs courage and hard tasks. Together in the Career Palace they bring strong drive and pioneering ability, suiting reform, high-difficulty work, law and enforcement and demanding roles. The risk is fierce energy that snaps, risk-taking and friction, so the key is pairing daring with rules, risk judgment and a team.',
 cnL:'廉杀在官禄的人，遇到要改革、要攻坚的事反而有精神，敢负责、敢碰硬，常是能打开局面的人；只是刚猛用过头，容易在风险和关系上吃亏。',
 enL:'People with Lian Zhen and Qi Sha in the Career Palace come alive around reform and hard tasks, willing to take responsibility and confront difficulty, often the ones who open new ground; when fierce energy runs too far, risk and relationships cost them.',
 cnA:'这个问题在问：廉杀在官禄是什么事业风格。要先理解官禄看做事方式，再看两星的魄力有没有被煞忌放大成冒险。',
 enA:'The question is the career style with Lian Zhen and Qi Sha in the Career Palace. Understand it reads how one works, then see whether the daring is amplified by malefics into risk.',
 cnLog:['廉贞在官禄，主有原则、有气魄、事业心强，也主规则与边界感。','七杀在官禄，主果敢、独立、能攻坚，适合开拓型岗位。','两星同宫是「刚猛开创」：见禄权科与吉曜，魄力能化成事业与位置。','见煞忌则易冒险、硬碰、招刑伤，合作、健康与安全要格外当心。'],
 enLog:['Lian Zhen in the Career Palace gives principles, daring and strong ambition, along with a sense of rules and boundaries.','Qi Sha there gives courage, independence and the ability to tackle hard problems, suiting pioneering roles.','Together they mean fierce pioneering: with Lu, Quan, Ke and auspicious stars, daring becomes career and position.','With malefics and Ji, risk, head-on clashes and injury follow, so cooperation, health and safety need extra care.'],
 cnStep:['先确认官禄宫是廉贞七杀同宫，并看两星亮度','把想开创、想改革的方向列清楚','行动前评估风险、规则和后果，避免凭魄力硬冲','给刚猛的劲设流程和检查点，边推进边校正','主动依靠团队和专业意见，补上孤克','结合大限流年判断开拓与稳守的年份'],
 enStep:['First confirm Lian Zhen and Qi Sha share the Career Palace and check their brightness','List the directions to pioneer and reform clearly','Weigh risk, rules and consequences before acting rather than charging on daring','Build processes and checkpoints around the fierce energy and correct while advancing','Actively rely on team and professional advice to offset solitude','With the decade and year, find the years to pioneer and to hold steady'],
 cnMis:['把廉杀在官禄只当成「敢闯就能成」，忽略规则和风险','刚猛过头、硬碰硬，把魄力变成损耗','只顾开创，忽略合作、健康与安全'],
 enMis:['Taking Lian Zhen-Qi Sha in the Career Palace only as daring enough to win while ignoring rules and risk','Running fierce energy into head-on clashes until daring becomes loss','Focusing only on pioneering while neglecting cooperation, health and safety'],
 cnClose:'廉杀在官禄给的是一条刚猛开创的事业路。给魄力配上规则、风险判断和团队，这股劲才能打开局面，也能在打开之后守得住。',
 enClose:'Lian Zhen and Qi Sha in the Career Palace give a fierce, pioneering path. Pairing daring with rules, risk judgment and a team lets that energy open new ground and hold it afterward.'},

{cat:'zhuxing',slug:'ziwei-ziwei-tianfu-zai-tianzhaigong',focus:'紫微天府在田宅宫',focusEn:'Zi Wei and Tian Fu together in the Property Palace',
 cnT:'紫微天府同在田宅宫：家庭重体面也重积累，怎么把家经营稳',
 enT:'Zi Wei and Tian Fu in the Property Palace: A Home That Values Both Dignity and Accumulation',
 cnD:'田宅宫看家庭、房产与资产沉淀，紫微主体面主导、天府主厚实守藏，两星同落在这里，家庭观念重、家产相对稳、讲究居家秩序，顾家也愿意为家积累。风险是好面子、家里层级感强、偏保守，关键是让家既有体面也有松弛。',
 enD:'The Property Palace reads home, real estate and accumulated assets. Zi Wei carries dignity and leadership while Tian Fu carries solidity and storage, so family matters, relatively steady assets and orderly home life, with a willingness to build for the household. The risk is face concerns, strong hierarchy at home and conservatism, so the key is letting the home hold both dignity and ease.',
 cnL:'紫府在田宅的人，通常把家看得很重，愿意为房子、家人和家底投入，家里收拾得有章法、也讲体面；只是太讲规矩和面子时，家容易少了松弛感。',
 enL:'People with Zi Wei and Tian Fu in the Property Palace take home seriously, willing to invest in the house, family and reserves, keeping things orderly and dignified; when rules and face dominate, the home can lose ease.',
 cnA:'这个问题在问：紫府在田宅是什么家庭与资产状态。要先理解田宅看家与资产承载，再看两星的体面和守藏怎么配合。',
 enA:'The question is the home and asset situation with Zi Wei and Tian Fu in the Property Palace. Understand it reads home and asset capacity, then see how dignity and storage combine.',
 cnLog:['紫微在田宅，主家庭重体面、有主心骨，家里事有人统筹，也讲究门面与秩序。','天府在田宅，主家产厚实、善守藏，能把资产和家底慢慢养厚。','两星同宫是「又稳又有体统」：顾家、重资产积累，见禄存化禄与吉曜，田宅运稳。','见煞忌则易因面子、房产或家里层级生压，居住的松弛和沟通要主动经营。'],
 enLog:['Zi Wei in the Property Palace gives a dignified home with a clear center, where household affairs are coordinated and appearance and order matter.','Tian Fu there gives solid household assets and skill at storage, able to build reserves slowly.','Together they mean steady and orderly: family-minded and asset-building, with Lu Cun, Hua Lu and auspicious stars giving stable property fortune.','With malefics and Ji, pressure grows over face, property or hierarchy, so ease and communication at home need active care.'],
 cnStep:['先确认田宅宫是紫微天府同宫，并看两星亮度','看家庭与房产的现状，分清资产和居住两件事','把资产积累做长期规划，避免只看门面','在家讲规矩之外，主动营造松弛、平等的氛围','买房、装修、大额家用决策全家商量、留预算','结合大限流年判断田宅运引动的阶段'],
 enStep:['First confirm Zi Wei and Tian Fu share the Property Palace and check their brightness','Read the home and property situation, separating assets from daily living','Plan asset accumulation for the long term rather than only appearance','Alongside rules at home, deliberately build an easy, equal atmosphere','Make home purchase, renovation and large spending family decisions with a budget','With the decade and year, see when property fortune is activated'],
 cnMis:['把紫府在田宅只当成「家产厚、命好」，忽略经营','只重门面和体面，家里反而紧绷','买房装修凭面子决定，不留预算和沟通余地'],
 enMis:['Taking Zi Wei-Tian Fu in the Property Palace only as solid assets and good fortune while ignoring stewardship','Valuing only appearance until the home feels tense','Deciding purchases and renovation on face without budget or room to talk'],
 cnClose:'紫府在田宅给的是一个顾家、重积累也讲体面的家。把资产做长期规划、把松弛和平等补上，家才既稳得住、也待得舒服。',
 enClose:'Zi Wei and Tian Fu in the Property Palace give a family-minded home that builds and values dignity. Planning assets for the long term and adding ease and equality make the home both steady and comfortable.'},

{cat:'ganqing',slug:'ziwei-tianji-tianliang-zai-fuqigong',focus:'天机天梁在夫妻宫',focusEn:'Tian Ji and Tian Liang together in the Spouse Palace',
 cnT:'天机天梁同在夫妻宫：伴侣善思又成熟，怎么把关心不变成说教',
 enT:'Tian Ji and Tian Liang in the Spouse Palace: A Thoughtful, Mature Partner and Keeping Care From Turning Into Lectures',
 cnD:'夫妻宫看长期关系的互动模式，天机善思善变、天梁成熟能荫庇，两星同落在这里，伴侣多是聪明、有主见、肯照顾人的类型，关系里沟通和忠告不少。风险是理性过头、爱操心好说教，关键是把建议收成陪伴和尊重。',
 enD:'The Spouse Palace reads the long-term relationship pattern. Tian Ji is thoughtful and adaptive while Tian Liang is mature and protective, so partners tend to be bright, opinionated and caring, with plenty of communication and advice. The risk is excessive rationality, worry and lecturing, so the key is turning suggestions into companionship and respect.',
 cnL:'机梁在夫妻的人，遇到一个肯替你想、也肯提醒你的人，道理和照顾都不缺；只是建议一多、操心一重，容易把相处变成教导，少了轻松。',
 enL:'People with Tian Ji and Tian Liang in the Spouse Palace meet someone who thinks for them and reminds them, with no lack of reason and care; when advice and worry grow, the relationship can turn into teaching and lose lightness.',
 cnA:'这个问题在问：机梁在夫妻是什么关系模式。要先理解夫妻看长期互动，再看两星的善思和荫庇怎么化成陪伴。',
 enA:'The question is the relationship pattern with Tian Ji and Tian Liang in the Spouse Palace. Understand it reads long-term interaction, then see how thought and shelter become companionship.',
 cnLog:['天机在夫妻，主伴侣聪明、善沟通、想法多，关系里重精神交流，也容易想得多、变来变去。','天梁在夫妻，主伴侣成熟、稳重、能照顾人，像长辈一样兜底，也主操心与原则。','两星同宫是「善思＋荫庇」：沟通深、照顾足，见禄权科与吉曜，关系稳定而有人托底。','见煞忌则易说教、唠叨、理性压过感情，倾听和留白要练。'],
 enLog:['Tian Ji in the Spouse Palace gives a bright, communicative partner with many ideas who values mental exchange, while tending to overthink and shift.','Tian Liang there gives a mature, steady, nurturing partner who catches you like an elder, while carrying worry and principle.','Together they mean thought plus shelter: deep communication and ample care, and with Lu, Quan, Ke and auspicious stars the relationship is stable and supported.','With malefics and Ji, lecturing, nagging and rationality over feeling follow, so listening and white space must be practiced.'],
 cnStep:['先确认夫妻宫是天机天梁同宫，并看两星亮度','把伴侣给的关心和建议分「陪伴」和「教导」两类','提建议前先倾听、共情，确认对方是否需要主意','把操心收成信任，给关系留轻松和留白','约定不翻旧账、不事事分析，保留情分和趣味','结合大限流年判断关系被引动的阶段，共同成长'],
 enStep:['First confirm Tian Ji and Tian Liang share the Spouse Palace and check their brightness','Sort the partner’s care and advice into companionship and teaching','Before suggesting, listen and empathize and check whether advice is even wanted','Turn worry into trust and leave the relationship light with white space','Agree not to revisit old issues or analyze everything, keeping warmth and play','With the decade and year, grow together as the relationship is activated'],
 cnMis:['把机梁在夫妻只当成「伴侣成熟靠谱」，忽略相处的轻松','好操心、爱说教，把关心变成压力','理性分析一切，把情分和趣味分析没了'],
 enMis:['Taking Tian Ji-Tian Liang in the Spouse Palace only as a mature, reliable partner while ignoring lightness','Worrying and lecturing until care becomes pressure','Analyzing everything rationally until warmth and play disappear'],
 cnClose:'机梁在夫妻给的是一个善沟通、肯照顾的成熟关系。把建议收成陪伴、把操心收成信任，关系既有深度，也不会被说教和理性压住。',
 enClose:'Tian Ji and Tian Liang in the Spouse Palace give a mature relationship that communicates and cares. Turning suggestions into companionship and worry into trust gives the bond depth without being weighed down by lectures and rationality.'},

{cat:'ganqing',slug:'ziwei-lianzhen-tianxiang-zai-fuqigong',focus:'廉贞天相在夫妻宫',focusEn:'Lian Zhen and Tian Xiang together in the Spouse Palace',
 cnT:'廉贞天相同在夫妻宫：伴侣有原则也懂分寸，怎么处好外柔内刚的关系',
 enT:'Lian Zhen and Tian Xiang in the Spouse Palace: A Principled, Tactful Partner in a Bond That Is Soft Outside and Firm Within',
 cnD:'廉贞主原则与感受、天相主正派与分寸，两星同在夫妻，伴侣多是有规矩、懂体面、外柔内刚的类型，关系讲责任也讲分寸。风险是敏感、规则感过强、遇事纠缠，关键是把原则用在边界上、把柔软留给日常。',
 enD:'Lian Zhen governs principles and feeling while Tian Xiang governs integrity and tact. Together in the Spouse Palace, partners tend to be proper, dignified and soft outside yet firm within, valuing both responsibility and tact. The risk is sensitivity, excessive rules and tangling over issues, so the key is using principles for boundaries and keeping softness for daily life.',
 cnL:'廉相在夫妻的人，遇到的人往往讲规矩、顾体面，相处有分寸、也靠得住；只是规则和敏感一多，容易在小事上较真、纠缠，少了松弛。',
 enL:'People with Lian Zhen and Tian Xiang in the Spouse Palace meet someone who values rules and dignity, tactful and dependable; when rules and sensitivity grow, small things get contested and tangled and ease is lost.',
 cnA:'这个问题在问：廉相在夫妻是什么关系模式。要先理解夫妻看长期互动，再看两星的原则和分寸怎么化成安全感。',
 enA:'The question is the relationship pattern with Lian Zhen and Tian Xiang in the Spouse Palace. Understand it reads long-term interaction, then see how principles and tact become safety.',
 cnLog:['廉贞在夫妻，主伴侣有原则、有魅力、感受强，关系里重忠诚，也主敏感与边界。','天相在夫妻，主伴侣正派、懂分寸、能协调，讲规矩也讲体面。','两星同宫是「原则＋分寸」：关系稳、责任清，见禄存化禄与吉曜（如财荫夹印），伴侣可靠、有家底。','见煞忌则易敏感、纠缠、因规则或面子生压，日常的柔软和沟通要练。'],
 enLog:['Lian Zhen in the Spouse Palace gives a principled, charming partner with strong feeling who values loyalty, while carrying sensitivity and boundaries.','Tian Xiang there gives an upright, tactful partner who mediates and values both rules and dignity.','Together they mean principles plus tact: the bond is steady with clear responsibility, and with Lu Cun, Hua Lu and auspicious stars the partner is reliable with resources.','With malefics and Ji, sensitivity, tangling and pressure over rules or face follow, so daily softness and communication must be practiced.'],
 cnStep:['先确认夫妻宫是廉贞天相同宫，并看两星亮度','把关系里的原则和规矩对到「边界」上，而不是日常细节','遇分歧先讲感受、再谈事情，避免只论对错','给敏感留安全感（坦诚、守约、及时沟通）','约定不纠缠旧账、不拿规则压人，保留松弛','结合大限流年判断关系引动阶段，共同经营'],
 enStep:['First confirm Lian Zhen and Tian Xiang share the Spouse Palace and check their brightness','Direct principles and rules to boundaries rather than daily details','In disagreement, speak feeling first and then the issue rather than only right and wrong','Give sensitivity safety through candor, keeping word and timely communication','Agree not to tangle over old issues or use rules to pressure, keeping ease','With the decade and year, tend the bond as it is activated'],
 cnMis:['把廉相在夫妻只当成「伴侣正派可靠」，忽略敏感','规则感过强、事事论对错，把相处绷紧','遇事纠缠旧账，把原则变成压力'],
 enMis:['Taking Lian Zhen-Tian Xiang in the Spouse Palace only as an upright, reliable partner while ignoring sensitivity','Overusing rules and debating right and wrong until the bond tightens','Tangling over old issues and turning principles into pressure'],
 cnClose:'廉相在夫妻给的是一个讲责任、有分寸、外柔内刚的关系。把原则守在边界上、把柔软留给日常，关系既靠得住，也能处得轻松。',
 enClose:'Lian Zhen and Tian Xiang in the Spouse Palace give a responsible, tactful bond that is soft outside and firm within. Keeping principles at the boundary and softness in daily life makes the relationship both dependable and easy to live in.'}
];
