// 2026-10-07 调研驱动 第4组：主星 2（太阳/天同总论）+ 辅煞 2（红鸾天喜区别/魁钺夹命）+ 流年 2（流年身宫/大限身宫）+ FAQ 2（盘准不准/可以自己看盘吗）
module.exports=[
{cat:'zhuxing',slug:'ziwei-taiyang-xing-ruhe-kan',focus:'太阳星总论',focusEn:'the Sun star overview',
 cnT:'太阳星总论：主贵、主外放、主名声',enT:'The Sun Star Overview: Distinction, Outwardness and Reputation',
 cnD:'太阳星主贵、主外放、主名声与光明，庙旺利公开舞台、公职、业务与领导，落陷防劳碌、虚名与操心；太阳的亮度随宫位变化大，落宫决定这股外放劲怎么表现。',
 enD:'The Sun star governs distinction, outwardness, reputation and light. At brightness it favors public stages, public service, sales and leadership; fallen, guard toil, empty name and worry. Its brightness varies greatly by palace, which sets how the outward energy expresses.',
 cnL:'太阳像天上的太阳，庙旺是正午、落陷是黄昏；同是外放，正午照得远，黄昏只剩忙碌。',
 enL:'The Sun star is like the sun in the sky, temple is noon and fallen is dusk; both outward, noon shines far while dusk only toils.',
 cnA:'有人见太阳守命就当一定显贵，其实亮度和三方配合决定兑现；太阳给的是外放和名声的底色，不是现成的功名。',
 enA:'Some see the Sun guarding life and assume rank, but brightness and trine support decide; the Sun gives outward and reputation tone, not ready distinction.',
 cnLog:['太阳主贵、主外放、主名声、主博爱。','庙旺（寅卯辰巳午）利公开舞台、公职、业务、领导。','落陷（申酉戌亥子丑）防劳碌、虚名、操心男性长辈。','太阳配吉星吉化，名声兑现；配煞忌，防口舌、过刚、眼目心血健康。'],
 enLog:['The Sun governs distinction, outwardness, reputation and generosity.','Brightness (Yin Mao Chen Si Wu) favors public stages, public service, sales and leadership.','Fallen (Shen You Xu Hai Zi Chou) guards toil, empty name and worry over male elders.','With auspicious stars and transformations, reputation materializes; with malefics, guard disputes, rigidity and eye or heart health.'],
 cnStep:['先看太阳所在宫位与亮度','庙旺：判断外放舞台在哪','落陷：判断劳碌操心在哪','看三方四正吉星，看名声能否兑现','数煞忌，防口舌过刚','看四化引动，定太阳的能量怎么表现'],
 enStep:['First read the Sun palace and brightness','Bright: judge where the outward stage is','Fallen: judge where toil and worry are','Read trine auspicious stars for whether reputation materializes','Count malefics to guard disputes and rigidity','Read transformation activation for how the Sun energy expresses'],
 cnMis:['见太阳守命就当一定显贵、坐等','只看外放不看亮度和三方','落陷就全盘否定，忽略博爱心'],
 enMis:['Seeing the Sun guard life and assuming rank and waiting','Seeing only outwardness without brightness and trines','Negating fallen entirely, missing generosity'],
 cnClose:'太阳星总论看的是「外放和名声的底色怎么兑现」。亮度够、三方稳、防住过刚，太阳的光才照得远、照得久。',
 enClose:'The Sun overview asks how outward and reputation tone materializes. Enough brightness, steady trines and guarding rigidity, and the Sun light shines far and long.'},

{cat:'zhuxing',slug:'ziwei-tiantong-xing-ruhe-kan',focus:'天同星总论',focusEn:'the Tian Tong star overview',
 cnT:'天同星总论：主福、主温和、主享受',enT:'The Tian Tong Star Overview: Blessing, Gentleness and Enjoyment',
 cnD:'天同星主福、主温和、主享受与情绪，逢吉星享福、人缘好、利服务文教，逢煞忌防懒散、情绪化与因情耗财；天同给的是福气底色，兑现要看努力和约束。',
 enD:'Tian Tong governs blessing, gentleness, enjoyment and emotion. With auspicious stars it enjoys fortune and good relationships, favoring service and education; with malefics, guard laziness, moodiness and spending through emotion. It gives a blessing tone, materializing through effort and discipline.',
 cnL:'天同像个有福的孩子，天性温和会享受；但福要守得住，光享受不努力，福气会变成懒散。',
 enL:'Tian Tong is like a blessed child, gentle and enjoying by nature; but fortune must be kept, and only enjoying without effort turns blessing into laziness.',
 cnA:'有人见天同守命就当一生享福，其实福气也要经营；也有人把温和当软弱，低估天同的韧性。',
 enA:'Some see Tian Tong guard life and assume lifelong ease, but fortune also needs work; others read gentleness as weakness, underestimating resilience.',
 cnLog:['天同主福、主温和、主情绪享受。','逢化禄、禄存、吉星，享福、人缘好、贵人多。','利服务、文教、儿童、餐饮、娱乐等温和领域。','逢煞忌，防懒散、情绪化、因情耗财、拖延。'],
 enLog:['Tian Tong governs blessing, gentleness, emotion and enjoyment.','With Hua Lu, Lu Cun and auspicious stars, it enjoys fortune and good relationships with mentors.','It favors service, education, children, food and entertainment fields.','With malefics, guard laziness, moodiness, spending through emotion and procrastination.'],
 cnStep:['先看天同所在宫位与亮度','看吉星化禄，定福气怎么兑现','数煞忌，防懒散情绪化','看所在宫，定福气施展领域','给自己设约束和目标，防光享受','看大限引动，定享福还是努力的阶段'],
 enStep:['First read the Tian Tong palace and brightness','Read auspicious stars and Lu for how fortune materializes','Count malefics to guard laziness and moodiness','Read the palace for the fortune area','Set discipline and goals, guard only enjoying','Read decade activation for ease or effort stages'],
 cnMis:['见天同就当一生享福、不努力','把温和当软弱','不防懒散情绪化，福气被耗掉'],
 enMis:['Seeing Tian Tong and assuming lifelong ease without effort','Reading gentleness as weakness','Not guarding laziness and moodiness, fortune consumed'],
 cnClose:'天同星总论看的是「福气底色怎么守、怎么兑现」。有吉星、肯努力、设约束，温和的福才长久而不是变成懒散。',
 enClose:'The Tian Tong overview asks how the blessing tone is kept and materializes. With auspicious stars, effort and discipline, gentle fortune lasts rather than turning to laziness.'},

{cat:'fuzhu',slug:'ziwei-hongluan-tianxi-qubie',focus:'红鸾天喜区别',focusEn:'the difference between Hong Luan and Tian Xi',
 cnT:'红鸾天喜区别：一主婚恋、一主喜庆，二星永远相对',enT:'Hong Luan vs Tian Xi: Romance and Celebration Stars',
 cnD:'红鸾主婚恋、动婚、感情喜事，天喜主喜庆、添丁、人缘，二星在盘上永远相隔六位相对；逢红鸾天喜引动，多应婚恋生育，但仍要看本命夫妻子女宫配合。',
 enD:'Hong Luan governs romance, marriage movement and relationship joy; Tian Xi governs celebration, children and relationships. The two always sit six positions apart in opposition. When activated, they often correspond to marriage or birth, but still read natal Spouse and Children Palaces.',
 cnL:'红鸾像桃花开、催动感情，天喜像喜事临门、添丁进口；一个偏婚恋，一个偏喜庆。',
 enL:'Hong Luan is like blossoms opening, stirring feelings; Tian Xi is like joy arriving with a new child; one leans romance, one celebration.',
 cnA:'有人见红鸾就当一定结婚、见天喜就当一定生子，其实只是喜事信号，成不成还要看本命和现实。',
 enA:'Some see Hong Luan and assume marriage, Tian Xi and assume birth, but they are only joy signals; whether it happens depends on natal and reality.',
 cnLog:['红鸾主婚恋动婚，天喜主喜庆添丁。','二星永远相对（隔六位）。','流年大限逢之，多应感情或生育喜事。','须合本命夫妻、子女宫，单看桃花星不足为据。'],
 enLog:['Hong Luan governs romance and marriage movement, Tian Xi celebration and children.','The two always sit in opposition six apart.','When met in a year or decade, they often correspond to relationship or birth joy.','Combine natal Spouse and Children Palaces; romance stars alone are insufficient.'],
 cnStep:['先找红鸾天喜所在宫位','区分红鸾（婚恋）与天喜（喜庆）','看流年大限是否引动','合本命夫妻宫看婚恋','合本命子女宫看生育','把信号当参考，现实努力和缘分定兑现'],
 enStep:['First find Hong Luan and Tian Xi palaces','Distinguish Hong Luan (romance) from Tian Xi (celebration)','See whether the year or decade activates them','Combine natal Spouse Palace for romance','Combine natal Children Palace for birth','Take signals as reference; real effort and bonds decide'],
 cnMis:['见红鸾就当必结婚、见天喜就当必生子','二星不区分','只看桃花星不看本命夫妻子女'],
 enMis:['Assuming Hong Luan means marriage and Tian Xi means birth','Not distinguishing the two','Seeing only romance stars without natal Spouse and Children'],
 cnClose:'红鸾天喜区别看的是「婚恋信号和喜庆信号怎么对照」。分清二星、合本命宫位，喜事信号才读得准、不被夸大。',
 enClose:'Hong Luan vs Tian Xi read how romance and celebration signals compare. Distinguish them and combine natal palaces, and joy signals are read accurately, not exaggerated.'},

{cat:'fuzhu',slug:'ziwei-kuiyue-jia-ming-ruhe-kan',focus:'魁钺夹命',focusEn:'Kui Yue flanking the Life Palace',
 cnT:'魁钺夹命：天魁天钺在左右，贵人贴身',enT:'Kui Yue Flanking the Life Palace: Close Mentors',
 cnD:'天魁（阳贵人）、天钺（阴贵人）分守命宫左右夹宫，主贵人贴身、逢难得助；成格须无煞冲破，贵人帮的是有准备的人，自身实力仍是根本。',
 enD:'Tian Kui (yang mentor) and Tian Yue (yin mentor) guard the two flanking palaces around Life, bringing close mentors and help in need. The pattern needs no malefic break; mentors help the prepared, and one own ability remains the root.',
 cnL:'魁钺夹命像一左一右有贵人，遇难有人搭把手；但贵人引路，路还得自己走。',
 enL:'This pattern is like having mentors on either side, help when in need; but mentors show the way, you still walk it.',
 cnA:'有人见魁钺夹命就当处处有人帮、自己不努力，结果贵人也扶不起；贵人是助力，不是替代。',
 enA:'Some see Kui Yue flanking and assume help everywhere without effort, and even mentors cannot lift them; mentors are support, not replacement.',
 cnLog:['天魁阳贵、天钺阴贵，夹命主贴身贵人。','主逢难得助、逢凶有解、机会有人引荐。','须无煞忌冲破夹宫。','贵人助有准备、有实力的人，自身努力是根本。'],
 enLog:['Tian Kui yang mentor and Tian Yue yin mentor flanking Life bring close mentors.','They bring help in need, relief in trouble and introductions to opportunity.','The flanking palaces must have no malefic or Ji break.','Mentors help the prepared and able; one own effort is the root.'],
 cnStep:['先确认天魁天钺在命宫左右夹宫','看二星亮度与庙旺','数煞忌，看有没有冲破','看贵人星所附主星，定贵人类型','结合自身实力，判断贵人帮不帮得上','合大限流年，看贵人何时出现'],
 enStep:['First confirm Kui Yue flank the Life Palace','Read their brightness','Count malefics and Ji for breaks','Read the stars they attach to for mentor type','Combine your own ability to judge whether mentors can help','Layer decade and year for when mentors appear'],
 cnMis:['见魁钺夹命就当不努力也有人帮','不查煞忌冲破','把贵人当替代，忽略自身实力'],
 enMis:['Seeing Kui Yue flanking and assuming help without effort','Not checking malefic or Ji breaks','Taking mentors as replacement, ignoring own ability'],
 cnClose:'魁钺夹命看的是「贵人贴身、自己值不值得帮」。无煞破、有实力、肯努力，贵人的助力才真正落得上。',
 enClose:'This pattern asks whether close mentors find you worth helping. No malefic break, ability and effort, and mentor support truly lands.'},

{cat:'liunian',slug:'ziwei-liunian-shishen-ruhe-kan',focus:'流年身宫',focusEn:'the annual Body Palace',
 cnT:'流年身宫怎么看：该年后天重心在哪',enT:'How to Read the Annual Body Palace',
 cnD:'流年身宫定这一年后天用力的方向与重心，与流年命宫（该年基调）对读；流年身宫落哪个领域，这一年就往哪使劲，只主一年加减。',
 enD:'The annual Body Palace sets the later effort direction and focus of the year, read with the annual Life Palace (the year tone). Whichever area it lands in is where the year effort goes; it only adjusts one year.',
 cnL:'流年命宫写这一年的基调，流年身宫写这一年实际往哪使劲；两个对着读，才看得到一年的主线。',
 enL:'The annual Life Palace writes the year tone, the annual Body Palace where effort actually goes; reading both shows the year main line.',
 cnA:'有人只看流年命宫不看身宫，读不到实际用力处；也有人把流年身宫当长期方向，其实它只管一年。',
 enA:'Some see only annual Life without Body, missing actual effort; others take the annual Body as long direction, but it only governs one year.',
 cnLog:['流年身宫依附在流年盘六宫之一。','流年命宫定基调，身宫定后天重心。','身宫落官禄：这年重心在事业；落财帛：在钱。','只主一年，长期仍看本命身宫与大限。'],
 enLog:['The annual Body Palace attaches to one of six palaces on the annual chart.','Annual Life sets tone, Body sets later focus.','Body in Career: year focus on work; in Wealth: on money.','It governs one year; the long term still depends on natal Body and decade.'],
 cnStep:['先排流年盘，定流年命宫','找流年身宫依附在哪一宫','流年命身对读，定基调与重心','看身宫主星，定用力方式','看该宫四化，定能量怎么引动','合大限，判断这年重心在十年里的位置'],
 enStep:['First build the annual chart and set annual Life Palace','Find which palace the annual Body attaches to','Read annual Life and Body together for tone and focus','Read the Body star for effort style','Read that palace transformations for energy activation','Combine the decade to place the year focus in ten years'],
 cnMis:['只看流年命宫不看身宫','把流年身宫当长期方向','流年身宫不看主星四化'],
 enMis:['Seeing only annual Life without Body','Taking annual Body as long direction','Reading annual Body without star and transformations'],
 cnClose:'流年身宫看的是「这一年实际往哪使劲」。命身对读、只论一年，再合大限，你才读得准当年的主线。',
 enClose:'The annual Body reads where the year effort actually goes. Read Life and Body together for one year, then combine the decade, and the year main line is accurate.'},

{cat:'liunian',slug:'ziwei-daxian-shishen-ruhe-kan',focus:'大限身宫',focusEn:'the decade Body Palace',
 cnT:'大限身宫怎么看：这十年后天重心在哪',enT:'How to Read the Decade Body Palace',
 cnD:'大限身宫定这十年后天用力方向与重心，与大限命宫（十年基调）对读；大限身宫落哪个领域，这十年就往哪深耕，主管十年走向。',
 enD:'The decade Body Palace sets the later effort direction and focus of ten years, read with the decade Life Palace (ten-year tone). Whichever area it lands in is where the decade deepens; it governs the ten-year direction.',
 cnL:'大限命宫写十年基调，大限身宫写十年实际深耕处；对读才看得到这一阶段的主线。',
 enL:'Decade Life writes the ten-year tone, decade Body where effort actually deepens; reading both shows the stage main line.',
 cnA:'有人只看大限命宫不看身宫，读不到深耕方向；大限身宫往往比命宫更能说明这十年实际活成什么样。',
 enA:'Some see only decade Life without Body, missing the deepening direction; decade Body often explains better than Life how the ten years actually go.',
 cnLog:['大限身宫依附在大限盘六宫之一。','大限命宫定基调，身宫定后天深耕重心。','身宫落官禄：十年重心在事业；落田宅：在家庭资产。','合本命身宫，看后天方向是否一致。'],
 enLog:['The decade Body attaches to one of six palaces on the decade chart.','Decade Life sets tone, Body sets later deepening focus.','Body in Career: decade focus on work; in Property: on home and assets.','Combine natal Body to see whether later directions align.'],
 cnStep:['先排大限盘，定大限命宫','找大限身宫依附在哪宫','大限命身对读，定基调与深耕重心','看身宫主星，定用力方式','看大限四化引动身宫','合本命身宫，判断长期方向'],
 enStep:['First build the decade chart and set decade Life Palace','Find which palace the decade Body attaches to','Read decade Life and Body together for tone and focus','Read the Body star for effort style','Read decade transformations activating Body','Combine natal Body to judge long direction'],
 cnMis:['只看大限命宫不看身宫','大限身宫不合本命身宫看','不看四化引动'],
 enMis:['Seeing only decade Life without Body','Not reading decade Body with natal Body','Ignoring transformation activation'],
 cnClose:'大限身宫看的是「这十年实际往哪深耕」。命身对读、合本命方向，你才读得准这一阶段活成什么样。',
 enClose:'The decade Body reads where ten years actually deepen. Read Life and Body together and combine natal direction, and you accurately read how the stage is lived.'},

{cat:'faq',slug:'ziwei-pan-zhun-bu-zhun',focus:'盘准不准',focusEn:'whether a chart is accurate',
 cnT:'紫微斗数盘准不准：准的是倾向，不是百分百剧本',enT:'Is a Zi Wei Chart Accurate? Tendencies, Not a Script',
 cnD:'命盘准的是性格倾向与概率区间，不是每件事的精确剧本；准不准还看读盘水平、出生信息准不准、以及你怎么用，读得对、用得好，盘就「准」。',
 enD:'A chart is accurate about temperament tendencies and probability ranges, not a precise script of every event. Accuracy also depends on reading skill, correct birth information and how you use it; read right and used well, the chart feels accurate.',
 cnL:'盘像天气预报，说的是趋势和概率，不是保证几点几分下雨；拿着它要求百分百精确，是用错了工具。',
 enL:'A chart is like a weather forecast of trends and probabilities, not a guarantee of rain at a precise minute; demanding full accuracy is using the wrong tool.',
 cnA:'有人盘有几处没应验就说不准，其实盘给的是区间；也有人把盘当百分百剧本，失去主动权，两头都偏。',
 enA:'Some call it inaccurate when a few things do not happen, but the chart gives ranges; others take it as a full script and lose initiative; both extremes err.',
 cnLog:['盘准在先天性格、相处模式、时间节奏的倾向。','不准在精确事件、具体数字、个人结局。','影响准度：出生信息、排盘、读盘水平。','正确用法：参考倾向、自己决策、知命不宿命。'],
 enLog:['The chart is accurate on innate temperament, relating patterns and timing tendencies.','It is not accurate on precise events, exact numbers and personal endings.','Accuracy factors: birth information, chart building and reading skill.','Right use: reference tendencies, decide yourself, know fate without fatalism.'],
 cnStep:['先核验出生信息和排盘是否准确','用性格和相处模式验证倾向层','不要求盘精确预测每件事','把应验和未应验都当反馈','读不准时提升方法，不简单否定','用盘辅助决策，把主动权握在手里'],
 enStep:['First verify birth information and chart building','Validate the tendency layer with temperament and relating','Do not demand precise prediction of every event','Take both matches and misses as feedback','When unclear, improve method rather than denying','Use the chart to aid decisions, holding initiative'],
 cnMis:['要求盘百分百精确、用错工具','几处没应验就全盘否定','把盘当剧本、失去主动权'],
 enMis:['Demanding full accuracy, using the wrong tool','Negating all at a few misses','Taking the chart as script, losing initiative'],
 cnClose:'盘准不准看的是「你读的是倾向还是剧本」。它在倾向层准、在精确层不保证，用它参考而不是替你决定，盘就用对了。',
 enClose:'Whether a chart is accurate depends on reading tendencies or a script. It is accurate on tendencies and not guaranteed on precision; use it for reference rather than decisions, and it is used right.'},

{cat:'faq',slug:'ziwei-keyi-ziji-kan-ma',focus:'可以自己看盘吗',focusEn:'can you read your own chart',
 cnT:'可以自己看盘吗：学方法、照自己，重大决策仍问专业',enT:'Can You Read Your Own Chart? Learn Method, Seek Pros for Big Decisions',
 cnD:'完全可以自己看盘，学基础的宫星四化方法、拿盘反思自己的性格与选择；但自己看容易带主观，重大健康、法律、财务决策仍以专业人士和正规途径为准。',
 enD:'You can absolutely read your own chart by learning basic palaces, stars and transformations to reflect on your temperament and choices. But self-reading carries subjectivity; major health, legal and financial decisions still defer to professionals and proper channels.',
 cnL:'自己看盘像给自己做心理分析，好处是最了解自己，风险是容易只看想看的；保持诚实和批判就行。',
 enL:'Self-reading is like self-analysis: the benefit is knowing yourself best, the risk is seeing only what you want; stay honest and critical.',
 cnA:'有人觉得自己看不准、必须找人，其实入门方法不难；也有人全信自己的解读、排斥专业意见，两头都偏。',
 enA:'Some feel they cannot read and must find someone, but the basics are not hard; others trust only their reading and reject professional views; both extremes err.',
 cnLog:['入门路径：十二宫→十四主星→四化→三方四正→大限流年。','自己看的价值：反思性格、理解模式、把握时间节奏。','风险：主观、只看吉不看凶、对号入座。','边界：重大决策找专业，命理只做参考。'],
 enLog:['Beginner path: twelve palaces, fourteen stars, transformations, triple-direction, decade and year.','Self-reading value: reflect on temperament, understand patterns, grasp timing.','Risks: subjectivity, seeing only auspicious and forcing matches.','Boundary: seek professionals for major decisions, astrology is reference.'],
 cnStep:['先学排盘和十二宫基础','认十四主星和四化象义','拿自己盘逐宫练习','对照性格经历验证、保持批判','读大限流年看时间节奏','重大决策不依赖自读，找专业人士'],
 enStep:['First learn chart building and twelve palaces','Learn fourteen stars and transformation meanings','Practice on your own chart palace by palace','Verify against temperament and history, stay critical','Read decade and year for timing','Do not rely on self-reading for major decisions, seek professionals'],
 cnMis:['觉得自己一定看不准、不敢学','全信自读、排斥专业','只看吉不看凶、对号入座'],
 enMis:['Feeling unable to read and not daring to learn','Trusting only self-reading and rejecting professionals','Seeing only auspicious and forcing matches'],
 cnClose:'可以自己看盘。学方法、照自己、保持批判，盘是认识自己的好工具；但别让它替代专业判断，重大事走正规途径。',
 enClose:'You can read your own chart. Learn method, reflect and stay critical; it is a good self-knowledge tool. But do not let it replace professional judgment; take proper channels for major matters.'}
];
