// 2026-10-08 调研驱动 第1组：看盘方法 8（四化优先级/桃花应期/叠宫叠盘/六十星系/对星/一事一占/提验/综合总结）
module.exports=[
{cat:'kanpan',slug:'ziwei-sihua-youxianji-ruhe-kan',focus:'四化优先级',focusEn:'the priority order of the Four Transformations',
 cnT:'四化优先级：先找风险、再看机会、最后评助力',enT:'The Priority Order of the Four Transformations',
 cnD:'读盘时四化有优先级：化忌＞化禄＞化权＞化科，先找化忌定风险卡点、再看化禄定机会资源、最后用权科评掌控与名声；顺序对了，精力花在刀刃上。',
 enD:'When reading a chart the transformations have priority: Hua Ji first, then Lu, then Quan, then Ke. First find Ji for risk and sticking points, then Lu for opportunity and resources, finally Quan Ke for control and reputation. With the right order, effort goes where it matters.',
 cnL:'一上来先找化忌不是悲观，是先看清坑在哪；坑看清了，再看机会才稳。',
 enL:'Finding Ji first is not pessimism, it is seeing where the pits are; with pits seen, looking at opportunity is steady.',
 cnA:'有人见吉就先高兴、把化忌放最后，结果风险没防住；优先级是读盘的先后，不是吉凶的多少。',
 enA:'Some rejoice at auspicious first and leave Ji last, failing to guard risk; priority is reading order, not amounts of good or bad.',
 cnLog:['化忌优先级最高：先定风险、卡点、亏欠领域。','化禄次之：定机会、资源、机缘。','化权化科最后：评掌控力与名声。','三层读完，先防守再谈发展。'],
 enLog:['Hua Ji has highest priority: first set risk, sticking points and debt areas.','Hua Lu next: set opportunity, resources and chances.','Hua Quan and Ke last: assess control and reputation.','Read all three layers, guard first then develop.'],
 cnStep:['先全盘找化忌落宫','看化忌所附星曜，定卡点性质','看三方，定风险影响范围','再找化禄，定机会资源','最后看权科，评掌控名声','综合：先给防守建议、再给发展建议'],
 enStep:['First find Hua Ji across the chart','Read the star Ji attaches to for the sticking-point nature','Read trines for risk scope','Then find Lu for opportunity and resources','Finally read Quan Ke for control and reputation','Synthesize: guard advice first, then development'],
 cnMis:['见吉先喜、把化忌放最后','把优先级当吉凶多少','只看四化不看落星落宫'],
 enMis:['Rejoicing at auspicious first and leaving Ji last','Taking priority as amounts of good or bad','Reading transformations without host stars and palaces'],
 cnClose:'四化优先级看的是「先防坑、再抓机会」。化忌先读、化禄次之、权科收尾，读盘才稳、行动才准。',
 enClose:'Transformation priority asks to guard pits first and seize opportunity next. Read Ji first, Lu next, Quan Ke last, and reading is steady and action accurate.'},

{cat:'kanpan',slug:'ziwei-taohua-yingqi-ruhe-kan',focus:'桃花应期',focusEn:'the timing of romance',
 cnT:'桃花应期怎么看：不是只找桃花星，要看飞化引动',enT:'How to Read the Timing of Romance',
 cnD:'看桃花什么时候来，不能只看流年有没有红鸾天喜，要看子女宫（桃花宫）的飞化有没有引动桃花星或带桃花的主星，引动成组、力量足，情缘概率才高。',
 enD:'To see when romance arrives, do not only check whether the year has Hong Luan or Tian Xi; read whether the Children Palace (romance palace) flights activate romance stars or romance-bearing main stars. When activation forms groups with strong force, the chance of a bond is high.',
 cnL:'桃花星像种子，子女宫飞化像春风，光有种子没有风，花开不起来。',
 enL:'Romance stars are like seeds and Children Palace flights like spring wind; with seeds but no wind, blossoms do not open.',
 cnA:'有人见流年有红鸾就当一定恋爱，结果没应验；少看了「有没有被飞化引动」这一层。',
 enA:'Some see Hong Luan in the year and assume romance, but it does not happen; they missed whether flights activate it.',
 cnLog:['子女宫是桃花宫，看桃花先看它的飞化。','飞禄权科引动桃花星，情缘机会来。','引动「成组」（禄忌组、权科组）力量翻倍。','桃花星只在流年出现、没被引动，不一定应。'],
 enLog:['The Children Palace is the romance palace; read its flights first.','Flying Lu Quan Ke activating romance stars brings bond chances.','Activation forming groups (Lu-Ji, Quan-Ke) doubles force.','Romance stars only appearing in the year without activation do not necessarily respond.'],
 cnStep:['先看本命子女宫与桃花星分布','看流年大限子女宫飞化','找飞化有没有引动桃花星','判断引动成不成组、力量强不强','流年逢桃花星且被引动，情缘概率高','结合现实社交，不坐等缘分'],
 enStep:['First read natal Children Palace and romance stars','Read annual and decade Children Palace flights','See whether flights activate romance stars','Judge whether activation forms groups and strength','Romance stars in the year and activated, bond chance is high','Combine real social life, do not wait passively'],
 cnMis:['只看流年桃花星、不看飞化引动','见红鸾就当必恋爱','不看子女宫，桃花读不全'],
 enMis:['Seeing only annual romance stars without flight activation','Seeing Hong Luan and assuming certain romance','Not reading Children Palace, romance incomplete'],
 cnClose:'桃花应期看的是「桃花星有没有被春风吹动」。子女宫飞化引动、成组有力，再逢桃花星，情缘才容易应。',
 enClose:'Romance timing asks whether romance stars are stirred by spring wind. Children Palace flights activate in groups with force, and meeting romance stars, a bond easily responds.'},

{cat:'kanpan',slug:'ziwei-diegong-diepan-ruhe-kan',focus:'叠宫叠盘',focusEn:'stacked palaces and layered charts',
 cnT:'叠宫叠盘怎么看：本命大限流年叠得越多，主题越重',enT:'How to Read Stacked Palaces and Layered Charts',
 cnD:'本命、大限流年的同一宫位叠在一起看：某领域在三层都被引动，这阶段主题就集中在那；叠宫读的是力量的叠加，不是简单重复。',
 enD:'Read the same palace stacked across natal, decade and year: when an area is activated on all three layers, the stage theme concentrates there. Stacked palaces read the accumulation of force, not simple repetition.',
 cnL:'一件事在本命、大限、流年都指向同一宫，像三重信号都亮在一处，想不注意都难。',
 enL:'When a matter points to the same palace on natal, decade and year, like three signals lit in one place, hard to miss.',
 cnA:'有人分层看、不叠宫，结果看不出某阶段为什么事特别集中；叠盘才读得出主题的重量。',
 enA:'Some read in layers without stacking, and cannot see why a stage concentrates; stacking shows the theme weight.',
 cnLog:['本命定先天，大限定十年，流年定当年。','同一领域三层都引动，主题最集中。','叠宫要看各层四化是同向加强还是互相拉扯。','只一层引动，主题轻、时间短。'],
 enLog:['Natal sets innate, decade ten years, year the current year.','An area activated on all three layers has the most concentrated theme.','Stacked palaces need reading whether layer transformations reinforce or pull.','Only one layer activated means a light, short theme.'],
 cnStep:['先读本命定各领域底色','找当前大限引动哪些宫','再找流年引动哪些宫','三层叠看，找共同引动的领域','看叠宫四化同向还是拉扯','判断当前阶段主题集中在哪、有多重'],
 enStep:['First read natal for area tones','Find which palaces the current decade activates','Then find which the year activates','Stack all three, find jointly activated areas','Read stacked transformations for reinforcement or pull','Judge where the stage theme concentrates and how heavily'],
 cnMis:['分层看不叠宫，读不出主题重量','把叠宫当简单重复','不看各层四化的方向'],
 enMis:['Reading in layers without stacking, missing theme weight','Taking stacked palaces as simple repetition','Not reading layer transformation directions'],
 cnClose:'叠宫叠盘看的是「力量怎么一层层叠加」。三层同指一宫、四化同向，这阶段的主题就特别集中、特别重。',
 enClose:'Stacked palaces read how force accumulates layer by layer. Three layers pointing to one palace and transformations aligned, the stage theme is especially concentrated and heavy.'},

{cat:'kanpan',slug:'ziwei-liushi-huagong-ruhe-kan',focus:'六十星系',focusEn:'the sixty star systems',
 cnT:'六十星系怎么看：按花甲分系，判断星性变化的骨架',enT:'How to Read the Sixty Star Systems',
 cnD:'六十星系把星曜组合按六十花甲分系，同一颗主星在不同星系里表达方式会变；它是判断星性随宫位和同伴变化的骨架，读组合先认清属于哪一系。',
 enD:'The sixty star systems divide star combinations by the sixty Jia Zi; the same major star expresses differently across systems. It is the framework for judging how star nature changes with palace and companions; read combinations by first recognizing the system.',
 cnL:'六十星系像给星曜组合编了六十种「处境」，同颗星换个处境，表现就不同。',
 enL:'The sixty systems are like sixty settings for star combinations; the same star in another setting behaves differently.',
 cnA:'有人背了单星性质就套所有盘，结果不准；没看到星在六十星系里的变化。',
 enA:'Some memorize single-star nature and apply it to all charts, ending inaccurate; they miss the star changes within the sixty systems.',
 cnLog:['六十星系以花甲为纲，归类星曜组合。','同主星在不同星系，表达方式不同。','星系决定星性被同伴加强还是调和。','是中州派读组合的基础骨架。'],
 enLog:['The sixty systems use Jia Zi as the outline to classify combinations.','The same main star expresses differently across systems.','The system sets whether star nature is reinforced or tempered by companions.','It is the basic framework for reading combinations.'],
 cnStep:['先认命宫星曜组合属于哪个花甲星系','看该星系里主星的基本表达方式','看同宫和对宫星怎么影响它','对比同主星在别的星系的差别','看四化落在哪个星系','以星系为骨架定该领域基调'],
 enStep:['First recognize which Jia Zi system the Life Palace combination belongs to','Read how the main star expresses in that system','See how conjunct and opposite stars affect it','Compare the same main star in other systems','See which system transformations land in','Use the system as framework for the area tone'],
 cnMis:['单星性质套所有盘、不看星系','六十星系当死分类、不看变化','只看命宫星系、不看三方'],
 enMis:['Applying single-star nature to all charts without systems','Taking sixty systems as rigid classes without change','Reading only Life system without trines'],
 cnClose:'六十星系看的是「星性怎么随处境变」。认清星系、对比差别，你才不会把同颗星在不同盘里读成一个样。',
 enClose:'The sixty systems ask how star nature changes with setting. Recognize systems and compare differences, and you do not read the same star alike across charts.'},

{cat:'kanpan',slug:'ziwei-duixing-ruhe-kan',focus:'对星',focusEn:'paired stars',
 cnT:'对星怎么看：有些星要一对对读，单看一颗读不全',enT:'How to Read Paired Stars',
 cnD:'斗数里有些星成对出现、互相定义：府相、昌曲、魁钺、左右、羊陀、火铃、空劫；逢府看相、逢昌看曲，拆成单颗就丢了一半含义。',
 enD:'Some stars appear in pairs and define each other: Fu-Xiang, Chang-Qu, Kui-Yue, Zuo-You, Yang-Tuo, Huo-Ling, Kong-Jie. See Fu with Xiang and Chang with Qu; splitting them loses half the meaning.',
 cnL:'对星像一对搭档，一个管这头、一个管那头，合起来才完整。',
 enL:'Paired stars are like partners, one governing this end and one that end; together complete.',
 cnA:'有人只看一颗吉星就下结论，忽略它的对星；结果力量估错、短板也没看到。',
 enA:'Some conclude from one auspicious star and ignore its pair; force is misjudged and weaknesses missed.',
 cnLog:['府相：天府财库配天相印星，逢府看相。','昌曲：文昌理性配文曲感性。','魁钺左右：贵人助力成对。','羊陀火铃空劫：煞星也成对，一明一暗。'],
 enLog:['Fu-Xiang: Tian Fu treasury with Tian Xiang seal; see them together.','Chang-Qu: Wen Chang reason with Wen Qu feeling.','Kui-Yue and Zuo-You: mentor support in pairs.','Yang-Tuo, Huo-Ling, Kong-Jie: malefics also pair, one open one hidden.'],
 cnStep:['先认盘里哪些是对星','成对读，不拆单颗','看一对星分别落在哪宫','看它俩是夹、是会还是对照','合四化，看对星怎么被引动','以对星为单位估力量'],
 enStep:['First recognize which stars are paired','Read in pairs, not split','See which palaces each of the pair lands in','See whether they flank, meet or oppose','Combine transformations for how the pair activates','Estimate force by the pair as a unit'],
 cnMis:['拆对星、单看一颗','只看吉星的对、不看煞星的对','把对星当两颗无关星'],
 enMis:['Splitting pairs and reading one star','Seeing only auspicious pairs, not malefic pairs','Taking paired stars as unrelated'],
 cnClose:'对星看的是「两颗星怎么互相成全」。成对读、看落宫、合四化，你才读得全这股力量。',
 enClose:'Paired stars ask how two stars complete each other. Read in pairs, see positions and combine transformations, and you read the full force.'},

{cat:'kanpan',slug:'ziwei-yishi-yizhan-ruhe-kan',focus:'一事一占',focusEn:'one matter one reading',
 cnT:'一事一占：专门追一件事，不泛泛看全盘',enT:'One Matter, One Reading: Focused Divination',
 cnD:'一事一占是锁定一件具体事（求职、求财、官司、姻缘），为它立太极、飞四化、看落点，给出这一件事的倾向；不把整张盘每个领域都断一遍。',
 enD:'One matter one reading locks onto one concrete thing (job, money, lawsuit, romance), sets Tai Ji for it, flies transformations and reads landings to give that one matter tendency; it does not judge every area of the chart.',
 cnL:'泛泛看全盘容易什么都说、什么都不深；一事一占把所有镜头对准一件事。',
 enL:'Reading the whole chart vaguely says everything shallowly; one matter one reading aims all lenses at one thing.',
 cnA:'有人问事却把盘从头断到尾，答案反而模糊；聚焦一事、追它的因果，结论才清楚。',
 enA:'Some ask one thing but get the whole chart read, blurring the answer; focus on one matter and trace its cause-effect for a clear conclusion.',
 cnLog:['先锁定要问的那一件事。','为这件事选起点宫、立太极。','只追相关的四化落点。','给这一件事的倾向和节奏，不扩散。'],
 enLog:['First lock onto the one matter asked.','Choose the starting palace and set Tai Ji for it.','Only trace relevant transformation landings.','Give that one matter tendency and timing, not spreading.'],
 cnStep:['把问题收窄成一件具体事','定这件事主要落在哪个宫','以该宫立太极','飞该宫四化、追落点','用禄追机会、用忌追卡点','只回答这一件事的走向'],
 enStep:['Narrow the question to one concrete matter','Set which palace the matter mainly lands in','Set Tai Ji with that palace','Fly its transformations and trace landings','Use Lu for opportunity, Ji for sticking points','Answer only that one matter direction'],
 cnMis:['问一事却断全盘、答案模糊','不立太极、追错方向','把一事一占当定论、忽略现实努力'],
 enMis:['Asking one thing but reading the whole, answer blurred','Not setting Tai Ji, tracing wrong direction','Taking one reading as verdict, ignoring effort'],
 cnClose:'一事一占看的是「聚焦一件事、追它的因果」。立对太极、只追相关落点，这一件事的答案才清楚、才有用。',
 enClose:'One matter one reading asks to focus and trace one thing cause-effect. Set the right Tai Ji and trace only relevant landings, and the answer is clear and useful.'},

{cat:'kanpan',slug:'ziwei-kanpan-ruhe-tiyan',focus:'看盘提验',focusEn:'verifying chart readings',
 cnT:'看盘怎么提验：把推断写下来，事后对照应验',enT:'How to Verify Your Chart Readings',
 cnD:'提验是提升读盘的实办法：事前把推断（哪个阶段、哪件事、什么倾向）写下来，事后逐条对照，应验的记对、没应验的找原因，水平才长得快。',
 enD:'Verification is the practical way to improve: write down predictions beforehand (which stage, what matter, what tendency), then compare afterward; record matches and find reasons for misses, and skill grows fast.',
 cnL:'光读盘不提验，对错永远一笔糊涂账；写下来、回头看，才知道自己哪读得准。',
 enL:'Reading without verification leaves right and wrong muddled; write and review to know what you read accurately.',
 cnA:'有人怕记错丢面子、不肯写，结果水平停在原地；提验是给自己看的，不是给别人评分。',
 enA:'Some fear wrong notes and face loss, not writing, staying at the same level; verification is for yourself, not others grading.',
 cnLog:['事前写清推断：时间、领域、倾向。','事后逐条对照应验与否。','应验：记下读对的信号。','没应验：找是信号看错、还是层次没分清。'],
 enLog:['Beforehand write clear predictions: time, area, tendency.','Afterward compare one by one.','Matches: note the signals read right.','Misses: find whether signals were misread or layers confused.'],
 cnStep:['养成推断先落字的习惯','写清时间和领域，不写模糊话','到点回头逐条对照','应验的总结规律','没应验的复盘哪一步错','长期积累，形成自己的读盘手感'],
 enStep:['Form the habit of writing predictions first','Write clear time and area, not vague terms','At the point, return and compare','Summarize patterns in matches','Review which step failed in misses','Accumulate over time into your own reading feel'],
 cnMis:['只读盘不提验、对错糊涂','怕丢面子不写推断','没应验不找原因、水平不涨'],
 enMis:['Reading without verification, right-wrong muddled','Fearing face loss and not writing','Not finding reasons for misses, skill stagnant'],
 cnClose:'看盘提验看的是「读盘水平怎么实打实提升」。写下来、回头对照、复盘对错，你才知道自己准在哪、差在哪。',
 enClose:'Chart verification asks how reading skill genuinely improves. Write, return to compare and review right-wrong, and you know where you are accurate and where you fall short.'},

{cat:'kanpan',slug:'ziwei-xingpan-zonghe-zongjie',focus:'星盘综合总结',focusEn:'synthesizing the whole chart',
 cnT:'星盘综合总结：宫星化限四层读完，给不矛盾的结论',enT:'How to Synthesize the Whole Chart',
 cnD:'综合总结是把宫位、星曜、四化、大限四层读完，整合成一个前后不矛盾的整体结论：主轴是什么、当前阶段在哪、风险机会各在哪，不东一句西一句。',
 enD:'Synthesis reads palaces, stars, transformations and decade, integrating them into one consistent conclusion: what the main axis is, where the current stage sits, where risks and opportunities are, not scattered statements.',
 cnL:'单宫读得再细，不合起来总结，信息就是散的；总结是把四条线收成一句话。',
 enL:'However detailed single palaces are, without synthesis information is scattered; summary pulls four lines into one statement.',
 cnA:'有人读了一堆细节却给不出整体判断，因为没做综合；好的总结让读者一下抓住主线。',
 enA:'Some read many details but cannot give an overall judgment, lacking synthesis; a good summary lets the reader grasp the main line at once.',
 cnLog:['宫：十二宫定各领域。','星：主星组合定表达方式。','化：四化定能量开关。','限：大限流年定当前阶段，四层合一。'],
 enLog:['Palaces: twelve set each area.','Stars: combinations set expression.','Transformations: set energy switches.','Limits: decade and year set the current stage; four layers as one.'],
 cnStep:['先按固定顺序读完四层','列出主轴和主色调','定当前大限阶段主题','汇总风险（忌）与机会（禄）','检查各层结论是否矛盾','整合成一段不矛盾的总结'],
 enStep:['First read all four layers in fixed order','List the main axis and tone','Set the current decade stage theme','Summarize risk (Ji) and opportunity (Lu)','Check whether layer conclusions contradict','Integrate into one consistent summary'],
 cnMis:['只堆细节、不给整体结论','各层结论矛盾也不核对','总结写成万能好话、没主线'],
 enMis:['Piling details without an overall conclusion','Layer conclusions contradicting without checking','Summary written as vague praise with no main line'],
 cnClose:'星盘综合总结看的是「四层怎么收成一个不矛盾的判断」。主轴、阶段、风险机会都点到，整张盘才读得完整、说得清楚。',
 enClose:'Chart synthesis asks how four layers become one consistent judgment. Main axis, stage, risk and opportunity all noted, and the whole chart is complete and clear.'}
];
