// 2026-10-08 调研驱动 第5组：应用 8（考研进修/移民留学/合伙结义/理财保险/健康关口/体检安排/领导相处/店铺生意）
module.exports=[
{cat:'yingyong',slug:'ziwei-kaoyan-jixiu-ruhe-kan',focus:'考研进修',focusEn:'graduate school and further study',
 cnT:'考研进修怎么看：官禄文昌化科看节奏，努力是主体',enT:'How to Read Graduate School and Further Study',
 cnD:'考研进修看官禄宫、文昌文曲与大限有没有化科引动，利深造的阶段节奏更顺；但盘只给节奏和状态，复习、方法、坚持才是主体，节奏顺要抓紧、不顺要更努力。',
 enD:'Graduate study reads the Career Palace, Wen Chang Wen Qu and whether the decade has Ke activation; stages favoring further study run smoother. But the chart only gives timing and state; review, method and persistence are the substance; seize smooth timing, work harder when not.',
 cnL:'深造的节奏到了，像考试这条路灯亮了；但灯亮不替你背书，功夫还得下。',
 enL:'When further-study timing arrives, the exam path light is on; but the light does not study for you, effort still required.',
 cnA:'有人见化科引动就当一定考上、不复习；也有人阶段不利就放弃；正确是看节奏、更看努力。',
 enA:'Some see Ke activation and assume admission without review; others give up in an unfavorable stage; the right way reads timing and effort.',
 cnLog:['官禄昌星看深造底子。','大限化科引动、利进修。','主学习状态顺。','努力方法是主体。'],
 enLog:['Career and literary stars read further-study foundation.','Decade Ke activation favors study.','It brings smooth learning state.','Effort and method are the substance.'],
 cnStep:['先看官禄昌星底子','看大限化科引动','定报考方向','节奏顺抓紧复习','不顺更重方法坚持','看流年定考试当年'],
 enStep:['First read Career and literary star foundation','Read decade Ke activation','Set the application direction','Smooth timing, seize and review','Not smooth, emphasize method and persistence','Read the year for the exam year'],
 cnMis:['见化科当必上、不努力','阶段不利就放弃','只看节奏、不看功夫'],
 enMis:['Seeing Ke and assuming admission without effort','Giving up in an unfavorable stage','Seeing only timing, not effort'],
 cnClose:'考研进修看的是「深造节奏和努力的配合」。化科给状态、坚持给结果，两者都有，进修这条路才走得通。',
 enClose:'Graduate study asks for the match of further-study timing and effort. Ke gives state, persistence gives results; with both, the study path works.'},

{cat:'yingyong',slug:'ziwei-yimin-liuxue-ruhe-kan',focus:'移民留学',focusEn:'immigration and studying abroad',
 cnT:'移民留学怎么看：迁移宫驿马化禄看远方缘分',enT:'How to Read Immigration and Studying Abroad',
 cnD:'移民留学看迁移宫、天马与化禄，看远方、外出的缘分和节奏；但手续、签证、资质必须走正规途径、以官方要求和书面材料为准，盘只提示远方主题，不替结果担保。',
 enD:'Immigration and study abroad read the Travel Palace, Tian Ma and Lu for distant-land bonds and timing. But procedures, visas and qualifications must take proper channels, following official requirements and written materials; the chart only hints at the distant theme, not guaranteeing results.',
 cnL:'迁移逢禄马，远方的门像开了；但门开了，手续一样不能少、一样要正规。',
 enL:'Travel with Lu Ma, the distant door seems open; but with it open, procedures are still required and must be proper.',
 cnA:'有人见迁移吉就当一定能出去、忽略手续；也有人完全不信远方缘分；正确是看节奏、走正规途径。',
 enA:'Some see Travel auspicious and assume departure, ignoring procedures; others disbelieve distant bonds; the right way reads timing and takes proper channels.',
 cnLog:['迁移宫看远方外缘。','天马化禄引动、利远行。','手续签证走正规途径。','以官方书面要求为准。'],
 enLog:['The Travel Palace reads distant outside bonds.','Tian Ma and Lu activation favor distant travel.','Procedures and visas take proper channels.','Follow official written requirements.'],
 cnStep:['先看迁移宫与禄马','看远方缘分节奏','现实了解签证移民政策','找正规机构、核验资质','材料以书面官方为准','不把盘当结果保证'],
 enStep:['First read the Travel Palace, Lu and Ma','Read distant bond timing','In reality understand visa and immigration policy','Find proper agencies and verify qualifications','Materials follow official writing','Do not take the chart as result guarantee'],
 cnMis:['见迁移吉当必出去、忽略手续','找非正规机构','把盘当保证'],
 enMis:['Seeing Travel auspicious and assuming departure, ignoring procedures','Finding non-formal agencies','Taking the chart as guarantee'],
 cnClose:'移民留学看的是「远方缘分和正规手续」。迁移给节奏、官方途径给保障，两者都有，远方这条路才走得稳。',
 enClose:'Immigration and study abroad read distant bonds and proper procedures. Travel gives timing, official channels give security; with both, the distant path is steady.'},

{cat:'yingyong',slug:'ziwei-hehuo-jieyi-ruhe-kan',focus:'合伙结义',focusEn:'partnership and sworn alliance',
 cnT:'合伙结义怎么看：交友宫看伙伴，权责写清再谈情',enT:'How to Read Partnership and Sworn Alliance',
 cnD:'合伙结义看交友宫与官禄，看伙伴类型和分工；越是好朋友越要先把权责、分成、退出写进书面合同，再谈情分，以专业律师和正规途径为准，不凭口头义气。',
 enD:'Partnership and sworn alliance read the Friends and Career Palaces for partner types and division. The closer the friends, the more authority, shares and exit terms must be written into a contract before feelings; rely on professional lawyers and proper channels, not verbal loyalty.',
 cnL:'结义讲情、合伙讲理，情归情、合同归合同，顺序不能反。',
 enL:'Sworn alliance speaks feelings, partnership speaks reason; feelings and contracts each in place, order not reversed.',
 cnA:'有人凭义气口头合伙、结果纠纷无据；也有人因怕不合不敢合作；真正靠的是分工清、合同明。',
 enA:'Some partner verbally on loyalty, ending in disputes without evidence; others fear discord and dare not cooperate; what works is clear division and contracts.',
 cnLog:['交友宫看伙伴缘分。','官禄看合作的事。','权责分成退出写书面。','以律师合同为准。'],
 enLog:['The Friends Palace reads partner bonds.','Career reads the cooperation matter.','Authority, shares and exit in writing.','Rely on lawyers and contracts.'],
 cnStep:['先看交友宫伙伴类型','合官禄看事靠不靠谱','现实尽调','权责分成退出逐条谈','签约前律师审核','不凭口头义气'],
 enStep:['First read Friends Palace partner types','Combine Career to see whether the matter is sound','Do due diligence in reality','Negotiate authority, shares and exit one by one','Lawyer review before signing','Not on verbal loyalty'],
 cnMis:['凭义气口头合伙','不写合同、纠纷无据','把情分当规则'],
 enMis:['Partnering verbally on loyalty','No contract, disputes without evidence','Taking feelings as rules'],
 cnClose:'合伙结义看的是「情分和规则各归其位」。先分工、写合同、再谈情，合作才走得远。以专业律师和正规途径、书面合同为准。',
 enClose:'Partnership reads feelings and rules each in place. Divide first, write contracts, then feelings, and cooperation goes far. Rely on professional lawyers, proper channels and written contracts.'},

{cat:'yingyong',slug:'ziwei-licai-baoxian-ruhe-kan',focus:'理财保险',focusEn:'financial planning and insurance',
 cnT:'理财保险怎么看：财帛田宅看节奏，产品合同持牌为准',enT:'How to Read Financial Planning and Insurance',
 cnD:'理财保险看财帛、田宅与大限节奏，看哪个阶段适合稳健配置或保障安排；但产品选择必须以持牌机构、正式合同和产品说明为准，不构成投资建议，不迷信「理财型保险高收益」。',
 enD:'Financial planning and insurance read Wealth, Property and decade timing for which stage suits conservative allocation or protection. But product choice must follow licensed institutions, formal contracts and product terms; this is not investment advice, and do not superstition high-return insurance products.',
 cnL:'理财看节奏、产品看合同，盘提示方向，真正的安全感来自正规保障和稳健配置。',
 enL:'Finance reads timing, products read contracts; the chart hints direction, real security comes from proper protection and conservative allocation.',
 cnA:'有人见财帛吉就追高收益、忽略风险；也有人把保险当理财、收益没保障；正确是持牌、合同、稳健。',
 enA:'Some see Wealth auspicious and chase high returns, ignoring risk; others take insurance as investment with unguaranteed returns; the right way is licensed, contracted and conservative.',
 cnLog:['财帛田宅看财务节奏。','持牌机构、正式合同为准。','保险重保障、理财重稳健。','不构成投资建议。'],
 enLog:['Wealth and Property read financial timing.','Licensed institutions and formal contracts govern.','Insurance emphasizes protection, finance conservatism.','Not investment advice.'],
 cnStep:['先看财帛田宅节奏','评估保障缺口','只找持牌机构','产品合同逐条看','理财以稳健、留应急钱','决策以产品说明为准'],
 enStep:['First read Wealth and Property timing','Assess protection gaps','Only seek licensed institutions','Read product contracts one by one','Finance conservatively, keep emergency funds','Decide by product terms'],
 cnMis:['追高收益、忽略风险','保险当理财、收益无保障','找非持牌机构'],
 enMis:['Chasing high returns, ignoring risk','Taking insurance as investment with unguaranteed returns','Finding non-licensed institutions'],
 cnClose:'理财保险看的是「财务节奏和正规保障」。持牌、合同、稳健三件套，安全感才踏实。命理倾向不构成投资建议，以持牌机构和正规产品说明为准。',
 enClose:'Financial planning and insurance read financial timing and proper protection. Licensed, contracted and conservative, and security is steady. This cultural-tendency reference is not investment advice; defer to licensed institutions and official product terms.'},

{cat:'yingyong',slug:'ziwei-jiankang-guankou-ruhe-kan',focus:'健康关口',focusEn:'health thresholds',
 cnT:'健康关口怎么看：疾厄宫看时间倾向，非诊断',enT:'How to Read Health Thresholds: Timing Tendencies, Not Diagnosis',
 cnD:'健康关口看疾厄宫与大限流年四化，看哪些阶段身体多操心、需要多留意；它给的是时间和方向倾向，不是诊断，关口前后更要规律作息、及时就医，以正规医院为准。',
 enD:'Health thresholds read the Health Palace and decade-year transformations for which stages need more body attention. It gives timing and direction tendencies, not diagnosis; around thresholds keep regular routines and seek timely care, deferring to proper hospitals.',
 cnL:'关口不是一定出事，是「这阶段要多留心身体」；越留心、越规律，越容易平稳过去。',
 enL:'A threshold does not mean certain trouble, it is to mind the body more this stage; the more attention and regularity, the smoother.',
 cnA:'有人见关口就恐慌、自己吓自己；也有人完全不留意；正确是看倾向、做预防、遵医嘱。',
 enA:'Some panic at thresholds and frighten themselves; others pay no attention; the right way reads tendencies, prevents and follows doctors.',
 cnLog:['疾厄宫看健康倾向。','大限流年定关口节奏。','给方向、不给诊断。','预防就医以正规医院为准。'],
 enLog:['The Health Palace reads health tendencies.','Decade and year set threshold timing.','It gives direction, not diagnosis.','Prevention and care defer to proper hospitals.'],
 cnStep:['先看疾厄宫主星','看大限流年关口','把倾向翻译成留意方向','规律作息、定期体检','不适及时就医','不恐慌、也不大意'],
 enStep:['First read the Health Palace star','Read decade-year thresholds','Translate tendencies into watch directions','Keep regular routines and check periodically','Seek timely care for discomfort','Neither panic nor careless'],
 cnMis:['见关口恐慌、自己吓自己','不留心、不预防','拿倾向当诊断'],
 enMis:['Panicking at thresholds and frightening yourself','Not minding or preventing','Taking tendencies as diagnosis'],
 cnClose:'健康关口看的是「哪些阶段多留心身体」。它给倾向不给诊断，预防和及时就医才是根本。倾向非诊断，以正规就医为准。',
 enClose:'Health thresholds ask which stages need more body attention. It gives tendencies not diagnosis; prevention and timely care are fundamental. Tendency is not diagnosis; defer to proper medical care.'},

{cat:'yingyong',slug:'ziwei-tijian-ruhe-anpai',focus:'体检安排',focusEn:'scheduling health check-ups',
 cnT:'体检怎么安排：结合健康节奏定期查，不因命理拖延',enT:'How to Arrange Health Check-Ups',
 cnD:'体检安排可结合疾厄宫的健康节奏，在容易有倾向的阶段更要定期、针对性检查；但任何体检都要到正规医疗机构、遵医嘱，盘只提示节奏，绝不能因「命理说没事」就拖延检查。',
 enD:'Check-up scheduling can combine Health Palace timing, with more regular and targeted checks in tendency-prone stages. But all check-ups must be at proper medical institutions and follow doctors; the chart only hints timing, never delaying checks because astrology says fine.',
 cnL:'体检是给身体做定期盘点，节奏到了就去、别拖；查的是安心、也是早发现。',
 enL:'Check-ups are regular body inventories; go when timing arrives, do not delay; they bring peace and early detection.',
 cnA:'有人觉得没不舒服就不体检；也有人听命理说没事就拖；正确是定期、正规、遵医嘱。',
 enA:'Some skip check-ups without symptoms; others delay because astrology says fine; the right way is regular, proper and doctor-led.',
 cnLog:['结合疾厄健康节奏。','定期、针对性检查。','到正规医疗机构。','不因命理拖延。'],
 enLog:['Combine Health Palace timing.','Check regularly and with focus.','Go to proper medical institutions.','Do not delay for astrology.'],
 cnStep:['先看健康节奏','定体检频率和项目','到正规医院或机构','有家族倾向的针对性查','拿到报告遵医嘱复查','不拖延、不迷信'],
 enStep:['First read health timing','Set check-up frequency and items','Go to proper hospitals or institutions','Target checks for family tendencies','Follow reports and doctor review','Do not delay or superstition'],
 cnMis:['没症状不体检','听命理拖延检查','去非正规机构'],
 enMis:['Skipping checks without symptoms','Delaying checks for astrology','Going to non-formal institutions'],
 cnClose:'体检安排看的是「定期正规、早发现」。结合节奏、到正规机构、遵医嘱，别让拖延把小问题拖成大问题。倾向非诊断，以正规就医为准。',
 enClose:'Check-up scheduling asks for regular, proper and early detection. Combine timing, go to proper institutions and follow doctors; do not let delay turn small into big. Tendency is not diagnosis; defer to proper medical care.'},

{cat:'yingyong',slug:'ziwei-lingdao-xiangchu-ruhe-kan',focus:'领导相处',focusEn:'getting along with leaders',
 cnT:'领导相处怎么看：官禄父母宫看上下级，守专业懂边界',enT:'How to Read Getting Along with Leaders',
 cnD:'与领导相处看官禄宫与父母宫（长辈上级），看上下级缘分和沟通方式；长期靠的是专业能力、靠谱和边界感，不靠一味讨好，也不必把上下级处成对立。',
 enD:'Getting along with leaders reads the Career and Parents Palaces (elders and superiors) for superior bonds and communication. The long term relies on professional ability, reliability and boundaries, not flattery, and superior relations need not become opposition.',
 cnL:'和领导相处，专业是底气、边界是分寸；讨好换不来长久信任，靠谱才换得来。',
 enL:'With leaders, professionalism is backing and boundaries are measure; flattery does not bring lasting trust, reliability does.',
 cnA:'有人见官禄吉就当领导一定赏识、自己不努力；也有人怕领导、处处躲；正确是靠实力、懂分寸。',
 enA:'Some see Career auspicious and assume favor without effort; others fear leaders and hide; the right way relies on ability and measure.',
 cnLog:['官禄宫看事业上下级。','父母宫看长辈贵人。','专业靠谱是根本。','边界感、不讨好。'],
 enLog:['The Career Palace reads work superior relations.','The Parents Palace reads elders and mentors.','Professional reliability is the root.','Boundaries, not flattery.'],
 cnStep:['先看官禄父母宫','看上下级沟通方式','把专业做扎实','沟通对事不对人','守边界、不越位','不讨好、也不对立'],
 enStep:['First read Career and Parents Palaces','Read superior communication style','Do solid professional work','Communicate on issues not personalities','Guard boundaries, do not overstep','Neither flatter nor oppose'],
 cnMis:['靠讨好换信任','见吉当必赏识、不努力','怕领导、处处躲'],
 enMis:['Relying on flattery for trust','Seeing auspicious and assuming favor without effort','Fearing leaders and hiding'],
 cnClose:'领导相处看的是「专业底气和边界分寸」。实力和靠谱换信任，不讨好、不对立，上下级才处得长久。',
 enClose:'Getting along with leaders reads professional backing and boundary measure. Ability and reliability bring trust, neither flatter nor oppose, and superior relations last.'},

{cat:'yingyong',slug:'ziwei-dianpu-shengyi-ruhe-kan',focus:'店铺生意',focusEn:'shop and store business',
 cnT:'店铺生意怎么看：财帛官禄田宅看经营，资质合同正规',enT:'How to Read Shop and Store Business',
 cnD:'开店做生意看财帛（进账）、官禄（经营）、田宅（店面）三宫配合与节奏；但选址、执照、合同、资质必须走正规途径，盘只提示经营节奏，不构成投资建议，不保证稳赚。',
 enD:'Shop business reads Wealth (income), Career (operation) and Property (premises) together with timing. But location, licenses, contracts and qualifications must take proper channels; the chart only hints at business timing, not investment advice or guaranteed profit.',
 cnL:'三宫稳、节奏到，开店的窗口像开了；但执照合同资质一样不能少，风险要提前算。',
 enL:'Three palaces steady and timing arriving, the shop window seems open; but licenses, contracts and qualifications are required, risks counted in advance.',
 cnA:'有人见财帛吉就冲动开店、不查资质市场；也有人完全不信节奏；正确是看节奏、走正规、算风险。',
 enA:'Some see Wealth auspicious and open impulsively without checking market and qualifications; others disbelieve timing; the right way reads timing, goes proper and counts risks.',
 cnLog:['财帛官禄田宅看经营。','执照资质走正规途径。','租赁合同书面为准。','不构成投资建议。'],
 enLog:['Wealth, Career and Property read operation.','Licenses and qualifications take proper channels.','Lease and contracts in writing.','Not investment advice.'],
 cnStep:['先看三宫经营节奏','现实做市场选址','办执照、核验资质','租赁合同书面审','算清成本现金流','不把盘当稳赚保证'],
 enStep:['First read three-palace business timing','Do market and location work in reality','Get licenses and verify qualifications','Review lease and contracts in writing','Calculate costs and cash flow clearly','Do not take the chart as guaranteed profit'],
 cnMis:['见吉冲动开店、不查资质','不做市场、不算风险','把盘当稳赚'],
 enMis:['Seeing auspicious and opening impulsively without qualifications','No market work or risk counting','Taking the chart as guaranteed profit'],
 cnClose:'店铺生意看的是「经营节奏和正规资质」。三宫给方向、合同执照给保障、风险提前算，开店才稳。命理倾向不构成投资建议，以持牌机构和正规合同为准。',
 enClose:'Shop business reads business timing and proper qualifications. Three palaces give direction, contracts and licenses give security, risks counted in advance, and opening is steady. This cultural-tendency reference is not investment advice; defer to licensed institutions and proper contracts.'}
];
