// 2026-10-04 调研驱动 第1组：流年串宫压运神煞 8篇（太岁/青龙/小耗/朱雀/五鬼/死符/力士/奏书）
module.exports=[
{cat:'liunian',slug:'ziwei-liunian-taisui-ruhe-kan',focus:'流年太岁值年',focusEn:'the year when Tai Sui presides',
 cnT:'流年太岁值年怎么看：一年主权在自己手里，也最怕硬碰',enT:'When Tai Sui Presides Over Your Year: Authority in Hand, but Clashes Cost Most',
 cnD:'太岁值年主这一年主动性强、机遇与变动都多，但太岁喜稳忌冲，逢刑冲硬碰容易把好事变成僵局，宜稳中求进。',
 enD:'A Tai Sui year brings initiative, opportunities and changes, but it favors steadiness and punishes head-on clashes; pushing too hard can turn an opening into a deadlock, so advance steadily.',
 cnL:'太岁不是一颗凶星，更像这一年的「当家人」，当值时你说话比平时有分量，可一旦逞强硬碰，反弹也最大。',
 enL:'Tai Sui is not a malefic so much as the year presiding over you; your voice carries more weight, but when you force a confrontation, the pushback is strongest too.',
 cnA:'有人一逢本命年或太岁相关年份就紧张，其实真正要问的不是「会不会倒霉」，而是这一年主动权变大后，自己会不会用得太猛。',
 enA:'People approach a Tai Sui year with fear, but the real question is not whether misfortune strikes; it is whether, given more initiative this year, you end up using it too aggressively.',
 cnLog:['太岁值年主「主权」与「变动」，这一年事情多由自己推动，也更容易被推到台前。','太岁喜安居、忌刑冲，逢冲的那一年大事容易反复，越硬碰越僵。','太岁是放大器：本身好的结构被放大，本身虚的地方也会被放大，不凭空制造吉凶。','流年太岁只主一年节奏，长期走向仍由本命与大限决定，不能据此另断一条命。'],
 enLog:['Tai Sui presides over authority and change; this year events tend to move because of you, and you are more likely to be pushed to the front.','It favors a settled position and dislikes clashes; in a year that clashes with it, big matters repeat themselves, and force only hardens them.','Tai Sui is an amplifier: strong structures grow stronger and weak spots are exposed, but it creates no fortune or misfortune on its own.','An annual Tai Sui sets only one year rhythm; the long-term course still belongs to the natal chart and decade limit, not a second fate.'],
 cnStep:['先定位流年太岁落在本命哪个宫位，定这一年的主场在哪','再看该宫三方四正，分清被放大的是强项还是短板','查流年有没有与太岁相冲的结构，逢冲则大事缓办','该年主动可以，但重要决定留缓冲、不把话说满','遇到僵持先退一步，借时间和第三方转圜，忌正面硬顶','年底复盘时把「主动推动」和「逞强硬碰」分开，校准下一年'],
 enStep:['Locate which natal palace the annual Tai Sui sits in to define the year main stage','Read that palace triple-direction to see whether strengths or weak spots are amplified','Check whether anything clashes with Tai Sui this year; if so, slow major decisions down','Take initiative, but leave margin in important decisions and avoid absolute statements','When stalled, step back and use time or a third party rather than forcing a head-on win','At year-end, separate healthy initiative from stubborn force and recalibrate'],
 cnMis:['把太岁年直接等同灾年，处处自我设限','以为主动权大就可以硬推，忽略太岁逢冲的反弹','只看流年太岁一层，不回到本命和大限就下长期结论'],
 enMis:['Treating a Tai Sui year as a disaster year and limiting yourself everywhere','Assuming more authority means you can force things, ignoring the rebound when it clashes','Reading only the annual Tai Sui and drawing long-term conclusions without the natal chart and decade'],
 cnClose:'太岁值年的功课，是学会「有力而不逞强」。把主动权用在推动真正重要的事上，逢冲时肯退一步，这一年反而走得稳。',
 enClose:'A Tai Sui year teaches power without force. Direct your initiative toward what truly matters and be willing to yield at a clash, and the year steadies itself.'},

{cat:'liunian',slug:'ziwei-liunian-qinglong-ruhe-kan',focus:'流年青龙',focusEn:'the year when Qing Long appears',
 cnT:'流年青龙怎么看：财喜、贵人与顺遂，但不是躺着就来',enT:'When Qing Long Appears: Wealth, Joy and Helpers, Not a Free Pass',
 cnD:'青龙主财喜、贵人与事业顺遂，这一年机会比平时顺，但吉象要靠行动接住，若逢煞忌或自己不动，好处也会打折。',
 enD:'Qing Long brings financial joy, helpful people and smoother progress, but the auspicious signs must be met with action; if malefics, obstructions or passivity enter, the benefit is discounted.',
 cnL:'青龙是流年里的喜神，它开门的那一年路比较顺，可门开了还得自己走进去。',
 enL:'Qing Long is the year joy-bringer; when it opens a door the road is smoother, but you still have to walk through it.',
 cnA:'看到青龙就以为今年一定发财、什么都不用做，结果年底没兑现，问题不在星不准，而在把「机会」当成了「结果」。',
 enA:'Seeing Qing Long, people expect guaranteed wealth and do nothing, then nothing arrives by year-end; the issue is not an inaccurate star but mistaking an opening for an outcome.',
 cnLog:['青龙属喜神，主财、喜、贵人与事情的开端顺利，常见于机会先到、阻力偏小的年份。','吉象是「条件变好」而非「自动成交」，仍要自己表态、争取和落实。','青龙逢煞忌同宫或对冲，喜力会被打折，表现为机会来了但中途生变。','青龙只描述这一年的顺遂面，长期财运仍以本命财帛与大限为主。'],
 enLog:['Qing Long is a joy star governing money, happy events, helpers and smooth beginnings, often showing a year when opportunities arrive early and resistance is low.','The auspicious sign means conditions improve, not that things close themselves; you still have to speak up, pursue and deliver.','When Qing Long meets malefics or obstruction in the same or opposite palace, its joy is discounted and opportunities arrive but change midway.','It describes only this year smooth side; long-term wealth still rests on the natal Wealth Palace and decade.'],
 cnStep:['先定位青龙落在哪个宫位，定这一年哪类事比较顺','看该宫三方有无煞忌，判断顺遂会不会中途打折','把机会具体列出来，别停在「感觉今年不错」','对每个机会定一个动作和时间点，主动去接','逢青龙利开端，重要的事尽量在这一年启动','同时守住基本面，不因顺遂就放松风险和预算'],
 enStep:['Locate which palace Qing Long falls in to see which affairs run smoothly this year','Check that palace triple-direction for malefics that could discount the smoothness','List concrete opportunities rather than settling for a vague good feeling','Set one action and a date for each opportunity and actively take it','Qing Long favors beginnings, so launch important matters this year','Keep the fundamentals intact and do not relax risk or budget just because things flow'],
 cnMis:['把青龙当结果，等好运自己兑现','只看青龙不看同宫煞忌，高估顺利程度','顺了一年就误判长期，忽略本命与大限的主线'],
 enMis:['Treating Qing Long as an outcome and waiting for luck to deliver itself','Reading Qing Long without its accompanying malefics and overestimating smoothness','Taking one smooth year as a long-term verdict while ignoring the natal and decade main line'],
 cnClose:'青龙给的是顺风，不是终点。顺风的一年里主动起手、把该开的局开起来，这颗喜星才算真正被用到。',
 enClose:'Qing Long gives a tailwind, not a destination. Start things while the wind favors you and open what should be opened, and the joy star is genuinely put to work.'},

{cat:'liunian',slug:'ziwei-liunian-xiaohao-ruhe-kan',focus:'流年小耗',focusEn:'the year when Xiao Hao appears',
 cnT:'流年小耗怎么看：琐碎漏财不伤根本，管的是习惯',enT:'When Xiao Hao Appears: Small Leaks That Do Not Break You, But Test Your Habits',
 cnD:'小耗主小额、琐碎的开销与计划小阻，不伤根本，却容易积少成多；这一年重点是做预算、堵小缝、留缓冲。',
 enD:'Xiao Hao governs small, scattered expenses and minor plan delays that never break the foundation but can add up; the year focus is budgeting, plugging small leaks and keeping a buffer.',
 cnL:'小耗不是大破财，更像口袋里的小洞，单看不大，一年下来却悄悄漏掉不少。',
 enL:'Xiao Hao is not a major loss; it is more like a small hole in a pocket, trivial at first but quietly draining over a year.',
 cnA:'有人觉得反正都是小钱不必在意，结果年底对不上账才发现漏在无数小处，问题正是把「小」当成了「无所谓」。',
 enA:'People dismiss small sums as not worth minding, then cannot reconcile the year accounts and find the loss spread across countless little places; the error is treating small as irrelevant.',
 cnLog:['小耗属小凶，主漏财、丢物、小维修与计划的小停顿，应事多为琐碎而非重大。','它不伤根本，但会反复出现，考验的是日常的预算和收纳习惯。','小耗逢吉星会照，损耗容易被补回；逢煞聚则小漏变多。','小耗只主一年的小损耗，不改变本命的财富格局。'],
 enLog:['Xiao Hao is a minor inauspicious sign governing leaks, lost items, small repairs and short plan pauses; its events are scattered rather than major.','It does not break the foundation, but it recurs and tests everyday budgeting and organization habits.','When it meets auspicious stars, the drain is easily recovered; when malefics gather, small leaks multiply.','It governs only one year of minor drains and does not change the natal wealth pattern.'],
 cnStep:['先定位小耗落在哪个宫位，定哪类事容易出小损耗','该年专门记账，把零碎开销显性化','设一个小额缓冲，专门应对维修、丢物、计划小阻','大额支出前多问一次是否必要，减少冲动小消费','定期复盘漏得最多的一类，改一个具体习惯','年底把小耗当体检，看哪些缝要长期堵'],
 enStep:['Locate which palace Xiao Hao falls in to see which affairs tend to leak small amounts','Track expenses deliberately this year so scattered spending becomes visible','Keep a small buffer reserved for repairs, lost items and minor plan delays','Before larger purchases, ask once more whether they are needed to cut impulse spending','Review the leakiest category regularly and change one concrete habit','Treat Xiao Hao at year-end as a checkup on which holes need long-term plugging'],
 cnMis:['把小钱当无所谓，放任小漏累积','把小耗看成大破财，过度紧张、处处抠门','只看流年小耗，不回到本命财富结构就下结论'],
 enMis:['Dismissing small money and letting leaks accumulate','Treating Xiao Hao as a major loss and becoming anxious and miserly','Reading only the annual Xiao Hao without returning to the natal wealth structure'],
 cnClose:'小耗的功课是「把小缝当回事」。一年里把预算和缓冲立起来、改掉一个漏财习惯，小耗反而帮你把财务管得更细。',
 enClose:'Xiao Hao teaches taking small holes seriously. Set up a budget and buffer and change one leaky habit, and the year helps you manage money more carefully.'},

{cat:'liunian',slug:'ziwei-liunian-zhuque-ruhe-kan',focus:'流年朱雀',focusEn:'the year when Zhu Que appears',
 cnT:'流年朱雀怎么看：口舌是非多，把话写清楚就少一半',enT:'When Zhu Que Appears: Disputes and Rumor; Clear Words Remove Half the Trouble',
 cnD:'朱雀主口舌、是非、文书争执与表达失当，这一年误会比平时多；凡事先说清、留书面、走正规途径，能避开大半风波。',
 enD:'Zhu Que governs disputes, rumor, paperwork arguments and careless speech, bringing more misunderstandings than usual; clarify first, keep written records and use proper channels to avoid most trouble.',
 cnL:'朱雀管的是「话」，这一年很多麻烦不是事本身坏，而是话说岔了、意思被曲解了。',
 enL:'Zhu Que governs words; this year much of the trouble is not a bad matter but a misspoken line or a twisted meaning.',
 cnA:'有人遇到背后议论就急着对骂，结果小事闹大，问题不在有没有是非，而在被朱雀带着情绪走、没把表达和证据管住。',
 enA:'When talked about, some rush to argue back and inflate a small matter; the issue is not whether gossip exists but being led by emotion and failing to manage speech and evidence.',
 cnLog:['朱雀属火、主口舌文书，应事多为争吵、误会、流言与合同条款上的分歧。','它考验表达：同一件事说清楚、留记录，风波就小；随口、含糊则易被曲解。','朱雀逢吉星化科，利靠正规文书和公开说明化解；逢煞聚则是非缠身。','重要约定这一年更要白纸黑字，以专业律师和正规途径、书面合同为准。'],
 enLog:['Zhu Que is fiery and governs speech and documents, showing arguments, misunderstandings, rumor and disagreements over contract terms.','It tests expression: a matter explained clearly and recorded stays small; careless or vague words are easily twisted.','When it meets auspicious stars and Hua Ke, proper documents and open statements resolve things; when malefics gather, disputes linger.','Important agreements this year especially need to be in writing, relying on a qualified lawyer, proper channels and a written contract.'],
 cnStep:['先定位朱雀落在哪个宫位，定哪类关系或事务易起口舌','该年重要沟通尽量书面化，少靠口头和情绪表达','遇到误会先澄清事实，不急着反驳或对骂','合同、票据、聊天记录留存好，把证据做扎实','涉及法律与合同的事走正规途径，不以私下斗气解决','练一次「把话说短、说准」，降低被曲解的空间'],
 enStep:['Locate which palace Zhu Que falls in to see which relationships or affairs draw disputes','Put important communication in writing this year and rely less on spoken or emotional words','Clarify facts first when misunderstood rather than arguing back','Keep contracts, receipts and messages organized so evidence is solid','Handle legal and contract matters through proper channels, not private feuds','Practice saying things briefly and precisely to reduce room for twisting'],
 cnMis:['被议论就情绪化对骂，把小事闹大','只凭口头约定，不留书面、不留证据','把朱雀年所有不顺都归因小人，不反省表达方式'],
 enMis:['Answering gossip with emotion and inflating small matters','Relying on spoken agreements with nothing written and no evidence','Blaming every setback on bad actors without examining how things were said'],
 cnClose:'朱雀年的功课是「让话经得起复述」。把表达管短、把书面留全、把纠纷交给正规途径，是非就很难真正缠住你。',
 enClose:'A Zhu Que year teaches making words bear repeating. Keep speech short, keep records complete and hand disputes to proper channels, and rumor struggles to take hold.'},

{cat:'liunian',slug:'ziwei-liunian-wugui-ruhe-kan',focus:'流年五鬼',focusEn:'the year when Wu Gui appears',
 cnT:'流年五鬼怎么看：暗耗与临门生变，靠核对和余地化解',enT:'When Wu Gui Appears: Hidden Drain and Last-Minute Changes, Resolved by Checking and Margin',
 cnD:'五鬼主暗耗、阻滞、计划临门生变与小人暗扰，这一年意外多在看不见处；多核对、留备份、给计划留余地，能把暗耗降到最低。',
 enD:'Wu Gui governs hidden drain, blockages, last-minute changes and quiet interference, with surprises coming from unseen places; double-check, keep backups and leave margin to minimize the hidden cost.',
 cnL:'五鬼不是什么阴灵，更像事情里那些没被看见的漏洞，平时不响，临到关键才冒出来。',
 enL:'Wu Gui is not a haunting; it is more like the unseen flaws in a plan, silent until a key moment when they surface.',
 cnA:'有人这一年总遇到临门一脚出意外，就怪运气邪门，其实问题在前期没核对、没备份、没留余地，把暗耗全攒到了最后。',
 enA:'Some face last-minute surprises all year and blame strange luck, when the real issue is no early checks, no backups and no margin, so hidden costs pile up to the end.',
 cnLog:['五鬼主暗耗与阻滞，应事多为计划临时生变、资料出错、合作方变卦与说不清的小阻碍。','它的特点是「看不见」，靠流程化解：核对、备份、留痕比事后补救省力。','五鬼逢吉星，暗耗有人提醒、容易补回；逢煞聚则小人暗扰变多。','五鬼只主一年的临时阻滞，不决定本命的长期成败。'],
 enLog:['Wu Gui governs hidden drain and blockage, showing last-minute changes, data errors, partners backing out and hard-to-name obstacles.','Its trait is invisibility, so process is the answer: checking, backups and records cost less than fixing things afterward.','When it meets auspicious stars, someone flags the hidden cost and it is recovered; when malefics gather, quiet interference grows.','It governs only one year of temporary blockage and does not decide long-term natal success or failure.'],
 cnStep:['先定位五鬼落在哪个宫位，定哪类事易出暗耗','重要计划提前做二次核对，尤其资料、金额、时间','关键文件和数据留备份，重要约定留书面痕迹','给每个计划预留缓冲时间和备用方案，不排到极限','合作前把分工和退出讲清楚，防临门生变','遇到阻滞先查流程漏洞，不归咎玄乎、不情绪化'],
 enStep:['Locate which palace Wu Gui falls in to see which affairs draw hidden costs','Double-check important plans in advance, especially data, amounts and timing','Back up key files and data, and keep important agreements in writing','Reserve buffer time and a fallback for each plan rather than scheduling to the limit','Clarify roles and exit terms before cooperating to prevent last-minute change','When blocked, look for process flaws rather than blaming the mysterious or reacting emotionally'],
 cnMis:['把五鬼想成阴灵作祟，往玄乎里解释','不留备份、不做核对，把暗耗全攒到关键时候','一年阻滞就误判长期，不回到本命与大限'],
 enMis:['Imagining Wu Gui as a haunting and explaining things mystically','Skipping backups and checks so hidden costs gather at the key moment','Taking one blocked year as a long-term verdict without the natal chart and decade'],
 cnClose:'五鬼年的功课是「把看不见的地方照亮」。用核对、备份和余地替代侥幸，暗耗再小也攒不成大麻烦。',
 enClose:'A Wu Gui year teaches lighting up unseen places. Replace hope with checks, backups and margin, and small hidden drains never grow into real trouble.'},

{cat:'liunian',slug:'ziwei-liunian-sifu-ruhe-kan',focus:'流年死符',focusEn:'the year when Si Fu appears',
 cnT:'流年死符怎么看：小灾与停顿，宜缓行排查而非硬闯',enT:'When Si Fu Appears: Minor Mishaps and Pauses; Slow Down and Inspect Rather Than Push Through',
 cnD:'死符主小灾、停顿与旧事收尾，这一年不宜硬闯冒进；把隐患排查在前、身体小信号当回事、大事留余地，多数风波能避开。',
 enD:'Si Fu governs minor mishaps, pauses and the closing of old matters; this is not a year to force ahead. Inspect for risks early, take small health signs seriously and leave margin to avoid most trouble.',
 cnL:'死符不是大凶，更像路口的黄灯，提醒这一年慢一点、查清楚再走。',
 enL:'Si Fu is not a major inauspicious sign; it is more like an amber light, telling you to slow down and check before moving.',
 cnA:'有人这一年图快硬闯，结果小伤、小故障、旧问题全冒出来，问题不在星凶，而在该停该查的时候没有停。',
 enA:'Some push through quickly this year and then face small injuries, breakdowns and returning old problems; the issue is not a fierce star but failing to pause and inspect when prompted.',
 cnLog:['死符常与小耗同体系，主小灾、停顿、旧物故障与旧事的收尾，应事偏「卡住」而非重大。','它提醒缓行：身体的小信号、设备的小故障、合同的旧条款，都要排查在前。','身体不适是倾向而非诊断，务必以正规就医为准，不靠命理拖延检查。','死符只主一年的停顿与小灾，不改变本命长期走向。'],
 enLog:['Si Fu belongs to the same system as Xiao Hao, governing minor mishaps, pauses, equipment faults and the closing of old matters; its events stall rather than devastate.','It advises slowing: small health signs, equipment faults and old contract terms should all be inspected early.','Health discomfort is a tendency, not a diagnosis; always rely on formal medical care rather than delaying checkups.','It governs only one year of pauses and minor mishaps and does not change the long-term natal course.'],
 cnStep:['先定位死符落在哪个宫位，定哪类事易停顿或出小灾','该年大事不抢跑，重要节点前留检查时间','身体小信号及时正规就医，不硬扛、不拖延','设备、车辆、合同条款做一次排查，把旧隐患清掉','旧事旧账主动收尾，不带进新阶段','硬闯前先问一句：是真急，还是图快'],
 enStep:['Locate which palace Si Fu falls in to see which affairs tend to pause or hit small mishaps','Do not rush major matters this year; leave inspection time before key points','Seek formal medical care promptly for small signs rather than enduring or delaying','Inspect equipment, vehicles and contract terms once to clear old risks','Close old matters and debts deliberately instead of carrying them into a new stage','Before forcing through, ask whether it is truly urgent or merely haste'],
 cnMis:['把黄灯当绿灯，图快硬闯','身体小信号不当回事，拖延正规检查','把死符看成大凶，整年自我恐吓、什么都不敢做'],
 enMis:['Treating an amber light as green and forcing through in haste','Dismissing small health signs and delaying formal checkups','Taking Si Fu as a major threat and living the year in fear, daring nothing'],
 cnClose:'死符年的功课是「肯停一下」。把排查做在前面、把小信号当回事，慢的这一年反而走得最稳。',
 enClose:'A Si Fu year teaches the willingness to pause. Inspect early and take small signs seriously, and the slower year ends up the steadiest.'},

{cat:'liunian',slug:'ziwei-liunian-lishi-ruhe-kan',focus:'流年力士',focusEn:'the year when Li Shi appears',
 cnT:'流年力士怎么看：执行力与辅佐，把主张稳稳落地',enT:'When Li Shi Appears: Execution and Support That Carry Your Plans Through',
 cnD:'力士随太岁而起，主执行力、辅佐与把主张落地，这一年动手能力强；关键是把力气用在已定的方向上，防用力过猛、事必躬亲。',
 enD:'Li Shi rises with Tai Sui, governing execution, support and carrying plans through; your ability to get things done is strong this year. Direct that energy at a settled direction and guard against overexertion and doing everything yourself.',
 cnL:'力士像太岁身边的执行者，这一年不缺力气，缺的往往是把力气使对地方、使对节奏。',
 enL:'Li Shi is like the executor beside Tai Sui; this year there is no shortage of strength, only the question of where and at what pace to use it.',
 cnA:'有人这一年特别能拼，却四处用力、事必躬亲，结果累垮还不讨好，问题不在不够努力，而在没把执行力对准主线。',
 enA:'Some work exceptionally hard this year but spread effort everywhere and do every task themselves, ending exhausted and unappreciated; the issue is not low effort but execution not aimed at the main line.',
 cnLog:['力士主执行与辅佐，应象为动手能力强、推进快、有人从旁落实具体事务。','它随太岁而起，方向要先定：方向对，力士是落地的保障；方向乱，越用力越偏。','力士要防「用力过猛」，包括事必躬亲、节奏太满和听不进分工。','力士只主一年的执行力，长期格局仍看本命与大限。'],
 enLog:['Li Shi governs execution and support, showing strong hands-on ability, fast progress and someone who carries out concrete tasks beside you.','It rises with Tai Sui, so the direction must be set first; with a clear direction it guarantees follow-through, while a scattered one means effort pulls you off course.','Guard against overexertion, including doing everything yourself, an overfull pace and refusing to share work.','It governs only one year of execution; the long-term pattern still rests on the natal chart and decade.'],
 cnStep:['先定位力士落在哪个宫位，定哪类事这一年最能落地','动手前先确认方向和目标，避免四处用力','把任务拆出先后，力气优先用在主线的关键环节','能分工的事分出去，不事事亲为','给节奏留白，防一上来就拉满、后劲不足','每完成一段复盘力气有没有使偏，及时校准'],
 enStep:['Locate which palace Li Shi falls in to see which affairs can be completed this year','Confirm direction and goals before acting to avoid spreading effort','Sequence tasks and put energy first into the key steps on the main line','Delegate what can be shared rather than doing everything yourself','Leave room in the pace to avoid starting at full tilt and losing momentum','After each stage, review whether effort drifted and recalibrate'],
 cnMis:['以为能拼就四处开工，力气分散','事必躬亲、节奏拉满，把自己和身边人都拖累','把一年执行力强误判成长期格局，不看本命大限'],
 enMis:['Starting everywhere just because you can work hard and scattering energy','Doing everything at a full pace and exhausting yourself and those around you','Taking one strong execution year as a long-term pattern without the natal chart and decade'],
 cnClose:'力士年的功课是「把力气变成结果」。先定方向、再分主次、肯分工，这一年的执行力才真正落到你要的事上。',
 enClose:'A Li Shi year teaches turning strength into results. Set the direction, rank priorities and be willing to delegate, and the year execution truly lands where you want it.'},

{cat:'liunian',slug:'ziwei-liunian-zoushu-ruhe-kan',focus:'流年奏书',focusEn:'the year when Zou Shu appears',
 cnT:'流年奏书怎么看：文书呈报与功名，利递交申请与发表',enT:'When Zou Shu Appears: Documents, Petitions and Academic Credit; Favoring Applications and Publication',
 cnD:'奏书主文书、呈报、功名与申请，这一年利递交、申报、考试与公开发表；关键是材料规范、节点抓准，把该交的东西按时交到位。',
 enD:'Zou Shu governs documents, petitions, academic credit and applications, favoring submissions, filings, exams and public expression; the key is well-prepared materials and accurate deadlines so what must be filed is filed on time.',
 cnL:'奏书是流年里的文书星，它当值的一年，「写下来、交上去」的事比平时容易成。',
 enL:'Zou Shu is the year document star; when it presides, matters that are written down and submitted tend to go through more easily.',
 cnA:'有人这一年材料一交就过，有人却总卡在格式、节点和表达上，差别不在运气，而在有没有把文书当回事、按规范做。',
 enA:'Some see their filings approved at once while others get stuck on format, deadlines and expression; the difference is not luck but whether documents were taken seriously and done to standard.',
 cnLog:['奏书主文书呈报，应象为申请、申报、考试、提案与公开发表一类「递交」的事。','它利功名但不自动给结果，材料规范、逻辑清楚、节点准时才接得住。','奏书逢文昌文曲、化科会照，文书更顺；逢煞忌则易因格式、疏漏被退回。','奏书只主一年的文书运，长期学业事业仍以本命官禄与大限为主。'],
 enLog:['Zou Shu governs documents and petitions, showing applications, filings, exams, proposals and published work, the kinds of things that are submitted.','It favors credit but grants nothing automatically; well-prepared materials, clear logic and punctual deadlines are what catch the opening.','When it meets Wen Chang, Wen Qu or Hua Ke, documents flow; when it meets malefics or obstruction, flaws in format cause rejection.','It governs only one year of document luck; long-term study and career still rest on the natal Career Palace and decade.'],
 cnStep:['先定位奏书落在哪个宫位，定哪类文书这一年最顺','把今年要递交、申报、发表的事项和截止节点列清楚','材料按规范准备，逻辑、格式、署名一次做到位','重要提交预留修改和复核时间，不压到最后','考试与提案提前演练表达，把内容讲清楚','被退回时按意见补正，不情绪化、不放弃节点'],
 enStep:['Locate which palace Zou Shu falls in to see which documents go smoothly this year','List the submissions, filings and publications due this year with their deadlines','Prepare materials to standard with clear logic, format and attribution done once','Reserve revision and review time for important submissions rather than finishing last','Rehearse exams and proposals so the content is expressed clearly','If returned, correct it according to feedback without emotion and keep the deadline'],
 cnMis:['以为文书星当值就会自动通过，材料草率','不记截止节点，把提交压到最后、来不及修改','一次被退回就放弃，不按意见补正'],
 enMis:['Assuming a document star means automatic approval and preparing careless materials','Ignoring deadlines and leaving submissions to the last with no time to revise','Giving up after one rejection instead of correcting per feedback'],
 cnClose:'奏书年的功课是「把该交的东西交漂亮」。规范、准时、留复核，这一年的文书和功名自然接得住。',
 enClose:'A Zou Shu year teaches filing what must be filed with care. Be standard, punctual and reviewed, and the year documents and credit are naturally caught.'}
];
