// 2026-10-06 调研驱动 第2组：四化双吉同宫 4（禄权/禄科/权科/自化科）+ 看盘方法 4（破格点/大限重布/追禄忌/象义对应人事）
module.exports=[
{cat:'sihua',slug:'ziwei-luquan-tonggong-ruhe-kan',focus:'禄权同宫',focusEn:'Hua Lu and Hua Quan in the same palace',
 cnT:'禄权同宫：有资源也有话语权，怎么把强势用成成事',enT:'When Hua Lu and Hua Quan Share a Palace: Resources and Authority Together',
 cnD:'化禄主资源机缘，化权主掌控执行，同宫等于既拿得到本钱又说了算，利经营、带队与自主；短板是强势功利、对人不留情面，容易招嫉。',
 enD:'Hua Lu brings resources and opportunity while Hua Quan brings control and execution. Together they mean you both secure the backing and call the shots, which favors business, leadership and autonomy; the risk is being forceful and transactional and provoking envy.',
 cnL:'禄权同宫是一副「自己有本钱、自己能拍板」的牌，使得好是成事的格局，使不好是处处强势、把人推远。',
 enL:'This pairing is a hand of having your own capital and making your own calls; played well it delivers results, played poorly it dominates everywhere and pushes people away.',
 cnA:'有人见禄权同宫就当躺赢，却没看到这股劲若全用在争利上，容易因合同、分成与人结怨。',
 enA:'Some see this pairing as an automatic win without noticing that when the energy goes entirely into chasing gain, it breeds disputes over contracts and shares.',
 cnLog:['禄主财源、机缘与人缘，权主掌控、魄力与执行，同宫形成「资源+执行力」的闭环。','落在哪个宫，就主你在哪个领域既拿得到资源、又说得上话。','逢擎羊、火星同宫，容易因争利起口舌、合同矛盾，需刻意留沟通余地。','它放大的是「我说了算」，对人过于功利、不留情面时，反而暗中招小人。'],
 enLog:['Lu governs income, opportunity and ties, while Quan governs control, drive and execution; together they close a loop of resources plus execution.','Whichever palace they occupy is the area where you both secure resources and hold a voice.','With Qing Yang or Huo Xing, disputes over gain and contracts arise, so deliberately leave room to communicate.','It amplifies I decide; when you become transactional and unsparing toward people, it quietly draws bad actors.'],
 cnStep:['先定位禄权同宫所在宫位，定这股劲主要用在哪个领域','看同宫主星，分清资源和魄力分别以什么方式表现','看三方四正有没有持续的支撑，防只旺一时','数清煞星，重点防因争利、分成、合同起的摩擦','看飞化，确认拿到的资源是入库还是过路','刻意在沟通上留余地、肯分功，不把强势对准人'],
 enStep:['Locate the palace with Lu and Quan to see which area the energy mainly serves','Read its major star to see how resources and drive each express','Check the triple-direction for ongoing support so it does not peak only briefly','Count malefics, especially guarding friction over gain, shares and contracts','Read the flying transformations to see whether resources enter storage or pass through','Deliberately leave room in communication and share credit rather than aiming force at people'],
 cnMis:['见禄权同宫就当躺赢，不经营、不积累','只看好处，忽略过刚功利会招怨、招嫉','只看本宫，不看资源能不能持续、能不能留住'],
 enMis:['Treating the pairing as an automatic win without building or accumulating','Seeing only the benefit and ignoring that rigidity and transactional thinking breed resentment','Reading only the home palace without checking whether resources last or stay'],
 cnClose:'禄权同宫的功课是「有力而不压人」。把资源和魄力用在成事上，再把沟通和分功留给别人，这副牌才走得长远。命理倾向不构成投资建议，决策以正规合同和持牌机构说明为准。',
 enClose:'This pairing teaches being strong without overpowering others. Put resources and drive into delivering, and leave communication and credit to others, so the hand lasts. This cultural-tendency reference is not investment advice; rely on proper contracts and licensed institutions.'},

{cat:'sihua',slug:'ziwei-luke-tonggong-ruhe-kan',focus:'禄科同宫',focusEn:'Hua Lu and Hua Ke in the same palace',
 cnT:'禄科同宫：财气配名声，怎么把人缘用成长久贵人',enT:'When Hua Lu and Hua Ke Share a Palace: Means and Reputation Together',
 cnD:'化禄主实利机缘，化科主名声缓和，同宫等于财气和名气互相带动，人缘好、贵人多，利教育、专业与口碑型发展；短板是好面子、易被人情牵住。',
 enD:'Hua Lu brings real benefit and opportunity while Hua Ke brings reputation and smoothing. Together means means and name reinforce each other, with strong relationships and mentors, which favors education, expertise and reputation-driven work; the risk is prizing face and being led by obligations.',
 cnL:'禄科同宫是一副「因名得财、因财得名」的牌，关键在名实相符，别让面子和人情把好处耗掉。',
 enL:'This pairing is a hand of gaining means through name and name through means; the key is matching name to substance so face and obligations do not drain the benefit.',
 cnA:'有人见禄科同宫就以为名利双收，却没看到若只图面子、不敢拒绝人情，容易被牵累、也容易虚名无实。',
 enA:'Some assume this guarantees both means and fame without noticing that prizing face and being unable to refuse obligations leads to burdens and an empty reputation.',
 cnLog:['禄主实利与机缘，科主名声、文书与缓和，同宫让名利互相带动。','常见表现是因名声、口碑而得财，或因慷慨、结缘而得名。','逢天魁、天钺、左辅、右弼会照，贵人更稳、助力更久。','要防苗而不秀：名声在外却没有真财源、真本事，面子反成负担。'],
 enLog:['Lu governs real benefit and opportunity, Ke governs reputation, documents and smoothing; together means and name reinforce each other.','It often shows as earning through reputation and word of mouth, or gaining name through generosity and making ties.','With Tian Kui, Tian Yue, Zuo Fu or You Bi, mentors are steadier and support lasts longer.','Guard against flowering without fruit: a public name without real income or skill, where face becomes a burden.'],
 cnStep:['先定位禄科同宫所在宫位，定名利主要落在哪个领域','看同宫主星，分清财气和名声分别怎么表现','看三方贵人星，评估助力是不是长久','核名实：有没有真本事、真财源支撑这个名声','数煞星，防虚名、口舌把好处打折','把人情和原则分开，该拒绝时温和而清楚'],
 enStep:['Locate the palace with Lu and Ke to see which area means and name mainly land in','Read its major star to see how benefit and reputation each express','Check mentor stars in the trine to assess whether support lasts','Verify name against substance: real skill and income backing the reputation','Count malefics to guard an empty name or disputes discounting the benefit','Separate obligations from principles and refuse gently but clearly when needed'],
 cnMis:['见禄科就当名利双收、坐等兑现','只图面子、忽略实力，把名声做成虚名','被人情绑住、不敢拒绝，最后被牵累'],
 enMis:['Treating the pairing as guaranteed means and fame and waiting for it','Prizing face over skill and turning reputation into an empty name','Being bound by obligations, unable to refuse, and ending up burdened'],
 cnClose:'禄科同宫的功课是「名实相符」。把名声建立在真本事和真财源上，再把人缘处成长久的贵人，这副牌才稳。',
 enClose:'This pairing teaches matching name to substance. Build reputation on real skill and income, then turn relationships into lasting mentors, and the hand stays steady.'},

{cat:'sihua',slug:'ziwei-quanke-tonggong-ruhe-kan',focus:'权科同宫',focusEn:'Hua Quan and Hua Ke in the same palace',
 cnT:'权科同宫：实干又有名，怎么把说服力用成专业招牌',enT:'When Hua Quan and Hua Ke Share a Palace: Doing the Work and Being Known',
 cnD:'化权主执行掌控，化科主名声理性，同宫等于既做得出又说得服，利专业成名、技术路线与带队；短板是好胜、爱面子、听不进异见。',
 enD:'Hua Quan brings execution and control while Hua Ke brings reputation and reason. Together means you both deliver and persuade, which favors professional recognition, technical tracks and leadership; the risk is competitiveness, face and refusing dissent.',
 cnL:'权科同宫是一副「做得出、也讲得明」的牌，适合把专业做成权威；要防的是好胜争功、容不下不同意见。',
 enL:'This pairing is a hand of producing and explaining, suited to turning expertise into authority; guard against competing for credit and refusing differing views.',
 cnA:'有人见权科同宫就当一定成名，却没看到若只靠强势说服、不肯听人，团队会散，名声也难长久。',
 enA:'Some assume this guarantees recognition without noticing that persuading through force and refusing to listen scatters the team and shortens the reputation.',
 cnLog:['权主魄力、执行与掌控，科主名声、理性与文书，同宫让实干与说服力合一。','利专业权威、技术领导、教学与需要公信力的角色。','逢文昌、文曲会照，表达与文名更盛，专业招牌更亮。','它放大好胜与面子，听不进异见、争功不省时，反而孤立自己。'],
 enLog:['Quan governs drive, execution and control, Ke governs reputation, reason and documents; together doing and persuading become one.','It favors professional authority, technical leadership, teaching and roles needing public credibility.','With Wen Chang or Wen Qu, expression and scholarly name grow and the professional brand brightens.','It amplifies competitiveness and face; refusing dissent and claiming credit isolate you instead.'],
 cnStep:['先定位权科同宫所在宫位，定实干与名声落在哪个领域','看同宫主星，分清执行力和说服力分别怎么表现','把实干和表达结合，先做得出、再讲得明','看三方与团队支撑，防只靠个人强势','数煞星，防争胜、口舌与功归功之争','刻意听取异见、肯分功，不把说服力变成压人'],
 enStep:['Locate the palace with Quan and Ke to see which area doing and recognition land in','Read its major star to see how execution and persuasion each express','Combine doing and expressing: produce first, then explain clearly','Check the trine and team support rather than relying on personal force','Count malefics to guard competitiveness, disputes and credit fights','Deliberately hear dissent and share credit rather than using persuasion to dominate'],
 cnMis:['见权科就当一定成名、坐等兑现','好胜争功、听不进异见，把自己孤立','只看本宫，不看团队与长期口碑'],
 enMis:['Treating the pairing as guaranteed fame and waiting for it','Competing for credit and refusing dissent until isolated','Reading only the home palace without the team and long-term reputation'],
 cnClose:'权科同宫的功课是「以实力服人」。把专业做扎实、把话讲明白，再肯听意见、肯分功，名声才立得久。',
 enClose:'This pairing teaches persuading through real ability. Do solid professional work, explain clearly, then hear dissent and share credit, and the reputation lasts.'},

{cat:'sihua',slug:'ziwei-zihuake-ruhe-kan',focus:'自化科',focusEn:'the self-transforming Hua Ke',
 cnT:'自化科怎么看：名声自己往外亮，也要防虚名好面子',enT:'How to Read the Self-Transforming Hua Ke: Reputation You Project Yourself',
 cnD:'宫干使本宫星自化科，是自己主动把形象、名声往外亮，利考试、发表与公关；与生年科的「天生有名」不同，要防虚名、好面子、苗而不秀。',
 enD:'When a palace stem makes its own star transform to Ke, you actively project image and reputation, which favors exams, publishing and public relations. Unlike a natal Ke that is innate, guard against an empty name, prizing face and flowering without fruit.',
 cnL:'自化科像自己给自己打光，灯打得多亮要看台上有没有真东西，光有灯、没有内容就成了虚名。',
 enL:'Self-transforming Ke is like shining your own spotlight; how bright it should be depends on whether there is real content on stage, or the light becomes an empty name.',
 cnA:'有人见自化科就以为天生带名，其实那是自己往外彰显的劲，若没有真才实学支撑，越亮越容易被看穿。',
 enA:'Some take self-transforming Ke as innate fame, but it is the energy of projecting yourself; without real skill behind it, the brighter it shines the easier it is to see through.',
 cnLog:['自化是本宫宫干引动本宫星，科自化主主动彰显、缓和与好形象。','它与生年科不同：生年科是天生底色，自化科是自己往外亮。','利考试临场、发表、形象与公关，容易给人温和、体面的第一印象。','要防虚名与好面子：名声是自己亮出来的，须有真本事、真成果托住。'],
 enLog:['Self-transformation is the palace own stem activating its star; self-Ke governs active projection, smoothing and a good image.','It differs from natal Ke: natal Ke is an innate tone, while self-Ke is something you project.','It favors exam performance, publishing, image and public relations, tending to give a gentle, presentable first impression.','Guard against an empty name and face: since the reputation is self-projected, it needs real skill and results to hold it up.'],
 cnStep:['先找自化科所在宫位，定你主动彰显的是哪个领域','理解这是「自己往外亮」，不是天生注定的名声','看本宫主星有没有真才实学，定光打出去有没有内容','看三方有没有实利、成果支撑，防虚名','把表达建立在实力上，先有料、再发声','防好面子、怕批评，遇到指正看内容而非情绪'],
 enStep:['Find the palace with self-Ke to see which area you actively project','Understand it as self-projection rather than destined fame','Read the palace major star for real skill, so the light has content','Check the trine for real benefit and results to guard an empty name','Build expression on ability: have substance before speaking','Guard face and fear of criticism, taking correction on content rather than emotion'],
 cnMis:['把自化科当天生有名，坐等兑现','只图形象、不练内功，把名声做成虚名','好面子、听不进指正，越亮越虚'],
 enMis:['Taking self-Ke as innate fame and waiting for it','Prizing image over skill and turning reputation into an empty name','Prizing face and refusing correction, growing brighter but hollower'],
 cnClose:'自化科的功课是「先有料、再发光」。把真本事和真成果备足，再让名声自然亮出去，这束光才照得久。',
 enClose:'Self-Ke teaches having substance before shining. Prepare real skill and results, then let reputation project naturally, and the light lasts.'},

{cat:'kanpan',slug:'ziwei-poge-dian-ruhe-zhao',focus:'格局破格点',focusEn:'where a pattern is broken',
 cnT:'怎么找格局的破格点：再好的格，也要看哪里被冲破',enT:'How to Find Where a Pattern Is Broken in a Zi Wei Chart',
 cnD:'格局是星曜的净组合，破格点就是破坏结构的那一两个煞、忌、空、劫；按本宫、三方、对宫、夹宫顺序排查，分清「成格有瑕」与「名存实破」。',
 enD:'A pattern is a net combination of stars, and its breaking point is the one or two malefics, Ji, emptiness or clashes that disrupt the structure. Check in the order of home palace, trines, opposite and flanking palaces to distinguish a valid pattern with flaws from one that exists in name only.',
 cnL:'看格局不能只数吉星，要反过来找破口：破在核心是不成立，破在外围只是减分。',
 enL:'Do not only count auspicious stars for a pattern; reverse the lens and look for the break. A break at the core means it does not hold, while one at the edge only discounts it.',
 cnA:'有人见吉星凑齐就认定成格，也有人见一颗煞就判全破；真正要判断的是那颗星破在什么位置、有多重。',
 enA:'Some declare a pattern once auspicious stars gather, while others call it wholly broken at one malefic; the real task is judging where that star breaks and how heavily.',
 cnLog:['格局成立看结构，破格点是破坏这个结构的星，位置决定破坏程度。','本宫见煞忌最重，三方、对宫次之，夹宫再次之。','吉星再多，一颗化忌或煞星落在关键位置，也可能让格局不成立。','要分清「有瑕」（格局仍在、好处打折）与「破」（结构不成立），不可一概而论。'],
 enLog:['A pattern holds through structure, and its breaking point is the star that disrupts that structure; position sets the degree of damage.','A malefic or Ji in the home palace weighs most, then the trines and opposite, then the flanking palaces.','However many auspicious stars there are, one Hua Ji or malefic at a key position can keep the pattern from holding.','Distinguish flawed (the pattern holds with discounted benefit) from broken (the structure does not hold); they are not the same.'],
 cnStep:['先写清这个格局的成立条件，逐条对照','列出本宫主星与辅星，看核心是否成立','逐一数三方四正的煞、忌、空、劫，定位破点','再看前后夹宫有没有暗中破坏','判断破在核心还是外围，定是减分还是不成立','最后才给行动建议，不笼统贴好坏标签'],
 enStep:['Write the pattern conditions clearly and check them one by one','List the home palace major and assistant stars to see whether the core holds','Count malefics, Ji, emptiness and clashes in the triple-direction to locate the break','Then check the flanking palaces for hidden disruption','Judge whether the break is at the core or edge, meaning discount or failure','Only then give action guidance rather than a vague good or bad label'],
 cnMis:['见一颗煞就判格局全破，自我恐吓','只数吉星、不找破口，把不成立的格当成格','不会定位破在哪，笼统说这格好或坏'],
 enMis:['Calling a pattern wholly broken from one malefic and frightening yourself','Counting only auspicious stars without finding the break, treating a failed pattern as valid','Being unable to locate the break and vaguely calling the pattern good or bad'],
 cnClose:'找破格点，是把格局从「看热闹」变成「看结构」。分清破在哪、有多重，你才知道这个格到底能不能靠、该怎么补。',
 enClose:'Finding the breaking point moves you from admiring a pattern to reading its structure. Knowing where and how heavily it breaks tells you whether the pattern can be relied on and how to reinforce it.'},

{cat:'kanpan',slug:'ziwei-daxian-pan-chongbu-shiergong-ruhe-kan',focus:'大限盘重布十二宫',focusEn:'rebuilding the twelve palaces on the decade chart',
 cnT:'大限盘怎么重布十二宫：以大限命宫立太极的看法',enT:'How to Rebuild the Twelve Palaces on the Decade Chart',
 cnD:'进入某个大限，要以大限命宫为新原点，按方向重排这十年的十二宫，再配大限四化；宫位是关系不是地名，这套是「十年视角」，与流年盘分层。',
 enD:'When you enter a decade, use its Life Palace as the new origin and rebuild the twelve palaces in direction for those ten years, then add the decade transformations. Palaces are relationships, not place names; this is the ten-year lens, layered separately from the annual chart.',
 cnL:'大限盘重布，是把镜头从「本命的我」换成「这十年的我」，坐标系一换，十二宫的角色也要重新排。',
 enL:'Rebuilding the decade chart shifts the lens from the natal me to the me of these ten years; once the coordinate system changes, the roles of the twelve palaces are re-arranged.',
 cnA:'有人读大限还沿用本命宫名，结果怎么对都错位；也有人把大限盘和流年盘混成一层，读不出层次。',
 enA:'Some keep using natal palace names when reading a decade and everything misaligns; others merge the decade and annual charts into one layer and lose the hierarchy.',
 cnLog:['大限命宫是这十年的新太极，以它为原点顺或逆重排十二宫。','重排后不必再用本命宫名，宫位代表的是相对关系，不是固定地名。','配合大限四化，看这十年事业、财、感情分别由哪一宫管。','大限盘是十年视角，再叠流年盘才能把事情收窄到具体年份。'],
 enLog:['The decade Life Palace is the new Tai Ji of these ten years; use it as origin to rebuild the twelve palaces in direction.','After rebuilding, drop the natal palace names; palaces express relative relationships, not fixed place names.','Add the decade transformations to see which palace governs work, money and relationships in these years.','The decade chart is the ten-year lens; layering the annual chart narrows events to a specific year.'],
 cnStep:['先定当前所在大限及其命宫位置','以大限命宫为太极，按阴阳男女方向重排十二宫','逐宫看该宫星曜组合在这十年的含义','加上该大限四化，定这十年的能量开关','锁定事业、财、感情等关键领域由哪宫管','再用流年盘重布，把十年判断收窄到年'],
 enStep:['First identify the current decade and the position of its Life Palace','Use the decade Life Palace as Tai Ji and rebuild the twelve palaces in the yin-yang gender direction','Read each palace star combination meaning across these ten years','Add the decade transformations to set the energy switches for the period','Identify which palace governs key areas such as career, money and relationships','Then rebuild the annual chart to narrow the ten-year reading to a year'],
 cnMis:['还用本命宫名读大限，怎么对都错位','把大限盘和流年盘混成一层，读不出层次','只看大限命宫，不重排其余十一宫'],
 enMis:['Keeping natal palace names when reading the decade so nothing aligns','Merging decade and annual charts into one layer and losing the hierarchy','Reading only the decade Life Palace without rebuilding the other eleven palaces'],
 cnClose:'大限盘重布，是学会用「这十年的坐标系」看自己。把十二宫重排、四化加上，再叠流年，你才读得准这一阶段的主线。',
 enClose:'Rebuilding the decade chart is learning to see yourself through the coordinate system of these ten years. Rebuild the palaces, add transformations, then layer the year, and you read the stage main line accurately.'},

{cat:'kanpan',slug:'ziwei-feixing-luji-luxian-ruhe-kan',focus:'飞星禄忌路线',focusEn:'tracing the Lu and Ji routes in flying stars',
 cnT:'飞星怎么追禄忌路线：把宫位之间的因果一笔笔连起来',enT:'How to Trace the Lu and Ji Routes: Linking Cause and Effect Across Palaces',
 cnD:'宫干飞化把十二宫连成网络，禄为因、为投入，忌为果、为牵挂；用「禄转忌」追一件事的回报落在哪、卡在哪，先立太极再追，区别于静态生年四化。',
 enD:'Palace-stem flying transformations link the twelve palaces into a network; Lu is the cause and investment, Ji the result and attachment. Use Lu-turns-to-Ji to trace where the return lands or stalls, setting the Tai Ji first, distinct from static natal transformations.',
 cnL:'追禄忌路线像顺着一笔笔转账记录看钱和情分去了哪，只看一个宫，永远不知道因果的另一头是谁。',
 enL:'Tracing Lu and Ji is like following a chain of transfers to see where money and care went; one palace alone never reveals the other end of cause and effect.',
 cnA:'有人看飞星不立太极、方向全乱，也有人只看单宫、不追落点，结果把动态的飞化和静态的生年四化混为一谈。',
 enA:'Some read flying stars without setting Tai Ji and lose direction; others inspect one palace without tracing the landing, and end up confusing dynamic flights with static natal transformations.',
 cnLog:['宫干飞化让十二宫不再是抽屉，而是一张有方向的关系网。','禄主投入、机缘与回报，忌主牵挂、亏欠与卡点，禄为因、忌为果。','「禄转忌」是从禄的落点再追其宫干之忌，看好处最终落在哪或卡在哪。','追之前先立太极，弄清自己站在哪个宫位说话，方向才不会错。'],
 enLog:['Palace-stem flights make the twelve palaces a directed relationship network rather than drawers.','Lu governs investment, opportunity and return, Ji governs attachment, debt and sticking points; Lu is the cause and Ji the result.','Lu-turns-to-Ji follows the stem of the palace where Lu lands to see where the benefit finally settles or stalls.','Set Tai Ji before tracing, knowing which palace you speak from, so the direction stays correct.'],
 cnStep:['先定要追的事与起点宫位，立好太极','找该宫宫干的四化，看清禄、权、科、忌分别飞向哪','先看禄落哪，定投入与回报的方向','再看忌落哪，定牵挂、亏欠或卡点','用禄转忌再追一步，看结果最终落在哪个宫','合本命与大限背景下结论，再决定怎么行动'],
 enStep:['First settle the matter to trace and the starting palace, setting Tai Ji','Find that palace stem transformations and see where Lu, Quan, Ke and Ji each fly','First read where Lu lands to set the direction of investment and return','Then read where Ji lands to set attachment, debt or the sticking point','Use Lu-turns-to-Ji one more step to see which palace finally holds the result','Conclude within the natal and decade background before deciding how to act'],
 cnMis:['不立太极就追，方向全乱','只看单宫、不追落点，读不到因果的另一头','把飞化和生年四化混为一谈，层次不清'],
 enMis:['Tracing without setting Tai Ji and losing all direction','Reading one palace without tracing the landing, missing the other end of cause and effect','Confusing flying transformations with natal transformations and losing the layers'],
 cnClose:'追禄忌路线，是把一张盘读成「有来有往的因果图」。立好太极、一笔笔连下去，你才知道一件事会回报在哪、卡在哪。',
 enClose:'Tracing Lu and Ji turns the chart into a cause-and-effect map with a sender and receiver. Set Tai Ji and link the steps one by one, and you learn where a matter returns and where it stalls.'},

{cat:'kanpan',slug:'ziwei-sihua-xiangyi-duiying-renshi-ruhe-kan',focus:'四化象义对应人事',focusEn:'mapping the Four Transformations to real human affairs',
 cnT:'四化象义怎么对应到具体人事：禄权科忌落到生活场景',enT:'How to Map the Four Transformations to Real Life Situations',
 cnD:'四化是星曜表达方式的变化，不是固定吉凶分数；禄主机会资源、权主掌控责任、科主名声文书、忌主执着亏欠，结合落星落宫，才能把术语翻译成现实场景。',
 enD:'The Four Transformations are changes in how a star expresses itself, not fixed good or bad scores. Lu is opportunity and resources, Quan control and responsibility, Ke reputation and documents, Ji attachment and debt. Combine the star and palace to translate the terms into real situations.',
 cnL:'四化的术语若不落到具体人事，就只是空转；先懂象义，再问它落在哪宫、附在哪颗星，含义才具体。',
 enL:'If transformation terms are not grounded in real affairs they merely spin; understand the meaning first, then ask which palace and star they attach to, and the meaning becomes concrete.',
 cnA:'有人把四化当固定加减分，也有人只背术语不翻译成人话，结果一套到自己的生活就对不上。',
 enA:'Some treat the transformations as fixed plus or minus scores, while others memorize terms without translating them into plain language, and nothing fits their own life.',
 cnLog:['四化描述的是星的表达方式变化，落宫决定领域、落星决定具体表现。','禄=机会、资源、顺利；权=掌控、责任、竞争；科=名声、缓和、文书；忌=执着、亏欠、卡点。','同一化在不同宫、不同星上，对应的人事差别很大，要分别翻译。','把象义转成工作、钱、关系、健康的现实场景，才知道怎么应对。'],
 enLog:['The transformations describe changes in how a star expresses; the palace sets the area and the star sets the concrete form.','Lu is opportunity, resources and smoothness; Quan control, responsibility and competition; Ke reputation, smoothing and documents; Ji attachment, debt and sticking points.','The same transformation maps to very different affairs across palaces and stars, so translate each separately.','Turn the meanings into real scenes of work, money, relationships and health to know how to respond.'],
 cnStep:['先认禄、权、科、忌的基本象义，不急着判吉凶','定位四化落在哪一宫，定对应领域','看它附在哪颗主星上，定具体表现','把象义翻译成现实生活里的具体场景','合三方四正与大限，看有没有被引动或打折','最后落到该怎么行动，而不是停在术语'],
 enStep:['First learn the basic meanings of Lu, Quan, Ke and Ji without judging good or bad','Locate which palace each lands in to set the area','Read which major star it attaches to for the concrete form','Translate the meaning into a specific scene in real life','Combine the triple-direction and decade to see whether it is activated or discounted','Finally settle how to act rather than stopping at terms'],
 cnMis:['把四化当固定吉凶分数，见到就贴标签','只背术语、不翻译成人话，一套生活就空','只看化曜，不看落星落宫与三方'],
 enMis:['Treating the transformations as fixed good or bad scores and labeling them on sight','Memorizing terms without plain-language translation, turning hollow in real life','Reading only the transformed star without the host star, palace and trines'],
 cnClose:'四化象义对应人事，是把命理从「背术语」变成「读生活」。把每颗化曜放回宫位、星性和现实场景里，你才读得懂它在说什么。',
 enClose:'Mapping transformation meanings to real affairs moves the practice from memorizing terms to reading life. Put each transformed star back into its palace, star nature and real situation, and you understand what it is saying.'}
];
