// 2026-09-25 调研驱动 第3组：辅煞3 + 流年4 = 7篇
module.exports=[
// ========== 辅煞 3 ==========
{cat:'fuzhu',slug:'ziwei-liujixing-fengong-hanyi',focus:'六吉星的分工',focusEn:'the division of labor among the six auspicious stars',
 cnT:'六吉星怎么分工：辅弼、魁钺、昌曲落宫后的现实含义',enT:'How the Six Auspicious Stars Divide Their Work: The Real Meaning of Fu-Bi, Kui-Yue and Chang-Qu',
 cnD:'六吉星分三组：左辅右弼偏人手协作，天魁天钺偏门路贵人，文昌文曲偏表达才华；要看落宫、是否成对，不能见吉星就断顺利。',
 enD:"The six auspicious stars form three pairs: Zuo-Fu and You-Bi for people and cooperation, Tian-Kui and Tian-Yue for openings and mentors, and Wen-Chang and Wen-Qu for expression and talent. Check the palace and pairing before assuming smoothness.",
 cnL:'很多人盘上看到一堆吉星就放心，其实六吉星各管一摊——有的帮你凑齐人手，有的给你门路，有的让你会写会说。分不清类型，吉星的好就读不具体。',
 enL:"Many people relax at the sight of many auspicious stars, but each handles a different area: some gather people, some open doors, and some make you write and speak well. Without distinguishing the types, their benefit stays vague.",
 cnA:'这个问题要从「笼统的吉」走到「具体的助力」。真正该问的是你缺的是人手、门路还是表达能力，然后看对应的那组星落在哪、成不成对，助力才有着落。',
 enA:"This moves from vague auspiciousness to concrete help. The right question is whether you lack people, openings or expression, then see where the matching pair lands and whether it is complete, so the support has a target.",
 cnLog:['左辅右弼偏向人手与协作，像有人帮你分担执行。','天魁天钺偏向门路和贵人，在关键时刻给机会和引荐。','文昌文曲偏向表达、学习和才华，主文书、考试和专业曝光。','成对会照比单星出现更有解释力，吉星仍受主星状态、煞忌和宫位限制。'],
 enLog:["Zuo-Fu and You-Bi lean toward people and cooperation, like someone sharing execution.","Tian-Kui and Tian-Yue lean toward openings and mentors, giving chances and referrals at key moments.","Wen-Chang and Wen-Qu lean toward expression, learning and talent, governing writing, exams and professional exposure.","A complete pair meeting the chart carries more weight than a single star, and auspicious stars remain limited by the major star, malefics and palace."],
 cnStep:['先把六颗吉星按辅弼、魁钺、昌曲分成三组','确认每组星在你盘上的落宫','看是否成对会照，成对的助力更完整','求职找门路，重点看天魁天钺','创业组队，重点看左辅右弼','考试和专业曝光，重点看文昌文曲，同时检查煞忌有没有打折'],
 enStep:["First divide the six stars into Fu-Bi, Kui-Yue and Chang-Qu","Confirm where each pair lands in your chart","See whether they appear as complete pairs, which give fuller support","For job searching and openings, focus on Tian-Kui and Tian-Yue","For startup team building, focus on Zuo-Fu and You-Bi","For exams and professional exposure, focus on Wen-Chang and Wen-Qu while checking whether malefics discount them"],
 cnMis:['看到吉星就笼统断顺利，不分助力类型','只看单星不看成对，高估了零散的吉','以为吉星万能，忽略主星弱、煞忌重时助力打折'],
 enMis:["Judging smoothness vaguely from auspicious stars without distinguishing the type of help","Looking at single stars instead of pairs and overestimating scattered luck","Treating auspicious stars as all-powerful and ignoring that weak major stars and heavy malefics discount their help"],
 cnClose:'六吉星不是一团模糊的好运，而是三类具体的资源。看清你缺什么、对应的星在哪、成不成对，贵人相助才会从一句话变成可走的路。',
 enClose:"The six auspicious stars are not a blur of good luck but three concrete resources. See what you lack, where the matching stars land and whether they pair, and help from mentors turns from a saying into a walkable path."},

{cat:'fuzhu',slug:'ziwei-dikong-dijie-luokong-xuhao',focus:'地空地劫的落空与虚耗',focusEn:'the emptying and draining of Di-Kong and Di-Jie',
 cnT:'地空地劫的落空和虚耗如何区分',enT:'How to Distinguish the Emptying and Draining of Di-Kong and Di-Jie',
 cnD:'地空地劫属消融型阻力，表现为资源不落地、投入难留存，和擎羊火星的冲击型不同；有吉星承接时也可能表现为抽象、创新和舍弃。',
 enD:"Di-Kong and Di-Jie are dissolving-type friction, showing resources that do not land and effort that is hard to keep, unlike the impact type of Qing-Yang and Huo-Xing. With auspicious support they can also show as abstraction, innovation and letting go.",
 cnL:'「为什么我明明很努力，却什么都没留下」——这往往是空劫的语言。它不像煞星那样正面冲撞，而是悄悄让投入落空、成果流失，像水从指缝间流走。',
 enL:"Why do I work hard yet keep nothing is often the language of Kong and Jie. They do not clash head-on like malefics but quietly let effort fall through and results slip away, like water through the fingers.",
 cnA:'关键是先分清「损失」的类型：是计划落空、成果流失，还是动作过猛？空劫管的是前两种。读懂它，才能解释努力为什么没有沉淀，而不是笼统地说自己运气差。',
 enA:"The key is first separating the type of loss: a plan falling through, results leaking away, or acting too forcefully. Kong and Jie govern the first two. Reading them explains why effort does not accumulate rather than vaguely blaming bad luck.",
 cnLog:['地空地劫归为消融型阻力，和擎羊陀罗火星铃星的冲击型区分开。','空劫更像资源不落地、投入难留存，主虚耗。','判断要看被作用的主星和宫位主题，落在财帛、事业表现不同。','有吉星或结构承接时，空劫也可能表现为抽象思维、创新和敢于舍弃。'],
 enLog:["Di-Kong and Di-Jie are dissolving-type friction, distinguished from the impact type of Qing-Yang, Tuo-Luo, Huo-Xing and Ling-Xing.","They are more like resources that do not land and effort that is hard to keep, governing draining.","Judgment depends on the affected major star and palace theme, showing differently in Wealth and Career.","With auspicious stars or structural support, they can also show as abstract thinking, innovation and the courage to let go."],
 cnStep:['先确认地空地劫落在哪一宫、作用在哪颗星','把它和冲击型煞星区分，确认这是虚耗而非冲突','看该宫主题：学习、项目还是理财，虚耗的内容不同','检查投入为什么不落地，是摊子太大还是方向常变','看有没有吉星承接，把空劫转向创新和舍弃的正面','针对虚耗设「沉淀动作」，如阶段交付、强制储蓄、作品归档'],
 enStep:["First confirm which palace Kong and Jie land in and which star they affect","Separate them from impact-type malefics, confirming this is draining rather than clash","Read the palace theme: study, projects or finances, each with different draining content","Examine why effort does not land, whether from taking on too much or changing direction often","See whether auspicious stars support it, turning Kong and Jie toward innovation and letting go","Set accumulation actions for the draining, such as staged delivery, forced saving and archiving work"],
 cnMis:['把空劫和所有煞曜混成一类，统统当冲撞','只看到损失，看不见吉星承接时的创新和舍弃','不做沉淀动作，任由努力反复落空'],
 enMis:["Mixing Kong and Jie with all malefics as if they all clash","Seeing only loss and missing innovation and letting go when auspicious stars support","Skipping accumulation actions and letting effort fall through repeatedly"],
 cnClose:'空劫讲的是「留不留得住」，不是「会不会被撞」。看清虚耗在哪、为什么不落地，再用沉淀动作接住，努力才会真正变成积累。',
 enClose:"Kong and Jie concern whether things are kept, not whether you are struck. See where the draining is and why things do not land, then use accumulation actions to catch them so effort truly becomes reserve."},

{cat:'fuzhu',slug:'ziwei-liushaxing-chongji-xiaorong',focus:'六煞星的冲击型与消融型',focusEn:'the impact and dissolving types of the six malefics',
 cnT:'六煞星落宫怎么读：先分冲击型与消融型',enT:'How to Read the Six Malefics by Palace: First Separate Impact from Dissolving',
 cnD:'六煞分直接冲击、持续摩擦和资源耗散：擎羊火星主骤变，陀罗铃星主拖延，空劫主虚耗；组合与吉星承接决定阻力能否转为执行力。',
 enD:"The six malefics divide into direct impact, sustained friction and resource dissolving: Qing-Yang and Huo-Xing for sudden change, Tuo-Luo and Ling-Xing for delay, and Kong and Jie for draining. Combinations and auspicious support decide whether friction becomes execution.",
 cnL:'一谈煞星，很多人就只想着「凶」，其实六颗煞星的作用方式完全不同。有的像当头一棒，有的像钝刀子磨，有的像沙漏，先分清类型才知道怎么应对。',
 enL:"At the mention of malefics, many think only of misfortune, but the six act in entirely different ways: some strike like a blow, others grind like a dull blade, and others drain like an hourglass. Separate the types before responding.",
 cnA:'这个问题要把「恐吓式读法」换成「风险管理式读法」。煞星不是判你坏，而是标出风险的形状——是骤变、拖延还是耗散，对症设流程，阻力反而能变成执行力。',
 enA:"This replaces fear-based reading with risk-management reading. Malefics do not judge you as bad but mark the shape of risk: sudden change, delay or draining. Set processes to match and friction can become execution.",
 cnLog:['擎羊、火星偏直接冲击和骤变，陀罗、铃星偏持续摩擦和拖延。','地空、地劫偏资源耗散和难留存，三类作用方式不同。','同一煞曜落命、财、官、疾等宫，现实问题各不相同。','组合与吉星承接决定阻力能否转为执行力，化解应写成风险管理和行动边界。'],
 enLog:["Qing-Yang and Huo-Xing lean toward direct impact and sudden change; Tuo-Luo and Ling-Xing toward sustained friction and delay.","Di-Kong and Di-Jie lean toward resource draining and weak retention, giving three distinct modes.","The same malefic in the Life, Wealth, Career or Health palace carries different real problems.","Combinations and auspicious support decide whether friction becomes execution; remedies should be written as risk management and action boundaries."],
 cnStep:['先列出六颗煞星并按冲击、摩擦、耗散分三类','确认每颗煞星落在哪一宫、作用什么主题','冲击型，重点做安全预案和缓冲','摩擦拖延型，重点做流程节点和截止时间','耗散型，重点做沉淀和强制留存','看吉星承接，把对应的阻力转化成执行力，而不是追求一个万能化解'],
 enStep:["First list the six malefics and group them into impact, friction and draining","Confirm which palace each lands in and what theme it affects","For the impact type, focus on safety plans and buffers","For friction and delay, focus on process checkpoints and deadlines","For draining, focus on accumulation and forced retention","See auspicious support to convert the matching friction into execution rather than seeking a universal remedy"],
 cnMis:['把六颗煞星笼统当凶，不区分作用方式','只想着「化解」，不做具体的风险管理流程','忽略落宫差异，同一煞星在不同宫位被一概而论'],
 enMis:["Treating the six malefics vaguely as bad without distinguishing their modes","Thinking only of remedies without concrete risk-management processes","Ignoring palace differences and generalizing the same malefic across positions"],
 cnClose:'煞星不是坏标签，而是风险的不同形状。学会分辨冲击、摩擦和耗散，再对症设流程，你会发现带煞的盘往往更有执行力。',
 enClose:"Malefics are not bad labels but different shapes of risk. Learn to distinguish impact, friction and draining, then set matching processes, and you often find charts with malefics carry stronger execution."},

// ========== 流年 4 ==========
{cat:'liunian',slug:'ziwei-daxian-xiaoxian-liunian-fenceng',focus:'大限小限流年的分层',focusEn:'the layering of decade, minor and annual limits',
 cnT:'大限、小限、流年怎么分层：十年背景与年度触发',enT:'How to Layer the Decade, Minor and Annual Limits: Ten-Year Background and Yearly Triggers',
 cnD:'大限管约十年的阶段背景，流年管当年推进，小限太岁是辅助校验；所有动态层都要回到本命承接，不能把十年主题复制到每一年。',
 enD:"The decade governs the roughly ten-year background, the year governs that year's progress, and the minor limit and Tai-Sui serve as auxiliary checks. Every dynamic layer returns to natal capacity; the ten-year theme cannot be copied to each year.",
 cnL:'「大限好是不是这十年都好」「流年和小限听谁的」——这些困惑都来自没分层。时间盘像地图的不同比例尺，十年看大势，一年看触发，各管各的尺度。',
 enL:"Whether a good decade means ten good years and whether the year or minor limit takes priority are confusions from not layering. Timing charts are like map scales: the decade shows the trend and the year shows triggers, each at its own scale.",
 cnA:'最常见的错误是把不同比例尺的信息混算，要么跳过本命，要么把十年主题复制到每一年，还把小限和流年重复计分。分层的意义，就是让每一层只回答它该回答的问题。',
 enA:"The common error is mixing information across scales, skipping the natal, copying the ten-year theme to every year, and double-counting the minor and annual limits. Layering means each level answers only its own question.",
 cnLog:['大限负责约十年的阶段主题，流年负责当年的具体推进。','小限与太岁是辅助校验层，不宜与流年重复计分。','本命盘是所有动态层的底盘，动态不能脱离本命承接。','不同门派对小限和流年起法有差异，需先声明采用的规则。'],
 enLog:["The decade is responsible for the roughly ten-year stage theme, and the year for that year's concrete progress.","The minor limit and Tai-Sui are auxiliary checks and should not be double-counted with the year.","The natal chart is the foundation for every dynamic layer, which cannot detach from natal capacity.","Schools differ in how they set the minor and annual limits, so declare the rules used first."],
 cnStep:['先读懂本命盘，确认底盘的承接条件','再排大限，定当前十年的阶段主题','然后看流年，定当年对十年主题的推进','用小限和太岁做辅助校验，不重复计分','检查有没有把十年好坏直接复制到某一年','用升职、搬家这类具体事，演示十年和今年说法为何不同'],
 enStep:["First read the natal chart to confirm the foundation's carrying conditions","Then cast the decade to set the current ten-year stage theme","Then read the year to set that year's progress on the decade theme","Use the minor limit and Tai-Sui as auxiliary checks without double-counting","Check whether the ten-year verdict has been copied directly onto one year","Use concrete matters such as promotion and moving to show why the decade and the year say different things"],
 cnMis:['把大限好坏平均摊到十年里的每一年','小限流年重复计分，同一信息算两遍','跳过本命直接谈运限，底盘空了'],
 enMis:["Spreading the decade verdict evenly across every year of the ten","Double-counting the minor and annual limits on the same information","Talking about limits while skipping the natal, leaving the foundation empty"],
 cnClose:'分层是看时间盘的基本功。十年给背景，一年给触发，本命给底盘，三者各归其位，你才听得懂一件事在不同尺度上的说法。',
 enClose:"Layering is the basic skill of timing charts. The decade gives background, the year gives triggers, and the natal gives the foundation; when each is in place, you understand one matter across different scales."},

{cat:'liunian',slug:'ziwei-siceng-shijianpan-diekan',focus:'四层时间盘叠看',focusEn:'stacking the four layers of timing charts',
 cnT:'本命、大限、流年与流月：四层时间盘怎么叠看',enT:'Natal, Decade, Year and Month: How to Stack the Four Timing Layers',
 cnD:'四层模型从本命底盘、大限阶段、流年年度到流月节奏，流年不能脱离本命与大限单独解释；每层只回答一个问题，并用趋势语言。',
 enD:"The four-layer model runs from the natal foundation through the decade stage, the year and the month. The year cannot be explained apart from the natal and decade; each layer answers one question and uses trend language.",
 cnL:'真正会看盘的人，手里像握着四张透明的图，叠在一起看。本命写你有什么，大限写这十年演什么，流年写今年推到哪，流月写当月的节奏，一层比一层细。',
 enL:"Skilled readers hold four transparent charts and stack them. The natal says what you have, the decade what these years perform, the year where things move now, and the month the current rhythm, each finer than the last.",
 cnA:'要避免两种极端：一是只看流年一宫就断事，二是四层信息全堆上来反而抓不住重点。叠盘的诀窍是让每一层只回答一个问题，再用条件和趋势表达，而不是说「必然发生」。',
 enA:"Avoid two extremes: judging from one yearly palace alone, and piling all four layers until the point is lost. The trick is having each layer answer one question and expressing conditions and trends rather than saying something must happen.",
 cnLog:['本命决定可以承接的结构，是四层的底盘。','大限决定十年主题，流年负责当年推进。','流月把年度主题细分到当月节奏和触发点。','趋势语言比必然发生更符合可验证边界，没有具体盘例不下保证。'],
 enLog:["The natal decides the structure that can be carried, the foundation of all four.","The decade decides the ten-year theme, and the year handles that year's progress.","The month subdivides the yearly theme into the current rhythm and triggers.","Trend language fits the verifiable boundary better than certainty; no guarantee is given without a concrete chart."],
 cnStep:['第一层读本命，只回答「我有什么结构」','第二层读大限，只回答「这十年的主题是什么」','第三层读流年，只回答「今年把主题推到哪」','第四层读流月，只回答「当月的节奏和触发点」','检查每层有没有越界回答别层的问题','全部用条件式趋势语言，整理成一张从结构到时机的流程图'],
 enStep:["First read the natal, answering only what structure I have","Second read the decade, answering only what this ten-year theme is","Third read the year, answering only where the theme moves this year","Fourth read the month, answering only the current rhythm and triggers","Check whether any layer oversteps into another layer's question","Use conditional trend language throughout and organize it into a flow from structure to timing"],
 cnMis:['只看流年一宫，脱离本命大限','四层全堆，抓不住每层只回答一个问题','用「必然发生」的口吻，越过可验证边界'],
 enMis:["Reading one yearly palace detached from the natal and decade","Piling all four layers and missing that each answers one question","Using it must happen language beyond the verifiable boundary"],
 cnClose:'四层叠盘不是把信息搞复杂，而是让结构和时机各归其位。底盘、十年、当年、当月层层递进，一件事的来龙去脉才看得完整。',
 enClose:"Stacking four layers does not complicate information but places structure and timing correctly. Foundation, decade, year and month progress in order, giving the full story of any matter."},

{cat:'liunian',slug:'ziwei-liuyue-niandu-chufa',focus:'流月的年度背景与触发',focusEn:'the yearly background and triggers of the monthly layer',
 cnT:'流月怎么用：先看年度背景，再找当月触发点',enT:'How to Use the Monthly Layer: Read the Yearly Background First, Then Find the Month Trigger',
 cnD:'流月不是独立新盘，而是把流年主题细分到月度节奏；先确认大限流年，再定位流月命宫四化，把趋势翻译成当月可观察的行动。',
 enD:"The monthly layer is not an independent chart but subdivides the yearly theme into monthly rhythm. Confirm the decade and year, then locate the monthly Life Palace and transformations, translating trends into observable actions for that month.",
 cnL:'很多人看流月像在看一张全新的盘，每个月换一套吉凶，这是误用。流月是放大镜——它不创造主题，只把今年这出戏，分到十二个月里逐场演。',
 enL:"Many read months like a brand-new chart with fresh fortune each month, which is misuse. The month is a magnifier; it does not create a theme but distributes this year's play across twelve scenes.",
 cnA:'关键是顺序不能反：先有大限和流年的背景，流月才有东西可放大。真正该做的是定位当月流月命宫和四化，再把抽象趋势翻译成当月能做、能验证的具体动作。',
 enA:"The key is not reversing order: with the decade and yearly background first, the month has something to magnify. Locate the monthly Life Palace and transformations, then translate abstract trends into concrete actions that month you can do and verify.",
 cnLog:['流月负责细化节奏，不替代本命、流年和大限。','节气与月份起法需先明确采用的规则，不同排法影响起点。','流月命宫与四化，把年度主题落到当月。','月度判断要落到可观察的任务和反馈，每月只抓一个重点。'],
 enLog:["The month handles refining rhythm and does not replace the natal, year or decade.","The solar terms and month-setting rules must be declared first, since different methods change the starting point.","The monthly Life Palace and transformations bring the yearly theme into the current month.","Monthly judgment should land on observable tasks and feedback, with one focus per month."],
 cnStep:['先确认大限和流年的背景主题','明确流月采用的节气和起月规则','定位当月流月命宫落在哪','看当月流月四化，找触发点','把年度主题翻译成当月一个重点和可观察任务','按签约、考试、搬家这类行动窗口，安排当月节奏并复盘反馈'],
 enStep:["First confirm the background themes of the decade and year","Declare the solar terms and month-setting rules used","Locate where the current monthly Life Palace lands","Read that month's transformations to find triggers","Translate the yearly theme into one focus and observable task for the month","Arrange the monthly rhythm around action windows such as signing, exams and moving, then review feedback"],
 cnMis:['把流月当独立新盘，每月另起吉凶','顺序搞反，没看年度背景就追当月','月度判断停在抽象运势，不落到可观察任务'],
 enMis:["Treating the month as an independent chart with fresh fortune each month","Reversing order and chasing the month without the yearly background","Leaving monthly judgment in abstract fortune without observable tasks"],
 cnClose:'流月是节奏工具，不是命运开关。先看年度大势，再找当月触发，每月只抓一个重点，你对「什么时候动手」会有清晰得多的判断。',
 enClose:"The month is a rhythm tool, not a switch of fate. Read the yearly trend first, find the month trigger, and keep one focus each month for a much clearer sense of when to act."},

{cat:'liunian',slug:'ziwei-liunian-sanpan-bimian-dangong',focus:'流年三盘叠看避免单宫',focusEn:'stacking three charts in the year to avoid one-palace reading',
 cnT:'流年命宫三盘叠看：如何避免只看今年一宫',enT:'The Yearly Life Palace in Three Stacked Charts: How to Avoid Reading Only This Year Palace',
 cnD:'流年是叠在本命底盘上的年度环境，本命、大限、流年三盘要同时看；流年不替换本命，年份关键词要由落宫和四化共同验证。',
 enD:"The year is an annual environment layered on the natal foundation, and the natal, decade and year must be read together. The year does not replace the natal; yearly keywords are verified by both the landing palace and transformations.",
 cnL:'「今年流年命宫坐这个星，是不是就怎样」——只看这一宫，结论一定飘。今年的你站在本命和大限的肩膀上，三张盘不叠，就看不到今年这件事的根。',
 enL:"If the yearly Life Palace holds this star, does that settle it? Reading only that palace makes the conclusion drift. This year you stand on the shoulders of the natal and decade; without stacking three charts, you miss the root.",
 cnA:'要纠的偏是「流年一宫定全年」。流年只是环境层，它不会抹掉本命结构。真正该做的是确认同一宫位在本命、大限、流年各扮演什么角色，再让落宫和四化一起验证。',
 enA:"What must be corrected is one palace settling the whole year. The year is only an environment and does not erase the natal structure. Confirm what role the same palace plays in the natal, decade and year, then let the landing palace and transformations verify together.",
 cnLog:['流年是环境层，不会抹掉本命结构。','本命、大限、流年三盘叠看，确认同一宫位在不同层的角色。','年份关键词必须由落宫和四化共同验证，缺一不可。','示例只说明方法，不构成对个人的年度预测。'],
 enLog:["The year is an environment layer and does not erase the natal structure.","Stack the natal, decade and year to confirm the same palace's role in each layer.","Yearly keywords must be verified by both the landing palace and transformations, neither alone sufficient.","Examples only demonstrate method and do not constitute a personal yearly forecast."],
 cnStep:['先读本命盘，定该宫位的先天角色','再读大限，定该宫位在十年里的角色','然后读流年，定今年加在上面的环境','确认同一宫位在三层里是同向还是冲突','用流年落宫和四化共同验证今年的关键词','以换工作为例，做一张三盘核对表：资源、责任、时间窗口'],
 enStep:["First read the natal to set the palace's innate role","Then read the decade to set its role across the ten years","Then read the year to set the environment added this year","Confirm whether the same palace aligns or conflicts across the three layers","Use the yearly landing palace and transformations together to verify this year's keywords","Using a job change as an example, make a three-chart checklist: resources, responsibility and timing window"],
 cnMis:['只看流年命宫一宫，就给全年下断语','把流年当替换本命的新盘','年份关键词只看落宫或只看四化，少验证一半'],
 enMis:["Judging the whole year from the yearly Life Palace alone","Treating the year as a new chart replacing the natal","Verifying yearly keywords by only the palace or only the transformations, missing half the check"],
 cnClose:'今年的故事，永远长在本命和大限的土壤里。学会三盘叠看、双重验证，你就不会被一个流年宫位的吉凶牵着走。',
 enClose:"This year's story always grows in the soil of the natal and decade. Learn to stack three charts and verify twice, and you will not be led by the fortune of one yearly palace."}
];
