// 2026-09-25 调研驱动 第5组：感情4 + 宫位3 + FAQ2 = 9篇
module.exports=[
// ========== 感情 4 ==========
{cat:'ganqing',slug:'ziwei-fuqi-fude-qianyi-guanxi-moshi',focus:'夫妻福德迁移的关系模式',focusEn:'the relationship pattern across Spouse, Karma and Travel',
 cnT:'夫妻宫、福德宫、迁移宫如何一起读关系模式',enT:'How to Read the Spouse, Karma and Travel Palaces Together for a Relationship Pattern',
 cnD:'夫妻宫写相处，福德宫写你内在的情感需求，迁移宫写外部相处场景；三宫合读才看得清一段关系是怎么运作的。',
 enD:"The Spouse Palace writes how you relate, Karma your inner emotional needs, and Travel the external scenes of relating. Reading the three shows how a relationship actually operates.",
 cnL:'只看夫妻宫，就像只看了两个人站在一起的样子。你们内心各自期待什么、在什么场景下容易出问题，答案在福德和迁移里，三宫连起来才是完整的关系。',
 enL:"Looking only at the Spouse Palace is like seeing two people stand together. What each expects inside and in which scenes things go wrong lie in Karma and Travel; the three connected form the full relationship.",
 cnA:'吵架后到底看哪一宫？这是最实在的问法。冲突本身看夫妻宫，但为什么会吵、是期待落差还是场景压力，要回到福德和迁移，分开才看得清。',
 enA:"After a fight, which palace do you check, the most practical question. The conflict itself is in Spouse, but why you fight, whether expectation gap or scene pressure, returns to Karma and Travel, separated to be clear.",
 cnLog:['夫妻宫写两个人表面的相处模式和吸引。','福德宫写你内在的情感需求和满足方式。','迁移宫写外部环境，如异地、社交和公开场合的相处。','三宫联动才能解释关系如何运作，单宫只给片段。'],
 enLog:["The Spouse Palace writes the surface pattern of relating and attraction.","The Karma Palace writes inner emotional needs and how they are met.","The Travel Palace writes the external environment, such as distance, social life and public relating.","The three linked explain how the relationship operates; one palace gives only a fragment."],
 cnStep:['先定夫妻宫主星，看相处模式','再定福德宫主星，看你内在的情感需求','然后定迁移宫主星，看外部相处场景','用同居、异地、公开关系三个案例分别对照','找三宫落差，识别冲突是期待问题还是场景问题','结合大限，看关系在哪个阶段面临什么课题'],
 enStep:["First set the Spouse Palace star for the relating pattern","Then set the Karma Palace star for your inner emotional needs","Then set the Travel Palace star for external relating scenes","Compare against the three cases of cohabiting, long distance and public relationship","Find the gaps among the three to identify whether conflict is expectation or scene","Use the decade to see what topic the relationship faces in each stage"],
 cnMis:['只盯夫妻宫，忽略内在需求和外部场景','把冲突一概而论，不分期待还是场景压力','三宫不连起来，读不到关系的运作方式'],
 enMis:["Fixating on Spouse and ignoring inner needs and external scenes","Generalizing all conflict without separating expectation from scene pressure","Not connecting the three and missing how the relationship operates"],
 cnClose:'关系是两个人在内心期待和现实场景里的持续互动。学会三宫合读，你才看得懂你们为什么好、为什么吵，而不是只盯着一个「合不合」的标签。',
 enClose:"A relationship is two people interacting across inner expectations and real scenes. Learn to read the three palaces together and you understand why you get along and fight rather than fixing on a compatible label."},

{cat:'ganqing',slug:'ziwei-fudegong-kan-banlv-neizai-qidai',focus:'福德宫看伴侣的内在期待',focusEn:'using the Karma Palace to see a partner and inner expectations',
 cnT:'福德宫看伴侣：内在期待如何影响相处和婚姻趋势',enT:'Seeing a Partner Through the Karma Palace: How Inner Expectations Shape Relating and Marriage Trends',
 cnD:'福德宫观察精神需求和潜在的择偶标准，要与夫妻宫、迁移宫联动；关系冲突常来自期待与现实互动的落差，而非简单的好坏。',
 enD:"The Karma Palace observes emotional needs and hidden partner criteria, linked with Spouse and Travel. Relationship conflict often comes from the gap between expectations and real interaction rather than simple good or bad.",
 cnL:'「我到底想找什么样的人」——这个答案往往不在你嘴上，而在福德宫。它写的是你内心深处觉得怎样才算被爱、被懂，这个标准会悄悄筛掉很多人。',
 enL:"What kind of person am I really looking for is often answered not by what you say but by the Karma Palace. It writes what you deep down feel it means to be loved and understood, a standard that quietly filters many people.",
 cnA:'关系里最隐蔽的冲突，是期待和现实对不上。福德宫给的是内在剧本，夫妻宫给的是实际相处，两厢一对照，才知道矛盾是期待问题还是分工问题。',
 enA:"The most hidden conflict is expectation not matching reality. Karma gives the inner script and Spouse the actual relating; comparing them shows whether friction is expectation or division of labor.",
 cnLog:['福德宫补充内在需求，不取代夫妻宫。','它写精神满足方式和潜在择偶标准。','期待与现实互动的落差，是关系问题的关键。','迁移宫补充外部环境，三宫合读才完整，且只作倾向不作保证。'],
 enLog:["The Karma Palace supplements inner needs and does not replace Spouse.","It writes how emotional fulfillment works and hidden partner criteria.","The gap between expectations and real interaction is the key to relationship issues.","Travel supplements the external environment; the three together are complete and only give tendencies, not guarantees."],
 cnStep:['先定福德宫主星，看内在情感需求','把它翻译成你对伴侣的具体期待','再看夫妻宫，定实际相处模式','对照期待和现实，找出落差','用同居和育儿案例，判断是期待问题还是分工问题','结合迁移宫看外部场景，再调整期待或沟通方式'],
 enStep:["First set the Karma Palace star for inner emotional needs","Translate it into concrete expectations of a partner","Then read Spouse for the actual relating pattern","Compare expectations with reality to find the gap","Using cohabiting and parenting cases, judge whether it is expectation or division of labor","Use Travel for external scenes, then adjust expectations or communication"],
 cnMis:['只看夫妻宫，不读内在期待','把关系问题全归为性格不合，忽略期待落差','期待定得太死，不随现实相处调整'],
 enMis:["Reading only Spouse and not inner expectations","Blaming all issues on incompatible personalities and ignoring expectation gaps","Holding expectations rigidly without adjusting to real relating"],
 cnClose:'福德宫让你看见自己在关系里的「内心剧本」。读懂期待、对照现实，再去沟通和调整，很多看似无解的矛盾其实有了出路。',
 enClose:"The Karma Palace lets you see your inner script in a relationship. Read expectations, compare with reality, then communicate and adjust, and many seemingly hopeless conflicts gain a way out."},

{cat:'ganqing',slug:'ziwei-fuqigong-buhao-hunyin-chai',focus:'夫妻宫不好与婚姻',focusEn:'a difficult Spouse Palace and marriage',
 cnT:'夫妻宫不好是不是婚姻一定差：先看关系如何运作',enT:'Does a Difficult Spouse Palace Mean a Bad Marriage? First See How the Relationship Operates',
 cnD:'夫妻宫的压力不等于婚姻失败，它可能推动关系成长；关系质量还要看命身主见、福德反省和官禄能否承接精力。',
 enD:"Pressure in the Spouse Palace does not equal a failed marriage and may push growth. Relationship quality also depends on the Life and Body resolve, Karma reflection and whether Career can carry the energy.",
 cnL:'「我夫妻宫看起来不好，是不是注定婚姻差」——先别急着认命。宫位有压力，只说明这段关系要花更多心思去经营，它考验的是两个人怎么一起面对，而不是提前判输赢。',
 enL:"My Spouse Palace looks bad, is my marriage doomed, do not resign yourself yet. Pressure only means the relationship needs more care; it tests how two people face things together rather than judging the outcome early.",
 cnA:'这个问题要破的是「单宫定终身」。夫妻宫再紧，也要看你本人有没有主见、福德会不会反省、事业能不能承接多余精力，这些共同决定关系走向。',
 enA:"What must be broken is one palace settling a lifetime. However tight Spouse is, also see whether you have resolve, whether Karma reflects and whether Career absorbs extra energy; together these decide the direction.",
 cnLog:['夫妻宫的压力不等于婚姻失败。','关系质量还要看命身、福德和现实分工。','压力有时反而是成长和磨合的契机。','单宫吉凶不能当结果，要回到完整盘和现实经营。'],
 enLog:["Pressure in the Spouse Palace does not equal marriage failure.","Relationship quality also depends on Life, Body, Karma and real division of labor.","Pressure is sometimes the very chance for growth and磨合.","One palace's fortune cannot be the result; return to the full chart and real effort."],
 cnStep:['先看夫妻宫具体是哪颗星、什么性质的压力','再看命身宫，确认自己有没有主见和承接力','看福德宫，判断是否愿意反省和调整','看官禄宫，看精力有没有别的出口','把压力翻译成具体课题：沟通、信任还是分工','结合现实经营和大限，给关系成长的时间，不提前放弃'],
 enStep:["First see which star is in Spouse and what kind of pressure it is","Then read Life and Body to confirm your own resolve and carrying capacity","Read Karma to judge whether you are willing to reflect and adjust","Read Career to see whether energy has another outlet","Translate the pressure into a concrete topic: communication, trust or division of labor","Give the relationship time to grow through real effort and the decade rather than giving up early"],
 cnMis:['夫妻宫一紧就断定婚姻必败','只看一宫，不看命身福德官禄的承接','把压力当终点而不是课题，提前放弃'],
 enMis:["Declaring marriage doomed as soon as Spouse is tight","Reading one palace without the carrying capacity of Life, Body, Karma and Career","Taking pressure as an ending rather than a topic and giving up early"],
 cnClose:'夫妻宫写的是关系要面对的功课，不是婚姻的判决书。看清压力、盘点承接、认真经营，再紧的宫位也可能磨出更扎实的感情。',
 enClose:"The Spouse Palace writes the work a relationship faces, not a marriage verdict. See the pressure, inventory support and earnestly work, and even a tight palace can forge a more solid bond."},

{cat:'ganqing',slug:'ziwei-fuqigong-huaji-goutong',focus:'夫妻宫化忌与沟通',focusEn:'Ji in the Spouse Palace and communication',
 cnT:'夫妻宫化忌怎么读：核心是沟通课题，不是感情完蛋',enT:'How to Read Ji in the Spouse Palace: The Core Is a Communication Topic, Not a Ruined Relationship',
 cnD:'夫妻宫化忌主在关系里容易牵挂、较真和卡住，最常表现为沟通问题；解法是降低预期、明确表达、建立边界，而非认定感情失败。',
 enD:"Ji in Spouse shows a tendency to worry, take things personally and get stuck in the relationship, most often as communication problems. The answer is lowering expectations, clear expression and boundaries rather than assuming failure.",
 cnL:'夫妻宫化忌的人，往往在感情里最用心也最容易受伤——一句话能琢磨半天，越在意越容易把天聊死。这不是不爱，而是沟通方式需要重新学。',
 enL:"People with Ji in Spouse often care most and hurt easiest in relationships, turning one sentence over for hours; the more they care, the more conversations deadlock. This is not lack of love but communication to relearn.",
 cnA:'要把「化忌=感情完蛋」的标签撕掉。它真正指出的是你在关系里哪里容易卡住——多半是没说清、想太多、边界模糊，对症去练，关系反而更深。',
 enA:"Remove the label Ji equals ruined love. It points to where you get stuck, mostly unclear speech, overthinking or blurred boundaries; practice accordingly and the relationship deepens.",
 cnLog:['化忌在夫妻宫主牵挂、较真和持续处理的沟通课题。','它不直接等于感情失败，处理好了是更深的在意。','常见卡点是表达不清、反复琢磨和边界模糊。','解法是降低预期、明确表达、建立边界，并给关系时间。'],
 enLog:["Ji in Spouse governs concern, taking things personally and communication topics needing ongoing work.","It does not directly equal relationship failure; handled well it becomes deeper care.","Common blocks are unclear expression, repeated overthinking and blurred boundaries.","The answer is lowering expectations, clear expression, boundaries and giving the relationship time."],
 cnStep:['先确认夫妻宫化忌作用的是哪颗星','识别自己在沟通里的具体卡点','把没说清的需求改成直接、具体的表达','降低对伴侣「应该懂我」的预期','建立清晰的相处边界，不把小事放大','结合福德反省沟通模式，在大限里持续练习'],
 enStep:["First confirm which star the Spouse Ji acts on","Identify your concrete block in communication","Turn unclear needs into direct and specific expression","Lower the expectation that a partner should simply understand","Build clear relating boundaries without magnifying small matters","Use Karma to reflect on communication patterns and keep practicing through the decade"],
 cnMis:['把夫妻宫化忌直接当感情失败','只在心里琢磨，不做明确表达','不设边界、不降预期，反复在同一处卡住'],
 enMis:["Taking Spouse Ji directly as relationship failure","Only turning things over in the mind without clear expression","Skipping boundaries and expectation lowering and getting stuck in the same place"],
 cnClose:'夫妻宫化忌是一张「沟通必修课」的通知，不是感情的坏牌。学会直说、降预期、立边界，你会发现最在意的关系也能越处越顺。',
 enClose:"Spouse Ji is notice of a required communication course, not a bad card for love. Learn direct speech, lower expectations and set boundaries, and the relationship you care most about can grow smoother."},

// ========== 宫位 3 ==========
{cat:'gongwei',slug:'ziwei-tianzhai-qianyi-maifang-banjia',focus:'田宅迁移与买房搬家',focusEn:'Property and Travel palaces for buying and moving',
 cnT:'田宅宫与迁移宫联读：买房、搬家与居住稳定感',enT:'Reading the Property and Travel Palaces Together: Buying, Moving and the Sense of Settling',
 cnD:'田宅宫看居住与资产承接，不直接等于房产数量；迁移宫补充搬迁动机，买房还要加入财帛和现金流，租房买房异地住分别看。',
 enD:"The Property Palace covers living and asset reception, not directly the number of properties; Travel adds moving motives, and buying also needs Wealth and cash flow. Read renting, buying and relocating separately.",
 cnL:'「我到底该买房还是继续租、要不要换个城市」——这类问题不能只看田宅。田宅写你和家的关系，迁移写你想往外走的冲动，两厢拉扯，就是居住选择的真相。',
 enL:"Should I buy or keep renting, should I change cities cannot be read from Property alone. Property writes your bond with home and Travel the urge to go out; their tension is the truth of housing choices.",
 cnA:'田宅有星不等于一定买房，迁移动也不代表必须搬家。真正的判断要把预算、通勤、现金流和家庭责任都加进来，命理只提示倾向，不预测房价和时点。',
 enA:"Stars in Property do not guarantee a purchase, and active Travel does not force a move. Real judgment adds budget, commute, cash flow and family responsibility; fortune reading only suggests tendencies, not prices or timing.",
 cnLog:['田宅宫先看居住与资产承接，不直接等于房产数量。','迁移宫补充外部环境与搬迁动机。','买房判断需加入财帛宫、现金流和家庭责任。','不能据此预测房价或买卖时点，租房买房异地住分开看。'],
 enLog:["The Property Palace first covers living and asset reception, not the number of properties.","The Travel Palace supplements the external environment and moving motives.","Buying requires the Wealth Palace, cash flow and family responsibility.","It cannot predict house prices or timing; renting, buying and relocating are read separately."],
 cnStep:['先定田宅宫主星，看居住和资产倾向','再定迁移宫主星，看搬迁和外部动机','分清问题是租房、买房还是异地住','买房，加入预算、首付和现金流测算','租房或异地，看通勤和工作流动性','结合家庭责任做决定，不把命理当房价预测'],
 enStep:["First set the Property Palace star for living and asset tendencies","Then set the Travel Palace star for moving and outside motives","Separate the question into renting, buying or relocating","For buying, add budget, down payment and cash-flow calculations","For renting or relocating, look at commute and work mobility","Decide with family responsibility without treating fortune reading as price prediction"],
 cnMis:['田宅有星就断定一定买房','只看宫位，不加预算现金流等现实变量','用命理预测房价和最佳买卖时点'],
 enMis:["Assuming stars in Property guarantee a purchase","Looking only at palaces without budget and cash flow","Using fortune reading to predict house prices and timing"],
 cnClose:'居住选择是「想要的稳定」和「现实的条件」之间的平衡。田宅迁移合读看清倾向，再用预算和现金流落地，住哪里才真正适合你。',
 enClose:"Housing choices balance desired stability against real conditions. Read Property and Travel for tendencies, then ground them with budget and cash flow so where you live truly suits you."},

{cat:'gongwei',slug:'ziwei-jiaoyougong-kehu-xiashu',focus:'交友宫的客户与下属',focusEn:'clients and subordinates in the Friends Palace',
 cnT:'交友宫怎么看客户和下属：不只是朋友关系',enT:'How to Read Clients and Subordinates in the Friends Palace: It Is Not Only Friendship',
 cnD:'交友宫（奴仆宫）写你与下属、客户、平辈合作者的相处模式；看主星可知是得助力还是耗精力，煞忌重则带团队、谈客户更费力。',
 enD:"The Friends Palace, historically the Servants Palace, writes how you relate to subordinates, clients and peer collaborators. The major star shows whether you gain support or spend energy; heavy malefics make leading and selling harder.",
 cnL:'很多人以为交友宫只管朋友，其实它管的是所有「你要打交道、却不能完全说了算」的人——下属、客户、供应商，这些关系最考验一个人的协调能力。',
 enL:"Many think the Friends Palace only covers friends, but it covers everyone you deal with yet cannot fully command: subordinates, clients and suppliers, the relationships that test coordination most.",
 cnA:'为什么有人带团队特别累、谈客户总吃亏？答案常写在交友宫。看懂它，才知道自己在这类关系里是容易得人助，还是容易被拖累，再对症调整管理和合作方式。',
 enA:"Why do some find leading teams exhausting and lose out with clients? The answer is often in Friends. Read it to know whether you gain help or get drained in these relationships, then adjust how you manage and cooperate.",
 cnLog:['交友宫古称奴仆宫，主下属、客户和平辈合作者。','主星性质决定是得助力还是耗精力。','煞星化忌重，带团队和谈客户更易摩擦。','结合事业宫看，能判断管理和业务协作的整体状态。'],
 enLog:["The Friends Palace, anciently the Servants Palace, governs subordinates, clients and peer collaborators.","The major star decides whether you gain support or spend energy.","Heavy malefics and Ji make leading teams and dealing with clients more friction-prone.","Read with the Career Palace to judge the overall state of management and business cooperation."],
 cnStep:['先定交友宫主星和亮度','把它翻译成你和下属客户的相处模式','看吉星，判断是否易得人相助','看煞忌，识别摩擦和被拖累的风险','结合事业宫，看团队和业务协作状态','据此调整管理方式和客户合作边界'],
 enStep:["First set the Friends Palace major star and brightness","Translate it into how you relate to subordinates and clients","Read auspicious stars to see whether help comes easily","Read malefics and Ji to identify friction and draining risk","Combine with the Career Palace for team and business cooperation","Adjust management style and client cooperation boundaries accordingly"],
 cnMis:['把交友宫窄化成只看朋友','只看主星，不看煞忌带来的团队摩擦','带团队累却不调整管理方式，空叹人缘差'],
 enMis:["Narrowing the Friends Palace to only friends","Looking only at the major star and not team friction from malefics","Being exhausted leading yet not adjusting management and sighing over poor relations"],
 cnClose:'交友宫是一面照出你「协作能力」的镜子。看清和下属客户的助力与摩擦，再调整管理和边界，事业里最累的那部分往往能松下来。',
 enClose:"The Friends Palace mirrors your ability to collaborate. See the support and friction with subordinates and clients, then adjust management and boundaries, and the most tiring part of work often eases."},

{cat:'gongwei',slug:'ziwei-qianyigong-yuancheng-pingtai-liuliang',focus:'迁移宫的远程平台与流量',focusEn:'remote work, platforms and traffic in the Travel Palace',
 cnT:'迁移宫不只看出远门：远程工作和线上流量也归它管',enT:'The Travel Palace Is Not Only Travel: It Also Governs Remote Work and Online Traffic',
 cnD:'迁移宫写外部环境和对外打交道的方式，在今天对应异地发展、远程办公、线上获客和个人流量；主星可知你在外部舞台是如鱼得水还是消耗。',
 enD:"The Travel Palace writes the external environment and how you deal with the outside, corresponding today to relocating, remote work, online acquisition and personal traffic. The star shows whether you thrive or drain on the outer stage.",
 cnL:'古人安迁移宫，看的是出门在外的际遇。换到今天，「外面」不只是地理上的远方，还包括你在线上平台、远程协作、陌生客户面前的表现，这是一个被低估的宫位。',
 enL:"The ancients set the Travel Palace for fortune away from home. Today the outside is not only geographic distance but how you show on platforms, in remote collaboration and before unfamiliar clients, an underrated palace.",
 cnA:'为什么有人一到线上、一面对陌生市场就特别来劲，有人却只想守着熟悉的小圈子？答案在迁移宫。看懂它，才知道自己适不适合做远程、做 IP、做对外的生意。',
 enA:"Why do some come alive online and before unfamiliar markets while others prefer a familiar circle? The answer is in Travel. Read it to know whether remote work, building a personal brand or outward-facing business suits you.",
 cnLog:['迁移宫写外部环境和对外打交道的方式。','现代对应异地发展、远程办公、线上获客和流量。','主星强弱决定在外部舞台是得机遇还是耗精力。','要与命宫、事业宫合读，判断内外舞台哪个更适合。'],
 enLog:["The Travel Palace writes the external environment and how you deal with the outside.","Modern equivalents are relocating, remote work, online acquisition and traffic.","The star's strength decides whether the outer stage brings opportunity or drains energy.","Read it with Life and Career to judge which stage, inner or outer, fits better."],
 cnStep:['先定迁移宫主星和亮度','理解它对应外部和线上舞台','看吉星，判断对外是否易得机会','看煞忌，识别在外和线上的消耗','结合命宫和事业宫，比较内外舞台','据此决定是否发展远程、线上获客或个人品牌'],
 enStep:["First set the Travel Palace star and brightness","Understand it corresponds to the outer and online stage","Read auspicious stars to see whether outside chances come easily","Read malefics to identify draining away from home and online","Combine with Life and Career to compare inner and outer stages","Decide whether to develop remote work, online acquisition or a personal brand accordingly"],
 cnMis:['把迁移宫窄化成就看出差旅行','忽略线上和远程这层现代含义','只看迁移不看命宫事业，判断不了哪个舞台更合适'],
 enMis:["Narrowing Travel to only business trips","Ignoring the modern layer of online and remote work","Reading Travel without Life and Career and unable to judge which stage fits"],
 cnClose:'迁移宫讲的是你在「外面世界」的生存方式。把异地、远程、线上流量都纳入读法，再对照命宫事业，你会更清楚自己的舞台到底在哪。',
 enClose:"The Travel Palace describes how you operate in the outside world. Include relocation, remote work and online traffic, then compare with Life and Career to see more clearly where your stage truly is."},

// ========== FAQ 2 ==========
{cat:'faq',slug:'ziwei-liuri-liushi-yuexi-yuezhun',focus:'流日流时是否越细越准',focusEn:'whether finer daily and hourly charts are more accurate',
 cnT:'流日流时是不是越细越准：先看出生时间误差',enT:'Are Daily and Hourly Charts More Accurate When Finer? First Check Birth-Time Error',
 cnD:'从流年细分到流日流时，信息量不等于准确度，出生几分钟的误差会在细层被放大；应先稳本命和流年，再按需下钻，且带着明确问题。',
 enD:"Subdividing from years to days and hours adds information, not accuracy, since a few minutes of birth-time error gets magnified at fine levels. Stabilize the natal and yearly reading first, then drill down only as needed with a clear question.",
 cnL:'「能不能帮我精确到哪天、哪个时辰」——这是很多人心里的期待。但盘的准确度有个天花板，出生时间本身若有误差，越往细处看，偏差被放得越大。',
 enL:"Can you pinpoint the day and hour is what many hope for, but accuracy has a ceiling. If the birth time itself is uncertain, the finer you look, the more the deviation is magnified.",
 cnA:'这个问题要建立「层级边界」。本命和大限还没读稳，就追流日流时，等于地基没打牢就去装修。细分只在回答具体问题、且定盘准确时才有意义。',
 enA:"This establishes a layer boundary. Chasing days and hours before the natal and decade are stable is decorating before the foundation. Finer reading matters only for a concrete question and an accurately set chart.",
 cnLog:['流日流时更细，也更容易放大定盘误差。','层级越细越需要明确问题和可验证事件。','本命与大限尚未稳定时，不宜直接追流时。','细分是工具而非默认，考试签约搬家等具体事才值得下钻。'],
 enLog:["Daily and hourly charts are finer but magnify chart-setting error more easily.","The finer the level, the more a clear question and verifiable event are needed.","When the natal and decade are not yet stable, chasing hours is inappropriate.","Subdividing is a tool, not the default; concrete matters like exams and signing are worth drilling into."],
 cnStep:['先确认出生时间是否准确、有没有定盘','把本命盘和大限先读稳','再看流年，确认年度趋势','只在有具体问题时才考虑流月以下','用考试、签约、搬家这类可验证事件检验细分','不把细分当默认，避免在误差上堆精度'],
 enStep:["First confirm whether the birth time is accurate and the chart set","Read the natal and decade steadily first","Then read the year to confirm the trend","Consider below the month only with a concrete question","Use verifiable events such as exams, signing and moving to test finer reading","Do not treat subdividing as default, avoiding precision piled on error"],
 cnMis:['默认越细越准，忽略定盘误差','本命没读稳就追流日流时','为了细分而细分，没有明确可验证的问题'],
 enMis:["Assuming finer means more accurate and ignoring chart-setting error","Chasing days and hours before the natal is stable","Subdividing for its own sake without a clear verifiable question"],
 cnClose:'准确度不是靠无限细分换来的，而是靠先稳底盘、再按需下钻。守住层级边界，紫微给你的信息才不会「看起来很精，其实不准」。',
 enClose:"Accuracy is not bought by endless subdividing but by stabilizing the foundation first and drilling down as needed. Hold the layer boundary so the information does not look precise while being unreliable."},

{cat:'faq',slug:'ziwei-liuyue-sihua-hetong-qianyue',focus:'流月四化与合同签约',focusEn:'monthly transformations and contract signing',
 cnT:'流月四化怎么用来看签约时机',enT:'How to Use Monthly Transformations to Time a Contract Signing',
 cnD:'签约时机先看流年大背景，再用流月四化找当月窗口；化禄化科利文书曝光，化忌化权则要反复核对条款，最终以合同和律师审核为准。',
 enD:"For signing, first read the yearly background, then use monthly transformations to find that month's window. Lu and Ke favor documents and exposure, while Ji and Quan call for repeated checks; the contract and lawyer review remain the standard.",
 cnL:'「这个合同哪个月签比较好」——这是流月最实用的用法之一。但它不是让你挑个黄道吉日，而是看懂年度大势后，在合适的月份把该谈的条款谈扎实。',
 enL:"Which month is better to sign is one of the most practical uses of the monthly layer. It is not picking an auspicious date but, after understanding the yearly trend, solidifying terms in the right month.",
 cnA:'要避免两种误用：一是脱离年度背景只看流月，二是把流月吉相当成条款不用审的理由。命理只提示节奏，白纸黑字和专业审核才真正保护你。',
 enA:"Avoid two misuses: reading the month detached from the yearly background and taking a good month as reason not to review terms. Fortune reading only suggests rhythm; the written contract and professional review truly protect you.",
 cnLog:['流月负责把年度主题细分到当月节奏。','化禄、化科利文书、合作和曝光。','化权、化忌则提示条款要反复核对、注意边界。','法律事项以合同文本和专业律师审核为准，命理不定输赢。'],
 enLog:["The month subdivides the yearly theme into monthly rhythm.","Lu and Ke favor documents, cooperation and exposure.","Quan and Ji indicate terms need repeated checks and attention to boundaries.","Legal matters follow the contract text and professional lawyer review; fortune reading does not decide outcomes."],
 cnStep:['先看流年和大限，定签约的大背景','再定位相关月份的流月命宫和四化','化禄化科的月份，利推进文书和合作','化权化忌的月份，重点核对条款和责任','把签约、违约、退出条款逐项谈清','请专业律师审核后再签，不凭流月定夺'],
 enStep:["First read the year and decade to set the signing background","Then locate the relevant month's Life Palace and transformations","Months with Lu and Ke favor advancing documents and cooperation","Months with Quan and Ji call for checking terms and responsibilities","Clarify signing, breach and exit clauses item by item","Have a professional lawyer review before signing rather than deciding by the month"],
 cnMis:['只看流月挑日子，脱离年度背景','流月一吉就不审合同条款','把命理当法律依据，忽略专业审核'],
 enMis:["Picking a date by the month alone, detached from the yearly background","Skipping contract review when the month looks good","Taking fortune reading as legal basis and ignoring professional review"],
 cnClose:'流月四化是帮你安排节奏的工具，不是合同的护身符。年度看清、当月选准、条款谈实、律师把关，签约这件事才真正稳妥。',
 enClose:"Monthly transformations are a tool to arrange rhythm, not a shield for a contract. Read the year, choose the month, solidify terms and use lawyer review so signing is genuinely secure."}
];
