// 2026-09-25 调研驱动 第1组：入门看盘4 + 四化5 = 9篇
// 观点框架来自当日同行研究卡，正文原创改写，无来源痕迹。
module.exports=[
// ========== 入门看盘 4 ==========
{cat:'rumen',slug:'ziwei-mingshen-liangong-hedu-buzou',focus:'命宫与身宫',focusEn:'the Life and Body palaces',
 cnT:'紫微斗数命宫身宫怎么合读：身宫不是第十三宫',enT:'How to Read the Life and Body Palaces Together in Zi Wei Dou Shu',
 cnD:'身宫不单独占宫，而是寄入命、夫妻、财帛、迁移、官禄、福德六宫之一；命身合读要先确认寄在哪一宫，再连同三方四正一起看。',
 enD:"The Body Palace never stands alone. It attaches to one of six palaces, so read it only after confirming where it lands and opening the full triple-direction.",
 cnL:'很多人看到盘上除了命宫还有个身宫，就以为多出一个宫位，其实身宫是寄宫——它像一个后天重心的标记，告诉你三十五岁后精力往哪件事上靠。',
 enL:"Many people see a Body Palace beside the Life Palace and assume a thirteenth position. It is actually an attached marker showing where your focus shifts later in life.",
 cnA:'初学者最常问的是「命宫和身宫到底听谁的」。这个问题本身就偏了——两宫不是各说各话，而是一个偏先天底色、一个偏后天养成，要叠在同一张结构上读。',
 enA:"Beginners ask which palace takes priority, but the question itself is off. The two do not compete; one is the innate baseline and the other is acquired direction, layered on one structure.",
 cnLog:['命宫由生月生时安出，写的是天生的性格与起点；身宫同样寄于十二宫，写的是阅历累积后你越活越靠近的方向。','身宫只寄命、夫妻、财帛、迁移、官禄、福德六处，寄在哪一宫，人生后段就越被那件事牵引。','命身同宫的人前后较一致；命身分离的人，往往年轻时和中年后像两个人，反差来自后天补课。','无论命宫还是身宫，都不能脱离三方四正和四化单独断，寄宫位置只提示重心，不直接等于职业或婚姻结果。'],
 enLog:["The Life Palace is set by birth month and hour and shows innate temperament; the Body Palace shows where accumulated experience pulls you over time.","It attaches only to Life, Spouse, Wealth, Travel, Career or Karma, and whichever it joins draws your later years.","When the two share a palace you stay consistent; when they differ, you often seem like two people at different ages because life is filling a gap.","Neither palace can be read apart from the triple-direction and transformations; the attached position only signals focus, never a fixed career or marriage outcome."],
 cnStep:['先用农历生月生时排好命宫，确认先天主星和亮度','再找身宫，确认它寄在六个宫位中的哪一个','把命宫与身宫所在位置连线，看先天和后天是同向还是错位','若同向，说明你越活越顺本性；若错位，看后天在补哪一块','把两宫各自的三方四正、辅煞、四化分别列清楚，算净效果','结合大限确认身宫在哪个年龄段被引动，再下结论，而不是命身各断一条'],
 enStep:["Cast the Life Palace from the lunar birth month and hour, then check the natal major star and its brightness","Locate the Body Palace and confirm which of the six positions it attaches to","Connect the two positions to see whether innate and acquired align or diverge","Alignment means you grow into your nature; divergence shows which gap life is training you to fill","List each position's triple-direction, assistant and malefic stars, and transformations for the net effect","Use the decade limit to see when the Body Palace activates before concluding, rather than reading two separate fates"],
 cnMis:['把身宫当成独立的第十三宫，另起一套解读','只看命宫不管身宫，解释不了人随年龄的明显变化','看到身宫寄官禄就直接断「一定做大官」，忽略了三方四正和现实条件'],
 enMis:["Treating the Body Palace as an independent thirteenth position with its own reading","Reading only the Life Palace and being unable to explain change with age","Assuming attachment to the Career Palace guarantees high office while ignoring the triple-direction and real conditions"],
 cnClose:'命身合读的意义，是让你看到一个人不是被出生那一刻定死的——先天给底色，后天的选择和阅历会一点点把重心改写。',
 enClose:"Reading the two together shows that no one is fixed at birth. Innate temperament sets the baseline, while later choices gradually rewrite where your center of gravity sits."},

{cat:'kanpan',slug:'ziwei-jiepai-liubu-zhengque-shunxu',focus:'解盘顺序',focusEn:'the chart-reading sequence',
 cnT:'紫微斗数解盘正确顺序：六步把一张盘读通',enT:'The Correct Six-Step Sequence for Reading a Zi Wei Dou Shu Chart',
 cnD:'解盘要先静后动：先定命宫与三方四正的静态结构，再叠生年四化、格局，最后加大限流年，顺序错了结论就容易偏。',
 enD:"Read a chart from static to dynamic: first the Life Palace and triple-direction, then natal transformations and patterns, and finally the decade and year. Wrong order skews the conclusion.",
 cnL:'新手拿到盘容易东看一颗星、西看一个宫，越看越乱。其实读盘有固定顺序，像剥洋葱——先底盘，再结构，再时间，一层一层来。',
 enL:"Beginners glance at one star here and one palace there and end up confused. Reading follows a fixed order, like peeling an onion: foundation, structure, then timing, layer by layer.",
 cnA:'很多人一上来就问「我今年会不会结婚」，却连命宫主星、三方四正都没定。问题不是不能问未来，而是未来必须有本命底盘承接，否则就是空中楼阁。',
 enA:"People immediately ask whether they will marry this year before fixing the Life Palace star or triple-direction. The future can certainly be asked about, but it must be carried by the natal foundation or it is a castle in the air.",
 cnLog:['第一步先核对农历生日时辰，排出命身十二宫，确认命宫主星与庙旺落陷。','第二步把命宫的三方四正摊开，财帛、官禄、迁移的星全部列出，看静态结构稳不稳。','第三步看生年四化落在哪几宫，定这张盘的先天底色和发力方向。','第四步在结构完整后判格局成不成，避免先被格局名字带着走。'],
 enLog:['第一步先核对农历生日时辰，排出命身十二宫，确认命宫主星与庙旺落陷。','第二步把命宫的三方四正摊开，财帛、官禄、迁移的星全部列出，看静态结构稳不稳。','第三步看生年四化落在哪几宫，定这张盘的先天底色和发力方向。','第四步在结构完整后判格局成不成，避免先被格局名字带着走。'],
 enLog:["First verify the lunar birthday and hour, cast the twelve palaces, and confirm the Life Palace star and its brightness.","Second, open the Life Palace triple-direction and list the Wealth, Career and Travel stars to test the static structure.","Third, check where the natal Four Transformations land to set the chart's baseline tone and direction.","Fourth, judge patterns only after the structure is complete, rather than being led by a pattern name."],
 cnStep:['核对公历转农历，确认时辰，排命身宫与十二宫','定命宫主星和亮度，这是整张盘的核心','拉命宫三方四正，把财帛、官禄、迁移的主星辅煞一次列清','看生年四化落宫，标出先天资源、权力、名声和卡点在哪','结构定完再判格局，看成格条件和破格因素','最后叠大限流年，回答「什么时候、在哪个阶段」的问题'],
 enStep:["Convert the solar birthday to lunar, confirm the hour, and cast the Life, Body and twelve palaces","Set the Life Palace major star and its brightness as the core of the whole chart","Open the Life Palace triple-direction and list the Wealth, Career and Travel stars and malefics together","Read the natal transformations to mark where innate resources, power, reputation and friction sit","Only judge patterns once the structure is set, checking formation and breaking factors","Finally layer the decade and year to answer when and in which stage things move"],
 cnMis:['一上来就追流年吉凶，跳过本命结构','看到一个好听的格局名就往自己身上套，不看成格条件','东一榔头西一棒子地看，没有固定顺序，结论互相矛盾'],
 enMis:["Chasing yearly fortune first and skipping the natal structure","Claiming an attractive pattern without checking its formation conditions","Glancing randomly without a fixed order, producing contradictory conclusions"],
 cnClose:'六步顺序不是死板的规矩，而是让你每一步都站在扎实的基础上。底盘稳了，后面的四化、格局、流年才有地方落。',
 enClose:"The six-step sequence is not rigid ritual; it keeps each step on solid ground. Once the foundation is stable, transformations, patterns and years have somewhere to land."},

{cat:'faq',slug:'ziwei-xiankan-minggong-haishi-weilai',focus:'先看命宫还是未来',focusEn:'whether to read the Life Palace or the future first',
 cnT:'紫微斗数先看命宫还是先看未来：顺序错了全盘皆输',enT:'In Zi Wei Dou Shu, Do You Read the Life Palace or the Future First?',
 cnD:'无论多想知道未来，都要先定命宫与本命三方四正；流年答案只是在本命底盘上叠加的时间层，跳过底盘直接问未来最容易误判。',
 enD:"However eager you are about the future, first fix the Life Palace and its triple-direction. The yearly answer is only a timing layer on the natal foundation, and skipping it invites misreading.",
 cnL:'「我只想知道今年会不会升职」——这是最常见的开场。但今年的你，依然是本命那个你，不先读懂底盘，流年给出的关键词就无处安放。',
 enL:"I only want to know whether I will be promoted this year is the most common opening. But this year you are still the natal you; without the foundation, yearly keywords have nowhere to sit.",
 cnA:'这个问题表面是问顺序，实际是问「能不能走捷径」。答案是不能——未来不是一张替换本命的新盘，而是叠加上去的一层，底盘不成立，上层再热闹也虚。',
 enA:"On the surface this asks about order, but really it asks whether a shortcut exists. It does not. The future does not replace the natal chart; it layers on top, and a weak foundation makes a busy upper layer hollow.",
 cnLog:['命宫与三方四正是静态底盘，回答「我是怎样的人、手里有什么牌」。','流年、大限是动态时间层，回答「这些牌在什么阶段被推到台前」。','两层是叠加关系，不是替代关系——流年不会把本命的结构抹掉。','只问未来不看底盘，等于不看地基就讨论这层楼怎么装修。'],
 enLog:["The Life Palace and triple-direction are the static foundation, answering who you are and what cards you hold.","The decade and year are dynamic timing layers, answering when those cards are pushed forward.","The layers add rather than replace; the year never erases the natal structure.","Asking only about the future without the foundation is like decorating a floor before checking the foundation."],
 cnStep:['先排本命盘，定命宫主星和亮度','拉三方四正，确认财帛、官禄、迁移的结构','看生年四化，定先天底色','底盘稳了，再叠大限看十年背景','然后看流年，定今年触发点','最后用条件式语言回答，而不是给一个绝对的「会或不会」'],
 enStep:["Cast the natal chart and set the Life Palace star and brightness","Open the triple-direction to confirm the Wealth, Career and Travel structure","Read the natal transformations to set the baseline","Once the foundation is solid, layer the decade for the ten-year background","Then read the year to set this year's trigger","Finally answer in conditional terms rather than an absolute yes or no"],
 cnMis:['把流年当成一张独立的新盘，以为能脱离本命','听到流年有化禄就断定今年一定发财，不看本命承接力','只想走捷径问结果，不愿先花时间读懂底盘'],
 enMis:["Treating the year as an independent chart detached from the natal","Assuming a yearly Hua Lu guarantees wealth without checking natal capacity","Wanting a shortcut to the result instead of first reading the foundation"],
 cnClose:'先命宫后未来，不是绕路，而是唯一走得通的路。底盘读不懂，给再多未来的断语也只是无根的猜测。',
 enClose:"Foundation first and future later is not a detour but the only viable path. Without understanding the base, any number of future claims are rootless guesses."},

{cat:'kanpan',slug:'ziwei-sanfang-sizheng-sigong-liandu',focus:'三方四正四宫联读',focusEn:'reading the four palaces of the triple-direction together',
 cnT:'三方四正怎么从单宫升级为四宫联读',enT:'How to Upgrade from One Palace to Reading the Four Palaces Together',
 cnD:'三方四正是本宫、对宫加两个三合宫的联合单位；单宫只给局部语义，四宫合起来才构成一个完整议题，再把四化当动力叠上去。',
 enD:"The triple-direction joins the home palace, its opposite and two trine palaces. One palace gives only partial meaning; the four together form a complete topic, with transformations as the driving force.",
 cnL:'盯着一宫一颗星下结论，是新手最容易犯的错。本宫像舞台中央，但对宫写牵引、三合写资源和执行，少看任何一个，这台戏都不完整。',
 enL:"Judging from one palace and one star is the classic beginner error. The home palace is center stage, but the opposite writes the pull and the trines write resources and execution; miss one and the play is incomplete.",
 cnA:'有人问「我命宫坐紫微是不是就很好」，问题在于一颗星再强，也要看四宫有没有辅佐、有没有煞星拆台。吉凶不在一颗星上，而在四张宫位的净效果里。',
 enA:"People ask whether Zi Wei in the Life Palace is enough, but even the strongest star depends on whether the four palaces support it or send malefics. The verdict lies in the net effect of four positions, not one star.",
 cnLog:['本宫写核心，对宫正对面写牵引，两个三合宫写资源与执行，四宫合称三方四正。','吉星会照叫有援，煞星冲照叫有破，强弱要数净效果，而不是单看一颗星。','三方四正也是判格局的基本单位——格局成不成立，先看这四宫凑不凑得齐。','四化叠在四宫结构上，回答动力往哪走，不能脱离结构单独飞。'],
 enLog:["The home palace writes the core, the opposite writes the pull, and the two trine palaces write resources and execution; together they are the triple-direction.","Auspicious meetings mean support and malefic clashes mean breaks; strength is the net effect rather than one star.","The triple-direction is also the basic unit for judging whether a pattern forms.","Transformations layer onto the four-palace structure to show where force moves, never flying free of it."],
 cnStep:['锁定要问的那一宫作为本宫','找到正对面的对宫，看它怎么牵引本宫','沿三合找到另外两个宫，看资源和执行力','把四宫主星全部列出，再数辅星和煞星','看四化落在四宫的哪个位置，定动力方向','四宫合起来算净效果，最后才判这一宫是稳是虚'],
 enStep:["Lock the palace you ask about as the home palace","Find the opposite palace and see how it pulls the home palace","Follow the trine to the other two palaces for resources and execution","List the major stars in all four, then count assistant and malefic stars","See where transformations land among the four to set the force direction","Combine the four for the net effect before judging the palace solid or hollow"],
 cnMis:['只盯本宫一颗星，忽略对宫和三合','看到一颗煞星就判坏，没看吉星是否化解','把三方四正背成口诀，却不在自己盘上真正连线'],
 enMis:["Fixating on one star and ignoring the opposite and trines","Judging one malefic as bad without checking whether auspicious stars resolve it","Knowing the rhyme but never actually drawing the lines on a real chart"],
 cnClose:'学会四宫联读，看盘就从「看一颗星」升级成「看一张关系网」——这是从背星到会读盘的第一道门槛。',
 enClose:"Mastering the four-palace reading moves you from one star to a relationship network, the first threshold between memorizing stars and truly reading a chart."},

// ========== 四化 5 ==========
{cat:'sihua',slug:'ziwei-sihua-nengliang-bianhua-bu-shi-jixiong',focus:'四化是能量变化',focusEn:'the Four Transformations as shifts rather than labels',
 cnT:'四化飞星怎么分辨能量变化与吉凶标签',enT:'How to Tell Energy Shifts Apart from Good-or-Bad Labels in the Four Transformations',
 cnD:'化禄权科忌是四种作用方向，不是好坏四格；化忌是牵挂和持续处理的课题，不必直接解释成灾，顺序应是星、宫、四化、现实。',
 enD:"Lu, Quan, Ke and Ji are four directions of effect, not good and bad boxes. Ji is a topic of concern and ongoing work, not automatically disaster; the order is star, palace, transformation, reality.",
 cnL:'很多人把化禄当中奖、化忌当完蛋，其实四化描述的是能量往哪流——资源、掌控、可见度、卡点，四种状态各有各的功课，没有一个是简单的吉凶。',
 enL:"Many treat Lu as a jackpot and Ji as ruin, but the transformations describe where energy flows: resources, control, visibility and friction, each with its own work rather than simple fortune.",
 cnA:'这个问题要拆的是「标签式读法」。一旦把四化贴成好坏，就看不到化禄也带消耗、化忌也逼你成长。真正该问的是这一化在这一宫，改变了星的哪种表现。',
 enA:"What needs dismantling is label-style reading. Once transformations are boxed as good or bad, you miss that Lu also brings spending and Ji forces growth. The real question is how a transformation changes the star in that palace.",
 cnLog:['四化改变的是星曜在某宫的表现方式，不替代主星的本质。','化禄联系资源与获得，化权联系推动与掌控，化科联系名声与可见，化忌联系牵挂与阻塞。','化忌常表现为持续投入和关注，处理好了是深耕，不必直接断成灾。','解读顺序永远是先星曜宫位，再叠四化，最后落回现实事件，不能倒过来。'],
 enLog:["Transformations change how a star expresses in a palace; they do not replace the star's essence.","Lu links to resources and gain, Quan to drive and control, Ke to reputation and visibility, Ji to concern and blockage.","Ji often shows as sustained investment and focus, which becomes deep cultivation when handled, not automatic disaster.","The order is always star and palace first, transformations next, and reality last, never reversed."],
 cnStep:['先认星曜本质和宫位主题，这是底色','再看生年四化落在哪一宫','判断这一化改变了星的哪种作用方向','化禄看资源从哪来、往哪去，化权看掌控和责任','化科看可见度有没有真本事承接，化忌看卡点要长期处理什么','最后用条件式语言落回现实，不贴吉凶标签'],
 enStep:["First recognize the star's essence and the palace theme as the baseline","See where the natal transformations land","Judge which direction of effect each transformation changes","For Lu trace where resources come and go; for Quan examine control and responsibility","For Ke check whether real skill backs the visibility; for Ji identify the friction to work on long term","Finally return to reality in conditional terms without good-or-bad labels"],
 cnMis:['把化禄化忌直接当好事坏事，不看落宫','以为化忌一定是灾，忽略它也代表深耕和专注','四化脱离星曜宫位单独飞，越飞越玄'],
 enMis:["Boxing Lu and Ji as simply good or bad without the palace","Assuming Ji is always disaster and ignoring that it also means deep focus","Flying transformations free of stars and palaces until it becomes mysticism"],
 cnClose:'四化是能量的流向，不是命运的判决。学会看「作用方向」而不是「吉凶标签」，你对一张盘的理解会立刻立体起来。',
 enClose:"The transformations are currents of energy, not verdicts of fate. Reading directions of effect instead of good-or-bad labels instantly makes your understanding three-dimensional."},

{cat:'sihua',slug:'ziwei-bingwu-sihua-luodi-fangfa',focus:'2026丙午四化落地',focusEn:'putting the 2026 Bing-Wu transformations into practice',
 cnT:'2026丙午年四化怎么落地：天同禄、天机权、文昌科、廉贞忌',enT:'Putting the 2026 Bing-Wu Four Transformations into Practice',
 cnD:'2026年丙干四化为天同禄、天机权、文昌科、廉贞忌，但必须先定位落宫再看本命结构，年度四化表不是每个人的统一运势。',
 enD:"The 2026 Bing stem gives Tong-Tian Lu, Tian-Ji Quan, Wen-Chang Ke and Lian-Zhen Ji, but locate the landing palace and natal structure first; the yearly table is not a universal fortune for everyone.",
 cnL:'年度四化表谁都能查到，真正难的是落地——同一组天同禄，落在财帛和落在福德，是完全不同的两件事。主星是底色，四化只是当期的加减。',
 enL:"Anyone can look up the yearly table, but the hard part is applying it. The same Tong-Tian Lu in the Wealth Palace and in the Karma Palace are two different matters; the star is the baseline and the transformation is the current adjustment.",
 cnA:'很多人看到丙午四化就往自己身上硬套，忽略了落宫。问题不在四化本身，而在它作用在你本命的哪个位置——不定位落宫，年度运势就是一句空话。',
 enA:"Many people force the Bing-Wu transformations onto themselves without the landing palace. The issue is not the transformations but where they act on your natal chart; without locating that, the yearly fortune is empty.",
 cnLog:['丙年四化固定为天同禄、天机权、文昌科、廉贞忌，但落宫因人而异。','天同禄偏福气与享受的资源，天机权偏思考与谋划的推动，文昌科偏文书名声，廉贞忌偏规则与感情的卡点。','化权常带来责任和推动，未必只是升职；化科的曝光要有内容承接。','仅凭年干不能给个人断语，必须叠本命和大限，看结构能否接住。'],
 enLog:["The Bing stem fixes Tong-Tian Lu, Tian-Ji Quan, Wen-Chang Ke and Lian-Zhen Ji, but the landing palace differs by person.","Tong-Tian Lu leans toward resources of comfort, Tian-Ji Quan toward planning drive, Wen-Chang Ke toward writing and reputation, and Lian-Zhen Ji toward friction with rules and relationships.","Quan often brings responsibility and drive, not only promotion; Ke's exposure needs real content to back it.","The year stem alone cannot judge an individual; it must layer over the natal chart and decade to see whether the structure can carry it."],
 cnStep:['先确认2026年丙干四化是哪四颗星','逐一找这四颗星在你本命盘的落宫','看落宫的主星和三方四正，定结构底色','天同禄看资源落在什么事上，天机权看责任在哪','文昌科看名声靠什么承接，廉贞忌看卡点要收敛什么','叠大限流年，确认这一年在十年背景中的位置，再行动'],
 enStep:["Confirm which four stars the 2026 Bing stem transforms","Locate each of the four stars in your natal chart","Read the landing palace's major star and triple-direction to set the structural baseline","For Tong-Tian Lu see what resources land on; for Tian-Ji Quan identify where responsibility sits","For Wen-Chang Ke examine what backs the reputation; for Lian-Zhen Ji see what the friction requires you to restrain","Layer the decade and year to place this year within the ten-year background before acting"],
 cnMis:['把年度四化表当成每个人统一的运势','只看星不看落宫，硬往自己身上套','以为化权就一定升职、化忌就一定出事，不看承接条件'],
 enMis:["Treating the yearly table as a universal fortune for everyone","Looking only at the star without the landing palace","Assuming Quan guarantees promotion and Ji guarantees trouble without checking what carries them"],
 cnClose:'丙午四化的价值，要在落宫和本命结构里才读得出来。先定位，再看承接，最后才谈这一年怎么计划。',
 enClose:"The value of the Bing-Wu transformations appears only through the landing palace and natal structure. Locate first, examine capacity next, and only then plan the year."},

{cat:'sihua',slug:'ziwei-niandu-sihua-jihui-zuli',focus:'年度四化的机会与阻力',focusEn:'the opportunities and friction of yearly transformations',
 cnT:'年度四化先定落宫，再谈机会和阻力',enT:'Yearly Transformations: Fix the Landing Palace Before Discussing Opportunity and Friction',
 cnD:'化禄权科忌可转成资源、推动、可信度和持续摩擦；化科要检验有没有实际内容，化忌像长期成本，应落到边界和复盘而不是恐吓。',
 enD:"Lu, Quan, Ke and Ji translate into resources, drive, credibility and ongoing friction. Test whether Ke has real substance, and treat Ji like a long-term cost to manage through boundaries and review rather than fear.",
 cnL:'看年度计划最有用的方式，是把四化当成一组信号——哪里给资源、哪里推你动、哪里让你被看见、哪里要你持续付成本。信号读懂了，行动才有准头。',
 enL:"The most useful way to read a yearly plan is treating the transformations as signals: where resources come, what pushes you, where you become visible, and where you keep paying cost. Read the signals and your actions gain precision.",
 cnA:'常见的偏差是只盯着化禄找机会、看到化忌就回避。其实机会和阻力是一体的——化禄也带支出，化忌也帮你止损，关键是落宫决定议题，星曜决定表达方式。',
 enA:"The common bias is chasing only Lu for opportunity and avoiding Ji. But opportunity and friction are one fabric: Lu also brings spending and Ji helps you cut losses; the landing palace sets the topic and the star sets the expression.",
 cnLog:['四化落宫决定议题领域，星曜本身决定表达方式。','化禄给资源也带相应支出，化权给推动也含竞争。','化科给可见度，但不能替代能力和证据，没真本事就是虚名。','化忌是持续摩擦和成本，应落到边界、复盘和收敛动作，而不是恐吓。'],
 enLog:["The landing palace sets the topic, while the star itself sets the expression.","Lu gives resources but also corresponding spending; Quan gives drive but also competition.","Ke gives visibility but cannot replace ability and evidence; without real skill it is an empty name.","Ji is ongoing friction and cost, to be handled through boundaries, review and restraint rather than fear."],
 cnStep:['先定四颗化星在本命的落宫','化禄那一宫，列资源从哪来、附带什么支出','化权那一宫，看推动什么、要承担什么竞争','化科那一宫，检验有没有作品和证据支撑可见度','化忌那一宫，把持续成本翻译成边界和复盘清单','给每一化设一个可验证指标，再据此排年度行动'],
 enStep:["First fix the landing palaces of the four transformed stars in the natal chart","For Lu, list where resources come from and what spending accompanies them","For Quan, see what is pushed forward and what competition you take on","For Ke, test whether works and evidence support the visibility","For Ji, translate the ongoing cost into boundaries and a review checklist","Set one verifiable indicator for each transformation, then arrange the year's actions"],
 cnMis:['只追化禄机会，看到化忌就躲','化科不看有没有真本事，把虚名当实力','把化忌当恐吓，不做边界管理，结果成本失控'],
 enMis:["Chasing only Lu's opportunity and hiding from Ji","Taking Ke's empty name as strength without checking real ability","Treating Ji as fear rather than managing boundaries, letting costs run out of control"],
 cnClose:'年度四化不是算命的判词，而是一份行动地图。机会要抓，成本要管，每一项都落到可验证的指标上，这一年才不慌。',
 enClose:"Yearly transformations are not fortune-telling verdicts but an action map. Grasp opportunities, manage costs, and tie each item to a verifiable indicator so the year stays steady."},

{cat:'sihua',slug:'ziwei-hualu-huaquan-tonggong-panduan',focus:'化禄化权同宫',focusEn:'judging Lu and Quan sharing one palace',
 cnT:'化禄化权同宫怎么判断：资源与掌控撞在一起',enT:'How to Judge Lu and Quan Sharing One Palace: Resources Meet Control',
 cnD:'化禄化权同宫是资源和推动叠加，常表现为机会多、掌控欲强，但也容易独揽和透支；要先看主星能否承受，再看落宫是什么事。',
 enD:"Lu and Quan in one palace layer resources over drive, often showing many opportunities and strong control, but also a tendency to take on everything and overextend. First see whether the major star can bear it and what matter the palace represents.",
 cnL:'禄权同宫是很有戏的组合——手里既有资源又有推动力，做事容易成。但成不成是一回事，累不累、会不会一个人扛太多，是另一回事。',
 enL:"Lu and Quan together are a dramatic combination: resources and drive in one place, making things happen. But whether it succeeds is one question; whether you exhaust yourself and carry everything alone is another.",
 cnA:'很多人一看到禄权同宫就断「大好」，问题是双重能量也要有结构承接。主星弱、三方破，资源和权力反而会变成压力和争夺。',
 enA:"Many declare Lu and Quan together excellent, but doubled energy still needs structure to carry it. With a weak major star and broken trines, resources and power instead become pressure and contest.",
 cnLog:['化禄给资源，化权给推动，同宫是两种能量叠加在同一件事上。','正面表现为机会到手又有执行力，容易在该宫代表的领域快速起势。','负面是掌控欲强、不愿分权，容易独揽、透支，或与人争主导。','吉凶要看主星强弱和三方四正能不能承接这股双倍的力。'],
 enLog:["Lu gives resources and Quan gives drive; in one palace the two energies stack onto the same matter.","The positive side shows opportunities in hand plus execution, quickly building momentum in that palace's area.","The negative side is strong control, reluctance to share power, taking everything on, overextension, or fighting for the lead.","The verdict depends on whether the major star and triple-direction can carry the doubled force."],
 cnStep:['先确认化禄化权是否真在同一宫','看该宫主星是什么、强弱能否承受双倍能量','拉三方四正，看有没有辅佐和煞星','正面利用：资源到手就配执行，快速起势','反面防范：刻意分权，避免独揽和透支','叠大限看这股能量在哪个阶段最旺，再决定扩张节奏'],
 enStep:["First confirm Lu and Quan truly share one palace","See what the palace's major star is and whether it can bear doubled energy","Open the triple-direction for assistants and malefics","Use the positive: pair resources with execution to build momentum fast","Guard the negative: deliberately share power to avoid taking everything on and overextending","Layer the decade to see when this energy peaks before choosing the pace of expansion"],
 cnMis:['看到禄权同宫就断绝对的好，不看承接条件','忽略双倍能量的负面，不做分权和节奏管理','只看同宫不看主星强弱，弱星扛重权反成压力'],
 enMis:["Declaring Lu and Quan together absolutely good without checking carrying conditions","Ignoring the negative of doubled energy and skipping power-sharing and pacing","Looking only at the combination without the star's strength; a weak star bearing heavy power becomes pressure"],
 cnClose:'禄权同宫是一副好牌，但好牌也要会打——资源和掌控同时在手时，学会分权和留余地，比一味扩张更能把势留住。',
 enClose:"Lu and Quan together are a strong hand, but a strong hand must be played well. With resources and control at once, learning to share power and leave margin preserves momentum better than relentless expansion."},

{cat:'sihua',slug:'ziwei-huaji-kezhi-bu-shi-zainan',focus:'化忌的克制含义',focusEn:"Ji's meaning of restraint rather than disaster",
 cnT:'化忌的核心是克制，不是灾难',enT:'The Core of Hua Ji Is Restraint, Not Disaster',
 cnD:'化忌要求收敛和持续处理，不等于灾祸；它常指出你最在意、最需要补课的领域，处理方式是收缩、守界、深耕，而不是被吓住。',
 enD:"Ji calls for restraint and ongoing work, not disaster. It often points to the area you care most about and need to cultivate, handled through contraction, boundaries and deep focus rather than fear.",
 cnL:'化忌是四化里被误解最深的一个。它不是老天爷判你输，而是提醒你在这件事上要慢、要收、要下笨功夫——越是在意的领域，越容易卡住，也越值得深耕。',
 enL:"Ji is the most misunderstood transformation. It is not a verdict of failure but a reminder to slow down, pull back and do patient work in that matter; the area you care most about is where you get stuck and where deep focus matters.",
 cnA:'标签式读法把化忌当「完蛋」，结果人先被吓住，什么都不敢动。真正该问的是这个忌在哪一宫、卡的是什么、要靠什么边界和长期动作去化解。',
 enA:"Label-style reading treats Ji as ruin, paralyzing a person before they act. The right questions are which palace the Ji sits in, what is stuck, and which boundaries and long-term actions can work through it.",
 cnLog:['化忌的本义是牵挂、收敛和持续处理，不是灾祸的同义词。','它落在哪个宫，就指出你在哪个领域最在意、也最容易用力过猛或落空。','正确动作是收缩预期、守住边界、深耕基本功，而不是硬冲或逃避。','化忌处理好了往往是深度所在——人在补课的地方，反而走得最扎实。'],
 enLog:["The original meaning of Ji is concern, contraction and ongoing work, not a synonym for disaster.","Wherever it lands points to the area you care most about and where you either push too hard or fall short.","The right move is to contract expectations, hold boundaries and deepen fundamentals, rather than forcing through or fleeing.","When handled well, Ji often becomes the source of depth; the place where you do remedial work becomes the most solid."],
 cnStep:['先确认化忌落在哪一宫、被作用的是哪颗星','看该宫的三方四正，理解卡点的结构来源','把化忌翻译成这个领域要长期处理的具体课题','收缩不切实际的预期，先守住边界和底线','在该领域下笨功夫深耕，不硬冲也不逃避','叠大限流年，看卡点在哪个阶段松动，再逐步加力'],
 enStep:["First confirm which palace Ji lands in and which star it acts on","Read that palace's triple-direction to understand the structural source of the blockage","Translate Ji into the specific topic to work on long term in that area","Contract unrealistic expectations and first hold the boundaries and baseline","Do patient, fundamental work there, neither forcing through nor fleeing","Layer the decade and year to see when the blockage loosens before gradually adding force"],
 cnMis:['把化忌直接等于灾难，先把自己吓住','看到忌就硬冲或彻底逃避，两个极端都错','不做边界和深耕，指望一个「化解」动作就一劳永逸'],
 enMis:["Equating Ji directly with disaster and paralyzing yourself","Forcing through or completely fleeing from Ji, both extremes wrong","Skipping boundaries and deep work and expecting one fix to solve it forever"],
 cnClose:'化忌不是命运的坏牌，而是一张要求你认真对待的牌。学会在卡点上收缩、守界、深耕，你会发现最扎实的成长往往就在那里。',
 enClose:"Ji is not a bad card of fate but one that asks you to take something seriously. Learn to contract, hold boundaries and deepen work at the blockage, and you will find your most solid growth there."}
];
