// 2026-09-25 调研驱动 第2组：格局4 + 主星3 = 7篇
module.exports=[
// ========== 格局 4 ==========
{cat:'geju',slug:'ziwei-fuxiang-chaoyuan-chengge-tiaojian',focus:'府相朝垣成格条件',focusEn:'the formation conditions of the Fu-Xiang Chao-Yuan pattern',
 cnT:'府相朝垣成格条件：为什么看到天府天相还不够',enT:'The Fu-Xiang Chao-Yuan Pattern: Why Seeing Tian-Fu and Tian-Xiang Is Not Enough',
 cnD:'府相朝垣要求天府、天相进入命宫三方四正，但出现星曜只是形式条件；主星亮度、煞忌破坏和运限引动才决定格局成色。',
 enD:"Fu-Xiang Chao-Yuan requires Tian-Fu and Tian-Xiang in the Life Palace triple-direction, but seeing the stars is only the formal condition. Brightness, malefic breaks and timing activation decide the quality.",
 cnL:'很多人盘上找到天府、天相就高兴地说自己成了府相朝垣，其实数到星只完成了第一步。这是一个讲稳定与辅佐的格局，条件差一点，成色就差一截。',
 enL:"Many people find Tian-Fu and Tian-Xiang and happily claim the pattern, but counting the stars is only step one. This is a pattern of stability and support, and one missing condition noticeably lowers its quality.",
 cnA:'这个问题的关键是「形式」和「成色」要分开。天府天相都在，只说明有这个架子；架子能不能立住、有没有被煞星拆掉、运限什么时候引动，才是格局真正的分量。',
 enA:"The key is separating form from quality. Both stars being present only shows the frame exists. Whether the frame holds, whether malefics dismantle it, and when timing activates it are the real weight of the pattern.",
 cnLog:['基本成格条件是天府、天相进入命宫三方四正，形成稳定与辅佐的结构。','主星组合和庙旺决定格局层次，不能只数星曜是否出现。','若天府天相被擎羊、陀罗、化忌等冲破，格局减色甚至破格。','格局是结构倾向而非定局，仍需四化与大限引动，才在现实中兑现。'],
 enLog:["The basic condition is Tian-Fu and Tian-Xiang entering the Life Palace triple-direction, forming a structure of stability and support.","The major star combination and brightness decide the level; simply counting the stars is not enough.","If the two are broken by Qing-Yang, Tuo-Luo or Hua Ji, the pattern weakens or even breaks.","A pattern is a structural tendency, not a fixed result; it still needs transformations and the decade to activate it in reality."],
 cnStep:['先看命宫三方四正里天府、天相是否都出现','确认两星的庙旺亮度，亮度足才立得稳','检查有没有擎羊、陀罗、火星、铃星、化忌冲破','看成格之外有没有左辅右弼、文昌文曲等吉星加持','看四化和大限，确认格局在哪个阶段被引动','最后区分上班族与创业者：同一格局在两种人身上兑现方式不同'],
 enStep:["First check whether both Tian-Fu and Tian-Xiang appear in the Life Palace triple-direction","Confirm the brightness of both stars, since sufficient brightness makes it stable","Check whether Qing-Yang, Tuo-Luo, Huo-Xing, Ling-Xing or Hua Ji break through","See whether auspicious stars such as Zuo-Fu, You-Bi, Wen-Chang and Wen-Qu add support beyond the formation","Read the transformations and decade to confirm when the pattern activates","Finally distinguish employees from entrepreneurs, since the same pattern manifests differently for each"],
 cnMis:['看到天府天相就断成格，不看亮度和煞忌','把格局当成定局，忽略运限引动和现实努力','只背格局名字，不区分普通上班族和创业者的不同兑现'],
 enMis:["Claiming the pattern from seeing the two stars without checking brightness and malefics","Treating the pattern as fixed and ignoring timing and real effort","Memorizing the name without distinguishing how it manifests for employees versus entrepreneurs"],
 cnClose:'府相朝垣是一副讲稳重和辅佐的好架子，但架子不等于结果。把成格条件、破格因素和引动时机都看清，它的分量才真正属于你。',
 enClose:"Fu-Xiang Chao-Yuan is a fine frame of steadiness and support, but the frame is not the result. See the formation conditions, breaking factors and activation timing clearly, and its weight truly becomes yours."},

{cat:'geju',slug:'ziwei-shapolang-miaoxian-sihua',focus:'杀破狼的庙陷与四化',focusEn:'the brightness and transformations of the Sha-Po-Lang pattern',
 cnT:'杀破狼格局：变动能力如何被庙陷、四化和大限放大',enT:'The Sha-Po-Lang Pattern: How Change Is Magnified by Brightness, Transformations and the Decade',
 cnD:'杀破狼是七杀、破军、贪狼在三方四正形成的变革结构，核心是突破而非动荡；庙旺、四化和大限决定变动能否转成成果。',
 enD:"Sha-Po-Lang is the change structure formed by Qi-Sha, Po-Jun and Tan-Lang in the triple-direction, centered on breakthrough rather than chaos. Brightness, transformations and the decade decide whether change becomes results.",
 cnL:'杀破狼被贴了太多「动荡」的标签，其实它是一张变革者的盘——七杀主决断、破军主推倒重来、贪狼主欲望和机缘，三颗星合起来，是一股要打破旧局的力。',
 enL:"Sha-Po-Lang is over-labeled as turbulent, but it is a changer's chart. Qi-Sha decides, Po-Jun rebuilds and Tan-Lang holds desire and opportunity; together they are a force that breaks the old order.",
 cnA:'真正要判断的不是「会不会变」，而是「变了能不能成」。同样是杀破狼，庙旺有吉星会照是开创新局，落陷加煞忌则可能是反复折腾，差别全在成色和时机。',
 enA:"What matters is not whether change happens but whether change succeeds. The same pattern in brightness with auspicious support opens new ground, while fallen stars with malefics can mean repeated struggle; the difference is quality and timing.",
 cnLog:['杀破狼的核心是变化与突破，不是单一吉凶标签。','七杀主决断执行，破军主破旧立新，贪狼主欲望机缘，三星分工不同。','庙陷和会入吉星影响行动能否沉淀为成果，落陷加煞则容易空折腾。','大限决定变动主题在哪个十年被放大，是格局兑现的关键时间层。'],
 enLog:["The core of Sha-Po-Lang is change and breakthrough, not a single good-or-bad label.","Qi-Sha drives decisive execution, Po-Jun breaks and rebuilds, and Tan-Lang holds desire and opportunity, each with a different role.","Brightness and auspicious meetings decide whether action settles into results; fallen stars with malefics tend toward empty struggle.","The decade decides which ten-year period magnifies the change, the key timing layer for the pattern's fulfillment."],
 cnStep:['先确认七杀、破军、贪狼是否在命宫三方四正会齐','分别看三颗星的庙旺落陷，判断变革力的成色','看有没有紫微、禄存、左右等吉星会照，给变动托底','检查煞星化忌，识别反复折腾的风险','看四化，判断这股变革力往哪个方向使','叠大限，确认变动在哪个十年被放大、何时最可能出成果'],
 enStep:["First confirm Qi-Sha, Po-Jun and Tan-Lang meet in the Life Palace triple-direction","Check the brightness of each star to judge the quality of the change force","See whether Zi-Wei, Lu-Cun, Zuo-You or other auspicious stars support the change","Check malefics and Ji to identify the risk of repeated struggle","Read the transformations to see which direction the change force takes","Layer the decade to confirm which ten-year period magnifies the change and when results are most likely"],
 cnMis:['把杀破狼直接等同于动荡不安，不看突破的正面','只看格局不看庙陷，成色差别被抹平','忽略大限，解释不了为什么有人早成、有人中年才起'],
 enMis:["Equating Sha-Po-Lang directly with instability while ignoring the breakthrough side","Looking only at the pattern and not brightness, flattening the quality difference","Ignoring the decade and being unable to explain why some succeed early and others in midlife"],
 cnClose:'杀破狼是变革者的结构，不是动荡者的判词。把庙陷、四化和大限看清，这股要打破旧局的力，才会变成开创新局的成果。',
 enClose:"Sha-Po-Lang is a changer's structure, not a verdict of chaos. See the brightness, transformations and decade clearly, and the force that breaks the old order becomes results that open new ground."},

{cat:'geju',slug:'ziwei-jiyueliangge-zhiye-changjing',focus:'机月同梁格的职业场景',focusEn:'the career scenarios of the Ji-Yue Tong-Liang pattern',
 cnT:'机月同梁格：成格后仍要看职业场景与星曜状态',enT:'The Ji-Yue Tong-Liang Pattern: Even After Forming, Check the Career Scenario and Star Conditions',
 cnD:'机月同梁描述天机、太阴、天同、天梁构成的规划文职倾向，但不是固定职业清单；星曜亮度和四化决定它落到哪类稳定工作。',
 enD:"Ji-Yue Tong-Liang describes the planning and clerical tendency of Tian-Ji, Tai-Yin, Tong-Tian and Tian-Liang, but it is not a fixed job list. Brightness and transformations decide which kind of stable work it becomes.",
 cnL:'机月同梁常被一句话概括成「适合吃公家饭」，这太粗了。它确实偏思考、规划和制度型路径，但同样叫稳定，公务、专业服务、产品策划是三种完全不同的稳定。',
 enL:"Ji-Yue Tong-Liang is often summed up as suited to government work, which is too coarse. It does lean toward thinking, planning and institutional paths, but civil service, professional services and product planning are three different kinds of stability.",
 cnA:'关键要破的是「格局锁死职业」的读法。成格只说明有这类结构倾向，真正落到什么岗位，要看四星落宫亮度，以及四化把哪些潜在能力变成了具体任务。',
 enA:"What must be broken is the reading that a pattern locks in a career. Forming only shows the tendency; which job it becomes depends on the four stars' palaces and brightness, and on which potential abilities the transformations turn into tasks.",
 cnLog:['机月同梁是结构倾向，不是固定职业清单。','天机主思考谋划，太阴主细致文职，天同主协调，天梁主监察，四星各有分工。','四星的落宫和亮度会改变表现，亮度不足时优势打折。','四化把潜在能力转成具体的工作任务或压力，是格局落地的关键。'],
 enLog:["Ji-Yue Tong-Liang is a structural tendency, not a fixed career list.","Tian-Ji handles thinking and planning, Tai-Yin detailed clerical work, Tong-Tian coordination, and Tian-Liang oversight, each with a role.","The palaces and brightness of the four stars change expression, and weak brightness discounts the advantage.","Transformations turn potential abilities into concrete tasks or pressure, the key to the pattern landing."],
 cnStep:['先确认天机、太阴、天同、天梁是否在三方四正构成格局','分别看四星的落宫和亮度，判断哪颗最得力','看事业宫，把结构倾向翻译成具体工作任务','比较公务、专业服务、产品策划三类稳定岗位，看哪类更合盘','看四化，确认哪些能力被转成了晋升任务或压力','结合大限，判断这种稳定路径在哪个阶段最顺，再做职业选择'],
 enStep:["First confirm Tian-Ji, Tai-Yin, Tong-Tian and Tian-Liang form the pattern in the triple-direction","Check each star's palace and brightness to see which is strongest","Read the Career Palace to translate the tendency into concrete work tasks","Compare civil service, professional services and product planning to see which stable path fits the chart","Read the transformations to confirm which abilities become promotion tasks or pressure","Use the decade to judge when this stable path is smoothest before choosing"],
 cnMis:['一句话把机月同梁等同于吃公家饭','只看格局名，不看四星亮度和落宫差别','忽略四化，解释不了同样格局为何有人做管理、有人做执行'],
 enMis:["Reducing Ji-Yue Tong-Liang to government work in one sentence","Looking only at the name and not the four stars' brightness and palaces","Ignoring transformations and unable to explain why the same pattern leads some to management and others to execution"],
 cnClose:'机月同梁给的是一类「靠脑子和制度吃饭」的倾向，不是一张岗位分配表。看清四星状态和四化，你才能找到属于自己的那种稳定。',
 enClose:"Ji-Yue Tong-Liang gives a tendency to work through intellect and institutions, not a job assignment table. See the four stars and transformations clearly to find the kind of stability that belongs to you."},

{cat:'geju',slug:'ziwei-shapolang-wutai-xuanze',focus:'杀破狼的舞台选择',focusEn:'choosing the stage for a Sha-Po-Lang chart',
 cnT:'杀破狼是换工作还是创业：先看三个条件',enT:'For Sha-Po-Lang, Change Jobs or Start a Business? Check Three Conditions First',
 cnD:'杀破狼的人面对变动，关键是分清换岗、转行、创业三种舞台；先看风险预算、退出机制和资源托底，再决定把变革力放在哪里。',
 enD:"When a Sha-Po-Lang person faces change, the key is separating an internal move, an industry switch and a startup. Check risk budget, exit mechanisms and resource backing before choosing where to place the change force.",
 cnL:'杀破狼的人天生闲不住，一有机会就想动。但「该往哪动」比「要不要动」重要得多——同样是变革者，在大公司内部创新、转行、自己创业，是三种完全不同的活法。',
 enL:"Sha-Po-Lang people are restless by nature and want to move at every opportunity. But where to move matters more than whether to move; internal innovation, switching industries and founding a company are three different ways to live.",
 cnA:'这个问题要避免的是「一冲动就裸辞创业」。变革力要用对舞台，判断标准是手里有没有足够的风险预算、有没有退路、有没有资源和团队托底，三者齐了才谈创业。',
 enA:"What must be avoided is quitting on impulse to start a business. Change force needs the right stage, judged by whether you have enough risk budget, an exit route, and resource and team backing; only with all three does a startup make sense.",
 cnLog:['杀破狼的变革力可以落在内部创新、转行或创业三种舞台，不是只有创业一条路。','创业风险最高，要求风险预算、退出机制和资源托底三者齐备。','若条件不足，把变革力放在大公司内部开新业务，往往更稳。','舞台选择还要看大限时机，格局能量在哪个十年最旺，决定何时出手。'],
 enLog:["The Sha-Po-Lang change force can land on internal innovation, an industry switch or a startup; entrepreneurship is not the only path.","A startup carries the highest risk and requires risk budget, an exit mechanism and resource backing all together.","When conditions are short, placing the change force in a new business inside a large company is often steadier.","Stage choice also depends on the decade; which ten-year period holds the strongest pattern energy decides when to act."],
 cnStep:['先确认自己确实是杀破狼结构，变革力是真实的','分清眼前机会是内部换岗、转行还是创业，三种舞台分开评估','算清风险预算：能承受多长时间没有稳定收入','设计退出机制：万一不成，退路是什么','盘点资源和团队托底，看有没有人接应、有没有启动资金','看大限时机，三者齐备且时机到了再创业，否则先用内部舞台练兵'],
 enStep:["First confirm you truly have the Sha-Po-Lang structure and real change force","Separate the opportunity into an internal move, industry switch or startup and assess each stage distinctly","Calculate the risk budget: how long you can bear without steady income","Design an exit mechanism: what the fallback is if it fails","Inventory resource and team backing, checking who supports you and whether startup funds exist","Read the decade; start a business only when all three are ready and timing arrives, otherwise use the internal stage to train"],
 cnMis:['把杀破狼等同于必须创业，忽略内部创新的舞台','不做风险预算和退出机制，一冲动就裸辞','只看格局不看大限时机，在能量低谷硬启动'],
 enMis:["Equating Sha-Po-Lang with having to start a business and ignoring the internal innovation stage","Skipping risk budget and exit planning and quitting on impulse","Looking only at the pattern and not the decade, forcing a launch in an energy trough"],
 cnClose:'变革者最稀缺的不是勇气，而是选对舞台的耐心。把三种舞台、三个条件和大限时机看清，你的变革力才不会被白白消耗。',
 enClose:"What changers lack most is not courage but the patience to choose the right stage. See the three stages, three conditions and decade timing clearly so your change force is not spent in vain."},

// ========== 主星 3 ==========
{cat:'zhuxing',slug:'ziwei-shisi-zhuxing-liangxi-huafen',focus:'十四主星的两大星系',focusEn:'dividing the fourteen major stars into two systems',
 cnT:'十四主星怎么分成紫微系与天府系来读',enT:'How to Divide the Fourteen Major Stars into the Zi-Wei and Tian-Fu Systems',
 cnD:'十四主星可按紫微星系和天府星系理解功能关系，从逐颗背性格转向按星系看结构；但星系分类不能替代宫位、庙旺和会照。',
 enD:"The fourteen major stars can be understood through the Zi-Wei and Tian-Fu systems, moving from memorizing personalities to reading structure. Yet the grouping cannot replace palaces, brightness and meetings.",
 cnL:'初学者常被十四颗主星的性格清单淹没，今天背明天忘。换个思路：先把它们分成两大星系，看清谁主权力、谁主资源、谁主执行、谁主变动，记忆就有了骨架。',
 enL:"Beginners are overwhelmed by personality lists for fourteen stars and forget them quickly. Change approach: first split them into two systems and see who handles power, resources, execution and change, giving memory a skeleton.",
 cnA:'这个问题要防的是「分了系就以为懂了」。星系只提供组织框架，让你理解星与星的关系；真正落到解读，同一颗星在命、官、财三宫表现完全不同，还得回到宫位。',
 enA:"What must be guarded is thinking that grouping means understanding. The systems only provide an organizing frame for relationships; in real reading, the same star behaves differently in the Life, Career and Wealth palaces, so you must return to palaces.",
 cnLog:['十四主星按紫微星系和天府星系分组，有助于理解星曜之间的功能关系。','紫微系偏权力与开创，天府系偏资源与承接，两系功能互补。','七杀、破军等变动星要放回紫微、天府体系中观察，才不孤立。','星系只是入门索引，主星性格是底色，落宫才决定应用问题。'],
 enLog:["Grouping the fourteen stars into the Zi-Wei and Tian-Fu systems helps understand their functional relationships.","The Zi-Wei system leans toward power and creation, and the Tian-Fu system toward resources and reception, complementing each other.","Change stars such as Qi-Sha and Po-Jun must be observed within the systems rather than in isolation.","The systems are only an entry index; star personality is the baseline and the palace decides the applied question."],
 cnStep:['先列出十四颗主星的名字','按紫微星系和天府星系把它们分成两组','理解紫微系偏权力开创、天府系偏资源承接','把七杀、破军、贪狼等变动星放回体系中定位','用同一颗星在命、官、财三宫的差异，检验「落宫决定表现」','记住星系只是骨架，后续仍要学庙旺、会照和四化'],
 enStep:["First list the names of the fourteen major stars","Split them into the Zi-Wei and Tian-Fu systems","Understand that Zi-Wei leans toward power and creation and Tian-Fu toward resources and reception","Place change stars such as Qi-Sha, Po-Jun and Tan-Lang back within the systems","Use the same star's differences in the Life, Career and Wealth palaces to test that the palace decides expression","Remember the systems are only a skeleton, followed by brightness, meetings and transformations"],
 cnMis:['逐颗死背性格，不按星系建立关系','分了系就以为读懂了，跳过宫位和庙旺','把七杀破军当孤立的凶星，不放进体系观察'],
 enMis:["Memorizing personalities one by one without building relationships through systems","Thinking grouping equals understanding and skipping palaces and brightness","Treating Qi-Sha and Po-Jun as isolated bad stars instead of observing them in the systems"],
 cnClose:'两大星系是帮你「挂住」十四颗星的衣架，而不是终点。先有骨架，再回到宫位和亮度，主星才会从标签变成活生生的结构。',
 enClose:"The two systems are a rack to hang the fourteen stars on, not the finish. Build the skeleton first, then return to palaces and brightness, and the major stars move from labels into living structure."},

{cat:'zhuxing',slug:'ziwei-tianfu-zuoming-caiku-shoucheng',focus:'天府坐命的财库守成',focusEn:'Tian-Fu in the Life Palace as treasury and stewardship',
 cnT:'天府星坐命与财库意象：守成、调度和风险边界',enT:'Tian-Fu in the Life Palace: Stewardship, Allocation and the Boundary of Risk',
 cnD:'天府的财库意象强调资源的承接、保管和调度，不等于现金必然充足；落在命财官不同宫位任务不同，守成过强会变成谨慎和延迟。',
 enD:"Tian-Fu's treasury image emphasizes receiving, keeping and allocating resources, not guaranteed cash. It carries different tasks in the Life, Wealth and Career palaces, and excessive caution becomes hesitation and delay.",
 cnL:'天府常被叫成「财库之星」，很多人以为坐命就一定有钱。其实财库讲的是一种能力——把资源接住、管好、调度好，会赚钱和会管钱，从来不是一回事。',
 enL:"Tian-Fu is often called the treasury star and people assume it means wealth in the Life Palace. The treasury is really an ability to receive, keep and allocate resources; earning money and managing money are never the same.",
 cnA:'要分清的是「财库」和「财运」。天府坐命给的是守成和调度的底色，不代表账上自动有钱；资源能不能留住、会不会被谨慎卡住，要看吉煞四化和落在哪一宫。',
 enA:"What must be separated is treasury from fortune. Tian-Fu in the Life Palace gives a baseline of stewardship and allocation, not automatic money; whether resources stay or get stuck by caution depends on stars, transformations and the palace.",
 cnLog:['天府的财库意象强调承接和管理，不等于现金必然充足。','天府坐命偏稳重守成，擅长保管和调度已有资源。','落在命、财、官不同宫位，现实任务各不相同。','吉煞与四化决定资源是留存、流动还是被卡住；守成过强会变成不愿冒险。'],
 enLog:["Tian-Fu's treasury image emphasizes receiving and managing, not guaranteed cash.","In the Life Palace it leans toward steadiness and stewardship, skilled at keeping and allocating existing resources.","It carries different real tasks in the Life, Wealth and Career palaces.","Stars and transformations decide whether resources stay, flow or get stuck; excessive stewardship becomes reluctance to take risk."],
 cnStep:['先确认天府是否坐命、亮度如何','理解财库是承接管理能力，不是现金数量','看天府所在宫位的三方四正，判断资源从哪来','看吉煞，判断资源留不留得住','看四化，判断资源是流动、留存还是被卡住','警惕守成过度，刻意留出适度冒险的空间，避免决策延迟'],
 enStep:["First confirm whether Tian-Fu sits in the Life Palace and its brightness","Understand the treasury as receiving and managing ability, not cash amount","Read the palace's triple-direction to see where resources come from","Check auspicious and malefic stars to see whether resources stay","Read transformations to see whether resources flow, stay or get stuck","Guard against excessive stewardship by deliberately leaving room for measured risk to avoid delayed decisions"],
 cnMis:['把天府坐命直接等同于有钱，不看承接条件','只讲守成，忽略资源调度和适度流动','守成过度变成谨慎拖延，还误以为是稳重'],
 enMis:["Equating Tian-Fu in the Life Palace directly with wealth without checking conditions","Speaking only of keeping and ignoring allocation and measured flow","Letting stewardship turn into cautious delay while mistaking it for steadiness"],
 cnClose:'天府坐命给的是一副「会管家底」的好底子，但财库要靠调度才活。守住资源又不被谨慎困住，才是这颗星真正的成熟用法。',
 enClose:"Tian-Fu in the Life Palace gives a fine gift for managing what you have, but the treasury comes alive through allocation. Keeping resources without being trapped by caution is the mature use of this star."},

{cat:'zhuxing',slug:'ziwei-tianfu-xingxi-ziyuan-biandong',focus:'天府星系的资源与变动',focusEn:'resources and change within the Tian-Fu system',
 cnT:'天府星系有哪些主星：从资源承接到变动执行',enT:'Which Major Stars Belong to the Tian-Fu System: From Receiving Resources to Executing Change',
 cnD:'天府星系含天府、太阴、贪狼、巨门、天相、天梁、七杀、破军，可按资源管理、表达判断、行动变动理解，仍需回到宫位和亮度。',
 enD:"The Tian-Fu system includes Tian-Fu, Tai-Yin, Tan-Lang, Ju-Men, Tian-Xiang, Tian-Liang, Qi-Sha and Po-Jun, understood through resource management, expression and judgment, and action and change, still returning to palaces and brightness.",
 cnL:'提到天府星系，很多人以为全是保守的星，其实它阵容很广——从管资源的天府，到做判断的巨门，再到主变动的七杀破军，一条线把「接住资源」到「推动变化」都覆盖了。',
 enL:"Mention the Tian-Fu system and people assume it is all conservative stars, but its lineup is broad, from Tian-Fu managing resources to Ju-Men judging and Qi-Sha and Po-Jun driving change, covering the full line from receiving to transforming.",
 cnA:'这个问题要破的是「天府系等于守成」的刻板印象。星系里既有承接资源的星，也有表达判断和执行变动的星，理解它们的分工，才看得清一个团队或一个人如何运转。',
 enA:"What must be broken is the stereotype that the system equals conservatism. It contains stars for receiving resources, expressing and judging, and executing change; understanding their roles shows how a team or person operates.",
 cnLog:['天府星系包含天府、太阴、贪狼、巨门、天相、天梁、七杀、破军等主星。','天府、太阴偏资源承接，天相、天梁偏协调监察。','巨门偏表达判断，贪狼偏欲望机缘，七杀、破军偏行动变动。','星系只提供组织框架，仍需回到宫位和亮度，按岗位任务而非性格标签理解。'],
 enLog:["The Tian-Fu system includes Tian-Fu, Tai-Yin, Tan-Lang, Ju-Men, Tian-Xiang, Tian-Liang, Qi-Sha and Po-Jun.","Tian-Fu and Tai-Yin lean toward receiving resources, and Tian-Xiang and Tian-Liang toward coordination and oversight.","Ju-Men leans toward expression and judgment, Tan-Lang toward desire and opportunity, and Qi-Sha and Po-Jun toward action and change.","The system only provides an organizing frame; return to palaces and brightness and understand stars through job tasks rather than personality labels."],
 cnStep:['先列出天府星系的八颗主星','按资源承接、协调监察、表达判断、行动变动给它们分组','理解从「接住资源」到「推动变化」的完整链条','用一个团队岗位来类比，看清每颗星承担什么任务','把同一星系的星放回命、官、财三宫，比较现实任务','记住星系是框架，最终仍要看落宫和亮度'],
 enStep:["First list the eight major stars of the Tian-Fu system","Group them into receiving resources, coordination and oversight, expression and judgment, and action and change","Understand the full chain from receiving resources to driving change","Use team roles as an analogy to see what task each star carries","Place the stars back in the Life, Career and Wealth palaces to compare real tasks","Remember the system is a frame and the final reading still depends on palaces and brightness"],
 cnMis:['把天府星系整体当成保守，看不见七杀破军的变动','只背星名不分组，理解不了星系的功能链条','停在星系框架，不回到宫位亮度做具体判断'],
 enMis:["Treating the whole system as conservative and missing the change stars Qi-Sha and Po-Jun","Memorizing names without grouping and unable to grasp the functional chain","Stopping at the frame and not returning to palaces and brightness for concrete judgment"],
 cnClose:'天府星系是一条从「管资源」到「推变化」的完整链条，不是一筐保守的星。看清八颗星的分工，你对一张盘如何运转会有全新的理解。',
 enClose:"The Tian-Fu system is a complete chain from managing resources to driving change, not a basket of conservative stars. See the roles of the eight stars clearly and you gain a fresh understanding of how a chart operates."}
];
