// 2026-09-25 调研驱动 第4组：职场财务应用 8篇
module.exports=[
{cat:'yingyong',slug:'ziwei-shiyegong-zhuxing-fuxing-pingjing',focus:'事业宫主星辅星与瓶颈',focusEn:'the major and assistant stars of the Career Palace and bottlenecks',
 cnT:'2026事业宫怎么看：主星、辅星与职场瓶颈',enT:'How to Read the 2026 Career Palace: Major Stars, Assistant Stars and Workplace Bottlenecks',
 cnD:'事业宫主星先描述工作方式再谈职位，天机太阳等组合要结合亮度四化；职场瓶颈可对应责任、曝光、协作或流程四类问题。',
 enD:"The Career Palace major star first describes how you work before the job title; combinations such as Tian-Ji and Tai-Yang need brightness and transformations. Bottlenecks map to responsibility, exposure, cooperation or process problems.",
 cnL:'「我到底适合做什么」——这个问题不能从职位名称里找答案。事业宫写的是你干活的方式：是擅长谋划、扛事、协调还是把关，先看清工作任务结构，岗位才对得上。',
 enL:"What am I suited to do cannot be answered from job titles. The Career Palace writes how you work: planning, carrying responsibility, coordinating or checking; see the task structure first and the position will match.",
 cnA:'很多人升职卡住，就笼统地说「事业运不好」。其实卡点分四种：责任没人给、做了没人看见、协作总出问题、流程被卡死。对应到星曜，才知道该补哪一块。',
 enA:"Many people hit a promotion ceiling and vaguely blame bad career fortune. Bottlenecks are four types: responsibility not given, work not seen, cooperation failing, or processes blocked. Mapping them to stars shows what to strengthen.",
 cnLog:['事业宫主星先描述工作方式，再谈职位名称。','天机偏谋划、太阳偏责任曝光、天同偏协调、太阴偏细致，各有任务。','主星组合要结合亮度与四化，亮度不足或化忌干扰则优势打折。','辅星和煞星分别对应协作助力与流程摩擦，是瓶颈的具体来源。'],
 enLog:["The Career Palace major star describes the way of working before the title.","Tian-Ji leans toward planning, Tai-Yang toward responsibility and exposure, Tong-Tian toward coordination, and Tai-Yin toward detail, each with tasks.","Combinations need brightness and transformations; weak brightness or Ji interference discounts the advantage.","Assistant stars and malefics correspond to cooperation support and process friction, the concrete sources of bottlenecks."],
 cnStep:['先定事业宫主星和亮度','把主星翻译成你擅长的工作任务结构','看辅星，确认协作和贵人助力','看煞星化忌，定位流程摩擦和干扰','把升职卡点归到责任、曝光、协作、流程中的哪一类','针对性补证据、调协作或换流程，而不是空等运势'],
 enStep:["First set the Career Palace major star and brightness","Translate the major star into the work task structure you are good at","Read assistant stars to confirm cooperation and mentor support","Read malefics and Ji to locate process friction and interference","Classify the promotion bottleneck into responsibility, exposure, cooperation or process","Strengthen evidence, adjust cooperation or change processes accordingly rather than waiting for fortune"],
 cnMis:['把事业宫直接等同于职位名称','升职卡住就空叹运不好，不细分瓶颈类型','只看主星，忽略辅星煞星带来的协作和流程问题'],
 enMis:["Equating the Career Palace directly with a job title","Sighing over bad fortune at a ceiling without breaking down the bottleneck type","Looking only at the major star and ignoring cooperation and process issues from assistants and malefics"],
 cnClose:'事业宫读的是「你怎么干活」，不是一张职位分配表。看清主星任务、辅星助力和煞星卡点，升职这件事就从碰运气变成了有方向的努力。',
 enClose:"The Career Palace reads how you work, not a job assignment table. See the major star's tasks, assistant support and malefic bottlenecks, and promotion moves from luck to directed effort."},

{cat:'yingyong',slug:'ziwei-caibogong-zhuanqian-liucun-xianjinliu',focus:'财帛宫的赚钱留存与现金流',focusEn:'earning, keeping and cash flow in the Wealth Palace',
 cnT:'财帛宫不是收入表：赚钱、留存与现金流要分开',enT:'The Wealth Palace Is Not an Income Statement: Separate Earning, Keeping and Cash Flow',
 cnD:'财帛宫写的是金钱使用与经营方式，进账多和留得住不是一回事；收入、留存、风险承受要分开，再结合命官田迁一起看。',
 enD:"The Wealth Palace writes how money is used and managed; high income and keeping it are not the same. Separate earning, retention and risk tolerance, then read it with the Life, Career, Property and Travel palaces.",
 cnL:'「我收入不低，为什么总存不下钱」——这是财帛宫最典型的问题。赚钱是一种能力，留住钱是另一种，中间还隔着现金流的节奏，三件事不能混为一谈。',
 enL:"I earn well, why can I not save is the classic Wealth Palace question. Earning is one ability and keeping money another, with cash-flow rhythm in between; the three cannot be conflated.",
 cnA:'月光、现金流紧张、高收入低留存，是三种不同的财务状况，对应星曜完全不同。把「财帛宫=有钱」这个等式拆掉，才看得清钱到底漏在哪一环。',
 enA:"Living paycheck to paycheck, cash-flow strain and high income with low retention are three different financial states with different stars. Breaking the equation Wealth Palace equals money shows where money leaks.",
 cnLog:['财帛宫更像金钱使用与经营方式，不是收入数字。','赚钱能力、留存能力、风险承受力要分开观察。','命宫、官禄、田宅、迁移会改变财帛的表现。','财务判断不能替代真实数据，以持牌机构和正规产品说明为准，不构成投资建议。'],
 enLog:["The Wealth Palace is more how money is used and managed than an income figure.","Earning ability, retention ability and risk tolerance must be observed separately.","The Life, Career, Property and Travel palaces change how Wealth expresses.","Financial reading cannot replace real data; rely on licensed institutions and official product terms, and this is not investment advice."],
 cnStep:['先定财帛宫主星和亮度','把主星翻译成赚钱的方式，而不是收入多少','看钱是怎么留住的，检查留存环节','看现金流节奏，识别紧张在哪个月','结合官禄看收入来源、田宅看资产沉淀、迁移看外部机会','针对月光、紧张、低留存分别做预算，以真实账目为准'],
 enStep:["First set the Wealth Palace major star and brightness","Translate the star into how you earn rather than how much","See how money is kept and check the retention step","Read the cash-flow rhythm to spot the strained months","Combine the Career for income sources, Property for asset accumulation and Travel for outside chances","Budget separately for paycheck-to-paycheck, strain and low retention, using real accounts"],
 cnMis:['把财帛宫直接当成收入高低','只看赚钱不看留存和现金流','用命理数字替代真实财务数据做决策'],
 enMis:["Treating the Wealth Palace directly as income level","Looking only at earning and not retention and cash flow","Using fortune numbers instead of real financial data for decisions"],
 cnClose:'财帛宫教你的是和钱相处的方式。把赚钱、留存、现金流分开看清，再以真实预算和正规产品为准，财务才会一步步稳起来。',
 enClose:"The Wealth Palace teaches your way of relating to money. Separate earning, retention and cash flow, then rely on real budgets and official terms, and finances gradually stabilize."},

{cat:'yingyong',slug:'ziwei-bingwu-sihua-zhichang-haiwai',focus:'丙午四化的职场与海外',focusEn:'the workplace and overseas dimensions of the Bing-Wu transformations',
 cnT:'丙午年机遇与陷阱：四化如何进入职场与海外行动',enT:'Bing-Wu Opportunities and Traps: How the Transformations Enter Work and Overseas Action',
 cnD:'天机化权可转译为决策和责任增加，年度四化要与职业场景和迁移议题结合；领导力和出行计划要分别看盘，案例需回完整命盘验证。',
 enD:"Tian-Ji Quan translates into added decisions and responsibility, and yearly transformations must combine with career scenarios and travel matters. Read leadership and travel plans separately, and verify cases on the full chart.",
 cnL:'丙午年的四化不是悬在天上的表，它会落到具体的事上：有人这一年被推上管理岗，有人要跑海外市场，机会和风险都藏在四化和宫位的交点里。',
 enL:"The Bing-Wu transformations are not a table in the sky but land on concrete matters: some are pushed into management and others into overseas markets, with opportunity and risk hidden where transformations meet palaces.",
 cnA:'要分清两件事：领导力的提升看事业宫和化权，出行与海外看迁移宫。混在一起读，就会把责任增加误读成奔波，或把出行风险误读成事业受阻。',
 enA:"Separate two matters: leadership growth through the Career Palace and Quan, and travel and overseas through the Travel Palace. Reading them together mistakes added responsibility for rushing about or travel risk for career blockage.",
 cnLog:['天机化权可被转译为决策和责任增加。','年度四化要与职业场景和迁移议题分别结合。','领导力看事业宫，出行海外看迁移宫，两事分读。','视频或案例需回到完整命盘验证，不能只取标题。'],
 enLog:["Tian-Ji Quan can be translated into added decisions and responsibility.","Yearly transformations must combine with career scenarios and travel matters separately.","Leadership is read through the Career Palace and overseas travel through the Travel Palace.","Cases must be verified on the full chart rather than taking only the title."],
 cnStep:['先确认丙午四化在本命的落宫','看天机化权是否引动事业宫，判断责任和决策变化','看迁移宫，判断出行和海外机会','把领导力和出行两件事分开列，避免混读','检查化忌在事业或迁移上的风险点','所有判断回完整命盘和大限验证，再安排行动'],
 enStep:["First confirm where the Bing-Wu transformations land in the natal chart","See whether Tian-Ji Quan activates the Career Palace, judging responsibility and decision changes","Read the Travel Palace to judge travel and overseas chances","List leadership and travel separately to avoid conflated reading","Check where Ji creates risk in career or travel","Verify all judgments on the full chart and decade before arranging action"],
 cnMis:['把化权简单等同于升职，忽略责任增加','事业和迁移混读，导致误判','只取案例标题，不回完整命盘验证'],
 enMis:["Equating Quan simply with promotion and ignoring added responsibility","Reading career and travel together and causing misjudgment","Taking case titles without verifying on the full chart"],
 cnClose:'丙午年的机会要在具体宫位里认领，风险也要在具体宫位里防范。领导力和海外行动分开看、回盘验证，这一年的步子才踩得稳。',
 enClose:"Bing-Wu opportunities are claimed in specific palaces and risks guarded in specific palaces. Read leadership and overseas action separately and verify on the chart, and this year's steps stay steady."},

{cat:'yingyong',slug:'ziwei-xiabannian-huan-gongzuo-duixian',focus:'下半年换工作的兑现',focusEn:'making a job change in the second half pay off',
 cnT:'2026下半年换工作：从流年热度到岗位兑现',enT:'Changing Jobs in the Second Half of 2026: From Yearly Heat to Delivering on the Role',
 cnD:'换工作要把上半年的表达曝光和下半年的成果兑现分开，关键是作品、数据、案例是否齐全；不只看机会，还要看离开成本。',
 enD:"A job change separates the first half's expression and exposure from the second half's delivery; the key is whether works, data and cases are complete. Look not only at opportunity but at the cost of leaving.",
 cnL:'「下半年适不适合换工作」——流年给的只是热度，真正决定成败的是你拿什么去兑现。岗位不会因为流年好就自动给你，它要的是证据。',
 enL:"Whether the second half suits a change is only the heat the year provides; what decides it is what you bring to deliver. A role is not granted because the year is good; it asks for evidence.",
 cnA:'很多人只看到机会就跳，结果新岗位兑现不了。要算两笔账：手里的作品数据案例够不够，以及离开现在的位置会损失什么，热度和兑现之间就靠这些承接。',
 enA:"Many jump at opportunity and fail to deliver in the new role. Count two ledgers: whether your works, data and cases are enough, and what you lose leaving the current position; these bridge heat and delivery.",
 cnLog:['年度趋势要落到岗位证据和现金流。','换工作不只看机会，还要看离开成本。','热度与兑现之间需要作品、数据和案例承接。','流年仅作时间背景，匿名讨论不能当作验证案例。'],
 enLog:["Yearly trends must land on role evidence and cash flow.","A change looks not only at opportunity but at the cost of leaving.","Works, data and cases bridge heat and delivery.","The year is only timing background, and anonymous discussion cannot serve as a verified case."],
 cnStep:['先看流年和大限，确认换工作的时间背景','盘点作品、数据、案例四项证据是否齐全','评估新岗位的兑现要求，自己接不接得住','算离开成本：待遇、积累、机会损失','看现金流，确认过渡期能撑多久','证据齐、成本算清再跳，否则先在现岗位补证据'],
 enStep:["First read the year and decade to confirm the timing background for a change","Inventory whether works, data and cases, the key evidence, are complete","Assess what the new role requires to deliver and whether you can carry it","Count the leaving cost: pay, accumulated position and lost chances","Read cash flow to see how long the transition can last","Jump only when evidence is complete and costs are clear; otherwise first build evidence in the current role"],
 cnMis:['只看流年热度就裸辞跳槽','不盘点证据，新岗位兑现不了','忽略离开成本和现金流，过渡期陷入被动'],
 enMis:["Quitting on yearly heat alone","Not inventorying evidence and failing to deliver in the new role","Ignoring leaving cost and cash flow and becoming passive in transition"],
 cnClose:'换工作是把热度变成兑现的过程，不是看到机会就跳。证据齐全、成本算清、现金流稳，下半年的这次转身才会真正垫高你。',
 enClose:"A change turns heat into delivery, not a jump at first sight. With complete evidence, clear costs and steady cash flow, the second-half move truly raises your position."},

{cat:'yingyong',slug:'ziwei-shiye-hunyin-caifu-sanxian',focus:'事业婚姻财富三线联动',focusEn:'the three-line linkage of career, marriage and wealth',
 cnT:'事业、婚姻、财富三线怎么一起读，别再单宫断事',enT:'How to Read Career, Marriage and Wealth as Three Linked Lines Instead of One Palace',
 cnD:'事业、夫妻、财帛三宫互相牵动，婚姻影响精力分配、事业影响收入、财富影响家庭选择；三线合读才能解释一个人真实的生活权衡。',
 enD:"The Career, Spouse and Wealth palaces affect one another: marriage shapes energy allocation, career shapes income, and wealth shapes family choices. Reading the three lines explains real trade-offs in life.",
 cnL:'人不是分成事业、感情、钱三个独立格子的。一个人选择拼事业，关系就被挤压；结了婚，花钱和置业的逻辑就变了，这些权衡都写在三宫的联动里。',
 enL:"A person is not split into independent boxes of career, relationship and money. Choosing to push career squeezes the relationship; marrying changes the logic of spending and property, and these trade-offs are written in the linkage.",
 cnA:'单宫断事的问题在于，它解释不了「为什么事业一忙婚姻就出问题」「为什么买了房现金就紧」。答案藏在三条线的交点，要把宫位连起来读。',
 enA:"One-palace reading cannot explain why a busy career strains marriage or why buying a home tightens cash. The answer sits where three lines cross, and the palaces must be read connected.",
 cnLog:['事业宫写精力投向和收入来源。','夫妻宫写关系对精力和决策的牵引。','财帛宫写金钱如何支撑或限制前两件事。','三线联动才构成真实的生活权衡，单宫断事必然片面。'],
 enLog:["The Career Palace writes where energy goes and income comes from.","The Spouse Palace writes how the relationship pulls energy and decisions.","The Wealth Palace writes how money supports or limits the first two.","The three-line linkage forms real trade-offs, and one-palace reading is necessarily one-sided."],
 cnStep:['先分别定事业、夫妻、财帛三宫主星','看事业线：精力投向和收入来源','看婚姻线：关系如何牵引决策','看财富线：钱支撑还是限制了选择','找三宫的交点，识别彼此挤压或成全的地方','结合大限，判断当前阶段哪条线是主轴'],
 enStep:["First set the major stars of the Career, Spouse and Wealth palaces","Read the career line: energy direction and income source","Read the marriage line: how the relationship pulls decisions","Read the wealth line: whether money supports or limits choices","Find where the three palaces cross, identifying squeeze or support","Use the decade to judge which line is central in the current stage"],
 cnMis:['把事业婚姻钱当三件互不相关的事','只看一宫，解释不了生活里的连锁反应','三线不分主次，抓不住当前阶段的重心'],
 enMis:["Treating career, marriage and money as unrelated matters","Reading one palace and unable to explain chain reactions in life","Not ordering the three lines and missing the current stage's focus"],
 cnClose:'一个人的生活是一张联动的网，不是三道单选题。学会三线合读，你才看得懂自己那些「顾此失彼」的时刻到底是怎么来的。',
 enClose:"A life is a linked network, not three single-choice questions. Learn to read the three lines together and you understand where your win-some-lose-some moments really come from."},

{cat:'yingyong',slug:'ziwei-hehuo-jiaoyougong-hetong',focus:'合伙的交友宫与合同',focusEn:'partnership through the Friends Palace and contracts',
 cnT:'紫微斗数看合伙：交友宫、合同和股权要先分清',enT:'Reading Partnership in Zi Wei Dou Shu: Separate the Friends Palace, Contracts and Equity First',
 cnD:'合伙先看交友宫反映的合作关系与下属，再看契约文书；关系好不等于条款清楚，股权、分工、退出要落到白纸黑字，以专业律师意见为准。',
 enD:"Partnership first reads the Friends Palace for cooperation and subordinates, then contracts. Good relations do not mean clear terms; equity, roles and exits must be in writing, with a professional lawyer's advice as the standard.",
 cnL:'很多人合伙是因为关系好，最后散伙也是因为关系好却没把规矩说清。交友宫写的是你和伙伴的相处模式，但相处得好，替代不了合同和股权的安排。',
 enL:"Many partner because of good relations and later split for the same reason: the rules were never made clear. The Friends Palace writes how you and partners get along, but goodwill cannot replace contracts and equity.",
 cnA:'关键是把「关系」和「契约」分开。盘上交友宫吉，只说明容易合得来；真正决定合伙能不能走远的，是股权、分工、退出机制有没有写清楚，两者缺一不可。',
 enA:"The key is separating relationship from contract. A good Friends Palace only shows you get along; what decides whether the partnership lasts is whether equity, roles and exits are clear, both indispensable.",
 cnLog:['交友宫反映合作伙伴、下属和人际相处模式。','文书契约看文昌文曲等文书星和相关宫位。','关系好不等于条款清楚，股权分工退出要落到白纸黑字。','法律事项以专业律师和正规途径为准，命理只提供关系倾向。'],
 enLog:["The Friends Palace reflects partners, subordinates and the pattern of relating.","Contracts are read through document stars such as Wen-Chang and Wen-Qu and related palaces.","Good relations do not mean clear terms; equity, roles and exits must be in writing.","Legal matters follow a professional lawyer and proper channels; fortune reading only gives relationship tendencies."],
 cnStep:['先看交友宫，定合作伙伴的相处模式','看有没有煞星化忌，识别合作中的摩擦风险','看文书星，判断契约文书运','把股权、分工、决策机制逐项列清','设计退出和散伙条款，先小人后君子','所有条款请专业律师审核，再签字出资'],
 enStep:["First read the Friends Palace to set the pattern with partners","Check for malefics and Ji to identify friction risk in cooperation","Read document stars to judge contract fortune","List equity, roles and decision mechanisms item by item","Design exit and dissolution terms, settling rules before feelings","Have a professional lawyer review all terms before signing and investing"],
 cnMis:['凭关系好就合伙，不签清楚合同','把交友宫吉直接等同于合伙一定成','忽略退出机制，散伙时纠缠不清'],
 enMis:["Partnering on goodwill without a clear contract","Equating a good Friends Palace directly with partnership success","Ignoring exit mechanisms and becoming entangled at the split"],
 cnClose:'合伙是关系加契约的组合，缺哪一半都危险。盘上看清相处模式，纸面上写清股权退出，再以律师审核为准，合作才走得长远。',
 enClose:"Partnership combines relationship and contract, and missing either is dangerous. Read the relating pattern on the chart, write equity and exits on paper, and use lawyer review so cooperation lasts."},

{cat:'yingyong',slug:'ziwei-tiaocao-chuangye-liuren-sanchangjing',focus:'跳槽创业留任三场景',focusEn:'the three scenarios of moving, founding and staying',
 cnT:'跳槽、创业还是留任：三种场景分别看什么',enT:'Move, Found or Stay: What to Read in Each of the Three Scenarios',
 cnD:'跳槽看迁移与事业、创业命财官三方、留任看大限是否引动现岗位；三种选择评估维度不同，要分别盘资源、风险和时机。',
 enD:"A move reads Travel and Career, a founding reads the Life-Wealth-Career trine, and staying reads whether the decade activates the current role. The three choices have different dimensions, assessing resources, risk and timing separately.",
 cnL:'「我到底该不该动」——这个问题没有统一答案，因为跳槽、创业、留任是三种不同的棋局，看的宫位、算的风险、等的时机都不一样。',
 enL:"Should I make a move has no single answer, because moving, founding and staying are three different games with different palaces, risks and timing.",
 cnA:'常见的错误是用一套标准衡量三种选择。跳槽重点看外部机会和离开成本，创业重点看资源和风险承受，留任重点看现岗位还有没有被大限引动的空间。',
 enA:"The common error is using one standard for three choices. A move focuses on outside opportunity and leaving cost, founding on resources and risk tolerance, and staying on whether the current role still has room activated by the decade.",
 cnLog:['跳槽重点看迁移宫、事业宫和离开成本。','创业重点看命财官三方、资源储备和风险承受。','留任重点看大限是否引动现岗位、还有没有晋升空间。','三场景分开评估，再结合个人现金流和家庭责任决定。'],
 enLog:["A move focuses on the Travel and Career palaces and leaving cost.","Founding focuses on the Life-Wealth-Career trine, resource reserves and risk tolerance.","Staying focuses on whether the decade activates the current role and whether promotion room remains.","Assess the three scenarios separately, then decide using personal cash flow and family responsibility."],
 cnStep:['先判断眼前的机会属于跳槽、创业还是留任','若跳槽，看迁移事业，算外部机会和离开成本','若创业，看命财官三方，盘资源和风险承受','若留任，看大限是否引动现岗位','三种都叠现金流和家庭责任，算现实约束','选净收益和风险最匹配的一条，不盲目跟风'],
 enStep:["First judge whether the opportunity is a move, founding or staying","For a move, read Travel and Career and count outside opportunity and leaving cost","For founding, read the Life-Wealth-Career trine and assess resources and risk tolerance","For staying, see whether the decade activates the current role","Layer cash flow and family responsibility onto all three for real constraints","Choose the path whose net gain and risk best match, without blindly following trends"],
 cnMis:['用一套标准衡量跳槽创业留任','只看机会不看风险承受和现金流','盲目跟风创业或跳槽，不评估自己的盘'],
 enMis:["Using one standard for moving, founding and staying","Looking only at opportunity without risk tolerance and cash flow","Blindly following others into founding or moving without assessing your own chart"],
 cnClose:'跳槽、创业、留任没有绝对好坏，只有合不合你当下的盘。三种场景分开看清资源、风险和时机，选择才不会被情绪和别人的节奏带走。',
 enClose:"Moving, founding and staying have no absolute verdict, only whether they fit your current chart. Read resources, risk and timing separately for each so the choice is not driven by emotion or others' pace."},

{cat:'yingyong',slug:'ziwei-caibo-tianzhai-shouru-zichan',focus:'财帛田宅的收入与资产',focusEn:'income versus assets across the Wealth and Property palaces',
 cnT:'财帛宫和田宅宫要分开：收入是流量，资产是存量',enT:'Separate the Wealth and Property Palaces: Income Is Flow, Assets Are Stock',
 cnD:'财帛宫主收入和现金的流量，田宅宫主固定资产和家宅的存量；赚得多不等于资产厚，两者要结合现金流和负债一起看。',
 enD:"The Wealth Palace governs the flow of income and cash, and the Property Palace the stock of fixed assets and home. High earning does not mean thick assets; read the two together with cash flow and debt.",
 cnL:'「我赚得不少，为什么家底不厚」——因为收入和资产是两本账。财帛写的是每个月进进出出的流量，田宅写的是沉淀下来的存量，流量再大不沉淀也留不下。',
 enL:"I earn well, why are my assets thin, because income and assets are two ledgers. Wealth writes the monthly flow in and out, and Property the settled stock; however large the flow, without settling it does not stay.",
 cnA:'要分清的是「赚钱」和「攒家底」。有人收入高却没资产，有人收入稳但靠房产慢慢变厚。看懂财帛和田宅的分工，才知道钱为什么没变成资产。',
 enA:"What must be separated is earning from building assets. Some have high income but no assets, and others steady income that thickens through property. Understanding the two palaces shows why money does not become assets.",
 cnLog:['财帛宫主收入和现金，是流量概念。','田宅宫主固定资产和家宅，是存量概念。','收入高不自动等于资产厚，要看沉淀和负债。','财务决策以真实数据、持牌机构和正规产品说明为准，不构成投资建议。'],
 enLog:["The Wealth Palace governs income and cash, a flow concept.","The Property Palace governs fixed assets and home, a stock concept.","High income does not automatically mean thick assets; look at accumulation and debt.","Financial decisions follow real data, licensed institutions and official product terms, and this is not investment advice."],
 cnStep:['先分别定财帛宫、田宅宫主星','看财帛线：收入和现金流量','看田宅线：固定资产和家底存量','检查流量有多少沉淀成了存量','把负债和现金流并进来，算净资产','以真实账目为准做规划，不靠命理数字下判断'],
 enStep:["First set the major stars of the Wealth and Property palaces","Read the Wealth line: income and cash flow","Read the Property line: fixed assets and home stock","Check how much flow has settled into stock","Bring in debt and cash flow to calculate net assets","Plan from real accounts rather than fortune numbers"],
 cnMis:['把收入和资产混为一谈','只看财帛进账，不看田宅沉淀和负债','用命理判断替代真实的资产盘点'],
 enMis:["Conflating income and assets","Looking only at Wealth income and not Property accumulation and debt","Replacing a real asset inventory with fortune reading"],
 cnClose:'收入是一阵子的流量，资产是留下来的存量。把财帛和田宅分开读、把负债现金流算清，再以真实数据为准，钱才会真正变成你的家底。',
 enClose:"Income is temporary flow and assets are kept stock. Read Wealth and Property separately, account for debt and cash flow, and rely on real data so money truly becomes your foundation."}
];
