// 2026-09-26 调研驱动 第1组：看盘方法6 + 四化2 = 8篇
// 观点框架来自当日同行研究卡，正文原创改写，无来源痕迹。
module.exports=[
// ========== 看盘方法 6 ==========
{cat:'kanpan',slug:'ziwei-konggong-jiexing-zhengju-buneng-chongfu-jisuan',focus:'空宫借星的证据',focusEn:'borrowed stars in an empty palace',
 cnT:'紫微斗数空宫借星：借来的星不能当本宫证据重复算',enT:'Borrowed Stars in an Empty Palace: Don\'t Count Them Twice in Zi Wei Dou Shu',
 cnD:'某宫没有十四主星时，可借对宫主星做结构参考，但借星只是参考，不能当本宫实驻再算一次吉凶，否则同一颗星被重复加权、结论虚高。',
 enD:"When a palace holds no major star, you may reference the opposite palace's star for structure, but it is only a reference. Treating it as a resident star and weighing it again doubles one star and inflates the verdict.",
 cnL:'很多人看到自己某宫是空的就慌，听到「借对宫」又把对宫那颗星原封不动搬过来，本宫算一遍、对宫又算一遍，等于一颗星当了两次用。',
 enL:"People panic at an empty palace, then borrow the opposite star and count it in both places, so one star does the work of two.",
 cnA:'真正要分清的是两类证据：本宫自己坐了什么、会照了什么，是本宫的直接证据；对宫那颗星，只是隔着中轴线的间接参考，分量要打折，更不能重复记账。',
 enA:"Separate two kinds of evidence: what the palace itself holds and receives is direct, while the opposite star is an indirect reference across the axis, weighted less and never double-booked.",
 cnLog:['空宫指本宫没有十四主星，不等于这一宫作废，辅星、煞星和四化仍然在本宫起作用。','借对宫主星是为了给本宫一个性格与结构的参照，理解「这件事大致受什么力量牵引」。','借星不能当本宫实驻：对宫那颗星在它自己宫里已经算过一次，搬到本宫只能算参考分，不能再给满权重。','判断时先列本宫自有证据，再附注对宫参考，两者分开写，吉凶才不会被同一颗星放大。'],
 enLog:["An empty palace holds no major star but is not void; its assistant stars, malefics and transformations still act there.","Borrowing the opposite star gives the palace a structural reference for the force that pulls the matter.","A borrowed star is not a resident one: it is already counted in its own palace and only earns partial reference weight here.","List the palace's own evidence first, note the opposite reference separately, and no single star gets magnified."],
 cnStep:['先确认该宫是否真的没有十四主星，别漏看辅星','再找正对面的对宫主星，作为结构参考','把本宫自有的辅星、煞星、四化先列全，这是直接证据','对宫借来的星单独标注为「参考」，权重打折，不重复计','拉本宫三方四正，看整体净效果而不是只靠借来的一颗星','最后下结论时，明确哪些是本宫证据、哪些是借星参考'],
 enStep:["Confirm the palace truly has no major star without overlooking assistant stars","Find the opposite palace's major star as a structural reference","List the palace's own assistant stars, malefics and transformations as direct evidence","Mark the borrowed star as a partial reference rather than counting it again","Open the palace triple-direction for the net effect instead of relying on one borrowed star","When concluding, state clearly which evidence is native and which is borrowed"],
 cnMis:['把空宫当作废，不敢再论这一宫的事','把对宫借星当本宫实驻，同一颗星重复加权','只靠借来的一颗星下结论，忽略本宫自有的辅煞与四化'],
 enMis:["Treating an empty palace as void and refusing to read it","Taking the borrowed star as resident and double-weighting it","Concluding from one borrowed star while ignoring the palace's own stars"],
 cnClose:'借星是帮你理解空宫的一把尺子，不是让你把一颗星算两次。证据分清，空宫一样能读得准。',
 enClose:"Borrowing is a ruler for understanding an empty palace, not a license to count a star twice. Keep the evidence distinct and an empty palace reads just as clearly."},

{cat:'kanpan',slug:'ziwei-wenti-daoxiang-zhi-dakai-xiangguan-gongwei',focus:'问题导向的宫位调用',focusEn:'problem-driven palace selection',
 cnT:'紫微斗数问题导向读法：一次只打开和问题相关的宫位',enT:'Problem-Driven Reading in Zi Wei Dou Shu: Open Only the Palaces Your Question Needs',
 cnD:'十二宫是一套按问题调用的工具箱：问财开财帛一线、问事业开官禄一线，一次只开与问题相关的共享宫系，不把所有对宫关系全叠上。',
 enD:"The twelve palaces are a toolbox opened by question: wealth opens the wealth line, career the career line. Open only the shared palaces your question needs rather than stacking every opposite relationship.",
 cnL:'新手容易一上来把十二宫连同所有对宫全摊开，结果信息太多、互相干扰。其实应该先问清楚「你到底想解决什么」，再按需开宫。',
 enL:"Beginners spread out all twelve palaces and every opposite at once, drowning in noise. First clarify what you want to solve, then open palaces as needed.",
 cnA:'这就像看病：头疼不会把全身每个器官都查一遍。读盘也是，问题定了，相关的宫位才浮出来，硬把不相关的宫位叠进来，结论反而被稀释。',
 enA:"It is like seeing a doctor: a headache does not trigger a scan of every organ. Once the question is set, the relevant palaces surface; forcing in unrelated ones dilutes the answer.",
 cnLog:['十二宫不是每次都要全读，而是按问题类型调用的共享宫系。','问财运开财帛—福德—田宅，问事业开官禄—夫妻—财帛，问感情开夫妻—福德—迁移。','本宫与对宫、三合构成一个议题单位，问题不同，调用的单位也不同。','一次只开一条线，读透了再开下一条，避免多线信息互相打架。'],
 enLog:["The twelve palaces are not all read every time; shared systems are called by the type of question.","Wealth opens Wealth-Karma-Property, career opens Career-Spouse-Wealth, and relationships open Spouse-Karma-Travel.","The home palace, its opposite and trines form one topic unit, and different questions call different units.","Read one line fully before opening the next so multiple lines do not fight each other."],
 cnStep:['先把对方的问题归类：财、事业、感情、健康还是家庭','按问题确定要打开的核心宫位','沿对宫与三合，把这条线上的相关宫位一起打开','列出这条线上的主星、辅煞与四化','只读这一条线并算净效果，不叠加无关宫位','一条线结论清楚后，若还有别的问题，再另开一条线'],
 enStep:["Classify the question: wealth, career, relationship, health or family","Set the core palace the question needs","Open the related palaces along its opposite and trine line","List the major stars, assistants, malefics and transformations on that line","Read only this line for its net effect without stacking unrelated palaces","Once one line is clear, open another line only if another question remains"],
 cnMis:['不管问什么都把十二宫全摊开，信息过载','把不相关的对宫关系硬叠进来，干扰主线','一条线没读透就同时开好几条，结论互相矛盾'],
 enMis:["Spreading out all twelve palaces regardless of the question","Forcing unrelated opposite relationships into the main line","Opening several lines before reading one through, producing contradictions"],
 cnClose:'问题导向，是让盘为你的疑问服务，而不是让你淹没在星曜里。一次一线，读得少反而读得准。',
 enClose:"Problem-driven reading makes the chart serve your question instead of burying you. One line at a time means reading less but reading accurately."},

{cat:'kanpan',slug:'ziwei-dingpan-hedui-wangwang-dashi-buzou',focus:'定盘与大事核对',focusEn:'chart verification against past events',
 cnT:'紫微斗数定盘步骤：用过往大事把盘核对准再读',enT:'How to Verify a Zi Wei Dou Shu Chart Using Past Events Before Reading',
 cnD:'盘排出后先别急着断，要用性格、升学、搬家、转职、婚变等过往大事的应期反推时辰与格局，对得上才说明盘准，再开始解读。',
 enD:"Do not judge a freshly cast chart at once. Use personality and the timing of past events such as schooling, moves, job changes and marriage to reverse-check the hour and pattern before interpreting.",
 cnL:'同样的出生时间，时辰差一点整张盘就移位。最可靠的校对办法不是再算一遍，而是拿已经发生的大事去对，看盘上能不能看出那些应期。',
 enL:"A small error in the birth hour shifts the whole chart. The most reliable check is not recalculating but matching major events that already happened against the chart.",
 cnA:'很多人排完盘直接问未来，结果盘本身可能就是错的。先往后看、把过往对清楚，盘立住了，往前看才有底气。',
 enA:"Many ask about the future from a chart that may itself be wrong. Verify the past first; once the chart stands, looking forward is trustworthy.",
 cnLog:['定盘是排盘与解读之间的必经校对环节，用来确认时辰与宫位无误。','用性格先对命宫主星，再用升学、搬家、转职、婚变、伤病等大事的年份对大限流年。','若大事对不上，优先怀疑时辰偏差或闰月、子时处理，调整后再对。','多次大事都能对应，才算盘定得准，之后的解读才有根基。'],
 enLog:["Chart verification is the mandatory check between casting and reading, confirming the hour and palaces.","Match personality to the Life star, then match years of schooling, moves, job changes, marriage and illness to the decade and year.","If events do not match, first suspect the hour, leap month or midnight handling, adjust, and recheck.","Several events matching in a row means the chart is set and later interpretation has a foundation."],
 cnStep:['先按所给生辰排出完整盘','用性格、脾气对命宫主星，初步判断方向','列出本人记得的几件大事及年份','逐件去对大限、流年的宫位与四化','对不上就检查时辰、闰月、子时并调整重对','多件大事都对应后，确认盘准，再开始正式解读'],
 enStep:["Cast the full chart from the given birth data","Match personality and temperament to the Life star for an initial direction","List the major events the person remembers and their years","Match each to the decade and yearly palaces and transformations","If they fail, check the hour, leap month and midnight, then adjust and recheck","Once several events match, confirm the chart and begin the formal reading"],
 cnMis:['排完盘不做定盘，直接在可能错的盘上断未来','只对一件小事就认定盘准，忽略多次校验','大事对不上也不怀疑时辰，硬往下解读'],
 enMis:["Reading the future from an unverified, possibly wrong chart","Trusting the chart after one small match instead of repeated checks","Ignoring hour error when events do not match and reading on anyway"],
 cnClose:'定盘是慢功夫，却决定了后面一切准不准。盘核对准了，再往前看，每一句话才落得住。',
 enClose:"Verification takes patience but decides everything that follows. Once the chart is checked and set, every forward statement holds."},

{cat:'rumen',slug:'ziwei-wuxingju-erju-wuxing-zenme-ding',focus:'五行局的定法',focusEn:'determining the Five-Element phase',
 cnT:'紫微斗数五行局怎么定：二局到六局决定几岁起运',enT:'How to Determine the Five-Element Phase in Zi Wei Dou Shu: Phase Two Through Six Sets the Starting Age',
 cnD:'五行局由命宫干支的纳音五行定，分水二、木三、金四、土五、火六局，局数决定阳男阴女顺逆排大限时几岁起运，是排大限的前置。',
 enD:"The Five-Element phase is set by the nayin of the Life Palace stem-branch: Water phase two, Wood three, Metal four, Earth five and Fire six. The number sets the age the decade limits begin and precedes casting them.",
 cnL:'初学者常被「水二局、木三局」绕晕，其实它回答一个很具体的问题：你几岁开始走第一步大限。',
 enL:"Beginners are confused by Water-two and Wood-three, but these answer one concrete question: the age your first decade limit begins.",
 cnA:'五行局不是又一个抽象概念，而是排盘的一道工序——命宫纳音定局，局数定起运岁数，跳过它，大限的起止年龄就排不对。',
 enA:"The phase is not another abstract idea but a casting step: the Life Palace nayin sets the phase, the phase sets the starting age, and skipping it misplaces the decades.",
 cnLog:['五行局依命宫所在干支的纳音五行而定，共水二、木三、金四、土五、火六局五种。','局数对应起运岁数：水二局二岁起运、木三三岁、金四四岁、土五五岁、火六六岁。','再依阳男阴女、阳女阴男确定大限顺行或逆行。','定了五行局与起运岁数，逐宫排每十年的大限才有依据。'],
 enLog:["The phase follows the nayin of the Life Palace stem-branch: Water two, Wood three, Metal four, Earth five and Fire six.","The number sets the starting age: Water at two, Wood at three, Metal at four, Earth at five and Fire at six.","Then the decade runs forward or backward by whether a male or female is yang or yin.","With the phase and starting age set, the ten-year decades can be placed palace by palace."],
 cnStep:['先排出命宫及其天干地支','查命宫干支对应的纳音五行','据纳音确定是水二至火六的哪一局','由局数确定几岁起运','按性别与年干阴阳定大限顺行或逆行','从命宫起逐宫排各步大限，再开始解读'],
 enStep:["Cast the Life Palace and its stem-branch","Look up the nayin element of that stem-branch","Set the phase from Water-two through Fire-six","Use the phase number to set the starting age","Set the decade direction by sex and the yin-yang of the year stem","Place the decades palace by palace from the Life Palace before interpreting"],
 cnMis:['把五行局当成抽象玄学，不明白它定起运岁数','跳过纳音直接猜局，大限起止年龄全错','不分阳男阴女顺逆，大限方向排反'],
 enMis:["Treating the phase as abstract mysticism instead of the starting-age rule","Guessing the phase without the nayin and misplacing the decades","Ignoring the forward-or-backward rule by sex and yin-yang"],
 cnClose:'五行局是连接命宫和大限的一道桥。纳音定局、局定起运，这一步清楚，时间盘才排得顺。',
 enClose:"The phase is the bridge between the Life Palace and the decades. Nayin sets the phase and the phase sets the start; with this clear, the timing chart falls into place."},

{cat:'kanpan',slug:'ziwei-duogong-xiangsheng-ruhe-lian-xian',focus:'宫位间的相生连线',focusEn:'the supporting lines between palaces',
 cnT:'紫微斗数多宫相生怎么连线：看一件事靠谁成就',enT:'How to Connect the Supporting Lines Between Palaces in Zi Wei Dou Shu',
 cnD:'宫位不是孤立的点，沿三方四正和四化飞出去的方向，可把资源从一个宫连到另一个宫；连线成网，才看得出一件事是靠谁生助、被谁牵制。',
 enD:"Palaces are not isolated points. Along the triple-direction and the path of flying transformations, resources connect one palace to another. Drawing these lines into a network shows who supports a matter and who restrains it.",
 cnL:'单宫读得再细，也回答不了「这件事到底靠谁」。把相关宫位用线连起来，资源的来路和去路就清楚了。',
 enL:"However carefully you read one palace, it cannot answer who the matter relies on. Connecting the relevant palaces reveals where resources come from and go.",
 cnA:'很多人把宫位当成一排互不相干的格子，其实它们更像一张网——四化飞星就是网上的流向，顺着连线看，因果才连得起来。',
 enA:"Many treat the palaces as unrelated boxes, but they form a web; flying transformations are its currents, and following the lines connects cause and effect.",
 cnLog:['三方四正给出宫位间固定的连线骨架，对宫牵引、三合支援。','四化尤其化禄、化权飞出去的方向，标出资源与力量实际流动的路线。','本宫受生则有助、受冲受制则有阻，连线的方向决定一件事顺不顺。','把固定骨架与动态飞化叠起来，才看得出一件事靠哪个宫成就。'],
 enLog:["The triple-direction gives the fixed skeleton: the opposite pulls and the trines support.","The path of flying transformations, especially Lu and Quan, marks where resources and force actually flow.","A palace that is supported is helped and one that is clashed is blocked; the line direction sets whether the matter runs smoothly.","Layering the fixed skeleton over dynamic flying transformations shows which palace brings the matter about."],
 cnStep:['锁定要问的核心宫位','先用三方四正画出固定的连线骨架','再看四化从哪些宫飞出、飞入哪些宫','沿连线标出资源的来路与去路','看本宫是受生助还是受冲制，算净效果','把整张网连起来，判断这件事靠谁成就、被谁牵制'],
 enStep:["Lock the core palace in question","Draw the fixed skeleton using the triple-direction","See which palaces the transformations fly from and into","Mark the incoming and outgoing resource paths along the lines","Check whether the core palace is supported or clashed for the net effect","Connect the whole network to judge who achieves the matter and who restrains it"],
 cnMis:['把宫位当孤立格子，不做连线','只看固定三方，不看四化飞化的动态流向','连线太多没有主次，抓不住真正生助的那个宫'],
 enMis:["Treating palaces as isolated boxes with no lines","Reading only the fixed trines and ignoring dynamic flying transformations","Drawing too many lines without priority, missing the palace that truly helps"],
 cnClose:'学会连线，看盘就从「看格子」升级成「看网络」。一件事从来不是一个宫定的，顺着相生的线，答案自己会浮出来。',
 enClose:"Connecting lines moves you from reading boxes to reading a network. No matter is decided by one palace; follow the supporting lines and the answer surfaces."},

{cat:'faq',slug:'ziwei-shichen-bu-qing-ruhe-zhunque-dingpan',focus:'时辰不清的校正',focusEn:'correcting an uncertain birth hour',
 cnT:'出生时辰不清怎么办：多线索把时辰校正准',enT:'What to Do When the Birth Hour Is Uncertain: Correcting It with Multiple Clues',
 cnD:'出生时辰宜精确到约半小时，偏差一个时辰十二宫整体移位；时辰模糊时，可用头顶旋、脸型、手足排行与过往大事综合校正，再配合定盘确认。',
 enD:"The birth hour should be accurate to about half an hour; one shichen off shifts all twelve palaces. When it is unclear, combine the hair whorl, face shape, sibling-birth order and past events, then confirm by chart verification.",
 cnL:'不少人只知道自己「大概傍晚生」，这种模糊时辰直接排盘风险很大。好在命理上留下了不少辅助线索，可以一点点把时辰收窄。',
 enL:"Many know only that they were born around evening, and casting from such a vague hour is risky. Fortunately, several supporting clues can narrow it down.",
 cnA:'要强调的是：时辰不能靠猜。单一线索都不够准，要把生理特征、家中排行和过往大事几类证据交叉用，指向同一个时辰才作数。',
 enA:"The hour cannot be guessed. No single clue is enough; cross physical traits, birth order and past events so several evidence types point to the same hour.",
 cnLog:['一个时辰管两小时，时辰差一格，命宫与十二宫整体移动，结论随之大变。','辅助线索包括头顶旋的位置与个数、脸型脸型方圆、手足中指尖与长短、家中兄弟姐妹排行。','再用升学、搬家、转职、婚变等过往大事的应期反推时辰。','几类线索一致指向同一时辰，并经定盘复核，才算校正准确。'],
 enLog:["One shichen spans two hours; one shift off moves the Life Palace and all twelve positions, changing the verdict.","Supporting clues include the hair whorl position and count, the shape of the face, the fingers and toes, and sibling-birth order.","Then reverse-check the hour using the timing of schooling, moves, job changes and marriage.","Several clue types pointing to one hour, confirmed by verification, make the correction accurate."],
 cnStep:['先收集已知的出生时间范围，越细越好','用头顶旋、脸型、手足等生理特征初步收窄','参考家中兄弟姐妹排行对应的时辰口诀','用几件过往大事的应期反推候选时辰','把几类线索交叉，取共同指向的那个时辰','按校正时辰排盘并做定盘复核，确认无误'],
 enStep:["Gather the known birth-time range as precisely as possible","Use the hair whorl, face shape and fingers or toes to narrow it","Reference the sibling-birth order clues","Reverse-check candidate hours using several past events","Cross the clue types and take the hour they all point to","Cast from the corrected hour and confirm by chart verification"],
 cnMis:['时辰模糊还硬猜一个直接排盘','只靠头顶旋或排行单一线索就定时辰','不拿过往大事复核，校正结果无法确认'],
 enMis:["Guessing an hour from vague information and casting at once","Fixing the hour from a single clue such as the hair whorl or birth order","Skipping past-event checks so the correction cannot be confirmed"],
 cnClose:'时辰是紫微的生命线，宁可多花时间用多线索校正，也不要在错时辰上排错盘、断错事。',
 enClose:"The hour is the lifeline of Zi Wei. Take time to correct it with multiple clues rather than casting and judging from the wrong hour."},

// ========== 四化 2 ==========
{cat:'sihua',slug:'ziwei-shengnian-sihua-yu-daxian-sihua-qubie',focus:'生年四化与大限四化',focusEn:'natal versus decade transformations',
 cnT:'紫微斗数生年四化和大限四化怎么分：底色与临时加减',enT:'Natal vs. Decade Transformations in Zi Wei Dou Shu: Baseline and Temporary Adjustments',
 cnD:'生年四化由出生年干定、是一辈子的先天底色；大限四化由所走大限的宫干定、是这十年的临时加减，两层要分开标，再看是否同宫共振。',
 enD:"Natal transformations come from the birth year stem and set a lifelong baseline; decade transformations come from the active decade's stem and make a ten-year adjustment. Mark the two layers separately, then check whether they resonate in one palace.",
 cnL:'同样叫「化禄」，生年带来的禄和这步大限带来的禄，分量和持续时间完全不同，混在一起看就会把一时的好运误当一辈子的资源。',
 enL:"The same Hua Lu from the birth year and from a decade differ in weight and duration; mixing them mistakes temporary luck for lifelong resources.",
 cnA:'关键是分层记账：先天那组四化是底盘，长期有效；大限那组是阶段性的，十年一换。两层若落在同一宫、指向同一件事，力量才会叠加放大。',
 enA:"Keep separate ledgers: the natal set is the long-term base and the decade set changes every ten years. Only when both layers land in one palace and point the same way does the force stack up.",
 cnLog:['生年四化依出生年天干，终生不变，写这张盘的先天基调与发力方向。','大限四化依当前所走大限的宫干，只管约十年，是阶段性加减。','两层分属不同时间尺度，不能用大限四化覆盖或替代生年四化。','当生年与大限四化同宫、同向时形成共振，该领域这十年特别强。'],
 enLog:["Natal transformations follow the birth year stem, stay for life, and set the chart's baseline tone and direction.","Decade transformations follow the active decade's stem, last about ten years, and make a stage adjustment.","The two layers run on different time scales; decade transformations never replace natal ones.","When natal and decade transformations share a palace and direction, they resonate and that area is especially strong for the ten years."],
 cnStep:['先标出出生年干对应的生年四化及落宫，作为底色','再确定当前走的是哪一步大限、该大限宫干是什么','标出大限四化及其落宫，作为这十年加减','两层分开列表，不互相替代','逐宫对照看是否有同宫、同向的共振','共振处重点看，非共振处区分长期与阶段，再下结论'],
 enStep:["Mark the birth-year natal transformations and palaces as the baseline","Determine the active decade and its stem","Mark the decade transformations and palaces as the ten-year adjustment","List the two layers separately without replacing one another","Check palace by palace for same-palace, same-direction resonance","Focus on resonance and separate long-term from stage effects elsewhere before concluding"],
 cnMis:['把生年四化和大限四化混为一层','用十年一换的大限四化当终生定局','不会看两层同宫共振，低估或高估了力量'],
 enMis:["Mixing natal and decade transformations into one layer","Taking decade transformations, which change every ten years, as lifelong","Missing same-palace resonance and over- or under-estimating the force"],
 cnClose:'分清两层四化，是把「一辈子的牌」和「这十年的手气」分开看。底色长期在，加减阶段性，叠对了才看得准。',
 enClose:"Separating the two layers divides your lifelong cards from this decade's luck. The baseline lasts and adjustments are temporary; stack them right to read accurately."},

{cat:'sihua',slug:'ziwei-lu-ji-duichong-ruhe-kan',focus:'禄忌对冲',focusEn:'Lu and Ji clashing across the axis',
 cnT:'紫微斗数禄忌对冲怎么看：资源与牵挂隔宫拉锯',enT:'How to Read Lu and Ji Clashing Across the Axis in Zi Wei Dou Shu',
 cnD:'化禄与化忌分落对宫时，是资源与牵挂隔着中轴线拉锯，常表现为一件事这边进、那边出；要算净流向，不能只盯着禄或只盯着忌。',
 enD:"When Lu and Ji land in opposite palaces, resources and concern pull across the axis, often showing gain on one side and outflow on the other. Read the net flow rather than fixating on only Lu or only Ji.",
 cnL:'有人盘上明明见禄，钱却留不住，往往是对宫那颗忌在拉扯——这边得到，那边牵挂或支出，两头都要看。',
 enL:"Some see Lu yet cannot keep money, often because the opposite Ji pulls: gain here and concern or spending there. Both ends must be read.",
 cnA:'禄忌冲不是简单的「先得后失」，而是一种结构性的进出关系。真正要算的是：禄进来的，够不够填忌那边持续的投入，净下来是正是负。',
 enA:"The Lu-Ji clash is not simply gain then loss but a structural in-and-out. The real question is whether what Lu brings covers the ongoing investment Ji demands and whether the net is positive.",
 cnLog:['禄忌对冲指化禄、化忌分处一对对宫，沿中轴线互相拉扯。','化禄那一宫给资源、机会或获得，化忌那一宫给牵挂、支出或反复投入。','表现为同一类事在两个相关领域一进一出，需合看净流向。','若禄强于忌、且有吉星扶，净效果仍可为正；忌重禄轻，则来得多去得也多。'],
 enLog:["Lu-Ji clash means Lu and Ji sit in opposite palaces and pull along the axis.","The Lu palace gives resources, opportunity or gain, while the Ji palace brings concern, spending or repeated investment.","It shows one kind of matter flowing in through one area and out through another, so read the net flow.","If Lu outweighs Ji with auspicious support the net can be positive; if Ji is heavier, much comes in but much also goes."],
 cnStep:['先找出化禄与化忌分别落在哪两个宫','确认两宫是否构成对宫关系','分别看禄宫给了什么资源、忌宫要什么投入','沿中轴线理解这一进一出的拉锯','比较禄与忌的轻重及吉星扶持，算净流向','据净效果给条件式建议，而不是断「先得后失」'],
 enStep:["Find which two palaces Lu and Ji land in","Confirm whether they form an opposite pair","Read what resources the Lu palace gives and what investment the Ji palace demands","Understand the in-and-out pull along the axis","Compare the weight of Lu and Ji and any auspicious support for the net flow","Give conditional advice from the net effect rather than declaring gain then loss"],
 cnMis:['见禄就断好，忽略对宫忌的拉扯','见禄忌冲就套「先得后失」的老话，不细算','只看一宫，不把对宫的进出合起来算净流向'],
 enMis:["Declaring good fortune at Lu and ignoring the opposite Ji","Applying the gain-then-loss cliche without detailed calculation","Reading one palace and failing to combine the in-and-out into a net flow"],
 cnClose:'禄忌对冲是一道进出账，不是非黑即白。把两头的资源与牵挂摊开算净额，才知道这件事到底留不留得住。',
 enClose:"The Lu-Ji clash is a balance sheet, not black and white. Spread out the resources and concern on both sides, total the net, and you see whether the matter holds."}
];
