// 2026-09-26 调研驱动 第2组：四化3 + 格局4 + 主星1 = 8篇
module.exports=[
// ========== 四化 3 ==========
{cat:'sihua',slug:'ziwei-shuangji-xianghui-bu-shi-jueselu',focus:'双忌相会',focusEn:'two Ji transformations meeting',
 cnT:'紫微斗数双忌相会怎么看：两处课题叠加不是绝路',enT:'Two Ji Transformations Meeting in Zi Wei Dou Shu: Stacked Lessons, Not a Dead End',
 cnD:'两颗化忌在三方会照，是两个领域的牵挂与课题叠加、关注度加倍；若主星庙旺、有禄权调和，反而是深耕之处，吉凶要看缓冲与承接。',
 enD:"When two Ji meet across the trine, concerns from two areas stack and attention doubles. If the major star is exalted and Lu or Quan mediates, it can instead become a place of deep cultivation; look for buffer and capacity.",
 cnL:'一看到「双忌」两个字，很多人先把自己吓住。其实双忌只是要你同时处理两件相关的功课，不等于无路可走。',
 enL:"At the words double Ji, many frighten themselves first. It only means working on two related lessons at once, not that no path remains.",
 cnA:'关键看有没有缓冲：主星有没有力、三方有没有禄权来调和、大限是不是走到帮你的位置。条件不同，同样是双忌，结果可以差很远。',
 enA:"The key is buffer: whether the major star is strong, whether Lu or Quan mediates in the trine, and whether the decade supports you. With different conditions, the same double Ji ends very differently.",
 cnLog:['双忌指两颗化忌在三方四正会照，使相关领域的牵挂与反复投入加倍。','它提示这是人生必须长期面对、认真处理的区域，而非判其必败。','若主星庙旺、有化禄化权调和，双忌的专注力可转为深耕与专业。','若主星落陷、又逢空劫煞星而无缓冲，才表现为反复受阻，需收缩与求助。'],
 enLog:["Double Ji means two Ji meet across the triple-direction, doubling concern and repeated investment in the related area.","It marks a region to face long term and handle carefully rather than one that must fail.","If the major star is exalted and Lu or Quan mediates, the doubled focus can become deep, professional cultivation.","Only when the star falls and empty or malefic stars bring no buffer does it show repeated blockage, requiring contraction and help."],
 cnStep:['先确认两颗化忌各自落在哪宫、被作用的是哪两颗星','看两宫是否在三方四正相会、共同指向什么议题','查主星庙旺落陷，判断有没有承受力','找三方有无化禄、化权或吉星来缓冲调和','有缓冲则把加倍的专注导向深耕，无缓冲则收缩、守界、求助','叠大限看这组课题在哪个阶段最紧、何时松动，再下结论'],
 enStep:["Confirm which palaces the two Ji land in and which stars they act on","See whether they meet across the triple-direction and what topic they share","Check the stars' brightness to gauge capacity","Look for Lu, Quan or auspicious stars in the trine as buffer","With buffer, direct the doubled focus to deep work; without it, contract, hold boundaries and seek help","Layer the decade to see when the topic is tightest and when it loosens before concluding"],
 cnMis:['一见双忌就判绝路，先把自己吓瘫','不看主星强弱与禄权缓冲，一律按大凶处理','把双忌的加倍专注当坏事，忽略它可转为深耕'],
 enMis:["Declaring a dead end at double Ji and becoming paralyzed","Ignoring star strength and Lu-Quan buffer and treating it all as disaster","Taking the doubled focus as bad while missing that it can become deep work"],
 cnClose:'双忌是加倍的功课，不是加倍的判决。先看有没有缓冲和承接，再决定是深耕还是收缩，绝路往往是被吓出来的。',
 enClose:"Double Ji is doubled homework, not a doubled verdict. Check buffer and capacity before choosing deep work or contraction; the dead end is often imagined from fear."},

{cat:'sihua',slug:'ziwei-quan-ke-jie-ji-tiaojian',focus:'权科解忌的条件',focusEn:'the conditions for Quan and Ke to ease Ji',
 cnT:'紫微斗数权科解忌成立的条件：不是见了就自动化解',enT:'The Conditions for Quan and Ke to Ease Ji in Zi Wei Dou Shu',
 cnD:'化权给掌控力、化科给名分与缓冲，理论上可缓解化忌，但必须落在相关宫位、且当事人愿意采取行动；单见权科而不动，忌仍在。',
 enD:"Quan gives control and Ke gives standing and buffer, which can ease Ji in theory, but they must land in the relevant palaces and the person must act. Quan and Ke alone, with no action, leave Ji in place.",
 cnL:'不少人听到「有权星科星就能化解忌」就松一口气，却什么都不做。化解不是自动发生的，它给的是条件，不是结果。',
 enL:"Many relax on hearing that Quan and Ke can resolve Ji, then do nothing. Resolution is not automatic; they offer conditions, not results.",
 cnA:'要满足三个条件：权或科要落在和忌相关的宫位、要和忌形成会照而非无关、当事人要借这股力真正去处理。三者齐，忌才松动。',
 enA:"Three conditions must hold: Quan or Ke lands in a palace related to Ji, it meets Ji rather than sitting unrelated, and the person uses the force to actually handle it. With all three, Ji loosens.",
 cnLog:['化权提供掌控与推动，让人有能力主动处理忌的卡点。','化科提供名分、理性与缓冲，让卡点能被看见、被缓和。','权科须落在与忌相关的宫位并会照，错位则帮不上。','星曜只给条件，最终要靠当事人采取行动，单有星曜而不作为，化解不成立。'],
 enLog:["Quan supplies control and drive, giving the ability to actively handle Ji's blockage.","Ke supplies standing, reason and buffer, letting the blockage be seen and softened.","Quan and Ke must land in palaces related to Ji and meet it; misplaced stars cannot help.","Stars only give conditions, and the person must act; with stars but no action, resolution does not hold."],
 cnStep:['先定位化忌所在宫位与卡点内容','再找化权、化科落在哪宫','判断权科是否与忌相关、是否形成会照','化权看能否提供掌控力去推动处理','化科看能否给理性与名分做缓冲','确认当事人愿借权科之力行动，再判断忌能否化解'],
 enStep:["Locate Ji's palace and the blockage it contains","Find where Quan and Ke land","Judge whether they relate to Ji and meet it","For Quan, see whether it supplies control to drive the handling","For Ke, see whether it supplies reason and standing as buffer","Confirm the person will act through Quan and Ke before judging whether Ji resolves"],
 cnMis:['以为见了权科就自动化解，自己不行动','不看权科是否落在相关宫位，错位也硬说化解','把权科当万能，忽略忌仍需长期处理'],
 enMis:["Assuming Quan and Ke resolve things automatically without acting","Ignoring whether they land in related palaces and claiming resolution anyway","Treating Quan and Ke as universal while Ji still needs long-term work"],
 cnClose:'权科解忌，给的是「你有能力、有名分去处理」的条件，不是免费的赦免。条件够、肯行动，卡点才真正松动。',
 enClose:"Quan and Ke easing Ji give you the ability and standing to handle it, not a free pardon. With the conditions and the will to act, the blockage truly loosens."},

{cat:'sihua',slug:'ziwei-gonggan-feihua-ruhe-zhunque-an',focus:'宫干飞化的安法',focusEn:'placing palace-stem flying transformations',
 cnT:'紫微斗数宫干飞化怎么准确安：先定宫干再看飞入',enT:'How to Place Palace-Stem Flying Transformations Accurately in Zi Wei Dou Shu',
 cnD:'以各宫宫干再排四化，可看本宫四化飞入何宫、与生年四化如何呼应；飞化要先确认宫干起法与本宫自化，规则不清，飞星就越飞越乱。',
 enD:"Re-casting transformations with each palace's stem shows where that palace's transformations fly and how they echo the natal set. Confirm the palace-stem method and self-transformations first, or the flying stars become chaos.",
 cnL:'飞宫四化是进阶工具，用得好能看出一件事主动往哪推，但它的前提是宫干不能安错，错了后面全盘乱。',
 enL:"Palace-stem flying is an advanced tool that, used well, shows where a matter is actively pushed, but it depends on placing the palace stems correctly or the whole reading gets muddled.",
 cnA:'要守两个前提：一是各宫天干要按规则准确推出，二是分清本宫有没有自化。前提立住，再看四化飞出去落在哪宫，才有意义。',
 enA:"Hold two premises: each palace's stem must be derived by rule, and self-transformations in the home palace must be identified. With the premises set, seeing where the transformations fly becomes meaningful.",
 cnLog:['宫干飞化是以十二宫各自的天干再起四化，追踪本宫力量主动流向何处。','先要准确安各宫天干，天干错则飞化全错。','再辨本宫有无自化（本宫化星又落本宫），自化有其特殊含义。','飞入他宫的禄权科忌，显示该宫事务对他宫的生助或牵挂，须与生年四化合参。'],
 enLog:["Palace-stem flying re-casts transformations with each palace's stem to trace where its force actively flows.","First place each palace's stem accurately, or all flying transformations are wrong.","Then identify self-transformations, where a palace's transformed star lands back in itself, which carry special meaning.","Lu, Quan, Ke or Ji flying into another palace shows support or concern between palaces and is read with the natal set."],
 cnStep:['先排好十二宫并准确推出各宫天干','检查各宫有无自化，单独标注','取所问宫位的宫干，按天干起四化','追踪这四颗化星分别飞入哪些宫','看飞入方向与生年四化是呼应还是冲突','合参后判断该宫事务主动往哪推、牵挂什么'],
 enStep:["Cast the twelve palaces and derive each stem accurately","Check and separately mark any self-transformations","Take the asked palace's stem and cast its four transformations","Trace which palaces the four transformed stars fly into","See whether their direction echoes or conflicts with the natal transformations","Read together to judge where that palace's affairs are pushed and what concerns them"],
 cnMis:['宫干没安准就飞化，越飞越错','忽略本宫自化，漏读关键信息','飞化不与生年四化合参，结论片面'],
 enMis:["Flying transformations before the palace stems are correct","Overlooking self-transformations and missing key information","Reading flying transformations without the natal set, giving a one-sided verdict"],
 cnClose:'宫干飞化像顺着宫位追一笔主动的流向，前提是宫干和自化都要先理清。基础对了，飞星才飞得有方向。',
 enClose:"Palace-stem flying traces an active current from each palace, provided the stems and self-transformations are clear first. With the foundation right, the flying stars have direction."},

// ========== 格局 4 ==========
{cat:'geju',slug:'ziwei-yangliang-changlu-poge-wenshe-lucun-weizhi',focus:'阳梁昌禄的破格位置',focusEn:'the breaking positions of the Sun-Tianliang-Chang-Lu pattern',
 cnT:'紫微斗数阳梁昌禄格怎么算破：文昌禄存的位置是关键',enT:'How the Sun-Tianliang-Chang-Lu Pattern Breaks in Zi Wei Dou Shu: The Position of Wenchang and Lu',
 cnD:'太阳天梁在卯宫坐命为底，三方须会文昌、禄存（或化禄）方为正格；文昌只在对宫凑出、或见羊陀火铃空劫与生年忌即破格，禄的位置还要参看「梁禄招怨」之辨。',
 enD:"Sun and Tianliang in Mao are the base, and the trine must meet Wenchang and Lu (or Hua Lu) for the true pattern. Wenchang only in the opposite, or meeting Yang, Tuo, Fire, Ling, Empty or natal Ji, breaks it; Lu's position also bears on the Liang-Lu complaint.",
 cnL:'很多人一听「阳梁昌禄、传胪第一名」就往自己身上安，却没核对文昌、禄存到底在什么位置——位置一错，格就不成立。',
 enL:"Many claim the Sun-Tianliang-Chang-Lu first-place pattern without checking where Wenchang and Lu actually sit; the wrong position means the pattern does not hold.",
 cnA:'本站重点讲破格：文昌要真在三方会入而非对宫凑数，禄要落在能发挥的位置；古诀又说天梁不宜见禄、梁禄同躔多招是非，要说明禄在何宫、是否中和天梁的孤忌。',
 enA:"The focus is breaking: Wenchang must truly meet in the trine rather than being counted from the opposite, and Lu must sit where it works. Another maxim says Tianliang should not meet Lu as it draws complaint; state where Lu is and whether it balances Tianliang's austerity.",
 cnLog:['正格条件：太阳、天梁在卯宫坐命且庙旺，三方四正会文昌与禄存或化禄。','文昌须在三方会入；若只在对宫凑出，文星之力打折，多不按正格论。','见擎羊、陀罗、火星、铃星、地空、地劫或生年忌冲会，则为破格。','禄的位置需辩证：禄能中和天梁孤忌、利科考，但梁禄同躔又有招怨之嫌，宜看落宫与是否有制。'],
 enLog:["The true pattern needs Sun and Tianliang in Mao and exalted, with Wenchang and Lu (or Hua Lu) meeting in the trine.","Wenchang must meet in the trine; if it is only counted from the opposite, its force is discounted and it is not the true pattern.","Meeting Yang, Tuo, Fire, Ling, Empty or natal Ji breaks the pattern.","Lu's position is two-sided: it balances Tianliang's austerity and aids exams, yet Liang and Lu together may draw complaint, so check the palace and any restraint."],
 cnStep:['先确认太阳、天梁是否在卯宫坐命且庙旺','查三方四正是否真会文昌星','再查禄存或化禄的位置，看能否会入','注意文昌若只在对宫凑出，需打折看待','逐一排查羊陀火铃空劫与生年忌是否破格','结合「梁禄招怨」之辨，综合判断是否成格'],
 enStep:["Confirm Sun and Tianliang sit in Mao and are exalted","Check whether Wenchang truly meets in the trine","Then check the position of Lu (or Hua Lu) and whether it meets","Note that Wenchang counted only from the opposite is discounted","Check one by one whether Yang, Tuo, Fire, Ling, Empty or natal Ji break it","Combine the Liang-Lu complaint to judge whether the pattern forms"],
 cnMis:['见太阳天梁就安格名，不查文昌禄存位置','把对宫凑出的文昌当三方正会，高估格局','忽略破格煞忌与梁禄招怨的流派辩证'],
 enMis:["Naming the pattern at Sun-Tianliang without checking Wenchang and Lu","Taking opposite-palace Wenchang as a true trine meeting and overrating it","Ignoring breaking stars and the Liang-Lu school debate"],
 cnClose:'阳梁昌禄是好格，但成不成全看位置。文昌、禄存放对、无煞忌破，才是真「学霸格」；否则只是沾了个好名字。',
 enClose:"Sun-Tianliang-Chang-Lu is a fine pattern, but position decides it. Wenchang and Lu placed right with no breaking stars make a true scholar pattern; otherwise it is only a good name."},

{cat:'geju',slug:'ziwei-huotan-lingtan-baofa-sudu-yu-chixu',focus:'火贪与铃贪的差异',focusEn:'the difference between the Fire-Tan and Ling-Tan patterns',
 cnT:'紫微斗数火贪格和铃贪格差异：爆发快慢与持续长短',enT:'Fire-Tan vs. Ling-Tan in Zi Wei Dou Shu: Speed of Breakout and How Long It Lasts',
 cnD:'贪狼守命遇火星，爆发快、起势猛但持续力短；遇铃星则酝酿久、来得慢而较绵长；同宫为上、三方会照稍次，见擎羊陀罗与火星同度即不合格。',
 enD:"Tanlang in the Life Palace meeting Fire breaks out fast and strong but lasts briefly; meeting Ling brews longer, arrives slowly and runs more steadily. Same palace is best and trine meeting is lesser; Yang or Tuo with Fire disqualifies it.",
 cnL:'同样是「贪狼遇煞变横财」，火贪像爆燃、铃贪像慢炖，节奏完全不同，混为一谈就会误判兑现的时机。',
 enL:"Both turn Tanlang with a malefic into sudden wealth, but Fire-Tan is a flash fire and Ling-Tan a slow stew, with very different timing; conflating them misjudges when it pays out.",
 cnA:'还要看成格位置：火星、铃星与贪狼同宫最纯粹，仅在三方会照格局稍次；若另有擎羊、陀罗与火星同度，杂煞混局则不按此格论。',
 enA:"Position also matters: Fire or Ling sharing Tanlang's palace is purest, trine meeting is lesser, and if Yang or Tuo also shares Fire, the mixed malefics mean it is not this pattern.",
 cnLog:['火贪：贪狼守命遇火星同宫或三方会照，爆发力大、起势快，但持续力不久。','铃贪：贪狼遇铃星，酝酿时间长、爆发较缓，但后劲相对绵长。','两格都以同宫为最佳配置，仅三方会照者格局稍次。','若另有擎羊、陀罗与火星同度等杂煞，则格局不纯，不按正格论。'],
 enLog:["Fire-Tan: Tanlang meeting Fire in the same palace or trine breaks out strongly and quickly but does not last long.","Ling-Tan: Tanlang meeting Ling brews long and breaks more slowly with a steadier after-effect.","Both are best with same-palace meeting, while trine-only meeting is a lesser pattern.","If Yang or Tuo also shares Fire and mixes malefics, the pattern is impure and not the true form."],
 cnStep:['先确认贪狼是否守命（或在财官迁相关位）','看所遇是火星还是铃星，定火贪或铃贪','查火铃与贪狼是同宫还是仅三方会照','火贪重点防爆发后守不住、节奏短','铃贪重点看长期酝酿与后劲','排查有无擎羊陀罗等杂煞混局，综合判断'],
 enStep:["Confirm Tanlang guards the Life Palace (or a related Wealth, Career or Travel position)","See whether it meets Fire or Ling to set Fire-Tan or Ling-Tan","Check whether Fire/Ling shares Tanlang's palace or only meets in the trine","For Fire-Tan, guard against being unable to hold after the fast breakout","For Ling-Tan, look at the long brewing and after-effect","Check for mixed malefics such as Yang or Tuo before judging"],
 cnMis:['把火贪铃贪混为一格，不辨快慢','只看爆发不看持续力，火贪易昙花一现','忽略同宫与会照的差别及杂煞破格'],
 enMis:["Conflating Fire-Tan and Ling-Tan without distinguishing speed","Looking only at breakout and not duration, so Fire-Tan fades fast","Ignoring the same-palace vs. trine difference and mixed-malefic breaking"],
 cnClose:'火贪求快、铃贪求稳，关键是认清自己属于哪一种节奏。爆发力人人羡慕，但守得住、配得上持续力，才真成得了格。',
 enClose:"Fire-Tan seeks speed and Ling-Tan steadiness; recognize which rhythm is yours. Breakouts are admired, but holding them with matching staying power is what truly forms the pattern."},

{cat:'geju',slug:'ziwei-zhenjia-geju-ruhe-bianbie',focus:'真假格局的辨别',focusEn:'telling true patterns from false ones',
 cnT:'紫微斗数真假格局怎么辨：三个条件齐才算真格',enT:'How to Tell True Patterns from False in Zi Wei Dou Shu: Three Conditions Must Hold',
 cnD:'安一个格局前，先看主星是否得地、吉星是否真会照、有无煞忌空劫破格，三者齐才是真格；只沾格名而条件不全，是假格，别被名头带走。',
 enD:"Before naming a pattern, check whether the major star is well placed, auspicious stars truly meet, and malefics, Ji or Empty break it. All three make a true pattern; a name with incomplete conditions is false, so do not be led by the label.",
 cnL:'格局名字往往很好听，什么「贵格」「富格」，但名字不等于成立。新手最容易对号入座，却没逐项核对成格条件。',
 enL:"Pattern names sound attractive, noble or wealthy, but the name is not the formation. Beginners claim them without checking the conditions item by item.",
 cnA:'辨真假用三步：主星有没有力、吉星是不是真会到、煞忌有没有破。三步都过才认；缺任何一步，就算盘上沾了边，也只能按普通结构看。',
 enA:"Use three steps: is the major star strong, do auspicious stars truly meet, and do malefics or Ji break it. Pass all three to accept it; missing any step means an ordinary structure even if it resembles a pattern.",
 cnLog:['第一看主星是否得地、庙旺有力，主星弱则格局无主。','第二看所需吉星是否真在三方四正会照，而非勉强凑数。','第三看有无煞星、化忌、空劫冲破，有破格因素则降等或不算。','三条件齐方为真格，只占一两条而安格名，是假格。'],
 enLog:["First, the major star must be well placed and exalted; a weak star leaves the pattern without a head.","Second, the required auspicious stars must truly meet in the triple-direction rather than being forced.","Third, malefics, Ji or Empty must not break it; any breaking factor lowers or voids it.","All three conditions make a true pattern, while a name resting on only one or two is false."],
 cnStep:['先列出该格局的全部成格条件','查主星是否庙旺得地、有力量','逐一核对吉星是否真在三方会照','排查煞星、化忌、空劫有无破格','三条件齐则认真格，缺项则按普通结构看','不被格局名头影响，以实际净效果为准'],
 enStep:["List all the pattern's formation conditions","Check whether the major star is exalted and strong","Verify one by one that auspicious stars truly meet in the trine","Check whether malefics, Ji or Empty break it","Accept a true pattern only when all three hold, otherwise read an ordinary structure","Do not be swayed by the name; use the actual net effect"],
 cnMis:['见吉星组合就安格名，不核条件','只占一两条就认贵格，把假格当真','被格局好听的名头带着走，忽略煞忌破格'],
 enMis:["Naming a pattern at an auspicious combination without checking conditions","Taking one or two conditions as a noble pattern and treating false as true","Being led by an attractive name while ignoring breaking factors"],
 cnClose:'格局是结构的总结，不是许愿的标签。三步条件核清楚，真格假格一目了然，读盘才不会自己骗自己。',
 enClose:"A pattern is a summary of structure, not a wishful label. Check the three conditions and true versus false is clear, so the reading does not deceive itself."},

{cat:'geju',slug:'ziwei-geju-chengge-hou-sihua-ruhe-shengjiang',focus:'格局成格后的四化升降',focusEn:'how transformations raise or lower a formed pattern',
 cnT:'紫微斗数格局成格后，四化如何让它升级或降级',enT:'After a Pattern Forms in Zi Wei Dou Shu: How Transformations Raise or Lower It',
 cnD:'格局不是固定品级，逢禄权科引动则升级兑现，逢化忌、空劫冲则降级打折；同一格局在不同大限流年随四化起落，要动态看而非一评定终身。',
 enD:"A pattern is not a fixed grade. Meeting Lu, Quan or Ke raises it and brings it to fruition, while Ji or Empty lowers and discounts it. The same pattern rises and falls with transformations across decades and years, so read it dynamically.",
 cnL:'很多人把格局当成一个固定分数，成了格就以为一辈子稳了。其实格局更像一个基础盘，四化走到不同位置，它的品级会被抬升或压低。',
 enL:"Many treat a pattern as a fixed grade that, once formed, stays secure for life. It is more like a base that transformations raise or lower as they move.",
 cnA:'四化是格局的升降开关：禄权科在相关宫位引动，把潜力兑现；化忌、空劫来冲，则让成格的东西打折。判断时要看当前大限流年的四化落在哪。',
 enA:"Transformations are the raise-lower switch: Lu, Quan and Ke activating the relevant palaces realize potential, while Ji or Empty clashing discounts what formed. Check where the current decade and year transformations land.",
 cnLog:['格局给出先天结构的潜力，四化决定这潜力在某阶段能否兑现。','化禄、化权、化科在相关宫位引动，使格局升级、好处兑现。','化忌、空劫、煞星来冲，会使成格之处降级、爆发打折。','同一格局在不同大限流年品级起落，须结合时间层动态判断。'],
 enLog:["A pattern gives innate structural potential, and transformations decide whether it pays out in a given stage.","Lu, Quan or Ke activating relevant palaces raises the pattern and realizes its benefit.","Ji, Empty or malefics clashing lower the formed area and discount its breakout.","The same pattern rises and falls across decades and years and must be judged dynamically with the timing layers."],
 cnStep:['先确认格局本身是否成立、潜力在哪','再看当前所走大限的四化落宫','化禄权科引动相关宫则看升级兑现','化忌空劫来冲则防降级打折','再看流年四化定当年的升降触发','动态评估当前品级，不把格局当固定分数'],
 enStep:["Confirm the pattern itself forms and where its potential lies","Read the active decade transformations and palaces","If Lu, Quan or Ke activate relevant palaces, look for raised, realized benefit","If Ji or Empty clashes, guard against a lowered, discounted result","Read the yearly transformations for the current year's raise-lower trigger","Assess the current grade dynamically rather than treating the pattern as fixed"],
 cnMis:['把格局当固定品级，认为成格就一劳永逸','忽略四化对格局的升降作用','只看先天不看大限流年，错过兑现期或误判风险'],
 enMis:["Treating a pattern as a fixed grade that stays secure once formed","Ignoring how transformations raise and lower it","Looking only at the innate chart and missing the payout period or risk"],
 cnClose:'格局是底子，四化是开关。底子好还要时机引动，看清当前四化往哪拨，才知道这副好牌什么时候真正兑现。',
 enClose:"The pattern is the base and transformations the switch. A good base still needs timing; see which way the current transformations turn to know when the strong hand pays out."},

// ========== 主星 1 ==========
{cat:'zhuxing',slug:'ziwei-tianji-jumen-shuangxing-zhiye-renwu',focus:'天机巨门的职业任务',focusEn:'the career tasks of the Tian-Ji and Ju-Men pairing',
 cnT:'紫微斗数天机巨门双星：搭框架与做审计的职业任务对照',enT:'The Tian-Ji and Ju-Men Pairing in Zi Wei Dou Shu: Frame-Building and Auditing as Career Tasks',
 cnD:'天机负责搭框架、出方案，巨门负责追问、审计与表达，二者同宫适合咨询、研究、教学、内容与跨域沟通；用书面记录和截止时间治过度思考，卯宫偏教学表达、酉宫偏在压力中练深度。',
 enD:"Tian-Ji builds frameworks and plans while Ju-Men questions, audits and expresses. Together they suit consulting, research, teaching, content and cross-domain communication. Use written notes and deadlines to curb overthinking; Mao leans to teaching and expression, and You to depth forged under pressure.",
 cnL:'天机巨门是很典型的「脑力+口才」组合，一个负责想清楚、一个负责问到底，用在需要分析和表达的工作上特别出彩。',
 enL:"Tian-Ji and Ju-Men form a classic mind-plus-voice pairing: one thinks it through and the other presses to the bottom, shining in work that needs analysis and expression.",
 cnA:'这组最大的坑是想太多、说太绕，反复推翻自己。对治办法很具体：把想法写下来、设截止时间、分场景用——卯宫的人适合把复杂讲简单去教学，酉宫的人适合在质疑声里把问题钻深。',
 enA:"The biggest pitfall is overthinking and roundabout speech that repeatedly overturns itself. The concrete fix is writing ideas down, setting deadlines and matching the scene: Mao simplifies complexity to teach, while You drills deep amid questioning.",
 cnLog:['天机主智，善规划、联想与搭框架，提供方案与思路。','巨门主口舌与辨析，善追问、审计、质疑与表达，负责查漏与说清。','双星同宫把「想清楚」和「问到底」结合，宜咨询、研究、教学、内容、跨域沟通。','卯宫偏表达与教学，酉宫偏在压力与质疑中练深度；过度思考可用书面记录与截止时间约束。'],
 enLog:["Tian-Ji governs intellect and excels at planning, association and framework-building, supplying plans and ideas.","Ju-Men governs speech and analysis, excelling at questioning, auditing, doubting and expressing, checking gaps and making things clear.","The pairing combines thinking it through with pressing to the bottom and suits consulting, research, teaching, content and cross-domain work.","Mao leans to expression and teaching, You to depth under pressure and questioning; written notes and deadlines curb overthinking."],
 cnStep:['先确认天机、巨门同宫或在相关三方','分清自己更偏天机的规划还是巨门的辨析','把职业任务对照：咨询、研究、教学、内容、跨域沟通','卯宫者练把复杂讲简单、做教学表达','酉宫者练在质疑中钻深、做研究审计','用书面记录与截止时间治过度思考，再定职业方向'],
 enStep:["Confirm Tian-Ji and Ju-Men share a palace or meet in the related trine","Tell whether you lean to Tian-Ji's planning or Ju-Men's analysis","Match career tasks: consulting, research, teaching, content or cross-domain communication","Mao types practice simplifying complexity for teaching and expression","You types practice drilling deep under questioning for research and audit","Use written notes and deadlines to curb overthinking before choosing a direction"],
 cnMis:['只讲双星性格，不落到具体职业任务','放任想太多、说太绕，反复推翻自己','不辨卯酉差异，用错表达或研究的方向'],
 enMis:["Describing only the pairing's temperament without concrete career tasks","Indulging overthinking and roundabout speech that overturns itself","Ignoring the Mao-You difference and misusing expression or research"],
 cnClose:'天机巨门是一副「会想又会问」的好脑子，关键是把脑力落到具体任务上、用纪律治多想，分析与表达都能成为你的职业护城河。',
 enClose:"Tian-Ji and Ju-Men give a mind that both thinks and questions; the key is landing the intellect on concrete tasks and disciplining overthinking, so analysis and expression become your professional edge."}
];
