// 2026-09-26 调研驱动 第3组：主星2 + 辅煞2 + 流年4 = 8篇
module.exports=[
// ========== 主星 2 ==========
{cat:'zhuxing',slug:'ziwei-ziwei-zuoming-2026-guanlu-huaji-liu-zuhe',focus:'紫微坐命的官禄化忌组合',focusEn:'Ziwei Life Palace career-Ji combinations',
 cnT:'紫微坐命遇2026官禄化忌：六种组合的压力与出路',enT:'Ziwei in the Life Palace Meeting the 2026 Career Ji: Six Combinations, Their Pressure and Way Out',
 cnD:'丙午年廉贞化忌落在官禄轴是年度气候，紫微独坐、紫破、紫府、紫贪、紫相、紫杀六组对同一事业课题表现不同；分清组合，才知道压力出在哪、怎么解。',
 enD:"In the Bing-Wu year, Lian-Zhen Ji on the career axis is the yearly climate. Ziwei alone, Zi-Po, Zi-Fu, Zi-Tan, Zi-Xiang and Zi-Sha handle the same career topic differently; distinguishing them shows where the pressure lies and how to resolve it.",
 cnL:'同样是紫微坐命，有人这一年事业卡得难受、有人却借机重整，差别往往在紫微和谁同宫——年度化忌是共同的，但承接它的组合不一样。',
 enL:"Among Ziwei Life charts, some find the year's career painful and others use it to restructure; the difference is usually Ziwei's companion. The yearly Ji is shared but the combinations that absorb it differ.",
 cnA:'本文做分组对照：六组各有典型卡点和出路。要强调的是，化忌给的是「该在事业上补什么课」，不是判这一年事业必败，落到行动仍有空间。',
 enA:"This is a grouped comparison, each of the six with its typical blockage and way out. Ji indicates what career lesson to take rather than declaring the year a failure, leaving room for action.",
 cnLog:['紫微为帝星，主主导、统筹与格局，坐命者多有领导与掌控倾向。','丙午年廉贞化忌作用于官禄轴，带来规则、合约、关系层面的年度课题。','紫微独坐、紫微破军、紫微天府、紫微贪狼、紫微天相、紫微七杀六组，主星搭配不同，对同一化忌的反应各异。','分清组合后看各自的卡点与出路，化忌是课题而非判决，应对得宜可转为重整与升级。'],
 enLog:["Ziwei is the emperor star of leadership, coordination and vision, and Life charts tend toward directing and control.","In Bing-Wu, Lian-Zhen Ji acting on the career axis brings a yearly lesson in rules, contracts and relationships.","Ziwei alone, Zi-Po, Zi-Fu, Zi-Tan, Zi-Xiang and Zi-Sha pair differently and react to the same Ji in different ways.","After distinguishing the combinations, read each blockage and way out; Ji is a lesson rather than a verdict and can become restructuring when handled well."],
 cnStep:['先确认紫微坐命及它与哪颗星同宫或对照','归入六组中的一种：独坐、紫破、紫府、紫贪、紫相、紫杀','明确丙午年廉贞化忌落在官禄轴的年度课题','逐组看该组合的典型卡点','对照每组的出路与可采取的行动','把化忌当课题处理，结合大限流年定应对节奏'],
 enStep:["Confirm Ziwei in the Life Palace and which star shares or opposes it","Place it in one of six: alone, Zi-Po, Zi-Fu, Zi-Tan, Zi-Xiang or Zi-Sha","State the Bing-Wu Lian-Zhen Ji career-axis lesson","Read each combination's typical blockage","Match each to its way out and possible actions","Treat Ji as a lesson and set the response pace with the decade and year"],
 cnMis:['只讲紫微帝王星，不看和谁同宫的差异','把官禄化忌当年度事业必败的判决','不做分组对照，笼统给一个结论'],
 enMis:["Describing only the emperor star without the companion differences","Taking career Ji as a verdict that the year's career must fail","Skipping grouped comparison and giving one vague conclusion"],
 cnClose:'紫微坐命的人遇到事业化忌，关键是先认清自己属于哪一组。压力的形状看清了，出路就具体了——这一年不是来打败你的，是来逼你升级的。',
 enClose:"For Ziwei Life charts meeting career Ji, first recognize which combination you are. Once the shape of the pressure is clear, the way out becomes concrete; the year is not here to defeat you but to force an upgrade."},

{cat:'zhuxing',slug:'ziwei-shisi-zhuxing-zhiye-nengli-qingxiang',focus:'十四主星的职业能力倾向',focusEn:'the career aptitude of the fourteen major stars',
 cnT:'紫微斗数十四主星职业能力倾向：把注定改写成擅长与风险',enT:'Career Aptitude of the Fourteen Major Stars in Zi Wei Dou Shu: From Destiny to Strengths and Risks',
 cnD:'主星给的是能力与风险倾向而非固定命运，星曜提供擅长的任务类型、宫位强弱决定能否落地，大限流年定兑现期；读法是「擅长什么、防什么、何时成」。',
 enD:"Major stars give aptitude and risk tendencies rather than fixed destiny. The stars supply the task types you do well, palace strength decides whether they land, and the decade and year set the payout; read it as what you excel at, what to guard and when it comes.",
 cnL:'「你这颗星注定做某行」是很偷懒的说法。同样一颗星，落在有力的宫和无力的宫、遇上不同大限，职业表现可以完全不同。',
 enL:"Saying a star destines you for one trade is lazy. The same star in a strong versus weak palace and across different decades produces entirely different career outcomes.",
 cnA:'更有用的读法是三层：先看星给了什么能力倾向，再看宫位强弱决定发挥几分，最后看大限流年什么时候兑现。倾向不等于定局，行动仍在自己。',
 enA:"The more useful reading has three layers: the star's aptitude, the palace strength that sets how much shows, and the decade-year timing of payout. Aptitude is not destiny and action remains yours.",
 cnLog:['十四主星各对应一类思维与做事方式，提供职业能力倾向。','同一颗星在庙旺宫位发挥充分、落陷宫位打折，宫位强弱决定落地程度。','辅星、煞星与四化进一步修正：辅星添助力、煞星添竞争或风险。','大限流年走到相关宫位时为兑现期，倾向由此转为实际成果。'],
 enLog:["Each of the fourteen stars corresponds to a style of thinking and working and gives a career aptitude.","The same star fully expresses in an exalted palace and is discounted in a fallen one; palace strength sets how much lands.","Assistant stars, malefics and transformations further adjust it: assistants add help and malefics add competition or risk.","When the decade and year reach the relevant palace, it is the payout period and tendency becomes actual result."],
 cnStep:['先定命宫与官禄宫的主星','据主星列出擅长的任务类型与能力倾向','查这些星所在宫位的庙旺落陷，定发挥程度','看辅星煞星四化如何修正助力与风险','再查大限流年走到相关宫位的兑现期','综合给出「擅长什么、防什么、何时成」的建议'],
 enStep:["Set the major stars of the Life and Career palaces","List the task types and aptitude those stars give","Check the brightness of their palaces to set how much expresses","See how assistants, malefics and transformations adjust help and risk","Find the decade-year payout period when it reaches the relevant palaces","Combine into advice on what you excel at, what to guard and when it comes"],
 cnMis:['把主星当固定职业命运，下绝对结论','只看星不看宫位强弱，高估或低估能力','忽略大限流年兑现期，急于求成'],
 enMis:["Taking major stars as fixed career destiny with absolute conclusions","Reading stars without palace strength and over- or under-rating ability","Ignoring the decade-year payout and rushing results"],
 cnClose:'主星告诉你「你手里是哪种工具」，宫位告诉你「用得几分」，时间告诉你「何时上场」。把注定改写成倾向，职业这条路才走得主动。',
 enClose:"The stars tell you which tool you hold, the palaces how well you use it and timing when you take the stage. Turn destiny into aptitude and you steer your career actively."},

// ========== 辅煞 2 ==========
{cat:'fuzhu',slug:'ziwei-tianxing-tianxu-anshi-xinxu',focus:'天刑与天虚',focusEn:'Tian-Xing and Tian-Xu',
 cnT:'紫微斗数天刑天虚：刑责纪律与虚惊空虚的区分',enT:'Tian-Xing and Tian-Xu in Zi Wei Dou Shu: Discipline and Liability vs. Empty Alarm',
 cnD:'天刑主纪律、刑责、医药与法律边界，天虚主虚惊、空虚与底气不足；二星同宫或会照时，要看作用在事务面还是情绪面，才不会混为一谈。',
 enD:"Tian-Xing governs discipline, liability, medicine and legal boundaries, while Tian-Xu governs empty alarm, hollowness and lack of confidence. When they meet, see whether they act on practical affairs or emotions so they are not conflated.",
 cnL:'天刑、天虚名字里都带点「不好」的意味，其实各管一摊：一个讲规则与责任，一个讲心里没底、虚惊一场。',
 enL:"Both names sound negative, but each handles a different area: one concerns rules and responsibility and the other a lack of inner grounding or false alarm.",
 cnA:'落在官禄、交友的天刑，多表现为要守规矩、注意合同与责任边界；落在福德、命宫的天虚，多表现为底气不足、容易把事情往坏处想。分清才好应对。',
 enA:"Tian-Xing in Career or Companions often means following rules and minding contracts and responsibility; Tian-Xu in Karma or Life often means low confidence and expecting the worst. Distinguish them to respond well.",
 cnLog:['天刑主刑克、纪律与医药法律，提示守规矩、明责任、重边界。','天虚主虚耗、空虚与虚惊，提示底气不足、情绪上的空。','二星同宫或会照时，事务性的刑责与情绪性的虚耗可能叠加。','应对上，天刑靠合规与书面，天虚靠积累实力与踏实的支持系统。'],
 enLog:["Tian-Xing governs restraint, discipline, medicine and law, prompting compliance, clear responsibility and boundaries.","Tian-Xu governs depletion, hollowness and false alarm, prompting a lack of grounding and emotional emptiness.","When they meet, practical liability and emotional depletion may stack.","For Tian-Xing rely on compliance and writing; for Tian-Xu build real competence and a steady support system."],
 cnStep:['先在盘上找出天刑、天虚所在宫位','判断主要作用在事务面还是情绪面','天刑看是否涉及规则、合同、责任或医药法律','天虚看是否表现为底气不足、虚惊、空虚','二星会照则看事务与情绪是否叠加','分别用合规书面或积累实力来应对'],
 enStep:["Find where Tian-Xing and Tian-Xu sit in the chart","Judge whether they act mainly on practical affairs or emotions","For Tian-Xing, see whether rules, contracts, responsibility, medicine or law are involved","For Tian-Xu, see whether low confidence, false alarm or hollowness appears","If they meet, see whether practical and emotional effects stack","Respond with compliance and writing, or with built competence, respectively"],
 cnMis:['把天刑天虚混为一颗，笼统说不好','只按名字吓人，不看落宫与事务情绪之分','用情绪方式处理刑责，或用规则方式处理心虚'],
 enMis:["Conflating Tian-Xing and Tian-Xu as one negative star","Being frightened by the names without reading the palace and affair-emotion split","Handling liability emotionally or inner hollowness with rules"],
 cnClose:'天刑要你守边界、负责任，天虚要你补底气、踏实下来。看清是哪一种、落在哪，该合规合规、该积累积累，就不必被名字吓住。',
 enClose:"Tian-Xing asks you to hold boundaries and responsibility, Tian-Xu to build grounding and settle. See which one it is and where it sits; comply where needed and build where needed, rather than fearing the names."},

{cat:'fuzhu',slug:'ziwei-wenqu-tonggong-caiqing-bida',focus:'文曲同宫的才情',focusEn:'Wen-Qu sharing a palace',
 cnT:'紫微斗数文曲同宫：才情机敏与分心多思的两面',enT:'Wen-Qu Sharing a Palace in Zi Wei Dou Shu: Talent and Quickness vs. Distraction',
 cnD:'文曲主口才、艺术、机敏与非正式表达，与主星同宫增添才情与变通，但也易分心、多思；须与文昌的正式文书区分，把聪明用在一处才出成绩。',
 enD:"Wen-Qu governs eloquence, art, quickness and informal expression. Sharing a major star adds talent and flexibility but also distraction and overthinking; distinguish it from Wen-Chang's formal writing and focus the cleverness in one place to produce results.",
 cnL:'命里带文曲的人多半机灵、会说话、有点才艺，但这股灵气用散了就变成什么都懂一点、什么都不精。',
 enL:"Those with Wen-Qu are often quick, articulate and artistic, but when the spark is scattered they know a little of everything and master nothing.",
 cnA:'要把文曲和文昌分开：文昌偏正式、学术、文书功名，文曲偏灵动、口才、艺术与人情。文曲同宫的关键，是给这股多才多艺找一个主攻方向。',
 enA:"Separate Wen-Qu from Wen-Chang: the latter is formal, academic and documentary, while Wen-Qu is nimble, verbal, artistic and social. The key with Wen-Qu is giving the versatility one main direction.",
 cnLog:['文曲主口才、艺术、机敏与非正式的表达与审美。','与主星同宫增添才情、变通与人情味，沟通和创意上有优势。','副作用是易分心、多思、兴趣广泛而难聚焦。','与文昌的正式文书功名区分，文曲之才宜选定主攻、持续打磨。'],
 enLog:["Wen-Qu governs eloquence, art, quickness and informal expression and taste.","Sharing a major star adds talent, flexibility and social warmth, with strengths in communication and creativity.","The side effect is distraction, overthinking and broad interests that make focus hard.","Distinguish it from Wen-Chang's formal documentary merit; Wen-Qu talent should choose one focus and be polished steadily."],
 cnStep:['先确认文曲与哪颗主星同宫或会照','列出文曲带来的才情：口才、艺术、机敏、审美','与文昌区分，确认偏非正式表达而非学术文书','警惕分心多思、兴趣过广的副作用','给多才多艺选定一个主攻方向','持续在主攻方向打磨，把灵气转成成果'],
 enStep:["Confirm which major star Wen-Qu shares or meets","List the talents Wen-Qu brings: eloquence, art, quickness and taste","Distinguish it from Wen-Chang, confirming informal expression rather than academic writing","Watch for distraction, overthinking and overly broad interests","Choose one main direction for the versatility","Polish that direction steadily to turn the spark into results"],
 cnMis:['把文曲文昌混为一谈，不辨正式与灵动','放任兴趣分散，聪明用不到一处','只夸多才多艺，不提醒分心多思的代价'],
 enMis:["Conflating Wen-Qu and Wen-Chang without distinguishing formal from nimble","Letting interests scatter so the cleverness is not focused","Praising versatility without noting the cost of distraction"],
 cnClose:'文曲是一份灵气，让你会表达、有审美、懂变通，但灵气最怕散。和文昌分清、给自己定个主攻，才华才会从「小聪明」长成「真本事」。',
 enClose:"Wen-Qu is a spark for expression, taste and flexibility, but a spark scatters most easily. Distinguish it from Wen-Chang and choose a focus, so talent grows from mere cleverness into real skill."},

// ========== 流年 4 ==========
{cat:'liunian',slug:'ziwei-2026-wugong-liunian-minggong-dingwei',focus:'午宫流年命宫定位',focusEn:'locating the yearly Life Palace at Wu',
 cnT:'2026丙午年流年命宫在午：先定个人主轴再叠四化',enT:'The 2026 Bing-Wu Yearly Life Palace at Wu: Set Your Personal Axis Before Layering Transformations',
 cnD:'流年命宫随流年地支走，丙午年落午宫；要先以午宫及其三方四正定个人年度主轴，再叠天同禄、天机权、文昌科、廉贞忌，年度气候才落到个人。',
 enD:"The yearly Life Palace follows the yearly branch and lands at Wu in Bing-Wu. First set your personal yearly axis with Wu and its triple-direction, then layer Tian-Tong Lu, Tian-Ji Quan, Wen-Chang Ke and Lian-Zhen Ji so the shared climate becomes personal.",
 cnL:'年度四化对所有人都一样，但每个人的感受天差地别，差别就在于流年命宫落在你本命哪个位置——这一步不定，年度运势就是空话。',
 enL:"The yearly transformations are the same for everyone yet feel very different, depending on where the yearly Life Palace lands in your natal chart; without this step, yearly fortune is empty.",
 cnA:'顺序很重要：先找到午宫在你盘上对应哪个领域，定出今年的主轴，再把四颗年度四化放上去看引动，而不是一上来就背四化吉凶。',
 enA:"Order matters: first find which life area Wu represents in your chart to set the year's axis, then place the four transformations to see activation rather than reciting their fortune first.",
 cnLog:['流年命宫由流年地支决定，丙午年为午宫，是个人当年的主轴位。','以午宫及其三方四正定该年的主要发力领域。','再叠年度四化：天同化禄、天机化权、文昌化科、廉贞化忌，看引动哪些宫。','主轴加四化，年度共通气候才落到具体个人。'],
 enLog:["The yearly Life Palace is set by the yearly branch, Wu in Bing-Wu, and is the person's axis for the year.","Use Wu and its triple-direction to set the year's main area of effort.","Then layer the yearly transformations Tian-Tong Lu, Tian-Ji Quan, Wen-Chang Ke and Lian-Zhen Ji to see which palaces activate.","Axis plus transformations turn the shared climate into something personal."],
 cnStep:['确认流年为丙午、流年命宫落午宫','找到午宫在本命盘上的位置与星曜','以午宫三方四正定个人年度主轴','再标年度四化各自落在哪宫','看四化对主轴是引动助力还是课题','综合判断今年个人的发力方向与重点'],
 enStep:["Confirm the Bing-Wu year and the yearly Life Palace at Wu","Find Wu's position and stars in the natal chart","Set the personal yearly axis with Wu's triple-direction","Mark where each yearly transformation lands","See whether the transformations aid the axis or present a lesson","Judge the year's personal direction and focus"],
 cnMis:['直接背年度四化，不定个人流年主轴','把对所有人一样的气候当成对自己的具体预测','忽略午宫所在领域，年度运势落空'],
 enMis:["Reciting yearly transformations without setting the personal axis","Taking the shared climate as a specific prediction for oneself","Ignoring the area Wu represents so the yearly fortune is empty"],
 cnClose:'看流年先定位、后四化：午宫告诉你今年主舞台在哪，四化告诉你这舞台上发生什么。顺序对了，年度运势才不是套话。',
 enClose:"For the year, locate first and transform second: Wu tells you where the year's stage is and the transformations what happens on it. In the right order, the yearly fortune is not boilerplate."},

{cat:'liunian',slug:'ziwei-daxian-zou-fuqi-shinian-guanxi',focus:'大限走夫妻宫',focusEn:'the decade moving through the Spouse Palace',
 cnT:'紫微斗数大限走夫妻宫：十年关系与合作的主题',enT:'The Decade Moving Through the Spouse Palace in Zi Wei Dou Shu: A Ten-Year Relationship Theme',
 cnD:'大限命宫走到本命夫妻位时，这十年主题是亲密关系、合作与对等课题；看该宫星曜、四化与煞星，定这十年是良缘、磨合还是重整。',
 enD:"When the decade Life Palace reaches the natal Spouse position, the ten-year theme is intimate relationship, partnership and the lesson of equality. Read that palace's stars, transformations and malefics to see whether the decade brings a good match,磨合 or restructuring.",
 cnL:'有人某步大限特别想安定、特别在意伴侣或合伙人，往往是大限走到了夫妻宫——这十年，关系成了人生的主考场。',
 enL:"When a decade brings a strong urge to settle and focus on a partner or associate, the decade often moves through Spouse; for these ten years relationship becomes life's main exam.",
 cnA:'夫妻宫不只管婚姻，也管一切对等合作。这十年该宫星曜吉、四化引动得宜，多是遇到重要关系；见煞忌则是要在相处中学习，不等于必散。',
 enA:"The Spouse Palace governs not only marriage but all equal partnerships. Auspicious stars and good transformations in this decade often bring an important relationship; malefics or Ji mean learning through relating rather than inevitable separation.",
 cnLog:['大限命宫走到本命夫妻位，十年主轴转向关系与合作。','夫妻宫主星定这十年遇到什么样的伴侣或伙伴、相处模式如何。','四化引动决定良缘出现、关系升级，还是课题加重。','见煞忌是相处功课，配合本命与双方经营，不等于关系必散。'],
 enLog:["When the decade Life reaches the natal Spouse position, the ten-year axis turns to relationship and partnership.","The Spouse star sets the kind of partner met and the relating style.","Transformation activation decides whether a good match appears and the relationship upgrades, or the lesson deepens.","Malefics or Ji are relating homework and, with the natal chart and mutual effort, do not mean inevitable separation."],
 cnStep:['先排大限，确认大限命宫走到本命夫妻位','看夫妻宫主星，定这十年的关系倾向','查该宫四化如何引动良缘或课题','看有无煞星，判断磨合程度','区分婚姻与对等合作两条线','结合本命承接，给这十年关系的条件式判断'],
 enStep:["Cast the decades and confirm the decade Life reaches the natal Spouse position","Read the Spouse major star to set the decade's relationship tendency","Check how its transformations activate a good match or lesson","Look for malefics to gauge the level of磨合","Separate marriage from equal partnership lines","With natal capacity, give a conditional reading of the decade's relationships"],
 cnMis:['把大限走夫妻只当婚恋，忽略合作线','见煞忌就断这十年关系必败','不看四化引动，错过良缘或升级的时机'],
 enMis:["Taking the Spouse decade as only romance and ignoring partnerships","Declaring the decade's relationships doomed at malefics or Ji","Ignoring transformation activation and missing a good match or upgrade"],
 cnClose:'大限走到夫妻宫，是把「关系」请上十年主舞台。星曜吉凶给的是倾向，怎么相处、怎么合作仍在人为，读懂了就不会在关系里乱了阵脚。',
 enClose:"The decade through Spouse puts relationship on the ten-year stage. The stars give tendencies, while how you relate and partner remains in your hands; read it and you keep your footing in relationships."},

{cat:'liunian',slug:'ziwei-daxian-zou-tianzhai-shinian-jiating',focus:'大限走田宅宫',focusEn:'the decade moving through the Property Palace',
 cnT:'紫微斗数大限走田宅宫：十年家庭、房产与安全感',enT:'The Decade Moving Through the Property Palace in Zi Wei Dou Shu: Ten Years of Home, Property and Security',
 cnD:'大限命宫走到本命田宅位，十年主题是家庭、房产、居住与内在安全感；该宫星曜吉凶与四化，决定这十年安家置业还是变动重整。',
 enD:"When the decade Life reaches the natal Property position, the ten-year theme is family, real estate, housing and inner security. That palace's stars and transformations decide whether the decade settles a home or brings change and restructuring.",
 cnL:'有人某步大限特别想买房、装修、把家安顿好，往往是大限走到田宅宫——这十年，「家」和「安全感」成了人生主线。',
 enL:"When a decade brings a strong urge to buy, renovate and settle a home, the decade often moves through Property; for these ten years home and security become the main thread.",
 cnA:'田宅宫不只管房子，也管家人关系、内在的安定感和家族资源。这十年逢禄权吉星宜安家置业，逢空劫煞忌则多搬迁变动，重大资产决策仍以预算、产权和正规手续为准。',
 enA:"Property governs not only housing but family relations, inner stability and family resources. Lu, Quan and auspicious stars favor settling and buying, while Empty or malefics bring moves; major asset decisions still rest on budget, title and proper procedures.",
 cnLog:['大限命宫走到本命田宅位，十年主轴转向家庭、房产与居住。','田宅宫主星定这十年安家、置业或变动的基调。','四化引动决定置业、家人关系升级，还是房产课题。','逢空劫煞忌多搬迁维修与变动，重大决策以正规手续为准。'],
 enLog:["When the decade Life reaches natal Property, the axis turns to family, real estate and housing.","The Property star sets whether the decade settles, buys or changes.","Transformation activation decides property purchase and family upgrades, or a housing lesson.","Empty or malefics bring moves, repairs and change, and major decisions follow proper procedures."],
 cnStep:['确认大限命宫走到本命田宅位','看田宅宫主星，定十年安家或变动基调','查四化引动：置业、家人升级还是房产课题','看空劫煞星，判断搬迁维修与变动程度','区分房产、家人关系与内在安全感','结合预算产权正规手续，给条件式判断'],
 enStep:["Confirm the decade Life reaches natal Property","Read the Property star to set settling or change","Check transformations: purchase, family upgrade or housing lesson","Look for Empty or malefics to gauge moves and repairs","Separate property, family relations and inner security","With budget, title and proper procedures, give a conditional reading"],
 cnMis:['把田宅大限只当买房，忽略家人与安全感','见空劫就断这十年必动荡，不看四化与承接','鼓励在信息不全时贸然大额置业'],
 enMis:["Taking the Property decade as only buying and ignoring family and security","Declaring the decade turbulent at Empty without reading transformations","Encouraging a large purchase with incomplete information"],
 cnClose:'大限走到田宅宫，是让你把「家」安顿好的十年。星曜给倾向、手续守底线，读懂了，安家与变动都能从容安排。',
 enClose:"The decade through Property is the ten years to settle home. The stars give tendencies and procedures hold the line; read it and both settling and changing can be arranged calmly."},

{cat:'liunian',slug:'ziwei-liunian-sanfang-sihua-ruhe-can',focus:'流年三方四化的参法',focusEn:'reading the yearly trine and transformations',
 cnT:'紫微斗数流年三方四正和四化怎么参：不只看流年命宫',enT:'How to Read the Yearly Trine and Transformations in Zi Wei Dou Shu',
 cnD:'看流年不能只盯流年命宫，要把流年财帛、官禄、迁移与流年四化一起参；单看流年命宫会夸大一年吉凶，三方连读才看得出全年走向。',
 enD:"Do not read a year by staring at the yearly Life Palace alone; take the yearly Wealth, Career and Travel palaces with the yearly transformations. The Life Palace alone exaggerates the year, while reading the trine shows the full direction.",
 cnL:'很多人一查流年就只看流年命宫那颗星，顺则大喜、逆则大悲，其实一年的事分散在三方四正，单宫看不全。',
 enL:"Many check a year by only its Life star, overjoyed or crushed, but the year's events spread across the trine and one palace cannot show them all.",
 cnA:'正确参法：流年命宫定当年基调，再开流年三方看财、官、迁各自被什么星和四化引动，合起来才是完整的一年。',
 enA:"The right way: the yearly Life sets the tone, then open the trine to see how Wealth, Career and Travel are each activated by stars and transformations; together they make the full year.",
 cnLog:['流年命宫定当年个人基调与主轴。','流年三方四正分掌该年的财务、事业、迁移等具体领域。','流年四化标出这一年资源、掌控、名声与课题落在哪。','几处合参，单宫的吉凶才不会被夸大。'],
 enLog:["The yearly Life sets the tone and axis.","The yearly trine governs the year's specific areas of wealth, career and travel.","The yearly transformations mark where resources, control, reputation and lessons land.","Reading them together keeps one palace's fortune from being exaggerated."],
 cnStep:['先定流年命宫及主星，作为当年基调','再排流年三方四正各宫','标流年四化各自落入哪个领域','看流年财帛引动：收入与支出','看流年官禄迁移引动：事业与外出','合参三方四化，给全年平衡判断'],
 enStep:["Set the yearly Life Palace and star as the tone","Cast the yearly trine palaces","Mark where each yearly transformation lands","Read yearly Wealth activation: income and spending","Read yearly Career and Travel activation: work and movement","Combine the trine and transformations for a balanced yearly reading"],
 cnMis:['只看流年命宫，凭一宫断全年','顺则大喜逆则大悲，被单宫放大情绪','不看流年三方四化，全年走向读不全'],
 enMis:["Reading only the yearly Life and judging the year from one palace","Being overjoyed or crushed by the amplified single palace","Ignoring the yearly trine and transformations so the full direction is missed"],
 cnClose:'流年是一张完整的小盘，不是一颗星的独角戏。命宫定调、三方展开、四化点题，合起来参，一年的吉凶才看得准、稳得住。',
 enClose:"A year is a complete small chart, not one star's solo. The Life sets the tone, the trine unfolds and transformations mark the theme; read together and the year is seen accurately and steadily."}
];
