// 2026-09-26 调研驱动 第4组：十四主星在交友宫（奴仆宫）落宫系列 8篇（全站空白）
// 交友宫管朋友、同事、伙伴、客户、下属、团队与社交圈。
module.exports=[
{cat:'gongwei',slug:'ziwei-ziwei-zai-jiaoyougong',focus:'紫微在交友宫',focusEn:'Ziwei in the Companions Palace',
 cnT:'紫微在交友宫：朋友多强势，遇贵人也要守住自己',enT:'Ziwei in the Companions Palace: Strong Friends and Noble Help, While Keeping Your Place',
 cnD:'交友宫坐紫微，所交多有地位、有能力或领导型人物，易得贵人提携，但也容易在关系中被主导、被比较，相处时要保有自己的位置与底气。',
 enD:"With Ziwei in Companions, friends tend to be capable, high-status or leading figures and noble help is common, but you can be dominated or compared; keep your own place and confidence in these relationships.",
 cnL:'你身边的朋友多半不是泛泛之辈，有人能拉你一把，但跟强势的人走得近，也容易不自觉矮一截、跟着别人的节奏走。',
 enL:"Your friends are often not ordinary and some pull you forward, but staying close to strong people can make you shrink and follow their rhythm without noticing.",
 cnA:'关键是区分「借力」和「依附」：可以向有地位的朋友学习、借助平台，但目标和判断要在自己手里，否则贵人一多，反而没了自己的方向。',
 enA:"Distinguish borrowing strength from dependence: learn from high-status friends and use their platform, but keep your goals and judgment in your own hands, or many helpers leave you without direction.",
 cnLog:['紫微为尊贵、主导之星，落交友宫，朋友多强势、有地位或带领导气质。','好处是易得贵人、能进入较高的圈子与平台。','风险是在关系中易被主导、被比较，或习惯依附而失去自我。','应对是借力而不依附，尊重对方也守住自己的目标与节奏。'],
 enLog:["Ziwei is the noble, leading star; in Companions, friends are strong, high-status or leader-like.","The benefit is noble help and access to higher circles and platforms.","The risk is being dominated or compared, or growing dependent and losing yourself.","Borrow strength without dependence: respect them and keep your goals and rhythm."],
 cnStep:['先确认交友宫坐紫微及其三方星曜','看清身边朋友是否多强势、有地位','善用贵人提携与较高平台的机会','警惕在关系中被主导、矮一截','区分借力与依附，目标判断留在自己手里','平等往来，既感恩提携也守住自我'],
 enStep:["Confirm Ziwei in Companions and its trine stars","See whether friends are mostly strong and high-status","Use noble help and higher-platform opportunities","Watch for being dominated or made to feel smaller","Distinguish borrowing from dependence and keep goals and judgment","Relate as equals, grateful for help yet holding yourself"],
 cnMis:['只夸贵人多，不提醒被主导的风险','把依附当借力，慢慢失去自己的方向','在强势朋友面前一味退让，不敢表达'],
 enMis:["Praising many helpers without noting domination risk","Mistaking dependence for borrowing and losing direction","Always yielding before strong friends and not speaking up"],
 cnClose:'紫微在交友宫是一副「能进高圈子」的好配置，贵人值得珍惜，但越是靠近强者，越要站得稳。借力而不依附，关系才能长久地成就你。',
 enClose:"Ziwei in Companions gives access to high circles and noble helpers worth treasuring, but the closer to the strong, the steadier you must stand. Borrow without dependence and the relationships last in supporting you."},

{cat:'gongwei',slug:'ziwei-tianji-zai-jiaoyougong',focus:'天机在交友宫',focusEn:'Tian-Ji in the Companions Palace',
 cnT:'天机在交友宫：朋友聪明善变，宜学习型圈子重质不重量',enT:'Tian-Ji in the Companions Palace: Clever, Changing Friends; Favor Learning Circles and Quality over Quantity',
 cnD:'交友宫坐天机，朋友多聪明、善思考、点子多，适合脑力交流与学习型圈子，但关系流动快、聚散不定，宜重质不重量、把核心友谊维护稳。',
 enD:"With Tian-Ji in Companions, friends are clever, thoughtful and full of ideas, suiting intellectual exchange and learning circles, but relationships move and change quickly; favor quality over quantity and keep core friendships steady.",
 cnL:'你跟朋友在一起多半聊想法、聊规划，能互相启发，但这样的朋友来得快、去得也快，圈子常换，深交的需要刻意维护。',
 enL:"With friends you mostly exchange ideas and plans and inspire one another, but such friends come and go and circles change, so deep ties need deliberate care.",
 cnA:'重点是防「浅尝辄止」：认识一堆聪明的人，却没有几个能在你需要时托底。把精力留给几个真正志同道合、能长期交流的朋友。',
 enA:"Guard against skimming the surface: knowing many clever people with few who support you when needed. Save energy for a few truly like-minded friends for the long term.",
 cnLog:['天机主智、善变，落交友宫，朋友多聪明、多思、点子多。','宜脑力激荡、学习交流与共同研究的圈子。','关系聚散快、流动大，稳定性不足。','应对是重质不重量，维护少数志同道合的深交。'],
 enLog:["Tian-Ji is intellectual and changeable; in Companions, friends are clever, thoughtful and full of ideas.","It suits brainstorming, learning and joint-research circles.","Relationships gather and part quickly with high turnover and low stability.","Favor quality over quantity and maintain a few like-minded deep ties."],
 cnStep:['确认交友宫坐天机及星曜组合','看清朋友是否多聪明、善思考、流动快','多参与学习、研究、脑力交流的圈子','警惕认识很多却深交很少','筛选少数志同道合者重点维护','用持续联系和共同成长稳住核心友谊'],
 enStep:["Confirm Tian-Ji in Companions and its star combination","See whether friends are clever, thoughtful and mobile","Join learning, research and intellectual-exchange circles","Watch for knowing many with few deep ties","Select a few like-minded people to maintain","Steady core friendships through ongoing contact and shared growth"],
 cnMis:['只夸朋友聪明，不提醒关系流动快','追求认识的人数，忽略深交质量','圈子常换却不维护，需要时无人托底'],
 enMis:["Praising clever friends without noting turnover","Chasing the number known and ignoring deep-tie quality","Changing circles without maintaining them, with no support when needed"],
 cnClose:'天机在交友宫让你身边不缺聪明的头脑和新鲜的想法，但真正值钱的是几个能走长远的人。重质不重量，学习型圈子才会越走越宽。',
 enClose:"Tian-Ji in Companions surrounds you with clever minds and fresh ideas, but a few long-term people are what count. Favor quality over quantity and learning circles widen over time."},

{cat:'gongwei',slug:'ziwei-taiyang-zai-jiaoyougong',focus:'太阳在交友宫',focusEn:'Tai-Yang in the Companions Palace',
 cnT:'太阳在交友宫：朋友热情坦荡，广结善缘益友多',enT:'Tai-Yang in the Companions Palace: Warm, Open Friends and Many Beneficial Ties',
 cnD:'交友宫坐太阳，朋友多热情、外向、光明坦荡，广结善缘、益友多，遇事常有人热心帮忙，但也要防为朋友过度操心、付出被当成理所当然。',
 enD:"With Tai-Yang in Companions, friends are warm, outgoing and open, with many beneficial ties and eager help, but guard against over-worrying for friends or having your giving taken for granted.",
 cnL:'你人缘通常不错，朋友愿意找你、也愿意帮你，圈子里有你在就热闹。但热心肠用过头，容易替别人扛太多、自己受累。',
 enL:"Your relationships are usually good; friends seek and help you and things are lively with you around, but too much warmth can make you carry too much for others and tire yourself.",
 cnA:'重点是「热心要有边界」：珍惜那些坦荡的益友，也学会在帮人时量力而行，区分真心互助和单方面消耗，别让好人缘变成负担。',
 enA:"Warmth needs boundaries: cherish open, beneficial friends and learn to help within your means, distinguishing mutual care from one-sided depletion so popularity does not become a burden.",
 cnLog:['太阳主光明、热情、博爱，落交友宫，朋友多外向坦荡。','广结善缘、益友多，遇事多有人热心相助。','风险是为朋友过度操心、付出，或被当成理所当然。','应对是热心而有边界，量力帮人，珍惜双向的友谊。'],
 enLog:["Tai-Yang is bright, warm and generous; in Companions, friends are outgoing and open.","Many beneficial ties form and eager help arrives in need.","The risk is over-worrying and giving, or being taken for granted.","Be warm with boundaries, help within your means and cherish two-way friendship."],
 cnStep:['确认交友宫坐太阳及星曜','看清朋友是否多热情、坦荡、热心','珍惜益友，遇事互助的好缘分','警惕替朋友扛太多、过度操心','帮人量力而行，设好边界','区分双向互助与单方面消耗'],
 enStep:["Confirm Tai-Yang in Companions and its stars","See whether friends are warm, open and eager","Cherish beneficial friends and mutual help","Watch for carrying too much and over-worrying","Help within your means and set boundaries","Distinguish mutual care from one-sided depletion"],
 cnMis:['只夸人缘好，不提醒过度付出','热心没边界，把自己累着','把单方面消耗当友谊，不懂得筛选'],
 enMis:["Praising popularity without noting over-giving","Warmth without boundaries that tires you","Taking one-sided depletion as friendship without screening"],
 cnClose:'太阳在交友宫是难得的好人缘，坦荡的朋友是一生的财富。只要热心带上边界、付出留给懂得回应的人，这份人脉会一直照亮你。',
 enClose:"Tai-Yang in Companions is rare good fortune in relationships, and open friends are lifelong wealth. With bounded warmth and giving to those who respond, this network keeps lighting your way."},

{cat:'gongwei',slug:'ziwei-tianfu-zai-jiaoyougong',focus:'天府在交友宫',focusEn:'Tian-Fu in the Companions Palace',
 cnT:'天府在交友宫：朋友稳重有资源，是较稳的人际配置',enT:'Tian-Fu in the Companions Palace: Steady, Resourceful Friends in a Stable Relationship Setup',
 cnD:'交友宫坐天府，朋友多稳重、可靠、手里有资源，多贵人、社交有底气，能借到实际支援；关系讲究对等与长久，是较让人安心的人际配置。',
 enD:"With Tian-Fu in Companions, friends are steady, reliable and hold resources, with noble help and real support to borrow; relationships value reciprocity and the long term, making a reassuring setup.",
 cnL:'你交的朋友多半踏实、讲信用，有人有积蓄、有门路，遇到事能给你实在的帮助，不是酒桌上的热闹交情。',
 enL:"Your friends tend to be grounded and trustworthy, some with savings and connections who give real help rather than mere banquet goodwill.",
 cnA:'重点是「以稳换稳」：天府重对等，你也要做那个可靠、有分寸的人，关系才长久；同时防圈子偏保守、太求稳而错过新机会。',
 enA:"Trade steadiness for steadiness: Tian-Fu values reciprocity, so be the reliable, measured person yourself for ties to last; also guard against overly conservative circles that miss new chances.",
 cnLog:['天府为府库、稳重之星，落交友宫，朋友多可靠、有资源。','多贵人，能借到实际、稳当的支援。','关系讲对等、信用与长久，让人安心。','风险是圈子偏保守，宜在稳的基础上保持开放。'],
 enLog:["Tian-Fu is the storehouse, a steady star; in Companions, friends are reliable and hold resources.","There is noble help and real, steady support to borrow.","Relationships value reciprocity, trust and the long term and reassure.","The risk is conservative circles; stay open on a stable base."],
 cnStep:['确认交友宫坐天府及星曜','看清朋友是否稳重、可靠、有资源','善用实在的贵人和实际支援','自己也做可靠、讲信用、有分寸的人','以对等和长久维护关系','防圈子过保守，保持对新机会的开放'],
 enStep:["Confirm Tian-Fu in Companions and its stars","See whether friends are steady, reliable and resourceful","Use real noble help and practical support","Be the reliable, trustworthy, measured person yourself","Maintain ties through reciprocity and the long view","Guard against conservative circles and stay open to new chances"],
 cnMis:['只夸朋友有资源，不提醒要对等','只索取不做可靠的人，关系难长久','圈子太求稳，错过新的人脉与机会'],
 enMis:["Praising resourceful friends without noting reciprocity","Only taking without being reliable, so ties do not last","Overly steady circles that miss new people and chances"],
 cnClose:'天府在交友宫给你一群靠得住的朋友和实实在在的支援，是很稳的福气。你以可靠回报可靠、在稳里保持开放，这份人脉会越用越厚。',
 enClose:"Tian-Fu in Companions gives dependable friends and real support, a steady blessing. Return reliability with reliability and stay open within steadiness, and this network grows richer."},

{cat:'gongwei',slug:'ziwei-taiyin-zai-jiaoyougong',focus:'太阴在交友宫',focusEn:'Tai-Yin in the Companions Palace',
 cnT:'太阴在交友宫：朋友温柔细腻，多女性或情感型挚友',enT:'Tai-Yin in the Companions Palace: Gentle, Sensitive Friends and Often Female or Emotional Close Ties',
 cnD:'交友宫坐太阴，朋友多温柔、细腻、重情感，常有女性或异性挚友，靠体贴与陪伴维系；但要防情绪上的过度依赖或彼此影响心情。',
 enD:"With Tai-Yin in Companions, friends are gentle, sensitive and emotional, often including female or opposite-sex close friends, held together by care and companionship; guard against emotional over-dependence or mutual mood influence.",
 cnL:'你和朋友之间很讲感情和默契，有人能陪你说心里话、在情绪上接住你，关系细腻，但也容易彼此牵挂太深、心情互相牵动。',
 enL:"Your friendships value feeling and rapport, with someone who listens and catches you emotionally; the ties are tender but can involve deep mutual concern and shared moods.",
 cnA:'重点是「亲密也要独立」：珍惜那些细腻体贴的挚友，也要各自有情绪空间，避免把对方当唯一的情感寄托、一有波动就互相拖累。',
 enA:"Intimacy needs independence: cherish tender close friends while keeping emotional space, avoiding making one person the sole emotional anchor and dragging each other at every fluctuation.",
 cnLog:['太阴主柔、情感与内敛，落交友宫，朋友多温柔细腻。','多女性或异性挚友，重陪伴、体贴与默契。','风险是情绪上过度依赖、彼此牵动心情。','应对是亲密而独立，各自保有情绪空间。'],
 enLog:["Tai-Yin is soft, emotional and reserved; in Companions, friends are gentle and sensitive.","There are often female or opposite-sex close friends who value companionship, care and rapport.","The risk is emotional over-dependence and mutual mood influence.","Be close yet independent, each keeping emotional space."],
 cnStep:['确认交友宫坐太阴及星曜','看清朋友是否温柔、细腻、重情感','珍惜体贴陪伴型的挚友','警惕情绪上过度依赖','各自保留情绪空间，不把对方当唯一寄托','用成熟的方式维系细腻的友谊'],
 enStep:["Confirm Tai-Yin in Companions and its stars","See whether friends are gentle, sensitive and emotional","Cherish caring, companion-like close friends","Watch for emotional over-dependence","Keep emotional space and avoid one sole anchor","Maintain tender friendship in a mature way"],
 cnMis:['只夸朋友体贴，不提醒情绪依赖','把挚友当唯一情感寄托，失去独立','彼此心情牵动太深，一波动就互相拖累'],
 enMis:["Praising caring friends without noting dependence","Making a close friend the sole emotional anchor and losing independence","Tying moods so closely that fluctuations drag each other"],
 cnClose:'太阴在交友宫给你温柔、懂你的挚友，是很暖的缘分。再加上一份独立和情绪边界，亲密的友谊才会细水长流、彼此滋养而不拖累。',
 enClose:"Tai-Yin in Companions gives gentle, understanding friends, a warm bond. Add independence and emotional boundaries and the close friendship endures, nourishing rather than dragging each other."},

{cat:'gongwei',slug:'ziwei-tanlang-zai-jiaoyougong',focus:'贪狼在交友宫',focusEn:'Tan-Lang in the Companions Palace',
 cnT:'贪狼在交友宫：朋友多才社交广，要分清真朋友与场面之交',enT:'Tan-Lang in the Companions Palace: Versatile Friends and Wide Circles; Sort True Friends from Fair-Weather Ties',
 cnD:'交友宫坐贪狼，朋友多才多艺、三教九流、社交面广，生活热闹有趣，但要防酒肉应酬、欲望型关系，须分清真朋友与场面之交，别为无效社交耗神。',
 enD:"With Tan-Lang in Companions, friends are versatile and from all walks of life in wide, lively circles, but guard against banquet and desire-based ties; sort true friends from fair-weather ones and avoid draining yourself on empty socializing.",
 cnL:'你很会交朋友，走到哪都能聊、局也多，生活不缺热闹。但圈子一杂，酒肉朋友和真正靠谱的人混在一起，需要你心里有数。',
 enL:"You make friends easily and liven up any gathering with no shortage of events, but as circles mix, fair-weather and reliable people blend and you must know which is which.",
 cnA:'重点是「广交更要慎交」：享受丰富的人际，也要主动筛选，把时间留给真诚、能共同进步的人，远离只在吃喝和利益上热络的关系。',
 enA:"Wide circles demand careful choosing: enjoy rich relationships yet actively select, giving time to sincere people who grow with you and staying clear of ties warm only over food and benefit.",
 cnLog:['贪狼主多才、欲望与社交，落交友宫，朋友三教九流、圈子广。','生活热闹、信息灵、机会多。','风险是酒肉应酬、欲望型关系与无效社交。','应对是广交慎交，分清真假，留住真诚的人。'],
 enLog:["Tan-Lang governs versatility, desire and sociability; in Companions, friends come from all walks in wide circles.","Life is lively, information flows and opportunities are many.","The risk is banquet socializing, desire-based ties and empty networking.","Widely yet carefully connect, sort true from false and keep sincere people."],
 cnStep:['确认交友宫坐贪狼及星曜','看清朋友是否多才、圈子是否广杂','善用广人脉带来的信息和机会','警惕酒肉应酬和欲望型关系','分清真朋友与场面之交','把时间留给真诚、共同进步的人'],
 enStep:["Confirm Tan-Lang in Companions and its stars","See whether friends are versatile and circles wide and mixed","Use the information and opportunities wide networks bring","Watch for banquet socializing and desire-based ties","Sort true friends from fair-weather ones","Give time to sincere people who grow with you"],
 cnMis:['只夸社交能力强，不提醒酒肉朋友','把场面热络当真交情，错付时间','为无效社交耗神，忽略真正的挚友'],
 enMis:["Praising strong sociability without noting fair-weather friends","Taking surface warmth as true friendship and misspending time","Draining yourself on empty socializing and ignoring real close friends"],
 cnClose:'贪狼在交友宫让你人脉广、生活热闹，这是本事；但真正拉开差距的是筛选力。把真诚的人留下来、把场面之交看淡，圈子才广而不乱。',
 enClose:"Tan-Lang in Companions gives wide networks and lively life, a real skill, but discernment sets people apart. Keep the sincere and take fair-weather ties lightly so your circles stay wide but not chaotic."},

{cat:'gongwei',slug:'ziwei-tianxiang-zai-jiaoyougong',focus:'天相在交友宫',focusEn:'Tian-Xiang in the Companions Palace',
 cnT:'天相在交友宫：朋友正派讲分寸，是合伙交友的佳配',enT:'Tian-Xiang in the Companions Palace: Proper, Measured Friends; A Fine Setup for Partnership',
 cnD:'交友宫坐天相，朋友多正派、体面、讲分寸、重承诺，易得稳重可靠的伙伴，人际讲究对等与体面，是合伙、协作上较理想的人际配置。',
 enD:"With Tian-Xiang in Companions, friends are proper, presentable, measured and promise-keeping, yielding steady reliable partners; relationships value reciprocity and dignity, making an ideal setup for partnership and collaboration.",
 cnL:'你身边的朋友多半规矩、讲体面，做事有分寸、说到做到，遇到合作让人放心，是那种可以一起把事情办稳的人。',
 enL:"Your friends tend to be proper and presentable, measured and true to word, reassuring in collaboration and the kind who get things done steadily with you.",
 cnA:'重点是「惜福也要防被动」：天相易受周围星曜影响，若三方逢煞，正派朋友里也会夹杂变数；合作仍要落到书面，别只凭体面和信任。',
 enA:"Cherish this but guard against passivity: Tian-Xiang is swayed by surrounding stars, and if the trine has malefics even proper friends bring variables; still put collaboration in writing rather than relying on dignity and trust alone.",
 cnLog:['天相主印、正派、辅佐与分寸，落交友宫，朋友多正派体面。','易得稳重可靠、重承诺的伙伴，宜合作。','关系讲对等、规矩与体面。','风险是天相受煞曜影响，合作仍需书面合同。'],
 enLog:["Tian-Xiang governs the seal, propriety, support and measure; in Companions, friends are proper and presentable.","Steady, reliable, promise-keeping partners make collaboration suitable.","Relationships value reciprocity, rules and dignity.","The risk is Tian-Xiang swayed by malefics, so collaboration still needs a written contract."],
 cnStep:['确认交友宫坐天相及星曜','看清朋友是否正派、讲分寸、重承诺','珍惜稳重可靠的合作伙伴','查三方有无煞星带来变数','合作对等、讲规矩、顾体面','重大合作仍落到书面合同，以专业意见为准'],
 enStep:["Confirm Tian-Xiang in Companions and its stars","See whether friends are proper, measured and promise-keeping","Cherish steady, reliable partners","Check the trine for malefics that bring variables","Collaborate with reciprocity, rules and dignity","Put major collaboration in writing and rely on professional advice"],
 cnMis:['只夸朋友正派，不查周围煞星','只凭体面信任，合作不立字据','把天相当作完全无风险，忽略其受影响'],
 enMis:["Praising proper friends without checking surrounding malefics","Trusting on dignity alone and not writing contracts","Taking Tian-Xiang as risk-free while ignoring its being swayed"],
 cnClose:'天相在交友宫给你正派可靠的伙伴，是合伙协作的好配置。再加上对煞星的警觉和一纸清楚的合同，好关系就能稳稳地变成好结果。',
 enClose:"Tian-Xiang in Companions gives proper, reliable partners, a fine collaboration setup. Add alertness to malefics and a clear contract and good relationships steadily become good results."},

{cat:'gongwei',slug:'ziwei-tianliang-zai-jiaoyougong',focus:'天梁在交友宫',focusEn:'Tian-Liang in the Companions Palace',
 cnT:'天梁在交友宫：朋友多年长老成型，能得荫庇与忠告',enT:'Tian-Liang in the Companions Palace: Older, Mentor-Like Friends Who Offer Shelter and Counsel',
 cnD:'交友宫坐天梁，朋友多老成、年长或长辈型，能给荫庇、忠告与提点，遇事有「老大哥/老大姐」式的帮助；但也要避免被过度保护或被说教束缚。',
 enD:"With Tian-Liang in Companions, friends are mature, older or mentor-like and offer shelter, counsel and reminders, with older-brother or older-sister help; avoid being overprotected or bound by lecturing.",
 cnL:'你身边常有比你年长、阅历深的人愿意提点你、护着你，遇到难事有人给忠告、帮你挡一挡，是很有依靠感的人际配置。',
 enL:"Older, experienced people often advise and protect you, giving counsel and a buffer in hard times, a relationship setup with a strong sense of backing.",
 cnA:'重点是「受荫也要自立」：珍惜长辈型朋友的忠告，也要培养自己的判断，不能总躲在别人的庇护下，把提点变成依赖、失去独当一面的机会。',
 enA:"Receive shelter but stand on your own: cherish mentor-like counsel while building your own judgment, not always hiding behind protection and turning guidance into dependence that costs you the chance to lead.",
 cnLog:['天梁主荫、老成、监察与教化，落交友宫，朋友多年长老成型。','能得忠告、荫庇与实际提点。','遇事有依靠、有人护持。','风险是被过度保护或说教，宜受荫而自立。'],
 enLog:["Tian-Liang governs shelter, maturity, oversight and teaching; in Companions, friends are older and mentor-like.","Counsel, shelter and practical reminders are available.","There is backing and protection in need.","The risk is overprotection or lecturing; receive shelter yet stand independent."],
 cnStep:['确认交友宫坐天梁及星曜','看清朋友是否多老成、年长、阅历深','善用长辈型朋友的忠告与荫庇','遇事多请教、听劝','警惕被过度保护、被说教束缚','培养自己的判断，从受提点走向能独当一面'],
 enStep:["Confirm Tian-Liang in Companions and its stars","See whether friends are mature, older and experienced","Use mentor-like counsel and shelter","Seek advice and listen in need","Watch for overprotection and binding lecturing","Build your own judgment and move from being guided to leading yourself"],
 cnMis:['只夸有长辈贵人，不提醒过度保护','习惯躲在庇护下，失去独当一面的机会','把说教当帮助，不培养自己的判断'],
 enMis:["Praising elder helpers without noting overprotection","Growing used to shelter and losing the chance to lead","Taking lecturing as help without building judgment"],
 cnClose:'天梁在交友宫让你身边不缺提点和护持，是难得的贵人缘。带着感恩去听、也带着自立去成长，长辈的荫庇才能成为你独立的台阶，而不是温室。',
 enClose:"Tian-Liang in Companions gives no shortage of guidance and protection, rare noble ties. Listen with gratitude and grow toward independence so the elders' shelter becomes the step to standing on your own rather than a hothouse."}
];
