// 2026-09-27 调研驱动 第4组：交友宫逐星补全6篇+辅煞曜2篇
module.exports=[
{cat:'gongwei',slug:'ziwei-wuqu-zai-jiaoyougong',focus:'武曲在交友宫',focusEn:'Wu-Qu in the Companions Palace',
 cnT:'武曲在交友宫：朋友务实讲利益，宜生意伙伴但别谈钱伤感情',enT:'Wu-Qu in the Companions Palace: Pragmatic, Deal-Minded Friends; Good Business Partners, Yet Keep Money from Hurting Feelings',
 cnD:'交友宫坐武曲，朋友多务实、讲实际、能力强，多是能一起谈生意、换资源的实干型人物；关系建立在能力与利益交换上，要防过于功利、谈钱伤感情。',
 enD:"With Wu-Qu in Companions, friends are pragmatic, practical and capable, often the doers with whom you can talk business and trade resources; ties rest on ability and mutual benefit, so guard against overly transactional relationships where money hurts feelings.",
 cnL:'你交的朋友多半不玩虚的，做事干脆、能干活，遇到要落地、要谈钱的事特别靠谱。但关系里利益算得太清楚，朋友之间也容易变得生分。',
 enL:"Your friends tend to be direct doers who get things done and are especially reliable when execution and money are involved, but when benefits are reckoned too clearly, friendships can grow distant.",
 cnA:'重点是「互利也要有情」：善用能干的生意伙伴做资源交换，但合伙、借款、分成都要白纸黑字讲清楚；别把所有关系都换算成利益，否则钱算清了，人也走散了。',
 enA:"Mutual benefit needs warmth: use capable business partners for resource exchange, yet put partnerships, loans and splits clearly in writing; do not reduce every tie to benefits, or once money is settled, people drift away.",
 cnLog:['武曲为财星、刚硬、实干，落交友宫，朋友多务实、能力强。','宜生意伙伴、资源交换与一起做事的实干圈。','关系重利益交换，过于功利则谈钱伤感情。','应对是互利而有情，合伙钱财落到书面，以专业律师和正规途径为准。'],
 enLog:["Wu-Qu is the finance star, hard and practical; in Companions, friends are pragmatic and capable.","It suits business partners, resource exchange and circles of doers.","Ties rest on exchange, and over-transactional dealings make money hurt feelings.","Be mutual yet warm, put partnership money in writing, and rely on professional lawyers and formal channels."],
 cnStep:['确认交友宫坐武曲及星曜组合','看清朋友是否务实、能干、讲实际','善用实干型伙伴做资源与生意合作','警惕关系过于功利、凡事算利益','合伙钱财与分成一律书面写清楚','保留不带利益的朋友情分，谈钱也讲分寸'],
 enStep:["Confirm Wu-Qu in Companions and its star combination","See whether friends are pragmatic, capable and practical","Use doer partners for resource and business collaboration","Watch for overly transactional, benefit-first ties","Put partnership money and splits clearly in writing","Keep friendship apart from interest so money stays in proportion"],
 cnMis:['只夸朋友能干，不提醒谈钱伤感情','合伙赚钱全凭口头，不立字据','把所有关系都算成利益，失去人情'],
 enMis:["Praising capable friends without noting that money hurts feelings","Doing deals on word of mouth without written terms","Reducing every tie to interest and losing human warmth"],
 cnClose:'武曲在交友宫给你一群能一起把事干成、把资源换到的实干伙伴，是做事的好帮手。把利益摆在明处、把情分放在心里，合作才能既算得清账，又留得住人。',
 enClose:"Wu-Qu in Companions gives you doers who get things done and trade resources, a real asset for work. Put benefits on the table and keep warmth in heart, so collaboration both settles accounts clearly and keeps people."},

{cat:'gongwei',slug:'ziwei-tiantong-zai-jiaoyougong',focus:'天同在交友宫',focusEn:'Tian-Tong in the Companions Palace',
 cnT:'天同在交友宫：朋友温和随和，相处舒服却要防一起享乐不成长',enT:'Tian-Tong in the Companions Palace: Gentle, Easygoing Friends; Comfortable Yet Guard Against Pleasure Without Growth',
 cnD:'交友宫坐天同，朋友多温和、随和、好相处，相处轻松舒服，宜陪伴型、轻松型友谊；但要防圈子缺乏推动力，大家一起享乐多、一起成长少，久了容易安于现状。',
 enD:"With Tian-Tong in Companions, friends are gentle, easygoing and pleasant, suiting comfortable companion-like friendships; guard against circles lacking drive, where pleasure outweighs growth and comfort breeds complacency over time.",
 cnL:'你跟朋友在一起多半不累，谁都好说话，吃吃喝喝、聊聊天很放松。但这样的圈子太舒服，久了没人 push 你往前走，舒服久了也会慌。',
 enL:"Being with friends usually feels easy; everyone is agreeable and meals and chats are relaxing, but such comfortable circles push no one forward, and long comfort can leave you anxious.",
 cnA:'重点是「舒服也要有长进」：珍惜这些让人放松的挚友，也要主动给自己和朋友设一点共同目标，比如一起学东西、一起健身、一起做点小事，别让友谊只剩下吃喝玩乐。',
 enA:"Comfort needs growth: cherish relaxing close friends yet set a shared goal for you both, like learning, fitness or a small project, so friendship is not left to food and fun alone.",
 cnLog:['天同主福、享受、温和与随和，落交友宫，朋友多好相处。','相处轻松舒服，宜陪伴型、减压型的友谊。','风险是圈子缺乏推动力，一起享乐多、成长少。','应对是舒服中带点目标，和朋友一起做点长进的事。'],
 enLog:["Tian-Tong governs bliss, enjoyment and gentleness; in Companions, friends are easy to be with.","Time together is relaxed and comfortable, suiting companion-like, stress-relieving friendship.","The risk is circles lacking drive, with more pleasure than growth.","Add some purpose to comfort and grow together on something."],
 cnStep:['确认交友宫坐天同及星曜','看清朋友是否温和、随和、好相处','珍惜让人放松、陪伴型的挚友','警惕圈子太舒服、没人推动','主动和朋友立一个共同小目标','把轻松友谊变成一起长进的关系'],
 enStep:["Confirm Tian-Tong in Companions and its stars","See whether friends are gentle, easygoing and agreeable","Cherish relaxing, companion-like close friends","Watch for circles too comfortable with no drive","Propose a small shared goal with friends","Turn easy friendship into growing together"],
 cnMis:['只夸相处舒服，不提醒缺乏推动力','把享乐当友谊，从不一起做事','太安于现状，被舒服圈子拖住不前'],
 enMis:["Praising comfort without noting the lack of drive","Taking pleasure as friendship and never doing things together","Growing complacent and held back by comfortable circles"],
 cnClose:'天同在交友宫给你一群相处不累、愿意陪你放松的朋友，是很治愈的缘分。在舒服里加一点点向上的劲儿，友谊既能给你情绪按摩，也能陪你慢慢变好。',
 enClose:"Tian-Tong in Companions gives you friends who are easy to be with and share relaxation, a healing bond. Add a touch of upward drive and friendship both soothes you and helps you slowly improve."},

{cat:'gongwei',slug:'ziwei-lianzhen-zai-jiaoyougong',focus:'廉贞在交友宫',focusEn:'Lian-Zhen in the Companions Palace',
 cnT:'廉贞在交友宫：朋友有才个性强，圈子精彩也多感情纠葛',enT:'Lian-Zhen in the Companions Palace: Talented, Strong-Willed Friends; Exciting Circles with Emotional Tangles',
 cnD:'交友宫坐廉贞，朋友多有才华、个性强、爱憎分明，关系精彩却也复杂，宜专业圈、兴趣圈和创作圈；要防感情纠葛、口舌是非与圈子里的内耗。',
 enD:"With Lian-Zhen in Companions, friends are talented, strong-willed and black-and-white; ties are exciting yet complex, suiting professional, interest and creative circles; guard against emotional entanglements, gossip and internal friction.",
 cnL:'你身边的朋友多半有两把刷子、有个性，跟他们相处很带劲，但情绪起伏大、爱恨分明，圈子里今天好得穿一条裤、明天可能就闹别扭。',
 enL:"Your friends tend to be capable and individual; being with them is exciting, but moods swing and feelings run strong, with circles that are tight as brothers one day and at odds the next.",
 cnA:'重点是「精彩要有边界」：享受才华与个性带来的火花，也要管住自己别卷进朋友的感情和恩怨，保持一点距离感；是非口舌能不掺和就不掺和，圈子再热闹也别站队。',
 enA:"Excitement needs boundaries: enjoy the spark of talent and personality, yet keep out of friends' romances and feuds with a little distance; stay out of gossip and do not take sides, however lively the circle.",
 cnLog:['廉贞主才、官禄、感情与复杂，落交友宫，朋友多有才华、个性强。','宜专业、兴趣与创作圈子，关系精彩。','风险是感情纠葛、口舌是非与圈子内耗。','应对是保持距离，不掺和恩怨、不轻易站队。'],
 enLog:["Lian-Zhen governs talent, career, emotion and complexity; in Companions, friends are talented and strong-willed.","It suits professional, interest and creative circles, and ties are exciting.","The risk is emotional tangles, gossip and internal friction.","Keep distance, stay out of feuds and avoid taking sides."],
 cnStep:['确认交友宫坐廉贞及星曜组合','看清朋友是否有才华、个性强、情绪起伏','善用专业与兴趣圈的交流机会','警惕卷进朋友的感情和恩怨','是非口舌尽量不掺和、不站队','与精彩的朋友保持舒服的距离'],
 enStep:["Confirm Lian-Zhen in Companions and its stars","See whether friends are talented, strong-willed and moody","Use exchange in professional and interest circles","Watch for being drawn into friends' romances and feuds","Stay out of gossip and avoid taking sides","Keep a comfortable distance from exciting friends"],
 cnMis:['只夸朋友有才华，不提醒感情纠葛','卷进朋友恩怨，把自己也搅进去','圈子一热闹就盲目站队，惹是非'],
 enMis:["Praising talent without noting emotional entanglements","Being drawn into friends' feuds and dragged in yourself","Blindly taking sides as circles heat up and courting trouble"],
 cnClose:'廉贞在交友宫让你身边不缺有才华、有故事的人，圈子精彩是真本事。只要守住边界、不掺和是非，精彩的关系就能给你灵感，而不是给你内耗。',
 enClose:"Lian-Zhen in Companions surrounds you with talented, story-rich people, and an exciting circle is a real asset. Hold boundaries and stay out of trouble, and exciting ties inspire you rather than drain you."},

{cat:'gongwei',slug:'ziwei-jumen-zai-jiaoyougong',focus:'巨门在交友宫',focusEn:'Ju-Men in the Companions Palace',
 cnT:'巨门在交友宫：朋友善言敢分析，宜研讨圈却防口舌伤人',enT:'Ju-Men in the Companions Palace: Articulate, Analytical Friends; Good for Debate Circles, Yet Guard Against Hurtful Words',
 cnD:'交友宫坐巨门，朋友多口才好、善分析、敢直言，适合讨论、辩论、研究型圈子，能互相拆台也互相长进；要防口舌争执、被朋友的话刺伤或彼此误解。',
 enD:"With Ju-Men in Companions, friends are articulate, analytical and outspoken, suiting discussion, debate and research circles where they challenge yet sharpen each other; guard against arguments, being hurt by friends' words and mutual misunderstanding.",
 cnL:'你跟朋友在一起很爱聊、爱辩，谁都有想法、敢直说，聊深了特别过瘾，但话赶话也容易说重了、顶起来，过后心里都不舒服。',
 enL:"With friends you love to talk and debate; everyone has views and speaks up, and deep talks are thrilling, but words can escalate and turn sharp, leaving both sides uneasy afterward.",
 cnA:'重点是「直言也要留情」：珍惜那些敢跟你讲真话、帮你看问题的朋友，但讨论归讨论、情绪归情绪，别争输赢争到伤感情；被话刺到时，也别闷在心里猜，把感受说开。',
 enA:"Plain speaking needs grace: cherish friends who tell the truth and help you see, but keep debate from emotion, and do not fight to win at the cost of friendship; when words sting, say your feelings rather than guessing in silence.",
 cnLog:['巨门主口、暗、分析与猜疑，落交友宫，朋友多口才好、敢直言。','宜讨论、辩论与研究型圈子，互相砥砺。','风险是口舌争执、被话刺伤与彼此误解。','应对是直言留情，论事不论人，有误会及时说开。'],
 enLog:["Ju-Men governs the mouth, the hidden, analysis and suspicion; in Companions, friends are articulate and outspoken.","It suits discussion, debate and research circles that sharpen each other.","The risk is arguments, hurtful words and misunderstanding.","Be frank yet gracious, debate the issue not the person, and clear misunderstandings quickly."],
 cnStep:['确认交友宫坐巨门及星曜','看清朋友是否口才好、爱分析、敢直言','善用研讨型圈子互相切磋','警惕争论升级、话说重了伤人','讨论对事不对人，不争输赢','被话刺到时及时沟通，不闷猜'],
 enStep:["Confirm Ju-Men in Companions and its stars","See whether friends are articulate, analytical and outspoken","Use debate circles to sharpen each other","Watch for escalating arguments and hurtful words","Debate the issue not the person and do not fight to win","Speak up when stung instead of guessing in silence"],
 cnMis:['只夸朋友敢说真话，不提醒口舌伤人','争输赢争到伤感情，过后后悔','被话刺中却闷着，误会越积越深'],
 enMis:["Praising honest speech without noting hurtful words","Winning arguments at the cost of friendship and regretting it","Stinging in silence and letting misunderstandings deepen"],
 cnClose:'巨门在交友宫给你一群敢说真话、帮你把问题想透的朋友，是难得的诤友。把直言留给事情、把留情留给人，越辩越明，而不越辩越远。',
 enClose:"Ju-Men in Companions gives you friends who speak truth and help you think things through, rare honest counselors. Save bluntness for the issue and grace for the person, so debate clarifies rather than alienates."},

{cat:'gongwei',slug:'ziwei-qisha-zai-jiaoyougong',focus:'七杀在交友宫',focusEn:'Qi-Sha in the Companions Palace',
 cnT:'七杀在交友宫：朋友果敢独立，宜一起开拓却防关系来去匆匆',enT:'Qi-Sha in the Companions Palace: Bold, Independent Friends; Good for Breaking New Ground, Yet Guard Against Ties That Come and Go',
 cnD:'交友宫坐七杀，朋友多果敢、有冲劲、独立性强，适合一起开拓新局、闯新领域，但关系来得快去得也快，合作中容易各不相让、硬碰硬。',
 enD:"With Qi-Sha in Companions, friends are bold, driven and independent, suiting breaking new ground and entering new fields, but ties come and go fast, and in cooperation both sides can refuse to yield and clash head-on.",
 cnL:'你交的朋友多半雷厉风行、自己拿主意，跟他们一起干很有干劲，但谁都有主见，合作时容易谁说了算上起冲突，关系也常一阵风就散了。',
 enL:"Your friends tend to act fast and decide for themselves; working with them is energetic, but as everyone has strong ideas, clashes over who leads are common, and ties often blow over quickly.",
 cnA:'重点是「闯劲也要讲分工」：善用敢冲的伙伴一起打新仗，但合伙前先把谁说了算、怎么分讲清楚；遇到分歧各退一步，别两个强人硬顶，硬顶的结果往往是事也黄了、朋友也没了。',
 enA:"Drive needs clear division: use bold partners for new battles, but settle who leads and how things split before partnering; compromise in disagreement and do not let two strong heads collide, or both the venture and the friendship end.",
 cnLog:['七杀主刚、冲劲、独立与开创，落交友宫，朋友多果敢有冲劲。','宜一起开拓新局、闯新领域。','风险是关系来去快、合作中各不相让。','应对是先定分工与决策权，分歧时各退一步。'],
 enLog:["Qi-Sha is hard, driven, independent and pioneering; in Companions, friends are bold and aggressive.","It suits breaking new ground and entering new fields together.","The risk is fast-come-fast-go ties and both sides refusing to yield.","Settle roles and decision rights first, and compromise when disagreeing."],
 cnStep:['确认交友宫坐七杀及星曜','看清朋友是否果敢、独立、有冲劲','善用敢冲的伙伴一起开拓新局','警惕关系来得快去得快','合伙前先定分工、决策权与分成','遇分歧各退一步，不硬碰硬'],
 enStep:["Confirm Qi-Sha in Companions and its stars","See whether friends are bold, independent and driven","Use aggressive partners to break new ground","Watch for fast-come-fast-go ties","Settle roles, decision rights and splits before partnering","Compromise in disagreements instead of head-on clashing"],
 cnMis:['只夸朋友敢闯，不提醒关系不稳','合作不分工，两个强人硬顶','把一时热血当长期伙伴，事后后悔'],
 enMis:["Praising boldness without noting unstable ties","Partnering without division so two strong heads clash","Mistaking short-term passion for a long-term partner and regretting it"],
 cnClose:'七杀在交友宫给你一群敢打敢冲的战友，一起开疆拓土特别带劲。只要先把规矩和分工摆在前头，闯劲就能变成战果，而不是硬碰硬后的散伙。',
 enClose:"Qi-Sha in Companions gives you bold comrades for breaking new ground, exciting to build territory with. Lay rules and roles upfront, and drive turns into results rather than a split after head-on clashes."},

{cat:'gongwei',slug:'ziwei-pojun-zai-jiaoyougong',focus:'破军在交友宫',focusEn:'Po-Jun in the Companions Palace',
 cnT:'破军在交友宫：朋友多变敢破局，宜创意圈却防关系突然生变',enT:'Po-Jun in the Companions Palace: Unconventional, Change-Making Friends; Good for Creative Circles, Yet Guard Against Sudden Shifts in Ties',
 cnD:'交友宫坐破军，朋友多变化大、不按常理、敢破旧立新，适合创意、变革、折腾型圈子，但关系不稳定，朋友常给你带来突发变动，计划容易被打乱。',
 enD:"With Po-Jun in Companions, friends are changeable, unconventional and keen to break the old, suiting creative, reforming, experimental circles, but ties are unstable and friends often bring sudden shifts that disrupt your plans.",
 cnL:'你身边的朋友多半不按牌理出牌，今天一个想法、明天一个新方向，跟他们在一起特别开脑洞，但也常被他们临时一变，原定的事就黄了。',
 enL:"Your friends tend to play by no rule, with a new idea today and a new direction tomorrow; it is mind-opening, but their sudden changes often scuttle what you had planned.",
 cnA:'重点是「创意也要留预案」：享受破旧立新的伙伴带来的火花，重要的合作却要留好备份和退路，别把全盘计划押在一个善变的朋友身上；变化来了能接就接，接不住就及时止损。',
 enA:"Creativity needs contingency: enjoy the spark of change-making partners, yet keep backups and exits for important deals and do not bet your whole plan on a mutable friend; ride the changes you can and cut losses when you cannot.",
 cnLog:['破军主耗、变革、破旧立新，落交友宫，朋友多变化大、不守常。','宜创意、变革与折腾型圈子，开脑洞。','风险是关系不稳定、朋友带来突发变动。','应对是重要合作留备份与退路，变化来了能接就接、接不住止损。'],
 enLog:["Po-Jun governs expenditure, reform and breaking the old; in Companions, friends are changeable and unconventional.","It suits creative, reforming and experimental circles that open the mind.","The risk is unstable ties and sudden changes friends bring.","Keep backups and exits for key deals; ride changes you can, cut losses when you cannot."],
 cnStep:['确认交友宫坐破军及星曜','看清朋友是否多变、不守常理、敢破局','善用创意变革型伙伴开脑洞','警惕朋友带来的突发变动','重要合作留备份、退路与止损线','变化来了能接就接，接不住及时调整'],
 enStep:["Confirm Po-Jun in Companions and its stars","See whether friends are changeable, unconventional and reform-minded","Use creative, reforming partners to open ideas","Watch for sudden shifts friends bring","Keep backups, exits and stop-loss lines for key deals","Ride changes you can and adjust when you cannot"],
 cnMis:['只夸朋友敢破局，不提醒变动风险','把全盘计划押在善变朋友身上','朋友一变就乱了阵脚，不设止损'],
 enMis:["Praising reform-making without noting change risk","Betting the whole plan on a mutable friend","Losing composure at each shift and setting no stop-loss"],
 cnClose:'破军在交友宫给你一群敢破旧、敢折腾的朋友，是创意和变革路上的好搭档。只要重要的事先留好退路，变化就只是惊喜，而不是把你生活打乱的意外。',
 enClose:"Po-Jun in Companions gives you friends who dare to break and experiment, great partners on the road of creativity and change. Keep exits for what matters, and change stays a surprise rather than an upheaval."},

{cat:'fuzhu',slug:'ziwei-huoxing-lingxing-kuaibao-menshao',focus:'火星铃星快爆与闷烧',focusEn:'Huo-Xing and Ling-Xing: quick burst and slow burn',
 cnT:'火星与铃星：一个快爆、一个闷烧，脾气与火气的两种打开方式',enT:'Huo-Xing and Ling-Xing: One Quick Burst, One Slow Burn; Two Ways Temper and Flare Play Out',
 cnD:'火星与铃星同属火性煞星，火星外显、来得猛去得快，铃星内滞、憋久了才爆。两星落不同宫位，象意不同，关键看是快爆型冲突还是闷烧型积怨。',
 enD:"Huo-Xing and Ling-Xing are both fiery malefics: Huo-Xing is external, flaring hard and fading fast, while Ling-Xing is internal, simmering until it erupts. Their meaning shifts by palace; the key is quick-burst conflict versus slow-burn resentment.",
 cnL:'火星在身边，脾气上来一阵风，发完也就完了；铃星则像闷烧，表面没事，心里那点火越积越深，哪天一件小事就炸出来。',
 enL:"With Huo-Xing around, temper flares like a gust and is over; Ling-Xing simmers, seemingly fine while the fire builds inside, until a small thing sets it off.",
 cnA:'重点是分宫看轻重：火星落命、迁移，多是冲动、急脾气、出门易摩擦；落疾厄，多是上火、炎症、睡眠躁；落财帛，多为急着赚钱、冲动消费；落福德，多是心里烦躁、静不下来。铃星则把这些情绪往后压、往里收，变成暗耗和积怨。',
 enA:"Weigh by palace: Huo-Xing in Life or Travel shows impulsiveness, short temper and friction on the road; in Health, inflammation and restless sleep; in Wealth, eagerness for money and impulse spending; in Mind, inner agitation and inability to settle. Ling-Xing pushes these inward, turning them into quiet drain and grudges.",
 cnLog:['火星主外显之火，来得猛、去得快，多为冲动与急性冲突。','铃星主内滞之火，闷烧累积，久憋后爆发，多为积怨与暗耗。','按命、迁移、疾厄、财帛、福德分宫，象意各有侧重。','加重看大运流年再逢、四煞聚、化忌同宫；缓冲看魁钺辅弼、化禄化科、天府太阴。'],
 enLog:["Huo-Xing is external fire: fierce, fast and short, mostly impulsiveness and acute conflict.","Ling-Xing is internal fire: slow-burning and erupting later, mostly resentment and quiet drain.","Read by Life, Travel, Health, Wealth and Mind palaces for different meanings.","It worsens on recurring in major or annual luck, gathering four malefics, or with Hua-Ji; it softens with Kui-Yue, Zuo-You, Hua-Lu, Hua-Ke, Tian-Fu and Tai-Yin."],
 cnStep:['先确认火星、铃星各自落在哪一宫','区分是外显快爆还是内滞闷烧','按命迁移疾厄财帛福德对号象意','查大运流年是否再逢、四煞是否会聚','看有无化忌同宫加重火气','借魁钺辅弼、化禄化科与天府太阴缓冲'],
 enStep:["First confirm the palace of each of Huo-Xing and Ling-Xing","Tell external quick burst from internal slow burn","Map meaning by Life, Travel, Health, Wealth and Mind","Check recurrence in major or annual luck and gathering of four malefics","See if Hua-Ji shares the palace and worsens the fire","Use Kui-Yue, Zuo-You, Hua-Lu, Hua-Ke, Tian-Fu and Tai-Yin to soften"],
 cnMis:['把火星铃星一概当「凶」，不分快慢内外','只看单星落宫，不查大运流年会合','只讲加重不讲缓冲，徒增焦虑'],
 enMis:["Treating both as simply 'bad' without telling quick from slow or inner from outer","Reading a star alone without checking major and annual luck","Only listing aggravators without buffers and breeding needless anxiety"],
 cnClose:'火星和铃星都是火气，一个发在明处、一个憋在心里。看懂自己是快爆还是闷烧，再结合宫位和大运流年看轻重，火气就能从脾气和暗耗，变成一股被接住的能量。',
 enClose:"Huo-Xing and Ling-Xing are both fire, one flaring in the open, one smoldering inside. Know whether you burst fast or burn slow, weigh it by palace and luck cycles, and the fire becomes energy you catch rather than temper and drain you."},

{cat:'fuzhu',slug:'ziwei-tianxing-tianyao-heyue-falv',focus:'天刑天姚与合约法律',focusEn:'Tian-Xing and Tian-Yao: contracts and legal boundaries',
 cnT:'天刑与天姚：一个管规则法律，一个管魅力名声，边界与分寸',enT:'Tian-Xing and Tian-Yao: One Rules and Law, One Charm and Reputation; Boundaries and Measure',
 cnD:'天刑主规则、纪律与法律边界，天姚主魅力、桃花与口碑名声。两星落在合约争议、公关合规、品牌授权等场景时，提示要把规矩和情面分开讲清，但它们不能单独断官司。',
 enD:"Tian-Xing governs rules, discipline and legal boundaries, while Tian-Yao governs charm, romance and reputation. In contract disputes, PR compliance and brand licensing, they signal separating rules from favor, yet they alone cannot decide a lawsuit.",
 cnL:'天刑重规矩，落在事情上总让人想到合同、条款、责任；天姚重人缘和好感，落在事情上则提示公关、口碑和形象。两者碰在一起，往往是「既要守规矩、又要顾体面」的难题。',
 enL:"Tian-Xing leans on rules and evokes contracts, clauses and liability; Tian-Yao leans on charm and evokes PR, word-of-mouth and image. Together they often pose the puzzle of both keeping to the rules and saving face.",
 cnA:'重点是「规矩归规矩、情面归情面」：涉及合约、授权、合规，先看条款和证据，再谈人情和形象；两星只是提示方向，不能单凭星象判断输赢，重大法律事务一律以专业律师和正规途径、书面合同为准。',
 enA:"Keep rules and favor apart: on contracts, licensing and compliance, read terms and evidence first, then talk of relationship and image; the stars only hint at direction and cannot alone decide outcomes, and major legal matters always rely on professional lawyers, formal channels and written contracts.",
 cnLog:['天刑主规则、纪律、法律与是非边界。','天姚主魅力、桃花、口碑与名誉形象。','在合约争议、公关合规、品牌授权场景，提示规矩与情面要分清。','两星不能单独断官司，重大法律事务以专业律师和正规途径、书面合同为准。'],
 enLog:["Tian-Xing governs rules, discipline, law and boundaries of right and wrong.","Tian-Yao governs charm, romance, reputation and public image.","In contract disputes, PR compliance and brand licensing, they signal separating rules from favor.","The two alone cannot decide a lawsuit; major legal matters rely on professional lawyers, formal channels and written contracts."],
 cnStep:['先确认天刑、天姚各自落宫与组合','看是否落在合约、公关、品牌相关场景','把规矩、条款、证据放在第一位','再谈人情、形象与公关分寸','涉及纠纷先固定证据、走正规途径','重大法律事务咨询专业律师，不凭星象下结论'],
 enStep:["First confirm the palace and combination of Tian-Xing and Tian-Yao","See whether they touch contracts, PR or brand scenarios","Put rules, terms and evidence first","Then weigh relationship, image and PR measure","Fix evidence and use formal channels on disputes","Consult professional lawyers on major matters and do not conclude from stars alone"],
 cnMis:['见天刑就说一定打官司，见天姚就说桃花惹祸','把星象当判决，不找律师不看合同','只讲情面不守条款，或只讲条款不顾口碑'],
 enMis:["Seeing Tian-Xing and predicting a lawsuit, or Tian-Yao and blaming romance","Treating stars as a verdict without lawyers or contracts","Keeping favor over terms, or terms while ignoring reputation"],
 cnClose:'天刑与天姚一个讲规矩、一个讲情面，像是提醒你：越是有魅力、有口碑的事，越要把合同和边界摆清楚。星象只点方向，真正的输赢交给证据和专业律师。',
 enClose:"Tian-Xing speaks rules and Tian-Yao speaks favor, reminding you that the more charming and reputation-driven the matter, the clearer the contract and boundaries must be. Stars only point the way; let evidence and professional lawyers decide the real outcome."}
];
