// 2026-09-27 调研驱动 第3组：主星/大限流年/财运 8篇
module.exports=[
{cat:'liunian',slug:'ziwei-2027-huan-gongzuo-guanlugong',focus:'2027换工作看官禄宫',focusEn:'2027 job change through Career Palace',
 cnT:'2027丁未年想换工作：别把官禄宫好当成该辞职',enT:'Thinking of Changing Jobs in 2027 Ding-Wei: Do Not Mistake a Good Career Palace for a Reason to Quit',
 cnD:'丁年太阴禄、天同权、天机科、巨门忌，官禄宫呈现的是年度气候，不是辞职判决书；换工作前先拆收入、上升空间、能否做久、生活可承受四问，再决定动不动。',
 enD:"In Ding-Wei, Tai-Yin Lu, Tian-Tong Quan, Tian-Ji Ke and Ju-Men Ji present the yearly climate on the career axis, not a verdict to quit. Before moving, unpack four questions: income, upward room, whether it lasts, and whether life can bear it.",
 cnL:'很多人一看官禄宫化禄就心动要跳槽，其实禄给的是机会与资源，不等于现在这份工不能做；真正该不该动，要落到具体条件上算。',
 enL:"Many see career Lu and feel like jumping ship, but Lu offers opportunity and resources, not proof the current job cannot work. Whether to move comes down to concrete conditions.",
 cnA:'丁年巨门忌落官禄，常见阻碍藏在沟通、合约、主管与能力缺口上。换工作前先把这四问写下来：新岗位收入能否覆盖过渡期、上升空间是否真实、能不能做满三年、生活与家庭是否扛得住。',
 enA:"In Ding-Wei, Ju-Men Ji on career often hides obstacles in communication, contracts, the manager and skill gaps. Before moving, write down four questions: does the new income cover the transition, is the upward room real, can it last three years, and can life and family bear it.",
 cnLog:['丁年四化：太阴化禄主资源与人缘、天同化权主缓和中掌权、天机化科主计划名声、巨门化忌主沟通合约口舌。','官禄宫在丁年呈现的是年度事业气候，禄权科是助力，巨门忌是该补的课。','巨门忌的阻碍常落在沟通不畅、合约条款不清、主管风格不合、自身能力缺口上。','换工作是决策，不是对一颗星的情绪反应，须用四问把星象翻译成现实条件。'],
 enLog:["Ding-Wei transformations: Tai-Yin Lu brings resources and rapport, Tian-Tong Quan brings gentle influence, Tian-Ji Ke brings planning and reputation, Ju-Men Ji brings communication and contract friction.","The Career Palace in Ding-Wei shows the yearly career climate; Lu, Quan and Ke help while Ju-Men Ji marks the lesson.","Ju-Men Ji obstacles often sit in poor communication, unclear contract terms, manager mismatch or personal skill gaps.","Changing jobs is a decision, not an emotional reaction to one star; the four questions translate the chart into real conditions."],
 cnStep:['先排出2027丁年四化，标出官禄宫被哪几颗引动','确认巨门忌落在沟通、合约、主管还是能力缺口','第一问收入：新岗位薪酬能否覆盖空窗与过渡期成本','第二问上升：晋升路径与技能成长是否真实可见','第三问耐久：岗位与团队能否让自己做满三年','第四问承受：通勤、家庭、生活节奏是否扛得住再动'],
 enStep:["Cast the 2027 Ding-Wei transformations and mark which ones touch the Career Palace","Locate whether Ju-Men Ji hits communication, contracts, the manager or a skill gap","Question one, income: does the new pay cover the gap and transition costs","Question two, upward: are the promotion path and skill growth real and visible","Question three, durability: can the role and team last three years","Question four, bearing: commute, family and life pace must hold before you move"],
 cnMis:['看官禄化禄就认定该辞职，把机会当成判决','把巨门忌只当口舌，不查合约与能力缺口','不算过渡成本与生活承受，凭心动就跳槽'],
 enMis:["Seeing career Lu and concluding one should quit, mistaking opportunity for a verdict","Treating Ju-Men Ji as mere gossip and skipping contracts and skill gaps","Moving on impulse without calculating transition costs and life bearing"],
 cnClose:'官禄宫好，是告诉你这一年事业有戏，不是催你立刻辞职。把四问答清楚，禄权是锦上添花，巨门忌是提前补的课，换不换都换得明白。',
 enClose:"A good Career Palace tells you the year has career potential, not that you must quit now. Answer the four questions clearly; Lu and Quan are icing, Ju-Men Ji is the lesson to prep, and you move or stay with understanding."},

{cat:'zhuxing',slug:'ziwei-guanlugong-zhuxing-bushi-zhiye-pei',focus:'官禄宫主星不是职业配对',focusEn:'Career Palace star is not a job match',
 cnT:'官禄宫主星不等于职业配对：星曜说的是角色不是行当',enT:'The Career Palace Major Star Is Not a Job Match: The Star Describes a Role, Not a Trade',
 cnD:'官禄宫主星描述的是一个人在工作中扮演的角色、承担的责任、做事方式与公共表现，不是「你该做哪一行」的标签；选职业还要补职位、能力、绩效、薪资与市场资料。',
 enD:"The Career Palace major star describes the role one plays at work, the responsibilities carried, the working style and public performance, not a label of which trade to enter. Choosing a career still needs the job title, skills, performance, pay and market data.",
 cnL:'「你官禄宫是紫微，所以你该当老板」这类说法最省事也最误导——它把一种领导风格直接翻译成了一个职业，中间跳过了太多现实。',
 enL:"Statements like your Career Palace is Ziwei so you should be a boss are the laziest and most misleading; they translate a leadership style straight into a job, skipping too much reality.",
 cnA:'星曜给的是工作中的「样子」：是统筹还是执行、是照顾人还是冲业绩、是稳扎稳打还是灵活多变。具体做什么岗位、拿多少薪水、市场要不要，要靠招聘信息、能力盘点和绩效数据来补。',
 enA:"The star gives the shape of working: coordinating or executing, caring for people or chasing targets, steady or flexible. Which exact role, what pay and whether the market wants it must be filled by job postings, a skill inventory and performance data.",
 cnLog:['官禄宫主星描述角色、责任、工作方式与公共表现，是一种行为倾向。','它不是职业标签，不能直接对应「医生、律师、程序员」等行当。','同一颗星在不同行业、不同职位上可以有完全不同的落地方式。','职业决策须叠加职位描述、能力盘点、绩效记录、薪资行情与市场需求。'],
 enLog:["The Career Palace major star describes role, responsibility, working style and public performance as a behavioral tendency.","It is not a job label and cannot map directly onto doctor, lawyer, programmer and so on.","The same star lands very differently across industries and positions.","Career decisions must add job descriptions, a skill inventory, performance records, pay ranges and market demand."],
 cnStep:['先读官禄宫主星，写下它描述的角色与做事方式','把它翻译成行为倾向，而不是一个职业名称','列出自己真实做过的职位与承担的责任','盘点现有能力、绩效成果与可迁移技能','对照招聘市场，看哪些岗位真的匹配这些倾向','结合薪资行情与个人条件，再做职业选择'],
 enStep:["Read the Career Palace star and write down the role and working style it describes","Translate it into a behavioral tendency, not a job title","List the positions actually held and responsibilities carried","Inventory existing skills, performance results and transferable abilities","Compare the job market to see which roles truly match these tendencies","Combine pay ranges and personal conditions before choosing"],
 cnMis:['把主星直接当职业标签，说某星必做某行','只看星不看职位描述与能力盘点','忽略市场需求与薪资行情，凭星象择业'],
 enMis:["Treating the major star as a job label and saying a star must do a trade","Reading only the star without job descriptions and a skill inventory","Ignoring market demand and pay ranges and choosing by the chart alone"],
 cnClose:'官禄宫主星告诉你「你在工作里像谁」，不告诉你「你该去哪一行」。把星曜当风格参考，把职位、能力、市场当决策依据，职业这条路才选得稳。',
 enClose:"The Career Palace star tells you who you are like at work, not which trade to enter. Treat the star as a style reference and the job, skills and market as the decision basis, and your career choice holds."},

{cat:'zhuxing',slug:'ziwei-guanlugong-gongzuo-tiaojian',focus:'官禄宫是一组工作条件',focusEn:'Career Palace as a set of working conditions',
 cnT:'官禄宫是一组工作条件：天同太阴天梁在官禄意味着什么',enT:'The Career Palace as a Set of Working Conditions: What Tian-Tong, Tai-Yin and Tian-Liang There Mean',
 cnD:'官禄宫星曜组合给出的是一组让人愿意持续做下去的工作条件；天同、太阴、天梁落官禄，往往更在意环境舒适、照顾他人与社会意义，选职要从「适合什么工作」改成「什么条件能让人做久」。',
 enD:"The Career Palace star combination gives the working conditions under which a person keeps going. Tian-Tong, Tai-Yin and Tian-Liang there often point to comfort, caring for others and social meaning; choose work by what conditions let you last, not by a job title.",
 cnL:'有人换了好几份高薪工作还是觉得不对味，问题可能不在钱，而在这份工缺了他真正在意的那组条件——环境、人、意义感。',
 enL:"Some leave several well-paid jobs and still feel off; the problem may not be money but the missing conditions they truly care about: environment, people, a sense of meaning.",
 cnA:'天同主享受与随和、太阴主细腻与照顾、天梁主荫庇与社会价值。三星聚官禄，工作选择更看重氛围舒服、能帮到人、有公共意义；把问题从「我适合什么职业」换成「什么条件下我能持续投入」，答案会具体得多。',
 enA:"Tian-Tong is ease and ease-going, Tai-Yin is care and sensitivity, Tian-Liang is protection and social value. With these in Career, work choices weigh a comfortable atmosphere, helping people and public meaning; ask under what conditions I can keep investing rather than what career suits me, and the answer gets concrete.",
 cnLog:['官禄宫星曜组合可解读为一组让人持续投入的工作条件。','天同主环境舒适、节奏随和，不喜高压紧绷。','太阴主细腻照顾、关注他人与幕后支持。','天梁主荫庇、社会意义与公共服务倾向。'],
 enLog:["The Career Palace star combination can be read as the working conditions that sustain engagement.","Tian-Tong favors a comfortable setting and easy pace over high pressure.","Tai-Yin favors sensitive care, attention to others and behind-the-scenes support.","Tian-Liang favors protection, social meaning and public service."],
 cnStep:['先看自己官禄宫是哪几颗星的组合','把每颗星翻译成它在意的工作条件','天同对应环境与节奏，太阴对应照顾与支持','天梁对应意义感与公共价值','列出当前工作缺了哪几条条件','按「什么条件能做久」重新评估岗位与机会'],
 enStep:["First read which stars combine in your Career Palace","Translate each star into the working condition it cares about","Tian-Tong maps to environment and pace, Tai-Yin to care and support","Tian-Liang maps to meaning and public value","List which conditions the current job lacks","Reassess roles and opportunities by what conditions let you last"],
 cnMis:['把官禄宫星曜当职业标签，不看工作条件','只盯薪资福利，忽略环境与意义感','忽略组合差异，笼统说某星适合某行'],
 enMis:["Treating Career stars as job labels and ignoring working conditions","Focusing only on pay and benefits while missing environment and meaning","Ignoring combination differences and broadly matching a star to a trade"],
 cnClose:'官禄宫不是一张职业配对表，而是一张「工作条件清单」。天同要舒服、太阴要照顾、天梁要意义，把这几条凑齐，工作才能做得久、做得心甘情愿。',
 enClose:"The Career Palace is not a job-matching table but a working-conditions checklist. Tian-Tong wants comfort, Tai-Yin wants care, Tian-Liang wants meaning; meet these and work lasts willingly."},

{cat:'liunian',slug:'ziwei-2026-shiyue-liuyue-sihua-hezuo',focus:'2026十月流月四化与合作留痕',focusEn:'Oct 2026 monthly transformations and cooperation records',
 cnT:'2026丙午年十月亥月：流月四化下的合作要留痕',enT:'The Tenth Month of Bing-Wu 2026: Leaving Written Records Under the Monthly Transformations',
 cnD:'十月亥月己干，武曲化禄、贪狼化权、天梁化科、文曲化忌；谈收入、合作与曝光时容易口头说好却落不下，要把负责人、期限、验收标准、金流状态四字段写成书面记录。',
 enD:"In the tenth month, Hai, the Ji stem brings Wu-Qu Lu, Tan-Lang Quan, Tian-Liang Ke and Wen-Qu Ji. When discussing income, partnership and exposure, things are easily agreed verbally but left hanging; write down owner, deadline, acceptance criteria and payment status in a record.",
 cnL:'这个月谈合作往往聊得很热、条件讲得很满，但文曲忌偏偏卡在讯息、口头承诺和文书上——话讲了不算数，落了纸才算。',
 enL:"This month partnerships are discussed warmly and terms sound full, yet Wen-Qu Ji sits right on messages, verbal promises and paperwork; spoken words do not count, only what is written does.",
 cnA:'武曲禄利于谈收入、贪狼权利于抢资源与曝光、天梁科利于名声背书，但文曲忌提醒：所有承诺必须留痕。每一项合作都落到四个字段——负责人是谁、期限到哪天、验收标准是什么、金流走到哪一步；涉及合同与权利义务，以专业律师和正规途径、书面合同为准。',
 enA:"Wu-Qu Lu helps with income talks, Tan-Lang Quan with resources and exposure, Tian-Liang Ke with reputation backing, but Wen-Qu Ji warns: every promise must be recorded. Land each cooperation on four fields: who owns it, the deadline, the acceptance criteria and the payment stage; where contracts and rights are concerned, defer to professional lawyers, proper channels and written agreements.",
 cnLog:['十月亥月己干四化：武曲禄主收入、贪狼权主资源与曝光、天梁科主名声、文曲忌主讯息文书。','禄权科同框，利于谈钱、抢资源、做曝光的合作话题。','文曲忌提示口头承诺易漂移，讯息与文书是本月最易出错处。','合作要留痕，把口头共识转成可核对的书面字段。'],
 enLog:["The tenth Hai month Ji-stem transformations: Wu-Qu Lu for income, Tan-Lang Quan for resources and exposure, Tian-Liang Ke for reputation, Wen-Qu Ji for messages and paperwork.","Lu, Quan and Ke together favor talks on money, resources and exposure.","Wen-Qu Ji warns verbal promises drift and that messages and documents are the month's weak point.","Cooperation must leave traces, turning verbal consensus into checkable written fields."],
 cnStep:['先确认十月亥月己干四化落入哪些宫','禄权科引动的合作话题：收入、资源、曝光、名声','识别文曲忌落在哪个合作环节的讯息或文书','为每项合作写下负责人与期限','写下验收标准与交付物清单','写下金流状态：定金、节点款、尾款走到哪一步'],
 enStep:["Confirm where the Hai-month Ji-stem transformations land","Identify the cooperation topics Lu, Quan and Ke activate: income, resources, exposure, reputation","Find which cooperation step Wen-Qu Ji hits in messages or paperwork","Write down the owner and deadline for each cooperation","Write down acceptance criteria and a deliverables list","Write down payment status: deposit, milestone and balance stages"],
 cnMis:['聊得热就当合作定了，不留任何书面记录','把文曲忌只当聊天不顺，不补文书','涉及权利义务仍靠口头，不走书面合同'],
 enMis:["Treating a warm chat as a settled deal with no written record","Taking Wen-Qu Ji as mere chat friction without paperwork","Relying on words rather than a written contract for rights and obligations"],
 cnClose:'这个月合作不缺热度，缺的是留痕。把负责人、期限、验收标准、金流状态四字段写清楚，禄权科的机会才不会被文曲忌的一场口头误会吞掉；正式合同务必以专业律师和正规途径、书面合同为准。',
 enClose:"This month partnerships lack not warmth but records. Write the four fields clearly, owner, deadline, acceptance criteria and payment status, or Lu, Quan and Ke opportunities get swallowed by a Wen-Qu Ji verbal misunderstanding; for formal contracts, defer to professional lawyers, proper channels and written agreements."},

{cat:'liunian',slug:'ziwei-daxian-jiaojie-nian-guodu',focus:'大限交接年的过渡',focusEn:'transition at decade-limit boundary',
 cnT:'大限交接年：两步大限交界那几年怎么过',enT:'The Decade-Boundary Year: How to Navigate the Years at the Edge of Two Decades',
 cnD:'大限每十年一换，交界那两年旧十年主题收尾、新十年主题启动，职业、居住、关系容易同时变动；宜提前布局、留有余地，不做不可逆的激进决策。',
 enD:"Decades change every ten years; at the boundary years, the old ten-year theme winds down and the new one starts, so career, housing and relationships often move at once. Plan early, keep slack and avoid irreversible aggressive moves.",
 cnL:'有些人某一年突然工作、房子、感情全动了起来，事后一看，正好卡在两步大限交界——旧的要收、新的要开，几件事挤在同一年。',
 enL:"When one year suddenly moves work, housing and romance at once, in hindsight it often sits at the edge of two decades: the old must close and the new open, and several things crowd into the same year.",
 cnA:'交接年不是凶年，而是「换挡年」。旧大限未完成的课题会在收尾期集中浮现，新大限的主题也开始冒头。正确做法是提前半年到一年布局，把该收的收掉、该试的小步试，别在信息未明时下重注。',
 enA:"A boundary year is not an unlucky year but a gear-shift year. Unfinished lessons of the old decade surface at wind-down, while the new decade's themes begin to appear. The right move is to plan six to twelve months ahead, close what must close and test in small steps, rather than betting big before the picture clears.",
 cnLog:['大限每十年一换，交界前后两年是主题切换的过渡期。','旧大限的残余课题在收尾期集中浮现，需了结。','新大限的主宫与主题开始启动，新的发力方向冒头。','几件人生大事容易在同一年同时变动，资源被分散。'],
 enLog:["Decades shift every ten years, and the years around the boundary are a transition between themes.","Residual lessons of the old decade surface at wind-down and need closing.","The new decade's main palace and theme start up, and a new direction appears.","Several major life events often move in the same year, spreading resources thin."],
 cnStep:['先排出大限起止年份，确认自己是否在交接前后','列出旧大限未了结的课题，安排收尾','观察新大限命宫与三方，识别新主题','把可能同时变动的职业、居住、关系排队','提前半年到一年布局，小步试新方向','交接期不做不可逆激进决策，留足余地'],
 enStep:["Cast the decade start and end years and confirm whether you are near the boundary","List unfinished lessons of the old decade and schedule their closure","Observe the new decade Life and trine to identify the new theme","Queue up career, housing and relationships that may move at once","Plan six to twelve months ahead and test the new direction in small steps","Avoid irreversible aggressive moves during transition and keep slack"],
 cnMis:['把交接年当凶年，惊慌失措做大改动','几件事同时变动时全上，不留余地','只看旧大限收尾，不提前看新大限主题'],
 enMis:["Treating a boundary year as ill-fated and panicking into big changes","Moving on several fronts at once without slack","Only closing the old decade and failing to preview the new theme"],
 cnClose:'大限交接年是换挡，不是翻车。旧课题收尾、新主题起步，提前布局、小步试探、不赌重注，这道坎就能平顺地跨过去。',
 enClose:"A decade boundary is a gear shift, not a crash. Close old lessons, start the new theme, plan ahead, test small and avoid heavy bets, and you cross this threshold smoothly."},

{cat:'yingyong',slug:'ziwei-liunian-caibogong-shouru-jiegou',focus:'流年财帛宫看收入结构',focusEn:'yearly Wealth Palace and income structure',
 cnT:'流年财帛宫：用主星与四化拆一年的收入结构',enT:'The Yearly Wealth Palace: Decompose One Year of Income by Star and Transformations',
 cnD:'流年财帛宫主星与四化可区分主动收入、被动收入、偏财与合作财；化禄看机会、化权看议价、化科看专业溢价、化忌看支出与牵挂，本文不构成投资建议，以持牌机构和正规产品说明为准。',
 enD:"The yearly Wealth Palace star and transformations distinguish active income, passive income, windfall and partnership money: Lu shows opportunity, Quan bargaining power, Ke professional premium and Ji spending and obligations. This is not investment advice; defer to licensed institutions and official product documentation.",
 cnL:'一年赚多少钱是个总数，真正决定松紧的是结构——工资、副业、租金、分红、报销、客户款，来源不同，抗风险能力完全不同。',
 enL:"Total yearly income is one number, but structure decides how tight things feel: salary, side work, rent, dividends, reimbursements and client payments differ in risk resilience.",
 cnA:'流年财帛宫主星提示这一年钱从哪类渠道来，四化进一步细化：禄是机会来了、权是你有议价空间、科是靠专业口碑溢价、忌是钱有去处或被牵住。看结构不猜数字，更不靠星象决定买卖任何产品；本文不构成投资建议，以持牌机构和正规产品说明为准。',
 enA:"The yearly Wealth star hints which channel money comes from, and the transformations refine it: Lu is opportunity arriving, Quan is bargaining room, Ke is a professional premium, Ji is money with a destination or a tie-up. Read the structure rather than guessing numbers, and never choose a product by the chart; this is not investment advice, defer to licensed institutions and official product documentation.",
 cnLog:['流年财帛宫主星提示当年收入主要来自哪类渠道。','主动收入靠时间与技能交换，被动收入靠资产与系统。','化禄看机会、化权看议价、化科看专业溢价、化忌看支出牵挂。','星象只做结构参考，具体产品与买卖须以正规渠道为准。'],
 enLog:["The yearly Wealth Palace star hints which channel the year's income mainly comes from.","Active income trades time and skill; passive income relies on assets and systems.","Lu shows opportunity, Quan bargaining power, Ke professional premium and Ji spending and obligations.","The chart is only a structural reference; specific products and trades follow proper channels."],
 cnStep:['先定流年财帛宫主星，判断主要收入渠道','拆主动收入：工资、兼职、按项目收费','拆被动与偏财：租金、利息、分红、偶发所得','看化禄：机会在哪个渠道出现','看化权化科：议价与专业溢价能否提价','看化忌：钱被哪项支出或牵挂牵住，做好预留'],
 enStep:["Set the yearly Wealth Palace star and judge the main income channel","Split active income: salary, side work, project fees","Split passive and windfall: rent, interest, dividends, occasional gains","Read Lu for which channel offers opportunity","Read Quan and Ke for whether bargaining and a professional premium raise rates","Read Ji for which expense or obligation ties up money and build a reserve"],
 cnMis:['把流年财帛宫直接当发财或破财的预言','按星象买卖金融产品，不走正规渠道','只看总数不看结构，忽略被动收入与支出牵挂'],
 enMis:["Treating the yearly Wealth Palace as a direct prediction of wealth or loss","Trading financial products by the chart instead of proper channels","Looking only at the total and missing passive income and spending ties"],
 cnClose:'流年财帛宫不是一张藏宝图，而是一张收入结构图。分清主动、被动、偏财与合作财，再用禄权科忌标出机会与牵挂；本文不构成投资建议，以持牌机构和正规产品说明为准。',
 enClose:"The yearly Wealth Palace is not a treasure map but an income-structure map. Separate active, passive, windfall and partnership money, then use Lu, Quan, Ke and Ji to mark opportunities and ties; this is not investment advice, defer to licensed institutions and official product documentation."},

{cat:'zhuxing',slug:'ziwei-ziwei-minggong-lingdao-fengge',focus:'紫微星在命宫的领导风格',focusEn:'Ziwei in Life Palace leadership style',
 cnT:'紫微星坐命：自尊、主导与领导欲的一体两面',enT:'Ziwei in the Life Palace: The Two Sides of Self-Esteem, Dominance and Drive to Lead',
 cnD:'紫微坐命者自尊高、喜主导、有领导欲，适合需要统筹与决策的角色；要防刚愎自用、面子过重与事必躬亲，三方四正有无辅佐与煞星调和决定这种风格走多远。',
 enD:"Those with Ziwei in the Life Palace carry high self-esteem, prefer to lead and want to direct; they suit roles needing coordination and decisions. Guard against stubbornness, face-saving and micromanagement; whether assistants and malefics in the trine balance it decides how far the style goes.",
 cnL:'紫微坐命的人多半有气场、敢拍板、愿意扛事，但同一股劲用过头，就变成听不进意见、死要面子、什么都要自己抓。',
 enL:"Ziwei Life people often have presence, dare to decide and are willing to take charge, but the same force in excess becomes not listening, face-saving and grabbing everything.",
 cnA:'紫微是帝星，坐命者天然适合统筹与决策岗位。但帝王也需要辅佐：三方四正见左辅右弼、天府天相等助力，领导风格能成事；见煞星无调和，则易刚愎、孤立。关键是把主导欲用在对的位置，学会授权。',
 enA:"Ziwei is the emperor star, and Life natives naturally fit coordination and decision roles. But an emperor needs ministers: assistants like Zuo-Fu, You-Bi, Tian-Fu and Tian-Xiang in the trine make the leadership effective; unbalanced malefics bring stubbornness and isolation. The key is to direct the dominance where it belongs and learn to delegate.",
 cnLog:['紫微为帝星，主尊贵、统筹、决策与格局，坐命者自尊高、喜主导。','适合需要拍板、整合资源、承担责任的领导角色。','副作用是刚愎自用、面子过重、事必躬亲、难以授权。','三方四正的辅佐星添助力，煞星无调和则放大刚愎。'],
 enLog:["Ziwei is the emperor star of dignity, coordination, decision and vision; Life natives have high self-esteem and prefer to lead.","They suit roles that decide, integrate resources and take responsibility.","Side effects are stubbornness, heavy face-saving, micromanagement and poor delegation.","Assistant stars in the trine add support; unbalanced malefics amplify stubbornness."],
 cnStep:['先确认命宫主星为紫微，看是否独坐或带同宫星','列出天然适合的统筹决策类角色','识别刚愎、面子、事必躬亲的具体表现','查三方四正有无左辅右弼天府天相等辅佐','查有无煞星会照及其调和方式','在实际工作中练习授权与听取不同意见'],
 enStep:["Confirm Ziwei as the Life Palace star and whether it is alone or paired","List coordination and decision roles it naturally fits","Identify concrete signs of stubbornness, face-saving and micromanagement","Check the trine for assistants such as Zuo-Fu, You-Bi, Tian-Fu, Tian-Xiang","Check malefics and how they are balanced","Practice delegating and hearing dissent at work"],
 cnMis:['只夸帝王气场，不提醒刚愎与面子的代价','把紫微坐命直接等同于必当老板','忽略三方四正辅佐与煞星，风格评估失真'],
 enMis:["Praising imperial presence without warning the cost of stubbornness and face-saving","Equating Ziwei Life with destined bosshood","Ignoring trine assistants and malefics so the style is misread"],
 cnClose:'紫微坐命给你一副能扛事、敢拍板的底子，但帝星也得靠辅佐。把主导欲用在统筹上，把面子和事必躬亲放下，这颗帝星才坐得稳、走得远。',
 enClose:"Ziwei Life gives you the backbone to carry things and decide, but even an emperor needs ministers. Aim the dominance at coordination, set aside face and micromanagement, and the imperial seat holds and lasts."},

{cat:'zhuxing',slug:'ziwei-tianji-minggong-shanbian-duolv',focus:'天机星在命宫的善变与多虑',focusEn:'Tian-Ji in Life Palace: changeability and overthinking',
 cnT:'天机星坐命：聪明善思与多虑摇摆的平衡术',enT:'Tian-Ji in the Life Palace: Balancing Clever Quick Thinking with Overthinking and Indecision',
 cnD:'天机坐命者聪明善思、点子多、适应力强，但易多虑、摇摆、执行跟不上想法；用书面计划与截止时间治过度思考，三方有无稳星定盘决定能否落地。',
 enD:"Tian-Ji Life natives are clever, thoughtful, idea-rich and adaptable, but prone to overthinking, wavering and execution that lags behind ideas. Treat overthinking with written plans and deadlines; whether steady stars in the trine anchor it decides whether ideas land.",
 cnL:'天机坐命的人脑子转得快、主意一个接一个，可问题往往是想得太多、动得太慢，一个念头还没落地上一个已经冒出来。',
 enL:"Tian-Ji Life minds spin fast with one idea after another, but the trouble is often thinking too much and moving too slowly; the next idea arrives before the first lands.",
 cnA:'天机主智慧、变动与策划，是军师型的脑子。要发挥它，就得给聪明装上刹车和跑道：把想法写下来、排优先级、定截止时间，让执行追得上灵感。三方见天府、天相等稳星，点子更容易落定；见煞星无制，则摇摆加重。',
 enA:"Tian-Ji governs wit, change and planning, a strategist's mind. To use it, fit the cleverness with brakes and a runway: write ideas down, rank them, set deadlines so execution keeps up with inspiration. Steady stars like Tian-Fu and Tian-Xiang in the trine help ideas settle; unbalanced malefics worsen wavering.",
 cnLog:['天机主智慧、机变、策划，坐命者聪明、反应快、点子多。','适应力强，善于在变化中找路，适合策划与变通类工作。','副作用是多虑、摇摆、兴趣易转移、执行落后于想法。','三方四正的稳星与截止机制帮助把念头落地。'],
 enLog:["Tian-Ji governs wit, adaptability and planning; Life natives are clever, quick and idea-rich.","They adapt well, navigate change and suit planning and flexible work.","Side effects are overthinking, wavering, shifting interests and execution lagging ideas.","Steady stars and deadline mechanisms in the trine help ideas land."],
 cnStep:['先确认命宫主星为天机，看同宫与三方星','列出聪明、机变、策划的优势场景','识别多虑、摇摆、执行慢的具体表现','把冒出的想法逐条写下来，不靠脑子硬记','给每条想法排优先级并定截止时间','查三方有无稳星定盘，必要时借外力约束执行'],
 enStep:["Confirm Tian-Ji as the Life star and read companions and trine","List scenarios where wit, adaptability and planning shine","Identify concrete signs of overthinking, wavering and slow execution","Write down each idea instead of holding it in mind","Rank ideas and set a deadline for each","Check whether steady stars anchor the trine and use external discipline when needed"],
 cnMis:['只夸聪明点子多，不提醒多虑与执行慢的代价','把善变当优点，不做计划与截止约束','忽略三方稳星，念头飘来飘去落不了地'],
 enMis:["Praising clever ideas without warning the cost of overthinking and slow execution","Treating changeability as a virtue without plans and deadlines","Ignoring steady trine stars so ideas drift and never land"],
 cnClose:'天机坐命给你一颗转得快的脑子，但脑子快也要有跑道。把想法写下来、排好优先级、卡死截止时间，聪明才不会被多虑耗成一场空转。',
 enClose:"Tian-Ji Life gives you a fast-spinning mind, but a fast mind also needs a runway. Write ideas down, rank them and lock deadlines, or cleverness burns as empty overthinking."}
];
