// 2026-09-27 调研驱动 第1组：看盘方法/校时/四化基础 8篇
module.exports=[
{cat:'kanpan',slug:'ziwei-zhen-taiyangshi-chushengdi-jingdu',focus:'真太阳时与出生地经度',focusEn:'true solar time and birthplace longitude',
 cnT:'紫微斗数真太阳时：出生地经度差一点，命宫就排到别处',
 enT:'True Solar Time and Birthplace Longitude in Zi Wei Dou Shu: A Degree Off Shifts the Life Palace',
 cnD:'钟表时间是统一时区的平太阳时，排盘要先换算成出生地的真太阳时，再叠加经度修正与均时差；不做这一步，同一生日不同城市会排出两张不同的盘。',
 enD:"Clock time is uniform mean time for a whole time zone; casting first converts it to the true solar time of the birthplace, then applies longitude correction and the equation of time. Skip this and one birthday in two cities yields two different charts.",
 cnL:'经常有人拿同样的出生年月日时去问，结果两个人排出来的盘不一样，以为是软件出错。其实差的往往不是日子，而是你按钟表时间直接排，没把出生地的经度和当天的均时差算进去。',
 enL:"People bring the same birth date and hour yet get two different charts and blame the software. The gap is usually not the date but casting from clock time without converting birthplace longitude and the day's equation of time.",
 cnA:'真太阳时要回答的是：太阳在你出生地正上方的那一刻，和你墙上钟表指的那一刻，到底差了多少。这个差值不补上，命宫安在哪一宫就是错的，后面全盘跟着错。',
 enA:"True solar time asks how far the moment the sun is overhead at your birthplace differs from what your wall clock showed. Without that correction the Life Palace lands in the wrong position and the whole chart follows.",
 cnLog:['钟表时间是国家统一规定的平太阳时，同一时区都用它，但它不代表太阳真实走到了你出生地的头顶。','经度修正按出生地相对时区中央经线的偏差计算，每偏一度约差四分钟，东早西晚。','均时差是地球公转轨道椭圆与黄赤交角造成的差值，一年里在正负十几分钟内浮动，需按出生日查算。','夏令时期间钟表被人为拨快一小时，要先拨回标准时间再换算；逢23点子时前后还要分清早晚子时边界。'],
 enLog:["Clock time is the uniform mean time a whole time zone shares, but it does not mean the sun is truly overhead at your birthplace.","Longitude correction follows the birthplace's offset from the time zone's central meridian, about four minutes per degree, earlier to the east.","The equation of time arises from the elliptical orbit and the tilted axis and swings within plus or minus about fifteen minutes over the year.","During daylight saving the clock was set forward an hour; set it back to standard before converting, and handle the 11 p.m. midnight boundary carefully."],
 cnStep:['先记下钟表显示的出生时间和出生地经纬度','确认出生当年当地是否实行夏令时，若有则先减一小时','按出生地与时区中央经线的经度差，算出经度修正分','查出生当日的均时差，叠加到经度修正上','把修正后的时间换算回十二时辰，注意23点前后的早晚子时','用校正后的真太阳时排盘，再与原钟表时间盘对比差异'],
 enStep:["Record the clock birth time and the birthplace longitude and latitude","Check whether daylight saving applied that year; if so, subtract an hour first","Compute the longitude correction from the birthplace's offset to the zone central meridian","Look up the equation of time for the birth day and add it to the longitude correction","Convert the corrected time into a shichen, watching the late and early midnight boundary","Cast from the corrected true solar time and compare it with the clock-time chart"],
 cnMis:['拿钟表时间直接排盘，不做经度与均时差修正','以为同一时区出生就不用换算经度','忽略夏令时或当年的拨钟记录，多算或少算一小时'],
 enMis:["Casting straight from clock time without longitude and equation-of-time correction","Assuming one time zone means no longitude conversion matters","Ignoring daylight saving or the clock change and adding or missing an hour"],
 cnClose:'排盘前多花几分钟把真太阳时算准，是在给整张盘打地基。经度、均时差、夏令时这三关过了，同一生日排出的盘才是你自己的盘。',
 enClose:"Spending a few minutes on true solar time before casting lays the chart's foundation. Once longitude, the equation of time and daylight saving are handled, the chart from your birthday is truly yours."},

{cat:'kanpan',slug:'ziwei-chusheng-shijian-wucha-minpan-yingxiang',focus:'出生时间误差对命盘稳定性',focusEn:'birth-time error and chart stability',
 cnT:'紫微斗数出生时间差半小时，命宫会偏多少',
 enT:'How Much a Half-Hour Birth-Time Error Shifts the Life Palace in Zi Wei Dou Shu',
 cnD:'一个时辰管两小时，出生时间偏移约半小时，命宫沿盘面挪过约四分之一格，格局就有了实质改变；偏到两小时整，命宫整格移位。八字时柱与紫微命宫共用这条两小时边界，不能拿来当独立交叉验证。',
 enD:"One shichen spans two hours. Shifting birth time by about half an hour moves the Life Palace a quarter of a step along the chart and materially changes the pattern; a full two hours shifts it a whole step. The Bazi hour pillar and the Zi Wei Life Palace share the same two-hour boundary, so neither independently cross-checks the other.",
 cnL:'很多人排完盘很放心，觉得差个十几二十分钟无所谓。其实紫微的命宫是按两小时一格切的，时间一旦越过格线，整张盘的坐标就换了。',
 enL:"Many cast confidently, thinking ten or twenty minutes do not matter. But the Zi Wei Life Palace is cut into two-hour steps; once the time crosses a boundary, the whole chart's coordinates change.",
 cnA:'这里要算清两笔账：第一，误差多大时命宫才动；第二，八字和紫微是不是能互相验证。结论是它们共用同一条两小时边界，一错俱错，不能当两张独立的票来对冲。',
 enA:"Two questions must be settled: how much error moves the Life Palace, and whether Bazi and Zi Wei cross-check each other. The answer is that they share one two-hour boundary and err together, so neither hedges the other.",
 cnLog:['紫微命宫以两小时为一格划分，时间在格内移动时，命宫格位不变但盘中细部星曜仍有微调。','时间偏移约半小时，命宫已逼近格线，格局、三方四正的净效果开始出现可感改变。','偏移达到约两小时，命宫整格跨过边界，十二宫整体重排，等于换了一张盘。','八字时柱同样按两小时切换，与紫微命宫共用边界，两者同时偏移，不能互为独立证据。'],
 enLog:["The Life Palace is divided into two-hour steps; time moving within a step keeps the palace but still tweaks finer stars.","A half-hour shift pushes the Life Palace toward the boundary and the net pattern of the triple-direction starts to shift.","At about two hours the Life Palace crosses a whole step and all twelve palaces reshuffle, which is effectively another chart.","The Bazi hour pillar also switches every two hours on the same boundary, so the two shift together and cannot be independent evidence."],
 cnStep:['先看出生时间落在哪个时辰格内、离上下边界多远','若时间贴近格线，评估这张盘属于格内还是越界状态','把时间往前后各推半小时，对比命宫与三方是否变化','再推到两小时，确认命宫整格移位的临界点','不要用八字时柱去反向证明紫微时辰，二者同源','对贴近边界的盘，优先用过往大事做定盘来锁定时辰'],
 enStep:["See which two-hour step the birth time falls in and how far it is from each boundary","If the time sits near a boundary, judge whether the chart is inside or crossing","Push the time forward and back half an hour and compare the Life Palace and triple-direction","Push it to two hours to find the whole-step crossing point","Do not use the Bazi hour pillar to prove the Zi Wei hour, since they share a source","For boundary-near charts, lock the hour using past events rather than assumptions"],
 cnMis:['认为差半小时无所谓，命宫纹丝不动','以为八字和紫微是两套独立系统，可互相交叉验证','时间贴近格线却不做定盘，直接在可能越界的盘上断事'],
 enMis:["Assuming half an hour changes nothing in the Life Palace","Treating Bazi and Zi Wei as two independent systems that cross-check each other","Skipping verification on a boundary-near chart and judging anyway"],
 cnClose:'知道命宫在两小时里怎么动，才知道自己这张盘稳不稳。贴线的盘别急着断未来，先用大事把时辰钉死，再谈后面。',
 enClose:"Knowing how the Life Palace moves within a two-hour step tells you whether your chart is stable. For boundary-near charts, pin down the hour with events before reading the future."},

{cat:'faq',slug:'ziwei-chusheng-shichen-buxiang-neng-kan-shenme',focus:'出生时辰不详的读盘边界',focusEn:'reading boundary when birth hour is unknown',
 cnT:'紫微斗数出生时辰不详还能看什么：三层结论不硬填',
 enT:'What You Can Still Read in Zi Wei Dou Shu When the Birth Hour Is Unknown: Three Layers, No Guessing',
 cnD:'八字缺时仍可读三柱大势，紫微却高度依赖时辰，命宫一错全盘皆错。时辰不详时，只把能确定的部分读成稳定结论，暂定的部分写明假设，待核实的部分留空，绝不硬填一个时辰造出完整盘。',
 enD:"Bazi can still read the three pillars without the hour, but Zi Wei leans heavily on it: one wrong Life Palace makes the whole chart wrong. When the hour is unknown, read what is certain as stable, mark tentative parts as assumptions, leave the unverifiable blank, and never force an hour to fabricate a complete chart.",
 cnL:'有人只记得自己「天快黑时」生，就要求排一张完整命盘断财运婚姻。这在紫微里做不到——命宫定不下来，后面十二宫全是悬空的。',
 enL:"Someone who remembers only born around dusk asks for a full chart to judge wealth and marriage. In Zi Wei this cannot be done: with no fixed Life Palace, all twelve palaces hang in the air.",
 cnA:'要分清什么是缺时也能读的，什么是缺时就不能读的。把结论分成稳定、暂定、待核实三层，对读者诚实，比硬凑一张看起来完整的盘有用得多。',
 enA:"Separate what survives a missing hour from what does not. Split conclusions into stable, tentative and to-verify layers; honesty to the reader beats a chart that merely looks complete.",
 cnLog:['紫微的命宫、身宫、十二宫排布都由出生时辰决定，时辰缺失则整张盘的宫位坐标无法立起。','八字年、月、日三柱不依赖时辰，仍可看大方向与部分性格，缺时影响相对小。','紫微可先把出生年月日确定的星曜排布、部分大趋势列为稳定结论，但凡依赖命宫的细断一律降级。','无法用定盘锁定的时辰，宁可标注待核实，也不臆造一个时辰冒充完整盘。'],
 enLog:["The Zi Wei Life Palace, Body Palace and all twelve positions are set by the birth hour, so without it the chart's coordinates cannot stand.","The Bazi year, month and day pillars do not depend on the hour, so broad direction and some personality remain readable.","Date-fixed star arrangements can be marked as stable, but any detailed judgment that relies on the Life Palace must be downgraded.","If chart verification cannot lock the hour, mark it to-verify rather than fabricating a complete chart."],
 cnStep:['先确认已知信息精确到什么程度，是只知年月日还是有大致时段','把不依赖时辰也能成立的部分列为稳定结论','凡依赖命宫与十二宫的细断，统一标注为暂定并写明假设','用过往大事尝试收窄时辰，能收窄到哪个程度算哪个','仍无法锁定的部分明确标注待核实，留空不补','对读者说明这张盘的可靠范围，不给出超出证据的断言'],
 enStep:["Confirm how precise the known data is: year-month-day only, or a rough window","List conclusions that hold without the hour as stable","Downgrade every Life-Palace-dependent detail as tentative and state the assumption","Use past events to narrow the hour as far as they allow","Leave whatever cannot be locked as to-verify rather than filling it","Tell the reader the reliable range of the chart and make no over-evidenced claim"],
 cnMis:['时辰不详还硬排一张完整盘并断细节','把暂定结论说成稳定结论，误导读者','用八字三柱去替代紫微命宫，误以为两者等价'],
 enMis:["Forcing a full chart and judging details when the hour is unknown","Presenting tentative conclusions as stable and misleading the reader","Substituting the Bazi three pillars for the Zi Wei Life Palace as if they were equivalent"],
 cnClose:'缺时不是不能看，而是要老实说出能看到哪一层。稳定的部分放心讲，暂定的部分带条件，待核实的部分留空——这比一张硬凑的完整盘诚实得多。',
 enClose:"A missing hour does not forbid reading; it means saying honestly how far you can see. Speak the stable part plainly, present the tentative part conditionally, and leave the unverifiable blank; this is far more honest than a patched-up complete chart."},

{cat:'kanpan',slug:'ziwei-jiaoshi-yong-naxie-shijian',focus:'校时用哪些事件',focusEn:'which events to use for hour rectification',
 cnT:'紫微斗数校时用什么事件：客观大事才算硬证据',
 enT:'Which Events to Use for Hour Rectification in Zi Wei Dou Shu: Objective Facts Are the Hard Evidence',
 cnD:'校时不靠性格描述，而靠搬家、工作变动、结婚、升学、伤病等有明确年份的客观事件作硬证据；性格谁都能套上两句，事件却有硬日期，多件事件交叉指向同一时辰才作数。',
 enD:"Hour rectification does not rely on personality descriptions but on objective, dated events such as moves, job changes, marriage, schooling and illness. Personality can be fitted to anyone, but events carry hard dates, and only when several point to the same hour does it count.",
 cnL:'有人说「我性格很像白羊座，所以应该是卯时」——这在校时里几乎不算证据。性格是软的，怎么解释都行；真正能定时辰的，是那些你记得清清楚楚发生在哪一年的事。',
 enL:"Someone says I act like an Aries, so it must be the Mao hour. That is hardly evidence for rectification. Personality is soft and explainable any way; what locks the hour are events you clearly remember by the year they happened.",
 cnA:'校时的逻辑是反推：先假设几个候选时辰，分别排盘，再看哪一个盘上的大限流年，能把你已知年份的大事一件一件对出来。能对上越多，那个时辰越真。',
 enA:"Rectification works by reverse inference: cast a few candidate hours, then see which chart's decade and yearly limits match the dated events you already know. The more events it matches, the more likely that hour is real.",
 cnLog:['硬证据指有明确公历年月的客观事件：搬家、换工作、结婚、离婚、升学、毕业、伤病住院、破财置业等。','性格、爱好、口头禅这类软性描述不算证据，因为它们能被任意时辰的盘解释。','每个候选时辰排盘后，用其大限与流年去碰这些事件的年份，看触发是否合理。','单一事件能被多个时辰凑上，必须多件事件交叉、一致指向同一时辰，校时才算成立。'],
 enLog:["Hard evidence means objective events with a clear year and month: moving, changing jobs, marrying, divorcing, schooling, graduating, illness and hospitalization, or buying property.","Soft traits such as personality, hobbies or catchphrases are not evidence, since any hour's chart can explain them.","Cast each candidate hour and test its decade and yearly limits against the years of these events for plausible triggers.","A single event fits several hours; only when several events cross and point to one hour does rectification hold."],
 cnStep:['先列出本人能确定公历年月的过往大事，越具体越好','筛掉只有模糊印象、记不清年份的事','为两三个候选时辰各排一张盘','逐盘用大限流年去碰每件大事的年份，记录匹配度','比较各盘匹配事件的数量与力度，取最优那个','多盘打平时再补充新的客观事件继续收窄'],
 enStep:["List past events whose year and month the person can pin down, as specifically as possible","Drop events remembered only vaguely without a year","Cast a chart for each of two or three candidate hours","For each chart, test the decade and yearly limits against each event's year and score the match","Compare the number and strength of matches across charts and take the best one","If charts tie, add new objective events to narrow further"],
 cnMis:['拿性格描述、长相、口头禅当校时证据','只用一件大事就拍板定时辰','把记不清年份的模糊事件硬塞进校验'],
 enMis:["Using personality, looks or catchphrases as rectification evidence","Fixing the hour from a single major event","Forcing vaguely-dated events into the check"],
 cnClose:'校时的硬通货是带年份的客观事件，不是好听的性格评语。把几件真事摆在盘上碰一碰，时辰自己会浮出来。',
 enClose:"The hard currency of rectification is dated objective events, not flattering personality notes. Lay a few real events against the chart and the hour surfaces on its own."},

{cat:'kanpan',slug:'ziwei-daxian-liunian-yingqi-zenme-kan',focus:'大限打底流年触发看应期',focusEn:'decade baseline and yearly trigger for timing',
 cnT:'紫微斗数大限打底、流年触发：应期到底怎么看',
 enT:'Reading Timing in Zi Wei Dou Shu: The Decade Sets the Baseline, the Year Triggers It',
 cnD:'大限定住十年的主题与承接力，流年定住当年的触发点；应期不是凭空冒出来的吉凶，而是大限这道课题在某一年被流年引动的那一刻。两层叠看，才知道事为什么偏偏发生在这一年。',
 enD:"The decade limit sets the ten-year theme and capacity, while the yearly limit sets that year's trigger. Timing is not luck appearing from nowhere; it is the decade's topic activated in a given year. Read the two layers together to see why an event happened in that specific year.",
 cnL:'有人问「我明明这步大限很好，为什么偏在某一年摔了一跤」。答案往往是：大限给了你这十年的底子，但具体哪一下被点着，要看那一年的流年引动了哪个宫。',
 enL:"Someone asks why they fell in a particular year despite a good decade. The answer is that the decade sets the ten-year base, but which moment gets lit depends on that year's limit activating a certain palace.",
 cnA:'要把时间盘分成两层：大限是河床，决定这十年水流往哪、水量多大；流年是雨，决定哪一年水涨起来。应期就是河床方向与当年那场雨对上的时刻。',
 enA:"Split the timing chart in two: the decade is the riverbed, setting the direction and volume for ten years, while the year is the rain, deciding which year the water rises. Timing is when the riverbed and that year's rain line up.",
 cnLog:['大限管约十年，定这十年的人生主题、资源承接力与整体基调，是长期底色。','流年管一年，把当年的宫位、四化叠加到大限之上，是短期触发。','应期=大限课题被流年引动的时刻：大限没有这个主题，流年再凶也无的放矢。','判断时先看大限这十年在哪个领域打底，再看流年引动了哪一宫，两者方向一致才是真应期。'],
 enLog:["The decade spans about ten years and sets the life theme, capacity and overall tone for that stretch, a long-term baseline.","The year spans one year and layers that year's palaces and transformations over the decade, a short-term trigger.","Timing is the moment the decade's topic is activated by the year: without the decade theme, even a harsh year has nothing to act on.","Read which area the decade lays as its base, then see which palace the year activates; only when both align is it a true timing."],
 cnStep:['先确定当前走在哪一步大限、这十年的主题宫是哪一宫','读大限的星曜与四化，记下这十年在哪个领域打底','再确定要问的是哪一年的流年','叠看流年宫位与四化，找它引动了大限的哪一宫','判断大限课题与流年触发是否同向、同领域','同向才断为应期，给出条件式解读而非绝对断言'],
 enStep:["Identify the active decade and its theme palace for the ten years","Read the decade's stars and transformations and note which area it lays","Pinpoint the specific year in question","Layer the year's palaces and transformations to see which decade palace it activates","Judge whether the decade topic and the year trigger align in direction and area","Only when aligned call it a timing, and read conditionally rather than absolutely"],
 cnMis:['只看流年吉凶，忽略大限这十年的承接底子','只看大限很好就断定年年都顺，不看当年触发','把应期当成凭空降临的运气，不问大限课题是否在场'],
 enMis:["Reading only the yearly fortune while ignoring the decade's baseline","Declaring every year smooth because the decade is good, ignoring the yearly trigger","Treating timing as luck from nowhere without asking whether the decade topic exists"],
 cnClose:'大限是底色，流年是笔触。十年的主题摆在那里，哪一年被流年点到，事才应在那一年——两层都看，应期才不空。',
 enClose:"The decade is the base color and the year the brushstroke. The ten-year theme is set there, and only when a year touches it does an event land in that year; read both layers and timing is not hollow."},

{cat:'sihua',slug:'ziwei-sihua-feixing-luquankeji-jiben',focus:'四化飞星禄权科忌基础',focusEn:'four transformations basics: Lu Quan Ke Ji',
 cnT:'紫微斗数四化飞星：禄权科忌到底各在说什么',
 enT:'The Four Transformations in Zi Wei Dou Shu: What Lu, Quan, Ke and Ji Actually Say',
 cnD:'化禄给资源与机会，化权给主动权与压力，化科给名声与缓冲，化忌给牵挂与课题；四化描述的是能量往哪里流，不是简单的吉凶好坏，要合起来看流向。',
 enD:"Hua Lu gives resources and opportunity, Hua Quan gives initiative and pressure, Hua Ke gives reputation and cushion, and Hua Ji gives attachment and a lesson. The four transformations describe where energy flows, not simple good or bad luck; read them together as a current.",
 cnL:'很多人一听化禄就笑、一见化忌就怕，把四化当成四张吉凶牌。其实它们更像四种力：有的帮你开源，有的逼你行动，有的给你面子，有的让你放不下。',
 enL:"Many smile at Hua Lu and fear Hua Ji, treating the four as four fortune cards. They are better read as four forces: some open resources, some push you to act, some give you face, and some keep you attached.",
 cnA:'四化要回答的是能量流向：这张盘的资源从哪个宫进来、主动权在谁手里、名声落在哪、又是什么事让人反复牵挂。把四股力连成线，才看得出一件事的走势。',
 enA:"The four transformations answer where energy flows: from which palace resources enter, who holds the initiative, where reputation lands, and what keeps one attached. Connecting the four forces into a line reveals how a matter moves.",
 cnLog:['化禄代表资源、机会与顺遂，落在哪个宫，哪个领域就容易有活水进来。','化权代表主动权、掌控力与压力，落在哪个宫，哪个领域就争强、要扛事。','化科代表名声、文书与缓冲，落在哪个宫，哪个领域易有体面与回旋余地。','化忌代表牵挂、阻滞与课题，落在哪个宫，哪个领域反复操心、需要面对；2026丙午年为天同化禄、天机化权、文昌化科、廉贞化忌，可作当年流年四化的参照。'],
 enLog:["Hua Lu stands for resources, opportunity and ease; where it lands, that area tends to receive a flow of fresh supply.","Hua Quan stands for initiative, control and pressure; where it lands, that area is driven and must carry weight.","Hua Ke stands for reputation, paperwork and cushion; where it lands, that area tends to have face and room to maneuver.","Hua Ji stands for attachment, blockage and a lesson; where it lands, that area recurs as a worry to face. In the 2026 Bing-Wu year the yearly transformations are Tian Tong Lu, Tian Ji Quan, Wen Chang Ke and Lian Zhen Ji, useful as a reference."],
 cnStep:['先按出生年干标出生年四化及各自落宫','再分清禄、权、科、忌四股力分别落在哪些宫','看禄从哪宫来、忌往哪宫去，理清资源进出','看权落在哪宫，判断主动权与压力在谁手里','看科落在哪宫，找名声与缓冲的位置','把四股力连成流向，判断这件事顺滞，而不是单看某一颗'],
 enStep:["Mark the natal transformations by the birth year stem and their palaces","Separate the four forces Lu, Quan, Ke and Ji by where each lands","Trace where Lu comes from and where Ji goes to, clarifying resource in and out","See which palace Quan lands in to judge who holds initiative and pressure","See which palace Ke lands in to locate reputation and cushion","Connect the four forces into a current and judge smooth or stuck rather than reading one star alone"],
 cnMis:['见禄就断好、见忌就断坏，不分流向','把四化当成独立事件，不看飞进飞出的宫位','只记生年四化，不叠加大限流年的临时四化'],
 enMis:["Declaring good at Lu and bad at Ji without the flow","Treating transformations as isolated events apart from the palaces they fly into and out of","Keeping only natal transformations and ignoring temporary decade and yearly ones"],
 cnClose:'四化是四股流，不是四张吉凶牌。看清资源往哪流、牵挂在哪停，盘的走势就从一堆星曜变成一条能读的河。',
 enClose:"The four transformations are four currents, not four fortune cards. Once you see where resources flow and where attachment stops, the chart turns from a pile of stars into a readable river."},

{cat:'kanpan',slug:'ziwei-jiepan-zenme-yong',focus:'借盘的用法',focusEn:'how to use borrowed palaces',
 cnT:'紫微斗数借盘怎么用：把夫妻宫当新命宫重排十二宫',
 enT:'How to Use Borrowed Palaces in Zi Wei Dou Shu: Treat the Spouse Palace as a New Life Palace and Rebuild the Twelve',
 cnD:'看配偶事业时，把夫妻宫当成新命宫重新排布十二宫；夫妻宫的官禄位其实就是本命财帛宫。借盘是换一个视角看同一张盘，不是另起一条命。',
 enD:"When reading a spouse's career, treat the Spouse Palace as a new Life Palace and rebuild the twelve positions; the spouse's career palace then corresponds to your native Wealth Palace. Borrowing palaces is shifting perspective on one chart, not starting a separate life.",
 cnL:'想问「我配偶事业做得怎么样」，却盯着自己的官禄宫看，方向就错了。正确做法是借盘：把夫妻宫立成新的起点，十二宫围着它重排。',
 enL:"Wondering about a spouse's career while staring at your own career palace points the wrong way. The right move is to borrow palaces: set the Spouse Palace as the new origin and rebuild the twelve around it.",
 cnA:'借盘解决的是视角问题：同一张盘，换一个宫当命宫，原本属于你的十二宫关系，就变成了属于配偶的十二宫关系。它没有造出第二个命，只是换了主语。',
 enA:"Borrowed palaces solve a perspective problem: with one palace as the new Life Palace, the same twelve relationships that were yours become your spouse's. It does not create a second life; it changes the subject.",
 cnLog:['借盘的核心是平移：以某宫为新命宫，按原十二宫的相对关系重新命名十二宫。','看配偶事业时，以夫妻宫为新命宫，其「官禄宫」对应本命盘的财帛宫。','看配偶财运、配偶家庭等，同理以夫妻宫为原点重排，再读那条线。','借盘得出的是对方在你这张盘里的投影，仍受原盘格局约束，不是另立一张命。'],
 enLog:["The core of borrowing is a shift: take one palace as the new Life Palace and rename the twelve by their original relative positions.","For a spouse's career, with the Spouse Palace as the new Life, its career palace maps to your native Wealth Palace.","A spouse's wealth or family is read the same way, rebuilding from the Spouse Palace and then reading that line.","A borrowed result is the spouse's projection within your chart, still bound by the original pattern, not a separate life."],
 cnStep:['先明确要问的是配偶、子女还是父母哪一方的事','选定对应的宫位作为新的命宫原点','按原十二宫相对位置，把新十二宫逐一改名','找到新原点下对应的目标宫位，如配偶事业对应新官禄','读这条新线上的星曜、辅煞与四化','始终记住这是借视角看同一盘，不把它当成对方独立的命'],
 enStep:["First clarify whether the question concerns a spouse, child or parent","Pick the corresponding palace as the new Life origin","Rename the twelve by their original relative positions from that origin","Locate the target palace under the new origin, such as spouse career as the new career","Read the new line's stars, assistants, malefics and transformations","Always remember this is a borrowed view of one chart, not the other person's independent fate"],
 cnMis:['问配偶的事却直接读自己的官禄或财帛宫','借盘后把它当成配偶独立的命来下断','只换了命宫原点，却不重排其余十一宫'],
 enMis:["Reading your own career or Wealth palace when asking about a spouse","Treating the borrowed chart as the spouse's independent fate after shifting","Changing only the Life origin without rebuilding the other eleven palaces"],
 cnClose:'借盘是换个主语看同一张盘。原点一移，十二宫的关系就换成了对方的故事，但底子还是你这张盘——视角对了，配偶那条线才读得准。',
 enClose:"Borrowing palaces changes the subject on one chart. Shift the origin and the twelve relationships become the spouse's story, yet the base remains your chart; with the right angle, the spouse's line reads accurately."},

{cat:'faq',slug:'ziwei-jiankang-bianjie-feizhenduan',focus:'紫微看健康的边界',focusEn:'boundary of health reading in Zi Wei',
 cnT:'紫微斗数看健康的边界：体质倾向，不是医学诊断',
 enT:'The Boundary of Health Reading in Zi Wei Dou Shu: A Tendency, Not a Medical Diagnosis',
 cnD:'疾厄宫与福德宫只能读出体质偏向与情绪压力倾向，用来提前留意、调整作息，不能替代正规医学诊断；持续不适、失眠、惊恐发作或自伤念头，必须及时就医并寻求专业心理支持。',
 enD:"The Health and Karma palaces can only reveal bodily tendencies and emotional-stress patterns, useful for early awareness and routine adjustment; they cannot replace formal medical diagnosis. Persistent discomfort, insomnia, panic episodes or self-harm thoughts require timely medical care and professional psychological support.",
 cnL:'有人一看到疾厄宫坐了某颗煞星，就吓得以为要生大病。其实盘上能说的，是你哪类体质偏虚、哪类情绪容易压着，不是判决书。',
 enL:"Someone sees a malefic in the Health Palace and panics about a serious illness. What the chart can say is which bodily tendency runs weak and which emotion tends to be suppressed; it is not a verdict.",
 cnA:'要把话说在边界上：命理给的是倾向和提醒，医生手里才是诊断和处方。把盘当体检表来用，是用错了工具；把它当作息调整的参考，才物尽其用。',
 enA:"Keep the claim inside its boundary: astrology gives tendencies and reminders, while the doctor holds diagnosis and prescription. Using the chart as a health checkup abuses the tool; using it as a reference for lifestyle adjustment makes it useful.",
 cnLog:['疾厄宫看体质强弱与薄弱环节，福德宫看情绪、压力与精神状态的长期偏向。','这些偏向提示某类问题更容易找上门，属概率与倾向，不等于一定会发生。','盘不能做检查、不能下诊断、不能替代药物与正规治疗。','出现持续不适、长期失眠、反复惊恐或自伤念头时，应立即寻求正规医疗与心理支持，不拿盘上的说法自我安慰。'],
 enLog:["The Health Palace shows bodily strengths and weak links, while the Karma Palace shows long-term emotional and stress tendencies.","These tendencies suggest which problems are more likely, as probability and inclination, not certainty.","The chart cannot run tests, make diagnoses, or replace medication and formal treatment.","Persistent discomfort, long insomnia, recurring panic or self-harm thoughts require immediate medical and psychological support rather than chart-based reassurance."],
 cnStep:['先明确疾厄宫与福德宫分别在说体质和情绪两件事','读出体质偏向，如偏弱的系统或易紧张的情绪模式','把这些翻译成生活作息建议，如作息、运动、减压','明确标注这是倾向提醒，不是诊断','若出现持续或加重的不适，优先建议正规就医','把心理与情绪问题单独提示寻求专业心理支持'],
 enStep:["First clarify that the Health Palace and Karma Palace speak of body and emotion separately","Read the bodily tendency, such as a weak system or a tense emotional pattern","Translate these into lifestyle advice on rest, exercise and stress relief","Mark clearly that this is a tendency reminder, not a diagnosis","If discomfort persists or worsens, prioritize formal medical care","Flag emotional and psychological issues as needing professional support"],
 cnMis:['把疾厄宫某颗煞星当成一定会生大病的判决','用盘上的说法拒绝或拖延正规就医','把情绪问题当作性格缺陷，不寻求心理支持'],
 enMis:["Taking a malefic in the Health Palace as a verdict of certain illness","Using chart talk to refuse or delay proper medical care","Treating emotional problems as a character flaw and skipping psychological support"],
 cnClose:'盘上的健康信息是一盏提醒灯，不是体检报告。它提示你留意身体与情绪的偏向，真出了问题，正规医疗和心理支持才是答案。',
 enClose:"Health information in the chart is a reminder light, not a checkup report. It nudges you to watch bodily and emotional tendencies; when real trouble comes, proper medical and psychological care are the answer."}
];
