// 2026-09-27 调研驱动 第5组：应用场景/感情/六亲 8篇
module.exports=[
{cat:'yingyong',slug:'ziwei-qianyigong-yidi-fazhan',focus:'迁移宫看异地发展',focusEn:'Migration Palace and relocation development',
 cnT:'紫微斗数迁移宫看异地发展：舞台好看，也要看命官禄财田',
 enT:'Reading Relocation Through the Migration Palace in Zi Wei Dou Shu: A Good Stage, but Read the Whole Chart',
 cnD:'迁移宫是离开熟悉环境后的外部场域，它好看说明在外的舞台与贵人缘顺；但强迁移不等于必须离乡，要连看命宫、官禄、财帛、福德、田宅与时间结构，法律、财务、家庭、健康才是能否落地的必要条件，文昌文曲只是语言与文件线索。',
 enD:'The Migration Palace is the external field after leaving familiar ground; a fine Migration Palace means smoother stage and benefactors away from home. But strong Migration does not mean you must leave. Read Life, Career, Wealth, Karma and Property together with timing; law, finance, family and health are the necessary conditions, while Wenchang and Wenqu are only clues about language and paperwork.',
 cnL:'很多人一看到迁移宫亮就铁了心要外出，结果舞台是有了，岗位不对、钱不够、家里又放不下。迁移宫只告诉你外面顺不顺，不替你决定走不走。',
 enL:'Many see a bright Migration Palace and rush to leave; the stage is there, but the role is wrong, money is short and family cannot be left behind. Migration only tells how smoothly things go away, not whether you should go.',
 cnA:'可操作的做法：迁移宫作倾向参考，再逐项核对官禄岗位、财帛薪资税务、田宅居住与家庭、福德情绪适应，以及必要的法律合同、签证、保险与健康安排，重大决定以实际机会和书面约定为准。',
 enA:'The practical approach: take Migration as a tendency, then check Career role, Wealth and tax, Property and family, and Karma adaptation one by one, along with contract, visa, insurance and health arrangements; base major decisions on real opportunities and written terms.',
 cnLog:['迁移宫看外部场域：在外顺逆、贵人缘、异地适应。','强迁移只是舞台倾向，不等于必须离乡发展。','命官禄财田福德连看，才知道岗位、收入、居住与内心是否接得住。','法律、财务、家庭、健康是落地的必要条件，文昌文曲仅为语言文件线索。'],
 enLog:['The Migration Palace shows the external field: how things go away, benefactors and adaptation.','Strong Migration is only a stage tendency, not a command to leave home.','Read Life, Career, Wealth, Property and Karma together to see whether role, income, shelter and inner self can hold.','Law, finance, family and health are the necessary conditions; Wenchang and Wenqu are only language and paperwork clues.'],
 cnStep:['先看迁移宫主星与四化，判断外部舞台顺不顺','再看官禄宫，评估异地岗位与发展空间','看财帛宫，算薪资税负与生活成本','看田宅与福德，评估居住根基与情绪适应','核对法律、签证、合同、保险与健康安排','综合全部条件，再决定是否成行与何时去'],
 enStep:['Read Migration stars and transformations to judge how the external stage runs','Read Career to assess the role and growth away','Read Wealth to calculate salary, tax and living cost','Read Property and Karma to assess shelter and emotional adaptation','Check law, visa, contract, insurance and health arrangements','Synthesize all conditions before deciding whether and when to go'],
 cnMis:['只看迁移宫亮就断定必须离乡','忽略岗位、薪资、居住与家庭等落地条件','把文昌文曲当成外出发展的决定性依据'],
 enMis:['Judging that you must leave home just because Migration is bright','Ignoring landing conditions like role, salary, shelter and family','Treating Wenchang and Wenqu as decisive factors for relocation'],
 cnClose:'迁移宫是一扇朝外的窗，不是一道必须出门的命令。窗外风景好，也要先看清屋里的人、手里的活、口袋的钱和自己的身体，再决定背不背包。',
 enClose:'The Migration Palace is a window outward, not an order to leave. If the view is fine, first see the people at home, the work in hand, the money in pocket and your own body before you pack.'},

{cat:'gongwei',slug:'ziwei-shengong-zai-qianyigong',focus:'身宫在迁移宫',focusEn:'Body Palace in the Migration Palace',
 cnT:'身宫落迁移宫：成长来自变化，也要防过度流动',
 enT:'Body Palace in the Migration Palace: Growth Through Change, Guarding Against Excess Motion',
 cnD:'身宫落迁移者，成长多来自环境变化与人际网络，朋友、平台、差旅和异地经历会成为资源；适度移动让人活跃，但要防过度流动导致作息紊乱、专业无法沉淀，建议带着产出目标做异地计划，动静交替。',
 enD:'When the Body Palace sits in Migration, growth comes from environmental change and networks; friends, platforms, travel and outside experience become resources. Moderate movement keeps you active, but watch that excess motion does not disrupt routine or let expertise fail to settle; plan relocation with deliverables and alternate movement with stillness.',
 cnL:'有人待在一个地方就蔫，一换环境、一见新人就来劲——身宫迁移的人，生命力是被外部世界点燃的，但飘太久也会忘了自己要扎哪。',
 enL:'Some wilt staying put and light up with new environments and people; for Body-in-Migration people vitality is ignited by the outside world, but drifting too long makes them forget where to root.',
 cnA:'建议是给流动装上方向盘：每次异地、差旅、换平台都带一个明确的产出目标——一段作品、一个客户、一项技能，回来能沉淀成履历；同时固定作息、留出安静期，避免一直在路上却没有积累。',
 enA:'Give motion a steering wheel: each relocation, trip or platform change carries a clear deliverable—a piece of work, a client, a skill—that settles into your record; keep a fixed routine and quiet periods so you are always on the road without accumulating.',
 cnLog:['身宫迁移者成长来自环境变化与人际网络。','朋友、平台、差旅、异地经历是重要资源。','适度移动让人活跃，过度流动则作息紊乱、专业难沉淀。','带产出目标做异地计划，动静交替，避免只飘不扎。'],
 enLog:['Body-in-Migration people grow through environmental change and networks.','Friends, platforms, travel and outside experience are key resources.','Moderate movement energizes, while excess disrupts routine and stalls expertise.','Plan relocation with deliverables and alternate motion with stillness to avoid drifting without rooting.'],
 cnStep:['先确认身宫是否落在迁移宫','梳理过去哪些成长来自换环境与遇新人','为下一段异地或差旅设定明确产出目标','固定作息与安静期，对抗流动紊乱','把异地经历沉淀成可展示的作品与履历','动静交替，定期回到稳定节奏'],
 enStep:['Confirm whether the Body Palace sits in Migration','Review which past growth came from change and new people','Set a clear deliverable for the next relocation or trip','Keep a routine and quiet periods against motion chaos','Turn outside experience into showable work and records','Alternate motion and stillness, returning to a steady rhythm'],
 cnMis:['把身宫迁移当成只能不停漂泊','只顾移动换刺激，不留产出与沉淀','作息随流动彻底打乱，专业长期悬空'],
 enMis:['Reading Body-in-Migration as an obligation to drift endlessly','Only chasing stimulation without deliverables and settling','Letting routine collapse under motion while expertise stays unfinished'],
 cnClose:'身宫在迁移的人，世界是你的训练场，但不是永远的旅馆。走出去见天地、见众生，也要定期回来，把见识酿成自己的本事。',
 enClose:'For those with Body in Migration, the world is your training ground but not a permanent hotel. Go out to see the world and people, then return regularly to distill what you see into your own craft.'},

{cat:'gongwei',slug:'ziwei-fudegong-shengong-shuimian',focus:'福德宫身宫与情绪睡眠',focusEn:'Karma Palace and Body Palace: emotion and sleep',
 cnT:'福德宫与身宫重合：对情绪和睡眠更敏感的人',
 enT:'Karma Palace Meeting the Body Palace: People More Sensitive to Emotion and Sleep',
 cnD:'福德与身宫重合者，对失落、旧事回放、深夜情绪较敏感，容易睡眠不稳、情绪疲惫、陪伴需求强；这是情绪与关系的象意，不作诊断。若持续失眠、焦虑或情绪低落，应寻求正规专业支持，不能只靠读盘解释。',
 enD:'When Karma and the Body Palace meet, people are more sensitive to loss, replaying the past and late-night emotions, tending to unsteady sleep, emotional fatigue and a strong need for companionship; this is imagery of emotion and relating, not a diagnosis. With persistent insomnia, anxiety or low mood, seek proper professional support rather than explaining it all by the chart.',
 cnL:'有些人一到深夜就放不下白天的委屈，醒来又觉得没睡透，身边需要有人陪着才安心——这种体质，盘上常写在福德与身宫同宫的位置。',
 enL:'Some cannot let go of daytime grievances at night and wake unrefreshed, feeling safe only with company; this tendency is often written where Karma and the Body Palace share a palace.',
 cnA:'可操作的方向：承认自己对情绪和睡眠更敏感，主动减少深夜独处和信息过载，固定睡前节奏、多一点陪伴和运动；若长期失眠、焦虑影响生活，请及时找正规医院和专业心理支持，倾向非诊断、以正规就医为准。',
 enA:'The practical direction: acknowledge your sensitivity to emotion and sleep, reduce late-night isolation and information overload, keep a bedtime rhythm, more company and exercise; if long insomnia or anxiety affects life, seek proper medical and mental support—this is tendency, not diagnosis, and proper care prevails.',
 cnLog:['福德与身宫重合者对失落、旧事、深夜情绪较敏感。','常见睡眠不稳、情绪疲惫、陪伴需求强。','这是情绪与关系象意，不作医学诊断。','持续失眠焦虑应寻求正规专业支持。'],
 enLog:['When Karma meets the Body Palace, people are more sensitive to loss, the past and late-night emotion.','Common signs are unsteady sleep, emotional fatigue and a strong need for company.','This is imagery of emotion and relating, not a medical diagnosis.','Persistent insomnia or anxiety calls for proper professional support.'],
 cnStep:['先确认福德宫与身宫是否同宫','观察自己是否易在深夜回放旧事','固定睡前节奏，减少深夜信息过载','主动安排陪伴与规律运动','记录睡眠与情绪变化，识别持续信号','长期不缓解时及时正规就医与心理支持'],
 enStep:['Confirm whether Karma and the Body Palace share a palace','Notice whether you replay the past late at night','Keep a bedtime rhythm and cut late-night information overload','Arrange company and regular exercise','Track sleep and mood to spot persistent signs','Seek proper medical and mental support if it does not ease'],
 cnMis:['把情绪睡眠问题全归因于命盘，拖延就医','因为敏感就否定自己，不主动调节作息','忽视持续失眠焦虑的预警信号'],
 enMis:['Attributing all mood and sleep issues to the chart and delaying care','Denying yourself for being sensitive without adjusting routine','Ignoring warning signs of persistent insomnia and anxiety'],
 cnClose:'福德身宫重合的人，心比别人多一层细腻，也多一分消耗。善待这份敏感，把作息和陪伴安排好，真扛不住时记得找医生——读盘是照见自己，不是代替治疗。',
 enClose:'Those with Karma meeting the Body Palace carry a finer heart and a heavier drain. Be kind to this sensitivity, arrange routine and company well, and when it is too much see a doctor—the chart reveals you, it does not replace treatment.'},

{cat:'gongwei',slug:'ziwei-fudegong-neizai-anding',focus:'福德宫内在状态与快乐来源',focusEn:'Karma Palace: inner state and source of happiness',
 cnT:'紫微斗数福德宫：你心里踏不踏实，快乐从哪来',
 enT:'The Karma Palace in Zi Wei Dou Shu: Whether You Feel Grounded and Where Joy Comes From',
 cnD:'福德宫是与自己相处、消化压力、培养兴趣、决定睡眠与情绪稳定度的内在系统；它联动命身、夫妻、官禄、田宅，要把心里踏实这件事，放进自我状态、关系、工作压力和居住根基一起看，而不是孤立判好坏。',
 enD:'The Karma Palace is the inner system for being with yourself, digesting stress, nurturing interests, and shaping sleep and emotional stability; it links Life, Body, Spouse, Career and Property, so inner peace must be read together with self-state, relationships, work pressure and living foundation rather than judged in isolation.',
 cnL:'有人外人看着风光，自己却总不快乐；有人日子普通，心里却很踏实——这种差别，往往不在财帛官禄，而在福德宫这个内在系统。',
 enL:'Some look successful yet feel unhappy; others live plainly yet feel grounded; the difference often lies not in Wealth or Career but in this inner system, the Karma Palace.',
 cnA:'读法是顺藤摸瓜：先看福德宫主星，知道你靠什么解压、什么让你安心；再看它受不受命身、夫妻、官禄、田宅的牵动，判断压力、关系和居住哪一头在消耗你，再从那里入手调整。',
 enA:'Read along the vine: first read the Karma star to know how you unwind and what grounds you; then see whether Life, Body, Spouse, Career or Property disturb it, judging which of pressure, relationships or living is draining you, and start adjusting there.',
 cnLog:['福德宫主内在状态、压力消化、兴趣与睡眠情绪。','它不是孤立宫，联动命身夫妻官禄田宅。','心里踏实与否，要放进关系、工作与居住一起看。','把福德读成「如何安顿自己」的线索，而非吉凶标签。'],
 enLog:['The Karma Palace governs inner state, stress digestion, interests, sleep and mood.','It is not isolated, linking Life, Body, Spouse, Career and Property.','Inner peace must be read together with relationships, work and living.','Read Karma as clues on how to settle yourself, not a fortune label.'],
 cnStep:['先看福德宫主星，了解解压与快乐来源','看福德与命身的关系，辨自我状态','看与夫妻宫的牵动，辨关系是否消耗','看与官禄的牵动，辨工作压力大小','看与田宅的牵动，辨居住根基是否安稳','从最消耗的那一头入手调整生活'],
 enStep:['Read the Karma star to know how you unwind and find joy','See its link to Life and Body for self-state','See its link to Spouse for relationship drain','See its link to Career for work pressure','See its link to Property for living foundation','Start adjusting life from the most draining side'],
 cnMis:['把福德宫单独判好坏，忽略联动宫位','只看外在成就，不问内心踏不踏实','见福德弱就灰心，不主动调整兴趣与作息'],
 enMis:['Judging Karma in isolation and ignoring linked palaces','Watching external achievements without asking inner peace','Desponding at a weak Karma and not adjusting interests and routine'],
 cnClose:'外在的宫位决定你能拿到什么，福德宫决定你装不装得下。把心里踏实当成一件可以经营的事，安顿好关系、工作和住处，快乐才留得住。',
 enClose:'Outer palaces decide what you can get, and Karma decides whether you can hold it. Treat inner peace as something to nurture; settle relationships, work and home, and joy can stay.'},

{cat:'ganqing',slug:'ziwei-2026-ganqing-lianzhenhuaji',focus:'2026感情运廉贞化忌',focusEn:'2026 relationship fortune and Lian-Zhen Hua Ji',
 cnT:'2026丙午年感情运：廉贞化忌落在夫妻宫怎么读',
 enT:'2026 Bing-Wu Relationship Fortune: How to Read Lianzhen Ji in the Spouse Palace',
 cnD:'看流年感情要叠三层变量：本命夫妻宫、大限夫妻宫，再到丙午年四化。2026廉贞化忌落夫妻、命、福德、迁移，多表纠结、旧情反复与关系磨合；巨门坐夫妻逢火旺年份易口舌，但同一颗忌在不同大限底盘上，可能只是争吵，不等于分手。',
 enD:'Read yearly relationships through three layers: the natal Spouse Palace, the decade Spouse Palace, then the Bing-Wu transformations. In 2026, Lianzhen Ji landing in Spouse, Life, Karma or Migration often signals tangles, returning old feelings and relational grinding; Ju-Men in Spouse during a fire-heavy year tends to bicker, but the same Ji under different decade foundations may mean quarrels, not breakups.',
 cnL:'每年到了廉贞化忌，总有人拿着盘来问「今年是不是要分」。其实忌落到夫妻宫更多是关系要补课、旧账要翻一翻，不一定是结局宣判。',
 enL:'Each time Lianzhen Ji arrives, someone asks whether the year means a breakup. In fact Ji in the Spouse Palace more often means the relationship has homework and old accounts to revisit, not a verdict on the ending.',
 cnA:'读法是分层定位：先看本命夫妻宫的底色，再看这步大限夫妻宫走到什么阶段，最后叠丙午年廉贞化忌落在哪、引动了哪一宫。巨门坐夫妻则重点放在沟通方式上，把话说开比争输赢重要。',
 enA:'Read in layers: first the natal Spouse baseline, then what stage the decade Spouse has reached, then where 2026 Lianzhen Ji lands and which palace it touches; with Ju-Men in Spouse, focus on communication—talking it through matters more than winning.',
 cnLog:['流年感情要叠本命、大限、流年三层夫妻宫变量。','2026丙午年四化：天同化禄、天机化权、文昌化科、廉贞化忌。','廉贞化忌落夫妻命福德迁移，主纠结、旧情反复与磨合。','巨门坐夫妻逢火旺年份易口舌，忌在不同底盘上可能只是争吵。'],
 enLog:['Yearly relationships layer the natal, decade and year Spouse Palaces.','2026 Bing-Wu transformations: Tian-Tong Lu, Tian-Ji Quan, Wen-Chang Ke, Lian-Zhen Ji.','Lianzhen Ji in Spouse, Life, Karma or Migration signals tangles, old feelings returning and grinding.','Ju-Men in Spouse bickers in a fire-heavy year; under different foundations the same Ji may mean quarrels, not splits.'],
 cnStep:['先排本命夫妻宫，了解关系底色','再看这步大限夫妻宫，定位关系阶段','叠丙午年四化，找廉贞化忌落在哪宫','看它引动命、福德、迁移还是夫妻','巨门坐夫妻则重点改善沟通方式','把忌当磨合信号，而非分手判决'],
 enStep:['Layout the natal Spouse Palace for the baseline','Read the decade Spouse Palace to locate the relationship stage','Layer Bing-Wu transformations and find where Lianzhen Ji lands','See whether it touches Life, Karma, Migration or Spouse','With Ju-Men in Spouse, focus on improving communication','Treat Ji as a signal to work through, not a breakup verdict'],
 cnMis:['见廉贞化忌落夫妻就断言必分手','只看流年，不叠本命与大限底盘','巨门逢火旺只吵不沟通，把摩擦升级'],
 enMis:['Declaring a definite breakup at Lianzhen Ji in Spouse','Reading only the year without natal and decade foundations','Letting Ju-Men bicker escalate instead of communicating'],
 cnClose:'2026这一年，感情里的廉贞化忌更像提醒你们把没说清的话说开、把没了结的事了掉。忌是来补课的，不是来宣判的——功课做完，关系往往更稳。',
 enClose:'In 2026, Lianzhen Ji in love more like a reminder to say what was left unsaid and settle what was unfinished. Ji comes to assign homework, not to pronounce sentence; when the work is done, the relationship often grows steadier.'},

{cat:'liuqin',slug:'ziwei-zinvgong-jiaoyu-qinzi',focus:'子女宫看教育亲子',focusEn:'Children Palace and education, parent-child',
 cnT:'紫微斗数子女宫看教育：亲子关系与切入点',
 enT:'Reading Education Through the Children Palace in Zi Wei Dou Shu: Parent-Child Bonds and Entry Points',
 cnD:'子女宫看亲子关系与教育切入点，但不能单独决定孩子能力；要同时看父母与孩子两张盘，再结合命宫、福德、文昌文曲与大限流年。文昌化忌不等于没救，可能只是提示文字记忆压力，孩子反而有实作与创意优势。',
 enD:'The Children Palace shows parent-child bonds and educational entry points, but cannot alone decide a child ability; read both the parents and the child charts together, then combine Life, Karma, Wenchang-Wenqu and decades and years. Wenchang Ji does not mean hopeless—it may signal pressure on rote text memory while the child has hands-on and creative strengths.',
 cnL:'很多家长一看到子女宫文昌化忌就慌了，担心孩子不是读书的料。其实这宫更该先看的是「跟孩子怎么处」，而不是急着给孩子的能力下结论。',
 enL:'Many parents panic at Wenchang Ji in the Children Palace, fearing their child cannot study. In fact this palace should first be read for how to relate to the child, not for rushing to judge the child ability.',
 cnA:'做法是对照着看：父母盘的命宫福德，看家长自己的情绪和期待；孩子盘的子女相关与命宫，看他的天性和学习节奏。文昌化忌时别硬逼刷题，多给实作、表达和动手的路径，找到他愿意投入的切口。',
 enA:'Read side by side: the parents Life and Karma show their own emotions and expectations; the child Children and Life show his nature and learning rhythm. With Wenchang Ji, do not force rote drills; offer hands-on, expressive and practical paths and find the entry he is willing to invest in.',
 cnLog:['子女宫看亲子关系与教育切入点，不单独决定孩子能力。','父母盘与孩子盘要对照看。','结合命宫、福德、文昌文曲与大限流年综合判断。','文昌化忌提示文字记忆压力，不等于没救，或有实作创意优势。'],
 enLog:['The Children Palace shows parent-child bonds and entry points, not a child ability alone.','Read the parents chart and the child chart side by side.','Combine Life, Karma, Wenchang-Wenqu with decades and years.','Wenchang Ji signals pressure on text memory, not hopelessness; the child may have hands-on and creative strengths.'],
 cnStep:['先看父母盘命宫福德，觉察自身期待','再看孩子盘子女宫与命宫','看文昌文曲及化忌落在哪宫','叠大限流年，找教育节奏的关键阶段','文昌化忌时减少死记硬背，多给实作路径','亲子沟通优先，再谈成绩与升学'],
 enStep:['Read the parents Life and Karma to notice their expectations','Read the child Children Palace and Life','See where Wenchang, Wenqu and Ji land','Layer decades and years to find key educational stages','With Wenchang Ji, cut rote drilling and offer hands-on paths','Prioritize parent-child communication before grades and schooling'],
 cnMis:['拿子女宫单独给孩子能力下判决','家长把自己的焦虑投射到孩子身上','文昌化忌就否定孩子，放弃实作创意路线'],
 enMis:['Judging a child ability from the Children Palace alone','Projecting parental anxiety onto the child','Writing off the child at Wenchang Ji and dropping hands-on creative routes'],
 cnClose:'子女宫不是给孩子算命的地方，是提醒家长「怎么陪、从哪下手」的地图。先把亲子关系处顺，再顺着孩子的天性找切口，比一张宫位定论有用得多。',
 enClose:'The Children Palace is not a place to predict a child, but a map reminding parents how to accompany and where to start. Smooth the parent-child bond first, then follow the child nature to find entry points; that matters far more than a verdict from one palace.'},

{cat:'ganqing',slug:'ziwei-fuqi-gong-shiye-chuangye',focus:'夫妻宫看共同创业',focusEn:'Spouse Palace and joint business',
 cnT:'夫妻宫也是合伙宫：和另一半共同创业怎么分工',
 enT:'The Spouse Palace Is Also the Partnership Palace: Dividing Work When Couples Co-found',
 cnD:'夫妻宫除婚姻外，也是合伙宫；共同创业要看夫妻宫主星与四化定分工模式。化禄看利益分配顺不顺、化权看谁说了算、化忌看矛盾点在哪。但盘只是倾向，重大合伙务必以书面合同、股权协议和专业律师意见为准。',
 enD:'Beyond marriage, the Spouse Palace is also the partnership palace; for co-founding, read its main star and transformations to set the division of labor. Lu shows whether profit sharing runs smoothly, Quan who calls the shots, and Ji where conflicts hide. The chart is only tendency—major partnerships must rest on written contracts, equity agreements and professional legal advice.',
 cnL:'夫妻一起开店做项目，最容易把感情和生意搅在一起：白天吵分工，晚上吵钱。盘上这部分写在夫妻宫，但真正兜底的，是那份谁都不愿先谈的合同。',
 enL:'Couples who open a shop or project together most easily tangle feeling with business: arguing roles by day and money by night. The chart writes this in the Spouse Palace, but the real backstop is the contract no one wants to discuss first.',
 cnA:'读法是把四化翻译成分工：化禄落夫妻，利益分配可谈但要写清；化权同宫，一人拍板更高效，另一人要有明确授权；化忌所在，提前定规则、留边界。无论感情多好，股权、分工、退出都落书面，以专业律师和正规途径、书面合同为准。',
 enA:'Translate transformations into roles: Lu in Spouse means profit sharing is workable but must be written; Quan together means one person deciding is efficient, with clear authority for the other; wherever Ji sits, set rules and boundaries ahead. However close, put equity, roles and exit in writing, relying on professional lawyers, proper channels and written contracts.',
 cnLog:['夫妻宫兼看婚姻与合伙关系。','主星定相处与分工的基本模式。','化禄看利益分配、化权看决策权、化忌看矛盾点。','重大合伙以书面合同、股权协议与专业律师为准。'],
 enLog:['The Spouse Palace covers both marriage and partnership.','The main star sets the basic mode of relating and dividing work.','Lu shows profit sharing, Quan decision power, and Ji conflict points.','Major partnerships rest on written contracts, equity agreements and professional lawyers.'],
 cnStep:['先看夫妻宫主星，判断相处与分工基调','看四化落宫：化禄在利益分配','看化权落在哪，明确谁拍板','看化忌落在哪，提前预判矛盾点','把股权分工退出写成书面协议','签约前请专业律师把关'],
 enStep:['Read the Spouse main star for the tone of relating and roles','Read Lu for profit sharing','Read where Quan lands to decide who calls shots','Read where Ji lands to anticipate conflict points','Put equity, roles and exit into a written agreement','Have a professional lawyer review before signing'],
 cnMis:['夫妻创业只凭感情，不写合同','把化权当成谁脾气大谁说了算','见化忌不设防，矛盾爆发才补救'],
 enMis:['Starting a couple business on feeling without a contract','Taking Quan as whoever is louder deciding','Ignoring Ji and fixing conflict only after it explodes'],
 cnClose:'和另一半共同创业，浪漫和账目要分开谈。盘帮你提前看见分工和矛盾的影子，真正让感情和生意都长久的，是把规则讲在前面、写在纸上。',
 enClose:'When co-founding with your partner, separate romance from the books. The chart helps you foresee roles and conflict; what makes both love and business last is setting rules first and putting them on paper.'},

{cat:'yingyong',slug:'ziwei-tianzhaigong-zichan-juzhu',focus:'田宅宫看资产与居住根基',focusEn:'Property Palace: assets and living foundation',
 cnT:'紫微斗数田宅宫看资产与居住根基',
 enT:'Reading Assets and Living Foundation Through the Property Palace in Zi Wei Dou Shu',
 cnD:'田宅宫看固定资产、居住环境与家庭根基；联动福德看住得安不安心，联动财帛看资产变现能力。它是倾向参考，不构成投资建议，具体购房、理财与资产配置以持牌机构和正规产品说明为准。',
 enD:'The Property Palace shows fixed assets, living environment and family roots; linked with Karma it shows whether you feel at home, and with Wealth the liquidity of assets. It is a tendency reference and not investment advice; home buying, wealth products and asset allocation rest on licensed institutions and official product documentation.',
 cnL:'有人换了房子后整个人都踏实了，有人资产看着不少却住得心不安——差别往往在田宅宫这个「家」的宫位，它不只看房子，也看你扎不扎得下根。',
 enL:'Some feel settled after moving, others hold many assets yet live uneasily; the difference often lies in the home palace, which is not only about the house but whether you can put down roots.',
 cnA:'读法是两连看：田宅配福德，判断居住环境能不能让你安心；田宅配财帛，判断资产是沉在房子里还是能灵活变现。重大买卖和配置多听持牌机构与正规产品说明，别把命盘当投资依据。',
 enA:'Read in pairs: Property with Karma judges whether your living environment settles you; Property with Wealth judges whether assets are locked in real estate or can move. For major purchases and allocation, rely on licensed institutions and official product docs; do not use the chart as an investment basis.',
 cnLog:['田宅宫看固定资产、居住环境与家庭根基。','联动福德，看住得安不安心。','联动财帛，看资产变现与流动性。','不构成投资建议，以持牌机构和正规产品说明为准。'],
 enLog:['The Property Palace shows fixed assets, living environment and family roots.','With Karma it shows whether you feel at home.','With Wealth it shows asset liquidity and convertibility.','It is not investment advice; licensed institutions and official product documentation prevail.'],
 cnStep:['先看田宅宫主星与四化','评估固定资产与居住环境倾向','联动福德，判断住得是否安心','联动财帛，看资产变现能力','叠大限流年，找购置与调整阶段','重大决策以持牌机构和正规产品说明为准'],
 enStep:['Read the Property main star and transformations','Assess fixed assets and living environment tendency','Link with Karma to judge whether you feel settled','Link with Wealth to see asset liquidity','Layer decades and years to find purchase and adjustment stages','Base major decisions on licensed institutions and official product docs'],
 cnMis:['把田宅宫当成购房投资的直接依据','只看有没有房，忽略住得安不安心','不看财帛联动，资产全沉在不动产里'],
 enMis:['Treating Property as a direct basis for home investment','Looking only at whether there is a house and ignoring peace of mind','Skipping the Wealth link and locking all assets in real estate'],
 cnClose:'田宅宫是你安身立命的那块根。它提醒你什么样的住处让人安心、资产该多沉还是多活，但真要买房配置，把它当参考，把决定权交给持牌机构和正规产品说明。',
 enClose:'The Property Palace is the root where you stand. It reminds you what kind of home settles you and how much to sink or keep liquid, but when buying or allocating, take it as reference and leave the decision to licensed institutions and official product docs.'}
];
