// 2026-09-28 批次 第5组：应用/感情/六亲 8篇
module.exports=[
{cat:'yingyong',slug:'ziwei-taiyin-xing-caibo-licai-fengge',focus:'太阴星财帛理财风格',focusEn:'Tai Yin star in Wealth Palace and investing style',
 cnT:'紫微斗数太阴星坐财帛：你是细水长流型还是夜里悄悄进账',
 enT:'Tai Yin in the Wealth Palace in Zi Wei Dou Shu: Steady Saver or Quiet After-Hours Income',
 cnD:'太阴星属水，主藏、主夜、主田宅积蓄，落在财帛宫时理财风格偏保守、重积累、偏好房产与稳健配置，来得细水长流而非一夜暴富；具体偏守还是偏动，要会同宫星曜与三方四化一起看。',
 enD:"Tai Yin is a water star of storage, the night and property savings. When it sits in the Wealth Palace, the money style leans conservative, accumulative and favors real estate and steady allocation, preferring slow rivers to windfalls. Whether it leans still or active depends on the stars in the same palace and the triple-direction transformations.",
 cnL:'一打开财帛宫看到太阴，很多人立刻想到「有钱」。其实太阴说的不是你能赚多大一笔，而是你跟钱相处的方式：它偏安静、偏藏、偏夜里盘算，而不是白天高调下注。',
 enL:"Seeing Tai Yin in the Wealth Palace, many immediately think rich. What Tai Yin actually describes is not the size of a windfall but how you handle money: quiet, stored, weighed at night, rather than loudly betting in daylight.",
 cnA:'太阴坐财帛要回答的是：你的钱从什么节奏来、习惯往哪里放、是攒下来还是流转出去。它给的是一种理财性格，不是收益数字。',
 enA:"Tai Yin in the Wealth Palace asks at what rhythm money arrives, where you habitually put it, and whether it accumulates or circulates. It describes a money temperament, not a return figure.",
 cnLog:['太阴属水，主藏蓄与田宅，落财帛时倾向把钱换成看得见的资产、存下来，而非高风险博取。','太阴主夜、主静，收入常与夜间、内勤、地产、女性相关行业或细致型工作有关，来得慢而稳。','同宫若见禄存化禄，积蓄能力被加强；见化忌则容易为家宅、情感或不动产反复操心破财。','太阴理财偏防守，不等于不会赚；它更像水库，平时蓄水、旱涝时才看得出价值。'],
 enLog:["As a water star of storage and property, Tai Yin in Wealth leans toward converting money into visible assets and saving rather than high-risk bets.","Tai Yin rules night and stillness, so income often ties to night work, back-office roles, real estate, female-related industries or meticulous tasks, arriving slowly and steadily.","Lu Cun or Hua Lu in the same palace strengthens the saving instinct; Hua Ji there brings recurring worry or outflow over home, emotion or property.","A defensive Tai Yin is not unable to earn; it behaves like a reservoir, storing in normal times and showing its worth in drought or flood."],
 cnStep:['先定位财帛宫是否坐太阴，记录同宫星曜与辅煞','看太阴是庙旺还是落陷，判断蓄财力的强弱','查三方四正的禄存、化禄、化忌落在哪些宫','判断收入节奏：偏固定薪资、夜间接活还是不动产','看大限流年引动，哪几年偏蓄水、哪几年偏支出','把以上读成理财性格倾向，具体产品与仓位另走正规渠道'],
 enStep:["Locate Tai Yin in the Wealth Palace and note the stars and assistants or malefics in the same palace","Check whether Tai Yin is bright or fallen to gauge the saving strength","See where Lu Cun, Hua Lu and Hua Ji fall across the triple direction","Judge the income rhythm: fixed salary, after-hours work or property","Read decade and yearly limits for which years store and which spend","Read all this as a money-tendency profile; choose actual products and positions through formal channels"],
 cnMis:['见太阴就断定一定有钱或一定没钱，不分庙旺落陷','把太阴的守财风格误读为抠门或不会赚钱','只看财帛一宫，不配合田宅、福德与大限一起读'],
 enMis:["Assuming wealth or poverty from Tai Yin alone, ignoring bright versus fallen","Reading Tai Yin's saving style as stinginess or inability to earn","Looking only at the Wealth Palace without the Property, Karma and decade lines"],
 cnClose:'太阴坐财帛，画的是一条细水长流的钱路。它提醒你偏守、偏藏、偏不动产，具体怎么配置、买什么产品、仓位多重，不构成投资建议，一律以持牌机构和正规产品说明为准。',
 enClose:"Tai Yin in the Wealth Palace draws a slow, steady money line. It reminds you to lean defensive, stored and property-side; as for allocation, products and position sizing, this is not investment advice and should follow licensed institutions and formal product documentation."},

{cat:'yingyong',slug:'ziwei-jumen-xing-guanlu-goutong',focus:'巨门星官禄沟通',focusEn:'Ju Men star in Career Palace and communication',
 cnT:'紫微斗数巨门星坐官禄：靠嘴和笔吃饭，也靠嘴惹事',
 enT:'Ju Men in the Career Palace in Zi Wei Dou Shu: Earning by Mouth and Pen, Tripped Up by Them Too',
 cnD:'巨门主口舌、暗曜与钻研，落官禄宫时职业常与沟通、教学、法律、传媒、研究、质检相关；优势是能把复杂事讲清楚，风险是言多易招是非，需配合化禄化科看名声走向。',
 enD:"Ju Men rules speech, the hidden and deep inquiry. In the Career Palace, work often ties to communication, teaching, law, media, research or quality control. The strength is explaining complexity clearly; the risk is that loose words invite disputes, read together with Hua Lu and Hua Ke for reputation.",
 cnL:'官禄宫坐巨门的人，多半吃过「一句话说对了就成、一句话说错了就炸」的亏。巨门不是坏星，它是一颗靠嘴和笔吃饭的星——但嘴是双刃剑。',
 enL:"Those with Ju Men in the Career Palace have often learned that one well-said line seals a deal and one careless line blows it up. Ju Men is not a bad star; it earns by mouth and pen, and both edges cut.",
 cnA:'巨门坐官禄要回答的是：你的职业能不能把钻研与表达变成产品，以及话说出去之后是给你加分还是结怨。化禄化科帮你把话变成名声，化忌则容易把话变成是非。',
 enA:"Ju Men in the Career Palace asks whether your work can turn inquiry and expression into a product, and whether your words build credit or grudges. Hua Lu and Hua Ke turn words into reputation; Hua Ji turns them into disputes.",
 cnLog:['巨门为暗曜，主怀疑、深究与口舌，落在官禄适合需要钻进去再讲出来的行当。','沟通、教学、辩论、写作、法务、研究、质检、医理等「把复杂讲清楚」的工作最能发挥。','同宫见化禄，表达变成资源与口碑；见化科，表达变成名声与专业认可。','同宫见化忌或煞星，容易言多必失、口舌官非、被断章取义，需管住输出节奏。'],
 enLog:["Ju Men is a hidden star of doubt, deep inquiry and speech; in Career it suits work that digs in then explains out.","Communication, teaching, debate, writing, legal, research, quality control and medicine fit the explain-complexity niche best.","Hua Lu in the same palace turns expression into resources and word of mouth; Hua Ke turns it into reputation and professional recognition.","Hua Ji or malefics there bring loose-tongued losses, verbal disputes and being quoted out of context, so output pace must be managed."],
 cnStep:['先确认官禄宫是否坐巨门，记录同宫辅煞与四化','判断职业方向：是否偏沟通、钻研、教学或法务','看化禄化科落宫，评估表达能否转化为名声','看化忌落宫，找出哪类话题或人群最易引发口舌','在日常中练习先想后说、留书面依据','大限流年引动巨门时，提醒自己该年谨言慎行'],
 enStep:["Confirm Ju Men in the Career Palace and note same-palace assistants, malefics and transformations","Assess whether work leans communication, inquiry, teaching or legal work","See where Hua Lu and Hua Ke land to judge whether expression becomes reputation","See where Hua Ji lands to find which topics or people most easily trigger disputes","Practice thinking before speaking and keeping written records in daily work","When decade or yearly limits activate Ju Men, remind yourself to speak cautiously that period"],
 cnMis:['把巨门一概论为口舌是非星，否定其专业表达价值','以为会说就行，忽略深耕与专业底子','只看宫位不看四化，分不清话是生财还是招灾'],
 enMis:["Writing off Ju Men as purely a dispute star and ignoring its professional expression value","Assuming glibness alone works, ignoring depth and expertise","Reading the palace without transformations, unable to tell whether words earn or burn"],
 cnClose:'巨门坐官禄，是给你一张嘴一支笔当工具。用好了把复杂讲清楚、把专业变成口碑；用松了，一句话就把积累说没。管住节奏，这颗星才站在你这边。',
 enClose:"Ju Men in the Career Palace hands you a mouth and a pen as tools. Used well, you explain complexity and turn expertise into reputation; used loosely, one line erases what you built. Manage the pace and the star stands with you."},

{cat:'yingyong',slug:'ziwei-guanlu-gong-sihua-zhiye',focus:'官禄宫四化职业',focusEn:'four transformations in the Career Palace and vocation',
 cnT:'紫微斗数官禄宫四化：禄权科忌落职业宫，各在提示什么',
 enT:'Four Transformations in the Career Palace: What Lu, Quan, Ke and Ji Say About Vocation',
 cnD:'官禄宫的化禄提示资源与机会型职业，化权提示掌权与扛压型岗位，化科提示名声与专业路线，化忌提示需要反复打磨的课题领域；四者合看，才知道职业该往哪条线走。',
 enD:"Hua Lu in the Career Palace signals resource- and opportunity-based work, Hua Quan signals authority and pressure-carrying roles, Hua Ke signals reputation and professional tracks, and Hua Ji signals a field of recurring refinement. Read all four together to choose a vocational line.",
 cnL:'很多人问「我适合做什么工作」，只盯着官禄宫坐了哪颗星。其实更直接的提示，是看这一宫被四化点亮了哪几股力。',
 enL:"Many ask what job suits them while staring only at which star sits in the Career Palace. A more direct signal is which of the four transformations light up that palace.",
 cnA:'官禄宫四化要回答的是：你的职业能量是被资源推着走、被权力压着扛、被名声领着走，还是被某个课题反复纠缠。四种力对应的活法完全不同。',
 enA:"Four transformations in the Career Palace ask whether your vocational energy is pulled by resources, pressed by authority, led by reputation, or tangled in a recurring lesson. Four forces mean four very different ways to work.",
 cnLog:['官禄化禄：职业领域资源活络，机会自来，适合做对接、拓展、资源整合型岗位。','官禄化权：主动性能量强，适合带团队、扛指标、争主导，但也要承担压力与责任。','官禄化科：走专业与名声路线，靠证书、作品、口碑立身，适合咨询、文教、专业技术。','官禄化忌：职业上有反复打磨的课题，容易在某一领域纠结、返工、放不下，化阻力为深耕是出路；2026丙午年为天同化禄、天机化权、文昌化科、廉贞化忌，可对照当年职业流年。'],
 enLog:["Hua Lu in Career: the field has flowing resources and self-arriving opportunities, suiting liaison, expansion and integration roles.","Hua Quan in Career: strong initiative, suited to leading teams, carrying targets and contending for control, with matching pressure.","Hua Ke in Career: a reputation and expertise path, built on credentials, portfolio and word of mouth, fitting consulting, education and technical specialties.","Hua Ji in Career: a recurring vocational lesson, easy to dwell, rework and not let go in some field; turning friction into depth is the way out. The 2026 Bing-Wu yearly transformations are Tian Tong Lu, Tian Ji Quan, Wen Chang Ke and Lian Zhen Ji for vocational-year reference."],
 cnStep:['先找出生年四化落在哪一宫，看哪些飞进官禄宫','分别标记化禄、化权、化科、化忌是否落在官禄','化禄在官禄：评估是否走资源拓展路线','化权在官禄：评估是否愿意带队扛压','化科在官禄：评估是否走专业证书口碑路线','化忌在官禄：找出反复纠结的领域，把它当深耕方向而非逃开'],
 enStep:["Locate the natal transformations by birth year stem and see which fly into the Career Palace","Mark whether Lu, Quan, Ke and Ji each land in Career","If Lu is in Career, assess a resource-expansion path","If Quan is in Career, assess whether you want to lead and carry pressure","If Ke is in Career, assess a credential-and-reputation professional track","If Ji is in Career, find the recurring field and treat it as a depth direction rather than an escape"],
 cnMis:['见官禄化禄就断定当官发财，不看实际承接','见官禄化忌就断定职业必败，不知可化深耕','只看生年四化，不叠加大限流年对职业宫的引动'],
 enMis:["Declaring official wealth from Lu in Career without real capacity","Declaring career failure from Ji in Career without seeing it as depth","Reading only natal transformations while ignoring decade and yearly activations of the Career Palace"],
 cnClose:'官禄宫四化不是四个岗位名称，而是四种职业能量。看清自己被哪股力牵着走，顺着力选赛道，比硬追热门行业省力得多。',
 enClose:"The four transformations in the Career Palace are not four job titles but four vocational energies. See which force pulls you and choose the track along it; that beats chasing a trendy industry."},

{cat:'yingyong',slug:'ziwei-caibo-gong-lucun-hualu-peihe',focus:'财帛宫禄存化禄配合',focusEn:'Lu Cun and Hua Lu together in the Wealth Palace',
 cnT:'紫微斗数财帛宫禄存加化禄：双禄守财是好，但别当成躺赢',
 enT:'Lu Cun and Hua Lu Together in the Wealth Palace: Double Lu Looks Great, But It Is Not Free Money',
 cnD:'禄存是固定存量，化禄是流动增量，双禄同宫或会照时储蓄与财源同时被加强；但能否留下来，还要看同宫是否见化忌、擎羊陀罗，以及大限流年是否引动破耗。',
 enD:"Lu Cun is fixed stock and Hua Lu is flowing increment. When both share or aspect the Wealth Palace, savings and inflow strengthen together; whether money actually stays depends on same-palace Ji, Yang Tuo and whether decade or yearly limits trigger outflow.",
 cnL:'排盘看到财帛宫同时坐禄存和化禄，很多人立刻觉得「这下发了」。先别急着庆祝：双禄是好底子，但它管的是能不能赚钱、能不能攒下，不是自动到账。',
 enL:"Seeing Lu Cun and Hua Lu together in the Wealth Palace, many immediately feel they have hit it big. Hold the celebration: double Lu is a strong base, but it governs earning and saving ability, not an automatic deposit.",
 cnA:'双禄要拆开看：禄存像仓库里的存货，化禄像新进来的流水。仓库满、流水也进，是结构上的好；可仓库有没有漏、流水会不会被抽走，还要看煞星与忌。',
 enA:"Double Lu should be split: Lu Cun is inventory in the warehouse, Hua Lu is fresh inflow. Full warehouse plus inflow is structurally good, but whether the warehouse leaks and whether the flow gets siphoned depend on malefics and Ji.",
 cnLog:['禄存为天禄，主固定存量、薪资与稳定资产，落在财帛代表积蓄能力扎实。','化禄为流动之禄，主机会与新增财源，落在财帛代表近年活水较旺。','双禄同宫或三方会照，是储蓄与开源同时被加强，属于结构上的优势。','但禄存两旁常夹擎羊、陀罗，且若见化忌冲照或大限流年引动，仍可能因担保、投资失误、人情破财而漏财。'],
 enLog:["Lu Cun is celestial salary, standing for fixed stock, steady income and stable assets; in Wealth it means solid saving ability.","Hua Lu is flowing salary, standing for opportunity and new income; in Wealth it means fresh current in recent years.","Double Lu in one palace or by triple aspect strengthens saving and open-source at once, a structural advantage.","Yet Lu Cun is often flanked by Yang Tuo, and if Ji clashes or a decade or yearly limit triggers, guarantees, bad investments or favors can still leak money."],
 cnStep:['先确认财帛宫是否同时见禄存与化禄','分开记录：哪颗是存量、哪颗是增量','查同宫及夹宫是否见擎羊、陀罗、火星、铃星','查是否有化忌冲照财帛或大限引动破耗','判断双禄是「能赚能存」还是「赚得多留不住」','落到现实，做好现金流与分散配置，不押单一标的'],
 enStep:["Confirm whether Lu Cun and Hua Lu share the Wealth Palace","Separate which is stock and which is increment","Check the same and flanking palaces for Yang, Tuo, Huo and Ling","Check whether Ji clashes or a decade limit triggers outflow","Judge whether double Lu means earn-and-keep or earn-more-keep-less","In practice, manage cash flow and diversify rather than concentrating on one asset"],
 cnMis:['见双禄就断定躺赢、盲目加杠杆','把禄存当成随时可花的现金，忽略它是存量资产','只看双禄不看煞忌，忽视漏财通道'],
 enMis:["Declaring free money from double Lu and blindly leveraging","Treating Lu Cun as spendable cash, ignoring it is stock","Reading double Lu without malefics and Ji, missing the leak channels"],
 cnClose:'双禄守财是好底子，但它给的是赚钱和存钱的能力，不是保险箱。具体怎么配置、上不上杠杆、选什么产品，不构成投资建议，一切以持牌机构和正规产品说明为准。',
 enClose:"Double Lu guarding wealth is a strong base, but it grants earning and saving ability, not a safe. As for allocation, leverage and product choice, this is not investment advice and should follow licensed institutions and formal product documentation."},

{cat:'ganqing',slug:'ziwei-fuqi-gong-tiankui-tianyue',focus:'夫妻宫天魁天钺',focusEn:'Tian Kui and Tian Yue in the Spouse Palace',
 cnT:'紫微斗数夫妻宫天魁天钺：贵人型配偶，不等于婚姻一定顺',
 enT:'Tian Kui and Tian Yue in the Spouse Palace: A Helpful Spouse, Not a Guaranteed Smooth Marriage',
 cnD:'天魁天钺是贵星，落夫妻宫常代表配偶或婚姻中易得长辈、贵人相助，对象条件或带提携资源；但婚姻顺不顺，必须联看夫妻宫三方、福德、迁移与大限，单看贵星不下结论。',
 enD:"Tian Kui and Tian Yue are nobleman stars. In the Spouse Palace they often mean the spouse or the marriage draws elders and helpful people, and the partner may bring connections; but whether the marriage is smooth requires the Spouse triple direction, Karma, Travel and the decade together. Noble stars alone do not settle it.",
 cnL:'夫妻宫坐天魁或天钺，听起来像「能遇到帮你的人」。确实有这层意思，但它说的是有人搭把手，不是说你们俩不吵架、不分手。',
 enL:"Tian Kui or Tian Yue in the Spouse Palace sounds like meeting someone who helps. There is that layer, but it says a hand is offered, not that the two of you never argue or split.",
 cnA:'贵星落夫妻要回答两件事：一是配偶本身是否带资源或长辈缘，二是这段婚姻在关键节点有没有外部贵人拉一把。它加分，但不替代夫妻宫本身的星曜煞忌与大限走势。',
 enA:"Noble stars in the Spouse Palace ask two things: whether the partner itself brings resources or elder favor, and whether the marriage gets an external helping hand at key moments. It adds points but does not replace the palace's own stars, malefics and decade trend.",
 cnLog:['天魁为阳贵、天钺为阴贵，主长辈、上司、外部贵人的提携。','落夫妻宫时，对象的家世、职场或人脉中常带有能帮衬你的资源。','贵人助力是外缘，婚姻本身的相处质量仍看夫妻宫主星、煞星与四化。','必须联看福德宫的心态、迁移宫的相处距离、以及当前大限对夫妻宫的引动，单宫断婚姻不稳。'],
 enLog:["Tian Kui is the nobleman of yang and Tian Yue of yin; both stand for mentors, seniors and external benefactors.","In the Spouse Palace, the partner's family, workplace or network often carries resources that can help you.","Benefactor help is external; the marriage's own quality still depends on the palace's main star, malefics and transformations.","You must read the Karma Palace for mindset, the Travel Palace for relational distance and the active decade's activation of the Spouse; judging marriage from one palace is unstable."],
 cnStep:['先确认夫妻宫坐的是天魁、天钺还是二者同宫','看夫妻宫主星与煞星，判断相处基调','联看福德宫，确认自己在感情里的心态与安全感','联看迁移宫，判断两人聚少离多还是近距离相处','查大限对夫妻宫的引动，定位感情关键阶段','综合判断：贵人助力是加分项，不是婚姻成败的判决'],
 enStep:["Confirm whether the Spouse Palace holds Tian Kui, Tian Yue or both","Read the Spouse main star and malefics for the relational tone","Layer the Karma Palace for your own emotional mindset and security","Layer the Travel Palace for closeness versus distance between the two","Check the decade's activation of the Spouse to locate key relationship stages","Conclude: benefactor help is a plus, not a verdict on whether the marriage works"],
 cnMis:['见夫妻宫贵星就断定一定嫁得好娶得好','把配偶的贵人缘当成自己可以躺靠的资本','只看夫妻一宫，不联看福德、迁移与大限'],
 enMis:["Declaring a great marriage from noble stars in the Spouse Palace","Treating the partner's benefactor network as capital you can lean on passively","Reading only the Spouse palace without Karma, Travel and the decade"],
 cnClose:'天魁天钺落夫妻，是说这桩婚姻里有人搭把手、配偶带资源。但日子过得顺不顺，要夫妻、福德、迁移、大限四宫一起看——贵人是风，船怎么划还得靠自己。',
 enClose:"Tian Kui and Tian Yue in the Spouse mean someone lends a hand and the partner brings resources. Whether the days go smoothly needs the Spouse, Karma, Travel and decade read together; benefactors are the wind, but you still row the boat."},

{cat:'ganqing',slug:'ziwei-zhengyuan-duogongwei-panduan',focus:'正缘多宫位判断',focusEn:'judging a true relationship across multiple palaces',
 cnT:'紫微斗数怎么判断正缘和烂桃花：按顺序看，别一上来就冲',
 enT:"How to Tell a True Match from a Bad Romance in Zi Wei Dou Shu: Read in Order, Don't Rush In",
 cnD:'正缘不靠夫妻宫一颗好星定，而按「夫妻宫主星—福德宫心态—迁移宫相处—大限引动—现实互动」五步交叉判断；烂桃花往往是某一步看着亮、后面几步全塌。',
 enD:"A true match is not settled by one good star in the Spouse Palace; it is judged across five steps: Spouse main star, Karma mindset, Travel dynamics, decade activation and real-life interaction. A bad romance often looks bright at one step and collapses in the rest.",
 cnL:'很多人一遇心动对象就问「这是不是正缘」。盘上看不出来「是」或「不是」，只能按顺序一层一层过：这一关过不了，后面再甜也先放着。',
 enL:"Many ask, the moment they feel a spark, whether this is the one. The chart cannot say yes or no; it can only be checked layer by layer in order. If a layer fails, however sweet the rest feels, hold off.",
 cnA:'判断正缘要回答的是：这段关系在结构上稳不稳、你在里面自不自在、两个人距离合不合、当下大限是成全还是消耗、现实里处得下去吗。五条全过关，才谈得上正缘。',
 enA:"Judging a true match asks whether the relationship is structurally stable, whether you feel at ease in it, whether the relational distance fits, whether the current decade supports or drains it, and whether real-life interaction works. Only when all five pass is it worth calling a true match.",
 cnLog:['第一步看夫妻宫主星与煞忌：关系的底色是稳定还是拉扯。','第二步看福德宫：你在这段关系里是心安还是内耗，自己骗不了自己。','第三步看迁移宫：两人相处距离、聚散节奏是否合得来。','第四步看大限引动：当前十年是把这段关系推近还是推远；现实互动是第五步——花钱、吵架、家务、家人关系这些真问题，盘上再好也要落地试。'],
 enLog:["Step one reads the Spouse main star and malefics and Ji: is the base stable or pulling?","Step two reads the Karma Palace: are you at peace or drained in this relationship; you cannot fool yourself.","Step three reads the Travel Palace: does the closeness and rhythm of being together actually fit.","Step four reads the decade: does this ten-year window pull the relationship closer or push it away. Real-life interaction is step five: money, arguments, chores and family relations; however good the chart, it must be tested on the ground."],
 cnStep:['先看夫妻宫主星与煞忌，判断关系底色','再看福德宫，确认自己在这段关系里的心安程度','看迁移宫，判断两个人距离与相处节奏','查当前大限对夫妻宫的引动，是助力还是消耗','把盘上结论拿到现实里试：沟通、花钱、矛盾处理','五步都过关再谈正缘；任何一步明显塌，先当观察期'],
 enStep:["First read the Spouse main star, malefics and Ji for the relational base","Then read the Karma Palace for how at ease you really feel","Read the Travel Palace for distance and rhythm between you","Check the active decade's activation of the Spouse for support or drain","Take the chart conclusion into real life: communication, money, conflict handling","Call it a true match only when all five pass; if any step clearly fails, stay in observation"],
 cnMis:['刚认识就拿夫妻宫好星断定是正缘','只凭心动感觉判定，不看福德宫的真实心态','把大限桃花误当正缘，流年一过人才看清'],
 enMis:["Declaring a true match from one good Spouse star right after meeting","Judging by a crush alone without the Karma Palace's real mindset","Mistaking a decade's peach-blossom activation for a true match, seeing clearly only after it passes"],
 cnClose:'正缘不是一眼命中的答案，而是一关一关过出来的。夫妻、福德、迁移、大限、现实互动，五关都过，再谈定终身；有一关塌了，先别把自己全交出去。',
 enClose:"A true match is not a one-glance verdict but something passed gate by gate. Spouse, Karma, Travel, decade and real interaction all pass before talking lifelong; if one gate falls, do not hand yourself over fully."},

{cat:'liuqin',slug:'ziwei-fumu-gong-muqin-shenti',focus:'父母宫母亲身体',focusEn:'the Parents Palace and mother health',
 cnT:'紫微斗数父母宫看母亲身体：倾向提醒，不是体检报告',
 enT:'Reading Mother Health Through the Parents Palace in Zi Wei Dou Shu: A Reminder, Not a Checkup',
 cnD:'父母宫兼看父母双方的缘薄与助力，其中母亲相关的体质偏向要结合太阴、太阳与疾厄宫综合读；盘上只能提示薄弱系统与作息提醒，不能替代检查与诊断。',
 enD:"The Parents Palace reads the bond and support from both parents; tendencies tied to the mother are read together with Tai Yin, Tai Yang and the Health Palace. The chart can only flag weak systems and routine reminders, not replace tests or diagnosis.",
 cnL:'有人排完盘看到父母宫坐了某颗煞星，立刻紧张母亲身体。先把话说清楚：盘上能读的是长期偏向，不是哪一年要生什么病。',
 enL:"Someone casts the chart, sees a malefic in the Parents Palace and immediately panics about the mother's health. Make this clear first: the chart reads long-term tendencies, not which illness strikes in which year.",
 cnA:'父母宫看母亲身体要回答的是：她哪一类体质偏虚、哪类生活习惯容易积劳、子女可以在哪些方面多留意。它是一张提醒清单，不是诊断书。',
 enA:"Reading mother health through the Parents Palace asks which bodily tendency runs weak, which habits accumulate strain, and where the children should pay extra attention. It is a reminder list, not a diagnosis.",
 cnLog:['父母宫看与父母的缘分、助力与相处模式，并非专门的疾病宫。','母亲相关的体质偏向，常配合太阴星、田宅与疾厄宫一起看，太阳则偏父亲一方。','煞星或化忌落父母宫，提示这一缘分或照护关系上容易操心、聚少离多或有牵挂。','盘不能量血压、不能拍片、不能开药；持续不适或老年慢病，一律以正规就医为准。'],
 enLog:["The Parents Palace reads the bond, support and dynamic with parents, not a dedicated illness palace.","Tendencies tied to the mother are read with Tai Yin, the Property Palace and the Health Palace; Tai Yang leans toward the father side.","Malefics or Hua Ji in the Parents Palace signal worry, distance or attachment in that care relationship.","The chart cannot measure blood pressure, scan or prescribe; persistent discomfort or chronic elder issues follow formal medical care."],
 cnStep:['先定位父母宫，看主星与煞忌的整体基调','配合太阴与疾厄宫，读出母亲体质上的薄弱倾向','把倾向翻译成生活提醒，如作息、饮食、体检项目','明确标注这是非诊断性的倾向参考','若母亲已有持续不适或老慢病，优先建议正规就医','定期陪她做正规体检，把盘上提醒变成具体的检查项'],
 enStep:["Locate the Parents Palace and read the main star, malefics and Ji for the overall tone","Pair Tai Yin and the Health Palace to read the mother's weak bodily tendencies","Translate tendencies into lifestyle reminders on rest, diet and checkup items","Mark clearly this is a non-diagnostic tendency reference","If the mother has persistent discomfort or chronic illness, prioritize formal medical care","Accompany regular checkups and turn chart reminders into concrete exam items"],
 cnMis:['把父母宫煞星当成母亲一定会生病的判决','用盘上说法推迟母亲该做的体检或就诊','把父母宫直接等同于母亲专属健康宫，忽略疾厄宫'],
 enMis:["Treating a malefic in the Parents Palace as a verdict of certain illness","Using chart talk to delay checkups or visits the mother needs","Equating the Parents Palace directly with the mother's health palace and ignoring the Health Palace"],
 cnClose:'父母宫看母亲，是提醒你多留心哪几类体质偏向、定期陪她体检。这是倾向，不是诊断；真有不舒服，正规就医永远比翻盘靠谱。',
 enClose:"Reading the mother through the Parents Palace reminds you which bodily tendencies to watch and to accompany regular checkups. This is a tendency, not a diagnosis; when real discomfort comes, formal care is always more reliable than the chart."},

{cat:'liuqin',slug:'ziwei-zinv-gong-taiyang-guanxin',focus:'子女宫太阳关心',focusEn:'Tai Yang in the Children Palace and parental care',
 cnT:'紫微斗数子女宫坐太阳：对孩子是操心型还是放养型',
 enT:"Tai Yang in the Children Palace: A Worrying Parent or a Hands-off One",
 cnD:'太阳主光明、外放与付出，落子女宫时父母对孩子倾向于公开关注、愿意投入资源、也容易操心过头；具体是严是宽，要会同宫星曜、煞忌与大限一起看，不写成定论。',
 enD:"Tai Yang stands for light, outward expression and giving. In the Children Palace, parents tend toward open attention, willing investment of resources and over-worrying; whether strict or lenient depends on same-palace stars, malefics, Ji and the decade, not a fixed verdict.",
 cnL:'子女宫坐太阳的父母，多半是那种「孩子在学校吃了没」都要发三条消息的类型。太阳是发光的星，它照向孩子，也容易照过头变成盯。',
 enL:"Parents with Tai Yang in the Children Palace are the type who send three messages to ask whether the child has eaten. Tai Yang is a shining star; it shines on the child, and can easily overshoot into constant watching.",
 cnA:'子女宫太阳要回答的是：你对孩子的关心是托举式的还是包办式的，资源给得够不够，以及有没有把自己的期待压到孩子身上。它看的是亲子互动的方式。',
 enA:"Tai Yang in the Children Palace asks whether your care is supportive or over-managing, whether resources are given enough, and whether you are projecting your own expectations onto the child. It reads the way parent and child interact.",
 cnLog:['太阳主光明、外向、付出，落子女宫时父母愿意在孩子身上花钱花时间。','阳光型关心是托举，让孩子敢往外走；过头则变成控制与焦虑，孩子反而缩手。','同宫见禄存化禄，资源投入宽裕；见化忌或煞星，容易为孩子的学业、健康或未来反复操心。','子女宫也要看大限引动：不同十年，父母关心的重点会从升学、交友到独立逐步切换。'],
 enLog:["Tai Yang is light, outward and giving; in the Children Palace, parents willingly spend money and time on the child.","Sunny care is support that lets the child step outward; overdone it becomes control and anxiety and the child shrinks.","Lu Cun or Hua Lu in the same palace means ample resource input; Hua Ji or malefics bring recurring worry over schooling, health or the child's future.","The Children Palace also reads decade activation: across ten-year windows, parental focus shifts from schooling to friendships to independence."],
 cnStep:['先定位子女宫是否坐太阳，记录同宫星曜与煞忌','判断自己关心的风格：托举型还是包办型','看化禄化忌落宫，评估资源给得是否适度','把过度操心翻译成可执行的放手动作','看大限引动，对应孩子当前年龄段的关注重点','始终记住亲子是双向成长，不是单向投射'],
 enStep:["Locate Tai Yang in the Children Palace and note same-palace stars, malefics and Ji","Judge your care style: supportive or over-managing","See where Hua Lu and Hua Ji land to assess whether resources are given in measure","Translate over-worry into concrete letting-go moves","Read decade activation to match the child's current life stage","Remember parenting grows both ways, not one-way projection"],
 cnMis:['见太阳就断定孩子一定有出息、自己一定是好父母','把太阳的付出等同于控制，不给孩子独立空间','只看子女宫本宫，不配合大限与孩子实际年龄'],
 enMis:["Declaring the child will surely succeed and the parent surely good from Tai Yang alone","Equating Tai Yang's giving with control and denying the child independence","Reading only the Children Palace without the decade and the child's actual age"],
 cnClose:'太阳落子女宫，是提醒你光要照在孩子身上，别变成盯。该给的资源给到位，该放的手放出去——亲子这条路，托举比抓紧走得远。',
 enClose:"Tai Yang in the Children Palace reminds you to shine light on the child, not to stare. Give the resources that are due and release the hand that should be free; on the parenting road, holding up travels further than gripping."}
];
