// 2026-09-28 批次 第2组：四化案例/格局 8篇
module.exports=[
{cat:'sihua',slug:'ziwei-shengianji-zihuaji-anli',focus:'生年忌自化忌案例',focusEn:'natal Hua Ji vs self-transformed Hua Ji cases',
 cnT:'紫微斗数生年忌与自化忌：同一宫位，牵挂的性质不一样',
 enT:'Natal Hua Ji Versus Self-Transformed Hua Ji in Zi Wei Dou Shu: Different Kinds of Attachment in the Same Palace',
 cnD:'生年忌是先天就摆在那里的课题，一辈子绕不开；自化忌是这一宫自己往外泄、事到临头又反悔。两者同坐一宫，不等于双倍阻滞，要分清哪一份是天生的、哪一份是自己反复造成的。',
 enD:"Natal Hua Ji is a lesson placed at birth and carried for life, while a self-transformed Hua Ji means the palace itself leaks or backtracks at the last moment. Sharing one palace is not double blockage; tell which part is innate and which part is self-inflicted.",
 cnL:'有人一看到某宫坐了生年忌，那颗星又自化忌，就吓一跳，以为这宫完蛋了。其实这两种忌根本不是一回事：一个是天生的债，一个是自己临事打退堂鼓。',
 enL:"Many panic when a natal Hua Ji shares a palace with a self-transformed Hua Ji, assuming that palace is ruined. The two Ji are not the same: one is an innate debt, the other is backing out at the last minute.",
 cnA:'这个问题到底在问什么：生年忌问的是「这件事我为什么天生放不下」，自化忌问的是「这件事为什么每次快成了又被我自己搅黄」。前者要面对，后者要觉察自己的反复。',
 enA:"What the question really asks: natal Hua Ji asks why this matter is inherently hard to let go, while self-transformed Hua Ji asks why it repeatedly falls apart at your own hand. The first you face; the second you watch yourself doing.",
 cnLog:['生年忌由出生年干决定，先天落定某一宫，代表这一生在该领域有反复要处理的课题，甩不掉也躲不开。','自化忌是某宫星曜自己化出忌，代表这一宫的能量往外收又回不来，事到临头容易生变、反悔、自己泄气。','同宫见生年忌加自化忌，不等于阻滞翻倍，而是先天课题之上又叠加了临事退缩的行为模式。','看的时候先问这宫的不顺，是命里带的功课，还是自己每次都在最后一步松手。'],
 enLog:["Natal Hua Ji is fixed by the birth year stem and lands in a palace from birth, marking a lifelong recurring lesson in that area.","Self-transformed Hua Ji arises within a palace itself, meaning its energy leaks out and returns: plans change, doubts surface, one deflates at the finish line.","Natal Ji plus self-Ji in one palace is not double blockage; it layers a self-sabotaging habit on top of an innate lesson.","Ask first whether the friction in that palace is a built-in lesson or a habit of letting go at the last step."],
 cnStep:['先按出生年干找出生年忌落在哪一宫，这是先天课题的位置','再逐宫查哪些宫位有自化忌，这是行为模式的位置','把两者同宫的情形单独标出来，问清是哪类不顺反复出现','看生年忌所在宫的三方四正，判断课题承接在哪个领域','看自化忌对应的事是不是总在临门一脚出问题','分开下结论：先天忌要长期面对，自化忌要在事上觉察自己'],
 enStep:["Find the natal Hua Ji palace from the birth year stem, the innate lesson's position","Scan every palace for self-transformed Hua Ji, the habit-pattern positions","Flag overlaps and ask which kind of friction recurs there","Read the natal Ji's triple-direction to see which area carries the lesson","Check whether self-Ji matters tend to fail at the last step","Conclude separately: face natal Ji over the long run, observe self-Ji in the moment"],
 cnMis:['把生年忌加自化忌直接当成凶上加凶','见忌就归命运，不看自己是不是每次都临阵退缩','把自化忌解释成外部小人破坏，忽略是宫内自泄'],
 enMis:["Reading natal Ji plus self-Ji as simply double misfortune","Blaming fate for every Ji without asking whether you back out at the finish","Blaming outside rivals for self-Ji while missing that the palace leaks itself"],
 cnClose:'盘上的忌不是判决书，是提醒。生年忌告诉你哪门功课要修一辈子，自化忌提醒你别在快拿到结果时自己先松手——看清是哪一种，才知道该改的是命还是自己。',
 enClose:"Ji on the chart is not a verdict but a reminder. Natal Ji tells you which lesson lasts a lifetime; self-Ji warns you not to let go just before the result arrives. Tell which is which, and you know whether to work on fate or on yourself."},

{cat:'sihua',slug:'ziwei-taiyin-huaquan-caibo-caiyuan',focus:'太阴化权财帛财源',focusEn:'Tai Yin Hua Quan in the Wealth Palace and income sources',
 cnT:'紫微斗数太阴化权坐财帛：财源是怎么来的，比钱多钱少更值得看',
 enT:'Tai Yin Hua Quan in the Wealth Palace: Where Income Comes From Matters More Than How Much',
 cnD:'太阴主藏、主静财，化权则加了主动权与扛事的分量；落财帛宫，往往提示财源偏稳、偏积累型，靠专业、夜间事务或女性相关资源慢慢立起来。读这一宫要看财源结构，而非直接断财富数字。本文不构成投资建议，以持牌机构和正规产品说明为准。',
 enD:"Tai Yin governs storage and quiet wealth, and Hua Quan adds initiative and the weight of carrying responsibility. In the Wealth Palace it often points to steady, accumulative income built through specialization, night-time work or resources linked to women. Read the structure of income rather than a wealth number. This is not investment advice; rely on licensed institutions and formal product documents.",
 cnL:'有人看到太阴化权在财帛，就问「我是不是要发大财」。其实这颗星加权，先说的是钱怎么进来、稳不稳、累不累，而不是一个总数。',
 enL:"Seeing Tai Yin Hua Quan in the Wealth Palace, people ask whether they are about to get rich. The star with Quan first says how money comes in, how steady it is and how hard it is earned, not a total figure.",
 cnA:'这个问题到底在问什么：太阴化权在财帛，是在描述财源的性质——偏储蓄、偏专业、偏细水长流，并且带一点主动争取的劲头。它不是印钞机标志，而是收入结构的画像。',
 enA:"What the question really asks: Tai Yin Hua Quan in the Wealth describes the nature of income, leaning toward savings, specialization and steady flow, with a push of active striving. It is not a money-printer sign but a portrait of how income is structured.",
 cnLog:['太阴为水、为藏，主储蓄、不动产相关的安静财，不喜浮夸的短线。','化权加在太阴上，给这股安静的财加上主动权与掌控欲，倾向靠专业能力和耐心去守住财源。','落财帛宫时，财源常与女性、夜间事务、房地产、细致服务或长期积累相关，而非风口暴利。','权也带压力，意味着这份钱要靠扛事、靠盯，不是躺着自动到账。'],
 enLog:["Tai Yin is water and storage, governing savings and quiet property-linked wealth, not flashy short-term gains.","Hua Quan on Tai Yin adds initiative and control to that quiet money, leaning on expertise and patience to hold the source.","In the Wealth Palace, the source often links to women, night-time work, real estate, meticulous service or long accumulation, not windfall trends.","Quan also carries pressure, meaning this money is held by carrying and watching, not by lying still."],
 cnStep:['先确认财帛宫是不是太阴坐守、并是否化权','看太阴是否庙旺，判断这份财源本身稳不稳','看财帛三方四正的辅煞，是助力多还是耗损多','找化禄与化忌分别落在哪，看钱从哪进来、又从哪漏掉','结合大限流年，看哪十年这份财源在扩张或收紧','把结论说成财源结构与节奏，不断具体金额，并提示投资以正规渠道为准'],
 enStep:["Confirm whether Tai Yin sits in the Wealth Palace and carries Hua Quan","Check whether Tai Yin is bright to judge the source's inherent stability","Read the triple-direction for assistants versus drainers","Locate Hua Lu and Hua Ji to see where money enters and where it leaks","Layer decade and year limits to see when the source expands or tightens","State the income structure and rhythm rather than a sum, and point to licensed channels for investing"],
 cnMis:['见太阴化权在财帛就断大富大贵','把权当成可以放任不管的自动财','只看一颗财帛星，不看禄忌流向与三方耗损'],
 enMis:["Calling great wealth on sight of Tai Yin Hua Quan in the Wealth Palace","Treating Quan as money that runs itself without oversight","Reading one wealth star while ignoring Lu-Ji flow and triple-direction drains"],
 cnClose:'太阴化权在财帛，画的是一张「稳而累、细水长流」的财源图。它提醒你守住专业、盯紧进出，而不是赌一把。真要做投资配置，交给持牌机构和正规产品，盘只能帮你理解自己的财源脾气。',
 enClose:"Tai Yin Hua Quan in the Wealth draws a portrait of steady yet diligent, long-flowing income. It reminds you to guard expertise and watch flows rather than gamble. For actual investment allocation, rely on licensed institutions and formal products; the chart only helps you understand your own income temperament."},

{cat:'sihua',slug:'ziwei-hualu-guanlu-gong-shiye-jiyu',focus:'化禄官禄事业机遇',focusEn:'Hua Lu in the Career Palace and career opportunities',
 cnT:'紫微斗数化禄落官禄：机会是来了，但接不接得住另说',
 enT:'Hua Lu in the Career Palace: Opportunity Arrives, But Whether You Can Hold It Is Another Matter',
 cnD:'化禄落官禄宫主事业领域容易有活水、有机会与好人缘，但禄只是开门，能不能把机会变成成果，还要看权科忌的配合与自身承接力。官禄见禄不等于躺赢，更像门口不断有人递机会进来。',
 enD:"Hua Lu in the Career Palace means the career field tends to receive a flow, opportunities and easy rapport, but Lu only opens the door. Whether the opportunity becomes results depends on Quan, Ke and Ji working together and on your own capacity. Lu in career is not automatic winning; it is people keeps handing opportunities through the door.",
 cnL:'有人官禄宫坐化禄，就觉得事业稳了。可真到机会上门，却常常接得手忙脚乱，甚至好事变麻烦。问题出在哪？',
 enL:"With Hua Lu in the Career Palace, people assume career is settled. Yet when opportunities actually arrive, they juggle clumsily and good things turn into mess. Where does that go wrong?",
 cnA:'这个问题到底在问什么：化禄在官禄，问的是事业领域的资源与机会从哪里来、顺不顺；它不直接等于职位高低或收入数字，而是机会密度与人际顺缘的画像。',
 enA:"What the question really asks: Hua Lu in the Career Palace asks where career resources and opportunities come from and how smoothly they flow. It is not directly a rank or salary figure but a portrait of opportunity density and easy rapport.",
 cnLog:['官禄宫看事业形态、上级环境与做事舞台，化禄落在这一宫，主该领域机会多、资源顺、人缘不差。','禄是「进得来」，代表有人愿意给机会、有项目找上门，但不等于「留得住、做得成」。','能否接住禄，要看同宫与三方有没有化权撑住执行、化科撑住名声、化忌会不会把好事拖成牵挂。','大限流年再叠一层禄到官禄，往往是某段时间机会明显变多的触发点。'],
 enLog:["The Career Palace shows work shape, superiors and stage; Hua Lu here means more opportunities, easier resources and decent rapport.","Lu means incoming: people offer chances and projects walk in, but it does not mean they are kept and completed.","Whether Lu is held depends on Quan for execution, Ke for reputation and Ji that may drag a good thing into attachment.","A decade or yearly Lu layered onto the career often marks a stretch when opportunities visibly multiply."],
 cnStep:['先确认官禄宫是哪颗主星坐守、有无化禄','看化禄同宫与三方的权科忌如何配合','判断这股机会是偏人际、偏项目还是偏资源','看化忌是否也落在官禄或其三方，评估哪里会被拖住','叠大限流年，找哪几年机会被特别引动','把结论说成机会来源与承接条件，不断职位或薪资数字'],
 enStep:["Identify the main star in the Career Palace and whether it carries Hua Lu","Read how Quan, Ke and Ji accompany that Lu in the same and triple-direction palaces","Judge whether the opportunity leans on people, projects or resources","See whether Ji also touches the career to know what drags","Layer decade and year limits to find which years activate the opportunities","State the source of opportunity and the conditions to hold it, not a job title or salary"],
 cnMis:['见官禄化禄就断事业一帆风顺、高枕无忧','把禄当成已经到手的成果，不看承接与执行','只看本命禄，不叠大限流年的机会窗口'],
 enMis:["Reading career as smooth and worry-free on sight of career Lu","Treating Lu as a result already in hand without execution","Reading only natal Lu while ignoring decade and yearly opportunity windows"],
 cnClose:'官禄化禄像门口一直有人递邀请函。机会多是好事，但请柬要自己走进去接得住才算数——看清谁在递、自己扛不扛得动，禄才不只是热闹一场。',
 enClose:"Hua Lu in career is like people handing invitation cards through the door. More chances is good, but you must walk in and hold them; see who is handing them and whether you can carry them, or Lu stays only a lively scene."},

{cat:'sihua',slug:'ziwei-huake-fumu-gong-wenshu-xueli',focus:'化科父母宫文书学历',focusEn:'Hua Ke in the Parents Palace, documents and education',
 cnT:'紫微斗数化科落父母宫：文书、学历与长辈缘的那条线',
 enT:'Hua Ke in the Parents Palace: The Line of Paperwork, Education and Elder Kinship',
 cnD:'父母宫除了看长辈缘，也兼看文书、学历与外在声名的来源；化科落此，常提示在学历、证书、正式文件和长辈提携上较容易有体面与缓冲。它不是学历高低的判决，而是这条线顺不顺的描述。',
 enD:"Beyond elder relationships, the Parents Palace also reads paperwork, education and external reputation; Hua Ke here often points to ease and cushion in degrees, certificates, formal documents and elder support. It is not a verdict on degree level but a description of how smoothly that line flows.",
 cnL:'有人父母宫坐化科，就问「我是不是学历特别高」。其实这颗科说的是文书这条线走不走得顺、有没有长辈帮衬，不是直接对应一张文凭的高度。',
 enL:"With Hua Ke in the Parents Palace, people ask whether they will hold a very high degree. The Ke really says whether the paperwork line flows smoothly and whether elders support it, not directly how tall a diploma is.",
 cnA:'这个问题到底在问什么：父母宫的化科，连接的是长辈、文书、学历与官方文件这一整条线。它看的是这条线容不容易有体面、有缓冲、有人带路，而不是单看读书分数。',
 enA:"What the question really asks: Hua Ke in the Parents Palace connects elders, paperwork, education and official documents as one line. It reads whether that line carries face, cushion and guidance, not just exam scores.",
 cnLog:['父母宫在传统看法里看父母缘、长辈助力，也延伸到文书、学历、上级与官方关系。','化科主名声、文书与缓冲，落父母宫，提示学历证书、正式文件类的事较易体面过关。','这也意味着长辈或上级里容易出现愿意背书、愿意带一程的人。','科是缓冲不是保送，遇到关键文书仍要自己把材料做扎实。'],
 enLog:["The Parents Palace traditionally reads elder kinship and support, and extends to paperwork, education, superiors and official relations.","Hua Ke governs reputation, documents and cushion; here it suggests degrees, certificates and formal files tend to pass with dignity.","It also means elders or superiors may include someone willing to endorse and guide you.","Ke is a cushion, not an automatic pass; key documents still must be prepared solidly by yourself."],
 cnStep:['先确认父母宫坐守何星、是否化科','看同宫与三方的辅星，判断文书线是顺还是多耗','读这条线上长辈缘与上级关系是助力还是压力','结合大限流年，看哪几年考试、证件、签约被引动','遇到关键文书或升学，提示把材料自己做扎实','把结论说成文书线顺不顺，不断定具体学历高度'],
 enStep:["Confirm which star sits in the Parents Palace and whether it carries Hua Ke","Read same-palace and triple-direction assistants to judge smooth versus costly paperwork","Read whether elder and superior relations help or pressure","Layer decade and year limits to see when exams, certificates or contracts activate","For key documents or schooling, prompt solid preparation on your own","State whether the paperwork line flows, not a fixed degree level"],
 cnMis:['见父母宫化科就断定一定高学历、名校','把科当成不用努力也能过的保送','只看父母宫不看三方，忽略文书线的实际耗损'],
 enMis:["Declaring an elite degree on sight of parental Hua Ke","Treating Ke as a free pass without effort","Reading only the Parents Palace while ignoring triple-direction drains on paperwork"],
 cnClose:'父母宫的化科是一条「文书有人帮、遇事有体面」的线。它给你带路的人，不替你走路；真要考试、签文件，材料还得自己一份一份做扎实。',
 enClose:"Hua Ke in the Parents Palace is a line where paperwork has help and dignity. It gives you guides but does not walk for you; for exams and contracts, you still prepare each document yourself."},

{cat:'sihua',slug:'ziwei-wenchang-huake-2026-hetong',focus:'文昌化科2026合同',focusEn:'Wen Chang Hua Ke in 2026 and contracts',
 cnT:'紫微斗数2026丙午年文昌化科：流年文书合同，顺水但要看清条款',
 enT:'Wen Chang Hua Ke in the 2026 Bing-Wu Year: Paperwork and Contracts Flow Easier, But Read the Clauses',
 cnD:'2026丙午年流年四化为天同化禄、天机化权、文昌化科、廉贞化忌；文昌化科主文书、合同、签约类事务较有体面与缓冲。但科只是顺缘，签约仍以专业律师、正规途径和书面合同为准，不能凭流年顺遂就放松审查。',
 enD:"The 2026 Bing-Wu year's transformations are Tian Tong Lu, Tian Ji Quan, Wen Chang Ke and Lian Zhen Ji. Wen Chang Hua Ke makes paperwork, contracts and signing flow with more dignity and cushion, but Ke is only easy rapport; signing still relies on professional lawyers, formal channels and written contracts, and you must not slacken review just because the year feels smooth.",
 cnL:'2026年有人一看到文昌化科，就觉得今年签合同肯定顺，随便落笔。可流年给的是文书这条线的气氛，不是替你审条款的律师。',
 enL:"In 2026 people see Wen Chang Hua Ke and assume contracts will surely go smoothly, signing lightly. The yearly star sets the atmosphere of the paperwork line, not a lawyer who reviews the clauses for you.",
 cnA:'这个问题到底在问什么：2026文昌化科，说的是这一年里文书、合同、证书、协议类事务整体较容易谈成、较有面子；它不替代法律审查，也不保证每份合同都没有坑。',
 enA:"What the question really asks: 2026 Wen Chang Hua Ke means paperwork, contracts, certificates and agreements are generally easier to close and more presentable that year; it does not replace legal review or guarantee every contract is pit-free.",
 cnLog:['2026为丙午年，流年四固定为天同化禄、天机化权、文昌化科、廉贞化忌。','文昌主文书、笔墨、合同与正式文件，化科加持，使签约、申报、文书类事务较易体面推进。','同一年廉贞化忌，提示人际、感情与规则层面仍有牵挂，文书再顺也不能掉以轻心。','科带来的是顺缘与体面，不是免责；条款、违约责任、付款节奏仍须逐字看清。'],
 enLog:["The 2026 Bing-Wu year has fixed yearly transformations: Tian Tong Lu, Tian Ji Quan, Wen Chang Ke and Lian Zhen Ji.","Wen Chang governs writing, paperwork, contracts and formal files; with Hua Ke, signing, filing and documents tend to move with dignity.","The same year carries Lian Zhen Ji, hinting at attachment in relationships and rules, so smooth paperwork is no reason to lower guard.","Ke brings ease and face, not exemption; terms, liability and payment schedules still must be read word by word."],
 cnStep:['先确认2026流年文昌化科落到本命哪一宫','看这一宫涉及的是哪类文书：劳动、合作、买卖还是证书','叠看同宫廉贞化忌引动的是哪类人际或规则课题','签约前把合同正文、附件、违约责任逐条过一遍','大额或长期合同，委托专业律师过目并走正规途径','把流年顺缘当作谈判气氛，不当作免审通行证'],
 enStep:["First locate where 2026 Wen Chang Hua Ke lands in your natal palaces","See which kind of paperwork it touches: employment, partnership, sale or certificate","Layer Lian Zhen Ji that year to find which relationship or rule topic it activates","Before signing, read the main text, annexes and liability clauses line by line","For large or long contracts, engage a professional lawyer and use formal channels","Treat yearly ease as negotiation atmosphere, not a review-free pass"],
 cnMis:['见文昌化科就认为今年签约必无风险','因为流年顺遂就跳过律师审查直接落笔','把科当成口头承诺也算数，不坚持书面合同'],
 enMis:["Reading Wen Chang Ke as guaranteeing risk-free signing","Skipping lawyer review because the year feels smooth","Treating Ke as making verbal promises binding without a written contract"],
 cnClose:'2026文昌化科，是给文书合同这条线加了一点顺风。风再顺，合同也要逐字看、律师也要请、纸也要落定——以专业律师和正规途径为准，流年只负责告诉你今年适合谈，不负责替你兜底。',
 enClose:"2026 Wen Chang Hua Ke adds a tailwind to paperwork and contracts. However favorable the wind, read every clause, hire the lawyer and put it in writing; rely on professional lawyers and formal channels. The yearly star only says this year is good to talk, not that it covers you."},

{cat:'geju',slug:'ziwei-mingzhu-chuhai-ge',focus:'明珠出海格',focusEn:'the Bright Pearl at Sea pattern',
 cnT:'紫微斗数明珠出海格：成格、破格与别只看到贵气',
 enT:'The Bright Pearl at Sea Pattern: Conditions to Form, Ways It Breaks, and Why Not to Chase Only the Glory',
 cnD:'明珠出海格指紫微、天府一类星曜在特定宫位与左辅右弼等会照下形成的格局，传统主晚发、靠积累而出海见光。读格局先看成格条件、再看破格因素，不能一见星群就断必大富大贵。',
 enD:"The Bright Pearl at Sea is a pattern in which stars such as Zi Wei and Tian Fu in specific palaces meet assistants like Zuo Fu and You Bi, traditionally suggesting later blooming through accumulation. Read the forming conditions first, then the breaking factors; do not call certain wealth or glory merely because a star cluster appears.",
 cnL:'有人一看到自己盘上紫府加左右，就兴奋地说自己是明珠出海格。可格局不是凑几颗星就成立，条件不齐，更像是长得像而已。',
 enL:"Seeing Zi Wei, Tian Fu and the assistants on their chart, people excitedly call it the Bright Pearl at Sea. But a pattern is not formed by clustering a few stars; without full conditions, it only looks the part.",
 cnA:'这个问题到底在问什么：明珠出海格要回答的是哪几颗星在哪个宫位、被哪些辅星会照，才算真正成格；以及见了煞忌冲照，又是在哪个环节破了格。',
 enA:"What the question really asks: which stars in which palaces, met by which assistants, truly form the pattern, and where clash or Ji breaks it when present.",
 cnLog:['明珠出海格的核心是紫府一类主星落于特定宫位，又得左辅、右弼等辅星会照，比喻明珠从水中浮出、逐渐见光。','传统看法多主晚发：早年积累、中年后渐渐打开舞台，不是少年成名的快格。','成格讲究星群位置与会照齐全，缺一两位辅星或位置偏移，格局成色就要打折。','破格看煞忌冲照：擎羊、陀罗、化忌等冲破会照时，明珠易被浊水掩住，发得迟且反复。'],
 enLog:["The core is main stars like Zi Wei and Tian Fu in specific palaces, met by assistants such as Zuo Fu and You Bi, likening a pearl rising from water to light.","Traditionally it means later blooming: early accumulation, the stage widening in midlife, not a quick youthful rise.","Formation depends on star placement and complete assistant meetings; missing one or two, or shifted placement, discounts the grade.","Breakage comes from clash and Ji: when Qing Yang, Tuo Luo or Hua Ji strike the meeting, the pearl is muddied, blooming late and repeatedly."],
 cnStep:['先确认紫府类主星落在命宫或相关宫位','数清左辅、右弼等辅星是否确实会照，位置对不对','看有没有煞星或化忌冲破这条会照线','判断格局是成格、半成还是形似而已','结合大限，看这颗明珠大概在哪一步才「出海」','把结论写成条件与时机，不断定必大富大贵'],
 enStep:["First confirm main stars like Zi Wei and Tian Fu in the Life or relevant palace","Count whether assistants like Zuo Fu and You Bi truly meet, and in the right positions","See whether any malefic or Hua Ji strikes that meeting line","Judge whether the pattern is fully formed, half-formed or merely similar","Layer decade limits to see roughly when the pearl rises to sea","Write the conclusion as conditions and timing, not certain wealth or glory"],
 cnMis:['见紫府加几颗辅星就直接认成格','只看成格喜悦，不看煞忌破格','把晚发格读成少年得志，时间预期错位'],
 enMis:["Calling the pattern formed on sight of Zi Wei, Tian Fu and a few assistants","Reading only the joy of formation and ignoring malefic and Ji breakage","Reading a late-blooming pattern as youthful success, mismatching the timing"],
 cnClose:'明珠出海格讲的是慢慢从水里浮出来的光。先数清成格条件、看破在哪一环，再决定这颗明珠大概什么时候见光——它给你节奏，不替你保证结果。',
 enClose:"The Bright Pearl at Sea is about light slowly rising out of water. First count the forming conditions and find where it breaks, then estimate roughly when the pearl sees light; it gives you rhythm, not a guaranteed result."},

{cat:'geju',slug:'ziwei-sanqi-jiahui-zhenjiabian',focus:'三奇佳会真假辨',focusEn:'distinguishing true and false Three Wonders pattern',
 cnT:'紫微斗数三奇佳会格：化禄化权化科会齐，也要辨真假',
 enT:'The Three Wonders Pattern: When Lu, Quan and Ke Meet, Still Distinguish True From False',
 cnD:'三奇佳会格指化禄、化权、化科三奇会照于命宫或三方，传统主人缘与做事体面兼备。但三奇齐见未必都成真格，落宫错位、被煞忌冲破，都可能只是形似，要先辨真假再谈成色。',
 enD:"The Three Wonders pattern is when Hua Lu, Hua Quan and Hua Ke meet on the Life Palace or its triple-direction, traditionally suggesting both rapport and dignified execution. But three wonders together do not automatically make a true pattern; misplaced palaces or clash and Ji may leave it looking only similar. Tell true from false before grading.",
 cnL:'很多人盘上一看禄权科都在，就自称三奇佳会。可三奇到底会照在谁身上、有没有被冲破，决定它是真有这回事，还是凑了个热闹。',
 enL:"Many see Lu, Quan and Ke on their chart and claim the Three Wonders. But which palace they meet on and whether they are struck decides whether it is real or merely a gathering.",
 cnA:'这个问题到底在问什么：三奇佳会要分清三件事——三奇是否真的会照到命宫或其三方、落宫是否有力、有没有煞忌把这股体面冲散。三条都立，才算真格。',
 enA:"What the question really asks: three things must be settled for the Three Wonders—whether Lu, Quan and Ke truly meet on the Life or its triple-direction, whether the palaces they land in are strong, and whether malefic or Ji scatters that dignity. All three hold for a true pattern.",
 cnLog:['三奇指化禄、化权、化科，三者会照命宫或三方，被视为资源、主动权与名声同时在线。','真格要求三奇落宫有力、彼此呼应，而不是各自孤立地散在全盘。','若三奇落宫衰弱、被擎羊陀罗化忌冲破，或会照不到命宫，多为形似而非真格。','大限流年也可临时凑出三奇会照，那是某段时间的顺局，不等于本命真格。'],
 enLog:["The three wonders are Hua Lu, Hua Quan and Hua Ke; when they meet on the Life or its triple-direction, resources, initiative and reputation are said to align.","A true pattern requires the three to land in strong palaces and echo each other, not to sit scattered and isolated.","If they land weakly, are struck by Qing Yang, Tuo Luo or Hua Ji, or fail to meet the Life palace, it is mostly similar rather than true.","Decade or yearly limits can temporarily assemble the three wonders, a good stretch, not a natal true pattern."],
 cnStep:['先把生年化禄、化权、化科各自的落宫标出来','看三者是否会照到命宫或命宫三方，而不是各据一方','看三奇所落宫位本身庙旺还是落陷','检查擎羊、陀罗、化忌是否冲破会照线','区分这是本命三奇，还是大限流年临时凑出的顺局','按真假与成色给结论，不一见三奇就断大成'],
 enStep:["First mark the natal Lu, Quan and Ke and their palaces","See whether the three meet on the Life or its triple-direction rather than sitting apart","Check whether the palaces they land in are bright or fallen","Inspect whether Qing Yang, Tuo Luo or Hua Ji strike the meeting","Distinguish a natal three wonders from a temporary decade-yearly smooth stretch","Grade by true-or-false and quality; do not declare great success on sight"],
 cnMis:['只要盘上出现禄权科就直接认定三奇佳会','只数三奇数量，不看落宫强弱与是否会照','把大限流年凑出的三奇当成本命真格一辈子受用'],
 enMis:["Declaring the Three Wonders as soon as Lu, Quan and Ke appear","Counting the three without checking palace strength or actual meeting","Treating a decade-yearly assembled three wonders as a lifelong natal pattern"],
 cnClose:'三奇佳会听着热闹，真假要一条一条对：会照到命宫没有、落宫有力没有、被冲破没有。真格是资源、主动权和名声同时在线；形似，就别替自己加戏。',
 enClose:"The Three Wonders sound impressive, but true or false is checked line by line: do they meet the Life palace, are their palaces strong, are they struck? A true pattern aligns resources, initiative and reputation; if it only looks similar, do not overstate it."},

{cat:'geju',slug:'ziwei-lingtan-ge-tufa',focus:'铃贪格突发',focusEn:'the Bell-Star-Tan-Lang pattern and sudden events',
 cnT:'紫微斗数铃星贪狼格：突发起来的事，也会突然收',
 enT:'The Bell-Star and Tan Lang Pattern: Sudden Rises Can Also Suddenly Pull Back',
 cnD:'铃贪格指铃星与贪狼同宫或会照，传统主突发、爆发式的进展，多与偏门、投机、非常规路径有关。读这一格要看成格条件与煞忌配合，突发不等于长稳，来得快去得也快，不能据此押上全部身家。',
 enD:"The Bell-Star and Tan Lang pattern is when Ling Xing and Tan Lang share or meet a palace, traditionally suggesting sudden, explosive progress, often linked to unconventional or speculative paths. Read its forming conditions and malefic-Ji interaction; a burst is not steady longevity. It arrives fast and may leave fast, so you should not stake everything on it.",
 cnL:'有人盘上铃星贪狼同宫，就盼着一夜翻盘。可这一格的关键词是「突发」——它能让你忽然起来，也能让同样的速度把事收走。',
 enL:"With Ling Xing and Tan Lang together, people hope for an overnight turnaround. The pattern's key word is sudden: it can lift you abruptly, and pull things away just as abruptly.",
 cnA:'这个问题到底在问什么：铃贪格问的是哪类机会容易以爆发式出现、靠的是什么非常规路径；它不是财富保证书，而是一段高波动、快起快落的节奏提示。',
 enA:"What the question really asks: which opportunities tend to arrive explosively and through what unconventional paths. It is not a wealth guarantee but a warning of a high-volatility, fast-up-fast-down rhythm.",
 cnLog:['贪狼主欲望、才艺、交际与偏门机会，铃星主暗耗、迟发的张力，两星相逢易激起爆发式事件。','传统多主突发、横发，常与投机、副业、非常规渠道相关，起落速度都快。','成格要看两星是否有力会照、三方有无吉辅稳住，否则只是不安稳的躁动。','若逢化忌、地空地劫冲破，突发之后容易突发地赔回去，不能当成长期饭票。'],
 enLog:["Tan Lang governs desire, talent, networking and unconventional chances; Ling Xing governs hidden strain and delayed tension; together they easily stir explosive events.","Traditionally this means sudden rise or windfall, often through speculation, side ventures or unusual channels, with fast rises and fast falls.","Formation depends on the two stars meeting strongly and helpful assistants in the triple-direction stabilizing them; otherwise it is merely restless volatility.","If Hua Ji, Di Kong or Di Jie strike, the sudden rise may suddenly be paid back; it cannot be treated as a long-term income."],
 cnStep:['先确认铃星与贪狼是否同宫或紧密会照','看两星本身庙旺还是落陷，判断这股爆发力的质量','读三方辅曜是稳住这股劲，还是再加躁动','检查化忌、空劫是否冲破，评估突发后会不会回吐','叠大限流年，找哪段时间这类爆发被引动','把结论写成高波动节奏提示，不鼓励押注投机'],
 enStep:["First confirm whether Ling Xing and Tan Lang share a palace or meet closely","Check whether both stars are bright or fallen to gauge the burst's quality","Read triple-direction assistants as stabilizing the energy or adding restlessness","Check whether Hua Ji, Di Kong or Di Jie strike, judging whether gains give back","Layer decade and year limits to find when such bursts activate","State the conclusion as a high-volatility rhythm warning, not an encouragement to speculate"],
 cnMis:['见铃贪就断定必暴发、一夜翻身','把突发横财当成可持续收入去规划生活','只看成格的爆发，不看破格后的快速回吐'],
 enMis:["Declaring certain windfall and overnight turnaround on sight of Ling-Tan","Planning life around a sudden gain as if it were steady income","Reading only the burst of formation without the fast give-back when broken"],
 cnClose:'铃贪格像一阵急风：能把你一下子推起来，也能一下子把东西卷走。它适合提示你哪段路波动大、别上头，不适合当成梭哈的理由——财来财去之间，守住本金才是正经。',
 enClose:"The Ling-Tan pattern is like a gust: it can push you up fast and sweep things away just as fast. It is a warning of a volatile stretch to stay sober through, not a reason to go all in; as money comes and goes, keeping the principal is the serious part."}
];
