// 2026-09-28 批次 第4组：辅星煞星/宫位现实场景 8篇
module.exports=[
{cat:'fuzhu',slug:'ziwei-qingyang-caibo-xiaofei',focus:'擎羊财帛消费',focusEn:'Qing Yang in the Wealth Palace and spending',
 cnT:'紫微斗数擎羊坐财帛宫：花钱冲动，也是逼你赚钱的磨刀石',
 enT:'Qing Yang in the Wealth Palace in Zi Wei Dou Shu: Impulse Spending, but Also a Whetstone That Forces You to Earn',
 cnD:'擎羊是带刀的煞星，落财帛宫常表现为花钱干脆、为面子或气头上一掷千金，也主求财时硬碰硬、敢拼敢争。它不是穷命，而是把钱的进出门都开得很响，关键看有没有禄存、化科或强主星把这把刀收进鞘里。',
 enD:"Qing Yang is a blade-bearing malefic. In the Wealth Palace it often shows as decisive spending, splurging for face or on impulse, and as a tough, head-to-head way of pursuing money. It is not a poverty sign; it makes both the entry and exit of money loud. The key is whether Lu Cun, Hua Ke or a strong ruling star sheathes the blade.",
 cnL:'很多人一看到擎羊坐财帛就慌，觉得这辈子留不住钱。其实擎羊在财帛，更像你手里握着一把快刀：切菜很快，剁到手指也疼。它逼你对钱有动作，而不是让你没饭吃。',
 enL:"Many panic at the sight of Qing Yang in the Wealth Palace, assuming money will never stay. In fact Qing Yang there is like holding a sharp knife: it chops fast, but it also nicks the fingers. It forces you to act on money rather than leave you penniless.",
 cnA:'要回答两件事：擎羊在财帛到底怎么花钱、怎么赚钱，以及有没有办法把这股刚劲用到正地方。结论是它主「硬碰硬的财」与「没刹车的花」，化解靠的是给刀配鞘，不是把刀扔掉。',
 enA:"Two things must be answered: how Qing Yang in the Wealth Palace spends and earns, and whether that force can be put to good use. It governs hard-fought money and brake-less spending; the fix is to give the blade a sheath, not to throw it away.",
 cnLog:['擎羊属金，性刚、主决断与冲劲，落财帛时求财方式偏硬，敢压价、敢竞标、敢在竞争里抢单。','花钱端则表现为冲动、干脆、不爽就买，为面子或一口气花出去，事后才心疼。','煞星是磨刀石不是断头台：擎羊逼你对钱有动作、有压力，反而能把人逼成能扛事的赚钱者。','化解方向看有没有禄存同宫、化科会照，或紫微、天府、武曲这类强主星制住刀性，把刚劲变成专业与纪律。'],
 enLog:["Qing Yang belongs to metal, firm in nature, governing decisiveness and drive; in the Wealth Palace it pursues money the hard way, unafraid of bargaining, bidding or competing.","On the spending side it shows as impulse, instant buys, buying when irritated or for face, with regret coming later.","A malefic is a whetstone, not a guillotine: Qing Yang forces action and pressure on money and can push someone into becoming a high-capacity earner.","Remedy depends on Lu Cun in the same palace, Hua Ke in aspect, or strong rulers like Zi Wei, Tian Fu or Wu Qu taming the blade into discipline and expertise."],
 cnStep:['先看擎羊是独坐财帛，还是与禄存、化科同宫或会照','同宫有禄存，先记下这是刀有鞘、能赚能守的结构','看三方四正有没有强主星制化，把刚劲导向专业','在花钱端设硬规则，如大额消费放三天再决定','在赚钱端把冲劲用在竞争、谈单、开拓，而非赌气','若煞性过重、屡花屡悔，优先做预算与自动储蓄，不靠意志力硬扛'],
 enStep:["First see whether Qing Yang sits alone in Wealth or shares it with Lu Cun or Hua Ke","If Lu Cun is present, note that the blade has a sheath and money can be earned and kept","Check the triple direction for a strong ruler that channels firmness into expertise","Set a hard spending rule, such as waiting three days on any large purchase","Channel the drive into competition, negotiation and expansion rather than temper tantrums","If the malefic feels heavy, rely on budgets and automatic savings rather than willpower"],
 cnMis:['见擎羊坐财帛就断定破财命、一辈子留不住钱','认为煞星只能躲，不靠禄存化科或主星制化去化解','把花钱冲动全怪在星上，不做预算、不设冷静期'],
 enMis:["Reading Qing Yang in Wealth as a definite ruin and lifelong inability to save","Assuming a malefic can only be avoided instead of tamed by Lu Cun, Ke or a ruler","Blaming all impulse spending on the star while skipping budgets and cooling-off rules"],
 cnClose:'擎羊在财帛，是把快刀，不是一张催款单。把它的冲劲用在赚钱和谈单上，给花钱加一道冷静期，这把刀就能切菜而不剁手。',
 enClose:"Qing Yang in the Wealth Palace is a sharp knife, not a demand note. Put its drive into earning and negotiating, add a cooling-off period to spending, and the knife chops vegetables instead of fingers."},

{cat:'fuzhu',slug:'ziwei-tuoluo-guanlu-fanfu',focus:'陀罗官禄反复',focusEn:'Tuo Luo in the Career Palace and delays',
 cnT:'紫微斗数陀罗坐官禄宫：升得慢，但熬出来的位置稳',
 enT:'Tuo Luo in the Career Palace in Zi Wei Dou Shu: Slow to Rise, but the Position Endured Is Solid',
 cnD:'陀罗是原地打转的煞星，落官禄宫常表现为升迁拖延、项目反复、明明做得不错却总差一步。它不是事业失败，而是让你走得比别人慢、回头路多；熬得住的人，位置反而比一步登天的人坐得久。',
 enD:"Tuo Luo is a circling malefic. In the Career Palace it often shows as delayed promotion, looping projects, and coming close yet missing by a step. It is not career failure; it makes you walk slower and take detours. Those who endure end up holding positions longer than overnight successes.",
 cnL:'有人看自己官禄宫坐陀罗，心就凉了，觉得一辈子升不上去。可现实里很多坐陀罗的人，年轻时走得磕磕绊绊，中年以后反而一步一个脚印，坐得比谁都稳。',
 enL:"Someone seeing Tuo Luo in the Career Palace grows discouraged, assuming a lifetime of stalled promotion. Yet many with Tuo Luo there stumble in youth and, after middle age, climb step by step and hold steadier than anyone.",
 cnA:'要分清陀罗带来的是「停」还是「慢」。它主拖延、反复、绕圈，不是把你踢出局。化解方向是别和它比快，而是把慢变成打磨——考证、深耕、熬资历。',
 enA:"Distinguish whether Tuo Luo brings a stop or a slowdown. It governs delay, repetition and circling, not ejection. The remedy is not to race it but to turn slowness into polishing: certifications, depth and seniority.",
 cnLog:['陀罗属金，性沉、主拖延与纠缠，落官禄时项目容易反复改、升迁容易被压一年半载。','它和擎羊不一样：擎羊是一刀见血的快，陀罗是慢慢磨、绕来绕去的钝。','煞星是磨刀石不是断头台：反复改方案、熬资历，反而把专业磨得比别人细。','化解方向看有没有化科同宫会照，或天府、紫微、太阳这类主星把拖劲沉淀为长期主义，而非急着跳槽。'],
 enLog:["Tuo Luo belongs to metal, slow in nature, governing delay and entanglement; in career it shows as revised projects and promotions held back for a year or two.","It differs from Qing Yang: Qing Yang is a swift cut, while Tuo Luo is a slow, circling dull grind.","A malefic is a whetstone, not a guillotine: repeated revisions and seniority-polishing make expertise finer than others'.","Remedy depends on Hua Ke in aspect, or rulers like Tian Fu, Zi Wei or Tai Yang settling the delay into long-termism rather than rushed job-hopping."],
 cnStep:['先确认陀罗是独坐官禄，还是与化科、强主星同宫会照','把它带来的反复翻译成正常现象，不把拖延当失败','在慢周期里深耕一门手艺或考一张硬证书','重要项目预留返工时间，别卡着最后一刻交','跳槽要谨慎，陀罗格频繁换赛道会把反复放大','熬到资历与作品都在手上，位置自然坐稳'],
 enStep:["First see whether Tuo Luo sits alone in Career or shares it with Hua Ke or a strong ruler","Translate its repetition as normal, not as failure","During the slow cycle, deepen one craft or earn a hard certification","Buffer rework time on key projects; never submit at the last minute","Be cautious about job-hopping, since a Tuo Luo chart magnifies repetition across switches","Once credentials and work are in hand, the position settles on its own"],
 cnMis:['见陀罗坐官禄就断定事业无成、注定被压一辈子','把反复改方案、晚一年升迁当成自己能力不行','受不了慢，用频繁跳槽去绕开陀罗，结果越跳越绕'],
 enMis:["Reading Tuo Luo in Career as lifelong failure and permanent suppression","Treating repeated revisions or a delayed promotion as proof of incompetence","Unable to tolerate slowness and job-hopping to dodge it, only circling more"],
 cnClose:'陀罗在官禄，是让你走得慢，不是让你走不出去。把慢当成打磨，把反复当成练兵，熬出来的位置往往比谁都稳。',
 enClose:"Tuo Luo in the Career Palace makes you walk slowly, not stop. Treat slowness as polishing and repetition as training; the position you endure tends to outlast the rest."},

{cat:'fuzhu',slug:'ziwei-huoxing-qianyi-gong-tufa',focus:'火星迁移宫突发',focusEn:'Huo Xing in the Travel Palace and sudden events',
 cnT:'紫微斗数火星坐迁移宫：出门在外，急事也多机会也多',
 enT:'Huo Xing in the Travel Palace in Zi Wei Dou Shu: Away from Home, Sudden Urgencies and Sudden Opportunities Alike',
 cnD:'火星是爆发型煞星，落迁移宫主出门、远行、外地发展时节奏快、变化急，容易遇到突发状况，也容易撞上意料之外的机会。它主「动中有事」，不是不能出门，而是出门前要留缓冲、留预案。',
 enD:"Huo Xing is an explosive malefic. In the Travel Palace it governs fast pace and sudden changes when away, traveling or developing elsewhere: unexpected crises, but also unforeseen opportunities. It means things happen on the move, not that you must stay home; rather, leave buffers and contingency plans before going.",
 cnL:'有人一听迁移宫坐火星，就怕出门出事，连差都不敢出。可现实里，很多常年跑外地、跑现场的人，恰恰是这种盘——急事多，但机会也常在路上冒出来。',
 enL:"Hearing Huo Xing in the Travel Palace, some fear going out and refuse business trips. In reality, many who travel constantly for fieldwork carry exactly this chart: more urgencies, but opportunities that also surface on the road.",
 cnA:'要回答火星在迁移到底是「凶」还是「急」。它主突发、快节奏、火气，落在外宫意味着人生很多事是在动中发生的。化解靠的是预案和冷静，不是不出门。',
 enA:"Decide whether Huo Xing in Travel means misfortune or urgency. It governs suddenness, fast pace and heat; sitting in the outer palace, it means much of life happens on the move. The remedy is contingency and calm, not staying home.",
 cnLog:['火星属火，性急、主突发与燃烧，落迁移时出门行程容易临时变、赶时间、起口角。','它同时带爆发力：外地机会、突发订单、赶出来的项目，也常在动中撞到。','煞星是磨刀石不是断头台：突发状况逼着人练反应和应急能力，不是把人挡在家门。','化解方向看有没有禄存、化科会照，或太阳、紫微这类主星把火气导向执行力，出行则留弹性时间、买好保险、备好备用方案。'],
 enLog:["Huo Xing belongs to fire, quick-tempered, governing suddenness and combustion; in Travel it shows as changed itineraries, time pressure and arguments while away.","It also carries explosive force: out-of-town opportunities, sudden orders and rushed projects also surface on the move.","A malefic is a whetstone, not a guillotine: sudden events train reaction and emergency skills rather than keeping you home.","Remedy depends on Lu Cun, Hua Ke in aspect, or rulers like Tai Yang and Zi Wei directing heat into execution; practically, leave buffer time, insure trips and prepare backups."],
 cnStep:['先确认火星是独坐迁移，还是与禄存、化科、强主星同宫会照','把出行计划留出弹性，关键行程不压死时间','重要差旅买好可改签与保险，预案先写在纸上','在外遇突发先停三秒再反应，不当场发火谈事','把外地的突发机会当正事接，别因为怕乱就全推掉','回来后复盘哪类突发最常出现，下次提前堵'],
 enStep:["First see whether Huo Xing sits alone in Travel or shares it with Lu Cun, Ke or a strong ruler","Build slack into travel plans; never pack key trips back-to-back","Book changeable tickets and insurance for major trips; write the contingency first","When a crisis hits away, pause three seconds before reacting; never negotiate in anger","Take sudden out-of-town opportunities seriously instead of pushing them all away","After returning, review which surprises recur and plug them next time"],
 cnMis:['见火星坐迁移就断定出门必凶、从此不敢远行','把所有突发都当成灾，看不出动中也藏着机会','出行不留缓冲、不买保险、不备预案，硬把急事变事故'],
 enMis:["Reading Huo Xing in Travel as certain disaster and swearing off all travel","Treating every surprise as misfortune while missing the opportunities on the move","Traveling without buffer, insurance or backups and turning urgency into an accident"],
 cnClose:'火星在迁移，是让路上多变数，不是不让你出门。留好缓冲、备好预案，那些突发急事反而能练出别人没有的反应力。',
 enClose:"Huo Xing in the Travel Palace makes the road more volatile; it does not forbid travel. With buffers and contingencies, those sudden urgencies build a reflex others lack."},

{cat:'fuzhu',slug:'ziwei-lingxing-fuqi-anji',focus:'铃星夫妻暗忌',focusEn:'Ling Xing in the Spouse Palace and hidden friction',
 cnT:'紫微斗数铃星坐夫妻宫：不是大吵大闹，是心里那点疙瘩',
 enT:'Ling Xing in the Spouse Palace in Zi Wei Dou Shu: Not Loud Fights, but the Quiet Grudge Inside',
 cnD:'铃星是闷烧型煞星，落夫妻宫很少表现为拍桌子，更多是冷战、翻旧账、心里记着不说的那种别扭。它主暗耗与积怨，不是婚姻破裂的判决，关键看有没有化科或吉星把话说开。',
 enD:"Ling Xing is a smoldering malefic. In the Spouse Palace it rarely shows as slammed doors; more often it is the cold war, the dredged-up old score, the grudge kept unsaid. It governs quiet erosion and accumulated resentment, not a verdict of divorce, and hinges on whether Hua Ke or auspicious stars help the couple talk it through.",
 cnL:'有人看夫妻宫坐铃星就吓一跳，以为婚姻要出大事。其实铃星这颗星不响，它是小火慢炖——表面风平浪静，底下却在一点一点冒烟。',
 enL:"Some panic at Ling Xing in the Spouse Palace, assuming the marriage is doomed. But Ling Xing makes no noise; it is a slow simmer—calm on the surface, smoke curling underneath.",
 cnA:'要分清铃星和擎羊火星的区别：后两个是明火，铃星是暗火。它带来的是没说出口的委屈、翻来覆去的旧事。化解不是压下去，而是把那点疙瘩摊开说。',
 enA:"Distinguish Ling Xing from Qing Yang and Huo Xing: the latter two are open flames, while Ling Xing is a hidden fire. It brings unspoken grievances and rerun old stories. The remedy is not to suppress but to lay that quiet friction out in words.",
 cnLog:['铃星属火，性闷、主暗耗与阴损，落夫妻宫时矛盾往往不正面吵，而是冷战、记账、翻旧账。','它不像擎羊火星当场爆发，而是把不满压着，几年后一件小事点着。','煞星是磨刀石不是断头台：这种钝感反而逼着人学沟通，不能靠吵完就算。','化解方向看有没有化科会照、天相左辅右弼这类吉星，或天府主星把闷气转成好好说话；现实里靠定期沟通、写下来、必要时找婚姻咨询。'],
 enLog:["Ling Xing belongs to fire, smoldering, governing quiet drain and hidden hurt; in the Spouse Palace conflicts rarely erupt openly but show as cold war, score-keeping and old stories.","Unlike Qing Yang or Huo Xing, it suppresses grievance and ignites years later over a small thing.","A malefic is a whetstone, not a guillotine: this dull friction forces the couple to learn communication instead of fighting and forgetting.","Remedy depends on Hua Ke, auspicious stars like Tian Xiang or assistants, or a Tian Fu ruler turning sullenness into calm talk; practically, regular check-ins, written notes, and counseling when needed."],
 cnStep:['先确认铃星是独坐夫妻，还是与化科、吉星、强主星同宫会照','把自己心里那句「不说也罢」找出来，别让它记账','选平静的时机，不翻旧账地说当下的感受','约定一个定期沟通节奏，比如每月坐下来聊一次','旧事已经过去的，明确说翻篇，不许反复拿出来','长期冷战无解时，优先寻求正规婚姻咨询，不靠硬撑'],
 enStep:["First see whether Ling Xing sits alone in Spouse or shares it with Hua Ke, auspicious stars or a strong ruler","Find the thing you told yourself not to mention; stop letting it be scored","Pick a calm moment and speak current feelings without dredging the past","Set a regular rhythm, such as sitting down once a month","For matters settled, explicitly say they are closed and stop rerunning them","If a long cold war has no way out, prioritize formal couples counseling rather than endurance"],
 cnMis:['见铃星坐夫妻就断定婚姻必离、配偶一定不好','把冷战当平静，以为不吵架就是感情好','靠忍和压去化解，结果委屈越积越多，一件小事总爆发'],
 enMis:["Reading Ling Xing in Spouse as certain divorce or a bad spouse","Mistaking the cold war for peace, assuming no quarrels means a good marriage","Relying on patience and suppression, so grievances pile up until a small thing detonates"],
 cnClose:'铃星在夫妻，是心里那点没说出口的烟。别等它烧成明火才处理，定期把话摊开，那点疙瘩也就闷不住你了。',
 enClose:"Ling Xing in the Spouse Palace is the smoke of what was left unsaid. Do not wait for it to flare into open fire; talk it through on a regular basis, and that quiet grudge loses its grip."},

{cat:'fuzhu',slug:'ziwei-feilian-xing-shifei-yingxiang',focus:'蜚廉星是非影响',focusEn:'Fei Lian star and its impact on disputes',
 cnT:'紫微斗数蜚廉星：一颗小星，专管那种说不出口的是非',
 enT:'Fei Lian in Zi Wei Dou Shu: A Minor Star That Runs the Quiet, Hard-to-Prove Gossip',
 cnD:'蜚廉是颗小星，不像擎羊火星那么响，它主暗中小人、口舌流言、莫名其妙被捎带。它落在哪一宫，哪方面就容易有说不清的闲话；不是大祸，却最磨人，应对靠的是行得正、少掺和、留证据。',
 enD:"Fei Lian is a minor star, nowhere as loud as Qing Yang or Huo Xing. It governs hidden petty people, gossip, and being dragged into things you never started. Wherever it lands, that area breeds hard-to-explain chatter; it is not a catastrophe, but it wears you out. The response is to act upright, stay out of other people's business and keep records.",
 cnL:'有人查自己盘，看到一堆大星都挺好，偏偏有颗叫蜚廉的，就问这是什么。其实它是颗小星，管的不是大事，是那种「明明没我事，怎么闲话传到我头上」的小别扭。',
 enL:"Someone checks their chart, finds the major stars all fine, spots a star called Fei Lian, and asks what it is. It is a minor star that does not run big events; it runs the small irritation of gossip reaching you though you had nothing to do with it.",
 cnA:'要讲清蜚廉在哪种宫位会怎么咬人。它落在命宫、迁移是自己易招口舌；落在兄弟、仆役是从同辈朋友那里捎来闲话；落在官禄是职场里被人背后议论。应对都一样：不接招、留书面、别站队。',
 enA:"Explain how Fei Lian bites in each palace. In the Life or Travel palace it attracts gossip to you; in the Siblings or Servants palace it brings chatter from peers and friends; in Career it means behind-the-back talk at work. The response is the same: do not take the bait, keep things in writing, and do not take sides.",
 cnLog:['蜚廉属小星，主口舌、小人、暗地流言，杀伤力有限，但最烦人的是说不清、对不上号。','它的表现不是正面冲突，而是传话、误会、被捎带、莫名其妙背锅。','蜚廉不主大祸，主耗：让你心情不好、解释不清、做事被拖慢。','应对方向是行得正、少掺和别人的是非、重要沟通留书面记录，不加入站队。'],
 enLog:["Fei Lian is a minor star, governing gossip, petty people and hidden rumors; its harm is limited, yet the annoying part is that it is hard to explain and hard to trace.","Its form is not open conflict but passing messages, misunderstandings, being dragged in and inexplicably blamed.","Fei Lian does not run catastrophe; it runs drain, souring mood, defying explanation and slowing work.","The response is to act upright, stay out of others' disputes, keep important communication in writing, and never take sides."],
 cnStep:['先确认蜚廉落在哪个宫，判断是非从哪个领域来','落命迁：自己言行端正，不在公开场合评价他人','落兄弟仆役：少掺和朋友同辈之间的传话与八卦','落官禄：重要工作沟通走邮件、文档，留痕备查','遇到流言不急于到处解释，越解释越像此地无银','把精力放回做事本身，时间长了闲话自己散'],
 enStep:["First locate which palace Fei Lian sits in, to see which area the gossip comes from","In Life or Travel: keep your conduct upright and do not judge others in public","In Siblings or Servants: stay out of peer gossip and second-hand messaging","In Career: route key work communication through email and documents for the record","When a rumor hits, do not rush to explain everywhere; over-explaining looks guilty","Put energy back into the work itself; given time, the chatter fades on its own"],
 cnMis:['把蜚廉当成大凶星，一见就觉得要倒大霉','到处找人解释自己，结果越描越黑','跟着别人一起议论是非，结果蜚廉把你也捎进去'],
 enMis:["Treating Fei Lian as a major malefic and expecting disaster at first sight","Running around explaining oneself and only making it darker","Joining others in gossip, so Fei Lian drags you into it as well"],
 cnClose:'蜚廉是颗磨人的小星，不是要你命的大煞。行得正、嘴把门、重要事留字据，那些说不清的闲话，过一阵自己就散了。',
 enClose:"Fei Lian is a wearing minor star, not a life-threatening malefic. Act upright, guard your tongue, keep key matters in writing, and the inexplicable chatter fades after a while."},

{cat:'gongwei',slug:'ziwei-xiongdi-gong-muqin-caiyuan',focus:'兄弟宫母亲财源',focusEn:'the Siblings Palace, mother and income reserves',
 cnT:'紫微斗数兄弟宫不只看兄弟：还管母亲和你的现金储备',
 enT:'The Siblings Palace in Zi Wei Dou Shu Is Not Just About Siblings: It Also Rules Mother and Your Cash Reserves',
 cnD:'兄弟宫在现实里对应三块：同辈手足关系、与母亲的缘分、以及手里能随时动用的现金储备。它不是只用来断「有几个兄弟」的，财帛看收入，兄弟宫看你口袋里那笔活钱厚不厚。',
 enD:"In practice the Siblings Palace maps onto three things: relationships with siblings and peers, the bond with your mother, and the liquid cash you can draw on. It is not only for counting brothers; while Wealth Palace reads income, the Siblings Palace reads how thick your ready cash is.",
 cnL:'很多人一听到兄弟宫，就以为是查自己有几个兄弟姐妹。其实这一宫在紫微里身兼三职：手足、母亲、还有你平时能动用的活钱。',
 enL:"Many hear Siblings Palace and think it counts brothers and sisters. In Zi Wei this palace holds three jobs: siblings, mother, and the liquid cash you can move day to day.",
 cnA:'要把兄弟宫的三条现实线分清：手足关系是人和，母亲线看与长辈的缘分与照护，财源线看现金流储备。三条线共用一个宫位，星曜好坏会同时影响这三处。',
 enA:"Separate the three real lines of the Siblings Palace: siblings are human bonds, the mother line is the tie with and care for elders, and the wealth line is cash reserves. All three share one palace, so a star's quality touches all three at once.",
 cnLog:['兄弟宫本义看手足关系，现实里也延伸到同事、同学、合伙人这一辈同辈人。','它在六亲里对应母亲，盘上兄弟宫好坏，常反映与母亲的缘分、照护与互动方式。','它在财务上对应现金流储备，也就是工资到手后能随时挪动的活钱，区别于田宅管的不动产。','兄弟宫坐煞或化忌，要同时留心同辈是非、母亲健康照护与现金周转这三件事。'],
 enLog:["The Siblings Palace originally reads sibling ties, and in practice extends to peers such as colleagues, classmates and partners.","Among kin it corresponds to the mother; its quality often reflects the bond, care and interaction with one's mother.","Financially it corresponds to liquid reserves, the ready cash after salary, distinct from the fixed assets ruled by the Property Palace.","When it holds a malefic or Hua Ji, watch three things at once: peer disputes, mother's health and care, and cash flow."],
 cnStep:['先找到自己兄弟宫的位置和里面坐的星曜','看手足同辈线：与兄弟姐妹、同事同学合不合','看母亲线：与母亲关系亲疏、近年照护是否吃力','看财源线：手里活钱够不够三到六个月周转','煞星或化忌坐守时，三条线一起排优先级','母亲健康相关只作倾向提醒，持续不适以正规就医为准'],
 enStep:["First locate your Siblings Palace and the stars in it","Read the sibling-peer line: how you get along with brothers, colleagues and classmates","Read the mother line: closeness to your mother and whether care has been heavy lately","Read the wealth line: whether ready cash covers three to six months of turnover","When a malefic or Hua Ji sits there, prioritize the three lines together","Mother's health is only a tendency reminder; persistent discomfort follows formal medical care"],
 cnMis:['把兄弟宫只当数兄弟姐妹的宫，忽略母亲与现金流','把兄弟宫煞星只当手足不和，看不出现金周转也紧','兄弟宫差就以为母亲一定出事，不下结论，只作倾向提醒'],
 enMis:["Using the Siblings Palace only to count siblings while missing mother and cash flow","Reading a malefic there as only sibling conflict while missing tight cash turnover","Declaring certain illness for the mother from a bad Siblings Palace; state it only as a tendency"],
 cnClose:'兄弟宫是个一身三职的宫：手足、母亲、活钱。把这三条线一起看，盘上那点变化才落得到你真实的生活里。',
 enClose:"The Siblings Palace wears three hats: siblings, mother, and ready cash. Read the three lines together, and what the chart changes actually lands in your real life."},

{cat:'gongwei',slug:'ziwei-tianzhai-gong-jiaju-buju',focus:'田宅宫家居布局',focusEn:'the Property Palace and home layout',
 cnT:'紫微斗数田宅宫：看不动产，也看你家那个空间住得舒不舒服',
 enT:'The Property Palace in Zi Wei Dou Shu: Real Estate, and Whether Your Home Space Actually Feels Right',
 cnD:'田宅宫对应两类现实：一是房子、不动产、置业换房这类硬资产；二是你日常居住的那个空间本身——采光、动线、收拾得干不干净、住得舒不舒服。它不只是看有没有房，还看你把家过成了什么样。',
 enD:"The Property Palace maps onto two realities: hard assets such as houses and property, buying or moving, and the living space itself—light, circulation, tidiness, whether the home actually feels good. It is not only about owning a house; it is about how you live in it.",
 cnL:'有人查田宅宫，只关心「我这辈子买不买得起房」。其实这一宫还管你每天回到那个空间的感受：乱不乱、亮不亮、住进去心定不定。',
 enL:"Some read the Property Palace only to ask whether they can ever afford a house. But it also governs how you feel returning to that space every day: cluttered or calm, bright or dim, grounded or uneasy.",
 cnA:'要把田宅宫拆成两条线：不动产线看置业、换房、租金这类大事；家居线看采光、收纳、动线这些日常。前者几年动一次，后者每天都在影响你的状态。',
 enA:"Split the Property Palace into two lines: the property line reads buying, moving and rent, while the home line reads light, storage and circulation. The former moves once in years; the latter shapes your state every day.",
 cnLog:['田宅宫本义看不动产、置产、房屋买卖，现实里也包括租房稳定性与居住城市的选择。','它同时看居住空间的气场：采光好不好、收纳够不够、动线顺不顺、整洁与否。','田宅坐吉星，往往住得顺心、置业也顺；坐煞星，房子容易有小毛病、住得不踏实。','田宅的调整不靠改运，而靠真实装修、收纳、采光和定期收拾，这才是这一宫能落地的化解。'],
 enLog:["The Property Palace originally reads real estate, asset buying and housing deals, and in practice also rental stability and choice of city.","It also reads the atmosphere of the living space: light, storage, circulation and tidiness.","Auspicious stars there tend to mean comfortable living and smooth property deals; malefics mean small house problems and an uneasy stay.","Adjusting the Property Palace is not ritual but real renovation, storage, lighting and regular tidying—the practical remedy."],
 cnStep:['先找到田宅宫，分清这一年重点是置业还是居住体验','若在置业线，看当下适不适合换房、贷款压力多大','若在居住线，先看采光和动线这两件最影响感受的','再看收纳与整洁：堆出来的乱，比星曜更影响状态','田宅坐煞时，优先维修老房子的小毛病，别拖成大问题','把家收拾亮堂、动线顺了，这一宫的感受线就已经在好转'],
 enStep:["First locate the Property Palace and decide whether this year is about buying or about living quality","If on the property line, judge whether now fits a move and how heavy the loan pressure is","If on the home line, start with light and circulation, the two things that most affect feeling","Then look at storage and tidiness: clutter affects state more than any star","When a malefic sits there, fix the small house defects before they grow into big ones","Brighten and smooth the home and the feeling line of this palace already improves"],
 cnMis:['把田宅宫只当买房指标，完全不管日常居住体验','以为田宅不好就只能认命，不动手收拾、不修老房','靠摆件风水化解，却不解决漏水、采光、收纳这些真问题'],
 enMis:["Using the Property Palace only as a home-buying metric and ignoring daily living quality","Assuming a bad Property Palace means accepting it without tidying or repairs","Relying on ornaments while ignoring real leaks, lighting and storage problems"],
 cnClose:'田宅宫是你晚上回去的那个地方。房子大小是一阵子的事，那个空间亮不亮、顺不顺、舒不舒服，才是天天跟着你的。',
 enClose:"The Property Palace is the place you return to at night. Square footage is for a while; whether that space is bright, smooth and comfortable stays with you every day."},

{cat:'gongwei',slug:'ziwei-nupu-gong-xiashu-zhongcheng',focus:'仆役宫下属忠诚',focusEn:'the Servants Palace and subordinate loyalty',
 cnT:'紫微斗数仆役宫：看下属、朋友和搭伙的人靠不靠得住',
 enT:'The Servants Palace in Zi Wei Dou Shu: Whether Subordinates, Friends and Partners You Rely On Hold Up',
 cnD:'仆役宫也叫朋友宫，现实里对应三块：你的下属与团队、你常来往的朋友、以及和你搭伙做事的合伙人。它不是只看「有没有人帮你」，更看这些人在关键时候靠不靠得住、会不会反水。',
 enD:"The Servants Palace, also called the Friends Palace, maps onto three real groups: your subordinates and team, your regular friends, and the partners you do business with. It is not only about whether people help you; it is whether they hold up at key moments and whether they turn on you.",
 cnL:'有人一听仆役宫，以为是看佣人。其实现代语境里，它是你手下那帮人、你朋友圈、还有和你合伙做生意的人——是你能借力的外围网络。',
 enL:"Hearing Servants Palace, some picture domestic staff. In modern terms it is your team under you, your circle of friends, and the business partners—the outer network you lean on.",
 cnA:'要把仆役宫的三类人分开读：下属看执行力与忠诚度，朋友看是不是长久处得来，合伙看利益写没写清楚。合伙这类事，最终以专业律师和书面合同为准，盘上只是倾向。',
 enA:"Read the three groups separately: subordinates for execution and loyalty, friends for long-term fit, and partners for whether interests are clearly written down. Partnerships ultimately follow a professional lawyer and a written contract; the chart only shows a tendency.",
 cnLog:['仆役宫本义看奴仆下属，现代延伸为团队、下属、助理等执行层的人。','它也看朋友与同辈社交圈：常来往的人是来帮你还是来耗你。','合伙、搭伙做事也借这一宫看：对方值不值得共担风险、会不会在分钱时生变。','仆役坐煞或化忌，要留心下属留不住、朋友拖累、合伙翻脸；涉及钱和股权，必须书面合同、专业律师把关，不以盘上说法替代法律文件。'],
 enLog:["The Servants Palace originally read servants and subordinates, and now extends to teams, reports and assistants—the execution layer.","It also reads friends and the social circle: whether the people around you help or drain you.","Partnerships and joint ventures borrow this palace: whether the other side can share risk and whether money splits will turn ugly.","When a malefic or Hua Ji sits there, watch turnover, draining friends and falling-out partners; for money and equity, rely on written contracts and a lawyer, never on the chart as a legal document."],
 cnStep:['先找到仆役宫，分清你要问的是下属、朋友还是合伙','看下属线：团队稳不稳、关键岗位的人会不会走','看朋友线：常来往的人是滋养你还是一直消耗你','看合伙线：利益分工、退出机制有没有写清楚','坐煞时不盲目相信人情，重要合作一律落到书面','涉及股权与责任，以专业律师和正规途径、书面合同为准'],
 enStep:["First locate the Servants Palace and decide whether you ask about subordinates, friends or partners","On the subordinate line: whether the team is stable and key people may leave","On the friend line: whether your circle nourishes or drains you","On the partner line: whether roles, splits and exit terms are written down","If a malefic sits there, do not trust sentiment alone; put key deals in writing","For equity and liability, defer to a professional lawyer, proper channels and a written contract"],
 cnMis:['把仆役宫只当看有没有贵人，不看下属和合伙风险','觉得坐吉星就可以全凭人情合伙，不写合同','合伙出了问题才想起盘上有煞，早不做书面约定'],
 enMis:["Using the Servants Palace only for benefactors while ignoring subordinate and partner risk","Assuming an auspicious star means partnering on trust alone with no contract","Recalling the malefic only after a partnership sours, without earlier written terms"],
 cnClose:'仆役宫是你能借上力的那张网。人靠不靠得住，平时处出来；钱怎么分、责任怎么担，白纸黑字写出来——盘只是提醒你别只信人情。',
 enClose:"The Servants Palace is the network you can lean on. Whether people hold up shows over time; how money splits and responsibilities sit must be written down—the chart only reminds you not to trust sentiment alone."}
];
