// 2026-09-28 调研驱动 第1组：看盘流程/空宫借对宫/定盘/辅煞分类 8篇
module.exports=[
{cat:'kanpan',slug:'ziwei-xinshou-dupan-liucheng-liubu',focus:'新手读盘六步流程',focusEn:'the six-step reading process for beginners',
 cnT:'紫微斗数新手读盘六步流程：从哪一宫下手才不乱',
 enT:'The Six-Step Chart Reading Process for Zi Wei Dou Shu Beginners: Where to Start Without Getting Lost',
 cnD:'新手拿到十二宫星盘往往不知从何看起。固定顺序：先看命宫立性格底色，再看三方四正定格局骨架，再看生年四化找能量流向，然后看大限流年接时间，最后看辅煞与宫位重叠，逐层收束而不是满盘乱读。',
 enD:'New readers stare at twelve palaces and do not know where to begin. Follow a fixed order: read the Life Palace for the baseline personality, the triple-direction for the pattern skeleton, the natal four transformations for energy flow, then decade and yearly limits for timing, and finally the assistants and malefics layered over palaces, narrowing step by step rather than reading the whole chart at once.',
 cnL:'很多人排完盘，眼睛直接被最亮的那颗星吸走，盯着一颗星断半天。其实一张盘是有阅读顺序的，跳着看、抓着单颗星看，越看越乱。',
 enL:"After casting, many readers' eyes lock onto the brightest star and judge half a day on it. A chart has a reading order; jumping around or fixing on one star only makes it messier.",
 cnA:'这个问题到底在问什么：新手真正需要的不是「哪颗星最厉害」，而是一个稳定的下手顺序，让十二宫星曜不会同时压过来。把盘拆成六层，一层看完再看下一层，就不会乱。',
 enA:"The real question is not which star is strongest, but a stable order of attack so the twelve palaces do not crash in at once. Split the chart into six layers, finishing one before the next, and it stops being chaotic.",
 cnLog:['命宫是整张盘的主语，先读它立住这个人的底色与基本性格，后面所有宫都围绕它展开。','三方四正把命宫的骨架撑起来：官禄、财帛、迁移三宫决定这个人在事业、钱财、外出三方面的承接力。','生年四化是能量流向，看禄从哪来、忌往哪停，才知道资源与课题落在哪。','大限与流年是时间层，决定这些底色与骨架在哪个阶段被触发；最后才看辅星煞星作细部修饰。'],
 enLog:["The Life Palace is the subject of the whole chart; read it first to establish baseline personality, since every other palace revolves around it.","The triple-direction builds the skeleton: career, wealth and outward palaces set how a person carries work, money and movement.","The natal four transformations are the energy current: where Lu comes from and where Ji stops shows resources and lessons.","Decade and yearly limits are the timing layer, deciding when this baseline and skeleton get triggered; assistants and malefics are last as fine shading."],
 cnStep:['先定命宫位置，读命宫主星与基本性格底色','转去三方四正，看官禄、财帛、迁移三宫撑住的格局骨架','标出生年四化禄权科忌各自落在哪宫，理清能量进出','再叠大限，看当前十年的主题承接在哪一宫','最后看流年引动了哪一宫，把时间点到具体一年','细部补看辅星煞星与宫位重叠，只作修饰不改主断'],
 enStep:["Locate the Life Palace and read its main stars for the baseline personality","Turn to the triple-direction to read the skeleton held by career, wealth and outward palaces","Mark where Lu, Quan, Ke and Ji land to clarify energy in and out","Layer the decade to see where this ten-year theme is carried","Then see which palace the year activates, pinning timing to a specific year","Finally add assistants and malefics over palace overlaps as shading, not as the main verdict"],
 cnMis:['拿到盘就盯着最亮或最凶的单颗星断事','跳过三方四正，不看格局骨架直接断细节','把辅星煞星看得比主星四化还重，本末倒置'],
 enMis:["Grabbing the brightest or fiercest single star and judging from it","Skipping the triple-direction and judging details before the skeleton","Weighing assistants and malefics more than main stars and transformations"],
 cnClose:'读盘不是抓着一颗星看，而是按六层顺序一层一层收。命宫立人、三方立骨架、四化找流向、大限流年接时间、辅煞补细节——顺序对了，盘才越读越清楚。',
 enClose:"Reading a chart is not clutching one star but narrowing through six layers. The Life Palace sets the person, the triple-direction the skeleton, the transformations the flow, decade and year the timing, and assistants the detail; with the right order the chart grows clearer."},

{cat:'kanpan',slug:'ziwei-konggong-jieduigong-caozuo',focus:'空宫借对宫操作',focusEn:'borrowing the opposite palace for empty palaces',
 cnT:'紫微斗数空宫借对宫怎么操作：本宫无主星时看哪一边',
 enT:'How to Handle Empty Palaces in Zi Wei Dou Shu: Reading the Opposite Palace When a Palace Has No Main Star',
 cnD:'某一宫十二颗主星都不落、称作空宫时，不代表这一宫是空的，而是借对宫的主星来看；借过来的星曜要按对宫的性质理解，再叠加本宫自带的辅星煞星与四化，才是这一宫的真实状态。',
 enD:"When none of the twelve main stars falls in a palace, it is called empty; that does not mean the palace is blank. You borrow the main stars from the opposite palace, read them through that opposite palace's nature, and then layer the palace's own assistants, malefics and transformations for its real state.",
 cnL:'新手排盘看到某一宫空空如也，就以为这方面「没东西、不用看」。其实空宫只是本宫没主星坐镇，对宫的主星会照过来，这一宫照样要读。',
 enL:"New readers see an empty palace and think that area has nothing to read. An empty palace simply has no main star seated; the opposite palace's main stars shine across, and the palace is still read.",
 cnA:'这个问题到底在问什么：空宫不是真空，而是「主星不在本宫、借对宫来用」。要分清借过来的星曜是对面哪一宫的、按对面的性质理解，再叠本宫自己的杂曜与四化，三者合起来才是这一宫。',
 enA:"The question is: an empty palace is not really empty; its main star sits across and is borrowed. Clarify which opposite palace the borrowed stars come from, read them through that palace's nature, then layer the local minor stars and transformations; the three together are the palace.",
 cnLog:['空宫指本宫十二颗主星无一落入，但辅星、煞星、四化仍在本宫，不能直接跳过。','借对宫主星时，要按对宫的宫位性质来理解这组星曜，而不是当成本宫自己生的。','对宫星曜力量照过来，通常不如本宫自坐主星那么贴身，带有「隔一层」的距离感。','本宫自带的辅煞与四化决定借过来的星曜最终在这一宫是助力还是拖累，必须叠加才完整。'],
 enLog:["An empty palace has none of the twelve main stars, but assistants, malefics and transformations still sit there and must not be skipped.","When borrowing the opposite main stars, read them through that opposite palace's nature, not as if born in this palace.","Stars shining from across carry a layer of distance and are less intimate than main stars seated in the palace.","The palace's own assistants, malefics and transformations decide whether the borrowed stars help or burden here, and must be layered on."],
 cnStep:['先确认本宫是否真的无主星落入，排除只是主星弱坐的情况','找到本宫的对宫，记下对宫主星组合','按对宫的宫位性质，把这组星曜「借读」到本宫来','再读本宫自带的辅星、煞星与杂曜','叠加本宫与对宫各自的四化，看能量怎么引动','综合判断这一宫状态，注明是借来的力量而非本宫自坐'],
 enStep:["Confirm the palace truly has no main star, ruling out a weakly seated one","Find the opposite palace and note its main-star combination","Read that combination across into this palace through the opposite palace's nature","Then read this palace's own assistants, malefics and minor stars","Layer the transformations from both this and the opposite palace to see activation","Judge the palace as borrowed force rather than a self-seated main star"],
 cnMis:['见空宫就跳过，以为这方面不用看','借了对宫主星却按本宫性质硬套，不换视角','只看借来的主星，不叠加本宫自己的辅煞与四化'],
 enMis:["Skipping an empty palace as if that area needs no reading","Borrowing the opposite stars but forcing them through this palace's own nature","Reading only the borrowed main stars and ignoring local assistants, malefics and transformations"],
 cnClose:'空宫不是没东西，而是主星坐在对面照过来。借对宫的星、换对面的视角、再叠自己本宫的杂曜与四化——三步做完，空宫就不空了。',
 enClose:"An empty palace is not blank; its main star sits across and shines over. Borrow the opposite stars, switch to that perspective, then layer local minor stars and transformations; the three steps fill the emptiness."},

{cat:'faq',slug:'ziwei-ziwei-bazi-shuangpan-duizhao',focus:'紫微八字双盘对照',focusEn:'comparing Zi Wei and BaZi charts side by side',
 cnT:'紫微斗数与八字双盘对照：两套系统各看什么、能不能互证',
 enT:'Zi Wei Dou Shu and BaZi Side by Side: What Each Reads and Whether They Cross-Check',
 cnD:'八字以年月日时四柱五行生克看人生大势与格局高低，紫微以十二宫星曜看具体领域的人事细节；两者切入角度不同，可以互相参照，但因共用两小时时辰边界，不能当成独立证据互相背书。',
 enD:"Bazi reads broad life direction and pattern through five-elements interactions across four pillars, while Zi Wei reads specific domains through twelve palaces of stars. They approach from different angles and can reference each other, but because they share the same two-hour hour boundary, neither independently verifies the other.",
 cnL:'有人排了紫微又排八字，发现两边说法差不多就很放心，说「两套系统都这么讲」。其实它们对时辰的依赖是同一条边界上的，不能当成两张独立的票来对冲。',
 enL:"Some cast both Zi Wei and BaZi, find them agree, and relax saying two systems both say so. But their dependence on the hour sits on the same boundary, so neither hedges the other as an independent ticket.",
 cnA:'这个问题到底在问什么：双盘对照不是为了让两边「互相盖章」，而是各取所长——八字看五行气势与格局高低，紫微看十二宫的人事具体领域。分工清楚了，对照才有意义。',
 enA:"Side-by-side comparison is not to get two stamps on the same claim but to use each strength: Bazi for five-element momentum and pattern level, Zi Wei for the twelve specific human domains. Once the division of labor is clear, comparison becomes useful.",
 cnLog:['八字以天干地支四柱为骨架，重五行旺衰、十神生克，长于看格局高低与人生大势。','紫微以十二宫为骨架，重星曜落宫与四化飞动，长于看各领域的具体人事与应期。','两套系统都按两小时切时辰，时辰一错，两边同时偏，不能互相校正。','双盘对照时，把两边结论放在同一时间段上互参：大势一致则加强信心，领域细节以紫微为准。'],
 enLog:["Bazi is built on four pillars of stems and branches, weighting element strength and ten-god interactions, good at pattern level and broad direction.","Zi Wei is built on twelve palaces, weighting star placement and transforming flies, good at specific human affairs and timing by domain.","Both cut the hour every two hours, so a wrong hour biases both at once; neither corrects the other.","Compare conclusions on the same time window: agreement strengthens confidence, while domain details defer to Zi Wei."],
 cnStep:['先分别排出八字与紫微两张盘，确认出生时间一致','用八字读五行气势与格局高低，记下大势判断','用紫微读十二宫各领域的具体人事与四化走向','把两边结论按时间段对齐，找一致与分歧','大势一致处作为较强结论，分歧处标注待查','记住两盘同源同时辰，不用一边去给另一边背书'],
 enStep:["Cast both Bazi and Zi Wei charts from the same birth time","Read Bazi for element momentum and pattern level, note the broad judgment","Read Zi Wei for twelve-domain affairs and transformation flows","Align both sets of conclusions by time window and find agreement and divergence","Treat agreement as a stronger conclusion and mark divergence as to-check","Remember the two share the same hour, so neither endorses the other"],
 cnMis:['两边说法一致就当成铁证，忽略它们时辰同源','用八字的十神直接替代紫微的宫位含义','拿双盘互相背书，却不在同一时间段上对齐'],
 enMis:["Treating agreement as iron proof while ignoring the shared hour","Substituting Bazi ten-gods directly for Zi Wei palace meanings","Using the two to endorse each other without aligning them by time window"],
 cnClose:'双盘对照是各取所长，不是互相盖章。八字看大势，紫微看领域，时辰同源不能对冲。放在同一段时间上互参，一致处更稳，分歧处留着继续看。',
 enClose:"Side-by-side reading draws on each strength; it is not mutual endorsement. Bazi reads the broad tide, Zi Wei the domains; sharing the hour means no hedging. Reference them on the same window: agreement is firmer, divergence stays open."},

{cat:'kanpan',slug:'ziwei-dingpan-shijian-jieding-fangfa',focus:'定盘时间界定方法',focusEn:'methods to verify the birth hour',
 cnT:'紫微斗数定盘时间界定：用哪几件事把时辰钉死',
 enT:'Methods to Verify the Birth Hour in Zi Wei Dou Shu: Which Events Lock the Shichen',
 cnD:'定盘不靠性格评语，而靠有明确公历年月的客观大事去碰候选时辰的大限流年；多件事件一致指向同一时辰才算定盘成功。贴边界的盘尤其要先定盘再断未来。',
 enD:"Hour verification does not rely on personality notes but on dated objective events tested against candidate hours' decade and yearly limits; only when several events point to one hour is the chart verified. Boundary-near charts must be verified before any future reading.",
 cnL:'很多人排完盘直接就看未来，却从不问自己这张盘稳不稳。出生时间记得是几点几分、还是只记得大概，决定了这张盘能不能直接拿来断事。',
 enL:"Many cast and immediately read the future without asking whether the chart is stable. Whether the birth time is remembered to the minute or only roughly decides whether the chart can be used directly.",
 cnA:'这个问题到底在问什么：定盘是反推时辰，不是先信时辰再找事来圆。方法是列出候选时辰、各自排盘、用过往带日期的大事去碰，哪个盘对上的事件最多、最硬，那个时辰才作数。',
 enA:"Verification is reverse-inferring the hour, not trusting the hour and fitting events after the fact. The method: list candidate hours, cast each, test dated past events against them; whichever chart matches the most, hardest events wins.",
 cnLog:['定盘的前提是出生时间不确定或贴近两小时格线，确定无疑的时间不必强行重定。','候选时辰一般取前后相邻的两三个，分别排盘作为对照。','硬证据是带公历年月的客观事件：搬家、换工作、结婚、升学、伤病、破财置业。','单一事件能被多个时辰凑上，必须多件事件交叉一致指向同一时辰，定盘才成立。'],
 enLog:["Verification is needed only when the birth time is uncertain or near a two-hour boundary; a firmly known hour needs no re-verification.","Candidate hours are usually the two or three adjacent ones, cast as a comparison set.","Hard evidence means objective events with a year and month: moving, job change, marriage, schooling, illness, buying property.","One event fits several hours; only cross-consistency across several events locks the hour."],
 cnStep:['先判断出生时间是确定无疑、大致记得还是只知区间','若贴边界，列出前后两三个候选时辰','为每个候选时辰各排一张盘','列出本人能确定公历年月的过往客观大事','逐盘用大限流年去碰每件大事的年份，记录匹配度','取匹配事件最多最硬的时辰为定盘结果，其余标注待核'],
 enStep:["First judge whether the birth time is certain, roughly remembered or only a window","If near a boundary, list the two or three adjacent candidate hours","Cast a chart for each candidate","List objective past events with known year and month","For each chart, test decade and yearly limits against each event's year and score matches","Take the chart matching the most hardest events as verified; mark the rest to-check"],
 cnMis:['用性格、长相、口头禅作为定盘证据','只凭一件大事就拍板定时辰','时间贴边界却不定盘，直接在可能错的盘上断未来'],
 enMis:["Using personality, looks or catchphrases as verification evidence","Fixing the hour from a single major event","Skipping verification on a boundary-near chart and judging the future on it"],
 cnClose:'定盘是拿真事去碰盘，不是拿盘去找理由圆。几件带日期的大事对上同一个时辰，这张盘才稳得住；稳了，后面的断未来才有意义。',
 enClose:"Verification lays real events against the chart rather than fitting reasons to it. Once several dated events land on the same hour, the chart holds; only then does reading the future mean anything."},

{cat:'rumen',slug:'ziwei-fuxing-shaxing-fenlei-rukou',focus:'辅星煞星分类入口',focusEn:'classifying assistant and malefic stars',
 cnT:'紫微斗数辅星煞星怎么分：先记住谁帮谁拖',
 enT:'Classifying Assistant and Malefic Stars in Zi Wei Dou Shu: Start by Knowing Who Helps and Who Drains',
 cnD:'辅星是给主星加分或加细节的助力，如左辅右弼、天魁天钺；煞星是给主星加压力或添波折的阻力，如擎羊陀罗、火星铃星；它们本身没有绝对好坏，落在哪个宫、配哪颗主星，才决定最终是帮还是拖。',
 enD:"Assistant stars add support or detail to the main star, such as Zuo Fu You Bi and Tian Kui Tian Yue; malefic stars add pressure or friction, such as Qing Yang Tuo Luo and Huo Xing Ling Xing. Neither is absolutely good or bad; which palace they land in and which main star they meet decides whether they help or drain.",
 cnL:'新手一看到煞星就紧张，一见辅星就放松，把它们分成「好星星」和「坏星星」两堆。其实辅煞更像调味料，主星才是主菜，料下在哪道菜里，效果完全不同。',
 enL:"New readers tense at malefics and relax at assistants, sorting them into good stars and bad stars. Assistants and malefics are more like seasoning; main stars are the dish, and where the seasoning lands changes everything.",
 cnA:'这个问题到底在问什么：辅星煞星不是独立断事的牌，而是修饰主星的修饰语。要先认得出谁是辅、谁是煞，再看它们贴着哪颗主星、落在哪个宫，最后判断这股修饰是放大了主星的优点还是缺点。',
 enA:"Assistants and malefics are not standalone fortune cards but modifiers of the main stars. First recognize who is assistant and who is malefic, then see which main star and palace they sit on, and judge whether the modifier amplifies the main star's strength or weakness.",
 cnLog:['辅星如左辅右弼、天魁天钺、文昌文曲，主助力、贵人、文书与细节加成。','煞星如擎羊陀罗、火星铃星、地空地劫，主压力、波折、破耗与执行力的另一面。','辅煞本身无绝对吉凶，凶星遇刚星有时反成冲劲，吉星落陷也可能帮倒忙。','辅煞要贴着主星与宫位读：同宫主星得助力则顺，同宫主星受冲则波折多。'],
 enLog:["Assistants such as Zuo Fu You Bi, Tian Kui Tian Yue and Wen Chang Wen Qu stand for support, patrons, paperwork and fine detail.","Malefics such as Qing Yang Tuo Luo, Huo Xing Ling Xing and Di Kong Di Jie stand for pressure, friction, drain and a flip side of drive.","Neither is absolutely good or bad: a harsh star meeting a firm main star can become drive, while an assistant fallen may help the wrong way.","Read them against the main star and palace: together with a strong main star they smooth, together with a pressured one they roughen."],
 cnStep:['先认出十二颗主星是谁，把主星当主角','再从辅星里挑出左辅右弼、魁钺、昌曲等助力星','再从煞星里挑出擎羊陀罗、火铃、空劫等阻力星','逐宫看每颗辅煞贴着哪颗主星坐','判断这股修饰是放大主星优点还是放大缺点','辅煞只作修饰，不脱离主星单独下断'],
 enStep:["First recognize the twelve main stars and treat them as the leads","Pick out assistants such as Zuo Fu You Bi, Kui Yue and Chang Qu","Pick out malefics such as Qing Yang Tuo Luo, Huo Ling and Kong Jie","Palace by palace, see which main star each assistant or malefic sits on","Judge whether the modifier amplifies the main star's strength or flaw","Treat assistants and malefics only as modifiers, never judging them alone"],
 cnMis:['把辅星一律当吉、煞星一律当凶，不看主星宫位','脱离主星单独拿一颗煞星断大凶','以为吉星越多盘越好，不看吉星落没落对宫'],
 enMis:["Reading assistants as always lucky and malefics as always harsh regardless of main star and palace","Judging great misfortune from one malefic apart from its main star","Assuming more assistants means a better chart without checking which palace they sit in"],
 cnClose:'辅星煞星是调味料，主星才是主菜。认出谁帮谁拖只是第一步，最终落在哪个宫、配哪颗主星，才决定这勺料是提鲜还是添乱。',
 enClose:"Assistants and malefics are seasoning; main stars are the dish. Recognizing who helps and who drains is step one; which palace and which main star they meet decides whether the seasoning lifts or spoils the dish."},

{cat:'faq',slug:'ziwei-paipan-jingdu-yingxiang-yinsu',focus:'排盘精度影响因素',focusEn:'factors affecting chart-casting accuracy',
 cnT:'紫微斗数排盘精度受什么影响：时辰、历法与出生地三件事',
 enT:'What Affects the Accuracy of a Zi Wei Dou Shu Chart: Birth Hour, Calendar and Birthplace',
 cnD:'排盘精度主要受三件事影响：出生时辰是否准确到两小时格线内、是否换算真太阳时与出生地经度、农历公历与早晚子时有没有处理对。三件里任何一件出错，命宫都会偏，整张盘跟着错。',
 enD:"Casting accuracy hinges on three things: whether the birth hour lands correctly inside its two-hour step, whether true solar time and birthplace longitude are converted, and whether lunar-solar calendar and the late-early midnight boundary are handled right. Any one error shifts the Life Palace and the whole chart follows.",
 cnL:'有人排出来的盘怎么读都不顺，以为是自己功力不够，其实根子可能在排盘那一步就错了。时辰差一格、历法没换算，后面读得再细也是错盘。',
 enL:"Some find the chart reads poorly and blame their own skill, when the root error may lie at casting. An hour off by one step or an unconverted calendar makes even the finest reading a wrong chart.",
 cnA:'这个问题到底在问什么：排盘精度不是玄学问题，而是三个可核对的技术环节——时辰边界、真太阳时、历法与早晚子时。先把这三关过了，再谈读盘，否则读的是别人的盘。',
 enA:"Casting accuracy is not a mystical matter but three checkable technical steps: the hour boundary, true solar time, and calendar with the midnight boundary. Pass these three before reading; otherwise you are reading someone else's chart.",
 cnLog:['紫微命宫按两小时一格切，出生时间跨格线就整格移位，是影响最大的一项。','真太阳时与出生地经度不换算，同一生日不同城市会排出不同命宫。','农历公历转换、闰月处理若用错历法，月系星曜排布会跟着偏。','23点子时前后的早晚子时边界若不分，命宫与身宫可能落错，需按当地时间严谨界定。'],
 enLog:["The Life Palace is cut into two-hour steps; crossing a boundary shifts it a whole step, the largest single factor.","Skipping true solar time and birthplace longitude yields different Life Palaces for one birthday across cities.","Wrong lunar-solar conversion or mishandled leap months skews the monthly star arrangement.","Confusing the late and early midnight boundary around 11 p.m. can misplace the Life and Body palaces and must be defined by local time."],
 cnStep:['先核对出生时间是否精确到时辰、是否贴近格线','换算真太阳时与出生地经度修正','确认农历公历转换与闰月是否处理正确','界定23点前后的早晚子时归属','用校正后的时间重新排盘','与原盘对比，命宫变了则整盘重判'],
 enStep:["First check whether the birth hour is precise and whether it sits near a boundary","Convert true solar time and apply birthplace longitude correction","Confirm lunar-solar conversion and leap-month handling","Define the late versus early midnight attribution around 11 p.m.","Re-cast with the corrected time","Compare with the original; if the Life Palace moved, re-judge the whole chart"],
 cnMis:['排完盘不回头核对时辰与经度，直接开读','把农历公历随便换算，不查闰月','23点出生不区分早晚子时，默认直接归次日'],
 enMis:["Casting and reading immediately without re-checking hour and longitude","Converting lunar and solar calendars carelessly without checking leap months","At 11 p.m. defaulting to the next day without separating late and early midnight"],
 cnClose:'排盘是地基，读盘是楼上。时辰边界、真太阳时、历法与早晚子时这三关不过，楼盖得再漂亮也是歪的。先把盘排准，再谈后面的断事。',
 enClose:"Casting is the foundation and reading the floors above. If the hour boundary, true solar time, calendar and midnight boundary are not right, even a beautifully built tower leans. Cast the chart accurately before judging."},

{cat:'kanpan',slug:'ziwei-liji-taiji-gongwei-zhuanhuan',focus:'立太极宫位转换',focusEn:'shifting the taiji pole between palaces',
 cnT:'紫微斗数立太极：把某一宫当新命宫重排十二宫',
 enT:'Shifting the Taiji Pole in Zi Wei Dou Shu: Treat One Palace as the New Life Palace and Rebuild the Twelve',
 cnD:'立太极就是换一个宫当新的命宫原点，按原十二宫的相对关系重排其余十一宫；问配偶的事立夫妻宫、问子女立子女宫，换的是主语不是造新命。原盘格局始终约束着借来的这条线。',
 enD:"Shifting the taiji pole means taking one palace as a new Life origin and renaming the other eleven by their relative positions: the Spouse Palace for spouse matters, the Children Palace for child matters. It changes the subject, not creating a new fate; the original pattern always bounds the borrowed line.",
 cnL:'想问「我孩子将来怎么样」，却盯着自己的命宫看，方向就偏了。紫微里换个问题就要换个原点，把对应的宫立成新的命，十二宫围着它重排。',
 enL:"Wondering how a child will turn out while staring at your own Life Palace points the wrong way. In Zi Wei, a new question needs a new origin: set the relevant palace as the new Life and rebuild the twelve around it.",
 cnA:'这个问题到底在问什么：立太极解决的是「以谁为主语」的问题。同一张盘，命宫为原点是你自己的人生；夫妻宫为原点，就是配偶在你盘里的投影。换原点后必须把十二宫逐一重新命名，不能只换命宫那一格。',
 enA:"Shifting taiji answers who is the subject. With the Life Palace as origin it is your own life; with the Spouse Palace as origin it is the spouse's projection within your chart. After shifting, all twelve palaces must be renamed, not just the Life cell.",
 cnLog:['立太极的核心是平移相对位置：新原点确定后，其余宫按原十二宫的固定关系逐一改名。','问配偶立夫妻宫、问子女立子女宫、问父母立父母宫，各有对应原点。','借来的十二宫仍在原盘之上，其星曜四化都受原盘格局约束，不是另立一张命。','原点换了之后，原来的三方四正关系也要跟着重算，不能沿用命宫那套三方。'],
 enLog:["Shifting works by translating relative positions: once the new origin is set, rename the rest by the fixed twelve-palace relationships.","Set the Spouse Palace for a spouse, the Children Palace for a child, the Parents Palace for parents, each as its own origin.","The borrowed twelve sit on top of the original chart, bound by its pattern; they do not become a separate fate.","Once the origin shifts, the triple-direction relationships are recalculated, not the ones from the Life Palace."],
 cnStep:['先明确要问的是配偶、子女、父母还是事业哪一方','选定对应宫位作为新的太极原点','按原十二宫相对位置，把其余十一宫逐一改名','重新计算新原点下的三方四正关系','读这条新线上的星曜、辅煞与四化','记住这是借视角看同一盘，受原盘格局约束'],
 enStep:["First clarify whether the question is about spouse, child, parent or career","Pick the corresponding palace as the new taiji origin","Rename the other eleven by their original relative positions","Recalculate the triple-direction under the new origin","Read the new line's stars, assistants, malefics and transformations","Remember this is a borrowed view of one chart, bound by the original pattern"],
 cnMis:['问某一方的事却直接读自己命宫或官禄宫','换了原点却不重排其余十一宫与三方','把借来的盘当成对方独立的命来下断'],
 enMis:["Reading your own Life or career palace when asking about another party","Shifting the origin without renaming the other eleven and the triple-direction","Treating the borrowed chart as the other party's independent fate"],
 cnClose:'立太极是换个主语看同一张盘。原点一移，十二宫的关系就换成了那条新线的故事，但底子还是原盘——主语换对了，配偶、子女那条线才读得准。',
 enClose:"Shifting taiji changes the subject on one chart. Move the origin and the twelve relationships become the new line's story, yet the base remains the original chart; with the right subject, the spouse or child line reads accurately."},

{cat:'rumen',slug:'ziwei-duigong-liuguan-ji-yi',focus:'对宫六关记忆',focusEn:'memorizing the six opposite-palace pairs',
 cnT:'紫微斗数对宫六关：六组宫位对照一次记牢',
 enT:'The Six Opposite-Palace Pairs in Zi Wei Dou Shu: Memorize Them in One Pass',
 cnD:'十二宫两两相对成六关：命迁、兄仆、夫官、子田、财福、父疾。对宫是本宫的镜子与补充，本宫立什么、对宫照什么，读盘时必须本宫对宫合看，不能只看一头。',
 enD:"The twelve palaces pair into six opposite pairs: Life-Outward, Sibling-Subordinate, Spouse-Career, Child-Property, Wealth-Karma, Parent-Health. The opposite palace is the mirror and complement of the home palace; read home and opposite together, never one side alone.",
 cnL:'新手记十二宫总是一团乱，但只要记住「两两相对」这条线，十二宫立刻变成六组，好记一半。命宫对面是谁、财帛对面是谁，一对一对着背就顺了。',
 enL:"New readers find the twelve palaces a jumble, but remembering they pair off cuts the mess in half. Once you ask who sits opposite the Life Palace and who opposite Wealth, the twelve become six easy pairs.",
 cnA:'这个问题到底在问什么：对宫不是无关的另一宫，而是本宫的镜像与补充。本宫说的是这一领域本身的状态，对宫说的是它外部的呼应与对照，两边合起来才是完整的一件事。',
 enA:"The opposite palace is not an unrelated palace but the mirror and complement of the home palace. The home palace states the matter itself; the opposite states its external echo; the two together make one complete thing.",
 cnLog:['命迁线：命宫与迁移相对，看自身性格与在外境遇的对照。','夫官线：夫妻宫与官禄宫相对，看婚姻与事业的互相牵动。','子田线：子女宫与田宅宫相对，看子女与家庭不动产的关联。','财福线与父疾线：财帛对福德看钱财与精神享受，父母对疾厄看长辈荫庇与体质。'],
 enLog:["Life-Outward: Life and Migration oppose, showing self against outer circumstance.","Spouse-Career: Spouse and Career oppose, showing how marriage and work pull on each other.","Child-Property: Children and Property oppose, showing children linked to the home estate.","Wealth-Karma and Parent-Health: Wealth against Karma shows money versus ease, Parents against Health shows upbringing versus body."],
 cnStep:['先把命宫位置定下来，沿盘面找到正对的迁移宫','顺时针数到夫妻宫，正对的就是官禄宫','继续数到子女宫，正对的是田宅宫','再数财帛宫，正对的是福德宫','最后父母宫正对疾厄宫，六对凑齐','读任一宫时都把对宫拉出来合看，不单独断'],
 enStep:["Fix the Life Palace and find Migration directly across","Count clockwise to Spouse; its opposite is Career","Continue to Children; its opposite is Property","Then Wealth; its opposite is Karma","Finally Parents opposite Health, completing the six pairs","Whenever reading any palace, pull out its opposite and read them together"],
 cnMis:['只看本宫不看对宫，断事缺一半','把六对关系记混，对错了宫位合看','以为对宫只是参考，本宫定了就不用看对面'],
 enMis:["Reading only the home palace and missing half the picture","Mixing up the six pairs and matching the wrong opposites","Treating the opposite as optional once the home palace is settled"],
 cnClose:'十二宫记成六对，盘就好读一半。命迁、夫官、子田、财福、父疾——每一对都是一面镜子，本宫立什么，对宫照什么，两头合看，一件事才完整。',
 enClose:"Twelve palaces remembered as six pairs makes the chart half as hard. Life-Outward, Spouse-Career, Child-Property, Wealth-Karma, Parent-Health; each pair is a mirror, home states and opposite reflects, and reading both completes the matter."}
];
