// 2026-09-28 批次 第3组：主星性格/双星组合/大限流年 8篇
module.exports=[
{cat:'zhuxing',slug:'ziwei-tianji-xing-siwei-fangfa',focus:'天机星思维方式',focusEn:'Tian Ji star and thinking style',
 cnT:'紫微斗数天机星：脑子转得快的人，为什么反而容易想太多',
 enT:'Tian Ji in Zi Wei Dou Shu: Why the Fast-Thinking Mind Also Overthinks',
 cnD:'天机星主思虑、变动与谋划，坐命的人习惯先在脑子里把事推演几遍再动手；优点是反应快、点子多，副作用是停不下来、容易临时改主意。它描述的是一种思维节奏，不是聪明或愚笨的判决。',
 enD:"Tian Ji governs thought, movement and planning. People with it in the Life Palace tend to run things through their head several times before acting. The upside is quick reflexes and many ideas; the cost is an overactive mind and last-minute changes of plan. It describes a thinking rhythm, not a verdict of cleverness or dullness.",
 cnL:'有人坐命天机，你刚开口说半句，他已经在脑子里把后面三步都演完了。这种人反应确实快，但你也常发现他一件事来回改，夜里还在床上复盘白天那句话说得到不到位。',
 enL:"With Tian Ji in the Life Palace, you may have said half a sentence while the person has already played out the next three steps in mind. They react fast, yet you also see them revise the same thing repeatedly and re-litigate a day's words in bed at night.",
 cnA:'天机要回答的不是「聪不聪明」，而是「脑子怎么转」：它是先想后动、边想边改、还是想个不停却落不了地。看清这个节奏，才知道该怎么用它，而不是空夸一句机灵。',
 enA:"Tian Ji is not asking whether someone is smart; it asks how the mind turns: think-then-act, think-and-adjust, or think endlessly without landing. Once you see the rhythm, you know how to use it rather than just praising quickness.",
 cnLog:['天机属木，被视为善星，主谋略、策划与机动，坐命者多靠脑力与点子吃饭。','它的快是推演式的：先在脑中把路径、风险、替代方案过一遍，再决定动不动手。','快的反面是停不下来：同一个问题反复翻面，主意随新信息不断调整，外人看着像没定性。','天机的强弱还要看同宫辅煞与四化，单见一颗天机不能断定成就高低，2026丙午年天机化权，主这一年思虑更有决断力道，可作流年参照。'],
 enLog:["Tian Ji, an auspicious wood star, governs strategy, planning and mobility; those with it in the Life Palace often earn a living through mental work and ideas.","Its speed is inferential: it runs paths, risks and alternatives through the mind before deciding to act.","The flip side is that it cannot stop, re-examining the same issue and revising with new information, which outsiders read as fickleness.","Its strength depends on co-palace assistants, malefics and transformations; one Tian Ji alone does not fix achievement. In 2026 Bing-Wu, Tian Hua is Hua Quan, sharpening the decisiveness of thought that year."],
 cnStep:['先确认天机是否坐命，还是落在身宫或三方四正','看同宫有无左右昌曲等助思考的星，还是火铃羊陀在旁','读它是偏向策划谋动，还是偏向犹豫反复','把思维节奏落到具体场景：决策、学习、出行、跳槽','看大限流年四化是否引动天机，判断这一年想动还是想守','用节奏建议自己：该想透的事留足推演时间，该落地的事设截止点'],
 enStep:["Confirm whether Tian Ji sits in the Life Palace, the Body Palace, or a triple-direction","See whether assistants like Zuo You or Wen Chang Wen Qu accompany it, or whether fire and bell malefics sit nearby","Read whether it leans to planning and mobility or to hesitation and revision","Map the thinking rhythm to concrete scenes: decisions, study, travel, job changes","Check whether decade or yearly transformations activate Tian Ji to see whether the year favors moving or holding","Advise by rhythm: leave room for deliberation on hard calls, and set deadlines on landing"],
 cnMis:['见天机就夸聪明，不问它是谋动还是空想','以为天机快就一定成事，忽略它反复改主意的一面','单看一颗天机断格局高低，不看辅煞与四化'],
 enMis:["Praising intelligence at the sight of Tian Ji without asking whether it plans or daydreams","Assuming fast thinking guarantees results while ignoring last-minute revisions","Judging rank from Tian Ji alone without its assistants, malefics and transformations"],
 cnClose:'天机是一台转得很快的脑子，不是一张聪明证书。给它配上落地的截止点，它是军师；由着它无限推演，它就变成了夜里停不下来的内耗。',
 enClose:"Tian Ji is a fast-turning mind, not a certificate of cleverness. Give it landing deadlines and it is a strategist; let it infer forever and it becomes nighttime overthinking."},

{cat:'zhuxing',slug:'ziwei-wuqu-xing-caiyuan-juezhe',focus:'武曲星财源决断',focusEn:'Wu Qu star, income sources and decisiveness',
 cnT:'紫微斗数武曲星：硬邦邦的财星，怎么读它的财源与决断',
 enT:'Wu Qu in Zi Wei Dou Shu: The Hard-Minded Wealth Star and How to Read Its Income and Decisiveness',
 cnD:'武曲属金，正财星，主实务、执行与钱财决断；坐命者做事干脆、肯扛硬活，财源多靠手艺、技术、金融或实业一点点挣，不是靠投机顺风。它的硬，用对了是执行力，用错了是硬碰硬的冲突。',
 enD:"Wu Qu, a metal star and the primary wealth star, governs practical work, execution and money decisions. Those with it in the Life Palace act crisply and take on hard jobs; income tends to be earned through craft, skill, finance or industry rather than speculation. Its hardness reads as execution when used well, and as head-on friction when not.",
 cnL:'有人坐命武曲，你跟他谈情怀他没兴趣，直接说这事能落地、能回款，他马上精神。这种人不怕吃苦，就怕一件事扯来扯去没个准话。',
 enL:"With Wu Qu in the Life Palace, talk of sentiment does not move him; mention that something can be delivered and billed and he perks up. He is not afraid of hard work; he is afraid of a matter dragged on without a clear word.",
 cnA:'武曲要分开读两件事：一是财源从哪来，二是钱财上敢不敢拍板。它不像化禄那样讲机会，它讲的是亲手挣、当场断，读盘时要顺着「实干—回款—决断」这条线走。',
 enA:"Wu Qu reads as two things: where the income comes from, and whether one dares to decide on money. Unlike Hua Lu, which is about opportunity, it is about earning by hand and deciding on the spot; follow the line of practical work, payment and decisiveness.",
 cnLog:['武曲为正财星，性刚、主决断与执行，落命者多在实务、金融、军警、工程一类硬行当里见长。','它的财是辛苦财与手艺财，靠技术、资历与执行力累积，与偏财、投机之财不是一路。','刚的正面是说干就干、不拖泥带水；反面是不肯绕弯、容易在人情上硬碰硬。','武曲的财路要看同宫与三方：见禄存化禄则财源扎实，见煞忌则求财过程磕碰，单见武曲不断贫富。'],
 enLog:["Wu Qu is the primary wealth star, firm in nature, governing decisiveness and execution; those with it in the Life Palace often excel in practical, financial, uniformed or engineering fields.","Its wealth is earned through toil and craft, built by skill, seniority and execution, and is a different line from windfall or speculative money.","The bright side is acting on the spot without dragging; the dark side is refusing to bend and clashing head-on with relationships.","Its income path depends on co-palace and triple-direction stars: Lu Cun or Hua Lu means solid sources, while malefics and Hua Ji mean a bumpy pursuit; Wu Qu alone does not fix wealth."],
 cnStep:['先确认武曲坐命或在三方，判断它是命主气质还是局部特质','看同宫有无禄存、化禄，分辨财源是否扎实','再看有无火铃羊陀，分辨求财过程是否磕碰','把它的刚落到决断上：财务、签约、跳槽时敢不敢拍板','看大限流年四化引动武曲时，这一步是开源还是守成','用它的执行力补短板：定下的事就落地，别再绕人情'],
 enStep:["First confirm whether Wu Qu is in the Life Palace or a triple-direction, telling core temperament from a local trait","See whether Lu Cun or Hua Lu sits with it to judge whether income sources are solid","Then see whether fire, bell or blade malefics sit nearby to judge a bumpy pursuit","Apply its firmness to decisions: on money, contracts and job moves, can it commit","See whether decade or yearly transformations activate Wu Qu, and whether the period opens income or defends it","Use its execution to close gaps: once decided, land it rather than circling on feelings"],
 cnMis:['见武曲就断发财，不看财源是否扎实、有无煞忌','把它的刚当成优点，忽略它在人情上硬碰硬的代价','以为武曲是偏财、投机之星，去押风口'],
 enMis:["Declaring wealth at the sight of Wu Qu without checking solid sources or malefics and Hua Ji","Treating its hardness as pure virtue while ignoring head-on costs in relationships","Mistaking Wu Qu for a windfall or speculative star and chasing trends"],
 cnClose:'武曲是硬邦邦的实干财星，财源靠手艺和执行力，决断靠敢拍板。把这股刚用在做事上是利器，用在和人较劲上，就成了硬碰硬的内耗。',
 enClose:"Wu Qu is a hard-minded, practical wealth star: income through craft and execution, decisiveness through daring to commit. Point that hardness at work and it is a blade; point it at arguing with people and it becomes head-on friction."},

{cat:'zhuxing',slug:'ziwei-lianzhen-xing-guize-yuanze',focus:'廉贞星规则原则',focusEn:'Lian Zhen star, rules and principles',
 cnT:'紫微斗数廉贞星：爱讲规则的人，原则感从哪来',
 enT:'Lian Zhen in Zi Wei Dou Shu: Where the Rule-Bound Sense of Principle Comes From',
 cnD:'廉贞属火，次桃花，也主规则、分寸与是非观；坐命者心里有一杆尺，在乎名分、体面与边界，守规矩时可靠，被触碰底线时也最反弹。它讲的是一套内在原则，不是装出来的正派。',
 enD:"Lian Zhen, a fire star and the secondary peach-blossom, also governs rules, propriety and a sense of right and wrong. Those with it in the Life Palace carry an inner ruler, caring about status, face and boundaries; reliable when rules hold, they rebound hardest when a bottom line is crossed. It is an inner code, not a performed decency.",
 cnL:'有人坐命廉贞，你跟他开玩笑过火一点，他当场脸就沉了；可你要是按规矩来，他又是最讲信用、最靠得住的那一个。这种人不是难搞，是心里那条线你得知道在哪。',
 enL:"With Lian Zhen in the Life Palace, push a joke a bit too far and the face drops at once; yet if you follow the rules, he is the most reliable and creditworthy. He is not difficult; he has a line you need to know about.",
 cnA:'廉贞要读的不是「正派不正派」，而是「他心里的规则是什么、边界在哪」。这套原则对内是自律，对外是要求；读盘要看它守规则时的稳定，和被越界时的反弹。',
 enA:"Lian Zhen is not about whether someone is upright; it asks what their inner rules are and where the boundary lies. This code is self-discipline inward and demand outward; read both its steadiness when rules hold and its rebound when they are crossed.",
 cnLog:['廉贞为次桃花，也主官禄、规则与是非，落命者重名分、讲体面、对分寸敏感。','它的规则感是内在的：知道什么该做、什么不该做，也期待别人按同一套来。','守规则时它可靠、干净、有担当；一旦底线被触碰，反弹直接、不留情面。','廉贞的表现要看同宫与四化：2026丙午年廉贞化忌，主这一年原则感容易被卡住、在规则与人情间反复，单见一颗不断吉凶。'],
 enLog:["Lian Zhen is the secondary peach-blossom and also governs career, rules and right-and-wrong; those with it in the Life Palace care about status, face and propriety.","Its sense of rules is internal: it knows what should and should not be done, and expects others to follow the same code.","When rules hold it is reliable, clean and accountable; once a bottom line is crossed, its rebound is direct and unsparing.","Its expression depends on co-palace stars and transformations. In 2026 Bing-Wu, Lian Zhen is Hua Ji, suggesting that year's sense of principle gets stuck and tugged between rules and feelings; one star alone fixes no fortune."],
 cnStep:['先确认廉贞坐命或在三方，判断这是核心气质还是局部倾向','看同宫辅煞，分辨它的规则感是自律还是挑剔','找出它最在乎的那条底线：名誉、感情、还是公事','观察它守规矩时的稳定输出，和被越界时的反应','看大限流年四化是否引动廉贞，判断这一年是讲原则还是被原则卡住','用它的分寸感立边界，也提醒它别把人情都按尺子量'],
 enStep:["First confirm whether Lian Zhen is in the Life Palace or a triple-direction, telling core temperament from a local lean","See co-palace assistants and malefics to tell whether its rule-sense is self-discipline or nitpicking","Locate the bottom line it cares about most: reputation, relationships, or public duty","Observe its steady output when rules hold and its reaction when crossed","See whether decade or yearly transformations activate Lian Zhen, and whether the year upholds principles or gets stuck on them","Use its sense of measure to set boundaries, and remind it not to measure every relationship by a ruler"],
 cnMis:['见廉贞就断正派或不正派，不看它内在规则的具体内容','把它的反弹当脾气，不理解那是底线被踩','单见廉贞化忌就断大凶，忽略它只是原则感被卡住'],
 enMis:["Declaring upright or corrupt at the sight of Lian Zhen without asking what its inner rules actually are","Reading its rebound as mere temper rather than a crossed bottom line","Crying great misfortune at Lian Zhen Hua Ji alone, ignoring that it only means the sense of principle is stuck"],
 cnClose:'廉贞心里有一杆尺，量的是分寸与底线。这把尺拿来自律是可靠，拿去量所有人就容易累。知道它那条线在哪，比夸一句正派有用得多。',
 enClose:"Lian Zhen carries an inner ruler that measures propriety and bottom lines. Used for self-discipline it is reliable; used to measure everyone it wears one out. Knowing where that line sits is worth more than a word of praise for decency."},

{cat:'zhuxing',slug:'ziwei-taiyang-jumen-shuangxing-minggong',focus:'太阳巨门双星命宫',focusEn:'Tai Yang and Ju Men paired in the Life Palace',
 cnT:'紫微斗数太阳巨门同坐命宫：一颗发光，一张开口',
 enT:'Tai Yang and Ju Men Together in the Life Palace: One Shines, One Speaks',
 cnD:'太阳主光明、外放与表现，巨门主口舌、沟通与猜疑；两颗同坐命宫，化学反应是「要把话讲出去、还要让人看见」——靠表达、传播、辩论、涉外立身。太阳怕被遮，巨门怕被堵，叠在一起就是越说越亮、越压越疑。',
 enD:"Tai Yang governs light, outward expression and visibility, while Ju Men governs speech, communication and suspicion. Paired in the Life Palace, the chemistry is 'must speak out and be seen': making a living through expression, media, debate or cross-border work. Tai Yang fears being shaded and Ju Men fear being gagged; together they grow brighter when heard and more suspicious when suppressed.",
 cnL:'有人太阳巨门坐命，你让他闷头做幕后他浑身难受，给他一支话筒、一个镜头、一桌要谈的客户，他立刻活过来。这种人天生要靠嘴和脸吃饭，但也最容易因为一句话说错惹是非。',
 enL:"With Tai Yang and Ju Men in the Life Palace, being told to work unseen behind the scenes feels like confinement; hand them a mic, a camera or a table of clients and they come alive. They are born to make a living by speech and presence, yet they also court trouble most easily by one wrong sentence.",
 cnA:'这组双星要读的不是「太阳怎样、巨门怎样」，而是它们叠在一起的合力：光明加上口舌，等于「把事情讲清楚、讲出去」的能量。读盘看这股力往哪使——是去做传播与教学，还是陷入口舌与猜疑。',
 enA:"This pair is not read as 'Tai Yang this, Ju Men that' but as their combined force: light plus speech equals the energy to make things clear and to get them out. Read where that force is aimed—toward communication and teaching, or into quarrels and suspicion.",
 cnLog:['太阳外放，主名声、表现与照顾他人；巨门内敛，主口舌、钻研与暗地猜疑，一明一暗同宫。','合力是「要表达」：靠说话、写作、教学、谈判、涉外把自己立起来，也容易因言惹事。','太阳喜明朗，被煞忌遮则发光受阻；巨门喜被听见，被压则转向多疑、暗斗。','这组星的落点看同宫与三方：见科文则口才成章，见煞忌则口舌是非多，2026丙午年文昌化科，对以表达立身者是名声上的助力。'],
 enLog:["Tai Yang is outward, governing fame, performance and caring for others; Ju Men is inward, governing speech, research and hidden suspicion, one bright and one shaded in one palace.","Their combined force is 'the need to express': building oneself through speech, writing, teaching, negotiation and cross-border work, while courting trouble by words.","Tai Yang likes openness and is blocked when shaded by malefics and Hua Ji; Ju Men likes being heard and turns to suspicion and infighting when suppressed.","Their expression depends on co-palace and triple-direction stars: scholarly stars turn speech into craft, malefics and Hua Ji multiply quarrels. In 2026 Bing-Wu, Wen Chang is Hua Ke, aiding reputation for those who live by expression."],
 cnStep:['先确认太阳巨门是否同坐命宫，而不是分别在两宫','读这股「表达+发光」的合力往哪个领域使','看是否有昌曲科文，分辨是口才成章还是纯口舌','再看火铃羊陀，分辨是传播有力还是是非缠身','看大限流年引动时，这一年是上台表达还是封口受压','用它的合力：把话讲清楚讲出去，同时管住不该说的那句'],
 enStep:["First confirm Tai Yang and Ju Men truly share the Life Palace rather than sitting in two palaces","Read where the combined 'expression plus light' force is aimed","See whether scholarly stars like Chang Qu are present, telling crafted speech from mere quarrels","Then see fire, bell and blade malefics to tell forceful communication from tangled disputes","When decade or yearly limits activate them, judge whether the year goes on stage or is silenced","Use the combined force: speak clearly and get it out, while holding back the sentence that should not be said"],
 cnMis:['把两颗星分开介绍，不看它们叠加的化学反应','见巨门就断口舌是非，忽略它也主钻研与表达','见太阳就断大吉，忽略它被遮时发光受阻'],
 enMis:["Introducing the two stars separately without their combined chemistry","Crying quarrels at Ju Men while ignoring its research and expression side","Crying great luck at Tai Yang while ignoring that its light is blocked when shaded"],
 cnClose:'太阳给你光，巨门给你嘴，叠在一起就是要把话讲出去的人。让这股力流向讲台、镜头和谈判桌，它是表达者；堵住它、又让它瞎猜，它就变成了是非。',
 enClose:"Tai Yang gives the light and Ju Men the mouth; paired, this is someone who must speak out. Aim that force at the podium, the lens and the negotiation table and it is a communicator; gag it and feed it suspicion and it turns into a quarrel."},

{cat:'zhuxing',slug:'ziwei-tiantong-tianxiang-shuangxing-fuqi',focus:'天同天相双星夫妻',focusEn:'Tian Tong and Tian Xiang paired in the Spouse Palace',
 cnT:'紫微斗数天同天相坐夫妻宫：一个想舒服，一个要体面',
 enT:'Tian Tong and Tian Xiang in the Spouse Palace: One Wants Comfort, One Wants Decorum',
 cnD:'天同主享受、情绪与随和，天相主印星、辅佐与体面；两颗同坐夫妻宫，化学反应是「关系要舒服、也要被安排妥当」——配偶温和顾家、重分寸，但也可能懒得争、遇事想靠规矩兜住。',
 enD:"Tian Tong governs comfort, emotion and easygoingness, while Tian Xiang governs the seal, support and decorum. Paired in the Spouse Palace, the chemistry is 'a relationship that must feel comfortable and also be properly arranged': a spouse who is gentle, home-loving and mindful of propriety, yet may avoid conflict and lean on routine to cushion problems.",
 cnL:'夫妻宫坐天同天相的人，往往找的对象脾气好、会照顾人、把日子过得体体面面；可真遇到要拍板的大事，又容易发现对方「都行啊你看着办」，想推你出来扛。',
 enL:"When Tian Tong and Tian Xiang sit in the Spouse Palace, the partner tends to be good-tempered, caring and keeps life presentable; yet when a real decision is needed, one may find the other saying whatever you prefer, wanting to push you forward to carry it.",
 cnA:'这组双星要读的是关系里的合力：享受加上印星，等于「把日子过得舒服又体面」。它不是要你分别描述配偶性格，而是看这段关系是被温柔托住，还是被和稀泥拖慢。',
 enA:"Read this pair as the relationship's combined force: comfort plus the seal equals 'a life lived comfortably and decorously'. It is not about describing the spouse separately, but about whether the relationship is gently held or slowed down by avoiding conflict.",
 cnLog:['天同是福星，主享受、情绪与随和；天相是印星，主辅佐、文书与体面，一柔一稳同宫。','合力是「把关系安排得舒服又妥当」：配偶温和、顾家、重分寸，对外讲究体面。','天同懒于冲突，天相依赖章法，叠在一起就可能遇事不争、想靠规矩或对方来兜。','2026丙午年天同化禄，对夫妻宫坐这组星者，是这一年感情与居家舒服度加分的流年参照；但仍要看大限打底，不单凭一年下断。'],
 enLog:["Tian Tong is the blessing star, governing comfort, emotion and easygoingness; Tian Xiang is the seal star, governing support, paperwork and decorum, one soft and one steady in one palace.","Their combined force is 'arranging the relationship comfortably and properly': a spouse who is gentle, home-loving, mindful of measure and concerned with face.","Tian Tong avoids conflict and Tian Xiang leans on routine; together they may shy from fighting and expect rules or the other person to cushion things.","In 2026 Bing-Wu, Tian Tong is Hua Lu, which for those with this pair in the Spouse Palace is a yearly reference adding comfort to the relationship and home; still read the decade baseline and never judge by one year alone."],
 cnStep:['先确认天同天相是否同坐夫妻宫，而非分处两宫','读这股「舒服+体面」的合力落在关系的哪一面','看配偶是温和顾家，还是懒得拍板、遇事退让','看同宫辅煞，分辨是被温柔托住还是被和稀泥拖慢','看大限这十年感情关系在打底什么主题','叠看流年引动时，这一年是加分舒服还是要面对回避的问题'],
 enStep:["First confirm Tian Tong and Tian Xiang truly share the Spouse Palace rather than sitting apart","Read which side of the relationship the combined 'comfort plus decorum' force lands on","See whether the spouse is gentle and home-loving, or avoids decisions and yields under pressure","Check co-palace assistants and malefics to tell being gently held from being slowed by conflict avoidance","Read the decade's ten-year theme for the relationship","Layer the yearly limit to judge whether the year adds comfort or forces a dodged issue to the surface"],
 cnMis:['把两颗星分开讲配偶性格，不看叠加后的关系氛围','见天同天相就断婚姻美满，忽略遇事不争的隐患','只看某一年化禄就断定感情必顺，不看大限打底'],
 enMis:["Describing the spouse by each star separately without the combined relationship mood","Calling the marriage blessed at the sight of the pair while ignoring the conflict-avoidance risk","Declaring the relationship smooth from one year's Hua Lu while ignoring the decade baseline"],
 cnClose:'天同给感情加舒服，天相让关系讲体面，叠在夫妻宫就是想把日子过暖和又周全的人。舒服是福气，可要是连架都懒得吵、大事都推给对方，舒服也就变成了回避。',
 enClose:"Tian Tong adds warmth to the relationship and Tian Xiang insists on decorum; in the Spouse Palace this is someone who wants life cozy and well arranged. Warmth is a blessing, but if no conflict is ever raised and every big call is pushed to the other, warmth becomes avoidance."},

{cat:'liunian',slug:'ziwei-liunian-qianyi-gong-zhuxing',focus:'流年迁移宫主星',focusEn:'the major star in the yearly Travel Palace',
 cnT:'紫微斗数流年迁移宫主星：这一年外出、出差、换环境顺不顺',
 enT:'The Major Star in the Yearly Travel Palace: How Travel, Trips and Changing Environments Go in a Given Year',
 cnD:'迁移宫看在外、出行、人际外缘与环境适应；流年迁移宫主星，是当年这股「对外活动」能量的基调。它只提示这一年出门、出差、换环境时该顺还是该守，不能脱离本命与大限单独断吉凶。',
 enD:"The Travel Palace governs going out, trips, outer social reach and adapting to environments. The major star in the yearly Travel Palace sets the tone for that year's outward activity. It only suggests whether travel, business trips or changing environments should be pushed or held that year; it cannot be read for fortune apart from the natal chart and the decade limit.",
 cnL:'有人问「今年适不适合出差、能不能换城市」。别直接翻黄历式地答吉凶，先看今年流年迁移宫坐了哪颗主星，再叠本命迁移和这步大限的底子，三层合起来才说得出方向。',
 enL:"Someone asks whether this year suits business trips or a city move. Do not answer fortune like an almanac; first see which major star sits in this year's Travel Palace, then layer in the natal Travel Palace and the current decade's baseline. Only the three together point to a direction.",
 cnA:'迁移宫要回答的是「对外这一年顺不顺」：出门遇不遇贵人、换环境适不适应、在外是省力还是费力。它是短期基调，本命迁移才是长期底盘，两层不能混为一谈。',
 enA:"The Travel Palace asks how the outer year goes: whether trips meet helpful people, whether a new environment fits, whether being out costs or saves effort. It is a short-term tone; the natal Travel Palace is the long-term base, and the two must not be conflated.",
 cnLog:['本命迁移宫定长期的外缘与出行风格，是你这辈子对外的底盘。','大限迁移定这十年外出、换环境的大方向，是中期河床。','流年迁移宫坐的主星，是当年这股对外能量的触发点，短期生效。','三层叠看：本命与大限没有这股动能，流年迁移再旺也只是偶然出差；方向一致，才谈得上这一年适合动。'],
 enLog:["The natal Travel Palace sets the long-term outer reach and travel style, your lifelong outward base.","The decade Travel Palace sets the ten-year direction for going out and changing environments, the mid-term riverbed.","The major star in the yearly Travel Palace is that year's trigger of outward energy, short-lived.","Read the layers: without momentum in the natal and decade palaces, even a lively yearly Travel Palace is just occasional trips; only when they align does the year truly favor moving."],
 cnStep:['先找到本命迁移宫，看长期外缘与出行的底盘','再看当前大限迁移，定这十年对外活动的方向','找到今年流年迁移宫，看坐了哪颗主星','读这颗星提示的基调：是宜动、宜守还是宜贵人','叠看流年四化是否引动迁移宫，找具体触发点','三层方向一致才建议出行或换环境，否则给出条件式提醒'],
 enStep:["First find the natal Travel Palace and read the long-term outer base","Then read the decade Travel Palace for the ten-year outward direction","Locate this year's Travel Palace and see which major star sits there","Read that star's tone: favor moving, holding, or meeting helpful people","Layer in yearly transformations to see whether they activate the Travel Palace for a concrete trigger","Only when the three layers align do you advise travel or a move; otherwise give a conditional note"],
 cnMis:['只看流年迁移宫一颗星就断今年必出远门或必破财','把流年迁移的短期基调当成长期外缘结论','不叠本命与大限，孤立地读当年吉凶'],
 enMis:["Judging guaranteed long trips or losses from one star in the yearly Travel Palace alone","Treating the yearly Travel tone as a long-term conclusion on outer reach","Reading the year's fortune in isolation without the natal and decade layers"],
 cnClose:'流年迁移宫主星只是当年对外那一下的风向。本命和大限是船，流年迁移是风；船本身适合出海，风才有用。三层对得上，这一年出门换环境才值得动。',
 enClose:"The major star in the yearly Travel Palace is only that year's outward wind. The natal and decade palaces are the ship, the yearly Travel Palace the wind; the wind matters only if the ship is fit to sail. When the three align, a year of travel or change is worth moving for."},

{cat:'liunian',slug:'ziwei-liunian-sihua-feixing-jiedu',focus:'流年四化飞星解读',focusEn:'reading yearly four transformations and flying stars',
 cnT:'紫微斗数流年四化飞星：当年那四股力，飞进了哪几个宫',
 enT:'Reading the Yearly Four Transformations and Flying Stars: Which Palaces That Year\'s Four Forces Fly Into',
 cnD:'每年天干会触发一组流年四化（2026丙午年为天同化禄、天机化权、文昌化科、廉贞化忌），四股力飞进本命盘的四个宫，提示当年资源、主动权、名声与牵挂落在哪些领域；它是短期触发，不是改写本命格局。',
 enD:"Each year's stem triggers a set of yearly transformations (in the 2026 Bing-Wu year: Tian Tong Lu, Tian Ji Quan, Wen Chang Ke, Lian Zhen Ji). These four forces fly into four natal palaces, hinting where resources, initiative, reputation and attachment land that year; they are short-term triggers, not a rewrite of the natal pattern.",
 cnL:'每年换天干，盘上就会重新点亮四颗星。很多人只盯着自己本命那组四化，其实当年飞进来的禄权科忌，才是这一年具体哪件事被点着的引线。',
 enL:"Each year a new stem lights four stars on the chart. Many only watch their natal transformations, yet the yearly Lu, Quan, Ke and Ji that fly in are the fuses that ignite a specific matter that year.",
 cnA:'流年四化要追的是「飞进哪宫」：禄从哪宫补资源、权在哪宫给压力、科落在哪宫有名声、忌挂在哪宫让人操心。把四条飞行路线连成线，当年的主题就浮出来了。',
 enA:"Yearly transformations are traced by which palace they fly into: Lu tops up resources from where, Quan pressures where, Ke lends reputation where, and Ji attaches where. Connect the four flight paths and that year's theme surfaces.",
 cnLog:['流年四化按当年天干起，2026丙午年为天同化禄、天机化权、文昌化科、廉贞化忌，先记住这组。','化禄飞入某宫，提示当年那个领域有资源、机会或顺手的事。','化权飞入某宫，提示当年那个领域主动权在争、压力在扛；化科飞入则有名声、文书与缓冲。','化忌飞入某宫，提示当年那个领域反复操心、有牵挂要面对；但它是短期触发，要叠大限这十年是否本来就有这个课题。'],
 enLog:["Yearly transformations follow that year's stem. For 2026 Bing-Wu they are Tian Tong Lu, Tian Ji Quan, Wen Chang Ke and Lian Zhen Ji; start by memorizing this set.","Lu flying into a palace hints that area receives resources, opportunity or an easy break that year.","Quan flying in hints the area sees contested initiative and pressure; Ke flying in brings reputation, paperwork and cushion.","Ji flying in hints the area recurs as a worry one must face; but it is a short trigger, so layer whether the decade already carries that lesson."],
 cnStep:['先按当年天干查出这一年的流年四化是哪四颗星','逐颗标出化禄、化权、化科、化忌各自落在本命哪一宫','看禄从哪宫进资源，忌挂在哪宫让人操心','看权落在哪宫争主动，科落在哪宫有名声','叠看大限这十年本来在哪个领域打底，找交集','有交集才把当年四化断为真主题，给出条件式解读'],
 enStep:["First use the year's stem to find that year's four transformations","Mark into which natal palace each of Lu, Quan, Ke and Ji flies","See where Lu brings resources in and where Ji attaches the worry","See where Quan contests initiative and where Ke lends reputation","Layer the decade's baseline area to find the overlap","Only where they intersect do you call the yearly transformations a real theme, reading conditionally"],
 cnMis:['把流年四化当成改写本命格局的大吉大凶','只看化禄化喜、见化忌就怕，不追飞进飞出的宫位','忽略大限打底，孤立地用当年四化断一年顺逆'],
 enMis:["Treating yearly transformations as rewriting the natal pattern into great luck or doom","Cheering Lu and fearing Ji without tracing the palaces flown into and out of","Ignoring the decade baseline and judging a year's smoothness from yearly transformations alone"],
 cnClose:'流年四化是每年换的四股风，飞进你本命的四个宫。风往哪吹要看风向，更要看你的船这十年往哪开——风向对船，那一年的事才真的应在那个领域。',
 enClose:"Yearly transformations are four winds that change each year and fly into four natal palaces. Where the wind blows matters, but so does the direction your boat has sailed for the decade; when wind and boat agree, that year's matter truly lands in that area."},

{cat:'liunian',slug:'ziwei-daxian-gongwei-zhongdie',focus:'大限宫位重叠',focusEn:'overlap between natal and decade palaces',
 cnT:'紫微斗数大限宫位重叠：本命盘和十年盘叠在一起怎么读',
 enT:'Overlap Between Natal and Decade Palaces: How to Read the Native Chart Laid Over the Ten-Year Chart',
 cnD:'大限盘以某一宫为新命宫重排十二宫，再叠回本盘；重叠处就是这十年被放大的人生领域。本命是底子，大限是课题，重叠读两层——底子好不好看本命，这十年扛不扛得住看大限。',
 enD:"The decade chart takes one palace as its new Life Palace, rebuilds the twelve, and lays it over the native chart. Where they overlap is the life area magnified over the decade. The natal chart is the base; the decade is the lesson; read the overlap in two layers—whether the foundation is sound is natal, whether it holds up for these ten years is the decade.",
 cnL:'有人走某步大限，忽然觉得某个领域突然被放大了：明明本来平平，这十年却事事绕着它转。这往往就是大限命宫叠到了本命的某一宫，那个宫成了这十年的主角。',
 enL:"Entering a certain decade, someone suddenly feels one area magnified: it was unremarkable, yet these ten years revolve around it. This usually happens when the decade Life Palace overlaps a natal palace, making that palace the lead for the decade.",
 cnA:'宫位重叠要回答的是两件事：第一，这十年哪个领域被推到台前；第二，本命在那个领域的底子接不接得住。重叠不是简单叠加吉凶，而是「十年课题压在本命那块地基上」。',
 enA:"Palace overlap answers two things: which area is pushed to center stage for the decade, and whether the natal foundation in that area can carry it. Overlap is not simply adding fortune and misfortune; it is the decade's lesson pressing on a specific natal foundation.",
 cnLog:['大限以某宫为新命宫重排十二宫，形成一张十年小盘，再叠回本命盘看重叠。','重叠处=这十年被放大、必须面对的人生领域，是十年课题的落点。','本命该宫的星曜与格局，决定这块地基本身的厚薄与承接力。','读法是两层：本命看底子，大限看这十年的承接与触发；底子弱而大限又重压，才谈得上吃力，不单凭一层下断。'],
 enLog:["The decade takes one palace as its new Life, rebuilds the twelve into a ten-year mini chart, and lays it over the native chart.","The overlap is the life area magnified and forced to be faced over the decade, where the ten-year lesson lands.","The stars and pattern of that natal palace decide the thickness and carrying capacity of the foundation itself.","Read two layers: the natal for the foundation, the decade for that ten-year load and trigger; only a weak foundation under a heavy decade reads as strain, never from one layer alone."],
 cnStep:['先找到当前大限命宫落在哪一宫','把这宫当作新命宫，重排出大限十二宫','逐宫叠回本命盘，标出大限各宫压在本命哪一宫上','找出重叠最深、被大限四化引动的那一宫，定为十年课题','读本命该宫的底子：星曜、辅煞、本命四化如何','再叠流年：哪一年这个重叠点被当年触发，才是应期'],
 enStep:["First find where the decade Life Palace falls","Treat that palace as the new Life and rebuild the decade's twelve palaces","Layer each decade palace back onto the native chart and mark where it presses","Find the deepest overlap, activated by decade transformations, as the ten-year lesson","Read that natal palace's foundation: its stars, assistants, malefics and natal transformations","Then layer the year: only when a yearly limit triggers the overlap is it a timing"],
 cnMis:['把大限盘当成另一张命，忽略它叠在本命底子上','只看重叠处吉凶，不看本命那块地基的厚薄','把十年课题压成某一年必吉必凶，不分两层'],
 enMis:["Treating the decade chart as a separate fate, ignoring that it lies on the natal foundation","Reading only the overlap's fortune without the thickness of that natal foundation","Compressing a ten-year lesson into a guaranteed good or bad year, collapsing the two layers"],
 cnClose:'大限盘不是另起一命，是把十年的重量压在本命某块地基上。地基厚、课题顺，这十年走得稳；地基薄、又被流年反复触发，就得提前补。两层叠看，重叠处才读得懂。',
 enClose:"The decade chart does not start a new fate; it presses ten years of weight onto one natal foundation. Thick ground and a fitting lesson mean a steady decade; thin ground repeatedly triggered by yearly limits means shoring up early. Read the two layers together and the overlap makes sense."}
];
