// 2026-09-29 调研驱动 第5组：收入曲线/考运/置产/相处模式/桃花落实/子女创作/交友更替/职业转行 8篇
module.exports=[
{cat:'yingyong',slug:'ziwei-shouru-quxian-guaidian-daxian',focus:'收入曲线与拐点的判断',focusEn:'reading income curves and turning points',
 cnT:'紫微斗数收入曲线怎么看：早成、晚成与拐点，不承诺发财年龄',
 enT:'Reading Income Curves in Zi Wei Dou Shu: Early, Late and Turning Points Without Promising an Age',
 cnD:'收入节奏看财帛星与大限：财星刚、大限早走财线偏早成，星柔或要等大限引动偏晚成，星曜变动多偏波动。拐点多出现在大限走到财帛三方、化禄化权引动之时。但收入增长不等于净资产增长，还要看支出与留存；本文不构成投资建议，理财以持牌机构和正规产品说明为准。',
 enD:'Income timing is read from the Wealth stars and the decade: firm stars with an early wealth-running decade lean early, softer stars or those awaiting activation lean late, and many changing stars lean volatile. Turning points often appear when the decade reaches the Wealth trine and Lu or Quan activates. Yet higher income is not higher net worth, and spending and saving matter too; this is not investment advice, and finances defer to licensed institutions and official product terms.',
 cnL:'有人总问"我几岁能赚到钱"，其实命盘不写死年龄，写的是节奏——有人早、有人晚、有人一波一波，看懂曲线比等一个岁数靠谱。',
 enL:'Some ask at what age they will earn, but the chart does not fix an age; it writes a rhythm, early, late or wavy, and reading the curve beats waiting for a number.',
 cnA:'这个问题在问：怎么判断自己的收入拐点。先看财帛星性定早成晚成，再看大限何时走到财帛三方、有没有禄权引动，最后看留存，三处分清才不会把"加薪"当"变富"。',
 enA:'The question is how to judge the turning point: read Wealth-star nature for early or late, see when the decade reaches the Wealth trine with Lu-Quan activation, and finally check saving, so a raise is not mistaken for wealth.',
 cnLog:['财帛星性定基调：武曲、紫微偏早能扛，天同、天梁、太阴偏稳或晚成，贪狼、破军、天机偏波动。','大限定拐点：十年走到财帛宫三方、化禄化权引动，多是收入台阶出现的阶段。','流年流月定触发：禄权飞入财帛、官禄的具体年份月份，机会较实。','收入≠净资产：支出、负债与留存机制决定最后留得住多少，理财以持牌机构和正规产品说明为准。'],
 enLog:['Wealth-star nature sets the tone: firm stars carry early, steady stars lean stable or late, and changing stars lean volatile.','The decade sets the turning point: reaching the Wealth trine with Lu-Quan activation often brings an income step.','The year and month set the trigger: Lu-Quan flying into Wealth or Career at specific times makes opportunity real.','Income is not net worth: spending, debt and saving decide what remains, and finances defer to licensed institutions and official terms.'],
 cnStep:['先读财帛宫主星，判断早成、晚成或波动','再排大限，找走到财帛三方的十年','看该大限有无化禄化权引动收入线','用流年流月把拐点点到具体时段','同时评估支出、负债与留存','理财走持牌机构与正规产品，不据盘做投资决策'],
 enStep:['First read the Wealth stars for early, late or volatile timing','Then place decades to find one reaching the Wealth trine','Check whether Lu-Quan activates the income line','Use year and month to time the turning point','Also assess spending, debt and saving','Use licensed institutions and official products, not the chart for investment decisions'],
 cnMis:['把"几岁发财"当成固定答案','只看收入不看支出留存，误把加薪当变富','据盘做投资决策，忽略持牌机构与风险'],
 enMis:['Taking an age of riches as a fixed answer','Seeing income without spending and saving, mistaking a raise for wealth','Making investment decisions from the chart and ignoring licensed institutions and risk'],
 cnClose:'收入曲线看的是节奏不是岁数：星性定早成晚成、大限定拐点、流年定触发，再看支出留存。它不承诺发财，也不构成投资建议——顺势提升能力、管好现金流，台阶才踩得稳。',
 enClose:'The income curve is rhythm, not an age: star nature sets early or late, the decade the turning point and the year the trigger, then spending and saving. It promises no riches and is not investment advice; build skill and manage cash flow to step steadily.'},

{cat:'yingyong',slug:'ziwei-kaoyun-zenme-kan-wenchang-huake',focus:'考运与文昌化科的读法',focusEn:'exam luck and reading Wen Chang and Hua Ke',
 cnT:'紫微斗数考运怎么看：文昌文曲与官禄化科',
 enT:'How to Read Exam Luck in Zi Wei Dou Shu: Wen Chang, Wen Qu and Hua Ke in Career',
 cnD:'考运主要看文昌文曲（文书、思维、记忆）与官禄宫化科（名声、发挥、功名）。流年、大限昌曲明、化科引动，多主考试发挥稳、文书顺。但吉星管的是"临场发挥"，真正的底子仍是平时积累，不能只靠流年。',
 enD:'Exam luck mainly reads Wen Chang and Wen Qu, the stars of documents, thinking and memory, plus Hua Ke in Career for reputation, performance and scholarly standing. When the year or decade brightens these and Hua Ke activates, performance tends to be steady and paperwork smooth. Yet the stars govern composure on the day; the real base is still steady preparation, not the calendar alone.',
 cnL:'有人考前才查"今年有没有考运"，其实昌曲化科提示的是发挥状态，平时没积累，再好的流年也变不出分数。',
 enL:'Some check exam luck only before the test, but the stars indicate performance; without preparation even a bright year cannot produce scores.',
 cnA:'这个问题在问：考试这件事在盘上看什么。先看本命昌曲与官禄，定学习与发挥的底色，再看大限流年是否化科、昌曲引动，最后仍回到复习与作息。',
 enA:'The question is what a chart shows for exams: first read natal Chang-Qu and Career for the learning baseline, then see whether the decade or year brings Hua Ke and activation, and finally return to review and rest.',
 cnLog:['文昌文曲主文书、记忆、表达与条理，是"读书星"。','官禄宫化科主功名、名声与临场的稳定发挥。','大限流年昌曲得地、化科引动，考试、考证、申请文书多较顺。','它只主发挥与机缘，成绩仍取决于长期积累、方法与心态。'],
 enLog:['Wen Chang and Wen Qu govern documents, memory, expression and order, the study stars.','Hua Ke in Career governs scholarly standing, reputation and steady performance on the day.','When the decade or year grounds Chang-Qu and activates Ke, exams and applications tend to go smoothly.','It only governs performance and chance; results still depend on long preparation, method and state of mind.'],
 cnStep:['先看本命文昌文曲与官禄宫','判断学习能力与发挥的底色','再排大限流年，找化科与昌曲引动','把有利年份用于重要考试与申请','平时坚持积累、考前调好作息心态','不把吉星当免复习的保证'],
 enStep:['First read natal Chang-Qu and the Career Palace','Judge learning ability and the performance baseline','Then place the decade and year to find Hua Ke and Chang-Qu activation','Use favorable periods for major exams and applications','Keep steady preparation and tune rest and mindset','Do not take the stars as a promise to skip review'],
 cnMis:['只查流年考运、不看本命学习底子','见昌曲化科就以为不用复习','把考试成败全归于流年，忽略方法与积累'],
 enMis:['Only checking the year without the natal learning base','Assuming Chang-Qu and Ke mean no review is needed','Attributing exam results wholly to the year and ignoring method and preparation'],
 cnClose:'考运是"积累加发挥"：昌曲主读书思维、化科主临场功名，流年引动的是状态。底子靠平时、机会看运限，两者都到位，考试这关才走得稳。',
 enClose:'Exam luck is preparation plus performance: Chang-Qu govern study and thought and Ke the day standing, while the year activates state. The base comes from steady work and the chance from timing; with both, exams go steadily.'},

{cat:'yingyong',slug:'ziwei-tianzhai-hualu-huaji-zhichan-shiji',focus:'田宅禄忌与置产售产时机',focusEn:'Lu and Ji in the Property Palace and timing for buying and selling',
 cnT:'紫微斗数田宅化禄化忌：买房、卖房的时机怎么判断',
 enT:'Lu and Ji in the Property Palace in Zi Wei Dou Shu: Timing Buying and Selling',
 cnD:'田宅宫化禄、化权，主宅运稳、置业顺、易持有好资产；化忌主宅动——可能是卖房、搬家，也可能是手续、合同、贷款上的纠缠。置产时机再叠大限是否走到田宅、禄权引动。本文不构成投资建议，买房合同与贷款以专业律师、正规途径和书面合同为准。',
 enD:'Lu or Quan in the Property Palace means steady home luck, smooth purchases and holding good assets; Ji means property movement, possibly selling or moving, but also tangles in procedures, contracts or loans. Layer whether the decade reaches Property with Lu-Quan activation. This is not investment advice, and purchase contracts and loans rely on a qualified lawyer, proper channels and a written agreement.',
 cnL:'有人买房只看房价行情，其实命盘上田宅宫的禄忌提示"这阶段适不适合动房产"，时机对、手续顺，比硬上要稳。',
 enL:'Some buy only by market price, but the Property Lu-Ji indicates whether this stage fits moving real estate; right timing and smooth procedures are steadier than forcing it.',
 cnA:'这个问题在问：怎么判断何时买、何时卖。先读田宅宫四化，再看大限是否引动田宅，最后把合同、贷款、产权核实清楚，禄忌只给倾向，不替你做决策。',
 enA:'The question is when to buy or sell. Read Property transformations, see whether the decade activates it, and verify contracts, loans and title; Lu-Ji only gives tendency rather than deciding for you.',
 cnLog:['田宅化禄：宅运稳、置业较顺、易遇合适房源，喜持有。','田宅化权：对房产掌控欲强、决策主动，适合在专业把关下择机。','田宅化忌：主宅动（售、搬）或手续、贷款、合同纠缠，宜慢、宜核。','大限走到田宅且禄权引动多为置产窗口；合同贷款以律师与书面为准，不构成投资建议。'],
 enLog:['Property Lu: steady home luck, smoother purchases and fitting listings, favoring holding.','Property Quan: strong control and active decisions, best with professional checks.','Property Ji: property movement or tangles in procedures, loans and contracts, favoring slowness and verification.','A decade reaching Property with Lu-Quan activation is often a buying window; contracts and loans rely on lawyers and writing, and this is not investment advice.'],
 cnStep:['先读田宅宫的禄权科忌','再排大限，看是否走到田宅、引动置产','化禄权且大限引动多为买、持的窗口','化忌则防宅动与手续贷款纠缠','合同、贷款、产权交专业律师与书面核实','不据盘做房产投资决策，以正规产品和机构为准'],
 enStep:['First read Lu, Quan, Ke and Ji in Property','Then place decades to see whether Property is activated','Lu-Quan with decade activation is often a buy-and-hold window','With Ji, guard against movement and procedure-loan tangles','Leave contracts, loans and title to qualified lawyers and writing','Do not make property investment decisions from the chart; use proper institutions'],
 cnMis:['见田宅化禄就当稳赚、闭眼买','化忌一律当不能买房，忽略它可能只是手续要慢','买房不核合同贷款、不找律师，只凭流年'],
 enMis:['Taking Property Lu as guaranteed gain and buying blindly','Taking Ji as never buy, ignoring it may only mean slower procedures','Buying without checking contracts and loans or consulting a lawyer, relying only on the year'],
 cnClose:'田宅禄忌给的是房产的节奏：禄权逢大限引动宜买宜持，化忌防宅动与手续纠缠。它不构成投资建议，合同贷款走律师与书面，时机和手续都稳，置产才踏实。',
 enClose:'Property Lu-Ji gives real-estate rhythm: Lu-Quan with decade activation favors buying and holding, while Ji guards movement and procedure tangles. It is not investment advice; use lawyers and writing for contracts and loans so timing and paperwork are both steady.'},

{cat:'ganqing',slug:'ziwei-fuqi-xiangchu-moshi-hudong-wendu',focus:'夫妻宫星曜决定的相处模式',focusEn:'relationship patterns set by the Spouse Palace stars',
 cnT:'紫微斗数夫妻相处模式：主星决定互动的温度',
 enT:'Relationship Patterns in Zi Wei Dou Shu: How the Spouse Stars Set the Interaction',
 cnD:'夫妻宫主星不只描述配偶类型，更描述两人进入关系后的互动温度：星刚多直来直去、星柔多体贴迁就、星变动多新鲜也多变数。先读夫妻宫主星，再合命宫看两人的相处方式，关系的磨合重点就清楚了。',
 enD:'The Spouse Palace stars describe not only the partner type but the interaction temperature after entering the relationship: firm stars are direct, soft stars considerate and accommodating, and changing stars bring freshness and variation. Read the Spouse stars, then combine Life to see how the two relate and where the磨合 focus lies.',
 cnL:'有人只看配偶"是什么类型"，却不看两人怎么相处，其实关系能不能长久，更多写在互动模式里，而不是单看谁好谁坏。',
 enL:'Some only see the partner type and not how the two relate; whether a bond lasts is written more in the interaction pattern than in who is good or bad.',
 cnA:'这个问题在问：怎么判断两人合不合、怎么处。先读夫妻宫主星定互动温度，再看命宫主星与夫妻星是相生还是相冲，最后用大限看关系被引动的阶段。',
 enA:'The question is how to judge fit and how to relate: read Spouse stars for interaction temperature, see whether Life and Spouse support or clash, and use the decade for when the bond is activated.',
 cnLog:['夫妻宫星刚（紫微、武曲、七杀）：互动偏直接、讲原则，也易硬碰硬。','星柔（天同、太阴、天相）：互动偏体贴、迁就、重和谐。','星变动（贪狼、破军、天机）：互动多新鲜、想法多，也需防变数与不定。','命宫与夫妻星合看：相生则处得顺，相冲则要学会彼此的语言。'],
 enLog:['Firm Spouse stars make interaction direct and principled, with a risk of hard meeting hard.','Soft stars make it considerate, accommodating and harmony-focused.','Changing stars bring freshness and many ideas, guarding against instability.','Read Life with Spouse: supportive stars relate smoothly and clashing stars require learning each other language.'],
 cnStep:['先读夫妻宫主星，定互动温度','再读命宫主星，看自己在关系里的样子','判断命宫与夫妻星是相生还是相冲','相生处发挥，相冲处找磨合点','用大限流年看关系在哪个阶段被引动','相处重在沟通与适应，不凭一星断好坏'],
 enStep:['First read Spouse stars for interaction temperature','Then read Life stars for how you show in the bond','Judge whether Life and Spouse support or clash','Build on support and find磨合 points in clashes','Use the decade and year to see when the bond activates','Focus on communication and adaptation, not judging from one star'],
 cnMis:['只看配偶类型，不读互动模式','把命宫夫妻星相冲一律当不合','凭一颗星断言婚姻好坏，不看磨合与运限'],
 enMis:['Only seeing partner type and not interaction','Taking Life-Spouse clash as always incompatible','Declaring marriage fortune from one star without磨合 and timing'],
 cnClose:'夫妻相处看互动温度：夫妻星定基调、命星看自己，相生相冲决定怎么处。关系不是"配出来"的，是处出来的——读懂模式、用心磨合，比找一个"完美类型"更靠谱。',
 enClose:'Relationships are read through interaction: Spouse stars set the tone and Life stars show yourself, with support or clash deciding how to relate. Bonds are lived rather than matched; reading the pattern and working through it beats seeking a perfect type.'},

{cat:'ganqing',slug:'ziwei-taohuaxing-jihui-luoshi-qufen',focus:'桃花星的机会与关系落实',focusEn:'peach-blossom stars, opportunity and making a relationship real',
 cnT:'紫微斗数桃花星出现时：怎么分「认识机会」与「关系落实」',
 enT:'Peach Blossom Stars in Zi Wei Dou Shu: Meeting Opportunity vs. Making It Real',
 cnD:'红鸾天喜、天姚咸池、贪狼等桃花星动，多主人缘、邂逅与机会增多，但不等于一定恋爱或结婚。认识机会看桃花星，关系能否落实要看夫妻宫稳不稳、福德是否相应，再用大限流年确认时机，两层分开才不会一见桃花就冲。',
 enD:'When peach-blossom stars such as Hong Luan Tian Xi, Tian Yao Xian Chi or Tan Lang move, social ties, encounters and opportunities increase, but that does not guarantee a relationship or marriage. Meeting opportunity reads the blossom stars, while whether it becomes real depends on a steady Spouse Palace and matching Fortune, with the decade and year confirming timing; keep the layers separate.',
 cnL:'有人流年桃花星一亮就以为"今年必脱单"，其实桃花管的是机会多不多，能不能成还要看夫妻宫与时机。',
 enL:'Some assume bright blossom stars mean a relationship this year, but they govern opportunity; whether it forms still depends on Spouse and timing.',
 cnA:'这个问题在问：桃花来了怎么判断是缘分还是过客。先看桃花星带来的机会，再看夫妻宫与福德的底色，最后用大限流年找关系落实的窗口。',
 enA:'The question is how to tell a real bond from a passing encounter: first see the opportunity, then the Spouse and Fortune baseline, and finally use the decade and year to find the window to make it real.',
 cnLog:['红鸾天喜主正当喜庆缘分，天姚咸池、贪狼主人际魅力与邂逅，各有侧重。','桃花星动多应在机会、人缘、应酬增多的阶段。','关系落实要看夫妻宫星曜是否稳、福德是否相应，以及大限的承接。','流年桃花只给"相遇的可能"，不替你保证结果。'],
 enLog:['Hong Luan Tian Xi govern proper happy ties, while Tian Yao Xian Chi and Tan Lang govern social charm and encounters.','Blossom activation usually shows in more opportunity, social ties and events.','Making it real depends on steady Spouse stars, matching Fortune and decade support.','Annual blossom only gives the possibility of meeting, not a guaranteed result.'],
 cnStep:['先认出流年大限引动了哪些桃花星','把它理解为机会与人缘增多','再读夫妻宫星曜，判断关系能否稳','看福德与命宫是否相应','用大限流年找落实的时间窗口','不因桃花动就急于确定或否定'],
 enStep:['First identify which blossom stars the decade or year activates','Read it as more opportunity and social ties','Then read Spouse stars to see whether a bond can steady','See whether Fortune and Life match','Use the decade and year to find the window to make it real','Avoid rushing to confirm or deny because blossoms move'],
 cnMis:['一见桃花星就断定今年必恋爱','把所有桃花当烂桃花、一律回避','只数桃花不看夫妻宫与时机'],
 enMis:['Declaring a relationship this year at the sight of blossom stars','Treating all blossoms as bad and avoiding them','Counting blossoms without reading Spouse and timing'],
 cnClose:'桃花星管"相遇的机会"，夫妻宫与运限管"关系的落实"。机会来了先看清、再确认稳定性与时机，缘分是真是过客，分两层读，才不会错过也不会错付。',
 enClose:'Blossom stars govern the chance to meet, while Spouse and timing govern making it real. When opportunity comes, read clearly and confirm stability and timing; tell true bonds from passing ones in two layers so you neither miss nor give wrongly.'},

{cat:'liuqin',slug:'ziwei-zinv-kan-chuangzuo-jiaoxue-dairen',focus:'子女宫看创作教学与带人',focusEn:'the Children Palace for creation, teaching and mentoring',
 cnT:'紫微斗数子女宫不只看孩子：创作、教学、学生与长期项目',
 enT:'Beyond Children: Creation, Teaching, Students and Long Projects in the Zi Wei Dou Shu Children Palace',
 cnD:'子女宫除了亲生子女，还代表学生、门徒、被你带的人，以及你正在培养的作品与长期项目。子女宫星曜吉、有力，主教学相长、创作有成果、带人得力；它与田宅相对，一头是你培育的人和成果，一头是承接它们的家与资产。',
 enD:'Besides biological children, the Children Palace represents students, disciples, people you mentor and the works and long projects you are cultivating. Auspicious, strong stars there mean teaching that deepens you, fruitful creation and able mentees; it opposes Property, one side being the people and results you nurture and the other the home and assets that hold them.',
 cnL:'有人以为子女宫只跟生孩子有关，其实"你培养的一切"都在这——学生、团队新人、作品、做了很久的项目，都是它的范围。',
 enL:'Some think the palace concerns only children, but everything you cultivate belongs there: students, new teammates, works and long projects.',
 cnA:'这个问题在问：子女宫在现代怎么用。看创作成果、教学带人，也看长期投入的项目，先读子女宫星曜，再合田宅看成果有没有地方落地。',
 enA:'The question is how to use it now: read creative results, teaching and mentoring and long projects, first reading the stars, then combining Property to see where results land.',
 cnLog:['子女宫传统主子女，现代延伸到学生、门徒、下属新人与被培养者。','也主创作成果、作品与"投入很久、慢慢长大"的项目。','星曜庙旺吉会，教学、带人、创作多能有所成。','与田宅相对：培育的人和成果，最终要落到家庭、空间或资产上承接。'],
 enLog:['Traditionally it governs children, extended now to students, disciples and new teammates being cultivated.','It also governs creative results, works and projects invested in for a long time.','Exalted stars with auspicious meetings favor teaching, mentoring and creation.','It opposes Property: the nurtured people and results finally land in a home, space or assets.'],
 cnStep:['先定位子女宫及其星曜（空宫借田宅星）','把范围从子女扩到学生、门徒、新人','再纳入作品与长期项目','看星曜吉凶判断教学创作是否得力','合田宅宫看成果在哪落地承接','结合大限看培育之事在哪个阶段收成'],
 enStep:['First locate the Children Palace and stars, borrowing Property stars if empty','Expand the scope from children to students, disciples and new teammates','Then include works and long projects','Read the stars to judge teaching and creation','Combine Property to see where results land','Use the decade to see when cultivated matters are harvested'],
 cnMis:['把子女宫窄化为只看生育','忽略学生、作品、长期项目这一层','只看子女星不合田宅，读不到成果的承接'],
 enMis:['Narrowing it to only childbearing','Missing students, works and long projects','Reading only the stars without Property and the landing of results'],
 cnClose:'子女宫是"培育宫"：孩子之外，学生、门徒、作品、长期项目都归它。星曜得力则教学创作有成，再合田宅看承接——你用心培养的东西，才知道最终落在何处。',
 enClose:'The Children Palace is the cultivation palace: beyond children, students, disciples, works and long projects belong there. Strong stars favor teaching and creation, then Property shows the landing, so you know where what you nurture finally rests.'},

{cat:'gongwei',slug:'ziwei-jiaoyou-chengnian-quanceng-gengti',focus:'交友宫看成年后圈层更替',focusEn:'the Friends Palace and adult circle turnover',
 cnT:'紫微斗数成年后朋友「换挡」：交友宫看圈层的更替',
 enT:'Friendship Gear Shifts in Adulthood in Zi Wei Dou Shu: Reading Circle Turnover',
 cnD:'交友宫（仆役宫）主人际圈层与关系的更替。成年后因工作责任、搬家、婚育、转职，共同场景消失，朋友变少或换圈，多是关系在换挡，不等于人际失败。读交友宫星曜，看自己在关系里的角色，也看新连接从哪来。',
 enD:'The Friends Palace governs social circles and relationship turnover. In adulthood, work duties, moving, marriage and career shifts remove shared scenes, so friends thin or circles change, often a gear shift rather than social failure. Read the Friends stars for your role in relationships and where new connections arise.',
 cnL:'有人三十岁后发现朋友少了，就怀疑自己不会做人，其实很多关系只是被生活阶段带走了，不是谁的错。',
 enL:'Some find fewer friends after thirty and doubt their social skill, but many relationships are simply carried away by a life stage, no one at fault.',
 cnA:'这个问题在问：怎么看待成年后的关系变化。先读交友宫星曜定人际模式，再看大限流年引动的圈层变化，最后主动建立与当下生活相应的新连接。',
 enA:'The question is how to view adult relationship change: read Friends stars for the social pattern, see the circle changes the decade and year bring, and actively build new connections fitting the present life.',
 cnLog:['交友宫主朋友、同事、圈层与各类合作往来。','成年后共同场景（同事、同城、同阶段）变化，关系自然分流。','大限走到交友或化禄化科引动，多是结识新圈、修复旧缘的阶段。','关系换挡非失败：理解角色、留出主动经营的精力即可。'],
 enLog:['The Friends Palace governs friends, colleagues, circles and cooperative exchanges.','In adulthood shared scenes change and relationships naturally divide.','When the decade reaches Friends or Lu-Ke activates, new circles form and old ties can repair.','Gear shifts are not failure: understand the role and keep energy to tend ties actively.'],
 cnStep:['先读交友宫主星，定自己在关系中的角色','体会成年后圈层为何分流','再排大限流年，看交友宫何时被引动','禄科引动时主动结识新连接','对值得的旧缘保持轻量联系','不因朋友变少就否定自己的人际能力'],
 enStep:['First read Friends stars for your role in relationships','See why adult circles divide','Then place the decade and year for when Friends activates','When Lu-Ke activates, build new connections actively','Keep light contact with worthwhile old ties','Do not deny your social ability because friends thin'],
 cnMis:['把朋友减少一律当个人失败','只被动接受关系流失、不主动建新连接','误读交友宫，把圈层更替当人缘差'],
 enMis:['Taking fewer friends as personal failure','Passively accepting loss without building new ties','Misreading the palace and taking turnover as poor social fortune'],
 cnClose:'成年后朋友换挡是常态：交友宫写的是圈层与更替，生活阶段带走一些、也带来一些。读懂角色、主动经营新连接，关系少而不浅，比抱着"朋友必须越来越多"更自在。',
 enClose:'Friendship gear shifts in adulthood are normal: the palace writes circles and turnover, with life stages taking some and bringing others. Read your role and build new ties actively; fewer but deeper relationships are more at ease than demanding ever more friends.'},

{cat:'yingyong',slug:'ziwei-zhiye-xuanze-zhuanxing-guanlu-qianyi',focus:'职业选择与转行方向的判断',focusEn:'career choice and the direction of a career change',
 cnT:'紫微斗数职业选择与转行：官禄看做事方式、迁移看外部机会',
 enT:'Career Choice and Change in Zi Wei Dou Shu: Career Shows How You Work and Travel Shows Outer Chance',
 cnD:'选职业、看转行，先读官禄宫——它写你适合的做事方式与岗位类型；再读迁移宫——外部机会、平台与异地；财帛则看收入形态（固定还是波动）。三者合起来定方向，再用大限流年看转行的时机，比只凭"喜不喜欢"稳。',
 enD:'For career choice or change, first read the Career Palace, which shows how you best work and the role type; then Travel for outer opportunity, platform and far places; Wealth shows the income form, fixed or variable. The three set direction, and the decade and year set timing, steadier than liking alone.',
 cnL:'有人转行只问"我想不想"，结果换了才发现做事方式不合、收入不稳，其实官禄、迁移、财帛三宫早就写着适合的形态。',
 enL:'Some change only by wanting to, then find the work style unfit and income unstable; Career, Travel and Wealth already show the fitting form.',
 cnA:'这个问题在问：怎么判断该往哪个方向转。先看官禄定做事方式，再看迁移找外部平台，财帛定收入偏好，最后用大限确认时机与承接。',
 enA:'The question is which direction to take: Career sets the work style, Travel finds the outer platform and Wealth the income preference, and the decade confirms timing and support.',
 cnLog:['官禄宫星曜定"怎么做事"：开创、规划、协调、执行各有适配岗位。','迁移宫定外部舞台：平台大小、异地或对外的机会。','财帛宫定收入形态：稳定俸禄型还是项目波动型。','大限引动官禄、迁移且禄权相会，多是转行或晋升较顺的窗口。'],
 enLog:['Career stars set how you work, with roles fitting initiative, planning, coordination or execution.','Travel sets the outer stage: platform size and far or outward opportunity.','Wealth sets the income form: steady salary or project-based variation.','When the decade activates Career or Travel with Lu-Quan meeting, change or promotion tends to have a smoother window.'],
 cnStep:['先读官禄宫主星，定做事方式与岗位','再读迁移，看外部平台与异地机会','读财帛，确认收入形态偏好','三者合起来定职业方向','用大限流年找转行或晋升的窗口','转行结合自身积累，不凭一时冲动'],
 enStep:['First read Career stars for work style and role','Then read Travel for platform and far opportunity','Read Wealth to confirm income-form preference','Combine the three to set direction','Use the decade and year to find change or promotion windows','Change with your accumulated base, not on a passing impulse'],
 cnMis:['只凭喜好或一时情绪转行','只看官禄不看迁移财帛，方向判断不全','忽略大限时机，硬在逆风期转'],
 enMis:['Changing only on liking or passing emotion','Reading only Career without Travel and Wealth','Ignoring decade timing and forcing a change against the trend'],
 cnClose:'职业选择是三宫合看：官禄定做事方式、迁移找外部机会、财帛看收入形态，再用大限定时机。方向对、时机到、积累够，转行这步才走得稳。',
 enClose:'Career choice reads three palaces: Career sets how you work, Travel finds outer chance and Wealth the income form, with the decade setting timing. Right direction, timing and accumulated base make a career change steady.'}
];
