// 2026-09-29 调研驱动 第4组：解神坐命/解神官财/天巫坐命/天厨财官/天才坐命/左右疾厄/昌曲疾厄/天空别地空 8篇
module.exports=[
{cat:'fuzhu',slug:'ziwei-jieshen-zai-minggong',focus:'解神坐命的转圜化解力',focusEn:'Jie Shen in the Life Palace and its power to turn things around',
 cnT:'紫微斗数解神坐命：逢凶化吉、擅长转圜的人',
 enT:'Jie Shen in the Life Palace in Zi Wei Dou Shu: Turning Trouble Around',
 cnD:'解神主逢凶化吉、解围与转圜。坐命的人性情偏豁达、不死磕，遇到僵局能换个角度、找台阶、寻转机，难处常出现缓冲与援手。但它给的是"化解的机会"，不是"无灾"，转机仍要主动去促成。',
 enD:'Jie Shen governs turning trouble into good, lifting sieges and finding a way through. In the Life Palace a person tends to be open rather than rigid, able to change angle, find a graceful exit and seek a turning point, with buffers and help in difficulty. Yet it offers a chance to resolve, not an absence of trouble, and the turn must still be actively made.',
 cnL:'有人命宫带解星，遇事总比旁人"想得开"，其实这是化解之星——它不替你挡事，但让你更容易找到转圜的缝。',
 enL:'Some with Jie Shen take things more in stride; it does not block events but makes a way through easier to find.',
 cnA:'这个问题在问：解神坐命到底体现在哪。一是心态不死磕、能转弯，二是遇困常有人或事带来缓冲，三是擅长调解与化解，但逢煞忌时转机来得晚、要多费周折。',
 enA:'The question is how it shows: a mind that can turn, buffers that appear in difficulty, and a talent for mediation, though with malefics the turn comes later and needs more effort.',
 cnLog:['解神（天解）化气为"解"，主化解、转圜、解围、逢凶有缓冲。','坐命者性格较豁达、能进退，不钻牛角尖，擅长给人也给自己找台阶。','遇到僵局、纠纷或难关，常出现中间人、新条件或时间差，让事情松动。','逢煞忌、化忌同宫则化解力打折、转机延迟，更要靠主动沟通与分步处理。'],
 enLog:['Jie Shen turns toward resolving, easing, lifting and buffering trouble.','In Life the temperament is open, able to advance and retreat and find a graceful exit for self and others.','In deadlocks and disputes, a go-between, new conditions or timing often loosen things.','With malefics the resolving power is discounted and delayed, requiring active talk and step-by-step handling.'],
 cnStep:['先确认命宫是否带解神（空宫看借星与杂曜）','体会其不死磕、能转弯的心态','遇困时主动找缓冲、中间人或新条件','把大问题拆小，先松动一角','逢转机延迟则多给时间、分步推进','不把解神当"无灾保证"，仍要正面处理'],
 enStep:['First confirm Jie Shen in the Life Palace, checking borrowed stars if empty','Note the non-rigid, turning mind','In difficulty, actively seek buffers, go-betweens or new conditions','Break large problems smaller and loosen one corner first','If the turn delays, allow time and move in steps','Do not take it as a guarantee of no trouble; still face the matter'],
 cnMis:['把解神当"灾星不侵"的护身符','只等转机却不主动沟通促成','见解神与煞同宫就以为化解无效'],
 enMis:['Taking it as a charm against all trouble','Only waiting for a turn without actively helping it','Assuming Jie Shen with a malefic cannot resolve anything'],
 cnClose:'解神坐命给的是"转圜力"：心态能转弯、遇困有缓冲、善调解。它不保证无灾，但让僵局更容易松动——主动找台阶、分步处理，这份化解力才真正用得上。',
 enClose:'Jie Shen in Life gives a power to turn: a flexible mind, buffers in trouble and a gift for easing things. It does not guarantee no trouble, but deadlocks loosen more readily; actively find the exit and move in steps to use it well.'},

{cat:'fuzhu',slug:'ziwei-jieshen-guanlu-caibo',focus:'解神在官禄财帛的解围力',focusEn:'Jie Shen in the Career and Wealth Palaces and its rescue power',
 cnT:'紫微斗数解神在官禄、财帛：工作与钱财上的解围之力',
 enT:'Jie Shen in the Career and Wealth Palaces in Zi Wei Dou Shu',
 cnD:'解神在官禄，工作遇瓶颈或危机常有转圜、善解围，适合协调、危机处理与善后；在财帛，钱财纠纷、误付、破财多有补救与回旋，但不主横财。涉及合同、借贷纠纷，仍以专业律师和正规途径、书面合同为准。',
 enD:'In Career, bottlenecks and crises often find a way through, suiting coordination and handling the aftermath; in Wealth, money disputes and losses find remedy and room to maneuver, though not windfalls. For contract or loan disputes, rely on a qualified lawyer, proper channels and a written contract.',
 cnL:'有人官禄、财帛带解星，工作和钱上的"烂摊子"总能慢慢收拾，其实这是解围之力，给的是补救与转圜，不是不出事。',
 enL:'Some with Jie Shen in Career or Wealth can gradually clean up messes; it is rescue power offering remedy and room, not freedom from trouble.',
 cnA:'这个问题在问：解神落事业、钱财宫具体怎么用。官禄看危机转圜与善后，财帛看纠纷补救与破财回补，都要主动处理并留好书面凭据，不能只等它自己解。',
 enA:'The question is how it works in Career and Wealth: the former handles crisis and aftermath and the latter remedies disputes and losses, both requiring active handling and written records rather than waiting.',
 cnLog:['解神在官禄：项目卡壳、岗位危机或善后事宜多有转圜，适合协调、调解、风控与危机处理岗。','解神在财帛：误付、纠纷、破财有补救余地，宜留凭证、走正规流程追回。','它不主"不亏"，而主"亏了能补、僵了能转"。','合同、借贷、合伙的分歧，最终以专业律师、正规途径和书面合同为准，解神只提示有转圜空间。'],
 enLog:['In Career, stalled projects and crises find room to turn, suiting coordination, mediation and risk-control roles.','In Wealth, mistaken payments, disputes and losses have remedy, best handled with records and proper procedures.','It does not promise no loss but that loss can be remedied and deadlocks turned.','Contract, loan and partnership disputes ultimately rely on a qualified lawyer, proper channels and a written contract; Jie Shen only signals room to turn.'],
 cnStep:['先定位解神落在官禄还是财帛','官禄则看危机转圜、善后与协调的机会','财帛则看纠纷补救、破财回补的空间','主动留凭证、走正规流程','合同借贷分歧交给专业律师与书面合同','结合大限流年看转圜出现在哪个阶段'],
 enStep:['First locate Jie Shen in Career or Wealth','In Career, look for crisis resolution and coordination','In Wealth, look for dispute remedy and recovery','Actively keep records and use proper procedures','Leave contract and loan disputes to a qualified lawyer and writing','Use the decade and year to see when the turn appears'],
 cnMis:['把解神官财当"只赚不亏"','钱财纠纷只等自解，不留凭证不走流程','合同借贷靠"有转机"就不找律师、不立字据'],
 enMis:['Taking it as only gains and no losses','Waiting for money disputes to self-resolve without records or process','Relying on a turning point for contracts without a lawyer or writing'],
 cnClose:'解神在官禄财帛是"善后与补救"之力：工作危机能转、钱财纠纷能补，但不保证不出事。主动处理、留好凭据，合同借贷走律师与书面，转圜才落得了地。',
 enClose:'Jie Shen in Career or Wealth is aftermath and remedy: work crises can turn and money disputes be remedied, but trouble is not prevented. Handle actively, keep records and use lawyers and writing for contracts so the turn becomes real.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-minggong',focus:'天巫坐命的直觉与传承缘',focusEn:'Tian Wu in the Life Palace and its intuition and inheritance ties',
 cnT:'紫微斗数天巫坐命：直觉、传承与玄学缘分',
 enT:'Tian Wu in the Life Palace in Zi Wei Dou Shu: Intuition, Inheritance and Metaphysical Ties',
 cnD:'天巫主直觉、灵感、传承、提拔与玄学宗教之缘。坐命的人感受力强、常凭直觉判断，对历史、命理、宗教、哲学或家学有兴趣，也容易与继承、传承之事相遇、得上一辈提携。逢煞则防空想、不切实际与情绪起伏。',
 enD:'Tian Wu governs intuition, inspiration, inheritance, promotion and ties to metaphysics and religion. In Life a person is perceptive, often judging by instinct, drawn to history, metaphysics, religion, philosophy or family learning, and likely to meet inheritance matters and gain backing from elders. With malefics, guard against fantasy, impracticality and emotional swings.',
 cnL:'有人天巫坐命，对"看不见的东西"特别有感觉，也容易接手家传或师承的东西，关键是把直觉落到实处，别只停在空想。',
 enL:'Some with Tian Wu sense the unseen strongly and take up family or teacher traditions; the key is grounding intuition rather than staying in fantasy.',
 cnA:'这个问题在问：天巫坐命体现在哪。一是直觉与共鸣力强，二是与传承、继承、师承有缘、易被提拔，三是好神秘与学问，逢煞则灵感易散、想法难落地。',
 enA:'The question is how it shows: strong intuition and resonance, ties to inheritance and teaching with promotion, and an interest in mystery and learning; with malefics inspiration scatters and ideas do not land.',
 cnLog:['天巫化气为"传承"，主直觉、灵感、提拔、继承与玄学宗教缘分。','坐命者感受细腻、悟性较高，凭直觉与同理理解人和事。','与家学、师承、遗产或"接手前人之事"有缘，也易得长辈、上级赏识。','逢煞忌、天空则易空想、飘忽、情绪起伏，课题在"落地"与"验证"。'],
 enLog:['Tian Wu turns toward inheritance, governing intuition, inspiration, promotion, legacy and metaphysical ties.','In Life the person is perceptive and quick to understand people and matters through instinct and empathy.','They are tied to family learning, teaching, legacies or taking over prior work, and gain favor from elders and superiors.','With malefics it leans to fantasy, drifting and emotional swings; the lesson is grounding and verifying.'],
 cnStep:['先确认命宫是否带天巫','体会其直觉、共鸣与悟性','留意传承、继承、师承与被提拔的机会','把直觉当成线索，再用事实验证','发展学问、专业或创作让灵感落地','逢空想飘忽则练务实，避免只凭感觉'],
 enStep:['First confirm Tian Wu in the Life Palace','Note its intuition, resonance and quick understanding','Watch for inheritance, teaching and promotion opportunities','Treat intuition as a clue and verify with facts','Develop learning, profession or creation to ground inspiration','If drifting, practice practicality rather than relying on feeling'],
 cnMis:['把天巫直觉当"超能力"而不验证','只沉迷神秘学、不务实际','忽略传承缘分，也不接受提拔'],
 enMis:['Taking intuition as a power that needs no verification','Indulging only in mystery without practical grounding','Ignoring inheritance ties and refusing backing'],
 cnClose:'天巫坐命给的是直觉与传承缘：悟性高、感受细、易接上一辈的东西、也被人提携。把灵感当线索、用事实验证、落到专业里，这份天赋才不致流于空想。',
 enClose:'Tian Wu in Life gives intuition and inheritance: quick, perceptive, apt to take up prior work and gain backing. Treat inspiration as a clue, verify with facts and ground it in a profession so the gift does not drift into fantasy.'},

{cat:'fuzhu',slug:'ziwei-tianchu-caibo-guanlu-fenglu',focus:'天厨在财帛官禄的食禄俸禄',focusEn:'Tian Chu in Wealth and Career and its provision and salary',
 cnT:'紫微斗数天厨在财帛、官禄：食禄、俸禄与稳定供养',
 enT:'Tian Chu in the Wealth and Career Palaces in Zi Wei Dou Shu: Provision and Salary',
 cnD:'天厨主食禄、俸禄与饮食供养。在财帛，主稳定的"养命之财"、与餐饮食品或供养之利相关；在官禄，主俸禄稳、单位福利好、与饮食行业或后勤保障有缘。它偏"稳的供养"，不主投机暴富，理财仍以持牌机构和正规产品说明为准。',
 enD:'Tian Chu governs provision, salary and food-based support. In Wealth it means steady sustaining income tied to food, provisions or support; in Career it means a stable salary and benefits with ties to food industries or logistics. It leans to steady provision rather than speculative riches, and finances still defer to licensed institutions and official product terms.',
 cnL:'有人财官带天厨，收入未必大起但"饭碗稳、福利实"，其实这是食禄之星，主被供养、有定额，不主冒险发财。',
 enL:'Some with Tian Chu have modest but stable income and real benefits; it is the provision star of steady support, not risky riches.',
 cnA:'这个问题在问：天厨落财帛官禄怎么读。财帛看稳定养命之财与饮食相关收入，官禄看俸禄福利与餐饮/后勤缘，都是"稳"字当头，不宜用它去博高风险。',
 enA:'The question is how to read it: Wealth shows steady sustaining income and food-related earnings, while Career shows salary, benefits and ties to food or logistics, both centered on stability rather than high risk.',
 cnLog:['天厨（食神）化气为"养"，主食禄、俸禄、饮食与被供养。','在财帛：收入偏稳定、定额，与餐饮、食品、供养或民生之利相关。','在官禄：俸禄可靠、福利较实，适合餐饮、食品、后勤、保障或机构内岗位。','它不主投机暴富；相关理财以持牌机构和正规产品说明为准，不构成投资建议。'],
 enLog:['Tian Chu turns toward nourishing, governing provision, salary, food and being supported.','In Wealth income is steady and fixed, tied to dining, food, provisions or everyday needs.','In Career the salary is reliable and benefits real, suiting food, logistics or institutional roles.','It does not indicate speculative riches; finances defer to licensed institutions and official terms, and this is not investment advice.'],
 cnStep:['先定位天厨落在财帛还是官禄','财帛看稳定养命之财与饮食相关收入','官禄看俸禄福利与餐饮后勤缘分','体会其"稳的供养"，不博高风险','理财走持牌机构与正规产品','结合大限看俸禄与饭碗在哪个阶段更稳'],
 enStep:['First locate Tian Chu in Wealth or Career','In Wealth, read steady sustaining income and food-related earnings','In Career, read salary, benefits and food-logistics ties','Note the steady provision and avoid high-risk bets','Use licensed institutions and official products for finances','Use the decade to see when the salary and livelihood are steadiest'],
 cnMis:['把天厨当"发财星"去投机','只看食禄不看稳定，误判收入性质','理财不看持牌机构与产品说明'],
 enMis:['Taking it as a riches star for speculation','Missing the stability and misreading the income nature','Ignoring licensed institutions and product terms in finances'],
 cnClose:'天厨在财帛官禄主"稳的供养"：饭碗可靠、俸禄福利实在、与饮食民生有缘。它不主暴富，理财走正规持牌渠道，把这份稳接住，日子才踏实。',
 enClose:'Tian Chu in Wealth or Career means steady provision: reliable livelihood, real salary and benefits and ties to food and everyday needs. It does not indicate riches, so use licensed channels and keep the steadiness for a grounded life.'},

{cat:'fuzhu',slug:'ziwei-tiancai-zai-minggong',focus:'天才坐命的先天才智',focusEn:'Tian Cai in the Life Palace and innate talent',
 cnT:'紫微斗数天才坐命：领悟力强、天生聪明的人',
 enT:'Tian Cai in the Life Palace in Zi Wei Dou Shu: Quick Comprehension and Innate Intelligence',
 cnD:'天才主先天才智、聪明与领悟，贴近命宫布列。坐命的人反应快、举一反三、学东西上手快、有才气与巧思。但聪明要用在深耕上，逢煞则防"聪明反被聪明误"、浅尝辄止与恃才轻忽。',
 enD:'Tian Cai governs innate intelligence, cleverness and comprehension, placed near the Life Palace. In Life a person is quick to react, infer and learn, with talent and ingenuity. Yet the intelligence should serve depth; with malefics, guard against being too clever by half, skimming the surface and relying on talent carelessly.',
 cnL:'有人天才坐命，学什么都比旁人快，却容易"样样懂一点、门门不精"，关键是给聪明找一个能扎下去的方向。',
 enL:'Some with Tian Cai learn faster than others yet know a little of everything; the key is finding one direction for the intelligence to go deep.',
 cnA:'这个问题在问：天才坐命好在哪、要注意什么。一是领悟快、反应灵，二是有巧思与创意，三是若不深耕则聪明易散，逢煞更易自负或轻敌。',
 enA:'The question is its gift and caution: quick grasp and response, ingenuity and creativity, and without depth the intelligence scatters, while with malefics it leans to conceit or underestimating.',
 cnLog:['天才为才智之星，主先天聪明、领悟、反应与巧思，随命宫布列。','坐命者学习快、联想广、点子多，擅长举一反三。','若配合主星与四化得宜，才气可化为专业上的早成与创新。','逢煞忌则易浅尝、自负、恃才，课题在"专注"与"下笨功夫"。'],
 enLog:['Tian Cai is the intelligence star of innate cleverness, comprehension, response and ingenuity, placed with the Life Palace.','In Life one learns fast, connects widely and has many ideas, inferring readily.','When aligned with the major stars and transformations, talent becomes early achievement and innovation.','With malefics it leans to skimming, conceit and relying on wit; the lesson is focus and doing the slow work.'],
 cnStep:['先确认命宫带天才','体会其领悟快、点子多的长处','给聪明选一个能深耕的方向','用刻意练习把才气变专业','防浅尝辄止与恃才轻敌','结合大限看才智在哪个阶段出成果'],
 enStep:['First confirm Tian Cai in the Life Palace','Note quick grasp and many ideas','Choose one direction for depth','Use deliberate practice to turn wit into expertise','Guard against skimming and conceit','Use the decade to see when the talent bears fruit'],
 cnMis:['把天才当"不用努力"的本钱','学什么都浅尝，不肯下笨功夫','恃才自负，轻敌误事'],
 enMis:['Taking talent as a reason not to work','Skimming everything and refusing slow effort','Becoming conceited and underestimating tasks'],
 cnClose:'天才坐命给的是先天聪明：领悟快、点子多、能创新。它不能替代深耕，选准方向、肯下笨功夫、戒骄轻，才气才真正变成站得住的本事。',
 enClose:'Tian Cai in Life gives innate intelligence: quick, full of ideas and creative. It cannot replace depth; choose a direction, do the slow work and shed conceit so the talent becomes real, lasting ability.'},

{cat:'gongwei',slug:'ziwei-zuofu-youbi-zai-jiegong',focus:'左辅右弼在疾厄的恢复助力',focusEn:'Zuo Fu and You Bi in the Health Palace and recovery support',
 cnT:'紫微斗数左辅右弼在疾厄：身体恢复力与病中的援手',
 enT:'Zuo Fu and You Bi in the Health Palace in Zi Wei Dou Shu: Recovery and Help in Illness',
 cnD:'左辅右弼主平辈助力与贵人扶持，落在疾厄宫，主身体有缓冲、恢复力较好，生病时易得到照顾与好的医疗资源，心态乐观也利于康复。但这只是倾向，不是健康保证；身体不适应以正规就医为准，不作自我诊断。',
 enD:'Zuo Fu and You Bi govern peer support and patron help; in the Health Palace they bring bodily buffers and fair recovery, with care and good medical resources when ill, while an optimistic outlook aids recovery. This is only a tendency, not a guarantee; for symptoms rely on proper medical care rather than self-diagnosis.',
 cnL:'有人疾厄宫带左右，生病时总有人帮、也恢复得顺，其实这是助力星入健康宫，提示"遇病有援、恢复有底"，但不等于可以不注意身体。',
 enL:'Some with Zuo You get help when ill and recover smoothly; it signals support and a base for recovery, not permission to ignore the body.',
 cnA:'这个问题在问：左右入疾厄怎么读。一看恢复力与缓冲，二看病中是否有人照顾、资源是否到位，三看心态，仍要规律作息、及时就医，不能把吉星当免病符。',
 enA:'The question is how to read it: recovery and buffers, care and resources when ill, and outlook, while still keeping regular habits and seeking care timely rather than treating it as a charm.',
 cnLog:['左辅右弼为平辈助力星，主扶持、协助、有人帮。','入疾厄则身体有缓冲、恢复力较好，病中易得家人朋友照顾与妥善医治。','心态较稳、愿意配合，利于康复与调养。','它只给倾向：不适应以正规就医为准、不作诊断，吉星不等于无病。'],
 enLog:['Zuo Fu and You Bi are peer-support stars of backing and help.','In Health the body has buffers and fair recovery, with care from family and friends and proper treatment.','A steady, cooperative outlook aids recovery and recuperation.','It only gives tendency: symptoms defer to proper medical care and not self-diagnosis, and auspicious stars do not mean no illness.'],
 cnStep:['先确认疾厄宫是否带左辅右弼（空宫借星）','看其恢复力与身体缓冲','看病中照顾与医疗资源是否到位','保持乐观配合的心态','规律作息、定期体检、不适及时正规就医','不把吉星当无病保证，也不忽视调养'],
 enStep:['First confirm Zuo You in the Health Palace, borrowing stars if empty','Read recovery and bodily buffers','See whether care and medical resources are in place','Keep an optimistic, cooperative outlook','Keep regular habits, check-ups and timely proper care','Do not take it as a no-illness guarantee or neglect recuperation'],
 cnMis:['把左右疾厄当"不会生病"','生病只靠乐观、不正规就医','忽视作息调养，以为有吉星就够'],
 enMis:['Taking it as never falling ill','Relying only on optimism without proper care','Ignoring habits and recuperation, assuming auspicious stars suffice'],
 cnClose:'左辅右弼在疾厄，提示恢复有底、病中有援、心态利于康复。它给的是倾向不是保证：规律作息、及时正规就医、不作自我诊断，这份"援"才真正帮得上身体。',
 enClose:'Zuo You in Health signals a base for recovery, help when ill and an outlook that aids healing. It gives tendency, not guarantee: keep regular habits, seek proper timely care and avoid self-diagnosis so the support truly helps the body.'},

{cat:'gongwei',slug:'ziwei-wenchang-wenqu-zai-jiegong',focus:'文昌文曲在疾厄的神经思虑倾向',focusEn:'Wen Chang and Wen Qu in the Health Palace and nervous-thinking tendencies',
 cnT:'紫微斗数文昌文曲在疾厄：用脑过度与神经敏感的身体读法',
 enT:'Wen Chang and Wen Qu in the Health Palace in Zi Wei Dou Shu',
 cnD:'文昌文曲主文书、思维与神经，落在疾厄宫，主身体的"敏感点"多在神经系统与思虑：易失眠、多梦、紧张性不适或用脑过度后的疲劳。它提示要给大脑留白、规律作息；这是倾向非诊断，不适以正规就医为准。',
 enD:'Wen Chang and Wen Qu govern documents, thinking and nerves; in the Health Palace the sensitive points lean to the nervous system and thought, tending toward insomnia, vivid dreams, tension discomfort or fatigue from overusing the mind. It suggests giving the mind space and regular habits; this is tendency, not diagnosis, and symptoms defer to proper medical care.',
 cnL:'有人昌曲在疾厄，身体不舒服常常是"想出来、熬出来"的——一紧张、一用脑就失眠头痛，关键是学会松下来、给脑子休息。',
 enL:'For some, discomfort arises from thinking and strain, with insomnia and headaches under stress; the key is learning to relax and rest the mind.',
 cnA:'这个问题在问：文书星入健康宫怎么读。一看神经与睡眠、二看思虑与情绪对身体的影响，三看是否用脑过度，仍要及时就医排查，不把它当定论。',
 enA:'The question is how to read it: nerves and sleep, the effect of thought and emotion on the body, and overusing the mind, while still seeking timely care rather than taking it as settled.',
 cnLog:['文昌文曲为文书、思维之星，与神经、表达、用脑相关。','入疾厄则先天敏感点偏神经系统：易失眠、多梦、焦虑或紧张性不适。','用脑过度、长期紧绷后易疲劳，身体常把"心里的事"表现出来。','它只给倾向：不适应以正规就医为准、不作诊断，调养重在放松与作息。'],
 enLog:['Wen Chang and Wen Qu are document and thinking stars tied to nerves, expression and mental effort.','In Health the sensitive points lean to the nervous system: insomnia, dreams, anxiety or tension discomfort.','Overthinking and long strain bring fatigue, and the body often expresses what is on the mind.','It only gives tendency: symptoms defer to proper care and not diagnosis, with relaxation and habits central.'],
 cnStep:['先确认疾厄宫是否带文昌文曲','看神经、睡眠与思虑相关的倾向','识别用脑过度与紧张的信号','给大脑留白，安排休息、运动与放松','不适及时到正规医院排查、不作自我诊断','结合大限看哪段时间精神压力偏重'],
 enStep:['First confirm Wen Chang Wen Qu in Health','Read nerves, sleep and thought-related tendencies','Recognize signs of overthinking and tension','Give the mind space with rest, exercise and relaxation','Seek proper timely care and avoid self-diagnosis','Use the decade to see when mental pressure runs high'],
 cnMis:['把昌曲疾厄当"注定神经衰弱"','只对症状焦虑、不放松不就医','忽视作息，用脑无度还硬扛'],
 enMis:['Taking it as a fixed nervous condition','Only worrying at symptoms without relaxing or seeking care','Ignoring habits and overusing the mind while pushing through'],
 cnClose:'文昌文曲在疾厄，提示身体的敏感点在神经与思虑：易失眠紧张、用脑易累。它是倾向非诊断，给大脑留白、规律作息、及时正规就医，才是对这份敏感最好的照顾。',
 enClose:'Wen Chang Wen Qu in Health signals sensitive points in nerves and thought: prone to insomnia, tension and mental fatigue. It is tendency, not diagnosis; give the mind space, keep regular habits and seek proper timely care to best handle the sensitivity.'},

{cat:'gongwei',slug:'ziwei-tiankong-yu-dikong-chabie-luogong',focus:'天空与地空的差别及落宫',focusEn:'the difference between Tian Kong and Di Kong and their placements',
 cnT:'紫微斗数天空与地空差别：两种「空」星，空的地方不一样',
 enT:'Tian Kong vs. Di Kong in Zi Wei Dou Shu: Two Emptiness Stars in Different Places',
 cnD:'地空（与地劫一对）偏"物质的空"：主破耗、财来财去、手头易空；天空偏"精神的空"：主想法空灵、灵感多、也易计划落空或与现实脱节。地空多落在求财与积蓄的课题，天空多落在心境与理想，逢吉则空灵成创意与悟性，逢煞则空转、虚耗。',
 enD:'Di Kong, paired with Di Jie, leans to material emptiness: drain, money coming and going and empty hands; Tian Kong leans to mental emptiness: airy ideas and inspiration, but also plans falling through or losing touch with reality. Di Kong mostly concerns money and saving, Tian Kong the inner state and ideals; with auspicious stars the airiness becomes creativity and insight, and with malefics it spins and wastes.',
 cnL:'有人分不清天空和地空，一见"空"就当破财，其实一个空在口袋、一个空在想法，读法和应对都不同。',
 enL:'Some confuse the two and read any emptiness as loss; one empties the pocket and the other the ideas, with different readings and responses.',
 cnA:'这个问题在问：同样是"空"，为什么差别这么大。先认星——地空偏物质破耗、天空偏精神空灵，再看落宫与同宫星，判断这股"空"是漏财、是创意、还是不切实际。',
 enA:'The question is why the emptiness differs so much. First identify the star, material drain versus mental airiness, then read the palace and company to see whether the emptiness leaks money, creates or becomes impractical.',
 cnLog:['地空与地劫成对，主物质层面的空亡、破耗与不聚财。','天空主精神层面的空灵、灵感与超脱，也主想法易落空。','地空落财帛、田宅等宫多应在钱财与资产的进出；天空落福德、官禄多应在心境、理想与创意。','逢吉星、化科，天空的空灵可成悟性与创作；逢煞忌则两空皆主虚耗，需以务实与留存化解。'],
 enLog:['Di Kong pairs with Di Jie and governs material emptiness, drain and unkept money.','Tian Kong governs mental airiness, inspiration and detachment, with ideas that can fall through.','Di Kong in Wealth or Property shows in money and assets; Tian Kong in Fortune or Career shows in mood, ideals and creativity.','With auspicious stars the airiness becomes insight and creation; with malefics both empties waste, resolved through practicality and keeping reserves.'],
 cnStep:['先分辨是地空还是天空','地空按物质破耗读，重储蓄与节流','天空按精神空灵读，重落地与验证','看落宫：财官田多应钱财、福官多应心境理想','逢吉把空灵转成创意悟性，逢煞练务实','结合大限看这股空在哪阶段被引动'],
 enStep:['First tell Di Kong from Tian Kong','Read Di Kong as material drain, focusing saving and restraint','Read Tian Kong as mental airiness, focusing grounding and testing','See the palace: money palaces show finances and inner palaces mood and ideals','With auspicious stars turn airiness into creativity; with malefics practice practicality','Use the decade to see when the emptiness activates'],
 cnMis:['把天空地空混为一谈、一律当破财','只看到"空"的负面，忽略空灵的悟性与创意','天空落宫却不落地，想法永远停在半空'],
 enMis:['Confusing the two and reading both as loss','Seeing only the negative side and missing insight and creativity','Not grounding Tian Kong so ideas stay half in the air'],
 cnClose:'天空与地空是两种空：地空漏在物质、天空空在精神。分清星、看准宫，逢吉把空灵变悟性，逢煞以务实留存接住——"空"就不再只是损耗，也能是转圜与创造的空间。',
 enClose:'Tian Kong and Di Kong are two emptinesses: one leaks materially and the other mentally. Distinguish them and read the palace, turning airiness to insight with auspicious stars and catching it with practicality under malefics, so emptiness is not only drain but room to turn and create.'}
];
