// 2026-09-29 调研驱动 第2组：两象同宫/法生年/忌出忌入/大限禄权/极向离明/寿星入庙/三层叠象/迁移远方 8篇
module.exports=[
{cat:'sihua',slug:'ziwei-shengnian-sihua-liangxiang-tonggong',focus:'生年两象同宫的读法',focusEn:'reading two natal transformations sharing one palace',
 cnT:'紫微斗数生年两象同宫：禄权、禄科、权忌落在一宫怎么读',
 enT:'Two Natal Transformations in One Palace in Zi Wei Dou Shu',
 cnD:'四颗化曜有时两颗落进同一宫：禄权同宫主资源加掌控、能干事；禄科同宫主机会加名声、顺水得体面；权忌同宫主拉扯内耗。先认出是哪两象，再按宫位主题读它的表现。',
 enD:'Sometimes two of the four transformations land in one palace: Lu plus Quan means resources with control and getting things done, Lu plus Ke means opportunity with reputation and a smooth, respectable path, while Quan plus Ji means tug-of-war and inner friction. Identify the pair first, then read it through the palace theme.',
 cnL:'新手看四化只逐颗查，其实两颗化曜挤在一宫会"合成一种新性格"，读懂组合比单记一颗更准。',
 enL:'Beginners check transformations one by one, but two in one palace blend into a new character; reading the pair is more accurate than memorizing one.',
 cnA:'这个问题在问：同一宫有两颗化曜，力量怎么算。关键是分清两象是"同向加强"（如禄权、禄科）还是"反向拉扯"（如权忌、禄忌），再落到这宫管的事上。',
 enA:'The question is how force is counted when two transformations share a palace. The key is whether they align and strengthen, such as Lu-Quan and Lu-Ke, or pull against each other, such as Quan-Ji and Lu-Ji, then apply it to the palace matter.',
 cnLog:['禄权同宫：机会来得着、自己又能主导，主能干、敢接事，但过旺易独断、事必躬亲。','禄科同宫：资源与名声相随，主顺水得名、有贵人、讲体面，是较舒展的组合。','权忌同宫：想掌控却受阻，主拉扯、内耗、较劲，课题在"放手"与"分步"。','禄忌同宫、科忌同宫：机会与纠缠并存，科能缓和忌；读法是看净效果，不简单判好坏。'],
 enLog:['Lu and Quan together: opportunity is reachable and you can lead it, capable and willing to take charge, though over-strong it leans to being arbitrary and doing everything yourself.','Lu and Ke together: resources and reputation go together, bringing smooth recognition, patrons and dignity, a more comfortable pairing.','Quan and Ji together: wanting control but meeting blocks, bringing tug-of-war, inner friction and rivalry; the lesson is letting go and taking steps.','Lu-Ji and Ke-Ji: opportunity and entanglement coexist, and Ke eases Ji; read the net effect rather than simple good or bad.'],
 cnStep:['先确认这一宫落了哪两颗化曜','判断两象是同向加强还是反向拉扯','同向（禄权、禄科、权科）看加强在哪种能力','反向（权忌、禄忌、科忌）看纠缠的课题','再结合宫位主题与主星星性','下结论时讲净效果，不贴单一吉凶标签'],
 enStep:['First confirm which two transformations share the palace','Judge whether they align and strengthen or pull against','For aligned pairs, see which ability is strengthened','For opposing pairs, see the entanglement and lesson','Then combine the palace theme and major-star nature','Conclude on the net effect without a single good-bad label'],
 cnMis:['逐颗孤立看，不读两象合成的意味','把权忌、禄忌一律判坏，忽略科能缓和','只看化曜不看宫位主题，落在哪宫都一个说法'],
 enMis:['Reading each transformation in isolation and missing the blend','Judging Quan-Ji and Lu-Ji as all bad and ignoring that Ke eases','Seeing only transformations without the palace theme, so every palace reads the same'],
 cnClose:'两象同宫是"合成力"：同向者更强、反向者更纠结。认出组合、分清方向，再落到这宫的人事上，你读到的就不是两颗孤立的星，而是一股合力。',
 enClose:'Two transformations in one palace are a combined force: aligned pairs strengthen and opposing pairs tangle. Recognize the pair and its direction, then apply it to the palace affairs to read one joint force rather than two isolated stars.'},

{cat:'sihua',slug:'ziwei-daxian-sihua-fa-shengnian',focus:'大限四化法生年找根源',focusEn:'rooting decade transformations in the natal transformations',
 cnT:'紫微斗数大限四化怎么「法生年」：找到十年事件的根源',
 enT:'How to Root Decade Transformations in the Natal Chart in Zi Wei Dou Shu',
 cnD:'看到大限、流年的化曜，要回头找同一种化曜在生年的位置，这叫「法生年」。生年为根、限运为枝，先把根源那条线找到，才知道这十年的机会或课题从哪来，而不是只在表面断吉凶。',
 enD:'When you see a decade or year transformation, look back to where the same kind of transformation sits in the natal chart; this is rooting in the natal. The natal is the root and the limit the branch; find the root line first to know where the decade opportunity or lesson comes from rather than judging the surface.',
 cnL:'有人看到大限化禄就高兴、化忌就紧张，却不回头看这股力的根在哪，结果只读到现象、读不到来龙去脉。',
 enL:'Some rejoice at a decade Lu and tense at a decade Ji without looking where the force is rooted, reading only the phenomenon and not the full line.',
 cnA:'这个问题在问：限运的化曜为什么要往回看。因为限运是引动、生年是底色，同象相法则找到事件的根源，异象则要看它牵动了哪条线。',
 enA:'The question is why limit transformations point backward. The limit activates and the natal sets the baseline; matching the same kind finds the root, while a different kind shows which line it pulls.',
 cnLog:['法生年：大限化禄找生年禄所在、大限化忌找生年忌所在，那条宫位线就是根源。','生年为体（定数、底色），大限流年为用（引动、变数），用不离体。','若限运化曜在生年找不到同象，就看它飞进哪一宫、牵动哪个领域。','找到根源后，再判断这十年是"顺势加强"还是"换条线出课题"。'],
 enLog:['Rooting: a decade Lu seeks the natal Lu and a decade Ji seeks the natal Ji; that palace line is the root.','The natal is the substance, the decade and year are the function; the function never leaves the substance.','If a limit transformation has no natal match, see which palace it flies into and which domain it pulls.','Once the root is found, judge whether the decade strengthens along the line or opens a lesson on another line.'],
 cnStep:['先排出大限（流年）四化落宫','取每颗限运化曜，找生年同象所在','把根源宫位与限运宫位连成一条线','判断这十年是顺势加强还是另出题','找不到同象则看飞化牵动哪宫','结合主星与宫位，再下结论'],
 enStep:['First place the decade transformations','For each, find where the same natal transformation sits','Connect the root palace and limit palace into a line','Judge whether the decade strengthens along the line or opens another lesson','If no match, see which palace the flight pulls','Combine major stars and palaces before concluding'],
 cnMis:['只看限运四化，不回头法生年','把生年和限运割裂，读不到根源','法生年硬套，找不到就胡乱连线'],
 enMis:['Reading only limit transformations without rooting them','Separating natal and limit and missing the root','Forcing the rooting and drawing random lines when no match exists'],
 cnClose:'限运四化是枝、生年四化是根。先「法生年」把来龙去脉找到，再看这十年怎么引动，你断的事才有源头，而不是停在表面的吉凶。',
 enClose:'Limit transformations are branches and natal transformations the root. Root them first to find the full line, then see how the decade activates, so your reading has a source rather than stopping at surface fortune.'},

{cat:'sihua',slug:'ziwei-huaji-feichu-yu-feiru-chabie',focus:'化忌飞出与飞入的方向差别',focusEn:'the directional difference of Hua Ji flying out versus flying in',
 cnT:'紫微斗数化忌「飞出」和「飞入」差别：方向决定谁牵挂谁',
 enT:'Hua Ji Flying Out vs. Flying In in Zi Wei Dou Shu: Direction Sets Who Is Attached',
 cnD:'宫干使星化忌，若忌星落在别的宫叫「飞出（忌出）」，本宫对那宫放不下；若别的宫飞化使忌落入本宫叫「飞入（忌入）」，是外宫牵挂到这里。方向相反，主客就相反，先看清谁飞向谁。',
 enD:'When a palace stem makes a star Hua Ji and that star sits elsewhere, it flies out, meaning this palace cannot let go of that one; when another palace flies Ji into this one, it flies in, meaning the outside palace attaches here. The directions reverse, and so do subject and object; first see who flies to whom.',
 cnL:'新手飞化只看"忌在哪宫"，却不问这忌是谁飞出来的，结果把主客体读反，结论自然偏。',
 enL:'Beginners only see where Ji sits without asking who flew it, reversing subject and object and skewing the conclusion.',
 cnA:'这个问题在问：同一颗化忌，为什么读法随方向变。关键是找"起飞宫"的宫干——它从哪宫飞出，就代表哪宫在牵挂、在投入、在受课题。',
 enA:'The question is why the same Ji reads differently by direction. Find the takeoff palace stem; whichever palace it flies from is the one that is attached, invested and working the lesson.',
 cnLog:['忌出（飞出本宫）：本宫宫干使他宫星化忌，主本宫把精力、牵挂投向那宫，也常主付出与耗损在那。','忌入（飞入本宫）：他宫宫干使本宫星化忌，主外宫因人、因事牵挂到本宫。','方向定主客：起飞宫是"主动方"，落宫是"指向处"。','化忌主"执著、放不下"，飞化把这份执著的两端标出来，读法是讲关系，不是断灾祸。'],
 enLog:['Flying out: the home stem makes a star elsewhere Hua Ji, meaning this palace invests energy and attachment there, often giving and draining toward it.','Flying in: another stem makes a star in the home Hua Ji, meaning an outside palace attaches to this one through a person or matter.','Direction sets subject and object: the takeoff palace is active and the landing palace the target.','Hua Ji means attachment and inability to let go; the flight marks its two ends, reading a relationship rather than foretelling disaster.'],
 cnStep:['先找到化忌星坐哪一宫','再查是哪一宫的宫干使它化忌（起飞宫）','起飞宫即主动、牵挂的一方，落宫是指向处','忌出看本宫对哪宫付出与放不下','忌入看哪宫因人因事牵挂到本宫','把它当关系执著来读，不直接断吉凶'],
 enStep:['First find which palace the Hua Ji star sits in','Then check which palace stem makes it Hua Ji, the takeoff','The takeoff is the active, attached party and the landing is the target','For flying out, see where this palace gives and cannot let go','For flying in, see who attaches to this palace through a person or matter','Read it as relational attachment, not direct fortune'],
 cnMis:['只看忌星落宫，不问起飞宫是谁','把忌出忌入方向读反，主客颠倒','见飞忌就断灾祸，忽略它讲的是执著与关系'],
 enMis:['Only seeing where Ji lands without asking the takeoff palace','Reversing flying out and in and swapping subject and object','Judging a flying Ji as disaster and ignoring it describes attachment and relationship'],
 cnClose:'化忌飞化先看方向：谁的宫干起飞，谁就是牵挂的一方。忌出是我投向人、忌入是人投向我——分清主客，这颗忌讲的关系才读得对。',
 enClose:'For a flying Ji, read direction first: whichever stem takes off is the attached party. Flying out is me reaching out and flying in is another reaching to me; with subject and object clear, the relationship reads correctly.'},

{cat:'sihua',slug:'ziwei-daxian-hualu-huaquan-shinian-fali',focus:'大限禄权的十年发力点',focusEn:'the decade Lu and Quan as the ten-year power point',
 cnT:'紫微斗数大限化禄化权：十年真正的发力点在哪一宫',
 enT:'Decade Lu and Quan in Zi Wei Dou Shu: Where the Ten-Year Power Sits',
 cnD:'大限化禄主十年机会与资源集中处，化权主十年主导、竞争与精力投入处；两象同宫或相会的位置，就是这十年真正的发力点。但要看生年底色与主星星性，机会来了也得接得住。',
 enD:'Decade Lu marks where ten-year opportunities and resources gather, while Quan marks where you lead, compete and invest energy; where the two share or meet is the real power point of the decade. Yet check the natal baseline and star nature, for an opportunity must still be caught.',
 cnL:'有人走大限看到一堆吉星却不知劲往哪使，其实把禄（资源）和权（主导）交会的宫位找出来，发力方向就清楚了。',
 enL:'Some see many auspicious stars in a decade but do not know where to push; finding the palace where Lu and Quan meet makes the direction clear.',
 cnA:'这个问题在问：十年里到底在哪件事上主动出击。禄给资源和机会、权给主导和执行，两者重叠处既是机会又能自己说了算，是最值得投入的地方。',
 enA:'The question is which matter to push actively in the decade. Lu supplies resources and opportunity and Quan supplies leadership and execution; where they overlap is both an opportunity and within your control, the best place to invest.',
 cnLog:['大限化禄：十年里这宫的资源、机会、缘分变得容易取得，主"想得到、也较易得"。','大限化权：十年里这宫让你想主导、敢竞争，是精力投入最多处。','禄权交会：既有机会又能掌控，是十年的主动发力点，事业、钱财多在此突破。','若禄权分散在不同宫，则机会与执行分处两线，要靠三方四正把它们连起来看。'],
 enLog:['Decade Lu: in these ten years the resources, opportunities and ties of this palace become easier to obtain, meaning you want and can more readily get them.','Decade Quan: this palace makes you want to lead and dare to compete, where you invest the most energy.','Lu-Quan meeting: opportunity plus control is the active power point where career and money often break through.','If Lu and Quan sit in different palaces, opportunity and execution lie on two lines and must be connected through the triple-direction.'],
 cnStep:['先排大限四化，定位化禄、化权落宫','看禄权是否同宫或在三方相会','交会处即十年主动发力点，优先投入','若分散，分别看机会线与执行线','回头法生年，确认这宫的先天底色','结合主星星性，判断机会接不接得住'],
 enStep:['First place the decade transformations, locating Lu and Quan','See whether Lu and Quan share a palace or meet in the trine','The meeting is the active power point to invest first','If separate, read the opportunity line and execution line','Root back to the natal to confirm the baseline','Combine star nature to judge whether the opportunity can be caught'],
 cnMis:['只看化禄不看化权，有机会却使不上劲','把禄权交会处一概当稳赢，忽略生年底色','禄权分散却硬当一回事，读错发力点'],
 enMis:['Seeing only Lu and not Quan, so opportunity lacks drive','Taking the Lu-Quan meeting as guaranteed and ignoring the natal baseline','Treating separate Lu and Quan as one and misreading the power point'],
 cnClose:'十年主动在哪，看禄权交会：禄给机会、权给掌控，重叠处最值得投入。先定位、再法生年、看星性，发力才不会使错方向。',
 enClose:'Where to push in a decade is where Lu and Quan meet: Lu gives opportunity and Quan control, and the overlap is worth the most. Locate it, root it and read the star nature so the force goes the right way.'},

{cat:'geju',slug:'ziwei-jixiang-liming-ge-ziwei-wugong',focus:'极向离明格的成格破格',focusEn:'the Ji Xiang Li Ming pattern and its breaks',
 cnT:'紫微斗数极向离明格：紫微午宫坐命的成格与破格',
 enT:'The Ji Xiang Li Ming Pattern in Zi Wei Dou Shu: Zi Wei in the Wu Palace',
 cnD:'紫微独坐午宫（入庙），迁移贪狼、官禄廉贞天府、财帛武曲天相，三方无煞忌冲破、再会左右魁钺与科权禄，是极向离明格，主大贵；若一个吉星都不会，降为孤君在野，煞忌重冲则破格。',
 enD:'Zi Wei alone in the Wu palace, with Tan Lang in Travel, Lian Zhen Tian Fu in Career and Wu Qu Tian Xiang in Wealth, forms the Ji Xiang Li Ming pattern when no malefic or Ji breaks it and Zuo You, Kui Yue and the transformations meet, indicating high standing. With no auspicious meeting it falls to a lone ruler in the wild, and heavy malefic clashes break it.',
 cnL:'有人一听紫微坐命就以为非富即贵，其实帝星再强也要有人辅佐，有没有左右魁钺、有没有煞忌冲，才决定格局高低。',
 enL:'Some assume Zi Wei in the Life Palace means wealth and rank, but even the emperor needs ministers; whether Zuo You and Kui Yue attend and whether malefics clash set the pattern level.',
 cnA:'这个问题在问：同样紫微午宫坐命，为什么有人成大格、有人却普通。差别就在三方四正——吉星来会、无煞忌冲破才成格，孤君无辅则格局大打折扣。',
 enA:'The question is why Zi Wei in Wu leads a great pattern for some and an ordinary life for others. It lies in the triple-direction: auspicious meetings without malefic breaks form the pattern, while a lone ruler without support drops sharply.',
 cnLog:['"极"指紫微（北极帝星），"离明"指午宫（离卦、光明之位），紫微在午皆入庙。','成格：三方四正无羊陀火铃空劫与化忌重重冲破，更会左右魁钺、科权禄。','破格：煞忌重冲为"无道孤君"，一个吉曜都不会则为"孤君在野"，格局明显降低。','此格主领导、统御与贵气，但现实成就仍取决于辅佐与运限，不是有紫微就够。'],
 enLog:['Ji refers to Zi Wei the polar emperor and Li Ming to the Wu palace, the bright position; Zi Wei in Wu is always exalted.','To form it, the triple-direction holds no Qing Yang, Tuo Luo, Huo Xing, Ling Xing, Kong, Jie or heavy Ji, and meets Zuo You, Kui Yue and the transformations.','It breaks when heavy malefics clash into a lone ruler without a way, while no auspicious meeting makes a lone ruler in the wild, lowering the pattern.','It indicates leadership, command and noble bearing, but real achievement still depends on support and the time cycles; Zi Wei alone is not enough.'],
 cnStep:['先确认命宫是否紫微独坐午宫','列出三方（迁移贪狼、官禄廉府、财帛武相）','数三方四正有无煞星、空劫、化忌冲破','再看左右、魁钺、科权禄是否来会','吉会无破为成格，无吉为孤君、煞重为破格','结论结合运限，不凭一颗紫微断贵贱'],
 enStep:['First confirm Zi Wei alone sits in the Wu Life Palace','List the trine: Tan Lang in Travel, Lian Fu in Career and Wu Xiang in Wealth','Count whether malefics, emptiness or Ji break it','Then see whether Zuo You, Kui Yue and the transformations meet','Auspicious meetings without breaks form it; no meeting is a lone ruler and heavy malefics break it','Conclude with the time cycles, never judging rank from Zi Wei alone'],
 cnMis:['见紫微坐命就断言大富大贵','只看帝星不看辅佐与煞忌，忽略成格条件','把无吉的孤君也当成上格'],
 enMis:['Declaring great wealth and rank at the sight of Zi Wei','Reading only the emperor without support and malefics, ignoring the conditions','Treating a lone ruler without auspicious meetings as a top pattern'],
 cnClose:'极向离明是"帝星得位、君臣相得"的格局：紫微在午只是底子，无煞忌冲、有吉曜辅才成格。条件看清，才不会把孤君误当大贵。',
 enClose:'Ji Xiang Li Ming is an emperor in place with ministers in accord: Zi Wei in Wu is only the base, and it forms with no malefic break and real support. Read the conditions so a lone ruler is not mistaken for high standing.'},

{cat:'geju',slug:'ziwei-shouxing-rumiao-ge-tianliang-wugong',focus:'寿星入庙格的成格与现实含义',focusEn:'the Longevity Star Exalted pattern and its meaning',
 cnT:'紫微斗数寿星入庙格：天梁入庙守命的稳重与逢凶化吉',
 enT:'The Longevity Star Exalted Pattern in Zi Wei Dou Shu: Tian Liang Guarding the Life Palace',
 cnD:'天梁为寿星、荫星，入庙守命（午宫等庙旺位），无煞忌刑耗冲破、再会吉曜，称寿星入庙格，主稳重老成、逢凶化吉、得荫庇而寿。现实中多与照顾、教育、医药、宗教或老成行有缘。',
 enD:'Tian Liang is the longevity and shelter star; when exalted in the Life Palace and free of malefic, Ji, punishment and drain breaks, with auspicious meetings, it forms the Longevity Star Exalted pattern, indicating steadiness, maturity, turning misfortune into good and a sheltered, long life. In practice it often ties to care, education, medicine, religion or mature lines of work.',
 cnL:'有人把天梁笼统当"老人星"，其实它入庙守命是一种逢凶化吉、有人荫庇的稳，关键看有没有煞忌来破。',
 enL:'Some treat Tian Liang vaguely as an old-person star, but exalted in the Life Palace it is a steady turning-aside of trouble with shelter; the key is whether malefics break it.',
 cnA:'这个问题在问：天梁入庙到底好在哪。它主"荫"——逢凶有解、遇事有人帮、性情稳，但逢煞忌刑耗则荫力打折，也易操心、爱管。',
 enA:'The question is what an exalted Tian Liang offers. It governs shelter: trouble finds a way out, help appears and the temperament is steady, but malefics discount the shelter and it can lean to worry and meddling.',
 cnLog:['天梁为南斗寿星，化气为荫，主逢凶化吉、遇难呈祥、得长辈或贵人庇荫。','寿星入庙：天梁在庙旺位守命，再会禄、科、左右魁钺，无煞忌刑耗方合格。','成格者性情稳重、老成、有原则，与教育、医药、公益、宗教或法务等"照顾人"的领域有缘。','逢煞忌则荫力减、易操心劳碌，此时"化解"要靠后天的稳健与专业，而非坐等。'],
 enLog:['Tian Liang is the Southern Dipper longevity star whose nature is shelter, turning trouble into good and gaining protection from elders or patrons.','Longevity exalted: Tian Liang in an exalted position guarding life, meeting Lu, Ke, Zuo You and Kui Yue, with no malefic, Ji, punishment or drain, qualifies.','Those who form it are steady, mature and principled, drawn to care-giving fields such as education, medicine, public service, religion or legal work.','With malefics the shelter weakens and worry rises; then the resolution comes from acquired steadiness and professionalism rather than waiting.'],
 cnStep:['先确认命宫是否天梁入庙坐守','数三方四正有无煞忌刑耗冲破','再看有无禄、科、左右、魁钺来会增荫','成格则看其稳重与逢凶化吉的倾向','逢煞则提示操心劳碌、荫力打折','结论结合运限，不把"寿星"当成无病无灾的保证'],
 enStep:['First confirm an exalted Tian Liang guards the Life Palace','Count whether malefics, Ji, punishment or drain break it','Then see whether Lu, Ke, Zuo You or Kui Yue add shelter','If formed, read the steadiness and trouble-turning tendency','With malefics, note worry and discounted shelter','Conclude with the cycles, not taking longevity as a guarantee of no illness or trouble'],
 cnMis:['把寿星入庙当成无病长寿的保证书','只看天梁不看煞忌，忽略成格条件','把荫星的"逢凶化吉"理解成不用行动'],
 enMis:['Taking the pattern as a guarantee of long life without illness','Reading Tian Liang without malefics and ignoring conditions','Understanding shelter as needing no action'],
 cnClose:'寿星入庙是"荫星得位"：天梁入庙守命、无煞忌破、有吉会，才主稳与逢凶化吉。它给的是倾向与庇荫，不是无灾的保证，仍要靠稳健和专业接住。',
 enClose:'Longevity exalted is a shelter star in place: Tian Liang guarding life without malefic breaks and with auspicious meetings brings steadiness and trouble turned aside. It gives tendency and shelter, not a guarantee of no misfortune, still caught through steadiness and skill.'},

{cat:'sihua',slug:'ziwei-sihua-diexiang-san-ceng-ruhe-die',focus:'四化三层叠象的读法',focusEn:'layering transformations across the natal, decade and year',
 cnT:'紫微斗数四化「三层叠象」：生年、大限、流年怎么叠着读',
 enT:'Layering the Four Transformations in Zi Wei Dou Shu Across Natal, Decade and Year',
 cnD:'四化分三层：生年定底色、大限定十年引动、流年定当年触发。同象叠在一宫（如两层禄、三层忌）为加强，异象叠（禄逢忌）要看净效果。把三层叠起来，才知道一件事是被反复加强还是互相牵制。',
 enD:'Transformations have three layers: the natal sets the baseline, the decade the ten-year activation and the year the current trigger. The same kind stacked in one palace strengthens, while different kinds meeting, such as Lu meeting Ji, require the net effect. Stacking the three shows whether a matter is repeatedly strengthened or mutually restrained.',
 cnL:'有人只看生年或只看流年，结果同一件事读得忽好忽坏，其实把三层叠起来，力量的轻重才看得清。',
 enL:'Some read only the natal or only the year and find the same matter reading now good now bad; stacking the three makes the weight clear.',
 cnA:'这个问题在问：多层四化落在同一宫怎么算。先分层定位、再看是同象还是异象、最后数净效果——同象相叠是加重，异象相逢是抵消或转化。',
 enA:'The question is how to count multiple transformations in one palace. Locate by layer, then see whether they are the same or different kinds, then take the net effect; the same kind stacks and different kinds offset or transform.',
 cnLog:['生年层：出生即定，是先天底色，一辈子不变。','大限层：十年一换，引动这阶段被点亮的领域。','流年层：一年一换，定当年的具体触发。','同象叠（如大限禄逢生年禄）为加强、机会更实；异象叠（如流年忌入生年禄之宫）为牵制，要看吉星与化科能否化解。'],
 enLog:['The natal layer is fixed at birth, the lifelong baseline.','The decade layer changes every ten years and activates the domains lit in this stage.','The year layer changes annually and sets the specific trigger.','The same kind stacked strengthens and makes opportunity real; different kinds meeting restrain, and you check whether auspicious stars or Ke can resolve it.'],
 cnStep:['先分层标出生年、大限、流年四化落宫','找三层化曜是否落在同一宫或同一条线','同象相叠按加强看，异象相逢按牵制看','数该宫三方四正的吉星、煞星算净效果','再用流月把被加强的事点到具体时段','结论讲净倾向，不凭单层化曜断吉凶'],
 enStep:['First mark the natal, decade and year transformations by layer','See whether the layers land in the same palace or line','Treat the same kind stacked as strengthening and different kinds as restraint','Count the auspicious and harsh stars in the triple-direction for the net effect','Then use monthly luck to time the strengthened matter','Conclude on the net tendency, not judging from one layer'],
 cnMis:['只看单层四化就下结论','把异象相逢一律判坏，不看净效果与化解','分层标了却不叠起来，等于没分层'],
 enMis:['Concluding from one transformation layer','Judging different kinds meeting as all bad without the net effect and resolution','Marking layers but never stacking them'],
 cnClose:'四化要叠着读：生年打底、大限引动、流年触发，同象加重、异象牵制。三层合起来算净效果，一件事在当下是机会还是课题，你才判得准。',
 enClose:'Transformations are read in layers: the natal grounds, the decade activates and the year triggers; the same kind stacks and different kinds restrain. Combine all three for the net effect to judge accurately whether a matter is opportunity or lesson now.'},

{cat:'gongwei',slug:'ziwei-qianyi-yuanfang-zaidi-fazhan',focus:'迁移宫看远方与异地发展',focusEn:'the Travel Palace and development in distant or foreign places',
 cnT:'紫微斗数迁移宫看远方：异地发展、外出缘分怎么读',
 enT:'Reading Distant and Foreign Development Through the Zi Wei Dou Shu Travel Palace',
 cnD:'迁移宫与命宫相对，主外出、远方、异地、社会舞台与外人眼中的你。迁移星曜吉、有力，主在外顺、异地有缘、适合往外走；煞忌重则外出多波折。问适不适合离开家乡、去外地或出国，先读迁移，再合命宫与大限。',
 enD:'The Travel Palace, opposite the Life Palace, governs going out, distant and foreign places, the public stage and how others see you. Auspicious, strong stars there mean smooth travel, ties to far places and a fit for moving outward, while heavy malefics bring friction. To judge whether to leave home, relocate or go abroad, read Travel first, then combine Life and the decade.',
 cnL:'有人纠结要不要离开家乡去外地发展，只盯着命宫看，其实"在外的境遇"写在迁移宫，那才是回答这个问题的宫位。',
 enL:'Some wonder whether to leave home for another region while staring at the Life Palace; the outer circumstance is written in Travel, which answers the question.',
 cnA:'这个问题在问：我适不适合往外走、远方有没有机会。先读迁移宫的星曜与四化，看在外顺不顺，再看大限是否引动迁移、命宫是否愿意动。',
 enA:'The question is whether you fit moving outward and whether opportunity waits afar. Read the Travel stars and transformations for smoothness, then see whether the decade activates Travel and whether Life is willing to move.',
 cnLog:['迁移宫主"动"与"外"：外出、旅行、迁移、异地与社会评价都归它。','迁移星曜庙旺、吉星会照，主在外遇助、舞台大、适合往外发展。','煞星、化忌在迁移，主外出多波折、阻滞或口舌，要靠选择地点与时机化解。','迁移与命宫相对：本宫写内在、迁移写外在，两厢合看才知"在家好还是在外好"。'],
 enLog:['Travel governs movement and the outer: trips, relocation, far places and public evaluation.','Exalted Travel stars with auspicious meetings mean help outside, a larger stage and a fit for outward development.','Malefics or Ji in Travel mean friction, blocks or disputes away from home, eased by choosing place and timing.','Travel opposes Life: the home is inner and Travel outer; read both to know whether home or away is better.'],
 cnStep:['先定位迁移宫及其主星（空宫借命宫星）','看迁移星曜亮度与三方四正吉凶','数迁移宫的辅星、煞星与四化','吉而有力主在外顺、异地有缘','煞忌重则提示波折，需慎选地点时机','再合命宫与当前大限，判断是否该往外走'],
 enStep:['First locate Travel and its major stars, borrowing Life stars if empty','Read the Travel brightness and triple-direction fortune','Count its assistants, malefics and transformations','Auspicious and strong means smooth travel and far-place ties','Heavy malefics indicate friction, requiring care with place and timing','Then combine Life and the current decade to decide whether to move outward'],
 cnMis:['只看命宫，不读迁移就判断该不该走','见迁移有煞就断不能外出，不看化解与地点','把迁移只当"出行"，忽略它也管社会舞台与异地发展'],
 enMis:['Judging whether to leave from Life alone without Travel','Seeing a Travel malefic and declaring no travel, without resolution and place','Treating Travel as only trips and ignoring the public stage and far development'],
 cnClose:'远方有没有机会，看迁移宫：星吉有力则在外顺、异地有缘，煞忌重则多波折。再合命宫与大限，"在家还是往外走"这个选择才判得稳。',
 enClose:'Whether opportunity waits afar is read in Travel: auspicious strong stars mean smooth outer paths and far-place ties, while heavy malefics bring friction. Combine Life and the decade to judge steadily whether to stay home or move outward.'}
];
