// 2026-09-29 调研驱动 第3组：廉府同宫/武相官禄/机梁福德/同梁夫妻/大限前后五年/顺逆行/流年地支循环/流月干支 8篇
module.exports=[
{cat:'zhuxing',slug:'ziwei-lianzhen-tianfu-tonggong-wenshou',focus:'廉贞天府同宫的稳守组合',focusEn:'the Lian Zhen Tian Fu pairing and its steady guarding',
 cnT:'紫微斗数廉贞天府同宫：规则与库藏相遇的稳中求进',
 enT:'Lian Zhen and Tian Fu Together in Zi Wei Dou Shu: Steady Progress Where Rules Meet the Storehouse',
 cnD:'廉贞主规则、原则与分寸，天府主库藏、包容与稳守，两星在辰戌同宫，组合是外圆内方、稳中求进：待人圆融、内里有底线，擅长把资源管稳、把规矩立住。逢煞忌则规则易变固执、库藏易变保守。',
 enD:'Lian Zhen governs rules, principles and boundaries, while Tian Fu governs the storehouse, tolerance and steady guarding. Together in Chen or Xu they blend an outward ease with an inner line, advancing steadily: easy with people yet principled within, skilled at holding resources and setting rules. With malefics, rules can harden into rigidity and the storehouse into conservatism.',
 cnL:'有人觉得廉贞和天府一刚一柔凑在一起会别扭，其实一个管"该不该"、一个管"留不留得住"，配合好了是很稳的组合。',
 enL:'Some think the firm Lian Zhen and soft Tian Fu clash, but one judges what is proper and the other holds what is kept, a very steady pair when aligned.',
 cnA:'这个问题在问：廉府同宫的人到底偏什么。底色是"稳"——讲规矩、能储蓄、会包容，但开创和冒险不是强项，逢吉则稳中有成，逢煞则守成过头。',
 enA:'The question is what the pairing leans to. The baseline is steady: rule-abiding, able to save and tolerant, though initiative and risk-taking are not strengths; with auspicious stars it achieves steadily and with malefics it over-guards.',
 cnLog:['廉贞为丁火，主原则、规则、分寸与自我约束；天府为戊土，主库藏、包容、稳定与承载。','同宫则外圆内方：对外圆融、给余地，对内有底线、讲规矩，擅长管理与守成。','资源观偏"先存稳、再图进"，适合财务、管理、合规、行政或稳健经营。','逢擎羊陀罗、化忌则原则变固执、库藏变保守，课题在"变通"与"放权"。'],
 enLog:['Lian Zhen is fire governing principles, rules, boundaries and self-restraint; Tian Fu is earth governing the storehouse, tolerance, stability and carrying.','Together they are easy outside and principled within, giving room outward and holding the line inward, skilled at management and guarding gains.','Their resource view is secure first and advance after, fitting finance, management, compliance, administration or steady business.','With Qing Yang, Tuo Luo or Ji, principles harden and the storehouse closes; the lesson is flexibility and delegating.'],
 cnStep:['先确认廉贞天府是否同宫及所在宫位','读廉贞的规则感与天府的库藏力','看三方四正吉凶，判断稳中有进还是守成过头','吉星会照则看其管理与守财的长处','煞忌来则提示固执保守，需练变通','结合大限看这稳局在哪个阶段出成果'],
 enStep:['First confirm the pairing and its palace','Read the Lian Zhen sense of rules and Tian Fu storehouse power','Check the triple-direction to see steady progress or over-guarding','With auspicious meetings, see the management and wealth-holding strength','With malefics, note rigidity and the need for flexibility','Use the decade to see when the steady pattern bears fruit'],
 cnMis:['把廉府同宫一律当保守没出息','只看一星不读两星合成的稳','逢吉就当稳成，忽略其开创力偏弱'],
 enMis:['Taking the pair as merely conservative and unambitious','Reading one star without the blended steadiness','Assuming auspicious meetings guarantee success while initiative is weak'],
 cnClose:'廉贞天府是"规则加库藏"的稳局：外圆内方、能守能藏，逢吉稳中有成。它的短板在开创与变通，看懂这两端，稳的长处才用得恰到好处。',
 enClose:'Lian Zhen Tian Fu is a steady pattern of rules plus storehouse: easy outside and principled within, able to guard and keep, achieving with auspicious stars. Its short side is initiative and flexibility; understanding both lets the steadiness serve well.'},

{cat:'zhuxing',slug:'ziwei-wuqu-tianxiang-guanlu',focus:'武曲天相守官禄的财印组合',focusEn:'Wu Qu and Tian Xiang in the Career Palace as finance and seal',
 cnT:'紫微斗数武曲天相守官禄：制度内的财务、印信与授权',
 enT:'Wu Qu and Tian Xiang in the Career Palace: Finance, Seal and Authorization Within a System',
 cnD:'武曲是财星，主决断与执行；天相是印星，主制度、文书与协调。两星守官禄宫，主在制度内把钱、印、授权和风控管清楚，适合财务、稽核、审计、银行、行政或大型机构的管理岗。逢煞则防文书错误、责任不清与决断犹豫。',
 enD:'Wu Qu is the finance star of decision and execution; Tian Xiang is the seal star of systems, documents and coordination. Guarding the Career Palace together, they manage money, seal, authorization and risk control within a system, fitting finance, audit, banking, administration or management in large institutions. With malefics, guard against paperwork errors, unclear responsibility and hesitant decisions.',
 cnL:'有人把武曲当"只会赚钱"、天相当"老好人"，其实两星在事业宫合成"财印相辅"，是制度内很可靠的管理组合。',
 enL:'Some see Wu Qu as only earning and Tian Xiang as a people-pleaser, but in Career they blend finance and seal into a reliable management pair within systems.',
 cnA:'这个问题在问：武相在官禄适合做什么。核心是"按制度把财与事管稳"——讲流程、重授权、能把关，开创与单干不是它的首选。',
 enA:'The question is what Wu Qu Tian Xiang fits in Career. The core is steady control of money and matters by system: process-minded, authorization-aware and able to check, while solo pioneering is not its first choice.',
 cnLog:['武曲主财与决断，天相主印与制度，财印相扶则"有钱可管、有章可循、有权可授"。','守官禄者适合财务、会计、稽核、审计、银行、税务、法务辅助或行政管理。','长处是稳健、可靠、把关严，能在组织内把流程和风控立住。','逢擎羊陀罗、火星化忌则防文书出错、责任推诿与当断不断，需以复核和分工化解。'],
 enLog:['Wu Qu governs finance and decision, Tian Xiang the seal and system; together there is money to manage, rules to follow and authority to grant.','In Career they fit finance, accounting, audit, banking, tax, legal support or administration.','Their strength is steady, reliable checking that builds process and risk control in an organization.','With malefics, guard against paperwork errors, buck-passing and indecision, resolved through review and division of work.'],
 cnStep:['先确认官禄宫是否武曲天相坐守','读武曲的财与决断、天相的印与制度','看三方四正吉凶，判断财印是否相扶','吉则定位财务、稽核、审计、银行、管理岗','煞忌来则提示文书与责任风险，需复核','结合大限看体制内的升迁与授权节奏'],
 enStep:['First confirm Wu Qu Tian Xiang guards Career','Read Wu Qu finance and decision and Tian Xiang seal and system','Check the triple-direction to see whether finance and seal support each other','With auspicious stars, target finance, audit, banking or management','With malefics, note paperwork and responsibility risks requiring review','Use the decade to see promotion and authorization timing within the system'],
 cnMis:['把武相官禄只当"财务"，忽略印信与管理','见煞就断事业差，不看复核与分工的化解','以为财印相扶就可独当一面去单干'],
 enMis:['Taking it as only finance and ignoring seal and management','Judging the career as poor at malefics without review and division','Assuming finance-seal support means going solo is best'],
 cnClose:'武曲天相守官禄是"财印相辅"：在制度内把钱、授权、风控管稳，可靠而把关严。它的舞台在组织而非单干，煞忌处靠复核分工，长处才发挥得出来。',
 enClose:'Wu Qu Tian Xiang in Career is finance supported by seal: steadily managing money, authorization and risk within a system, reliable and careful. Its stage is the organization rather than solo work, and review plus division handle the malefics so its strength can show.'},

{cat:'zhuxing',slug:'ziwei-tianji-tianliang-fude',focus:'天机天梁坐福德的精神世界',focusEn:'Tian Ji and Tian Liang in the Fortune Palace and the inner world',
 cnT:'紫微斗数天机天梁坐福德：谋虑、规划与被庇荫的内心',
 enT:'Tian Ji and Tian Liang in the Fortune Palace: Planning and a Sheltered Inner World',
 cnD:'天机主思维、规划与应变，天梁主荫庇、稳重与原则，两星坐福德宫（精神宫），主内心爱谋虑、好钻研、做事有章法，也容易感到"有人托底"。偏学问、哲学、宗教或专业研究；逢煞则操心、失眠、想太多。',
 enD:'Tian Ji governs thinking, planning and adaptability, Tian Liang shelter, steadiness and principle. In the Fortune Palace they bring a mind that loves planning and study with a sense of method and of being backed, leaning toward scholarship, philosophy, religion or professional research. With malefics it turns to worry, insomnia and overthinking.',
 cnL:'有人福德宫天机天梁，脑子总停不下来，其实这是"善荫在精神宫"——爱想、也信道理，关键是别让思虑变成负担。',
 enL:'Some with Tian Ji Tian Liang in Fortune cannot switch the mind off; it is the thoughtful-sheltered pair in the inner palace, loving ideas and trusting principle, provided thinking does not become a burden.',
 cnA:'这个问题在问：机梁在福德的人内心偏什么。偏"谋定而后动"——喜欢先想清楚、讲依据、求稳妥，精神满足多来自钻研与被认可，逢吉则从容，逢煞则多虑。',
 enA:'The question is what the pair leans to in the inner palace. It is plan before acting: wanting clarity, grounds and steadiness, with inner satisfaction from study and recognition; with auspicious stars it is composed and with malefics it overworries.',
 cnLog:['天机主思维与规划，天梁主荫庇与原则，在福德宫合成"有谋、有守、有托底"的内心。','精神兴趣偏学问、研究、哲学、宗教、历史或专业深耕。','长处是思虑周密、讲章法、能自省，遇事倾向先弄明白再行动。','逢煞忌、天月则易操心、失眠、反复想，课题在"放下"与"给自己留白"。'],
 enLog:['Tian Ji governs thinking and planning, Tian Liang shelter and principle, blending in Fortune into an inner world of strategy, steadiness and backing.','Inner interests lean to scholarship, research, philosophy, religion, history or professional depth.','The strength is careful, methodical, self-reflective thinking that prefers understanding before acting.','With malefics it leans to worry, insomnia and looping thoughts; the lesson is letting go and leaving inner space.'],
 cnStep:['先确认福德宫是否天机天梁坐守','读天机的思维规划、天梁的荫庇原则','看三方四正吉凶，判断内心从容还是多虑','吉则看其钻研、研究与精神追求','煞忌来则提示操心失眠，需练留白','结合大限看精神状态在哪个阶段舒展'],
 enStep:['First confirm Tian Ji Tian Liang guards Fortune','Read Tian Ji thinking and Tian Liang shelter','Check the triple-direction to see composure or overworry','With auspicious stars, see the study and inner pursuits','With malefics, note worry and insomnia and practice leaving space','Use the decade to see when the inner state opens'],
 cnMis:['把机梁福德只当"想太多"，忽略其钻研深度','见煞就断精神差，不看自我调节','以为爱谋虑就一定优柔寡断'],
 enMis:['Taking it as mere overthinking and ignoring depth of study','Judging poor inner health at malefics without self-regulation','Assuming a planning mind is always indecisive'],
 cnClose:'天机天梁坐福德是"善荫在内心"：爱谋虑、好钻研、讲章法，也信有人托底。它的课题在别让思虑过载，学会留白，这份周密才是滋养而不是消耗。',
 enClose:'Tian Ji Tian Liang in Fortune is thoughtful shelter within: loving plans and study with method and a sense of backing. Its lesson is keeping thought from overload and leaving space, so the care becomes nourishment rather than drain.'},

{cat:'zhuxing',slug:'ziwei-tiantong-tianliang-fuqi',focus:'天同天梁坐夫妻的被照顾关系',focusEn:'Tian Tong and Tian Liang in the Spouse Palace and the cared-for bond',
 cnT:'紫微斗数天同天梁坐夫妻：讲情分、被照顾型的关系',
 enT:'Tian Tong and Tian Liang in the Spouse Palace: A Bond of Affection and Being Cared For',
 cnD:'天同是福星，主温和、享受与孩子气；天梁是荫星，主照顾、老成与原则。两星坐夫妻宫，主关系讲情分、偏被照顾，配偶往往成熟、体贴、愿意担事，年龄或心态偏长。逢煞则防依赖、长幼心态与一方过度操心。',
 enD:'Tian Tong is the blessing star of gentleness, enjoyment and a childlike quality; Tian Liang is the shelter star of care, maturity and principle. In the Spouse Palace they bring an affectionate, cared-for bond, with a partner who is often mature, thoughtful and willing to carry things, older in years or manner. With malefics, guard against dependence, a parent-child dynamic and one side overworrying.',
 cnL:'有人夫妻宫天同天梁，关系里总有人在"照顾"另一个，其实这是福荫相遇——温情有余，关键是别让照顾变成依赖。',
 enL:'With Tian Tong Tian Liang in Spouse, one person often cares for the other; it is blessing meeting shelter, warm enough that care should not become dependence.',
 cnA:'这个问题在问：同梁在夫妻的关系模式是什么。底色是"温情加照顾"——重情分、讲体谅、想安稳，精神上像有个依靠，但需要各自独立，避免一方永远像长辈。',
 enA:'The question is the relationship pattern. The baseline is warmth plus care: valuing affection and understanding and wanting steadiness, with a sense of having someone to lean on, yet each needs independence so one is not forever the elder.',
 cnLog:['天同主温和与福气，天梁主照顾与荫庇，在夫妻宫合成"有情、有靠、有人担"的关系。','配偶多成熟、体贴、乐照顾，可能年长或心态稳重，关系偏温情安稳。','长处是重情、包容、顾家，能在平淡里相守。','逢煞忌则易依赖、长幼错位、一方操心，课题在"各自成长"与"平等相处"。'],
 enLog:['Tian Tong governs gentleness and blessing, Tian Liang care and shelter, blending in Spouse into a bond of affection, backing and someone to carry things.','The partner is often mature, thoughtful and caring, possibly older or steady, and the relationship leans warm and stable.','The strength is affection, tolerance and devotion to home, able to stay together through ordinary days.','With malefics it leans to dependence, an elder-child mismatch and one side worrying; the lesson is growing separately and relating as equals.'],
 cnStep:['先确认夫妻宫是否天同天梁坐守','读天同的温和福气、天梁的照顾荫庇','看三方四正吉凶，判断温情安稳还是依赖','吉则看其顾家、重情、能相守','煞忌来则提示依赖与长幼错位，需各自独立','结合大限看关系在哪个阶段成熟'],
 enStep:['First confirm Tian Tong Tian Liang guards Spouse','Read Tian Tong gentleness and Tian Liang care','Check the triple-direction to see warm steadiness or dependence','With auspicious stars, see devotion, affection and lasting companionship','With malefics, note dependence and the elder-child dynamic, requiring independence','Use the decade to see when the bond matures'],
 cnMis:['把同梁夫妻只当"被照顾"，忽略温情与责任','见煞就断婚姻差，不看双方成长','以为有荫星照顾就可以一直依赖'],
 enMis:['Taking it as merely being cared for and ignoring warmth and responsibility','Judging the marriage as poor at malefics without mutual growth','Assuming shelter means dependence can last forever'],
 cnClose:'天同天梁坐夫妻是"福荫相遇"：温情、体谅、有人照顾、能在平淡里相守。它的课题在平等与独立，别让照顾变依赖，这份安稳才长久。',
 enClose:'Tian Tong Tian Liang in Spouse is blessing meeting shelter: warm, understanding, cared for and able to stay through ordinary days. Its lesson is equality and independence so care does not become dependence and the steadiness lasts.'},

{cat:'liunian',slug:'ziwei-daxian-qianwunian-houwunian-yingqi',focus:'大限前后五年的南北斗应期',focusEn:'timing the first and second five years of a decade by dipper',
 cnT:'紫微斗数大限前五年后五年怎么分：北斗应前、南斗应后',
 enT:'Dividing the First and Second Five Years of a Decade in Zi Wei Dou Shu',
 cnD:'一个大限十年，吉凶不会平均落在十年里：北斗星的吉凶多应在前五年、南斗星多应在后五年，上半年下半年也同理。它帮你把十年里的大事点到更具体的阶段，但仍要结合四化引动，不能机械套。',
 enD:'Within a ten-year decade, effects do not land evenly: Northern Dipper stars tend to manifest in the first five years and Southern Dipper stars in the last five, likewise for the first and second half of a year. It helps place major events in a more specific stage, but still combine the transformations rather than applying it mechanically.',
 cnL:'有人走大限只问"这十年好不好"，其实同是吉，北斗的吉来得早、南斗的吉来得晚，分清前后，节奏判断才细。',
 enL:'Some only ask whether the decade is good, yet Northern fortune arrives early and Southern fortune late; dividing the halves refines the timing.',
 cnA:'这个问题在问：怎么把十年的事点到前半还是后半。先看主事星属北斗还是南斗，再看大限四化在哪几年引动，两者合起来定阶段，而不是凭一条口诀硬断。',
 enA:'The question is how to place a decade matter in the first or second half. First see whether the governing star is Northern or Southern, then see which years the decade transformations activate, combining both rather than relying on one rhyme.',
 cnLog:['北斗星（紫微、武曲、廉贞、贪狼、巨门、破军）多主开创，吉凶多应在大限前五年。','南斗星（天府、天机、天同、天相、天梁、七杀）多主蓄守，吉凶多应在后五年。','以一年论，北斗多应上半年、南斗多应下半年，是同一条规律的细化。','这只是"倾向哪个阶段"的参考，具体年份仍以大限、流年四化的引动为准。'],
 enLog:['Northern stars tend to initiate and their effects land in the first five years.','Southern stars tend to gather and guard and their effects land in the last five.','Within a year, Northern effects lean to the first half and Southern to the second, the same rule refined.','It only indicates the likely stage; the exact year still follows the decade and year transformations.'],
 cnStep:['先确定大限里主事的星曜组合','分辨主星属北斗还是南斗','北斗为主则重点看前五年、南斗为主看后五年','再排大限四化，找具体被引动的流年','把"南北斗倾向"与"流年引动"对齐','结论给阶段与节奏，不把口诀当死年份'],
 enStep:['First identify the governing stars of the decade','Tell whether they are Northern or Southern','If Northern, focus the first five years; if Southern, the last five','Then place the decade transformations to find activated years','Align the dipper tendency with the year activation','Conclude with stage and rhythm, not treating the rhyme as fixed years'],
 cnMis:['把十年吉凶平均看，不分前后','机械认定北斗必应前、南斗必应后，不看四化','只分了前后五年却不落到具体流年'],
 enMis:['Treating decade fortune as even across the halves','Mechanically fixing North to early and South to late without transformations','Dividing the halves but never pinning specific years'],
 cnClose:'大限应期分前后：北斗主事先应前五年、南斗主事后应五年。它给的是阶段倾向，再用流年四化钉死年份，十年节奏才看得又细又稳。',
 enClose:'Decade timing divides into halves: Northern-led matters show early and Southern-led late. It gives a stage tendency, then the year transformations pin the years, making the ten-year rhythm both detailed and sound.'},

{cat:'liunian',slug:'ziwei-daxian-shunni-yangnan-yinnv',focus:'大限顺逆行的排法',focusEn:'determining the forward and backward direction of decades',
 cnT:'紫微斗数大限顺逆行怎么定：阳男阴女顺、阴男阳女逆',
 enT:'How to Determine the Direction of Decades in Zi Wei Dou Shu',
 cnD:'大限从命宫起排，方向由生年天干阴阳和性别共同决定：阳男、阴女顺行（顺时针，命宫→兄弟→夫妻），阴男、阳女逆行（逆时针，命宫→父母→福德）。起运年龄则由五行局定（水二、木三、金四、土五、火六）。',
 enD:'Decades begin from the Life Palace and their direction is set by the yin-yang of the birth stem together with sex: yang males and yin females go forward clockwise, while yin males and yang females go backward counterclockwise. The starting age is set by the element phase, such as two for water and three for wood.',
 cnL:'有人排大限方向搞反，后面所有十年宫位全错，其实只要记住"阳男阴女顺、阴男阳女逆"这一条，方向就不会错。',
 enL:'Some reverse the decade direction and every later ten-year palace is wrong; remembering the one rule keeps it straight.',
 cnA:'这个问题在问：为什么有人顺排、有人逆排。关键看两个条件——生年天干是阴是阳、是男是女，两者一组合方向即定；再配合五行局起运岁数。',
 enA:'The question is why some go forward and some backward. It depends on two conditions: whether the birth stem is yin or yang and the sex; combining them sets the direction, with the element phase setting the start age.',
 cnLog:['阳干（甲丙戊庚壬）生男、阴干（乙丁己辛癸）生女为顺行，顺时针走兄弟、夫妻方向。','阴干生男、阳干生女为逆行，逆时针走父母、福德方向。','起运岁数由五行局定：水二局、木三局、金四局、土五局、火六局。','大限每十年一宫，方向定错则整张运限图全偏，需先核对再起盘。'],
 enLog:['Yang-stem males and yin-stem females go forward clockwise toward Siblings and Spouse.','Yin-stem males and yang-stem females go backward counterclockwise toward Parents and Karma.','The start age follows the element phase: water two, wood three, metal four, earth five, fire six.','Each decade spans ten years in one palace; a wrong direction skews the whole limit map, so verify before reading.'],
 cnStep:['先确认生年天干属阴还是阳','再确认性别，按"阳男阴女顺、阴男阳女逆"定方向','顺行从命宫顺时针、逆行逆时针','用五行局定起运岁数（水二木三金四土五火六）','逐宫排十年大限并标注年龄','排完用过往大事核对方向与岁数是否对'],
 enStep:['First confirm whether the birth stem is yin or yang','Then confirm sex and set the direction','Forward goes clockwise from Life and backward counterclockwise','Use the element phase for the start age','Place the ten-year decades palace by palace with ages','Verify against past events that direction and ages are correct'],
 cnMis:['只看性别或只看天干，方向判断不全','顺逆搞反还照着断十年','忽略五行局起运岁数，年龄全错位'],
 enMis:['Using only sex or only stem to set direction','Reversing forward and backward while reading the decades','Ignoring the element-phase start age so ages are all off'],
 cnClose:'大限方向是运限的骨架：天干阴阳配性别，阳男阴女顺、阴男阳女逆，再用五行局定起岁。这一步对了，后面十年一宫的排法才立得住。',
 enClose:'Decade direction is the skeleton of the limit map: stem yin-yang with sex sets forward or backward, and the element phase sets the start age. With this correct, the ten-year palaces hold.'},

{cat:'liunian',slug:'ziwei-liunian-dizhi-shiernian-xunhuan',focus:'流年地支十二年循环',focusEn:'the twelve-year cycle of annual branches',
 cnT:'紫微斗数流年地支十二年循环：当年激活本命哪一宫',
 enT:'The Twelve-Year Cycle of Annual Branches in Zi Wei Dou Shu: Which Natal Palace It Activates',
 cnD:'流年地支与本命某宫的地支同位，该年流年命宫就落在那一宫，十二年转一圈，激活这一宫的主题。如流年走到命宫地支即本命年（虚岁12、24、36…）。再叠流年四化，才知道这一年把哪条线点亮。',
 enD:'When the year branch matches the branch of a natal palace, that year annual Life Palace lands there, cycling every twelve years and activating that palace theme; for example reaching the Life branch is the birth-year age. Add the annual transformations to see which line is lit.',
 cnL:'有人看流年只查当年生肖运势，其实流年走到本命哪一宫，那宫的事就被推到台前，这比套"属什么今年如何"更具体。',
 enL:'Some read the year only by zodiac fortune, but where the year lands among the natal palaces pushes that matter forward, more concrete than generic zodiac readings.',
 cnA:'这个问题在问：怎么定位某一年重点在哪一宫。先找流年地支对应本命哪宫，再看流年四化飞入哪几宫，两者合起来定当年主题。',
 enA:'The question is how to locate which palace a given year emphasizes. First find which natal palace the year branch matches, then see where the annual transformations fly; together they set the theme.',
 cnLog:['流年命宫按地支定位：流年地支与某宫地支同位即落该宫，十二年一循环。','该宫主题在这一年被推到台前，流年走到命、财、官、夫等宫各有侧重。','再叠流年四化（如2026丙午年天同化禄、天机化权、文昌化科、廉贞化忌）看能量落点。','流年只是引动，强弱仍以本命与大限的底色为准。'],
 enLog:['The annual Life Palace is set by branch: matching a natal palace lands there in a twelve-year cycle.','That palace theme is pushed forward that year, with different emphasis for Life, Wealth, Career or Spouse.','Then add the annual transformations to see where energy lands.','The year only activates; strength still follows the natal and decade baseline.'],
 cnStep:['先取流年地支','在本命盘找同地支的宫位，即流年命宫落点','看该宫本命主题与主星','再排流年四化，找禄权科忌飞入哪几宫','把"落宫主题"与"四化落点"合起来','结合大限判断当年轻重，不凭生肖断吉凶'],
 enStep:['First take the year branch','Find the natal palace with the same branch, the annual Life landing','Read that palace natal theme and stars','Then place the annual transformations to see where they fly','Combine the landing theme and transformation points','Use the decade to judge weight, not fortune by zodiac'],
 cnMis:['只看生肖流年，不定位本命宫位','流年命宫找到了却不叠四化','把流年激活当成全新的命运，忽略本命底色'],
 enMis:['Reading only zodiac fortune without locating natal palaces','Finding the annual palace but not adding transformations','Taking the year activation as a new fate and ignoring the natal baseline'],
 cnClose:'流年十二年转一圈，落到本命哪宫就激活哪宫，再用流年四化找能量落点。本命打底、大限定势、流年触发——三层合看，当年重点才判得准。',
 enClose:'The year cycles every twelve and activates the natal palace it lands on, then annual transformations locate energy. Natal grounds, decade sets and year triggers; reading all three pins the year focus.'},

{cat:'liunian',slug:'ziwei-liuyue-ganzhi-zenme-pai',focus:'流月干支的排法',focusEn:'placing the stems and branches of monthly luck',
 cnT:'紫微斗数流月干支怎么排：把一年的趋势落到月份',
 enT:'How to Place Monthly Stems and Branches in Zi Wei Dou Shu',
 cnD:'流月地支按农历正月起寅、依次顺排；流月天干用「五虎遁」由年干推（甲己年正月起丙寅、乙庚起戊寅、丙辛起庚寅、丁壬起壬寅、戊癸起甲寅）。逐月推进，就能把年度趋势与四化落到具体月份，找事情的高发月。',
 enD:'Monthly branches follow the lunar months starting with the first at Yin, while monthly stems are derived from the year stem using the five-tiger method, for example a Jia-Ji year starts the first month at Bing Yin. Moving month by month brings the annual trend and transformations down to specific months to find high-event periods.',
 cnL:'有人知道流年趋势却不会落到月份，其实只要会五虎遁排流月干支，再看流月四化，哪月顺、哪月紧就清楚了。',
 enL:'Some know the year trend but cannot bring it to months; with the five-tiger stems and monthly transformations, which months are smooth or tense becomes clear.',
 cnA:'这个问题在问：流月具体怎么排、怎么用。先由年干遁出正月天干、配月支，再逐月顺排；然后看流月四化引动哪一宫，把年度的事点到月。',
 enA:'The question is how monthly luck is placed and used. First derive the first-month stem from the year stem with its branch, then proceed month by month; then see which palace the monthly transformations activate to place annual matters by month.',
 cnLog:['流月地支：农历正月固定起寅，二月卯、三月辰，顺数十二支。','流月天干用五虎遁：甲己起丙寅、乙庚起戊寅、丙辛起庚寅、丁壬起壬寅、戊癸起甲寅。','流月四化由流月天干去遁，看当月禄权科忌飞入哪宫。','流月只在需要精确择月（如跳槽、签约、考试）时细看，用于把年度趋势点到高发月。'],
 enLog:['Monthly branches: the first lunar month is fixed at Yin, then Mao and Chen through the twelve branches.','Monthly stems use the five-tiger method: Jia-Ji at Bing Yin, Yi-Geng at Wu Yin, Bing-Xin at Geng Yin, Ding-Ren at Ren Yin and Wu-Gui at Jia Yin.','Monthly transformations derive from the monthly stem to see where that month forces fly.','Monthly luck is examined when a precise month matters, bringing the annual trend to high-event periods.'],
 cnStep:['先确定流年（农历）年干','用五虎遁遁出正月的天干、配寅支','按顺序排出十二个月的干支','再由每月天干遁出流月四化','找流月四化引动的宫位，定高发月','结合流年大限，判断哪月宜进、哪月宜守'],
 enStep:['First determine the lunar year stem','Use the five-tiger method for the first-month stem with the Yin branch','Place the twelve months in order','Then derive each month transformations','Find the palaces activated to set high-event months','Combine year and decade to judge which months to push or guard'],
 cnMis:['流月地支排错（不从寅起）','五虎遁用错年干，整月天干全偏','把流月当主要判断，忽略它只作年度内的细化'],
 enMis:['Placing monthly branches wrongly, not starting at Yin','Using the wrong year stem in the five-tiger method so all stems shift','Treating months as the main verdict and forgetting they only refine the year'],
 cnClose:'流月是年度趋势的细化：月支从寅起、月干用五虎遁，再看流月四化引动哪宫。需要择月时把它排准，哪月发力、哪月收敛，就有了更细的节奏。',
 enClose:'Monthly luck refines the annual trend: branches start at Yin, stems use the five-tiger method, and monthly transformations show activation. Place it accurately when choosing a month for a finer rhythm of when to push and when to hold.'}
];
