// 2026-09-30 调研驱动 第3组：流年忌入命/大限天府/武七财/紫贪疾/紫贪迁/机巨友/武贪官/机阴福 8篇
module.exports=[
{cat:'liunian',slug:'ziwei-liunian-huaji-ru-minggong',focus:'流年化忌入命宫',focusEn:'the annual Hua Ji entering the Life Palace',
 cnT:'紫微斗数流年化忌入命宫：向内修的一年，怎么过不内耗',
 enT:'When the Annual Hua Ji Enters Your Life Palace: A Year of Inner Work Without Self-Drain',
 cnD:'流年天干化忌落在流年命宫（与本命宫同位），这一年人容易对自己要求高、反复琢磨、情绪内收，是「向内修」的年份，而非外事变坏；把劲用在打磨自己上，反而出活。',
 enD:'When the year-stem Hua Ji lands in the annual Life Palace (coinciding with the natal Life Palace), one tends toward high self-standards, repeated reflection and inward emotion that year—a year of inner work rather than outer events turning bad; directing the energy to refining oneself actually produces results.',
 cnL:'有人某一年突然变得爱钻牛角尖、对自己不满意，事情没出什么，心里却很累，这往往是流年化忌入命的味道：考题不在外面，在「怎么和自己相处」。',
 enL:'Some people suddenly grow prone to overthinking and self-dissatisfaction in a given year, feeling tired inside despite little going wrong outside; this is often the tone of annual Hua Ji entering the Life Palace: the test is not out there but how to be with oneself.',
 cnA:'这个问题在问：流年忌入命这一年会怎样、怎么过。要先分清它主「内在收紧」而非「外在灾祸」，再把这股认真劲导向具体的打磨与积累。',
 enA:'The question is what a year with annual Ji in the Life Palace brings and how to live it. First separate inner tightening from outer disaster, then direct the earnest energy toward concrete refinement and accumulation.',
 cnLog:['化忌主牵挂与执着，流年忌入命，这一年注意力收回到自己身上，标准高、感受细、也容易自我否定。','它是「时间层」的象，只主这一年的状态，不是一生底色，更不是外事变坏的判决书。','用得好，这一年特别适合打磨技能、修正习惯、深度钻研，出活质量常比往年高。','若被情绪带着走，则易内耗、失眠、钻牛角尖；配合流年福德、疾厄一起看，必要时以正规就医与专业心理支持为准。'],
 enLog:['Hua Ji governs concern and attachment; with the annual Ji in the Life Palace, attention returns to oneself that year—standards high, feelings sharp and self-questioning easy.','It is a time-layer image governing only that year\u2019s state, not the lifelong tone, and certainly not a verdict of outer events turning bad.','Used well, this year especially suits refining skills, correcting habits and deep study, often producing higher-quality work than other years.','If carried by emotion, it easily brings inner drain, insomnia and overthinking; read it together with the annual Karma and Health palaces, relying on proper medical and professional psychological support when needed.'],
 cnStep:['先确认流年化忌是否落在流年命宫（与本命同位）','把它读成「向内修的年份」，不先往灾祸上想','给这一年设一两个具体的打磨目标（技能、习惯、作品）','把高标准拆成可完成的小步，避免反复自我否定','安排运动、休息与社交，给内收的情绪留出口','逐月对照，看进展而不是只盯情绪，年末再回看收获'],
 enStep:['First confirm whether the annual Hua Ji lands in the annual Life Palace coinciding with the natal one','Read it as a year of inner work rather than assuming disaster','Set one or two concrete refinement goals for the year: skills, habits or work','Break high standards into small, completable steps to avoid repeated self-denial','Arrange exercise, rest and social contact to give the inward emotion an outlet','Compare month by month, watching progress rather than only mood, and review gains at year\u2019s end'],
 cnMis:['把流年忌入命当成「今年要倒大霉」，自己吓自己','只感到内耗却不行动，把认真劲空转在情绪上','把一年的状态误读成一生底色，忘了它随流年而走'],
 enMis:['Taking annual Ji in the Life Palace as disaster ahead and frightening oneself','Feeling inner drain without acting, idling the earnest energy in emotion','Misreading one year\u2019s state as the lifelong tone and forgetting it passes with the year'],
 cnClose:'流年化忌入命，不是外事变坏，而是一年「向内用功」的邀请。把标准落到具体打磨上、给情绪留出口，年末你会发现这一年的长进往往最扎实。',
 enClose:'Annual Hua Ji in the Life Palace is not outer events turning bad but an invitation to a year of inner work. Put standards onto concrete refinement and give emotion an outlet; at year\u2019s end you often find this year\u2019s growth the most solid.'},

{cat:'liunian',slug:'ziwei-daxian-zou-tianfu-shinian',focus:'大限走天府这十年',focusEn:'the decade moving through Tian Fu',
 cnT:'紫微斗数大限走天府这十年：库藏、稳守与家底积累期',
 enT:'The Decade Through Tian Fu: A Ten-Year Period of Storage, Stewardship and Building Foundations',
 cnD:'十年大限命宫落天府，主这一阶段重在守成、积累与安顿，资源偏「进得来也要留得住」，适合沉淀家底、稳固平台，不宜在这十年冒进铺摊。',
 enD:'When the decade Life Palace falls on Tian Fu, the stage emphasizes consolidation, accumulation and settling; resources must both come in and be retained. It suits building foundations and steadying the platform, rather than aggressive expansion during these ten years.',
 cnL:'有人走到某步大限，节奏自然慢下来，开始想存钱、安家、稳住一摊事，这就是大限走天府的味道：十年主题不在冲，在「守得住、积得厚」。',
 enL:'When people enter a certain decade, the pace naturally slows and they begin thinking of saving, settling and steadying their affairs; this is the tone of the decade through Tian Fu: the ten-year theme is not charging but retaining and accumulating depth.',
 cnA:'这个问题在问：大限走天府这十年该怎么把握。要先理解天府是「库星」，主稳守与资源管理，再判断这十年该守什么、怎么积。',
 enA:'The question is how to make the most of a decade through Tian Fu. First understand Tian Fu as the storehouse star governing stewardship and resource management, then judge what to retain and how to accumulate in these ten years.',
 cnLog:['天府为南斗主、库藏之星，主资源管理、稳定与包容，大限走此，十年基调偏守。','这一阶段机会未必最多，但资源容易沉淀：适合储蓄、置业、巩固团队与把一门做深。','天府能「容」也能「守」，要防过于保守、只守不进，该布局的新线仍要适度投入。','读法看三方：见禄与辅星，库能充实；见煞忌，则易守得吃力或因资产、人事而生耗。'],
 enLog:['Tian Fu is the Southern Dipper ruler and storehouse star, governing resource management, stability and inclusiveness; with the decade here, the ten-year tone leans toward retaining.','Opportunities may not be most numerous in this stage, but resources settle readily: it suits saving, property, consolidating teams and deepening one field.','Tian Fu can contain and retain; guard against over-conservatism that only defends without advancing, and still invest moderately in new lines worth positioning.','Read the triple-direction: with Lu and assistant stars the storehouse fills; with malefics and Ji, retaining feels strained or drains arise through assets and personnel.'],
 cnStep:['先确认当前大限命宫是否落在天府','把这十年主题定为「守成、积累、安顿」','盘点要守住的资源：存款、平台、团队、专长','在稳的前提下，给一两条新线留适度投入','看三方禄星辅星与煞忌，判断库能充实还是守得吃力','十年节奏按前稳后开安排，避免一上来就冒进'],
 enStep:['First confirm whether the current decade Life Palace falls on Tian Fu','Set the ten-year theme as consolidation, accumulation and settling','Take stock of resources to retain: savings, platform, team and expertise','On the premise of stability, leave moderate investment for one or two new lines','Check the triple-direction for Lu, assistant stars, malefics and Ji to judge whether the storehouse fills or retaining strains','Arrange the decade as steady first and opening later, avoiding aggression at the start'],
 cnMis:['把大限天府当成「可以躺平」，只守不经营','见节奏偏稳就急着冒进铺摊，违背库星本性','忽略三方煞忌，守成也可能守得很吃力'],
 enMis:['Taking the decade through Tian Fu as a reason to lie back and defend without managing','Growing impatient with the steady pace and expanding aggressively against the storehouse nature','Ignoring triple-direction malefics and Ji, so consolidation can still feel strained'],
 cnClose:'大限走天府，是十年「守库、积家底」的阶段。稳住基本盘、适度布新线，这十年把根扎深，下一步开拓时你才有足够的本钱。',
 enClose:'The decade through Tian Fu is a stage of guarding the storehouse and building foundations. Steady the base and invest moderately in new lines; deepen the roots in these ten years and you have ample capital for the next stage\u2019s opening.'},

{cat:'zhuxing',slug:'ziwei-wuqu-qisha-zai-caibogong',focus:'武曲七杀在财帛宫',focusEn:'Wu Qu and Qi Sha in the Wealth Palace',
 cnT:'武曲七杀在财帛宫：赚钱敢拼大单，也要防财来财去',
 enT:'Wu Qu and Qi Sha in the Wealth Palace: Bold for Big Deals While Guarding Against Easy Come, Easy Go',
 cnD:'武曲是财星、七杀是将星，两星同入财帛，赚钱风格硬、敢接大单、能在竞争中取财，但钱来得猛去得也快，关键看有没有库星与规划把钱留住。',
 enD:'Wu Qu is the wealth star and Qi Sha the general star; together in the Wealth Palace, the earning style is hard-edged, bold for big deals and able to take money through competition, but money arrives and leaves fast. The key is whether storehouse stars and planning retain it.',
 cnL:'有人赚钱像打仗，专挑有挑战、金额大的活，敢拼也真能拿下；可这种财路最怕「左手进右手出」，赚得多却留不住。',
 enL:'Some earn money like fighting a campaign, choosing challenging, large deals and able to win them; but this financial path most fears money entering one hand and leaving the other—earning much yet retaining little.',
 cnA:'这个问题在问：武曲七杀同守财帛怎么读。要把「敢拼能赚」和「留不留得住」分开，前者看星性，后者看库星、煞忌与用钱习惯。',
 enA:'The question is how to read Wu Qu and Qi Sha guarding Wealth together. Separate bold earning from retention: the first rests on star nature, the second on storehouse stars, malefics, Ji and spending habits.',
 cnLog:['武曲主财与规则，七杀主决断与执行，两星同宫是「财星遇上将星」，赚钱有魄力、敢竞争。','适合大单、项目制、开拓型与竞争性强的财路，收入弹性大、上限高。','风险在「破」：七杀带孤克、武曲忌硬，财来财去、大起大落，煞忌重时更明显。','能否留住，看三方有没有天府、禄存等库星，以及自己有没有储蓄规划，否则只是过路财。'],
 enLog:['Wu Qu governs wealth and rules, Qi Sha governs decisiveness and execution; together the wealth star meets the general star, earning with boldness and willingness to compete.','It suits large deals, project-based, pioneering and highly competitive income, with large elasticity and a high ceiling.','The risk is breaking: Qi Sha carries solitary firmness and Wu Qu favors hard edges, so money comes and goes with big swings, especially with heavy malefics and Ji.','Whether it is retained depends on storehouse stars such as Tian Fu or Lu Cun in the triple-direction and on your own savings plan; otherwise it is merely passing money.'],
 cnStep:['先确认财帛宫是武曲七杀同守，并看亮度','把「敢拼能赚」与「留不留得住」分开判断','看三方有没有天府、禄存等库星','数煞忌，评估大起大落与破财风险','给大单收入预设储蓄比例，到账先划走再谈花','结合大限流年，在财星被引动的年份大胆接单、在煞重年份守现金'],
 enStep:['First confirm Wu Qu and Qi Sha guard Wealth together and check brightness','Separate bold earning from retention','Check whether the triple-direction has storehouse stars such as Tian Fu or Lu Cun','Count malefics and Ji to weigh big swings and loss risk','Preset a savings ratio for large-deal income, moving it aside on arrival before spending','With the decade and year, take bold deals when the wealth stars activate and guard cash in heavy-malefic years'],
 cnMis:['见武曲七杀就断「能赚大钱」，忽略留财条件','把大单收入当常态收入安排开支，结果淡季吃紧','只拼赚不规划留，赚得多却始终没积蓄'],
 enMis:['Judging great wealth from Wu Qu and Qi Sha while ignoring retention conditions','Treating large-deal income as steady income when planning expenses, leading to tight off-seasons','Only chasing earnings without planning retention, earning much yet never saving'],
 cnClose:'武曲七杀守财帛，天赋在敢拼大单，功课在把钱留住。配上库星与储蓄纪律，这组星的高上限才真正变成你账户里的存量。',
 enClose:'Wu Qu and Qi Sha guarding Wealth gift boldness for big deals, and the lesson is retaining money. Pair it with storehouse stars and savings discipline; then the pair\u2019s high ceiling truly becomes the balance in your account.'},

{cat:'zhuxing',slug:'ziwei-ziwei-tanlang-zai-jiegong',focus:'紫微贪狼在疾厄宫',focusEn:'Zi Wei and Tan Lang in the Health Palace',
 cnT:'紫微贪狼在疾厄宫：应酬多、节奏满，身体最需要给欲望设边界',
 enT:'Zi Wei and Tan Lang in the Health Palace: A Full Social Schedule and the Body\u2019s Need for Boundaries',
 cnD:'紫微是帝星、贪狼主欲望交际，两星同入疾厄，身体常与应酬、熬夜、饮食丰盛绑定，肝胆代谢与心血管负担要留意；倾向非诊断，规律作息、节制应酬是关键。',
 enD:'Zi Wei is the emperor star and Tan Lang governs appetite and socializing; together in the Health Palace, the body is often tied to entertaining, late nights and rich food, with attention to liver-gallbladder metabolism and cardiovascular load. This is a tendency, not a diagnosis; regular rest and tempered socializing are key.',
 cnL:'有人身体没什么大病，却常被应酬、酒局、熬夜拖着走，体检指标随生活节奏起伏，这就是紫微贪狼在疾厄的味道：身体的功课多在「管不住欲望和面子」。',
 enL:'Some have no major illness yet are carried along by entertaining, drinking and late nights, with check-up numbers rising and falling with their lifestyle; this is the tone of Zi Wei and Tan Lang in Health: the body\u2019s lesson is often governing appetite and face.',
 cnA:'这个问题在问：紫微贪狼落疾厄怎么读。要把「应酬型身体模式」看清，它给的是生活方式上的倾向提醒，不是具体疾病预言。',
 enA:'The question is how to read Zi Wei and Tan Lang in Health. See the entertaining-driven body pattern clearly; it gives a lifestyle tendency reminder, not a specific disease prediction.',
 cnLog:['紫微主尊贵与统筹，贪狼主欲望与交际，入疾厄则身体常被社交应酬、饮食与情绪兴奋牵动。','现实中多表现为作息满、酒局多、口味重，肝胆、代谢与心血管系统更易随年龄亮提醒。','盘是倾向不是诊断：同样配置，节制者指标稳、放纵者负担重，差别在生活方式。','见禄与辅星，恢复力不差、也易得好医生照顾；见煞忌，则要更早管住应酬，身体不适以正规就医为准。'],
 enLog:['Zi Wei governs dignity and coordination, Tan Lang appetite and socializing; in Health the body is often moved by social entertaining, rich food and emotional excitement.','In practice it appears as a full schedule, many drinking occasions and heavy flavors, with liver-gallbladder, metabolic and cardiovascular systems more likely to signal with age.','The chart is a tendency, not a diagnosis: with the same configuration, the temperate keep steady numbers and the indulgent carry heavier loads; the difference is lifestyle.','With Lu and assistant stars, recovery is decent and good care is readily found; with malefics and Ji, socializing must be curbed earlier, and any discomfort relies on proper medical treatment.'],
 cnStep:['先确认疾厄宫是紫微贪狼同守','把它读成「应酬型身体模式」，不先往大病上想','盘点日常的酒局、熬夜、重口味与情绪兴奋频率','给应酬与饮食设硬边界（次数、量、作息时间）','每年规律体检，关注代谢与心血管指标','见煞忌或指标异常时尽早就诊，以正规医疗为准'],
 enStep:['First confirm Zi Wei and Tan Lang guard Health together','Read it as an entertaining-driven body pattern rather than assuming major illness','Take stock of the frequency of drinking occasions, late nights, heavy flavors and emotional excitement','Set firm boundaries around socializing and diet: occasions, amounts and rest times','Have regular annual check-ups, watching metabolic and cardiovascular indicators','Seek care early with malefics, Ji or abnormal numbers, relying on proper medical treatment'],
 cnMis:['把紫微贪狼在疾厄直接断成某种大病','只归咎于命盘，不管住应酬与作息','把倾向当诊断，自己吓自己，或反向忽视体检'],
 enMis:['Directly predicting a specific major illness from Zi Wei and Tan Lang in Health','Blaming the chart while not curbing socializing and rest','Taking a tendency as a diagnosis and frightening oneself, or conversely skipping check-ups'],
 cnClose:'紫微贪狼在疾厄，提醒的是「应酬与欲望会写在身体上」。给社交与饮食设边界、规律体检，这组星的健康功课，多半靠生活方式就能答好。',
 enClose:'Zi Wei and Tan Lang in Health remind that socializing and appetite are written on the body. Set boundaries around both and have regular check-ups; this pair\u2019s health lesson can mostly be answered well through lifestyle.'},

{cat:'zhuxing',slug:'ziwei-ziwei-tanlang-zai-qianyigong',focus:'紫微贪狼在迁移宫',focusEn:'Zi Wei and Tan Lang in the Travel Palace',
 cnT:'紫微贪狼在迁移宫：在外多彩、机会多，也要防应酬与分心',
 enT:'Zi Wei and Tan Lang in the Travel Palace: Colorful Opportunities Away from Home, with Guard Against Distraction',
 cnD:'紫微贪狼同守迁移，在外人面前有气场、善交际、机会与桃花都偏多，适合外向型、应酬型发展；但外面世界太热闹也易分心、耗神，关键看本命能否收得住。',
 enD:'Zi Wei and Tan Lang guarding Travel gives presence and sociability in front of outsiders, with many opportunities and romantic possibilities, suiting outward and networking-driven paths; but a too-colorful outer world easily distracts and drains; the key is whether the natal self can stay focused.',
 cnL:'有人一出门、换个环境就如鱼得水，朋友多、机会多、场面也撑得住，这是紫微贪狼在迁移的味道：外部舞台又大又热闹，就怕看花了眼。',
 enL:'Some thrive the moment they leave home or change environments, with many friends, opportunities and an ability to hold the room; this is the tone of Zi Wei and Tan Lang in Travel: the outer stage is large and lively, and the risk is being dazzled.',
 cnA:'这个问题在问：紫微贪狼落迁移怎么读。要把「在外的机会与魅力」和「分心、应酬耗神」两面都看到，再判断怎么用外部舞台。',
 enA:'The question is how to read Zi Wei and Tan Lang in Travel. See both sides—outer opportunity and charm versus distraction and social drain—then judge how to use the external stage.',
 cnLog:['迁移宫主外在表现、外出缘分与外部舞台，紫微贪狼同守，在外有气场、手腕活、人缘广。','适合外向型工作：市场、公关、商务、演艺、跨地域发展，机会常来自社交场合。','风险在「花」：外面应酬多、诱惑多、选择多，精力分散则正事被拖、人情反成负担。','读法看本命与三方：主星稳、有规划，外部机会能为我所用；煞忌重，则易在外因应酬、桃花或面子生耗。'],
 enLog:['The Travel Palace governs outward expression, away-from-home ties and the external stage; with Zi Wei and Tan Lang guarding it, one has presence, social skill and wide connections outside.','It suits outward work: marketing, public relations, business, performance and cross-regional development, with opportunities often arising in social settings.','The risk is scattering: many social occasions, temptations and choices outside, and scattered energy delays the main matter while social obligations become burdens.','Read the natal self and triple-direction: with a steady, planning major star, outer opportunities serve you; with heavy malefics and Ji, drains easily arise outside through entertaining, romance or face.'],
 cnStep:['先确认迁移宫是紫微贪狼同守','把在外的「机会魅力」与「分心耗神」两面列清','优先发展需要对外交际与跨地域的方向','给外部应酬与选择设主次，避免处处开花','固定一两个主目标，让社交场合围着正事转','结合流年，在外部机会最旺的年份主动出击、同时守住作息'],
 enStep:['First confirm Zi Wei and Tan Lang guard Travel','List both sides clearly: outer opportunity and charm versus distraction and drain','Prioritize directions needing outward networking and cross-regional work','Set priorities among outer social occasions and choices to avoid blooming everywhere','Fix one or two main goals and let social settings revolve around the main matter','With the annual cycle, push in years when outer opportunities peak while keeping regular rest'],
 cnMis:['把在外人缘好直接等同于发展顺、机会都能成','沉迷热闹应酬，精力分散，正事反被拖','只看迁移不看本命，外部舞台再大也可能接不住'],
 enMis:['Equating popularity outside with smooth progress and every opportunity succeeding','Indulging in lively socializing until energy scatters and the main matter is delayed','Reading only Travel without the natal self, so even a large outer stage may be too much to handle'],
 cnClose:'紫微贪狼守迁移，给的是又大又热闹的外部舞台。分清主次、让社交为正事服务，这组星最容易在「走出去」之后，把人缘变成真正的机会。',
 enClose:'Zi Wei and Tan Lang guarding Travel give a large, lively outer stage. Set priorities and let socializing serve the main matter; this pair most readily turns connections into real opportunities after stepping out.'},

{cat:'zhuxing',slug:'ziwei-tianji-jumen-zai-jiaoyougong',focus:'天机巨门在交友宫',focusEn:'Tian Ji and Ju Men in the Friends Palace',
 cnT:'天机巨门在交友宫：朋友多是脑力型，沟通好也要防口舌',
 enT:'Tian Ji and Ju Men in the Friends Palace: Intellectual Friends and Strong Communication, with Guard for Words',
 cnD:'天机巨门同守交友，朋友圈里多爱思考、善表达的人，靠讨论与交流聚人，适合带学习型、创意型团队；但话说多了也易起争辩，要防因言失和。',
 enD:'Tian Ji and Ju Men guarding Friends fills the circle with thoughtful, articulate people, gathering others through discussion and exchange, suiting learning-oriented and creative teams; but too many words easily spark debate, so guard against friction through speech.',
 cnL:'有人的朋友圈特别「能聊」，凑在一起就讨论问题、交换想法，团队里点子不断；这是天机巨门在交友的味道：靠脑力和表达聚人，也最考验说话分寸。',
 enL:'Some people\u2019s circles are especially talkative, gathering to discuss problems and exchange ideas with no shortage of suggestions; this is the tone of Tian Ji and Ju Men in Friends: gathering people through intellect and expression, which most tests verbal judgment.',
 cnA:'这个问题在问：天机巨门落交友怎么读。要把「交流聚人」的好处和「争辩失和」的风险都看到，再判断怎么带这群朋友。',
 enA:'The question is how to read Tian Ji and Ju Men in Friends. See both the benefit of gathering through exchange and the risk of friction through debate, then judge how to lead these friends.',
 cnLog:['交友宫主朋友、平辈与团队，天机主思维、巨门主表达，同守则圈子以「脑力与讨论」为纽带。','适合学习社群、创意团队、教学与研究型组织，朋友中多出主意、会分析的人。','风险在「争」：观点碰撞多、好辩好胜，话不投机易因言语伤和气。','见昌曲、魁钺，交流能得名声与贵人；见煞忌，则易遇好辩成员、口舌是非，带团队要先立沟通规矩。'],
 enLog:['The Friends Palace governs friends, peers and teams; Tian Ji governs thought and Ju Men expression, so together the circle bonds through intellect and discussion.','It suits learning communities, creative teams and teaching or research organizations, with friends who offer ideas and analysis.','The risk is contention: many clashing views and a love of debate, so ill-judged words easily harm goodwill.','With Chang Qu or Kui Yue, exchange brings reputation and patrons; with malefics and Ji, one meets argumentative members and verbal disputes, so leading a team begins with communication rules.'],
 cnStep:['先确认交友宫是天机巨门同守','把「交流聚人」与「争辩失和」两面列清','发展学习型、创意型社群与团队','在群体里先立沟通规矩：对事不对人、不翻旧账','主持讨论时引导建设性表达，避免争胜负','见煞忌时远离好辩之人，关键合作落到书面'],
 enStep:['First confirm Tian Ji and Ju Men guard Friends','List both sides: gathering through exchange versus friction through debate','Develop learning-oriented and creative communities and teams','Set communication rules in the group: address the matter, not the person, and do not revisit old grievances','When hosting discussion, guide constructive expression and avoid winning or losing','With malefics and Ji, keep distance from argumentative people and put key cooperation in writing'],
 cnMis:['把朋友能聊当成不会有矛盾，忽略言语也能伤人','讨论里好胜争对错，结果因言失和','只看聚人不立规矩，圈子越热闹口舌越多'],
 enMis:['Taking talkative friends as conflict-free and ignoring that words can hurt','Competing to be right in discussion and ending in friction through words','Gathering people without rules, so the livelier the circle the more disputes'],
 cnClose:'天机巨门守交友，靠脑力与表达聚人，功课在说话分寸。立好沟通规矩、引导建设性讨论，这组星最容易把一群聪明人带成能出活的团队。',
 enClose:'Tian Ji and Ju Men guarding Friends gather people through intellect and expression, and the lesson is verbal judgment. Set communication rules and guide constructive discussion; this pair most readily turns a group of bright people into a team that delivers.'},

{cat:'zhuxing',slug:'ziwei-wuqu-tanlang-zai-guanlugong',focus:'武曲贪狼在官禄宫',focusEn:'Wu Qu and Tan Lang in the Career Palace',
 cnT:'武曲贪狼在官禄宫：生意头脑加交际手腕，事业贵在收束欲望',
 enT:'Wu Qu and Tan Lang in the Career Palace: Business Acumen Meets Social Skill, and Success Rests on Focusing Appetite',
 cnD:'武曲贪狼同守官禄，事业上既讲务实经营、又善交际张罗，适合市场、商务、贸易与应酬型生意，机会多；但贪多求快易分散，把欲望收束到主业才做得大、守得住。',
 enD:'Wu Qu and Tan Lang guarding Career combines pragmatic management with social skill, suiting marketing, business, trade and entertaining-driven commerce with many opportunities; but overreaching for speed scatters focus, and only concentrating appetite onto the main business makes it large and durable.',
 cnL:'有人在事业上特别会来事，既能算账经营、又能组局谈单，生意机会不断；这是武曲贪狼在官禄的味道：手腕和欲望都强，就怕铺得太宽。',
 enL:'Some are especially adept at making things happen in their career, able both to run the numbers and to host the room and close deals, with constant business opportunities; this is the tone of Wu Qu and Tan Lang in Career: strong skill and appetite, with the risk of spreading too wide.',
 cnA:'这个问题在问：武曲贪狼落官禄怎么读。要把「经营加交际」的优势和「贪多分散」的风险分开，再判断事业怎么聚焦。',
 enA:'The question is how to read Wu Qu and Tan Lang in Career. Separate the advantage of management plus networking from the risk of overreaching and scattering, then judge how to focus the career.',
 cnLog:['武曲主务实经营，贪狼主交际欲望，同守官禄是「生意头脑遇上社交手腕」。','适合商务、贸易、市场、渠道、餐饮娱乐等靠经营与人情的行业，机会多、财路活。','风险在「多」：战线长、应酬重、诱惑多，精力分散则主业不精、守成困难。','见火铃、化禄，欲望化为开拓、事业能做大；见煞忌，则易因贪多、人情或应酬生耗，聚焦与纪律是关键。'],
 enLog:['Wu Qu governs pragmatic management and Tan Lang social appetite; guarding Career together, business acumen meets networking skill.','It suits commerce, trade, marketing, channels, food and entertainment—industries built on management and human warmth, with many opportunities and lively income.','The risk is excess: long battle lines, heavy entertaining and many temptations, so scattered energy leaves the main business unrefined and hard to retain.','With fire stars or Hua Lu, appetite becomes enterprise and the career grows; with malefics and Ji, drains arise through overreaching, social obligations or entertaining, so focus and discipline are key.'],
 cnStep:['先确认官禄宫是武曲贪狼同守','把「经营交际」优势与「贪多分散」风险列清','选定一两个主业，让人情与机会围着它转','给战线、应酬与新机会设取舍标准','见火禄年份大胆扩张，煞忌年份守住现金与口碑','用预算、目标和节奏约束欲望，避免冲动铺摊'],
 enStep:['First confirm Wu Qu and Tan Lang guard Career','List clearly the management-networking advantage and overreaching-scattering risk','Choose one or two main businesses and let connections and opportunities revolve around them','Set criteria for choosing among battle lines, social occasions and new opportunities','Expand boldly in fire-Lu years and guard cash and reputation in malefic-Ji years','Use budgets, goals and pace to constrain appetite and avoid impulsive expansion'],
 cnMis:['把机会多当成都该抓，战线越铺越长','只靠应酬人情做生意，忽略务实经营与口碑','见火禄就盲目扩张，不看煞忌与自身承接力'],
 enMis:['Taking many opportunities as all worth seizing and lengthening the battle lines','Relying only on social obligations for business while ignoring pragmatic management and reputation','Expanding blindly at fire-Lu without checking malefics, Ji and capacity'],
 cnClose:'武曲贪狼守官禄，胜在经营手腕活、机会多，功课在聚焦。把欲望收束到主业、用纪律约束节奏，这组星最容易把生意做大又守住。',
 enClose:'Wu Qu and Tan Lang guarding Career win on lively management skill and many opportunities, and the lesson is focus. Concentrate appetite onto the main business and discipline the pace; this pair most readily grows the business large while keeping it.'},

{cat:'zhuxing',slug:'ziwei-tianji-taiyin-zai-fudegong',focus:'天机太阴在福德宫',focusEn:'Tian Ji and Tai Yin in the Karma Palace',
 cnT:'天机太阴在福德宫：心思细、感受丰，怎么让敏感变成滋养',
 enT:'Tian Ji and Tai Yin in the Karma Palace: A Fine Mind and Rich Feelings, Turning Sensitivity into Nourishment',
 cnD:'天机善思、太阴细腻，两星同守福德，内心世界丰富、审美与感受力强，适合文艺、规划类爱好；但想太多、感受太细也易内耗，给心思一个安放处是关键。',
 enD:'Tian Ji thinks quickly and Tai Yin is refined; together guarding Karma, the inner world is rich with strong aesthetics and sensitivity, suiting literary, artistic and planning interests; but overthinking and fine feelings also easily drain within, so giving the mind a place to settle is key.',
 cnL:'有人外表平静，脑子里却一直在转，感受多、画面多，喜欢安静的爱好，这是天机太阴在福德的味道：精神世界细腻丰富，就怕想深了出不来。',
 enL:'Some look calm outside while the mind keeps turning, rich in feelings and imagery and fond of quiet interests; this is the tone of Tian Ji and Tai Yin in Karma: a delicate, rich inner world, with the risk of thinking deeply and being unable to come back.',
 cnA:'这个问题在问：天机太阴落福德怎么读。要把「细腻丰富」的礼物和「思虑内耗」的风险分开，再判断怎么安顿内心。',
 enA:'The question is how to read Tian Ji and Tai Yin in Karma. Separate the gift of rich refinement from the risk of mental drain, then judge how to settle the inner self.',
 cnLog:['福德宫主精神享受与内心状态，天机主思维、太阴主感受，同守则心思细、审美强、想象丰。','适合文艺、写作、园艺、音乐、规划研究等安静而有审美的爱好，精神满足多来自内心。','风险在「想」：反复琢磨、感受太细、易多愁多虑，夜深人静时更明显。','见科、禄与辅星，敏感能化为才华与安稳；见煞忌，则易失眠、焦虑，必要时以正规就医和专业心理支持为准。'],
 enLog:['The Karma Palace governs spiritual enjoyment and inner state; Tian Ji governs thought and Tai Yin feeling, so together the mind is fine, aesthetics strong and imagination rich.','It suits quiet, aesthetic interests such as literature, writing, gardening, music, planning and research, with inner satisfaction coming largely from within.','The risk is thinking: repeated reflection and overly fine feelings, prone to melancholy and worry, especially in the quiet of night.','With Ke, Lu or assistant stars, sensitivity becomes talent and steadiness; with malefics and Ji, insomnia and anxiety are likely, relying on proper medical and professional psychological support when needed.'],
 cnStep:['先确认福德宫是天机太阴同守','把「细腻丰富」与「思虑内耗」两面列清','培养一两个能安放心思的审美或研究爱好','给反复琢磨设停止动作：写下来、转场景、按时睡','安排适度运动与社交，把注意力从内心引出来','见煞忌或长期失眠焦虑时，尽早寻求专业帮助'],
 enStep:['First confirm Tian Ji and Tai Yin guard Karma','List both sides clearly: rich refinement versus mental drain','Cultivate one or two aesthetic or research interests that settle the mind','Set a stop routine for repeated reflection: write it down, change scene, sleep on time','Arrange moderate exercise and social contact to draw attention outward','With malefics, Ji or prolonged insomnia and anxiety, seek professional help early'],
 cnMis:['把心思细只当成多愁善感，忽略它也是才华与审美','任由脑子空转，不设停止动作，结果内耗失眠','只看福德不看煞忌，把敏感放大成负担'],
 enMis:['Taking a fine mind only as melancholy and ignoring that it is also talent and taste','Letting the mind idle without a stop routine and ending in drain and insomnia','Reading only Karma without malefics and Ji and magnifying sensitivity into a burden'],
 cnClose:'天机太阴守福德，给的是细腻的精神世界，功课在让心思有处安放。把敏感导入审美与研究、给思虑设边界，这份丰富就会成为滋养而不是内耗。',
 enClose:'Tian Ji and Tai Yin guarding Karma give a refined inner world, and the lesson is giving the mind a place to settle. Channel sensitivity into aesthetics and study and set boundaries on thought; then the richness becomes nourishment rather than drain.'}
];
