// 2026-09-30 调研驱动 第5组：跨行转行/官禄环境/夫妻认识/武府夫/机阴夫/紫相子女/廉府田/武府父母 8篇
module.exports=[
{cat:'yingyong',slug:'ziwei-kuahangye-zhuanxing-shiji-zenme-kan',focus:'跨行业转行的时机',focusEn:'timing a cross-industry career change',
 cnT:'紫微斗数看跨行业转行时机：转行不是跳槽，先过这四道判断',
 enT:'Timing a Cross-Industry Change in Zi Wei Dou Shu: Switching Fields Is Not Job Hopping',
 cnD:'转行是换赛道、换能力圈，比换平台风险大。看官禄星性是否可迁移、迁移宫有没有新机会、大限流年是否引动，再判断什么时候走，别把「干腻了」当成「该转了」。',
 enD:'Switching fields means changing track and skill set, a bigger risk than changing platforms. Check whether the Career star traits transfer, whether the Travel Palace offers new openings, and whether the decade and year activate the move; do not take being bored as a sign to switch.',
 cnL:'有人把转行和跳槽混为一谈，结果只是换了家公司干老本行，赛道没动；也有人盲目跨行，新行业的门槛没摸清，两头落空。转行前先把判断顺序走一遍。',
 enL:'Some confuse switching fields with job hopping and only change companies while doing the same work; others cross industries blindly without learning the barriers and miss both sides. Walk through the judgment order before switching.',
 cnA:'这个问题在问：什么时候适合转行、怎么判断。要把「离开的推力」和「新赛道的拉力」分开，再用盘上的官禄、迁移与时间层确认。',
 enA:'The question is when switching fields suits you and how to judge. Separate the push to leave from the pull of the new track, then confirm with the Career, Travel and time layers on the chart.',
 cnLog:['官禄星性看「可迁移度」：通用能力（管理、销售、运营、表达）强的星组转行成本低，过度依赖单一行业资源的星组跨行要慎重。','迁移宫看「新机会」：有没有异地、跨领域、新圈子的入口，吉星会照则外部拉力足。','大限流年看「时机」：大限走变动星组、流年四化引动官禄迁移，才是转行窗口；时间没到，先蓄力。','转行是「换能力圈」：新行业要补的功课、证书、人脉要提前备，盘只提示窗口，不替你补能力。'],
 enLog:['Career star traits show transferability: star groups strong in general abilities such as management, sales, operations and expression switch at lower cost, while those relying on a single industry\u2019s resources should cross carefully.','The Travel Palace shows new opportunities: whether there are entries into distant, cross-field or new-circle work; auspicious meetings mean a strong outer pull.','The decade and year show timing: only when the decade moves through change-oriented star groups and annual transformations activate Career and Travel is it a switching window; before that, build strength.','Switching fields changes the skill set: the lessons, credentials and connections needed in the new industry must be prepared early; the chart only signals the window and does not build ability for you.'],
 cnStep:['先确认自己是「转行」还是「跳槽」，别混','看官禄星性，盘点哪些能力可迁移、哪些要重学','再查迁移宫，找新赛道、新圈子的入口','看大限流年，判断转行窗口到没到','在窗口到来前补功课：证书、作品、人脉与试错','正式动作先小步试水（兼职、项目、副业），确认接得住再全力转'],
 enStep:['First confirm whether you are switching fields or merely changing jobs; do not mix them','Read the Career star traits and take stock of which abilities transfer and which must be relearned','Then check the Travel Palace for entries into the new track and new circles','Read the decade and year to judge whether the switching window has arrived','Before the window, prepare: credentials, work, connections and small experiments','Make the formal move in small steps first—part-time work, projects or side ventures—and switch fully only once you know it holds'],
 cnMis:['把干腻了、人际不顺当成转行信号，忽略新赛道门槛','只看离开压力，不看新行业的拉力与能力匹配','时间没到就裸辞转行，窗口没来、储备没够，两头落空'],
 enMis:['Taking boredom or relationship friction as a sign to switch while ignoring the new field\u2019s barriers','Seeing only the push to leave and not the new industry\u2019s pull and ability match','Quitting to switch before the window arrives and the preparation is done, missing both sides'],
 cnClose:'转行看的是「能力可迁移、外部有拉力、时间到窗口」三件事。先蓄力、再试水、后全力，跨赛道这一步才能走得稳，而不是从一个坑跳进另一个坑。',
 enClose:'Switching fields rests on three things: transferable abilities, an outer pull, and the timing window. Build strength, test the water, then commit; crossing tracks then goes steadily rather than leaping from one pit into another.'},

{cat:'yingyong',slug:'ziwei-guanlugong-kan-gongzuo-huanjing',focus:'官禄宫与工作环境',focusEn:'the Career Palace and work environment',
 cnT:'紫微斗数官禄宫看工作环境：你适合什么团队、节奏与角色',
 enT:'Reading Work Environment Through the Career Palace: Team, Pace and Role That Fit You',
 cnD:'官禄宫不只看职位高低，更看一个人适合什么工作环境：团队大小、节奏快慢、独立性与角色分工。读清这些，比盯着一个头衔找工作更能选得对、待得住。',
 enD:'The Career Palace shows not only rank but the work environment that fits a person: team size, pace, independence and role. Reading these clearly helps you choose better and stay longer than chasing a title.',
 cnL:'有人换了几份工作才发现，问题不在职位，而在环境：大公司嫌闷、小团队嫌乱，节奏不合怎么干都别扭。官禄宫写的就是这层「合不合」。',
 enL:'Some change several jobs before realizing the issue is not the position but the environment: large firms feel stifling, small teams chaotic, and mismatched pace makes everything awkward; the Career Palace writes this layer of fit.',
 cnA:'这个问题在问：官禄宫怎么读工作环境。要把「团队规模、工作节奏、独立性、角色」四件事看清，再判断什么样的平台接得住自己。',
 enA:'The question is how the Career Palace reads work environment. See four things—team size, pace, independence and role—then judge what platform can hold you.',
 cnLog:['官禄宫主工作的整体条件：做什么事、在什么环境、与谁协作、担什么角色。','星曜组合提示环境偏好：刚星组适合节奏快、授权足、能独立拍板的环境；柔星组适合协作稳、支持多、分工清的团队。','对宫与三方补充资源：迁移亮适合对外型岗位，财帛稳适合经营型岗位，辅星足则平台支持多。','头衔是面子、环境是里子：环境合，能力才长得出来；只追头衔而忽略节奏与角色，很快又想走。'],
 enLog:['The Career Palace governs the overall conditions of work: what you do, in what setting, with whom you collaborate and what role you carry.','Star combinations indicate environment preferences: firm star groups suit fast-paced, well-authorized settings where one can decide independently; soft groups suit steady, supportive teams with clear division.','The opposite and trine palaces add resources: bright Travel suits outward-facing roles, steady Wealth suits business roles, and ample assistant stars mean platform support.','A title is the surface and the environment the inside: only when the setting fits can ability grow; chasing rank while ignoring pace and role soon makes one want to leave.'],
 cnStep:['先看官禄宫主星组合，判断基本工作偏好','把「团队规模、节奏、独立性、角色」四项逐一列清','再看迁移、财帛与辅星，确认适合的岗位类型','找工作时把环境问题问在前面，不只谈头衔','用试用期核对节奏与团队是否真的合','选定后顺着环境优势发力，而不是硬改自己去适应'],
 enStep:['First read the Career Palace star combination to judge basic work preferences','List the four items clearly: team size, pace, independence and role','Then check Travel, Wealth and assistant stars to confirm the fitting role type','When job hunting, ask environment questions up front rather than only discussing title','Use the probation period to verify whether pace and team truly fit','Once chosen, push along the environment\u2019s strengths rather than forcing yourself to adapt'],
 cnMis:['只盯职位与薪资，忽略团队节奏与角色','把「大公司一定好」当公式，不看自己星性','环境不合时只怪自己，忽略是选择错位'],
 enMis:['Fixating only on rank and pay while ignoring team pace and role','Taking big companies are always better as a formula without reading your star nature','Blaming yourself when the environment does not fit and ignoring the mismatch in choice'],
 cnClose:'官禄宫真正回答的，是「你在什么环境里最能出活」。把团队、节奏、角色读清，选对平台，你的能力才会在合适的土壤里长出来。',
 enClose:'What the Career Palace truly answers is the setting in which you do your best work. Read team, pace and role clearly and choose the right platform; then your ability grows in fitting soil.'},

{cat:'ganqing',slug:'ziwei-fuqigong-kan-zai-nali-renshi',focus:'夫妻宫与认识场景',focusEn:'the Spouse Palace and meeting contexts',
 cnT:'紫微斗数夫妻宫看在哪里认识另一半：把场景接到宫位上',
 enT:'Reading Where You Meet Your Partner Through the Spouse Palace: Mapping Contexts to Palaces',
 cnD:'夫妻宫的星曜组合，能提示更可能在什么场景里认识另一半：工作场合、熟人介绍、兴趣圈子还是异地旅途。它给的是倾向不是地址，更不保证结婚年份。',
 enD:'The Spouse Palace star combination can hint at the contexts where you more likely meet a partner: work, introductions, interest circles or travel. It gives tendencies, not addresses, and certainly does not guarantee the marriage year.',
 cnL:'「我会在哪里遇到对象」是很常见的问法。盘上不会写一个具体地点，但星曜落宫与三方组合，确实能把认识场景收窄到几类，帮你少在不对的圈子里等。',
 enL:'Where will I meet someone is a very common question. The chart does not name a place, but the stars and triple-direction can narrow the meeting contexts to a few types, helping you stop waiting in the wrong circles.',
 cnA:'这个问题在问：夫妻宫怎么读认识场景。要把星曜象意翻译成现实场合，并明白它只提高概率、不定地点与婚期。',
 enA:'The question is how the Spouse Palace reads meeting contexts. Translate star meanings into real settings, and understand it only raises probability without fixing place or timing.',
 cnLog:['认识场景看夫妻宫主星与三方：偏事业财星的组合，多在工作、业务、合作场合认识。','偏贵人、熟人星（魁钺、左右）的组合，多经长辈、朋友、同事介绍。','偏桃花、才艺星（贪狼、廉贞、昌曲）的组合，多在兴趣、学习、演出、社交场合认识。','偏动星（天马、迁移亮）的组合，多在异地、旅途、外派、网络跨城场景认识；但认识只是开始，关系能否落实仍要看双方相处与流年。'],
 enLog:['Meeting contexts follow the Spouse Palace major stars and triple-direction: combinations leaning toward career and wealth stars often meet at work, business or cooperation settings.','Compositions with patron and familiarity stars such as Kui Yue or Zuo You often meet through elders, friends or colleagues.','Compositions with romance and talent stars such as Tan Lang, Lian Zhen or Chang Qu often meet in interest, study, performance or social settings.','Compositions with movement stars such as Tian Ma or bright Travel often meet in distant, travel, expatriate or online cross-city settings; but meeting is only the start, and whether the bond holds still depends on getting along and the annual cycles.'],
 cnStep:['先看夫妻宫主星与三方组合','按星曜象意判断更可能的两三类认识场景','再看迁移、天马，评估有没有异地与跨城缘分','把精力放到高概率的场合与圈子，而不是干等','认识后回到相处模式判断，不凭一个场景下结论','明白盘只给倾向，不保证地点、婚期与结果'],
 enStep:['First read the Spouse Palace major stars and triple-direction','Judge the two or three more likely meeting contexts from the star meanings','Then check Travel and Tian Ma to assess distant and cross-city ties','Put energy into the higher-probability settings and circles rather than waiting passively','After meeting, return to the interaction pattern to judge rather than concluding from one context','Understand the chart gives only tendencies and does not guarantee place, timing or result'],
 cnMis:['把认识场景读成具体地点或时间','见到动星就断「异地恋、远嫁」，忽略现实选择','以为知道了场景就坐等缘分，不主动进入相应圈子'],
 enMis:['Reading meeting contexts as a fixed place or time','Judging long-distance romance from movement stars while ignoring real choices','Knowing the context yet waiting passively instead of entering the relevant circles'],
 cnClose:'夫妻宫能把「在哪里认识」收窄成几类高概率场景，但不写地址、不保证婚期。顺着场景主动走进相应圈子，缘分才更容易被你遇见。',
 enClose:'The Spouse Palace can narrow where you meet to a few high-probability contexts, but names no address and guarantees no timing. Step into the relevant circles along those contexts and you more readily meet the tie.'},

{cat:'ganqing',slug:'ziwei-wuqu-tianfu-zai-fuqigong',focus:'武曲天府在夫妻宫',focusEn:'Wu Qu and Tian Fu in the Spouse Palace',
 cnT:'武曲天府在夫妻宫：务实顾家的伴侣，感情落在柴米油盐里',
 enT:'Wu Qu and Tian Fu in the Spouse Palace: A Practical, Home-Minded Partner and Love in Daily Life',
 cnD:'武曲是财星、天府是库星，两星同守夫妻，伴侣多务实稳重、会过日子、重视家庭与积累，关系靠责任与经营维系；但表达偏含蓄，别把不浪漫当成不深情。',
 enD:'Wu Qu is the wealth star and Tian Fu the storehouse star; together guarding Spouse, the partner is practical, steady, good at daily life and focused on home and accumulation, with the bond sustained by responsibility; expression is reserved, so do not take lack of romance as lack of love.',
 cnL:'有人的另一半不擅长甜言蜜语，却把家里安排得妥当、钱也规划得稳，这是武曲天府在夫妻的味道：感情不在嘴上，在一饭一蔬和长期的担待里。',
 enL:'Some partners are not good at sweet words yet arrange the home well and plan money steadily; this is the tone of Wu Qu and Tian Fu in Spouse: love lies not in speech but in daily meals and long-term care.',
 cnA:'这个问题在问：武曲天府落夫妻怎么读。要把「务实顾家」的长处和「表达含蓄、少情趣」的风险分开。',
 enA:'The question is how to read Wu Qu and Tian Fu in Spouse. Separate the practical, home-minded strength from the risk of reserved expression and little playfulness.',
 cnLog:['武曲主务实与责任，天府主稳守与包容，同守夫妻是「财星遇上库星」，关系重经营与积累。','伴侣多稳重可靠：会理财、重家庭、讲承诺，给人踏实感。','风险在「淡」：不善表达、偏现实，少了浪漫与情绪共鸣，易被误会为冷淡。','见禄、辅星，家庭经济稳、互相扶持；见煞忌，则易因钱、固执或家庭责任分配生摩擦，关键在主动表达关心。'],
 enLog:['Wu Qu governs pragmatism and responsibility, Tian Fu steady guarding and inclusiveness; guarding Spouse together, the wealth star meets the storehouse star, and the relationship emphasizes management and accumulation.','The partner is often steady and reliable: good with money, focused on home and committed to promises, giving a grounded feeling.','The risk is blandness: not expressive and somewhat practical, with little romance or emotional resonance, easily mistaken for coldness.','With Lu or assistant stars, family finances are steady and the two support each other; with malefics and Ji, friction easily arises over money, stubbornness or division of duties, and the key is actively expressing care.'],
 cnStep:['先确认夫妻宫是武曲天府同守','把「务实顾家」与「含蓄少趣」两面列清','看三方禄星辅星与煞忌，判断关系稳不稳','接受伴侣用行动而非语言表达爱','主动承担情绪表达与生活情趣的部分','谈钱与家庭责任时把分工讲明，避免闷在心里'],
 enStep:['First confirm Wu Qu and Tian Fu guard Spouse together','List both sides clearly: practical and home-minded versus reserved and less playful','Check the triple-direction for Lu, assistant stars, malefics and Ji to judge whether the bond is steady','Accept that the partner expresses love through action rather than words','Take the initiative on emotional expression and adding liveliness','When discussing money and duties, clarify the division rather than keeping it unspoken'],
 cnMis:['把伴侣不浪漫当成不爱、不懂感情','只看到稳定，忽略关系也需要情绪共鸣','谈钱只凭默契，分工不清反而生怨'],
 enMis:['Taking a partner\u2019s lack of romance as not loving or understanding feelings','Seeing only stability and ignoring that the bond also needs emotional resonance','Handling money only by unspoken understanding until unclear division breeds resentment'],
 cnClose:'武曲天府守夫妻，给的是踏实顾家、能一起过日子的伴侣。读懂行动里的深情、补上表达与情趣，这份关系会在柴米油盐里越处越稳。',
 enClose:'Wu Qu and Tian Fu guarding Spouse give a grounded, home-minded partner to build daily life with. Read the deep care in action and add expression and liveliness; then the bond steadies further within everyday life.'},

{cat:'ganqing',slug:'ziwei-tianji-taiyin-zai-fuqigong',focus:'天机太阴在夫妻宫',focusEn:'Tian Ji and Tai Yin in the Spouse Palace',
 cnT:'天机太阴在夫妻宫：细腻聪慧的伴侣，感情最怕想太多',
 enT:'Tian Ji and Tai Yin in the Spouse Palace: A Delicate, Intelligent Partner and the Risk of Overthinking Love',
 cnD:'天机善思、太阴细腻，两星同守夫妻，伴侣多聪明温柔、心思细、有审美，关系重精神交流；但双方都敏感、想得多，容易因小事琢磨、暗自委屈，沟通要直接。',
 enD:'Tian Ji thinks quickly and Tai Yin is refined; together guarding Spouse, the partner is often bright, gentle, fine-minded and aesthetic, with the bond emphasizing spiritual exchange; but both are sensitive and prone to overthinking, easily fretting over small matters and quietly feeling wronged, so communication should be direct.',
 cnL:'有人的另一半聪明体贴、能聊心事，相处有默契；可两个人都心思细，一句话没说对就各自琢磨半天，这是天机太阴在夫妻的味道：感情的功课在「别把感受藏着」。',
 enL:'Some partners are bright, considerate and able to talk through what is on the mind, with quiet rapport; but both being fine-minded, one ill-chosen sentence leads to long private fretting; this is the tone of Tian Ji and Tai Yin in Spouse: the lesson is not hiding feelings.',
 cnA:'这个问题在问：天机太阴落夫妻怎么读。要把「细腻会交流」的长处和「敏感多想、暗自委屈」的风险分开。',
 enA:'The question is how to read Tian Ji and Tai Yin in Spouse. Separate the delicate, communicative strength from the risk of sensitive overthinking and quiet hurt.',
 cnLog:['天机主思维，太阴主感受，同守夫妻是「善思遇上细腻」，伴侣多聪慧温柔、重精神默契。','关系里有话聊、有审美、能彼此理解，情绪价值高。','风险在「想」：心思太细、容易解读过度，矛盾没说清就暗自难过、累积成结。','见科、禄与辅星，细腻能化为体贴与安稳；见煞忌，则易因猜忌、冷战伤感情，关键是有话直说、不隔夜。'],
 enLog:['Tian Ji governs thought and Tai Yin feeling; guarding Spouse together, quick thinking meets refinement, and the partner is often bright, gentle and focused on spiritual rapport.','The relationship has things to talk about, shared aesthetics and mutual understanding, with high emotional value.','The risk is thinking: minds too fine and prone to over-reading, quietly hurting before a conflict is spoken and accumulating knots.','With Ke, Lu or assistant stars, refinement becomes thoughtfulness and steadiness; with malefics and Ji, suspicion and cold wars harm the bond, and the key is speaking directly without letting it sit overnight.'],
 cnStep:['先确认夫妻宫是天机太阴同守','把「细腻交流」与「敏感多想」两面列清','发挥能聊心事、彼此理解的长处','约定有话直说、感受不过夜','起了猜测先开口核对，不暗自琢磨','见煞忌或反复冷战时，主动修复或寻求专业情感咨询'],
 enStep:['First confirm Tian Ji and Tai Yin guard Spouse together','List both sides clearly: delicate communication versus sensitive overthinking','Lean into the strengths of talking things through and understanding each other','Agree to speak directly and not let feelings sit overnight','When suspicion arises, check it by speaking first rather than fretting privately','With malefics, Ji or repeated cold wars, actively repair or seek professional relationship counseling'],
 cnMis:['把默契当成不需要沟通，结果感受被藏成结','一有分歧就暗自揣测，把小事想大','只看到温柔，忽略敏感也需要被安抚和明确表达'],
 enMis:['Taking rapport as needing no communication until feelings are hidden into knots','Fretting privately at every disagreement and magnifying small matters','Seeing only gentleness and ignoring that sensitivity also needs reassurance and clear expression'],
 cnClose:'天机太阴守夫妻，给的是细腻、能交心的关系，功课在别让多想伤了默契。有话直说、感受不过夜，这份温柔才会越长越深。',
 enClose:'Tian Ji and Tai Yin guarding Spouse give a delicate, heart-sharing bond, and the lesson is not letting overthinking harm the rapport. Speak directly and do not let feelings sit overnight; then this gentleness deepens over time.'},

{cat:'liuqin',slug:'ziwei-ziwei-tianxiang-zai-zinvgong',focus:'紫微天相在子女宫',focusEn:'Zi Wei and Tian Xiang in the Children Palace',
 cnT:'紫微天相在子女宫：孩子稳重懂事，亲子关系重规矩与陪伴',
 enT:'Zi Wei and Tian Xiang in the Children Palace: Steady, Sensible Children and Parenting Through Rules and Presence',
 cnD:'紫微是帝星、天相是印星，两星同守子女，子女多稳重懂事、有主见、讲规矩，也可能与学生、晚辈、长期作品有缘；但管教易偏严、期待偏高，分寸与陪伴要平衡。',
 enD:'Zi Wei is the emperor star and Tian Xiang the seal star; together guarding Children, the children are often steady, sensible, self-possessed and rule-aware, and one may also connect with students, juniors or long-term work; but discipline can turn strict and expectations high, so balance judgment with presence.',
 cnL:'有人的孩子从小像个小大人，懂事、要面子、也服规矩，这是紫微天相在子女的味道：亲子之间既要有规矩，也别忘了孩子需要被肯定和陪着长大。',
 enL:'Some children are like small adults from early on, sensible, concerned with face and responsive to rules; this is the tone of Zi Wei and Tian Xiang in Children: parenting needs rules, but also the child\u2019s need for recognition and presence.',
 cnA:'这个问题在问：紫微天相落子女怎么读。要把「稳重懂事」的礼物和「管教偏严、期待过高」的风险分开。',
 enA:'The question is how to read Zi Wei and Tian Xiang in Children. Separate the gift of steady sense from the risk of strict discipline and high expectations.',
 cnLog:['子女宫也管晚辈、学生与创作成果，紫微主主见，天相主规矩，落此则子女多稳重、有担当。','孩子自尊心强、讲道理，适合用明确规则和正面尊重的方式教。','风险在「严」：期待高、爱面子，管得太紧易压抑，亲子之间少了轻松。','见禄、辅星，子女发展稳、得师长善待；见煞忌，则易因管教、代沟起冲突，关键是多陪伴、少比较。'],
 enLog:['The Children Palace also governs juniors, students and creative成果; Zi Wei governs self-possession and Tian Xiang rules, so here children are often steady and responsible.','The child has strong self-respect and responds to reason, suiting teaching through clear rules and positive regard.','The risk is strictness: high expectations and concern with face, and too-tight control easily suppresses, leaving little ease between parent and child.','With Lu or assistant stars, the child develops steadily and is treated well by teachers; with malefics and Ji, conflict easily arises over discipline and the generation gap, and the key is more presence and less comparison.'],
 cnStep:['先确认子女宫是紫微天相同守','把「稳重懂事」与「易管严」两面列清','用明确规则和尊重的方式沟通，少用压制','给孩子合理的肯定与自主空间','把期待落到孩子本身，不与别家比较','多安排轻松陪伴，平衡规矩与亲密'],
 enStep:['First confirm Zi Wei and Tian Xiang guard Children together','List both sides clearly: steady sense versus easy over-discipline','Communicate through clear rules and respect rather than suppression','Give the child reasonable recognition and room for autonomy','Place expectations on the actual child rather than comparing with others','Arrange more relaxed presence to balance rules with closeness'],
 cnMis:['孩子懂事就提高期待、管得更严','只讲规矩少陪伴，亲子关系偏紧','把孩子的好面子当虚荣批评，忽略他需要被尊重'],
 enMis:['Raising expectations and tightening control because the child is sensible','Stressing rules with little presence, leaving the parent-child bond tense','Criticizing the child\u2019s concern with face as vanity and ignoring the need for respect'],
 cnClose:'紫微天相守子女，孩子多稳重可靠，功课在管教分寸。规矩之外多给肯定与陪伴，这份亲子缘才会既立得住、又亲得近。',
 enClose:'Zi Wei and Tian Xiang guarding Children often give steady, reliable children, and the lesson is discipline with judgment. Add recognition and presence beyond rules; then the parent-child tie both stands firm and stays close.'},

{cat:'zhuxing',slug:'ziwei-lianzhen-tianfu-zai-tianzhaigong',focus:'廉贞天府在田宅宫',focusEn:'Lian Zhen and Tian Fu in the Property Palace',
 cnT:'廉贞天府在田宅宫：居家讲秩序，家是一点点经营出来的',
 enT:'Lian Zhen and Tian Fu in the Property Palace: An Orderly Home Built Through Steady Care',
 cnD:'廉贞主规则、天府主库藏，两星同守田宅，家庭重视秩序、积累与安全感，善于管家、顾家，居家环境稳；但家人之间也讲规矩、偏含蓄，温情要主动表达。',
 enD:'Lian Zhen governs rules and Tian Fu storage; together guarding Property, the family values order, accumulation and security, with skill at managing and tending the home and a steady living environment; but family members also favor rules and are reserved, so warmth must be expressed actively.',
 cnL:'有人把家里打理得井井有条，东西有归处、开支有计划，一家人过得安稳，这是廉贞天府在田宅的味道：家的底气，是秩序和积累给的。',
 enL:'Some keep the home in perfect order, with everything in its place and expenses planned, so the family lives steadily; this is the tone of Lian Zhen and Tian Fu in Property: the home\u2019s grounding comes from order and accumulation.',
 cnA:'这个问题在问：廉贞天府落田宅怎么读。要把「善管家、重积累」的长处和「规矩多、温情含蓄」的风险分开。',
 enA:'The question is how to read Lian Zhen and Tian Fu in Property. Separate the strength of good management and accumulation from the risk of many rules and reserved warmth.',
 cnLog:['田宅宫主房产与家庭，廉贞主秩序，天府主库藏，同守则家有规矩、也有积累。','善于管家、理财、布置，居家安稳、家底渐厚。','风险在「拘」：家里讲规矩多、讲情分少，气氛易偏严肃。','见禄、辅星，家产稳、家人互助；见煞忌，则易因家庭责任、产权或固执起摩擦，关键是主动表达关心。'],
 enLog:['The Property Palace governs real estate and family; Lian Zhen governs order and Tian Fu storage, so together the home has both rules and accumulation.','One is good at managing the household, finances and arrangement, with a steady home and gradually thickening foundations.','The risk is restraint: the home stresses rules more than warmth, and the atmosphere easily turns serious.','With Lu or assistant stars, family assets are steady and members help each other; with malefics and Ji, friction easily arises over duties, title or stubbornness, and the key is actively expressing care.'],
 cnStep:['先确认田宅宫是廉贞天府同守','把「善管家重积累」与「规矩多温情少」两面列清','发挥会规划、能守家的长处','在秩序之外主动安排家人相处的温情时刻','涉及家庭开支与责任，把分工讲明','见煞忌或家事摩擦多时，先缓和情绪、再处理问题'],
 enStep:['First confirm Lian Zhen and Tian Fu guard Property together','List both sides clearly: good management and accumulation versus many rules and little warmth','Lean into the strengths of planning and guarding the home','Beyond order, actively arrange warm moments for the family','When family expenses and duties are involved, clarify the division','With malefics, Ji or frequent household friction, soothe emotion first and then handle the matter'],
 cnMis:['只讲家里规矩，忽略情绪与温情','把善管家当成控制家人，气氛偏紧','家产责任只凭默契，分工不清反生怨'],
 enMis:['Stressing household rules only and ignoring emotion and warmth','Turning good management into controlling family members and tightening the atmosphere','Handling assets and duties only by unspoken understanding until unclear division breeds resentment'],
 cnClose:'廉贞天府守田宅，给的是会经营、有积累的家。秩序之上加一份主动的温情，这个家才会既安稳牢靠，又让人打心底想回去。',
 enClose:'Lian Zhen and Tian Fu guarding Property give a well-managed home with accumulation. Add active warmth beyond order; then the home is both steady and secure and a place one truly wants to return to.'},

{cat:'liuqin',slug:'ziwei-wuqu-tianfu-zai-fumugong',focus:'武曲天府在父母宫',focusEn:'Wu Qu and Tian Fu in the Parents Palace',
 cnT:'武曲天府在父母宫：长辈务实可靠，亲子缘分重在互相担待',
 enT:'Wu Qu and Tian Fu in the Parents Palace: Practical, Reliable Elders and a Bond Built on Mutual Care',
 cnD:'武曲是财星、天府是库星，两星同守父母宫，长辈多务实稳重、顾家能扛事，也可能在物质与实际问题上帮得上忙；但表达偏含蓄，亲子间少甜言，多靠行动见真情。',
 enD:'Wu Qu is the wealth star and Tian Fu the storehouse star; together guarding the Parents Palace, the elders are often practical, steady, home-minded and able to carry matters, and may help with material and practical problems; but expression is reserved, with few sweet words and love shown mainly through action.',
 cnL:'有人的父母不大会表达，却用一辈子把家撑起来、把钱和事都安排妥当，这是武曲天府在父母的味道：和长辈的缘分，要在行动和担待里去读。',
 enL:'Some parents are not expressive yet spend a lifetime holding the family up and arranging money and matters well; this is the tone of Wu Qu and Tian Fu in Parents: the bond with elders is read through action and mutual care.',
 cnA:'这个问题在问：武曲天府落父母宫怎么读。要把「长辈可靠、实际能帮」的长处和「表达含蓄、亲子偏客气」的风险分开。',
 enA:'The question is how to read Wu Qu and Tian Fu in Parents. Separate the strength of reliable, practically helpful elders from the risk of reserved expression and overly polite distance.',
 cnLog:['父母宫主长辈、师长与上位者，武曲主务实，天府主稳守，同守则长辈多稳重可靠。','父母责任感强、会持家，在金钱、工作、实际难处上常给实打实的支持。','风险在「疏」：不善表达情感，亲子间客气多、亲昵少，容易报喜不报忧。','见禄、辅星，长辈助力稳、家底实；见煞忌，则易因固执、钱或家庭责任生隔阂，关键是主动沟通、多些陪伴。'],
 enLog:['The Parents Palace governs parents, mentors and superiors; Wu Qu governs pragmatism and Tian Fu steady guarding, so together the elders are often steady and reliable.','The parents have strong responsibility and manage the household well, often giving concrete support with money, work and practical difficulties.','The risk is distance: not good at expressing emotion, with more politeness than closeness and a tendency to report only good news.','With Lu or assistant stars, the elders\u2019 support is steady and the family base solid; with malefics and Ji, distance easily arises over stubbornness, money or duties, and the key is active communication and more presence.'],
 cnStep:['先确认父母宫是武曲天府同守','把「长辈可靠务实」与「表达含蓄客气」两面列清','读懂父母用行动表达的关心','主动承担情感表达，多聊感受而不只是事情','在实际难处上接受长辈的支持，也回报陪伴','见煞忌或有隔阂时，尽早主动沟通、化解心结'],
 enStep:['First confirm Wu Qu and Tian Fu guard Parents together','List both sides clearly: reliable practical elders versus reserved, polite expression','Read the care parents express through action','Take the initiative on emotional expression and talk more about feelings, not only matters','Accept the elders\u2019 support in practical difficulty and repay it with presence','With malefics, Ji or distance, communicate early to untie knots'],
 cnMis:['把父母不表达当成不亲、不爱','只在有事时联系，忽略日常陪伴与情感','谈钱与责任只凭默契，心结攒着不解'],
 enMis:['Taking parents\u2019 reserve as lack of closeness or love','Only contacting when there is a problem and ignoring daily presence and emotion','Handling money and duties only by unspoken understanding and letting knots accumulate'],
 cnClose:'武曲天府守父母，给的是务实可靠、用行动撑家的长辈。读懂行动里的爱、主动表达与陪伴，这份亲子缘会在互相担待里越走越近。',
 enClose:'Wu Qu and Tian Fu guarding Parents give practical, reliable elders who hold the family together through action. Read the love in their deeds and take initiative on expression and presence; then the bond draws closer through mutual care.'}
];
