// 2026-09-30 调研驱动 第4组：福德幸福感/迁移深度/天月疾/天巫田/解神夫/解神田/天寿命/天德福 8篇
module.exports=[
{cat:'gongwei',slug:'ziwei-fudegong-shenme-shi-xingfugan',focus:'福德宫与幸福感',focusEn:'the Karma Palace and happiness',
 cnT:'紫微斗数福德宫看幸福感：满足从哪来、被什么悄悄消耗',
 enT:'Reading Happiness Through the Zi Wei Dou Shu Karma Palace: Where Contentment Comes From and What Quietly Drains It',
 cnD:'福德宫看一个人精神享受与内心满足：兴趣、悠闲、审美是幸福感来源，想不开、求不得、闲不住则是消耗。读懂这一宫，才知道自己靠什么真正开心。',
 enD:'The Karma Palace shows spiritual enjoyment and inner contentment: interests, leisure and aesthetics are sources of happiness, while inability to let go, wanting what is unreachable and being unable to rest drain it. Reading this palace tells you what genuinely makes you happy.',
 cnL:'有人日子过得不错却不开心，有人物质一般却很知足，差别常在福德宫：它不看你拥有多少，看你心里觉不觉得够、享不享受当下。',
 enL:'Some have good lives yet are unhappy, while others with modest means are content; the difference often lies in the Karma Palace: it sees not how much you own but whether your heart feels enough and enjoys the present.',
 cnA:'这个问题在问：福德宫到底怎么看幸福感。要把「满足的来源」和「精神的消耗」两边都看到，再判断自己该往心里添什么、减什么。',
 enA:'The question is how the Karma Palace reads happiness. See both the sources of contentment and the drains on spirit, then judge what to add to and remove from your inner life.',
 cnLog:['福德宫主精神层面：享受、兴趣、心境与潜意识，是一个人独处时的状态。','幸福感多来自「能享受」：有爱好、懂松弛、审美与节奏合自己，哪怕小事也能品出滋味。','消耗多来自「放不下」：求不得、爱比较、脑子闲不住，拥有再多也觉得缺。','福德与财帛相对、与命疾相连：心里知足，赚钱与花钱都从容；心里空，财再多也填不满。'],
 enLog:['The Karma Palace governs the spiritual layer: enjoyment, interests, mood and the subconscious—one\u2019s state when alone.','Happiness largely comes from being able to enjoy: having interests, knowing how to relax, and aesthetics and pace that fit oneself, so even small things can be savored.','Drain largely comes from inability to let go: wanting what is unreachable, loving comparison and a mind that cannot rest, so one feels lacking however much one owns.','Karma opposes Wealth and connects with Life and Health: a contented heart earns and spends calmly, while an empty heart cannot be filled by any amount of wealth.'],
 cnStep:['先找到自己的福德宫及主星、辅煞','列出真正让你放松、享受的两三件事','再列出常让你心里累、放不下的模式','看三方与对宫，判断知足的底气足不足','给消耗项设边界：少比较、定时放下、留独处时间','主动培养爱好与松弛感，把幸福感建立在内心而非外物'],
 enStep:['First find your Karma Palace with its major, assistant and malefic stars','List two or three things that genuinely relax and delight you','Then list the patterns that often make your heart tired and unable to let go','Check the triple-direction and opposite palace to judge whether the basis for contentment is strong','Set boundaries around drains: compare less, let go on schedule and leave time alone','Actively cultivate interests and relaxation, building happiness on the inner self rather than outer things'],
 cnMis:['把幸福感等同于拥有多少，只在物质上找答案','只看到享受，忽略想不开、求不得的消耗','把福德宫读成「命好不好」，忽略它是可以主动经营的'],
 enMis:['Equating happiness with how much one owns and seeking answers only in things','Seeing only enjoyment and ignoring the drains of attachment and wanting','Reading the Karma Palace as whether fate is good and ignoring it can be actively cultivated'],
 cnClose:'福德宫写的是一个人幸福的来处与消耗处。把心安顿好、学会享受当下，你会发现幸福感更多是一种能力，而不是等条件凑齐才有的结果。',
 enClose:'The Karma Palace writes where happiness comes from and what drains it. Settle the heart and learn to enjoy the present; you find happiness is more an ability than a result that waits for all conditions to be met.'},

{cat:'gongwei',slug:'ziwei-qianyigong-shendu-wutai-jiezou',focus:'迁移宫的深度读法',focusEn:'an in-depth reading of the Travel Palace',
 cnT:'紫微斗数迁移宫深度：外出发展的舞台、节奏与外部资源',
 enT:'An In-Depth Reading of the Zi Wei Dou Shu Travel Palace: The Stage, Pace and Resources Away from Home',
 cnD:'迁移宫不只看出差远行，更看一个人在外部世界的舞台、人缘与机会：在外顺不顺、能不能靠外面成事，要合本命与三方一起读，单宫断不准。',
 enD:'The Travel Palace covers not only travel and relocation but one\u2019s stage, connections and opportunities in the outer world: whether things go smoothly outside and one can accomplish through the outer world must be read with the natal self and triple-direction; one palace alone is unreliable.',
 cnL:'有人在家平平、出门却风生水起，有人反过来，一离熟悉环境就不自在，这都是迁移宫在说话：它管的是你和「外部世界」的关系。',
 enL:'Some are ordinary at home but thrive the moment they go out, while others feel uneasy as soon as they leave familiar ground; the Travel Palace speaks in both cases, governing your relationship with the outer world.',
 cnA:'这个问题在问：迁移宫到底能看出什么。要把「外在舞台、外出缘分、外部资源」三层看清，并和本命对读，才知道适不适合走出去。',
 enA:'The question is what the Travel Palace can reveal. See its three layers—outer stage, away-from-home ties and external resources—and read against the natal self to know whether stepping out suits you.',
 cnLog:['迁移宫主外在表现与外出缘分：出差、远行、搬迁、异地与对外社交都归它管。','它是命宫的对宫：本宫写内在，迁移写外在，一个人对外的形象、手腕与机会都在这。','在外能否成事，看三方与煞曜：见魁钺、禄马，外出多贵人、动中生财；见煞忌，则在外多波折、口舌或奔波。','迁移强而本命稳，走出去能成事；迁移亮而本命虚，则容易看着热闹、实际接不住。'],
 enLog:['The Travel Palace governs outward expression and away-from-home ties: business trips, long journeys, relocation, distant places and external socializing.','It is the Life Palace\u2019s opposite: the home palace writes the inner self and Travel the outer, including one\u2019s public image, skill and opportunities.','Whether one accomplishes outside depends on the triple-direction and malefics: with Kui Yue or Lu Ma, patrons and moving-based wealth appear away; with malefics and Ji, outside brings friction, disputes or weary travel.','Strong Travel with a steady natal self lets one accomplish by stepping out; bright Travel with a hollow natal self easily looks lively yet cannot actually be sustained.'],
 cnStep:['先找到迁移宫及其主星、辅煞','把「外在舞台、外出缘分、外部资源」三层列清','再看本命宫，判断内外方向是否一致','看三方魁钺、禄马与煞忌，评估外出顺逆','适合走出去的，主动争取异地、对外与出差机会','本命偏稳的，则把外部资源引回主业，不必勉强离家'],
 enStep:['First find the Travel Palace with its major, assistant and malefic stars','List clearly the three layers: outer stage, away ties and external resources','Then read the Life Palace to judge whether inner and outer directions align','Check the triple-direction for Kui Yue, Lu Ma, malefics and Ji to assess how things go outside','If stepping out suits you, actively seek distant, outward and travel opportunities','If the natal self favors steadiness, draw outer resources back to the main work rather than forcing a move'],
 cnMis:['把迁移宫只当「出远门」，忽略它也管日常对外社交','见迁移有吉星就断「适合外出」，不看本命接不接得住','把在外一时顺利当成必然，忽略煞忌带来的波折'],
 enMis:['Reading Travel only as long journeys and ignoring daily external socializing','Judging that going out suits you from auspicious stars without checking whether the natal self can sustain it','Taking temporary smoothness outside as certain and ignoring friction from malefics and Ji'],
 cnClose:'迁移宫写的是你与外部世界的关系：舞台多大、缘分多活、资源多远。内外合参，你才知道该走出去借势，还是把外面的机会接回自己的地盘。',
 enClose:'The Travel Palace writes your relationship with the outer world: the stage, the lively ties and how distant the resources reach. Read inner and outer together; only then do you know whether to step out for momentum or bring outer opportunities home.'},

{cat:'fuzhu',slug:'ziwei-tianyue-xing-zai-jiegong',focus:'天月在疾厄宫',focusEn:'Tian Yue (Illness Star) in the Health Palace',
 cnT:'紫微斗数月在疾厄宫：体质偏敏感，怎么把小毛病管在前面',
 enT:'Tian Yue in the Health Palace: A Sensitive Constitution and Managing Minor Ailments Early',
 cnD:'天月又名病符，落疾厄宫主体质偏敏感、小毛病、慢性病容易找上门，也主对身体变化感受细。它是倾向不是诊断，规律作息、定期体检、早做管理最关键。',
 enD:'Tian Yue, the Illness Tally, in the Health Palace indicates a sensitive constitution prone to minor and chronic ailments and fine awareness of bodily changes. It is a tendency, not a diagnosis; regular rest, periodic check-ups and early management matter most.',
 cnL:'有人没什么大病，却常年有些小毛病跟着，换季、累了就犯，这往往是天月在疾厄的味道：不是凶险，是提醒你身体需要更细的日常管理。',
 enL:'Some have no major illness yet carry minor ailments year-round that flare with the seasons or fatigue; this is often the tone of Tian Yue in Health: not danger, but a reminder that the body needs finer daily management.',
 cnA:'这个问题在问：天月落疾厄意味着什么。要把「体质敏感、小毛病多」当成生活方式提醒，而非疾病预言，管理得好，影响可以很小。',
 enA:'The question is what Tian Yue in Health means. Take a sensitive constitution with many minor ailments as a lifestyle reminder rather than a disease prediction; with good management the impact can be small.',
 cnLog:['天月主「病气」：偏慢性、小毛病与体质敏感，落疾厄则身体对疲劳、换季、饮食反应更明显。','它不主大病大灾，多是鼻炎、过敏、肠胃、睡眠等反复发作的小问题，提醒早管早养。','盘是倾向不是诊断：同样配置，作息规律、定期体检者少受困扰，透支体力者小毛病不断。','见天寿、天福、解神，恢复与化解有力；见煞忌，则要更早重视，任何持续不适应以正规就医为准。'],
 enLog:['Tian Yue governs illness qi: chronic minor ailments and a sensitive constitution; in Health the body reacts more clearly to fatigue, seasonal change and diet.','It does not bring major disease but recurring small problems such as allergies, digestive and sleep issues, reminding one to manage and nourish early.','The chart is a tendency, not a diagnosis: with the same configuration, those with regular rest and check-ups are less troubled, while those who overdraw their strength face constant minor ailments.','With Tian Shou, Tian Fu or Jie Shen, recovery and resolution are strong; with malefics and Ji, attention must come earlier, and any persistent discomfort relies on proper medical care.'],
 cnStep:['先确认疾厄宫有天月，并看同宫主星','把它读成「体质敏感、需细养」，不先往大病上想','列出自己反复发作的小毛病与诱因','建立规律作息、饮食与运动的日常管理','安排定期体检，小毛病早看早治、不拖成慢性','见煞忌或症状持续时，尽早到正规医院就诊'],
 enStep:['First confirm Tian Yue is in the Health Palace and see the sharing major star','Read it as a sensitive constitution needing fine care rather than assuming major illness','List your recurring minor ailments and their triggers','Build daily management of regular rest, diet and exercise','Schedule periodic check-ups and treat minor problems early rather than letting them become chronic','With malefics, Ji or persistent symptoms, seek proper medical care early'],
 cnMis:['见天月就断「身体差、要生病」，自己吓自己','把小毛病当无关，拖着不管，结果反复发作','把倾向当诊断，自行用药，忽略正规体检与就医'],
 enMis:['Judging poor health and coming illness from Tian Yue and frightening oneself','Dismissing minor ailments until they recur repeatedly','Taking a tendency as a diagnosis and self-medicating while ignoring proper check-ups and care'],
 cnClose:'天月在疾厄，给的是「身体要细养、毛病要早管」的提醒。规律作息、定期体检，这颗星的影响多半能靠日常管理降到很低。',
 enClose:'Tian Yue in Health gives the reminder to care for the body finely and manage ailments early. With regular rest and periodic check-ups, this star\u2019s impact can mostly be kept very low through daily management.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-tianzhaigong',focus:'天巫在田宅宫',focusEn:'Tian Wu in the Property Palace',
 cnT:'紫微斗数天巫在田宅宫：祖荫、继承与家传缘分',
 enT:'Tian Wu in the Property Palace: Ancestral Blessing, Inheritance and Family Legacy',
 cnD:'天巫主继承、直觉与传承，落田宅宫主与家产、祖荫、家传之物或家学有缘，也可能继承房产、接棒家事；但继承带责任，要分辨是资源还是担子。',
 enD:'Tian Wu governs inheritance, intuition and lineage; in the Property Palace it indicates ties to family assets, ancestral blessing, heirlooms or family learning, and possibly inherited property or carrying on family affairs; but inheritance carries responsibility, so distinguish a resource from a burden.',
 cnL:'有人家里有些东西、房子或一门手艺会顺理成章交到自己手上，也对家族的事特别上心，这是天巫在田宅的味道：家庭和「传承」两个字连在一起。',
 enL:'Some naturally receive certain possessions, property or a craft from the family and care especially about family matters; this is the tone of Tian Wu in Property: home tied closely to the word legacy.',
 cnA:'这个问题在问：天巫落田宅意味着什么。要把「继承的资源」和「继承的责任」两边看清，再判断这份祖荫怎么接。',
 enA:'The question is what Tian Wu in Property means. See both the inherited resources and the inherited responsibilities, then judge how to receive the ancestral blessing.',
 cnLog:['田宅宫主房产、家产、居家与家庭氛围，天巫主继承与传承，落此则家产家学多与自己有缘。','正面是祖荫：可能继承房产、物品、手艺或得到家中长辈暗中的安排与资助。','背面是责任：接了家产也接了家事，长辈养老、家庭义务随之而来，未必轻松。','见禄存、化禄与辅星，继承多为实益；见煞忌，则易因家产分配、产权而起纠葛，重大处置以书面与正规法律手续为准。'],
 enLog:['The Property Palace governs real estate, family assets, home and family atmosphere; Tian Wu governs inheritance and lineage, so here family assets and learning are tied to oneself.','The positive side is ancestral blessing: possibly inheriting property, possessions or a craft, or receiving quiet arrangements and support from elders.','The other side is responsibility: receiving assets also means receiving family affairs, elder care and obligations, which may not be light.','With Lu Cun, Hua Lu or assistant stars, inheritance is largely a real benefit; with malefics and Ji, disputes easily arise over division and title, and major handling relies on written, proper legal procedures.'],
 cnStep:['先确认田宅宫有天巫，并看同宫主星','把「继承资源」与「继承责任」两面列清','盘点家中可能传承的房产、物品、手艺或学问','评估自己愿不愿意、能不能接好家事与义务','见禄辅则顺势承接、妥善经营','涉及产权分配时，提前用书面与法律手续理清，避免口头约定'],
 enStep:['First confirm Tian Wu is in the Property Palace and see the sharing major star','List both sides clearly: inherited resources and inherited responsibilities','Take stock of property, possessions, crafts or learning that may be passed on in the family','Assess whether you are willing and able to take on family affairs and obligations','With Lu and assistants, receive it in stride and manage it well','When title or division is involved, clarify early through written and legal procedures, avoiding verbal agreements'],
 cnMis:['只看到继承的好处，忽略随之而来的责任与义务','把祖荫当成必然到手，不做沟通与准备','家产分配只凭口头，最后因产权起纠葛'],
 enMis:['Seeing only the benefit of inheritance and ignoring the responsibilities and obligations that follow','Taking ancestral blessing as guaranteed without communication or preparation','Dividing family assets only verbally and ending in title disputes'],
 cnClose:'天巫在田宅，给的是祖荫与传承的缘分。资源和责任一起看、手续提前理清，这份家传才能真正成为你的后盾，而不是包袱。',
 enClose:'Tian Wu in Property gives the tie of ancestral blessing and legacy. Look at resources and responsibilities together and clarify procedures early; then the family legacy truly becomes your backing rather than a burden.'},

{cat:'fuzhu',slug:'ziwei-jieshen-zai-fuqigong',focus:'解神在夫妻宫',focusEn:'Jie Shen in the Spouse Palace',
 cnT:'紫微斗数解神在夫妻宫：会解开纠缠，也要防关系说散就散',
 enT:'Jie Shen in the Spouse Palace: Untangling Entanglements, with Guard Against Bonds Loosening Too Easily',
 cnD:'解神主化解、解围与「解开」，落夫妻宫主在关系里擅长沟通转圜、能化解矛盾，但也容易把分歧「解开」成分开，遇到问题别急着松手，先谈清楚。',
 enD:'Jie Shen governs resolving, relieving and untying; in the Spouse Palace one is good at communication and reconciliation in a relationship and can dissolve conflicts, but it is also easy to untie a disagreement into a separation; when problems arise, do not rush to release—talk it through first.',
 cnL:'有人在感情里特别会化解僵局，吵架后总能找到台阶；可这颗星也有另一面——谈不拢时容易觉得「算了、解开吧」，关系反而松得快。',
 enL:'Some are especially good at dissolving standoffs in relationships, always finding a way down after a fight; but the star has another side—when talks fail it is easy to feel forget it, let it go, and the bond loosens quickly.',
 cnA:'这个问题在问：解神落夫妻宫意味着什么。要把「化解矛盾」的长处和「轻易分开」的风险分开，再判断怎么经营关系。',
 enA:'The question is what Jie Shen in the Spouse Palace means. Separate the strength of resolving conflict from the risk of easy separation, then judge how to tend the relationship.',
 cnLog:['解神主「解」：逢凶化吉、解围转圜，落夫妻则遇到矛盾善于找台阶、化解僵局。','正面是关系里有弹性：不钻牛角尖、能沟通、愿意给彼此留余地。','风险在「散」：把问题「解开」的习惯用过头，分歧一多就想放手，缘分容易松。','见红鸾天喜、化禄，化解能让关系回暖；见煞忌，则易因一时想不开或第三者等问题说散，重大决定别在情绪头上做。'],
 enLog:['Jie Shen governs resolving: turning misfortune around and relieving pressure; in Spouse, when conflict arises one is good at finding a way down and dissolving deadlock.','The positive side is elasticity in the relationship: not fixating, able to communicate and willing to leave each other room.','The risk is scattering: overusing the habit of untying problems, so with many disagreements one wants to let go and the bond loosens easily.','With Hong Luan, Tian Xi or Hua Lu, resolving warms the relationship again; with malefics and Ji, one may speak of parting over a moment\u2019s deadlock or a third party, so major decisions should not be made at the height of emotion.'],
 cnStep:['先确认夫妻宫有解神，并看同宫主星','把「化解矛盾」与「轻易松手」两面列清','发挥会沟通、能转圜的长处','给自己定规则：分歧先谈，不在情绪头上说分手','区分「需要解开的问题」和「需要珍惜的人」','见煞忌或反复闹矛盾时，先冷静或寻求专业情感咨询'],
 enStep:['First confirm Jie Shen is in the Spouse Palace and see the sharing major star','List both sides clearly: resolving conflict versus releasing easily','Lean into the strengths of communication and reconciliation','Set a rule for yourself: talk through disagreement first and do not say goodbye at the height of emotion','Distinguish problems that need untying from people worth cherishing','With malefics, Ji or repeated conflict, cool down first or seek professional relationship counseling'],
 cnMis:['把会化解当成矛盾不存在，或反过来一有问题就想解开走人','在情绪头上做分手决定，事后又后悔','只看解神不看主星与桃花，忽略关系也要日常经营'],
 enMis:['Taking resolving to mean the conflict does not exist, or conversely wanting to untie and leave at the first problem','Making separation decisions at the height of emotion and regretting later','Reading only Jie Shen without the major star and romance stars, ignoring that relationships need daily care'],
 cnClose:'解神在夫妻，给的是化解与转圜的能力，功课是别把「解开」用成「放手」。先谈、再惜，这份弹性才能成为关系的润滑剂而不是散场的理由。',
 enClose:'Jie Shen in Spouse gives the ability to resolve and reconcile, and the lesson is not turning untying into letting go. Talk first, then cherish; this elasticity can become the lubricant of a relationship rather than the reason for parting.'},

{cat:'fuzhu',slug:'ziwei-jieshen-zai-tianzhaigong',focus:'解神在田宅宫',focusEn:'Jie Shen in the Property Palace',
 cnT:'紫微斗数解神在田宅宫：家里的僵局能化解，也主住处常调整',
 enT:'Jie Shen in the Property Palace: Resolving Household Deadlocks and Frequent Adjustments at Home',
 cnD:'解神落田宅，主善于化解家中矛盾、处理居住难题，也常通过搬家、装修、整理来「解开」居家问题；但住处调整太频也不安稳，重大产权处置要慎重。',
 enD:'Jie Shen in Property means skill at resolving household conflicts and handling living problems, often untying home matters through moving, renovation or reorganizing; but too-frequent adjustments bring instability, and major title decisions need care.',
 cnL:'有人家里有矛盾、房子有问题，他总能想出办法解开，也爱时不时重新布置、换个住处，这是解神在田宅的味道：家的问题靠「化解」和「调整」来答。',
 enL:'Some always find a way to untie household conflicts or property problems and also enjoy periodically rearranging or changing residence; this is the tone of Jie Shen in Property: home\u2019s questions are answered through resolving and adjusting.',
 cnA:'这个问题在问：解神落田宅意味着什么。要把「化解家事」的长处和「住处不稳、说动就动」的风险分开。',
 enA:'The question is what Jie Shen in Property means. Separate the strength of resolving household affairs from the risk of an unstable home that moves on impulse.',
 cnLog:['田宅宫管房产、居家与家庭关系，解神主化解，落此则家中僵局、居住难题多能转圜。','正面是善处理：家庭矛盾会调解、漏水产权等问题能找人解开，居家氛围有修复力。','背面是多动：靠搬家、装修「解开」问题成习惯，住处常变、根基不深。','见禄与辅星，化解后家宅安稳；见煞忌，则易因产权、合同或一时冲动反复折腾，买卖租赁以书面与正规手续为准。'],
 enLog:['The Property Palace manages real estate, home and family relationships; Jie Shen governs resolving, so household deadlocks and living problems can largely be reconciled here.','The positive side is handling well: mediating family conflicts and finding people to untie leaks or title problems, with a restorative home atmosphere.','The other side is frequent movement: untying problems through moving and renovation becomes a habit, so residence changes often and roots stay shallow.','With Lu and assistant stars, the home steadies after resolving; with malefics and Ji, repeated折腾 easily follows from title, contracts or impulse, so buying, selling and leasing rely on written, proper procedures.'],
 cnStep:['先确认田宅宫有解神，并看同宫主星','把「化解家事」与「住处多动」两面列清','发挥善调解、会处理居住难题的长处','搬家、装修前先问是不是非动不可，避免习惯性折腾','家庭矛盾优先当面化解，把修复力用在关系上','涉及买卖租赁与产权，一律走书面正规手续'],
 enStep:['First confirm Jie Shen is in Property and see the sharing major star','List both sides clearly: resolving household affairs versus frequent moves','Lean into the strengths of mediation and handling living problems','Before moving or renovating, ask whether it is truly necessary to avoid habitual折腾','Resolve family conflicts face to face, using the restorative power on relationships','For buying, selling, leasing and title, always use written, proper procedures'],
 cnMis:['把会化解当成家里不会有问题','一不顺心就搬家装修，住处始终不安稳','产权处置凭冲动和口头，忽略正规手续'],
 enMis:['Taking resolving to mean the household will have no problems','Moving or renovating at every frustration so the home never steadies','Handling title on impulse and verbal agreement while ignoring proper procedures'],
 cnClose:'解神在田宅，给的是化解家事、解开居住难题的能力。把这份修复力先用在关系上、少折腾住处，家才会既和睦又安稳。',
 enClose:'Jie Shen in Property gives the ability to resolve household affairs and untie living problems. Use this restorative power first on relationships and折腾 the home less; then the household is both harmonious and steady.'},

{cat:'fuzhu',slug:'ziwei-tianshou-zai-minggong',focus:'天寿在命宫',focusEn:'Tian Shou in the Life Palace',
 cnT:'紫微斗数天寿在命宫：稳重、耐久，像慢工出细活的人',
 enT:'Tian Shou in the Life Palace: Steady, Enduring and Built for Slow, Careful Work',
 cnD:'天寿星主寿元、稳重与耐久，落命宫的人性子稳、有耐心、做事经得起时间，身体根基也偏扎实；但偏慢热保守，节奏上要防拖，后劲通常很足。',
 enD:'The Tian Shou star governs longevity, steadiness and endurance; in the Life Palace one is stable, patient and able to stand the test of time, with solid bodily roots; but one is slow to warm and conservative and must guard against dragging, usually with ample staying power.',
 cnL:'有人做什么都不快，却能一直做下去，别人换了几轮，他还在原地深耕，这是天寿在命的味道：不比爆发力，比谁活得久、走得长。',
 enL:'Some are not fast at anything yet can keep going; while others have changed tracks several times, they are still deepening the same ground; this is the tone of Tian Shou in Life: not competing on bursts but on who lasts.',
 cnA:'这个问题在问：天寿坐命意味着什么。要把「稳重耐久」的长处和「慢热、拖延」的风险分开，再判断怎么用这股后劲。',
 enA:'The question is what Tian Shou in the Life Palace means. Separate the strength of steady endurance from the risk of being slow and prone to delay, then judge how to use the staying power.',
 cnLog:['天寿主「久」：寿元、耐心与耐久，落命宫则性格稳、做事长、身体根基扎实。','适合需要长期积累、慢工细活的领域，一门手艺或事业做越久越有价值。','正面是后劲足：不被一时起伏带走，时间站在自己这边。','背面是偏慢：起步慢、变化慢，若再逢陀罗等星易拖延，节奏上要给自己设期限。'],
 enLog:['Tian Shou governs duration: longevity, patience and endurance; in the Life Palace the temperament is steady, the work long and the bodily roots solid.','It suits fields needing long accumulation and slow, careful work, where a craft or career gains value the longer it is held.','The positive side is ample staying power: not being carried off by momentary swings, with time on one\u2019s side.','The other side is slowness: slow to start and slow to change, and with stars such as Tuo Luo it is prone to delay, so set deadlines for the pace.'],
 cnStep:['先确认命宫有天寿，并看同宫主星','把「稳重耐久」与「慢热拖延」两面列清','选择能靠时间增值的方向，深耕一门','发挥后劲足、经得起起伏的长处','给自己的慢节奏设阶段期限，避免一拖再拖','配合大限，中晚年行运时积累的价值会集中兑现'],
 enStep:['First confirm Tian Shou is in the Life Palace and see the sharing major star','List both sides clearly: steady endurance versus slow delay','Choose directions that gain value with time and deepen one field','Lean into the strengths of staying power and bearing swings','Set staged deadlines for your slow pace to avoid repeated postponement','With the decade, accumulated value兑现集中 in the middle and later cycles'],
 cnMis:['把稳重当没冲劲、自我设限','任由慢节奏拖延，迟迟不开工','只看天寿不看主星，忽略它只加一层耐久底色'],
 enMis:['Taking steadiness as lack of drive and self-limiting','Letting the slow pace delay until work barely starts','Reading only Tian Shou without the major star and ignoring it only adds an enduring tone'],
 cnClose:'天寿坐命，胜在稳、贵在久。选一条值得长期走的路、给慢节奏设期限，时间会成为你最大的盟友，后劲往往比聪明更可靠。',
 enClose:'Tian Shou in the Life Palace wins on steadiness and is valued for endurance. Choose a path worth holding long and set deadlines for the slow pace; time becomes your greatest ally, and staying power is often more reliable than quickness.'},

{cat:'fuzhu',slug:'ziwei-tiande-zai-fudegong',focus:'天德在福德宫',focusEn:'Tian De in the Karma Palace',
 cnT:'紫微斗数天德在福德宫：心善、宽厚，精神上自有逢凶化吉的底气',
 enT:'Tian De in the Karma Palace: A Kind, Generous Heart with an Inner Gift for Turning Misfortune Around',
 cnD:'天德主德行、宽厚与逢凶化吉，落福德宫主心地善良、待人宽厚、精神上有底气，遇到难事常有人帮、也能自我宽慰；但别把好脾气用成无底线，善良要带分寸。',
 enD:'Tian De governs virtue, generosity and turning misfortune around; in the Karma Palace one is kind-hearted and forgiving with inner grounding, and in hardship help often appears or one can console oneself; but do not let good temper become boundless tolerance—kindness should carry judgment.',
 cnL:'有人心宽、爱帮人，遇到难处反而常遇好人，夜里也睡得安稳，这是天德在福德的味道：精神上的福气，多半是自己一点点修来的。',
 enL:'Some are broad-hearted and fond of helping, and in difficulty they often meet good people and sleep peacefully at night; this is the tone of Tian De in Karma: spiritual blessings are largely cultivated by oneself bit by bit.',
 cnA:'这个问题在问：天德落福德意味着什么。要把「宽厚逢凶化吉」的礼物和「无底线退让」的风险分开。',
 enA:'The question is what Tian De in Karma means. Separate the gift of generous turning of misfortune from the risk of boundless yielding.',
 cnLog:['天德主「善」：德行、宽厚、贵人与逢凶化吉，落福德则内心仁厚、待人留余地。','正面是精神有底气：心宽少结、遇事有人帮，也容易在帮人中得到回应。','风险在「软」：把宽厚用过了头，事事退让、不会拒绝，反被人情所累。','见天魁天钺、化禄，善缘能聚成福；见煞忌，则要防好心被利用，关键处把分寸和边界立起来。'],
 enLog:['Tian De governs kindness: virtue, generosity, patrons and turning misfortune around; in Karma the inner self is benevolent and leaves room for others.','The positive side is spiritual grounding: a broad heart with few knots, help in trouble, and easy回应 from those one has helped.','The risk is softness: carrying generosity too far, yielding in everything and unable to refuse, until worn by social obligations.','With Tian Kui Tian Yue or Hua Lu, kind ties gather into blessing; with malefics and Ji, guard good intentions being used and set judgment and boundaries at key points.'],
 cnStep:['先确认福德宫有天德，并看同宫主星','把「宽厚化吉」与「无底线退让」两面列清','发挥心善、会宽慰、能聚善缘的长处','练习有分寸地拒绝，善良也要带边界','把帮人的热情留给值得的人和事','见煞忌或反复被人情所累时，先把自己的底线理清'],
 enStep:['First confirm Tian De is in Karma and see the sharing major star','List both sides clearly: generous turning of misfortune versus boundless yielding','Lean into the strengths of kindness, consolation and gathering good ties','Practice refusing with judgment; kindness also needs boundaries','Reserve the热情 for helping people and matters worth it','With malefics, Ji or repeated wear from obligations, first clarify your own bottom line'],
 cnMis:['把心宽当软弱可欺，或反过来无底线退让','只讲行善不看对象，好心反被利用','把逢凶化吉当成必然，忽略分寸与边界'],
 enMis:['Taking a broad heart as weakness to exploit, or conversely yielding without limits','Being kind regardless of whom it serves until good intentions are used','Taking turning misfortune around as certain and ignoring judgment and boundaries'],
 cnClose:'天德在福德，给的是宽厚与逢凶化吉的精神福气。善良带上分寸、帮人先看对象，这份仁厚才会成为你内心最稳的底气。',
 enClose:'Tian De in Karma gives the spiritual blessing of generosity and turning misfortune around. Let kindness carry judgment and consider whom you help; then this benevolence becomes the steadiest grounding of your inner self.'}
];
