// 2026-09-30 调研驱动 第2组：天同禄落宫/天机权落宫/科忌同宫/化权交友/贪武格/百官格/天官官禄/天巫官禄 8篇
module.exports=[
{cat:'sihua',slug:'ziwei-2026-tiantong-hualu-shiergong',focus:'天同化禄落十二宫',focusEn:'Tian Tong Hua Lu across the twelve palaces',
 cnT:'2026天同化禄落十二宫怎么读：福气、合作与被善待的资源落在哪',
 enT:'How to Read Tian Tong Hua Lu Across the Twelve Palaces in 2026',
 cnD:'2026丙午年天同化禄，主福气、人和与「被善待」的资源。它落在哪个宫，哪个领域就更容易遇到善意与合作，但禄是机会不是坐享，仍要自己接住。',
 enD:'In the 2026 Bing Wu year, Tian Tong carries Hua Lu, governing blessings, harmony and resources that come through goodwill. Whichever palace it lands in finds goodwill and cooperation more readily, but the Lu is an opportunity, not a free ride; you still have to receive it.',
 cnL:'天同本是福星，再化禄，是这一年最温和的一股能量：事情容易有人帮、关系容易谈得拢。关键是先在自己盘上找到它落在哪一宫，再判断哪件事被这股福气照着。',
 enL:'Tian Tong is already the blessing star, and with Hua Lu it is the gentlest energy of the year: help arrives readily and relationships come together. The key is first finding on your chart which palace it lands in, then judging which matter this blessing covers.',
 cnA:'这个问题在问：天同化禄落在不同宫位分别意味着什么。要先理解这颗禄的性质是「福气与人和」，再逐宫读，不能把它读成单纯的发财星。',
 enA:'The question is what Tian Tong Hua Lu means in each palace. First understand that this Lu is blessings and harmony, then read palace by palace; it cannot be read as a simple wealth star.',
 cnLog:['天同化禄的底色是「福」：主享受、照顾、人情与被善待，落宫之事容易在轻松、和气的氛围里推进。','落在命、财、官：命宫主一生人缘好、心情宽；财帛主赚钱靠人和与口碑；官禄主职场得同事与上级善待、适合服务协调岗。','落在夫、兄、父、子：关系宫里主因亲情人情得助，伴侣、手足、长辈、晚辈多是助力，但也要防人情成为依赖。','落在迁、友、田、福、疾：迁友主在外遇贵人、朋友和善；田宅主居家安稳；福德主内心知足；疾厄主病中遇照顾、恢复有援，仍以正规就医为准。'],
 enLog:['The tone of Tian Tong Hua Lu is blessing: it governs enjoyment, care, human warmth and goodwill, so matters in the landing palace advance in a relaxed, congenial atmosphere.','In Life, Wealth or Career: in Life it gives lifelong congeniality and an open mood; in Wealth, earnings come through harmony and reputation; in Career, colleagues and superiors are supportive, suiting service and coordination roles.','In Spouse, Siblings, Parents or Children: in relationship palaces, help comes through family warmth, with partners, siblings, elders and juniors as supports, while guarding against warmth turning into dependence.','In Travel, Friends, Property, Karma or Health: Travel and Friends bring helpful strangers and kind companions; Property gives a stable home; Karma gives contentment; Health gives care during illness and support in recovery, still relying on proper medical treatment.'],
 cnStep:['先在自己盘上找到天同化禄落在哪一宫','按该宫的事务，判断「福气与人和」具体表现为什么','看同宫主星与三方，判断这股禄能不能被稳稳接住','数煞忌，评估人情是否会变成依赖或口头承诺','把禄给的机会主动接过来（开口、行动、落实），而不是坐等','结合流月，在人和最旺的月份推进关键的合作与请求'],
 enStep:['First find on your chart which palace Tian Tong Hua Lu lands in','According to that palace\u2019s affairs, judge how the blessings and harmony concretely appear','Check the sharing major star and triple-direction to see whether the Lu can be received steadily','Count malefics and Ji to assess whether warmth may become dependence or mere promises','Actively take the opportunity the Lu gives—speak up, act and confirm—rather than waiting','With the month stream, advance key cooperation and requests in the months when harmony is strongest'],
 cnMis:['把天同化禄只当「发财」，忽略它主福气与人和','以为有禄就不必行动，结果机会来了没接住','把人情助力当成长期依靠，忽略了关系也要经营与回报'],
 enMis:['Reading Tian Tong Hua Lu only as wealth and ignoring blessings and harmony','Assuming the Lu means no action is needed and failing to receive the opportunity','Treating goodwill as permanent support and ignoring that relationships need care and reciprocity'],
 cnClose:'天同化禄落宫，给的是善意、合作与被照顾的机会。先定位落宫、再主动接住，这一年你在那件事上更容易遇到「愿意帮你的人」。',
 enClose:'Tian Tong Hua Lu in a palace gives goodwill, cooperation and chances to be cared for. Locate the palace and actively receive it; this year you more readily meet people willing to help in that very matter.'},

{cat:'sihua',slug:'ziwei-2026-tianji-huaquan-shiergong',focus:'天机化权落十二宫',focusEn:'Tian Ji Hua Quan across the twelve palaces',
 cnT:'2026天机化权落十二宫怎么读：变动中的主导权与规划力',
 enT:'How to Read Tian Ji Hua Quan Across the Twelve Palaces in 2026',
 cnD:'2026丙午年天机化权，主在变化中拿主意、掌节奏，善规划、能应变。它落在哪宫，哪个领域就更需要你主动决策，但权也带责任，用急了易焦虑。',
 enD:'In the 2026 Bing Wu year, Tian Ji carries Hua Quan, governing taking charge within change, setting the pace, planning and adapting. Whichever palace it lands in calls on you to decide actively there, but the Quan also carries responsibility, and rushing it breeds anxiety.',
 cnL:'天机本是智慧星、善机变，再化权，是这一年最「动脑、要拍板」的能量：变化越多的地方，越需要有人拿主意，那个人可能就是你。',
 enL:'Tian Ji is already the wisdom star, adept at adapting, and with Hua Quan it is the year\u2019s most planning-and-deciding energy: where change is greatest, someone must make the call, and that person may be you.',
 cnA:'这个问题在问：天机化权落在不同宫位怎么读。要先理解这颗权是「变动中的主导」，再逐宫看它让你在哪件事上从配合者变成拿主意的人。',
 enA:'The question is how to read Tian Ji Hua Quan in each palace. First understand that this Quan is leadership within change, then see palace by palace where it turns you from a follower into the decision-maker.',
 cnLog:['天机化权的底色是「变中掌权」：主规划、调整、决策与技术主导，落宫之事更靠脑力与节奏取胜。','落在命、迁、官：命宫主善谋能断、适合出谋划策；迁移主在外能应变、掌握主动；官禄主事业上靠专业与规划担纲，适合技术管理。','落在财、田、福：财帛主赚钱靠点子与灵活调度；田宅主居家与资产常调整、自己说了算；福德主内心主意正，但易思虑过紧。','落在夫、兄、父、子、友、疾：关系宫主你在该关系里爱拿主意，要防强势；交友主带团队靠方案；疾厄主神经过紧、思虑型身体模式，以正规就医为准。'],
 enLog:['The tone of Tian Ji Hua Quan is taking charge within change: it governs planning, adjustment, decisions and technical leadership, so the landing palace is won through intellect and pacing.','In Life, Travel or Career: in Life it gives strategic decisiveness suited to advising; in Travel it gives adaptability and initiative away from home; in Career it means leading through expertise and planning, suiting technical management.','In Wealth, Property or Karma: in Wealth, earnings come through ideas and flexible allocation; in Property, home and assets are often adjusted on your own terms; in Karma the inner resolve is firm but prone to over-tight thinking.','In Spouse, Siblings, Parents, Children, Friends or Health: in relationship palaces you like to decide there and must guard being forceful; in Friends you lead teams through plans; in Health it indicates a wound-tight, thinking-driven body pattern, relying on proper medical care.'],
 cnStep:['先在自己盘上找到天机化权落在哪一宫','按该宫事务，判断「变中主导」具体让你负责什么','看同宫主星与三方，判断这股权有没有专业支撑','数煞忌，评估焦虑、神经过紧与强势主导的风险','把权用在「先规划、再拍板」上，而不是事事插手','结合流月，在需要决策与调整的月份主动担纲'],
 enStep:['First find on your chart which palace Tian Ji Hua Quan lands in','According to that palace\u2019s affairs, judge what leading within change concretely makes you responsible for','Check the sharing major star and triple-direction to see whether the Quan has professional support','Count malefics and Ji to weigh anxiety, wound-tight nerves and forceful leadership','Use the Quan for planning first, then deciding, rather than interfering in everything','With the month stream, take the lead in months that call for decisions and adjustment'],
 cnMis:['把化权只当「升官」，忽略它主变动中的责任与决策','以为有权就能说了算，忽略专业与团队支撑','权急用强，在关系里太强势、在身体上思虑过紧'],
 enMis:['Reading Hua Quan only as promotion and ignoring responsibility and decisions within change','Assuming authority means the final word without professional and team support','Using the Quan forcefully, becoming domineering in relationships and over-tight in the body'],
 cnClose:'天机化权落宫，给的是变化中的主导权与规划力。先定位、再以专业支撑决策，这一年你在那件事上更容易从「跟着走」变成「拿主意的人」。',
 enClose:'Tian Ji Hua Quan in a palace gives leadership and planning within change. Locate it and support decisions with expertise; this year you more readily shift from following to being the one who decides in that matter.'},

{cat:'sihua',slug:'ziwei-keji-tonggong-zenme-du',focus:'化科与化忌同宫',focusEn:'Hua Ke and Hua Ji sharing a palace',
 cnT:'紫微斗数科忌同宫怎么读：因事得名，也容易因名受累',
 enT:'Reading Hua Ke and Hua Ji in One Palace: Recognition That Can Also Weigh You Down',
 cnD:'化科主名声、缓和与被认可，化忌主牵挂、课题与纠缠，两象同宫时，一个人常在某领域因认真而出名，也因这份名声与执着而受累，关键看净效果。',
 enD:'Hua Ke governs reputation, easing and recognition, while Hua Ji governs concern, lessons and entanglement. With both in one palace, a person often becomes known in a field through diligence, yet is also weighed down by that recognition and attachment; the key is the net effect.',
 cnL:'有人在某件事上特别较真，做得好、被人认可，可这份「被看见」也让他更放不下——这就是科忌同宫的典型味道：名和功课缠在一起。',
 enL:'Some are especially earnest in a matter, doing it well and being recognized, yet being seen also makes it harder to let go; this is the classic tone of Hua Ke and Hua Ji together: recognition and lesson intertwined.',
 cnA:'这个问题在问：科与忌落在同一宫到底怎么读。要先分清两象各自的方向，再看它们叠加后是「认真得名」还是「好名声反成枷锁」。',
 enA:'The question is how to read Ke and Ji in one palace. First separate the directions of the two, then see whether their overlap means recognition through diligence or a good name becoming a burden.',
 cnLog:['化科给「名」：主被认可、讲体面、能缓和，落宫之事容易获得正面评价与回旋余地。','化忌给「结」：主牵挂、执着与反复，落宫之事让人放不下、想做好、也容易觉得亏欠。','两象同宫是「名与课」相缠：常表现为在该领域因认真负责而被看见，却也因这份认可与高标准而更累、更难抽身。','读法看净效果：若有禄、辅星来会，名能化为助力；若再见煞，名声易成压力，甚至因名招是非。'],
 enLog:['Hua Ke gives name: recognition, dignity and easing, so matters in the landing palace readily gain positive evaluation and room to maneuver.','Hua Ji gives a knot: concern, attachment and repetition, so matters in the landing palace are hard to release and invite both the wish to do well and a sense of owing.','Together, name and lesson intertwine: one is often seen in that field for being conscientious, yet is more tired and less able to step back because of the recognition and high standards.','Read the net effect: with Lu or assistant stars meeting, the name becomes support; with further malefics, reputation easily becomes pressure or even invites disputes through visibility.'],
 cnStep:['先确认是哪一宫科忌同宫，并看是哪颗星所化','把化科的「名」与化忌的「结」分开理解','看三方有没有禄与辅星，判断名是助力还是压力','数额外煞星，评估因名招是非、因认可而更累的风险','给自己在该领域的高标准设一个「够好」的边界','把被看见的位置转为带人和立规矩，而不是独自硬扛'],
 enStep:['First confirm which palace holds Ke and Ji together and which stars carry them','Separate the name from Hua Ke and the knot from Hua Ji','Check whether the triple-direction has Lu or assistant stars to judge if recognition helps or presses','Count additional malefics to weigh disputes through visibility and fatigue through approval','Set a good-enough boundary around your high standards in that field','Turn the visible position into leading people and setting rules rather than carrying it alone'],
 cnMis:['见到化科就断好、见到化忌就断坏，不会读两象同宫','把被认可当成必须做得更多，结果名声成枷锁','忽略三方净效果，单凭科忌两字下结论'],
 enMis:['Calling Ke good and Ji bad without reading the two together','Taking recognition as a demand to do ever more until reputation becomes a burden','Ignoring the triple-direction net effect and concluding from Ke and Ji alone'],
 cnClose:'科忌同宫，读的是「因认真得名、也因名要继续修这门课」。看清净效果、给努力设边界，那份被看见就能从压力变成真正的口碑。',
 enClose:'Hua Ke and Hua Ji together read as recognition through diligence, and through that recognition the lesson continues. See the net effect and set boundaries on effort, and being seen can turn from pressure into a genuine reputation.'},

{cat:'sihua',slug:'ziwei-huaquan-zai-jiaoyougong',focus:'化权在交友宫',focusEn:'Hua Quan in the Friends Palace',
 cnT:'紫微斗数化权在交友宫：在朋友与团队里争主导，也担组织的责任',
 enT:'Hua Quan in the Friends Palace: Leading Among Friends and Teams While Carrying the Group\u2019s Responsibility',
 cnD:'化权落交友宫（奴仆宫），一个人在朋友圈、团队与下属中容易成为拿主意的人，组织能力强，但也容易把团队的事扛上身，要防权责不清与好胜。',
 enD:'Hua Quan in the Friends Palace makes one the decision-maker among friends, teams and subordinates, with strong organizing ability, but it is also easy to carry the group\u2019s affairs personally; guard against unclear authority and the urge to win.',
 cnL:'有人一进团队就自然成了牵头的，活动他张罗、方向他来定，这是化权在交友宫的味道：在平辈与下属之间有主导欲，也真有那份组织力。',
 enL:'Some naturally become the lead as soon as they join a group, arranging activities and setting direction; this is the tone of Hua Quan in the Friends Palace: the urge to lead among peers and subordinates, backed by real organizing ability.',
 cnA:'这个问题在问：化权落交友宫意味着什么。要把「在群体中主导」和「替群体担责」两层都看到，它既给组织力，也给权责边界的功课。',
 enA:'The question is what Hua Quan in the Friends Palace means. See both layers—leading within the group and taking responsibility for it; it gives organizing power and also a lesson in authority boundaries.',
 cnLog:['交友宫（奴仆宫）主朋友、平辈、团队与下属关系，化权落此，主在群体中爱牵头、能服众、善调配。','正面是组织力强：能带团队、定分工、推动协作，在项目与社群里常是实际的组织者。','背面是责任上肩：容易把大家的事当成自己的事，权责不清时替人扛、替人急，也会因好胜与人争主导。','读法要看三方：见禄与辅星，团队能成你的助力；见煞忌，则易遇强势成员、下属不服或因组织事务生耗。'],
 enLog:['The Friends Palace governs friends, peers, teams and subordinates; with Hua Quan here, one likes to lead within the group, can command respect and is good at coordinating.','The positive side is strong organizing ability: leading teams, setting divisions of work and driving cooperation, often serving as the de facto organizer in projects and communities.','The other side is responsibility settling on the shoulders: it is easy to treat group matters as one\u2019s own, carrying and worrying for others when authority is unclear, and competing to lead out of pride.','Read the triple-direction: with Lu and assistant stars, the team becomes your support; with malefics and Ji, you meet forceful members, resistant subordinates or drains from organizing.'],
 cnStep:['先确认交友宫有化权，并看是哪颗星化权','把「牵头组织」与「替人担责」两种表现分开','看三方禄星辅星，判断团队能不能成为助力','数煞忌，评估强势成员、下属不服与争主导的风险','在团队里先把分工与权责写明，不凭义气硬扛','把主导欲用在建机制、带骨干上，而不是事事亲自拍板'],
 enStep:['First confirm Hua Quan is in the Friends Palace and see which star carries it','Separate leading and organizing from taking responsibility for others','Check the triple-direction for Lu and assistant stars to judge whether the team becomes support','Count malefics and Ji to weigh forceful members, resistant subordinates and contests for leadership','In the team, write out the division of work and authority rather than carrying it on loyalty','Use the urge to lead on building mechanisms and developing key people rather than deciding everything personally'],
 cnMis:['把在团队里牵头当成「大家都该听我的」','凭义气替团队扛事，权责不清反而受累','只看到组织力，忽略煞忌带来的成员摩擦'],
 enMis:['Taking leading the team as everyone should obey me','Carrying group matters out of loyalty and growing tired when authority is unclear','Seeing only organizing power and ignoring member friction from malefics and Ji'],
 cnClose:'化权在交友宫，给的是群体中的主导与组织力，功课是权责边界。牵头而不越界、担责而不独扛，你带的团队才会真正成为助力而不是负担。',
 enClose:'Hua Quan in the Friends Palace gives leadership and organizing power within groups, and the lesson is authority boundaries. Lead without overstepping and take responsibility without carrying it alone; then your team truly becomes support rather than a burden.'},

{cat:'geju',slug:'ziwei-tanwu-tongxing-ge',focus:'贪武同行格',focusEn:'the Tan Wu Tong Xing pattern',
 cnT:'紫微斗数贪武同行格：武曲贪狼同度，为什么偏晚成',
 enT:'The Tan Wu Tong Xing Pattern in Zi Wei Dou Shu: Why Wu Qu and Tan Lang Together Tend to Mature Late',
 cnD:'贪武同行指武曲贪狼同守（多在丑未），财星遇上欲望，早年多应酬折腾、成败起伏，中年后若见火铃或禄星把欲望化为开拓，反而越走越稳，是典型晚成格。',
 enD:'Tan Wu Tong Xing means Wu Qu and Tan Lang guarding together, often in Chou or Wei; the wealth star meets appetite, bringing early socializing, swings and restlessness. After midlife, if fire stars or Lu turn that appetite into enterprise, it steadies—a classic late-blooming pattern.',
 cnL:'武曲贪狼同度的人，年轻时机会多、人情多、想法也多，常常先折腾几年；等把欲望收束成一门生意或专长，后劲才真正出来，所以古人说这组星「不耐早发」。',
 enL:'People with Wu Qu and Tan Lang together have many opportunities, connections and ideas when young and often spend years in restless trying; only when appetite is focused into a business or specialty does the staying power emerge, which is why the tradition says this pair does not favor early success.',
 cnA:'这个问题在问：贪武同行格成格条件是什么、为什么晚成。关键看武曲的务实能否收住贪狼的欲望，以及火铃、禄星有没有把多欲引为开拓。',
 enA:'The question is what forms the Tan Wu Tong Xing pattern and why it matures late. The key is whether Wu Qu\u2019s pragmatism can focus Tan Lang\u2019s appetite, and whether fire stars or Lu channel that appetite into enterprise.',
 cnLog:['武曲给「务实与执行」，贪狼给「欲望与交际」，两星同度是财星遇上欲望，资源手腕不缺。','早年限贪狼主事：应酬多、人情多、尝试多，精力分散，成败起伏也大，早发常守不住。','成格要见「火」或「禄」：火铃把欲望引为开拓、化禄禄存给资源出口，中年后事业才越做越开。','若煞忌重重而无制，则易因贪多、人情或应酬而横破，晚成也无从谈起；辨格局必须回到这些盘面证据。'],
 enLog:['Wu Qu gives pragmatism and execution, Tan Lang gives appetite and sociability; together the wealth star meets desire, with no lack of resources and social skill.','In early limits Tan Lang dominates: much entertaining, social obligation and trying, energy scattered and swings large, so early success often does not hold.','The pattern requires fire or Lu: fire stars channel appetite into enterprise, while Hua Lu or Lu Cun give resources an outlet, so after midlife the career opens further.','If malefics and Ji are heavy without control, boom-and-bust easily follows from overreaching, social obligations or entertaining, and late blooming never arrives; judging the pattern must return to these chart evidences.'],
 cnStep:['先确认命宫（或三方）是武曲贪狼同度','看有没有火铃同会，判断欲望能否化为开拓','再找化禄、禄存，确认资源有没有出口','数煞忌，评估横发横破与应酬损耗','年轻时主动收窄赛道，把多欲变成一门专长或生意','结合大限，中年后行到火禄之限再重点扩张'],
 enStep:['First confirm Wu Qu and Tan Lang guard together in the Life Palace or its triple-direction','See whether fire stars meet them to judge if appetite becomes enterprise','Then look for Hua Lu or Lu Cun to confirm resources have an outlet','Count malefics and Ji to weigh boom-and-bust and entertainment loss','When young, deliberately narrow the track and turn appetite into a specialty or business','With the decade, expand mainly in the middle-age limit carrying fire or Lu'],
 cnMis:['见武曲贪狼就断「会暴富」，忽略火禄条件','年轻时贪多求快、处处铺摊，结果早发守不住','只认格局名，不看煞忌与大限，晚成也可能落空'],
 enMis:['Judging sudden wealth from Wu Qu and Tan Lang while ignoring the fire and Lu conditions','Overreaching for speed and spreading everywhere when young, so early success does not hold','Trusting the pattern name without checking malefics, Ji and the decade, so late blooming may not arrive'],
 cnClose:'贪武同行格，胜在资源手腕活、贵在晚成。先用务实收住欲望、等火禄引动再扩张，这组星的后劲往往比早年的热闹更可靠。',
 enClose:'The Tan Wu Tong Xing pattern wins on resources and social skill and is valued for blooming late. First focus appetite with pragmatism and wait for fire or Lu to trigger expansion; this pair\u2019s staying power is often more reliable than its early bustle.'},

{cat:'geju',slug:'ziwei-ziwei-baiguan-chaogong',focus:'紫微百官朝拱格',focusEn:'the Hundred Officials Court the Ruler pattern',
 cnT:'紫微斗数百官朝拱格：帝星得辅佐，有班底才成得了事',
 enT:'The Hundred Officials Court the Ruler Pattern in Zi Wei Dou Shu: The Emperor Star Needs Its Court',
 cnD:'百官朝拱指紫微坐命而三方四正得左辅右弼、天魁天钺、文昌文曲、禄存天马等吉星会照，主有辅佐、善用人、能成事；若无百官，则降为孤君，格局真假要看会照实数。',
 enD:'Hundred Officials Court the Ruler means Zi Wei in the Life Palace with auspicious stars such as Zuo Fu You Bi, Tian Kui Tian Yue, Wen Chang Wen Qu and Lu Cun Tian Ma meeting its triple-direction, indicating support, skill in using people and real accomplishment. Without them it falls to a lone ruler; the pattern\u2019s truth rests on actual meetings.',
 cnL:'紫微是帝星，再强也要有人辅佐。命宫紫微而吉星环拱的人，常常不是单打独斗型，而是善于搭班子、用人成事；反之满盘只见一颗紫微，就容易高处不胜寒。',
 enL:'Zi Wei is the emperor star and needs support however strong. People with Zi Wei in the Life Palace ringed by auspicious stars are often not solo fighters but skilled at building teams and accomplishing through others; with only a lone Zi Wei on the chart, the top can feel cold.',
 cnA:'这个问题在问：百官朝拱怎么才算成格。关键要逐组数清辅佐星是否真的会照，而不是见到紫微就自称入格，孤君无辅与百官朝拱是两种命。',
 enA:'The question is what forms the Hundred Officials pattern. The key is counting group by group whether supporting stars truly meet, rather than claiming the pattern at the sight of Zi Wei; a lone ruler and a courted ruler are two different charts.',
 cnLog:['紫微主领导、自尊与统筹，落命宫者有主见、想做事，也需要舞台与班底。','百官分四类：左辅右弼主辅佐执行，天魁天钺主贵人提携，文昌文曲主文书名声，禄存天马主资源与流动。','会照越多、越无煞忌冲破，格局越真：主善用人、能聚人，资源与人缘把位置抬得稳。','若吉星稀少而煞忌环伺，则非此格，反成「孤君无辅」，表现为眼高手低、事事亲为而少人帮。'],
 enLog:['Zi Wei governs leadership, self-respect and coordination; in the Life Palace one has views and the wish to accomplish, and also needs a stage and a court.','The officials fall into four groups: Zuo Fu You Bi for support and execution, Tian Kui Tian Yue for patronage, Wen Chang Wen Qu for documents and reputation, and Lu Cun Tian Ma for resources and movement.','The more meetings and the fewer malefics or Ji breaking them, the truer the pattern: skill in using and gathering people, with resources and connections steadying the position.','If auspicious stars are few and malefics with Ji surround it, this is not the pattern but a lone ruler, appearing as high aims with limited means, doing everything personally with little help.'],
 cnStep:['先确认命宫为紫微，并看其亮度','逐组清点左右、魁钺、昌曲、禄马是否会照','数煞忌，评估辅佐是否被冲破','会照足则按「搭班子、用人成事」的方式走','会照稀则放下「等别人来辅」的期待，先练独当一面','结合大限，行到吉星会聚之限再扩大团队与平台'],
 enStep:['First confirm Zi Wei is in the Life Palace and check its brightness','Group by group, count whether Zuo You, Kui Yue, Chang Qu and Lu Ma meet','Count malefics and Ji to assess whether the support is broken','If meetings are ample, proceed by building teams and accomplishing through others','If meetings are sparse, drop the expectation of support and first learn to handle matters alone','With the decade, expand teams and platforms in the limit where auspicious stars gather'],
 cnMis:['见到紫微就自称百官朝拱，不数辅佐实数','把有辅佐当成可以不亲为，忽略自己也要有真本事','忽略煞忌冲破，把孤君误判成贵格'],
 enMis:['Claiming the Hundred Officials pattern at the sight of Zi Wei without counting actual support','Taking support as needing no personal involvement and ignoring one\u2019s own ability','Ignoring malefics and Ji and mistaking a lone ruler for an auspicious pattern'],
 cnClose:'百官朝拱格，读的是「帝星得辅佐、用人能成事」。逐组数清会照、辨明孤君，你才知道这张盘该走搭班子的路，还是先练独当一面。',
 enClose:'The Hundred Officials pattern reads the emperor star gaining support and accomplishing through people. Count the meetings group by group and distinguish the lone ruler; only then do you know whether the chart calls for building a team or first learning to stand alone.'},

{cat:'fuzhu',slug:'ziwei-tianguan-zai-guanlugong',focus:'天官在官禄宫',focusEn:'Tian Guan in the Career Palace',
 cnT:'紫微斗数天官在官禄宫：适合走制度内文职与管理路线',
 enT:'Tian Guan in the Career Palace: Suited to Institutional, Civil and Management Tracks',
 cnD:'天官主官贵、秩序与文职名声，落官禄宫的人做事讲规矩、适合体制内、行政管理或专业幕僚路线，升迁稳但偏渐进，不宜把它读成一步登天。',
 enD:'Tian Guan governs official standing, order and civil reputation; in the Career Palace one works by rules and suits institutional, administrative or professional advisory tracks, with steady but gradual advancement; it should not be read as instant elevation.',
 cnL:'有人一上班就适应制度、讲流程、重名分，在组织里待得住也升得稳，这往往是天官在官禄的味道：贵气不在张扬，在「按规矩把事办成」。',
 enL:'Some adapt to institutions from the start, valuing process and standing, staying and rising steadily within organizations; this is often the tone of Tian Guan in Career: the distinction lies not in show but in getting things done by rules.',
 cnA:'这个问题在问：天官落官禄宫意味着什么。要把「官贵、秩序、文职」三层看清，它给的是制度内的稳，不是创业型的爆发。',
 enA:'The question is what Tian Guan in the Career Palace means. See its three layers—official standing, order and civil work; it gives steadiness within institutions, not entrepreneurial bursts.',
 cnLog:['天官主「贵」：偏官贵、名分与被正式认可，落官禄者适合有明确层级与制度的平台。','天官主「序」：讲规矩、重流程、善协调，适合行政、管理、幕僚、公职等岗位。','升迁多走稳健渐进路线，靠资历、口碑与办事牢靠被提拔，而非靠冒险一搏。','天官力量轻，吉凶仍要看官禄主星与四化；若主星刚、又逢煞，也可能在组织里与人硬碰。'],
 enLog:['Tian Guan governs distinction: official standing, rank and formal recognition; in Career it suits platforms with clear hierarchy and institutions.','Tian Guan governs order: valuing rules and process and coordinating well, suiting administration, management, advisory and public-service roles.','Advancement tends to be steady and gradual, promoted through seniority, reputation and reliability rather than risky gambles.','Tian Guan is a light star; fortune still rests on the Career major star and transformations; with a firm major star and malefics, one may clash within the organization.'],
 cnStep:['先确认官禄宫有天官，并看同宫主星','把天官的象意分「官贵、秩序、文职」理解','优先考虑制度健全、层级清晰的平台','发挥讲规矩、善协调、办事牢靠的长处','升迁按稳扎稳打的节奏规划，不急于求险','结合大限，在组织最重视你的阶段争取名分'],
 enStep:['First confirm Tian Guan is in the Career Palace and see the sharing major star','Read its meaning in layers: official standing, order and civil work','Prioritize platforms with sound institutions and clear hierarchy','Lean into the strengths of following rules, coordinating and delivering reliably','Plan advancement on a steady, solid track rather than rushing into risk','With the decade, seek rank in the stage when the organization values you most'],
 cnMis:['把天官直接等同于大官、一步登天','只看到稳定，忽略主星与四化决定的发展高低','在制度内只讲流程不变通，反而限制发展'],
 enMis:['Equating Tian Guan with high office and instant elevation','Seeing only stability and ignoring that the major star and transformations set the ceiling','Sticking only to process within institutions without flexibility, limiting growth'],
 cnClose:'天官在官禄，给的是制度内的稳贵与文职路线。顺着规矩与协调的长处走、按部就班，这颗星最容易在组织里把位置坐得稳、走得长。',
 enClose:'Tian Guan in the Career Palace gives steady distinction and a civil track within institutions. Follow the strengths of rules and coordination and proceed step by step; this star most easily builds a position that is stable and long within an organization.'},

{cat:'fuzhu',slug:'ziwei-tianwu-zai-guanlugong',focus:'天巫在官禄宫',focusEn:'Tian Wu in the Career Palace',
 cnT:'紫微斗数天巫在官禄宫：升迁、传承与靠专业立身的事业',
 enT:'Tian Wu in the Career Palace: Advancement, Lineage and a Career Built on Expertise',
 cnD:'天巫主直觉、升迁、继承与玄学缘分，落官禄宫的人事业上易得提携、适合接棒传承或研究、咨询、文化类专业路线，升迁常带「被前辈点中」的味道。',
 enD:'Tian Wu governs intuition, advancement, inheritance and an affinity for metaphysics; in the Career Palace one readily gains sponsorship at work and suits succession or research, consulting and cultural professional tracks, with promotions often carrying the tone of being chosen by a senior.',
 cnL:'有人在单位里特别容易被前辈、老师看中，愿意教、愿意带，机会像顺着传承线下来，这就是天巫在官禄的味道：事业和「接棒、得授」连在一起。',
 enL:'Some are especially readily noticed by seniors and mentors at work, who are willing to teach and guide, with opportunities arriving along a line of succession; this is the tone of Tian Wu in Career: work tied to receiving and carrying on a legacy.',
 cnA:'这个问题在问：天巫落官禄宫意味着什么。要把「升迁、传承、直觉」三层看清，它给的是被提携与接棒的机会，不是凭空掉职位。',
 enA:'The question is what Tian Wu in the Career Palace means. See its three layers—advancement, lineage and intuition; it gives chances for sponsorship and succession, not positions appearing from nowhere.',
 cnLog:['天巫主「授」：主被前辈、师长看中与传授，落官禄者事业多有贵人引路。','天巫主「承」：适合接棒、传承类工作，如家族事业、师徒制行业、研究与文化机构。','天巫主「悟」：直觉与灵感强，适合研究、咨询、玄学、文创等靠悟性立身的领域。','机会多带条件：要先肯学、肯接，传承才落得到自己身上；煞忌重时也易因人事变动而错失提携。'],
 enLog:['Tian Wu governs being granted: noticed and taught by seniors and mentors, so in Career one\u2019s work often has guides opening the way.','Tian Wu governs receiving: suiting succession and lineage work, such as family business, master-apprentice trades, research and cultural institutions.','Tian Wu governs insight: strong intuition and inspiration, suiting research, consulting, metaphysics and creative-cultural fields built on grasp.','The opportunities carry conditions: one must first be willing to learn and receive before the legacy lands; with heavy malefics and Ji, sponsorship may be lost through personnel changes.'],
 cnStep:['先确认官禄宫有天巫，并看同宫主星','把天巫的象意分「升迁、传承、直觉」理解','主动找前辈、师长学习，争取被引路与点中','评估自己是否适合接棒、研究或咨询文化类路线','看三方煞忌，判断提携会不会被人事变动打断','机会来时肯接肯担，把传承变成自己的真本事'],
 enStep:['First confirm Tian Wu is in the Career Palace and see the sharing major star','Read its meaning in layers: advancement, lineage and intuition','Actively seek seniors and mentors to learn from and gain guidance','Assess whether you suit succession, research or consulting-cultural tracks','Check the triple-direction for malefics and Ji to judge whether sponsorship may be interrupted by personnel changes','When opportunity comes, receive and take responsibility, turning the legacy into genuine ability'],
 cnMis:['把天巫当成「自动升迁」，忽略要先肯学肯接','只看到玄学缘分，忽略它也主传承与事业提携','不处理煞忌带来的人事变动，错失接棒机会'],
 enMis:['Taking Tian Wu as automatic promotion and ignoring the need to learn and receive first','Seeing only the metaphysical affinity and ignoring lineage and career sponsorship','Not addressing personnel changes from malefics and Ji and missing succession chances'],
 cnClose:'天巫在官禄，给的是被提携、接传承的事业机缘。主动向学、肯接肯担，这颗星最容易让你在前辈的引路下，把一门专业真正承到自己手里。',
 enClose:'Tian Wu in the Career Palace gives chances for sponsorship and carrying on a legacy. Seek learning and be willing to receive and take responsibility; this star most readily lets you truly inherit a profession under a senior\u2019s guidance.'}
];
