// 2026-09-30 调研驱动 第1组：流派取舍/双星查法/无吉扶/概率区间/西方占星/武贪命/机巨命/天厨命 8篇
module.exports=[
{cat:'kanpan',slug:'ziwei-liupai-shuofa-buyi-ruhe-qushe',focus:'不同流派的说法差异',focusEn:'differences between Zi Wei schools',
 cnT:'紫微斗数不同流派说法不一怎么取舍：三合、飞星、中州各管什么',
 enT:'Zi Wei Dou Shu Schools Compared: How to Choose Between San He, Flying Star and Zhongzhou',
 cnD:'同一个盘，三合派重星曜组合、飞星派重宫干四化、中州派重星系结构，结论常常不一样。先分清各自擅长回答什么，再按问题取法，而不是听到两种说法就慌。',
 enD:'Different Zi Wei Dou Shu schools read the same chart differently: San He stresses star combinations, Flying Star stresses palace-stem transformations, and Zhongzhou stresses star-system structure. Learn what each does well, then choose by your question instead of panicking at conflicting answers.',
 cnL:'很多人学了一阵就发现，同一个宫位，不同老师讲法对不上，一个说吉、一个说忌，到底听谁的？其实不是谁对谁错，而是各家看的不是同一层。',
 enL:'After studying for a while, people notice that different teachers read the same palace differently—one calls it auspicious, another points to a transformation. It is rarely a matter of right or wrong; the schools are looking at different layers.',
 cnA:'这个问题在问：流派之间的差别到底差在哪、自己该怎么取舍。关键是先理解三套主流方法各自的切入点，再按你要问的事决定主用哪一家、参考哪一家。',
 enA:'The question is where the schools actually differ and how to choose. The key is understanding the entry points of the three main approaches, then deciding which one leads and which one supplements based on what you are asking.',
 cnLog:['三合派重「星曜组合」：以十四主星的同宫、会照、三方四正与辅煞搭配来读，擅长描述性格、关系形态与一件事的整体样貌。','飞星派重「宫干四化」：以本宫与他宫天干所起的禄权科忌飞动来读，擅长看宫与宫之间的能量往来、因果牵引与具体事件的来去。','中州派重「星系结构」：把星曜按固定星系（如紫微系、天府系）与大限流年的星系配合来读，擅长阶段推演与大局层次。','三家不是互斥而是分层：先用星系/组合定结构底色，再用飞化看事件如何引动，结论会比单守一家更稳。'],
 enLog:['The San He school stresses star combinations: how major stars share palaces, shine across, meet in the triple-direction, and pair with assistant and malefic stars. It excels at describing temperament, relationship patterns and the overall shape of a matter.','The Flying Star school stresses palace-stem transformations: the Lu, Quan, Ke and Ji set flying from each palace stem. It excels at reading energy exchange between palaces, causal pulls and the comings and goings of specific events.','The Zhongzhou school stresses star-system structure: fixed star systems such as the Zi Wei and Tian Fu systems and how the decade and annual cycles align with them. It excels at staged reasoning and big-picture layers.','The schools are not rivals but layers: set the structural tone with systems and combinations, then use flying transformations to see how events trigger, and the conclusion is steadier than clinging to one school.'],
 cnStep:['先弄清自己要问的是「结构题」还是「事件题」','结构题（性格、关系形态、长期格局）主用三合与星系读法','事件题（某件事的来去、谁牵动谁）主用飞星四化读法','大限流年的阶段推演，参考中州的星系配合','两家结论冲突时，先核对所用星曜与四化是否一致，再看是不是层次不同','最后自己把结构层与飞化层叠起来下结论，不盲信单一名词'],
 enStep:['First decide whether you are asking a structure question or an event question','Structure questions—temperament, relationship patterns, long-term patterns—lead with San He and star-system reading','Event questions—how a matter unfolds and who pulls whom—lead with Flying Star transformations','For decade and annual staged reasoning, consult the Zhongzhou star-system alignment','When two answers clash, first check whether the stars and transformations used even match, then whether the layers differ','Finally layer the structure and flying-transformation readings yourself instead of trusting a single label'],
 cnMis:['把流派差异当成「有真有假」，非要选一个唯一正确的','听到不同说法就各取一半，结果哪个方法都没用对','只学一家口诀就否定别家，看不到自己只读到了一层'],
 enMis:['Treating school differences as true versus false and insisting on one correct answer','Splitting the difference between conflicting answers and ending up using neither method correctly','Learning one school\u2019s rhymes and dismissing the others without seeing you only read one layer'],
 cnClose:'流派没有绝对高下，只有问题匹配度：结构找三合、事件找飞星、阶段找中州。把三家当成同一盘的三个镜头，你的判断会立体得多。',
 enClose:'No school is simply superior; the match is to the question—structure from San He, events from Flying Star, stages from Zhongzhou. Treat the three as three lenses on one chart and your judgment gains real depth.'},

{cat:'rumen',slug:'ziwei-shuangxing-tonggong-dushuo-zenme-cha',focus:'双星同宫与独坐的查法',focusEn:'identifying paired and solo major stars',
 cnT:'紫微斗数双星同宫和独坐怎么查：先在自己盘上认出星曜组合',
 enT:'How to Identify Paired and Solo Major Stars in Your Zi Wei Dou Shu Chart',
 cnD:'十四主星在同一宫有时两颗同宫、有时一颗独坐，组合不同读法完全两样。新手先学会在自己盘上认出是哪一种组合，再谈星性，顺序别搞反。',
 enD:'Major stars sometimes share a palace as a pair and sometimes sit solo, and the readings differ greatly. Beginners should first learn to identify which arrangement their chart holds before studying star traits; do not reverse the order.',
 cnL:'很多人一上来就背星性，背了一堆，回到自己盘却连命宫是一颗星还是两颗星都没看清，结果把「独坐」的星按「双星」去读，越读越偏。',
 enL:'Many people start by memorizing star traits, yet back on their own chart they cannot even tell whether the Life Palace holds one star or two—then read a solo star as a pair and drift further off.',
 cnA:'这个问题在问：怎么在盘上确认某宫是双星同宫还是独坐。关键是先定位宫位、再数其中的主星，最后对照该组合的固定搭配表确认。',
 enA:'The question is how to confirm on the chart whether a palace holds a pair or a solo star. The key is locating the palace, counting the major stars in it, then checking against the fixed pairing table.',
 cnLog:['「同宫」指两颗十四主星落在同一格，星性直接混合，如紫微贪狼、武曲七杀、天机太阴等都是固定搭配。','「独坐」指该宫只有一颗主星，星性不受另一颗主星调和，表现更纯粹也更极端，如七杀、破军、太阳在某些宫位独坐。','同宫组合由星曜排布规则固定，不会随意搭配，记住常见二十余组同宫搭配即可对号。','是组合还是独坐，决定了后续怎么读：同宫看两星如何调和，独坐看对宫与三方如何补。'],
 enLog:['A paired palace holds two major stars in one cell whose natures blend directly; fixed pairs include Zi Wei with Tan Lang, Wu Qu with Qi Sha, and Tian Ji with Tai Yin.','A solo palace holds one major star untempered by another, so its expression is purer and more extreme—for example Qi Sha, Po Jun or Tai Yang sitting alone in certain palaces.','Pairings are fixed by the star-placement rules rather than random; learning the roughly twenty common pairs is enough to identify them.','Whether a palace is paired or solo decides how to proceed: pairs are read through how the two stars reconcile, while solo stars are read through how the opposite and trine palaces supplement them.'],
 cnStep:['先在盘上找到要查的宫位','数这一格里有几颗十四主星','两颗即同宫，对照固定搭配表确认是哪一组','一颗即独坐，记下星名再看它所在宫位的亮度','独坐的星接着查对宫与三方，看靠谁补位','同宫的星再查两星谁主谁辅、如何调和，最后才进入解读'],
 enStep:['First locate the palace you want to check','Count how many major stars sit in that cell','Two means a pair; confirm which one against the fixed pairing table','One means solo; note the star and check its brightness in that palace','For a solo star, then check the opposite and trine palaces for support','For a pair, then check which star leads and how they reconcile before interpreting'],
 cnMis:['不数星就背星性，把独坐当同宫读','以为两颗星在一起就一定比一颗好，忽略了组合也可能互相牵制','硬记搭配表却不回自己盘核对，落不了地'],
 enMis:['Memorizing traits without counting stars and reading solo stars as pairs','Assuming two stars are always better than one, ignoring that a pair may restrain each other','Memorizing the pairing table without checking it on the real chart'],
 cnClose:'认组合是读盘的第一道基本功：先数清是双星还是独坐，再谈星性与调和。这一步做扎实，后面所有解读才有正确的起点。',
 enClose:'Identifying the arrangement is the first basic skill: count whether a palace is paired or solo before discussing traits and reconciliation. Do this solidly and every later reading starts from the right place.'},

{cat:'kanpan',slug:'ziwei-minggong-sanfang-wu-jixing-zenme-du',focus:'命宫三方无吉星会照',focusEn:'a Life Palace with no auspicious meetings',
 cnT:'紫微斗数命宫三方无吉星会照怎么读：没有吉扶不等于差命',
 enT:'Reading a Zi Wei Dou Shu Life Palace with No Auspicious Meetings: Unsupported Is Not Doomed',
 cnD:'命宫三方四正见不到左辅右弼、魁钺、昌曲、禄存等吉星，常被叫成「无救」。其实没有吉扶只代表少了顺风，煞星反而可能倒逼出执行力，关键看星性与后天怎么走。',
 enD:'When the Life Palace triple-direction shows no auspicious stars such as Zuo Fu You Bi, Kui Yue, Chang Qu or Lu Cun, it is often called hopeless. In fact, lacking support only means fewer tailwinds, and malefics can instead forge drive; the key is the star nature and how the person lives it.',
 cnL:'有人一看命宫三方没什么吉星就先泄气，觉得自己「命不好」。但盘上没有吉星，不等于没有能力，很多硬拼出来的人恰恰是这种结构。',
 enL:'Some people give up at once when they see no auspicious stars around the Life Palace and decide their fate is poor. But no auspicious stars does not mean no ability; many who built everything through sheer effort have exactly this structure.',
 cnA:'这个问题在问：吉星缺席到底意味着什么。要先分清「无吉扶」和「煞忌重重」是两回事，前者只是少助力，后者才是压力集中，读法不能混。',
 enA:'The question is what the absence of auspicious stars really means. First separate no support from heavy malefics and transformations: the first merely lacks help, while the second concentrates pressure; the readings must not be mixed.',
 cnLog:['吉星主「顺」：贵人、机会、文书、稳定等来得轻松；无吉会照表示这些要靠自己主动争取，而不是没有。','煞星主「执行与压力」：命宫三方有煞而无吉，常表现为凡事靠硬扛，反而练出强行动力和抗压性。','判断这种盘要看主星本性：刚星（七杀、破军、武曲）无吉扶更能吃苦，柔星无吉扶则容易信心不足，需要后天补。','大限流年若行到吉星会照的宫位，顺风一样会来，说明「无吉」是阶段性可补的，不是定死的判决。'],
 enLog:['Auspicious stars govern ease: patrons, opportunities, documents and stability come readily. No auspicious meetings mean these must be actively争取 rather than being absent.','Malefics govern execution and pressure: a Life Palace with malefics but no auspicious stars often means carrying everything alone, which instead builds strong drive and resilience.','Read such charts by the major star\u2019s nature: firm stars such as Qi Sha, Po Jun and Wu Qu bear hardship better without support, while soft stars are prone to self-doubt and need后天 reinforcement.','When the decade or year moves through a palace with auspicious meetings, tailwinds still arrive—showing that no support is a stage that can be supplemented, not a fixed verdict.'],
 cnStep:['先确认命宫三方四正到底有没有吉星，别漏看夹宫','再数其中煞星与四化，分清是「无吉」还是「煞重」','看命宫主星本性，判断无吉扶时是更能扛还是易泄气','查身宫与福德，看内在动力够不够','找大限流年哪一步会行到吉星宫位，定顺风到来的阶段','结论落在「靠自己、等风来」，而不是先贴差命标签'],
 enStep:['First confirm whether the Life Palace triple-direction truly has no auspicious stars, without missing flanking palaces','Then count malefics and transformations to separate no support from heavy malefics','Read the Life Palace major star\u2019s nature to judge whether no support means more endurance or more discouragement','Check the Body Palace and Karma for inner drive','Find which decade or year step moves through an auspicious palace to time the tailwind','Conclude with rely on yourself and wait for the wind rather than labeling the chart poor'],
 cnMis:['把无吉星直接等同于命差、一生无成','看到煞星就判坏，没看到煞星也能逼出执行力','忽略大限流年可以补顺风，把一时结构当成定局'],
 enMis:['Equating no auspicious stars with a poor fate and lifelong failure','Judging malefics as bad without seeing they can forge drive','Ignoring that the decade and year can add tailwinds, treating a temporary structure as fixed'],
 cnClose:'命宫无吉扶，读的是「少顺风、多硬功」，不是「没救」。把注意力放回主星与后天行动，等到行运补照，该来的一样会来。',
 enClose:'A Life Palace without auspicious support reads fewer tailwinds and more hard-won skill, not hopelessness. Return focus to the major star and your actions; when the cycles add meetings, what is due still arrives.'},

{cat:'faq',slug:'ziwei-mingpan-miaoshu-gailv-qujian-bushi-dingju',focus:'命盘与概率区间',focusEn:'the chart as a range of probability',
 cnT:'紫微斗数命盘描述的是概率区间不是定局：怎么理解「倾向」',
 enT:'A Zi Wei Dou Shu Chart Describes Probability Ranges, Not Fixed Outcomes: Understanding Tendency',
 cnD:'命盘给的是星曜组合下的倾向与概率区间，不是逐条兑现的事件清单。同样的结构，有人落在区间上端、有人落在下端，差别就在选择与行动。',
 enD:'A chart gives tendencies and probability ranges under a star combination, not a fixed list of events. With the same structure, some land at the top of the range and others at the bottom; the difference is choice and action.',
 cnL:'很多人把命盘读成「剧本」，以为哪一年一定发生什么，结果没应验就怀疑，应验了又害怕。其实它更像天气预报说的降水概率，不是逐小时脚本。',
 enL:'Many read a chart as a script, certain of what must happen in a given year; when it fails they doubt it, and when it holds they fear it. It is closer to a rain probability in a forecast than an hour-by-hour script.',
 cnA:'这个问题在问：命盘到底「准」在什么层面。要把「排盘可重复」和「解读非定局」分开——同一出生数据排出同一张盘是确定的，但盘上写的是倾向而非事件。',
 enA:'The question is what level a chart is accurate on. Separate reproducible casting from non-fixed interpretation: the same birth data yields the same chart reliably, but the chart writes tendencies, not events.',
 cnLog:['星曜组合描述的是「偏好用什么方式」：遇到事更可能怎么反应、资源更容易从哪来，这是概率较高的方向。','区间有上下：同一组合下，结果因环境、教育、选择与努力而落在不同位置，不是一个固定点。','时间层（大限流年）改变的是区间被引动的时机，让某些年份概率升高，而不是把事件钉死。','理解概率区间后，读盘的用处就从「预测会发生什么」变成「在高概率方向上提前准备、在高风险处提前避让」。'],
 enLog:['Star combinations describe preferred ways: how one is more likely to react and where resources more easily come from—the higher-probability directions.','Ranges have upper and lower ends: under the same combination, outcomes land at different points due to environment, education, choice and effort, not one fixed point.','Time layers—the decade and year—change when the range is activated, raising probability in certain years rather than pinning events down.','Once you understand probability ranges, a reading shifts from predicting what will happen to preparing early along high-probability directions and avoiding high-risk points ahead of time.'],
 cnStep:['先把盘上写的内容改读成「倾向」而非「事件」','对每条倾向，想清楚它的区间上端和下端分别是什么','看大限流年，判断哪些年份区间被抬高或压低','在高概率的好方向上提前投入，在高风险处提前留余地','把结果的落点交给选择与努力，而不是坐等兑现','定期回看，用现实验证区间，校准自己的读法'],
 enStep:['First re-read what the chart writes as tendencies rather than events','For each tendency, clarify what the upper and lower ends of its range look like','Read the decade and year to judge which years raise or lower the range','Invest early in high-probability good directions and leave room at high-risk points','Leave the landing point to choice and effort rather than waiting for fulfillment','Review periodically, testing the range against reality and calibrating your reading'],
 cnMis:['把倾向读成必然事件，应验时间一偏就否定全盘','以为既然是概率就无所谓、不做任何准备','只看区间吉凶，不看自己的选择能把落点推到哪一端'],
 enMis:['Reading tendencies as certain events and dismissing the whole chart when timing shifts','Assuming probability means nothing matters and making no preparation','Seeing only the range\u2019s good or bad without seeing how your choices push the landing point'],
 cnClose:'命盘给的是概率区间，行动决定你落在区间的哪一端。读懂这层「倾向」，读盘就从算命变成了提前布局——这才是它真正的用处。',
 enClose:'A chart gives probability ranges; action decides which end you land on. Understand this layer of tendency and reading shifts from fortune-telling to positioning ahead of time—which is its real use.'},

{cat:'faq',slug:'ziwei-yu-xifang-zhanxing-qubie',focus:'紫微与西方占星的区别',focusEn:'differences between Zi Wei Dou Shu and Western astrology',
 cnT:'紫微斗数和西方占星有什么不同：两套体系看的不是一回事',
 enT:'Zi Wei Dou Shu vs Western Astrology: Two Systems Reading Different Things',
 cnD:'西方占星以行星落入黄道十二宫与相位为主，紫微以虚拟星曜落入十二人事宫与四化为主，一个重行星心理、一个重宫位人事，按问题选择即可。',
 enD:'Western astrology centers on planets in the twelve zodiac signs and their aspects, while Zi Wei Dou Shu centers on symbolic stars in twelve human-affairs palaces and the four transformations—one stresses planetary psychology, the other palace-based affairs; choose by your question.',
 cnL:'有人问紫微和西方星座是不是一回事，能不能一起看。两者都叫占星、都用出生时间，但坐标、星曜和读法其实是两套独立系统。',
 enL:'People ask whether Zi Wei and Western sun signs are the same and whether they can be read together. Both are called astrology and use birth time, but their coordinates, stars and reading methods are two independent systems.',
 cnA:'这个问题在问：两套体系到底差在哪、能不能互证。关键看三处——坐标怎么分、星曜是什么、重点落在心理还是人事。',
 enA:'The question is where the two systems differ and whether they can verify each other. Look at three points: how the coordinates divide, what the stars are, and whether the focus is psychology or human affairs.',
 cnLog:['坐标不同：西方占星按黄道十二星座（白羊等）分宫，紫微按命、财、夫、官等十二人事宫分宫，宫名即事务。','星曜不同：西方用太阳月亮与水金火木土等真实行星及相位，紫微用紫微、天府等一套星曜并以四化（禄权科忌）调节能量。','侧重不同：西方现代占星偏心理结构、成长议题与人格动力，紫微偏具体人事领域（财运、事业、婚姻、六亲）的形态与时机。','两者可以互参但不能硬套：把占星的心理洞察与紫微的人事落宫对照着看，各取所长，结论不必强求一致。'],
 enLog:['Coordinates differ: Western astrology divides by the twelve zodiac signs such as Aries, while Zi Wei divides by twelve human-affairs palaces such as Life, Wealth, Spouse and Career, where the palace name is the matter.','Stars differ: the West uses the sun, moon, Mercury, Venus, Mars, Jupiter, Saturn and other real planets with aspects, while Zi Wei uses stars such as Zi Wei and Tian Fu and tunes energy with the four transformations.','Emphasis differs: modern Western astrology leans toward psychological structure, growth themes and personality dynamics, while Zi Wei leans toward the shape and timing of concrete affairs—wealth, career, marriage and family.','They can inform each other but not be forced to match: contrast the psychological insight of astrology with the affairs-based palaces of Zi Wei, taking the strengths of each without demanding identical conclusions.'],
 cnStep:['先确认自己更关心「心理成长」还是「具体人事」','心理与人格议题主看西方占星的行星宫位与相位','财运、事业、婚姻、六亲等具体领域主看紫微十二宫','对照时只比大方向（如内外向、稳定与变动），不硬套名词','两套结论冲突时，回到现实观察哪一种更贴合自己','把两套当成互补的自我认识工具，而非争谁更准'],
 enStep:['First confirm whether you care more about psychological growth or concrete affairs','Psychological and personality questions lead with Western planets, signs and aspects','Concrete domains such as wealth, career, marriage and family lead with the Zi Wei twelve palaces','When comparing, only contrast broad directions such as introversion and stability versus change, without forcing terms','When the two clash, return to reality and observe which fits you better','Treat the two as complementary self-knowledge tools rather than competing for accuracy'],
 cnMis:['把十二星座直接当成紫微十二宫，按名字对号','以为用了出生时间就该结论一致，忽略体系不同','只信一套就否定另一套，看不到各自擅长的问题'],
 enMis:['Matching the twelve zodiac signs directly to the Zi Wei palaces by name','Expecting identical conclusions because both use birth time, ignoring the different systems','Trusting only one and dismissing the other without seeing its strengths'],
 cnClose:'紫微与西方占星不是同一套东西：一个重人事落宫、一个重心理行星。按问题选工具、互参不硬套，你得到的自我认识会更完整。',
 enClose:'Zi Wei Dou Shu and Western astrology are not the same: one stresses affairs in palaces, the other planets and psychology. Choose by question and cross-reference without forcing, and your self-knowledge becomes more complete.'},

{cat:'zhuxing',slug:'ziwei-wuqu-tanlang-zai-minggong',focus:'武曲贪狼在命宫',focusEn:'Wu Qu and Tan Lang in the Life Palace',
 cnT:'武曲贪狼在命宫：务实与欲望并存，沉住气反而走得远',
 enT:'Wu Qu and Tan Lang in the Life Palace: Pragmatism Meets Appetite, and Patience Goes Further',
 cnD:'武曲是务实财星、贪狼是多才多欲之星，两星同宫的人既想赚钱又爱折腾，机会多、交际广，但若沉不住气容易横冲横破，晚发通常更稳。',
 enD:'Wu Qu is the pragmatic wealth star and Tan Lang the versatile, desirous star. People with both in the Life Palace want both money and stimulation, with many opportunities and wide networks, but impatience brings boom-and-bust; later and steadier success usually holds better.',
 cnL:'武曲贪狼同宫的人，常常脑子活、手腕强，既能谈业务也会攒资源，但心里那股「想要更多」的劲，用好了是开拓，用急了是冒险。',
 enL:'People with Wu Qu and Tan Lang together are often quick-minded and socially skilled, able both to negotiate business and gather resources, but the inner drive for more is pioneering when used well and reckless when rushed.',
 cnA:'这个问题在问：这组双星坐命到底是什么性格、怎么走更顺。关键看务实的武曲能不能管住贪狼的欲望，以及火铃、禄星有没有把欲望化为开拓。',
 enA:'The question is the temperament of this pair in the Life Palace and how to live it more smoothly. The key is whether pragmatic Wu Qu can govern Tan Lang\u2019s appetite, and whether fire stars or Lu transform that appetite into enterprise.',
 cnLog:['武曲主理性、务实与执行，谈钱讲规则、做事重结果，给这组组合压了一块「稳」的底。','贪狼主欲望、多才与交际，兴趣广、人缘活，给这组组合添了一股「动」的劲。','两星相遇，是「财星遇上欲望」：资源手腕都不缺，成败常在心性——沉住气则资源越滚越大，急功近利则易横发横破。','若再见火铃、化禄，欲望被引为开拓，偏生意场与应酬场的成功；若见煞忌，则易因贪多、人情或应酬而生损耗。'],
 enLog:['Wu Qu governs reason, pragmatism and execution, treating money by rules and results by outcomes, laying a steady base for the pair.','Tan Lang governs appetite, versatility and sociability, with broad interests and lively connections, adding a driving energy to the pair.','When the two meet, the wealth star meets desire: resources and social skill are not lacking, and success often rests on self-command—patience rolls resources larger, while quick profit brings boom-and-bust.','With fire stars or Hua Lu, appetite is channeled into enterprise and success in business and social circles; with malefics or Ji, loss easily follows from overreaching, social obligations or entertaining.'],
 cnStep:['先确认命宫是武曲贪狼同宫，并看两星亮度','再看三方有没有火铃、化禄，判断欲望能否化为开拓','数其中煞忌，评估横发横破与应酬损耗的风险','日常用武曲的务实给贪狼的欲望设边界（目标、预算、节奏）','把广交与多欲收束到一两个主赛道，避免处处铺摊','结合大限流年，等阅历与资源够了再发力，晚发更稳'],
 enStep:['First confirm Wu Qu and Tan Lang share the Life Palace and check their brightness','Then see whether the triple-direction has fire stars or Hua Lu to judge if appetite becomes enterprise','Count malefics and Ji to weigh boom-and-bust and entertainment-related loss','In daily life, use Wu Qu\u2019s pragmatism to set boundaries—goals, budget and pace—around Tan Lang\u2019s appetite','Focus wide networks and many desires onto one or two main tracks instead of spreading everywhere','With the decade and year, wait until experience and resources are sufficient before pushing; later success is steadier'],
 cnMis:['把贪狼的多欲当成「会发」，忽略了武曲也要守规则','看到火铃就以为必暴富，没看煞忌与心性','年轻时急着求快，资源没攒够就铺开，结果横发横破'],
 enMis:['Taking Tan Lang\u2019s desires as guaranteed success and ignoring that Wu Qu still needs rules','Assuming fire stars guarantee sudden wealth without checking malefics, Ji and self-command','Rushing when young and expanding before resources are gathered, ending in boom-and-bust'],
 cnClose:'武曲贪狼坐命，胜在资源手腕活、败在贪多求快。让务实的武曲牵住贪狼，沉住气、收窄赛道，这组星的后劲往往比爆发力更值得期待。',
 enClose:'Wu Qu and Tan Lang in the Life Palace win on resources and social skill and lose on overreaching for speed. Let pragmatic Wu Qu guide Tan Lang, stay patient and narrow the track; this pair\u2019s staying power is often more promising than its burst.'},

{cat:'zhuxing',slug:'ziwei-tianji-jumen-zai-minggong',focus:'天机巨门在命宫',focusEn:'Tian Ji and Ju Men in the Life Palace',
 cnT:'天机巨门在命宫：善思善辩的人，怎么把口才用对地方',
 enT:'Tian Ji and Ju Men in the Life Palace: Turning a Quick Mind and Sharp Tongue to the Right Use',
 cnD:'天机善思、巨门善辩，两星同宫的人脑子快、口才好、爱钻研，靠表达与学问立身；但若管不住嘴、想太多，容易多言招尤、内耗伤身。',
 enD:'Tian Ji thinks quickly and Ju Men argues well; people with both in the Life Palace are fast, articulate and studious, building a place through expression and learning. But an unmanaged tongue or overthinking easily brings friction through words and drains within.',
 cnL:'天机巨门同宫的人，常常能说会道、反应快，别人还在想，他已经把逻辑理完了；可这股聪明用在讲理上是本事，用在争胜上就容易惹口舌。',
 enL:'People with Tian Ji and Ju Men together are often articulate and quick, finishing the reasoning while others are still thinking; this intelligence is an ability when used to clarify and a source of disputes when used to win.',
 cnA:'这个问题在问：这组双星坐命是什么性格、怎么扬长避短。关键看善思的天机与善辩的巨门合在一起，是化为表达与研究，还是流于多心与多言。',
 enA:'The question is the temperament of this pair and how to use its strengths. The key is whether thoughtful Tian Ji and argumentative Ju Men together turn into expression and study, or drift into suspicion and excessive talk.',
 cnLog:['天机主思维、规划与机变，脑子活、点子多，给这组组合装了一台高速运转的思考机器。','巨门主口舌、辨析与暗昧，表达力强、爱追根究底，也主是非与开口的两面性。','两星同宫是「思与辩」相遇：逻辑与口才都强，适合教学、传播、研究、谈判等靠表达立身的领域。','若化吉、见魁钺昌曲，口才学问易得赏识；若见煞忌，则易言多必失、想深成结，口舌与内耗都要防。'],
 enLog:['Tian Ji governs thinking, planning and adaptiveness, with a lively mind and many ideas, installing a high-speed thinking engine in the pair.','Ju Men governs speech, analysis and obscurity, expressing strongly and probing to the root, while also carrying the two-sided nature of words and disputes.','Together, thinking meets argument: logic and eloquence are both strong, suiting teaching, communication, research and negotiation—fields built on expression.','With auspicious transformations, Kui Yue or Chang Qu, eloquence and learning win recognition; with malefics or Ji, loose words lose and deep thinking knots, so both disputes and inner drain must be guarded.'],
 cnStep:['先确认命宫是天机巨门同宫，并看两星亮度','再看三方有没有昌曲、魁钺与吉化，判断口才学问能否被赏识','数煞忌，评估多言招尤与思虑内耗的风险','把善思善辩收束到专业领域，成为「有内容的表达」而非空谈','练习开口前先停一下，区分「讲理」与「争胜」','结合大限流年，在需要表达与研究的阶段重点发力'],
 enStep:['First confirm Tian Ji and Ju Men share the Life Palace and check their brightness','Then see whether the triple-direction has Chang Qu, Kui Yue or auspicious transformations to judge if expression and learning are recognized','Count malefics and Ji to weigh friction from words and inner drain from overthinking','Focus the quick mind and tongue into a professional field, making expression substantive rather than empty talk','Practice pausing before speaking, distinguishing clarifying from winning','With the decade and year, push hardest in stages that call for expression and study'],
 cnMis:['把能说会道当成能力本身，忽略了口才要有内容支撑','好辩争胜，图一时嘴上痛快，结果多言招尤','只想不做、反复琢磨，把思考的优势变成内耗'],
 enMis:['Taking eloquence as ability itself and ignoring that words need substance','Arguing to win for the moment\u2019s satisfaction and inviting friction through words','Thinking without acting and turning the strength of thought into inner drain'],
 cnClose:'天机巨门坐命，天赋在思与辩，功课也在思与辩。把口才接到真学问上、把多言收成分寸，这组星最容易靠「会讲、讲得对」立住脚。',
 enClose:'Tian Ji and Ju Men in the Life Palace gift both thought and argument, and the lesson lies there too. Connect eloquence to real learning and temper words with judgment; this pair most easily succeeds by speaking well and speaking rightly.'},

{cat:'fuzhu',slug:'ziwei-tianchu-zai-minggong',focus:'天厨在命宫',focusEn:'Tian Chu in the Life Palace',
 cnT:'紫微斗数天厨在命宫：有口福、懂供养，也主稳定俸禄',
 enT:'Tian Chu in the Life Palace: A Taste for Good Food, Nurturing and a Steady Stipend',
 cnD:'天厨又名食禄星，落命宫的人多有口福、讲究吃、待人厚道，也主一生供养不缺、适合与饮食、俸禄相关的稳定行当，但不直接等于大富。',
 enD:'Tian Chu, the food-and-stipend star, in the Life Palace often gives a good appetite, a care for food and a generous manner, while also indicating steady provision and work related to food or salary—though not great wealth by itself.',
 cnL:'有人命宫带天厨，从小爱吃、会吃，也爱张罗一桌饭招呼人，日子过得有烟火气；这颗星不主大起大落，主的是「吃得好、有人养、有份稳定口粮」。',
 enL:'Some with Tian Chu in the Life Palace love good food from childhood and enjoy gathering people around a table, living a warm, grounded life; this star does not bring big swings but eating well, being provided for and having a steady livelihood.',
 cnA:'这个问题在问：天厨坐命到底意味着什么。要把「口福、供养、俸禄」三层分清，它给的是稳定的食禄，不是暴发的财，读法别夸大。',
 enA:'The question is what Tian Chu in the Life Palace means. Separate its three layers—good food, nurturing and stipend; it gives steady provision rather than sudden wealth, so do not exaggerate the reading.',
 cnLog:['天厨主「食」：口福、饮食、味觉与供养，落命宫者多爱吃、会吃、也常以食物表达关心。','天厨主「禄」：偏稳定的俸禄与供养，适合餐饮、食品、后勤、供养型岗位，收入细水长流。','天厨入命者性情多温和厚道、爱照顾人，人际关系因「会养人」而不差。','天厨力量轻，只给生活加一层安稳与烟火气，富贵吉凶仍要看主星与四化，不能单凭它断。'],
 enLog:['Tian Chu governs food: appetite, cuisine, taste and provision; in the Life Palace people often love good food and express care through it.','Tian Chu governs stipend: a steady salary and provision, suiting catering, food, logistics and nurturing roles with a long, even income.','People with Tian Chu in the Life Palace tend to be warm and generous, liking to care for others, and their relationships benefit from nurturing people.','Tian Chu is a light star that adds steadiness and warmth to life; wealth and fortune still rest on the major stars and transformations, so it cannot decide alone.'],
 cnStep:['先确认命宫有天厨，并看同宫主星是谁','把天厨的象意分「口福、供养、俸禄」三层理解','看三方吉煞，判断稳定口粮之外还有没有更大发展','若从事饮食、食品、后勤、供养类工作，更容易顺星性而为','待人接物可发挥厚道、会照顾人的长处','结论只把天厨当安稳加分项，不夸大成富贵保证'],
 enStep:['First confirm Tian Chu is in the Life Palace and see which major star shares it','Read its meaning in three layers: good food, nurturing and stipend','Check the triple-direction for auspicious and malefic stars to see whether there is larger growth beyond a steady livelihood','Work in catering, food, logistics or nurturing roles aligns more easily with the star','In relationships, lean into the generous, caring strength','Treat Tian Chu only as a steady plus, not exaggerating it into a guarantee of wealth'],
 cnMis:['把有口福直接等同于有钱、大富','只看到吃，忽略天厨也主稳定俸禄与供养','单凭一颗天厨断吉凶，不看同宫主星与四化'],
 enMis:['Equating a good appetite with being rich or wealthy','Seeing only food and ignoring that Tian Chu also governs steady stipend and provision','Judging fortune from Tian Chu alone without the sharing major star and transformations'],
 cnClose:'天厨坐命，给的是烟火气与稳定口粮：会吃、会养人、有份细水长流的供养。把它当生活的安稳底色，大方向仍回到主星与四化去看。',
 enClose:'Tian Chu in the Life Palace gives warmth and a steady livelihood: good food, nurturing others and long-even provision. Treat it as a steady base for life, while the big direction still returns to the major stars and transformations.'}
];
