const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'faq',slug:'ziwei-doushu-zhunma-neng-jueding-mingyun-ma',focus:'准不准',focusEn:'whether Zi Wei is accurate',
 cnT:'紫微斗数准吗：它能描述倾向，不能替你做决定',enT:'Is Zi Wei Dou Shu Accurate? It Describes Tendencies, It Does Not Decide for You',
 cnD:'紫微斗数是一套描述性格倾向、阶段节奏与概率结构的工具，准不准取决于排盘是否正确、解读者水平，以及你把它当参考还是当判决书。',
 enD:'Zi Wei Dou Shu is a tool describing temperament, timing and probability structures. Its accuracy depends on a correct chart, the reader\'s skill, and whether you treat it as reference or verdict.',
 cnL:'紫微更像一张「人生气象图」：它提示哪里容易起风、哪段时间多雨，但怎么走、带不带伞，始终是你自己决定。',
 enL:'Zi Wei is closer to a life weather map: it flags where wind tends to rise and which periods are rainy, but how you walk and whether you carry an umbrella stay your decision.',
 cnA:'问「准不准」的人，往往是想要一个确定答案，可命理真正的价值不在预测得神不神，而在帮你更了解自己的模式、提前做准备。',
 enA:'People who ask whether it is accurate usually want certainty, yet its value is not in sounding prophetic but in helping you know your patterns and prepare ahead.',
 cnLog:['紫微用出生时间排盘，描述的是统计意义上的倾向和结构，不是逐条注定的事件。','「准」的部分多来自性格与阶段节奏的高度概括，「不准」常源于排盘错、时辰错或解读绝对化。','同一张盘，不同选择会走出不同结果，盘给区间、人定落点。','理性用法是把它当决策参考和自我觉察工具，重大医疗、法律、财务决策仍要靠专业判断。'],
 enLog:['Cast from birth time, Zi Wei describes statistical tendencies and structures, not a fixed list of events.','What feels accurate is usually its sharp summary of temperament and timing; what feels off often stems from a wrong chart, wrong hour or absolutist reading.','The same chart branches into different outcomes through different choices—the chart gives a range, the person picks the point.','Use it rationally as a decision aid and self-awareness tool; major medical, legal and financial decisions still need professional judgment.'],
 cnStep:['先确认排盘正确：农历、时辰、命身宫都核对过','把解读拆成「倾向、节奏、风险提示」三类，而不是注定事件','用过往经历验证哪些倾向确实贴合自己','对未来部分只取「需要注意、提前准备」的部分','重大决策以现实信息和专业意见为主，命理为辅','定期复盘：是选择改变了结果，还是结果验证了倾向'],
 enStep:['First confirm a correct chart: lunar date, hour, Life and Body palaces','Split readings into tendencies, timing and risk cues rather than fixed events','Use past experience to test which tendencies truly fit','For the future, take only what to watch and prepare for','Base major decisions on real information and professional opinion, with Zi Wei as support','Periodically review whether choice changed the outcome or the outcome confirmed a tendency'],
 cnMis:['把命理当判决书，准就躺平、不准就否定','排盘没核对就讨论准不准，前提就是错的','用单次巧合验证或否定整套体系'],
 enMis:['Treating it as a verdict—lying flat if it fits, dismissing it if not','Debating accuracy before verifying the chart, on a false premise','Validating or rejecting the whole system from one coincidence'],
 cnClose:'紫微斗数的价值不在「算得准不准」，而在「能不能让你更清醒地选」。把它当参考，它会很好用；把它当命运，它反而会困住你。',
 enClose:'Zi Wei\'s value is not how precisely it predicts but how clearly it helps you choose. As a reference it serves well; as a cage of fate it traps you.'},

{cat:'faq',slug:'ziwei-zao-zishi-wan-zishi-wei-shenme-chayizhangpan',focus:'早晚子时',focusEn:'early versus late Zi hour',
 cnT:'紫微斗数早子时晚子时为什么差一张盘：跨日的那道线',enT:'Why Early and Late Zi Hour Produce Different Zi Wei Charts: The Line Across Midnight',
 cnD:'子时跨23点到1点，23到24点属当日晚子时、0到1点属次日早子时，跨日会换日柱和命宫，排盘时不分早晚子时，整张盘都可能错。',
 enD:'The Zi hour spans 23:00–01:00; 23:00–24:00 belongs to the current day (late Zi) and 00:00–01:00 to the next (early Zi). Crossing midnight changes the day pillar and Life Palace, so ignoring this split can produce a wrong chart.',
 cnL:'23点是一天里最特殊的一小时边界：跨过它，日期换了，命盘也可能整张换，所以夜生人格外要确认早晚子时。',
 enL:'Eleven at night is the day\'s trickiest boundary: crossing it changes the date and potentially the whole chart, so night births need the early/late Zi check.',
 cnA:'很多23点前后出生的人排盘总是对不上，问题不在命理，而在排盘时没处理「子时跨日」这道线，日柱一错全盘皆错。',
 enA:'Many born near 23:00 never get a matching chart—not because the system fails but because the cross-midnight line was mishandled; a wrong day pillar means a wrong whole chart.',
 cnLog:['一个时辰两小时，唯独子时跨午夜，被拆成晚子时（23–24点）和早子时（0–1点）。','晚子时仍属当天日干支，早子时已进入次日，两者日柱不同，排出来的命宫、星曜可能完全不同。','不同流派对夜子时换不换日柱有分歧，稳妥做法是两种都排，用定盘决定。','跨子时出生者必须结合出生证明时间和人生大事做定盘，单靠记忆容易出错。'],
 enLog:['Every block lasts two hours, but Zi alone crosses midnight, split into late Zi (23–24) and early Zi (00–01).','Late Zi keeps the current day\'s stem-branch; early Zi enters the next day. Different day pillars can yield entirely different Life Palace and stars.','Schools differ on whether late Zi changes the day pillar; the safe approach casts both and verifies.','Cross-midnight births must verify with birth records and major life events; memory alone is error-prone.'],
 cnStep:['确认出生时间是否落在23:00–01:00之间','分清23–24点（晚子）还是0–1点（早子）','按流派分别排出「当日」与「次日」两张候选盘','用性格、六亲、过往大事对两张盘做定盘','哪张多点吻合就用哪张，并记录采用规则','以后所有大限流年都在定下来的那张盘上推'],
 enStep:['Confirm whether birth time falls between 23:00 and 01:00','Distinguish late Zi (23–24) from early Zi (00–01)','Cast both the current-day and next-day candidate charts per your school','Verify both against personality, family and major past events','Adopt the chart that fits on more points and record the rule used','Run all later decades and years on the verified chart'],
 cnMis:['23点后出生一律按当天算，不做区分','不知道早晚子时之分，盘对不上就怀疑命理','两张候选盘里只挑自己喜欢的，不用事实定盘'],
 enMis:['Counting all post-23:00 births as the same day with no split','Not knowing the early/late Zi distinction and doubting the system when charts do not fit','Picking the preferred candidate instead of verifying with facts'],
 cnClose:'早晚子时是排盘里最容易被忽略、也最致命的细节。把跨日这道线处理对，后面的解读才有可靠的起点。',
 enClose:'Early versus late Zi is the most overlooked yet fatal detail in casting. Get the cross-midnight line right, and every later reading has a reliable starting point.'},

{cat:'faq',slug:'ziwei-doushu-he-bazi-you-shenme-qubie',focus:'紫微与八字',focusEn:'Zi Wei versus BaZi',
 cnT:'紫微斗数和八字有什么区别：两套模型看的是不同层面',enT:'Zi Wei Dou Shu vs BaZi: Two Models Looking at Different Layers',
 cnD:'八字以天干地支、五行生克看气场与一生结构，紫微以星曜落宫、十二人事宫看具体生活面向与事件，两者可互参但不能混用规则。',
 enD:'BaZi uses stems, branches and five-element generation to read qi and life structure; Zi Wei uses stars in twelve life-affair palaces for concrete life domains and events. They complement but do not share rules.',
 cnL:'八字像看一棵植物的种子与气候，紫微像看它在不同生活场景里怎么生长，一个偏底层结构，一个偏具体人事。',
 enL:'BaZi reads the seed and climate of a plant; Zi Wei reads how it grows across concrete life scenes—one is underlying structure, the other lived affairs.',
 cnA:'很多人学混了，用五行生克去套紫微星曜，或拿紫微宫位去断八字，结果两套都读不准，根源是没分清它们的模型差异。',
 enA:'People blend them—applying five-element cycles to Zi Wei stars or Zi Wei palaces to BaZi—and read neither well, because they never separated the models.',
 cnLog:['八字用四柱干支、五行旺衰与生克制化，重气机、格局与一生层次，时间按节气换月。','紫微用虚拟星曜与十二人事宫，重星曜组合、宫位关系与大限流年的具体事件，时间按农历。','八字擅长看整体结构、五行喜忌与气质倾向；紫微擅长把人生拆成十二个具体领域逐一读。','两者结论方向常能互证，但术语和推演规则各自独立，不应直接照搬，最好一门深入再互参。'],
 enLog:['BaZi uses four pillars, five-element strength and generation-control, emphasizing qi, structure and life level, with months changing by solar terms.','Zi Wei uses symbolic stars and twelve affair palaces, emphasizing star combinations, palace relations and concrete decade/year events, by the lunar calendar.','BaZi excels at overall structure, five-element preferences and temperament; Zi Wei excels at dividing life into twelve concrete domains.','Their directions often corroborate, but terms and rules are independent—master one deeply before cross-referencing rather than copying across.'],
 cnStep:['先明确你要回答的问题：偏整体气质结构还是偏具体人事','看一生层次、五行喜忌、用神，优先用八字','看十二个具体领域、关系和阶段事件，优先用紫微','两套各自独立排盘，不混用历法和规则','结论方向一致则互相加强，不一致时回看排盘与解读前提','把一套学扎实，再用另一套做交叉验证'],
 enStep:['Clarify the question: overall structure or concrete affairs','For life level, five-element preferences and useful god, favor BaZi','For twelve concrete domains, relationships and stage events, favor Zi Wei','Cast each independently without mixing calendars or rules','When directions agree, reinforce; when not, recheck casting and premises','Learn one system solidly, then use the other for cross-validation'],
 cnMis:['把五行生克直接套到紫微星曜上','用紫微农历规则去排八字，历法混用','两套都半懂就互相否定或硬凑结论'],
 enMis:['Applying five-element cycles directly to Zi Wei stars','Casting BaZi with Zi Wei\'s lunar rules, mixing calendars','Half-knowing both and denying or forcing conclusions between them'],
 cnClose:'紫微和八字不是谁取代谁，而是一张地图的两种比例尺。想清楚要看宏观地形还是具体街道，选对工具，才看得清。',
 enClose:'Neither replaces the other; they are two scales of one map. Decide whether you need terrain or street level, choose the right tool, and the picture clears.'},

{cat:'faq',slug:'ziwei-xinshou-xian-beixing-haishi-xian-xue-kanpan',focus:'新手学习顺序',focusEn:'beginner learning order',
 cnT:'紫微斗数新手先背星还是先学看盘：正确顺序是先骨架后填星',enT:'Should a Zi Wei Beginner Memorize Stars First or Learn to Read First? Skeleton Before Stars',
 cnD:'新手最容易陷进背星性的泥潭，正确路径是先懂十二宫和三方四正的骨架，再拿自己的盘边看边补星，最后才学四化格局与大限流年。',
 enD:'Beginners often drown memorizing star traits. The right path is the skeleton of twelve palaces and triple-direction first, then fill in stars on your own chart, and only then learn transformations, patterns and cycles.',
 cnL:'先背一百颗星却不会看一张盘，是大多数人学废的原因；先搭骨架，星性才知道往哪放、怎么用。',
 enL:'Memorizing a hundred stars without reading a chart is why most learners stall; build the skeleton first and star meanings have somewhere to land.',
 cnA:'新手一上来就买本星性大全硬背，背完还是不会看盘，问题不在记性，而在学习顺序错了，把零件当成了图纸。',
 enA:'Beginners buy star encyclopedias and memorize hard, yet still cannot read a chart; the problem is order—parts mistaken for the blueprint.',
 cnLog:['十二宫和三方四正是看盘的坐标系，没有它，星性背得再熟也无处安放。','第二阶段用自己的盘认识十四主星，结合真实性格记星性，比抽象背诵快得多。','第三阶段学生年四化，理解一张盘的动态主线，再学辅煞曜做修饰。','格局和大限流年是进阶，等能独立读完一张本命盘再学，否则容易空中楼阁。'],
 enLog:['Twelve palaces and the triple-direction are the coordinate system; without it, memorized stars have nowhere to attach.','Stage two learns the fourteen major stars on your own chart, remembering traits through real personality far faster than abstract rote.','Stage three adds natal transformations for the dynamic storyline, then assistant and malefic stars as shading.','Patterns and cycles are advanced; learn them only after independently reading a natal chart, or the whole thing floats.'],
 cnStep:['第一步学会用工具排出自己的盘，不手算','第二步吃透十二宫和六组对宫、三方四正的连线','第三步拿自己命宫主星入门，结合性格记十四主星','第四步学生年四化，看资源、掌控、名声、功课落在哪','第五步补辅煞曜和常见格局，丰富细节','第六步进大限流年，在自己的真实年份上验证节奏'],
 enStep:['First cast your own chart with a tool rather than by hand','Second, master the twelve palaces, six opposite pairs and triple-direction lines','Third, start with your own Life major star and learn the fourteen through real personality','Fourth, learn natal transformations for resources, control, reputation and lessons','Fifth, add assistant/malefic stars and common patterns for detail','Sixth, enter decades and years, testing timing against your real years'],
 cnMis:['一上来死背全部星性，背完仍不会看盘','跳过十二宫三方直接学格局，地基悬空','只在书本上学，从不拿自己和身边人的盘实操'],
 enMis:['Rote-memorizing every star first and still being unable to read','Skipping palaces and triple-direction to study patterns, with no foundation','Learning only from books without practicing on real charts'],
 cnClose:'学紫微和拼地图一样，先有坐标系，再填地标。按「宫位—主星—四化—辅煞—格局—流年」的顺序走，会比硬背快很多。',
 enClose:'Learning Zi Wei is like assembling a map: coordinates first, landmarks after. Follow palaces, major stars, transformations, assistants, patterns and cycles, and you progress far faster than rote memorization.'},
];
