const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'kanpan',slug:'ziwei-konggong-bushi-meiyun-yao-jie-duigong-sanfang',focus:'空宫',focusEn:'an empty palace',
 cnT:'紫微斗数空宫不是没运：借对宫之前先把三方看全',enT:'An Empty Palace in Zi Wei Dou Shu Is Not No Luck: Borrow the Opposite After Reading the Whole Triple-Direction',
 cnD:'空宫指本宫没有十四主星，要借对宫主星来读，但只借对宫会读薄，必须连同三方四正一起，才知道借来的星稳不稳。',
 enD:'An empty palace holds none of the fourteen major stars and borrows its opposite\'s major star, but borrowing only the opposite reads thin; the whole triple-direction shows how stable that borrowed star is.',
 cnL:'空宫不是空白人生，而是本宫不设主角、要请对宫来主演；请之前先看三方给不给配角和资源。',
 enL:'An empty palace is not a blank life but a stage without its own lead that invites the opposite to star; check the trine for supporting cast and resources first.',
 cnA:'有人一看命宫空宫就慌，以为自己「命里什么都没有」，直接把对宫主星整套搬过来，结果忽略了三方煞星会让借来的星走样。',
 enA:'People panic at an empty Life Palace, assume they have nothing, and copy the opposite star wholesale—overlooking that malefics in the trine distort the borrowed star.',
 cnLog:['空宫是本宫无十四主星，并非没有辅星、煞星和四化，这些照样要读。','第一步借对宫主星定基调，本宫的表现会带对宫的影子，但力量打折扣。','第二步看本宫三方四正，吉星多则借来的星被加强，煞星重则借来的星变形。','空宫的人适应力强、易受环境影响，所以更要看大限流年谁来填这个宫。'],
 enLog:['Empty means no major star, not no assistant stars, malefics or transformations—these still count.','First borrow the opposite major star for tone; the empty palace echoes it but at reduced strength.','Then read its triple-direction: many auspicious stars strengthen the borrowed lead; heavy malefics distort it.','Empty-palace people adapt strongly and are shaped by environment, so which star fills the palace in each decade and year matters even more.'],
 cnStep:['确认本宫确实没有十四主星，先别下「无运」结论','找对宫主星作为借来的主角，记下它的星性','看本宫三方四正，吉星煞星分别数清楚','判断借来的星是被吉星加固还是被煞星扭曲','再看本宫的辅星、四化，补上细节','最后看大限流年是否有主星入主，那是这一宫被真正点亮的时段'],
 enStep:['Confirm the palace truly has no major star before concluding anything','Take the opposite major star as the borrowed lead and note its nature','Read the palace\'s triple-direction, counting auspicious and malefic stars separately','Judge whether the borrowed lead is reinforced by auspicious stars or distorted by malefics','Add detail from the palace\'s assistant stars and transformations','Finally see which decade or year brings a major star in—that is when this palace truly lights up'],
 cnMis:['把空宫当「什么都没有」而自我设限','只借对宫主星、不看三方，导致借来的力量判断失真','以为对宫主星就等于本宫，忽略了力量打折和环境塑造'],
 enMis:['Treating empty as having nothing and self-limiting','Borrowing only the opposite star while skipping the trine, misjudging the borrowed strength','Equating the opposite star with the home palace and ignoring reduced power and environmental shaping'],
 cnClose:'空宫读对了，反而是一种弹性：你不是没有主角，而是会随阶段和环境换主角，关键是学会主动选择靠近什么样的三方。',
 enClose:'Read correctly, an empty palace is flexibility: you are not without a lead but change leads with stage and environment—the skill is choosing which triple-direction to stand near.'},

{cat:'kanpan',slug:'ziwei-li-taiji-huan-ge-gong-dang-minggong',focus:'立太极',focusEn:'resetting the Taiji (re-centering)',
 cnT:'紫微斗数立太极是什么：换一个宫当命宫，整件事就换了视角',enT:'What "Resetting the Taiji" Means in Zi Wei Dou Shu: Re-Centering on Another Palace Changes the Whole View',
 cnD:'想看哪一类事，就以那个宫为新的命宫重排十二宫，比如看事业以官禄宫立太极，就能读出这件事本身的资源、过程与结果。',
 enD:'To examine a matter, treat its palace as a new Life Palace and re-map the twelve around it; centering on the Career palace, for example, reveals that matter\'s own resources, process and outcome.',
 cnL:'命宫只是「以我为中心」的一套读法；立太极是把镜头对准那件事本身，看它自己的十二宫关系。',
 enL:'The Life Palace is only the self-centered view; resetting the Taiji points the camera at the matter itself and reads its own twelve-palace relations.',
 cnA:'新手常把所有问题都拿回命宫解释，结果看事业、看感情都只能说「因为你是这种性格」，读不出这件事自身的来龙去脉。',
 enA:'Beginners route every question back to the Life Palace and explain career or love only as personality, missing the matter\'s own chain of cause and effect.',
 cnLog:['十二宫是一套相对关系，以哪个宫为命宫，其它宫就相对它重新定义，这就是立太极。','看事业以官禄为新命宫：其财帛是交友宫（客户团队），其官禄是命宫（你自己），其福德是财帛（变现满足）。','看感情以夫妻宫立太极，能看这段关系本身的资源、压力和外在环境。','立太极不是另排一张盘，而是同一张盘换中心，用来深挖某一件具体的事。'],
 enLog:['The twelve palaces are relative relations; whichever you treat as Life redefines the rest—that is resetting the Taiji.','For career, center on Career: its wealth becomes Friends (clients and team), its career becomes Life (you), its karma becomes Wealth (monetized satisfaction).','For relationships, center on the Spouse palace to read that relationship\'s own resources, pressure and environment.','Resetting is not casting a new chart but re-centering the same chart to dig into one specific matter.'],
 cnStep:['先明确你要深挖的是哪一类事，锁定对应宫位','把该宫当作新的「命宫」（太极点）','按固定间隔重数它的兄弟、夫妻、财帛、官禄等关系宫','读这件事的「财帛」（资源）、「官禄」（过程）、「福德」（结果感受）','再回到原命宫视角，把「我」和「这件事」两层叠起来','两层一致才下结论，不一致处往往就是矛盾和突破口'],
 enStep:['Decide which matter to dig into and lock its palace','Treat that palace as the new Life Palace, the Taiji point','Recount its sibling, spouse, wealth and career palaces at fixed intervals','Read the matter\'s own wealth (resources), career (process) and karma (felt outcome)','Return to the original Life view and layer self over the matter','Conclude only when the two layers agree; their mismatch is often the tension and the opening'],
 cnMis:['所有问题都只从命宫解释，无法深入具体事务','立太极时宫位数错间隔，导致关系宫张冠李戴','把立太极当成另一张命盘，忽略它和本命盘要叠加看'],
 enMis:['Explaining everything from the Life Palace, unable to go deep on a matter','Counting palace intervals wrong when re-centering and mismatching relation palaces','Treating a reset as a separate chart instead of layering it over the natal chart'],
 cnClose:'立太极是从「我是什么人」进阶到「这件事怎么运转」的关键工具，学会换中心，很多原本卡住的问题会突然通透。',
 enClose:'Resetting the Taiji is the key move from who you are to how a matter works; learning to re-center often dissolves a stuck question at once.'},

{cat:'kanpan',slug:'ziwei-nadao-pan-xian-kan-shenme-zhengque-shunxu',focus:'看盘顺序',focusEn:'the reading order',
 cnT:'紫微斗数拿到一张盘先看什么：正确顺序比死记星性更重要',enT:'What to Read First in a Zi Wei Chart: Order Matters More Than Memorizing Star Meanings',
 cnD:'正确顺序是先定盘与命身宫，再看主星格局与三方四正，接着生年四化定底色，最后大限流年定时间，乱序就容易以偏概全。',
 enD:'The right order is verify the chart and Life/Body palaces, then major stars and patterns with the triple-direction, then natal transformations for tone, and finally cycles for timing; reading out of order skews the picture.',
 cnL:'看盘不是看到哪颗星说哪颗，而是有固定的层层推进顺序，顺序对了，细节才各归各位。',
 enL:'A reading is not commenting on whichever star catches the eye; it follows fixed layers, and in the right order every detail falls into place.',
 cnA:'新手最常见的问题是东看一颗吉星、西看一颗煞星，信息越多越乱，根源是没有一条从骨架到细节的主线。',
 enA:'Beginners spot an auspicious star here and a malefic there and get more confused with more information, because they lack a line from skeleton to detail.',
 cnLog:['第一层定盘：核对农历、时辰、命身宫，盘错一切皆错。','第二层看命宫主星与整体格局、三方四正，定一个人的主轴和强弱。','第三层看生年四化落宫，定一生反复的主题与功课。','第四层看辅煞曜修饰，第五层才进大限流年定应期，顺序不可颠倒。'],
 enLog:['Layer one verifies the chart: lunar date, hour and Life/Body palaces—a wrong chart invalidates everything.','Layer two reads the Life Palace major star, overall pattern and triple-direction to set the person\'s main line and strength.','Layer three reads natal transformation palaces for recurring themes and lessons.','Layer four adds assistant and malefic shadings; layer five enters cycles for timing—the order cannot be reversed.'],
 cnStep:['先定盘：确认农历生日、时辰、命身宫无误','看命宫主星与三方四正，定主轴和整体强弱','扫一眼主要格局成不成立，但不急着贴富贵标签','读生年四化，定一生的资源、掌控、名声与功课','用辅煞曜和四化细节做修饰，补充具体表现','最后进大限、流年，判断当前阶段和今年的引动'],
 enStep:['Verify the chart: lunar birthday, hour and Life/Body palaces','Read the Life major star and triple-direction for the main line and overall strength','Scan whether major patterns hold without rushing wealth-or-rank labels','Read natal transformations for lifelong resources, control, reputation and lessons','Refine with assistant and malefic stars and transformation details','Only then enter decade and year for the current stage and this year\'s trigger'],
 cnMis:['上来就盯单颗星或单个化忌，以偏概全','格局还没看就先看流年，把阶段波动当成一生定局','跳过定盘，在一张可能排错的盘上做精细解读'],
 enMis:['Starting with one star or one Ji and generalizing from a fragment','Reading the year before the pattern and mistaking stage fluctuation for lifelong fate','Skipping verification and doing fine-grained reading on a possibly wrong chart'],
 cnClose:'看盘顺序本质是「先骨架后细节、先一生后阶段」。把顺序练成习惯，你会发现读盘又快又稳。',
 enClose:'The reading order is skeleton before detail and life before stage. Making it a habit makes reading both faster and steadier.'},

{cat:'kanpan',slug:'ziwei-zhuxing-buruo-shaxing-duo-zenme-pingheng',focus:'主星与煞星',focusEn:'major stars versus malefics',
 cnT:'紫微斗数主星不弱但煞星很多：先定主轴还是先判风险',enT:'Strong Major Star but Many Malefics in Zi Wei Dou Shu: Main Line First or Risk First',
 cnD:'主星决定一个人的主轴和能力，煞星决定过程中的摩擦与代价，主星稳则煞星多表现为折腾而非崩盘，读法是先认主轴再评估煞星怎么用。',
 enD:'The major star sets your main line and ability; malefics set friction and cost along the way. A stable major star turns many malefics into struggle rather than collapse—confirm the main line, then assess how the malefics operate.',
 cnL:'煞星多不等于命差，关键看主星扛不扛得住：扛得住，煞星是磨刀石；扛不住，才是反复受挫。',
 enL:'Many malefics do not equal a bad fate; what matters is whether the major star can bear them—if so they are a whetstone, if not, repeated setbacks.',
 cnA:'有人一看三方会了擎羊陀罗火星就紧张，却没先评估主星是开创型还是保守型、有没有吉星辅佐，风险判断因此被放大。',
 enA:'People tense up at Yang, Tuo and Huo in the trine before judging whether the major star is pioneering or conservative and whether auspicious stars assist, inflating the risk.',
 cnLog:['主星是「人」，煞星是「路上的坡和坑」，先确认这个人有没有力气走路，再谈路况。','开创型主星（杀破狼、紫微等）遇煞反而激发冲劲，保守型主星遇煞更容易内耗。','煞星要看有没有吉星、化科化权制衡，有制则为用，无制才为祸。','同宫煞与三方煞不同：同宫贴身、影响最直接，三方煞是环境层面的摩擦。'],
 enLog:['The major star is the person; malefics are slopes and pits on the road—first confirm the person can walk, then discuss the road.','Pioneering stars (Sha-Po-Lang, Zi Wei) are sparked by malefics; conservative stars are more easily drained.','Check whether auspicious stars or Hua Ke/Quan balance the malefics—controlled, they become useful; unchecked, they harm.','Same-palace malefics are贴身 and direct; trine malefics are environmental friction.'],
 cnStep:['先定主星类型与强弱，确认主轴能力','数清煞星是同宫还是三方会照，判断贴身程度','找有没有吉星、化科、化权制衡','主星强且有制：把煞星解读为执行力和抗压训练','主星弱又无制：重点给风险管理和节奏建议','最后用大限流年判断煞星在哪个阶段被引动'],
 enStep:['Fix the major star\'s type and strength to confirm core ability','Count whether malefics share the palace or meet by trine to gauge closeness','Look for auspicious stars, Hua Ke or Hua Quan that balance them','Strong major star with checks: read malefics as execution and resilience training','Weak major star without checks: focus advice on risk management and pacing','Finally use decade and year to see when the malefics are triggered'],
 cnMis:['数到煞星多就直接判差命，不看主星强弱','把所有煞星一概而论，忽略擎羊、陀罗、火铃性质不同','只看数量不看有没有制衡，风险被夸大或低估'],
 enMis:['Judging a bad fate from many malefics without the major star\'s strength','Treating all malefics alike, ignoring that Yang, Tuo, Huo and Ling differ','Counting quantity without checks, inflating or understating risk'],
 cnClose:'主星是底子，煞星是过程。底子稳，再多摩擦也是成长的形状；读盘要先给人信心，再给出和摩擦相处的方法。',
 enClose:'The major star is the foundation and malefics the process. On a solid foundation, friction shapes growth—give confidence first, then ways to work with the friction.'},

{cat:'kanpan',slug:'ziwei-jixing-duo-jiu-yiding-hao-ma',focus:'吉星多',focusEn:'many auspicious stars',
 cnT:'紫微斗数吉星多就一定命好吗：吉星也要看场合和主轴',enT:'Do Many Auspicious Stars Guarantee a Good Fate in Zi Wei Dou Shu? Context and Main Line Matter',
 cnD:'吉星是助力和机会，但吉星过多而主星无力，反而容易「什么机会都有、什么都抓不深」，吉星要挂在一条清晰主轴上才有用。',
 enD:'Auspicious stars are help and opportunity, but too many around a weak major star can mean every chance appears and none is taken deeply; they work only when hung on a clear main line.',
 cnL:'吉星不是越多越好，而是越对位置越好；没有主轴承接，吉星只是一堆用不上的好条件。',
 enL:'Auspicious stars are not about quantity but placement; without a main line to receive them, they are unused advantages.',
 cnA:'有人看到命宫三方左辅右弼文昌文曲天魁天钺全齐就断言好命，现实里却选择太多、方向太散，问题就在只数吉星不看主轴。',
 enA:'People see Zuo Fu, You Bi, Wenchang, Wenqu, Tian Kui and Tian Yue all present and predict a great fate, yet real life shows too many options and scattered direction—counting stars without a main line.',
 cnLog:['吉星分辅佐（左右）、文书（昌曲）、贵人（魁钺），各有分工，不是同一种「好」。','吉星要挂在主星和主轴上才发力，主星弱则吉星无所依附。','吉星与煞星同宫时，吉凶相杂，要看谁主导、事情在哪个领域。','吉星给的是「容易得到帮助」，最终结果仍取决于大限流年是否引动、本人是否行动。'],
 enLog:['Auspicious stars divide into aides (Zuo Fu/You Bi), letters (Chang/Qu) and helpful people (Kui/Yue)—different kinds of good.','They fire only when attached to a major star and main line; a weak major star leaves them nothing to cling to.','When auspicious and malefic stars share a palace, judge which dominates and in which field.','They make help easier to receive, but the outcome still depends on cycle triggers and personal action.'],
 cnStep:['先看主星主轴，确认有没有承接吉星的「主干」','把吉星按辅佐、文书、贵人分类，看助力类型','检查吉星落在哪个宫，判断机会出现在哪个领域','看吉星是否被煞星拖累或被化忌打折扣','吉星多而主轴弱时，建议聚焦而非扩张','结合大限看哪段时间贵人与机会真正到位'],
 enStep:['Read the major star and main line first to confirm a trunk for auspicious stars','Classify them into aides, letters and helpful people to see the type of help','Note which palace they land in, i.e. where opportunities appear','Check whether malefics drag them down or Hua Ji discounts them','With many auspicious stars but a weak main line, advise focus rather than expansion','Use the decade to see when helpful people and opportunities actually arrive'],
 cnMis:['把吉星数量当命好的唯一指标','不分类，把所有吉星当成同一种助力','吉星多就劝人大胆扩张，忽略主轴不清时机会反成干扰'],
 enMis:['Using auspicious-star count as the only measure of a good fate','Not classifying them and treating all help as identical','Urging expansion from many auspicious stars while a blurred main line turns chances into noise'],
 cnClose:'吉星是好风，但船得先有舵。先立主轴，再谈顺风，吉星才不会变成一堆漂亮却分散的可能。',
 enClose:'Auspicious stars are good wind, but the boat needs a rudder first. Set the main line, then the tailwind helps instead of becoming a set of pretty, scattered possibilities.'},

{cat:'kanpan',slug:'ziwei-dingpan-shichen-buzhun-ruhe-jiaoshi',focus:'定盘校时',focusEn:'chart verification and hour correction',
 cnT:'紫微斗数时辰不准怎么定盘：用性格和大事把时辰校回来',enT:'How to Verify a Zi Wei Chart When the Birth Hour Is Uncertain',
 cnD:'时辰不确定时不要硬断，可用相邻两个时辰分别排盘，再用性格、六亲、过往重大转折逐年比对，最贴合事实的那张就是对的盘。',
 enD:'When the hour is uncertain, do not force a verdict; cast the two adjacent hours and compare personality, family and major past turning points against each—the chart that fits the facts is the right one.',
 cnL:'定盘的本质是「让盘去对人」，而不是让人去迁就一张可能错的盘，事实是检验时辰的唯一标准。',
 enL:'Verification means fitting the chart to the person, not bending the person to a possibly wrong chart; facts are the only test of the hour.',
 cnA:'很多人只知道大概是上午还是下午生，就随便挑个时辰排盘，结果越算越对不上，其实只要用已知人生事件反推，就能把时辰收敛到正确区间。',
 enA:'Knowing only morning or afternoon, people pick an hour loosely and find the reading never fits; known life events can reverse-engineer the correct block.',
 cnLog:['一个时辰跨两小时，跨时辰命宫就可能整盘换，所以时辰是定盘第一关。','先列出可能的两到三个相邻时辰，各排一张候选盘。','用命宫主星核对性格、用父母宫等核对六亲、用大限流年核对过往大事年份。','哪张候选盘能同时解释性格和多件大事，哪张就是定盘；单点吻合不算数。','闰月、夜子时、异地出生还要叠加历法与真太阳时的校正。'],
 enLog:['One block spans two hours, and crossing it can move the whole chart, so hour is the first gate.','List the two or three adjacent candidate blocks and cast a candidate chart for each.','Match personality via the Life major star, family via its palaces, and past event years via decades and annual palaces.','The candidate that explains personality and several events together is the verified chart; a single match does not count.','Leap months, late Zi hour and distant birthplaces also need calendar and true-solar-time correction.'],
 cnStep:['收集出生信息：已知时间范围、出生地、闰月与否','列出所有可能的相邻时辰，分别排候选盘','先用性格快速排除明显不符的候选','再用父母、兄弟、配偶等六亲情况缩小范围','用过往升学、搬家、结婚、换工作等大事年份逐一比对','多张都接近时，用最近一两年的流年事件做最终裁决'],
 enStep:['Gather birth facts: time range, birthplace and leap-month status','List every plausible adjacent block and cast candidate charts','Use personality to quickly rule out obvious mismatches','Narrow with parents, siblings and partner circumstances','Compare years of past events such as schooling, moving, marriage and job changes','When several stay close, use the most recent one or two annual events as the final arbiter'],
 cnMis:['时辰没定就开始细断，把错盘上的结论当真','只用一件巧合事件定时辰，忽略要多点交叉验证','忽略真太阳时和早晚子时，导致校时方向错误'],
 enMis:['Reading in detail before the hour is fixed and trusting conclusions on a wrong chart','Verifying from one coincidental event instead of cross-checking multiple points','Ignoring true solar time and early/late Zi hour, sending correction the wrong way'],
 cnClose:'定盘是所有解读的前提。宁可在校时上多花时间，也不要让一张没校准的盘带你走错方向。',
 enClose:'Verification precedes every interpretation. Better to spend time correcting the hour than let an uncalibrated chart lead you astray.'},
];
