const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'liunian',slug:'ziwei-shinian-daxian-he-benming-shi-shenme-guanxi',focus:'大限与本命',focusEn:'the decade limit versus the natal chart',
 cnT:'紫微斗数十年大限和本命盘是什么关系：底盘不变，舞台轮换',enT:'The Relationship Between the Ten-Year Decade Limit and the Natal Chart in Zi Wei Dou Shu',
 cnD:'本命盘是一生不变的底盘，大限是每十年换一次的主舞台，大限宫位叠在本命盘上解读，本命定可能性、大限定哪个阶段兑现。',
 enD:'The natal chart is a lifelong base that never changes; the decade limit is a main stage that rotates every ten years and is read layered over the natal chart. The natal sets possibilities, the decade sets when they cash out.',
 cnL:'本命像你的体质，大限像你在不同十年所处的环境，体质不变，但顺不顺要看这十年走到哪个宫位。',
 enL:'The natal chart is your constitution; the decade is the environment of each ten-year stretch. The constitution stays, but how smoothly things go depends on which palace the decade walks through.',
 cnA:'有人本命普通就灰心，或大限一顺就以为从此翻身，都是没分清「不变的底盘」和「轮换的舞台」。',
 enA:'Despairing over an ordinary natal chart, or assuming one smooth decade means permanent turnaround, both fail to separate the fixed base from the rotating stage.',
 cnLog:['本命盘固定，描述一生的星曜结构、性格底色与可能性边界。','大限每十年顺移一宫，以该宫为这十年的「大限命宫」，重布这十年的四化与重心。','读大限必须叠回本命：同一颗星，落在本命不同宫位，十年含义完全不同。','本命定「有没有、是什么」，大限定「这十年强不强、动不动」，流年再定「今年哪件事」。'],
 enLog:['The natal chart is fixed, describing lifelong star structure, temperament and the range of possibility.','The decade moves one palace every ten years, making that palace the decade Life Palace and resetting the decade\'s transformations and focus.','A decade must be read over the natal: the same star means different things depending on which natal palace it lands.','The natal sets what-is, the decade sets how strong and active these ten years, and the year sets which specific matter occurs now.'],
 cnStep:['先读懂本命盘的主轴、四化和格局，建立底盘','找到当前十年大限命宫落在本命哪个宫','以大限命宫重数这十年的十二宫，定阶段主题','看大限四化叠在本命哪几宫，判断引动了哪条线','区分哪些是本命长期特质、哪些只是这十年的阶段现象','再用流年细化到具体年份，不拿大限结论给一生定性'],
 enStep:['First read the natal main line, transformations and patterns to build the base','Find which natal palace holds the current decade Life Palace','Recount the decade twelve palaces from it for the stage theme','See where decade transformations land on the natal chart to find the activated line','Separate lifelong natal traits from ten-year stage phenomena','Then refine to specific years, never defining a whole life by one decade'],
 cnMis:['只看本命就把人看死，忽略大限的阶段起伏','只看大限不回叠本命，导致十年主题落不到具体领域','把某十年的顺逆当成终身结论'],
 enMis:['Reading only the natal and fixing a person for life, ignoring decade swings','Reading the decade without overlaying the natal, leaving the stage theme ungrounded','Taking one decade\'s fortune as a lifelong verdict'],
 cnClose:'本命是牌，大限是出牌的回合。底盘决定你手里有什么，大限决定这十年怎么打，两层一起看，人生才是动态的而不是定死的。',
 enClose:'The natal is the hand, the decade the round in which you play it. The base decides your cards, the decade how you play them; reading both makes life dynamic rather than fixed.'},

{cat:'liunian',slug:'ziwei-liunian-luogong-zenme-ding-jinnian-zhuti',focus:'流年落宫',focusEn:'the annual palace',
 cnT:'紫微斗数流年落宫怎么定今年的主题：流年命宫走到哪，哪类事上台',enT:'How the Annual Palace Sets This Year\'s Theme in Zi Wei Dou Shu',
 cnD:'流年命宫按当年地支落在本命盘某宫，叠加该宫原有星曜，决定这一年的主场景，再看流年四化与三方，定今年具体在哪件事上起伏。',
 enD:'The annual Life Palace lands on a natal palace by the year\'s earthly branch and combines with that palace\'s stars to set the year\'s main scene; annual transformations and its trine then pin down which matter rises or falls.',
 cnL:'看流年先找「今年的你站在本命的哪个宫」，那个宫管的事，就是今年最容易被推上台面的主题。',
 enL:'To read a year, first find which natal palace this year\'s self stands in; whatever that palace governs is the theme most likely pushed to the front.',
 cnA:'很多人看流年只看流年生肖或一颗流年化忌，说来说去很笼统，关键是没把流年命宫落回本命十二宫去定位主题。',
 enA:'People read the year only through its zodiac or one annual Ji and stay vague, because they never locate the annual Life Palace within the natal twelve palaces.',
 cnLog:['流年命宫由当年地支决定，顺布流年十二宫，是一年的临时命宫。','流年命宫叠加本命某宫的星曜：本命该宫的长期含义，就是今年的主场景。','流年四化给主场景定调：化禄是机会、化忌是卡点，落在哪个领域就动哪个领域。','流年判断必须在本命和大限之下进行，三层一致，今年那件事才最明显。'],
 enLog:['The annual Life Palace is set by the year\'s branch, with the annual twelve palaces spread from it as a temporary self for the year.','It overlays a natal palace\'s stars: that palace\'s long-term meaning becomes the year\'s main scene.','Annual transformations set its tone—Lu the opening, Ji the snag—activating whichever field they land in.','The year is read under natal and decade; when all three align, that year\'s matter is clearest.'],
 cnStep:['先确认本命底盘和当前大限方向','按当年地支找到流年命宫落在本命哪个宫','读出该宫的本命含义，定今年主场景','布流年四化，看禄权科忌分别落在哪个领域','看流年命宫三方四正，评估今年的助力与摩擦','三层一致处重点规划，单一流年信号只作参考'],
 enStep:['Confirm the natal base and current decade direction','Use the year\'s branch to find which natal palace the annual Life Palace lands on','Read that palace\'s natal meaning to set the year\'s main scene','Spread annual transformations to see where Lu, Quan, Ke and Ji land','Read the annual Life Palace triple-direction for this year\'s help and friction','Plan heavily where all three layers align; treat a lone annual signal as reference only'],
 cnMis:['只看生肖运势，不排流年命宫','流年脱离大限本命，单独放大成全年结论','只盯流年化忌，忽略流年化禄给的机会口'],
 enMis:['Reading only zodiac fortune without casting the annual Life Palace','Detaching the year from decade and natal and inflating it into a full-year verdict','Fixating on annual Ji while ignoring the opening annual Lu provides'],
 cnClose:'流年是时间轴上最贴身的一层。先让它站回本命的宫位，再听大限的方向，今年的主题才会具体到「哪件事、怎么动」。',
 enClose:'The year is the closest layer on the timeline. Standing it back in its natal palace and under the decade\'s direction makes this year\'s theme concrete: which matter, and how it moves.'},

{cat:'liunian',slug:'ziwei-daxian-hao-liunian-cha-zenme-ban',focus:'大限好流年差',focusEn:'a good decade with a difficult year',
 cnT:'紫微斗数大限好但流年差怎么办：顺境十年里的回调年怎么过',enT:'What to Do When the Decade Is Good but the Year Is Difficult in Zi Wei Dou Shu',
 cnD:'大限走上升期、个别流年却遇化忌或煞星引动，属于大趋势中的短期回调，不是十年好运被推翻，策略是守核心、降杠杆、等节奏回来。',
 enD:'During an upward decade, a year triggered by Ji or malefics is a short-term correction within a larger trend, not the end of a good ten years; the strategy is defend the core, cut leverage and wait for rhythm to return.',
 cnL:'先分清「风」和「一阵浪」：大限是风，流年是浪，风没改向时，一个逆风浪不该让你弃船。',
 enL:'Distinguish wind from a single wave: the decade is the wind, the year a wave; when the wind has not turned, one headwind wave is no reason to abandon ship.',
 cnA:'有人在好的大限里遇到一个差流年就全盘否定、仓促转向，结果把十年上升通道里本可消化的小回调，做成了大损失。',
 enA:'People hit one hard year in a good decade, deny the whole picture and pivot hastily, turning a digestible correction in a ten-year uptrend into a real loss.',
 cnLog:['大限管十年主趋势，流年管一年内的短期引动，层级不同、权重不同。','好大运里的差流年，多表现为节奏被打乱、某件事卡一下，而非根基动摇。','判断关键看差流年的化忌是否冲到大限主轴和本命核心，冲不到就是局部回调。','回调年的正确动作是收缩风险、补足短板、为下一个顺流年蓄力，而不是推翻方向。'],
 enLog:['The decade governs the ten-year trend, the year a short trigger—different levels, different weight.','A hard year in a good decade usually disrupts rhythm or snags one matter rather than shaking the foundation.','The key test is whether the year\'s Ji clashes with the decade main line or natal core; if not, it is a local correction.','In a correction year, shrink risk, fix weak links and store energy for the next smooth year instead of overturning direction.'],
 cnStep:['先确认大限主轴确实向上，避免把「大限转差」误判成「流年回调」','定位差流年的化忌煞星落在哪个领域，判断是局部还是全局','守住十年主线相关的核心资产、关系和岗位，不轻易丢','降低杠杆和冒进决策，回调年以稳为主','趁节奏慢补能力、补流程、补短板','等下一个流年四化转好再加力，而不是在最低点放弃'],
 enStep:['Confirm the decade main line is truly up, so you do not mistake a turning decade for a yearly correction','Locate the hard year\'s Ji and malefics to judge local versus global impact','Hold the core assets, relationships and position tied to the ten-year line','Cut leverage and aggressive decisions; prioritize stability in a correction year','Use the slower rhythm to build skill, process and weak links','Re-accelerate when the next annual transformations improve rather than quitting at the low point'],
 cnMis:['一个差流年就推翻十年方向','分不清大限转差和流年回调，动作做反','回调年反而加杠杆赌反弹，放大损失'],
 enMis:['Overturning a ten-year direction over one hard year','Confusing a turning decade with a yearly correction and acting the wrong way','Adding leverage in a correction year to bet a rebound, magnifying loss'],
 cnClose:'好的大限不是每年都顺。把差流年理解成上升途中的换气点，守住核心、收一收拳头，下一拳才打得更有力。',
 enClose:'A good decade is not smooth every year. Read a hard year as a breathing point on the way up—hold the core, pull the fist back, and the next strike lands harder.'},

{cat:'liunian',slug:'ziwei-shuangji-diejia-daxianji-liunianji-zenme-fang',focus:'双忌叠加',focusEn:'double Ji stacking',
 cnT:'紫微斗数双忌叠加怎么办：大限忌和流年忌同打一处时怎么防',enT:'How to Handle Double Ji Stacking in Zi Wei Dou Shu When Decade Ji and Annual Ji Hit the Same Place',
 cnD:'大限化忌与流年化忌落同一宫或对冲时，这一领域当年压力集中，属于需要主动防守的年份，重点是提前识别、降低投入、守住底线而不是硬冲。',
 enD:'When decade Ji and annual Ji land in the same palace or clash across, that field faces concentrated pressure that year—a year to defend proactively by spotting it early, lowering exposure and holding the line rather than charging.',
 cnL:'双忌同打一处，不是叫你认命，而是提示你「这处今年最脆」，提前把风险敞口收小，反而最容易平稳过关。',
 enL:'Double Ji on one spot is not fate but a warning that this area is most fragile this year; shrinking exposure early is exactly how you pass it steadily.',
 cnA:'多数人是被双忌打了才回头找原因，其实大限忌是已知的十年功课，流年忌可以提前排出来，完全有时间做防守预案。',
 enA:'Most people look for causes only after double Ji hits, yet the decade Ji is a known ten-year lesson and the annual Ji can be cast ahead of time, leaving room to prepare.',
 cnLog:['化忌主执念与卡点，大限忌是这十年反复磨的领域，流年忌是当年再点一次。','两者同宫或对冲，等于长期功课在今年被集中放大，是全年最需要谨慎的一条线。','判断强度看是否还引动本命化忌，三层忌交汇则该领域当年宜守不宜攻。','双忌年不是无解：化科可缓和、禄存可补资源、主动降预期和减投入就是最实在的化解。'],
 enLog:['Ji is fixation and blockage; decade Ji is the field ground across ten years, annual Ji presses it again this year.','Same palace or clash means a long-term lesson is concentrated this year—the line requiring most caution.','Gauge strength by whether natal Ji is also triggered; three-layer convergence calls for defending, not attacking, that field.','A double-Ji year is not hopeless: Hua Ke smooths, Lu Cun adds resources, and lowering expectations and exposure is the most concrete resolution.'],
 cnStep:['先找大限化忌落在哪个领域，明确这十年的功课区','排出当年流年化忌，看是否与大限忌同宫或对冲','若双忌叠加，提前把该领域的投入、承诺和杠杆降到可承受范围','找化科、禄存或吉星，制定缓冲和补救方案','该领域当年以「守住、收口、不恶化」为目标，不追求扩张','全年复盘触发事件，把这一年当作集中清理旧功课的机会'],
 enStep:['Find where decade Ji lands to know the ten-year lesson area','Cast the year\'s annual Ji and see whether it shares or clashes with decade Ji','If they stack, lower that field\'s investment, commitments and leverage to a bearable range early','Find Hua Ke, Lu Cun or auspicious stars to build a buffer and recovery plan','Set that field\'s yearly goal as hold, close loops and avoid worsening—not expansion','Review triggers through the year and treat it as concentrated cleanup of an old lesson'],
 cnMis:['双忌年还逆势重仓扩张，把防守年打成硬冲年','只看到「忌」就恐慌，忽略化科禄存的缓冲','事后才发现双忌叠加，错过提前布防的窗口'],
 enMis:['Expanding heavily against a double-Ji year, turning defense into a charge','Panicking at Ji while ignoring the buffer of Hua Ke and Lu Cun','Noticing the stack only afterward and missing the early defense window'],
 cnClose:'双忌叠加是一张「此地今年慢行」的路标。看懂它、提前减速、守住底线，你会发现最被看衰的年份，反而过得最稳。',
 enClose:'Double Ji is a slow-down-here sign for the year. Read it, ease off early and hold the line, and the year everyone fears can turn out to be your steadiest.'},
];
