const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'sihua',slug:'ziwei-shengnian-sihua-jueding-mingpan-dise',focus:'生年四化',focusEn:'the natal Four Transformations',
 cnT:'紫微斗数生年四化怎么定一张盘的底色',enT:'How the Natal Four Transformations Set the Baseline of a Zi Wei Chart',
 cnD:'生年四化由出生年天干决定，化禄化权化科化忌落在哪个宫，这一生就反复在那件事上体验收获、掌控、名声与卡点。',
 enD:'The natal Four Transformations come from your birth-year stem. Where Lu, Quan, Ke and Ji land shows where you repeatedly experience gain, control, reputation and blockage across life.',
 cnL:'看一张盘先找生年四化，它像四个永久标记，告诉你这张盘天生的资源在哪、力气往哪使、又会被什么绊住。',
 enL:'Find the natal Four Transformations first; they are four permanent markers showing innate resources, where effort goes, and what keeps snagging you.',
 cnA:'很多人一上来就看命宫主星，却跳过生年四化，结果讲性格很热闹，讲不准一个人一生反复出现的主题。',
 enA:'Many start with the Life Palace major star and skip the natal transformations, producing vivid personality talk but missing the recurring themes of a life.',
 cnLog:['生年四化由出生年的天干决定，同一年出生的人四化星相同，但落宫不同，主题就不同。','化禄是资源与收获的方向，化权是掌控与承担的方向，化科是名声与缓和的方向，化忌是执念与卡点的方向。','四化不是四颗孤立的星，而是一条因果链：禄给资源、权给执行、科给名声、忌给要修的功课。','生年四化落宫是先天底色，要再叠大限、流年四化才看得到时间变化。'],
 enLog:['The natal transformations follow the birth-year stem; everyone born that year shares the same transformed stars, but different landing palaces change the theme.','Lu is resources and gain, Quan is control and responsibility, Ke is reputation and smoothing, Ji is fixation and blockage.','They form a causal chain rather than four isolated stars: Lu supplies, Quan executes, Ke reputes, Ji gives the lesson to work on.','The natal transformations are the baseline; decade and annual transformations add timing on top.'],
 cnStep:['由出生年天干查出化禄、化权、化科、化忌分别是哪四颗星','逐一定位这四颗星落在十二宫的哪个宫','先读化禄：这张盘的资源和机会天生从哪来','再读化权化科：靠什么掌握主动、靠什么被看见','重点读化忌：一生反复卡住、需要放下的是哪类事','把四宫连起来看，得出这张盘的先天主线，再进入大限流年'],
 enStep:['From the birth-year stem, identify which four stars become Lu, Quan, Ke and Ji','Locate each transformed star in the twelve palaces','Read Lu first: where innate resources and opportunities come from','Then Quan and Ke: how you take control and gain recognition','Focus on Ji: which kind of matter repeatedly blocks you and needs letting go','Connect the four palaces into a natal storyline before moving to cycles'],
 cnMis:['只看化忌吓自己，忽略禄权科其实给了资源和能力','把四化当四颗普通星，不理解它们是一条动态因果链','只看生年四化就断一生，忘了大限流年还会层层叠加'],
 enMis:['Fearing Ji alone while ignoring the resources and ability Lu, Quan and Ke provide','Treating transformations as ordinary stars instead of a dynamic causal chain','Judging a whole life from natal transformations and forgetting the layered cycles'],
 cnClose:'生年四化是一张盘的「出厂主题」。读懂它，你才看得懂后面大限流年为什么在某些年份被突然放大。',
 enClose:'The natal transformations are a chart\'s factory-set theme. Understanding them explains why certain years suddenly magnify specific matters.'},

{cat:'sihua',slug:'ziwei-daxian-sihua-jueding-shinian-fangxiang',focus:'大限四化',focusEn:'the decade-limit transformations',
 cnT:'紫微斗数大限四化怎么定十年方向：别把阶段主题当一生',enT:'How Decade-Limit Transformations Set a Ten-Year Direction',
 cnD:'每个十年大限有自己的天干和四化，它决定这十年资源、权力、名声、卡点集中在哪件事上，大限一过主题就换。',
 enD:'Each decade limit has its own stem and transformations, concentrating resources, control, reputation and blockage on one matter for ten years before the theme shifts.',
 cnL:'本命写一生底色，大限写这十年的主舞台，大限四化就是这十年剧本的主线，别用它去断一辈子。',
 enL:'The natal chart sets a lifelong tone; the decade limit is the stage for ten years, and its transformations are that decade\'s main plot—not a life sentence.',
 cnA:'有人在某个大限特别顺或特别卡，就以为自己命好或命坏，其实那只是这十年的四化把某一类事推到了台前。',
 enA:'People who sail through or struggle in one decade assume their fate is fixed, when that decade\'s transformations simply pushed one kind of matter to the front.',
 cnLog:['大限每十年换一个宫位，由该宫天干起一组新的四化。','大限化禄指向这十年资源聚集处，大限化忌指向这十年最磨人的功课。','大限四化与生年四化叠加，先天主题在这十年被放大、缓解或转向。','判断十年运势要先看大限命宫与大限四化，再看它和本命盘的关系。'],
 enLog:['The decade limit moves one palace every ten years and raises a fresh set of transformations from that palace\'s stem.','Decade Lu points to where resources gather; decade Ji points to the most grinding lesson of these years.','Decade transformations layer over natal ones, magnifying, easing or redirecting the innate theme.','To read a decade, start with its Life Palace and transformations, then relate them to the natal chart.'],
 cnStep:['先确定当前大限命宫落在本命哪个宫','由大限宫干找出这十年的禄权科忌','看大限化禄落在哪个领域，那里是这十年的机会口','看大限化忌落在哪，那里是这十年要交的功课','把大限四化与生年四化叠看，判断是顺势还是转向','十年结论只限定在这一阶段，不提前给一生定性'],
 enStep:['Determine which natal palace holds the current decade Life Palace','Derive the decade Lu, Quan, Ke and Ji from that palace\'s stem','See where decade Lu lands—that field holds the decade\'s opening','See where decade Ji lands—that field is the lesson due','Layer decade over natal transformations to judge tailwind or turn','Keep the conclusion to this stage rather than defining a whole life'],
 cnMis:['把大限的好坏当成命的好坏，忽略十年后会换场','只看大限命宫主星，不看大限四化这条主线','大限化忌一来就以为十年全毁，没看禄权科是否同时在补'],
 enMis:['Taking a decade\'s luck as lifelong fate and ignoring the stage change in ten years','Reading only the decade Life Palace star while missing its transformation storyline','Assuming a decade Ji ruins ten years without checking whether Lu, Quan and Ke compensate'],
 cnClose:'大限四化教你的是「这十年把力气用在哪」。顺的时候借势，卡的时候知道这是阶段功课，而不是给自己判终身。',
 enClose:'Decade transformations tell you where to invest ten years. Ride the tailwind when up, and when blocked treat it as a stage lesson rather than a life verdict.'},

{cat:'sihua',slug:'ziwei-liunian-sihua-ding-jinnian-xijie',focus:'流年四化',focusEn:'the annual transformations',
 cnT:'紫微斗数流年四化怎么定今年的具体触发',enT:'How Annual Transformations Pin Down This Year\'s Specific Trigger',
 cnD:'流年四化管的是当年这一层的资源与卡点，它落在本命和大限的哪个宫，就决定今年哪件事被真正点着。',
 enD:'Annual transformations govern one year\'s resources and snags; where they land on the natal and decade palaces decides which matter is actually ignited this year.',
 cnL:'生年定底色、大限定方向，流年定的是「今年具体在哪件事上发生」，三层叠起来才是完整的时间判断。',
 enL:'Natal sets the tone, decade sets direction, and the year sets where something actually happens; stacking all three gives a complete timing read.',
 cnA:'很多人看流年只看流年命宫主星，忽略流年四化，结果只能说个大概情绪，说不准今年具体动的是哪件事。',
 enA:'Reading only the annual Life Palace star while ignoring annual transformations leaves a vague mood instead of the specific matter moving this year.',
 cnLog:['流年四化由当年天干决定，每年换一组，是最表层、最贴身的引动。','流年化禄是当年的机会与进账方向，流年化忌是当年最容易卡、最耗神的地方。','流年四化要同时落回大限盘和本命盘看，同一颗化忌落在不同层级含义不同。','三层四化同指一件事时，当年那件事的应验强度最高。'],
 enLog:['Annual transformations follow the year\'s stem and change every twelve months—the closest, most surface-level trigger.','Annual Lu is the year\'s opening and income direction; annual Ji is where energy drains and things snag.','Annual transformations must be projected onto both decade and natal charts; the same Ji means different things at different levels.','When all three layers point to one matter, that matter is most likely to materialize this year.'],
 cnStep:['先确认本命底色和当前大限方向','由当年天干找出流年禄权科忌','把流年四化落回本命盘，看触动哪个生活领域','再落回大限盘，看是否与十年主线一致','重点找三层四化交汇的宫位，那里是今年最强触发点','结合流月判断大致节奏，但行动建议只给到可把握的层面'],
 enStep:['Confirm the natal baseline and current decade direction first','Derive the year\'s Lu, Quan, Ke and Ji from its stem','Project them onto the natal chart to see which life field is touched','Project onto the decade chart to see whether it matches the ten-year plot','Find palaces where all three layers converge—that is this year\'s strongest trigger','Use monthly palaces for rough timing, but keep advice at a level you can act on'],
 cnMis:['跳过本命和大限，直接拿流年四化断全年','只看流年化忌就预判一年倒霉，不看它是否被大限承接','把流年四化当静态结果，忽略它是「引动」而非「注定」'],
 enMis:['Skipping natal and decade layers and judging the year from annual transformations alone','Predicting a bad year from annual Ji without checking whether the decade supports it','Treating annual transformations as fixed outcomes rather than triggers'],
 cnClose:'流年四化是时间轴上最细的开关。先有底色和方向，再看今年的开关按在哪，判断才不会飘。',
 enClose:'Annual transformations are the finest switch on the timeline. Ground them in baseline and direction first, and the yearly read stops drifting.'},

{cat:'sihua',slug:'ziwei-hualu-bushi-diaoxianqian-ziyuan-cong-na-lai',focus:'化禄',focusEn:'Hua Lu',
 cnT:'紫微斗数化禄不是天上掉钱：资源要经过哪个宫才到手',enT:'Hua Lu in Zi Wei Dou Shu Is Not Free Money: How Resources Actually Reach You',
 cnD:'化禄代表缘分、机会和资源的入口，但它落在哪个宫，资源就以哪种形式来，能不能变现还要看官禄和命宫接不接得住。',
 enD:'Hua Lu marks the doorway to affinity, opportunity and resources, but its palace decides their form; whether they convert into results depends on the Career and Life palaces.',
 cnL:'化禄是「有缘、有得、顺手」，不是直接发钱，看到化禄先问资源从哪来、谁来接、怎么落袋。',
 enL:'Lu means affinity, gain and ease rather than cash dropped from the sky; on seeing Lu ask where the resource comes from, who receives it, and how it is banked.',
 cnA:'有人一看财帛或命宫有化禄就断言要发财，结果机会来了却没能力或没平台接住，问题就在把入口当成了结果。',
 enA:'People see Lu in Wealth or Life and predict a windfall, yet when the chance arrives they lack the skill or platform—the error is mistaking a doorway for the result.',
 cnLog:['化禄的本质是「多、顺、有缘」，让所在宫位的事变容易、资源变多。','化禄在不同宫有不同形态：在财帛是现金机会，在官禄是职位与项目机会，在迁移是外部资源。','资源到手要过三关：禄给入口、权给执行力、命宫与三方给承接能力。','化禄也可能是「糖衣」，禄随忌走时，得到的同时也埋下牵挂。'],
 enLog:['Lu\'s essence is abundance, ease and affinity, making the matters of its palace flow more easily.','Lu takes different forms by palace: cash chances in Wealth, roles and projects in Career, outside resources in Travel.','A resource passes three gates: Lu opens the door, Quan supplies execution, and the Life palace plus triple-direction supply capacity.','Lu can be sugar-coated; when Lu follows Ji, gain also plants attachment.'],
 cnStep:['先定位化禄落在哪一宫，判断资源以什么形式出现','沿三方四正看有没有化权或主星承接这份资源','看命宫与相关宫位有没有能力把机会做实','若化禄与化忌对冲，先评估得到之后的代价','区分「有机会」和「已到手」，给建议时强调行动环节','结合大限流年判断资源窗口什么时候真正打开'],
 enStep:['Locate Lu to see what form the resource takes','Follow the triple-direction for Hua Quan or major stars that can receive it','Check whether the Life palace and related palaces can make the chance real','If Lu clashes with Ji, weigh the cost after gaining','Distinguish an opening from a done deal and emphasize action in advice','Use decade and year to judge when the resource window actually opens'],
 cnMis:['把化禄直接等同于发财、结婚等结果','只看化禄所在宫，不看有没有执行力去接','以为化禄永远是好事，忽略禄随忌走的牵挂面'],
 enMis:['Equating Lu directly with outcomes like wealth or marriage','Reading only Lu\'s palace without the capacity to receive it','Assuming Lu is always good and ignoring the attachment when Lu follows Ji'],
 cnClose:'化禄回答的是「机会从哪扇门进来」，能不能变成你的，还要看你有没有走到门口、伸手去接。',
 enClose:'Lu answers which door opportunity enters through; whether it becomes yours still depends on walking to the door and reaching out.'},

{cat:'sihua',slug:'ziwei-huaquan-zeren-yali-zhudongquan',focus:'化权',focusEn:'Hua Quan',
 cnT:'紫微斗数化权：权力的背面是责任，掌控感从哪来',enT:'Hua Quan in Zi Wei Dou Shu: Behind Power Lies Responsibility',
 cnD:'化权让所在宫位的事变重、变主动，给你掌控力也压上责任，它落在哪个领域，你就要在那个领域当家、扛事。',
 enD:'Hua Quan makes its palace\'s matters heavier and more active, granting control while loading responsibility; wherever it lands, you must take charge there.',
 cnL:'化权不是升官发财的保证书，而是「这件事你得说了算、也得你来扛」，先看扛不扛得动，再谈权力。',
 enL:'Quan is not a guarantee of promotion or wealth; it means you call the shots and carry the load—check whether you can carry it before claiming the power.',
 cnA:'有人一见化权就高兴，觉得要掌权，真到那个位置才发现责任、压力、冲突全压过来，这就是只看权力不看承重。',
 enA:'People welcome Quan as coming power, only to find responsibility, pressure and conflict landing on them—reading power without the load-bearing side.',
 cnLog:['化权化气为「掌握、推进、加重」，让星曜的力量更具主导性和执行力。','化权在官禄是要在事业上当家，在财帛是要主动掌控钱，在关系宫则可能变成强势与主导。','权能化解一部分忌的拖延，也能让禄的资源真正落地，是四化里的执行环节。','权要有位置和能力匹配，孤权无辅则是「责任在你、资源不在你」的辛苦。'],
 enLog:['Quan transforms into mastery, drive and weight, making a star more dominant and execution-oriented.','In Career you must lead at work; in Wealth you actively control money; in relationship palaces it can become dominance.','Quan resolves some of Ji\'s delay and makes Lu\'s resources land—it is the execution link among transformations.','Power must match position and ability; lone Quan without support means you carry responsibility without resources.'],
 cnStep:['定位化权所在宫，确认你要在哪个领域当家','看该宫三方有没有禄、科或辅星支援，判断扛不扛得动','看化权与哪些主星同宫，评估主导方式是稳还是冲','若化权冲化忌，先处理冲突再谈扩张','区分「被授权」和「被压责任」，结合大限看是否名实相符','行动上把掌控力转成具体分工和边界，而不是一味硬扛'],
 enStep:['Locate Quan to confirm which field you must lead','Check its triple-direction for Lu, Ke or assistants to gauge whether you can carry the load','See which major star joins Quan to judge a steady or aggressive style','If Quan clashes with Ji, resolve conflict before expanding','Distinguish being empowered from being burdened, using the decade to check name versus reality','Turn control into concrete division of labor and boundaries instead of carrying everything'],
 cnMis:['把化权无条件当好事，忽略责任和压力','只看权不看有没有资源和辅佐，导致孤权硬扛','在关系宫把化权的主导误读成「对方条件好」'],
 enMis:['Treating Quan as unconditionally good while ignoring responsibility and pressure','Seeing power without resources or assistants, leading to lone burden','Misreading dominance in a relationship palace as a partner\'s high status'],
 cnClose:'化权给的是主导权，也是一份承重契约。看清自己扛不扛得动，权力才会变成成就而不是消耗。',
 enClose:'Quan grants initiative but also a load-bearing contract. Seeing whether you can carry it turns power into achievement instead of burnout.'},

{cat:'sihua',slug:'ziwei-huake-mingsheng-kaoshi-huanhe',focus:'化科',focusEn:'Hua Ke',
 cnT:'紫微斗数化科：名声、考试与缓和，为什么它能给事情留余地',enT:'Hua Ke in Zi Wei Dou Shu: Reputation, Exams and the Room It Leaves for Things',
 cnD:'化科主名声、贵人、文书考试与缓和，它不直接给资源或权力，却能让事情好看一点、平顺一点、有台阶下。',
 enD:'Hua Ke governs reputation, helpful people, documents and exams, and smoothing. It gives no direct resource or power, yet makes things look better, run smoother and leave a graceful way out.',
 cnL:'化科是四化里的「缓冲带」和「招牌」，最会化解尖锐、把事情摆上台面体面处理，也利于文书与考试。',
 enL:'Ke is the buffer and the signboard among the transformations; it softens sharpness, handles matters with dignity on the record, and favors documents and exams.',
 cnA:'有人觉得化科不如化禄实在就轻视它，可在化忌冲来、眼看要撕破脸时，往往是化科给了转圜余地和名声上的保护。',
 enA:'People dismiss Ke as less tangible than Lu, yet when Ji threatens an open break, Ke is often what leaves room to maneuver and protects reputation.',
 cnLog:['化科化气为「名、文、缓」，主声名、文书、考试、贵人与体面。','化科能缓和化忌的尖锐，形成「科忌同宫」时以理性、流程、名声去化解卡点。','化科在官禄利于职称、考核、品牌，在财帛不直接发财但利于信用与口碑变现。','化科的力量偏柔，需要禄或权配合，才不只是「好听不落实」。'],
 enLog:['Ke transforms into reputation, documents and softening—fame, paperwork, exams, helpful people and dignity.','Ke eases Ji\'s sharpness; when they share a palace, reason, process and reputation work through the blockage.','In Career it favors titles, reviews and brand; in Wealth it does not mint money but converts credibility and word of mouth.','Ke is soft and needs Lu or Quan alongside, or it stays pleasant-sounding but unrealized.'],
 cnStep:['定位化科所在宫，看哪个领域容易得名声、文书或贵人','若该宫同时有化忌，重点看化科怎么用流程和体面去缓冲','考试、考核、签约类问题，优先看化科与文昌文曲的配合','看化科有没有禄权支撑，判断名声能否转成实际收益','对外沟通、品牌、公关类决策，可借化科的缓和属性','别把化科当结果，它是让过程平顺、让结果更体面的力量'],
 enStep:['Locate Ke to see where reputation, documents or helpful people appear','If Ji shares the palace, focus on how Ke uses process and dignity to buffer it','For exams, reviews and contracts, weigh Ke together with Wenchang and Wenqu','Check whether Lu or Quan backs Ke so reputation can convert to real gain','Use Ke\'s smoothing quality in communication, branding and PR decisions','Do not treat Ke as an outcome; it smooths the process and dignifies the result'],
 cnMis:['嫌化科不实惠而忽略它的化解与贵人作用','以为有化科考试必过，不看基础实力和煞星干扰','把化科当万能缓冲，忘了它力量柔、需禄权配合'],
 enMis:['Dismissing Ke as intangible and missing its rescue and helpful-people role','Assuming Ke guarantees passing an exam without real ability and malefic interference','Treating Ke as a universal buffer while forgetting its softness and need for Lu or Quan'],
 cnClose:'化科像润滑剂和招牌：它不替你把事做成，却让你在做成的路上少一点硬碰硬、多一点体面和余地。',
 enClose:'Ke acts as lubricant and signboard: it does not do the work for you, but on the way there it reduces head-on clashes and adds dignity and room.'},

{cat:'sihua',slug:'ziwei-huaji-shi-kaidian-zhinian-bushi-huai',focus:'化忌',focusEn:'Hua Ji',
 cnT:'紫微斗数化忌不是坏：它是你最在意也最容易卡住的地方',enT:'Hua Ji Is Not Evil: It Is What You Care Most About and Get Stuck On',
 cnD:'化忌代表收敛、执念、欠债感与卡点，落在哪宫你就对哪类事特别执着、特别容易内耗，看懂它就知道此生的功课。',
 enD:'Hua Ji stands for convergence, fixation, a sense of owing and blockage; whichever palace it lands is where you obsess and drain—and where your life lesson lies.',
 cnL:'化忌不是「那里会倒霉」，而是「那里你太在乎、容易钻牛角尖」，功课是学会在那一处放手和收口。',
 enL:'Ji does not mean disaster there; it means you care too much and tend to fixate there—the lesson is learning to loosen and close that loop.',
 cnA:'多数人看到化忌就想躲开，可越躲越卡，因为化忌的力量来自执念，你不面对，它就换个事件反复回来。',
 enA:'Most people try to dodge Ji and get more stuck, because its power comes from fixation; unaddressed, it returns through different events.',
 cnLog:['化忌化气为「收、藏、欠」，让所在宫位的事变紧、变重、变放不下。','化忌在财帛是对钱的安全感执念，在夫妻是对关系的执着，在官禄是对成就与认可的执念。','忌不是无解，化科可缓和、化权可推进、双禄可疏导，关键是别让它单独发酵。','生年忌是一生功课，大限忌、流年忌是阶段性把这门功课推到台前。'],
 enLog:['Ji transforms into gathering, hiding and owing, tightening and weighting its palace\'s matters.','In Wealth it is fixation on financial security; in Spouse, relationship fixation; in Career, fixation on achievement and recognition.','Ji is not hopeless—Ke softens, Quan pushes forward, double Lu channels; the key is not letting it ferment alone.','Natal Ji is a lifelong lesson; decade and annual Ji bring that lesson to the front in stages.'],
 cnStep:['定位化忌所在宫，确认你在哪类事上最容易执着','分辨这是生年忌（长期功课）还是大限流年忌（阶段触发）','看同宫或三方有没有科、权、禄来缓冲与疏导','把「怕失去」翻译成具体可处理的问题，而不是情绪内耗','给这一宫的事设边界和止损线，主动收口而非被动纠缠','复盘每次被忌牵动的事件，找共同模式，逐步松绑'],
 enStep:['Locate Ji to see which kind of matter you fixate on','Tell whether it is natal Ji (long-term lesson) or decade/annual Ji (stage trigger)','Check the palace and triple-direction for Ke, Quan or Lu to buffer and channel','Translate fear of loss into a concrete, solvable problem instead of emotional drain','Set boundaries and stop-loss lines for that palace, closing loops actively rather than brooding','Review each Ji-triggered event, find the shared pattern, and loosen it step by step'],
 cnMis:['一见化忌就判凶，把功课当成灾祸','只盯化忌单宫，不看禄权科能否化解','以为躲开那个领域就能避开，结果它换件事重来'],
 enMis:['Judging Ji as doom and treating a lesson as a disaster','Fixating on Ji\'s palace alone without seeing whether Lu, Quan or Ke resolve it','Thinking avoidance escapes it, only for it to return in another form'],
 cnClose:'化忌指出的是你此生要修的那门课。不和它硬碰、也不逃，学会收口，卡点反而会变成你最通透的地方。',
 enClose:'Ji points to the lesson you are here to learn. Neither fighting nor fleeing, but learning to close the loop, turns your biggest snag into your clearest strength.'},

{cat:'sihua',slug:'ziwei-luji-duichong-zenme-du-dedao-shiqu',focus:'禄忌对冲',focusEn:'the Lu-Ji clash',
 cnT:'紫微斗数禄忌对冲怎么读：得到和牵挂为什么总在同一条线',enT:'How to Read a Lu-Ji Clash in Zi Wei Dou Shu: Why Gain and Attachment Share One Line',
 cnD:'化禄与化忌落在对宫或同一条线时，资源和卡点会绑在一起出现，表现为一边得到、一边被它牵住，关键是看清代价再决定拿不拿。',
 enD:'When Lu and Ji sit in opposite palaces or on one line, resource and blockage arrive bound together—you gain in one place while being pulled by it; read the cost before taking it.',
 cnL:'禄忌对冲不是一边好一边坏，而是「好处和牵挂成对出现」，读盘要把这笔账的收益和代价一起算。',
 enL:'A Lu-Ji clash is not good on one side and bad on the other; benefit and attachment come as a pair, so read gain and cost in one ledger.',
 cnA:'有人遇到禄忌对冲，只盯着化禄那一头冲进去，最后被化忌那一头的代价拖住，才发现当初没算这笔成对的账。',
 enA:'Facing a Lu-Ji clash, people chase the Lu side and get dragged by the Ji side, realizing too late they never priced the paired cost.',
 cnLog:['禄在本宫、忌在对宫，或禄忌在同一条三合线上，都叫禄忌交战，资源与执念成对出现。','禄随忌走时，得到的领域正是你最放不下、最容易被反制的领域。','读这类结构先找连接线：是现金与安全感的拉扯，还是事业与家庭的互相占用。','解法不是二选一，而是在拿资源的同时给化忌那头预设边界。'],
 enLog:['Lu in one palace and Ji in its opposite, or both on one trine line, is a Lu-Ji encounter where resource and fixation pair up.','When Lu follows Ji, the field you gain in is exactly the one you cannot let go of and are most vulnerable in.','Read such structures by finding the connecting line: cash versus security, or career versus family time.','The answer is not either/or; take the resource while presetting a boundary on the Ji side.'],
 cnStep:['先找出化禄和化忌分别落在哪两个宫','确认两宫是对宫关系还是同一条三合线','写出化禄那头的具体收益，再写出化忌那头的具体代价','判断这笔账在当前大限是否值得、能不能承受','若要拿，提前给化忌那头设止损和边界，不让牵挂失控','行动后定期回看两头是否失衡，及时调整而不是硬撑'],
 enStep:['Find which two palaces hold Lu and Ji','Confirm whether they are opposites or share a trine line','Write the concrete gain on the Lu side and the concrete cost on the Ji side','Judge whether the trade is worth it and bearable in the current decade','If you take it, preset stop-loss and boundaries on the Ji side so attachment stays controlled','After acting, recheck whether the two sides fall out of balance and adjust rather than endure'],
 cnMis:['只看化禄那一头，假装化忌的代价不存在','把禄忌对冲简单判成「先好后坏」，忽略可以主动设边界','二选一硬切，结果机会没拿到、牵挂也没解决'],
 enMis:['Watching only the Lu side and pretending the Ji cost does not exist','Labeling the clash as good-then-bad while ignoring that boundaries can be set proactively','Forcing an either/or that neither captures the chance nor resolves the attachment'],
 cnClose:'禄忌对冲教的是「天下没有只拿不付的资源」。把代价摆上台面算清楚，你反而能拿得稳、放得下。',
 enClose:'A Lu-Ji clash teaches that no resource comes free. Pricing the cost openly lets you take steadily and let go when needed.'},
];
