const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'yingyong',slug:'ziwei-kan-caiyun-wei-shenme-buneng-zhiding-caibogong',focus:'财运',focusEn:'wealth reading',
 cnT:'紫微斗数看财运为什么不能只盯财帛宫：命财官迁要一起看',enT:'Why Reading Wealth in Zi Wei Dou Shu Means More Than the Wealth Palace: Life, Wealth, Career and Travel Together',
 cnD:'财帛宫只写现金方式，钱从哪来看官禄、能不能留住看命宫与福德、外部机会看迁移，真正的财运是命财官迁这条线的净结果。',
 enD:'The Wealth Palace only describes cash style; where money comes from is Career, whether you keep it is Life and Karma, and outside opportunity is Travel. Real wealth is the net result of the Life-Wealth-Career-Travel line.',
 cnL:'财帛宫是「钱包」，但赚钱的能力在官禄、守财的底子在命宫、送机会上门的在迁移，只看钱包看不出贫富。',
 enL:'The Wealth Palace is the wallet, but earning power sits in Career, the ability to keep it in Life, and incoming opportunity in Travel; the wallet alone never shows wealth.',
 cnA:'有人一看财帛宫有化禄或禄存就断定发财，却没看官禄有没有持续赚钱能力、迁移有没有外部机会，结果判断和现实对不上。',
 enA:'Seeing Lu or Lu Cun in Wealth, people predict wealth without checking whether Career sustains earning or Travel brings outside chances, and the read misses reality.',
 cnLog:['财帛宫描述的是「和钱打交道的方式」：是稳拿、是冲量、是靠人脉还是靠技术，不直接等于财富多少。','官禄宫是收入来源，事业结构决定现金流的稳定度和上限，是财运的发动机。','命宫决定赚钱的能力与性格，福德宫决定花钱的心态，迁移宫决定外部资源与远方之财。','再叠田宅（资产）和化禄化忌，才看得到「赚、存、增、耗」的完整循环。'],
 enLog:['The Wealth Palace describes how you handle money—steady, high-volume, network-based or skill-based—not the amount itself.','Career is the income source; its structure decides cash-flow stability and ceiling—the engine of wealth.','Life Palace sets earning ability and temperament, Karma the spending mindset, Travel outside resources and distant money.','Adding Property (assets) and Hua Lu/Ji reveals the full cycle of earning, keeping, growing and draining.'],
 cnStep:['先看财帛宫主星四化，确定现金往来的方式','重点看官禄宫，判断钱靠什么持续赚进来','看命宫与福德，评估赚钱能力和花钱守财心态','看迁移宫，找外部、远方、跨领域的财源','看田宅与化禄化忌，判断资产沉淀和破财点','把命财官迁田串成一条线，再下财运结论'],
 enStep:['Read the Wealth Palace major star and transformations for cash style','Focus on Career to judge what keeps money coming in','Read Life and Karma to assess earning ability and saving/spending mindset','Read Travel for outside, distant or cross-field income','Read Property plus Lu/Ji for asset accumulation and loss points','String Life, Wealth, Career, Travel and Property into one line before concluding'],
 cnMis:['只看财帛宫一颗星就断贫富','把化禄在财帛直接等于发财，不看收入发动机','忽略福德和田宅，判断不了钱能不能留住'],
 enMis:['Judging rich or poor from one Wealth Palace star','Equating Lu in Wealth with windfall without the income engine','Ignoring Karma and Property, unable to tell whether money stays'],
 cnClose:'财运是一张网，不是一个点。学会沿着命财官迁这条线走一圈，你对自己怎么赚钱、怎么存钱会清楚得多。',
 enClose:'Wealth is a network, not a point. Walking the Life-Wealth-Career-Travel loop gives a far clearer picture of how you earn and keep money.'},

{cat:'yingyong',slug:'ziwei-shi-bu-shi-he-huan-gongzuo-zenme-panduan',focus:'换工作',focusEn:'changing jobs',
 cnT:'紫微斗数怎么判断适不适合换工作：官禄命宫迁移大限一起判',enT:'How Zi Wei Dou Shu Judges Whether to Change Jobs: Career, Life, Travel and the Decade Together',
 cnD:'换工作不能只看官禄宫好坏，要结合命宫的适配、迁移的外部机会、当前大限与流年四化，判断是「该换平台」还是「该补能力」。',
 enD:'A job change is not just whether the Career Palace looks good; combine Life for fit, Travel for outside opportunity, and the current decade and annual transformations to tell whether you need a new platform or stronger skills.',
 cnL:'换工作的盘，关键不是看现在顺不顺，而是看机会在外部还是内部、时机在今年还是再等等，方向错了越换越差。',
 enL:'For a job-change chart, the key is not current comfort but whether opportunity sits outside or inside and whether timing is now or later; the wrong direction makes each move worse.',
 cnA:'很多人一遇到工作不顺就想换，把「能力没跟上」误判成「平台不行」，或在大限收缩期硬跳，结果越跳越糟，这就是只看一时情绪没看结构。',
 enA:'People want to leave at the first frustration, mistaking lagging skills for a bad platform, or jump during a contracting decade and land worse—reading mood instead of structure.',
 cnLog:['官禄宫写事业方式与岗位状态，是判断的核心，但不是唯一依据。','命宫决定你适不适合当前赛道、性格和工作方式是否匹配。','迁移宫写外部机会与贵人，迁移被引动时向外走更有利，官禄内部被引动则适合内部调整。','大限定十年事业方向，流年定具体动作时机，双忌叠加的年份宜守不宜跳。'],
 enLog:['The Career Palace describes work style and role status—the core, but not the only basis.','Life Palace decides whether the current track fits your temperament and way of working.','Travel holds outside opportunity and helpful people; when activated, moving out helps, while activated Career favors internal adjustment.','The decade sets the ten-year career direction, the year the timing of a move; a double-Ji year favors staying over jumping.'],
 cnStep:['先看官禄宫现状与四化，判断问题在岗位、行业还是自身','对照命宫，看当前赛道和你的性格能力是否匹配','看迁移宫是否被引动，评估外部机会成熟度','看当前大限事业方向，是上升、平台期还是收缩期','用流年锁定动作时机，避开双忌、化忌冲官禄的年份','综合判断：换平台、换赛道、内部转岗还是先补能力，再行动'],
 enStep:['Read Career status and transformations to locate the problem in role, industry or self','Compare Life to see whether the track fits your temperament and ability','Check whether Travel is activated to gauge outside opportunity maturity','Read the current decade career direction—upward, plateau or contraction','Use the year to time the move, avoiding double-Ji or Ji clashing Career','Conclude among new platform, new track, internal transfer or building skills first, then act'],
 cnMis:['工作一不顺就归因为平台差，忽略能力问题','只看官禄不看迁移，判断不了外部有没有坑位','不看大限流年时机，在收缩年硬跳槽'],
 enMis:['Blaming every frustration on the platform while ignoring skill gaps','Reading Career without Travel, unable to tell whether outside roles exist','Ignoring decade and year timing and jumping in a contraction year'],
 cnClose:'换工作是结构题，不是情绪题。把官禄、命宫、迁移和大限流年摆在一起，你才分得清是该走、该留，还是该先把自己练好。',
 enClose:'Changing jobs is structural, not emotional. Laying Career, Life, Travel and the cycles side by side tells you whether to go, stay, or build yourself first.'},
];
