const {T}=require('./_topics_0904.js');
module.exports=[
{cat:'zhuxing',slug:'ziwei-ziwei-zuoming-diwangguxing-ye-pa-guli',focus:'紫微星',focusEn:'the Zi Wei star',
 cnT:'紫微坐命：帝王星也怕孤立无辅，会不会用人决定上限',enT:'Zi Wei in the Life Palace: Even the Emperor Star Fears Standing Alone',
 cnD:'紫微主统御、尊贵与主见，天生有带队和定方向的能力，但孤君无辅时容易好面子、听不进话，上限取决于有没有左辅右弼这类班底。',
 enD:'Zi Wei governs command, dignity and vision, with a natural ability to lead and set direction; but a lone emperor becomes image-conscious and deaf to advice, so its ceiling depends on aides such as Zuo Fu and You Bi.',
 cnL:'紫微坐命的人不是天生赢家，而是天生想当家；能不能当好这个家，关键看身边有没有人、自己肯不肯听。',
 enL:'A Zi Wei person is not born a winner but born to take charge; doing it well depends on having people and being willing to listen.',
 cnA:'很多人一听紫微是帝星就自我感觉良好，却忽略紫微无辅时「高处不胜寒」的短板，现实里常表现为能干但孤、决策没人补位。',
 enA:'Hearing emperor star flatters people, who then ignore the lonely-at-the-top weakness; in life it shows as capable but isolated, with no one to back decisions.',
 cnLog:['紫微化气为尊，主领导、格局、自尊心与定方向的能力，是十四主星里的统御核心。','紫微高度依赖辅佐：左辅右弼给班底，文昌文曲给谋略，天魁天钺给贵人，天相给执行力。','孤君无辅又逢煞，容易主观、爱面子、耳根软或硬撑，决策缺第二道校验。','紫微的成长课题是「从自己强，变成让一群人一起强」，会授权比会亲为更重要。'],
 enLog:['Zi Wei transforms into dignity and leads command, vision and self-respect—the commanding core of the fourteen major stars.','It relies heavily on aides: Zuo Fu/You Bi for a team, Chang/Qu for strategy, Kui/Yue for helpful people, Tian Xiang for execution.','A lone emperor with malefics turns subjective, image-conscious, easily flattered or stubborn, with no second check on decisions.','Its growth task is moving from being strong alone to making a group strong; delegating matters more than doing everything personally.'],
 cnStep:['先确认紫微是否得位、三方有没有辅佐吉星','有辅：重点培养授权与统筹，把班底用起来','无辅：警惕好面子和独断，主动建立外部参谋机制','看煞星落在哪，判断是决策风险还是人际压力','结合化权化科，强化领导而非强化控制','在大限引动事业的十年，重点搭团队而不是单打独斗'],
 enStep:['Confirm whether Zi Wei is well-placed and whether its trine has aides','With aides: build delegation and coordination, using the team','Without aides: watch image-consciousness and solo decisions, and build external advisors','See where malefics land to judge decision risk versus relationship pressure','Use Hua Quan/Hua Ke to strengthen leadership rather than control','In a career-activating decade, focus on building a team instead of fighting alone'],
 cnMis:['把帝星名号直接等同于成功，忽略辅佐','紫微无辅还硬撑亲力亲为，越能干越累','把听不进意见当「有主见」，错过纠偏机会'],
 enMis:['Equating the emperor title with success while ignoring aides','Insisting on doing everything without aides—the more capable, the more drained','Mistaking refusal to listen for strong conviction and missing corrections'],
 cnClose:'紫微的贵气不是孤芳自赏，而是能聚人、能用众。学会把身段放下、把班底搭起来，帝王星才真正坐得稳。',
 enClose:'Zi Wei\'s nobility is not self-admiration but gathering and using people. Lowering the guard and building a team is what truly steadies the emperor.'},

{cat:'zhuxing',slug:'ziwei-tianji-zuoming-linghua-shanbian-neihao',focus:'天机星',focusEn:'the Tian Ji star',
 cnT:'天机坐命：灵活善变是天赋也是内耗，怎么把聪明用稳',enT:'Tian Ji in the Life Palace: Flexibility Is a Gift and a Drain—How to Steady a Quick Mind',
 cnD:'天机主智慧、策划、学习与应变，脑子快、点子多，但天机化气为善变，想太多、换太快时容易内耗和三分钟热度，需要辅星与流程来定心。',
 enD:'Tian Ji governs intelligence, planning, learning and adaptability—quick and idea-rich—but its changeable nature brings overthinking and short-lived enthusiasm; assistants and process are needed to settle the mind.',
 cnL:'天机坐命不缺想法，缺的是把一个想法做深做久的定力，把聪明接上节奏，才不会被自己的念头拖着跑。',
 enL:'A Tian Ji mind never lacks ideas; it lacks the steadiness to deepen and sustain one. Connecting cleverness to rhythm keeps you from being dragged around by your own thoughts.',
 cnA:'天机的人常被夸聪明，却也常陷入「计划很多、落地很少、睡前千条路、早上走原路」，根源是应变力强而稳定力弱。',
 enA:'Tian Ji people are praised as clever yet trap themselves in many plans and little execution, because adaptability is strong while stability is weak.',
 cnLog:['天机为智慧之星，主逻辑、策划、学习力、手脚与神经系统层面的灵活。','优点是反应快、会找方法、擅协调；短板是善变、多虑、容易因想太多而迟于行动。','吉星辅佐上，文昌文曲让思考成体系，左辅右弼让想法有人落地，化权则能把策划变成推进。','煞星太重时，天机的灵活会变成焦虑、反复和失眠式内耗，需要靠节奏和聚焦来解。'],
 enLog:['Tian Ji is the star of intelligence—logic, planning, learning and mental/nimble flexibility.','Its strengths are quick response, finding methods and coordination; its weakness is changeability, overthinking and delayed action.','Wenchang/Wenqu systematize thought, Zuo Fu/You Bi help ideas land, and Hua Quan turns planning into drive.','Under heavy malefics its flexibility becomes anxiety, reversal and sleepless overthinking, solved by rhythm and focus.'],
 cnStep:['先看天机是否得位、有没有昌曲等吉星让思考成体系','把「想」和「做」分开：限定策划时间，到点必须行动','一次只推进一个主方案，其它点子先入备选清单','用左辅右弼或合伙人补足执行力，别只靠自己脑内循环','煞重时建立固定作息和决策流程，给快脑子一个刹车','用大限判断哪十年适合学习转型、哪十年适合深耕落地'],
 enStep:['Check whether Tian Ji is well-placed and whether Chang/Qu systematize its thinking','Separate thinking from doing: cap planning time and act when time is up','Advance one main plan at a time; park other ideas in a backlog','Use aides or partners to supply execution instead of looping in your own head','Under heavy malefics, set fixed routines and decision rules to brake a fast mind','Use decades to see which years suit learning or pivoting and which suit deep execution'],
 cnMis:['把善变当灵活，频繁换方向导致一事无成','只享受想方案的过程，回避落地的枯燥','天机一焦虑就继续多想，反而越想越乱'],
 enMis:['Mistaking changeability for flexibility and switching so often nothing completes','Enjoying planning while avoiding the dull work of execution','Answering Tian Ji anxiety with more thinking, which only tangles further'],
 cnClose:'天机的聪明是上等资源，但它需要缰绳。给快脑子装上节奏、聚焦和执行伙伴，善变就会变成真正的善谋。',
 enClose:'Tian Ji cleverness is a top resource that needs reins. Give the quick mind rhythm, focus and an executing partner, and changeability becomes genuine strategy.'},

{cat:'zhuxing',slug:'ziwei-tanlang-zuoming-duocai-duoyu-zenme-yong',focus:'贪狼星',focusEn:'the Tan Lang star',
 cnT:'贪狼坐命：多才多欲不是缺点，关键看欲望往哪导',enT:'Tan Lang in the Life Palace: Versatility and Desire Are Not Flaws—It Depends Where Desire Is Directed',
 cnD:'贪狼主欲望、人际、才艺与机会，是桃花星也是财星，能量强、兴趣广；欲望导向事业才艺则多成，导向享乐放纵则多耗，关键在疏导而非压制。',
 enD:'Tan Lang governs desire, networking, talent and opportunity—a romance and wealth star with strong energy and broad interests. Directed into career and skill it builds; into indulgence it drains. Channel, do not suppress.',
 cnL:'贪狼的核心是「强欲望＋强社交＋强好奇」，压是压不住的，越懂得给欲望找对出口，成就越大。',
 enL:'Tan Lang is strong desire, strong sociability and strong curiosity; it cannot be suppressed, and the better the outlet you find for desire, the greater the achievement.',
 cnA:'一谈贪狼就往桃花、享乐上想，是最大的误读。历史上很多最会经营人脉、捕捉机会、跨界成事的人，都是贪狼能量用对了方向。',
 enA:'Reducing Tan Lang to romance and indulgence is the biggest misread; many who build networks, seize chances and cross fields successfully are simply Tan Lang energy aimed right.',
 cnLog:['贪狼为欲望之星、正桃花与偏财之星，主交际、才艺、应酬、商机与对新鲜事物的敏感。','它的能量是中性的动力源：导向正途是进取心和魅力，导向放纵是消耗和纠缠。','贪狼喜与火铃成火贪爆发、喜化禄化权给欲望一个可执行的出口，最怕无目标地发散。','桃花性质在现代更多表现为人缘、审美、内容与娱乐产业的天赋，不只是男女关系。'],
 enLog:['Tan Lang is the star of desire, primary romance and indirect wealth—networking, talent, socializing, business chances and a nose for novelty.','Its energy is a neutral engine: aimed well it is drive and charm; aimed at indulgence it is drain and entanglement.','It thrives with Huo/Ling (the Huo-Tan burst) and with Hua Lu/Quan giving desire an executable outlet; it suffers most from aimless scattering.','Its romance quality today shows more as likability, aesthetics and talent for content and entertainment than just relationships.'],
 cnStep:['先看贪狼落宫与三方，判断欲望主要指向哪个领域','给强欲望设一个「主出口」：事业、才艺或经营，而不是全面铺开','用化禄化权或目标管理，把兴趣转成可积累的成果','警惕酒色财气式的即时满足，设消耗上限','善用社交天赋经营人脉，但区分真关系和应酬消耗','用大限看哪十年欲望最容易变现、哪十年要特别守边界'],
 enStep:['See where Tan Lang lands and its trine to judge which field desire mainly points to','Give strong desire one main outlet—career, craft or business—rather than spreading everywhere','Use Hua Lu/Quan or goal management to turn interests into accumulable results','Beware instant gratification through drink, romance or spending, and set drain limits','Use social talent to build real networks, distinguishing true ties from draining entertainment','Use decades to see when desire monetizes and when boundaries need special guarding'],
 cnMis:['把贪狼一概当烂桃花，否定其社交与商机天赋','靠硬压欲望，结果反弹更猛','兴趣太多没有主出口，最终样样通样样松'],
 enMis:['Writing Tan Lang off as bad romance and denying its networking and opportunity talent','Harshly suppressing desire only for it to rebound harder','Too many interests with no main outlet, ending mediocre at everything'],
 cnClose:'贪狼像一团火，烧对地方是引擎，烧错地方是消耗。别想着灭火，去修一条让它稳定做功的通道。',
 enClose:'Tan Lang is fire: aimed right it is an engine, aimed wrong it is a burn. Do not put it out—build a channel where it does steady work.'},

{cat:'zhuxing',slug:'ziwei-qisha-zuoming-jiangxing-de-gang-yu-gu',focus:'七杀星',focusEn:'the Qi Sha star',
 cnT:'七杀坐命：将星的刚是开创力，也是孤独感',enT:'Qi Sha in the Life Palace: The General Star\'s Toughness Is Both Pioneering Power and Loneliness',
 cnD:'七杀主决断、开创、独立与冲锋，行动力强、能扛事，但过刚则易折、不喜求助，容易把人生活成孤军奋战，功课是学会借力与柔软。',
 enD:'Qi Sha governs resolve, pioneering, independence and charge—strong action and load-bearing capacity—but too much rigidity breaks and dislikes asking for help, turning life into a lone fight; the lesson is borrowing strength and softening.',
 cnL:'七杀的人最能打硬仗，但人生不是只靠硬扛，学会让别人上车、允许自己示弱，刚才有价值而不是代价。',
 enL:'Qi Sha people fight the hardest battles, but life is not won by enduring alone; letting others aboard and allowing vulnerability makes toughness an asset instead of a cost.',
 cnA:'七杀常被贴上「凶、孤、冲」的标签，其实它是最有行动力和担当的星之一，问题不在刚，而在只有刚、没有缓冲和支援。',
 enA:'Qi Sha is often labeled fierce, lone and aggressive, yet it is among the most action-oriented and responsible stars; the issue is not toughness but toughness without buffer or support.',
 cnLog:['七杀为将星，化气为权，主决断、开创、肃杀和独立承担，属杀破狼格局的变动核心。','优点是敢决断、能攻坚、不拖泥带水；短板是刚硬、急躁、不善迂回，也不轻易信任和求助。','七杀喜禄存化禄给资源、喜化权正名、需辅星与伙伴补「谋」和「缓」，孤峰无援则大起大落。','人生课题是把「一个人冲」升级为「带队攻坚」，在刚之外建立财务、关系和情绪的缓冲带。'],
 enLog:['Qi Sha is the general star transforming into authority—resolve, pioneering, severity and independent bearing, the change core of the Sha-Po-Lang pattern.','Strengths are decisiveness and攻坚 without dragging; weaknesses are rigidity, impatience, poor detours and reluctance to trust or ask for help.','It benefits from Lu Cun/Hua Lu for resources, Hua Quan for legitimacy, and aides or partners for strategy and pacing; a lone peak swings wildly.','The task is upgrading from charging alone to leading a charge, building financial, relational and emotional buffers alongside toughness.'],
 cnStep:['先看七杀落宫与三方，判断开创力指向事业还是其他领域','主动配「军师型」伙伴或辅星，补自己不擅谋划的一面','重大决策强制设冷静期，避免刚硬急躁下拍板','建立财务和情绪缓冲，别让每次冲锋都不留后路','练习表达需求和接受帮助，把求助当成战略而非软弱','用大限判断何时该全力开创、何时该守成消化'],
 enStep:['See where Qi Sha lands and its trine to judge whether pioneering points to career or elsewhere','Actively pair with strategist partners or aides to complement planning','Impose a cooling-off period on big decisions to avoid rigid, rushed calls','Build financial and emotional buffers so no charge leaves no retreat','Practice expressing needs and accepting help, treating it as strategy not weakness','Use decades to judge when to pioneer full-out and when to consolidate'],
 cnMis:['把七杀当凶星，否定其难得的担当和行动力','迷信「靠自己」，拒绝求助导致孤军深入','只刚不柔，关系和身体都长期透支'],
 enMis:['Treating Qi Sha as malefic and denying its rare responsibility and action','Believing in self-reliance so completely that refusing help leads deep into enemy lines alone','Staying rigid without softness, chronically overspending relationships and health'],
 cnClose:'七杀的刚，是用来开路的，不是用来孤立自己的。给将星配上军师、后方和休整，开创力才走得远。',
 enClose:'Qi Sha\'s toughness is for opening roads, not for isolation. Give the general a strategist, a rear guard and rest, and pioneering power goes the distance.'},

{cat:'zhuxing',slug:'ziwei-tianliang-zuoming-yinxing-qinggui-yuelao-yuezhi',focus:'天梁星',focusEn:'the Tian Liang star',
 cnT:'天梁坐命：荫星清贵，为什么越老越值钱',enT:'Tian Liang in the Life Palace: The Sheltering Star Grows More Valuable With Age',
 cnD:'天梁主荫护、原则、逢凶化吉与老成，是清贵的老人星，年轻时可能不显甚至吃亏，随着阅历和专业沉淀，中年后声望与福气越来越厚。',
 enD:'Tian Liang governs shelter, principle, turning misfortune around and maturity—a noble elder star. It may be quiet or even lose out young, but with experience and expertise, reputation and blessing thicken after midlife.',
 cnL:'天梁是「慢热型贵气」：不靠爆发靠积累，越是需要经验、信誉和担当的领域，它越到后面越有分量。',
 enL:'Tian Liang is slow-burn nobility: it builds rather than bursts, and in fields needing experience, credibility and responsibility it carries increasing weight later on.',
 cnA:'年轻人天梁坐命常觉得自己太老成、不合群、占便宜的事轮不到，其实这颗星的回报曲线本来就后置，急不得。',
 enA:'Young Tian Liang people feel old before their time, out of place and last in line for quick gains; this star\'s reward curve is simply back-loaded.',
 cnLog:['天梁化气为荫，为老人星、清贵星，主原则、庇荫、化解灾厄与受人敬重。','它擅长在复杂局面里主持公道、兜底善后，适合教育、医疗、法务、监察、咨询等靠信誉的领域。','天梁逢凶化吉的能力来自稳重和原则，但怕过度清高、固执或与现实脱节。','它的运势曲线后段上扬：阅历、口碑、人脉随年龄增值，所以有「越老越值钱」之说。'],
 enLog:['Tian Liang transforms into shelter—the elder, noble star of principle, protection, turning disaster around and earning respect.','It excels at upholding fairness and cleaning up in complex situations, suiting education, medicine, law, oversight and consulting—credibility fields.','Its ability to turn misfortune around comes from steadiness and principle, but it suffers from excessive aloofness, rigidity or detachment from reality.','Its fortune curve rises late: experience, reputation and networks appreciate with age, hence growing more valuable over time.'],
 cnStep:['先看天梁落宫与三方，判断荫护能力主要用在哪个领域','选赛道时优先「越老越吃香」的经验型、信誉型行业','年轻时不与爆发型的人比快，专注积累专业和口碑','警惕过度清高，学会在原则和现实之间找可行解','发挥逢凶化吉的优势，主动承担兜底和协调角色','用大限看中后期哪十年声望与收成集中兑现'],
 enStep:['See where Tian Liang lands and its trine to judge where sheltering ability is used','When choosing a track, favor experience and credibility fields that reward seniority','When young, do not race burst-type people; build expertise and reputation','Guard against aloofness and find workable points between principle and reality','Use the disaster-turning strength by taking on coordination and safety-net roles','Use decades to see which later years concentrate reputation and harvest'],
 cnMis:['年轻时拿自己和爆发型主星比，越比越焦虑','把清高当原则，不愿处理现实利益导致吃亏','没意识到天梁回报后置，过早否定自己'],
 enMis:['Comparing yourself young to burst-type stars and growing anxious','Mistaking aloofness for principle and refusing real-world trade-offs, losing out','Not realizing the reward is back-loaded and giving up on yourself too early'],
 cnClose:'天梁走的是厚积薄发的路。年轻时把信誉和本事存好，中年以后，时间会成为这颗星最硬的靠山。',
 enClose:'Tian Liang walks the path of accumulated depth. Bank credibility and skill when young; after midlife, time becomes this star\'s firmest backing.'},

{cat:'zhuxing',slug:'ziwei-zhuxing-zuo-fuqigong-zenme-kan-lingyiban',focus:'夫妻宫主星',focusEn:'the major star in the Spouse Palace',
 cnT:'主星坐夫妻宫怎么看另一半：看的是关系模式，不是寻人启事',enT:'How to Read the Major Star in Your Spouse Palace: It Shows a Relationship Pattern, Not a Person Wanted Ad',
 cnD:'夫妻宫主星描述的是你容易被哪类人吸引、亲密关系以什么方式展开、会卡在哪，它给的是相处模式和功课，不是对方的精确长相或职业。',
 enD:'The major star in the Spouse Palace describes who you are drawn to, how intimacy unfolds and where it snags—a pattern and lesson, not the partner\'s exact face or job.',
 cnL:'夫妻宫不是用来「按图索骥找对象」，而是照见你在亲密关系里的剧本：你要什么、怕什么、会重复什么。',
 enL:'The Spouse Palace is not a wanted ad for a partner; it mirrors your intimacy script—what you want, what you fear, and what you repeat.',
 cnA:'很多人把夫妻宫主星当成对另一半的说明书，去对号入座职业外貌，对不上就说不准，其实它讲的是两个人互动出来的关系形态。',
 enA:'People treat the Spouse star as a partner spec sheet and match jobs or looks, calling it inaccurate when it fails; it actually describes the shape two people create together.',
 cnLog:['夫妻宫主星定关系基调：主星刚健则关系里主导性强，柔曜则重情感黏合，变动星则关系起伏多。','要对宫官禄一起看：事业节奏直接占用关系时间，婚姻和事业是一组对宫。','三方四正的辅煞与四化，决定这段关系有没有助力、哪里有摩擦、哪类执念最重。','同一个夫妻宫，遇到不同主星的人会有不同互动，所以它给的是模式区间，不是唯一答案。'],
 enLog:['The Spouse major star sets the tone: strong stars bring dominance, soft stars emphasize emotional bonding, changeable stars bring fluctuation.','Read it with its opposite, Career: work rhythm directly spends relationship time—marriage and career are an opposite pair.','Assistants, malefics and transformations in the trine decide support, friction and the heaviest fixation in the relationship.','The same Spouse Palace interacts differently with partners of different stars, so it gives a pattern range, not a single answer.'],
 cnStep:['先看夫妻宫主星，定你在关系里的基调和吸引类型','看对宫官禄，评估事业如何影响这段关系','看三方四正的吉星煞星，找助力点和摩擦点','看四化，尤其化忌落在关系线的哪一环','用大限夫妻宫判断关系在哪个阶段被引动（桃花、定下来、考验）','把结论用于调整自己的相处模式，而不是给对方下定义'],
 enStep:['Read the Spouse major star for your relationship tone and attraction type','Read its opposite Career to weigh how work affects the relationship','Read trine auspicious and malefic stars for support and friction points','Read transformations, especially where Hua Ji lands on the relationship line','Use the decade Spouse Palace to see which stage activates romance, commitment or testing','Use the result to adjust your own pattern rather than define the partner'],
 cnMis:['把夫妻宫当对象的外貌职业说明书','只看夫妻宫单宫，不看官禄对宫和三方','拿一个模式去要求对方，忽略关系是两个人互动出来的'],
 enMis:['Treating the Spouse Palace as the partner\'s looks-and-job spec sheet','Reading it alone without the Career opposite and trine','Imposing one pattern on the partner, forgetting a relationship is co-created'],
 cnClose:'夫妻宫真正照见的是你自己去爱和被爱的方式。读懂这个剧本，你才能在关系里少重复旧结、多长出新的相处能力。',
 enClose:'What the Spouse Palace truly reveals is how you love and receive love. Understanding that script lets you repeat fewer old knots and grow new ways of relating.'},
];
